### ISSUE TITLE
Dialog 的loading希望可以自主触发

### ISSUE THREAD

**Issue by rayroad** [youzan/vant-weapp#1001]
**你需要的功能是？**
目前在使用dialog组件时遇到一些业务问题
我通过solt 定义了一个输入框 希望在点击确定按钮时验证这个输入框是否填写了内容
所以启用了 `asyncClose` 但是当我点击确定按钮后由于没有触发关闭操作，确定按钮的状态则一直显示为loading状态 

希望通过组件调用 Dialog 并启用 `asyncClose` 时，在触发 `confirm` 后可手动关闭 loading 
或者loading动作由用户自主触发

**你期望 API 是什么样的？**
```
<van-dialog
 confirmLoading="{{ confirmLoading }}"
 cacleLoading="{{ cacleLoading }}"
  />
```

**Comment by rayroad** [comment]
![6olu1r4beg n i1 zy2 a9](https://user-images.githubusercontent.com/1949219/49363973-0df46480-f71e-11e8-8ff6-4d18bdec1de2.png)

**Comment by rex-zsd** [comment]
关闭loading可通过`Dialog.stopLoading`方法。
如果需要多次点击confirm按钮的话，只能通过监听`bind:confirm`事件，如果在`then`上处理只能触发一次。

**Comment by rayroad** [comment]
谢谢 不过直接调用Dialog.stopLoading貌似不起作用，找到了如下方法
```
this.selectComponent("#dilaogId").stopLoading()
```

**Comment by rex-zsd** [comment]
调用实例上的方法也可以。
