### ISSUE TITLE
rate 评分组件能否支持小数

### ISSUE THREAD

**Issue by guakeliao** [youzan/vant-weapp#1003]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**你需要的功能是？**
rate 评分组件能够支持小数，比如4.5的星星等。

**你期望 API 是什么样的？**
count="{{ 4.5 }}"

**Comment by rex-zsd** [comment]
之后会增加一个属性，控制是选择一颗星、半颗星还是自由选择（一位小数）。

**Comment by guakeliao** [comment]
感谢，能加急出这个功能吗

**Comment by qzmly100** [comment]
同求 
没有半颗星吗？

**Comment by qzmly100** [comment]
今天看到半颗星了 什么时候更新的？看官方日志没有添加 但是半星的文档没有及时更新

**Comment by eyougo** [comment]
文档是支持半星的，但实际配置了没作用貌似不支持，希望能支持半星，谢谢

**Comment by chenjiahan** [comment]
目前 Vue 版本已支持半星，小程序版本会在近期支持

**Comment by qzmly100** [comment]
希望小程序版本支持一下，辛苦大大。
