### ISSUE TITLE
官网文档，小程序组件的checkbox-group搭配cell的示例代码有问题

### ISSUE THREAD

**Issue by leaon4** [youzan/vant-weapp#1017]
<van-checkbox-group value="{{ result }}" bind:change="onChange">
  <van-cell-group >
    <van-cell
      wx:for="{{ list }}"
      wx:key="{{ index }}"
      title="复选框 {{ item }}"
      clickable
      data-name="{{ item }}"
      bind:click="toggle"
    >
      <van-checkbox catch:tap="noop" class="checkboxes-{{ item }}" name="{{ item }}" />
    </van-cell>
  </van-cell-group>
</van-checkbox-group>
Page({
  data: {
    list: ['a', 'b', 'c'],
    result: ['a', 'b']
  },

  onChange(event) {
    this.setData({
      result: event.detail
    });
  }

  toggle(event) {
    const { name } = event.currentTarget.dataset;
    const checkbox = this.selectComponent(`.checkboxes-${name}`);
    checkbox.toggle();
  },

  noop() {}
});
官网的这部分代码，不能覆盖所有的点击区域。在某些点击区域上，不会触发onChange事件

设备：
windows下开发者工具，安卓手机
版本:0.4.8

**Comment by rex-zsd** [comment]
是的 这里还需要设置`van-cell`的外部样式类`value-class`，`flex: none !important;`
因为`van-cell`默认是title和value各占50%宽度的。
