### ISSUE TITLE
Dialog 弹出框中Dialog.stopLoading无效

### ISSUE THREAD

**Issue by 1429880240** [youzan/vant-weapp#1021]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**描述一下问题**
Dialog 弹出框中Dialog.stopLoading无效，不能停止按钮加载动作
描述一下你遇到的问题，包括复现方式、导致结果

**截图**
如果是 UI 问题，请提供具体截图

**环境**
 - 设备: 微信开发者工具
 - 基础库版本: 2.4.1
 - Vant Weapp 版本:0.4.8

**Comment by rex-zsd** [comment]
提供一下代码片段或者贴下代码截图？

**Comment by 1429880240** [comment]
![g essp 6v 8c_o56 8 cv](https://user-images.githubusercontent.com/35157291/49571665-e4814600-f974-11e8-81e7-69adc350b8f3.png)

![712d6qq r qhm_rdiwo9p1](https://user-images.githubusercontent.com/35157291/49571652-dd5a3800-f974-11e8-9fd5-b1ee1c5c02e4.png)

**Comment by 1429880240** [comment]
@rex-zsd

**Comment by yoage** [comment]
同样遇到这个问题

**Comment by rex-zsd** [comment]
#1047 已经有pr增加了在事件中返回dialog实例，可以通过调用实例方法关闭，下版本发布。

**Comment by 1429880240** [comment]
经测试在dist/dialog/index.js中第92行左右将
this.$emit(action); 改成 this.$emit(action, {dialog: this});
在绑定cancel和confirm方法中使用 e.detail.dialog.stopLoading(); 或者
e.mp.detail.dialog.stopLoading();【mpvue写法】关闭loading的状态

**Comment by dpgirl** [comment]
> [＃1047](https://github.com/youzan/vant-weapp/pull/1047)已经有PR增加了在事件中返回对话框实例，可以通过调用实例方法关闭，下版本发布。

请问这个有加了吗？我现在也没办法阻止加载

**Comment by 1429880240** [comment]
最新版本没有试过，但是当时的版本我加了可以用

在 2019-04-06 23:47:32，"dpgirl" <notifications@github.com> 写道：


＃1047已经有PR增加了在事件中返回对话框实例，可以通过调用实例方法关闭，下版本发布。

请问这个有加了吗？我现在也没办法阻止加载
