### ISSUE TITLE
collapse 折叠面板没作用

### ISSUE THREAD

**Issue by ZhangLorne** [youzan/vant-weapp#1024]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**描述一下问题**
collapse 折叠面板，点击没作用，箭头指向也有问题。。。
**截图**
代码：
![image](https://user-images.githubusercontent.com/20028329/49570996-0bd71380-f973-11e8-9de5-f8ed0f5b0d04.png)

![image](https://user-images.githubusercontent.com/20028329/49570966-f9f57080-f972-11e8-9d6c-595115b0b4d5.png)

**环境**
 - 设备: ios
 - 基础库版本: 
 - Vant Weapp 版本:0.4.8

**Comment by rex-zsd** [comment]
箭头指向下版本修复，点击没作用是因为你没有监听`change`事件并修改`activeNames`的值。

**Comment by yanyansmile** [comment]
change 事件咋写滴呀？拜求

**Comment by yanyansmile** [comment]
onChange(event) {
    console.log(event)
    this.setData({
      activeNames: event.id
    })
  },

无效

**Comment by rex-zsd** [comment]
@yanyansmile 文档这部分有缺失，下版本补上。
```
onChange(event) {
  this.setData({
    activeNames: event.id
  })
}
```
