### ISSUE TITLE
field

### ISSUE THREAD

**Issue by byrwyj** [youzan/vant-weapp#1025]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**你需要的功能是？**

希望field输入框能够复制和粘贴。

**你期望 API 是什么样的？**
暂无

**Comment by rex-zsd** [comment]
微信已经提供了[剪贴板API](https://developers.weixin.qq.com/miniprogram/dev/api/wx.getClipboardData.html)可以DIY一下哈。
