### ISSUE TITLE
van-icon中的name引用不了图片链接

### ISSUE THREAD

**Issue by LWM108** [youzan/vant-weapp#1033]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**你需要的功能是？**
描述一下你需要的功能，用于解决什么问题
van-icon中的name引用图片链接
van-icon中的name引用不了图片链接
**你期望 API 是什么样的？**
描述一下你期望的 API 形式

**Comment by rex-zsd** [comment]
van-icon只能引用指定的图标，无法引用图片链接，可参考demo。
