### ISSUE TITLE
VM1535:1 jsEnginScriptError Component is not found in path "path/to/vant-weapp/dist/button/index" (using by "pages/index/index");onAppRoute Error: Component is not found in path "path/to/vant-weapp/dist/button/index" (using by "pages/index/index")

### ISSUE THREAD

**Issue by leepule** [youzan/vant-weapp#1036]
VM1535:1 jsEnginScriptError
Component is not found in path "path/to/vant-weapp/dist/button/index" (using by "pages/index/index");onAppRoute
Error: Component is not found in path "path/to/vant-weapp/dist/button/index" (using by "pages/index/index")

 - 基础库版本: 2.4.1
 - Vant Weapp 版本:0.4.9

**Comment by leepule** [comment]
我刚下载就这样啊   什么动没动

**Comment by stefango** [comment]
如果是用npm安装的话，尝试微信IDE-工具-构建npm，然后清缓存
