### ISSUE TITLE
Search 搜索组件

### ISSUE THREAD

**Issue by chinabin1993** [youzan/vant-weapp#1038]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**描述一下问题**
search搜索框的外部样式问题，
custom-class
field-class
这两个外部样式设置背景色时有问题。不起作用。
**截图**
![image](https://user-images.githubusercontent.com/25213840/49717056-bbbcc180-fc90-11e8-970a-b3a3d54df6b4.png)

**环境**
 - 设备: 
 - 基础库版本: 2.4.1
 - Vant Weapp 版本:0.4.9

`
<van-search use-action-slot placeholder="{{placeholder}}" custom-class="custom" field-class="input-search" input-class="input-search" bind:change="handleInputSearch">
    <view slot="action" bind:tap="handleAdd">
      
      +
    </view>
  </van-search>

------.wxss---------
.custom {
	background: red;
	border: 1px solid red;
}

.field {
	background-color: blue;
}
.input-search {
	/* border: 1px solid red; */
	background-color: red;
	/* background: #f4f4f4 !important; */
}
`

**Comment by chinabin1993** [comment]
![image](https://user-images.githubusercontent.com/25213840/49717275-8795d080-fc91-11e8-9de3-a3d3d20f577a.png)

**Comment by rex-zsd** [comment]
`custom-class`设置背景色时需要`!important`，因为本身已经设置了`background-color`了。

**Comment by chinabin1993** [comment]
field-class呢？如果同时更改custom-class 和 field-class 。 custom加 important是起作用的。但是field不起作用。
另外，希望官方文档明确指明一下，需要加上important。
