### ISSUE TITLE
popup点击蒙层无法关闭弹窗

### ISSUE THREAD

**Issue by mengxianghan** [youzan/vant-weapp#1045]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**描述一下问题**
1.popup点击蒙层无法关闭弹窗，设置了close-on-click-overlay为true也不行
2.bind:click-overlay事件无效

**截图**
如果是 UI 问题，请提供具体截图

**环境**
 - 设备: 微信开发者工具
 - 基础库版本: 2.4.0
 - Vant Weapp 版本:0.4.6

**Comment by rex-zsd** [comment]
是否有监听`close`事件并将`show`设为`false`？
请提供一下代码片段或者代码截图。

**Comment by mengxianghan** [comment]
> 是否有监听`close`事件并将`show`设为`false`？
> 请提供一下代码片段或者代码截图。

看了github仓库中的示例后在`close`事件中将`show`设为false后可用了
但是官方文档给的`close`是在蒙层关闭时触发的，这就有点搞不懂了

**Comment by rex-zsd** [comment]
文档中[代码演示](https://youzan.github.io/vant-weapp/#/popup)部分有写，`bind:close="onClose"`这部分是不能省的。
