### ISSUE TITLE
field组件输入速度稍快会回退

### ISSUE THREAD

**Issue by heisenberg9799** [youzan/vant-weapp#1053]
输入数字的速度快一点就会出现回退删除的错乱现象

**Comment by rex-zsd** [comment]
这是因为`change`后调用`setData`设置`value`，输入速度快时就会出现这个现象。
可以尝试在`blur`事件中获取`value`。

**Comment by ChinaFanny** [comment]
问题1：设置value方法放在blur中，输入过快还是会出现回退删除的现象
问题2：设置了blur和clear方法，其中两个方法都设置了value（blur设置value为输入内容，clear设置value为空字符串），点击后面的清空叉号时，输入框会闪一下，原因是先会调用blur方法，然后才会调用clear方法

请问这个两个问题有解决办法吗？
