### ISSUE TITLE
van-area Event事件触发无效

### ISSUE THREAD

**Issue by ch345073110** [youzan/vant-weapp#1062]
van-area 中的 Event事件confirm cancel change 都不触发。
版本：v0.4.9
配置 macPro
<img width="1432" alt="2018-12-12 12 04 23" src="https://user-images.githubusercontent.com/32119580/49846426-19264f00-fe06-11e8-89ee-6d2a2655b051.png">
<img width="353" alt="2018-12-12 12 04 40" src="https://user-images.githubusercontent.com/32119580/49846433-204d5d00-fe06-11e8-837c-58b6ec9e670b.png">

**Comment by rex-zsd** [comment]
wxml中是如何绑定事件的？

**Comment by ch345073110** [comment]
@rex-zsd 图片上面有啊

**Comment by XiangTan-Liumou** [comment]
他的意思是你没有bind:confirm
