### ISSUE TITLE
van-search 设置 focus 没能自动聚焦唤起键盘

### ISSUE THREAD

**Issue by gogoodboy** [youzan/vant-weapp#1063]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**描述一下问题**
van-search 设置 focus 没能自动聚焦唤起键盘
代码如下
```
<van-search focus="true"
 show-action value="{{ value }}" placeholder="搜索您想要的服务" bind:change="onChange" bind:search="onSearch" background="#fff" placeholderStyle="color:#B2B2B2">
</van-search>
```

**截图**
如果是 UI 问题，请提供具体截图
调试器中看到 input 的属性如下，focus 的值不是设置的值
![image](https://user-images.githubusercontent.com/14175675/49849861-58f53280-fe16-11e8-9023-d1271c478f42.png)

**环境**
 - 设备: 
 - 基础库版本: 当前已是最新版本（1.02.1811290）
 - Vant Weapp 版本:  "vant-weapp": "^0.4.9"

**Comment by rex-zsd** [comment]
`focus="true"`传入的是字符串，这里接受的是一个`Boolean`类型的值。
