### ISSUE TITLE
van-popup真机调试失效

### ISSUE THREAD

**Issue by tu3susu** [youzan/vant-weapp#1072]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**描述一下问题**
在map组件上弹出van-popup，开发者工具上可以正常显示，真机调试时点击弹出没有任何反应。

**截图**

**环境**
 - 设备: iphone 8
 - 基础库版本: 2.4.1
 - Vant Weapp 版本:0.4.9

**Comment by rex-zsd** [comment]
信息不足，请提供使用代码、截图等。

**Comment by tu3susu** [comment]
> @tu3susu 你好，问下你是单独使用cover-view写了一个组件还是把popup组件内的view给修改成cover-view了？

在map里单独写的cover-view，没有用popup

**Comment by jiangxiaoqiang** [comment]
遇到同样的问题，模拟器中可以，真机上无法弹出。真机是Iphone XR。

 ```
<view>
            <canvas canvas-id="canvas1" class="myCanvas" style="width:{{chartWidth}}px;height:{{chartHeight}}px;">
              <cover-view>
                <van-popup show="{{ bottom }}" position="bottom" custom-class="bottom" bind:close="toggleBottomPopup2">
                  <van-picker show-toolbar title="切换医院" columns="{{ column1 }}" bind:change="onChange1" bind:confirm="onConfirm" />
                </van-popup>
              </cover-view>
            </canvas>
          </view>
```

**Comment by tu3susu** [comment]
@jiangxiaoqiang canvas是原生组件，真机调试的时候不允许在上面覆盖popup，单独使用cover-view代替popup实现弹出功能，不要在cover-view中嵌套popup
