### ISSUE TITLE
CountDown 倒计时组件需求

### ISSUE THREAD

**Issue by lonquan** [youzan/vant-weapp#1076]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

需求: CountDown 倒计时组件

电商秒杀等场景较多需求

**Comment by rex-zsd** [comment]
倒计时的功能逻辑居多，样式不定，感觉不太适合组件库来提供。

**Comment by lonquan** [comment]
提供基本的倒计时就后了吧, 不需要样式, 由外部定义

**Comment by feelslive** [comment]
![image](https://user-images.githubusercontent.com/20579220/59261104-709b5f80-8c6f-11e9-9dbf-1ef4f5b80ce4.png)
实现基本逻辑就行，求加入
