### ISSUE TITLE
popup组件在真机上不支持覆盖原生组件

### ISSUE THREAD

**Issue by smile33** [youzan/vant-weapp#1078]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**描述一下问题**
canvas、map等原生组件下，使用vue-action-sheet等popup时，虚拟机显示正常，但真机无法覆盖原生组件，导致样式错乱。内部组件标签无法用cover-view代替~~

**截图**
![_15446909396364](https://user-images.githubusercontent.com/11691667/49926658-0b9cc200-fef7-11e8-951f-2059521318a9.png)

**环境**
 - 设备: iphone X
 - 基础库版本: 2.4.1
 - Vant Weapp 版本: 0.4.6

**Comment by AlwaysSkylll** [comment]
+1 iphone6 iphone5s
自定义了一个组件用了popup,不能覆盖外层的其他组件和 view 标签

**Comment by AlwaysSkylll** [comment]
> +1 iphone6 iphone5s
> 自定义了一个组件用了popup,不能覆盖外层的其他组件和 view 标签

看了下可以了，是因为被一个全局的view { overflow: auto } 影响了，

**Comment by rex-zsd** [comment]
这个问题暂时无解，自定义组件的层级是最高的。

**Comment by GitACDreamer** [comment]
@rex-zsd 那这种情况如何解决？ 设置蒙层？

**Comment by jiangxiaoqiang** [comment]
遇到同样的问题
