### ISSUE TITLE
Failed to load font https://b.yzcdn.cn/vanui-weapp/vanui-weapp-icon-4381aded05.ttf

### ISSUE THREAD

**Issue by VonSdite** [youzan/vant-weapp#1082]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**描述一下问题**
描述一下你遇到的问题，包括复现方式、导致结果
使用 `van-field`输入框的 `clearable` API显示不出来清除控件的图标

**截图**
如果是 UI 问题，请提供具体截图
![image](https://user-images.githubusercontent.com/25704948/50005593-da4eef80-ffe5-11e8-9d0b-16a794eebad2.png)
![image](https://user-images.githubusercontent.com/25704948/50005605-e0dd6700-ffe5-11e8-919a-081c52b10d55.png)

**环境**
 - 设备: 
 - 基础库版本: 
 - Vant Weapp 版本: 0.4.9

**Comment by rex-zsd** [comment]
微信开发者工具的问题，真机不会出现的。
