### ISSUE TITLE
如何在TypeScript引入Toast模块

### ISSUE THREAD

**Issue by Freeway1979** [youzan/vant-weapp#1088]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**你需要的功能是？**
描述一下你需要的功能，用于解决什么问题

我在使用TypeScript时，引用Toast存在问题，没有相关d.ts 无法引入Toast

`import Toast from '../../node_modules/vant-weapp/dist/toast/toast";`

提示找不到模块。

**你期望 API 是什么样的？**
描述一下你期望的 API 形式

希望提供相关的d.ts或其它方案。

**Comment by rex-zsd** [comment]
下版本将会导出声明文件

**Comment by SeLiNnnn** [comment]
求问怎么解决这个问题呢，现在有.d.ts文件 但是外部node_modules里的根本无法引用呀，miniprogram_npm里的是.js根本不知道怎么引
