### ISSUE TITLE
[Bug Report] Tab组件动态调整父容器宽度时，下划线显示错位

### ISSUE THREAD

**Issue by frontbear** [youzan/vant-weapp#1089]
> 这个BUG类似 https://github.com/youzan/vant-weapp/issues/811

**描述一下问题**
```html
  <van-row>
    <van-col span="{{ isSuccess ? 18 : 24 }}">
      <van-tabs active="{{ tabIndex }}">
        <van-tab title="推荐"></van-tab>
        <van-tab title="最新"></van-tab>
        <van-tab title="热度"></van-tab>
      </van-tabs>
    </van-col>
  <van-row>
```
当 `isSuccess ` 变为 `true`的时候，tab底部line的长度没有改变，导致错位。然后点击一下其他的tab之后，line的宽度才变为正常。

**截图**
![image](https://user-images.githubusercontent.com/35812002/50069286-545cbf80-0204-11e9-89e1-2cc7c307d6a4.png)

**环境**
 - 设备: ios
 - 基础库版本: 最新
 - Vant Weapp 版本: 最新

**Comment by rex-zsd** [comment]
的确有这个问题，但是小程序组件内部监听不到外部的宽度变化。
可以在set `isSuccess ` 为 `true` 的时候，通过 `this.selectComponent` 获取到 `tabs` 组件的示例，手动调用 `tabs` 组件的 `setLine` 方法解决。
