### ISSUE TITLE
Cell 单元格中type="danger"不能正常显示颜色

### ISSUE THREAD

**Issue by yang5200793** [youzan/vant-weapp#1090]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**描述一下问题**
Cell 单元格中type="danger"不能正常显示颜色

**截图**
如果是 UI 问题，请提供具体截图
![Uploading 无标题1.png…]()

**环境**
 - 设备: windows
 - 基础库版本: 2.2.5
 - Vant Weapp 版本:Vant Weapp v0.4.9

**Comment by rex-zsd** [comment]
`cell`组件并没有`type`属性，截图挂了没传上来。
