### ISSUE TITLE
van-submit-bar希望price能够支持没有小数的格式

### ISSUE THREAD

**Issue by teri5354** [youzan/vant-weapp#1092]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**你需要的功能是？**
van-submit-bar希望price能够支持没有小数的格式

**你期望 API 是什么样的？**
描述一下你期望的 API 形式
format="{{0.00}}"或format="{{0}}"

**Comment by rex-zsd** [comment]
新增了`decimal-length`属性用于控制小数位数，将在下版本发布。
