### ISSUE TITLE
utils.wxs not found把weapp安装后，出现找不到utils.wxs的问题，目录中不存在

### ISSUE THREAD

**Issue by MartinLongYW** [youzan/vant-weapp#1096]
描述一下问题
utils.wxs not found 把weapp安装后，出现找不到utils.wxs的问题，目录中不存在

截图
![image](https://user-images.githubusercontent.com/8198638/50129133-a2300100-02b2-11e9-9477-a55b118301da.png)

环境

设备:微信开发者工具 v1.02.1811290
基础库版本:2.4.2
Vant Weapp 版本:v0.4.9

**Comment by MartinLongYW** [comment]
![image](https://user-images.githubusercontent.com/8198638/50129208-e7543300-02b2-11e9-8e42-afb775e48b4d.png)

**Comment by rex-zsd** [comment]
实际上是有的，可以打开node_modules中查看。
微信开发者工具没有把这个文件移动过来。

**Comment by MartinLongYW** [comment]
> 实际上是有的，可以打开node_modules中查看。
> 微信开发者工具没有把这个文件移动过来。

实际是有，但开发者工具中没有，引用会报错
