### ISSUE TITLE
popup示例不能显示

### ISSUE THREAD

**Issue by yang5200793** [youzan/vant-weapp#1097]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**描述一下问题**
popup按官方示例不能正常显示

**截图**
如果是 UI 问题，请提供具体截图

**环境**
 - 设备: iPhone5
 - 基础库版本: 2.4.2
 - Vant Weapp 版本:v0.4.9
![1](https://user-images.githubusercontent.com/45918476/50129624-d3113580-02b4-11e9-8ff5-4bc61a3522db.png)

**Comment by rex-zsd** [comment]
是否正确注册了组件？可以参考demo中的使用。
