### ISSUE TITLE
.wxml与.js中数据不能渲染

### ISSUE THREAD

**Issue by yang5200793** [youzan/vant-weapp#1098]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**描述一下问题**
小程序vant ui中.wxml与相应的.js数据不能互通。没办法被渲染，也不报错

**截图**
如果是 UI 问题，请提供具体截图

**环境**
 - 设备: iphone5
 - 基础库版本: 2.4.2
![2](https://user-images.githubusercontent.com/45918476/50134023-268d7e80-02c9-11e9-87cb-2e61ab07ae7a.png)
![3](https://user-images.githubusercontent.com/45918476/50134029-2a210580-02c9-11e9-84d1-655bd2af4d20.png)

 - Vant Weapp 版本:v0.4.9

**Comment by rex-zsd** [comment]
微信开发者工具的问题吧，重新编译并重启下开发者工具试下。

**Comment by yang5200793** [comment]
可以了，但还有一些小问题，可以加微信吗，我进度好慢
----- 原始邮件 -----
发件人：rex <notifications@github.com>
收件人：youzan/vant-weapp <vant-weapp@noreply.github.com>
抄送人：yang5200793 <yang5200793@sina.com.cn>,  Author <author@noreply.github.com>
主题：Re:_[youzan/vant-weapp]_.wxml与.js中数据不能渲染_(#1098)
日期：2018年12月18日 13点52分

微信开发者工具的问题吧，重新编译并重启下开发者工具试下。



&mdash;
