### ISSUE TITLE
体验评分

### ISSUE THREAD

**Issue by tong233** [youzan/vant-weapp#1102]
用小程序自带的体验评分测了一下example，比我的小程序分低哈哈。有些建议挺好的，可以参考。
![tim 20181218180659](https://user-images.githubusercontent.com/21073132/50146885-c100b880-02ef-11e9-9482-84b0d33d94d5.png)

**Comment by rex-zsd** [comment]
感谢反馈，也欢迎提pr帮助我们一起优化。
