### ISSUE TITLE
sku缩略图不可点击，需要出现轮播sku大图，如何实现？

### ISSUE THREAD

**Issue by yinxun22** [youzan/vant-weapp#1103]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**描述一下问题**
描述一下你遇到的问题，包括复现方式、导致结果

**截图**
如果是 UI 问题，请提供具体截图

**环境**
 - 设备: 
 - 基础库版本: 
 - Vant Weapp 版本:

**Comment by yinxun22** [comment]
想实现京东商城商品的sku展示方式，
点击缩略图，出现sku图片并轮播，但是没有找到sku缩略图的点击事件；
点击属性值，商品详情页轮播大图也需要改变为sku图片，所以属性的事件该如何解决。

移动端微信公众号商城

来自菜鸟前端的提问～

**Comment by rex-zsd** [comment]
这里是小程序`vant-weapp`组件库，`vant`的问题提到[issue](https://github.com/youzan/vant/issues)
