### ISSUE TITLE
van-tag标记同事使用多个标记时,英文标记和中文标记的大小无法统一

### ISSUE THREAD

**Issue by Chris-jq** [youzan/vant-weapp#1104]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**你需要的功能是？**
描述一下你需要的功能，用于解决什么问题

需要的功能: van-tag标记,在同时使用多个标记时,英文标记和中文标记的高度即使加自定义样式也无法统一高度, 如何才能设置统一高度?

**你期望 API 是什么样的？**
描述一下你期望的 API 形式

**Comment by rex-zsd** [comment]
与#1105 重复
