### ISSUE TITLE
van-tag标记同事使用多个标记时,英文标记和中文标记的大小无法统一

### ISSUE THREAD

**Issue by Chris-jq** [youzan/vant-weapp#1105]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**你需要的功能是？**
描述一下你需要的功能，用于解决什么问题

需要的功能: van-tag标记,在同时使用多个标记时,英文标记和中文标记的高度即使加自定义样式也无法统一高度,
问题: 如何才能设置统一高度?
![image](https://user-images.githubusercontent.com/34177807/50154264-d384ed00-0303-11e9-807a-a3787354b6fa.png)

**你期望 API 是什么样的？**
描述一下你期望的 API 形式

**Comment by rex-zsd** [comment]
![image](https://user-images.githubusercontent.com/8767877/50163340-30d86880-031b-11e9-95f8-de1b6512e5f1.png)
未复现问题，是自定义样式的原因？
