### ISSUE TITLE
文档中有部分icon无法显示 

### ISSUE THREAD

**Issue by nineyang** [youzan/vant-weapp#1106]
**描述一下问题**
你好，我在使用文档中的icon时，有一些可以使用，另外一些无法加载，比如`todo-list`、`bill` 、`balance-list`等，我在`index.wxss`中也没有发现对应的`class`。

**截图**

![image](https://user-images.githubusercontent.com/19544562/50161064-b8bb7400-0315-11e9-9cae-3ef5dfede577.png)

![image](https://user-images.githubusercontent.com/19544562/50161092-c7099000-0315-11e9-954f-29a317433713.png)

![image](https://user-images.githubusercontent.com/19544562/50161219-210a5580-0316-11e9-9e37-6a826876a6fa.png)

**环境**
 - 设备: 开发者工具
 - 基础库版本: 
 - Vant Weapp 版本:0.4.9

**Comment by rex-zsd** [comment]
目前小程序不支持这几个图标，可以查看demo小程序有哪些可用。
`vant`和`vant-weapp`文档中共用了一套demo，所以会看到这几个图标。
计划在`v0.5.0`版本支持这些在`vant`中新增的图标。
