### ISSUE TITLE
Area 邮编错误以及code设置问题

### ISSUE THREAD

**Issue by willnew** [youzan/vant-weapp#1107]
**描述一下问题**
Area组件使用的邮编有误，举例：成都市为510100，实际应为610000；相应的下面的行政区的邮编也有问题。不过这不是重点，使用了正确的邮编过后会出现某些区选不上的问题，这个时候看了下area/index.js的逻辑，发现一个逻辑会使很多city无法选中，并且fallback到第一个city（截图为该段代码）

**截图**
![1545147876946](https://user-images.githubusercontent.com/1535543/50165272-8f9fe100-031f-11e9-9fa5-decb4a9d5b65.jpg)

**环境**
 - 设备: ALL
 - 基础库版本: ??
 - Vant Weapp 版本: 0.4.9

**Comment by willnew** [comment]
后续pickerValue里面city的设置也有类似的问题，由于成都市的锦江区，武侯区，青羊区，金牛区和成华区都是6100**，所以比较低前四位的时候完全一致，从而拿到的index始终是第一个city

**Comment by rex-zsd** [comment]
`area`组件中的areaCode不是邮编，而是行政区划代码。
参考[国家统计局](http://www.mca.gov.cn/article/sj/xzqh/2018/201804-12/20181011221630.html)
