### ISSUE TITLE
急需帮助，设置了三个van-tab，其中一个内容滚动到下面的时候，另外两个也自动滚动？

### ISSUE THREAD

**Issue by tismagic** [youzan/vant-weapp#1108]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**你需要的功能是？**
如图第一个tab我自己滚动到下面
![image](https://user-images.githubusercontent.com/3600190/50196841-cb6a9300-037f-11e9-97ac-72f5f709c71f.png)
切换到第二个tab也跟着滚动了
![image](https://user-images.githubusercontent.com/3600190/50196878-e89f6180-037f-11e9-8395-91db0cdb31ba.png)

**你期望 API 是什么样的？**
第二个tab不应该是保持原样的吗

**Comment by 593496637** [comment]
同样遇到此问题

**Comment by Bubbleinpit** [comment]
相同问题，在标签切换时将scrollTop置为0也没用。

**Comment by Bubbleinpit** [comment]
#1030

**Comment by Bubbleinpit** [comment]
`<van-tabs sticky scroll-top="{{scrollTop}}" active="{{ tags.defaultIndex }}" bind:change="onChange">`
相同问题

**Comment by rex-zsd** [comment]
已有 pr #1030 修复，下版本发布

**Comment by tismagic** [comment]
> 已有 pr #1030 修复，下版本发布

谢谢
