### ISSUE TITLE
var-toast VM99619:1 未找到 van-toast 节点，请确认 selector 及 context 是否正确

### ISSUE THREAD

**Issue by ch345073110** [youzan/vant-weapp#1109]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**描述一下问题**
使用van-toast的时候
VM99619:1 未找到 van-toast 节点，请确认 selector 及 context 是否正确

**截图**
如果是 UI 问题，请提供具体截图

**环境**
 - 设备: 
macPro
 - 基础库版本: 
 - Vant Weapp 版本:
v0.4.9

**Comment by ch345073110** [comment]
![2018-12-19 12 05 50](https://user-images.githubusercontent.com/32119580/50198474-cceb8980-0386-11e9-8219-3b4ebb084716.png)

**Comment by MetooQ** [comment]
请问是怎么解决的呀？我也遇到了同样的问题

**Comment by maojindao55** [comment]
同求

**Comment by ch345073110** [comment]
bindtap名字不对

在 2019-01-19 22:18:53，maojindao55 <notifications@github.com> 写道：


同求

**Comment by JunevaYang** [comment]
都是在页面上忘了加<van-toast id="van-toast" />

**Comment by JunevaYang** [comment]
都是在页面上忘了加`<van-toast id="van-toast" />`

**Comment by jiangzhaojie22** [comment]
> 都是在页面上忘了加`<van-toast id="van-toast" />`

确实

**Comment by Tokisakixin** [comment]
toast能不能在组件内使用？我在组建内调用toast，<van-taost id=“van-toast”>加了，引入也没问题，但是还是出错，未找到toast节点

**Comment by xuebin00** [comment]
> toast能不能在组件内使用？我在组建内调用toast，加了，引入也没问题，但是还是出错，未找到toast节点

同问？？？

**Comment by xuebin00** [comment]
> toast能不能在组件内使用？我在组建内调用toast，加了，引入也没问题，但是还是出错，未找到toast节点

得在引入Component组件的根级Page页引入toast。。根级页的json里引入van-toast，再在wxml中加<van-toast id="van-toast" />。。。

**Comment by Tokisakixin** [comment]
> > 吐司能不能在组件内使用？我在正常内调用吐司，加了，已经没有问题，但是还是出错，未找到吐司节点
> 
> 得在引入组件组件的根级页面引入toast。根级页面的json里引入van-toast，再在wxml中加。。。

好的，谢谢，这边解决了,我这边和你说的不一样的地方就是 “得在引入组件组件的根级页面引入toast”，但是引入toast我这里是在component引入的

**Comment by shadowX1121** [comment]
> toast能不能在组件内使用？我在组建内调用toast，加了，引入也没问题，但是还是出错，未找到toast节点



> > toast能不能在组件内使用？我在组建内调用toast，加了，引入也没问题，但是还是出错，未找到toast节点
> 
> 同问？？？

toast组件context参数指定为this，即context: this就可以了

**Comment by Kobe972** [comment]
我加了`<van-toast id="van-toast" />`还不行

**Comment by totwjt** [comment]
这种都是this指向问题， 需要使用额外参数 例： 
Toast({
    context: this,
    selector: '#van-toast',
    message: '提示信息'
});
