### ISSUE TITLE
van-swipe-cell唯一性如何保证

### ISSUE THREAD

**Issue by xiao0502** [youzan/vant-weapp#1114]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**你需要的功能是？**
`van-swipe-cell` 组件在列表渲染中，如何保证想左滑动后显示删除的唯一性？

**你期望 API 是什么样的？**
描述一下你期望的 API 形式
希望能增加API字段，保证滑动后的唯一性

**Comment by rex-zsd** [comment]
开发者自行保证，可通过dataset等等手段。

**Comment by duchaolin** [comment]
这个唯一性你有办法解决么？
