### ISSUE TITLE
van-tab  内容高度一样

### ISSUE THREAD

**Issue by 593496637** [youzan/vant-weapp#1115]
**描述一下问题**
设置四个van-tab后，tab内容数量不一致的情况下，所有tab下的高度默然跟内容量最多的那个tab高度一样了。

**截图**
![default](https://user-images.githubusercontent.com/15769004/50261886-7abf6c80-0449-11e9-922c-06b2aa745908.png)

![default](https://user-images.githubusercontent.com/15769004/50261902-8f9c0000-0449-11e9-9a65-12ff27f3135e.png)

**环境**
 - 设备: windows 10
 - 基础库版本: 2.4.2
 - Vant Weapp 版本:v0.4.9

**Comment by rex-zsd** [comment]
组件式这样设计的，有什么特殊需求吗？

**Comment by createskyak** [comment]
是不是设置了动画 animated 
把 动画 去掉高度就自适应了
