### ISSUE TITLE
新增的icon不显示

### ISSUE THREAD

**Issue by wdlw** [youzan/vant-weapp#1116]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**你需要的功能是？**
描述一下你需要的功能，用于解决什么问题

**你期望 API 是什么样的？**
描述一下你期望的 API 形式

**Comment by rex-zsd** [comment]
文档的问题，vant-weapp文档中的右侧demo目前跟vant共用了一套，实际未支持这些图标。
将在0.5.0版本支持。
