### ISSUE TITLE
van-datetime-picker + popup 组合出现问题

### ISSUE THREAD

**Issue by typist** [youzan/vant-weapp#1117]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**描述一下问题**
弹出时间选择器后滑动时间控件，确定选取时间，关闭popup，在popup控件再弹出后
时间会跳到2008-01-01-00-00 且无法滚动。
多试几次就会出现。
<pre>
[van-popup
  show="{{show}}"
  position="bottom"
  bind:close="toggleAppointTimePopup"
]
[van-datetime-picker
  type="datetime"
  value="{{currentDate}}"
  bind:confirm="chooseAppointTime"
  bind:cancel="toggleAppointTimePopup"
/]
[/van-popup]
</pre>
-------------------------
<pre>
Page({
  data: {
    show:false,
    currentDate: new Date().getTime()
  },
popupAppointTimeChooser:function(e){
    this.setData({
      show:true
    });
  },
  chooseAppointTime:function(e){
    console.log(e);
    var time = new Date(e.detail);
    var appointTime = util.formatTime(time);
    this.setData({
      appointTime:appointTime,
      show:false
    });
  },
  toggleAppointTimePopup:function(e){
      this.setData({
        show:!this.data.show
      });
  }
});
</pre>
**截图**
![image](https://user-images.githubusercontent.com/3132857/50267306-c716a680-0461-11e9-87c9-b558f409b7ea.png)

**环境**
 - 设备: 开发工具内部模拟器iphone7P
 - 基础库版本: 2.3.0
 - Vant Weapp 版本: v0.4.9

**Comment by rex-zsd** [comment]
`datetime-picker`目前使用的是小程序原生的`picker-view`实现，原生的`picker-view`有点问题。
后续`datetime-picker`会用`picker`重构。

**Comment by rex-zsd** [comment]
可以关注 #1127
