### ISSUE TITLE
不知道从哪里能获取到对应icon的那些png图片

### ISSUE THREAD

**Issue by imhager** [youzan/vant-weapp#1118]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**你需要的功能是？**
功能做的很强大，正在研究学习中，但是有一个小小期望，就是从哪里能获取到对应icon的那些png图标。主要想用于小程序底层tabBar的图标设置上。

**你期望 API 是什么样的？**
描述一下你期望的 API 形式

**Comment by rex-zsd** [comment]
png图片提供不了，icon是用svg图片聚合起来的。
