### ISSUE TITLE
Stepper支持异步请求返回成功后修改相应的值

### ISSUE THREAD

**Issue by huixisheng** [youzan/vant-weapp#1124]
**你需要的功能是？**
用于购物数量加减，购物车数据同步于后台，加减数量要等`ajax`返回后修改

**你期望 API 是什么样的？**
`before` 返回 `Promise`

**Comment by rex-zsd** [comment]
有重复issue #1131 了，下版本会增加`async-change`属性。

**Comment by stonyme** [comment]
Page({
  data: {
    value: 1,
  },

  onChange(value) {
    Toast.loading({ forbidClick: true });

    setTimeout(() => {
      Toast.clear();
      this.setData({ 5 });
    }, 500);
  },
});
