### ISSUE TITLE
build 支持生成ES5的组件

### ISSUE THREAD

**Issue by huixisheng** [youzan/vant-weapp#1125]
**你需要的功能是？**
多数小程序框架使用需要关闭`ES6 转 ES5`, 希望提供`ES5`版本的组件, 便于直接使用

**你期望 API 是什么样的？**
不要自己fork仓库构建`ES5`的版本，可以根据需要选择`ES6`, `ES5`版本

**Comment by zaxlct** [comment]
有道理

**Comment by rex-zsd** [comment]
还是自己编译一下吧，打包2份没有必要。
