### ISSUE TITLE
popup+datetime-picker或popup+area 组合出现问题

### ISSUE THREAD

**Issue by goodliang** [youzan/vant-weapp#1127]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**描述一下问题**
popup+datetime-picker或popup+area  滑动中关闭 popup，多次打开或关闭，会导致 picker-view丢失 value 值，导致不能滑动，

**截图**
如果是 UI 问题，请提供具体截图
![image](https://user-images.githubusercontent.com/15775197/50337477-323ca780-054c-11e9-97f0-22f1972959fb.png)
![image](https://user-images.githubusercontent.com/15775197/50337494-47b1d180-054c-11e9-9910-43951d0bea0f.png)
![image](https://user-images.githubusercontent.com/15775197/50337502-4c768580-054c-11e9-8268-a6fe6189b797.png)

**环境**
 - 设备: 任何手机
 - 基础库版本: 2.3.2
 - Vant Weapp 版本:4.10

**Comment by rex-zsd** [comment]
`datetime-picker`和`area`后续会用`picker`重构，小程序原生的`picker-view`初始化有点问题。

**Comment by Chenganzhuo** [comment]
请问，这个问题怎么解决或者规避呢？我用datetime-picker也出现一样的问题了

**Comment by rex-zsd** [comment]
v0.5.0版本datetime-picker已经使用picker重构，应该不会有这个问题了。

**Comment by GreenyZD** [comment]
诶，我升级之后还是出现这个问题诶。
稳定复现的方式是迅速划过，在动画完成前点击确定，之后再打开就出现异常
