### ISSUE TITLE
tab切换时，页面会自动滚动到顶部，这是故意设置的吗？

### ISSUE THREAD

**Issue by createskyak** [youzan/vant-weapp#1130]
tab组件在切换时，当切换到非第一个选项时，页面会自动跳转到 顶部，切换到第一个选项时不会跳转

**截图**
![image](https://user-images.githubusercontent.com/24787348/50369052-a3bb3b00-05ca-11e9-8af8-2a0525f2389c.png)
![image](https://user-images.githubusercontent.com/24787348/50369098-044a7800-05cb-11e9-8120-1bc6f72ee5d8.png)

**环境**
 - 设备: 小米5、微信开发工具
 - 基础库版本: 2.4.1
 - Vant Weapp 版本: v0.4.10 及 v0.4.9

**Comment by zychome** [comment]
我也遇到此问题，怎么解决？？？

**Comment by powerlau** [comment]
我也遇到了这个问题，这个bug发布了这么久怎么还没修复

**Comment by DaoZhuang** [comment]
现在依然有这个问题这个问题会不会被解决？

**Comment by White-piao** [comment]
小程序用onPageScroll监听滚动条距离，然后切换其他tab页的时候，记录这个距离，之后再切换回来，使用wx.pageScrollTo方法 ，将页面滚动到之前记录的位置，duration:0 动画设置为0即可，这样用户体验更好一些，不会有从上到下的滚动效果，希望能帮到你们😉

**Comment by White-piao** [comment]
小程序用onPageScroll监听滚动条距离，然后切换其他tab页的时候，记录这个距离，之后再切换回来，使用wx.pageScrollTo方法 ，将页面滚动到之前记录的位置，duration:0 动画设置为0即可，这样用户体验更好一些，不会有从上到下的滚动效果，希望能帮到你们😉
