### ISSUE TITLE
goodsAction的z-index属性

### ISSUE THREAD

**Issue by elfland** [youzan/vant-weapp#1135]
**描述问题**
goodsAction在出现弹窗时（如商品规则选择弹窗）会被遮挡，手动改了goodsAction源码中wxss的z-index属性可解决此问题。

希望能尽快加上设置goodsAction z-index属性的接口，谢谢

**环境**
 - Vant Weapp 版本: 0.4.10

**Comment by rex-zsd** [comment]
`custom-class`有提供外部样式类`custom-class`，用这个就可以了。
