### ISSUE TITLE
mpvue使用toast报错

### ISSUE THREAD

**Issue by chenkanglin** [youzan/vant-weapp#1136]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**描述一下问题**
import 方式引入：

**截图**
![image](https://user-images.githubusercontent.com/32332525/50389295-9f765580-0763-11e9-9694-a467bbb59fac.png)

**环境**
 - 设备: 微信开发工具
 - 基础库版本: 2.4.2
"mpvue": "^1.0.11"
 - Vant Weapp 版本: v0.4.10

**Comment by chenkanglin** [comment]
import Toast from "vant/toast/toast";  在 mounted周期里面调用 Toast('测试')

**Comment by rex-zsd** [comment]
在mpvue中并没有复现你的问题。
