### ISSUE TITLE
van-cell希望能加上右边图标的功能

### ISSUE THREAD

**Issue by teri5354** [youzan/vant-weapp#1144]
**你需要的功能是？**
van-cell希望能加上右边图标的功能（自定义图标）

**你期望 API 是什么样的？**
icon-right="/images/test.png"
icon-right-class="test"

.test{
width:40px;
height:40px;
border-radius:40px;
}

**Comment by rex-zsd** [comment]
目前是支持通过slot自定义右边icon的呀，可以看下[文档](https://youzan.github.io/vant-weapp/#/cell)。
