### ISSUE TITLE
小程序里的vant图标不显示

### ISSUE THREAD

**Issue by Candytt** [youzan/vant-weapp#1149]
Vant Weapp0.4.10
小程序正常引入，搜索控件显示正常，cell控件也正常，就是van-icon 不显示，info正常显示，控制台不报错
![image](https://user-images.githubusercontent.com/33855772/50412352-8348e600-0841-11e9-8681-370331a236b7.png)

**Comment by CQByte** [comment]
貌似文档里面好多图标在icon组件的样式里都没有哈

**Comment by Candytt** [comment]
> 貌似文档里面好多图标在icon组件的样式里都没有哈

对只要是涉及到图标的都不显示，包括van-cell左侧的图标

**Comment by Candytt** [comment]
但是name是url的时候就显示 写chat-o就不显示

**Comment by Candytt** [comment]
我知道了 官网教程里的有些图标是没有的，官网里的chat-o没有，要写chat才可以
