### ISSUE TITLE
stepper组件最小限制1 输入框不能直接删除数值

### ISSUE THREAD

**Issue by wiexin** [youzan/vant-weapp#1151]
官方网页版基础用法中 input值可以直接删除变成0后输入  在小程序上是不能对1进行删除 需先输入数字再删除1

**Comment by chuangbo** [comment]
我也遇到了一样的问题，vant-weapp 示例小程序没有这个 bug，但是发布版本是有的。

`git bisect` 找到是 696ae3c 带来的问题，尝试修复一下。
