### ISSUE TITLE
使用小程序编辑器导入example目录，无法编译成功

### ISSUE THREAD

**Issue by Alan18725158720** [youzan/vant-weapp#1165]
使用小程序编辑器导入example目录，想要看看程序跑到编辑器里的效果时，编辑器提示“小程序重启耗时过久，有死循环”
![image](https://user-images.githubusercontent.com/26639852/50499031-effdf380-0a80-11e9-9fb2-0f5d21f09ca2.png)

**Comment by rex-zsd** [comment]
看下开发者工具是不是最新的。
