### ISSUE TITLE
Tab嵌套内部tabs下标显示异常

### ISSUE THREAD

**Issue by Leslie-Luo** [youzan/vant-weapp#1167]
**问题描述**
Tab嵌套内部tabs下标显示异常，第一个嵌套的tabs显示正常的，从第二个开始就不显示active选中的那个下标，切换后能显示

**代码**
`<van-tabs>
  <van-tab title="标签 1">
    <van-tabs active="0">
      <van-tab title="标签 1">内容 1</van-tab>
      <van-tab title="标签 2">内容 2</van-tab>
      <van-tab title="标签 3">内容 3</van-tab>
      <van-tab title="标签 4">内容 4</van-tab>
    </van-tabs>
  </van-tab>
  <van-tab title="标签 2">
    <van-tabs active="0">
      <van-tab title="标签 1">内容 1</van-tab>
      <van-tab title="标签 2">内容 2</van-tab>
      <van-tab title="标签 3">内容 3</van-tab>
      <van-tab title="标签 4">内容 4</van-tab>
    </van-tabs>
  </van-tab>
  <van-tab title="标签 3">内容 3</van-tab>
  <van-tab title="标签 4">内容 4</van-tab>
</van-tabs>`

**截图**

### 第一个嵌套显示正常
![WX20181228-114014.png](https://i.loli.net/2018/12/28/5c259b66b94d5.png)

### 第二个嵌套显示异常
![WX20181228-114051.png](https://i.loli.net/2018/12/28/5c259b67a7c4e.png)

### 切换后显示正常
![WX20181228-114109.png](https://i.loli.net/2018/12/28/5c259b67e588a.png)

**环境**
 - 设备: iPhone 7
 - 基础库版本: 2.4.3
 - Vant Weapp 版本: 0.4.10

**Comment by rex-zsd** [comment]
这个问题源于小程序的一个bug，组件还未渲染的时候生命周期已经执行，不是很好修复。

**Comment by wumugulu** [comment]
我也碰到同样的问题了，第二个tabs首次显示异常，点击change之后才能恢复正常:(

**Comment by rex-zsd** [comment]
tabs不建议嵌套使用，会出现初始化异常。

**Comment by RussellCao824** [comment]
现在有解决方案了吗？ @Leslie-Luo
