### ISSUE TITLE
import Page from '../../common/page';  导致Page 内函数不执行

### ISSUE THREAD

**Issue by jiaxiucai** [youzan/vant-weapp#1170]
index.js 文件导入 ../../common/page 导致页面 onLoad onShow 绑定函数不执行 删除就可以了
import Page from '../../common/page';
Page({
  data: {
    areaList: {},
    loading: true,
    value: 330302
  },
  onLoad: function () {
    console.log("2")
  },
  onShow() {
    wx.request({
      url: 'https://cashier.youzan.com/wsctrade/uic/address/getAllRegion.json',
      success: response => {
        this.setData({
          loading: false,
          areaList: response.data.data
        });
      }
    });
  },
  onChange(event) {
    console.log(event);
  },
  confirmArea(event) {
    console.log(event);
  },
});

**Comment by rex-zsd** [comment]
这个跟vant-weapp没什么关系吧？
