### ISSUE TITLE
小程序 Search 的 custom-class 无效 

### ISSUE THREAD

**Issue by GonyMaster** [youzan/vant-weapp#1172]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**描述一下问题**
定义custom-class后 样式表中未被引用 已经使用了!important

**代码**
` <van-search style="border-radius: 5px;" custom-class='custom' value="{{searchValue }}" placeholder="请输入搜索关键词" use-action-slot
        bind:search="onSearch">
        <view slot="action" bind:tap="onSearch">搜索</view>
      </van-search>`

`.custom {
  border-radius: 5px !important;
}`

**环境**

 - 设备: 模拟器
 - 基础库版本: 1.9.9
 - Vant Weapp 版本:last

**Comment by rex-zsd** [comment]
测试生效了呀。。。
![image](https://user-images.githubusercontent.com/8767877/50561273-199a7180-0d44-11e9-8b5e-619a6cd2fb7a.png)

**Comment by GonyMaster** [comment]
@rex-zsd  基础库问题  换了解决

**Comment by yoage** [comment]
@GonyMaster 请问换那个了？
