### ISSUE TITLE
tree-select 右侧选项能否支持 slot

### ISSUE THREAD

**Issue by afishhhhh** [youzan/vant-weapp#1176]
tree-select 右侧选项能否支持 slot
我想自定义右侧的 html

**Comment by rex-zsd** [comment]
否，tree-select是是通过配置来运作的单个组件，没法支持slot。

**Comment by afishhhhh** [comment]
@rex-zsd 不考虑做个 商品分类的？

**Comment by xuchengxue** [comment]
为什么我的 @click-nav="onClickNav" 不能点击
