### ISSUE TITLE
collapse折叠面板初始化报错，点击报错，点击无变化

### ISSUE THREAD

**Issue by AsanoErika** [youzan/vant-weapp#1178]
**描述一下问题**
collapse折叠面板初始化报错，点击报错，点击无变化

**截图**
![image](https://user-images.githubusercontent.com/33487077/50582597-a8bb9c80-0e9e-11e9-9e4f-883ad6184781.png)
![image](https://user-images.githubusercontent.com/33487077/50582608-bcff9980-0e9e-11e9-92ac-d54c9569d3b3.png)

**环境**
 - 设备: 微信开发者工具
 - 基础库版本: 
 - Vant Weapp 版本: 0.5.0

**Comment by rex-zsd** [comment]
初始值设了嘛？

**Comment by AsanoErika** [comment]
尴尬了，直接从指南copy过去的，指南初始值名字写错了。
