### ISSUE TITLE
新版本下question图标在oppo r9手机下显示为蓝点

### ISSUE THREAD

**Issue by Wan9x** [youzan/vant-weapp#1181]
新版本下question图标在oppo r9手机下只显蓝色背景
其他手机未测
<van-icon name="question" size="24px" color="#1296DB" />

**Comment by rex-zsd** [comment]
可以提供一下代码与UI截图吗？

**Comment by Wan9x** [comment]
> 可以提供一下代码与UI截图吗？
![e364820a739fcc0eac6295ca5d92f21](https://user-images.githubusercontent.com/37938743/50671515-62d11680-100d-11e9-854c-0a622b837821.png)
代码：
![_20190104104359](https://user-images.githubusercontent.com/37938743/50671567-ad529300-100d-11e9-8402-69ef7baa819b.png)
.mall_title {
      display: flex;
      display: -webkit-flex;
      flex-direction: row;
      justify-content: flex-start;
      align-items: center;
      font-size: 18px;
    }
