### ISSUE TITLE
ActionSheet中定义视图，如何让视图在mask中能显示

### ISSUE THREAD

**Issue by jervainy** [youzan/vant-weapp#1182]
我使用`ActionSheet`标签在`ActionSheet`中自定义了自己的视图，其中有一个`image`标签我设置为`absolute`，当我将`top`设为负数、`zIndex`设为10000时，`image`不是显示在`mask`上，而是被`mask`遮盖了，期待的效果是下面那样的
![image](https://user-images.githubusercontent.com/15903712/50626483-85a9ef00-0f69-11e9-85b2-cf07a6e54e87.png)
目前我的解决方式是在图片上面放一个`view`，高度与`image`的`top`值相等，背景设为`rgba(0,0,0,.7)`，请问有没有什么方法能让`image`直接在`mask`上显示

**Comment by chenjiahan** [comment]
这个问题的原因是 ActionSheet 默认设置了 `overflow-y: auto`

可以通过覆盖样式来解决(需要基础库 2.2.3 以上)

```html
<van-action-sheet class="my-action-sheet">
  <view class="content">内容</view>
</van-action-sheet>
```

```css
.my-action-sheet .van-popup {
  overflow: visible !important;
}
```
