### ISSUE TITLE
cell单元格icon如何设置

### ISSUE THREAD

**Issue by DaiXiaoshuai** [youzan/vant-weapp#1183]
<van-cell title="联系我们" icon='location-o' is-link />
example中的一个icon例子，在自己工程中无法显示出图标
另外这个location-o是在哪边定义的，如何获取同类型图标的icon值

 - 设备: all
 - 基础库版本:2.4.3 
 - Vant Weapp 版本:0.4.1.0

**Comment by rex-zsd** [comment]
可参考[icon文档](https://youzan.github.io/vant-weapp/#/icon)
