### ISSUE TITLE
希望有一个自定义图片的Toast

### ISSUE THREAD

**Issue by aPathFinder** [youzan/vant-weapp#1185]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**你需要的功能是？**
之前 ZanUI 在 showZanToast 中可以传 Image 参数, 希望在 Toast 组件中也可以加这个 参数.

**你期望 API 是什么样的？**
加个 image 参数就行

**Comment by mynameismaosheng** [comment]
这样的需求可以放在type为html里实现.
但是目前的代码里没有做type为html的处理方案, 而文档里是有type为html的选项的
@rex-zsd

**Comment by rex-zsd** [comment]
这个应该是文档错误了，小程序里`type=html`是实现不了的。

**Comment by rex-zsd** [comment]
增加一个slot好了。

**Comment by cctvzqj008** [comment]
我也有这个需求怎么加呢
