### ISSUE TITLE
van-field 开发者工具中无法输入 

### ISSUE THREAD

**Issue by yanjiuku** [youzan/vant-weapp#1189]
van-field 开发者工具中无法输入  无法触发焦点  但是在手机中可以

**Comment by rex-zsd** [comment]
看下是不是开发者工具的问题？

**Comment by yanjiuku** [comment]
> 看下是不是开发者工具的问题？

我更新到最新版的

**Comment by rex-zsd** [comment]
测试未复现的，还是找下本地的原因吧。

**Comment by yanjiuku** [comment]
> 测试未复现的，还是找下本地的原因吧。

谢谢了，我用其他电脑没有问题，非常感谢，是我本地的问题
