### ISSUE TITLE
似乎无法通过form表单获取formid、

### ISSUE THREAD

**Issue by bluegeek** [youzan/vant-weapp#1190]
**你需要的功能是？**
和原生form一样的体验

**你期望 API 是什么样的？**

**Comment by rex-zsd** [comment]
指的是哪个组件的问题？

**Comment by rex-zsd** [comment]
如果指的是`van-button`组件为什么无法在form中submit，仔细看[小程序官方文档](https://developers.weixin.qq.com/miniprogram/dev/component/button.html#bug--tip)
