### ISSUE TITLE
dialog等反馈组件，层级不够

### ISSUE THREAD

**Issue by XiongJingzhi** [youzan/vant-weapp#1192]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**你需要的功能是？**
在小程序中video、map、canvas等组件的层级都最高的，dialog使用的是view，无法覆盖。

**你期望 API 是什么样的？**
改用cover-view写，能蒙住map，canvas

**Comment by rex-zsd** [comment]
`cover-view`限制太大，内部只能使用指定元素，这个方案不可行的。

**Comment by Jarryxin** [comment]
有map时，触摸dialog中的内容，map组件会移动怎么解决
