### ISSUE TITLE
0.5.0版本重构了datepicker 需求change事件也返回value

### ISSUE THREAD

**Issue by andypinet** [youzan/vant-weapp#1193]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**你需要的功能是？**
0.5.0版本重构了datepicker 需求change事件也返回value

**你期望 API 是什么样的？**
我自己改了下
```
      this.updateColumnValue(value).then(function () {
        _this3.$emit('input', value);

        _this3.$emit('change', {
          picker, value
        });
      });
```

**Comment by rex-zsd** [comment]
获取`value`请监听`input`事件，目前的设计是为了跟`vant`统一。

**Comment by andypinet** [comment]
但是你们文档又没改

**Comment by andypinet** [comment]
![](https://github.com/andypinet/resourses/blob/master/2019_1_8_01.png?raw=true)

**Comment by andypinet** [comment]
@rex-zsd
