### ISSUE TITLE
无法修改van-stepper plus和minus（加号和减号）自定义样式的颜色和大小

### ISSUE THREAD

**Issue by 1429880240** [youzan/vant-weapp#1194]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**描述一下问题**
描述一下你遇到的问题，包括复现方式、导致结果
无法修改van-stepper plus和minus（加号和减号）自定义样式的颜色和大小
**截图**
如果是 UI 问题，请提供具体截图
![sdoqcx ijsq1tkuwqptt](https://user-images.githubusercontent.com/35157291/50766238-638ad680-12b3-11e9-9714-07b912311ebb.png)

**环境**
 - 设备: 微信开发者工具
 - 基础库版本: 2.4.3
 - Vant Weapp 版本:0.5.0

**Comment by rex-zsd** [comment]
加减号的样式在`::after`和`::before`伪元素上。

**Comment by rex-zsd** [comment]
加减号的样式在`::after`和`::before`伪元素上。

**Comment by congyingww** [comment]
> 加减号的样式在`::after`和`::before`伪元素上。

样式在`::after`和`::before`伪元素上 仍然无效
.van-stepper__minus::after{
    color: #3795EC !important;
}
.van-stepper__minus::before{
    color: #3795EC !important; 
}
.van-stepper__plus::after{
    color: #3795EC !important;
}
.van-stepper__plus::before{
    color: #3795EC !important;
}

**Comment by Lixq1** [comment]
.van-stepper__minu::after ,.van-stepper__minu::before,.van-stepper__plus::after， .van-stepper__plus::before
 {
   background: #ffffff !important;
 }  
是要设置背景色的
