### ISSUE TITLE
小程序省市区 首次初始化

### ISSUE THREAD

**Issue by vinokobe** [youzan/vant-weapp#1195]

**Comment by vinokobe** [comment]
![_20190108110309](https://user-images.githubusercontent.com/21050503/50807855-e86b0400-1336-11e9-9b1a-e271dcfb0f4b.png)

**Comment by rex-zsd** [comment]
问题是什么？

**Comment by vinokobe** [comment]
> 问题是什么？

就是van area组件绑定  value值，首次打开的时候并不一定能准确选中该地址
