### ISSUE TITLE
小白请教～ 怎么实现类似原生的那种tabBar  可以让tabBar一直现实在底部

### ISSUE THREAD

**Issue by liangshaoJY** [youzan/vant-weapp#1198]
我现在是在首页引用这个组件，点击任意一个标签，跳转到其他页面，但是返回之后，标签的选中态不对，跳转过去的页面是没有tabBar的， 应该不是新页面引入tabBar吧

**Comment by rex-zsd** [comment]
就是新页面引入tabbar
