### ISSUE TITLE
tab 粘性布局无效

### ISSUE THREAD

**Issue by liangshaoJY** [youzan/vant-weapp#1199]
**描述一下问题**
在做小程序时，使用粘性tab，但是向上滑动没有吸顶效果

**截图**

<img width="974" alt="image" src="https://user-images.githubusercontent.com/29418593/50911451-dee2b880-146a-11e9-88e3-6ddfadae1a05.png">

**环境**
 - 设备: 开发工具 小米8
 - 基础库版本: 2.4.4
 - Vant Weapp 版本:v0.5.0

**Comment by liangshaoJY** [comment]
Sorry. 自己使用错误

**Comment by HanLinfeng** [comment]
请问一下，您这边是怎么使用 粘性布局的呢？我这边使用的时候也发现 粘性布局无效的情况。

**Comment by HanLinfeng** [comment]
@liangshaoJY 请问一下，您这边是怎么使用 粘性布局的呢？我这边使用的时候也发现 粘性布局无效的情况。

**Comment by liangshaoJY** [comment]
> @liangshaoJY 请问一下，您这边是怎么使用 粘性布局的呢？我这边使用的时候也发现 粘性布局无效的情况。

不好意思，刚看到，不知道你有没有解决问题，你可以看下示例中的js代码，当时我就没有写所以没有效果，不过你应该不会像我一样傻
