### ISSUE TITLE
Steps当字数过多~

### ISSUE THREAD

**Issue by mynameismaosheng** [youzan/vant-weapp#1206]
**当字数过多页面异常**
desc字数过多

**截图**
![0ecd76550372414dd4ace615652ab84](https://user-images.githubusercontent.com/19756360/51010014-4e50c900-158d-11e9-9d62-d9a14934814f.png)

**环境**
 - Vant Weapp 版本: 0.5.0

**Comment by rex-zsd** [comment]
steps不适合放大量字符的，如果是这种场景，显示为竖版会更合适。

**Comment by mynameismaosheng** [comment]
> steps不适合放大量字符的，如果是这种场景，显示为竖版会更合适。

可以把 desc改成可以换行的, 2-3行之后 ...显示吗?
