### ISSUE TITLE
van-area配合van-popup组件，van-area组件滑动时关闭popup后再次打开，van-area只显示第一列且不可滑动

### ISSUE THREAD

**Issue by kurisLei** [youzan/vant-weapp#1207]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**描述一下问题**
van-area配合van-popup组件，van-area组件滑动过程中关闭popup后再次打开，van-area只显示第一列且不可滑动，请问这个怎么解决？

**截图**

**环境**
 - 设备: ios 12.1.2
 - 基础库版本: 2.4.4
 - Vant Weapp 版本: 0.5.0

**Comment by 1429880240** [comment]
van-area中用wx:if 试试

**Comment by LYlanfeng** [comment]
出现这个原因是因为在选择省市区的时候，如果选择动画（组件正在滑动中）还没结束，就直接关闭area组件，那么100%出现这个问题。通过if是可以解决，但是总感觉这样不好，但是导致的原因并不清楚具体由什么导致。

**Comment by rex-zsd** [comment]
van-area用van-picker重构过，现在还有这个问题嘛？

**Comment by a995564763** [comment]
我也遇到了 0.5.8数据还不显示 只能用老版本 老版本这个还滑不动
