### ISSUE TITLE
ActionSheet上拉菜单在小程序基础库2.4.4及以上报错

### ISSUE THREAD

**Issue by Mayandev** [youzan/vant-weapp#1208]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**描述一下问题**
ActionSheet上拉菜单在小程序基础库2.4.4及以上点击事件报错

**截图**
如果是 UI 问题，请提供具体截图
![image](https://user-images.githubusercontent.com/28648715/51019556-4c4f3000-15b6-11e9-851a-acc851ebb254.png)

**环境**
 - 设备: 模拟器
 - 基础库版本: 
 - Vant Weapp 版本:0.5

**Comment by rex-zsd** [comment]
这个是微信调用相册的报错，跟vant无关。
https://developers.weixin.qq.com/community/develop/doc/00006e5a9c0b086ffee7c25f256800
