### ISSUE TITLE
使用van-collapse报 Cannot read property 'concat' of null; 非手风琴模式

### ISSUE THREAD

**Issue by yangchaojiang** [youzan/vant-weapp#1209]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**描述一下问题**
 添加获取数据，非手风琴模式下 ，value为数组。

**截图**
 
![default](https://user-images.githubusercontent.com/13806413/51026275-19fafe00-15c9-11e9-9fc2-bb3ccef7687b.png)

**环境**
 - 设备:  微信模拟器
 - 基础库版本:  2..4.3
 - Vant Weapp 版本:  0.5.1

**Comment by rex-zsd** [comment]
请按文档传入`value`属性。

**Comment by yangchaojiang** [comment]
![default](https://user-images.githubusercontent.com/13806413/51166908-f644fa00-18df-11e9-9410-31556afaa2fe.png)

**Comment by yangchaojiang** [comment]
传入是数组哦
