### ISSUE TITLE
picker  getIndexes问题【BUG】

### ISSUE THREAD

**Issue by yanjiuku** [youzan/vant-weapp#1212]
城市多列列表【省份，城市】，我先选择省份  然后选择城市  用picker.getIndexes()获取第一次索引 例如结果为：[2, 5]  然后我第二次选择省份结果为 [3, 5]  然后我三次选择省份  [4, 0]     这里的问题就是  第一次选择完成之后  我第二次只选择省份 并没有把城市的索引设置为0  例如 [3, 0] 这样子

**Comment by rex-zsd** [comment]
异步时序有点问题，感谢反馈，将在下版本修复。
