### ISSUE TITLE
使用collapse组件时的bug

### ISSUE THREAD

**Issue by wumugulu** [youzan/vant-weapp#1214]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**描述一下问题**
使用mpvue，引入了vant的dist，在组件渲染时，console报错：
TypeError: Cannot read property 'some' of null
    at c.updateExpanded (index.js? [sm]:55)
    at c.<anonymous> (index.js? [sm]:10)
    at WAService.js:17
    at p (WAService.js:17)
    at WAService.js:17
    at n (WAService.js:6)
    at e (appservice?t=1547448729977:14796)
    at r.registerCallback.t (appservice?t=1547448729977:14796)
    at l.forEach.t (appservice?t=1547448729977:14796)
    at Array.forEach (<anonymous>)

代码如下：
```
      <van-collapse :value="activeNames" del-accordion @change="myChange">
        <van-collapse-item title="有赞微商城" name="1">
          提供多样店铺模板，快速搭建网上商城
        </van-collapse-item>
        <van-collapse-item title="有赞零售" name="2">
          网店吸粉获客、会员分层营销、一机多种收款，告别经营低效和客户流失
        </van-collapse-item>
        <van-collapse-item title="有赞美业" name="3">
          线上拓客，随时预约，贴心顺手的开单收银
        </van-collapse-item>
        <van-collapse-item title="这个不可用" name="4" disabled>
          disabled是这么用的
        </van-collapse-item>
      </van-collapse>

```
```
  data () {
    return {
      activeNames: ['1']
    }
  },
  methods: {
    myChange (e) {
      this.activeNames = e.mp.detail
    },
    。。。。。。
  }
```

**截图**
如果是 UI 问题，请提供具体截图

**环境**
 - 设备: 
 - 基础库版本: 
 - Vant Weapp 版本:

**Comment by rex-zsd** [comment]
用这个代码测试未复现呢。。
报这个错是因为传入的`value`不是数组导致的，检查下是否有别处修改了`activeNames`？

**Comment by weiwei02580** [comment]
引发这个问题的原因是官方文档，最后一个示例activeName少了个s
Page({
  data: {
    activeName: ['1']
  },
  onChange(event) {
    this.setData({
      activeNames: event.detail
    });
  }
});
