### ISSUE TITLE
Dialog 弹出框在移动端内容过多滚动时，有时候滚动不了

### ISSUE THREAD

**Issue by webtianjia** [youzan/vant-weapp#1216]
Dialog 弹出框在移动端内容过多滚动时，有时候滚动不了

                Dialog.alert({
                    title: '标题',
                    message: '通过组件调用 Dialog 时，可以实现自定义弹窗内容、异步关闭、监听微信开放能力回调事件，具体可以参考下面的示例通过组件调用 Dialog 时，可以实现自定义弹窗内容、异步关闭、监听微信开放能力回调事件，具体可以参考下面的示例通过组件调用 Dialog 时，可以实现自定义弹窗内容、异步关闭、监听微信开放能力回调事件，具体可以参考下面的示例通过组件调用 Dialog 时，可以实现自定义弹窗内容、异步关闭、通过组件调用 Dialog 时，可以实现自定义弹窗内容、异步关闭、监听微信开放能力回调事件，具体可以参考下面的示例通过组件调用 Dialog 时，可以实现自定义弹窗内容、异步关闭、监听微信开放能力回调事件，具体可以参考下面的示例通过组件调用 Dialog 时，可以实现自定义弹窗内容、异步关闭、监听微信开放能力回调事件，具体可以参考下面的示例通过组件调用 Dialog 时，可以实现自定义弹窗内容、异步关闭、监听微信开放能力回调事件，具体可以参考下面的示例通过组件调用 Dialog 时，可以实现自定义弹窗内容、异步关闭、监听微信开放能力回调事件，具体可以参考下面的示例通过组件调用 Dialog 时，可以实现自定义弹窗内容、异步关闭、监听微信开放能力回调事件，具体可以参考下面的示例通过组件调用 Dialog 时，可以实现自定义弹窗内容、异步关闭、监听微信开放能力回调事件，具体可以参考下面的示例，具体可以参考下面的示例通过组件调用 Dialog 时，可以实现自定义弹窗内容、异步关闭、监听微信开放能力回调事件，具体可以参考下面的示例'
                }).then(() => {
                    // on close
                });

**Comment by webtianjia** [comment]
过程是我在滚动中点击了遮罩层

**Comment by rex-zsd** [comment]
未复现哦，提供下测试机型？

**Comment by webtianjia** [comment]
6ps 在滑到黑色遮罩以后滚动会卡住

**Comment by webtianjia** [comment]
@rex-zsd  6ps 在滑到黑色遮罩以后滚动会卡住

**Comment by chenjiahan** [comment]
没复现这个问题喔，如果你滑了一下遮罩层，要等到遮罩层停止滑动以后，才能滑弹窗的内容，这个是浏览器正常的逻辑
