### ISSUE TITLE
Tabs明显的bug

### ISSUE THREAD

**Issue by Jadyli** [youzan/vant-weapp#1221]
**描述一下问题**
小程序npm装vant-weapp, tabs的sticky属性无效。

**截图**
如果是 UI 问题，请提供具体截图
![image](https://user-images.githubusercontent.com/15962904/51231413-6e71f500-199e-11e9-8a82-9d639df95fc9.png)
![image](https://user-images.githubusercontent.com/15962904/51231440-7fbb0180-199e-11e9-8583-dea30f3deb78.png)
![image](https://user-images.githubusercontent.com/15962904/51231462-8ba6c380-199e-11e9-8a2a-f81ee76bb71c.png)

**环境**
 - 设备: 所有
 - 基础库版本: 2.4.3
 - Vant Weapp 版本: 0.5.1

**Comment by rex-zsd** [comment]
0.5.1的tabs sticky有问题，这个pr即将回滚。

**Comment by fukcup** [comment]
me too
