### ISSUE TITLE
ActionSheet应当加入“选中”状态

### ISSUE THREAD

**Issue by microkof** [youzan/vant-weapp#1223]
**你需要的功能是？**
ActionSheet应当加入“选中”状态，比如左边有“>”符号，或者颜色高亮。

**你期望 API 是什么样的？**
selected: true || false

**Comment by rex-zsd** [comment]
action-sheet增加选中状态不是很科学，暂不考虑。

**Comment by microkof** [comment]
> action-sheet增加选中状态不是很科学，暂不考虑。

你的意思是，action-sheet是用来作为无差别的菜单的，每个action应当是无优先级的。但是现实不是这样，你认为的无差别用法，确实也有，但也有用在选中、非选中的场合的，例子很多，并没有让人觉得不合适。

我只是觉得咱们vant这么牛逼，但支持的功能不够多，就不该了。

**Comment by rex-zsd** [comment]
你的场景是什么？
action-sheet一般是用作选择一个action后立即触发相应的操作并关闭的，所以并不需要选中态。
如果你需要一个浮层，用来选择一些选项，然后点击确定来完成选择。
action-sheet可能不太适合，可以考虑用popup自定义。

**Comment by microkof** [comment]
> 你的场景是什么？
> action-sheet一般是用作选择一个action后立即触发相应的操作并关闭的，所以并不需要选中态。
> 如果你需要一个浮层，用来选择一些选项，然后点击确定来完成选择。
> action-sheet可能不太适合，可以考虑用popup自定义。

场景：在setting页面，比如有一行典型的cell，是性别：男/女，默认是男，点拉下来可以看到男和女两个action，男为选中，如果点女，则女出现在cell里。

而且有一点，并不用点击“确定”，点击女就直接OK了。

**Comment by money4marry** [comment]
> Reference in

我也有类似的想法，把actionsheet作为select的替代，使用picker感觉操作繁琐。选项少的情况下actionsheet的点击生效用户体验好一点
