### ISSUE TITLE
nav-bar 组件希望可以增加属性传入机制

### ISSUE THREAD

**Issue by webyangpei** [youzan/vant-weapp#1225]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**你需要的功能是？**
需要nav-bar 组件可以增加属性传入的功能，目前只需要一个padding-top属性传入，就像z-index属性那样，用于解决小程序自定义头部在不同机型上的表现差异问题。（比如普通ipone需要padding-top：20px；iponeX就需要46px；还有更多的安卓机），通过微信小程序的自动检测api来为不同的机型适配不同的padding-top

**你期望 API 是什么样的？**
期望一个类似z-index那样的属性

**Comment by rex-zsd** [comment]
通过`custom-class`可以自定义内部的样式，设置`padding-top`足够了。
`zIndex`单独成属性是为了与 vant 统一API。
