### ISSUE TITLE
van-dialog van-popup在里面填充内容后，还可以滑动页面。

### ISSUE THREAD

**Issue by sonofmagic** [youzan/vant-weapp#1226]
**描述一下问题**
本人写了几个页面比较长，上下滑动的那种,发现使用van-dialog van-popup的时候，拖动dialog中间和popup里面的时候，页面依旧可以上下滑动（非外层的modal），不知道是否有什么方法，可以在dialog和popup出现的时候，锁住页面的位置。

**截图**
非锁定状态的问题（canvas 手写签名后上下滑动）
![image](https://user-images.githubusercontent.com/15621541/51298357-3b436a80-1a5f-11e9-8d1d-8785ce878d8e.png)

**环境**
 - 设备: 安卓
 - 基础库版本: 2.5.0
 - Vant Weapp 版本:0.4.10

**Comment by Hsensor** [comment]
page 节点添加overflow:hidden 样式就可以了

**Comment by woodccc** [comment]
这是微信滚动穿透的问题，跟 vant 没关系。
可以使用 scroll-view ,弹出 popup 时，设置 scroll-y 为 false。
希望有帮助。

**Comment by weijiegao** [comment]
该组件外层套一层view,<view catchtouchmove='banScroll'>即可
