### ISSUE TITLE
van-dialog组件引用后在IOS中阻止了整个页面的渲染，组件也渲染不出

### ISSUE THREAD

**Issue by xiaojunzi** [youzan/vant-weapp#1227]
在IOS中，引用van-dialog组件后组件也渲染不出，阻止了整个页面的渲染，wxml中只剩下个page标签了

![Uploading image.png…]()
![image](https://user-images.githubusercontent.com/8497470/51300434-d68c0e00-1a66-11e9-8887-c5ac3efaff8f.png)

**环境**
IOS环境
 - 设备: 所有苹果真机
 - 基础库版本: 
 - Vant Weapp 版本: 最新版本

**Comment by rex-zsd** [comment]
整个页面都渲染不出来，一个dialog肯定达不到这样的效果。
检查下wxml代码是不是有什么问题吧。。。
