### ISSUE TITLE
filed 放在actionSheet 页面滚动时 placeholder 和value会滚动出去

### ISSUE THREAD

**Issue by airzhanglin** [youzan/vant-weapp#1232]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**描述一下问题**
描述一下你遇到的问题，包括复现方式、导致结果
filed 放在actionSheet 页面滚动时 placeholder 和value会滚动出去
**截图**
如果是 UI 问题，请提供具体截图

**环境**
 - 设备: iphoe7
 - 基础库版本: 2.4.3
 - Vant Weapp 版本:v0.5.1

**Comment by rex-zsd** [comment]
input是原生组件，微信小程序的问题。
请尽量避免这样使用。
