### ISSUE TITLE
在微信开发工具中，提示这么一个错误：Failed to load font https://img.yzcdn.cn/vant/vant-icon-3d2f5b.woff2

### ISSUE THREAD

**Issue by fanhualei** [youzan/vant-weapp#1235]
**描述一下问题**
在微信开发工具中，提示这么一个错误：Failed to load font https://img.yzcdn.cn/vant/vant-icon-3d2f5b.woff2

**Comment by rex-zsd** [comment]
微信开发者工具的问题，下载字体文件失败了。
