### ISSUE TITLE
请问能具体说一下怎么在开发者工具预览么

### ISSUE THREAD

**Issue by Fnckerpoi** [youzan/vant-weapp#1240]
我按照npm install npm run dev 不成功
请问我到底应该要怎么安装编译才可以正常在开发者工具中预览组件？
还有小程序怎么输入执行命令行？不应该是cmd进入到目录下面执行代码么？

**Comment by rex-zsd** [comment]
npm没安装？

**Comment by liguangze** [comment]
@Fnckerpoi  你预览成功了吗
