### ISSUE TITLE
请问 van-tabs 如何固定在顶部不随页面滚动消失?

### ISSUE THREAD

**Issue by Ri-Forever** [youzan/vant-weapp#1241]
请问 van-tabs 如何固定在顶部不随页面滚动消失?

**Comment by teri5354** [comment]
试一下这个
.van-tabs__wrap {
  position: fixed !important;
}

**Comment by rex-zsd** [comment]
通过外部样式类custom-class可以自定义样式，注意加`!important`。

**Comment by tong233** [comment]
> 通过外部样式类custom-class可以自定义样式，注意加`!important`。

@rex-zsd 试了有问题,看了源码custom-class在最外层view上,改到里面那层van-tabs__wrap上就行了

**Comment by afishhhhh** [comment]
@rex-zsd 这个问题还在诶，最新版本的，我直接在源代码里往里面一层view加了fixed
