### ISSUE TITLE
小程序中NavBar 导航栏软盘弹出来时会将导航栏顶出去

### ISSUE THREAD

**Issue by 18390211712** [youzan/vant-weapp#1247]
**描述问题**
小程序中使用NavBar 导航栏提交表单时如果最低部是textarea,input软盘弹出来时会将导航栏顶出去，请问这个问题怎么破。

**截图**

![image](https://user-images.githubusercontent.com/30167120/51614067-dfe21280-1f5f-11e9-9c22-e2061186fcdd.png)
![image](https://user-images.githubusercontent.com/30167120/51614074-e5d7f380-1f5f-11e9-8b30-8245edc9a607.png)
![image](https://user-images.githubusercontent.com/30167120/51614559-defdb080-1f60-11e9-96da-768cb778ab38.png)
![image](https://user-images.githubusercontent.com/30167120/51614566-e2913780-1f60-11e9-8fab-a76c89f5f6d7.png)
![image](https://user-images.githubusercontent.com/30167120/51614568-e4f39180-1f60-11e9-9dcb-14de9298ee9c.png)

**环境**
 - 设备: 目前使用得时iphone6（估计所有得手机都有这问题）
 - 基础库版本: 微信web开发者工具(wechat_devtools_1.02.1812271_x64)
 - Vant Weapp 版本: v0.5.1

**Comment by 18390211712** [comment]
![image](https://user-images.githubusercontent.com/30167120/51614415-947c3400-1f60-11e9-902f-dbbefa08ddf0.png)
![image](https://user-images.githubusercontent.com/30167120/51614482-b5448980-1f60-11e9-8cc2-ec99e6062b92.png)
![image](https://user-images.githubusercontent.com/30167120/51614488-b83f7a00-1f60-11e9-90ba-6d9b38c5f3e2.png)

**Comment by rex-zsd** [comment]
这个暂时没有办法，iOS键盘弹起来时会把整个页面推上去，NavBar毕竟也是页面里的一个组件而已。
