### ISSUE TITLE
能不能给个详细一点的引入教程?微信文档就两句话，然后UI文档也是两句话。我直接目录运行命令行根本就不行。

### ISSUE THREAD

**Issue by Fnckerpoi** [youzan/vant-weapp#1248]

**Comment by lixize** [comment]
发现同样的问题，直接下载zip包解压，运行npm install和npm run dev后，打开example是报错的，而且不同版本报的错误还不一样。
目前我是通过运行npm命令后，在开发者工具中打开有提示某些文件缺失，关闭项目，然后直接复制dist文件夹覆盖到example的dist，就可以实现正常预览。

**Comment by Fnckerpoi** [comment]
> 发现同样的问题，直接下载zip包解压，运行npm install和npm run dev后，打开example是报错的，而且不同版本报的错误还不一样。
> 目前我是通过运行npm命令后，在开发者工具中打开有提示某些文件缺失，关闭项目，然后直接复制dist文件夹覆盖到example的dist，就可以实现正常预览。

请问你后面调用组件的时候是怎么调用的？因为npm预览都不行更别说构建npm引用了
