### ISSUE TITLE
toast调用没反应

### ISSUE THREAD

**Issue by Ri-Forever** [youzan/vant-weapp#1249]
js文件引用toast

import Toast from '../../dist/toast/toast';
Toast.success("成功!");

报  未找到 van-toast 节点，请确认 selector 及 context 是否正确

**Comment by Ri-Forever** [comment]
可是官方文档就这么些的为啥没问题???????

**Comment by Ansxu** [comment]
要在页面中增加一个dom节点，看文档
![image](https://user-images.githubusercontent.com/39543324/51781752-197d6e00-2158-11e9-8042-84401fc9739a.png)

**Comment by gaofengxu888** [comment]
奇怪的是，我加了也不行，又和我一样的吗

**Comment by liu-xiao-cui** [comment]
@gaofengxu888 如果是在自定义组件中使用，需要加上 context 配置，可以看看文档
```js
// wxml 加上这个
<van-toast id="van-toast" />

// js 中这样使用
Toast({
  context: this,
  message: '我是提示文案'
});
```
