### ISSUE TITLE
tabs的粘性定位没用

### ISSUE THREAD

**Issue by BenXi630** [youzan/vant-weapp#1250]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**描述一下问题**
描述一下你遇到的问题，包括复现方式、导致结果
![c632925d-d62a-45aa-b192-4381cecd5a6f png](https://user-images.githubusercontent.com/38492283/51784109-15b11200-217f-11e9-92ca-976b29ceb89d.jpg)

**截图**
如果是 UI 问题，请提供具体截图

**环境**
 - 设备: 小程序
 - 基础库版本: 
 - Vant Weapp 版本:最新版

**Comment by rex-zsd** [comment]
scrollTop传对了吗？

**Comment by BenXi630** [comment]
> scrollTop的传对了吗？
对了
![bfe759d4-8d3d-4dda-b568-5f15883dc837 png](https://user-images.githubusercontent.com/38492283/51784154-bc95ae00-217f-11e9-99e2-2b405cb39de8.jpg)

**Comment by rex-zsd** [comment]
版本是0.5.2对吧？

**Comment by BenXi630** [comment]
> 版本是0.5.2对吧？

v0.5.1

**Comment by rex-zsd** [comment]
0.5.1粘性定位有bug #1217 ，0.5.2回滚了。
可以升下0.5.2试试。

**Comment by BenXi630** [comment]
> 0.5.1 粘性定位有bug [＃](https://github.com/youzan/vant-weapp/pull/1217) 1217,0.5.2回滚了。
> 可以升下0.5.2试试。

在哪下，我看官网现在版本是0.5.1
