### ISSUE TITLE
usingComponents后复杂对象失去双向绑定

### ISSUE THREAD

**Issue by Sunzhuokai** [youzan/vant-weapp#1251]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**描述一下问题**
描述一下你遇到的问题，包括复现方式、导致结果
```html
<van-cell title="单元格" :value="message.message.message"/>
<div class="usermotto">
  <div class="user-motto">
    <card :text="message.message.message"></card>
  </div>
</div>
```
页面引入usingComponents后，复杂对象不会进行深拷贝，造成双向绑定失效
**截图**
如果是 UI 问题，请提供具体截图
![image](https://user-images.githubusercontent.com/8599906/51784439-8823f100-2183-11e9-8d90-df7ceaa98f01.png)

**环境**
 - 设备: 
 - 基础库版本: 
 - Vant Weapp 版本:

**Comment by Sunzhuokai** [comment]
在card中可以双向绑定，在vant组件中不会

**Comment by rex-zsd** [comment]
这个不是vant的问题吧= =

**Comment by rex-zsd** [comment]
这是mpvue没处理好小程序的逻辑呀。。。
