### ISSUE TITLE
wepy下使用toast和Dialog都提示了一个警告，没出现demo的演示效果

### ISSUE THREAD

**Issue by yangchunboy** [youzan/vant-weapp#1252]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**wepy下使用Dialog没有效果**
首先，我在引用cell等其他组件都是没问题的,但是按照文档将Dialog和toast引入进去后却没出现效果，
1.首先引用了dialog，config = {
    "usingComponents": {
      "van-dialog": "../vant/dialog/index"
    }
  }
2.在template模板中加了<van-dialog id="van-dialog" />
3.在script中也引入了import Dialog from '../vant/dialog/dialog'
点击事件触发后执行Dialog.confirm({
        title: '标题',
        message: '弹窗内容'
      }).then(() => {
        // on confirm
      }).catch(() => {
        // on cancel
      });
但是没有出现弹出框，console界面出现了一个警告文字是：未找到 van-dialog 节点，请确认 selector 及 context 是否正确

**截图**
![qq20190127-180835](https://user-images.githubusercontent.com/22066237/51799709-8f203180-225f-11e9-84ba-f7b150717e0c.png)

**环境**
 - 设备: macos high sierra 10.13.6
 - 基础库版本: wepy: 1.7.2
 - Vant Weapp 版本:0.5.2

**Comment by rex-zsd** [comment]
`wxml`节点写了吗？

**Comment by yangchunboy** [comment]
在template里面写了<van-dialog id="van-dialog" />

**Comment by yangchunboy** [comment]
<van-dialog id="van-dialog" />

**Comment by yangchunboy** [comment]
‘<van-dialog id="van-dialog" />’

**Comment by rex-zsd** [comment]
贴代码

**Comment by yangchunboy** [comment]
2.<van-dialog id="van-dialog" />

**Comment by yangchunboy** [comment]
这个标记怎么粘不上去、。。。

**Comment by yangchunboy** [comment]
稍等一下

**Comment by linliya** [comment]
![image](https://user-images.githubusercontent.com/17542781/51963111-64232100-249d-11e9-9935-0b748743ff24.png)
加上 context 试试？

**Comment by rex-zsd** [comment]
@yangchunboy 在组件里使用请指定 `context ` 为 `this`。

**Comment by alvin198761** [comment]
然后加了context: this 也没有什么用,依然是这个错误,其他的控件用起来好像没有这个问题

**Comment by youngsherlee** [comment]
遇到了同样的问题，添加了context还是报一样的错误

```
  buyCode: function(e) {
    console.log(e);
    Dialog.alert({
      context: this,
      message
    });
  }
```

`<van-dialog id="van-dialog" />
`

**Comment by youngsherlee** [comment]
解决了，在app.json里面引入一下就好了
```
  "usingComponents": {
    "van-dialog": "miniprogram_npm/vant-weapp/dialog/index"
  }
```

**Comment by GitHub-Haisheng** [comment]
> 解决了，在app.json里面引入一下就好了
> 
> ```
>   "usingComponents": {
>     "van-dialog": "miniprogram_npm/vant-weapp/dialog/index"
>   }
> ```

这里才是问题的关键  在组件中使用 一定要加这个 最容易忘记了。非常感谢！
