### ISSUE TITLE
van-submit-bar & van-field 层级问题 

### ISSUE THREAD

**Issue by webtianjia** [youzan/vant-weapp#1253]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**描述一下问题**

**截图**
# 正常状态 PC 端测试

![image](https://user-images.githubusercontent.com/22638382/51813559-ef5fb380-22f1-11e9-9349-f7d1d8f17203.png)

ios 6Puls
# 手动截图
![image](https://user-images.githubusercontent.com/22638382/51813688-8593d980-22f2-11e9-9331-fd65cae80f8f.png)

**环境**
ios 6puls 
版本：12.1.2
 - Vant Weapp 版本: 0.5.1

# 部分代码 样式上我没有设置任何层级

# van-submit-bar
``` 
<slot>
        <van-submit-bar   button-text="提交订单" @submit="onClickButton" :loading="false">
            <div  slot="top" class="van-submit-bar__tip van-submit-bar__tip">
                     订单金额与服务费将分别支付，订单金额支付成功后请进行二次支付服务费
            </div>
            <div class="price-wrapper">
                <div class="item">
                    <label class="label">合计 :</label>
                    <span class="price-main">HK$9999.00</span>
                </div>
                <div class="item">
                    <label class="label">约 :</label>
                    <span class="price-secondary">￥9999.50</span>
                </div>
            </div>
        </van-submit-bar>

```
# van-field type=textarea

```
    <van-field :value="message" label="买家留言" type="textarea" placeholder="请输入留言" autosize :border="false"/>
```
# PS
需要更新资料请随时联系我，辛苦了~

**Comment by rex-zsd** [comment]
这个无解，小程序的input是原生组件，层级比普通组件高的，设置`z-index`也没用。

**Comment by StephenCMZ** [comment]
请问问题解决了吗？弹出dialog和action-sheet都出现这个问题
