### ISSUE TITLE
van-collapse用在van-popup里面默认第一次显示面板内容是关闭状态无法更改

### ISSUE THREAD

**Issue by pangxiaolong** [youzan/vant-weapp#1254]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**描述一下问题**
van-collapse用在van-popup里面，设置activeNames值为全部面板打开，发现初始化时候面板全部为未打开状态，查看dom发现面板view的height为0不是auto，点击2次之后面板会出现，点击改变状态没有问题，只是初始化的参数空时显示有问题

**截图**
[![kMpUJK.md.png](https://s2.ax1x.com/2019/01/28/kMpUJK.md.png)](https://imgchr.com/i/kMpUJK)

**环境**
 - 设备: 微信开发者工具
 - 基础库版本: 2.5.1
 - Vant Weapp 版本:v0.5.1

**Comment by pangxiaolong** [comment]
@rex-zsd

**Comment by rex-zsd** [comment]
collapse 组件在初始化时会计算 collapse-item 的展开状态，为了实现动画效果需要获取内容的高度。
如果套在popup中，因为节点还未渲染高度获取不到，所以会有这个问题。
利用小程序现有的生命周期 collapse 组件没法从内部获取到是否进行了渲染。
可以在 collapse 上用`wx:if`控制下，跟popup的状态同步，可以解决。

**Comment by 908705107** [comment]
你好，我也遇到了一样的问题， @rex-zsd 按你说的给van-collapse 加了wx:if="{{ popShow }}" 控制了还是无效

`    <van-button type="default" bindtap="showSxBox">展开抽屉</van-button>
		<van-popup show="{{ popShow }}" position="right" custom-style="width:50%;height:100%;" bind:close="onClose">
				<van-collapse wx:if="{{ popShow }}" value="{{ activeNames }}" bind:change="onChange">
					<van-collapse-item  title="有赞微商城" name="1">
						提供多样店铺模板，快速搭建网上商城
					</van-collapse-item>
					<van-collapse-item   title="有赞零售" name="2">
						网店吸粉获客、会员分层营销、一机多种收款，告别经营低效和客户流失
					</van-collapse-item>
					<van-collapse-item  title="有赞美业" name="3" disabled>
						线上拓客，随时预约，贴心顺手的开单收银
					</van-collapse-item>
				</van-collapse>
		</van-popup>`


`Page({
  data: {
    activeNames: ['1'],
  },
  onChange(event) {
    this.setData({
      activeNames: event.detail,
    });
  },
  showSxBox: function () {
    this.setData({
      popShow: true,
    });
  },
  onClose() {
    this.setData({
      popShow: false
    });
  },
});`

**Comment by 908705107** [comment]
> 注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.
> 
> **描述一下问题**
> van-collapse用在van-popup里面，设置activeNames值为全部面板打开，发现初始化时候面板全部为未打开状态，查看dom发现面板view的height为0不是auto，点击2次之后面板会出现，点击改变状态没有问题，只是初始化的参数空时显示有问题
> 
> **截图**
> [![kMpUJK.md.png](https://camo.githubusercontent.com/5688b03a96173dd5a1fcaa11661c1fc43b62a446/68747470733a2f2f73322e617831782e636f6d2f323031392f30312f32382f6b4d70554a4b2e6d642e706e67)](https://imgchr.com/i/kMpUJK)
> 
> **环境**
> 
> * 设备: 微信开发者工具
> * 基础库版本: 2.5.1
> * Vant Weapp 版本:v0.5.1

兄弟 你解决了吗，我加了wx:if 有时候能渲染，有时候不行
