### ISSUE TITLE
小程序中Tabbar功能

### ISSUE THREAD

**Issue by marquisXuan** [youzan/vant-weapp#1256]
# 使用小程序中的custom-tab-bar出现的问题

1. 使用小程序的custom-tab-bar，封装了vant-tabbar组件。但是在使用wx.hideTabBar时，van-tabbar不能如期的隐藏。请问该如何实现？

2. 在微信的custom-tab-bar组件中使用了vant-tabbar组件。在第一次切换tab时，active可以与tab对应上，但是已经渲染过的tab页面，再次点击时，tab与active对应不上。

**Comment by rex-zsd** [comment]
`wx.hideTabBar`是小程序原生的api，无法控制vant组件的显示/隐藏。
vant-tabbar只是一个展示组件，本身没有任何切换页面的功能，需要开发者自己控制`active`。

**Comment by hiwjd** [comment]
@marquisXuan active对应不上的原因应该是[这个](https://developers.weixin.qq.com/miniprogram/dev/framework/ability/custom-tabbar.html)
> 每个 tab 页下的自定义 tabBar 组件实例是不同的，可通过自定义组件下的 getTabBar 接口，获取当前页面的自定义 tabBar 组件实例。
> 注意：如需实现 tab 选中态，要在当前页面下，通过 getTabBar 接口获取组件实例，并调用 setData 更新选中态。可参考底部的代码示例。

我在页面的onLoad里加了
```
if (typeof this.getTabBar === 'function' &&
      this.getTabBar()) {
      this.getTabBar().setData({
        active: "me"
      })
}
```
来设置正确的选中Tab
