### ISSUE TITLE
DatetimePicker  format 

### ISSUE THREAD

**Issue by DestinyHunter** [youzan/vant-weapp#1258]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**你需要的功能是？**

时间组件的格式化功能.需要显示2019年 1月 1日 10点50分

**你期望 API 是什么样的？**
描述一下你期望的 API 形式

**Comment by rex-zsd** [comment]
小程序自定义组件不支持prop传函数，这个功能没法跟vant对齐了。

**Comment by DestinyHunter** [comment]
可以传对象字符串啊.起码能让后面添加年月日类

**Comment by rex-zsd** [comment]
formatter在0.5.11中支持了。
