### ISSUE TITLE
加载中的按钮需要可以加说明文字

### ISSUE THREAD

**Issue by ALANXIAORUI** [youzan/vant-weapp#1259]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**你需要的功能是？**
加载中的按钮需要可以加说明文字，支持变量，不然跟用户沟通信息不全面，为什么加载，在加载什么

**你期望 API 是什么样的？**
如题，允许直接加一个<text>并生效即可

**Comment by chenjiahan** [comment]
下个版本会支持
