### ISSUE TITLE
field 清除图标不居中

### ISSUE THREAD

**Issue by tong233** [youzan/vant-weapp#1261]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**描述一下问题**

.van-field__clear-root {
  `display: flex;`
  `align-items: center;`
  height: 24px;
}

加这个就可以了

**截图**
如果是 UI 问题，请提供具体截图
![image](https://user-images.githubusercontent.com/21073132/51951964-8ef78000-2471-11e9-80d7-c628797f4c6e.png)

**Comment by tong233** [comment]
注意看偏下

**Comment by rex-zsd** [comment]
感谢反馈，将在下版本优化。
