### ISSUE TITLE
tabs组件的bind:scroll不触发

### ISSUE THREAD

**Issue by Lingqinyu** [youzan/vant-weapp#1263]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**描述一下问题**
描述一下你遇到的问题，包括复现方式、导致结果
tabs组件的bind:scroll不触发，控制台无报错和打印
**截图**
如果是 UI 问题，请提供具体截图
![image](https://user-images.githubusercontent.com/20594036/51955267-38447300-247e-11e9-88ef-7021fafe252d.png)
![image](https://user-images.githubusercontent.com/20594036/51955279-41cddb00-247e-11e9-8494-b2f741b27cfb.png)

**环境**
 - 设备:  微信开发者工具
 - 基础库版本: 2.5.1
 - Vant Weapp 版本:0.5.1

**Comment by rex-zsd** [comment]
tabs组件没有抛出scroll事件呀，外面肯定监听不到。
