### ISSUE TITLE
submitBar 中 API safe-area-inset-bottom 设置无效

### ISSUE THREAD

**Issue by lishihai** [youzan/vant-weapp#1266]
**描述一下问题**
1、tabBar页面中，因为底部有小程序默认的tabBar，故将submitBar 组件中 safe-area-inset-bottom="false" ，但是没有效果，padding-bottom:34px 都会出现
2、其他普通页面中设置也没有效果

**环境**
 - 设备: iPhone X
 - 基础库版本: 2.5.2
 - Vant Weapp 版本: 0.5.2

**Comment by rex-zsd** [comment]
贴代码，demo中设为`false`都是有效的。

**Comment by rex-zsd** [comment]
额，小程序虽然会自动转类型，但是经常会出些意外的bug
最好还是按照类型来传参
