### ISSUE TITLE
GoodsAction组件中角标提示`info`变形

### ISSUE THREAD

**Issue by lishihai** [youzan/vant-weapp#1268]
**描述一下问题**

GoodsAction组件中角标提示`info`变形，微信开发工具中显示正常，真机显示变形。

**截图**
![](http://d.u.pingcoo.com/img/20190131141255.png)

**环境**
 - 设备: 小米8
 - 基础库版本: 2.5.2
 - Vant Weapp 版本:0.5.2

**Comment by qinchi** [comment]
感觉是 van-icon 的问题，单独把van-icon拿出来写 当info是两位数时，van-icon就会拖长变形
环境
* 设备: iphone 8
* 基础库版本: 2.6.0
* Vant Weapp 版本:0.5.4

**Comment by heda20** [comment]
解决了吗？我的也是

- 设备: 小米8SE
-基础库版本: 2.6.2
-Vant Weapp 版本:0.5.7

**Comment by heda20** [comment]
![image](https://user-images.githubusercontent.com/30659608/54584401-35173d80-4a52-11e9-8fb5-29bc00aba2b1.png)
