### ISSUE TITLE
单选框选中item时无法触发函数，控制台显示组件没有触发事件对应的方法

### ISSUE THREAD

**Issue by weikairen** [youzan/vant-weapp#1279]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**描述一下问题**
参考文档后，新建了一个小程序，在使用输入框之类时没有问题，用到单选框是遇见触发函数找不到的错误

**截图**
如果是 UI 问题，请提供具体截图
![image](https://user-images.githubusercontent.com/16503739/52166302-7d022f80-2746-11e9-82f0-9089dfdd0add.png)

**环境**
 - 设备: 
 - 基础库版本: 2.0.4
 - Vant Weapp 版本:v0.5.2

**Comment by rex-zsd** [comment]
请提供一下代码

**Comment by weikairen** [comment]
> 请提供一下代码

https://github.com/weikairen/vant-test，请您看一下pages文件夹下面的forms

**Comment by rex-zsd** [comment]
js中未定义`onChange`方法呀？
