### ISSUE TITLE
van-collapse-item组件点击失效

### ISSUE THREAD

**Issue by hnty545** [youzan/vant-weapp#1281]
使用mpvue:1.0.18，git上下载vant-weapp最新版
van-collapse-item组件时点击失效无效，并没有打开折叠面板
看源码发现onClick事件没有改变自身状态，做如下修改

let newExpanded = !expanded;
      this.parent.switch(currentName, newExpanded);
      this.updateStyle(newExpanded);
      this.expanded = newExpanded;

这样能打开，但是无法点击收起来，我是初学者可能考虑不周到，麻烦作者看下做个比较完善的修复，谢谢！

**Comment by hnty545** [comment]
我发现是通过修改van-collapse的value，再做的子控件遍历的，这个逻辑没错，但是我目前点击无效，不知道怎么回事，我再看看

**Comment by rex-zsd** [comment]
文档针对的是小程序原生预发，使用其他框架的请参照框架文档，与vant-weapp无关。
