### ISSUE TITLE
van-field不支持双向绑定？

### ISSUE THREAD

**Issue by csabc** [youzan/vant-weapp#1289]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**描述一下问题**
    <van-field value="{{ username }}" label="姓名" placeholder="请输入姓名" clearable required />
我使用上面的方式绑定数据，输入姓名后，添加一个按钮点击console.log(this.data.username),
输出是空值。
**环境**
 - 设备: 开发环境和安卓8.0、微信7.0
 - 基础库版本: 2.5.2
 - Vant Weapp 版本:0.5.3

**Comment by fantasyni** [comment]
这个问题我也遇到了

**Comment by aoxiang594** [comment]
写了一大半，发现这个问题，不能双向绑定这有个P用啊，完全增加代码量

**Comment by rex-zsd** [comment]
@csabc 双向绑定是？

**Comment by mynameismaosheng** [comment]
目前的做法是有onChange事件的, 可以再onChange里修改当前model.

**Comment by rex-zsd** [comment]
如果指的是用mpvue框架然后用`v-model`做双向绑定，是不支持的。
原因是mpvue不支持小程序原生组件的双向绑定。
