### ISSUE TITLE
layout布局和checkbox group一起使用导致全选

### ISSUE THREAD

**Issue by beikezengyi** [youzan/vant-weapp#1290]
**描述一下问题**
在van-checkbox-group内使用van-row和van-col，导致checkbox-group内的change事件event.detail的值为空数组，如不使用van-row和van-col就能正常获得点击的van-checkbox的值，请问是使用方式不正确吗，请指教

**截图**
### wxml:
![image](https://user-images.githubusercontent.com/37478439/52543736-de7d6a80-2de6-11e9-93fc-7fbca88be3b7.png)
### js:
![image](https://user-images.githubusercontent.com/37478439/52543758-108ecc80-2de7-11e9-8c13-928a23c070bc.png)

**环境**
 - 设备: iphone5
 - 基础库版本: 2.5.2
 - Vant Weapp 版本:0.5.3

**Comment by rex-zsd** [comment]
`name`属性写错位置了。
