### ISSUE TITLE
希望实现无障碍访问

### ISSUE THREAD

**Issue by xcchcaptain** [youzan/vant-weapp#1291]
**希望实现官方无障碍访问能力**
目前即将开发针对视障用户的小程序，不知道当前的框架是否支持？
小程序官方文档参考`https://developers.weixin.qq.com/miniprogram/dev/component/aria-component.html`

**Comment by rex-zsd** [comment]
目前还没有对无障碍访问做优化
可以在这里写下你的需求，或者直接动手提pr
让我们一起把vant建设得更好 😃
