### ISSUE TITLE
NoticeBar在link 模式出现错误

### ISSUE THREAD

**Issue by zxz-googleman** [youzan/vant-weapp#1293]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**在使用NoticeBar示例第三种情况时出现错误提示**

在使用NoticeBar示例第三种情况时（即“link 模式，在右侧显示链接箭头”），出现下面的错误提示。请问怎么回事？
“VM2021:5 should have url attribute when using navigateTo, redirectTo or switchTab”
**截图**
![image](https://user-images.githubusercontent.com/14339771/52630177-82097080-2ef6-11e9-99ed-3b451d785050.png)

**环境**
 - 设备: MACOS High Sierra
 - 基础库版本: 2.5.2
 - Vant Weapp 版本:0.5.2

**Comment by rex-zsd** [comment]
link 模式需要传 `url`参数，文档漏写了。
下版本补上。

**Comment by zxz-googleman** [comment]
OK
