### ISSUE TITLE
field组件输入速度稍快会回退

### ISSUE THREAD

**Issue by tong233** [youzan/vant-weapp#1294]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**描述一下问题**
 这个问题在手机键盘上快速按退格键很明显。非常影响体验。
以前有人提过#1053

**截图**
```
onInput(event: Weapp.Event) {
      const { value = '' } = event.detail || {};

      this.set({
        value,
        showClear: this.getShowClear(value)
      }, () => {
        this.emitChange(value);
      });
    },
```
源码里this.emitChange(value);不应该写在回调里，写在外面就可以了。这里没有必要异步emit，不能保证最新的bindinput setData是最新的value。

**Comment by rex-zsd** [comment]
可以自己用debounce控制下set频率。
