### ISSUE TITLE
datetime-picker 返回为undefined

### ISSUE THREAD

**Issue by EasyChris** [youzan/vant-weapp#1299]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**描述一下问题**
描述一下你遇到的问题，包括复现方式、导致结果
https://youzan.github.io/vant-weapp/#/datetime-picker
按照官网的配置，配置完datetime-picker之后返回为undefined
**截图**
如果是 UI 问题，请提供具体截图

**环境**
 - 设备: 
 - 基础库版本: 
 - Vant Weapp 版本: 0.5.3

**Comment by rex-zsd** [comment]
请提供一下代码，包括wxml、js。
