### ISSUE TITLE
van-collapse嵌套van-collapse右侧图标显示不正确,内部的图标,在未展开时箭头应该朝下,现在一律朝上

### ISSUE THREAD

**Issue by zhangcx1994** [youzan/vant-weapp#1307]
<van-collapse v-model="activeNames">
      <van-collapse-item name="1">
        <div slot="title">有赞微商城<van-icon name="" /></div>
        <van-collapse
        

 v-model="active2"
          accordion>
          <van-collapse-item title="$t('title1')">$t('content1') </van-collapse-item>
          <van-collapse-item title="$t('title2')">$t('content2')</van-collapse-item>
          <van-collapse-item title="$t('title3')">$t('content3') </van-collapse-item>
        </van-collapse>
      </van-collapse-item>
    </van-collapse>
截图:
![qq 20190215162803](https://user-images.githubusercontent.com/31567668/52843914-61cbf280-313e-11e9-8301-86ae13a1bc0a.png)
收起来还是朝上
![qq](https://user-images.githubusercontent.com/31567668/52844417-7d83c880-313f-11e9-84e4-d8c4aa356612.png)

**Comment by rex-zsd** [comment]
贴下使用的代码？
