### ISSUE TITLE
dist错误

### ISSUE THREAD

**Issue by little-eight-china** [youzan/vant-weapp#1309]
无法启动项目，dist报错

模板如下：Cannot read property 'apply' of undefined
    at getRegExp
    at ./utils/dist/wxs/object.wxs

版本为最新

**Comment by rex-zsd** [comment]
看下你的引入方法是不是有问题

**Comment by Jialufeng** [comment]
遇到同样问题，object.wxs文件是在wxs 文件夹，没有改动
