### ISSUE TITLE
van-action-sheet带取消按钮时会有上下滚动条

### ISSUE THREAD

**Issue by lixize** [youzan/vant-weapp#1312]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**描述一下问题**
van-action-sheet带取消按钮的时候会有上下滚动条，官方demo中也有。

**截图**
![_20190215222407](https://user-images.githubusercontent.com/16396311/52862539-745f1f80-3170-11e9-91f3-79c450c2a308.png)

**环境**
 - 设备: 微信开发者工具
 - 基础库版本: v2.6.0
 - Vant Weapp 版本: 0.5.3

**Comment by chenjiahan** [comment]
感谢反馈，下个版本会修复
