### ISSUE TITLE
Tab组件不能设置背景颜色

### ISSUE THREAD

**Issue by fanhualei** [youzan/vant-weapp#1313]
**你需要的功能是？**
Tab组件可以设置背景颜色

**你期望 API 是什么样的？**
custom-class 中可以设置background: ，来改变现在的颜色，现在一直是白色背景。

[]
![tab](https://user-images.githubusercontent.com/34436863/52866394-87c2b880-3179-11e9-9264-05fa139bb185.png)
(url)

**Comment by XinjianQi** [comment]
同问如何修改tabs背景色，使用custom-class也改不了呢，都是白色的。

**Comment by KongValley** [comment]
官方给了api了啊
![tim 20190304164236](https://user-images.githubusercontent.com/30281453/53721759-f81e4900-3e9e-11e9-9093-0fb373a806bd.png)
直接用就行了
![image](https://user-images.githubusercontent.com/30281453/53721809-171cdb00-3e9f-11e9-99d5-6020542af7e5.png)

**Comment by rex-zsd** [comment]
下版本会增加外部样式类`nav-class`用于控制标签栏的样式。
