### ISSUE TITLE
toast组件无法使用 在mpvue2.0中

### ISSUE THREAD

**Issue by zengkaii** [youzan/vant-weapp#1314]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**toast组件无法使用 在mpvue2.0中**
使用时提示
未找到 van-toast 节点，请确认 selector 及 context 是否正确
**截图**
![image](https://user-images.githubusercontent.com/38418699/52895216-22f77480-31f2-11e9-99f5-08c054df1c7b.png)

页面中引入了组件
![image](https://user-images.githubusercontent.com/38418699/52895209-170bb280-31f2-11e9-9dc4-110be571ee2d.png)

打印toast 为null
![image](https://user-images.githubusercontent.com/38418699/52895200-065b3c80-31f2-11e9-8329-2ed1f8747e29.png)

是不是现在的mpvue 配置无法使用 selectComponent 这个api

**环境**
 - 设备: 微信开发者工具
 - 基础库版本: mpvue2.0 
 - Vant Weapp 版本:0.5.3

**Comment by rex-zsd** [comment]
默认selector是`van-toast`而不是`vant-toast`。

**Comment by zengkaii** [comment]
> 默认selector是`van-toast`而不是`vant-toast`。

已解决 粗心了谢谢
