### ISSUE TITLE
可以设置tree-select中选中的颜色，不是现在的红色

### ISSUE THREAD

**Issue by fanhualei** [youzan/vant-weapp#1315]
**你需要的功能是？**
可以设置tree-select中选中的颜色，不是现在的红色

**你期望 API 是什么样的？**
描述一下你期望的 API 形式
追加一个actionColor属性，来设置选中的颜色，现在默认是红色的，不通用，我还要到源代码中进行修改。下面是我修改的样子

![tree](https://user-images.githubusercontent.com/34436863/52914638-d7ce8600-3305-11e9-9907-7e78b3df6ebe.png)

**Comment by rex-zsd** [comment]
已经预留了外部样式类`main-active-class`来修改左侧选项激活态的样式。
示例
```
.tree-select-main-active {
    color: green !important;

    &::after {
      background-color: green !important;
    }
  }
```

**Comment by lbs2016** [comment]
如何修改选中后的左边的红色边框为绿色？

**Comment by lbs2016** [comment]
已实现我的想法：

在van-tree-select元素中增加：
main-active-class="tree_father" content-active-class="tree_father" 

wxss中设置为：

.tree_father {
  border-color: #1989fa !important;
  color: #1989fa !important;
}

即可实现左边竖条和文字均为蓝色。

红色再见！

**Comment by BenDavisClark** [comment]
左边分类可以加图标吗
