### ISSUE TITLE
Area 省市区选择 显示bug

### ISSUE THREAD

**Issue by sevend93** [youzan/vant-weapp#1318]
**描述一下问题**
Area 省市区选择  columns-num 设置为 2  value设置为 450100，按道理第一项应该是 广西壮族自治区，但是却显示的是 北京市。如果 columns-num 设置为3就行

**截图**
![image](https://user-images.githubusercontent.com/6322531/52925414-434b3e80-336c-11e9-93d7-842f38e0b196.png)

**环境**
 - 设备: 三星S8
 - 基础库版本: 2.1.0
 - Vant Weapp 版本: v0.5.3

**Comment by rex-zsd** [comment]
贴一下代码

**Comment by rex-zsd** [comment]
可复现，感谢反馈，将在下个版本修复。

**Comment by MulderLiu** [comment]
请问这个已经修复了吗？ 我在0.5.6中还是有这个问题

**Comment by rex-zsd** [comment]
确实有问题，之前并未修复。

**Comment by HADB** [comment]
@rex-zsd when will this be released?

**Comment by vanbolee** [comment]
0.5.18，当前问题还是存在。columns-num设置为2，value设置为市级code，此时省级没有发生变化。 @rex-zsd
