### ISSUE TITLE
功能使用疑问之传值是否支持data-xxx

### ISSUE THREAD

**Issue by olddoor** [youzan/vant-weapp#1320]
使用原生小程序开发的过程中一般可以通过data-XXX这种方式实现传值.
在使用vant-weapp的组建比如van-tabbar-item 
  <van-tabbar-item icon="home-o" title="/pages/index/index "data-url="/pages/index/index">首页</van-tabbar-item>
请问是否可以支持自定义传值. 比如上诉代码中的data-url
如不可, 那么在设计上预期是希望开发者自行在click事件中进行索引和url的对应?

**Comment by rex-zsd** [comment]
事件和参数在一个wxml节点上的，可以获取到。
不在一个节点上的，需要自行在js中做对应。

**Comment by olddoor** [comment]
<van-tabbar active="{{ active }}" bind:change="onChange">
  <van-tabbar-item icon="home-o" title="/pages/index/index "data-url="/pages/index/index">首页</van-tabbar-item>
  <van-tabbar-item icon="search" title="/pages/index/index" dot
  data-url="/pages/index/index"
  >标签</van-tabbar-item>
</van-tabbar>
比如上述的代码. 在onChange的形参中无法拿到title或者data-url的值啊.

**Comment by olddoor** [comment]
> 事件和参数在一个wxml节点上的，可以获取到。
> 不在一个节点上的，需要自行在js中做对应。

比如上述的代码. 在onChange的形参中无法拿到title或者data-url的值啊.
