### ISSUE TITLE
van-datetime-picker 使用当前时间，仅年生效

### ISSUE THREAD

**Issue by q7101488** [youzan/vant-weapp#1322]
**描述一下问题**
使用van-datetime-picker 控件，设置最小时间是当前时间，直接打开的时候不会生效，随意选择某一项之后，才会生效。

**截图**
![1](https://user-images.githubusercontent.com/9312733/52941561-17e44600-33a4-11e9-8003-b88e64324861.png)
![2](https://user-images.githubusercontent.com/9312733/52941558-17e44600-33a4-11e9-839d-17338503f16d.png)
![3](https://user-images.githubusercontent.com/9312733/52941582-229edb00-33a4-11e9-9fe8-0e48895f30c3.jpg)

**环境**
 - 设备: 模拟器、华为荣耀3
 - 基础库版本: 2.60
 - Vant Weapp 版本: v0.5.3

代码，用的mpvue：
<van-datetime-picker type="datetime" value="" :min-date="minDate" @change="onChange" />

data() {
			return {
				minDate: new Date().getTime()
			};
		},

**Comment by ppttfish** [comment]
兄弟你解决了吗？请教一下
