### ISSUE TITLE
navbar的leftarrow不出现

### ISSUE THREAD

**Issue by hnty545** [youzan/vant-weapp#1323]
有2个问题
1、navbar的leftarrow在刚进入的时候不出现，在小程序IDE上的wxml预览里找到na那个icon组件的class，双击他什么都不改回车，那个左箭头图标就出现了
2、class里的标签里class都有重复的，我查了相关内容，别人也遇到过，如果不影响使用就没关系。主要是第1点存在问题，图标不显示。
麻烦帮忙判断一下问题，谢谢！

![image](https://user-images.githubusercontent.com/6417805/52996001-2c354b00-3457-11e9-8078-0f13f4970a65.png)

**Comment by hnty545** [comment]
![image](https://user-images.githubusercontent.com/6417805/52997245-ed08f900-345a-11e9-95e4-3ea0708fe156.png)

**Comment by hnty545** [comment]
.ui-inner-nav-bar {
  background-color: #1989fa !important;
  color: #fff !important;
}

我发现是我加了这个样式以后，左箭头的颜色不会变，是蓝色和标题的颜色一样，没有看出来
请问我要修改左箭头为白色，应该怎么做呢

**Comment by rex-zsd** [comment]
目前从外部没办法修改

**Comment by hnty545** [comment]
我修改源码增加了个属性
