### ISSUE TITLE
van-tabs,显示异常

### ISSUE THREAD

**Issue by zhangkaicheng521** [youzan/vant-weapp#1326]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**描述一下问题**
描述一下你遇到的问题，包括复现方式、导致结果
我用的是吸附模式。初次进来，
（1.展示的数量大于一屏。van-tab不显示，只有滚动滚动条才会出现。 ）
（2.展示数量小于一屏，van-tab会出现在，展示card的下方）
（3.如果是吸顶后，点击其他tab标签，第一次的时候，会跳转到索引为0的tab标签）
**截图**
如果是 UI 问题，请提供具体截图

![Uploading image.png…]()
**环境**
 - 设备: 开发平台 、华为meta20安卓
 - 基础库版本: 2.5.2
 - Vant Weapp 版本:

**Comment by rex-zsd** [comment]
下版本会重构stiky部分的实现，之后可以看一下。

**Comment by zhengyu7664** [comment]
大大，您好，首先感谢提供的好用的ui库。
**描述一下问题**
van-tabs 添加吸顶后会出现 真机上第一个van-tab字体变大的现象（模拟器上和真机第一个后面的van-tab字体正常）
**截图**
加了吸顶效果前
![_20190223114702](https://user-images.githubusercontent.com/38236354/53281273-bc79d580-3760-11e9-8680-d058bd58cee0.png)

![_20190223112844](https://user-images.githubusercontent.com/38236354/53281249-6b69e180-3760-11e9-9895-6bf8eb6f454b.png)
分割线---------
加了吸顶效果后（真机上第一栏van-tab字体变大，第二栏van-tab正常）
第一栏van-tab字体
![_20190223114808](https://user-images.githubusercontent.com/38236354/53281285-e7fcc000-3760-11e9-992d-df8afdd42181.png)

第二栏van-tab字体
![_20190223115017](https://user-images.githubusercontent.com/38236354/53281307-272b1100-3761-11e9-96fe-0ba3e4f2571c.png)

ps：（开发模拟器上，均显示正常）


![_20190223113528](https://user-images.githubusercontent.com/38236354/53281253-70c72c00-3760-11e9-96c3-511b3d4c4720.png)

**环境**

* 设备: 开发平台 、IOS12.3
* 基础库版本: 2.6
* Vant Weapp 版本:V0.5.4

**Comment by rex-zsd** [comment]
tabs组件没有对字体做特殊处理，检查一下你的样式看看是不是做了什么处理。。。

**Comment by q215171650** [comment]
我也遇到了，开启animated属性，首个标签字体就变大了，你是怎么解决的。
