### ISSUE TITLE
有计划支持iphonex吗

### ISSUE THREAD

**Issue by hnty545** [youzan/vant-weapp#1327]
有计划支持iphonex吗？
类似notify、noticebar这样的控件，都存在iphonex的兼容问题

**Comment by hnty545** [comment]
是否可以增加iphonex的内部样式，由我们外部判断之后来选择是否上部留出距离

**Comment by rex-zsd** [comment]
底部安全距离已经支持了，顶部安全距离下版本可以支持一下。

**Comment by hnty545** [comment]
我在notify增加了个paddingTop属性解决问题
期待官方修改
