### ISSUE TITLE
tabs的底线如何去掉？

### ISSUE THREAD

**Issue by kroawen** [youzan/vant-weapp#1328]
如果我改变TABS整个的背景色，但是这个线的颜色还是不变
![image](https://user-images.githubusercontent.com/6927999/53073175-425c0d80-3522-11e9-88ec-b04c209942c5.png)

**Comment by tianxinll** [comment]
你的问题解决了吗？

**Comment by kroawen** [comment]
放弃了

**Comment by tianxinll** [comment]
有人回复我border设置成false  我试了，也不行
