### ISSUE TITLE
row的垂直居中有计划增加吗

### ISSUE THREAD

**Issue by hnty545** [youzan/vant-weapp#1329]
尝试了好久，没办法做到垂直居中，请问有计划或者办法吗

![image](https://user-images.githubusercontent.com/6417805/53082178-4b0b0e80-3537-11e9-8f92-9913eaaab859.png)

**Comment by hnty545** [comment]
是右侧箭头

**Comment by rex-zsd** [comment]
目前暂时没有，可以自己实现处理一下样式。

**Comment by laienliang** [comment]
怎么解决的呢？

**Comment by 316boss** [comment]
请问有解决方案了吗，custom-style设置垂直居中样式无效 @rex-zsd
