### ISSUE TITLE
Dialog点击穿透如何解决？

### ISSUE THREAD

**Issue by ldwonday** [youzan/vant-weapp#1330]
**描述一下问题**
对话框下面有一个teatarea组件，点击对话框，teatarea聚焦了，并且弹出键盘。
如图：
![wechatimg470](https://user-images.githubusercontent.com/4630157/53083189-5cedb100-3539-11e9-8e88-b314da04e160.jpeg)

**环境**
 - 设备:  iphone
 - 基础库版本: 
 - Vant Weapp 版本: 0.5.4

**Comment by rex-zsd** [comment]
没有办法，textarea是原生组件层级是最高的·无法覆盖。
