### ISSUE TITLE
iponeXS MAX 语言问题

### ISSUE THREAD

**Issue by Danielguang** [youzan/vant-weapp#1331]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**描述一下问题**
系统语言是日语的时候，小程序中的字体会变成乱码

**截图**
如果是 UI 问题，请提供具体截图
![img_0286](https://user-images.githubusercontent.com/10718395/53083867-a7236200-353a-11e9-88c5-ad9980fbd0f7.PNG)

**环境**
 - 设备: iphonexs max，系统语言日文
 - 基础库版本: 
 - Vant Weapp 版本:

**Comment by rex-zsd** [comment]
这个跟vant没关系，你代码写的中文文本在日文系统下展示不出来。

**Comment by Danielguang** [comment]
但是为什么其他的可以，只有button上面的中文字显示不出来

**Comment by Danielguang** [comment]
> 这个跟vant没关系，你代码写的中文文本在日文系统下展示不出来。

但是其他组件都可以，只有vant-button不行

**Comment by kniost** [comment]
同样遇到了该问题，其他组件都没问题，只有van-button不对
