### ISSUE TITLE
tabs如何设置背景颜色？滑动时如何去掉滚动条？

### ISSUE THREAD

**Issue by XinjianQi** [youzan/vant-weapp#1333]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**你需要的功能是？**
tabs设置背景颜色，滑动时可以去掉底部滚动条。

**你期望 API 是什么样的？**

如果这两个没有解决，这个控件就没意义了。

**Comment by rex-zsd** [comment]
已经有相同issue #1313
