### ISSUE TITLE
在小程序中使用<van-area area-list="{{ areaList }}" />组件,没数据展示

### ISSUE THREAD

**Issue by yeziWee** [youzan/vant-weapp#1334]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**描述一下问题**
在小程序中使用<van-area area-list="{{ areaList }}" />组件,没数据展示

**截图**

![image](https://user-images.githubusercontent.com/42226710/53155431-04c9b400-35f8-11e9-9767-13d18ea75ef2.png)
![image](https://user-images.githubusercontent.com/42226710/53155457-11e6a300-35f8-11e9-8e82-9208527e8f0d.png)
![image](https://user-images.githubusercontent.com/42226710/53155490-21fe8280-35f8-11e9-84ad-76289750774c.png)
控制台中输出data中的areaList
![image](https://user-images.githubusercontent.com/42226710/53155536-3b9fca00-35f8-11e9-8159-b9af4eadbea1.png)

**环境**
 - 设备: mac
 - 基础库版本: 
 - Vant Weapp 版本:

**Comment by rex-zsd** [comment]
使用的vant-weapp版本是?

**Comment by rex-zsd** [comment]
areaList.areaList?

**Comment by yeziWee** [comment]
解决了，没设置value所以没有数据出来。


| |
yezidokee
邮箱：yezidokee@163.com
|

Signature is customized by Netease Mail Master

在2019年02月21日 23:08，rex 写道：

areaList.areaList?

**Comment by yangchangming** [comment]
请问你用的是那个版本？我用的是0.5.8，有同样的问题，请问下你说的value没有设置 是什么意思？

**Comment by benjamingli** [comment]
> 请问你用的是那个版本？我用的是0.5.8，有同样的问题，请问下你说的value没有设置 是什么意思？

我也遇到了这个问题刚刚，跟你用的同一版本，请问你解决了吗？

**Comment by dingtwo** [comment]
> > 请问你用的是那个版本？我用的是0.5.8，有同样的问题，请问下你说的value没有设置 是什么意思？
> 
> 我也遇到了这个问题刚刚，跟你用的同一版本，请问你解决了吗？

降了一个版本(0.5.7)好了, 应该是当前这个版本有问题, 没时间看代码

**Comment by yangchangming** [comment]
> > 请问你用的是那个版本？我用的是0.5.8，有同样的问题，请问下你说的value没有设置 是什么意思？
> 
> 我也遇到了这个问题刚刚，跟你用的同一版本，请问你解决了吗？
我们没有解决，我放弃了！

**Comment by mizi23** [comment]
可以在areaList.js下面加入
module.exports = {
  areaList: areaList
}
就好了
从外部调用要用module.exports 导入

**Comment by leehave** [comment]
![image](https://user-images.githubusercontent.com/16717693/69713104-e83a4980-113e-11ea-9eb8-f0ae48b5bddc.png)
表示tong同样遇到的问题

**Comment by JakeLaoyu** [comment]
> ![image](https://user-images.githubusercontent.com/16717693/69713104-e83a4980-113e-11ea-9eb8-f0ae48b5bddc.png)
> 表示tong同样遇到的问题

areaList. areaList

**Comment by leehave** [comment]
![image](https://user-images.githubusercontent.com/16717693/69724668-55f26f80-1157-11ea-8b0f-63e66e2f6274.png)
![image](https://user-images.githubusercontent.com/16717693/69724686-5be85080-1157-11ea-90e6-3d8905c28828.png)
![image](https://user-images.githubusercontent.com/16717693/69724707-63a7f500-1157-11ea-832e-117eae8bf4e9.png)
![image](https://user-images.githubusercontent.com/16717693/69724719-6c003000-1157-11ea-8b97-6b696718a6c0.png)
van-weapp版本1.0.0-beta.4

**Comment by leehave** [comment]
我把组件单独新建一个项目出来是好的 但是在实际项目中他始终是出不来的
