### ISSUE TITLE
rate和icon无法显示图标

### ISSUE THREAD

**Issue by Jobin0821** [youzan/vant-weapp#1335]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**描述一下问题**
在引用了UI库之后,
调用van-icon和van-rate 均不能正常显示图标,显示一个小框框,
<van-icon name="chat" />等等吧 试验都不行.
我使用name=链接是可以显示图标的.
控件的功能是正常可用的,

**截图**
![image](https://user-images.githubusercontent.com/46119360/53155972-3d1dc200-35f9-11e9-8054-0ac049db31b4.png)

**环境**
 - 设备: windows 7
 - 基础库版本: 2.2.5 云开发版本
 - Vant Weapp 版本:0.5.4

当然我本地还安装了一个css的UI库 不知道是不是 有冲突.但是我测试了下其他的控件都是正常显示样式的.
引用库的介绍如下,他们没有评分我才另外找的库.
ColorUI
ColorUI是一个Css类的UI组件库！不是一个Js框架。相比于同类小程序组件库，ColorUI更注重于视觉交互！

其组件在美观性方面比较突出。

GitHub地址：https://github.com/weilanwl/ColorUI

**Comment by rex-zsd** [comment]
测试没复现，看截图`van-rate`是正常显示了，`<van-icon name="chat" />`没显示出来。
看下字体文件有没有加载进来，可能是冲突或者开发者工具的网络问题。

**Comment by Jobin0821** [comment]
已经解决了,确实是和原有字体文件冲突导致.
谢谢

**Comment by Smilefish2** [comment]
怎么解决的，碰到一样的问题

**Comment by Jobin0821** [comment]
> 怎么解决的，碰到一样的问题

就是把引用的另外一个图标库/字体库给删掉。

**Comment by Smilefish2** [comment]
我是这样解决了
```
/* 解决vant-icon冲突问题*/
[class*="van-icon-"] {
    font-family: "vant-icon" !important;
    font-size: inherit;
    font-style: normal;
}
```

**Comment by gitrocyang** [comment]
> 我是这样解决了
> 
> ```
> /* 解决vant-icon冲突问题*/
> [class*="van-icon-"] {
>     font-family: "vant-icon" !important;
>     font-size: inherit;
>     font-style: normal;
> }
> ```

加在哪个文件里了？我怎么试都无效……

**Comment by Smilefish2** [comment]
@gitrocyang 全局样式里，例如,app.wxss
