### ISSUE TITLE
微信小程序时间选择器回掉函数没有value值<van-datetime-picker type="date" value="{{ currentDate }}" min-date="{{ minDate }}" bind:change="onChange"/>

### ISSUE THREAD

**Issue by yeziWee** [youzan/vant-weapp#1337]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**描述一下问题**
wxml如下
![image](https://user-images.githubusercontent.com/42226710/53223359-0b196800-36ac-11e9-83da-e6a560c3a8f4.png)
js部分
![image](https://user-images.githubusercontent.com/42226710/53223387-284e3680-36ac-11e9-84c0-1c6e8803a0de.png)
![image](https://user-images.githubusercontent.com/42226710/53223398-313f0800-36ac-11e9-9c9b-4dc73eb470f5.png)
控制台中detail里面并没有value这个对象
![image](https://user-images.githubusercontent.com/42226710/53223427-49af2280-36ac-11e9-8c12-8c49e2881901.png)
所以点击选择会不停的报错误，无法设置值

**截图**
如果是 UI 问题，请提供具体截图

**环境**
 - 设备: mac
 - 基础库版本: 
 - Vant Weapp 版本:v0.5.4

**Comment by rex-zsd** [comment]
看文档，值只在input事件中返回，change事件只返回picker实例。

**Comment by zhouhuafei** [comment]
那就是文档示例有错。拷贝的示例。死活不行

**Comment by gaofei019** [comment]
event返回只有detail，没有value。文档有错误。直接通过event.detail获取日期的值
