### ISSUE TITLE
tab标题的点击事件bind：click和bind：change不能同时用

### ISSUE THREAD

**Issue by zengcheng2018** [youzan/vant-weapp#1339]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**你需要的功能是？**
描述一下你需要的功能，用于解决什么问题

**你期望 API 是什么样的？**
描述一下你期望的 API 形式

**Comment by rex-zsd** [comment]
没有复现你的问题，测试可以同时触发。
