### ISSUE TITLE
请教：如何加入组件单元测试？

### ISSUE THREAD

**Issue by Pasoul** [youzan/vant-weapp#1343]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**你需要的功能是？**
加入组件单元测试

**Comment by rex-zsd** [comment]
小程序本身支持[单元测试](https://developers.weixin.qq.com/miniprogram/dev/framework/custom-component/unit-test.html)。但是目前不支持 wxs、Behavior、外部样式类，基本处于不可用的状态。
