### ISSUE TITLE
cell right-icon点击面积过小

### ISSUE THREAD

**Issue by tong233** [youzan/vant-weapp#1348]
![image](https://user-images.githubusercontent.com/21073132/53457772-78dbe000-3a6e-11e9-92a3-b3943453d74c.png)

**你需要的功能是？**
在手机上难以准确点到，Field的icon也是这样，加padding也只有横向生效，纵向无效，因为icon是在cell-body里面的高度限制了。容纳icon的view应该像红框标出来那么大才合理，尝试icon:before给absolute top bottom负px也不行，可能要改布局才能办到。

**Comment by rex-zsd** [comment]
可以优化一下

**Comment by rex-zsd** [comment]
@tong233 是用的slot插入的iron？

**Comment by tong233** [comment]
@rex-zsd 上图是field的slot icon

**Comment by tong233** [comment]
cell的icon确实会撑开 。

**Comment by chenjiahan** [comment]
目前 Field 图标的点击区域是 36*24 像素，理论上够用了，布局不太好调整

如果你是插槽自行插入的图标，建议使用伪元素增加点击区域大小
