### ISSUE TITLE
van-picker 的setColumnValues 第二次set无效

### ISSUE THREAD

**Issue by 1eez** [youzan/vant-weapp#1349]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**描述一下问题**

我有一个van-radio，另外一个van-picker
van-picker初始值：XYZ
两个组件需要联动：点radio1的时候，picker里面显示123，点radio2的时候，picker里面显示ABC，再点radio1的时候，再变成123.

在radio click事件中。
通过：this.selectComponent("#picker").setColumnValues(1, this.data.column4[1].values)
第一次，成功从XYZ set成功了123
但是，再点radio2的时候，就没法set了，我在console抓var tempArr = this.selectComponent("#picker").getColumnValues(1)
显示picker已经是ABC了，但是界面上还是显示123.

我set之后，加了这句话getApp().picker = this.selectComponent("#picker")
也没用。

**截图**
无论在Mac编辑器，还是发到手机端预览，都是一样的效果。无法第二次set不同的值。

**环境**
 - 设备: Mac 10.14
 - 基础库版本: 2.5
 - Vant Weapp 版本: v0.5.5

**Comment by 1eez** [comment]
我set之后，加了这句话getApp().picker = this.selectComponent("#picker")
也没用。

**Comment by rex-zsd** [comment]
已回复，不要动态设置columns内的成员。
