### ISSUE TITLE
Collapse 通过setData改变data数据 但是视图不更新 也不报错 完全按照官网手风琴代码书写引入 点击无任何反应

### ISSUE THREAD

**Issue by MySun-Shine** [youzan/vant-weapp#1352]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**描述一下问题**
描述一下你遇到的问题，包括复现方式、导致结果

**截图**
如果是 UI 问题，请提供具体截图

**环境**
 - 设备: 
 - 基础库版本: 
 - Vant Weapp 版本:

**Comment by MySun-Shine** [comment]
Collapse 通过setData改变data数据 但是视图不更新 也不报错 完全按照官网手风琴代码书写引入 点击无任何反应

**Comment by rex-zsd** [comment]
提供一下代码

**Comment by MySun-Shine** [comment]
<view class='container'>
  <van-collapse value="{{ activeName }}" bindchange="activeChange" accordion>
    <van-collapse-item title="有赞微商城" name="1">
      提供多样店铺模板，快速搭建网上商城
    </van-collapse-item>
    <van-collapse-item title="有赞零售" name="2">
      网店吸粉获客、会员分层营销、一机多种收款，告别经营低效和客户流失
    </van-collapse-item>
    <van-collapse-item title="有赞美业" name="3">
      线上拓客，随时预约，贴心顺手的开单收银
    </van-collapse-item>
  </van-collapse>
</view>

js部分：
  data: {
    activeName: ''
  },
  activeChange: function(event) {
    console.log(event)
    console.log(this)
    this.setData({
      activeNames: event.detail
    });
    console.log(this.data.activeNames)
  },

**Comment by MySun-Shine** [comment]
![image](https://user-images.githubusercontent.com/27773374/53540133-4229c680-3b4f-11e9-8eb4-3b48b59d5cd1.png)

![image](https://user-images.githubusercontent.com/27773374/53540146-4bb32e80-3b4f-11e9-88c7-2fa95e4d2165.png)

**Comment by MySun-Shine** [comment]
已解决！文档跟官网还是有差距

**Comment by rex-zsd** [comment]
activeName要设置一下
