### ISSUE TITLE
部分iPhone机型出现白屏

### ISSUE THREAD

**Issue by rcyyou** [youzan/vant-weapp#1353]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**描述一下问题**
描述一下你遇到的问题，包括复现方式、导致结果
部分iPhone进入小程序首页白屏，只有导航和Tab栏，内容加载不出来。报Compontents引入路径错误。
**截图**
如果是 UI 问题，请提供具体截图
![image](https://user-images.githubusercontent.com/18318319/53545675-31844b00-3b65-11e9-9d44-9032fa0b4419.png)

**环境**
 - 设备: iPhone7
 - 基础库版本: 2.6.0
 - Vant Weapp 版本:v0.5.5

**Comment by rex-zsd** [comment]
贴下代码吧

**Comment by rcyyou** [comment]
> 贴下代码吧

![image](https://user-images.githubusercontent.com/18318319/53554948-e164b300-3b7b-11e9-87b7-a90e9d4bcd3f.png)
<van-search placeholder="请输入关键字" bind:search="bindSearch" />
  <van-row>
    <block wx:for="{{adRow}}" wx:key="{{item.id}}">
      <van-col custom-class="navi-list">
        <view class="navigate-wrap" bindtap="bindBanner" data-url="{{item.url}}">
          <image class="navigate-img" src="{{imageUrl}}{{item.pic}}"></image>
          <view class="navigate-title">{{item.title}}</view>
        </view>    
      </van-col>
    </block>  
  </van-row>

**Comment by rex-zsd** [comment]
可以删掉所有组件试试看，估计不是vant-weapp的问题。
