### ISSUE TITLE
Failed to load font https://img.yzcdn.cn/vant/vant-icon-956c55.woff2

### ISSUE THREAD

**Issue by cos800** [youzan/vant-weapp#1354]
**描述一下问题**
调试器 总是有一个错误信息
```
Failed to load font https://img.yzcdn.cn/vant/vant-icon-956c55.woff2
net::ERR_CACHE_MISS 
```
虽然对小程序没什么影响，但是看着难受。

**环境**
 - 设备: macos
 - 基础库版本: 2.4.4
 - Vant Weapp 版本: v0.5.6

**Comment by rex-zsd** [comment]
开发者工具的问题，字体文件没下载下来，真机上没有问题。

**Comment by XinjianQi** [comment]
真机上也不显示，如何解决？

**Comment by zhangshichuan** [comment]
@XinjianQi 同样的问题，难受。真机也不行。导致radio选择没有效果。

**Comment by nyaapass** [comment]
好像把 dist 复制进项目不会报错, npm 引入的话会

**Comment by zhangshichuan** [comment]
@nyaapass 我试试

**Comment by MARahman49** [comment]
any updates on this issue?

**Comment by good1uck** [comment]
@MARahman49 

> any updates on this issue?

It's a problem of the Developer Tool and won't affect the performance on a real mobile phone.(I am told too)

**Comment by MARahman49** [comment]
> @MARahman49
> 
> > any updates on this issue?
> 
> It's a problem of the Developer Tool and won't affect the performance on a real mobile phone.(I am told too)

so there is no way to fix that on local machine?

**Comment by good1uck** [comment]
@MARahman49 
Yea that's strange but only Weixin can fix that problem,  by updating their developer tool.

**Comment by MARahman49** [comment]
> @MARahman49
> Yea that's strange but only Weixin can fix that problem, by updating their developer tool.

any way to open an issue on weixin there

**Comment by good1uck** [comment]
@MARahman49 
Create a post on their community :
https://developers.weixin.qq.com/community/develop/question

**Comment by 1213William** [comment]
import dist show error

**Comment by Canees** [comment]
转成base64就行了

**Comment by fat-Tsai** [comment]
> 转成base64就行了

怎么转成base64 ,转完后放到项目文件夹下吗
