### ISSUE TITLE
toast.loading有几率导致跳转后的页面上覆盖一层遮罩导致不能点击

### ISSUE THREAD

**Issue by d0apga** [youzan/vant-weapp#1355]
**描述一下问题**
在网络请求时候使用
`showLoading(msg) {
	const toast = Toast.loading({
			duration: 0,
			forbidClick: true,
			message: msg || "请稍后..."
		});
	return toast;
}
hideLoading() {
	Toast.clear();
}
async processData(d) {
	showLoading("请稍后...");

	try {
		await doReq('api/save', d);
		Toast.success("已保存");
	} catch (e) {}

	hideLoading();
}
`
使用版本为74cb663c85f9bc5d825c81d168853acea990b0e9的提交，一切正常，这个版本后的所有提交都有几率出现问题

**截图**

**环境**
 - 设备: 米6
 - 基础库版本: 2.4.4
 - Vant Weapp 版本:0.5.6 [01da68bcf945019fdb03db9ca0beffaccd0a58b4]

**Comment by rex-zsd** [comment]
跳转后的页面的意思是调用`toast.loading`之后做了页面跳转？

**Comment by d0apga** [comment]
> 跳转后的页面的意思是调用`toast.loading`之后做了页面跳转？

是的，抱歉代码里面没写清楚，是先调用toast.loading, 然后跳转wx.navigateTo

**Comment by rex-zsd** [comment]
暂时复现不出来，toast显示依赖页面上的`<van-toast />`节点，按道理页面切换之后是不会存在的。

**Comment by funme** [comment]
![bug](https://user-images.githubusercontent.com/44284929/53718571-83dfa780-3e96-11e9-8506-f94b5cabf374.gif)

**Comment by rex-zsd** [comment]
跟 #1377 应该是同一个问题，下版本修复，可以关注一下那个 issue。
