### ISSUE TITLE
微信更新7.0.3后，steps步骤条组件出现bug

### ISSUE THREAD

**Issue by xander-personal** [youzan/vant-weapp#1356]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**描述一下问题**
使用步骤条组件的小程序页面（包括vant官方demo）首次进入页面没问题，返回后再次进入就会报错出现白屏

**截图**
![331551346827_ pic](https://user-images.githubusercontent.com/11306208/53557300-94371000-3b80-11e9-98d6-477b51ea52fc.jpg)

**环境**
 - 设备: ios或android，更新到微信7.0.3
 - 基础库版本: 2.6.1
 - Vant Weapp 版本: 0.5.6

**Comment by rex-zsd** [comment]
应该跟这个 #1336 是一样的原因，下版本会修复。
