### ISSUE TITLE
bug！MPVUE使用单选框模板，将van-radio嵌套在div中循环，此时点击图标切换时，有事件产生但无打勾效果，但点击后面的字就有。

### ISSUE THREAD

**Issue by villageheadlaoniuwang** [youzan/vant-weapp#1358]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**描述一下问题**
MPVUE使用单选框模板，将van-radio嵌套在div中循环，此时点击图标切换时，有事件产生但无打勾效果，但点击后面的字就有。
`<template>
<div class="page">
  <van-radio-group :value="radio" @change="onChange">
    <div v-for='item in [1,2,3]' :key='item'>
      <van-radio :name="item">单选框</van-radio>
    </div>
  </van-radio-group>
</div>
</template>
<script>
export default {
  config: {
    navigationBarTitleText: '测试'
  },
  data () {
    return {
      radio: 1
    }
  },
  methods: {
    onChange (e) {
      console.log('选择了第几项', e.mp.detail)
      this.radio = e.mp.detail
    }
  }
}
</script>
<style>
</style>`
**截图**
如果是 UI 问题，请提供具体截图
![image](https://user-images.githubusercontent.com/27476619/53609082-32b68600-3c00-11e9-9d13-7b78e6cd960b.png)

**环境**
 - 设备: 微信小程序开发工具V1.02.1902010
 - 基础库版本: 2.6.0
 - Vant Weapp 版本:V0.5.5

**Comment by villageheadlaoniuwang** [comment]
<template>
<div class="page">
  <van-radio-group :value="radio" @change="onChange">
    <div v-for='item in [1,2,3]' :key='item'>
      <van-radio :name="item">单选框</van-radio>
    </div>
  </van-radio-group>
</div>
</template>
<script>
export default {
  config: {
    navigationBarTitleText: '测试'
  },
  data () {
    return {
      radio: 1
    }
  },
  methods: {
    onChange (e) {
      console.log('选择了第几项', e.mp.detail)
      this.radio = e.mp.detail
    }
  }
}
</script>
<style>
</style>

**Comment by villageheadlaoniuwang** [comment]
看了vant-weapp源码，怀疑是radio中checked=""属性未生效，请确认

**Comment by villageheadlaoniuwang** [comment]
`<template>
<div class="page">
  <van-radio-group :value="radio" @change="onChange">
    <div v-for='item in [1,2,3]' :key='item'>
      <van-radio :name="item">单选框</van-radio>
    </div>
  </van-radio-group>
</div>
</template>
<script>
export default {
  config: {
    navigationBarTitleText: '测试'
  },
  data () {
    return {
      radio: 1
    }
  },
  methods: {
    onChange (e) {
      console.log('选择了第几项', e.mp.detail)
      this.radio = e.mp.detail
    }
  }
}
</script>
<style>
</style>
`

**Comment by rex-zsd** [comment]
提供一下代码？

**Comment by kapbook-caizhehao** [comment]
我也遇到类似问题，请问如何解决的。
