### ISSUE TITLE
dialog框高级用法的问题

### ISSUE THREAD

**Issue by urglyfish** [youzan/vant-weapp#1359]
我想说关于dialog 框   能不能自定义允许它关闭或展开   ，或者去掉转圈，场景问题（（用的before关闭前）点击提交按钮，弹出高级用法dialog框时，输入文字，按确认按钮，这样频繁操作，确认按钮一致转圈（用取消，确认分开事件，点击会自动关闭，无法达到按确认事件在当前dialog框展示toast提示））

**Comment by chenjiahan** [comment]
没看懂在说什么
