### ISSUE TITLE
好多组件都会有一个组件名-index的class 并且没有空格

### ISSUE THREAD

**Issue by DestinyHunter** [youzan/vant-weapp#1360]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**描述一下问题**
好多组件都会有一个组件名-index的class 并且没有空格

**截图**

![image](https://user-images.githubusercontent.com/20897838/53613179-3a7e2680-3c10-11e9-86f7-05a54792f725.png)

**环境**
 - 设备: win10 
 - 基础库版本: 2.6.1
 - Vant Weapp 版本: 0.5.5

**Comment by rex-zsd** [comment]
小程序内部加的前缀，有兴趣可以了解一下。

**Comment by DestinyHunter** [comment]
那我覆盖样式的时候 van-field 不生效

**Comment by DestinyHunter** [comment]
好多组件没有提供自定义class

**Comment by rex-zsd** [comment]
哪些组件？可以提出来

**Comment by DestinyHunter** [comment]
col  field dialog steps内容  checkbox-group Radio-group custom-class 无效

**Comment by DestinyHunter** [comment]
现在我需要自定义field 的样式.需要怎么做,只能修改组件吗
