### ISSUE TITLE
可不可以出一个不引入wxs文件的版本

### ISSUE THREAD

**Issue by pigzzz123** [youzan/vant-weapp#1361]
现阶段的小程序开发框架 貌似都不支持对wxs文件的解析

**Comment by suguoyao** [comment]
@pigzzz123 
你是否也出现小程序报错：ReferenceError:can't find _wxAppCode_
在ios11以下会出现这个情况

**Comment by pigzzz123** [comment]
> @pigzzz123
> 你是否也出现小程序报错：ReferenceError:can't find _wxAppCode_
> 在ios11以下会出现这个情况
没有啊，我是用一些小程序第三方框架的时候报错
