### ISSUE TITLE
引入miniprogram-api-typings导致找不到wx的定义？

### ISSUE THREAD

**Issue by Pasoul** [youzan/vant-weapp#1364]
**描述一下问题**
拉取最新的仓库代码，typescript编译报错“找不到名称wx”

**截图**
如果是 UI 问题，请提供具体截图
![image](https://user-images.githubusercontent.com/22902187/53624053-d96b4880-3c39-11e9-8361-7caca7d278b3.png)

**环境**
- Vant Weapp 版本: 0.5.6

**Comment by rex-zsd** [comment]
npm install一下？
