### ISSUE TITLE
Field组件

### ISSUE THREAD

**Issue by feelingsky** [youzan/vant-weapp#1365]
**描述一下问题**
Field组件  type="textarea"  定位层级过高  

**环境**
 - 设备: android
 - 基础库版本: 2.5.1
 - Vant Weapp 版本:0.5.3

**Comment by rex-zsd** [comment]
textarea组件是原生组件 层级是最高的 不受zindex的控制

**Comment by feelingsky** [comment]
![_20190301164919](https://user-images.githubusercontent.com/35163869/53627203-ce68e600-3c42-11e9-8b1e-2c5829f27c47.jpg)

打开Popup会出现层级太高       调用手机相册没有选择照片后  返回的时候也会出现层级高

其它页面也有用到原生textarea组件   不会出现调用相册后返回层级过高

**Comment by rex-zsd** [comment]
textarea里的placeholder层级更高

**Comment by feelingsky** [comment]
项目中没有写过有关placeholder的样式      希望可以修复一下

**Comment by rex-zsd** [comment]
这个没法修复= =
可以看下[小程序官方的说明](https://developers.weixin.qq.com/miniprogram/dev/component/native-component.html#%E5%8E%9F%E7%94%9F%E7%BB%84%E4%BB%B6%E7%9A%84%E4%BD%BF%E7%94%A8%E9%99%90%E5%88%B6)

**Comment by lite-J** [comment]
textarea 对齐方式不对，autosize高度计算不准确，要怎样修改呢

**Comment by hcw969376855** [comment]
安装手机设置了autosize 会出现闪屏
