### ISSUE TITLE
关于dialog，popup 事件绑定的一点建议

### ISSUE THREAD

**Issue by techGay** [youzan/vant-weapp#1366]
**你需要的功能是？**
看源码，dialog，popup组件中绑定点击事件的方式均为bind（包括蒙层的点击事件），这在一般情况下没有问题，但是当包含dialog的父组件也绑定了点击事件，就会导致点击dialog时也会触发父组件的事件，当然这样的场景很少或者可以调整dialog放置来解决。

我个人希望dialog，popup组件的点击事件绑定改为catch方式，因为dialog，popup等弹出组件绝大多数场景下就是要阻挡用户与下层进行交互，点击等事件不应传到父组件中而是进行拦截。

个人的一点愚见

**你期望 API 是什么样的？**
dialog ,popup等（包括蒙层点击事件） 弹出组件应拦截所有事件，即点击事件等绑定由bind改为catch

**Comment by rex-zsd** [comment]
可以在使用组件时自己catch一下tap事件。
```html
<van-popup
    show="{{ show }}"
    catchtap="noop"
    bind:close="onClose"
  >
    内容
  </van-popup>
```
