### ISSUE TITLE
Tab 自定义标签

### ISSUE THREAD

**Issue by MulderLiu** [youzan/vant-weapp#1368]
**你需要的功能是？**
我想使用 Tab 自定义标签，但我在使用说明中没有找到要如何实现。。，没有给出范例代码
https://youzan.github.io/vant-weapp/#/tab

**Comment by rex-zsd** [comment]
tab目前不支持像vant一样完全自定义，因为需要操作DOM，小程序上暂时实现不了。

**Comment by wangjiahan** [comment]
> tab目前不支持像vant一样完全自定义，因为需要操作DOM，小程序上暂时实现不了。

那为什么在demo中还有自定义的展示效果
