### ISSUE TITLE
van-popup 在基础库 2.6.1 下报渲染层错误

### ISSUE THREAD

**Issue by imyellow** [youzan/vant-weapp#1371]
点击更改 show 值时会报一个错误：

渲染层错误
`Error: Framework inner error (expect FLOW_APPLY_PROPERTY but get another)`

在其他版本的基础库内没有问题，是已经上线的项目，在更新微信为 7.0.3 之后出现该问题。

vant@0.5.6
mpvue@1.0.18

开始以为是 mpvue 的问题，升级至 mpvue 2.0.5 或 1.4.2 问题依旧，在更改开发工具基础库为 2.6.0 或之前的版本就没有问题，真机（微信7.0.3）调试问题依旧。

**Comment by tcl1215** [comment]
请问一下这是什么原因？我也碰到这个问题，在filed组件上写了控制弹窗的click事件，报错Error: Framework inner error (expect FLOW_APPLY_PROPERTY but get another)，
改为cell后问题解决

**Comment by imyellow** [comment]
> 请问一下这是什么原因？我也碰到这个问题，在filed组件上写了控制弹窗的click事件，报错Error: Framework inner error (expect FLOW_APPLY_PROPERTY but get another)，
> 改为cell后问题解决

记不太清楚了，是 content 还是 value 的值是 null 就报错了，应该是组件内没有判断处理 null 值，我在赋值前处理了一下 null 数据就可以了
