### ISSUE TITLE
tabs无法设置tab的百分比高度

### ISSUE THREAD

**Issue by a08515673** [youzan/vant-weapp#1372]
tabs的高度100%可以实现，tab的高度只能用确定值而不能用百分比来确定。

![tim 20190304180356](https://user-images.githubusercontent.com/34846246/53726741-96171100-3ea9-11e9-8c85-e0e72d2d8e62.png)

tab我想设为100%，充满屏幕

**环境**
 - 设备: iphone7
 - 基础库版本:2.x
 - Vant Weapp 版本: v 0.5.5

**Comment by rex-zsd** [comment]
可以使用js计算一下高度

**Comment by CHENDONGY** [comment]
@rex-zsd 在tab里面不能写样式,怎么在js里面进行绑定呢

**Comment by a08515673** [comment]
我是获取设备的高度，然后动态绑定到style里面，windowHeight是设备高度的全局变量
:style="'height:'+(windowHeight-70)+'px'"

**Comment by a08515673** [comment]
> @rex-zsd 在tab里面不能写样式,怎么在js里面进行绑定呢

我是获取设备的高度，然后动态绑定到style里面，windowHeight是设备高度的全局变量
:style="'height:'+(windowHeight-70)+'px'"

**Comment by CHENDONGY** [comment]
@a08515673 能提供动态绑定的xml和js代码吗? 感谢

**Comment by a08515673** [comment]
> @a08515673 能提供动态绑定的xml和js代码吗? 感谢
我用的是mpvue+vant-weapp框架。你参考下
页面：
  <div class="none-data-div" v-else  :style="'height:'+(windowHeight-70)+'px'"> </div>
vue：
data () {
    return {
      windowHeight:null
    }
  }
onLoad: function (options) {
    this.windowHeight = global.windowHeight;
  }

**Comment by a08515673** [comment]
> @a08515673 能提供动态绑定的xml和js代码吗? 感谢
![tim 20190307104749](https://user-images.githubusercontent.com/34846246/53928851-9809eb80-40c6-11e9-9c53-166f5c0c9cd1.png)

**Comment by CHENDONGY** [comment]
@a08515673 高度的问题解决了. 我这边又出现了一个新的问题.
```
<van-tabs swipeable sticky id='tabs' custom-class="customtabs" color="#5882d6" bind:change="onChange" bind:scroll="onScroll">
  <van-tab
    wx:for='{{["123","123"]}}'
    wx:key="index"
    title='{{item}}'
    title-style="font-size: 17px;"
  >

```
我查看文档说 设置color是改变被选中的tab的颜色. 现在我这么设置改变的颜色是tab下面线条的颜色,而字体颜色并没有改变. 上面你的截图被选中的文字和线条是一致的.

**Comment by rex-zsd** [comment]
@CHENDONGY 修改的的确是线条的颜色而不是自提的颜色，这部分应该是文档有误。

**Comment by CHENDONGY** [comment]
@rex-zsd 如果我要保持选中的颜色和线条的颜色一致,当前版本是没有没有办法设置的吗?

**Comment by rex-zsd** [comment]
@CHENDONGY `0.5.7` 已新增外部样式类 `nav-class`、`tab-class`、`tab-active-class` 分别用于控制标签栏样式、标签样式、激活标签样式。

**Comment by Zq986928835** [comment]
![image](https://user-images.githubusercontent.com/20550145/198496296-7d15754f-8fb2-4612-9dc2-b615662220ad.png)
我也遇到了这么个问题，不生效是因为你的父级不是100%；js的方法始终无法让我舒服，可以尝试像我这样子，通过css让tab组件到你的内容中间，每一层的高度都设置为100%即可，这是我的代码可以参考下
