### ISSUE TITLE
example 微信开发者工具中，无法运行

### ISSUE THREAD

**Issue by MulderLiu** [youzan/vant-weapp#1373]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**描述一下问题**
git 下来最新版 

npm install
npm run dev 
也执行了，网页可以跑起来
但是使用微信开发者工具报错

**截图**
如果是 UI 问题，请提供具体截图

**环境**
 - 设备: windows10
 - 基础库版本: 
 - Vant Weapp 版本:

**Comment by MulderLiu** [comment]
![20190304215326](https://user-images.githubusercontent.com/11418478/53737823-8ce96c80-3ec8-11e9-8da0-17a742da0c98.png)

**Comment by rex-zsd** [comment]
检查一下代码引入、开发者工具等有没有问题？

**Comment by 841464118** [comment]
你全局查找这个引用，然后把这个引用删掉。我暂时是这么解决的
