### ISSUE TITLE
Area 省市区选择 

### ISSUE THREAD

**Issue by MulderLiu** [youzan/vant-weapp#1374]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**描述一下问题**
看有人提过了 不过我在0.5.6 中发现还是有这问题

https://github.com/youzan/vant-weapp/issues/1318#issue-411282299

**截图**
如果是 UI 问题，请提供具体截图

**环境**
 - 设备: win 10
 - 基础库版本: 
 - Vant Weapp 版本:0.5.6

**Comment by rex-zsd** [comment]
确实有问题，可以继续关注一下那个issue。
