### ISSUE TITLE
添加搜索组件高级用法的示例

### ISSUE THREAD

**Issue by thinkmoon** [youzan/vant-weapp#1375]
**添加搜索组件高级用法的示例**
![image](https://user-images.githubusercontent.com/28600813/53779047-c3130480-3f39-11e9-9cd6-8e83f403072f.png)

项目需要一个如文档中搜索组件高级用法的需求。但是一直做不到文档中的效果。希望可以在example中添加相关示例。

**Comment by rex-zsd** [comment]
vant-weapp与vant文档共享同一份示例，vant-weapp暂时还未支持这个特性。
