### ISSUE TITLE
field组件输入的内容异常清空

### ISSUE THREAD

**Issue by Ti-tanium** [youzan/vant-weapp#1378]
**描述一下问题**
情况：
UI上总共有3个field和一个switch一个picker（微信自带picker）
switch和picker都绑定了change方法
field也都绑定了change方法
问题：
在事先输入了field以后，再去改变picker或者switch，field的内容被清空了。

**环境**
 - 设备: web微信小程序开发工具、Android手机
 - 基础库版本: 2.6.1
 - Vant Weapp 版本:最新版本（刚下的field）

**Comment by rex-zsd** [comment]
查看下代码，vant并不具有这样的能力。

**Comment by Ti-tanium** [comment]
vant 不具这个能力，但是vant放在vue里面就有了。。。我试了一下，原生确实没问题，好像和vue的数据绑定有关系

**Comment by rex-zsd** [comment]
贴代码

**Comment by Ti-tanium** [comment]
简化过的代码：

<template>
  <div class="setting-container">
    <van-field
      :value="QQId"
      name="QQId"
      label="QQ:"
      required
      type="number"
      placeholder="请输入QQ号"
      :error-message="QQErrorMessage"
      @confirm="onQQConfirm"
    />
    <picker @change="MajorPickerChange" :value="index" :range="majorArray">
      <van-field :value="major" label="专业:" name="major" placeholder="请选择专业类别" disabled/>
    </picker>
  </div>
</template>

<script>
export default {
  data() {
    return {
      major: "",
      QQErrorMessage: "",
      QQId: "",
      majorArray: ["哲学类", "经济学类", "财政学类", "金融学类", "设计学类"],
      index: ""
    };
  },
  methods: {
    onQQConfirm(event) {
      const QQ = event.mp.detail;
      if (!numberValidate(QQ)) {
        this.QQErrorMessage = "请输入正确QQ号";
      } else {
        this.QQErrorMessage = "";
      }
    },
    numberValidate(obj) {
      var reg = /^[0-9|.]*$/;
      return reg.test(obj);
    },
    MajorPickerChange(e) {
      this.index = e.target.value;
      console.log(e);
      this.major = this.majorArray[this.index];
    }
  }
};
</script>

<style>
</style>

**Comment by Ti-tanium** [comment]
由于文字代码不知道怎么弄高亮，所以用的截图：
![image](https://user-images.githubusercontent.com/23275363/53808284-cf747d00-3f8c-11e9-8b4c-72d70e6895d1.png)
![image](https://user-images.githubusercontent.com/23275363/53808318-dc916c00-3f8c-11e9-9c03-a42281fc3732.png)
