### ISSUE TITLE
mpvue中使用picker组件，配置defaultIndex无效

### ISSUE THREAD

**Issue by leo0828** [youzan/vant-weapp#1379]
**描述一下问题**
在mpvue中使用picker组件，配置defaultIndex无效，默认index依然为0
```
 <van-picker show-toolbar title="test" :columns="test" />

```
```
data(){
    return {
        test: [{
            values:[1,2,3,4,5],
            defaultIndex: 1
        }]
    }
}
```

**截图**
如果是 UI 问题，请提供具体截图

**环境**
 - 设备: macOS 10.12
 - mpvue版本: @1.4.2
 - Vant Weapp 版本:@0.5.6

**Comment by Hack-DJ** [comment]
微信小程序原生开发中defaultIndex也是无效

**Comment by Hack-DJ** [comment]
> **描述一下问题**
> 在mpvue中使用picker组件，配置defaultIndex无效，默认index依然为0
> 
> ```
>  <van-picker show-toolbar title="test" :columns="test" />
> ```
> ```
> data(){
>     return {
>         test: [{
>             values:[1,2,3,4,5],
>             defaultIndex: 1
>         }]
>     }
> }
> ```
> **截图**
> 如果是 UI 问题，请提供具体截图
> 
> **环境**
> 
> * 设备: macOS 10.12
> * mpvue版本: @1.4.2
> * Vant Weapp 版本:@0.5.6

问题找到了   picker-column 生命周期改一下，我把beforeCreate改成了created就OK了

**Comment by rex-zsd** [comment]
defaultIndex的确有问题，感谢反馈 👍

**Comment by leo0828** [comment]
> defaultIndex的确有问题，感谢反馈 👍

如果bug修复了请告知我一声，谢谢:)

**Comment by alive2011** [comment]
微信小程序版本, 现在同步设置是没有问题的,，但是异步设置,依然会设置不上。如下：
```javascript
    let c = [
      { id: 1, name: "北京"},
      { id: 2,  name: "天津"},
      {id: 3, name: "上海"}
    ]

    let column1 = [{}]
    setTimeout(() => {
      column1[0].values = c
      column1[0].className = 'column1'
      column1[0].defaultIndex = 2
      this.setData({
        column1: column1
      })
    }, 3000)
```
如果是直接同步设置是没问题的，像这样
```javascript
    let column1 = [{}]
    column1[0].values = c
    column1[0].className = 'column1'
    column1[0].defaultIndex = 2
    this.setData({
      column1: column1
    })
```
