### ISSUE TITLE
swipe-cell在真机上左右滑动时，页面也会上下滚动

### ISSUE THREAD

**Issue by shuimupj** [youzan/vant-weapp#1380]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**描述一下问题**
swipe-cell在真机上左右滑动时，页面也会上下滚动；除非手指的绝对水平滑动，才能保证页面不会上下滚动，这个如何解决？

**截图**
![_20190305233808](https://user-images.githubusercontent.com/20787055/53817130-c80a9f00-3f9f-11e9-8dd6-434f132f98ec.jpg)

**环境**
 - 设备: ios 10.2.1
 - 基础库版本: 2.6.0
 - Vant Weapp 版本: v0.5.5

**Comment by Tim1023** [comment]
如果页面swipe-cell 占主体，现在页面也无法滚动了

**Comment by BadReese** [comment]
如果一个列表同时可以左滑删除跟竖直滚动，那会有很大的情况无法正常响应竖直滑动的手势。
