### ISSUE TITLE
h5版的vant有sku，小程序的却没有，以后会出嘛？

### ISSUE THREAD

**Issue by ULQUIARROSYX** [youzan/vant-weapp#1381]
之前用vant的sku组件搭过一个项目，很方便。现在想转到小程序，却发现小程序版根本没有这个组件了。。。。。

**Comment by rex-zsd** [comment]
近期不会，后续会把业务组件也完善起来，可以关注一下roadmap。

**Comment by bolechen** [comment]
> 之前用vant的sku组件搭过一个项目，很方便。现在想转到小程序，却发现小程序版根本没有这个组件了。。。。。

楼主解决这个 Sku 组件的问题了吗？能不能分享下
