### ISSUE TITLE
van-button 使用custom-class自定义样式无效，不能覆盖，即使使用!important 也没有效果

### ISSUE THREAD

**Issue by GitACDreamer** [youzan/vant-weapp#1384]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**描述一下问题**
van-button 使用custom-class自定义样式无效，不能覆盖，即使使用!important 也没有效果

**截图**
试了各种办法，发现高度、宽度、等一些样式都更改不了
![image](https://user-images.githubusercontent.com/19402747/53852568-709b1c00-3ffd-11e9-936e-212c0a9d98cb.png)
控件
```<van-button custom-class="paramter-btn"></van-button>```
样式设置
```
.parameter-btn {
  width: 65px !important;
  height: 40px !important;
}
```
**环境**
 - 设备: 
微信开发者工具
 - 基础库版本:  
 2.6.1
 - Vant Weapp 版本:
v0.5.5

**Comment by GitACDreamer** [comment]
另外补充一点，就是我把`van-search`控件的样式修改是生效了的

**Comment by rex-zsd** [comment]
![image](https://user-images.githubusercontent.com/8767877/53937775-1a0b0c00-40e9-11e9-875e-e46d1bde3ee9.png)
测试没有问题

**Comment by GitACDreamer** [comment]
我是在```<style lang="less scoped>``` 添加 `scoped` 就发现没有效果了，找到原因了，谢谢

**Comment by chenPei0413** [comment]
是什么原因啊

**Comment by towry** [comment]
我的是使用了 tarojs 框架，然后在写模板的时候，应该用驼峰写法的。

下面是错误的用法 ❌：

```jsx
<van-button custom-class="myclass">click</van-button>
```

下面是正确的用法 ✅：

```jsx
<van-button customClass="myclass">click</van-button>
```

同时记得给样式加 `important`。

**Comment by Windancer** [comment]
> 我的是使用了 **tarojs 框架**，写模板的时候，应该用驼峰写法的。
> 
> 下面是错误的用法 ❌：
> 
> ```js
> <van-button custom-class="myclass">click</van-button>
> ```
> 
> 下面是正确的用法 ✅：
> 
> ```js
> <van-button customClass="myclass">click</van-button>
> ```
> 
> 同时记得给样式加 `important`。
加 important就好了

**Comment by b-ss** [comment]
这个外部样式类，只能用在微信小程序开发吗？在web网页上，怎么写都不生效啊？
