### ISSUE TITLE
navbar图标不居中

### ISSUE THREAD

**Issue by fingertap** [youzan/vant-weapp#1385]
`van-nav-bar`用`slot`插入的图标并不能居中对齐，在index.wxss中修改`.van-nav-bar__left`或者`.van-nav-bar__right`，加入`vertical-align: middle;`无效。

![image](https://user-images.githubusercontent.com/7274689/53859075-7aca1400-4017-11e9-8343-e4e4bfe05537.png)

在开发者工具中审查元素：

![image](https://user-images.githubusercontent.com/7274689/53860130-f7122680-401a-11e9-8496-e26aa562821d.png)

**Comment by fingertap** [comment]
在`<van-icon>`下的`view`标签中添加`top: 10rpx`看起来像是居中了。我翻看了`van-nav-bar`和`van-icon`的css，由于项目实在太多我没仔细看，不清楚这里的布局是出了什么问题。

**Comment by rex-zsd** [comment]
插入slot请自行控制样式。小程序自定义组件机制是shadow-dom，vertical-align为什么不生效请参考相关知识点。
