### ISSUE TITLE
Search 组件 this.set is not a function

### ISSUE THREAD

**Issue by Ti-tanium** [youzan/vant-weapp#1387]
**描述一下问题**
使用search组件输入的时候出现this.set is not a function
使用了mpvue框架

**截图**
![image](https://user-images.githubusercontent.com/23275363/53868676-8296b200-4031-11e9-8808-efd8779901c9.png)

**环境**
 - 设备: web微信小程序开发工具
 - 基础库版本: 2.6.1
 - Vant Weapp 版本:最新版

**Comment by rex-zsd** [comment]
检查下是不是引入的有问题。
