### ISSUE TITLE
van-tabs 如何固定在顶部？

### ISSUE THREAD

**Issue by umeitime** [youzan/vant-weapp#1388]
van-tabs 如何固定在顶部？
这个在小程序里面加了
`.van-tabs__wrap {
  position: fixed !important;
}`
可以实现。
但是在web端vue项目里面却没有任何效果。

**Comment by dxbo** [comment]
修改tabs\index.wxml
<view class="van-tabs van-tabs--{{ type }}">
  <view style="z-index: {{ zIndex }}; {{ wrapStyle }}" class="van-tabs__wrap {{ scrollable ? 'van-tabs__wrap--scrollable' : '' }} {{ type === 'line' && border ? 'van-hairline--top-bottom' : '' }} custom-class">
把custom-class改到后面来，然后传入一个自定义样式就可以了
