### ISSUE TITLE
https://youzan.github.io/vant-weapp/#/picker文档中 多联互动 代码错误

### ISSUE THREAD

**Issue by Forrest554** [youzan/vant-weapp#1389]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**描述一下问题**
文档多联互动的实例代码为 picker.setColumnValues(1, citys[values[0]]);
应改为picker.setColumnValues(1, citys[value[0]]);

**截图**
如果是 UI 问题，请提供具体截图

**环境**
 - 设备: macbook air
 - 基础库版本: 2.6.1
 - Vant Weapp 版本:0.5.6

**Comment by rex-zsd** [comment]
感谢反馈 👍
