### ISSUE TITLE
van-icon的name为图片路径时，van-info的层级显示有问题

### ISSUE THREAD

**Issue by shuimupj** [youzan/vant-weapp#1393]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**描述一下问题**
因为小程序不支持svg图标，同时iconfont（阿里矢量图标）会将彩色图标统一转化为纯色的图标字体，所以项目中难免会遇到使用图片图标的情况。
当van-icon使用图片作为name的参数，同时使用了info属性，会出现图片遮住ban-info的情况；原因是两者都使用了position:absolute;且都没有设置z-index导致的。
如果继续不设置两者的z-index值，建议调整van-info和image的上下顺序。

**截图**
这是未调整的截图：
![微信截图_20190309222612](https://user-images.githubusercontent.com/20787055/54072862-758cf380-42bb-11e9-9a63-9de77399f3ae.png)
以下是调整之后的截图：
![微信截图_20190309222716](https://user-images.githubusercontent.com/20787055/54072872-8ccbe100-42bb-11e9-9564-39421a78a875.png)

**Comment by rex-zsd** [comment]
感谢反馈，将在下版本修复 👍
