### ISSUE TITLE
<van-button>标签内无法正常嵌套<text>

### ISSUE THREAD

**Issue by fyy99** [youzan/vant-weapp#1395]
**问题描述**
`<van-button>`标签内无法正常嵌套`<text>`

**环境**
 - 设备: 微信开发者工具、iOS11
 - 基础库版本: 2.6.1
 - Vant Weapp 版本: 20190310

**Comment by rex-zsd** [comment]
请详细描述一下问题并提供代码，不然没有办法帮你解决问题
