### ISSUE TITLE
van-slider滑动块时报 TypeError: Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by zengzhichao** [youzan/vant-weapp#1398]
**描述一下问题**
描述一下你遇到的问题，包括复现方式、导致结果
0.5.3版本点击滑动条就会出现

**环境**
 - 设备:  mac 微信开发者工具最新1.02.1902010
 - 基础库版本: 2.6.1
 - Vant Weapp 版本:0.5.3

**Comment by rex-zsd** [comment]
slider组件内部没有调用split方法，应该不是vant的问题。
