### ISSUE TITLE
DatetimePicker时间选择器

### ISSUE THREAD

**Issue by trj-web124** [youzan/vant-weapp#1399]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**描述一下问题**
wepy搭建框架引入vant-weapp  使用DatetimePicker组件无法获取vlaue值
![image](https://user-images.githubusercontent.com/32631462/54107524-5fdf1180-4414-11e9-8cdc-1a23c3fb3a73.png)

**截图**
如果是 UI 问题，请提供具体截图

**环境**
 - 设备: Ios
 - 基础库版本: 
 - Vant Weapp 版本: "vant-weapp": "^0.5.6",

**Comment by trj-web124** [comment]
![image](https://user-images.githubusercontent.com/32631462/54107616-a2a0e980-4414-11e9-937d-ffd8f8989f30.png)
![image](https://user-images.githubusercontent.com/32631462/54107623-a7fe3400-4414-11e9-95ee-fd61874962b1.png)
此处为undefined 
![image](https://user-images.githubusercontent.com/32631462/54107662-c19f7b80-4414-11e9-8fc5-da1842d9a852.png)
我设置一个最大max-date为今天  就报此类错误info

**Comment by 15260749922** [comment]
你这个问题解决了吗？我也遇到event.detail.value undefine的

**Comment by mrseanchow** [comment]
这个组件 需要再写一些方法赋值，我先分享下我写的代码吧。
![image](https://user-images.githubusercontent.com/4811211/55542070-deb82900-56f8-11e9-9fc3-0a6b3c24013f.png)


```js
Page({
  data: {
    showDatetimePickerBox: false,
    minDate: new Date(2018, 1, 1).getTime(),
    maxDate: new Date(2050, 1, 1).getTime(),
    currentDate: new Date().getTime(),
  },
  onShowPopBox: function(e) {
    const {
      key
    } = e.target.dataset;
    this.setData({
      [key]: true
    });

  },
  onHidePopBox: function(e) {
    const {
      key
    } = e.target.dataset;
    this.setData({
      [key]: false
    });
  },
  onCloseDatetimePickerBox: function(e) {
    const {
      key
    } = e.target.dataset;
    const {
      name
    } = e.target.dataset;
    this.setData({
      [name]: this.formatDate(new Date(e.detail)),
      [key]: false
    });

  },
  formatDate: function(date) {
    var year = date.getFullYear()
    var month = date.getMonth() + 1
    var day = date.getDate()
    return [year, month, day].map(this.formatNumber).join('-')
  },
  formatNumber: function(n) {
    n = n.toString()
    return n[1] ? n : '0' + n
  }

});

```

```wxml

 <van-field  data-name="se_day" label="日期" placeholder="请选择日期" value="{{ se_day }}" data-key="popbox_se_day" bind:focus="onShowPopBox" />
<van-popup show="{{popbox_se_day}}" position="bottom">
  <van-datetime-picker type="date" data-name="se_day" data-key="popbox_se_day" value="{{ currentDate }}" min-date="{{ minDate }}" bind:confirm="onCloseDatetimePickerBox" bind:cancel="onHidePopBox" />
</van-popup>

```

**Comment by dreamHeroK** [comment]
我也有同样的问题。
```
    <van-popup :show="showDatePicker" position="bottom" @close="onShowDatePickerCancel">
      <van-datetime-picker type="date" :value="date" @cancle="onShowDatePickerCancel" @confirm="onConfirmDate" :max-date="maxDate" :min-data="minDate" />
    </van-popup>
    onConfirmDate(e) {
      console.log(e, 'e')
    }
```
没设置最大时间会报`VM25193:5 Error: Framework inner error (expect FLOW_APPLY_PROPERTY but get another)`的错误
设置最大时间会报`VM25588:1 thirdScriptError
Invalid array length; [Component] Property Observer Error @ vant-weapp/dist/datetime-picker/index#updateColumns
RangeError: Invalid array length`
`VM25719:5 Error: Expect END descriptor with depth 0 but get another`
然后无论是input时间还是confirm事件，都没有detail属性返回

![image](https://user-images.githubusercontent.com/23441508/56478513-8e0b4300-64e2-11e9-9568-dc39de4eda37.png)

**Comment by rex-zsd** [comment]
@dreamHeroK 你用了mpvue，原生事件的返回会被包装到mp里面，注意一下。

**Comment by dreamHeroK** [comment]
> 了mpvue，原生事件的返回会被包装到mp里面，注意一下。

嗯。我直接项目根目录导入小程序无问题了。之前是导入的dist文件夹。不懂为何会出现。

**Comment by Lan-megumi** [comment]
> 这个组件 需要再写一些方法赋值，我先分享下我写的代码吧。
> ![image](https://user-images.githubusercontent.com/4811211/55542070-deb82900-56f8-11e9-9fc3-0a6b3c24013f.png)
> 
> ```js
> Page({
>   data: {
>     showDatetimePickerBox: false,
>     minDate: new Date(2018, 1, 1).getTime(),
>     maxDate: new Date(2050, 1, 1).getTime(),
>     currentDate: new Date().getTime(),
>   },
>   onShowPopBox: function(e) {
>     const {
>       key
>     } = e.target.dataset;
>     this.setData({
>       [key]: true
>     });
> 
>   },
>   onHidePopBox: function(e) {
>     const {
>       key
>     } = e.target.dataset;
>     this.setData({
>       [key]: false
>     });
>   },
>   onCloseDatetimePickerBox: function(e) {
>     const {
>       key
>     } = e.target.dataset;
>     const {
>       name
>     } = e.target.dataset;
>     this.setData({
>       [name]: this.formatDate(new Date(e.detail)),
>       [key]: false
>     });
> 
>   },
>   formatDate: function(date) {
>     var year = date.getFullYear()
>     var month = date.getMonth() + 1
>     var day = date.getDate()
>     return [year, month, day].map(this.formatNumber).join('-')
>   },
>   formatNumber: function(n) {
>     n = n.toString()
>     return n[1] ? n : '0' + n
>   }
> 
> });
> ```
> 
> ```
> 
>  <van-field  data-name="se_day" label="日期" placeholder="请选择日期" value="{{ se_day }}" data-key="popbox_se_day" bind:focus="onShowPopBox" />
> <van-popup show="{{popbox_se_day}}" position="bottom">
>   <van-datetime-picker type="date" data-name="se_day" data-key="popbox_se_day" value="{{ currentDate }}" min-date="{{ minDate }}" bind:confirm="onCloseDatetimePickerBox" bind:cancel="onHidePopBox" />
> </van-popup>
> ```

多谢老哥，萌新程序员一直不知道传回来的那一串数字是什么意思.....
