### ISSUE TITLE
希望cell组件新增value的slot插槽

### ISSUE THREAD

**Issue by zenonux** [youzan/vant-weapp#1400]
**你需要的功能是？**
希望cell组件新增value的slot插槽,用于处理value值不是文字而是头像图片的情况

**你期望 API 是什么样的？**
`<van-cell title="头像" is-link>
<view slot="value">
    <image mode="widthFix" src="avatar.png" />
  </view>
</van-cell>
`

**Comment by rex-zsd** [comment]
已有的功能，请仔细看文档。

**Comment by jimixy** [comment]
<van-cell>
            <view slot="icon">
                <text>icon</text>
            </view>
            <view slot="title">
                <text>title</text>
            </view>
            <view slot="-">
                <text>value</text>
            </view>
            <view slot="right-icon">
                <text>right-icon</text>
            </view>
        </van-cell>

这样使用value没有出现，是什么原因；

**Comment by rex-zsd** [comment]
![image](https://user-images.githubusercontent.com/8767877/54252622-7efdb080-4586-11e9-827e-d181fbe074a3.png)

**Comment by YarenTang** [comment]
> `<van-cell> <view slot="icon"> <text>icon</text> </view> <view slot="-"> <text>value</text> </view> </van-cell>`
> 
> 这样使用value没有出现，是什么原因，麻烦帮忙看一下；

value 对应默认 slot，去掉 `slot="-"` 即可。
