### ISSUE TITLE
希望field组件的背景色可以修改

### ISSUE THREAD

**Issue by zenonux** [youzan/vant-weapp#1401]
**你需要的功能是？**
希望field组件的背景色可以修改，目前是用cell组件包裹的，颜色为固定白色

**你期望 API 是什么样的？**
`  <van-field
    value="{{ value }}"
    background="#000"
    placeholder="请输入用户名"
    border="{{ false }}"
    bind:change="onChange"
  />
`

**Comment by rex-zsd** [comment]
可以通过`custom-style`属性修改，文档上没有体现，实际可用。
![image](https://user-images.githubusercontent.com/8767877/54191174-575c0900-44f0-11e9-8d69-fe0d3672622d.png)
