### ISSUE TITLE
关于van-tabbar

### ISSUE THREAD

**Issue by CurryHan** [youzan/vant-weapp#1403]
不理解为什么 currentActive 为什么从data中去除掉了
之前可以通过setData currentActive 去主动 更改组件的active tabbarItem 
现在却不行了

**Comment by rex-zsd** [comment]
`currentActive`是内部使用的属性，从未暴露给外部使用，如果需要修改激活的item请操作`active`属性。
从data中移除 `currentActive` 是为了优化性能，因为渲染层并没有用到这个属性。
