### ISSUE TITLE
van-field中当设置了error=false 后，真机调试时输入框中字体仍为红色

### ISSUE THREAD

**Issue by weim2k** [youzan/vant-weapp#1405]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**描述一下问题**
van-field中当设置了error=false 后，真机调试时输入框中字体仍为红色，在电脑上显示正常，调试发现当输入框为空时，class=“van-field__input field-index--van-field__input van-field__input--error field-index--van-field__input--error”，当输入内容后，class=“van-field__input field-index--van-field__input”，但字体仍为红色。弄了两天了，找不到原因。

wxml：
<form bindsubmit="formSubmit" id='1' bindreset="formReset">
  <van-cell-group>
    <van-field name="username" value="{{username}}" label="用户名" placeholder="请输入用户名" error="{{error}}" bind:change="onChange" />
  </van-cell-group>
  <button form-type="submit"> 发送至下一步 </button>
</form>

js：
Page({
  data: {
    username: '',
    error: false
  },

  onLoad: function(options) {},

  onChange: function(e) {
    this.setData({
      username: e.detail,
      error: ((e.detail) == "") ? true : false,
    })
  },
  formSubmit: function(e) {
    this.setData({
      error: ((this.data.username) == "") ? true : false,
    })
  },
})

**截图**
如果是 UI 问题，请提供具体截图

**环境**
 - 设备: 安卓6.0
 - 基础库版本: 2.4.4 [213]
 - Vant Weapp 版本:线上下载的最新版

**Comment by rex-zsd** [comment]
测试未复现，试下写个最小的demo，看会不会有问题。

**Comment by newpost** [comment]
我也出现这个bug

**Comment by miracle-sean** [comment]
我也出现这个bug
