### ISSUE TITLE
使用tab标签页"usingComponents": {   "van-tab": "path/to/vant-weapp/dist/tab/index",   "van-tabs": "path/to/vant-weapp/dist/tabs/index" }这个组件时，设置Tabs API中的color初始化时会无效

### ISSUE THREAD

**Issue by yangjingchuang** [youzan/vant-weapp#1411]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**描述一下问题**
描述一下你遇到的问题，包括复现方式、导致结果
使用tab标签页"usingComponents": {   "van-tab": "path/to/vant-weapp/dist/tab/index",   "van-tabs": "path/to/vant-weapp/dist/tabs/index" }这个组件时，设置Tabs API中的color初始化时会无效
**截图**
如果是 UI 问题，请提供具体截图

**环境**
 - 设备: 
 - 基础库版本: 
 - Vant Weapp 版本:
V0.5.7

**Comment by yangjingchuang** [comment]
![image](https://user-images.githubusercontent.com/29910922/54271875-5b099180-45bd-11e9-8e80-0124198fdf81.png)
如图，定义color了颜色，初始化时会闪一下，出现默认的颜色

**Comment by rex-zsd** [comment]
没有复现，请提供以下代码

**Comment by yangjingchuang** [comment]
<van-tabs bind:change="onChange" color="#3ECC56">
再安卓手机上面比较明显，测试使用的时华为荣耀V9

**Comment by yangjingchuang** [comment]
<van-tabs bind:change="onChange" color="#3ECC56">

**Comment by rex-zsd** [comment]
还是没法复现……待后续由更多反馈

**Comment by leekoho** [comment]
我也遇到了同样的情况, 页面进来开始是红色, 隔一会变成设置的color, 安卓手机

**Comment by yangjingchuang** [comment]
> 我也遇到了同样的情况, 页面进来开始是红色, 隔一会变成设置的color, 安卓手机

看上面官方的说法，竟然没法复现，我也是醉了，放弃了

**Comment by leekoho** [comment]
#1018

**Comment by leekoho** [comment]
> > 我也遇到了同样的情况, 页面进来开始是红色, 隔一会变成设置的color, 安卓手机
> 
> 看上面官方的说法，竟然没法复现，我也是醉了，放弃了

#1018 我通过这个方法解决了

**Comment by yangjingchuang** [comment]
> > > 我也遇到了同样的情况，页面进来开始是红色，隔一会变成设置的颜色，安卓手机
> > 
> > 
> > 看上面官方的说法，竟然没法复现，我也是醉了，放弃了
> 
> [＃1018](https://github.com/youzan/vant-weapp/issues/1018)我通过这个方法解决了

本来框架支持更改颜色，不需要用户覆盖颜色，然后用这种虽然可以解决问题，但是框架的bug还是没有解决
