### ISSUE TITLE
多列联动 picker onChange 的时候获取的 e.mp.detail.value 不正确

### ISSUE THREAD

**Issue by lostsnow** [youzan/vant-weapp#1412]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**描述一下问题**
描述一下你遇到的问题，包括复现方式、导致结果

**截图**
如果是 UI 问题，请提供具体截图

我实现了一个定制的 date picker (因为需要 年月日 + 自定义的时段)

其中时段 是根据不同的日期进行动态调整的, 日期的最小时间限制为当天, 比如今天是 2019年3月14日, picker 刚打开的时候是这个日期 

![图片](https://user-images.githubusercontent.com/220461/54333110-30bae100-465c-11e9-825f-b723f2b99229.png)

然后我点击2020年 这时候界面变成

![图片](https://user-images.githubusercontent.com/220461/54333131-47613800-465c-11e9-8082-6466a73b8750.png)

但是在这个时候我获取到的值(`e.mp.detail.value`)是 `[2020, 3, 14, "12-14"]`

![图片](https://user-images.githubusercontent.com/220461/54333152-5811ae00-465c-11e9-9908-913066f7a831.png)

只有年份变了但是 月 日 时段 都没有改变(界面上显示的是符合预期的 ), 这样就导致我没办法获取到正确日期 也没办法处理正确的时段

下一步我再选回2019年

![图片](https://user-images.githubusercontent.com/220461/54333222-a1fa9400-465c-11e9-9871-a57271c8dd32.png)

这里可以看到界面上 年月日是符合预期的 但是时段和一开始的不一样了, 因为我打印 `e.mp.detail.value` 的值是 

![图片](https://user-images.githubusercontent.com/220461/54333282-dc643100-465c-11e9-9edd-857c6ad4279d.png)

这里面也是上一步 2020-1-1 8-10 只变化了年份

另外这两次切换 点确定的时候都是按照界面上显示的值来写入的(这个是符合预期的)

**环境**
 - 设备: 
 - 基础库版本: 2.2.5
 - Vant Weapp 版本: 0.5.6

**Comment by zxzbenjamin** [comment]
还有另一个问题，在picker mode=“region”的时候，bindchange 事件中的mp.detail.code似乎没有取到

**Comment by beautifulnight** [comment]
问一下这个多级联动可以设置disabled属性吗，如果可以的话要怎么设置呢？

**Comment by zaxlct** [comment]
> 问一下这个多级联动可以设置disabled属性吗，如果可以的话要怎么设置呢？
在初始化数据时候就把 disabled 给预先设定好，不要用 setColumnValues 等 API 去设置

**Comment by rex-zsd** [comment]
之前应该已经修复这个问题了，demo测试没问题。
