### ISSUE TITLE
mpvue+vant tabs标签页使用echarts切换宽度无法适应

### ISSUE THREAD

**Issue by leleTang** [youzan/vant-weapp#1414]
使用mpvue创建微信小程序,用vant框架
把charts控件放在tabs标签页里时,后面的切换宽度崩溃

针对vue有lazy-render属性,但是针对小程序开发没有这个属性设置,不起效果
![image](https://user-images.githubusercontent.com/17635886/54402297-7af89c80-4706-11e9-99b4-ac2cea9fe374.png)
![image](https://user-images.githubusercontent.com/17635886/54402302-7fbd5080-4706-11e9-881a-d738584d6e62.png)

**Comment by rex-zsd** [comment]
这个不是vant的问题吧……

**Comment by leleTang** [comment]
> 这个不是vant的问题吧……

主要是需要 lazy-render 这个属性呀~

**Comment by leleTang** [comment]
把tabs的animated属性开起来就可以了~
用mpvue+vant要注意属性设置的语法,不要弄混了~

**Comment by MickeyMouse623** [comment]
> 把tabs的animated属性开起来就可以了~
> 用mpvue+vant要注意属性设置的语法,不要弄混了~

我看vant-weapp 源码中只在 tabs.js 中的 props 声明了，但是在 tabs.wxml 中并没有 lazy-render 使用。

你现在怎么弄得？我这边有4个van-tab，不能实现懒加载
