### ISSUE TITLE
Stepper 的input框为空时按退格造成maximum call stack size exceeded错误

### ISSUE THREAD

**Issue by fingertap** [youzan/vant-weapp#1422]
**描述一下问题**
Stepper 的input框为空时按退格造成maximum call stack size exceeded错误

**环境**
 - 设备: 微信开发者工具
 - 基础库版本: sdk 2.6.2
 - Vant Weapp 版本: 0.5.7

**Comment by rex-zsd** [comment]
请提供一下代码
