### ISSUE TITLE
GoodsActionIcon type 属性无效

### ISSUE THREAD

**Issue by questionlin** [youzan/vant-weapp#1425]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**描述一下问题**
如题，从源代码上看还有其他一些属性无效

**环境**
 - 设备: 
 - 基础库版本: 
 - Vant Weapp 版本: v0.5.7

**Comment by rex-zsd** [comment]
请详细说明一下问题并提供代码

**Comment by rex-zsd** [comment]
文档错误，GoodsActionIcon组件并没有`type`属性。
