### ISSUE TITLE
van-fieldt组件type="textarea"时，van-popup没有罩住，会透明重叠显示

### ISSUE THREAD

**Issue by Allenszk** [youzan/vant-weapp#1426]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**描述一下问题**
描述一下你遇到的问题，包括复现方式、导致结果

**截图**
如果是 UI 问题，请提供具体截图

**环境**
 - 设备: 
 - 基础库版本: 
 - Vant Weapp 版本:

**Comment by rex-zsd** [comment]
textarea是原生组件，层级最高，小程序本身的问题无法解决。

**Comment by DaiHuaXieHuaKai** [comment]
@rex-zsd 可以将弹出的popup修改为cover-view的不

**Comment by yaoshanliang** [comment]
我也遇到了，那大家是怎么解决的呢

**Comment by DaiHuaXieHuaKai** [comment]
@yaoshanliang 可以在popup弹出的时候隐藏textarea，在popup关闭的时候再显示textarea。
