### ISSUE TITLE
van-popup组件不能完全遮盖van-field，当 type="textarea"，会透明重叠显示

### ISSUE THREAD

**Issue by Allenszk** [youzan/vant-weapp#1427]
**描述一下问题**
van-popup组件不能完全遮盖van-field，当 type="textarea"，会透明重叠显示

**截图**

**环境**
 - 设备:  Android手机
 - 基础库版本: 
 - Vant Weapp 版本: V0.5.7

**Comment by Allenszk** [comment]
wxml.

<van-field value="{{job.profile}}" required clearable label="职位描述：" type="textarea" placeholder="请输入职位描述" bind:change="onChangeProfile" autosize/>
  <van-field value="{{job.requirement}}" required clearable label="任职要求：" type="textarea" placeholder="请输入任职要求" bind:change="onChangeRequirement" autosize/>

<van-popup show="{{showType}}" position="bottom" bind:close="onClickType">
    <van-picker show-toolbar title="选择类型" columns="{{typeList}}" bind:confirm="onSelectType" />
  </van-popup>

**Comment by rex-zsd** [comment]
textarea是原生组件，层级最高，小程序本身的问题无法解决。

**Comment by yaoshanliang** [comment]
我也遇到了，那大家是怎么解决的呢

**Comment by BreezeDealer** [comment]
我的解决方法就是另写一个view，填充内容为textarea的值，当弹出popup组件时显示这个view，关闭弹窗时显示textarea。

**Comment by Allenszk** [comment]
我后来也是这么解决的，



shenzhenkai@126.com
 
发件人： jhxxs
发送时间： 2019-08-22 09:19
收件人： youzan/vant-weapp
抄送： Allenszk; Author
主题： Re: [youzan/vant-weapp] van-popup组件不能完全遮盖van-field，当 type="textarea"，会透明重叠显示 (#1427)
我的解决方法就是另写一个view，填充内容为textarea的值，当弹出popup组件时显示这个view，关闭弹窗时显示textarea。

**Comment by leoshuaige** [comment]
@rex-zsd 大佬，这个问题怎么解决？能不能留个联系方式？？万分感激

**Comment by rex-zsd** [comment]
emmm……似乎是github客户端的bug或者我的操作问题，reply直接把原comment修改了。

**Comment by xxxmj-xx** [comment]
另写一个view,但是在真机调试时,关闭弹窗时会有几秒的延迟,弹窗还未关闭,textarea已立马显示出来了.还是可以看到.这个是要对小程序进行处理,还是给弹出层设置动画时间为0
