### ISSUE TITLE
使用 megalo vue tabs 吸顶失效，页面滚动事件失效

### ISSUE THREAD

**Issue by webtianjia** [youzan/vant-weapp#1428]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**描述一下问题**
sticky 参数 滚动不触发事件，吸顶失效

微信小程序

**截图**
如果是 UI 问题，请提供具体截图
![image](https://user-images.githubusercontent.com/22638382/54658834-59ceec00-4b0a-11e9-9ac9-ff10a8bddfcb.png)
![image](https://user-images.githubusercontent.com/22638382/54658842-5fc4cd00-4b0a-11e9-8533-d87dd26d226e.png)
![image](https://user-images.githubusercontent.com/22638382/54658846-62bfbd80-4b0a-11e9-9fd0-7daacebafdcc.png)

**环境**   开发者工具
 - 设备: 
 - 基础库版本: 2.2.2
 - Vant Weapp 版本:0.5.2

**Comment by webtianjia** [comment]
修改源码判断可以用

**Comment by rex-zsd** [comment]
@webtianjia 修改源码判断是？

**Comment by webtianjia** [comment]
1.页面
``` onPageScroll(e) {
            this.scrollTop = e.scrollTop;
        }
//传递scrollTop过去
```
![image](https://user-images.githubusercontent.com/22638382/54675114-cf51b100-4b38-11e9-9357-123cdd391ade.png)

**Comment by rex-zsd** [comment]
额 0.5.2版本是依赖外部传入 `scrollTop` 属性的。
