### ISSUE TITLE
使用tabBar组件作为小程序自定义tabBar

### ISSUE THREAD

**Issue by songxk** [youzan/vant-weapp#1429]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**描述一下问题**
小程序2.5开始支持自定义tabBar功能（https://developers.weixin.qq.com/miniprogram/dev/framework/ability/custom-tabbar.html），我在自定义的tabBar中使用了如下代码
`Component({
  attached() {
  },
  methods: {
    goMyPage: function() {
      wx.switchTab({
        url: '/pages/my/index'
      })
    },
    goHome: function() {
      wx.switchTab({
        url: '/pages/index/index'
      })
    },
    onChange: function(event) {
      console.log(event.detail)
    }
  }
})

{
  "component": true,
  "usingComponents": {
    "van-tabbar": "/components/vant/tabbar/index",
    "van-tabbar-item": "/components/vant/tabbar-item/index"
  }
}

  <van-tabbar bind:change="onChange">
    <van-tabbar-item icon="shop-o" bindtap="goHome">首页</van-tabbar-item>
    <van-tabbar-item icon="shopping-cart-o">购物车</van-tabbar-item>
    <van-tabbar-item icon="user-o" bindtap="goMyPage">我的</van-tabbar-item>
  </van-tabbar>
`

然后在切换下面tab的时候很卡，并且不能正确的切换active

**截图**
![image](https://user-images.githubusercontent.com/1507323/54660781-acaca180-4b12-11e9-8a12-0ad977e3d9f5.png)

**环境**
 - 设备:  微信开发者工具
 - 基础库版本: 
 - Vant Weapp 版本: git最新的版本

**Comment by smallcham** [comment]
我也遇到了相似的问题，使用自定义tabBar调用switchTab事件时，active状态会被重置为默认值。

**Comment by rex-zsd** [comment]
@smallcham `van-tabbar`仅仅是一个展示组件，没有`active`项完全是使用者自己控制的.

**Comment by rex-zsd** [comment]
tabbar组件把一些不需要的数据保存在`data`中了，可能会有性能影响，下版本优化。
