### ISSUE TITLE
search 组件 bind:clear事件问题

### ISSUE THREAD

**Issue by goodliang** [youzan/vant-weapp#1430]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**描述一下问题**
bind:clear 事件触发之后，页面上其它事件，不管是 navigator 或 bindtap 第一次点击都会失效，需要触发两次，如图，点击了搜索框 X 号之后，下边苹果等label 的事件都会失效，需要点击两次。我见有其它同学提问过这个问题，可能他描述的不够清楚，希望管方解决

**截图**
![image](https://user-images.githubusercontent.com/15775197/54666678-6d3b8080-4b25-11e9-9ba7-0424afbaae69.png)

**环境**
 - 设备: 任何设备
 - 基础库版本: 任何版本
 - Vant Weapp 版本: 任何版本

**Comment by ChangeZhang** [comment]
出现同样的问题！

**Comment by rex-zsd** [comment]
比较奇怪，因为`clear`其实也只是一个点击事件而已，并没有什么特殊逻辑。

**Comment by pepse1208** [comment]
点击bind:clear 事件只有当输入内容为1时能触发，其余都不能触发

**Comment by litianyangz** [comment]
field 组件clearable出现同样的情况

**Comment by vueto** [comment]
有解决的办法吗？

**Comment by susan007** [comment]
同求解决办法！
