### ISSUE TITLE
使用var-tabs组件，给tab自定义数据属性

### ISSUE THREAD

**Issue by songxk** [youzan/vant-weapp#1432]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**你需要的功能是？**
使用var-tabs组件，给tab自定义数据属性，在js中使用target的dataset可以获取到
官方的基础组件是支持的，

![image](https://user-images.githubusercontent.com/1507323/54681918-7ee24f80-4b48-11e9-9281-a8960ede8fb3.png)

**你期望 API 是什么样的？**
`<van-tabs bind:change="onChangeCategory">
  <block wx:for="{{categories}}" wx:key="category">
    <van-tab title="{{item.name}}" data-hi="111" bindtap="clickTab">
      <van-col wx:for="{{item.list}}" wx:key="index">
        <image src="{{item}}" class="goods-list-item" />
      </van-col>
    </van-tab>
  </block>
</van-tabs>`

`onChangeCategory: function(e) {
    let id = e.target.dataset.hi;
    console.log(e);
    wx.showToast({
      title: "id is " + id,
      icon: 'none'
    });
  },`

**Comment by rex-zsd** [comment]
根据`active`取下数据就行，不需要vant支持。

**Comment by songxk** [comment]
> 根据`active`取下数据就行，不需要vant支持。

这个原生的组件支持的，如果我使用active的index再去数据里面用索引拿的话就多余了一步，而且有性能消耗
