### ISSUE TITLE
关于VantComponent内置的computed和watch的一些困惑

### ISSUE THREAD

**Issue by shuimupj** [youzan/vant-weapp#1436]
**描述一下问题**
computed里面的变量为什么会执行三次？

**截图**
![微信截图_20190321111753](https://user-images.githubusercontent.com/20787055/54731754-01135800-4bcb-11e9-9c86-313f2d9454f8.png)

**Comment by rex-zsd** [comment]
vant中`computed`的实现是每次`setData`都会执行一次。
