### ISSUE TITLE
van-field 组件中的size 有哪些可选值，能不能在说明文档中列出来？

### ISSUE THREAD

**Issue by polokang** [youzan/vant-weapp#1440]
**你需要的功能是？**
van-field 组件中的size 有哪些可选值，能不能在说明文档中列出来？

**你期望 API 是什么样的？**
在说明文档中列出即可

**Comment by taoxueweilong** [comment]
field组件在项目中不显示，你那是怎么用的？求助，谢谢

**Comment by rex-zsd** [comment]
![image](https://user-images.githubusercontent.com/8767877/54810649-8da04200-4cc1-11e9-844c-65dc94f6b3d4.png)
