### ISSUE TITLE
picker column 选中效果

### ISSUE THREAD

**Issue by Virczz** [youzan/vant-weapp#1441]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**你需要的功能是？**
描述一下你需要的功能，用于解决什么问题
需要添加picker选中当前列的效果。
问题描述：
我在调用 picker中的active-class的时候，现在的表现是将当前行的所有列都添加了边框。我想要在点击第一列的时候，只有第一列有边框；点击第二列的时候，只有第二列有边框
![picker-select](https://user-images.githubusercontent.com/15669121/54795887-d8519800-4c88-11e9-8da2-3d78503a6fb5.png)

**你期望 API 是什么样的？**
描述一下你期望的 API 形式

**Comment by rex-zsd** [comment]
`className`的设计就是对每一列的激活选项生效。
你的需求目前无法实现。
