### ISSUE TITLE
van-field 没有效果

### ISSUE THREAD

**Issue by taoxueweilong** [youzan/vant-weapp#1442]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**描述一下问题**
页面中引入van-field没有效果，其它组件均正常显示，引入路径没有问题，在static中的field打印，检测到组件已被引入，但是没有执行beforeCreate函数
**截图**
如果是 UI 问题，请提供具体截图

**环境**
 - 设备: 微信小程序开发者工具
 - 基础库版本: 
 - Vant Weapp 版本:0.5.7

**Comment by rex-zsd** [comment]
检查下代码吧，截图、代码都没提供，帮不了你。
