### ISSUE TITLE
picker的render渲染延迟与设置选中项的冲突问题

### ISSUE THREAD

**Issue by iouhuan** [youzan/vant-weapp#1443]
**描述一下问题**
picker的render渲染延迟与设置选中项的冲突问题
* 我尝试在应用中通过setColumnValues对picker的可选项项进行修改
* 同时，用setIndexes需要对picker进行选中项的初始化（defaultIndex != 0）
* 另外， 我一直不太理解picker提供了那么多的实例方法？是不是其他方法也会有这个问题？当前我有什么办法可以很好解决这个问题么？

**截图**
![image](https://user-images.githubusercontent.com/18160278/54803840-190ed880-4cac-11e9-98db-100d9fa61460.png)
只能通过setTimeout实现选中项的初始化，异步线程渲染的，而非同步阻塞

**环境**
 - 设备: 微信开发工具
 - 基础库版本: 2.6.1
 - Vant Weapp 版本:我是直接pull的， git log 最新日志为：
```
commit 2cc9943392c65a846ee8c85a82d562d2db4ccf6a (HEAD -> dev, origin/dev, origin/HEAD)
Author: rex <rexkaneki@gmail.com>
Date:   Mon Mar 18 19:41:26 2019 +0800

    [bugfix] Picker: defaultIndex not work


```

**Comment by rex-zsd** [comment]
picker组件的set类方法都会返回`Promise`。
可以利用`Promise`控制执行顺序。
