### ISSUE TITLE
如何支持 i18n ?

### ISSUE THREAD

**Issue by lubancafe** [youzan/vant-weapp#1446]
**你需要的功能是？**
前端多语言的切换，(如 zh-CN, en-US, zh-TW )。类似于 ngx-translate 的模块功能。前端自由切换显示语言。

**你期望 API 是什么样的？**
可否采用pipeline的方式翻译？
HTML如：
<p>{{'projectname' | translate}}</p>
<button type="button" (click)="useChinese()">中文</button>
<button type="button" (click)="useEnglish()">English</button>

简单的使用方式可以参见：
https://github.com/ngx-translate/core 
https://tc9011.com/2017/12/16/angular%E4%B8%ADngx-translate%E4%BD%BF%E7%94%A8%E7%AE%80%E4%BB%8B/

**Comment by rex-zsd** [comment]
vant-weapp暂时还不支持，可以用微信自己出的[miniprogram-i18n](https://github.com/wechat-miniprogram/miniprogram-i18n)
