### ISSUE TITLE
构建npm后编译出错提示找不到../wxs/utils.wxs

### ISSUE THREAD

**Issue by terrywcw** [youzan/vant-weapp#1448]
构建npm后编译出错提示找不到../wxs/utils.wxs，但目录里确实存在
<img width="646" alt="image" src="https://user-images.githubusercontent.com/48821202/54862562-c00c7680-4d77-11e9-8316-ab448441602a.png">
<img width="173" alt="image" src="https://user-images.githubusercontent.com/48821202/54862564-cbf83880-4d77-11e9-91dd-528c7a06c346.png">

**环境**
 - 设备: 
 - 基础库版本: 2.2.5
 - Vant Weapp 版本:0.5.8

**Comment by TonyLiuYan** [comment]
+1

**Comment by Kennersky** [comment]
我也遇到过，原来是构建后确实没有这个文件，不过我再点一次构建又正常了。

**Comment by rex-zsd** [comment]
既然文件的确存在，那应该不是vant-weapp的问题，试试重新编译。

**Comment by terrywcw** [comment]
我把开发工具关了重启编译就正常了

**Comment by 13836005450** [comment]
重启重新编译就好了
