### ISSUE TITLE
swipe-cell不能触发事件

### ISSUE THREAD

**Issue by lixize** [youzan/vant-weapp#1449]
**描述一下问题**
swipe-cell不能触发事件，在官方Example中也有同样的问题。

**截图**
如果是 UI 问题，请提供具体截图

**环境**
 - 设备: 微信开发者工具
 - 基础库版本: 2.6.4
 - Vant Weapp 版本: 0.5.8

**Comment by rex-zsd** [comment]
0.5.8版本引入的bug，可以先回退到0.5.7，下个版本会修复。

**Comment by zhuhengtan** [comment]
使用0.5.19依然有该问题
微信开发者工具
基础库版本: 2.8.0
Vant Weapp 版本: 0.5.19
@rex-zsd
