### ISSUE TITLE
van-field里添加popup，输入法会弹出覆盖popup，怎么禁用输入法

### ISSUE THREAD

**Issue by exelin** [youzan/vant-weapp#1450]
请教van-field里添加popup，输入法会弹出覆盖popup，怎么禁用输入法

试用了readonly和一系列的bind动作组合，手机预览无法成功，恳请指导

**Comment by selin0410** [comment]
我也遇到了类似问题。popup+省市区选择 弹出的时候 会让另一个textarea的输入法弹出...去掉type=textarea就没有这种问题了。 而且textarea的placeholder也没有和label文字水平对齐 其他type的van-field就没有问题。

**Comment by rex-zsd** [comment]
@exelin 尝试一下阻止popup上click事件的冒泡
```html
<van-popup catchtap="noop">
</van-popup>
```

**Comment by rex-zsd** [comment]
@selin0410 textarea在安卓和iOS上的内边距是不同的，可以在小程序开发者社区上查一下。

**Comment by exelin** [comment]
> 我也遇到了类似问题。popup+省市区选择 弹出的时候 会让另一个textarea的输入法弹出...去掉type=textarea就没有这种问题了。 而且textarea的placeholder也没有和label文字水平对齐 其他type的van-field就没有问题。

大神，你的问题解决了吗？我还是会有输入法档popup的问题，可以把你的相关代码贴一份给我学习吗？感谢
