### ISSUE TITLE
tab标签页设置背景后  下面没有内容就没有背景颜色了   而且设置了滑动   没有内容的地方也不能滑动

### ISSUE THREAD

**Issue by Memoryzzzzzz** [youzan/vant-weapp#1451]
描述一下问题
tab标签页设置背景后     下面没有内容就没有背景颜色了   现在搞得好丑     而且设置了滑动   没有内容的地方也不能滑动

截图
如果是 UI 问题，请提供具体截图
![image](https://user-images.githubusercontent.com/41710152/54881006-5464ff00-4e86-11e9-981b-65c271675aa8.png)

环境
 - 设备: 都一样会有这样的问题
 - 基础库版本: 2.6.2
 - Vant Weapp 版本:19.1.14号的  我是直接下载引用的  不知道版本

**Comment by rex-zsd** [comment]
描述不清楚，图也看不清，不知道是什么问题。

**Comment by rex-zsd** [comment]
还有请贴上代码

**Comment by Memoryzzzzzz** [comment]
> 描述不清楚，图也看不清，不知道是什么问题。

没有内容的地方没有背景颜色   也不能滑动

**Comment by Memoryzzzzzz** [comment]
> 还有请贴上代码

<van-tabs swipeable animated duration="0.3" bind:click="onClick" bind:change="onClick" custom-class="tab">
  <block wx:for="{{year}}" wx:for-item="i" wx:key="unique">
    <block wx:for="{{semester}}" wx:for-item="j" wx:key="unique">
      <van-tab title="{{i}}学年 第{{j}}学期" name>
        <van-row custom-class="dark">
          <van-col span="24">{{data}}学年 第{{term}}学期</van-col>
        </van-row>
        <block wx:if="{{data=='2018-2019'&&term==2}}">
          <van-row custom-class="light graduation">
            <van-col span="24">我们毕业啦！</van-col>
          </van-row>
        </block>
        <block wx:else>
          <van-row custom-class="dark">
            <van-col span="5">课程代码</van-col>
            <van-col span="7">课程名称</van-col>
            <van-col span="2">学分</van-col>
            <van-col span="2">绩点</van-col>
            <van-col span="3">成绩</van-col>
            <van-col span="4">备注</van-col>
          </van-row>
          <block wx:for="{{GradeList}}" wx:key="unique">
            <block wx:if="{{item.Semester==term}}">
              <van-row custom-class="light">
                <van-col span="5">{{item.CourseCode}}</van-col>
                <van-col span="7">{{item.CourseTitle}}</van-col>
                <van-col span="2">{{item.Credit}}</van-col>
                <van-col span="2">{{item.AchievementPoint}}</van-col>
                <van-col span="3">{{item.Achievement}}</van-col>
                <van-col span="4">{{item.Remarks}}</van-col>
              </van-row>
            </block>
          </block>
        </block>
      </van-tab>
    </block>
  </block>
</van-tabs>

**Comment by Memoryzzzzzz** [comment]
> 还有请贴上代码

以重新编辑   请查看
