### ISSUE TITLE
radio加载字体图标报错

### ISSUE THREAD

**Issue by zhangshichuan** [youzan/vant-weapp#1453]
**描述一下问题**
- 引入radio组件后，字体图标加载报错，导致ridio选中样式不生效
- 相关的issues我也看过，并不只是开发者工具报错，真机上面也没有选中效果

**截图**
![image](https://user-images.githubusercontent.com/8280832/54895813-5f5a7680-4efc-11e9-8673-5a30ec30c4a3.png)

**环境**
 - 设备: deepin15.9.2
 - 基础库版本: 2.6.4
 - Vant Weapp 版本: 0.5.8

**Comment by rex-zsd** [comment]
可以参考[开发者社区](https://developers.weixin.qq.com/community/search?query=ERR_CACHE_MISS&page=1)
清除缓存后第一次编译会出现这个报错，再次编译就可以了，不是vant-weapp的问题。

**Comment by chen-can** [comment]
请问这个问题解决了吗
