### ISSUE TITLE
Picker选择器 默认选中项 实现方式

### ISSUE THREAD

**Issue by kapbook-caizhehao** [youzan/vant-weapp#1454]
**你需要的功能是？**
Picker选择器 默认选中项不知如何实现

**你期望 API 是什么样的？**
![image](https://user-images.githubusercontent.com/38315632/54909619-9bee9800-4f25-11e9-8294-2877c64a8dcd.png)

**Comment by rex-zsd** [comment]
看[文档](https://youzan.github.io/vant-weapp/#/picker)
