### ISSUE TITLE
tabs的右边slot(即"nav-right")在动态加载tab时(tab数量10个)不显示

### ISSUE THREAD

**Issue by CoolPrince** [youzan/vant-weapp#1457]
**描述一下问题**
使用tabs组件时，动态获取要显示的tab，然后在slot="nav-right"中添加一个按钮，结果按钮在真机上不显示，在模拟器上向右拖到最后会显示。
如果tabs中的tab是静态数据，那么slot="nav-right"在真机和模拟器显示都正常。

**环境**

设备: 微信小程序开发者工具
基础库版本:2.6.2
Vant Weapp 版本:0.5.8

**Comment by bluesky628** [comment]
.custom-class scroll-view{
  width: 90%
} 加个宽度
