### ISSUE TITLE
在微信小程序预览，可以详细一些吗，

### ISSUE THREAD

**Issue by liguangze** [youzan/vant-weapp#1463]
安装项目依赖
npm install

 执行组件编译
npm run dev
打开微信开发者工具，把vant-weapp/example目录添加进去就可以预览示例了。

我是照做的，运行不起来呢

![image](https://user-images.githubusercontent.com/10549682/54982471-e2a3c700-4fe5-11e9-9611-e0f1a0ff84ef.png)
npm run dev  执行组件编译  报这个错

我主要是想在开发者工具中预览示例

**Comment by rex-zsd** [comment]
提示很明显了，当前目录下不存在`package.json`文件，检查下是不是位置有问题吧。

**Comment by liguangze** [comment]
那这个文件是怎么生成的，半路转的小程序，我的操作是在一个空的文件里面执行npm install 这个命令，
![image](https://user-images.githubusercontent.com/10549682/55052853-45a06700-5095-11e9-8f26-6d8d75afc459.png)


生成了package-lock.json  这个文件，在执行npm run dev这个命令吗，

能详细些怎么操作吗，小白，谢谢
