### ISSUE TITLE
SwipeCell 内放输入框无法focus输入

### ISSUE THREAD

**Issue by wulienen** [youzan/vant-weapp#1464]
**描述一下问题**
SwipeCell组件内放输入框无法点击输入，只有真机调试会这样。代码如下：
` <van-swipe-cell right-width="{{ 65 }}" left-width="{{ 65 }}">
  <view slot="left">选择</view>
  <van-cell-group>
    <van-field value="12345" title-width="50px" label="重量" border="{{ false }}" />
  </van-cell-group>
  <view slot="right">删除</view>
</van-swipe-cell>`

**环境**
 - 设备: iphone6S 系统版本12.1.4
 - 基础库版本: 2.2.0
  -微信版本：7.0.3
 - Vant Weapp 版本:v0.5.8

**Comment by rex-zsd** [comment]
0.5.9已修复
