### ISSUE TITLE
Tab组件若被包含在 if block当中会存在bug

### ISSUE THREAD

**Issue by powerlau** [youzan/vant-weapp#1467]
**描述一下问题**
Tab组件如果外层是根据条件显示隐藏的，如果默认不显示的话，那么当显示出来的时候Tab组件不会有下标横线。如下图Tab1虽然处于选中状态，然而并没有底部的横线。如果Tabs外部没有v-if或者v-show那么不存在这个问题

**截图**
![image](https://user-images.githubusercontent.com/7065910/55041410-d95b3e80-5067-11e9-9076-9df07af5cb94.png)
![image](https://user-images.githubusercontent.com/7065910/55041433-f5f77680-5067-11e9-93f9-69ac5d0abbe4.png)

**环境**
 - 设备: 
 - 基础库版本: 
 - Vant Weapp 版本: ^0.5.8

**Comment by rex-zsd** [comment]
mpvue@2.0 + vant-weapp@0.5.8 没复现，看下是不是mpvue的问题

**Comment by powerlau** [comment]
我也是mpvue@2.0 + vant-weapp@0.5.8，你可以打开微信小程序搜索 "六壬金口诀排盘"，其中类象选项卡的下级选项卡就有这个问题。
同时我也遇到了 https://github.com/youzan/vant-weapp/issues/1130 同样的问题，点击tab的时候窗口会经常会被置顶。

**Comment by rex-zsd** [comment]
@powerlau 
你的小程序里嵌套了tabs组件，tab组件依赖初始化时计算下划线的样式和位置，如果嵌套会造成初始化时页面并未渲染内层的tabs，无法计算样式。你的问题和这个issue的情况是不一样的。

**Comment by rex-zsd** [comment]
至于置顶的问题，tab组件并没有控制页面的滚动，这个是页面的默认行为。
页面会尝试将滚动条位置维持在原处，如果目标tab中的内容高度不够，甚至有tab中的内容依赖异步获取（切换时内容高度为0），此时因为底部高度不够，页面无法维持原滚动位置，只能回到顶部。
