### ISSUE TITLE
是否有编译后的es5版本

### ISSUE THREAD

**Issue by chavesgu** [youzan/vant-weapp#1469]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**你需要的功能是？**
是否有编译后的es5版本？uni-app使用了内置的es6编译es5，需要不勾选小程序的es6转es5

**你期望 API 是什么样的？**
期望是已编译的es5版本

**Comment by rex-zsd** [comment]
目前没有，之后可以支持。

**Comment by chavesgu** [comment]
> 目前没有，之后可以支持。

那就很无奈了。。是不是可以认为不勾选es6转es5就无法使用vant了呢

**Comment by chavesgu** [comment]
@rex-zsd  可以参考下我的解决方案， 修改为小程序的模块化方案即可和uniapp兼容。
https://juejin.im/post/5c9b25e06fb9a070bf3605ed
