### ISSUE TITLE
van-cell组件跳转深度层级页数问题？

### ISSUE THREAD

**Issue by 91xtw** [youzan/vant-weapp#1470]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**描述一下问题**
van-cell。我从首页开始wx[nav组件]->van-cell分类列表->van-cell细分列表->详情；
然后：点击微信上边的返回，按原路返回至首页、再从首页开始执行上面的操作；
就不行了。报页面深度问题。超过5个页面；跳转失败；
怎么解决呢？

**截图**
-

**环境**
 - 设备: 所有
 - 基础库版本: 1.9.9 版本

 - Vant Weapp 版本:Vant Weapp 最低支持到小程序基础库 1.9.9 版本

**Comment by rex-zsd** [comment]
小程序的页面层级限制应该跟vant无关吧。

**Comment by 91xtw** [comment]
> 小程序的页面层级限制应该跟vant无关吧。

不过我们已经修复了。我可以肯定是组件问题。！！！另外项目用了之后发现了许多缺点。当然优点也很多。
