### ISSUE TITLE
van-tabs多个tab页的情况下   切换tab页会显示滚动条

### ISSUE THREAD

**Issue by Memoryzzzzzz** [youzan/vant-weapp#1471]
描述一下问题
van-tabs多个tab页的情况下   切换tab页会显示滚动条   要是可以去掉  或者选择是否显示

截图
![微信图片_20190327165200](https://user-images.githubusercontent.com/41710152/55062330-ba34cf00-50b0-11e9-9d2d-f9411cbce522.jpg)

环境
 - 设备: 所有设备
 - 基础库版本: 2.6.4
 - Vant Weapp 版本:v0.5.8

**Comment by Memoryzzzzzz** [comment]
> 描述一下问题
> van-tabs多个tab页的情况下 切换tab页会显示滚动条 要是可以去掉 或者选择是否显示
> 
> 环境
> 
> * 设备: 所有设备
> * 基础库版本: 2.6.4
> * Vant Weapp 版本:v0.5.8

**Comment by rex-zsd** [comment]
滚动条的问题没法避免。
