### ISSUE TITLE
van-popup无法关闭弹出层，只能关闭遮罩层，微信小程序

### ISSUE THREAD

**Issue by yan357174356** [youzan/vant-weapp#1472]
**描述一下问题**
在微信小程序中van-popup show='false"无法关闭弹出层。内容还是显示在页面上

**截图**
无

**环境**
 - 设备: 微信小程序
 - 基础库版本: 
 - Vant Weapp 版本:

**Comment by rex-zsd** [comment]
`show`接受的是`Boolean`，不是`String`。

**Comment by yan357174356** [comment]
show=false一样不行呀

**Comment by phoebemoon16** [comment]
请问解决了吗 设置为false 确实是不关闭的
