### ISSUE TITLE
组件用最新的开发工具，各种报错

### ISSUE THREAD

**Issue by chaituan** [youzan/vant-weapp#1474]
使用版本 0.58
开发工具 1.02.1902010
git 到本地把dist和example 放到项目中后，
编译各种报错，都是安装你们文档提示来操作的，还不行。 难道还有别的要操作？  我把dist文件放到我项目中 也是提示报错.... 
是还要配置什么东西吗？
![image](https://user-images.githubusercontent.com/26025563/55130701-c1aeb380-5156-11e9-98f7-c63bc05176a6.png)

**Comment by dxwb** [comment]
我也有一样的错误

**Comment by rex-zsd** [comment]
把dist放到项目中？你应该是操作有误
