### ISSUE TITLE
swiperCell组件的event事件无效

### ISSUE THREAD

**Issue by kurisLei** [youzan/vant-weapp#1475]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**描述一下问题**
在使用swiperCell组件时，发现该组件的event事件如 bind:close,bind:click 全部无效，使用的官网文档的sample(https://youzan.github.io/vant-weapp/#/swipe-cell).

**截图**
如果是 UI 问题，请提供具体截图

**环境**
 - 设备: iPhone X
 - 基础库版本: 2.6.4
 - Vant Weapp 版本: 0.5.8

**Comment by transtone** [comment]
看4天前有提交，似乎是修复了，不知道什么时候发布。

**Comment by rex-zsd** [comment]
#1449
已经修复，将在0.5.9发布

**Comment by DannyLiu0705** [comment]
0.5.14版本
<van-swipe-cell right-width="80" v-for="(item, i) in list" :key="i" @click="modify">
......
</van-swipe-cell>
click事件不执行.
