### ISSUE TITLE
van-toast调用是，关闭的时候还有一块透明的view，没有完全隐藏

### ISSUE THREAD

**Issue by yht520** [youzan/vant-weapp#1476]

**Comment by yht520** [comment]
![image](https://user-images.githubusercontent.com/20833627/55219360-b2576500-523f-11e9-9c44-c517689901c5.png)

**Comment by yht520** [comment]
van-toast调用是，关闭的时候还有一块透明的view，没有完全隐藏，那一块东西遮挡了后面的内容无法被点击

截图

![image](https://user-images.githubusercontent.com/20833627/55219688-81c3fb00-5240-11e9-9777-2499513a7f1e.png)


环境

设备: iPhone X
基础库版本: 2.6.4
Vant Weapp 版本: 0.5.8

**Comment by rex-zsd** [comment]
调用的代码提供一下？

**Comment by rex-zsd** [comment]
跟 #1565 应该是相同问题，可以关注一下
