### ISSUE TITLE
设置van-tabbar为自定义tabbar时，调用wx.switchTab后active激活状态异常，无法正常对应tabbar

### ISSUE THREAD

**Issue by maoniangv5** [youzan/vant-weapp#1481]
**描述一下问题**
设置van-tabbar为自定义tabbar时，调用wx.switchTab后active激活状态异常，switchTab正常切换但是无法正常对应tabbar
自定义tabbar，使用van-tabbar组件引入custom-tab-bar/index.wxml

**截图**
![image](https://user-images.githubusercontent.com/11324745/55340725-d503ab00-54d7-11e9-8046-2ac5c739500e.png)
如图示：
当前切换tab为第一个exchange，激活状态为第三个user

**环境**
 - 设备: macbpro、ip7 ios12
 - 基础库版本：2.5.0
 - Vant Weapp 版本：^0.5.8

谢谢

**Comment by rex-zsd** [comment]
建议仔细看一下小程序自定义tabbar的[文档和示例](https://developers.weixin.qq.com/miniprogram/dev/framework/ability/custom-tabbar.html?search-key=%E8%87%AA%E5%AE%9A%E4%B9%89tabbar)。
每个页面的tabbar都是不同的实例。
