### ISSUE TITLE
van-field 组件在不输入文本时placeholder提示文本没有垂直居中，输入文本正常

### ISSUE THREAD

**Issue by Kennersky** [youzan/vant-weapp#1483]
van-field 组件textarea高度自适应模式时在不输入文本时placeholder提示文本没有垂直居中，输入文本正常
![TIM截图20190402153453](https://user-images.githubusercontent.com/2129521/55384288-e5119e00-555c-11e9-993f-3cc0f95ef2de.jpg)

**截图**
![TIM截图20190402152321](https://user-images.githubusercontent.com/2129521/55383636-459fdb80-555b-11e9-862f-a476d104d620.jpg)
![TIM截图20190402152434](https://user-images.githubusercontent.com/2129521/55383713-6ff19900-555b-11e9-9025-4f78c66e4cec.jpg)
![TIM截图20190402152627](https://user-images.githubusercontent.com/2129521/55383831-b8a95200-555b-11e9-83b9-9ee42b2b8815.jpg)

**环境**
 - 设备: Honor V20 、微信开发者工具模拟器
 - 基础库版本: 2.6.4
 - Vant Weapp 版本: 0.5.8

**Comment by rex-zsd** [comment]
微信原生组件的样式问题，要找下是不是有稍微优雅一点的方法兼容这个问题。

**Comment by Kennersky** [comment]
> 微信原生组件的样式问题，要找下是不是有稍微优雅一点的方法兼容这个问题。

发现一个库[color-ui](https://www.color-ui.com/)，里面的textarea并不会这样，可以参考看看
