### ISSUE TITLE
关于checkbox-group 中刷新数据后之前选中的没有选中状态

### ISSUE THREAD

**Issue by echoyl** [youzan/vant-weapp#1486]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**描述一下问题**
使用checkbox-group是 checkbox中的name是数字类型
比如 我有2道题目第一题已经选中了1,2然后下一题渲染之后回到上一题刚才选中的1,2没有了选中状态，group中的value是有的。然后查看checkbox-group的js代码发现组件中的 watch函数中的
var children = this.getRelationNodes('../checkbox/index');
这个this.getRelationNodes 这个获取的是之前的子元素，也就是说在渲染前就获取了数据，那么导致这个children是上一道题目的选项
child.set({
          value: _value.indexOf(child.data.name) !== -1
        });
这个值永远都是-1了，就不会选中了。
一直没有解决这个，然后就不用checkbox-group，直接使用checkbox 自己判断添加选中与否的逻辑。

**Comment by rex-zsd** [comment]
提供一下核心代码？没看明白你的描述。

**Comment by 121134388** [comment]
遇到一模一样的问题，就是回答问题，选项选中了后，进行下一题，然后返回上一题，无法自动渲染成选中状态

**Comment by aierong** [comment]
是喔，我也碰到这个问题，列表刷新后，之前选择的，没有了
