### ISSUE TITLE
tree-select点击事件没有效果？

### ISSUE THREAD

**Issue by wjf9492** [youzan/vant-weapp#1487]
`@navclick="onClickNav"
      @itemclick="onItemClick"`

**Comment by rex-zsd** [comment]
mpvue不支持中划线的事件名，不是vant-weapp的问题。

**Comment by fangkyi03** [comment]
所以有解决办法吗

**Comment by rex-zsd** [comment]
只能手动改写vant weapp的源码，把事件名改成不带`-`的了

**Comment by lixiaodaoaaa** [comment]
<img width="744" alt="图片" src="https://user-images.githubusercontent.com/4048031/82311200-f7b49400-99f7-11ea-8ba0-24aeb5ae4b70.png">

文档有错误

应该为：
```javascript 
  <van-tree-select
        :items="storageRegions"
        :main-active-index="regionActivieId"
        :active-id="shelfActiveId"
        @navclick="clicknav"
        @itemclick="clickitem"
      />
```

这样就可以了
