### ISSUE TITLE
van-dialog 加 van-field,弹出后field文字会抖动一下

### ISSUE THREAD

**Issue by Kennersky** [youzan/vant-weapp#1488]
**描述一下问题**
如题，作用van-dialog 加 van-field,弹出后field文字会抖动一下
代码：
`<van-dialog use-slot async-close show="{{addDialogShow}}" title="添加分类" show-cancel-button show-confirm-button confirm-button-text="确定添加" bind:close="onCloseAdd">
    <van-field value="{{ addSortTitle }}" placeholder="请输入分类名" border="{{ false }}" bind:input="onAddChange" />
  </van-dialog>`
**截图**
![TIM截图20190403175132](https://user-images.githubusercontent.com/2129521/55469996-51fa6600-5639-11e9-9edc-efa1354cbbf6.jpg)

**环境**
 - 设备: honor v20,微信开发者工具
 - 基础库版本: 2.6.4
 - Vant Weapp 版本:0.5.8

**Comment by rex-zsd** [comment]
将`van-dialog`的`transition `属性设置为`fade`即可。
