### ISSUE TITLE
tabs tabBar navBar可否支持原生组件如：cover-view实现呢

### ISSUE THREAD

**Issue by flycj** [youzan/vant-weapp#1492]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**你需要的功能是？**
描述一下你需要的功能，用于解决什么问题
tab和 tabbar 一般都会固定在页面上，但是如果这些组件内部有原生组件的话，就会覆盖 tab tabbar 或 navbar；
解决问题：一般固定组件和原生组件的覆盖问题
**你期望 API 是什么样的？**
描述一下你期望的 API 形式
可在 组件属性上添加 native ，native = true 则用原生组件渲染 tab 等组件
**示例代码**
请展示一下新功能的大致用法

```js
```

```wxml
```

**Comment by rex-zsd** [comment]
cover-view限制了内部使用的元素，会有很大的限制。

**Comment by rex-zsd** [comment]
以小程序目前的设计，cover-view内部只能嵌套指定的几个元素，很难实现扩展性，暂时不考虑了。

**Comment by flycj** [comment]
嗯嗯，好的
