### ISSUE TITLE
Bug：van-info在引用wxParse的页面中数字错位

### ISSUE THREAD

**Issue by shuimupj** [youzan/vant-weapp#1495]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**描述一下问题**
![微信图片_20190405003526](https://user-images.githubusercontent.com/20787055/55573009-79395c00-573b-11e9-8005-07757dff8e32.png)
![微信截图_20190405003625](https://user-images.githubusercontent.com/20787055/55572962-6161d800-573b-11e9-8f93-3574602f401b.png)
问题和解决方案如图。
个人认为像van-info这种最末端、内部无solt且包含数字的组件，应该在css中重声明一下文字换行问题。
（因为小程序还未上线，所以一些涉及到特殊ui的打码了，见谅！）

**Comment by rex-zsd** [comment]
从图里看是wxParse用标签选择器覆盖了全局样式，不是vant-weapp的问题。
