### ISSUE TITLE
notify 麻烦支持top 和 zIndex

### ISSUE THREAD

**Issue by flycj** [youzan/vant-weapp#1498]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**你需要的功能是？**
![image](https://user-images.githubusercontent.com/5103045/55694418-ba08cd80-59e6-11e9-8cdb-14aa4da9f659.png)
小程序 Notify 支持top 属性 和 z-index属性

**你期望 API 是什么样的？**
描述一下你期望的 API 形式
<van-notify top="70" zIndex="101"/>
**示例代码**
请展示一下新功能的大致用法

```js
```

```wxml
```

**Comment by rex-zsd** [comment]
top的问题可以设置`safe-area-inset-top`为`true`

**Comment by flycj** [comment]
好的
