### ISSUE TITLE
title-active-color 自定义颜色，选中时文字的颜色没有变化

### ISSUE THREAD

**Issue by wwsgg** [youzan/vant-weapp#1499]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**描述一下问题**
描述一下你遇到的问题，包括复现方式、导致结果

**截图**
如果是 UI 问题，请提供具体截图

**核心代码**
请提供使用组件的核心代码

```js
```

```wxml
```

**环境**
 - 设备:
 - 基础库版本:
 - Vant Weapp 版本:

**Comment by rex-zsd** [comment]
issue不符合规范，先关闭了。
