### ISSUE TITLE
功能性的优化希望知悉！

### ISSUE THREAD

**Issue by 91xtw** [youzan/vant-weapp#1502]
**核心代码**
请提供使用组件的核心代码
使用的组件panel->cell
```js
```

```wxml
```
    <block wx:if="{{ title }}">
     {{ title }}
      <view wx:if="{{ label }}" class="van-cell__label label-class">{{ label }}</view>
    </block>
改进后的。
```wxml
```
    <block wx:if="{{ title }}">
      <view class='v__title'>{{ title }}</view>  这里套个这样，title和label都可以单独通过样式控制了。
      <view wx:if="{{ label }}" class="van-cell__label label-class">{{ label }}</view>
    </block>

**问题说明 **
不知道你们设计这个组件的逻辑，但我想说的是。标题和label，是有多少就可以显示多少，我加上根类后控制多行省略。惊奇的发现你的title和label...title居然是直接输出文字，而没有外加view或者text组件，这样的弊端会导致label可能根样式控制，而title无法控制如你们上面代码；
我觉得改进后应该这样合理 ：

**Comment by rex-zsd** [comment]
vue版的vant已经修改成title和label分开了, vant-weapp下版本也会跟进的。

**Comment by 91xtw** [comment]
> vue版的vant已经修改成title和label分开了, vant-weapp下版本也会跟进的。

颜色配置，通局使用蓝色为主调，而不是每个组件调用一个公共的主色，如果要改颜色，必需 一个一个组件改，相当麻烦。

**Comment by rex-zsd** [comment]
受限于小程序的机制，主题定制暂时无法支持
