### ISSUE TITLE
当页面同时使用两个tab时点击切换后第二个tab的当前标签没有恢复到第一个

### ISSUE THREAD

**Issue by waikam** [youzan/vant-weapp#1503]
当页面使用两个tab时，点击第一个tab的时候第二个tab的内容会改变，这时候如果第二个tab的下标是1，然后我点击第一个tab从而第二个tab的内容改变，但是第二个tab的下标依然是1，并没有变成默认0，难道不是我每次点击第一个tab的时候，第二个tab的下标都是默认0吗？但是我在点击第一个tab的时候也有设置绑定的active为0，但是实际并没有效果

还有一个问题就是tabs的宽度不能根据内容自适应吗？感觉固定宽度超过了变成省略号的话有点不是很好，不知道是不是我没找到方法...

![image](https://user-images.githubusercontent.com/42863371/55859797-61336380-5ba5-11e9-94e7-3c562f2bdb4d.png)
![image](https://user-images.githubusercontent.com/42863371/55859956-bc655600-5ba5-11e9-8195-9bde39f26964.png)
![image](https://user-images.githubusercontent.com/42863371/55860071-00f0f180-5ba6-11e9-8ae6-592da7942aa6.png)

**Comment by rex-zsd** [comment]
目前请不要嵌套使用tabs组件。
因为tabs组件会在初始化时进行激活态的计算，嵌套使用时内部的tabs会有各种问题。

**Comment by rex-zsd** [comment]
另外从图中看下面的部分其实没有使用tab实现的必要，可以用多个按钮控制主体部分的显示。

**Comment by ouyang0010** [comment]
我现在也是嵌套使用的tabs 开启swipeable 手势滑动后，子级的滑动会触发父级滑动事件，本想用@touchmove.stop 但是并没有效果，请问大佬有好的方案嘛？求指点～谢谢（必须要嵌套哦，没法改动）
