### ISSUE TITLE
我想在自己的组件中再次封装vant组件，始终不起作用，在page中是有效的

### ISSUE THREAD

**Issue by mediasale** [youzan/vant-weapp#1507]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**对组件进行二次封装**
我想在自己的组件中再次封装vant组件，始终不起作用，在page中是有效的

**Comment by rex-zsd** [comment]
没明白具体的问题是什么，另开一个issue按格式提供足够的信息吧。
