### ISSUE TITLE
Dialog弹窗被原生组件覆盖

### ISSUE THREAD

**Issue by HoJun626** [youzan/vant-weapp#1511]
Dialog弹窗被canvas原生组件覆盖
![微信图片_20190412184449](https://user-images.githubusercontent.com/38808298/56031816-135c5e00-5d53-11e9-9489-b4837d2b4d1d.png)

**Comment by rex-zsd** [comment]
注意[原生组件的限制](https://developers.weixin.qq.com/miniprogram/dev/component/native-component.html#%E5%8E%9F%E7%94%9F%E7%BB%84%E4%BB%B6%E7%9A%84%E4%BD%BF%E7%94%A8%E9%99%90%E5%88%B6)
图片建议不要用canvas
