### ISSUE TITLE
Collapse折叠板，数据多了会很卡，影响用户体验

### ISSUE THREAD

**Issue by longchuan** [youzan/vant-weapp#1512]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**描述一下问题**
Collapse折叠板，数据多了会很卡，影响用户体验

**环境**
 - 设备:三星G9600
 - 基础库版本:2.6.4
 - Vant Weapp 版本:最新版

**Comment by longchuan** [comment]
看到源码里用到了数组遍历，这样肯定会卡。可以去掉数组遍历，手风琴模式，只需要记录两条就可以了，点击下一个的时候，关闭上一个。

**Comment by longchuan** [comment]
因为开启和关闭的原理我没有弄懂，所以一时也改不了代码。。。

**Comment by mynameismaosheng** [comment]
> 看到源码里用到了数组遍历，这样肯定会卡。可以去掉数组遍历，手风琴模式，只需要记录两条就可以了，点击下一个的时候，关闭上一个。

这个意思是异步获取数据吗?

**Comment by longchuan** [comment]
> > 看到源码里用到了数组遍历，这样肯定会卡。可以去掉数组遍历，手风琴模式，只需要记录两条就可以了，点击下一个的时候，关闭上一个。
> 
> 这个意思是异步获取数据吗?

不是。现在里面的方法是，用some进行遍历，然后数据匹配的就展开，不匹配的就关闭，这样肯定会卡呀。
