### ISSUE TITLE
按钮box-shadow在ios问题

### ISSUE THREAD

**Issue by sym134** [youzan/vant-weapp#1513]
我在按钮上增加了box-shadow属性，安卓没有任何问题，但是在ios上回退就会有问题
上一页的阴影回退以后依然在，只是阴影在，开发调试页看不到，但是刷新就没了
![image](https://user-images.githubusercontent.com/32946251/56092895-d16b1d80-5ef4-11e9-8728-f94c6ad17184.png)

返回以后
![image](https://user-images.githubusercontent.com/32946251/56092901-dc25b280-5ef4-11e9-8040-bf9e4f6ccb32.png)

**Comment by mynameismaosheng** [comment]
这个好像不是小程序吧?

**Comment by sym134** [comment]
> 这个好像不是小程序吧？

发错了……
