### ISSUE TITLE
新需求：van-goods-action-input

### ISSUE THREAD

**Issue by angerpeanut** [youzan/vant-weapp#1514]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**你需要的功能是？**
类似于van-goods-action-button，希望做一个van-goods-action-input，主要是用于一些评论场景

**你期望 API 是什么样的？**
把input的api集成到van-goods-action-input就行

**Comment by rex-zsd** [comment]
直接用`van-field`就可以了，不需要新增组件。
![image](https://user-images.githubusercontent.com/8767877/56103339-debff080-5f64-11e9-8197-33fe8273eeea.png)
