### ISSUE TITLE
构建npm成功之后，编译报错 : module "miniprogram_npm/vant-weapp/mixins/observer/props" is not defined

### ISSUE THREAD

**Issue by oloshe** [youzan/vant-weapp#1516]
命令行执行npm i vant-weapp -S --production
构建npm
有miniprogram_npm目录
编译提示报错：
module "miniprogram_npm/vant-weapp/mixins/observer/props" is not defined

![image](https://user-images.githubusercontent.com/40467840/56103857-78889d00-5f67-11e9-8723-2a1a24cb7af6.png)

 - 设备: windows 10 微信web开发者工具：（1.02.1902010）（当前最新）
 - 基础库版本: 2.6.5
 - Vant Weapp 版本: 0.5.10

**Comment by oloshe** [comment]
重新构建npm一次，解决了...

**Comment by a294974783** [comment]
我也遇到此问题，求大神解答，构建就出问题如此容易出的问题，是开发工具的问题还是ui本身的问题？
