### ISSUE TITLE
先把beforeCreate 改成created 又把 created改成 attached 不觉得很奇怪吗？

### ISSUE THREAD

**Issue by 9007967** [youzan/vant-weapp#1518]
`mapKeys(vantOptions, options, {
        data: 'data',
        props: 'properties',
        mixins: 'behaviors',
        methods: 'methods',
        beforeCreate: 'created',
        created: 'attached',
        mounted: 'ready',
        relations: 'relations',
        destroyed: 'detached',
        classes: 'externalClasses'
    });`

> 先把beforeCreate 改成created 又把 created改成 attached 不觉得很奇怪吗？

**Comment by rex-zsd** [comment]
为了对齐小程序与vue的生命周期。

**Comment by 9007967** [comment]
> 为了对齐小程序与vue的生命周期。

关键问题是造成了 picker-column 出现问题 导致 area显示内容为空

**Comment by rex-zsd** [comment]
那按照issue模板另开一个issue，详细说明一下问题吧。
会尽快修复的。
