### ISSUE TITLE
动态修改datePicker defaultIndex ，默认选中项不更新

### ISSUE THREAD

**Issue by tianyazjq** [youzan/vant-weapp#1519]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**你需要的功能是？**
描述一下你需要的功能，用于解决什么问题

**你期望 API 是什么样的？**
描述一下你期望的 API 形式

**示例代码**
请展示一下新功能的大致用法

```js
```
 onLoad: function (options) {
    let that = this;
    MembercontrollerApi.getMyInfoUsingGET(function (res) {
      app.handleApiFail(res, function () {
        let memberInfo = res.data.item;
        let pickerValue = that.data.pickerData0;
        pickerValue[0].defaultIndex = memberInfo.sex;
        console.log(pickerValue)
        that.setData({
          memberInfo: memberInfo,
          uploadHeadImgUrl: memberInfo.headImgPath,
          nickName: memberInfo.nickname,
          sex: memberInfo.sex,
          timeStampBirthday: memberInfo.birthdate,
          pickerData0: pickerValue
        });
      });
    });
  },
```wxml
```

<van-popup show="{{ sexPopShow }}" position="bottom" bind:close="onCloseSexPopup"   overlay="{{ true }}" close-on-click-overlay="{{false}}">
    <van-picker show-toolbar title="请选择性别" columns="{{ pickerData0 }}" bind:change="onSexChange" cancel="onCloseSexPopup" confirm="onSexConfirm" custom-class="picker-reset" />
</van-popup>

![image](https://user-images.githubusercontent.com/5754329/56109897-0f178700-5f85-11e9-8873-33f441eddf75.png)
![image](https://user-images.githubusercontent.com/5754329/56109903-12127780-5f85-11e9-9730-c6bf98fd70c9.png)

我动态设置 pickerValue[0].defaultIndex = memberInfo.sex;为男的，现在组件不选中！！！！！也没有refresh方法API或者自动更新选中项的功能。

**Comment by tianyazjq** [comment]
![image](https://user-images.githubusercontent.com/5754329/56109996-6ae21000-5f85-11e9-9df4-22a5e39ac38a.png)
只有初始化的时候才生效，动态修改defaultIndex不更新

**Comment by rex-zsd** [comment]
`defaultIndex`之所以叫`defaultIndex`就是因为只有初始化的时候才生效啊…………
动态修改还能生效的叫能`defaultIndex`吗？
如果需要动态修改激活项的请用picker的API。

**Comment by tianyazjq** [comment]
在异步里面直接去修改 oSexPicker.setValues([sexValues[sex]]);，这个是有bug的，执行顺序先执行组件内的created方法，然后在调用异步数据，这个不行的。
我现在是在popup打开完之后在去设值的是可以的

不过小程序一加载，直接去改选中的项，选不中的。这个也算是bug吧。

![image](https://user-images.githubusercontent.com/5754329/56135225-d9918e80-5fc2-11e9-9309-110e808a462e.png)

![image](https://user-images.githubusercontent.com/5754329/56135416-46a52400-5fc3-11e9-8f1f-08d01fbbc41c.png)
