### ISSUE TITLE
van-icon实底question没有问号

### ISSUE THREAD

**Issue by parallel-kevin** [youzan/vant-weapp#1522]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**描述一下问题**
实底Icon里question中间的问号缺失

**截图**
![image](https://user-images.githubusercontent.com/15011656/56119422-adfcad00-5f9e-11e9-8311-ae649470b558.png)

**核心代码**
请提供使用组件的核心代码

```js
```

```wxml
```

**环境**
 - 设备:荣耀Play
 - 基础库版本:
 - Vant Weapp 版本:0.5.10

**Comment by chenjiahan** [comment]
下个版本会修复

**Comment by chenjiahan** [comment]
已在 0.5.12 版本修复
