### ISSUE TITLE
tabs 组件宽度问题

### ISSUE THREAD

**Issue by Hugh-Shen** [youzan/vant-weapp#1525]
tabs 组件报无法获取宽度
![1555380304(1)](https://user-images.githubusercontent.com/45509602/56176876-20b56900-602f-11e9-93b0-8abcc16b05d6.jpg)

**环境**
 - 设备:
 - 基础库版本:
 - Vant Weapp 版本: v0.5.10 
 
![1555380120(1)](https://user-images.githubusercontent.com/45509602/56176845-fd8ab980-602e-11e9-8fef-b2fb49611fc4.jpg)

**Comment by chengaobin** [comment]
tabs多个tab页会相互影响，比如第一页向下滑动，切换到第二页后，第二页也会滑动了一段距离

**Comment by rex-zsd** [comment]
这个问题暂时没有好的办法，tabs的行为很依赖初始化时的rect计算。
只能建议不要把tabs嵌套使用，或者不要在页面初始化时隐藏tabs组件。
