### ISSUE TITLE
dateTimePicker什么没有自定义的custom-class啊，不支持自定义的class

### ISSUE THREAD

**Issue by tianyazjq** [youzan/vant-weapp#1526]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**你需要的功能是？**
描述一下你需要的功能，用于解决什么问题
dateTimePicker什么没有自定义的custom-class啊，不支持自定义的class
**你期望 API 是什么样的？**
描述一下你期望的 API 形式

**示例代码**
请展示一下新功能的大致用法
<van-datetime-picker type="date" title="请选择出生日期" value="{{ currentDate }}" min-date="{{ minDate }}"
                bind:input="onInput" custom-class="picker-reset" />
```js
```

```wxml
```
<van-datetime-picker type="date" title="请选择出生日期" value="{{ currentDate }}" min-date="{{ minDate }}"
                bind:input="onInput" custom-class="picker-reset" />
![image](https://user-images.githubusercontent.com/5754329/56177072-f6b07680-602f-11e9-8455-bedaa4a44075.png)

**Comment by tianyazjq** [comment]
![image](https://user-images.githubusercontent.com/5754329/56177138-324b4080-6030-11e9-82eb-ce1797a99429.png)

**Comment by tianyazjq** [comment]
<van-datetime-picker type="date" title="请选择出生日期" value="{{ currentDate }}" min-date="{{ minDate }}"
                bind:input="onInput" custom-class="picker-reset" />

**Comment by tianyazjq** [comment]
```
<van-datetime-picker type="date" title="请选择出生日期" value="{{ currentDate }}" min-date="{{ minDate }}"
                bind:input="onInput" custom-class="picker-reset" />
```

**Comment by rex-zsd** [comment]
为什么时间选择器需要外部样式类？

**Comment by tianyazjq** [comment]
![image](https://user-images.githubusercontent.com/5754329/56179527-9eca3d80-6038-11e9-894f-fc13732fd30c.png)
这种高度自定义就很难支持，建议参考滴滴 Mand Mobile的Picker这个设计API方面写的非常好

**Comment by tianyazjq** [comment]
![image](https://user-images.githubusercontent.com/5754329/56179575-c6b9a100-6038-11e9-8b8b-021bd516729f.png)

**Comment by rex-zsd** [comment]
Mand Mobile是vue的组件库，跟小程序不太一样。
看图其实你的需求是需要自定义format

**Comment by tianyazjq** [comment]
Mand Mobile应用在h5上面，不过都差不多，网页上面可以做到那么方便，小程序理论上也是可以搞那么方便的，现在vant Picker还是有很多体验不如意的地方。
```
<!-- pop up mask -->
<van-popup show="{{ sexPopShow }}" position="bottom" bind:close="onCloseSexPopup" overlay="{{ true }}"
    close-on-click-overlay="{{false}}">
    <van-picker id="van-picker" show-toolbar title="请选择性别" columns="{{ pickerData0 }}" custom-class="picker-reset"
        bind:cancel="onSexCancel" bind:confirm="onSexConfirm" />
</van-popup>
<!-- 生日Picker -->
<van-popup show="{{ datePopShow }}" position="bottom" bind:close="onCloseSexPopup" overlay="{{ true }}"
    close-on-click-overlay="{{false}}">
    <van-datetime-picker type="date" title="请选择出生日期" value="{{ currentDate }}" min-date="{{ minDate }}"
            max-date="{{ maxDate }}" bind:input="onInput" custom-class="picker-reset" />
</van-popup>

```
![image](https://user-images.githubusercontent.com/5754329/56179760-81e23a00-6039-11e9-83a5-ee599d74bf70.png)
![image](https://user-images.githubusercontent.com/5754329/56179781-94f50a00-6039-11e9-8e08-83241e7f71b7.png)
![image](https://user-images.githubusercontent.com/5754329/56179791-a0483580-6039-11e9-9b5b-6263e642111b.png)
我现在实现一个picker打开关闭要写一堆的代码，现在Picker可以在现有的基础上，结合日常的业务会好很多。
