### ISSUE TITLE
auth required for publishing

### ISSUE THREAD

**Issue by Pasoul** [youzan/vant-weapp#1531]
**描述一下问题**

通过'yarn release'发布组件库到npm，报错：`need auth auth required for publishing`，但是直接在项目根目录下执行`npm publish`却能成功发布，应该不是npm未登录的问题。

**截图**

![image](https://user-images.githubusercontent.com/22902187/56203524-00f66300-6078-11e9-809b-4423929125e4.png)

**Comment by rex-zsd** [comment]
跟vant-weapp无关的问题。
