### ISSUE TITLE
popup底部弹出时，被页面底部内容覆盖

### ISSUE THREAD

**Issue by liaolinyan2018** [youzan/vant-weapp#1532]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**描述一下问题**
弹出层被页面底部内容穿透。

**截图**
两张截图，一张是从底部弹出，被底部内容覆盖。另一张是从顶部弹出，很明显看出底部内容并没有被蒙层覆盖。
https://i.loli.net/2019/04/16/5cb5d75f3a714.png
https://i.loli.net/2019/04/16/5cb5d75f3ad01.png

**核心代码**
请提供使用组件的核心代码

```js
```
我是在这个页面引入了自己写的file组件，页面底部的内容是直接写在这个页面下的，然后file引入了set组件，set组件里面使用了vant-popup组件。

```wxml
```

**环境**
 - 设备:  苹果手机
 - 基础库版本:   
 - Vant Weapp 版本:  三周前clone的

**Comment by rex-zsd** [comment]
你自己写的组件层级比`van-popup`高？
用`zIndex`属性控制一下呗？

**Comment by liaolinyan2018** [comment]
> 你自己写的组件层级比`van-popup`高？
> 用`zIndex`属性控制一下呗？



> 你自己写的组件层级比`van-popup`高？
> 用`zIndex`属性控制一下呗？

在安卓手机上是正常的，所以我把我的弹层组件放在了最外面的页面里，然后它就可以覆盖整个页面里的内容了。
