### ISSUE TITLE
Stepper 录入小数点马上被还原成整数

### ISSUE THREAD

**Issue by 4cup** [youzan/vant-weapp#1533]
**描述一下问题**
Stepper组件，只要录入小数点，就会被还原成整数

**截图**
如果是 UI 问题，请提供具体截图
![1](https://user-images.githubusercontent.com/18362721/56254600-01344400-60f4-11e9-81bc-6e37da0c5250.jpg)

**核心代码**
请提供使用组件的核心代码

```js
```

```wxml
<van-stepper
        value="{{discount}}"
        min="0"
        max="10"
        step="0.1"
        bind:change="onDisChange"
      />
```

**环境**
 - 设备: 一加 6
 - 基础库版本: 2.6.5
 - Vant Weapp 版本: 0.5.1

**Comment by rex-zsd** [comment]
stepper目前不支持小数的。

**Comment by chenjiahan** [comment]
下个版本会修复

**Comment by chenjiahan** [comment]
已在 0.5.12 版本修复

**Comment by TobinXu** [comment]
@chenjiahan 该问题1.11.6又出现了
