### ISSUE TITLE
Dialog弹出框弹出时，其中的Field输入框会向下抖动

### ISSUE THREAD

**Issue by kapbook-caizhehao** [youzan/vant-weapp#1534]
问题类型：UI问题
描述：在Dialog 弹出框中有一个Field输入框，当弹出Dialog时，Field输入框会向下抖动。
代码：
![image](https://user-images.githubusercontent.com/38315632/56257749-eb2c8080-60ff-11e9-8003-190680206df2.png)
页面：
![image](https://user-images.githubusercontent.com/38315632/56257910-62621480-6100-11e9-92f9-f4fdab8103bd.png)

**Comment by rex-zsd** [comment]
将`transition`属性设置为`fade`或`none`即可。
