### ISSUE TITLE
部分手机 cell is-link 会造成页面空白

### ISSUE THREAD

**Issue by ghost** [youzan/vant-weapp#1537]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**描述一下问题**
测试了两个机型： iPhoneX 、小米mix-2s；
van-cell 设置 is-link 后，导致mix-2s上 整个页面都会空白，iPhoneX 正常
取消is-link 后 就完全正常了。

**环境**
 - 设备: 小米mix-2s
 - 基础库版本: 2.6.5
 - Vant Weapp 版本:0.5.9

**Comment by rex-zsd** [comment]
神奇 `is-link`只是增加一个图标的显示而已，按理是影响不了整个页面的渲染的。
