### ISSUE TITLE
area 还是不显示

### ISSUE THREAD

**Issue by caojianwei1991** [youzan/vant-weapp#1541]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**描述一下问题**
最新版本 0.5.10
 不多说了   在你的另一个项目里你解决了
就是初始化的时候
beforeCreate() {
    const { defaultIndex, initialOptions } = this.data;

    this.set({
      currentIndex: defaultIndex,
      options: initialOptions
    }).then(() => {
      this.setIndex(defaultIndex);
    });
  },

**截图**
如果是 UI 问题，请提供具体截图

**核心代码**
请提供使用组件的核心代码

```js
```

```wxml
```

**环境**
 - 设备:
 - 基础库版本:
 - Vant Weapp 版本:0.5.10

**Comment by caojianwei1991** [comment]
没解决的看一下吧。

**Comment by rex-zsd** [comment]
什么另一个项目？你的问题是什么？

**Comment by Ele-Cat** [comment]
调完areaList数据后把loading置为false就可以了

**Comment by rex-zsd** [comment]
根据另一个issue #1543 的描述信息可以复现相同问题，下版本修复。
