### ISSUE TITLE
tabbar 未适配 iPhone X，border-top 那条线和 icon 重叠了

### ISSUE THREAD

**Issue by zaxlct** [youzan/vant-weapp#1545]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**描述一下问题**
tabbar 未适配 iPhone X 

**截图**
![image](https://user-images.githubusercontent.com/14342431/56412250-1d7fde80-62b6-11e9-9875-e8595b344977.png)

**核心代码**
无

**环境**
 - 设备: iPhone X
 - 基础库版本: 微信 7.0 以上
 - Vant Weapp 版本: 0.5.10

**Comment by zaxlct** [comment]
https://github.com/youzan/vant-weapp/issues/977
不是说已经修复了，为什么又出现这个问题了。。。

**Comment by ChandlerVer5** [comment]
我最近在移植 vant组件 到taro时，发现该问题，应为css中定义了`height:50px`;
解决办法：自定义外部样式(通过custom-class)：
```css
height:auto;
padding:8px 0;
```
顺便@vant开发人员。

**Comment by zaxlct** [comment]
@ChandlerVer5 谢谢~

**Comment by rex-zsd** [comment]
是不是通过`custom-class`设置了`box-sizing: border-box;`？
默认盒子`height: 50px` `padding-bottom: 44px`是不会有问题的。

**Comment by zaxlct** [comment]
确实是全局设置了 box-sizing: border-box;

**Comment by rex-zsd** [comment]
额，这样的话应该不是vant-weapp的问题，外部样式影响了。
