### ISSUE TITLE
Stepper 步进器的输入框，从别的地方复制文字进去，会导致整个小程序报错，从而无法使用

### ISSUE THREAD

**Issue by flyweights** [youzan/vant-weapp#1546]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**描述一下问题**
Stepper 步进器的输入框，从别的地方复制文字进去，会导致整个小程序报错，从而无法使用

**截图**
![image](https://user-images.githubusercontent.com/12111609/56424401-add41880-62e2-11e9-97e9-abc386287bdc.png)

**核心代码**
没有

```js
```

```wxml
```

**环境**
 - 设备: iOS
 - 基础库版本: 2.6.5
 - Vant Weapp 版本:v0.5.10

**Comment by chenjiahan** [comment]
感谢反馈，下个版本会修复

**Comment by chenjiahan** [comment]
已在 0.5.12 版本修复
