### ISSUE TITLE
提供megalo版本

### ISSUE THREAD

**Issue by wangzhengbo** [youzan/vant-weapp#1547]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**你需要的功能是？**
megalo是网易提供的基于vue的类mpvue的小程序框架，使用了vue语法。
vant-weapp目前能直接在megalo项目中用，但是vant-weapp的每一个组件
在使用的时候都需要全局或者局部的通过usingComponents的方式引入，
如果直接提供vue语法的megalo版本，就能import组件，在使用分包
的情况下，就不需要单独的指定每个分包依赖的vant-weapp组件。

**你期望 API 是什么样的？**
描述一下你期望的 API 形式

**示例代码**
请展示一下新功能的大致用法

```js
```

```wxml
```

**Comment by rex-zsd** [comment]
目前不会考虑提供，小程序框架数量太多。
