### ISSUE TITLE
cell的title自定义时，label不显示

### ISSUE THREAD

**Issue by ChinaFanny** [youzan/vant-weapp#1554]
**描述一下问题**
使用van-cell时，title自定义时，设置的label不显示

**截图**
<img width="991" alt="WX20190423-115213@2x" src="https://user-images.githubusercontent.com/22438061/56552554-422dcc00-65be-11e9-929c-2d89e8546529.png">

**核心代码**
查看dist中cell的wxml文件，发现：当使用slot=title时，没有做label的处理

<img width="619" alt="WX20190423-115421@2x" src="https://user-images.githubusercontent.com/22438061/56552676-96d14700-65be-11e9-9aea-fd412e29db47.png">

修改为如下可现实label：
<img width="991" alt="WX20190423-115655@2x" src="https://user-images.githubusercontent.com/22438061/56552781-eadc2b80-65be-11e9-860d-354835e45539.png">

**环境**
 - 设备:iOS
 - 基础库版本:2.5.1
 - Vant Weapp 版本:v0.5.10

**Comment by rex-zsd** [comment]
之前的版本是这么处理的，最近调整了 #1510 下版本会发布
