### ISSUE TITLE
SubmitBar 提交订单栏 没有全选按钮

### ISSUE THREAD

**Issue by JHeLiu** [youzan/vant-weapp#1561]
https://youzan.github.io/vant-weapp/#/submit-bar

已经查看了组件源代码 也没见有 全选按钮这个

![image](https://user-images.githubusercontent.com/15246138/56642977-44218900-66ab-11e9-913c-9031e619104f.png)

**Comment by rex-zsd** [comment]
全选按钮是通过插槽自己插入的，文档上有写。

**Comment by JHeLiu** [comment]
好的，我自己加入插件去 了，
