### ISSUE TITLE
notify无法弹出

### ISSUE THREAD

**Issue by hnty545** [youzan/vant-weapp#1562]
最新版本0.5.11
断点到这里，也走了show，但是界面并没有弹出来，也有div
<van-notify id="van-notify" :custom-style="customStyle"/>

0.5.3还可以的，升级就不行了

![image](https://user-images.githubusercontent.com/6417805/56643936-4258c500-66ad-11e9-92eb-0b6d90ff270c.png)

**Comment by hnty545** [comment]
知道问题了，是被状态栏挡住了，之前可不是这样，是z-index的问题吗

![image](https://user-images.githubusercontent.com/6417805/56649222-4e498480-66b7-11e9-90ef-f628609b65c0.png)

**Comment by rex-zsd** [comment]
notify有zIndex属性，如果是层级问题可以用这个属性控制。
