### ISSUE TITLE
tabbar 点击切换时能不能先进行一些判断，条件不满足时，不切换tab，还在当前tab上

### ISSUE THREAD

**Issue by ChinaFanny** [youzan/vant-weapp#1564]
**你需要的功能是？**
tabbar 点击切换时能不能先进行一些判断，条件不满足时，不切换tab，还在当前tab上，如active当前为0，点击第二个item时，做判断，条件不满足时，返回当前tab（activie为0的tab），activie为1的tab图标和字体不改变颜色

**Comment by chenjiahan** [comment]
暂时没计划支持这个功能喔
