### ISSUE TITLE
NoticeBar取消不了滚动；用不多行显示

### ISSUE THREAD

**Issue by 80Arrow** [youzan/vant-weapp#1568]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**描述一下问题**
NoticeBar；scrollable="false" 还是滚动；没有多行显示

**截图**
![image](https://user-images.githubusercontent.com/7716081/56729834-c6cc4600-6788-11e9-9d01-6f8a0d5183e8.png)

**核心代码**
<van-notice-bar wrapable="true" scrollable="false" text="足协杯战线连续第2年上演广州德比战，上赛季半决赛上恒大以两回合5-3的总比分淘汰富力。" />

```js
```

```wxml
```
<van-notice-bar wrapable="true" scrollable="false" text="足协杯战线连续第2年上演广州德比战，上赛季半决赛上恒大以两回合5-3的总比分淘汰富力。" />

**环境**
 - 设备:开发者工具
 - 基础库版本:2.6.5
 - Vant Weapp 版本:

**Comment by rex-zsd** [comment]
注意一下是`scrollable="{{ false }}"`
`wrapable`属性是vant近几个版本增加的，vant-weapp暂未支持。
