### ISSUE TITLE
表单placeholder 遮挡

### ISSUE THREAD

**Issue by Ziazan** [youzan/vant-weapp#1569]
**问题**
在使用表单组件，设置placeholde。如果页面有弹出层的话，placeholder 的显示层级会更高，会遮挡。

**截图**
![image](https://user-images.githubusercontent.com/11722002/56778962-7518cf80-680b-11e9-977a-d1bc2e5eba1d.png)

**核心代码**

```wxml

<van-cell-group>
  <van-field
    value="{{ value }}"
    placeholder="请输入用户名"
    border="{{ false }}"
    bind:change="onChange"
  />
</van-cell-group>

<van-popup show="{{ show }}" bind:close="onClose">内容</van-popup>
```

**环境**
 - Vant Weapp 版本:最新

**Comment by rex-zsd** [comment]
https://developers.weixin.qq.com/miniprogram/dev/component/native-component.html
原生组件了解一下
