### ISSUE TITLE
官方是否可以增加scroll-view下拉刷新的模块

### ISSUE THREAD

**Issue by 9007967** [youzan/vant-weapp#1570]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**你需要的功能是？**
官方是否可以增加scroll-view下拉刷新的模块

**你期望 API 是什么样的？**
描述一下你期望的 API 形式

**示例代码**
请展示一下新功能的大致用法

```js
```

```wxml
```

**Comment by rex-zsd** [comment]
目前不会考虑，小程序本身就有下拉刷新的API。
