### ISSUE TITLE
vant-weapp   Slider 组件文档中有垂直方向 但是属性或者propsl里并没有提供参数可以配置

### ISSUE THREAD

**Issue by jahnli** [youzan/vant-weapp#1571]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**描述一下问题**
描述一下你遇到的问题，包括复现方式、导致结果
vant-weapp   Slider 组件文档中有垂直方向 但是属性或者propsl里并没有提供参数可以配置
**截图**
如果是 UI 问题，请提供具体截图
![image](https://user-images.githubusercontent.com/20943608/56784640-20ce1980-6824-11e9-9458-dca8ef6989a5.png)

**核心代码**
请提供使用组件的核心代码

```js
```

```wxml
```

**环境**
 - 设备:
 - 基础库版本:
 - Vant Weapp 版本:

**Comment by chenjiahan** [comment]
此处是文档疏漏，目前小程序暂不支持垂直方向，文档已更新
