### ISSUE TITLE
Search 组件高级模式点击触发查询事件失效

### ISSUE THREAD

**Issue by zhencc1023** [youzan/vant-weapp#1572]
Search 组件，使用 use-action-slot    点击搜索  bind:search   事件无效。
*注: 之前是点击有效，但是   event.detail  中没有value的值，只有xy坐标值
但是  使用  show-action   可以取到，开启  use-action-slot  取不到值，而且，突然搜索事件绑定不触发了，清缓存，重载都无效
**截图**

**核心代码**

```js
```
 /**
   * 查询
   */
  onSearch: function (e) {
    var params = this.data.columns[this.data.index];
    var code = params === undefined ? '' : params.id
    ;
    var val = e.detail;
   }
```wxml
<van-search
  value="{{ val }}"
  placeholder="请输入订单号"
  use-action-slot=true
  bind:search="onSearch"> 
  <view slot="action" bind:tab="onSearch">搜索</view>
</van-search>
</view>

**环境**
 - 微信开发者工具:
 - 基础库版本:
 - Vant Weapp 版本:

**Comment by aQingYun** [comment]
use-action-slot="{{true}}"或者use-action-slot

**Comment by vancenx** [comment]
因为你点击slot中搜索按钮执行onSearch方法时，type为tap，而不是search
![image](https://user-images.githubusercontent.com/36067335/69959380-fa9ef380-1541-11ea-9dc9-fe77a6f04866.png)
type为search时才能获取到内容（点击自带键盘中的搜索）
![image](https://user-images.githubusercontent.com/36067335/69959497-405bbc00-1542-11ea-89a3-a9605e96e5b1.png)
