### ISSUE TITLE
switch在微信小程序中显示异常

### ISSUE THREAD

**Issue by fafala** [youzan/vant-weapp#1575]
异常：switch图标显示异常

截图:
![image](https://user-images.githubusercontent.com/12274717/56858126-d4134b80-69a7-11e9-8f9f-a3394e624cbd.png)

**核心代码**
`<style lang="less" scoped>
  .container {
    display: flex;
    flex-direction: column;
  }
  .view_item {
    width: 100%
  }
</style>

<template>
  <view class="container">
    <view class="view_item">
      <van-switch checked="{{ checked }}" bind:change="onChange" />
      <van-switch-cell title="标题" loading="{{true}}" checked="{{ checked }}" bind:change="onChange" />
      <van-switch-cell title="标题" checked="{{ checked }}" bind:change="onChange" />
      <van-switch-cell title="标题" checked="{{ checked }}" bind:change="onChange" />
      <van-switch-cell title="标题" checked="{{ checked }}" bind:change="onChange" />
    </view>
  </view>
</template>

<script>
  import wepy from 'wepy';
  export default class Approval extends wepy.page {
    config = {
      navigationBarTitleText: '设置'
    }
    data = {
      checked:false,
      param:{
        
      }
    }
    onChange(e){
      this.checked = e.detail;
    }
  }
</script>
`

**环境**
 - 设备:windows7开发者工具，ios
 - 基础库版本: 小程序调试基础库：2.6.6
 - Vant Weapp 版本: "vant-weapp": "^0.5.11",

**Comment by zhushuai662** [comment]
这个问题我也碰到了，有解决吗？
