### ISSUE TITLE
DatetimePikcer 选择2019年的时候 月份显示不全

### ISSUE THREAD

**Issue by wjf9492** [youzan/vant-weapp#1580]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**描述一下问题**
DatetimePikcer 选择2019年的时候 没有12月份，在demo中可以复现。

**截图**
![image](https://user-images.githubusercontent.com/24648326/56861070-1cdefa80-69d0-11e9-8ad9-a92a2ecab8df.png)

**核心代码**
请提供使用组件的核心代码

```js
```

```wxml
```

**环境**
 - 设备:
 - 基础库版本:
 - Vant Weapp 版本:

**Comment by chenjiahan** [comment]
不是 bug，demo 设置了 maxDate 属性的
