### ISSUE TITLE
[Feature Request] field组件对password的支持

### ISSUE THREAD

**Issue by hnty545** [youzan/vant-weapp#1581]
源生input组件的password是控制是否密码掩码的，但是field组件没有对这个的支持，本来想在type上做文章，但是不可以用，查阅官方文档type的合法值没有password的，所以应该要加上对password字段的支持

**Comment by chenjiahan** [comment]
下个版本会支持

**Comment by chenjiahan** [comment]
已在 0.5.12 版本支持

**Comment by wangning411222** [comment]
按照官方文档示例.表单使用type="password"时.获取到的输入的值为"******",根本获取不到输入的值
