### ISSUE TITLE
goodsAction的info只显示了1/4（疑似与wxParse样式冲突）

### ISSUE THREAD

**Issue by Rebuilding127** [youzan/vant-weapp#1582]
**描述一下问题**
从github下载源码包引入项目使用，info内容只显示了左下部分1/4内容。
另外还使用开源组件wxParse用于解析html内容。
由于wxParse中全局定义了view的样式，可能引起样式冲突。
但是在`.van-info`中加入`overflow: visible;`没有效果

**截图**
![图片](https://user-images.githubusercontent.com/26793016/56862096-df7f6a80-69d9-11e9-9452-6fca57392aff.png)

下面这是开发工具中的调试截图

![图片](https://user-images.githubusercontent.com/26793016/56862301-266e5f80-69dc-11e9-9468-cffdf6d81eb8.png)

![图片](https://user-images.githubusercontent.com/26793016/56862312-44d45b00-69dc-11e9-82c8-886ea683f3f4.png)

**核心代码**
正常示例使用，未做任何修改

**环境**
 - 设备: Iphone8 Plus
 - 基础库版本:
 - Vant Weapp 版本: 0.5.8

**Comment by chenjiahan** [comment]
wxParse 这个全局样式显然是有很大问题的，建议不要这样引入，或者去他们的仓库下提 issue
