### ISSUE TITLE
Layout组件设置gutter无效

### ISSUE THREAD

**Issue by qinqinany** [youzan/vant-weapp#1587]
van-row设置gutter=20后，没有效果
效果截图：
![QQ截图20190429151128](https://user-images.githubusercontent.com/1768599/56880916-24b2a380-6a91-11e9-85ff-f75f3df128df.png)

**核心代码**
![QQ截图20190429151229](https://user-images.githubusercontent.com/1768599/56880999-8246f000-6a91-11e9-89c4-f0d49655adfc.png)

样式代码：
.van-col {
  color: white;
  margin-top: 0.5rem;
  padding: 8px 0;
  font-size: 0.75rem;
  text-align: center;
}
.col-even view{
  background: #3497DA;
}
.col-odd view {    background: #19B5FF;}

**环境**
 - 设备:
 - "libVersion": "2.6.6",
 - Vant Weapp 版本:0.5.11

**Comment by chenjiahan** [comment]
示例代码运行是没问题的，建议看下是不是用法有问题，可以把你的 wxml 代码贴一下

**Comment by maggie-chen** [comment]
同问，gutter失效 
`
<van-row gutter="20">
            <van-col wx:for="{{item.second}}" wx:for-item="second" wx:for-index="secondindex" wx:key="{{second.id}}" custom-class="popup-second-item {{second.active?'active':''}}" span="8" data-index="{{index}}" data-secondindex="{{secondindex}}" bindtap="selectCategorys">
              {{second.name}}
            </van-col>
          </van-row>
`

**Comment by hanwenbo** [comment]
无效
