### ISSUE TITLE
请教小程序版van-field如何搭配van-popup?

### ISSUE THREAD

**Issue by StephenKare** [youzan/vant-weapp#1588]
很抱歉,刚刚接触!能力有限,文档看了很多次,尝试了很多次,没有找到比较完美办法通过 van-field通过一个click触发van-popup!
目前使用了
`<van-field value="{{ catevalue }}" required clearable label="商品分类" placeholder="选择商品分类" size="large" data-type="cate" bind:focus="dochoosecate" is-link />`
通过bind:focus来"实现"点击效果! 求教! 谢谢了

**Comment by chenjiahan** [comment]
直接绑定`tap`事件即可，不需要通过`focus`喔

```html
<van-field
  label="用户名"
  readonly
  bind:tap="showPopup"
/>
```
