### ISSUE TITLE
[Feature Request] Dialog的宽度设置

### ISSUE THREAD

**Issue by qiuxiaojian** [youzan/vant-weapp#1592]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**你需要的功能是？**
弹出框没有办法设置宽度属性，有时候设计稿的宽度不一，很难直接使用

**你期望 API 是什么样的？**
希望添加一个可以设置弹出框的类，科按需要进行修改

**示例代码**

```js
```

```wxml
```

**Comment by chenjiahan** [comment]
下个版本会支持

**Comment by chenjiahan** [comment]
已在 0.5.12 版本支持 `className` 属性
