### ISSUE TITLE
van-stepper 的点击事件会传递给父层级

### ISSUE THREAD

**Issue by LiuJinGH** [youzan/vant-weapp#1594]
**描述一下问题**
van-stepper 的点击事件会传递给父层级，会导致对van-stepper点击时，同时触发van-stepper事件和父层级的事件

**核心代码**
比如在van-checkbox 里面套用van-stepper 时，对van-stepper 进行点击，会同时触发van-checkbox的事件，这是不合理的。
```js
eidtNumber: function (e){
    console.log(e)
  },
allCheckIndex: function (e){
    console.log(e)
  }
```

```wxml
<van-checkbox  bind:change="allCheckIndex" >
    <van-card  >
      <view slot="footer">
        <van-stepper bind:change="eidtNumber"/>
      </view>
    </van-card>
  </van-checkbox>
```

**环境**
 - 设备: 小程序IDE的模拟器
 - 基础库版本: 2.6.6
 - Vant Weapp 版本:  0.5.11

**Comment by LiuJinGH** [comment]
UI界面
![image](https://user-images.githubusercontent.com/18226613/57191021-92f4db80-6f53-11e9-949a-aedb4baa9749.png)

**Comment by chenjiahan** [comment]
并没有不合理，本身点击事件就是可以冒泡的，如果你不想要冒泡，在容器上添加 `catch:tap` 即可

**Comment by LiuJinGH** [comment]
@chenjiahan 
```
<van-checkbox  catch:change="allCheckIndex" >
    <van-card  >
      <view slot="footer">
        <van-stepper catch:change="eidtNumber"/>
      </view>
    </van-card>
  </van-checkbox>
```
改成这样子了，但是还是会同时触发allCheckIndex事件和eidtNumber事件

**Comment by LiuJinGH** [comment]
@chenjiahan 
```
<van-stepper capture-catch="eidtNumber"/>
```
使用这个调起函数就解决，谢谢解答。

**Comment by Lanceff** [comment]
@LiuJinGH 没用
