### ISSUE TITLE
vant-weapp 官网文档 中 Search 组件缺少 change 方法

### ISSUE THREAD

**Issue by IdenPin** [youzan/vant-weapp#1596]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**描述一下问题**
描述一下你遇到的问题，包括复现方式、导致结果

**截图**
![image](https://user-images.githubusercontent.com/8908021/57191497-11a04780-6f59-11e9-9035-13a463395325.png)

**核心代码**
请提供使用组件的核心代码

```js
<van-search value="{{ proName }}" placeholder="搜索项目名称" bind:change="onSearchChange" use-action-slot bind:search="getProList">
      <view slot="action" bind:tap="getProList">搜索</view>
    </van-search>
```

```wxml
```

**环境**
 - 设备:
 - 基础库版本: 最新版本
 - Vant Weapp 版本: 最新官网文档

**Comment by chenjiahan** [comment]
在底部的 Event 表格中有说明 change 方法的
