### ISSUE TITLE
Collapse折叠板点击无变化 bug

### ISSUE THREAD

**Issue by Levxn7** [youzan/vant-weapp#1597]
**描述一下问题**
 手风琴文档中data 里的字段与 satdata 里的字段不同
一个是activeName，一个是activeNames
导致点击无效

**截图**
![image](https://user-images.githubusercontent.com/24467846/57191583-ca668680-6f59-11e9-9e75-e60fe32cdb95.png)

**环境**
 - Vant Weapp 版本:0.5.11

**Comment by chenjiahan** [comment]
感谢反馈，此处已更正，文档会在近日更新
