### ISSUE TITLE
小程序官方demo中tab切换时偶尔会闪屏

### ISSUE THREAD

**Issue by Linbiiiin** [youzan/vant-weapp#1605]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**描述一下问题**
官方Demo中的tab组件多次切换的时候会有闪屏现象
**截图**
如果是 UI 问题，请提供具体截图

**核心代码**
请提供使用组件的核心代码

```js
```

```wxml
```

**环境**
 - 设备: 小米8微信小程序
 - 基础库版本:
 - Vant Weapp 版本:  0.5.12

**Comment by superlbr** [comment]
点击其中一个tab，可能会切换到临近的tab上

**Comment by MoonCheung** [comment]
我有类似情况和您描述问题一样，怎么解决tab组件多次切换闪屏的

**Comment by Linbiiiin** [comment]
我用swiper自己封装了一个tabs

**Comment by MoonCheung** [comment]
@Linbiiiin 是swiper怎么封装tabs呢

**Comment by Linbiiiin** [comment]
你可以去看看小程序官方文档结合swiper组件和swiper-item，自己写一个tab切换用activeIdex来控制当前的swiper应该怎么显示。

**Comment by MoonCheung** [comment]
我的tab里放入scroll-view用来切换上线之后出现有闪屏现象，暂时不考虑结合swiper组件和swiper-item

**Comment by daidaishuiping** [comment]
我也有闪动现象啊，怎么搞哦

**Comment by xuhao408** [comment]
我也遇到了同样的问题，然后特意体验了vant-weapp给出的样例，其在切换tab页时，会出现闪屏现象，体验很差。同时我也体验了iViewUI，Taro UI，ColorUI组件，均无此问题，希望官方尽快解决更新呀!!!

**Comment by xuhao408** [comment]
> 我也有闪动现象啊，怎么搞哦
闪动问题你解决了吗？
