### ISSUE TITLE
tab 文字过长显示不全

### ISSUE THREAD

**Issue by zs1040466634** [youzan/vant-weapp#1607]
tab 文字过长显示不全
**截图**
![image](https://user-images.githubusercontent.com/23735986/57213587-de71bd00-7019-11e9-9564-e32e54ee299e.png)

**核心代码**
data: {
    titleNames: [
      '剪板机刀片',
      '折弯机刀片',
      '卷板机刀片',
      '折弯机刀片片',
      '卷板机刀片',
      '折弯机刀片',
      '卷板机刀片',
    ],
    active: 1
  },
  onChange(event) {
    wx.showToast({
      title: `切换到标签 ${event.detail.index + 1}`,
      icon: 'none'
    });

  },
```js
```

<van-tabs animated="true" swipeable="true" sticky="true" duration="0.1" color="#1296db" bind:change="onChange" >
  <van-tab title="{{item}}" wx:for="{{titleNames}}" wx:key>{{item}}的内容</van-tab>
</van-tabs>
```wxml
```

**环境**
 - 设备: iPhone7
 - 基础库版本: 2.6.6
 - Vant Weapp 版本:

**Comment by zs1040466634** [comment]
Vant Weapp 版本:0.5.12

**Comment by rex-zsd** [comment]
为了防止标签过长做的样式处理。
可以通过外部样式类`tab-class`自定义。
```
.tab-class {
  flex: none !important;
}
```

**Comment by zs1040466634** [comment]
好的，谢谢
