### ISSUE TITLE
小程序使用van-progress，百分比无效

### ISSUE THREAD

**Issue by yangxiong** [youzan/vant-weapp#1609]
**问题描述** 
 第一个van-tab里面引入van-progress，百分比设置正常，在第二个van-tab开始引入van-progress，百分比设置无效。
**截图** 
![image](https://user-images.githubusercontent.com/4617206/57345689-5953e880-717e-11e9-904a-1fed0678dda9.png)

![image](https://user-images.githubusercontent.com/4617206/57345711-6a9cf500-717e-11e9-8268-e421567c9982.png)

**核心代码** 
 <van-progress custom-class="progress" percentage="50" show-pivot="{{false}}" color="linear-gradient(to right, #F0DA58, #F00102)" />

**环境** 
小程序ide

**Comment by Minisal** [comment]
出现同样的问题。
progress在van-tab组件下无法正常使用。
应该是progress下函数
getWidth() {        }
出现了问题。
对于未被激活的van-tab下的进度条，获取到的progressWidth和pivotWidth均为0，导致进度条无法正常加载
希望官方早日修复这个BUG QAQ

**Comment by rex-zsd** [comment]
是的，初始化的时候会计算宽度，一开始隐藏的话就会不正常。

**Comment by pipicoming** [comment]
> 是的，初始化的时候会计算宽度，一开始隐藏的话就会不正常。

什么时候修复？

**Comment by HermioneZeng** [comment]
我的是在popup里面使用，百分比无效，望尽快修复
