### ISSUE TITLE
循环radio后，radio内容区域点击有效，直接点击radio无效

### ISSUE THREAD

**Issue by kapbook-caizhehao** [youzan/vant-weapp#1610]
![image](https://user-images.githubusercontent.com/38315632/57347666-a6878880-7185-11e9-8234-9e6bfe133acd.png)
问题：点击红框区域，radio能被勾选上，而点击蓝框radio区域，radio则不能被勾选。
    注：点击蓝框radio区域时，监听onChange方法，该方法正常执行，但页面上radio无法被勾选。
代码：
![image](https://user-images.githubusercontent.com/38315632/57347931-c4092200-7186-11e9-8215-f3fbb1aef6d5.png)

**Comment by kapbook-caizhehao** [comment]
问题：radio内容区域点击有效，直接点击radio无效
补充：经重新验证，是因循环radio出现了该问题。代码如下：
![image](https://user-images.githubusercontent.com/38315632/57595302-c4366280-7576-11e9-875d-ac608c19fd4c.png)

**Comment by kapbook-caizhehao** [comment]
临时解决方案：将onRadioChange方法接收到的值转化为Int类型再赋值给radioCheck

**Comment by rex-zsd** [comment]
demo中尝试循环radio没复现，可能是wepy框架下特有的问题。

**Comment by rex-zsd** [comment]
> 临时解决方案：将onRadioChange方法接收到的值转化为Int类型再赋值给radioCheck

wepy中也没复现问题。
这个解决方案没太看明白，change事件接收到的值是需要赋值给value的呀。
