### ISSUE TITLE
tabs内容过多滑动会相互影响

### ISSUE THREAD

**Issue by chengaobin** [youzan/vant-weapp#1612]
tabs多个tab页会相互影响，比如第一页向下滑动，切换到第二页后，第二页也会滑动了一段距离

**Comment by lzpswat** [comment]
你好，你可以滑动切换tabs吗？我想问一下你是怎么设置的，我加了swipeable后没有反应

**Comment by rex-zsd** [comment]
#1867
跟这个是相同的问题
