### ISSUE TITLE
popup 组件中的 close-on-click-overlay 失效

### ISSUE THREAD

**Issue by ahan** [youzan/vant-weapp#1613]
**描述一下问题**
在文档中，popup 组件中的 close-on-click-overlay 默认值是 true，即点击蒙层会关闭 Popup。
但实际测试点击蒙层是没有关闭 popup 的。

**截图**

**核心代码**
```wxml
<van-popup show="{{ show }}">内容</van-popup>
```

**环境**
 - 设备: 开发者工具
 - 基础库版本: 2.0.0
 - Vant Weapp 版本: 0.15.12

**Comment by rex-zsd** [comment]
demo测试没问题，看下是不是没有处理`close`事件。

**Comment by ahan** [comment]
> demo测试没问题，看下是不是没有处理`close`事件。

意思是说 `close` 事件是必配项是吗？

官方文档中是这样写：`close-on-click-overlay | 点击蒙层是否关闭 Popup`

我理解是点击蒙层会自动关闭 `popup`，而 `close` 事件是给需要有额外业务逻辑的钩子。
看来可能我理解错了。

文档会不会需要更改下，注明 `close` 事件是必配项？

**Comment by ethanbing** [comment]
我也遇到了在mpvue里用  Popup和ActionSheet都有这个问题，点击蒙版和取消都是无效
有解决办法吗？？

**Comment by zhoufanglu** [comment]
> 我也遇到了在mpvue里用 Popup和ActionSheet都有这个问题，点击蒙版和取消都是无效
> 有解决办法吗？？

` bind:close="onClose" ` 加上这个事件就好了

**Comment by kid1412621** [comment]
> @rex-zsd 意思是说 `close` 事件是必配项是吗？
> 
> 官方文档中是这样写：`close-on-click-overlay | 点击蒙层是否关闭 Popup`
> 
> 我理解是点击蒙层会自动关闭 `popup`，而 `close` 事件是给有额外业务逻辑用的钩子。
> 
> 还有就是在 `Dialog` 组件中，给 `close-on-click-overlay` 设置 `true` 是会自动关闭弹窗，无需配置 `close` 事件
> 
> 似乎 `Poupu` 和 `Dialog` 的 `close-on-click-overlay` 所表现的行为不一样，是否 `popup` 需要修改下？

+1, 这里文档确实挺模糊的, 我也理解产生了偏差

**Comment by 343195246** [comment]
求解,为也遇到了这个问题.

**Comment by CrazyRoy** [comment]
:close-on-click-overlay=false 即可

**Comment by BowenHero** [comment]
vant ui 2.10.13 ActionSheet :close-on-click-overlay=false 依然不好用

**Comment by rex-zsd** [comment]
`close-on-click-overlay` 会触发关闭事件，但是事件还是需要手动处理的哈。

**Comment by jmsdqwl** [comment]
真是的 文档表述有问题
