### ISSUE TITLE
tabbar 无法通过设置border消除白边

### ISSUE THREAD

**Issue by xuuexu** [youzan/vant-weapp#1614]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**描述一下问题**
描述一下你遇到的问题，包括复现方式、导致结果

将背景色调成暗色就很容易注意到上下有白边，通过为tabbar和tabbar-item设置border可以区分出，**这个白边并不属于这两个组件的border**。

同时已经设置为 `border= {{false}}`

查看编译后的源码也没有找到可以修改的地方:(

如何复现：将页面背景色和tabbar背景色调成暗色调就可以。

**截图**
如果是 UI 问题，请提供具体截图

<img width="351" alt="Screen Shot 2019-05-08 at 5 23 01 PM" src="https://user-images.githubusercontent.com/31076337/57364670-40672980-71b6-11e9-92e6-7e5b2083555c.png">

<img width="375" alt="892C829C69D9E09C5C38A05492EBDCDD" src="https://user-images.githubusercontent.com/31076337/57365039-e6b32f00-71b6-11e9-8942-95cf704db5d5.png">

**核心代码**
请提供使用组件的核心代码

```js
```

```wxml

```

**环境**
 - 设备: iPhone 6s
 - 基础库版本: 
 - Vant Weapp 版本: lastest v0.5.12

**Comment by chenjiahan** [comment]
下个版本会加个 border 属性

**Comment by rex-zsd** [comment]
#1649 已支持
