### ISSUE TITLE
formatter	选项格式化函数 报错

### ISSUE THREAD

**Issue by shi995548347** [youzan/vant-weapp#1615]
thirdScriptError
formatter is not a function; [Component] Lifetime Method Error @ static/vant/datetime-picker/index#created
TypeError: formatter is not a function

**Comment by rex-zsd** [comment]
issue不符合规范，未提供核心代码

**Comment by luckymore** [comment]
@shi995548347   formatter is not a function, 没定义呀

**Comment by towry** [comment]
@rex-zsd 我也碰到了

**Comment by towry** [comment]
原来有类似 issue的，怎么到现在还没解决。。。

https://github.com/youzan/vant-weapp/issues/1627

**Comment by towry** [comment]
我的天，这个 bug 能不能修掉。

https://github.com/youzan/vant-weapp/issues/3140

**Comment by shi-nn** [comment]
你好 累不累  换个ui框架 祝好

**Comment by towry** [comment]
master 分支下，dist 和 lib 的代码不一样。

dist 目录： https://github.com/youzan/vant-weapp/blob/1bbf13addee94df9f77f7ff3d8f740c19e3e64a3/dist/datetime-picker/index.js#L115

lib 目录：https://github.com/youzan/vant-weapp/blob/1bbf13addee94df9f77f7ff3d8f740c19e3e64a3/lib/datetime-picker/index.js#L152

**Comment by towry** [comment]
> 你好 累不累 换个ui框架 祝好

我在解决问题，你在放什么屁？都入坑了拿你妹换？
