### ISSUE TITLE
picker需要增加一下range-key属性

### ISSUE THREAD

**Issue by mynameismaosheng** [youzan/vant-weapp#1619]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**你需要的功能是？**
如果columns里的value是  [{id:1,name:'123'}]这种形式, 就需要处理一下 而一般用这个东西的时候 都会是这种数据格式,. 可否和微信小程序的picker一样有一个 range-key

**你期望 API 是什么样的？**
https://developers.weixin.qq.com/miniprogram/dev/component/picker.html

**Comment by rex-zsd** [comment]
文档中有`value-key`，可以达成你要的效果。

**Comment by wenjayliu** [comment]
多选的时候好像不行 

例如：
```js
    columns: [{
      key: 1,
      values: [{text: '全部项目', value: 1}, {text: 'dfdf', value: 1},{text: 'dfdfd', value: 1}]
    },
    {
      key: 2,
      values: [{text: '立柱', value: 1}, {text: '堆场', value: 1}]
    }]

```
