### ISSUE TITLE
tabs 组件问题

### ISSUE THREAD

**Issue by lliuyang** [youzan/vant-weapp#1624]
**你需要的功能是？**

滑动tab里的内容 tab吸顶的api不够全面且bind:scroll 无法使用

bind:scroll	滚动时触发	{ scrollTop: 距离顶部位置, isFixed: 是否吸顶 }

**你期望 API 是什么样的？**

详细事件说明文档

**Comment by rex-zsd** [comment]
不够全面指的是？
