### ISSUE TITLE
希望官方提供一个van-tabbar的案例教程

### ISSUE THREAD

**Issue by lzpswat** [youzan/vant-weapp#1625]
**你需要的功能是？**
希望官方提供一个tabbar的案例教程，网络上也很少相关说明，感觉对新手很不友好。我安装微信官方的自定义tabbar的说明来弄也没有弄出效果。所以希望vant官方出一个小小的使用案例教程。

**Comment by I322871** [comment]
希望官方提供一个小程序中如何通过自定义tabbar的方式来使用van-tabbar的教程。谢谢！
