### ISSUE TITLE
area组件不显示city一栏

### ISSUE THREAD

**Issue by melote** [youzan/vant-weapp#1630]
## 问题
van-area组件如果只传递province_list和city_list的话，初次显示时，只显示了province_list一栏，city_list不会被加载，当再次滑动province时，city栏就会出现

## 环境
 - 设备: 1.02.1904090小程序开发工具官方工具版本1.02.1904090
 - 基础库版本: 2.2.5
 - Vant Weapp 版本:0.5.13

**Comment by rex-zsd** [comment]
请提供示例代码和使用的`province_list` `city_list`
