### ISSUE TITLE
area无法显示 

### ISSUE THREAD

**Issue by mhxy13867806343** [youzan/vant-weapp#1632]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**描述一下问题**
描述一下你遇到的问题，包括复现方式、导致结果

**截图**
如果是 UI 问题，请提供具体截图
如下图片
![TIM截图20190517160432](https://user-images.githubusercontent.com/4418166/57912679-82325700-78bd-11e9-9d48-555f6d9393fe.png)
**核心代码**
请提供使用组件的核心代码

        <van-popup
                :show="address.show"
                :position="address.position"
                :overlay="address.overlay"
                :safe-area-inset-bottom="address.safeareainserBottm"
                :safe-area-inset-top="address.safeareainserTop"
                @close="onClose">
            <van-area :value="address.value":area-list="areaList":columns-num="address.columnsNum" :loading="address.loading" title="地区选择"
            @confirm="areaConfirm" @cancel="areaCancel" @change="areaChange"
                      @reset="areaReset"
            />
        </van-popup>

```js
```

```wxml
```

**环境**
 - 设备:widnows 微信小程序 webstrom HBuilderX ide
 - 基础库版本: 
 - Vant Weapp 版本: 0.5.13

**Comment by rex-zsd** [comment]
demo中没复现，是用了mpvue?

**Comment by mhxy13867806343** [comment]
> 演示中没复现，是用了mpvue？

uni-app里面
