### ISSUE TITLE
tab自定义头部

### ISSUE THREAD

**Issue by superlbr** [youzan/vant-weapp#1635]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**你需要的功能是？**
tab可以自定义头部，利用slot嵌入

**你期望 API 是什么样的？**
参考https://meili.github.io/min/docs/minui/index.html#tab

**示例代码**
请展示一下新功能的大致用法

```
<tab>
  <view slot="tabHeader">
     自定义内容
  </view>
</tab>
```

**Comment by rex-zsd** [comment]
小程序缺少相关DOM操作API，暂时无法实现。

**Comment by superlbr** [comment]
可以参考minui的做法，把头部拆开成组件
