### ISSUE TITLE
单列picker，设置default-index，不起作用

### ISSUE THREAD

**Issue by ChinaFanny** [youzan/vant-weapp#1636]
**描述一下问题**
单列picker，设置default-index，不起作用

**截图**
![image](https://user-images.githubusercontent.com/22438061/58010794-97a8ba80-7b23-11e9-9e95-9545c67f3266.png)
![image](https://user-images.githubusercontent.com/22438061/58010722-79db5580-7b23-11e9-93c2-953dc66beba6.png)

**环境**
 - 设备:iOS
 - 基础库版本:
 - Vant Weapp 版本:0.5.13

**Comment by rex-zsd** [comment]
demo是没有问题的，可以看下是不是动态设置了`index`？
`default-index`是初始选中项，后续动态设置是没有用的，所以这个截图并不能说明什么。
如果需要动态设置，请使用`setIndexes ` `setColumnIndex` `setColumnValues`这些API。

**Comment by ChinaFanny** [comment]
> demo是没有问题的，可以看下是不是动态设置了`index`？
> `default-index`是初始选中项，后续动态设置是没有用的，所以这个截图并不能说明什么。
> 如果需要动态设置，请使用`setIndexes ` `setColumnIndex` `setColumnValues`这些API。
@rex-zsd 
index确实是动态设置的，使用setColumnIndex设置，但还是默认选择第一个（此时index=1）
![image](https://user-images.githubusercontent.com/22438061/58166131-bcd03100-7cbb-11e9-9d45-46da30acf26f.png)

**Comment by ChinaFanny** [comment]
发现如上问题的解决办法：onLoad方法里面执行setColumnIndex如上的评论的两行代码不起作用，只有在点击显示picker的方法里面设置才可以

**Comment by top-plan** [comment]
遇到同样的问题！default-index 属性无效，只能通过setColumnIndex（0,2）来达到需求

**Comment by qzmly100** [comment]
setColumnIndex 这个方法是怎么写的？

**Comment by qzmly100** [comment]
不太明白怎么运用？

**Comment by swearl** [comment]
> 不太明白怎么运用？

van-picker给一个class, 然后参考3楼的截图

**Comment by kingdsa** [comment]
不用这么麻烦 直接在van-popup 上加一个wx:if 就行了  wx:if的条件和show的条件一样就可以了

**Comment by lucyanddarlin** [comment]
> 不用这么麻烦 直接在van-popup 上加一个wx:if 就行了 wx:if的条件和show的条件一样就可以了

加上 `wx:if` 虽然可以，但是关闭时会缺少动画，看起来比较生硬

解决办法如下：
```html
<van-picker class="custom-picker" />
```

```js
    /**
     * @description 开启弹窗
     */
    openPopup() {
      const index = 2
      const picker = this.selectComponent('. custom-picker')
      picker && picker.setColumnIndex(0, index)
      this.setData({
       popupVisible: true
      })
    },
```
