### ISSUE TITLE
datetime-picker设置max-date报错

### ISSUE THREAD

**Issue by chengaobin** [youzan/vant-weapp#1637]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**描述一下问题**
datetime-picker设置max-date报错

**截图**
如果是 UI 问题，请提供具体截图

**核心代码**
请提供使用组件的核心代码

```js
```data={
      maxDate: new Date('2019/10').getTime(),
      value: new Date().getTime(),
      emitDate: '',
      formatter (type, value) {
        if (type === 'year') {
          return `${value}年`
        } else if (type === 'month') {
          return `${value}月`
        }
        return value
      }
    }

```wxml
  <van-datetime-picker
        toolbar-class="toolBarStyle"
        type="year-month"
        max-date="{{maxDate}}"
        value="{{value}}"
        bind:input="onInput"
        bind:confirm="confirm"
        bind:cancel="cancel"
        bind:change="handleChange"
      />

**环境**

 - 设备:
 - 基础库版本:
 - Vant Weapp 版本:

**Comment by chengaobin** [comment]
![1558346882(1)](https://user-images.githubusercontent.com/14012804/58014379-48ff1e80-7b2b-11e9-8496-376d77b9931e.jpg)
报错截图

**Comment by ZjVirus** [comment]
+1

**Comment by rex-zsd** [comment]
@ZjVirus 使用的vant-weapp版本是多少呢？在最新版本的demo里确实没复现这个问题。

**Comment by chengaobin** [comment]
> @ZjVirus 使用的vant-weapp版本是多少呢？在最新版本的demo里确实没复现这个问题。

版本是应该是0.5.11，试过多种格式还是有问题

**Comment by rex-zsd** [comment]
@chengaobin 是原生开发吗？还是有用mpvue、wepy什么的？

**Comment by chengaobin** [comment]
> @chengaobin 是原生开发吗？还是有用mpvue、wepy什么的？wepy开发的

**Comment by rex-zsd** [comment]
wepy确实会报错，但是貌似不影响功能
我研究一下

**Comment by chengaobin** [comment]
> wepy确实会报错，但是貌似不影响功能
> 我研究一下

是的，的确不影响功能，我大概看了下源码，貌似是数组里面传参顺序反了，麻烦修正了给个回复，谢谢了

**Comment by rex-zsd** [comment]
![image](https://user-images.githubusercontent.com/8767877/58528532-702fad00-8209-11e9-9c32-4d9cdad69b47.png)
可能是wepy初始化组件的问题，datetime-picker刚被初始化的时候，接收到的`max-date`是`0`，此时`max-date`小于`min-date`了，报了错。
之后正确的`max-date`又被传进来，重新计算了选项，所以之后的使用都是正常的。

**Comment by chengaobin** [comment]
> ![image](https://user-images.githubusercontent.com/8767877/58528532-702fad00-8209-11e9-9c32-4d9cdad69b47.png)
> 可能是wepy初始化组件的问题，datetime-picker刚被初始化的时候，接收到的`max-date`是`0`，此时`max-date`小于`min-date`了，报了错。
> 之后正确的`max-date`又被传进来，重新计算了选项，所以之后的使用都是正常的。
那我这边应该如何写，再加个最小日期？

**Comment by rex-zsd** [comment]
我处理下这种异常情况吧

**Comment by chengaobin** [comment]
> 我处理下这种异常情况吧

好的，多谢
