### ISSUE TITLE
做了一个百度小程序版本  欢迎使用

### ISSUE THREAD

**Issue by bobiscool** [youzan/vant-weapp#1638]
#### 所以抽空 弄了一版 百度小程序的移植
![](https://github.com/bobiscool/vantui-baiapp/blob/master/show.jpg?raw=true)
#### 下面是我的演示
![](https://github.com/bobiscool/vantui-baiapp/raw/master/baiapp.gif)

**Comment by rex-zsd** [comment]
做的还是不错的，但是广告注意。。。
