### ISSUE TITLE
tabs切换  tab内容会闪动一下

### ISSUE THREAD

**Issue by webfunction** [youzan/vant-weapp#1641]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**描述一下问题**
tabs切换  tab内容会闪动一下

**截图**
如果是 UI 问题，请提供具体截图

**核心代码**
请提供使用组件的核心代码
Tab 标签页
```js
```

```wxml
```

**环境**
 - 设备:   努比亚Z17
 - 基础库版本:
 - Vant Weapp 版本:

**Comment by rex-zsd** [comment]
重复issue，可以关注下 #1605

**Comment by j78742** [comment]
@rex-zsd 您操作关闭了1605，又要关注1605解决，这个操作有点看不懂

**Comment by daidaishuiping** [comment]
根本都没有提供解决办法或者思路啊
