### ISSUE TITLE
GoodsAction组件的GoodsActionIcon 外部样式类无效 的问题

### ISSUE THREAD

**Issue by cybbyc** [youzan/vant-weapp#1644]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**描述一下问题**
GoodsAction组件的GoodsActionIcon 外部样式类无效 

**截图**
无

**核心代码**

```wxml
```
<van-goods-action-icon
          icon="wap-home"
          text="首页"
          text-class="van-icon-custom"
          icon-class="van-icon-custom"
          @click="handleGoHome"
        />

```scss
```
 .van-icon-custom{
      color: red !important;
      font-size: 30px !important;
    }

**环境**
 - 设备:
 - 基础库版本:
 - Vant Weapp 版本:

**Comment by rex-zsd** [comment]
![image](https://user-images.githubusercontent.com/8767877/58142327-2da22980-7c79-11e9-8b00-7f310e81f945.png)
在demo上没有复现，看下版本是不是低于0.5.3，或者其他代码影响。

**Comment by cybbyc** [comment]
我这是在mpvue框架中用作小程序组件，使用的是0.5.13版本，没看到0.5.3版本，微信开发者工具中Wxml能看到class包含有自定义的class，但是在styles中没有自定义类的呈现
![bug1](https://user-images.githubusercontent.com/24407048/58152422-1aa25000-7c9f-11e9-87cc-ab4be28481a2.png)
代码：
![bug2](https://user-images.githubusercontent.com/24407048/58152484-41f91d00-7c9f-11e9-9455-399a0348284f.png)

**Comment by rex-zsd** [comment]
去掉scoped

**Comment by cybbyc** [comment]
嗯，好了

**Comment by cybbyc** [comment]
蟹蟹
