### ISSUE TITLE
轮播图的宽高没设置百分比

### ISSUE THREAD

**Issue by mdshxm** [youzan/vant-weapp#1647]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**你需要的功能是？**
描述一下你需要的功能，用于解决什么问题

**你期望 API 是什么样的？**
描述一下你期望的 API 形式

**示例代码**
请展示一下新功能的大致用法

```js
```

```wxml
```

**Comment by rex-zsd** [comment]
vant-weapp没有轮播图组件…………
