### ISSUE TITLE
为何每个组件的每个class都生成2个？

### ISSUE THREAD

**Issue by liangei** [youzan/vant-weapp#1648]
![TIM截图20190523212617](https://user-images.githubusercontent.com/3949198/58256373-7c4ae300-7da1-11e9-8c0d-070351ac4f41.png)

 - Vant Weapp 版本:0.5.13

**Comment by chenjiahan** [comment]
框架生成的，小程序框架对使用 addGlobalClass 属性的组件，会生成两份 class
