### ISSUE TITLE
radio 和checkbox数据格式的不一致

### ISSUE THREAD

**Issue by fengxingll** [youzan/vant-weapp#1650]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.
      <van-radio-group value="{{value}}" bind:change="onChange" >
         <block wx:for="{{  [1,2,,3]  }}"
          <van-radio name="{{item+1}}" simple>{{item+1}}</van-radio>
         </block>
      </van-radio-group>
上边的代码中，得到的数据value是数字格式。但完全类似的代码，若换成checkbox，如下，则value是字符类型的数组
      <van-checkbox-group value="{{value}}" bind:change="onChange" >
         <block wx:for="{{  [1,2,,3]  }}"
          <van-checkbox name="{{item+1}}" simple>{{item+1}}</van-checkbox>
         </block>
      </van-checkbox-group>
这种不一致，使得问题变得很麻烦。

**Comment by rex-zsd** [comment]
issue格式不规范，看不明白问题是什么。
