### ISSUE TITLE
van-tabs组件点击时吸顶效果失效

### ISSUE THREAD

**Issue by hxgithub201314** [youzan/vant-weapp#1651]
<van-tabs sticky>
		<van-tab title="标签 1">
			<view style="height:200px">
				11111
			</view>
			<view style="height:200px">
				22222
			</view>
			<view style="height:200px">
				33333
			</view>
			<view style="height:200px">
				44444
			</view>
		</van-tab>
		<van-tab title="标签 2">
			<view style="height:200px">
				11111
			</view>
			<view style="height:200px">
				22222
			</view>
			<view style="height:200px">
				33333
			</view>
			<view style="height:200px">
				55555
			</view>
		</van-tab>
		<van-tab title="标签 3">

			<view style="height:200px">
				11111
			</view>
			<view style="height:200px">
				22222
			</view>
			<view style="height:200px">
				33333
			</view>
			<view style="height:200px">
				444444
			</view>
		</van-tab>
		<van-tab title="标签 4">
			<view style="height:200px">
				5555
			</view>
			<view style="height:200px">
				66666
			</view>
			<view style="height:200px">
				77777
			</view>
			<view style="height:200px">
				8888
			</view>
		</van-tab>
	</van-tabs>

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
