### ISSUE TITLE
Cannot find name 'VantComponentOptions'.

### ISSUE THREAD

**Issue by wu0211** [youzan/vant-weapp#1652]
miniprogram/miniprogram_npm/vant-weapp/common/component.d.ts:1:85 - error TS2304: Cannot find name 'VantComponentOptions'.

1 declare function VantComponent<Data, Props, Watch, Methods, Computed>(vantOptions?: VantComponentOptions<Data, Props, Watch, Methods, Computed, CombinedComponentInstance<Data, Props, Watch, Methods, Computed>>): void;
                                                                                      ~~~~~~~~~~~~~~~~~~~~

miniprogram/miniprogram_npm/vant-weapp/common/component.d.ts:1:145 - error TS2304: Cannot find name 'CombinedComponentInstance'.

1 declare function VantComponent<Data, Props, Watch, Methods, Computed>(vantOptions?: VantComponentOptions<Data, Props, Watch, Methods, Computed, CombinedComponentInstance<Data, Props, Watch, Methods, Computed>>): void;

**Comment by rex-zsd** [comment]
跟#1591应该是一个问题，后期修复哈。
