### ISSUE TITLE
华为P20使用van-field组件password类型时无法选中进行输入

### ISSUE THREAD

**Issue by zhayujie** [youzan/vant-weapp#1654]
**描述一下问题**
华为P20使用van-field组件无法选中进行输入, 其中type="password"时无法获取焦点, 甚至未显示placeholder

**截图**

![image](https://user-images.githubusercontent.com/26161723/58378786-708f3480-7fcc-11e9-9ff6-c98937e49fe0.png)

**核心代码**
<van-field size="large" type="password" required clearable label="密码" placeholder="请输入密码" @change="setPassWord"/>

**环境**
 - 设备: 华为P20
 - 基础库版本: 未知
 - Vant Weapp 版本: v0.5.12

**Comment by rex-zsd** [comment]
用P20测试了一下，没有复现问题哎。
试下demo看看有没有问题？
<img src="https://img.yzcdn.cn/vant-weapp/qrcode-201808101114.jpg" width="200" height="200" style="margin-top: 10px;" >
