### ISSUE TITLE
[Picker]选择器 层级问题

### ISSUE THREAD

**Issue by zhangyuanliang** [youzan/vant-weapp#1655]
**如下图，小程序原声组件textarea层级出现在了picker之上，有没有方法解决？**

![image](https://user-images.githubusercontent.com/20222232/58402777-af3bf200-8093-11e9-8f47-beb325d36bcd.png)

![image](https://user-images.githubusercontent.com/20222232/58402340-a8f94600-8092-11e9-90c9-9eba3c6286ed.png)

**Comment by rex-zsd** [comment]
微信本身的限制，没办法解决，可以尝试弹出的时候隐藏一下textarea。
