### ISSUE TITLE
小程序 tabbar 功能切换BUG 反馈

### ISSUE THREAD

**Issue by Yuppiezero** [youzan/vant-weapp#1656]
在不同页面使用 tabbar 时候会有图标切换不回来的BUG  

需要**注释掉** tabbar 文件夹下的 index.js 第53行 this.currentActive = active;

//this.currentActive = active;

复现：

在全局json 文件中定义了自定义 tabbar   这样使得切换更顺畅  

但是需要 在页面的JS load 中 先隐藏掉自己定义的tabbar

使用  vant 的 tabbar  来切换 原因是 wx.switchTab 切换页面不会抖动 如果使用 wx.reLaunch 页面
会抖动厉害  所以使用上面多此一举的方法   这个时候   vant 的 tabbar   第一个切换到第二个 显示正常  但是第二个切换回第一个 时候图标依旧是 第二个的  
尝试解决方法1:在小程序的 onShow 和 onHide 中改变 active 的值 但是没有效果
正确解决方法：**注释掉** tabbar 文件夹下的 index.js 第53行 this.currentActive = active;

**Comment by Yuppiezero** [comment]
编写的小哥哥应该是从VUE 的组件里copy来修改的 但是小程序没有类似于APP.VUE这种 全局使用的HTML，所以要在每个页面里定义一下的话 这个功能就有点多余了

**Comment by I322871** [comment]
@Yuppiezero 遇到类似的问题，点击切换之后，页面确实变了，但是底下选中的就不一定是我刚刚点的那个。。。试了试你说的删掉53行还是不起作用。Debug发现运行都是正常的。

我一共有3个tab，在tabbar/index.js的第26行加断点，发现切换的时候会进入这个断点刚好三次，也按照我的点击正确的给每个tab设置了颜色。但是点F8继续运行，就发现颜色又变了。。。

按道理来讲任何对于tab颜色的改变都该最终执行到这个断点位置。不知道有没有其他的地方可以设置tab颜色，反正我没找到。。。捕获不到bug发生的位置。

**Comment by Yuppiezero** [comment]
目前在小程序里我已经没有问题了 
应该是页面的JS里 没有 active  参数吧？ 要在data 里设置对应的参数  例如 首页 显示 active: 0    第二个导航页 需要设置  active: 1   第三个导航页 需要设置  active: 2  然后配合上之前的修改 如果还有问题的话 可以联系我  我发一份demo 给你 @I322871 @

**Comment by rex-zsd** [comment]
@Yuppiezero 所以是使用姿势的问题吗？

**Comment by I322871** [comment]
@Yuppiezero  我这边暂时观察到的是，在进入到van-tabbar的change处理方法的时候，颜色显示还都是对的，但是我在bind:change中执行了wx.switchTab方法，然后颜色就不对了。。。请问你是把van-tabbar作为自定义tabbar用在custom-tab-bar下面吗？麻烦分享一下你的demo哈，谢谢！wangcong891221@163.com

**Comment by Yuppiezero** [comment]
@I322871  我这里是直接写在页面里的 没有使用自定义tabbar的custom-tab-bar  感觉是这样的话 那应该不需要该我说的那个注释

步骤说一下 

1、 先在app.json 里 定义  tabbar   

2、在首页JS 里 onLoad 的时候 放置 wx.hideTabBar()  隐藏掉  等下说为什么这操作

3、我有5个页面  有3个页面需要显示底部导航  

这3个页面是 首页   数据列表  和 个人中心

在这三个页面的wxml 文件里 底部直接粘贴 下面的代码

    <van-tabbar active="{{ active }}"  bind:change="onChange">

      <van-tabbar-item>

    <image slot="icon" src="{{ icon.normal }}" mode="aspectFit" />

    <image slot="icon-active" src="{{ icon.active }}" mode="aspectFit" />

    首页

      </van-tabbar-item>

      <van-tabbar-item>

    <image slot="icon" src="{{ icon2.normal }}" mode="aspectFit" />

    <image slot="icon-active" src="{{ icon2.active }}" mode="aspectFit" />

    数据列表

      </van-tabbar-item>

      <van-tabbar-item>

    <image slot="icon" src="{{ icon3.normal }}" mode="aspectFit" />

    <image slot="icon-active" src="{{ icon3.active }}" mode="aspectFit" />

    个人中心

      </van-tabbar-item>

    </van-tabbar>

4、注意相关参数以及函数

  active  这个需要在 js 的data 里设置一下  

    例如 ： 

     第一个 首页的 页面 需要设置这个值为active:0      

     第二个列表数据列表 值 active:1  

     第三个个人中心页面 值 active:2

icon.normal 是第一个的 首页的未选中图标   icon.active  是第一个的 `首页的选中图标 

贴一下页面的JS里的data里如何定义的


    icon: {
          normal: '/images/icon_HOME.png',
          active: '/images/icon_HOME_HL.png'
        },
        icon2: {
          normal: '/images/icon_ORDER.png',
          active: '/images/icon_ORDER_HL.png'
        },
        icon3: {
          normal: '/images/icon_MY.png',
          active: '/images/icon_MY_HL.png'
        }

5、如何定义页面的切换 这个其实也是和上面的一样，那个页面使用那个页面粘贴就好了

通过 onChange(event) 的 参数来判断当前点击的是那个 切换页面，这样你可以看到 wx.switchTab 进行跳转 这也就是前面的那个app.json里定义的那个 tab-bar 的作用  因为使用其他的跳转页面会跳动和闪烁的厉害  这样就可以完美解决这个问题

         onChange(event) {
             var n=event.detail;
             if (n == 0) {
               wx.switchTab({
                 url: '/pages/index/index'
               })
             }
             else if(n==1){
               wx.switchTab({
                 url:'/pages/mybill/mybill'
               })
             }
             else if(n==2){
               wx.switchTab({
                 url: '/pages/mycenter/mycenter'
               })
             }
             else{

             }
           }

wx.reLaunch    wx.redirectTo  wx.navigateTo 点击底部的按钮时候都会 闪烁的厉害

所以回到  app.json 里 定义  tabBar 这里的只要随意定义一个就好了 然后点击 底部按钮 跳转的时候使用wx.switchTab 可以完美解决

     "tabBar": {
         "color": "#999999",
         "selectedColor": "#2884C7",
         "backgroundColor": "#ffffff",
         "borderStyle": "black",
         "list": [
           {
             "pagePath": "pages/index/index",
             "iconPath": "images/b.png",
             "selectedIconPath": "images/b.png",
             "text": "-"
           },
           {
             "pagePath": "pages/mybill/mybill",
             "iconPath": "images/b.png",
             "selectedIconPath": "images/b.png",
             "text": "-"
           },
           {
             "pagePath": "pages/mycenter/mycenter",
             "iconPath": "images/b.png",
             "selectedIconPath": "images/b.png",
             "text": "-"
           }
         ]
       }

**Comment by I322871** [comment]
@Yuppiezero 非常感谢你的分享！很受益！我之前一直以为应该尽量使用自定义tabbar的方式引入第三方tabbar，不知道这种在每个tab页面上都加入tabbar是不是vant的推荐用法，总之确实可以工作，非常感谢！

**Comment by I322871** [comment]
@Yuppiezero 刚刚发现我那个问题应该是小程序的bug，跟vant无关。微信官方自定义tabbar案例中只有两个tab，不会出现问题，在那个基础上再加入一个tab就会出现这个问题。。。应该是微信小程序的bug。

**Comment by Yuppiezero** [comment]
漏掉了一点 需要在 app.json 里粘贴 引入的代码 我是把这俩放在了根目录下的control 文件夹里 所以就这样引入了

    "usingComponents": {
          "van-tabbar": "/control/tabbar/index",
          "van-tabbar-item": "/control/tabbar-item/index"
        }

**Comment by wuxinweb** [comment]
https://developers.weixin.qq.com/s/FjLU4mmp7r9s
这个例子解决了我的问题
// this.getTabBar().init();

**Comment by airzhanglin** [comment]
> @I322871 我这里是直接写在页面里的 没有使用自定义tabbar的custom-tab-bar 感觉是这样的话 那应该不需要该我说的那个注释
> 
> 步骤说一下
> 
> 1、 先在app.json 里 定义 tabbar
> 
> 2、在首页JS 里 onLoad 的时候 放置 wx.hideTabBar() 隐藏掉 等下说为什么这操作
> 
> 3、我有5个页面 有3个页面需要显示底部导航
> 
> 这3个页面是 首页 数据列表 和 个人中心
> 
> 在这三个页面的wxml 文件里 底部直接粘贴 下面的代码
> 
> ```
> <van-tabbar active="{{ active }}"  bind:change="onChange">
> 
>   <van-tabbar-item>
> 
> <image slot="icon" src="{{ icon.normal }}" mode="aspectFit" />
> 
> <image slot="icon-active" src="{{ icon.active }}" mode="aspectFit" />
> 
> 首页
> 
>   </van-tabbar-item>
> 
>   <van-tabbar-item>
> 
> <image slot="icon" src="{{ icon2.normal }}" mode="aspectFit" />
> 
> <image slot="icon-active" src="{{ icon2.active }}" mode="aspectFit" />
> 
> 数据列表
> 
>   </van-tabbar-item>
> 
>   <van-tabbar-item>
> 
> <image slot="icon" src="{{ icon3.normal }}" mode="aspectFit" />
> 
> <image slot="icon-active" src="{{ icon3.active }}" mode="aspectFit" />
> 
> 个人中心
> 
>   </van-tabbar-item>
> 
> </van-tabbar>
> ```
> 
> 4、注意相关参数以及函数
> 
> active 这个需要在 js 的data 里设置一下
> 
> ```
> 例如 ： 
> 
>  第一个 首页的 页面 需要设置这个值为active:0      
> 
>  第二个列表数据列表 值 active:1  
> 
>  第三个个人中心页面 值 active:2
> ```
> 
> icon.normal 是第一个的 首页的未选中图标 icon.active 是第一个的 `首页的选中图标
> 
> 贴一下页面的JS里的data里如何定义的
> 
> ```
> icon: {
>       normal: '/images/icon_HOME.png',
>       active: '/images/icon_HOME_HL.png'
>     },
>     icon2: {
>       normal: '/images/icon_ORDER.png',
>       active: '/images/icon_ORDER_HL.png'
>     },
>     icon3: {
>       normal: '/images/icon_MY.png',
>       active: '/images/icon_MY_HL.png'
>     }
> ```
> 
> 5、如何定义页面的切换 这个其实也是和上面的一样，那个页面使用那个页面粘贴就好了
> 
> 通过 onChange(event) 的 参数来判断当前点击的是那个 切换页面，这样你可以看到 wx.switchTab 进行跳转 这也就是前面的那个app.json里定义的那个 tab-bar 的作用 因为使用其他的跳转页面会跳动和闪烁的厉害 这样就可以完美解决这个问题
> 
> ```
>      onChange(event) {
>          var n=event.detail;
>          if (n == 0) {
>            wx.switchTab({
>              url: '/pages/index/index'
>            })
>          }
>          else if(n==1){
>            wx.switchTab({
>              url:'/pages/mybill/mybill'
>            })
>          }
>          else if(n==2){
>            wx.switchTab({
>              url: '/pages/mycenter/mycenter'
>            })
>          }
>          else{
> 
>          }
>        }
> ```
> 
> wx.reLaunch wx.redirectTo wx.navigateTo 点击底部的按钮时候都会 闪烁的厉害
> 
> 所以回到 app.json 里 定义 tabBar 这里的只要随意定义一个就好了 然后点击 底部按钮 跳转的时候使用wx.switchTab 可以完美解决
> 
> ```
>  "tabBar": {
>      "color": "#999999",
>      "selectedColor": "#2884C7",
>      "backgroundColor": "#ffffff",
>      "borderStyle": "black",
>      "list": [
>        {
>          "pagePath": "pages/index/index",
>          "iconPath": "images/b.png",
>          "selectedIconPath": "images/b.png",
>          "text": "-"
>        },
>        {
>          "pagePath": "pages/mybill/mybill",
>          "iconPath": "images/b.png",
>          "selectedIconPath": "images/b.png",
>          "text": "-"
>        },
>        {
>          "pagePath": "pages/mycenter/mycenter",
>          "iconPath": "images/b.png",
>          "selectedIconPath": "images/b.png",
>          "text": "-"
>        }
>      ]
>    }
> ```
在首页的隐藏tabbar不会 不会出现闪的问题吗

**Comment by Xbigfat** [comment]
> https://developers.weixin.qq.com/s/FjLU4mmp7r9s
> 这个例子解决了我的问题
> // this.getTabBar().init();

研究了两个小时看到这段代码，我真是没猜到有三个 tabbar

**Comment by rex-zsd** [comment]
![image](https://user-images.githubusercontent.com/8767877/102600658-10d21e80-415a-11eb-90be-ffd2981d2936.png)

@Xbigfat 文档里一直都贴着这段代码片段呀……你们看文档不会不会太不仔细了下

**Comment by aoyangyang** [comment]
> I322871
你好~方便发一份demo给我吗
