### ISSUE TITLE
组件的style样式无效

### ISSUE THREAD

**Issue by yule6869** [youzan/vant-weapp#1658]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**描述一下问题**
组件的style样式无效

**核心代码**
在组件上加任意的style=".......”都无效。

**Comment by rex-zsd** [comment]
无效是正常的，建议看一下小程序自定义组件部分的文档。

**Comment by yule6869** [comment]
谢谢答复

**Comment by rex-zsd** [comment]
如果需要修改样式，可以看下文档，使用暴露的外部样式类来修改。
或者找下对应节点的class，然后在页面的wxss里覆盖该class的样式。

**Comment by yule6869** [comment]
用外部class可以覆盖。但是有些节点需要另外设置样式。感觉style要灵活一点。我看了几遍自定义组件文档。也没找到关于style的说明，只有class类的。请提供一下。

**Comment by rex-zsd** [comment]
[组件样式隔离](https://developers.weixin.qq.com/miniprogram/dev/framework/custom-component/wxml-wxss.html#%E7%BB%84%E4%BB%B6%E6%A0%B7%E5%BC%8F%E9%9A%94%E7%A6%BB)可以看下这部分，vant-weapp开启了`addGlobalClass: true`，可以在页面里覆盖组件样式。

**Comment by yule6869** [comment]
是的。可以在组件上使用custom-class=“abc” 然后再wxss文件中定义好abc类。我觉得有些麻烦，想在某些组件上直接用style=”color：red“。可是一直无效。可以这样加吗？还是必须在wxss中定义了再通过custom-class加进来？
