### ISSUE TITLE
关于API对新手不友好的建议

### ISSUE THREAD

**Issue by BrotherFly** [youzan/vant-weapp#1660]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**你需要的功能是？**
描述一下你需要的功能，用于解决什么问题

**你期望 API 是什么样的？**
描述一下你期望的 API 形式

**示例代码**
请展示一下新功能的大致用法

```js
```

```wxml
```

**Comment by BrotherFly** [comment]
能不能把popup和picker连起来给出一个案例或教程，作为小程序的新手，官方给的例子总感觉用不到点子上，比如我想做一个点击触发picker，按照现有的实现不了啊

**Comment by EDGDK** [comment]
> 能不能把popup和picker连起来给出一个案例或教程，作为小程序的新手，官方给的例子总感觉用不到点子上，比如我想做一个点击触发picker，按照现有的实现不了啊

请问您现在有这个例子吗 ？我在网上找了好久没找到如何把popup和picker连起来

**Comment by BrotherFly** [comment]
> > 能不能把popup和picker连起来给出一个案例或教程，作为小程序的新手，官方给的例子总感觉用不到点子上，比如我想做一个点击触发picker，按照现有的实现不了啊
> 
> 请问您现在有这个例子吗 ？我在网上找了好久没找到如何把popup和picker连起来

js
Page({
  data: {
    bottom: false,
    column1: ['杭州', '宁波', '温州', '嘉兴', '湖州'],
    vaa:""
  },
  toggleBottomPopup(e) {
    console.log(e)
    this.setData({
      bottom: true
    });
  }, 
  toggleBottomPopup2(e) {
    console.log(e)
    this.setData({
      bottom: false
    });
  }, 
  onChange1(event) {
    console.log("change", event.detail.value)

    this.setData({
      vaa: event.detail.value
    });
  },
  onConfirm(event) {
    console.log("confirm", event.detail.value);
    this.setData({
      vaa: event.detail.value
    });
    this.setData({
      bottom: false
    });
  },


wxml
<van-cell title="单元格" is-link value="{{vaa}}" arrow-direction="down" bind:click="toggleBottomPopup"/>
  <van-popup
    show="{{ bottom }}"
    position="bottom"
    custom-class="bottom"
    bind:close="toggleBottomPopup2"
  >

    <van-picker
      show-toolbar
  title="城市"
    columns="{{ column1 }}"
    bind:change="onChange1"
    bind:confirm="onConfirm"
    />


  </van-popup>

**Comment by BrotherFly** [comment]
<van-cell title="单元格" is-link value="{{vaa}}" arrow-direction="down" bind:click="toggleBottomPopup"/>
  <van-popup
    show="{{ bottom }}"
    position="bottom"
    custom-class="bottom"
    bind:close="toggleBottomPopup2"
  >
  <van-picker
      show-toolbar
  title="城市"
    columns="{{ column1 }}"
    bind:change="onChange1"
    bind:confirm="onConfirm"
    />
  </van-popup>

**Comment by BrotherFly** [comment]
<van-cell title="单元格" is-link value="{{vaa}}" arrow-direction="down" bind:click="toggleBottomPopup"/>
  <van-popup
    show="{{ bottom }}"
    position="bottom"
    custom-class="bottom"
    bind:close="toggleBottomPopup2"
  >
  <van-picker
      show-toolbar
  title="城市"
    columns="{{ column1 }}"
    bind:change="onChange1"
    bind:confirm="onConfirm"
    />
  </van-popup>

**Comment by BrotherFly** [comment]
<van-cell title="单元格" is-link value="{{vaa}}" arrow-direction="down" bind:click="toggleBottomPopup"/>
  <van-popup
    show="{{ bottom }}"
    position="bottom"
    custom-class="bottom"
    bind:close="toggleBottomPopup2"
  >
  <van-picker
      show-toolbar
  title="城市"
    columns="{{ column1 }}"
    bind:change="onChange1"
    bind:confirm="onConfirm"
    />
  </van-popup>

**Comment by BrotherFly** [comment]
`<van-cell title="单元格" is-link value="{{vaa}}" arrow-direction="down" bind:click="toggleBottomPopup"/>
  <van-popup
    show="{{ bottom }}"
    position="bottom"
    custom-class="bottom"
    bind:close="toggleBottomPopup2"
  >
  <van-picker
      show-toolbar
  title="城市"
    columns="{{ column1 }}"
    bind:change="onChange1"
    bind:confirm="onConfirm"
    />
  </van-popup>`

**Comment by BrotherFly** [comment]
> > 能不能把popup和picker连起来给出一个案例或教程，作为小程序的新手，官方给的例子总感觉用不到点子上，比如我想做一个点击触发picker，按照现有的实现不了啊
> 
> 请问您现在有这个例子吗 ？我在网上找了好久没找到如何把popup和picker连起来

<van-cell title="单元格" is-link value="{{vaa}}" arrow-direction="down" bind:click="toggleBottomPopup"/>
  <van-popup
    show="{{ bottom }}"
    position="bottom"
    custom-class="bottom"
    bind:close="toggleBottomPopup2"
  >
  <van-picker
      show-toolbar
  title="城市"
    columns="{{ column1 }}"
    bind:change="onChange1"
    bind:confirm="onConfirm"
    />
  </van-popup>
