### ISSUE TITLE
如何不在回调函数中获取picker组件，从而调用相应方法

### ISSUE THREAD

**Issue by chengaobin** [youzan/vant-weapp#1661]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**你需要的功能是？**
描述一下你需要的功能，用于解决什么问题

**你期望 API 是什么样的？**
如何不在回调函数中获取picker组件，从而调用相应方法，
希望能在比如onload或者其他函数中能够获取当前组件，从而调动组件的方法
描述一下你期望的 API 形式

**示例代码**
请展示一下新功能的大致用法

```js
```

```wxml
```

**Comment by rex-zsd** [comment]
看一下小程序文档`selectComponent`相关API

**Comment by chengaobin** [comment]
> 看一下小程序文档`selectComponent`相关API
我将picker跟popup在wepy中封装成一个组件使用的，那我我在这个封装的组件如何获取picker组件呢，我试过selectComponent获取不到对应的组件，可以麻烦告知下吗
