### ISSUE TITLE
picker设置setColumnIndex报错

### ISSUE THREAD

**Issue by chengaobin** [youzan/vant-weapp#1662]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**描述一下问题**
wepy中使用setColumnIndex设置选中列报错，并且没有选中所选列

**截图**
![1559182289(1)](https://user-images.githubusercontent.com/14012804/58603512-9d409600-82c3-11e9-80d9-2f36cc76fd6f.jpg)
![1559182323(1)](https://user-images.githubusercontent.com/14012804/58603513-9dd92c80-82c3-11e9-83fb-384d5b1ad161.jpg)

**核心代码**
请提供使用组件的核心代码

```js
```

```wxml
```

**环境**
 - 设备:
 - 基础库版本:
 - Vant Weapp 版本:0.5.11

**Comment by rex-zsd** [comment]
picker上设置的数据是什么？

**Comment by chengaobin** [comment]
> picker上设置的数据是什么？

picker是一组字符串，单列的，初始设置过一次columns，然后后续是通过pupup的show字段控制显示，通过wepy的invoke方法触发组件里面的方法后就会报错，需要重新设置下columns才不会报错，并且不会生效，第二次才会生效。
![1559201249(1)](https://user-images.githubusercontent.com/14012804/58616132-75672780-82ef-11e9-978a-ac584e045df2.png)
r如图所示红线，重新设置下colums才不会报错
![1559201345(1)](https://user-images.githubusercontent.com/14012804/58616208-a8112000-82ef-11e9-8001-b8693c3da291.jpg)
用异步再执行一次这个方法才会生效
