### ISSUE TITLE
icon在button中无法上下居中对齐

### ISSUE THREAD

**Issue by leo95123** [youzan/vant-weapp#1663]
**描述一下问题**
icon在button中无法上下居中对齐，发现是icon容器与内容错位，详细见截图

**截图**
![0](https://user-images.githubusercontent.com/28439527/58603861-e5ac8380-82c4-11e9-9714-f3edf64df9a0.png)
![1](https://user-images.githubusercontent.com/28439527/58603862-e5ac8380-82c4-11e9-9486-9c39b28ac35c.png)

**核心代码**
请提供使用组件的核心代码
```wxml
<van-button type="primary" custom-class="we-login-btn">
            <van-icon name="wechat" custom-class="btn-icon" size="18px"/>
            微信登录
        </van-button>
```

**环境**
 - 设备:
 - 基础库版本:
 - Vant Weapp 版本:

**Comment by rex-zsd** [comment]
自行控制一下icon的样式即可，小程序自定义组件的容器与内部有点错位，内部不能控制。
