### ISSUE TITLE
使用popUpd弹层时，在弹层上上下滑动，或者点击，事件会透传到下方控件

### ISSUE THREAD

**Issue by fafala** [youzan/vant-weapp#1664]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

问题：
使用popUpd弹层时，在弹层上上下滑动，或者点击，事件会透传到下方控件

 - 设备: iPhone7
 - 基础库版本:2.70
 - Vant Weapp 版本:0.5.13

**Comment by rex-zsd** [comment]
正常的事件冒泡现象，自己catch一下需要屏蔽的事件即可，例如
```html
<van-popup catch:tap="noop">
   ...
</van-popup>
```

```js
Page({
   noop() {}
});
```
