### ISSUE TITLE
使用npm开始项目时报错

### ISSUE THREAD

**Issue by cangyu1993** [youzan/vant-weapp#1666]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**描述一下问题**
描述一下你遇到的问题，包括复现方式、导致结果
使用npm构建完之后开始项目就出现这个错误

**截图**
如果是 UI 问题，请提供具体截图
![image](https://user-images.githubusercontent.com/42930030/58606982-3f667b00-82d0-11e9-8bdf-c98f5bed1896.png)

**核心代码**
请提供使用组件的核心代码

```js
```

```wxml
```

**环境**
 - 设备:1.02.1905151
 - 基础库版本:2.70
 - Vant Weapp 版本:0.5.13

**Comment by rex-zsd** [comment]
不是vant的问题，可以去小程序社区看下。
建议先关闭开发者工具重启下试试。
