### ISSUE TITLE
Module build failed:  module.exports = __webpack_public_path__ + "libs/vant-weapp/lib/common/index.wxss";              ^ Unrecognised input

### ISSUE THREAD

**Issue by elvisz2016** [youzan/vant-weapp#1667]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**描述一下问题**
wepack 打包出现报错

**截图**
如果是 UI 问题，请提供具体截图
![image](https://user-images.githubusercontent.com/24736504/58607123-e9460780-82d0-11e9-86c7-638146f32764.png)

**核心代码**
请提供使用组件的核心代码

```js
```

```wxml
```

**环境**
 - 设备: 
 - 基础库版本: 2.7
 - Vant Weapp 版本:  "vant-weapp": "^0.5.13",

**Comment by rex-zsd** [comment]
跟vant没关系吧…………
