### ISSUE TITLE
微信小程序Toast.success('成功');图标不显示且报错Failed to load font https://img.yzcdn.cn/vant/vant-icon-839a51.woff2

### ISSUE THREAD

**Issue by Marshiruo** [youzan/vant-weapp#1669]
Toast.success('成功');
![4981A23D-6CC6-4df1-8EDB-AF4A2FE94CC6](https://user-images.githubusercontent.com/42396294/58614626-801fbd80-82eb-11e9-9d94-fca57462004e.png)

**Comment by rex-zsd** [comment]
开发者工具的问题i
![image](https://user-images.githubusercontent.com/8767877/58615085-c7f31480-82ec-11e9-8e31-1792b19fd075.png)

**Comment by Marshiruo** [comment]
使用的图标都不显示了
