### ISSUE TITLE
按钮文档缺乏部分信息

### ISSUE THREAD

**Issue by BadReese** [youzan/vant-weapp#1672]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**描述一下问题**
文档中的图标按钮没有说明写法，应该给van-button增加什么参数来定义图标呢？麻烦回复并补充下文档，谢谢

**截图**
![image](https://user-images.githubusercontent.com/18170860/58751462-3f819900-84d1-11e9-9629-278c2b312611.png)

**核心代码**
文档连接：https://youzan.github.io/vant-weapp/#/button

**环境**
 - 设备:
 - 基础库版本:
 - Vant Weapp 版本:

**Comment by freechen** [comment]
缺少唯独缺少了这部分的案例代码，麻烦官方补充下，谢谢。

**Comment by gotounix** [comment]
@BadReese 兄弟，知道这个怎么用了吗？

**Comment by BadReese** [comment]
@gotounix 最后我没用这个好像

**Comment by chenjiahan** [comment]
这里是文档的疏漏，在目前版本可以通过按钮的默认插槽嵌入 van-icon 组件来实现，后续版本会支持 icon 属性

**Comment by chenjiahan** [comment]
已在 0.5.18 版本支持 icon 属性

**Comment by s209392599** [comment]
<van-button type="primary">
  <van-icon name="star-o" />按钮
</van-button>
这样就可以显示按钮，按官方文档的暂时不能显示图标 2019年8月13日17:02:39

**Comment by s209392599** [comment]
<van-button type="primary">
  <van-icon name="star-o" />按钮
</van-button>

**Comment by yaoshanliang** [comment]
自定义颜色呢
