### ISSUE TITLE
什么时候会出下拉菜单的组建啊？

### ISSUE THREAD

**Issue by xiaoshuoyiyi** [youzan/vant-weapp#1674]

**Comment by rex-zsd** [comment]
vue的vant2.0已经支持了，vant-weapp会在1.0版本跟进，可以关注一下。

**Comment by EasonShen1989** [comment]
@rex-zsd 你好，下拉菜单组件加上了么？

**Comment by chenjiahan** [comment]
@EasonShen1989  预计下个 1.0 的 beta 版本会支持，目前代码已开发完成，正在 review 中
