### ISSUE TITLE
时间选择器，能不能加上可配置将时辰自定义转化成上午、下午这种格式

### ISSUE THREAD

**Issue by lhwtyu** [youzan/vant-weapp#1675]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**你需要的功能是？**
描述一下你需要的功能，用于解决什么问题

**你期望 API 是什么样的？**
描述一下你期望的 API 形式

**示例代码**
请展示一下新功能的大致用法

```js
```

```wxml
```

**Comment by rex-zsd** [comment]
标题一句话，issue内容什么也没写，实在看不明白是什么样的需求…………
