### ISSUE TITLE
submitbar 可以双向绑定价格吗？

### ISSUE THREAD

**Issue by llh1187** [youzan/vant-weapp#1676]
**你需要的功能是？**
每选择一件商品，submitbar就更新一次价格。
**你期望 API 是什么样的？**
假设submitbar 中的价格绑定的是index.js中的Page.data里面的price，然后触发js更改price事件的时候，submitbar能够响应并更新。
**示例代码**
请展示一下新功能的大致用法

```js
Page({
  data:{
  price:0,
},
ChangePrice:function(){
  this.data.price = 100;
},
})
```

```wxml
<van-submit-bar price="{{ price }}" button-text="提交订单" bind:submit="onSubmit" />
```

**Comment by rex-zsd** [comment]
可以优化一下

**Comment by rex-zsd** [comment]
#1689 已经支持了，下版本发布。

**Comment by llh1187** [comment]
您好，刚刚按照我在issue里面的使用方法试了一下，<SubmitBar>发现并没有实现价格双向绑定的功能。补充一点，我是直接在本地的仓库那里pull request最新的更新下来，然后使用dist文件夹的（我之前也是这么用的）。

**Comment by llh1187** [comment]
您好，我将价格通过setData的方式设定就成功了，谢谢~
