### ISSUE TITLE
官方教程快速上手npm部分对新手不友好

### ISSUE THREAD

**Issue by good1uck** [youzan/vant-weapp#1677]
小程序版本rc v1.02.1905151，
npm版本6.9.0
好奇有没有根据“快速上手”教程成功用上组件的

**Comment by good1uck** [comment]
小程序版本rc v1.02.1905151，
npm版本6.9.0
好奇有没有根据“快速上手”教程成功用上组件的

**Comment by good1uck** [comment]
4.在小程序根目录`npm init`以及`npm i vant-weapp -S --production`后，再使用`npm install`，最后执行`npm run dev`报错如下：`npm ERR! missing script: dev`

**Comment by good1uck** [comment]
`npm install`和`npm run dev`应该在什么目录下执行？

**Comment by good1uck** [comment]
`npm install`和`npm run dev`应该在什么目录下执行？

**Comment by heinihaoa** [comment]
快速上手给的button路径是错的,有点小坑
教程引入这个路径''/path/to/vant-weapp/dist/button/index
我改成了'/miniprogram_npm/vant-weapp/button/index''
才能成功使用 
/miniprogram_npm 应该是根据项目名变化的

**Comment by heinihaoa** [comment]
第一次安装模块的话,
必须 `npm init` 以建立一个新的package.json后才可以安装模块.
安装模块之后,在`微信开发者工具->工具->构建npm`
还有必须`微信开发者工具->详情->本地设置->使用npm模块`

**Comment by chenjiahan** [comment]
文档已更新
