### ISSUE TITLE
第一次点击的时候都没有蒙层，第二次才有

### ISSUE THREAD

**Issue by Angelinanay** [youzan/vant-weapp#1680]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**描述一下问题**
我自己封装了一个上传图片的组件，在内部使用了van-action-sheet这个组件
在图片上传成功后想通过点击去预览或者删除图片，然而却发现点击图片后出现的下拉菜单没有蒙层，但是第二次点击的时候蒙层就出现了。

**环境**
 - 设备:模拟器以及ios手机
 - 基础库版本:1.2.0
 - Vant Weapp 版本:0.5.11

**截图**
第一次点击
![微信截图_20190603140254](https://user-images.githubusercontent.com/24545670/58779486-ac4b7f00-8608-11e9-8c01-841db1462173.png)

第二次点击
![微信截图_20190603140514](https://user-images.githubusercontent.com/24545670/58779494-b2d9f680-8608-11e9-9228-31554d826ba2.png)

**Comment by o0teamo0o** [comment]
我也遇到了相同情况

**Comment by Angelinanay** [comment]
> 我也遇到了相同情况

原生的picker没有这个问题，我暂时替换了。

**Comment by o0teamo0o** [comment]
> > 我也遇到了相同情况
> 
> 原生的picker没有这个问题，我暂时替换了。

我找到问题了,第一次点击的时候,他触发了样式 .van-fade-leave-to{opacity:0} 我把这个样式给去掉了就没事了  这个样式在 transition组件的wxss文件里面

**Comment by LesterWeng** [comment]
> > > 我也遇到了相同情况
> > 
> > 
> > 原生的picker没有这个问题，我暂时替换了。
> 
> 我找到问题了,第一次点击的时候,他触发了样式 .van-fade-leave-to{opacity:0} 我把这个样式给去掉了就没事了 这个样式在 transition组件的wxss文件里面

我也试在那里处理了一下 ):

**Comment by ll60** [comment]
https://github.com/youzan/vant-weapp/issues/1695
这个问题我也在BUG里面提了，解决方案也在里面，你可以照着改下
