### ISSUE TITLE
Cell组件value-class不生效

### ISSUE THREAD

**Issue by good1uck** [youzan/vant-weapp#1681]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**描述一下问题**
Cell组件value-class不生效

**截图**
1.wxml部分
![企业微信截图_20190603154646](https://user-images.githubusercontent.com/23480644/58785018-487c8280-8617-11e9-9f2a-4fe2a0c97ec9.png)

2.wxss部分
![企业微信截图_20190603154939](https://user-images.githubusercontent.com/23480644/58785073-65b15100-8617-11e9-9b2a-ac07f42a982c.png)

3.debug panel
![企业微信截图_20190603154755](https://user-images.githubusercontent.com/23480644/58785043-56ca9e80-8617-11e9-9b0f-bba90dbcff9f.png)

![企业微信截图_20190603154928](https://user-images.githubusercontent.com/23480644/58785209-a741fc00-8617-11e9-94fa-490da5a3d571.png)

**环境**
 - 微信开发者工具:RC v1.02.1905151
 - Vant Weapp 版本: v0.5.12

**Comment by good1uck** [comment]
主要是没法定义颜色。如果是个bug，有张图还能给你们参考一下，debug
![企业微信截图_15595495348054](https://user-images.githubusercontent.com/23480644/58786631-96df5080-861a-11e9-97bc-80b39d9aa2cd.png)

title-class可以用来定义颜色，相关默认类里没有定义过颜色。
而value-class相关默认类定义过了颜色。这个意思就是你们定义过的属性，就没法再用外部样式类覆盖了。

这是特性还是bug？

**Comment by good1uck** [comment]
是不是用有赞weapp自定义属性的话，用slot更妥当一点？外部样式类似乎不是很可靠。

**Comment by rex-zsd** [comment]
`!important`，外部样式类的优先级是不确定的。
