### ISSUE TITLE
vant没有索引外表吗？mint-ui都有啊

### ISSUE THREAD

**Issue by qzmly100** [youzan/vant-weapp#1683]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**你需要的功能是？**
Index List 我需要的是索引功能
描述一下你需要的功能，用于解决什么问题
索引列表，可由右侧索引导航快速定位到相应的内容

**你期望 API 是什么样的？**
无

**示例代码**
无
```js
```

```wxml
```

**Comment by chenjiahan** [comment]
Vue 版本已经有了，小程序版本暂时没有，另外 mint-ui 对标的是 Vue 版本
