### ISSUE TITLE
希望增加垂直居中样式

### ISSUE THREAD

**Issue by leo95123** [youzan/vant-weapp#1684]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**你需要的功能是？**
希望增加垂直居中样式或者增加van-row的垂直居中

**你期望 API 是什么样的？**
在van-row中增加一个可以使其垂直居中的api

**示例代码**
请展示一下新功能的大致用法

```js
```

```wxml
```

**Comment by rex-zsd** [comment]
不会支持，可以通过custom-class自定义样式
