### ISSUE TITLE
文档不更新了？

### ISSUE THREAD

**Issue by ChangeZhang** [youzan/vant-weapp#1685]
https://youzan.github.io/vant-weapp/#/intro 这个地址的文档怎么一直不更新了~~

**Comment by chenjiahan** [comment]
sorry 疏漏了，已更新，刷新一下就好

**Comment by ChangeZhang** [comment]
https://youzan.github.io/vant-weapp/#/changelog 又没更新了，都不知道更改了什么~

**Comment by ChangeZhang** [comment]
@chenjiahan

**Comment by chenjiahan** [comment]
@rex-zsd

**Comment by ChangeZhang** [comment]
@chenjiahan  @rex-zsd 辛苦了
