### ISSUE TITLE
如果我引入async、await支持就会报错

### ISSUE THREAD

**Issue by 9yues** [youzan/vant-weapp#1686]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**你需要的功能是？**
如果我引入async、await支持就会报错

**你期望 API 是什么样的？**
因为引入async await 支持的话，就得关掉es6转ES5，但是一关掉vant这边就会报错

**示例代码**
请展示一下新功能的大致用法
![image](https://user-images.githubusercontent.com/19297519/58935450-10ed1200-87a0-11e9-8ac5-5929bf8d8f75.png)

```js
```

```wxml
```

**Comment by 9yues** [comment]
或者哪位大哥能给一份编译好的ES5代码，这样的话我在开发者工具不开启ES6、转ES5，应该也能运行起来

**Comment by rex-zsd** [comment]
看下文档，有提供es5的版本
