### ISSUE TITLE
tabbar组件遮挡底部内容

### ISSUE THREAD

**Issue by good1uck** [youzan/vant-weapp#1687]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**描述一下问题**
tabbar组件遮挡底部内容

**截图**
1.wxml
![企业微信截图_20190605162154](https://user-images.githubusercontent.com/23480644/58941454-66302000-87ae-11e9-9f4e-a2f76325d5ee.png)
2.ui
![企业微信截图_20190605162054](https://user-images.githubusercontent.com/23480644/58941451-62040280-87ae-11e9-8446-e3a7419d11c7.png)

**暂行办法**
1.给内容增加高度
![企业微信截图_20190605162315](https://user-images.githubusercontent.com/23480644/58941522-94adfb00-87ae-11e9-818c-f40802533f90.png)
2.内容不被遮挡了
![企业微信截图_20190605162522](https://user-images.githubusercontent.com/23480644/58941548-9f689000-87ae-11e9-8ddd-5b8a074fbe81.png)

**环境**
 - 微信开发者工具: v1.02.1905151
 - Vant Weapp 版本:v0.5.12

**Comment by rex-zsd** [comment]
页面请自行组织，在底部预留足够的空间。
