### ISSUE TITLE
datetime-picker日期时间滚动的时候 增加惯性

### ISSUE THREAD

**Issue by Ludidi** [youzan/vant-weapp#1688]
**你需要的功能是？**
datetime-picker日期时间滚动的时候 增加惯性，滚动的时候可以更快的定位到需要的时间

**Comment by WEBhslv** [comment]
我使用这个组件的时候，先滑动选择时间，我没有滑动后，他自己还会上下滑动，你有遇到过吗？

**Comment by xupenghu** [comment]
> 我使用这个组件的时候，先滑动选择时间，我没有滑动后，他自己还会上下滑动，你有遇到过吗？

我也遇到了 不知道什么情况
