### ISSUE TITLE
关于van-submit-bar使用form中的report-submit="true"不起作用？

### ISSUE THREAD

**Issue by arrowfeng** [youzan/vant-weapp#1690]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

我想点击van-submit-bar返回form_id，我在form表单设置了report-submit="true"，但是不起作用，有什么好办法吗？

**Comment by rex-zsd** [comment]
暂时没有办法，由于微信小程序的限制，自定义组件中的button是无法触发report-submit的。
