### ISSUE TITLE
Dialog遮罩层无法遮盖原生组件tabBar

### ISSUE THREAD

**Issue by Anstall** [youzan/vant-weapp#1693]
**期望结果**
调用Dialog组件时，原生组件tabBar不能点击

**实际结果**
调用Dialog组件后，点击tabBar可以切换

**截图**
![image](https://user-images.githubusercontent.com/25213736/59257363-632ea700-8c68-11e9-955b-65e00fc5aea9.png)

**核心代码**

    <van-dialog
      show="{{isShowAuthDialog}}"
      title="授权提示"
      confirm-button-text="授权用户信息"
      confirm-button-open-type="getUserInfo"
      bind:getuserinfo="getUserInfo"
      message="{{message}}"
    >
    </van-dialog>

**环境**
 - 设备: 开发者工具/真机
 - 基础库版本: 2.7.1
 - Vant Weapp 版本: 0.5.14

**Comment by ll60** [comment]
这个tabar最高层级，不过可以用个小技巧，用wx.hideTabBar关掉，等请求完成之后再wx.showTabBar打开。包括小程序各种原生组件的层级问题可以用wx:if控制下。。虽然有点蛋疼。

**Comment by chenjiahan** [comment]
原生组件层级是最高的，覆盖不了，可以参考楼上的做法

**Comment by Anstall** [comment]
> 这个塔巴尔最高层级，不过可以用个小技巧，用wx.hideTabBar关掉，等请求完成之后再wx.showTabBar打开包括小程序各种原生组件的层级问题可以用WX：如果控制下..虽然有点蛋疼。

这个方法可行，谢谢提醒！

**Comment by Anstall** [comment]
> 这个tabar最高层级，不过可以用个小技巧，用wx.hideTabBar关掉，等请求完成之后再wx.showTabBar打开。包括小程序各种原生组件的层级问题可以用wx:if控制下。。虽然有点蛋疼。

这个方法可行，谢谢提醒！

**Comment by zhengpan** [comment]
> > 这个tabar最高层级，不过可以用个小技巧，用wx.hideTabBar关掉，等请求完成之后再wx.showTabBar打开。包括小程序各种原生组件的层级问题可以用wx:if控制下。。虽然有点蛋疼。
> 
> 这个方法可行，谢谢提醒！

顶部的标题栏没法隐藏，这个有什么好办法吗
