### ISSUE TITLE
关于Tab 标签页类不友好建议

### ISSUE THREAD

**Issue by qiuxiaojian** [youzan/vant-weapp#1694]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**你需要的功能是？**
1、需要在tab标签的类设置成宽度打开只有屏幕的40%左右的宽度，然后内容区其实就是继承父元素的宽度（即标签的总宽度），可是需求的tab的内容是是跟屏幕的宽度是一样的。尝试多种操作并无效。
2、关于tab自定义类的：文档提供的自定义类其实是受到了css层叠的影响的。如果如果不设置多层选择类（直接写文档提供的类名设置），其实是会导致无效的（因为单单写一个类，层级没有组件封装的类的等级高，会出现无效）。 文档说明也不够详细，对于新手，是很难理解的

**你期望 API 是什么样的？**
期望提供的类是最高级的，或者有层级关系的的话，说明有多少层。（当然对于属性有例子说明的话，就无敌了）

图片说明：
![image](https://user-images.githubusercontent.com/34261007/59257926-8574f480-8c69-11e9-90cf-5ca4b8d8131e.png)

```js
```

```wxml
```

**Comment by rex-zsd** [comment]
可以只用van-tab做顶部标签栏，下面的内容部分自行处理，通过事件控制内容部分的展示。
```html
<van-tabs active="{{ 1 }}" bind:change="onChange">
    <van-tab title="我创建的球队"></van-tab>
    <van-tab title="我加入的球队"></van-tab>
</van-tabs>
<view wx:if="{{ active === 1 }}">内容1</view>
<view wx:elif="{{ active === 2 }}">内容2</view>
```
