### ISSUE TITLE
field输入框，切换输入框时，键盘会先收起再弹出

### ISSUE THREAD

**Issue by HermioneZeng** [youzan/vant-weapp#1696]
比如输入账号密码，输入完账号后，再点击密码框，键盘会先收起再弹出，刚开始以为是卡了，后来发现官方的案例也会这样。

**Comment by rex-zsd** [comment]
正常的吧 从一个输入框点到另一个输入框是这样的没错

**Comment by HermioneZeng** [comment]
@rex-zsd 不正常啊，在安卓机上问题更严重，直接不弹出来了，要点2下，vant的vue组件完全不会有这个问题，切换输入框的时候键盘一直在那，小程序组件就有问题

**Comment by su1924** [comment]
苹果，安卓都弹不出，官网例子就不行，希望早日修改

**Comment by okayFan** [comment]
@rex-zsd 正常你妹妹啊 傻屌
