### ISSUE TITLE
dialog组件使用组件调用方式调用时，class-name属性不起作用

### ISSUE THREAD

**Issue by chengaobin** [youzan/vant-weapp#1697]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**描述一下问题**
dialog组件使用组件调用方式调用时，class-name属性不起作用，在模拟器可以起作用，
但是在真机时，在元素的class名字前会多出个dialog-index--，例如，我设置class-name='adv'
在真机的生成的class为dialog-index--adv,导致样式不起作用

**截图**
如果是 UI 问题，请提供具体截图
![image](https://user-images.githubusercontent.com/14012804/59411390-b7af5f00-8ded-11e9-92fa-29a9671e452e.png)

**核心代码**
请提供使用组件的核心代码
![image](https://user-images.githubusercontent.com/14012804/59411419-c8f86b80-8ded-11e9-9c4c-f4e64eedcffe.png)

```js
```

```wxml
```

**环境**
 - 设备:
realme x 安卓系统
 - 基础库版本:
 - Vant Weapp 版本:
0.5.10

**Comment by rex-zsd** [comment]
小程序外部样式类的原理就是这样的，会加前缀。
没生效可以看看增加`!important`

**Comment by sex-squirrel** [comment]
van-dialog 为什么强制加85%的width，还有白色背景？外部样式没用，这样完美无法完全控制slot的样式
