### ISSUE TITLE
radio  checked-color 选中之后把没选中的颜色都改了

### ISSUE THREAD

**Issue by shimangdian** [youzan/vant-weapp#1700]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**描述一下问题**
描述一下你遇到的问题，包括复现方式、导致结果
rt, 没选中之前是正确的
**截图**
如果是 UI 问题，请提供具体截图
、
默认的
![image](https://user-images.githubusercontent.com/23499945/59480796-9bb2c880-8e94-11e9-9fbe-4d477adabb73.png)

选中一个之后
![image](https://user-images.githubusercontent.com/23499945/59480703-41b20300-8e94-11e9-8156-31a7f84401af.png)

**核心代码**
请提供使用组件的核心代码
![image](https://user-images.githubusercontent.com/23499945/59480712-4ecef200-8e94-11e9-8dcc-69850c96ac6b.png)

```js
```

```wxml
```
![image](https://user-images.githubusercontent.com/23499945/59480731-63ab8580-8e94-11e9-9ca6-cb4ecd13182d.png)

**环境**
 - 设备:微信开发工具
 - 基础库版本:2.7.1
 - Vant Weapp 版本:0 .5.14

**Comment by rex-zsd** [comment]
感谢反馈 将在下版本修复
