### ISSUE TITLE
关于Loading 不显示文字

### ISSUE THREAD

**Issue by HDONGDeveloper** [youzan/vant-weapp#1708]
![image](https://user-images.githubusercontent.com/31230864/59595953-64107e80-9129-11e9-830c-a0814e9ef2d7.png)
![image](https://user-images.githubusercontent.com/31230864/59595964-68d53280-9129-11e9-82a3-26ea58efa22e.png)
不显示文字

**Comment by rex-zsd** [comment]
issue格式不规范
