### ISSUE TITLE
field输入框 ios原生键盘时输入会自动关闭键盘bug

### ISSUE THREAD

**Issue by daiwenbo19940227** [youzan/vant-weapp#1710]
当使用field输入框时，ios原生的输入键盘输入文字时，滑动选择联想的文字时，输入框会被关闭

**Comment by daiwenbo19940227** [comment]
微信小程序

**Comment by rex-zsd** [comment]
issue不符合规范，描述看不懂。
如果指的是选联想文案键盘收起的话，不是组件库的问题。键盘不是组件库实现的，小程序也没有提供控制收起键盘的API，完全是小程序的自身行为。

**Comment by chechengpeng** [comment]
为解决此bug，小程序已经在 input 组件中加入了 always-embed 属性，希望尽快跟进哦，辛苦开发兄弟！
