### ISSUE TITLE
Popup组件存在滚动穿透，遮罩层无法覆盖echart图表

### ISSUE THREAD

**Issue by silentchild** [youzan/vant-weapp#1712]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**描述一下问题**
描述一下你遇到的问题，包括复现方式、导致结果

**截图**
如果是 UI 问题，请提供具体截图

**核心代码**
请提供使用组件的核心代码

```js
```

```wxml
```

**环境**
 - 设备:
 - 基础库版本:
 - Vant Weapp 版本:

**Comment by rex-zsd** [comment]
注意[原生组件限制](https://developers.weixin.qq.com/miniprogram/dev/component/canvas.html#Bug-Tip)

**Comment by silentchild** [comment]
> 注意[原生组件限制](https://developers.weixin.qq.com/miniprogram/dev/component/canvas.html#Bug-Tip)

滚动穿透也是原生组件限制吗

**Comment by rex-zsd** [comment]
这个倒不是，可以修复一下。

**Comment by silentchild** [comment]
> 这个倒不是，可以修复一下。

小程序版和vue版都有这个问题，修的话一起修吧

**Comment by silentchild** [comment]
> 这个倒不是，可以修复一下。

其实可以考虑使用cover-view来写组件，这样会不会就解决了这些问题，不过工作量太大了

**Comment by rex-zsd** [comment]
cover-view限制太大，内部也必须全部用cover相关的原生组件来实现，易用性会大大下降。

**Comment by rex-zsd** [comment]
安卓基本上没有这个问题，主要是iOS下会出现滚动穿透的现象，不是很好处理。
如果确定popup内容部分没有内滚动的话，可以直接在popup上catch一下touchmove事件。
```html
<van-popup
  catchtouchmove="noop"
></van-popup>
```

**Comment by silentchild** [comment]
> 安卓基本上没有这个问题，主要是iOS下会出现滚动穿透的现象，不是很好处理。
> 如果确定popup内容部分没有内滚动的话，可以直接在popup上catch一下touchmove事件。
> 
> ```
> <van-popup
>   catchtouchmove="noop"
> ></van-popup>
> ```
popup内是需要滚动的picker组件，不能用这个方法

**Comment by shimangdian** [comment]
popup内有个列表。必须滚动，能解决吗？

**Comment by gromit1sm** [comment]
> popup内有个列表。必须滚动，能解决吗？

你解决这个问题没有
