### ISSUE TITLE
小程序的没有van-list

### ISSUE THREAD

**Issue by Bigsongyao** [youzan/vant-weapp#1713]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**你需要的功能是？**
我想要小程序有van-list

**你期望 API 是什么样的？**
和其它的一样

**示例代码**
和web的一样

```js
```

```wxml
```

**Comment by rex-zsd** [comment]
目前没有list组件，预计1.0版本会支持。

**Comment by hrhhz** [comment]
然而，到现在还是没有vanlist组件

**Comment by YadOwO** [comment]
然而，到现在还是没有vanlist组件

**Comment by MiniSnk** [comment]
然而，到现在还是没有vanlist组件
