### ISSUE TITLE
picker 组件对于懒加载的支持

### ISSUE THREAD

**Issue by Tzcodejs** [youzan/vant-weapp#1714]
**你需要的功能是？**
picker 组件目前好像不能支持懒加载，加载新的数据会造成picker组件重置，回到索引为0的选项。

**你期望 API 是什么样的？**
按照官方文档即可。

**Comment by rex-zsd** [comment]
用picker组件提供的`setValues`、`setIndexes`等方法手动设置需要选中的原选项可以满足吗？
