### ISSUE TITLE
网络渲染层错误

### ISSUE THREAD

**Issue by good1uck** [youzan/vant-weapp#1715]
Failed to load font https://img.yzcdn.cn/van/van-icon-839a51.ttf
the server responded with a status of 404 (HTTP/1.1 404 Not Found) 
From server 27.159.71.248

**Comment by good1uck** [comment]
VM1641:1 Failed to load font https://img.yzcdn.cn/van/van-icon-839a51.woff2
net::ERR_CACHE_MISS

**Comment by good1uck** [comment]
VM1641:1 Failed to load font https://img.yzcdn.cn/van/van-icon-839a51.woff2
net::ERR_CACHE_MISS

**Comment by rex-zsd** [comment]
这个错误微信开放社区应该能搜到很多了。
加载字体报的错，不影响真机渲染。
