### ISSUE TITLE
example文件夹用微信开发工具运行不起来

### ISSUE THREAD

**Issue by iwaygan** [youzan/vant-weapp#1717]
按照编译报错倒腾了一下，还是没解决，可能还不够熟悉，望高手指点

**Comment by jokimina** [comment]
![image](https://user-images.githubusercontent.com/11460661/59959420-612ada80-94e9-11e9-800d-d371935e2b7e.png)

同无法运行, dev, master以及 v0.5.14 tag均会报错

**Comment by rex-zsd** [comment]
# 安装项目依赖
npm install

# 执行组件编译
npm run dev

这两部有执行吗？

**Comment by luyk** [comment]
![图片](https://user-images.githubusercontent.com/15984125/60395849-2cafc200-9b6c-11e9-8390-b08793f6a9e1.png)
![图片](https://user-images.githubusercontent.com/15984125/60395855-481acd00-9b6c-11e9-96d4-aa43f5703862.png)
npm install
npm run dev
编译成功后，用微信开发者工具导入example项目，报错无法预览

**Comment by rex-zsd** [comment]
```
npm install
npm run dev
```
运行的输出看一下，是否有报错
example实在跑不起来的话可以直接扫码打开我们的demo小程序，对照着example的代码看。

**Comment by QQwangxiaoqing** [comment]
遇到一样的问题
