### ISSUE TITLE
picker选择器如何搭配弹出层使用

### ISSUE THREAD

**Issue by EDGDK** [youzan/vant-weapp#1720]
我现在想使用pick搭配弹出层进行选择。

本人刚刚入坑小程序，翻阅了一下官方文档，对于这块有案例展示，但是没有具体代码。
![image](https://user-images.githubusercontent.com/23516142/59995916-5f991800-968b-11e9-8da0-2de05daf5abf.png)

**Comment by rex-zsd** [comment]
#1660 重复issue，可以关注这个

**Comment by EDGDK** [comment]
尴尬 那个也是我问的 但是没人回答官网文档也没有，仔细看了下 有一些文档没例子

**Comment by pipione** [comment]
<van-action-sheet show="{{ showEditOffsetActionSheet }}">
        <view class="picker-container">
            <van-row custom-class="picker-operate">
                <van-col custom-class="cancel left" span="12" ><text class="text-btn" bindtap="cancelEditOffsetActionSheet">取消</text></van-col>
                <van-col custom-class="confirm right" span="12"><text class="text-btn" bindtap="confirmEditOffsetActionSheet">确认</text></van-col>
            </van-row>
            <van-row custom-class="picker-value">
                <van-col custom-class="picker__stepper" span="10">
                    <view class="text-btn sub">-</view>
                    <view class="text-btn add">+</view>
                </van-col>
                <van-col span="8">
                    <van-picker
                            columns="{{ columns }}"
                    />
                </van-col>
            </van-row>
        </view>
    </van-action-sheet>

你可以参考我的示例 ： 把picker 嵌入到action-sheet   https://youzan.github.io/vant-weapp/#/action-sheet

**Comment by EDGDK** [comment]
> ```
> <van-action-sheet show="{{ showEditOffsetActionSheet }}">
>     <view class="picker-container">
>         <van-row custom-class="picker-operate">
>             <van-col custom-class="cancel left" span="12" ><text class="text-btn" bindtap="cancelEditOffsetActionSheet">取消</text></van-col>
>             <van-col custom-class="confirm right" span="12"><text class="text-btn" bindtap="confirmEditOffsetActionSheet">确认</text></van-col>
>         </van-row>
>         <van-row custom-class="picker-value">
>             <van-col custom-class="picker__stepper" span="10">
>                 <view class="text-btn sub">-</view>
>                 <view class="text-btn add">+</view>
>             </van-col>
>             <van-col span="8">
>                 <van-picker
>                         columns="{{ columns }}"
>                 />
>             </van-col>
>         </van-row>
>     </view>
> </van-action-sheet>
> ```
> 
> 你可以参考我的示例 ： 把picker 嵌入到action-sheet https://youzan.github.io/vant-weapp/#/action-sheet

好的 我看下

**Comment by EDGDK** [comment]
> ```
> <van-action-sheet show="{{ showEditOffsetActionSheet }}">
>     <view class="picker-container">
>         <van-row custom-class="picker-operate">
>             <van-col custom-class="cancel left" span="12" ><text class="text-btn" bindtap="cancelEditOffsetActionSheet">取消</text></van-col>
>             <van-col custom-class="confirm right" span="12"><text class="text-btn" bindtap="confirmEditOffsetActionSheet">确认</text></van-col>
>         </van-row>
>         <van-row custom-class="picker-value">
>             <van-col custom-class="picker__stepper" span="10">
>                 <view class="text-btn sub">-</view>
>                 <view class="text-btn add">+</view>
>             </van-col>
>             <van-col span="8">
>                 <van-picker
>                         columns="{{ columns }}"
>                 />
>             </van-col>
>         </van-row>
>     </view>
> </van-action-sheet>
> ```
> 
> 你可以参考我的示例 ： 把picker 嵌入到action-sheet https://youzan.github.io/vant-weapp/#/action-sheet

好的 我看下

**Comment by BrotherFly** [comment]
> 我现在想使用pick搭配弹出层进行选择。
> 
> 本人刚刚入坑小程序，翻阅了一下官方文档，对于这块有案例展示，但是没有具体代码。
> ![image](https://user-images.githubusercontent.com/23516142/59995916-5f991800-968b-11e9-8da0-2de05daf5abf.png)

https://blog.csdn.net/u011320260/article/details/93652436

**Comment by EDGDK** [comment]
> > 我现在想使用pick搭配弹出层进行选择。
> > 本人刚刚入坑小程序，翻阅了一下官方文档，对于这块有案例展示，但是没有具体代码。
> > ![image](https://user-images.githubusercontent.com/23516142/59995916-5f991800-968b-11e9-8da0-2de05daf5abf.png)
> 
> https://blog.csdn.net/u011320260/article/details/93652436

懂了，谢谢原来是直接在单元格里面调popup直接拉起picker就行
