### ISSUE TITLE
[Bug Report] 按照文档使用van-tabs，添加swipeable属性在设备预览时滑动切换没有效果，是否还需要其他设置？

### ISSUE THREAD

**Issue by lzpswat** [youzan/vant-weapp#1724]
### 设备
索尼xz1（安卓9.0）

### VantWeapp 版本
0.5.12

### 基础库版本
2.7.1

### 如果是 UI 问题，截图链接（多图回车分隔）

![截图](<script)

![截图](src="https://gist.github.com)

### 请提供核心代码片段链接
https://gist.github.com/lzpswat/b1b443dc127d0135b251fac01d90a139

### 描述问题
按照文档使用van-tabs，添加swipeable属性在设备预览时滑动切换没有效果，是否还需要其他设置？

**Comment by rex-zsd** [comment]
没有其他设置了，demo小程序中是ok的，对照下example的代码再看下吧~
