### ISSUE TITLE
[Bug Report] van-button、van-field属性问题

### ISSUE THREAD

**Issue by BigHuiWolf** [youzan/vant-weapp#1725]
### 设备
微信小程序，开发者工具及OPPOr7sm

### VantWeapp 版本
0.5.15

### 基础库版本
小程序开发调试库2.7.2

### 如果是 UI 问题，截图链接（多图回车分隔）

![截图](https://i.loli.net/2019/06/26/5d12e716284f976883.jpg)

### 请提供核心代码片段链接
https://gist.github.com/BigHuiWolf/28017b51bf931b5da5db5b2657574e50#gistcomment-2954012

### 描述问题
1、van-button的disabled属性仅样式改变，仍是可点击状态。（无法有效截图，点击状态你们可测试）
2、van-field的error属性仅placeholder生效，value未受影响，跟文档展示效果相驳。（有截图，有链接）

**Comment by Lay3** [comment]
碰到相同的问题，项目比较紧急。。属实尴尬

**Comment by BigHuiWolf** [comment]
什么时候解决啊，等得我花儿都谢了，0.0

**Comment by 15922501743** [comment]
我也遇到这个问题了。

**Comment by chenjiahan** [comment]
解释一下，button 提供的是 click 事件，而不是 tap 事件。

这两者的区别是，click 事件是组件提供的自定义事件，当按钮 disabled 时，是不会触发的 click 事件的。

而 tap 事件是小程序的原生事件，它绑定在组件的 shadow root 上，我们无法控制 tap 事件是否触发，除非设置原生 disabled 属性。

但是我们并不会设置原生 disabled 属性，因为小程序内设置 disabled 属性后会添加一些默认样式，导致按钮的样式不正确。

因此对于这个问题，直接使用 click 事件即可解决。

**Comment by chenjiahan** [comment]
Field 的问题下个版本会修复，Button 的问题后续会在文档里说明

**Comment by chenjiahan** [comment]
已在 0.5.18 版本修复

**Comment by lyq027** [comment]
button disabled问题解决了吗，在mpvue中使用@click，还是会触发点击事件

**Comment by BigHuiWolf** [comment]
> button disabled问题解决了吗，在mpvue中使用@click，还是会触发点击事件

我没试了，之前我都换成原生button进行封装使用了。

**Comment by lyq027** [comment]
@chenjiahan  button disabled在mpvue中使用@click，还是会触发点击事件
