### ISSUE TITLE
关于van-popup 和 微信map组件

### ISSUE THREAD

**Issue by 841464118** [youzan/vant-weapp#1726]
如下图，代码的预期实现是：用户点击 **区域**/**类别**/**价格**/**更多筛选** 都会弹出van-popup。
遇到的问题：van-popup在弹出时自带的遮罩层盖不住微信的map组件。

![$R %( ~3(TO528$M R4E_AB](https://user-images.githubusercontent.com/33533905/60162054-4af38600-982b-11e9-8cde-6d7ee5e61fea.png)

**Comment by chenjiahan** [comment]
参见 https://github.com/youzan/vant-weapp/issues/646
