### ISSUE TITLE
[Feature Request] dialog希望可以设置在手机屏幕居中显示

### ISSUE THREAD

**Issue by cywork** [youzan/vant-weapp#1729]
### 这个功能解决了什么问题
目前的dialog默认是页面居中，显示可能会比手机屏幕居中偏低。
在手机屏幕居中显示，也许有更好的体验。

### 建议的API是什么样的
:screenCentered="true"

**Comment by chenjiahan** [comment]
下个版本会默认上调一点位置，和微信的弹窗大致在一个高度

**Comment by rex-zsd** [comment]
#1781 已经调整了默认的位置，#1808 新增了`custom-stye`属性，可以用这个自定义一下位置。
