### ISSUE TITLE
tabs底部条宽度问题

### ISSUE THREAD

**Issue by swearl** [youzan/vant-weapp#1730]
使用tabs时, line-width的默认值是"与当前标签等宽"

但如果我在tab中使用了info, 那么tab的宽度就加大了, 但是line-width的宽度还是原来没有info的宽度, 这样就显示有点不好看了...

**Comment by 3326Bai** [comment]
唔，想请教您怎么把tabbar整合到小程序里的

**Comment by swearl** [comment]
> 
> 
> 唔，想请教您怎么把tabbar整合到小程序里的

第三方tabbar如果要做得切换好看, 基本都要单页面

**Comment by rex-zsd** [comment]
现在底部线条宽度已经包含info了

**Comment by rex-zsd** [comment]
@3326Bai tabbar整合可以看下[文档](https://youzan.github.io/vant-weapp/#/tabbar#jie-he-zi-ding-yi-tabbar)，有完整的代码片段示例。
