### ISSUE TITLE
很多组件的 Slot 没有效果

### ISSUE THREAD

**Issue by wendraw** [youzan/vant-weapp#1732]
https://youzan.github.io/vant-weapp 中很多例子中的效果出不来，如 Field 的 label 属性，Card 的 tag 属性等等。还有使用 Slot 来创建的效果使用不了，比如 Card 的 footer。作为新手这些东西比较困惑。

**Comment by wendraw** [comment]
我使用的是从 GitHub clone 最新版的

**Comment by rex-zsd** [comment]
issue格式不符合规范，请使用https://youzan.github.io/vant-issue-generater生成

还有，使用姿势类的issue，如果不贴如何使用的代码，是完全没有办法帮你的。
