### ISSUE TITLE
van-cell   van-cell-group  都不能显示出来  再 mpvue框架下 

### ISSUE THREAD

**Issue by leida1983** [youzan/vant-weapp#1734]
<div v-if="StepIndex == 3">
        <van-cell-group title="基本信息">
          <van-field v-model="xm" label="学员姓名" placeholder="请输入学员的真实姓名" />
          <van-field v-model="sfzmhm" label="证件号码" placeholder="请输入您的身份证件号码" />
          <van-field v-model="djzsxxdz" label="登记住所" placeholder="请输入您的身份证件登记地址" />
          <van-cell title="学员性别" :value="xb == 1?'男':'女'" />
        </van-cell-group>
      </div>

**Comment by rex-zsd** [comment]
issue没有内容，帮不了你了。
