### ISSUE TITLE
textarea输入框placeholder问题，iOS下输一串拼音还没确定中文时，拼音会跟placeholder重叠

### ISSUE THREAD

**Issue by vikingfeng** [youzan/vant-weapp#1735]
### 设备
iOS设备（iPhone XR）

### VantWeapp 版本
0.5.15

### 基础库版本
v2.7.1

### 如果是 UI 问题，截图链接（多图回车分隔）

![截图](https://i.loli.net/2019/07/01/5d196a660ac6389316.png)

![截图](https://i.loli.net/2019/07/01/5d196a661783666774.png)

### 请提供核心代码片段链接
https://youzan.github.io/vant-weapp/#/field

### 描述问题
在ios设备下，textarea输入框有placeholder时，输入拼音未选中中文时，拼音与placeholder重叠显示在输入框（如上图）。推测是（Field: 使用 view 模拟 textarea 的 placeholder, 修复 placeholder 漂移问题 #1527）这个引起的。
此问题在小米9下不会（安卓机应该都不会）出现

**Comment by rex-zsd** [comment]
跟目前`textarea`的`placeholder`实现方式有关。
