### ISSUE TITLE
mpvue中van-cell如何自定义title/value/label的样式

### ISSUE THREAD

**Issue by kongxubihai** [youzan/vant-weapp#1736]
设备 / 浏览器
谷歌浏览器

Vant 版本
2.0.3

Vue版本
2.6.10

重现链接 暂无
https://codesandbox.io

描述问题
mpvue中van-cell 暂无发现如何自定义title/value/label的样式；需要自行去修改源码样式？

**Comment by rex-zsd** [comment]
可以参考文档的外部样式类部分。
![image](https://user-images.githubusercontent.com/8767877/60571206-b9919000-9da5-11e9-9490-177654393012.png)

**Comment by MrDragonn** [comment]
value-class 里设置color：red 不生效

**Comment by kongxubihai** [comment]
> value-class 里设置color：red 不生效
在调试工具里看一下该样式是否被覆盖了，必要时使用!important
