### ISSUE TITLE
关于button 中如何设置iocn问题

### ISSUE THREAD

**Issue by zhoufanglu** [youzan/vant-weapp#1737]
![image](https://user-images.githubusercontent.com/24451091/60425919-23832b80-9c26-11e9-9c1d-87582f3f10c2.png)
这样写，在页面上不显示 `在线咨询`
请问如何在button中增加icon
官网中并没有说明！谢谢

**Comment by BigHuiWolf** [comment]
![1562057194(1)](https://user-images.githubusercontent.com/36195100/60498378-06636100-9ce9-11e9-965f-353a57c709ad.jpg)
类似上图，是可以的，在按钮内自定义icon或图片

**Comment by zhoufanglu** [comment]
> ![1562057194(1)](https://user-images.githubusercontent.com/36195100/60498378-06636100-9ce9-11e9-965f-353a57c709ad.jpg)
> 类似上图，是可以的，在按钮内自定义icon或图片

我不显示啊，是不是因为环境是mpvue2.0的原因

**Comment by BigHuiWolf** [comment]
不知道，我在小程序里面直接这么写的

**Comment by rex-zsd** [comment]
跟vant-weapp似乎没什么关系，可以谷歌一下mpvue如何用字体图标。
