### ISSUE TITLE
field input-align="right"时 placehoder还是居左的

### ISSUE THREAD

**Issue by yaoshanliang** [youzan/vant-weapp#1741]
如题，field input-align="right"时 placehoder还是居左的

`<van-field label="物品描述" value="{{ description }}" type="textarea" autosize  size="large" input-align="right" placeholder="请输入描述信息" />`

![image](https://user-images.githubusercontent.com/5028569/60632931-e8a61100-9e3a-11e9-8214-0f6920bf8e7c.png)
![image](https://user-images.githubusercontent.com/5028569/60632938-ef348880-9e3a-11e9-8a03-4bdc98f53b39.png)

**Comment by yaoshanliang** [comment]
有人解答么

**Comment by 602122993** [comment]
你要设置 placehoder-style  普通模式下就有效了....但是文本域无效..... 我正要提issue

**Comment by rex-zsd** [comment]
#1764 已经修复了，下版本发布
