### ISSUE TITLE
文档中手机端业务组件内容比pc端多了些许，但是手机端是不展示那些组件的详细介绍的

### ISSUE THREAD

**Issue by gzlsmcl** [youzan/vant-weapp#1742]
![image](https://user-images.githubusercontent.com/46860071/60639207-3418e900-9e54-11e9-968f-0d960e385e91.png)这是手机端
![image](https://user-images.githubusercontent.com/46860071/60639256-6d515900-9e54-11e9-8bea-bd70eebe6c14.png)
这是pc端
很明显，手机端的业务组件内容是比pc要多好几个的。
我非常希望 在pc上可以看到这些内容 因为手机上无法查看那些组件的详细介绍的

**Comment by rex-zsd** [comment]
上图是vue版的vant的示例，vant-weapp中并没有实现。
