### ISSUE TITLE
请问class="checkboxes-{{ index }}" 如何在mpvue使用

### ISSUE THREAD

**Issue by liuyaochen04** [youzan/vant-weapp#1743]
checkbox 复选框 搭配单元格组件使用
` <van-cell
        v-for="(item,index) in list"
        :key="index"
        title="复选框"
        value-class="checkboxFiled"
        clickable
        :data-index="index"
        @click="toggle"
      >`
`     <van-checkbox catch:tap="noop" class="checkboxes-{{ index }}" name="{{ item }}" />`
`</van-cell>`
 class="checkboxes-{{ index }}
mpvue提示使用时需要 :index 可是前面还有字符串如何拼接？如果放在计算属性中 怎么传值呢 谢谢。

**Comment by liuyaochen04** [comment]
我自己填坑。 可能回答不是最好的。
  <van-checkbox-group :value="result" @change="onChange">
    <van-cell-group >
      <van-cell
        v-for="(item,index) in list"
        :key="index"
        :title="item.name"
        value-class="checkboxFiled"
        clickable
        :data-index="index"
        @click="toggle"
      >
        <van-checkbox @tap.stop="noop"  :class="'checkboxes-'+index"  :name="item.id" />
      </van-cell>
    </van-cell-group>
  </van-checkbox-group>
///////////////////////////
   data() {
      return {
        list:[
          {
            id:"1",
            name:"lyc"
          },
          {
            id:"2",
            name:"jmx"
          }, {
            id:"3",
            name:"yrx"
          }

        ],
        result: []
      }
    },
    methods: {
      onChange(event) {
        this.result=event.mp.detail;
      },
      toggle(event) {
        const { index } = event.currentTarget.dataset;
        const checkbox = this.$mp.page.selectComponent(`.checkboxes-${index}`);
        checkbox.toggle();
      },
      noop() {
        console.info("noop已组织冒泡");
      }
    }

**Comment by yuyu147** [comment]
你toggle能用？

**Comment by Rayzworld** [comment]
checkbox拿到的不是null？
