### ISSUE TITLE
mpvue 外部样式类 应用不好用，dom可以查看到class类名 但是无css样式

### ISSUE THREAD

**Issue by liuyaochen04** [youzan/vant-weapp#1744]
类名 | 说明
-- | --
input-class | 输入框样式类
right-icon-class

这种的都失效了请问如何处理比较好

**Comment by liuyaochen04** [comment]
去掉scoped jiuhaole

**Comment by liumin1128** [comment]
去掉scoped也没用啊

**Comment by liumin1128** [comment]
验证了下，去掉scoped可以应用样式，但要优先级不够高，要加!important
