### ISSUE TITLE
[Bug Report] van-field小程序聚焦问题

### ISSUE THREAD

**Issue by liknzero** [youzan/vant-weapp#1747]
### 设备
魅族pro6, iPhone8, iphoneX等部分机型

### VantWeapp 版本
0.5.14

### 基础库版本
2.7.3

### 如果是 UI 问题，截图链接（多图回车分隔）

![截图](https://i.loli.net/2019/07/05/5d1ebdfd2f27c68320.png)

![截图](https://i.loli.net/2019/07/05/5d1ebdfd3eba342108.png)

![截图](https://i.loli.net/2019/07/05/5d1ebdfcb481c17491.jpg)

### 请提供核心代码片段链接
https://gist.github.com/a10bbfd5349a98b6a8f5aed984c501e7.git

### 描述问题
van-field使用真机测试,点击聚焦, 默认的placeholder字体会加粗.使用小程序原生的就不会,图片中上面两张是用vant组件写的, 下面最后一张图是用小程序原生写的, 点击聚焦的时候,不会出现placeholder字体加粗的情况,

**Comment by chenjiahan** [comment]
这是微信小程序原生组件导致的问题，暂时无解，可以等待官方优化

参考链接：https://developers.weixin.qq.com/community/develop/doc/0002ac32fd0e88082aa84865b5fc00?highLine=placeholder%2520%25E5%258A%25A0%25E7%25B2%2597

**Comment by maruihua1997** [comment]
同求解决办法。只是加粗可以添加input-class给字体加上font-weight就可以了，但是在安卓手机中input框获取焦点后会跳一下。有没有解决办法

**Comment by rex-zsd** [comment]
field没有给placeholder增加加粗的样式，placeholder的加粗、闪烁都是微信小程序的默认行为，可以参考https://developers.weixin.qq.com/community/develop/doc/0002ac32fd0e88082aa84865b5fc00?highLine=placeholder%25E5%258A%25A0%25E7%25B2%2597
