### ISSUE TITLE
小程序TreeSelect 分类选择组件问题

### ISSUE THREAD

**Issue by xiaoshuoyiyi** [youzan/vant-weapp#1750]
小程序的分类选择器组件最多只有7组数据吗？左侧分类导航，右侧分类选择都是七个！
![1562491012639](https://user-images.githubusercontent.com/28432902/60766367-5a9c8580-a0db-11e9-82a6-13bcab92c6c0.jpg)

**Comment by rex-zsd** [comment]
并不，取决于你的数据条数和设置的`maxHeight`属性。
