### ISSUE TITLE
关于Van-Field不支持双向绑定的解决方案，只用一个监听方法解决区分字段问题

### ISSUE THREAD

**Issue by seemgame** [youzan/vant-weapp#1751]
最近使用uni-app开发小程序，ui组件用的vant-weapp，在表单提交中发现值还是空的，看issues有不少这个问题，原因是不支持，要使用bind:input/change方法。但是这里有个坑，每个字段都用一个方法来获取的话不太现实，于是看到文档有个name的属性值可以用来区分，但是坑爹的字段用了没反应，最后看了组件原文件，发现根本没写进去，于是只能自己动手了。

组件路径：/vant/field/index.js

**修改步骤**

`props对象加入：name:  String`

`onInput方法修改：this.emitChange({value, name: this.data.name})`

**使用步骤**

组件引用：
`<van-field
			size='large'
			:value="form.wechat"
			label="微信号"
			placeholder="请输入微信号"
			input-align='right'
			name='wechat'
			v-on:input='onInput'
		  />`

方法：
`onInput (event) {
				最后值和标识都在event.detail里面，根据业务自行调用咯
			}`

**注意**
未修改前 v-on:input 中返回的 event.detail 是表单上的值，类型是STRING。
修改后 v-on:input 中返回的 event.detail 是一个对象，对象里面的 value 才是表单上的值。

**Comment by rex-zsd** [comment]
`name`字段是有的，使用`wx://form-field`的behavior会给自定义组件自动加上`name`和`value`属性。
还有按照你的修改事件传参会造成breaking change。
表单的问题可以参考下小程序官方的[form部分](https://developers.weixin.qq.com/miniprogram/dev/component/form.html)，vant-weapp表单类组件都配置了`wx://form-field`，会有标准的表单组件行为。

**Comment by chen-can** [comment]
我也遇到了 有没有示例demo

**Comment by seemgame** [comment]
感谢大大指导，我在获取formId时已经发现了我这样做所引发的问题了。所以上面的方法不可取。
