### ISSUE TITLE
IndexBar 索引栏

### ISSUE THREAD

**Issue by JacksonMeng** [youzan/vant-weapp#1752]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater?repo=VantWeapp

---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater?repo=VantWeapp

**Comment by JacksonMeng** [comment]
IndexBar 索引栏怎么使用，文档上没有这个东西

**Comment by chenjiahan** [comment]
目前仅在 Vue 版本的 Vant 中提供 IndexBar 组件喔
