### ISSUE TITLE
使用van-tabbar自定义tabbar页面跳转到其他页面依然带tabbar

### ISSUE THREAD

**Issue by guziping** [youzan/vant-weapp#1753]
Component({
  data: {
    active: 0,
    list: [
      {
        icon: 'send-gift',
        text: '产品',
        url: '/pages/item/item'
      },
      {
        icon: 'column',
        text: '订单',
        url: '/pages/order/order'
      },
      {
        icon: 'bill',
        text: '对账',
        url: '/pages/doc/me/me'
      },
      {
        icon: 'manager',
        text: '我的',
        url: '/pages/doc/me/me'
      }
    ]
  },

  methods: {
    onChange(event) {
      this.setData({ active: event.detail });
      wx.switchTab({
        url: this.data.list[event.detail].url
      });
    },

    init() {
      const page = getCurrentPages().pop();
      this.setData({
        active: this.data.list.findIndex(item => item.url === `/${page.route}`)
      });
    }
  }
});
我从这四个页面跳转到其他页面如
`<van-cell icon="home-o" title="" value="采购商" is-link profilelink-type="navigateTo" url="type/type"/>`
type/type这个页面依然带tabbar，为什么，跟官方代码对比过，一直都没找到原因，求解答

**Comment by rex-zsd** [comment]
参考小程序官方文档，看app.json是怎么配置的。
