### ISSUE TITLE
能支持uni-app吗？

### ISSUE THREAD

**Issue by wanganxp** [youzan/vant-weapp#1754]
虽然uni-app支持小程序组件，从而可以在微信端使用vant。但其他端使用不了。
uni-app的插件市场有很多多端通用组件，https://ext.dcloud.net.cn/，希望vant能支持uni-app的多端组件，其实就是把vant-weapp改成vue组件写法

**Comment by chenjiahan** [comment]
暂无计划支持喔，如果改写成 uni-app 的写法，就相当于和 uni-app 强制绑定了，会导致其他用户无法使用

**Comment by guojingwen** [comment]
> 然uni-app支持小程序组件，从而可以在微信端使用vant。

微信端可以使用吗？ 能提供一个demo吗
