### ISSUE TITLE
[Bug Report] 输入框在type=textarea的情况下 在placeholder-style中设置的样式不会影响placeholder

### ISSUE THREAD

**Issue by 602122993** [youzan/vant-weapp#1755]
### 设备
iphone8plus

### VantWeapp 版本
0.5.15

### 基础库版本
2.6.6

### 如果是 UI 问题，截图链接（多图回车分隔）

![截图](https://i.loli.net/2019/07/10/5d25f2d7c621e95871.png)

### 请提供核心代码片段链接
https://gist.github.com/602122993/92c155fd0d382822a96495d6ca2512db

### 描述问题
输入框在type=textarea的情况下 在placeholder-style中设置的样式不会影响placeholder  文字的样式是可以正常显示的

**Comment by rex-zsd** [comment]
textarea的placeholder是组件库自己实现的，与原生的样式有部分不统一，将在下版本修复。
