### ISSUE TITLE
[Bug Report] Field的bind:input在真机上对于输入字母无效

### ISSUE THREAD

**Issue by I322871** [youzan/vant-weapp#1756]
### 设备
魅族16

### VantWeapp 版本
0.5.15

### 基础库版本
2.7.0

### 请提供核心代码片段链接
https://youzan.github.io/vant-weapp/#/field

### 描述问题
我使用field，并使用bind:change方法来更新绑定的字段。在开发者工具中运行完美。但是在我的真机上出现如下情况：
1. 当输入数字时，绑定的字段会被实时更新；
2. 当输入汉字时，绑定的字段会被实时更新；
3. 当输入一串英文字母时，输入完必须先失焦，绑定的字段才会被更新。例如我连续输入“abcdefg”，然后在field并未失焦的情况下马上点击一个button去检查field的内容，发现是输入前的内容。

**Comment by JakeLaoyu** [comment]
可以在button事件中 取值操作设置一个延迟

**Comment by rex-zsd** [comment]
设置延迟+1，大概率是微信小程序本身的问题。
