### ISSUE TITLE
[Bug Report] cell 只输入value的情况下还是靠右对齐

### ISSUE THREAD

**Issue by 602122993** [youzan/vant-weapp#1758]
### 设备
iphone8plus

### VantWeapp 版本
0.5.15

### 基础库版本
2.6.6

### 如果是 UI 问题，截图链接（多图回车分隔）

![截图](https://i.loli.net/2019/07/11/5d2698c0e514490350.jpg)

### 请提供核心代码片段链接
https://gist.github.com/602122993/18a8c67431082c71022a2448c9f85954

### 描述问题
cell 只输入value的情况下还是靠右对齐 文档里有这个功能的实现但是没有demo 我按照文档上说的 只配置demo 还是靠右对齐

**Comment by rex-zsd** [comment]
这个特性目前只有vant支持，vant-weapp受限于小程序的机制并不支持。
demo是vant和vant-weapp共用的，所以这里会有点迷。

**Comment by rex-zsd** [comment]
可以用`value-class`手动控制一下这个`text-align`的样式。
