### ISSUE TITLE
[Feature Request] 建议修改van-cell子元素的宽度

### ISSUE THREAD

**Issue by bks233** [youzan/vant-weapp#1760]
### 这个功能解决了什么问题
子元素内容过长会掉下来换行

### 建议的API是什么样的
.van-cell {justify-content:space-between;} 
里面的元素flex:none

**Comment by rex-zsd** [comment]
这个可以通过几个外部样式类`custom-class` `title-class`自行控制一下。

**Comment by bks233** [comment]
嗯 我是这么做的。但我想表达的是最好默认就是用space-between，而不是flex：1。这么做可以输入更多的文案而不会换行...



------------------ 原始邮件 ------------------
发件人: "rex"<notifications@github.com>; 
发送时间: 2019年7月15日(星期一) 上午10:47
收件人: "youzan/vant-weapp"<vant-weapp@noreply.github.com>; 
抄送: "白开水sss"<846936341@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [youzan/vant-weapp] [Feature Request] 建议修改van-cell子元素的宽度 (#1760)




这个可以通过几个外部样式类custom-class title-class自行控制一下。
