### ISSUE TITLE
wepay 编译后 utils.wxs中的内容无法被引入

### ISSUE THREAD

**Issue by xiongs** [youzan/vant-weapp#1770]
用wepay编译后，组件中的引用的 utils.wxs 文件代码
以下部份未部引入
var bem = require('./bem.wxs').bem;
var memoize = require('./memoize.wxs').memoize;

**Comment by chenjiahan** [comment]
如果是 wepy 新版的问题，请到 wepy 仓库下反馈，感谢配合
