### ISSUE TITLE
存在将未绑定在 WXML 的变量传入 setData

### ISSUE THREAD

**Issue by superlbr** [youzan/vant-weapp#1773]
微信开发工具，Audits又提示了

变量名 | 调用堆栈 | 调用组件 | 页面
-- | -- | -- | --
count|   | static/vant/picker-column/index | pages/index/main
baseOffset|   | static/vant/picker-column/index | pages/index/main
offset|   | static/vant/picker-column/index | pages/index/main
startY|   | static/vant/picker-column/index | pages/index/main
startOffset|   | static/vant/picker-column/index | pages/index/main

**Comment by rex-zsd** [comment]
这些是必要的参数，可以先忽略提示。
