### ISSUE TITLE
[Feature Request] field禁止弹出键盘

### ISSUE THREAD

**Issue by rungroo** [youzan/vant-weapp#1775]
### 这个功能解决了什么问题
当点击field时，有popup弹出picker供用户选择（比如男女，城市等），此时不需要系统弹出软键盘输入文字。即便为field内的input设置ime-mode也无法生效。

另外，像MintUI、WeUI等，都提供了日期field的示例（底层是input type='date'实现的），这个常用功能是否也能做一个例子？我试过，type='date'无效。

### 建议的API是什么样的
field中加入一个属性imemode，参考css属性ime-mode。

**Comment by rex-zsd** [comment]
field就是一个输入组件，不需要输入的场景可以用cell替代。
微信小程序是不支持input组件的type为`date`的，需要选择日期可以使用cell搭配datetime-picker组件。
