### ISSUE TITLE
[Bug Report] ios 系统切换语言 图标字体bug GoodsAction bug

### ISSUE THREAD

**Issue by webtianjia** [youzan/vant-weapp#1776]
### 设备
ios 任意系列

### VantWeapp 版本
0.5.16

### 基础库版本
2.7.0

### 如果是 UI 问题，截图链接（多图回车分隔）

![截图](https://i.loli.net/2019/07/18/5d30125025d6812568.jpg)

### 请提供核心代码片段链接
https://i.loli.net/2019/07/18/5d30125025d6812568.jpg

### 描述问题
ios 系统切换语言 图标字体bug GoodsAction bug

**Comment by rex-zsd** [comment]
vant-weapp的组件是没有指定字体的，默认用的就是系统字体。
请问有修改过系统字体吗？推测是系统字体不支持这几个中文的显示

**Comment by webtianjia** [comment]
正是修改系统字体为韩语




------------------ 原始邮件 ------------------
发件人: "elcarim5efil"<notifications@github.com>;
发送时间: 2019年7月23日(星期二) 上午10:24
收件人: "youzan/vant-weapp"<vant-weapp@noreply.github.com>;
抄送: "田佳"<676854227@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [youzan/vant-weapp] [Bug Report] ios 系统切换语言 图标字体bug GoodsAction bug (#1776)




vant-weapp的组件是没有指定字体的，默认用的就是系统字体。
 请问有修改过系统字体吗？推测是系统字体不支持这几个中文的显示

**Comment by rex-zsd** [comment]
那是正常的吧…………字体库里没有这几个汉字
