### ISSUE TITLE
van-field在小程序开发者工具里键盘同时敲击多个键时有bug

### ISSUE THREAD

**Issue by BigHuiWolf** [youzan/vant-weapp#1777]
![image](https://user-images.githubusercontent.com/36195100/61447381-67469680-a983-11e9-87b7-ade378ca13a0.png)
如图示。正常敲键盘，不小心按到两个键时出此bug。
手机上测试倒是没这样，但是出现了反复删除现象（一直按输入法删除键，输入框删除完会跳动出部分数据再次执行删除过程），仅我的安卓机oppor7sm（可能是性能问题）。
代码就是单纯的数据双向绑定的van-field组件而已。

**Comment by rex-zsd** [comment]
开发者工具这个情况是输入法的原因，部分中文输入法输入时输入的拼音会显示不正常。
反复删除的问题是因为小程序setData有延迟，给input事件的处理函数加个debounce处理可以解决。
后期我们考虑看看要不要内置这个优化。
