### ISSUE TITLE
[Bug Report] van-field的type=textarea时安卓手机无法点击聚焦，iOS正常

### ISSUE THREAD

**Issue by xayoung** [youzan/vant-weapp#1779]
### 设备
多台Android手机

### VantWeapp 版本
0.5.16

### 基础库版本
2.7.0

### 请提供核心代码片段链接
https://gist.github.com/xayoung/67302b0cebe32e3f687ee23b4d47356b

### 描述问题
van-field的type=textarea时安卓手机无法点击聚焦，iOS正常

**Comment by xayoung** [comment]
补充：当type不为textarea时，安卓是可以正常使用的

**Comment by 15303570216** [comment]
现在是安卓手机可以聚焦，ios不能，知道原因吗
