### ISSUE TITLE
请问有没有组件库的使用交流群，遇到问题找不到解决方案

### ISSUE THREAD

**Issue by deepthan** [youzan/vant-weapp#1780]
请问有没有组件库的使用交流群，遇到问题找不到解决方案。

比如我现在是写一个模态框，使用
```

<van-dialog
  use-slot
  show="true"
  className="register-dialog"
  showConfirmButton="false"
  bind:close="onClose"
>
  12434
</van-dialog>

```
showConfirmButton传进去不起作用

**Comment by chenjiahan** [comment]
README 的下面有群二维码
https://github.com/youzan/vant-weapp

你的用法有问题，正确写法是 showConfirmButton="{{ false }}"
