### ISSUE TITLE
关于wepy引入vant-weapp的相关问题

### ISSUE THREAD

**Issue by arlenbiao** [youzan/vant-weapp#1785]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater?repo=VantWeapp

---
目前我因公司业务需求，要求用vant-weapp作为小程序的开发UI库，但是在我几次三番并且与朋友查看后，发现采用wepy框架开发后，引入vant-weappUI库后，对于类型似乎引用不了，在原生上是可以的，还请给到回复

**Comment by rex-zsd** [comment]
类型是？

**Comment by arlenbiao** [comment]
问题描述：
wepy版本2.x最新的，然后引入vant-weapp的ui框架，结果会报一个【bem】的错，翻译后就是属性读取不了，后面问题定位到是wepy版本问题，wepy2.x版本不兼容vant-weapp


解决方案：
最后解决方案：wepy1.x(1.7)与vant-weapp结合完美解决。


建议：
还请希望可以修复避免这个问题




------------------ 原始邮件 ------------------
发件人: "rex"<notifications@github.com>; 
发送时间: 2019年7月23日(星期二) 上午10:17
收件人: "youzan/vant-weapp"<vant-weapp@noreply.github.com>; 
抄送: "づ風﹏"<80188623@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [youzan/vant-weapp] 关于wepy引入vant-weapp的相关问题 (#1785)




类型是？

**Comment by chenjiahan** [comment]
如果是 wepy 新版的问题，请到 wepy 仓库下反馈，感谢配合
