### ISSUE TITLE
[Bug Report] 在微信开发者工具中用真机调试特别卡，几乎不能用

### ISSUE THREAD

**Issue by shuiyueqingnong** [youzan/vant-weapp#1786]
### 设备
红米note7 pro

### VantWeapp 版本
0.5.16

### 基础库版本
2.7.7

### 请提供核心代码片段链接
https://gist.github.com/shuiyueqingnong/960bc5ab957647e9f55880fac41eb368

### 描述问题

无论是npm还是git安装vant-weapp在真机调试上所有组件都很卡，几乎用不了，比如：date-picker, tab等。
下面是wx.getSystemInfo得到的信息：
SDKVersion: "2.7.7"
bluetoothEnabled: false
brand: "xiaomi"
cameraAuthorized: true
deviceOrientation: "portrait"
errMsg: "getSystemInfo:ok"
fontSizeSetting: 16
language: "zh_CN"
locationAuthorized: false
locationEnabled: false
microphoneAuthorized: true
model: "Redmi Note 7 Pro"
notificationAuthorized: true
pixelRatio: 2.75
platform: "android"
safeArea:
bottom: 804
height: 774
left: 0
right: 393
top: 30
width: 393
__proto__: Object
screenHeight: 804
screenWidth: 393
statusBarHeight: 30
system: "Android 9"
version: "7.0.5"
wifiEnabled: false
windowHeight: 678
windowWidth: 393
__proto__: Object
﻿
​

**Comment by chenjiahan** [comment]
试了下还好，可能你用的手机性能比较差，后续版本里我们会持续优化性能
