### ISSUE TITLE
notice-bar动态设置值，会出现不滚动的现象

### ISSUE THREAD

**Issue by chengaobin** [youzan/vant-weapp#1788]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater?repo=VantWeapp
![image](https://user-images.githubusercontent.com/14012804/61601678-27283200-ac69-11e9-874c-b25e63623a40.png)
这是代码，一开始的逻辑值有的短，有的长，但是长的时候不会滚动，然后刷新一下页面，就会滚动了，
vant是最新的版本，用的wepy，ios跟安卓都会出现这样的问题，麻烦解决下，谢谢。
---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater?repo=VantWeapp

**Comment by chengaobin** [comment]
![1563761770(1)](https://user-images.githubusercontent.com/14012804/61601828-c1887580-ac69-11e9-8346-4042cdcdf42e.jpg)

**Comment by chenjiahan** [comment]
重复 issue https://github.com/youzan/vant-weapp/issues/1789
