### ISSUE TITLE
[Bug Report] noticebar不能滚动

### ISSUE THREAD

**Issue by chengaobin** [youzan/vant-weapp#1789]
### 设备
iphone6，realmex

### VantWeapp 版本
0.5.16

### 基础库版本
0.5.16

### 请提供核心代码片段链接
https://gist.github.com/chengaobin/38d9cec39a27290d7d3ea8ade345acef

### 描述问题
一开始的值有的短，有的长，但是长的时候不会滚动，然后刷新一下页面，或者改动一下值就会滚动了，
vant是最新的版本，用的wepy，ios跟安卓都会出现这样的问题，麻烦解决下，谢谢

**Comment by chengaobin** [comment]
测试了之后发现，是在组件里面写话会出现这样的问题，在页面写就不会出现这样的问题。wepy中

**Comment by rex-zsd** [comment]
测试 wepy + vant-weapp@0.5.16 没问题了，可能是wepy做了调整
