### ISSUE TITLE
小程序中 引入两个 van-area 初始化 市区显示会错误

### ISSUE THREAD

**Issue by Lojze** [youzan/vant-weapp#1791]
小程序页面中使用两个van-area，初始化value位置的时候，
第一的van-area显示是正确的，第二个van-area显示就是错误的。
![image](https://user-images.githubusercontent.com/11644830/61623039-8c4f4800-aca8-11e9-865b-e471ef63b876.png)

**Comment by rex-zsd** [comment]
demo里也是同时使用了多个area组件，可以正常运行。
贴下代码吧，看下是不是使用姿势的问题。
