### ISSUE TITLE
建议增加一些icon图标

### ISSUE THREAD

**Issue by yinshaoqian** [youzan/vant-weapp#1793]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater?repo=VantWeapp

---
建议增加一些icon图标
比如password的小锁子或者是
![image](https://user-images.githubusercontent.com/43122779/61689808-7ef29600-ad5a-11e9-8101-4ec5105b008e.png)

![image](https://user-images.githubusercontent.com/43122779/61689757-5ff40400-ad5a-11e9-815f-79731eb3e553.png)
图标右下角添加一个➕

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater?repo=VantWeapp

**Comment by chenjiahan** [comment]
暂无计划添加喔
