### ISSUE TITLE
[Bug Report] [van-picker]组件选项值为0时错误显示

### ISSUE THREAD

**Issue by wsi18n** [youzan/vant-weapp#1796]
### 设备
all

### VantWeapp 版本
0.5.16

### 基础库版本
all

### 请提供核心代码片段链接
https://github.com/youzan/vant-weapp/blob/dev/dist/picker-column/index.wxml

### 描述问题
[van-picker]组件选项值为0时错误显示为[Object object]

https://github.com/youzan/vant-weapp/blob/dev/dist/picker-column/index.wxml
第29行
应改为:
  return isObj(option) && (option[valueKey] !== undefined) ? option[valueKey] : option;

**Comment by rex-zsd** [comment]
感谢反馈 👍
