### ISSUE TITLE
[Feature Request] Dialog定位的设置

### ISSUE THREAD

**Issue by hahadaba** [youzan/vant-weapp#1798]
### 这个功能解决了什么问题
目前dialog是在屏幕居中，如果嵌套了field，那么在输入的时候，弹出的输入法软键盘就会挡住输入框，所以我想能不能设置顶部20%或者100px？我测试了，任何用custom-class='my-dialog-class', 类似.my-dialog-class{top:20%!important;}，这样的设置，dialog就会跳到最顶端。

### 建议的API是什么样的
top=string（如20%，或者100px）

**Comment by rex-zsd** [comment]
原因是上面还设置了`transform: translate3d(-50%,-50%,0);`，导致实际位置偏上。
可以把`top`的值调大一点，
或者再同时设置上`transform: translate3d(-50%,0,0); !important`，就可以保证`top`值与实际相符。
