### ISSUE TITLE
[Feature Request] 官方文档中badge下面的demo中包含了很多控件都找不到文档，请问哪里可以查到那些示例代码，例如swipe轮播，九宫格

### ISSUE THREAD

**Issue by mblackcat** [youzan/vant-weapp#1799]
### 这个功能解决了什么问题
官方文档中badge下面的demo中包含了很多控件都找不到文档，请问哪里可以查到那些示例代码，例如swipe轮播，九宫格

### 建议的API是什么样的
求解

**Comment by chenjiahan** [comment]
你好，Vant 文档有 Vue 版本和小程序版本，两个版本的组件是不同的，请找准对应文档

https://youzan.github.io/vant - Vue 版本
https://youzan.github.io/vant-weapp - 小程序版本
