### ISSUE TITLE
MPVue做微信小程序开发，popup这个组件在IOS无法正常显示，只显示遮罩层

### ISSUE THREAD

**Issue by ha1ger** [youzan/vant-weapp#1800]
如题

**Comment by zaxlct** [comment]
@chenjiahan 
经测试，未在 iOS 上发现这个问题，但是有另外一个 BUG：
popop 遮罩层在 mpvue 里点击无法关闭 popup，也无法触发 click-overlay 事件

**Comment by Taoqun** [comment]
问题：同上，mpvue显示遮罩层；但无法触发关闭事件。
解决：自己写了个遮罩层，触发后，关闭show。

**Comment by chenjiahan** [comment]
如果是 mpvue 下的问题，建议到 mpvue 仓库下反馈。这几个事件在原生框架下是正常的
