### ISSUE TITLE
[Bug Report] 使用组件tabs不能修改边框颜色

### ISSUE THREAD

**Issue by Arthurcherryli** [youzan/vant-weapp#1802]
### 设备
微信模拟器

### VantWeapp 版本
0.5.16

### 基础库版本
2.7.7

### 如果是 UI 问题，截图链接（多图回车分隔）

![截图](https://i.loli.net/2019/07/26/5d3ace477c88c87395.png)

### 请提供核心代码片段链接
https://gist.github.com/Arthurcherryli/14b4b33804241465ef31f6990ccd5874

### 描述问题
使用组件tabs不能修改边框颜色

**Comment by chenjiahan** [comment]
不需要外边框的话，设置 border={{ false }} 即可
