### ISSUE TITLE
[Bug Report] notify的逻辑里set前只删除了selector留下了context可能产生问题

### ISSUE THREAD

**Issue by sky-admin** [youzan/vant-weapp#1803]
### 设备
任意

### VantWeapp 版本
0.5.16

### 基础库版本
任意

### 请提供核心代码片段链接
https://github.com/youzan/vant-weapp/blob/dev/packages/notify/notify.ts#L33

### 描述问题
按文档，context属性用于自定义组件中使用时传this，一旦this上存在自引用的东西，就会栈溢出的。或者就算不溢出，也存在把不用的数据setData的浪费。

**Comment by chenjiahan** [comment]
感谢反馈，已在代码里处理，会在下个版本发布
