### ISSUE TITLE
picker,部分安卓机型滑动卡顿解决方法

### ISSUE THREAD

**Issue by zgeaw** [youzan/vant-weapp#1804]
picker-column/index.js
45行，修改wrapperStyle

wrapperStyle() {
            const { data } = this;
            let height = data.offset + data.baseOffset//修改
            return [
              `transition: ${data.duration}ms`,
               `transform: translate3d(0, ${height}px, 0)`,//修改
               `line-height: ${data.itemHeight}px`
            ].join('; ');
        }

**Comment by JakeLaoyu** [comment]
可以提PR

**Comment by kyle127** [comment]
****
