### ISSUE TITLE
[Bug Report] van-action-sheet/van-popup的蒙层在wepy中无效

### ISSUE THREAD

**Issue by xiandanin** [youzan/vant-weapp#1807]
### 设备
Android 8.0

### VantWeapp 版本
0.5.16

### 基础库版本
2.7.7

### 描述问题
overlay和close-on-click-overlay都无效
默认的、overlay=true、:overlay=page.overlay怎么写都没有蒙层
```
<van-action-sheet
      @tap="page.statusActionSheet=false"
      show="{{ page.statusActionSheet }}"
      actions="{{ page.actions }}"
      @select="onSelectStatusAction"
    />
```

**Comment by dengyuhan** [comment]
试过手动设背景，但也只有模拟器有效，Android真机还是无效
```
  .overlay-index--van-overlay {
    background-color: #000000B2
  }
```

<img src="https://user-images.githubusercontent.com/17588779/62096607-c3c88080-b2b6-11e9-9666-24c0ff94a759.png" height=500/><img src="https://user-images.githubusercontent.com/17588779/62096627-d642ba00-b2b6-11e9-9e98-32575b14f301.png" height=500/>

**Comment by bundlejs** [comment]
vant-weapp@0.5.19
基础库2.8.0
也是同样的问题

**Comment by WebChenSir** [comment]
在wepy2中通过npm模块方式引入的组件不仅蒙层没样式，蒙层默认点击的关闭事件也无效的。还有希望能给vant-weapp@x.0的van-dialog组件也增加个overlay-style属性。  @rex-zsd
