### ISSUE TITLE
关于步进器的小建议

### ISSUE THREAD

**Issue by EpicWang** [youzan/vant-weapp#1812]
1. 值为0时，默认不显示减号和数字view，类似于饿了么
2. 可以自定义加减号图标

**Comment by chenjiahan** [comment]
第一个需求，下个版本会新增 show-plus 和 show-minus 属性，用来手动控制是否展示按钮
第二个需求暂时不会支持

**Comment by chenjiahan** [comment]
已在 0.5.18 版本支持 show-plus 和 show-minus 属性
