### ISSUE TITLE
van-input中的focus聚焦异常

### ISSUE THREAD

**Issue by MyZhouGit** [youzan/vant-weapp#1813]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater?repo=VantWeapp

---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater?repo=VantWeapp

复现过程：
我有一个页面，页面中有一个输入框，聚焦事件为跳转页面，当我点击聚焦后成功跳转页面，但是当我返回页面时输入框并没有自动失焦，导致我点击页面中其他位置时又发生一次页面跳转。

代码示例（wxml）：
![image](https://user-images.githubusercontent.com/32385383/62270659-1ba6e900-b469-11e9-8466-404538cfbb88.png)

代码示例（js）
![image](https://user-images.githubusercontent.com/32385383/62270753-57da4980-b469-11e9-9131-6f6bd4f4e22d.png)

动图展现
![bug](https://user-images.githubusercontent.com/32385383/62271073-42195400-b46a-11e9-8292-8d62d5a21027.gif)

**Comment by chenjiahan** [comment]
这是小程序本身事件触发的问题，建议改成绑定 tap 事件，可以避免这个问题
