### ISSUE TITLE
van-field中单元格样式不能自定义

### ISSUE THREAD

**Issue by MyZhouGit** [youzan/vant-weapp#1814]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater?repo=VantWeapp

---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater?repo=VantWeapp

问题描述：
在我的页面中使用了一个van-field的组件，这个组件默认是van-cell单元格中嵌套了输入框，但是单元格默认背景颜色为白色，现在我希望自定义设置van-field中van-cell的样式，请开源者提供

代码示例：
![image](https://user-images.githubusercontent.com/32385383/62271867-48103480-b46c-11e9-99c5-98bbb4683b4a.png)

界面复现
![image](https://user-images.githubusercontent.com/32385383/62271916-6a09b700-b46c-11e9-8cbb-937dee1f3bea.png)

![image](https://user-images.githubusercontent.com/32385383/62271944-7aba2d00-b46c-11e9-94a6-d3b44037d9f0.png)

**Comment by BigHuiWolf** [comment]
目前没有bug的话，建议手动修改里面的样式，因为bug他们都修改不过来。😂

**Comment by chenjiahan** [comment]
用 custom-style 属性即可，文档漏了，后续会补上
