### ISSUE TITLE
[Bug Report] Collapse 动态增加内容高度不会自动适应

### ISSUE THREAD

**Issue by Bing573** [youzan/vant-weapp#1817]
### 设备
IPhone 6s, 开发工具

### VantWeapp 版本
0.5.17

### 基础库版本
2.7.4

### 请提供核心代码片段链接
https://gist.github.com/Bing573/56d1f9f194cd2354755de8a7970008c8

### 描述问题
Collapse默认展开情况下，动态增加内容会因为高度不变导致底部内容不可见，也无滚动条。但若收拢再展开，高度可根据内容自适应

**Comment by Halokitiboy** [comment]
同楼上一样的问题

**Comment by chenjiahan** [comment]
已在 0.5.18 版本修复
