### ISSUE TITLE
[Feature Request] 增加按需编译的能力

### ISSUE THREAD

**Issue by abrahamgreyson** [youzan/vant-weapp#1820]
### 这个功能解决了什么问题
目前文档中，快速上手部分，方式一为 npm 安装，所有组件包含在内。方式二为手工复制文件，这样的缺陷是需要手工去追踪新代码的更新，如果只使用特定的一两个组件，复制所有文件显然是不划算的（空间限制），而只复制特定组件，需要去处理组件的依赖。我的需求是只引入必要的代码。

### 建议的API是什么样的
建议以配置文件的形式，提供按需编译的能力。
目前我简单的写了个 gulp 脚本去复制 dist 中的文件至开发目录。

**Comment by rex-zsd** [comment]
按照目前`/path/to/vant-weapp/dist/button/index`的引入方法，开发者工具的编译上传本就是按需的，不需要再做一遍。

**Comment by abrahamgreyson** [comment]
@rex-zsd 感谢回复

**Comment by nikolausliu** [comment]
@rex-zsd 我试了官网的引入方式，只引入了这一个image组件，然而上传代码后还是被全量上传了，因为上传后的代码包大小多了300kb左右，忽略上传文件列表也没显示miniprogram_npm中的其它组件。
所以，我想说，你确定开发者工具编译上传是按需的吗？
```
"usingComponents": {
    "van-image": "@vant/weapp/image/index"
  }
```

**Comment by rex-zsd** [comment]
> @rex-zsd 我试了官网的引入方式，只引入了这一个image组件，然而上传代码后还是被全量上传了，因为上传后的代码包大小多了300kb左右，忽略上传文件列表也没显示miniprogram_npm中的其它组件。
> 所以，我想说，你确定开发者工具编译上传是按需的吗？
> 
> ```
> "usingComponents": {
>     "van-image": "@vant/weapp/image/index"
>   }
> ```

看了一遍[文档](https://developers.weixin.qq.com/miniprogram/dev/devtools/npm.html#%E5%8E%9F%E7%90%86%E4%BB%8B%E7%BB%8D)，确实是这样，微信会把所有的 miniprogram_npm 都上传上去。
按照这个原理，vant weapp 这边没办法做到按需引用，因为只有纯 js 包才能走依赖分析。vant weapp 作为UI组件库，需要在 json 中配置，是没办法走 js 入口分析依赖的路径的。

**Comment by rex-zsd** [comment]
这样看来只能是 npm 构建之后在 miniprogram_npm 内手动删除不需要的组件了。

**Comment by nikolausliu** [comment]
@rex-zsd 不知道微信的npm构建能否不通过开发者工具，而是开发者自己写个工具动态的解析依赖了哪些组件来完成构建。不过我不懂编译，不知道有没有人做过类似这样的尝试

**Comment by nikolausliu** [comment]
@rex-zsd 不知道微信的npm构建能否不通过开发者工具，而是开发者自己写个工具动态的解析依赖了哪些组件来完成构建。不过我不懂编译，不知道有没有人做过类似这样的尝试

**Comment by nikolausliu** [comment]
@rex-zsd 不知道微信的npm构建能否不通过开发者工具，而是开发者自己写个工具动态的解析依赖了哪些组件来完成构建。不过我不懂编译，不知道有没有人做过类似这样的尝试

**Comment by rex-zsd** [comment]
有赞内部是自己实现 npm 依赖的，所以之前确实对微信npm构建这部分疏于了解了。

**Comment by rex-zsd** [comment]
这个 [plugin](https://github.com/realywithoutname/mini-program-webpack-loader) 也是开源了的，不过没挂在 youzan group 下面。
能折腾的话可以试试。

**Comment by nikolausliu** [comment]
@rex-zsd 好的谢谢，我看一下

**Comment by Leafyyuki** [comment]
请问有人折腾出好的解决方案吗

**Comment by cafehaus** [comment]
使用 vant-tree-shaking 包，使用说明：https://www.npmjs.com/package/vant-tree-shaking
