### ISSUE TITLE
[Bug Report] 关于wepy2.X 最新版本中vant-weapp不兼容问题

### ISSUE THREAD

**Issue by xmt2018** [youzan/vant-weapp#1823]
### 设备
荣耀9

### VantWeapp 版本
0.5.17

### 基础库版本
v0.5.17

### 请提供核心代码片段链接
https://github.com/xmt2018/ybuxi.git

### 描述问题
wepy版本2.x最新的，然后引入vant-weapp的ui框架，结果会报一个【bem】的错，翻译后就是属性读取不了，后面问题定位到是wepy版本问题，wepy2.x版本不兼容vant-weapp

**Comment by chenjiahan** [comment]
如果是 wepy 新版的问题，请到 wepy 仓库下反馈，感谢配合
