### ISSUE TITLE
按钮里怎么显示图标

### ISSUE THREAD

**Issue by yaoshanliang** [youzan/vant-weapp#1824]
![image](https://user-images.githubusercontent.com/5028569/62450743-79a43b00-b79f-11e9-8d3f-e376c189e728.png)

如题，这个在示例里有，文档里好像没说怎么写。

另外怎么自定义按钮的颜色?

**Comment by dengyuhan** [comment]
同问，试过设置`icon`但是无效

**Comment by chenjiahan** [comment]
参见 https://github.com/youzan/vant-weapp/issues/1672
