### ISSUE TITLE
何时能加上商品规格这个组件呢？

### ISSUE THREAD

**Issue by xni220** [youzan/vant-weapp#1831]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater?repo=VantWeapp

---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater?repo=VantWeapp
何时能加上商品规格这个组件呢？

**Comment by chenjiahan** [comment]
暂时没计划支持
