### ISSUE TITLE
[Bug Report] <van-badge>数据从新渲染 顺序发送改变，active的index没有从新生成

### ISSUE THREAD

**Issue by Creamweiwei** [youzan/vant-weapp#1832]
### 设备
微信小程序

### VantWeapp 版本
0.5.16

### 基础库版本
2.7.7

### 请提供核心代码片段链接
` <van-badge-group active="{{ badgeIndex }}" bind:change="onChangeSupplie">
    <bloclk wx:for="{supplies}}" wx:key="supplyId" >
      <van-badge info="{{item.publishCargos.length}}" title="{{item.name}}" ></van-badge>
    </bloclk>
    </van-badge-group>`

### 描述问题

supplies数据从新生成顺序发送改变，active中索引出现混乱

**Comment by anythink-wx** [comment]
van-sidebar 也是，比如有10个项目，重新渲染索引会 从11开始。

**Comment by rex-zsd** [comment]
@anythink-wx 索引指的是什么？

**Comment by anythink-wx** [comment]
@rex-zsd  active选项的index，我在 issus [2369](https://github.com/youzan/vant-weapp/issues/2369) 上贴了详细的说明

**Comment by rex-zsd** [comment]
同 #2444  将在beta.6版本修复哈

**Comment by rex-zsd** [comment]
ok的 #2369 比较详细，可以关注那个issue
