### ISSUE TITLE
希望尽快更新indexBar索引栏等等，vant-vue组件库早就有了的东西

### ISSUE THREAD

**Issue by a294974783** [youzan/vant-weapp#1833]
如题，vant-vue很多用户体验很好的组件，比如indexbar，现在我要另外引入一个组件库去做这个交互，如果vant-weapp也有我就不用引入多个UI了，希望尽快跟进！

**Comment by chenjiahan** [comment]
目前开发资源有限，这个组件近期不会支持，抱歉喔
