### ISSUE TITLE
stepper 增加问题

### ISSUE THREAD

**Issue by Gokeyoung** [youzan/vant-weapp#1835]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater?repo=VantWeapp

---
stepper -- index.js
const value = Math.round((this.data.value + diff) * 100) / 100;
会因 **this.data.value** string类型而直接连接，不是相加
```
onChange(type) {
        if (this.data[`${type}Disabled`]) {
            this.$emit('overlimit', type);
            return;
        }
        const diff = type === 'minus' ? -this.data.step : +this.data.step;
        const value = Math.round((Number(this.data.value) + diff) * 100) / 100;
        this.triggerInput(this.range(value));
        this.$emit(type);
 }
```

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater?repo=VantWeapp

**Comment by chenjiahan** [comment]
下个版本会修复

**Comment by chenjiahan** [comment]
已在 0.5.18 版本修复
