### ISSUE TITLE
按钮禁用了为什么还是会触发绑定的事件函数

### ISSUE THREAD

**Issue by bks233** [youzan/vant-weapp#1837]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater?repo=VantWeapp

---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater?repo=VantWeapp

**Comment by chenjiahan** [comment]
参见 https://github.com/youzan/vant-weapp/issues/1725
