### ISSUE TITLE
wepy2可以使用这个吗 我尝试了一下不行 是啥问题（我看到的是wxs没有正确编译）

### ISSUE THREAD

**Issue by y-e-y-u** [youzan/vant-weapp#1845]
![image](https://user-images.githubusercontent.com/26995987/62669670-0549e180-b9c3-11e9-8760-b42549fa6de0.png)

**Comment by y-e-y-u** [comment]
fix

**Comment by chenjiahan** [comment]
这个是 wepy 2 的问题，请到对应仓库下反馈，感谢配合
