### ISSUE TITLE
[Bug Report] 使用van-picker进行多列分类选择，确定选择后重新点击选择，第二列将无法自动刷新

### ISSUE THREAD

**Issue by SeLiNnnn** [youzan/vant-weapp#1848]
### 设备
ios

### VantWeapp 版本
0.5.18

### 基础库版本
2.7.2

### 如果是 UI 问题，截图链接（多图回车分隔）

![截图](https://i.loli.net/2019/08/08/qfHr6lRnSjTkib8.png)

![截图](https://i.loli.net/2019/08/08/mj3wVDrycnPlTs8.png)

![截图](https://i.loli.net/2019/08/08/shjmpbSloiV4ytN.png)

### 请提供核心代码片段链接
https://gist.github.com/SeLiNnnn/e16b339e8fcfb367fa8f770abe547a8d

### 描述问题
如图所示，弹出的选择框分为1，2列，1列有A,B选项，2列对应A-A1，A-A2，B-B1，B-B2等具体内容。问题在于，如果第一次选择了1列B项点击确定后，再次点开该选择框，1列停留在B项，而2列却显示A的内容。如果这时滑动2列具体内容，会更新变成B项内容，如果不滑动2列，直接点确定，最终选择结果会变成B-A1。

**Comment by Eamonnzhang** [comment]
在原生小程序中按照你的例子写，无法复现你的问题

**Comment by KePingHub** [comment]
mpvue ^2.0.0 微信小程序 使用van-popup + van-picker 多列 碰到同样的问题

**Comment by SeLiNnnn** [comment]
是的...不好意思 忘了说明 我也是用的mpvue

**Comment by KePingHub** [comment]
我这边已经解决了，
defaultIndexArr: [0, 0]  // 存储van-picker每项的默认选中的索引
columns: [
  { values: ['column1', 'column2'], defaultIndex: this.defaultIndex[0] },
 { values: ['column2-child1', 'column2-child2'], defaultIndex: this.defaultIndex[1]}
]
v-if="isPopupShow" 控制van-picker 在van-popup显示时重新渲染 

在confirm事件回调中获取最新索引
const { value, index } = e.mp.detail
this.defaultIndexArr = index

**Comment by KePingHub** [comment]
我这边已经解决了，
defaultIndexArr: [0, 0] // 存储van-picker每项的默认选中的索引
columns: [
{ values: ['column1', 'column2'], defaultIndex: this.defaultIndexArr[0] },
{ values: ['column2-child1', 'column2-child2'], defaultIndex: this.defaultIndexArr[1]}
]
v-if="isPopupShow" 控制van-picker 在van-popup显示时重新渲染

在confirm事件回调中获取最新索引
const { value, index } = e.mp.detail
this.defaultIndexArr = index

**Comment by KePingHub** [comment]
我这边已经解决了，
defaultIndexArr: [1, 1] // 存储van-picker每项的默认选中的索引
columns: [
{ values: ['column1', 'column2'], defaultIndex: this.defaultIndexArr[0] },
{ values: ['column2-child1', 'column2-child2'], defaultIndex: this.defaultIndexArr[1]}
]
v-if="isPopupShow" 控制van-picker 在van-popup显示时重新渲染

在confirm事件回调中获取最新索引
const { value, index } = e.mp.detail
this.defaultIndexArr = index

**Comment by zaxlct** [comment]
同样踩到这个坑

**Comment by youngbo-china** [comment]
好深的坑，同样

**Comment by rex-zsd** [comment]
原生小程序没有问题，看来是mpvue环境下特有的问题，我尝试复现看看。

**Comment by rex-zsd** [comment]
确认是 mpvue 的问题了，mpvue 在每次唤起组件的时候，会把`columns`再重新传入一遍，导致 van-picker 内部保存的选中项是正确的，但是`columns`被重置回了初始值。
绕过方法有2种
在 van-picker 上用`v-if`手动控制，以在 van-popup 唤起时重新渲染 van-picker，此时选中状态也会被初始化。
```html
<van-popup :show="show" position="bottom">
    <van-picker
        v-if="show"
        ...
    />
</van-popup>
```

或者在`onChange`事件中手动修改传入的`columns`值
```js
export default {
  data () {
    return {
      show: false,
      column3: {
        浙江: ['杭州', '宁波', '温州', '嘉兴', '湖州'],
        福建: ['福州', '厦门', '莆田', '三明', '泉州']
      },
      column4: [
        {
          values: ['浙江', '福建'],
          className: 'column1'
        },
        {
          values: ['杭州', '宁波', '温州', '嘉兴', '湖州'],
          className: 'column2',
          defaultIndex: 2
        }
      ]
    }
  },
  methods: {
    onChange (event) {
      const { picker, value } = event.mp.detail
      const newOptions = this.column3[value[0]];
      picker.setColumnValues(1, newOptions)
      this.column4[1].values = newOptions
    }
  }
}
```
