### ISSUE TITLE
[Bug Report] field组件blur事件中修改data.value后，立马被change事件给修改回去了，导致修改失败

### ISSUE THREAD

**Issue by wubinsheng2017** [youzan/vant-weapp#1849]
### 设备
wxApp

### VantWeapp 版本
0.5.18

### 基础库版本
2.8.0

### 请提供核心代码片段链接
https://github.com/youzan/vant-weapp/blob/dev/dist/field/index.js

### 描述问题
【业务场景】
field失去焦点后，需要强制恢复成默认值

【问题描述】
在blur事件中，通过 [this.data.fieldValue = '0']来手动修改field的值，
→ 修改结果没有生效，field内容依然是空

翻看vant-field的源码后发现，blur事件的处理有点问题，
        onBlur: function (event) {
            var _this = this;
            var _a = event.detail || {}, _b = _a.value, value = _b === void 0 ? '' : _b, _c = _a.cursor, cursor = _c === void 0 ? 0 : _c;
            this.$emit('blur', { value: value, cursor: cursor });
            this.focused = false;
            var showClear = this.getShowClear();

>>>>>>>this.data.value已经被修改成了0，但value依然是空
            if (this.data.value === value) {
                this.set({
                    showClear: showClear
                });
            }
            else if (!this.blurFromClear) {
                // fix: the handwritten keyboard does not trigger input change
                this.set({
                    value: value,

>>>>>>在这里又把空给扔回去了，导致0被赋值失败
>>>>>>建议修改逻辑：
1、this.data.value === value 时 → 现有逻辑没问题
2、this.data.value != value && this.blurFromClear → 直接赋值空
3、this.data.value != value && ! this.blurFromClear → 赋值this.data.value

                    showClear: showClear
                }, function () {
                    _this.emitChange(value);
                });
            }
        },

**Comment by rex-zsd** [comment]
原本blur的处理是为了兼容手写输入法，确实不太合理。

**Comment by wubinsheng2017** [comment]
> 原本blur的处理是为了兼容手写输入法，确实不太合理。

那请问有修复计划吗？

**Comment by rex-zsd** [comment]
下个版本会修复
