### ISSUE TITLE
[Bug Report]图标service-o显示不全

### ISSUE THREAD

**Issue by Exrick** [youzan/vant-weapp#1851]
### 设备
IPhone X  + 安卓机

### VantWeapp 版本
0.5.18

### 基础库版本
2.8.0

### 截图
- IOS
![0FFB373EC6C83E771447B69E32B4AF0E.png](https://i.loli.net/2019/08/10/5LwMnP4EZi1KosT.jpg)

![IMG_3986_20190810-145108_.jpg](https://i.loli.net/2019/08/10/aZ8OpournEDxyJt.jpg)

- 安卓机

![IMG_3987_20190810-171519_.jpg](https://i.loli.net/2019/08/10/xvTzGInk1FBmAeD.jpg)

### 请提供核心代码片段链接
``` javascript
<van-icon name="service-o" />
```

### 描述问题
线框风格图标service-o在IOS设备上左下角显示不全，详见官方预览demo同样问题

**Comment by chenjiahan** [comment]
下个版本会修复

**Comment by chenjiahan** [comment]
已在 0.5.19 版本修复
