### ISSUE TITLE
popup组件无法触发onclose

### ISSUE THREAD

**Issue by p1094358629** [youzan/vant-weapp#1852]
1.按照demo 引入popup
    "van-popup": "../../component/vant-weapp/dist/popup/index"
2. xhtml中写入
            <van-popup show="{{show}}" position="top"  bind:close="onClose" >内容</van-popup>
js也写好对应 data: {
            show: false,
}
但是编译项目报错
safe-area.js:36 Uncaught (in promise) TypeError: _this.set is not a function
    at safe-area.js:36

且无法触发onclose

环境:
微信开发工具,所有机型

**Comment by chenjiahan** [comment]
未复现此问题，建议检查下是否正确引入了 vant-weapp
