### ISSUE TITLE
请问一下van-button如何提交表单，例如form-type="submit" 这样无效

### ISSUE THREAD

**Issue by xiaofuliang** [youzan/vant-weapp#1855]

**Comment by rex-zsd** [comment]
https://developers.weixin.qq.com/miniprogram/dev/component/button.html#Bug-Tip
很遗憾，van-button不可能做到提交表单。
只能使用原生button实现。

**Comment by n19ht** [comment]
> https://developers.weixin.qq.com/miniprogram/dev/component/button.html#Bug-Tip 很遗憾，van-button不可能做到提交表单。 只能使用原生button实现。

网页端好像也不行呢
