### ISSUE TITLE
[Bug Report] 在 popup 中调用 dialog.close() 失效

### ISSUE THREAD

**Issue by kid1412621** [youzan/vant-weapp#1857]
### 设备
Android

### VantWeapp 版本
0.5.18

### 基础库版本
2.7.7

### 请提供核心代码片段链接
https://gist.github.com/kid1412621/3f2c0455e9365d1a97da541d7d71ac90

### 描述问题
在 popup 中调用 dialog.close() 失效.
在 popup 包含的子组件中 : https://gist.github.com/kid1412621/3f2c0455e9365d1a97da541d7d71ac90

**Comment by JakeLaoyu** [comment]
dialog 放到 popup外部

**Comment by JakeLaoyu** [comment]
```html
  <van-popup>
    <view bind:tap="showCustomDialog">
      弹框
    </view>

  </van-popup>
  <van-dialog id="van-dialog" />
```

**Comment by kid1412621** [comment]
> ```
>   <van-popup>
>     <view bind:tap="showCustomDialog">
>       弹框
>     </view>
> 
>   </van-popup>
>   <van-dialog id="van-dialog" />
> ```

谢谢解答, 我是把 dialog 封装在组件里面, 组件又放在 popup 里面的, 看来只能改写了
