### ISSUE TITLE
[Feature Request] 日期选择器是否支持选择文本

### ISSUE THREAD

**Issue by csyunyou** [youzan/vant-weapp#1858]
### 这个功能解决了什么问题
有些日期是“永久”，“长期”之类的文本日期，选择器能选择数字日期的同时，支持选择文本日期

### 建议的API是什么样的
还没想好

**Comment by rex-zsd** [comment]
应该不会支持。
”长期“这样的文案，更多的是表示时间段而不是时间点，往往意味着不需要选择时间。
建议另外用一个开关控制。
