### ISSUE TITLE
[Bug Report] datetime-picker设置formatter报错

### ISSUE THREAD

**Issue by danplin** [youzan/vant-weapp#1863]
### 设备
macbook

### VantWeapp 版本
0.5.18

### 基础库版本
开发者工具：2.7.7     wepy-cli@1.7.3

### 请提供核心代码片段链接
https://gist.github.com/danplin/91ccea633b5d2e6220fe3e2a59750004

### 描述问题
在popup在添加datetime-picker。如果不设置datetime-picker的formatter可以正常运行。按照文档https://youzan.github.io/vant-weapp/#/datetime-picker 设置formatter之后报错。

<a href="https://sm.ms/image/NliLQCtu2hZAFq8" target="_blank"><img src="https://i.loli.net/2019/08/13/NliLQCtu2hZAFq8.png" ></a>

**Comment by WebChenSir** [comment]
你可以试下写成键值对的形式formatter:()=>{}，我在wepy2用过是可以的。

**Comment by rex-zsd** [comment]
原生小程序并没有这个问题，只能等wepy修复了。

**Comment by Teemwu** [comment]
维护旧版本 wepy 项目时也遇到这个问题，由于 wepy2.x 变化较大，不打算花时间升级，在不升级 wepy 版本的基础上，可以封装一个原生小程序组件，引用  vant 的 datetime-picker 组件，此时在原生小程序组件内设置 formatter 是可以正常使用的，在 wepy 文件中调用自己封装的原生小程序组件即可。
