### ISSUE TITLE
[Bug Report] Cell的clickable属性不起作用

### ISSUE THREAD

**Issue by I322871** [youzan/vant-weapp#1865]
### 设备
Meizu 16th

### VantWeapp 版本
0.5.18

### 基础库版本
2.7.0

### 请提供核心代码片段链接
https://youzan.github.io/vant-weapp/#/cell

### 描述问题
Cell有一个属性是clickable，用来控制cell是否可以点击。但是看起来这个属性并不会产生作用，一个cell能否点击只受控于它是否绑定了click事件。看了下cell的源码，貌似是这样的。。。。

建议参考button的disabled属性的实现方式，如果cell的clickable设为false，无论是否绑定了click事件，都无法触发。

**Comment by rex-zsd** [comment]
文档中`clickable`的作用是点击反馈(点击态样式变化)，而不是是否可以点击。
