### ISSUE TITLE
[Feature Request] filed组件能否提供focus后自动全选的功能

### ISSUE THREAD

**Issue by wubinsheng2017** [youzan/vant-weapp#1866]
### 设备
wxApp

### VantWeapp 版本
0.5.18

### 基础库版本
2.8.0

### 请提供核心代码片段链接
https://github.com/youzan/vant-weapp/blob/dev/dist/field/index.js

### 描述问题
如题，期望提供类似js中dom.select()方法的功能。
field组件获得焦点后，自动全选中原先的内容，
方便继续输入新内容后，可以直接覆盖老的内容

**Comment by chenjiahan** [comment]
下个版本会把 selection-start、selection-end 这两个原生属性加上，可以用于实现这个需求

**Comment by chenjiahan** [comment]
已在 0.5.20 版本支持
