### ISSUE TITLE
 tabs的sticky属性 滑动到顶部后切换tab 会回滚到原来位置

### ISSUE THREAD

**Issue by heda20** [youzan/vant-weapp#1867]
描述一下问题
 tabs的sticky属性 滑动到顶部后切换tab 会回滚到原来位置，而不是继续固定在顶部

截图(不能放gif 图只能放链接)
[https://wx3.sinaimg.cn/mw690/006T30vygy1g60drlxl13g30au0iiu0z.gif](url)
[环境]

设备: 小米8SE
基础库版本: 2.8.0
Vant Weapp 版本: 0.5.7

**Comment by heda20** [comment]
![gif](https://user-images.githubusercontent.com/30659608/63078854-7105ee80-bf6f-11e9-87e6-f513efeeb1a0.gif)
vant Weapp版本：0.5.17

**Comment by MagicHacker** [comment]
请问这个问题已经解决了吗？

**Comment by badjone** [comment]
我这里是切换tab，到了底部
![image](https://user-images.githubusercontent.com/8895430/64581914-76aff200-d3be-11e9-8e58-5713c2be6440.png)

**Comment by badjone** [comment]
是不是这里的关系

**Comment by MagicHacker** [comment]
当从长列表切换到短的列表时就会切换到底部，而且每次都是到了底部的同一个位置

**Comment by xiaodongning** [comment]
> 当从长列表切换到短的列表时就会切换到底部，而且每次都是到了底部的同一个位置
我也遇到这个问题

**Comment by lovefeng0709** [comment]
这个bug很难受，利用sticky吸顶后，切换tab会回滚到原来位置，而不是继续固定在顶部，而且还有页面其他元素的闪动。难受！

**Comment by lovefeng0709** [comment]
我发现 吸顶后  我从右边往左边点不会出BUG，但是只要你从左往右点就会出BUG，开始默认展示都是索引为0的数据，我把它点到最后一个索引号，这次他会出bug回到原来位置(因为是从左往右的)。当我从最后一个往左点时就不会出bug。难道是组件在做逻辑时没写好吗？

**Comment by Danfengzhou** [comment]
> ![gif](https://user-images.githubusercontent.com/30659608/63078854-7105ee80-bf6f-11e9-87e6-f513efeeb1a0.gif)
> vant Weapp版本：0.5.17

这个bug解决了嘛?

**Comment by Danfengzhou** [comment]
> 我发现 吸顶后 我从右边往左边点不会出BUG，但是只要你从左往右点就会出BUG，开始默认展示都是索引为0的数据，我把它点到最后一个索引号，这次他会出bug回到原来位置(因为是从左往右的)。当我从最后一个往左点时就不会出bug。难道是组件在做逻辑时没写好吗？

解决没有?这个问题

**Comment by rex-zsd** [comment]
暂时无解，因为切换的时候目标tab的content还未渲染，高度为0，导致页面自动上滑。

**Comment by homeabc** [comment]
> 描述一下问题
> tabs的sticky属性 滑动到顶部后切换tab 会回滚到原来位置，而不是继续固定在顶部
> 
> 截图(不能放gif 图只能放链接)
> [https://wx3.sinaimg.cn/mw690/006T30vygy1g60drlxl13g30au0iiu0z.gif](url)
> [环境]
> 
> 设备: 小米8SE
> 基础库版本: 2.8.0
> Vant Weapp 版本: 0.5.7

不知道你可解决了。我现在也是这种问题。很难受

**Comment by heda20** [comment]
没有解决，小程序没有上线就没有处理了
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"notifications"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月6日(星期五) 下午4:37
收件人:&nbsp;"youzan/vant-weapp"<vant-weapp@noreply.github.com&gt;;
抄送:&nbsp;"贺达"<314474899@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [youzan/vant-weapp]  tabs的sticky属性 滑动到顶部后切换tab 会回滚到原来位置 (#1867)



 
描述一下问题
 tabs的sticky属性 滑动到顶部后切换tab 会回滚到原来位置，而不是继续固定在顶部
 
截图(不能放gif 图只能放链接)
 https://wx3.sinaimg.cn/mw690/006T30vygy1g60drlxl13g30au0iiu0z.gif
 [环境]
 
设备: 小米8SE
 基础库版本: 2.8.0
 Vant Weapp 版本: 0.5.7
  
不知道你可解决了。我现在也是这种问题。很难受

**Comment by ling317** [comment]
### 关于各位在微信小程序中长短列表切换时滚动到底部的问题，解决思路如下：
### 1.wxml
`<van-tabs  sticky animated bindchange="bindChange">
  <block wx:for="{{list}}" wx:key="index">
    <van-tab title="{{item.title}}" class="{{tabActiveIndex==index?'tab-active':'tab-inactive'}}" >{{item.text}}</van-tab>
  </block>
</van-tabs>
`
### 2.js
`data: {
  tabActiveIndex: 0,	
},
bindChange: function(e) {
  const index = e.detail.index;
  let that = this;
  wx.nextTick(function () {
    that.setData({
      tabActiveIndex: index,
    })
  })
},`
### 3.wxss
`
.tab-active .van-tab__pane--inactive {
	height: auto;
}
.tab-inactive .van-tab__pane--inactive {
	height: 0;
}`
按以上步骤就可以解决。
对于各个tab滚动相对独立的情况，需要去判断sticky模式中是否置顶isFixed,在对容器高度修改为固定高度，只提供思路。

**Comment by rex-zsd** [comment]
后续开启sticky时，点击切换tab，会自动滚动到tabs顶部，跟 vant 保持一致。

**Comment by afishhhhh** [comment]
这个问题还在诶，长列表换到短列表，就到底部去了，然后就跟着页面一起滚动了。。。

**Comment by Galileo01** [comment]
在遇到上诉bug之后，尝试自己实现一个tabs 之后，发现自己实现的tabs也存在这个bug，所以个人认为有一份小程序本身的问题，一部分原因是：当切换tab之后，tab的内容不足以撑开页面达到滚动，那么页面就会自动滚到最顶端，我的解决方法是让tab的内容加上页面其他内容的内容始终大于页面高度，就会始终可以滚动，比如 设置height:100vh这样内容区域就始终可以滚动了

**Comment by Galileo01** [comment]
> 暂时无解，因为切换的时候目标tab的content还未渲染，高度为0，导致页面自动上滑。

我的想法是保证页面可以滚动，至少在吸顶的时候，方法就是在设置tab区域高度为100vh

**Comment by gzggithub** [comment]
<van-tabs v-model="active" :ellipsis="false" color="#3D91FF" title-active-color="#3D91FF" sticky offset-top="46" swipe-threshold="2" ></van-tabs >
刷新页面 会出现吸顶？？？？？
![image](https://user-images.githubusercontent.com/31639033/91127433-d50dd780-e6d8-11ea-8ef1-ce759a39be96.png)


![image](https://user-images.githubusercontent.com/31639033/91127345-a132b200-e6d8-11ea-9388-57cee67cdec3.png)

**Comment by liguoliangiOS** [comment]
van-tabs在sticky状态下 滚动到导航栏下悬停后，在部分华为和小米机型上，下拉页面标题栏不会下来。
<img width="686" alt="WeChat99cf7b9fcc841992537e6b99257d4043" src="https://user-images.githubusercontent.com/14325806/93547033-b4af0100-f996-11ea-916f-7e23170e58d6.png">

**Comment by zuonidelaowang** [comment]
> > 我发现 吸顶后 我从右边往左边点不会出BUG，但是只要你从左往右点就会出BUG，开始默认展示都是索引为0的数据，我把它点到最后一个索引号，这次他会出bug回到原来位置(因为是从左往右的)。当我从最后一个往左点时就不会出bug。难道是组件在做逻辑时没写好吗？
> 
> 解决没有?这个问题
解决了吗？

**Comment by ChinaGc** [comment]
我其实有个思路 就是给滚动内容一个min-height，这里的min-height就是让sticky吸顶的最小高度，就可以完美实现

**Comment by liguoliangiOS** [comment]
你好！您的邮件我也经收到。
祝你生活愉快！

**Comment by callmesoul** [comment]
需要自己去记录滚动高度，然后切换的时候用wx.pageScrollTo去返回高度

**Comment by liguoliangiOS** [comment]
你好！您的邮件我也经收到。
祝你生活愉快！
