### ISSUE TITLE
为什么radio disabled了还可以点击并切换？

### ISSUE THREAD

**Issue by gotounix** [youzan/vant-weapp#1873]
虽然获取不到真实的值，但是在显示上还是操作成功了，只不过是灰色显示而已？
如果对disabled的radio禁用click？

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合

**Comment by gotounix** [comment]
@chenjiahan 表述这么清晰，没有模板就看不懂了吗？

**Comment by chenjiahan** [comment]
1. 这是规范，写的很清楚
2. 连字都打错了，谈何清晰

**Comment by zhoufanglu** [comment]
题主最后解决了吗，我也遇到这个问题了。

**Comment by gotounix** [comment]
@zhoufanglu 没有解决，我后面用iview去了。
