### ISSUE TITLE
[Bug Report] tag组件在flex布局下不垂直居中

### ISSUE THREAD

**Issue by aQingYun** [youzan/vant-weapp#1875]
### 设备
微信开发者工具

### VantWeapp 版本
0.5.19

### 基础库版本
2.8.0

### 如果是 UI 问题，截图链接（多图回车分隔）

![截图](https://sm.ms/image/K5qCIRi3NHdDFZn)

### 请提供核心代码片段链接
https://developers.weixin.qq.com/s/6IWILGmD7kaA

### 描述问题
tag组件在flex布局下垂直不是居中的 测试了正常情况下的view保持和tag同样的样式无上述问题

**Comment by aQingYun** [comment]
![1DD38576-0050-40A2-A588-C195BF553070](https://user-images.githubusercontent.com/37834281/63209908-84ed5400-c119-11e9-906d-f7a17c61757a.png)

**Comment by rex-zsd** [comment]
小程序的自定义组件是通过shadowDOM来实现的，`van-tag`标签本身也是一个元素。
flex布局下样式只能影响`van-tag`的对齐行为，而不能影响到`van-tag`的内部。
你应该换一种实现方式来达到你的效果了。
