### ISSUE TITLE
希望Tab标签页支持 动画滑动跟随

### ISSUE THREAD

**Issue by JasonLamv-t** [youzan/vant-weapp#1876]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater?repo=VantWeapp

---

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater?repo=VantWeapp

**Comment by chenjiahan** [comment]
暂无计划支持
