### ISSUE TITLE
icon 的info为空时，info的边框始终存在

### ISSUE THREAD

**Issue by leo95123** [youzan/vant-weapp#1882]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater?repo=VantWeapp

---
如下图所示，icon的info本来是有一个1px的边框的，但是当我的info的内容为空时，这个边框不能自动取消，所以显示出来就有一条白线。
![微信截图_20190820140144](https://user-images.githubusercontent.com/28439527/63321467-6d011480-c353-11e9-829c-f04e72a83770.png)

https://youzan.github.io/vant-issue-generater?repo=VantWeapp

**Comment by chenjiahan** [comment]
目前版本`info`传空字符串会有这个问题，下个版本会修复

**Comment by chenjiahan** [comment]
已在 0.5.20 版本修复

**Comment by leo95123** [comment]
非常感谢
