### ISSUE TITLE
体验库中tabbar问题

### ISSUE THREAD

**Issue by PinelliaTime** [youzan/vant-weapp#1883]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater?repo=VantWeapp

---体验库小程序点击tabbar后无法返回到首页；
     手机版本：iPhone7 
     iOS-12.3.1
     微信：7.0.5

Please use the link below to create a new issue, the non-standard issue will be closed.

https://youzan.github.io/vant-issue-generater?repo=VantWeapp

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
