### ISSUE TITLE
[Bug Report] example导入微信开发者工具报错

### ISSUE THREAD

**Issue by Jarvis2018** [youzan/vant-weapp#1886]
### 设备
微信开发者工具

### VantWeapp 版本
0.5.19

### 基础库版本
2.8.0

### 请提供核心代码片段链接
https://github.com/youzan/vant-weapp/tree/dev/example

### 描述问题
example文件夹导入微信开发者工具报错

**Comment by chenjiahan** [comment]
报错内容是？

**Comment by I322871** [comment]
@chenjiahan  遇到类似问题，组件找不到。。。看了一下代码, app.json中写的组件lib的路径都是类似“../../dist/area/index”，可实际目录结构中dist和example目录是同级，所以应该是“../dist/area/index”?

**Comment by chenjiahan** [comment]
这个路径确实有点问题，已在 dev 分支修复

**Comment by I322871** [comment]
@chenjiahan 请问这个是修好了吗？还是有问题啊。。。变成./dist，可是同级别没有dist目录啊。。。我就说下载了项目，切换到dev分支，npm install, npm run dev，然后还是不行啊。。。你有没有亲测一下呢？

**Comment by chenjiahan** [comment]
npm run dev 后会生成 example/dist 目录的
