### ISSUE TITLE
[Feature Request] swiper-cell新增互斥功能

### ISSUE THREAD

**Issue by chengaobin** [youzan/vant-weapp#1889]
### 这个功能解决了什么问题
我希望滑动swiper-cell的时候，其他已经右划 的swiper-cell能够自动关闭，或者能够提供相应的监听事件api

### 建议的API是什么样的
能够监听swiper-cell的滑动事件或者能够给出字段设置互斥

**Comment by rex-zsd** [comment]
预计将在1.0版本支持互斥功能~
