### ISSUE TITLE
网站进不去

### ISSUE THREAD

**Issue by careCao** [youzan/vant-weapp#1891]
https://youzan.github.io/vant-weapp/#/tab
![image](https://user-images.githubusercontent.com/21763302/63399956-b9585d00-c404-11e9-895f-b82ede907d3f.png)

**Comment by ZjVirus** [comment]
加1

**Comment by careCao** [comment]
![image](https://user-images.githubusercontent.com/21763302/63400188-89f62000-c405-11e9-8d72-d0f37ce41e98.png)

**Comment by ZjVirus** [comment]
可以了

**Comment by chenjiahan** [comment]
刚才有点问题，已修复
