### ISSUE TITLE
[Bug Report] van-switch-cell按钮显示异常

### ISSUE THREAD

**Issue by zhushuai662** [youzan/vant-weapp#1892]
### 设备
iphone6sp, MAC版微信小程序开发工具

### VantWeapp 版本
0.5.17

### 基础库版本
2.8.0

### 如果是 UI 问题，截图链接（多图回车分隔）

https://sm.ms/image/WaBJSXvj2iw9GpQ

![截图](https://i.loli.net/2019/08/21/WaBJSXvj2iw9GpQ.png)

### 请提供核心代码片段链接
https://gist.github.com/zhushuai662/6c3faac5b915795bb6e6670c40d9db9e

### 描述问题
github gist打不开，在这里写下核心代码
<view class="container">
<van-cell-group>

   <van-switch-cell
        title="是否在售"
        checked="{{ product.isOnSale }}"
        bind:change="isOnSaleChange"
        border
        title-width= "100rpx"
      />
</van-cell-group>
</view>

css代码：
page {
  background: #f4f4f4;
  min-height: 100%;
}
.container {
  background: #f4f4f4;
  min-height: 100%;
  padding-top: 10rpx;
  width: 100%;
}

**Comment by rex-zsd** [comment]
从贴的代码来看没有问题，是不是有全局给`van-switch`或`van-switch__node`设置了`font-size`？

**Comment by zhushuai662** [comment]
> 从贴的代码来看没有问题，是不是有全局给`van-switch`或`van-switch__node`设置了`font-size`？

没有设置全局，只有在这一个页面引入了vant相关组件

**Comment by lkangjing** [comment]
我也遇到了同样的问题，解决了没？
