### ISSUE TITLE
[Bug Report] `van-tree-select`的`click-nav`和`click-item`在Taro中无法触发

### ISSUE THREAD

**Issue by mihuartuanr** [youzan/vant-weapp#1893]
### 设备
微信开发者工具

### VantWeapp 版本
0.5.19

### 基础库版本
2.8.0

### 描述问题
`van-tree-select`的`click-nav`和`click-item`在Taro中无法触发，见有朋友提过这个问题，[#764](https://github.com/youzan/vant-weapp/issues/764)。

**Comment by kinm** [comment]
> ### 设备
> 微信开发者工具
> 
> ### VantWeapp 版本
> 0.5.19
> 
> ### 基础库版本
> 2.8.0
> 
> ### 描述问题
> `van-tree-select`的`click-nav`和`click-item`在Taro中无法触发，见有朋友提过这个问题，[#764](https://github.com/youzan/vant-weapp/issues/764)。

我这边是用的WEPY2.0，也遇到这种问题，我将“-”命名方式改为驼峰即可正常运行，老哥可以试试！

**Comment by chenjiahan** [comment]
参见 https://github.com/youzan/vant-weapp/issues/1911

**Comment by mihuartuanr** [comment]
> > ### 设备
> > 微信开发者工具
> > ### VantWeapp 版本
> > 0.5.19
> > ### 基础库版本
> > 2.8.0
> > ### 描述问题
> > `van-tree-select`的`click-nav`和`click-item`在Taro中无法触发，见有朋友提过这个问题，[#764](https://github.com/youzan/vant-weapp/issues/764)。
> 
> 我这边是用的WEPY2.0，也遇到这种问题，我将“-”命名方式改为驼峰即可正常运行，老哥可以试试！

你这是又封装了一层吧，这个库本身还是不支持的样子。

> > ### 设备
> > 微信开发者工具
> > ### VantWeapp 版本
> > 0.5.19
> > ### 基础库版本
> > 2.8.0
> > ### 描述问题
> > `van-tree-select`的`click-nav`和`click-item`在Taro中无法触发，见有朋友提过这个问题，[#764](https://github.com/youzan/vant-weapp/issues/764)。
> 
> 我这边是用的WEPY2.0，也遇到这种问题，我将“-”命名方式改为驼峰即可正常运行，老哥可以试试！

你这是选择又封装一层或者修改源码的了吧，本身还是不支持的样子。

**Comment by kinm** [comment]
> > > ### 设备
> > > 微信开发者工具
> > > ### VantWeapp 版本
> > > 0.5.19
> > > ### 基础库版本
> > > 2.8.0
> > > ### 描述问题
> > > `van-tree-select`的`click-nav`和`click-item`在Taro中无法触发，见有朋友提过这个问题，[#764](https://github.com/youzan/vant-weapp/issues/764)。
> > 
> > 
> > 我这边是用的WEPY2.0，也遇到这种问题，我将“-”命名方式改为驼峰即可正常运行，老哥可以试试！
> 
> 你这是选择又封装一层或者修改源码的了吧，本身还是不支持的样子。
> 
> 我现在是直接封装了一层...希望本身就支持。

刚刚看了一遍wepy编译后的代码，发现这个问题是由于wepy编译后的WXML文件引起的！编译后的代码如下图：
![image](https://user-images.githubusercontent.com/7105727/63745673-5fa8d480-c8d5-11e9-9bdc-65c0378ac23f.png)


最后的解决方案是给bind多加一个 `:`解决

![image](https://user-images.githubusercontent.com/7105727/63745571-22dcdd80-c8d5-11e9-968e-6877a3bba8ec.png)

![image](https://user-images.githubusercontent.com/7105727/63745691-6df6f080-c8d5-11e9-88ec-b12fb5f30e99.png)

**Comment by chenjiahan** [comment]
对的
