### ISSUE TITLE
[Bug Report] 图标有时不显示

### ISSUE THREAD

**Issue by chenyi5266** [youzan/vant-weapp#1899]
### 设备
所有手机

### VantWeapp 版本
0.5.19

### 基础库版本
2.8.0

### 请提供核心代码片段链接
http://test.com

### 描述问题
图标字体应该是从有赞的cdn获取的，偶尔网慢的时候，第一次进入小程序，所有图标都不显示，只是显示个框

Failed to load font https://img.yzcdn.cn/vant/vant-icon-c2acf5.woff2

**Comment by chenyi5266** [comment]
加载字体需要100K，用户首次进入时如果赶上网慢，那体验真的是非常不好！！！

**Comment by chenjiahan** [comment]
字体文件只有 22k，不知道你说的 100k 是什么文件

**Comment by chenyi5266** [comment]
> 字体文件只有 22k，不知道你说的 100k 是什么文件

3个字体文件呢，两个20K的，一个50K的，你看看icon里的css

**Comment by chenjiahan** [comment]
字体文件只会加载一个，优先加载浏览器支持的字体格式

**Comment by chenyi5266** [comment]
> 字体文件只会加载一个，优先加载浏览器支持的字体格式

这样啊，受教了~

**Comment by chenjiahan** [comment]
嗯呐，iconfont 都是这样的，如果真有网络特别差的情况，也木有什么办法
