### ISSUE TITLE
button的按钮自定义颜色没有生效了

### ISSUE THREAD

**Issue by mablevi** [youzan/vant-weapp#1901]
简单的使用，发现自定义颜色没有生效
![image](https://user-images.githubusercontent.com/6835617/63597638-896dad00-c5f0-11e9-8cbb-89125ef8a357.png)

**Comment by chenjiahan** [comment]
请升级到最新版试下，这个是新增的功能

**Comment by mablevi** [comment]
@chenjiahan 0.5.19  代码里就没找到 color 这个属性，是不是漏掉了，请检查。。。

**Comment by chenjiahan** [comment]
记错了，这个还没发布，0.5.20 才有。。

**Comment by mablevi** [comment]
好的，看来文档超前了

**Comment by chenjiahan** [comment]
刚发布了 0.5.20 版本，可以试下哈
