### ISSUE TITLE
Popup 弹出层蒙层偶尔会不显示

### ISSUE THREAD

**Issue by liuzhichao2017** [youzan/vant-weapp#1902]
描述一下问题，触发的条件是在我进入页面后，通过Onload请求接口获取数据后才弹出蒙层，Popup 弹出层中内容会正常显示，但是蒙层在第一次进入小程序的时候有一定概率不显示，切换到其他页面再切回来后即正常显示。

**Comment by liuzhichao2017** [comment]
出现问题的机型，iphonexsmax，iphone5s以及iphoneXR

**Comment by rex-zsd** [comment]
未按规范提交issue，重新提一个吧，把必要的信息都补一下。
