### ISSUE TITLE
toast调用显示警告,无法显示toast

### ISSUE THREAD

**Issue by zhanglijie5997** [youzan/vant-weapp#1903]
警告内容     ： 未找到 van-toast 节点，请确认 selector 及 context 是否正确
index.json  =>  {
    "usingComponents":{
        "index-com":"../../components/index/index",
        "van-button": "../../components/vant-weapp/dist/toast/index"
    }
}
index.wxml => <van-toast id="van-toast" ></van-toast>
index.js      => import  Toast  from '../../components/vant-weapp/dist/toast/toast';
                         showToast:function() {
                              Toast('加载中')
                          }

**Comment by rex-zsd** [comment]
请检查一下是否有在wxml中引入`van-toast`组件，然后如果是在自定义组件中调用，请传入`context: this`。
