### ISSUE TITLE
[Bug Report]textarea组件placeholder错位

### ISSUE THREAD

**Issue by Exrick** [youzan/vant-weapp#1906]
### 设备
IPhone X

### VantWeapp 版本
0.5.20

### 基础库版本
2.8.0

### 截图
- IOS
![11566748157_.pic.jpg](https://i.loli.net/2019/08/25/aMeHtUXKNh8b46r.jpg)

### 请提供核心代码片段链接
``` javascript
<van-field
    value="{{ message }}"
    label="留言"
    type="textarea"
    placeholder="请输入留言"
    autosize
    border="{{ false }}"
  />
</van-cell-g
```

### 描述问题
textarea组件placeholder错位，详见官方预览demo

**Comment by rex-zsd** [comment]
#1931 fix this

**Comment by chen-can** [comment]
这到底是解决了没

**Comment by rex-zsd** [comment]
0.5.21将会修复

**Comment by chen-can** [comment]
目前有没有什么临时解决办法

**Comment by chen-can** [comment]
样式穿透可以吗

**Comment by flycj** [comment]
还没修复
