### ISSUE TITLE
是否支持钉钉小程序？

### ISSUE THREAD

**Issue by mingxuan0624** [youzan/vant-weapp#1908]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。
你好，我想问下vant-weapp是否支持钉钉小程序？谢谢！
https://youzan.github.io/vant-issue-generater?repo=VantWeapp

**Comment by chenjiahan** [comment]
不支持的喔，目前仅支持微信小程序
