### ISSUE TITLE
代码示例中，SubmitBar 提交订单栏，效果与代码不符

### ISSUE THREAD

**Issue by zhxyms** [youzan/vant-weapp#1909]
SubmitBar中，高级用法的示例效果和代码不相符，用van-radio-group替代tag时，单选框紧靠着左侧，不符合常规的美观，如能看到，请修复此问题。

**Comment by rex-zsd** [comment]
默认是没有样式的，demo中也是在`tag`上加了左侧外边距。
可以自己手动加下哈。
