### ISSUE TITLE
[BUG] VANT组件中所有带有“-”的$emit事件在wepy2.0中都不会执行，望查实、更新！ 比如click-overlay、click-item、click-nav

### ISSUE THREAD

**Issue by kinm** [youzan/vant-weapp#1911]
解决方法：将“-”的这种命名方式改为驼峰即可
`this.$emit('clickNav', {
        index: index
  });`

`bind:clickNav="onClickNav"`

**Comment by kinm** [comment]
解决方法：将“-”的这种命名方式改为驼峰即可

**Comment by rex-zsd** [comment]
修改事件名称会造成breaking change，原生小程序是支持事件名中带`-`的，这个是wepy的bug。

**Comment by chenjiahan** [comment]
请到 wepy 仓库下反馈此问题

**Comment by kinm** [comment]
> 请到 wepy 仓库下反馈此问题

OK，感谢老哥

**Comment by kinm** [comment]
> 修改事件名称会造成breaking change，原生小程序是支持事件名中带`-`的，这个是wepy的bug。

![image](https://user-images.githubusercontent.com/7105727/63744352-aa285200-c8d1-11e9-9e9d-393ae3594721.png)

这是wepy2.0编译后的wxml代码，确实是wepy的问题，bindclick-nav改为bind:click-nav即可运行！

哭 ....

**Comment by kinm** [comment]
最终解决方法如下（仅限WEPY2.0，其他框架未证实）：

给`bind:`多加一个 `:`

![image](https://user-images.githubusercontent.com/7105727/63745807-b9110380-c8d5-11e9-8abb-5b1978a26674.png)
