### ISSUE TITLE
0.5.20版本 van-submit-bar的tip设为false，还是显示自定义tip

### ISSUE THREAD

**Issue by hyfdemo** [youzan/vant-weapp#1914]
<van-submit-bar
  disabled='{{disabled}}'
  loading="{{loading}}"
  price="{{ amount }}"
  button-text="提交订单"
  bind:submit="orderCreate"
  tip="{{ false}}"
>
  <view slot="tip">
    <van-icon name="info-o" style='vertical-align:middle;'/>您未选择收货地址, <navigator url='/pages/addressList/addressList?url=orderShops' style='color:blue;text-decoration:underline;display:inline-block;'>请选择地址</navigator>
  </view>
</van-submit-bar>

![image](https://user-images.githubusercontent.com/23278722/63761259-6a726200-c8f3-11e9-92d0-023e841337f1.png)

**Comment by rex-zsd** [comment]
`tip`属性与`tip`slot是独立的，不能互相控制。
