### ISSUE TITLE
submit-bar 按钮样式无效

### ISSUE THREAD

**Issue by rungroo** [youzan/vant-weapp#1915]
我在submit-bar中使用了自定义的按钮样式类 btn-submit，如下：
<van-submit-bar button-text="提交" button-class="btn-submit" bind:submit="submit" />

btn-submit 类具体定义：
.btn-submit {
  background-color: #096;
  color: black;
}

问题是按钮颜色没有变化，还是红色。
查看源码，这里的按钮强制使用了内置的.van-button--danger，该类的颜色将我自定义的颜色覆盖掉了。

请问如何使用我自定义的颜色呢？

**Comment by rex-zsd** [comment]
加上`!important`试试。
