### ISSUE TITLE
[Bug Report] module "dist/@vant/icons/src/config" is not defined

### ISSUE THREAD

**Issue by lzpswat** [youzan/vant-weapp#1921]
### 设备
win10 微信开发者工具

### VantWeapp 版本
0.5.20

### 基础库版本
2.8.1

### 请提供核心代码片段链接
https://gist.github.com/lzpswat/a39e25b848ec053888c4662f433a2457

### 描述问题
查看example时出现报错。

**Comment by rex-zsd** [comment]
多半是微信开发者工具的问题，可以尝试`npm run dev`之后重启微信开发者工具。
