### ISSUE TITLE
[Bug Report] 调用toast提示 未找到 van-toast 节点，请确认 selector 及 context 是否正确

### ISSUE THREAD

**Issue by daweiyong** [youzan/vant-weapp#1924]
### 设备
mac

### VantWeapp 版本
0.5.20

### 基础库版本
2.7.1

### 如果是 UI 问题，截图链接（多图回车分隔）

![截图](https://sm.ms/image/y6AqnUsWjkdJYVP)

![截图](https://sm.ms/image/qbD5wWeniAjzNxU)

![截图](https://sm.ms/image/7UwI2iyfXDdJ8zo)

![截图](https://sm.ms/image/HjVh3PsvWUBGoOl)

### 请提供核心代码片段链接
https://gist.github.com/daweiyong/4111f7707a737c9ff281f450c1796e9f

### 描述问题
调用toast提示 未找到 van-toast 节点，请确认 selector 及 context 是否正确

**Comment by rex-zsd** [comment]
请确认 selector 及 context 是否正确，组件内使用请传递正确的 context

**Comment by ww5656** [comment]
<van-toast id="van-toast"/>在需要的页面加上就可以了

**Comment by ww5656** [comment]
`<van-toast id="van-toast"/>`

**Comment by gaofengxu888** [comment]
经实测，加上也不行

**Comment by liu-xiao-cui** [comment]
@rex-zsd 可以把 selector 和 context 放在文档开头部分说明，比较显眼点，或者加个在组件中使用的例子 ^_^
