### ISSUE TITLE
[Bug Report] 关于vant-weapp的单位是px的问题

### ISSUE THREAD

**Issue by h262729** [youzan/vant-weapp#1930]
### 设备
微信开发者工具

### VantWeapp 版本
0.5.20

### 基础库版本
2.8.1

### 如果是 UI 问题，截图链接（多图回车分隔）

![截图](https://i.loli.net/2019/08/29/9QtfOR6DyvdIHM3.png)

![截图](https://i.loli.net/2019/08/29/zyRxFLQbldqZTCn.png)

### 请提供核心代码片段链接
http://无.com

### 描述问题
vant-weap的组件的单位是px，在适配的时候会有点问题，因为页面自己用的是rpx的单位。然后导致iphone6 和 iphone5的样式效果不一样。
原因是vant-weap是px，自己用的是rpx(微信小程序提供的适配单位)。这要怎么解决？

**Comment by rex-zsd** [comment]
可以使用postcss插件自行转换。
