### ISSUE TITLE
[Bug Report] wap-home等图标，只有线框风格图标，没有实底风格图标

### ISSUE THREAD

**Issue by wubinsheng2017** [youzan/vant-weapp#1936]
### 设备
wxApp

### VantWeapp 版本
0.5.20

### 基础库版本
2.8.0

### 请提供核心代码片段链接
https://github.com/youzan/vant-weapp/tree/dev/packages/icon

### 描述问题
wap-home等图标，只有线框风格图标，没有实体风格图标
能否提供对应的实体图标？

**Comment by mw248** [comment]
home图标是APP都要用的，建议至少把home对应的实底风格提供一下，方便调用

**Comment by chenjiahan** [comment]
后续会加上 wap-home 的实底版本

**Comment by chenjiahan** [comment]
已在 1.0.0-beta.0 版本支持
