### ISSUE TITLE
van-button的size属性设置mini后，不兼容小程序style:v2

### ISSUE THREAD

**Issue by a294974783** [youzan/vant-weapp#1937]
微信客户端 7.0 开始，UI 界面进行了大改版。小程序也进行了基础组件的样式升级。app.json 中配置 "style": "v2"可表明启用新版的组件样式。

我项目使用了v2，不兼容van-button的size属性

**Comment by chenjiahan** [comment]
后续会适配下

**Comment by chenjiahan** [comment]
试了一下，目前如果想覆盖 weui v2 Button 的样式，必须通过 important 强制覆盖多个属性，会对原有用户的样式产生影响，所以不会马上修改样式，继续观察下。

建议先不要使用 weui v2 样式

**Comment by cjsky666** [comment]
可以在单个组件使用的页面 进行强制覆盖  这样不会污染全局

页面上这样
<van-goods-action>
      <van-goods-action-icon icon="shop-o" link-type="switchTab" url="/pages/home/index" text="主页"  />
      <van-goods-action-icon icon="chat-o" text="客服"  open-type=""/>
      <van-goods-action-icon icon="cart-o" link-type="switchTab" info="99+" url="/pages/cart/index" text="购物车" />
      <van-goods-action-button class="mm"  text="加入购物车" type="warning" />
      <van-goods-action-button class="mm" text="立即购买" />
    </van-goods-action>
页面的wxss样式文件上这样覆盖 就OK了
.mm button{
  width:100%!important;
}
