### ISSUE TITLE
[Bug Report] 小程序-mpvue+vant-weapp 年月日时间选择器 报错

### ISSUE THREAD

**Issue by 2248157705** [youzan/vant-weapp#1938]
### 设备
微信开发者工具

### VantWeapp 版本
0.5.20

### 基础库版本
0.5.20

### 如果是 UI 问题，截图链接（多图回车分隔）

![截图](https://sm.ms/image/DaFyJ8VAEuWMcQn)

### 请提供核心代码片段链接
https://code.aliyun.com/2010055734/vant-weapp-date-pick/blob/master/src/pages/index/index.vue

### 描述问题
小程序-DatetimePicker 时间选择   年月日  报错formatter is not a function; [Component] Property Observer Error @ static/vant-weapp/dist/datetime-picker/index#updateValue 报错截图：https://sm.ms/image/DaFyJ8VAEuWMcQn

<template>
    <van-datetime-picker
      type="date"
      :value="currentDate"
      :formatter="formatter"
      bind:input="onInput"
    />
  </div>
</template>
   methods: {
    formatter(type, value) {
      if (type === 'year') {
        return `${value}年`;
      } else if (type === 'month') {
        return `${value}月`;
      }
      else if (type === 'day') {
        return `${value}日`;
      }
      return '';
    },
  },

**Comment by rex-zsd** [comment]
mpvue不支持原生小程序组件传入function类型的prop，不是vant-weapp的问题。

**Comment by rex-zsd** [comment]
mpvue用户只能避免使用这个特性，之后会在文档中标注。

**Comment by 2248157705** [comment]
果断放弃mpvue ,使用wepy o(￣▽￣)ｄ

**Comment by mircle** [comment]
第一次打开这个含有时间选择组件的页面  可以正常选择时间   第二次打开  时间选择空间弹出里面没有任何数据
