### ISSUE TITLE
[Feature Request] 建议van-card组件thumb-class控制的是van-card__thumb的样式

### ISSUE THREAD

**Issue by wswax** [youzan/vant-weapp#1945]
### 这个功能解决了什么问题
解决“van-card组件thumb-class不能控制van-card__thumb的样式 导致卡片左侧空间宽度无法自定义”的问题

### 建议的API是什么样的
建议van-card组件thumb-class控制的是van-card__thumb的样式

**Comment by JakeLaoyu** [comment]
可以使用外部样式覆盖

**Comment by rex-zsd** [comment]
修改`thumb-class`的位置会造成breaking change哦~暂时应该是不会动了
1.0会考虑用其他方式支持定义卡片图片尺寸。

**Comment by herock** [comment]
> 1.0会考虑用其他方式支持定义卡片图片尺寸

请问现在（v1.6.2）自定义卡片图片尺寸的最佳方式是什么？

**Comment by herock** [comment]
> 修改`thumb-class`的位置会造成breaking change哦~暂时应该是不会动了
> 1.0会考虑用其他方式支持定义卡片图片尺寸。

请问现在（v1.6.2）自定义卡片图片尺寸的最佳方式是什么？

**Comment by rex-zsd** [comment]
@herock 可以使用 CSS 变量 `--card-thumb-size` 来指定 `.van-card__thumb` 元素的尺寸。
CSS 变量的使用方式请看[文档](https://youzan.github.io/vant-weapp/#/theme)哈
