### ISSUE TITLE
hi vant 引用只有部分组件应用了 但是全部的组件都到了dist/ 如何打包只有引用的组件？

### ISSUE THREAD

**Issue by wastef** [youzan/vant-weapp#1950]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater?repo=VantWeapp

**Comment by rex-zsd** [comment]
这个不用担心，小程序在上传时只会上传有用到的代码。
