### ISSUE TITLE
[Bug Report] 输入框 onChange 与 onBlur事件

### ISSUE THREAD

**Issue by maopixin** [youzan/vant-weapp#1957]
### 设备
安卓9与微信开发者工具

### VantWeapp 版本
0.5.20

### 基础库版本
2.8.0

### 请提供核心代码片段链接
https://gist.github.com/

### 描述问题
当监听onBlur 事件的时候 onChange事件在输入框失焦的时候 会错误的触发一次，并且并且参数为 { value:'',curson: 0 } 对象类型，与文档描述的直接是value不同，导致使用onchange赋值的做法失败。

**Comment by chenjiahan** [comment]
已在 0.5.21 版本修复
