### ISSUE TITLE
picker多级联动滑动onChange事件获取value位置错位？

### ISSUE THREAD

**Issue by StellaYangF** [youzan/vant-weapp#1959]
<van-picker 
        columns="{{ columns }}" 
        bind:change="onChange"
        item-height='35'
/>

const citys = {
  '武汉': ['武昌', '硚口', '汉阳', '青山', '洪山'],
  '咸宁': ['咸安', '通山', '通城', '嘉鱼', '重阳']
};
Page({
 data: {
  columns: [
      {
        values: ['湖北'],
        className: 'column1',
      },
      {
        values: Object.keys(citys),
        className: 'column2'
      },
      {
        values: citys['武汉'],
        className: 'column3',
        defaultIndex: 2
      }
    ],
 },
  onChange(event) {
    const { picker, value, index } = event.detail;
    picker.setColumnValues(2, citys[value[1]]);
    console.log(value, picker, index);
  },
})
具体为下图: 
![1](https://user-images.githubusercontent.com/47094272/64307082-8b0f7b80-cfc7-11e9-9e0c-3cf97d87501f.jpg)

![2](https://user-images.githubusercontent.com/47094272/64314463-ae472480-cfe1-11e9-8a4f-81c7aaae6f62.jpg)

**Comment by rex-zsd** [comment]
第三行是`onChange`回调中你通过`picker.setColumnValues(2, citys[value[1]]);`自己修改的。
picker组件在中间列切换到咸宁时，第三列选中项就是汉阳。
