### ISSUE TITLE
Tabbar标签栏页面没有返回按钮，体验时无法回到主页了

### ISSUE THREAD

**Issue by Ctrlsman** [youzan/vant-weapp#1961]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater?repo=VantWeapp

**Comment by VicenLaw** [comment]
可以点击 右上角的【...】，回到首页

**Comment by rex-zsd** [comment]
目前可以重新打开小程序，后续1.0版本将会在demo小程序中去除这一部分。
