### ISSUE TITLE
[Bug Report] 倒计时修改手机系统时间会影响倒计时的正常运行

### ISSUE THREAD

**Issue by BrowLi** [youzan/vant-weapp#1966]
### 设备
移动端所有

### VantWeapp 版本
0.5.20

### 基础库版本
2.1.8

### 请提供核心代码片段链接
https://youzan.github.io/vant/#/zh-CN/count-down

### 描述问题
倒计时，time字段我通过获取服务器上的时间段计算出来的时间差，但是修改手机系统时间后会影响倒计时的正常运行

**Comment by chenjiahan** [comment]
这个没有办法解决呢，修改手机系统时间就是会影响计时的准确性
