### ISSUE TITLE
[Bug Report] 带图标的Toast，显示宽度被限定成了90px，导致显示不正确

### ISSUE THREAD

**Issue by wubinsheng2017** [youzan/vant-weapp#1980]
### 设备
wxApp

### VantWeapp 版本
0.5.20

### 基础库版本
2.8.2

### 请提供核心代码片段链接
https://github.com/youzan/vant-weapp/blob/dev/packages/toast/index.less

### 描述问题
带图标的Toast，显示宽度被限定成了90px，导致显示不正确。
<br/>【现象】
<br/>不带icon：
<br/>![noIcon.png](https://i.loli.net/2019/09/07/lnZCDovzNrEdIGA.png)
<br/>带icon：
<br/>![hasIcon.png](https://i.loli.net/2019/09/07/EwIgcCOvuBbd1nG.png)

<br/>【建议】
<br/>van-toast--icon样式中的width:90px，修改为min-width:90px
<br/>现状：
<br/>![bug.png](https://i.loli.net/2019/09/07/1YLkozwQxOmWI8J.png)
<br/>修复：
<br/>![bugfix.png](https://i.loli.net/2019/09/07/WueL8GH5nr4YJVb.png)

**Comment by chenjiahan** [comment]
设计规范就是这样的（微信也是如此），建议不要在图标 Toast 中显示太多的文字
