### ISSUE TITLE
dist 目录下没有 sidebar sidebarItem 组件

### ISSUE THREAD

**Issue by littlefromSea** [youzan/vant-weapp#1987]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater?repo=VantWeapp

**Comment by chenjiahan** [comment]
dev 分支上目前在开发的是 1.0 版本的代码，在 0.5 版本中，这个组件叫 Badge，所以你按照文档引入 Badge 组件就好
