### ISSUE TITLE
tabs吸顶模式，切换tab。tab组件会跑到底部去（ios）

### ISSUE THREAD

**Issue by badjone** [youzan/vant-weapp#2011]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater?repo=VantWeapp

**Comment by badjone** [comment]
第一页数据较多，tabs已经在顶部了，在加载过程中，快速切换第二个item，tabs就跑到底部了。
目前ios发现这个问题，android未发现

**Comment by badjone** [comment]
![image](https://user-images.githubusercontent.com/8895430/64582250-998ed600-d3bf-11e9-99a3-0077f895fb8f.png)
只用作顶部显示，暂时改了这里，可以了

**Comment by badjone** [comment]
是否是top 和bottom判断出问题了

**Comment by rex-zsd** [comment]
#1867
跟这个应该是一个问题
