### ISSUE TITLE
Slider取值范围

### ISSUE THREAD

**Issue by mihuartuanr** [youzan/vant-weapp#2022]
> 当前进度百分比，取值范围为 0-100

取值范围为0-100，可是，不同的业务场景下，该范围是不一样的。比如，目前，我的需求是20～50。

当前的效果是，显示0～100长度的轨道，只能在20～50范围拖拽。

希望效果：轨道两端就是20、50，在整个轨道内可以拖拽。

**Comment by chenjiahan** [comment]
1.0 版本会改成这样

**Comment by chenjiahan** [comment]
已在 1.0.0-beta.0 版本支持
