### ISSUE TITLE
关于组件disable失效问题

### ISSUE THREAD

**Issue by zhoufanglu** [youzan/vant-weapp#2023]
版本:
* weapp:0.5.2
* mpvue:2.0
使用`van-switch` 内添加disabled不生效
`switch`是变灰了，但是还能点击。
![image](https://user-images.githubusercontent.com/24451091/64681006-7e03f800-d4b1-11e9-9184-6f53e10f7ed4.png)
![image](https://user-images.githubusercontent.com/24451091/64681015-83614280-d4b1-11e9-9763-49be87f1d66f.png)

虽然变灰，但是还能点击变化

**Comment by chenjiahan** [comment]
Switch 并没有提供 click 事件，禁用的时候也没有对点击事件的处理逻辑
