### ISSUE TITLE
TreeSelect单选情况下选择报错

### ISSUE THREAD

**Issue by Mcyfeng** [youzan/vant-weapp#2026]
![image](https://user-images.githubusercontent.com/35359402/64765587-faacda00-d576-11e9-826b-18c35c666608.png)
这里应该改成  return array && array.constructor === 'Array';

**Comment by bruceqiq** [comment]
改成return array && array.constructor === 'Array';提示如下错误信息
ReferenceError: array is not defined

**Comment by cosloli** [comment]
同报错，错误信息： TypeError: activeList.indexOf is not a function

**Comment by cosloli** [comment]
解决方案：修改`tree-select\index.wxml` isArray方法：
```
function isArray (array) {
  // return array instanceof Array;
  return array.constructor === 'Array'
}
```

**Comment by cosloli** [comment]
@chenjiahan 建议修复

**Comment by bruceqiq** [comment]
> 解决方案：修改`tree-select\index.wxml` isArray方法：
> 
> ```
> function isArray (array) {
>   // return array instanceof Array;
>   return array.constructor === 'Array'
> }
> ```

使用该方式已修复

**Comment by chenjiahan** [comment]
已在 0.5.21 版本修复
