### ISSUE TITLE
SubmitBar或者GoodsAction中的按钮怎么调整圆角并一直靠右呢？

### ISSUE THREAD

**Issue by ArthurCL** [youzan/vant-weapp#2030]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater?repo=VantWeapp

**Comment by chenjiahan** [comment]
参见 https://github.com/youzan/vant-weapp/issues/2032
