### ISSUE TITLE
[Bug Report] van-search 组件clearable属性失效

### ISSUE THREAD

**Issue by david2tdw** [youzan/vant-weapp#2031]
### 设备
安卓

### VantWeapp 版本
0.5.19

### 基础库版本
2.8.2

### 请提供核心代码片段链接
https://gist.github.com/

### 描述问题
van-search组件在设置了clearable="{{false}}" 后 清除图标依然会在输入内容后显示出来

<van-search value="{{ value }}" clearable="{{false}}" placeholder="请输入搜索关键词" />

**Comment by david2tdw** [comment]
代码如下
```
<van-search value="{{ value }}" clearable="{{false}}" placeholder="请输入搜索关键词" />
```

**Comment by chenjiahan** [comment]
0.5.20 版本开始支持该属性
