### ISSUE TITLE
[Bug Report] GoodsAction组件圆形按钮怎么设置

### ISSUE THREAD

**Issue by yellowswf** [youzan/vant-weapp#2032]
### 设备
所有通用设备

### VantWeapp 版本
0.5.21

### 基础库版本
2.8.2

### 请提供核心代码片段链接
https://github.com/youzan/vant-weapp/blob/dev/example/pages/goods-action/index.wxml

### 描述问题
圆形按钮不能配置

**Comment by chenjiahan** [comment]
圆形按钮会在 1.0 版本提供，目前正在开发中
