### ISSUE TITLE
[Bug Report] textarea输入时placeholder不消失

### ISSUE THREAD

**Issue by www6688265** [youzan/vant-weapp#2035]
### 设备
iOS

### VantWeapp 版本
0.5.21

### 基础库版本
2.8.0

### 如果是 UI 问题，截图链接（多图回车分隔）

![截图](https://i.loli.net/2019/09/17/PJjyk32BrfMx4Fh.jpg)

### 请提供核心代码片段链接
https://gist.github.com/www6688265/aa2b05ce6557547a00d8c50b9b0a4bdc

### 描述问题
在苹果设备中使用原生输入法，在打字的时候placeholder不会消失，导致拼音重叠在placeholder上。

**Comment by JakeLaoyu** [comment]
`0.5.21` 没有复现，请确认版本

**Comment by WormGirl** [comment]
同样的问题
