### ISSUE TITLE
支付宝小程序UI组件库

### ISSUE THREAD

**Issue by chen-can** [youzan/vant-weapp#2038]
请问能否使用 Antmove 小程序转换器基于 vant-weapp 转换得到UI组件库
目前已知 iview-weapp 可以使用 希望官方能够支持

**Comment by chenjiahan** [comment]
已经有了喔 是 antmove 团队提供的

https://github.com/ant-move/Vant-Aliapp

**Comment by liujiayii** [comment]
> 已经有了喔 是 antmove 团队提供的
> 
> https://github.com/ant-move/Vant-Aliapp

自己怎么用antmove搬运vant呢？antmove官网好像并没有提到怎么搬运组件库

**Comment by chenjiahan** [comment]
搬运方法得请教 antmove 团队了，我们也不是很清楚

**Comment by liujiayii** [comment]
> 搬运方法得请教 antmove 团队了，我们也不是很清楚

谢谢，vant以后有出跨端的ui组件库的计划吗？

**Comment by chenjiahan** [comment]
暂时木有呢

**Comment by liudonghua123** [comment]
支付宝小程序为什么不用支付宝自己的antd ui (mobile) 呢？

**Comment by liujiayii** [comment]
> 支付宝小程序为什么不用支付宝自己的antd ui (mobile) 呢？

小程序用不了antd 吧

**Comment by liudonghua123** [comment]
@liujiayii antd我自己的感觉其实是一套设计规范，类似于google的material，之前还看过一个https://eva.design/，主要就是组件样式再加上vue、react封装成方便使用的组件，理论上应该可以做到应用于小程序端的，可能开发团队没有这个计划

**Comment by meigesir** [comment]
> 已经有了喔 是 antmove 团队提供的
> 
> https://github.com/ant-move/Vant-Aliapp

star数太少了，而且好久没更新了，不敢用

**Comment by meigesir** [comment]
> > 已经有了喔 是 antmove 团队提供的
> > https://github.com/ant-move/Vant-Aliapp
> 
> star数太少了，而且好久没更新了，不敢用

看到了支付宝小程序官方库 mini-ali-ui
https://github.com/Alibaba-mp/mini-ali-ui
