### ISSUE TITLE
tab标签套list列表，切换连续多次触发加载

### ISSUE THREAD

**Issue by fanhu371328** [youzan/vant-weapp#2039]
tab标签里面嵌套list列表，初始化加载没问题，tab.id =1 是上拉加载三页数据，此时切换tab.id=2，onchange事件只执行一次，但是数据请求会执行2次或者3次。
次情况发生的场景：

如果加载完tab.id =1 的三页数据后将页面滑动到顶部，也就是第一条数据那里，再切换tab.id=2，此时加载数据正常为tab.id=2的第一页数据。

如果加载完tab.id =1 的三页数据后不将页面滑动到顶部，也就是还在最后一页数据那里不动，直接点或者左右滑动切换tab.id=2，此时加载数据或一次性触发多次请求。onchange事件中congsole.log只会打印一次，

求解决方案，

**Comment by fanhu371328** [comment]
问题最后跟踪到是list列表的onLoad 事件会连续多次执行

**Comment by fanhu371328** [comment]
一页数据有10条，是可以占满一屏的，都可以占满两屏

**Comment by chenjiahan** [comment]
这里是小程序仓库，请到 Vant 仓库下按照模板提 issue
