### ISSUE TITLE
[Bug Report] van-field click-icon事件无法获取

### ISSUE THREAD

**Issue by xiaohunsdt** [youzan/vant-weapp#2054]
### 设备
android and ios

### VantWeapp 版本
0.5.21

### 基础库版本
2.8.2

### 请提供核心代码片段链接
https://gist.github.com/xiaohunsdt/596e4c683ef6df4189c1e48080b00669

### 描述问题
在微信开发工具中，点击右边图标没有任何反应！在组件源码内 
onClickIcon() {
            this.$emit('click-icon');
 },
这里添加一行 console.log('icon is clicked!')
测试，点击事件是可以捕获到！但是我自己@click-icon这里却没办法捕获到事件

**Comment by rex-zsd** [comment]
是用了mpvue?
mpvue不支持事件名中间带`-`的，vant-weapp这解决不了。
