### ISSUE TITLE
[Bug Report] search组件 无法绑定value

### ISSUE THREAD

**Issue by egg2** [youzan/vant-weapp#2056]
### 设备
锤子，微信开发工具

### VantWeapp 版本
0.5.20

### 基础库版本
2.8.2

### 请提供核心代码片段链接
https://gist.github.com/egg2/b9fd3f936c46cc420a92c03270700d45

### 描述问题
使用search组件时，输入搜索内容， 搜索内容并未绑定

 
 <van-search value="{{widget.options.defaultValue}}" bind:search="handleClickEvent">
  </van-search>
  
  
  methods: {
    handleClickEvent:function(event){
      console.log(this.data.widget.options.defaultValue); //  defaultValue 为空
    }
  }

**Comment by rex-zsd** [comment]
小程序是没有双向绑定的，需要自行绑定一下`change`事件并修改value值哈。
