### ISSUE TITLE
当页面tab多余4个标签横向滑动时，底部出现明显滚动条样式

### ISSUE THREAD

**Issue by VenusPP** [youzan/vant-weapp#2070]
![Screenshot_20190920-113316](https://user-images.githubusercontent.com/28476594/65297651-4248ec80-db9b-11e9-8d93-b7bc45617e47.png)
"vant-weapp": "^0.5.21"，
手机: 华为麦芒6，
版本: 7.0,
调试基础库: 2.8.3

**Comment by chenjiahan** [comment]
在此 issue 中跟进 https://github.com/youzan/vant-weapp/issues/2144

**Comment by Miracle-nx** [comment]
怎么解决呢的
