### ISSUE TITLE
[Feature Request] <van-transition>​动画延迟结束后如何自动进行某些操作？

### ISSUE THREAD

**Issue by githubZhangMingXin** [youzan/vant-weapp#2071]
### 这个功能解决了什么问题
有没有类似bindanimationend的功能？

### 建议的API是什么样的
类似bindanimationend
想实现的效果是，动画结束后运行某些功能方法。请问这该怎么做？

**Comment by rex-zsd** [comment]
下版本将会在transition上增加一系列事件。
