### ISSUE TITLE
[Bug Report] checkbox复选框显示bug

### ISSUE THREAD

**Issue by zhxyms** [youzan/vant-weapp#2075]
### 设备
华为荣耀9

### VantWeapp 版本
1.0.0-beta.0

### 基础库版本
2.8.0

### 如果是 UI 问题，截图链接（多图回车分隔）

![截图](https://i.loli.net/2019/09/20/ceTkwhxS9yZoBKJ.png)

![截图](https://i.loli.net/2019/09/20/sagtqh9AH3GdfDT.png)

### 请提供核心代码片段链接
https://developers.weixin.qq.com/s/xhQzDwmS7WbS

### 描述问题
checkbox出现显示bug，整体页面布局flex，checkbox运用margin:0 auto;即出现此bug

**Comment by rex-zsd** [comment]
问题跟`flex`和`margin: 0 auto;`没关系。
根本原因是在`width: 15%;`使得图标只有上层view宽度的15%，导致图标被切割。
调整下你的样式吧~
