### ISSUE TITLE
官网为什么没有Sku规格文档介绍了

### ISSUE THREAD

**Issue by tangtianyo** [youzan/vant-weapp#2077]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater?repo=VantWeapp

**Comment by chenjiahan** [comment]
VantWeapp 没有 Sku 组件，Vant 有

**Comment by Megasu** [comment]
Vant 4 也没有了 SKU 组件，请问是太忙了没时间开发吗？
