### ISSUE TITLE
Tab 标签页 如何插入或动态调整顺序

### ISSUE THREAD

**Issue by imyellow** [youzan/vant-weapp#2084]
某一个标签页如果设置了暂时隐藏或者需要根据网络获取的参数来决定显不显示，那么如果先隐藏后显示，他的顺序始终会排到最后面，请问如何解决？

或者如何动态的调整 tab 标签的顺序？

**Comment by rex-zsd** [comment]
没提供代码和截图，不清楚是什么情况…………

**Comment by imyellow** [comment]
> 没提供代码和截图，不清楚是什么情况…………


**问题1：**

就是比如：

当载入时 `someValue=false`

```
<van-tabs active="{{ active }}">
  <van-tab title="标签 1">内容 1</van-tab>
  <van-tab v-if="someValue" title="标签 2">内容 2</van-tab>
  <van-tab title="标签 3">内容 3</van-tab>
</van-tabs>
```

以上只会显示 `标签1` 和`标签3`

当我过一会儿再改变 `someValue=true` 时，显示的标签变成了

`标签1` `标签3` `标签2`


**问题 2**

例如代码：

```
<van-tabs active="{{ active }}">
  <van-tab title="标签 1">内容 1</van-tab>
  <van-tab title="标签 2">内容 2</van-tab>
</van-tabs>
```

经过用户操作之后，我想插入一个新的标签页进去，比如变成

`标签1` `新标签` `标签2`

我要如何实现呢？
