### ISSUE TITLE
van-tabbar-active默认颜色

### ISSUE THREAD

**Issue by leejing4766465** [youzan/vant-weapp#2091]
这是我在app.wxss定义的van-tab的默认激活颜色，可以用。但是有一个让人抓狂的问题：第一次加载的时候会显示默认的红色，颜色一闪而过，第二次加载就没有了，但是看着很不爽！请问有没有办法解决？

.van-tab--active .van-ellipsis{
  color: #5AC380;
}

.van-tabbar-item,
.van-tabbar-item--active{
  color: #5AC380;
}

**Comment by rex-zsd** [comment]
加上`!important`试试
