### ISSUE TITLE
van-grid-item 有 active 这个属性吗

### ISSUE THREAD

**Issue by neozhu** [youzan/vant-weapp#2092]
van-grid-item 有 active 这个属性吗

**Comment by neozhu** [comment]
van-grid-item info/dot 这个属性好像无效，并没有是现实出来，不知道你们有没有这样问题

**Comment by rex-zsd** [comment]
`active`、`info`、`dot`这几个属性都没有。
看下文档https://youzan.github.io/vant-weapp/#/grid

**Comment by neozhu** [comment]
> https://youzan.github.io/vant-weapp/#/grid

我看了你提供的最后一个例子里是信息提示里有info 99 这个数字的。
另外能否考虑加上

**Comment by Eamonnzhang** [comment]
@neozhu  下个版本会支持 info dot 属性。例子里面当前预览的是 Vue 版 Vant 的示例，少部分功能可能与小程序版有出入，请以文档描述和实际效果为准。
