### ISSUE TITLE
tabbar遮挡到action-sheet组件

### ISSUE THREAD

**Issue by Pearson-Zhang** [youzan/vant-weapp#2095]
实例化<van-action-sheet 
  show="{{ show }}" 
  actions="{{ actions }}"
  cancel-text="取消"
/>
全局的vant tabbar会遮挡到action-sheet 的底部

![TIM截图20190925170508](https://user-images.githubusercontent.com/40453270/65586949-9b5bba80-dfb7-11e9-8fa7-e764db596691.jpg)

**Comment by Pearson-Zhang** [comment]
<van-action-sheet 
  show="{{ show }}" 
  actions="{{ actions }}"
  cancel-text="取消"
/>
cancel-text="取消"会被tabbar遮挡到

**Comment by rex-zsd** [comment]
微信的tabbar层级位于最顶层，使用`z-index`是无法覆盖的。
无论原生的tabbar还是用van-tabbar作为自定义tabbar都是一样的。
具体可以看下微信社区的讨论。
https://developers.weixin.qq.com/community/develop/doc/000ee4ccd6cfa8a67da76bad251000

**Comment by SC-wuyingkai** [comment]
computed: {
    screenHeight() {
      return window.innerHeight - 50 + "px";
    },
  },

然后设置 路由的style
  <router-view class="mainRouter"  :style="{height:screenHeight}"/>
动态计算高度，这样久不会覆盖了
