### ISSUE TITLE
[Feature Request] 请问能在type为datetime的时间选择器中对分钟数进行filter筛选吗？

### ISSUE THREAD

**Issue by subdance** [youzan/vant-weapp#2100]
### 这个功能解决了什么问题
在type为datetime的时间选择器中对分钟数进行filter筛选

### 建议的API是什么样的
return options.minute.filter(minute => minute % 15 === 0)

**Comment by JakeLaoyu** [comment]
`1.0.0-beta.0` 版本已经支持

**Comment by zhuhengtan** [comment]
@JakeLaoyu type='datetime' 时的使用格式和type='time' 是一样的吗？我按官网的做怎么没有效果？
