### ISSUE TITLE
[Bug Report] Sticky 粘性布局在mpvue下无法触发scroll事件

### ISSUE THREAD

**Issue by havebear** [youzan/vant-weapp#2101]
### 设备
微信开发者工具（1.02.1907300）

### VantWeapp 版本
1.0.0-beta.0

### 基础库版本
2.8.2

### 请提供核心代码片段链接
https://codepen.io/havebear/pen/dybrxBR

### 描述问题
在mpvue的页面中引入Sticky并使用，无法触发scroll回调函数。

**Comment by JakeLaoyu** [comment]
mpvue 会把绑定 @scroll 时间的元素转成 `scroll-view`。没有保持对组件的引用

**Comment by havebear** [comment]
> mpvue会把绑定`@scroll`事件的元素转成`scroll-view`。没有保持对组件的引用

好的，倒是忘记这一茬了，谢谢
