### ISSUE TITLE
[Bug Report] Vant-weapp checkbox 无法控制icon-size

### ISSUE THREAD

**Issue by Hyejeongdd** [youzan/vant-weapp#2102]
### 设备
所有设备

### VantWeapp 版本
1.0.0-beta.0

### 基础库版本
2.7.7

### 请提供核心代码片段链接
https://gist.github.com/Hyejeongdd/bbfd80b20181f3725ae05c3993129881.js

### 描述问题
默认大小为20px 设定为12px不生效

**Comment by Hyejeongdd** [comment]
<view class="user-protocol">
                <van-checkbox value="{{checked}}" bind:change="onChange" shape="square" icon-size="12px" checked-color="#1AAD19"></van-checkbox>
                <view class="user-protocol-text" bindtap="goAgreement">同意《使用条款》</view>
            </view>

**Comment by JakeLaoyu** [comment]
请描述清楚问题，我这边没有复现无法控制， 有发现设置为 `12px` 后有样式bug。

**Comment by newbaner** [comment]
楼主问题解决了吗？

**Comment by JakeLaoyu** [comment]
使用 `1.0.0-beta.0` 版本

**Comment by Hyejeongdd** [comment]
> 使用 `1.0.0-beta.0` 版本

目前就是使用1.0版本

**Comment by JakeLaoyu** [comment]
@Hyejeongdd 请提供一下截图

**Comment by Lan-megumi** [comment]
同样的问题 
`<van-checkbox value="{{ item.chose }}" icon-size="12px"></van-checkbox>`

![image](https://user-images.githubusercontent.com/36163110/70367582-481db680-18dc-11ea-8e0f-8de8516f55b2.png)
