### ISSUE TITLE
[Feature Request] input-class 顺序问题

### ISSUE THREAD

**Issue by zpdsky** [youzan/vant-weapp#2103]
### 这个功能解决了什么问题
目前的 input-class 是在组件的 class 之前的，要想覆盖样式就需要每个写 !important 

### 建议的API是什么样的
建议改成 input-class 放在 class 的末尾，免去经常写 !important 的麻烦

**Comment by rex-zsd** [comment]
跟顺序无关，是用外部样式类必须加`!important`
仔细看下[官方文档](https://developers.weixin.qq.com/miniprogram/dev/framework/custom-component/wxml-wxss.html#%E5%A4%96%E9%83%A8%E6%A0%B7%E5%BC%8F%E7%B1%BB)
