### ISSUE TITLE
省市区组件为一列时，好像设置value以后无效，没有初始化

### ISSUE THREAD

**Issue by bks233** [youzan/vant-weapp#2104]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater?repo=VantWeapp

**Comment by bks233** [comment]
省市区组件为一列时，好像设置value以后无效，没有初始化

**Comment by JakeLaoyu** [comment]
> 每项以省市区编码作为 key，省市区名字作为 value。编码为 6 位数字，前两位代表省份，中间两位代表城市，后两位代表区县，以 0 补足 6 位。如北京编码为 11，以零补足 6 位，为 110000。

只有一列默认使用前两位判断默认值

**Comment by bks233** [comment]
完了，我用来选学校的，编码也不对





------------------ 原始邮件 ------------------
发件人: "Jake"<notifications@github.com>; 
发送时间: 2019年9月27日(星期五) 中午11:39
收件人: "youzan/vant-weapp"<vant-weapp@noreply.github.com>; 
抄送: "白开水sss"<846936341@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [youzan/vant-weapp] 省市区组件为一列时，好像设置value以后无效，没有初始化 (#2104)



 
每项以省市区编码作为 key，省市区名字作为 value。编码为 6 位数字，前两位代表省份，中间两位代表城市，后两位代表区县，以 0 补足 6 位。如北京编码为 11，以零补足 6 位，为 110000。
  
只有一列默认使用前两位判断默认值

**Comment by bks233** [comment]
我想了个办法解决了，我是编码不对，我是用来选学校的




------------------ 原始邮件 ------------------
发件人: "Jake"<notifications@github.com>;
发送时间: 2019年9月27日(星期五) 中午11:39
收件人: "youzan/vant-weapp"<vant-weapp@noreply.github.com>;
抄送: "白开水sss"<846936341@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [youzan/vant-weapp] 省市区组件为一列时，好像设置value以后无效，没有初始化 (#2104)



 
每项以省市区编码作为 key，省市区名字作为 value。编码为 6 位数字，前两位代表省份，中间两位代表城市，后两位代表区县，以 0 补足 6 位。如北京编码为 11，以零补足 6 位，为 110000。
  
只有一列默认使用前两位判断默认值
