### ISSUE TITLE
感觉 1.0.0.beta.1 的 env 有问题啊

### ISSUE THREAD

**Issue by cielu** [youzan/vant-weapp#2114]
### 设备
Android和iOS都有

### VantWeapp 版本
1.0.0-beta.1

### 基础库版本
1.9.97

### 请提供核心代码片段链接
https://youzan.github.io/vant-weapp/#/nav-bar

### 描述问题
更新到最新版，不是说 使用env()重构iOS安全区域适配，结果我安卓的 也没有自动适配顶部了啊，，当我用 navigationStyle:"custom" 的时候，出现的这个问题，看看你们会不会重现

**Comment by cielu** [comment]
不管我用模拟器还是真机都一样，顶部的 statusBar 的距离没有被填满。 beta-0 是正常的

**Comment by rex-zsd** [comment]
可能小程序在部分手机上未适配……

**Comment by pensacola1989** [comment]
请问这个修复更新了么？等着呢。。😂
