### ISSUE TITLE
[Bug Report] van-tabs标签 swipeable属性不能开启手势滑动切换

### ISSUE THREAD

**Issue by zjw950323** [youzan/vant-weapp#2115]
### 设备
微信小程序 iphone7

### VantWeapp 版本
1.0.0-beta.1

### 基础库版本
2.8.3

### 请提供核心代码片段链接
https://gist.github.com/zjw950323/93f41b14dafc2a5f66061e98b7f88869.js

### 描述问题
van-tabs标签 swipeable属性不能开启手势滑动切换

**Comment by JakeLaoyu** [comment]
实测可以滑动。是否是内容区域高度太小，滑动位置不正确
