### ISSUE TITLE
van-icon没有右箭头

### ISSUE THREAD

**Issue by jiangxiaoqiang** [youzan/vant-weapp#2116]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater?repo=VantWeapp

在vant中指定右侧箭头没有效果：

`<van-cell icon="{{imageUrl}}/home/popup-choice-icon.png" title="{{defaultHospital}}" is-link value="{{vaa}}" size="large" arrow-direction="right" bind:click="toggleBottomPopup" />`

看了icon中没有右侧箭头？

```
.van-icon-apps-o:before {
  content: "\F006";
}

.van-icon-arrow-down:before {
  content: "\F007";
}

.van-icon-arrow-left:before {
  content: "\F008";
}

.van-icon-arrow-up:before {
  content: "\F009";
}

.van-icon-arrow:before {
  content: "\F00A";
}
```

**Comment by chenjiahan** [comment]
默认值就是 right，不用指定

**Comment by xioxu** [comment]
虽然最终根据这里提示发现class="arrow"可以工作， 但还是建议不要这样做，还是加上"arrow-right"吧，不要跟使用的人带来这种奇怪的假定。
