### ISSUE TITLE
图标里没有“删除”？？就是垃圾桶的那个图标

### ISSUE THREAD

**Issue by zerocorner** [youzan/vant-weapp#2117]
### 设备
所有

### VantWeapp 版本
1.0.0-beta.1

### 基础库版本
所有

### 请提供核心代码片段链接
https://youzan.github.io/vant-weapp/#/icon

### 描述问题
图标里垃圾桶的那个“删除”图标吗？

**Comment by chenjiahan** [comment]
有的，仔细看
