### ISSUE TITLE
[Feature Request] Picker、Popup、Dialog等在微信小程序中打开,遮罩层未能覆盖原生头部

### ISSUE THREAD

**Issue by whlong789** [youzan/vant-weapp#2120]
### 这个功能解决了什么问题
Picker、Popup、Dialog等在微信小程序中打开,遮罩层未能覆盖原生头部

### 建议的API是什么样的
类似WeUI 或 小程序示例对应的Picker、Popup、Dialog

**Comment by chenjiahan** [comment]
无法做到遮挡原生头部喔
