### ISSUE TITLE
[Bug Report] Vant-weapp Dialog 不会弹出授权窗口

### ISSUE THREAD

**Issue by Hyejeongdd** [youzan/vant-weapp#2121]
### 设备
所有设备

### VantWeapp 版本
1.0.0-beta.1

### 基础库版本
2.8.3

### 请提供核心代码片段链接
https://gist.github.com/Hyejeongdd/99ad4060ae42e462cd5330a5b060f540

### 描述问题
组件调用时van-dialog时 confirm-button-open-type="getUserInfo" 并不会弹出微信授权窗口，confirm-button-open-type="getPhoneNumber"可以正常弹出

**Comment by Hyejeongdd** [comment]
清除所有信息后即可正常

**Comment by xuchengxue** [comment]
老哥为什么我的都弹不出，可以分享一下你的代码吗
