### ISSUE TITLE
[Bug Report] van-tabs报computedName of undefined

### ISSUE THREAD

**Issue by ZjVirus** [youzan/vant-weapp#2122]
### 设备
开发工具

### VantWeapp 版本
1.0.0-beta.1

### 基础库版本
2.8.1

### 请提供核心代码片段链接
https://youzan.github.io/vant-weapp/#/tab

### 描述问题
tabs报Cannot read property 'computedName' of undefined 
![image.png](https://i.loli.net/2019/10/08/RCjGJhbZ4BUqePp.png)

**Comment by JakeLaoyu** [comment]
组件库里并没有使用 `computedName`

**Comment by ZjVirus** [comment]
![image](https://user-images.githubusercontent.com/21301648/66381107-46726800-e9eb-11e9-919d-2742f0378341.png)
这个位置报的错

**Comment by JakeLaoyu** [comment]
`1.0.0-beta.1` 版本？

**Comment by ZjVirus** [comment]
是的，最新的版本

**Comment by chenjiahan** [comment]
@Eamonnzhang

**Comment by Eamonnzhang** [comment]
@ZjVirus  下个版本修复

**Comment by yellowswf** [comment]
v1.0.0-beta.2 问题依然存在

**Comment by huyongyong1992** [comment]
> ![image](https://user-images.githubusercontent.com/21301648/66381107-46726800-e9eb-11e9-919d-2742f0378341.png)
> 这个位置报的错

是的，默认active为0的话，而且又没设置computedName的情况下，会执行到 或后面逻辑，如果没用到computedName的话，或后面的  || this.children[0].computedName可以先删掉使用
