### ISSUE TITLE
DropdownMenu下拉菜单会跑到顶上去

### ISSUE THREAD

**Issue by DoubleYellowEgg** [youzan/vant-weapp#2123]
![QQ图片20191008172326](https://user-images.githubusercontent.com/45248334/66384010-89830a00-e9f0-11e9-8bc0-198f0abbdf2e.png)
![QQ图片20191008172332](https://user-images.githubusercontent.com/45248334/66384011-8a1ba080-e9f0-11e9-864c-bf9fdfc599b6.png)

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
