### ISSUE TITLE
Search 搜索组件中，自定义行动按钮中使用的bind:tap="onSearch"不可用，api不对

### ISSUE THREAD

**Issue by maxiaoqu** [youzan/vant-weapp#2124]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater?repo=VantWeapp
Search 搜索组件中，自定义行动按钮中使用的bind:tap="onSearch"不可用，api不对

**Comment by rex-zsd** [comment]
issue不合规范。
并且自定义按钮slot中的事件完全是自定义的，跟vant-weapp没关系的。
