### ISSUE TITLE
请问van-stepper怎么阻止冒泡事件，谢谢

### ISSUE THREAD

**Issue by hepai323** [youzan/vant-weapp#2125]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater?repo=VantWeapp

**Comment by rex-zsd** [comment]
直接在标签上catch需要阻止冒泡的事件即可
比如
```html
<van-stepper 
  catch:tap="noop" 
/>
```
