### ISSUE TITLE
[Bug Report] van-tabber切换状态没改变的问题

### ISSUE THREAD

**Issue by liutiyao** [youzan/vant-weapp#2128]
### 设备
微信开发者工具

### VantWeapp 版本
1.0.0-beta.1

### 基础库版本
无

### 如果是 UI 问题，截图链接（多图回车分隔）

![截图](https://i.loli.net/2019/10/09/hMrSKQ8WsiwykcJ.png)

![截图](https://i.loli.net/2019/10/09/C35DBqFZMetSsgH.png)

![截图](https://i.loli.net/2019/10/09/4P1XCTMS7qkQh9p.png)

### 请提供核心代码片段链接
https://sm.ms/image/hMrSKQ8WsiwykcJ

### 描述问题
数据已经改变为0了，但是tabber的状态还是没改变，需要再点击一次 onchange会在执行一遍

**Comment by rex-zsd** [comment]
看下文档代码示例里的代码片段。
这样的用法是不对的。

**Comment by iszmxw** [comment]
@rex-zsd  没用过

**Comment by liutiyao** [comment]
找到原因了，没调用this.getTabBar().init();
