### ISSUE TITLE
[Feature Request] Vant-weapp Toast 字数过多换行

### ISSUE THREAD

**Issue by Hyejeongdd** [youzan/vant-weapp#2129]
### 这个功能解决了什么问题
Toast.fail和success均为超过6个字就换行 建议能够自定义换行字数

### 建议的API是什么样的
 建议能够自定义换行字数 或提升数量限制

**Comment by chenjiahan** [comment]
暂无计划支持喔，太长就很难看了，建议使用换行符自行换行
