### ISSUE TITLE
[Bug Report] Vant-weapp ActionSheet 文档Demo错误

### ISSUE THREAD

**Issue by Hyejeongdd** [youzan/vant-weapp#2130]
### 设备
所有设备

### VantWeapp 版本
1.0.0-beta.1

### 基础库版本
2.8.3

### 如果是 UI 问题，截图链接（多图回车分隔）

![截图](https://i.loli.net/2019/10/10/FxBIudEbzm6JlYZ.png)

### 请提供核心代码片段链接
https://youzan.github.io/vant-weapp/#/action-sheet

### 描述问题
van-action-sheet/  应该更改为 /van-action-sheet

**Comment by chenjiahan** [comment]
感谢反馈，会修正下
