### ISSUE TITLE
[Bug Report] Tabs 问题

### ISSUE THREAD

**Issue by yuerzm** [youzan/vant-weapp#2131]
### 设备
iOS

### VantWeapp 版本
1.0.0-beta.1

### 基础库版本
2.8.3

### 如果是 UI 问题，截图链接（多图回车分隔）

![截图](https://i.loli.net/2019/10/10/UJE8S7lLKztXrW3.png)

### 请提供核心代码片段链接
https://github.com/youzan/vant-weapp/blob/dev/packages/tabs/index.ts

### 描述问题
1. tab 组件中 没有 定义 computedName， 
 
2. tabs methods 中的方法 有 currentIndex 的，都出来了null

**Comment by chenjiahan** [comment]
@Eamonnzhang

**Comment by Eamonnzhang** [comment]
#2122
