### ISSUE TITLE
[Bug Report] picker多列选择时columns设置defaultIndex不生效

### ISSUE THREAD

**Issue by chinaguopeng** [youzan/vant-weapp#2136]
### 设备
微信开发工具

### VantWeapp 版本
1.0.0-beta.1

### 基础库版本
2.8.3

### 请提供核心代码片段链接
https://github.com/youzan/vant-weapp/blob/dev/example/pages/picker/index.js

### 描述问题
 就在例子中测试的

      onShow(){
        let column4 = this.data.column4
        column4[0].defaultIndex = 1
        column4[1].defaultIndex = 1
        this.setData({ column4: column4})
      },

**Comment by rex-zsd** [comment]
`defaultIndex`是用来设置**默认选项**的，不是用来设置**当前选中项**的。
修改选中项请使用方法。

**Comment by chinaguopeng** [comment]
let picker = this.selectComponent('.ceshi')
    picker.setColumnValue(1,'嘉兴')
    console.log(picker.getColumnValue(1))//嘉兴，原温州

我试过这样，还试过setValues，getValues显示已经是设置的值了，但是页面上不会变化 @rex-zsd

**Comment by rex-zsd** [comment]
`setValues` `setColumnValue`这两个api可以用来指定选中项没问题。

**Comment by chinaguopeng** [comment]
指定完需要setData吗，应该怎么写，也没有例子，卡这里俩天了，我知道指定选中项没问题，但是页面没改变啊
![捕获](https://user-images.githubusercontent.com/25874614/66695195-154aae00-ecf1-11e9-93bb-ad8fac7fb20c.PNG)

**Comment by lshz0088** [comment]
> 指定完需要setData吗，应该怎么写，也没有例子，卡这里俩天了，我知道指定选中项没问题，但是页面没改变啊
> ![捕获](https://user-images.githubusercontent.com/25874614/66695195-154aae00-ecf1-11e9-93bb-ad8fac7fb20c.PNG)

请问解决了么，我也是回显有问题
