### ISSUE TITLE
[Bug Report] vant tab组件安卓小程序端出现bug

### ISSUE THREAD

**Issue by manongwuma** [youzan/vant-weapp#2144]
### 设备
安卓

### VantWeapp 版本
1.0.0-beta.1

### 基础库版本
荣耀20

### 如果是 UI 问题，截图链接（多图回车分隔）

![截图](https://sm.ms/image/fXg2QVLxbS1pD6u)

### 描述问题
tab多个选项时，安卓端出现横向滚动条，影响美观！

**Comment by rex-zsd** [comment]
#2285 已优化
v1.0.0-beta.3已经发布
