### ISSUE TITLE
[Feature Request] vant-weapp能否完全兼容uniapp？

### ISSUE THREAD

**Issue by qinkaiyuan** [youzan/vant-weapp#2147]
### 这个功能解决了什么问题
在uniapp上使用vant

### 建议的API是什么样的
完全通vant

**Comment by rex-zsd** [comment]
有什么不兼容的地方可以反馈，这样笼统的issue没有意义。

**Comment by qinkaiyuan** [comment]
> 有什么不兼容的地方可以反馈，这样笼统的issue没有意义。

使用前咨询，我试了下h5端可以使用，uniapp无法使用，就来问一下，也没有具体尝试，我刚用，所以我就先问一下是不是可以完全兼容，如果可以的话我就用，不可以我就不用了，照你的回答来说，vant-weapp理论上是可以完全兼容uniapp的到 小程序，app，h5端的是吧

**Comment by rex-zsd** [comment]
如果希望借助uni-app实现一套代码跨端运行，vant-weapp是不支持的。
vant-weapp用原生小程序语法写成，完全不支持非小程序平台的。

**Comment by qinkaiyuan** [comment]
> 如果希望借助uni-app实现一套代码跨端运行，vant-weapp是不支持的。
> vant-weapp用原生小程序语法写成，完全不支持非小程序平台的。

谢谢，明白了
