### ISSUE TITLE
[Bug Report] 自定义按钮不能设置背景颜色

### ISSUE THREAD

**Issue by liujuesi** [youzan/vant-weapp#2150]
### 设备
phone

### VantWeapp 版本
1.0.0-beta.0

### 基础库版本
2.8.0

### 请提供核心代码片段链接
https://youzan.github.io/vant-weapp/#/button#dai-ma-yan-shi

### 描述问题
自定义按钮不能设置背景颜色，前端代码 <van-button color="#7232dd">单色按钮</van-button>, 版本 "dependencies": {"vant-weapp": "^1.0.0-beta.0"}

**Comment by rex-zsd** [comment]
没看懂，van-button没提供背景色的props呀，你是怎么修改的？

**Comment by liujuesi** [comment]
https://youzan.github.io/vant-weapp/#/button#dai-ma-yan-shi
这里的，

参数 | 说明 | 类型 | 默认值 | 版本
-- | -- | -- | -- | --
id | 标识符 | string | - | -
type | 按钮类型，可选值为 primary info warning danger | string | default | -
size | 按钮尺寸，可选值为 normal large small mini | string | normal | -
color | 按钮颜色，支持传入linear-gradient渐变色 | string | - | 1.0.0

**Comment by rex-zsd** [comment]
代码怎么写的？

**Comment by liujuesi** [comment]
![image](https://user-images.githubusercontent.com/45506410/66728497-e579e280-ee77-11e9-808c-dbd0675c6f50.png)
![image](https://user-images.githubusercontent.com/45506410/66728506-f3c7fe80-ee77-11e9-80ac-0017029fe3ee.png)

**Comment by liujuesi** [comment]
直接复制demo的代码都不行

**Comment by rex-zsd** [comment]
![image](https://user-images.githubusercontent.com/8767877/66728625-91bbc900-ee78-11e9-960e-c93b8c22ebe1.png)
demo本身是没问题的，可能是非代码原因，试试看重新编译，关闭开发者工具再打开？

**Comment by liujuesi** [comment]
试过了，没办法解决这个问题，你那边demo有试过在自己的项目测试过这个参数了吗，可以传个其他颜色看下是否能正常使用

**Comment by rex-zsd** [comment]
在检查下版本这些有没有问题吧，demo是没问题的。

**Comment by liujuesi** [comment]
版本也是最新那个了，看了button文件下的源码，也和git上面的一样

**Comment by liujuesi** [comment]
小问题，我这边弄不了就不管他了，自己写个样式改一下就行
