### ISSUE TITLE
vant-tabs 动态绑定active报错

### ISSUE THREAD

**Issue by bellawei** [youzan/vant-weapp#2152]
**使用vant-tab的时候报错**
index.js:153 Uncaught (in promise) TypeError: Cannot read property 'width' of undefined
![微信图片_20191014145717.png](https://i.loli.net/2019/10/14/veUmaNrjOZo2Wix.png)

局部业务代码如下
![微信图片_20191014145725.png](https://i.loli.net/2019/10/14/THN14fr37YEDoPX.png)
发现去掉active="{{active}}" 就不报错。
========================================
翻开源码。。。
![微信图片_20191014145731.png](https://i.loli.net/2019/10/14/BdlIr31pLRj4oQc.png)
this.data.active由于我传入的是String,所以this.currentName也为String类型，与item.computedName类型不符，===不成立。

再次翻看文档，active是支持 String|Number的。于是手动将===改为==。问题解决

**Comment by fangxu864** [comment]
我改了下面三个地方，就可以用了，不知道为什么
![image.png](https://i.loli.net/2019/10/14/ygmKojEZI8H52Si.png)

**Comment by bellawei** [comment]
> 我改了下面三个地方，就可以用了，不知道为什么
> ![image.png](https://camo.githubusercontent.com/abb6d69c3a0a38a0160f4799fe3a07613c185cd7/68747470733a2f2f692e6c6f6c692e6e65742f323031392f31302f31342f79676d4b6f6a455a493848353253692e706e67)

**Comment by bellawei** [comment]
> > 我改了下面三个地方，就可以用了，不知道为什么
> > ![image.png](https://camo.githubusercontent.com/abb6d69c3a0a38a0160f4799fe3a07613c185cd7/68747470733a2f2f692e6c6f6c692e6e65742f323031392f31302f31342f79676d4b6f6a455a493848353253692e706e67)

直接将===改成==应该就好了
