### ISSUE TITLE
[Feature Request] 如何方便得让整体字号变大一点？

### ISSUE THREAD

**Issue by Lynn-cc** [youzan/vant-weapp#2154]
### 这个功能解决了什么问题
vant的默认字号设计比较小，在大屏幕手机上体验不太好。提供的主题vars变量修改不能覆盖大部分的字号场景

### 建议的API是什么样的
开发者比较方便得使用大号的设计，能试用所有组件。

**Comment by chenjiahan** [comment]
我们会持续完善 vars 变量，在 1.0 正式版中 vars 基本上可以覆盖所有组件
