### ISSUE TITLE
[Bug Report] 在小程序中引入van-swipe-cell滑动单元格无效

### ISSUE THREAD

**Issue by sjy1234** [youzan/vant-weapp#2155]
### 设备
微信开发者工具

### VantWeapp 版本
1.0.0-beta.1

### 基础库版本
2.8.3

### 请提供核心代码片段链接
https://youzan.github.io/vant-issue-generater/dist/#/zh-CN?repo=VantWeapp

### 描述问题
  <van-cell-group>
    <van-cell title="单元格" value="内容" />
  </van-cell-group>
  <view slot="right">删除</view>
</van-swipe-cell>

json文件
{
  "usingComponents": {
    "van-button": "../../npm/vant-weapp/button",
    "van-field": "../../npm/vant-weapp/field",
    "van-swipe-cell": "../../npm/vant-weapp/swipe-cell"
  }
}

不报错也不出来效果

**Comment by rex-zsd** [comment]
估计还是引用路径的问题，再仔细看看吧。

**Comment by sjy1234** [comment]
确定过不是路径问题，同样的页面引用其他组件就没问题，就这个不显示。查看元素后也渲染上了，就是高度为0，所以不显示。

**Comment by luo2096** [comment]
> 
> 
> 确定过不是路径问题，同样的页面引用其他组件就没问题，就这个不显示。查看元素后也渲染上了，就是高度为0，所以不显示。

我也是这个问题，就是高度为0不显示

**Comment by rex-zsd** [comment]
可以把代码贴一下，这样反馈解决不了问题的…………

**Comment by sjy1234** [comment]
github代码链接https://github.com/sjy1234/demo  你拉取一下代码试试


------------------ 原始邮件 ------------------
发件人: "rex"<notifications@github.com>;
发送时间: 2019年10月15日(星期二) 上午10:54
收件人: "youzan/vant-weapp"<vant-weapp@noreply.github.com>;
抄送: "树下的猫"<1321447500@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [youzan/vant-weapp] [Bug Report] 在小程序中引入van-swipe-cell滑动单元格无效 (#2155)




可以把代码贴一下，这样反馈解决不了问题的…………

**Comment by rex-zsd** [comment]
@sjy1234 van-cell没引入，中间没内容所以没高度

**Comment by sjy1234** [comment]
兄弟谢谢了，确实是这个问题。但是现在单元格出来了，样式没生效，是什么情况？
如果你是vant内部人员的话，我个人觉得有必要在文档内注明一下，给个提示也好啊，最后还是说声谢谢喽！

------------------ 原始邮件 ------------------
发件人: "rex"<notifications@github.com>;
发送时间: 2019年10月15日(星期二) 下午2:48
收件人: "youzan/vant-weapp"<vant-weapp@noreply.github.com>;
抄送: "树下的猫"<1321447500@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [youzan/vant-weapp] [Bug Report] 在小程序中引入van-swipe-cell滑动单元格无效 (#2155)




@sjy1234 van-cell没引入，中间没内容所以没高度

**Comment by rex-zsd** [comment]
左右slot的样式是自己写的，本身没有任何样式。
组件要引入才会生效，这个没有疑问吧？
初次尝试可以clone一下项目，在example中发挥。

**Comment by sjy1234** [comment]
那你这样说就明白了，之前一直在用微信官方做的样式库，确实初次尝试vant-weAPP仍需多加练习。
最后还是感谢一下你： 辛苦辛苦




------------------ 原始邮件 ------------------
发件人: "rex"<notifications@github.com>;
发送时间: 2019年10月15日(星期二) 下午3:17
收件人: "youzan/vant-weapp"<vant-weapp@noreply.github.com>;
抄送: "树下的猫"<1321447500@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [youzan/vant-weapp] [Bug Report] 在小程序中引入van-swipe-cell滑动单元格无效 (#2155)




左右slot的样式是自己写的，本身没有任何样式。
 组件要引入才会生效，这个没有疑问吧？
 初次尝试可以clone一下项目，在example中发挥。
