### ISSUE TITLE
动态van-tabs设置默认选中

### ISSUE THREAD

**Issue by Angle-bo** [youzan/vant-weapp#2157]
v-for循环出来的van-tabs，通过代码改变v-model绑定的name来实现选中效果，没有效果，是bug还是？

**Comment by Angle-bo** [comment]
数据类型不一致导致的问题。

**Comment by cherish1260** [comment]
请问你那边是怎么数据类型不一致了，我现在每个tab没有设置name，更改active值也是无法更改tabs的选中状态的

**Comment by Angle-bo** [comment]
0 '0'

**Comment by cherish1260** [comment]
你那版本使用的是1.0.0-beta-2吗？我这边1.0.0-beta-2、1.0.0-beta-1这两个版本好像都不对，不是类型的问题

**Comment by Angle-bo** [comment]
没，我用的不是小程序组件，用的是web组件

**Comment by littleBelle** [comment]
我用v-mode设置active=9，选中的标签页还是第0个
