### ISSUE TITLE
[Bug Report] 文档网站链接问题

### ISSUE THREAD

**Issue by vancenx** [youzan/vant-weapp#2161]
### 设备
windows

### VantWeapp 版本
1.0.0-beta.2

### 基础库版本
0.0.0

### 如果是 UI 问题，截图链接（多图回车分隔）

![截图](https://i.loli.net/2019/10/16/mcXV1p9uYH2KWrw.png)
![image.png](https://i.loli.net/2019/10/16/379YLVMqOgbK6Gx.png)

### 请提供核心代码片段链接
https://youzan.github.io/vant-weapp/#/tabbar

### 描述问题
https://youzan.github.io/vant-weapp/#/tabbar 内  [Icon 组件](https://youzan.github.io/#/icon) 页面未配置

**Comment by chenjiahan** [comment]
感谢反馈，后续会修正下链接
