### ISSUE TITLE
微信小程序原生 组件调用vant-dialog时,before-close属性怎么写

### ISSUE THREAD

**Issue by 741912526** [youzan/vant-weapp#2163]
微信小程序原生 组件调用vant-dialog时,before-close属性怎么写
`//wxml
<van-dialog
      use-slot
      show="{{ show }}"
      show-cancel-button
      before-close="{{beforeclose}}"
    >
    </van-dialog>`
//js
beforeclose(action, done) {} 
该方法写在哪里？

**Comment by chenjiahan** [comment]
直接写在 Page 下即可

```js
Page({
  beforeclose() {

  }
});
```

**Comment by 741912526** [comment]
> 直接写在 Page 下即可
> 
> ```js
> Page({
>   beforeclose() {
> 
>   }
> });
> ```
写在下面都不触发

**Comment by chenjiahan** [comment]
更正下：vant-weapp 并没有提供 before-close 属性，你可以再看一遍文档确认下
