### ISSUE TITLE
[Bug Report]van-steps 使用未激活图标会移位

### ISSUE THREAD

**Issue by whoopsHzh** [youzan/vant-weapp#2165]
小程序中
html
![image](https://user-images.githubusercontent.com/32846446/66975284-a1354f00-f0d0-11e9-8062-f6d1b7349efd.png)
出来的效果
![image](https://user-images.githubusercontent.com/32846446/66975294-abefe400-f0d0-11e9-80ab-6203779fcacf.png)

**Comment by chenjiahan** [comment]
下个 beta 版本会修复此问题
