### ISSUE TITLE
button组件不支持form-type 吗

### ISSUE THREAD

**Issue by linhaibo147** [youzan/vant-weapp#2169]
### 这个功能解决了什么问题
button按扭有open-type解决了我的调取微信的授权功能，但没有form-type在一些表单提交还是得写原生的

### 建议的API是什么样的
van-button是否下个版本支待form-type

**Comment by rex-zsd** [comment]
小程序组件无法支持form-type，可以看下微信小程序的文档。

**Comment by changziyu** [comment]
也遇到这个问题，太难了^_^

**Comment by taoeer** [comment]
> 小程序组件无法支持form-type，可以看下微信小程序的文档。

小程序有这个属性的

**Comment by linhaibo147** [comment]
\(^o^)/~好的，问了这个问题我就查了微信文档了，才知道自定义组件不支持这种形式，谢谢您百忙之中回答了

**Comment by linhaibo147** [comment]
> 小程序组件无法支持form-type，可以看下微信小程序的文档。

（^ o ^）/〜好的，问了这个问题我就查了微信文档了，才知道自定义组件不支持这种形式，谢谢您百忙之中回答了
