### ISSUE TITLE
如何获取自定义导航栏的高度？

### ISSUE THREAD

**Issue by 358xiaoyihezemin** [youzan/vant-weapp#2172]
我使用自定义导航栏后  使用fixed 后     下面的页面元素会自动顶上来     我希望获取到自定义导航栏高度后设置一个margin-top

**Comment by 358xiaoyihezemin** [comment]
希望可以把自定义导航栏的高度暴露出来

**Comment by rex-zsd** [comment]
跟vant-weapp无关，获取组件高度的方法请自行查阅微信小程序文档。
