### ISSUE TITLE
mpvue 中使用Notify报未找到 van-notify 节点，请确认 selector 及 context 是否正确

### ISSUE THREAD

**Issue by oumaharuki** [youzan/vant-weapp#2174]
官方没有修复这个bug，其实就是在节点还没有初始化就获取了节点。
我去看了一下源码：
![image](https://user-images.githubusercontent.com/29711725/67155508-aa7a2200-f343-11e9-845d-ca92f175098e.png)

然后再看了官方文档，嗯，果然官方也很垃圾，不服可以来砍我，于是我改了一下传参

![image](https://user-images.githubusercontent.com/29711725/67155553-31c79580-f344-11e9-8a16-0f7738f95314.png)

**Comment by JakeLaoyu** [comment]
是不是在节点还没初始化就调用了 Notify。

如果觉得你写的好，可以提PR。

> [善良比重名更重要](https://github.com/lifesinger/blog/issues/227)

**Comment by oumaharuki** [comment]
直接像vue一样在节点绑定点击事件，方法里面写的就是如图的内容，你可以回去试，而且我看到了有一些人提到过这个东西，但都是没有解决。

**Comment by chenjiahan** [comment]
首先请确认下原生框架是否有这个问题，如果是 mpvue 框架下特有的问题，请到 mpvue 仓库下提问，感谢配合
