### ISSUE TITLE
[Bug Report] app.json 中配置 "style": "v2" 导致多个组件样式错乱

### ISSUE THREAD

**Issue by charescape** [youzan/vant-weapp#2178]
### 设备
IOS

### VantWeapp 版本
1.0.0-beta.2

### 基础库版本
2.8.3

### 请提供核心代码片段链接
https://developers.weixin.qq.com/miniprogram/dev/reference/configuration/app.html#style

### 描述问题
以下内容来自小程序开发文档：

> 微信客户端 7.0 开始，UI 界面进行了大改版。小程序也进行了基础组件的样式升级。app.json 中配置 "style": "v2"可表明启用新版的组件样式。

https://developers.weixin.qq.com/miniprogram/dev/reference/configuration/app.html#style

**Comment by chenjiahan** [comment]
参见 https://github.com/youzan/vant-weapp/issues/1937
