### ISSUE TITLE
[Bug Report] Popup组件内容区域的区块使用transform属性偏离被截断无法展示

### ISSUE THREAD

**Issue by HelTi** [youzan/vant-weapp#2185]
### 设备
ios、安卓

### VantWeapp 版本
1.0.0-beta.2

### 基础库版本
2.6.6

### 如果是 UI 问题，截图链接（多图回车分隔）

![截图](https://i.loli.net/2019/10/22/c3Fd7gZkTBlfoUs.png)

![截图](https://i.loli.net/2019/10/22/jFYi6bKk9hVqOta.png)

### 请提供核心代码片段链接
https://developers.weixin.qq.com/s/1bAIujmG7lcZ

### 描述问题
Popup组件内容区域的区块使用transform属性偏离被截断无法展示。
如块元素使用transform: translateY(-43%); Popup会隐藏区域外的内容。

**Comment by chenjiahan** [comment]
你可以通过外部样式类去修改这个属性

**Comment by HelTi** [comment]
> 你可以通过外部样式类去修改这个属性

是的，可以通过
```css
.van-popup {
    overflow: visible !important;
}
```
来解决，不过对于不知道的用户来说，的确给人带来了困扰，需要排查样式。

**Comment by chenjiahan** [comment]
移除这个属性，会导致原有的样式出现问题（比如弹窗内有长列表的情况），所以我们暂时不会移除，抱歉
