### ISSUE TITLE
vue-swipe

### ISSUE THREAD

**Issue by ywAlexyw** [youzan/vant-weapp#2188]
![image](https://user-images.githubusercontent.com/41054299/67355098-f538ab80-f588-11e9-8f55-eea9fd1f1505.png)

    <van-swipe :autoplay="3000">
      <van-swipe-item v-for="(image, index) in imageList" :key="index">
        <img v-lazy="image" style="height:100px; width:100%;" />
      </van-swipe-item>
    </van-swipe>

组件都引用了，但是图片都是竖着

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
