### ISSUE TITLE
[Bug Report] 表单组件输入速度快会持续不断的回退，尤其是纯英文键盘或调起数字键盘进行输入的时候

### ISSUE THREAD

**Issue by charescape** [youzan/vant-weapp#2189]
### 设备
IOS 12（iPhone 7）

### VantWeapp 版本
1.0.0-beta.2

### 基础库版本
2.8.3

### 如果是 UI 问题，截图链接（多图回车分隔）

![截图](https://i.loli.net/2019/10/23/uGU2zyqSw7QgxCe.png)

### 请提供核心代码片段链接
https://github.com/youzan/vant-weapp/blob/dev/packages/field/index.ts#L82-L88

### 描述问题
连续不断的setData导致出现性能问题，出现输入框闪动、回退，输入内容错乱的情况

**Comment by guangbi** [comment]
onInput(event) {
            clearTimeout(this.timer)
            var self = this;
            self.timer = setTimeout(function () {
                const { value = '' } = event.detail || {};
                self.setData({ value }, () => {
                    self.emitChange(value);
                });
            },50);
        }

输入事件中增加一个定时器，可以解决这个问题

**Comment by CHANGSHAQI** [comment]
@charescape 我也遇到了这个问题,请问你怎么解决的

**Comment by basstk** [comment]
@guangbi 按照你的方法测试了,无效

**Comment by CHANGSHAQI** [comment]
@basstk 自己用input写一个吧,只能先这样了

**Comment by hujingyuki** [comment]
field使用过程中也发现了这个问题，真机上英文键盘疯狂输入必现，开发工具中不会，初步判断是field的oninput事件中setData异步导致的，望修复

**Comment by RedheatWei** [comment]
相同的问题,debug中发现

> Invoke event onInput in component: miniprogram_npm/@vant/weapp/field/index
![image](https://user-images.githubusercontent.com/13144369/74425744-279b4b00-4e8f-11ea-84df-2f0d272f42ad.png)
