### ISSUE TITLE
Vant Weapp中的折叠面板collapse van-collapse-item在使用时重复展开同一个

### ISSUE THREAD

**Issue by Pittsburgh7zhu** [youzan/vant-weapp#2200]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater?repo=VantWeapp

**Comment by Pittsburgh7zhu** [comment]
在开发者工具内测试是好的  但是真机调试就会有问题 !  问题描述:  当点击 第一项是展开面板两次

**Comment by rex-zsd** [comment]
issue格式不符合规范。
