### ISSUE TITLE
[Bug Report] gulp打包配置操作环境兼容性问题

### ISSUE THREAD

**Issue by wuxiuran** [youzan/vant-weapp#2201]
### 设备
window10

### VantWeapp 版本
1.0.0-beta.2

### 基础库版本
latest

### 请提供核心代码片段链接
https://gist.github.com/wuxiuran/f7dd0600b329c214c4ade86e36834560

### 描述问题
gulp 的  golb 机制分隔符永远是 / 字符 - 不区分操作系统 - 即便是在采用 \\ 作为分隔符的 Windows 操作系统中。在 glob 中，\\ 字符被保留作为转义符使用。避免使用 Node 的 path 类方法来创建 glob，例如 path.join。在 Windows 中，由于 Node 使用 \\ 作为路径分隔符，因此将会产生一个无效的 glob。还要避免使用 __dirname 和 __filename 全局变量，由于同样的原因，process.cwd() 方法也要避免使用。目前项目构建的部分功能比如监听文件的修改在window操作系统中因为匹配不到正确的路径而失效。
最后附上gulp文档地址 https://www.gulpjs.com.cn/docs/getting-started/explaining-globs/

**Comment by luckymore** [comment]
> process.cwd() 方法也要避免使用
亲，那建议怎么用呢？

**Comment by landluck** [comment]
issue 时间太久了，如还有问题，可以提供代码片段后重新创建 issue
