### ISSUE TITLE
picker 和 datapicker 同时使用会导致组件失效

### ISSUE THREAD

**Issue by NineSu** [youzan/vant-weapp#2204]
![image](https://user-images.githubusercontent.com/27474230/67555721-712b2300-f744-11e9-9995-612ab24576aa.png)
同时使用两个组件的时候出现图中所示情况、
使用的是mpvue2.0 vant-weapp 1.0.0.beta2

**Comment by JakeLaoyu** [comment]
贴一下代码和是否有报错

**Comment by NineSu** [comment]
代码没有报错。我看代码显示空白是出现布局错乱。显示的很上面很上面
![image](https://user-images.githubusercontent.com/27474230/67566100-89f20380-f759-11e9-8ce8-d442cdd59f3f.png)
这个高度负的八百多。。刚刚试了一下没能重现。

**Comment by JakeLaoyu** [comment]
`没能复现` 是已经没问题了吗
