### ISSUE TITLE
加载中按钮图片icon图标不能居中不能

### ISSUE THREAD

**Issue by wangpeng00544** [youzan/vant-weapp#2208]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater?repo=VantWeapp

**Comment by rex-zsd** [comment]
跟ShadowDOM的原理有关，可以自己在根节点上加样式让内部居中。
