### ISSUE TITLE
我想问一下，如何去修改源码关于code的判断？

### ISSUE THREAD

**Issue by Fantastic-Chen** [youzan/vant-weapp#2209]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater?repo=VantWeapp
因为公司数据库中的地区的code码与参考文档中的code码不相同，所以我想修改一下对于code码的判断。

**Comment by rex-zsd** [comment]
这个应该修改不了，代码是按国家标准的省市县地区代码来处理的。
给你们内部的code码和地区码之间做个映射能不能行？
