### ISSUE TITLE
datetime-picker， time模式使用filter后选择结果不是filter后的结果

### ISSUE THREAD

**Issue by QYZX** [youzan/vant-weapp#2223]
问题出现在以下代码

https://github.com/youzan/vant-weapp/blob/3cbd24c35bd927eeac7b7b3f1bc15b9e3b0dbccd/dist/datetime-picker/index.js#L236

onChange时没有取filter后返回的数组作为数据源

**Comment by rex-zsd** [comment]
#2196 已修复
v1.0.0-beta.3版本已发布
