### ISSUE TITLE
[Bug Report] Notify文档使用message设置文本，但是实际是text，Notify设置type属性无效，如何设置都是默认的danger值

### ISSUE THREAD

**Issue by woleicom** [youzan/vant-weapp#2225]
### 设备
微信开发者工具

### VantWeapp 版本
0.5.22

### 基础库版本
0.5.22

### 请提供核心代码片段链接
https://gist.github.com/woleicom/feebbc61d0818faeab7c4b3fad833cd8

### 描述问题
1.Notify文档使用message设置文本，但是实际是text，
2.Notify设置type属性无效，如何设置都是默认的danger值

**Comment by JakeLaoyu** [comment]
选择对应版本的文档
