### ISSUE TITLE
tabbar组件，iphone 11 pro下无法正常显示。高度偏移

### ISSUE THREAD

**Issue by CodeZT** [youzan/vant-weapp#2238]
修改safe-area.js文件如下
`const iphoneNew = (/iPhone11/i.test(model) || /iPhone12/i.test(model)) && screenHeight === 812;`

添加tabbar.wxss代码如下
`.van-tabbar.van-tabbar--safe{height: 84px;}`

**Comment by chenjiahan** [comment]
重复 issue：https://github.com/youzan/vant-weapp/issues/2239
