### ISSUE TITLE
[Bug Report] tabbar 在iphone 11 pro下高度计算不对

### ISSUE THREAD

**Issue by CodeZT** [youzan/vant-weapp#2239]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

设备
iphone 11 pro

VantWeapp 版本
0.5.10

基础库版本
2.7.7

请提供核心代码片段链接
https://gist.github.com/

描述问题
tabbar 在iphone 11 pro下高度计算不对

safe-area.js const iphoneNew = (/iPhone11/i.test(model) || /iPhone(12,13)/i.test(model)) && screenHeight === 812;

tabbar.wxss .van-tabbar--safe{padding-bottom:34px;height: 84px}

**Comment by rex-zsd** [comment]
v1.0.0已经有用`env()`优化了安全区的实现，可以升级下看看。
