### ISSUE TITLE
请问下是否可以支持vant上面的sku规格功能呢，好期待！

### ISSUE THREAD

**Issue by xni220** [youzan/vant-weapp#2242]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater?repo=VantWeapp
请问下是否可以支持vant上面的sku规格功能呢，好期待！这个功能很好希望小程序端也能加上

**Comment by a1029382825** [comment]
同求，感觉vant上的那些业务组件真的很实用

**Comment by chenjiahan** [comment]
抱歉，暂时没有计划支持喔，我们优先开发基础组件
