### ISSUE TITLE
[Bug Report] Field placeholder twinkle.

### ISSUE THREAD

**Issue by xjh22222228** [youzan/vant-weapp#2245]
### 设备
IOS

### VantWeapp 版本
1.0.0-beta.0

### 基础库版本
2.9.0

### 如果是 UI 问题，截图链接（多图回车分隔）

![截图](https://ftp.bmp.ovh/imgs/2019/11/4039f75b6c1827dd.gif)

### 请提供核心代码片段链接
https://ftp.bmp.ovh/imgs/2019/11/4039f75b6c1827dd.gif

### 描述问题
```code
<van-dialog
  use-slot
  confirm-button-text="绑定"
  show="{{ dialogShow }}"
  show-cancel-button
  async-close
  bind:confirm="handleConfirmBind"
  bind:cancel="handleCancel"
>
  <van-field
    value="{{ inputValue }}"
    placeholder="请输入导购工号"
    border="{{ true }}"
    maxlength="{{ 100 }}"
    bind:change="handleInputChange"
  />
</van-dialog>
```

**Comment by rex-zsd** [comment]
可以把`van-dialog`的`transition`属性设为`fade`或`none`。
小程序input的`placeholder`部分是原生渲染的，在缩放动画渲染会有问题。
