### ISSUE TITLE
[Bug Report] notice-bar 显示closeable点击事件不是预期行为

### ISSUE THREAD

**Issue by mipawn** [youzan/vant-weapp#2246]
### 设备
编辑器，iPhone6

### VantWeapp 版本
1.0.0-beta.2

### 基础库版本
2.9.1

### 请提供核心代码片段链接
https://gist.github.com/dongbusi/f81c98b7e03fcd263994813041781377

### 描述问题
1.notice-bar 显示closeable点击关闭按钮时，本应该是直接关闭，但是现在会同时触发暴漏出的click事件，造成现在关闭的同时，会触发click事件。
2.文档的参数不全，比如url和opentype等。

**Comment by dongbusi** [comment]
![image](https://user-images.githubusercontent.com/39559813/68097306-4fbef980-fef1-11e9-874f-e5878c10ab70.png)
实测，将源文件bind改为catch可以

**Comment by dongbusi** [comment]
![image](https://user-images.githubusercontent.com/39559813/68097325-6f562200-fef1-11e9-9c88-2f441dcaf963.png)
实测将源文件的bind改为catch可以
