### ISSUE TITLE
小程序的倒计时 count-down组件的离开页面清除定时器在哪..？不知道是不是我代码的问题 使用了多个倒计时之后 页面就崩了

### ISSUE THREAD

**Issue by hgr007** [youzan/vant-weapp#2249]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater?repo=VantWeapp

**Comment by rex-zsd** [comment]
v1.0.0-beta2已经优化了定时器清除的逻辑，试下新版本看看？
