### ISSUE TITLE
[Bug Report] radio禁用后依然可以点击并切换

### ISSUE THREAD

**Issue by Chocomoon** [youzan/vant-weapp#2252]
### 设备
iPhone 6/7/8

### VantWeapp 版本
1.0.0-beta.2

### 基础库版本
2.9.1

### 请提供核心代码片段链接
https://youzan.github.io/vant-weapp/#/radio

### 描述问题
在 radio 和 cell 一起使用时，无论是对整个 radio-group 还是单个的 radio 设置 disabled，都会出现设置完之后，背景变化了，但是依然可以点击并切换。使用的就是文档里代码。请问就是这样设定的还是bug？

**Comment by rex-zsd** [comment]
radio与cell合用时，选中逻辑是在cell的click事件中处理的。
这里需要开发者自己处理，判断下该项是否可选中。
