### ISSUE TITLE
[Bug Report] swith的高度不是预期高度

### ISSUE THREAD

**Issue by mipawn** [youzan/vant-weapp#2254]
### 设备
编辑器，iPhone6

### VantWeapp 版本
1.0.0-beta.2

### 基础库版本
2.9.1

### 如果是 UI 问题，截图链接（多图回车分隔）

![image.png](https://i.loli.net/2019/11/05/yR491OZnfsPcDMV.png)

### 请提供核心代码片段链接
https://gist.github.com/dongbusi/2f58902cc24d5262a51fc9ec189fe2d9

### 描述问题
switch的高度在用属性size设置大小后，switch实际高度比设置的要大一点，影响居中，实测加入 flex可以解决问题
![image.png](https://i.loli.net/2019/11/05/VmhEuGXdKnDYO35.png)

**Comment by rex-zsd** [comment]
可以自己加一下class控制一下哈。
