### ISSUE TITLE
[Bug Report] 安卓机型下vant-search的placeholder不显示问题

### ISSUE THREAD

**Issue by WXQ2017** [youzan/vant-weapp#2256]
### 设备
MEIXU 16 X

### VantWeapp 版本
1.0.0-beta.2

### 基础库版本
2.6.6

### 如果是 UI 问题，截图链接（多图回车分隔）

![截图](https://i.loli.net/2019/11/06/5zPfuISoUCOnBA9.png)

![截图](https://i.loli.net/2019/11/06/kqBSeugWvXAQaPN.png)

### 请提供核心代码片段链接
https://sm.ms/image/xfhBG59CHNcoFnM

### 描述问题
默认情况下placeholder会显示出来 ， 但是输入内容后 ，再次按键盘的删除按钮清空input中的内容，清空完内容以后placeholder未显示出来。
代码上传没网站， 就将就一下在图片里面看看哈QAQ

**Comment by rex-zsd** [comment]
可能是输入法的问题，在删除时没有清除所有内容。
可以看看在demo小程序中有没有这个问题。
