### ISSUE TITLE
按钮设置大小结果只有字体变小了

### ISSUE THREAD

**Issue by SomeOneNoBrain** [youzan/vant-weapp#2259]
![1573029554(1)](https://user-images.githubusercontent.com/34363060/68282112-feab3300-00b3-11ea-891f-c978960dc898.jpg)

**Comment by chenjiahan** [comment]
参见 https://github.com/youzan/vant-weapp/issues/1937

**Comment by SomeOneNoBrain** [comment]
> 参见 #1937
你的意思是不设置，还是调整成V1?编译的时候直接提示appJSON["style"] 字段需为 v2，这个怎么整？

**Comment by chenjiahan** [comment]
删除 style 字段
