### ISSUE TITLE
[Bug Report] vant env 问题

### ISSUE THREAD

**Issue by wsafight** [youzan/vant-weapp#2264]
### 设备
iphonex

### VantWeapp 版本
1.0.0-beta.2

### 基础库版本
2.9.2

### 请提供核心代码片段链接
https://gist.github.com/wsafight/5d1c3c91e29abb9fdb72ef438d11b09e

### 描述问题
.van-popup--safe{padding-bottom: env(safe-area-inset-bottom)}
无法在项目中实际生效,是否提供备用数据
不了解 env,请问 safe-area-inset-top 是否能根据 移动端不同而适应不同？

**Comment by chengxiansheng** [comment]
这个咋解决的；安全距离没生效

**Comment by wsafight** [comment]
安全距离是 由浏览器设置的，不要去看小程序模拟器，小程序模拟器没有设置。（当然，在 beta2 版本因为    "navigationStyle": "custom"  popup 无法设置安全距离之外的东西，所以我没有升级）。你可以尝试用真实手机试一试。

**Comment by chengxiansheng** [comment]
> 安全距离是 由浏览器设置的，不要去看小程序模拟器，小程序模拟器没有设置。（当然，在 beta2 版本因为 "navigationStyle": "custom" popup 无法设置安全距离之外的东西，所以我没有升级）。你可以尝试用真实手机试一试。

发现新版移除 import { safeArea } from '../mixins/safe-area'; 之后；感觉就失效了。

**Comment by wsafight** [comment]
我记得我是因为测试真实手机，确实由安全距离，才关闭的 issue。

**Comment by rex-zsd** [comment]
开发者工具没有设置viewport，所以不会生效
iphone真机上应该是ok的

**Comment by chengxiansheng** [comment]
> 开发者工具没有设置viewport，所以不会生效
> iphone真机上应该是ok的

大佬；安卓呢？比如华为mate20 pro

**Comment by rex-zsd** [comment]
safe-area其实是iOS特有的概念，安卓没有的，所以安卓中没有全面屏的适配。
当然NavBar这类的组件是根据顶部状态栏高度来的，还是会有刘海屏适配的。

**Comment by rex-zsd** [comment]
https://developers.weixin.qq.com/community/develop/doc/000e8a022084e046c82830e3c51800
搜了一下开发者社区关于模拟器不支持safe-area的反馈，也是有点哈哈哈 😄

**Comment by chengxiansheng** [comment]
> safe-area其实是iOS特有的概念，安卓没有的，所以安卓中没有全面屏的适配。
> 当然NavBar这类的组件是根据顶部状态栏高度来的，还是会有刘海屏适配的。

当小程序设置自定义导航栏；安卓肯定也需要根据状态栏来适配吧；目前华为的mate20 pro 就是齐刘海全面曲屏。  所以导致notify 提示中间被挡住了

**Comment by rex-zsd** [comment]
嗯，notify用safe-area适配会有点问题，可以再提个issue，我们做下适配。

**Comment by chengxiansheng** [comment]
> 嗯，notify用safe-area适配会有点问题，可以再提个issue，我们做下适配。

好的

**Comment by chengxiansheng** [comment]
> 嗯，notify用safe-area适配会有点问题，可以再提个issue，我们做下适配。

https://github.com/youzan/vant-weapp/issues/2372
