### ISSUE TITLE
[Feature Request] swipe-cell 禁止向右滑动

### ISSUE THREAD

**Issue by robotgoto** [youzan/vant-weapp#2267]
### 这个功能解决了什么问题
建议新增一个禁止向右滑动，大部分场景下不需要左边的内容。

### 建议的API是什么样的
建议新增一个禁止向右滑动，大部分场景下不需要左边的内容。

**Comment by rex-zsd** [comment]
目前`left-width`不设或者设`0`还是可以拖动的，可以把`left-width`设成`1`，可以达成类似的效果。
