### ISSUE TITLE
[Bug Report] van-button 不传参

### ISSUE THREAD

**Issue by Codes-Breaker** [youzan/vant-weapp#2268]
### 设备
MacOS

### VantWeapp 版本
0.5.23

### 基础库版本
最新

### 请提供核心代码片段链接
https://gist.github.com/Codes-Breaker/3548e3d60efd1e612812db0c52d00488

### 描述问题
用了open-type="share"就传不了ID或者dataset

**Comment by rex-zsd** [comment]
`onShareAppMessage`事件返回的target是van-button内部触发share事件的button。
所以id、data-*这些参数是不会有的，暂时也没发传递。
可以考虑换种取参的方式。

**Comment by FuDesign2008** [comment]
> `onShareAppMessage`事件返回的target是van-button内部触发share事件的button。
> 所以id、data-*这些参数是不会有的，暂时也没发传递。
> 可以考虑换种取参的方式。

如果一个页面有多个`vant-button` 设置 `open-type="share"` ，那么在 `onShareAppMessage` 上该如何区分呢？

**Comment by FuDesign2008** [comment]
> ### 设备
> MacOS
> 
> ### VantWeapp 版本
> 0.5.23
> 
> ### 基础库版本
> 最新
> 
> ### 请提供核心代码片段链接
> https://gist.github.com/Codes-Breaker/3548e3d60efd1e612812db0c52d00488
> 
> ### 描述问题
> 用了open-type="share"就传不了ID或者dataset

请问一下 @Codes-Breaker  ，你是如何绕过这个问题的？
