### ISSUE TITLE
van-popup组件使用自定义图标，如何给图标添加点击事件，不是关闭弹出层。

### ISSUE THREAD

**Issue by tonyhelloworld** [youzan/vant-weapp#2270]
请问大佬。
`<van-popup
      v-model="shoppingShow"
      round
      position="bottom"
      :style="{ height: '40%' }"
      close-icon="delete"
      close-icon-position="top-right"
      closeable
      safe-area-inset-bottom
      @click="deleteShopping"
    >
    </van-popup>`
此组件如何添加关闭图标上的事件。我不希望他只是关闭弹出层。

**Comment by rex-zsd** [comment]
vant的问题可以去vant下提issue咨询哈，这里是vant-weapp小程序组件库
https://github.com/youzan/vant/issues

**Comment by tonyhelloworld** [comment]
> vant的问题可以去vant下提issue咨询哈，这里是vant-weapp小程序组件库
> https://github.com/youzan/vant/issues
