### ISSUE TITLE
[Bug Report] panel内slot无效

### ISSUE THREAD

**Issue by Pidbid** [youzan/vant-weapp#2272]
### 设备
Windows10 Android9(xiaomi mix 2)

### VantWeapp 版本
0.5.23

### 基础库版本
2.9.2

### 如果是 UI 问题，截图链接（多图回车分隔）

![截图](https://i.loli.net/2019/11/08/CthGHuMOZ7zoV3b.png)

### 请提供核心代码片段链接
https://gist.github.com/Pidbid/e7db8643622aac3a221ad7ec6afbea8c

### 描述问题
未使用npm方式，直接引入文件，在panel下plot不生效，详情见代码和截图。

**Comment by rex-zsd** [comment]
demo小程序是没问题的，看下是不是代码引入什么的问题？

**Comment by rex-zsd** [comment]
看起来很多样式都没生效，应该还是引入的问题。

**Comment by kcunitary** [comment]
遇到了相同的问题，van-panel__content这条属性找不到对应的样式，导致下面正文渲染全部失败了

**Comment by rex-zsd** [comment]
如果app.json里面配置了`style: "v2"`的，需要去除。

**Comment by kcunitary** [comment]
> 
> 
> 如果app.json里面配置了`style: "v2"`的，需要去除。

开了个新项目试了，没有成功。

**Comment by lanrain** [comment]
遇到同样的问题，使用的是vant1.2.1，app.json中已经去除掉了style: "v2"

**Comment by gm-fire** [comment]
遇到同样的问题，使用的是vant1.3.0，npm安装，app.json中已经去除掉了style: "v2"

**Comment by gm-fire** [comment]
自行添加对应的样式类就好了
`<van-panel title="标题" desc="描述信息" status="状态" use-footer-slot>
      <view class="content">内容</view>
      <view slot="footer" class="footer">
        <van-button size="small">按钮</van-button>
        <van-button size="small" type="danger">按钮</van-button>
      </view>
    </van-panel>`

`.content {
  padding: 20px;
  font-size: 16px;
}

.footer {
  text-align: right;
}
`
