### ISSUE TITLE
field点击弹出popup，里面的内容是单列picker，小程序在6s上测试，先弹出键盘再弹出popup，且picker无法选择的问题

### ISSUE THREAD

**Issue by StudyMonkey** [youzan/vant-weapp#2273]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater?repo=VantWeapp
如题：
field点击弹出popup，里面的内容是单列picker，小程序在6s上测试，先弹出键盘再弹出popup，且picker无法选择，双列picker也无法选择，滚动之后popup消失了

**Comment by rex-zsd** [comment]
点击field弹出键盘是小程序默认操作吧，有什么疑问？
