### ISSUE TITLE
微信小程序 van-filed标签 设置type=“textarea”属性后 苹果显示不正常

### ISSUE THREAD

**Issue by cwz346852114** [youzan/vant-weapp#2276]
placeholder 这个占位符属性 van-filed标签设置为textarea属性后 
苹果输入的时候 placeholder和输入的内容会同时显示   只要是textarea属性的标签改为微信小程序自带的input标签后就显示正常了   排坑

**Comment by rex-zsd** [comment]
`type=“textarea”`时使用的是原生的textarea组件，这个是微信的问题，暂时无解，可以用普通的`type=text`……
