### ISSUE TITLE
tree-select问题

### ISSUE THREAD

**Issue by liusichang** [youzan/vant-weapp#2277]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater?repo=VantWeapp

**Comment by liusichang** [comment]
<van-tree-select items="{{ items }}" main-active-index="{{ mainActiveIndex }}" active-id="{{ activeId }}" bind:click-nav="onClickNav" bind:click-item="onClickItem">
  <image slot="content" src="../../../images/qjrs.jpg" />
<van-tree-select />
使用这段代码的时候会报错

**Comment by rex-zsd** [comment]
重复提交
#2278
