### ISSUE TITLE
[Bug Report] Tree-select组件问题

### ISSUE THREAD

**Issue by liusichang** [youzan/vant-weapp#2278]
### 设备
小程序工具

### VantWeapp 版本
1.0.0-beta.2

### 基础库版本
不晓得

### 请提供核心代码片段链接
https://youzan.github.io/vant-issue-generater/dist/#/zh-CN?repo=VantWeapp

### 描述问题
<van-tree-select items="{{ items }}" main-active-index="{{ mainActiveIndex }}" active-id="{{ activeId }}" bind:click-nav="onClickNav" bind:click-item="onClickItem">
  <image slot="content" src="../../../images/qjrs.jpg" />
<van-tree-select />
使用这段代码的时候会报错

**Comment by rex-zsd** [comment]
图片没有传上来…………
