### ISSUE TITLE
[Bug Report] Layout组件中，如何获得bind:click事件？

### ISSUE THREAD

**Issue by lbs2016** [youzan/vant-weapp#2279]
### 设备
微信小程序

### VantWeapp 版本
0.5.23

### 基础库版本
2.8.2

### 请提供核心代码片段链接
http://no.show.com/

### 描述问题
Layout组件中，如何获得bind:click事件？

**Comment by rex-zsd** [comment]
用原生的`bindtap`事件就可以了。

**Comment by lbs2016** [comment]
收到，肥肠感谢！！！！！！！！！！！！！
