### ISSUE TITLE
回调函数怎么用 confirm   change  cancel

### ISSUE THREAD

**Issue by qwerlh** [youzan/vant-weapp#2282]
<van-area area-list="{{ areaList }}" value="110101" cancel="shut"
  change = "onChange" confirm="onConfirm" />

这三个回调函数怎么用？

**Comment by rex-zsd** [comment]
Issue不符合格式，先关闭了。

**Comment by qwerlh** [comment]
&nbsp; 哪里不符合格式 ？&nbsp; &nbsp;这几个回调函数 我调用不成功&nbsp; 请问还需要配置什么嘛 官方文档上并没有给出具体案例&nbsp; &nbsp; 现在只能选择&nbsp; 不能取消 和 确定&nbsp;&nbsp;






------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"rex"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月12日(星期二) 下午2:24
收件人:&nbsp;"youzan/vant-weapp"<vant-weapp@noreply.github.com&gt;;
抄送:&nbsp;"凌乱。"<1979962112@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [youzan/vant-weapp] 回调函数怎么用 confirm   change  cancel (#2282)




Issue不符合格式，先关闭了。
