### ISSUE TITLE
[Bug Report] van-field获取光标内容自动提高

### ISSUE THREAD

**Issue by cangyu1993** [youzan/vant-weapp#2283]
### 设备
黑鲨2pro

### VantWeapp 版本
0.5.23

### 基础库版本
2.93

### 请提供核心代码片段链接
暂无

### 描述问题
点击获取焦点后内容闪烁，位置上移一段距离

**Comment by cangyu1993** [comment]
就是闪烁加粗位置变高

**Comment by rex-zsd** [comment]
小程序的input是原生组件，聚焦时闪烁加粗都是正常现象。

**Comment by cangyu1993** [comment]
好久没开发小程序了，突然开发项目遇到的bug，搞了半天是它自己的bug，不好意思打扰了
