### ISSUE TITLE
安装完毕，运行报错

### ISSUE THREAD

**Issue by zhouchunmei** [youzan/vant-weapp#2284]
ERROR in E:/myProjects/mini-market-h5/resources/node_modules/vant/types/notify.d.ts
37:5 Subsequent property declarations must have the same type.  Property '$notify' must be of type 'ElNotification', but here has type 'Notify'.
     declare module 'vue/types/vue' {
    interface Vue {
 |     $notify: Notify
       |     ^
    |   }
    | }

**Comment by rex-zsd** [comment]
找错地方了，你这是vant，不是vant-weapp。
