### ISSUE TITLE
vant-weapp 文档挂了

### ISSUE THREAD

**Issue by okxiaoliang4** [youzan/vant-weapp#2286]
vant-weapp 文档挂了
https://youzan.github.io/vant-weapp/

![image](https://user-images.githubusercontent.com/22525904/68649595-08261680-055e-11ea-8cb2-01a4c3a57d7f.png)

**Comment by rex-zsd** [comment]
恢复了，刚才文档发布有些问题。

**Comment by okxiaoliang4** [comment]
好的,可以了
