### ISSUE TITLE
[Bug Report] 使用npm下载库之后，van-image组件缺失

### ISSUE THREAD

**Issue by zhang-zedong** [youzan/vant-weapp#2289]
### 设备
mac

### VantWeapp 版本
1.0.0-beta.3

### 基础库版本
无

### 请提供核心代码片段链接
http://test.no

### 描述问题
使用npm下载库之后，van-image组件缺失

**Comment by rex-zsd** [comment]
看了一下是有的

**Comment by lxk0301** [comment]
我这边也是用的npm下载的。 image组件， 也是缺失，里面没有这个组件
