### ISSUE TITLE
[Feature Request] image组件的bindtap事件，希望换成阻止冒泡的catchtap

### ISSUE THREAD

**Issue by wubinsheng2017** [youzan/vant-weapp#2291]
### 这个功能解决了什么问题
一些包含图片的卡片组件，会有两种点击需求：
1.点击image图片，需要全屏预览图片
2.点击卡片，需要进入某些详情页面

### 建议的API是什么样的
bind:tap="onClick"
→ catchtap="onClick"

**Comment by rex-zsd** [comment]
自行在van-image上增加catchtap="noop"阻止一下冒泡就可以了，内部加不太合理，会有人需要事件冒泡的。
