### ISSUE TITLE
tab动画延迟

### ISSUE THREAD

**Issue by TonyLiuX** [youzan/vant-weapp#2292]
使用官网的example例子，tab组件点击选项卡时，底部的横线在iphone7 12.1.2上面出现延迟，但是扫描官网的小程序在相同的真机上面却没有这样的问题，改如何处理呢？？

**Comment by rex-zsd** [comment]
demo小程序ok应该是没问题的。
可以自查下代码，或者看下是不是开发者工具的问题。

**Comment by TonyLiuX** [comment]
原理是开发调试会很慢，预览就没有问题了
