### ISSUE TITLE
ImagePreview 预览 slots 无效问题

### ISSUE THREAD

**Issue by xxnhuanhuan** [youzan/vant-weapp#2296]
<van-image-preview
  v-model="show"
  :images="images"
  @change="onChange"
>
  <template v-slot:index>第{{ index }}页</template>
</van-image-preview>

框架已更新到最新版本@2.2.12, 图片预览的插槽功能使用无效。

**Comment by xxnhuanhuan** [comment]
补充：  <template v-slot:index>第{{ index }}页</template>  插槽Index 和cover s使用无效
 建议：ImagePreview弹出页面 新增一个关闭图标

**Comment by rex-zsd** [comment]
额 提错issue了，这里是vant-weapp，vant问题去vant的issue区反馈哈…………

**Comment by xxnhuanhuan** [comment]
不好意思&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "rex"<notifications@github.com&gt;; 
发送时间: 2019年11月14日(星期四) 中午11:17
收件人: "youzan/vant-weapp"<vant-weapp@noreply.github.com&gt;; 
抄送: "雪花飞扬"<445968809@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [youzan/vant-weapp] ImagePreview 预览 slots 无效问题 (#2296)




额 提错issue了，这里是vant-weapp，vant问题去vant的issue区反馈哈…………

**Comment by rex-zsd** [comment]
https://github.com/youzan/vant/issues
没事，指引一下
