### ISSUE TITLE
[Bug Report] Vant-weapp Field在基础库2.9.3事件失效

### ISSUE THREAD

**Issue by Hyejeongdd** [youzan/vant-weapp#2298]
### 设备
所有设备

### VantWeapp 版本
1.0.0-beta.3

### 基础库版本
2.9.3

### 请提供核心代码片段链接
https://gist.github.com/Hyejeongdd/61fd39d5fdaa8231700a6ca6b5951d88

### 描述问题
微信小程序2.9.3下Field组件的事件全部失效不会触发 2.9.1版本时候为正常

**Comment by Hyejeongdd** [comment]
1.0.0.beta.2同样出现问题

**Comment by hopex** [comment]
微信官方回复是基础库问题，原生组件也无法触发，等微信修复把

**Comment by rex-zsd** [comment]
https://developers.weixin.qq.com/community/develop/doc/00082a731689b07d0879aa95651400?highLine=2.9.3%2520%25E4%25BA%258B%25E4%25BB%25B6
微信的问题，目前只在开发者工具上出现，等微信修复吧。
