### ISSUE TITLE
[Bug Report] van-dropdown-item 的 value值

### ISSUE THREAD

**Issue by renmu123** [youzan/vant-weapp#2302]
### 设备
微信开发者工具

### VantWeapp 版本
1.0.0-beta.3

### 基础库版本
0.0.0

### 如果是 UI 问题，截图链接（多图回车分隔）

![截图](https://i.loli.net/2019/11/14/WEAsbcXuqPpxt14.png)

![截图](https://i.loli.net/2019/11/14/jAQDnfOXrSb64lp.png)

### 请提供核心代码片段链接
https://gist.github.com/renmu123/e17e7d9a811a8bebfdec2edb6497eb30.js

### 描述问题
不太清楚基础库版本是什么？

这个组件的value不会随着点击进行修改，我看文档上value值应该是“当前选中项的value”

核心代码如下：
```
 {{ ordedBy }}
  <van-dropdown-menu>
    <van-dropdown-item value="{{ ordedBy }}" options="{{ option1 }}" bind:change="change"/>
    <van-dropdown-item value="{{ reversed }}" options="{{ option2 }}" />
  </van-dropdown-menu>
  
  
    option1: [{
      text: '统帅',
      value: 'command'
    },
    {
      text: '武力',
      value: 'mforce'
    },
    {
      text: '智力',
      value: 'intelligence'
    },
    {
      text: '政治',
      value: 'politics'
    },
    {
      text: '魅力',
      value: 'charm'
    },
  ],
  option2: [{
      text: '正序',
      value: 1
    },
    {
      text: '倒叙',
      value: -1
    },
  ],
  ordedBy: 'mforce',
  reversed: 1
```

**Comment by rex-zsd** [comment]
value需要在change事件中自行修改，组件内部不会直接修改value，可以参考下文档。

**Comment by 358xiaoyihezemin** [comment]
> value需要在change事件中自行修改，组件内部不会直接修改value，可以参考下文档。

这个下拉框在部分苹果手机上点击下拉按钮后不显示下面的选项框    不知道你们有没有遇到这个问题
