### ISSUE TITLE
[Bug Report] 如何将vantweapp的px转成rpx

### ISSUE THREAD

**Issue by ganke** [youzan/vant-weapp#2306]
### 设备
全部

### VantWeapp 版本
1.0.0-beta.3

### 基础库版本
最新的

### 请提供核心代码片段链接
https://github.com/youzan/vant-weapp/issues/new

### 描述问题
在小程序里面直接使用vantweapp的时候，发现里面的单位全都是px单位的，有没有方法将px转成rpx的呢？

**Comment by rex-zsd** [comment]
这类的postcss插件有很多，在issue区搜索一下，同类issue里有推荐。
