### ISSUE TITLE
[Bug Report] van-tab中的scrollview中使用van-field，type使用textarea，在安卓机下点击无法获取焦点

### ISSUE THREAD

**Issue by huoyanwuzhe629** [youzan/vant-weapp#2307]
### 设备
安卓 meizu-16X，多个安卓机器均有问题

### VantWeapp 版本
1.0.0-beta.3

### 基础库版本
2.8.3

### 请提供核心代码片段链接
https://developers.weixin.qq.com/s/rruYXSm177c1

### 描述问题
van-tab中的scrollview中使用van-field，type使用textarea，在安卓机下点击无法获取焦点

**Comment by rex-zsd** [comment]
scroll-view中不要使用textarea，会出现很多问题。
官方开发者社区里有很多反馈，可以搜索看一下。
