### ISSUE TITLE
van-count-down 组件在IOS 12.4 下不兼容，显示0

### ISSUE THREAD

**Issue by yellowswf** [youzan/vant-weapp#2308]

**Comment by chenjiahan** [comment]
iOS 其他版本会有问题吗，能否看下是否有报错

**Comment by ylethe** [comment]
ios 11，13版本都没能复现，能否提供下使用方式？

**Comment by hddhyq** [comment]
该版本IOS中，检查下new Date()的时间格式传参，2018-08-30这样的格式在IOS不兼容，需要替换成2018/08/30格式 使用 str.replace(/-/g, '/')来替换掉。
