### ISSUE TITLE
[Bug Report] sticky组件包裹元素滚动速度快时吸顶后并不会回归至原来位置

### ISSUE THREAD

**Issue by one-pupil** [youzan/vant-weapp#2310]
### 设备
ios

### VantWeapp 版本
1.0.0-beta.3

### 基础库版本
2.9.1

### 如果是 UI 问题，截图链接（多图回车分隔）

![截图](https://i.loli.net/2019/11/20/4qOiRDz1o6Ajagt.png)
https://i.loli.net/2019/11/20/4qOiRDz1o6Ajagt.png

### 请提供核心代码片段链接
https://gist.github.com/one-pupil/9cc3af6e8a7e11ab4e96df7d56a848c8

### 描述问题
使用sticky组件包裹元素滚动速度快时吸顶后并不会回归至原来位置

**Comment by mircle** [comment]
我也遇到了

**Comment by rex-zsd** [comment]
图破了…………没明白是什么情况

**Comment by shimangdian** [comment]
能不能像betterScroll那样做个refresh的方法，可以更新或者重置一下sticky组件，他的错误应该类似
![image](https://user-images.githubusercontent.com/23499945/69119334-33b27f00-0ad1-11ea-8c08-3897b447fcb0.png)

**Comment by mircle** [comment]
官方实例 就有问题（工具上调试都没问题 真机上有问题） 
   andorid滑动  很多时候  上去下不来  （多滑几次  我的是2段式吸顶）

**Comment by one-pupil** [comment]
@rex-zsd 吸顶组件如图出现BUG，尝试着解决，好像是小程序`createIntersectionObserver`的api有问题？

**Comment by rex-zsd** [comment]
如果滚动很慢的情况下，intersectionObserver可能正好在临界点触发，这时候吸顶判断会有问题。
这个问题有点棘手，短期内可能无法解决。

**Comment by frei-x** [comment]
一样的遇到了 ,超出顶部再显示一个固定的

**Comment by rex-zsd** [comment]
目前的办法是为intersectionObserver多增加几个监控阈值，扩大触发范围，避免在边缘条件时触发。

**Comment by Fyerl** [comment]
intersectionObserver 低端机型滑快了实际都不会触发，考虑改为外部传入 scroll

**Comment by frei-x** [comment]
用position:sticky 实际测试兼容性还可以
