### ISSUE TITLE
怎么有些图标添加了显示不了啊？

### ISSUE THREAD

**Issue by LNyears** [youzan/vant-weapp#2316]
<van-tabbar-item icon="home-o">标签</van-tabbar-item>
比如这个图标就不能正常显示，只有一个方框显示占位一样，有部分就是这个样子，有部分图标能正常显示，请问我该怎么处理呢？

**Comment by rex-zsd** [comment]
可以在真机上看看，开发者工具有问题，有时会无法显示图标。
