### ISSUE TITLE
skeleton在npm包中未更新

### ISSUE THREAD

**Issue by WangQuanTang** [youzan/vant-weapp#2317]
skeleton更新后，小程序npm安装的包里还没有这个组件，请官方尽快更新！

skeleton：[https://youzan.github.io/vant-weapp/#/skeleton](url)

**Comment by rex-zsd** [comment]
实测是有的，是不是装错了版本…………

**Comment by WangQuanTang** [comment]
> 实测是有的，是不是装错了版本…………
根据官方文档执行：
# npm
npm i vant-weapp -S --production

开发者工具构建完npm后，在package.json看到vant版本是："vant-weapp": "^0.5.23"，在引入的包中查找，的确是没有skeleton！那就应该是npm i vant-weapp -S --production指向的默认版本不是v1.0.0-beta.3以及v1.0.0-beta.3以上的版本！

**Comment by rex-zsd** [comment]
npm i vant-weapp -S --production默认是不会安装beta版本的，需要手动指定版本到1.0.0-beta.4

**Comment by WangQuanTang** [comment]
> npm i vant-weapp -S --production默认是不会安装beta版本的，需要手动指定版本到1.0.0-beta.4

好的，感谢回复！
