### ISSUE TITLE
uploader 文件上传不了多张图片 设置multiple无效

### ISSUE THREAD

**Issue by xin10** [youzan/vant-weapp#2323]
设备
iphone 5

VantWeapp 版本
1.0.0-beta.3

基础库版本
2.9.1

描述问题
uploader 文件上传不了多张图片 设置multiple无效

**Comment by baochunsan** [comment]
我使用的也是，请问您那边解决了吗，有什么解决方案吗

**Comment by rex-zsd** [comment]
#2327 将在beta.4中修复

**Comment by CodeyunFei0905** [comment]
在安卓webview 环境下 多选还是不可以使用 只能上传单个图片或者文件
