### ISSUE TITLE
小程序中使用field，clearable属性失效，bind:change方法失效，版本

### ISSUE THREAD

**Issue by 18sby** [youzan/vant-weapp#2324]
![image](https://user-images.githubusercontent.com/47735184/69033079-191ccf00-0a19-11ea-9d15-9a956b208d06.png)，这是安装的版本号
前几天还是好的，开发工具，基础库等等都是最新的，望尽快解决，谢谢

**Comment by bochoi** [comment]
我的是最新版，昨天更新的一样的问题change事件失效，clearable不出现清除icon
![image](https://user-images.githubusercontent.com/22139382/69046307-a10fd280-0a33-11ea-9ccd-df0228359073.png)

**Comment by rex-zsd** [comment]
issue格式不规范，没有示例代码…………
看了下demo小程序是ok的，这个组件近半年没有什么大的变更了，检查下自己的代码？

**Comment by bochoi** [comment]
小程序基础库2.9.3的问题，降到其他基础库就好了

**Comment by Skura23** [comment]
> 小程序基础库2.9.3的问题，降到其他基础库就好了

这个方法可以, 但如何在基础库2.9.3里使用呢? 这个算是项目bug吧?

**Comment by Meatchell** [comment]
> > 小程序基础库2.9.3的问题，降到其他基础库就好了
> 
> 这个方法可以, 但如何在基础库2.9.3里使用呢? 这个算是项目bug吧?

这个是官方bug，先切换到其他基础库。是小程序bug原生change,input 事件也无效
