### ISSUE TITLE
[Bug Report] van-tab  文字过多显示不全

### ISSUE THREAD

**Issue by wlsh** [youzan/vant-weapp#2333]
### 设备
iphone8

### VantWeapp 版本
1.0.0-beta.2

### 基础库版本
2.8.3

### 如果是 UI 问题，截图链接（多图回车分隔）

https://i.loli.net/2019/11/19/8yjHNeFDbZdaR1v.png

### 请提供核心代码片段链接
https://gist.github.com/wlsh/de2ac908bb1945e88cebbb451b686a67

### 描述问题
van-tab 文字过长显示不全

**Comment by rex-zsd** [comment]
#2297
