### ISSUE TITLE
[Bug Report] 使用tabs组件的页面，离开页面会报错

### ISSUE THREAD

**Issue by a1029382825** [youzan/vant-weapp#2335]
更新版本1.0.0-beta.4后，使用tabs组件的页面按返回按钮离开页面时报错
![image](https://user-images.githubusercontent.com/21085420/69116849-b551df00-0ac8-11ea-8ab4-2ee0d908fe2f.png)

**Comment by gromit1sm** [comment]
+1,更新后出现的问题

**Comment by xin10** [comment]
+1,更新后出现问题

**Comment by Airam1016** [comment]
+1, 页面初次渲染时会bind:change事件多次触发
