### ISSUE TITLE
[Bug Report] tabs组件使用吸顶共能后，快速向上滑动有几率出现吸顶失败

### ISSUE THREAD

**Issue by a1029382825** [youzan/vant-weapp#2336]
tabs组件使用吸顶共能后，快速向上滑动有几率大幅度抖动并吸顶失败，
这个问题在beta2版本商是没有的
在tabs组件中去掉van-sticky的container属性后不会出现吸顶失败

**Comment by rex-zsd** [comment]
tabs的吸顶只在tabs内容区域内有效，也就是说一旦tabs内容区的底部位于可视区上方，就会取消吸顶。
所以快速向上滑动时，出现快速吸顶并快速取消是正常的现象。

**Comment by rex-zsd** [comment]
beta.2版本因为sticky没有实现container属性，所以与vant不一致，只要tabs顶部位于可视区就会吸顶。
