### ISSUE TITLE
[Bug Report] 更新完最新版本后能多选图片，但是选择图片之后直接报错

### ISSUE THREAD

**Issue by baochunsan** [youzan/vant-weapp#2337]
### 设备
iphone

### VantWeapp 版本
1.0.0-beta.4

### 基础库版本
2.9.3

### 如果是 UI 问题，截图链接（多图回车分隔）

![截图](https://i.loli.net/2019/11/19/IqjJm4ZpR9y21XE.png)

### 请提供核心代码片段链接
https://i.loli.net/2019/11/19/IqjJm4ZpR9y21XE.png

### 描述问题
弹出选择图片，然后选择之后报错

**Comment by chenjiahan** [comment]
图片挂了，能否更新下

**Comment by rex-zsd** [comment]
demo小程序并没有复现，是不是使用姿势的问题？
重新上传下报错提示图看下？
