### ISSUE TITLE
van-uploader不能选择图片

### ISSUE THREAD

**Issue by guanmu666** [youzan/vant-weapp#2338]
![image](https://user-images.githubusercontent.com/52024456/69138639-01694780-0afa-11ea-9cef-e64570f26652.png)
![image](https://user-images.githubusercontent.com/52024456/69138557-dbdc3e00-0af9-11ea-9550-bead51b65ad9.png)
![image](https://user-images.githubusercontent.com/52024456/69138785-442b1f80-0afa-11ea-8936-3a81a01ff175.png)

请问事先加入fileList中的图片可以展示，但点击视图中的加号选中图片确定后，after-read没有执行

**Comment by baochunsan** [comment]
我也是，console中直接报错

**Comment by IFreeOvO** [comment]
我在mpvue使用也遇到相同的问题，没有任何报错，但就是接受不到事件

**Comment by rex-zsd** [comment]
> 我在mpvue使用也遇到相同的问题，没有任何报错，但就是接受不到事件

@IFreeOvO mpvue是不支持事件名中带`-`的，只能自行修改下源码。

**Comment by rex-zsd** [comment]
@guanmu666 mpvue是不支持事件名中带`-`的，自行修改下源码吧。
