### ISSUE TITLE
tab标签页组件click，change事件回调的event.detail中无法取得被点击标签的标识符（name）

### ISSUE THREAD

**Issue by Mr-sunyijie** [youzan/vant-weapp#2339]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。
文档中介绍说tab组件的click，change事件的回调中可以拿到title和name，但是在实际使用中只得到了index和title，并没有拿到name标识符
https://youzan.github.io/vant-issue-generater?repo=VantWeapp

**Comment by rex-zsd** [comment]
issue格式不规范，信息不足，帮不了你咯……

**Comment by Mr-sunyijie** [comment]
好的，我再修改修改，第一次提





------------------ 原始邮件 ------------------
发件人: rex <notifications@github.com&gt;
发送时间: 2019年11月20日 23:17
收件人: youzan/vant-weapp <vant-weapp@noreply.github.com&gt;
抄送: Mr-sunyijie <2461541829@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[youzan/vant-weapp] tab标签页组件click，change事件回调的event.detail中无法取得被点击标签的标识符（name） (#2339)

**Comment by Catcheer** [comment]
请问解决了嘛 我遇到了同样的问题
