### ISSUE TITLE
vant-field  绑定 bind:input  bind:change 事件全部失效 

### ISSUE THREAD

**Issue by xin10** [youzan/vant-weapp#2342]
设备
iphone

VantWeapp 版本
1.0.0-beta.4

基础库版本
2.9.3

描述问题
vant-field  绑定 bind:input  bind:change 事件全部失效

**Comment by Jackrz** [comment]
今天也遇到了这个问题 , 把基础库版本换到2.9.2 已解决

**Comment by rex-zsd** [comment]
微信开发者工具的bug，回归基础库到2.9.2即可。
