### ISSUE TITLE
求助，mpvue使用TreeSelect分类选择如何绑定事件

### ISSUE THREAD

**Issue by g9420** [youzan/vant-weapp#2348]
<van-tree-select
      :items="item"
      :main-active-index="mainActiveIndex"
      :active-id="activeId"
      :max="max"
      @click-nav="onClickNav"
      @lick-item="onClickItem"
    />

**Comment by rex-zsd** [comment]
mpvue不支持事件名带`-`，目前只能自己修改vant-weapp的源码，更改事件名。

**Comment by g9420** [comment]
好的，非常感谢您！
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"rex"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月20日(星期三) 晚上11:15
收件人:&nbsp;"youzan/vant-weapp"<vant-weapp@noreply.github.com&gt;;
抄送:&nbsp;"嵩"<942075508@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [youzan/vant-weapp] 求助，mpvue使用TreeSelect分类选择如何绑定事件 (#2348)




mpvue不支持事件名带-，目前只能自己修改vant-weapp的源码，更改事件名。
