### ISSUE TITLE
van-cell slot="default" value内容不显示

### ISSUE THREAD

**Issue by fang7665955** [youzan/vant-weapp#2349]
`<van-cell title="入库数量">
      <view slot="default">
        <van-stepper value="{{ 5 }}" min="1" max="8" integer input-width="40px" button-size="32px" />
      </view>
    </van-cell>`
![image](https://user-images.githubusercontent.com/30946999/69240462-7cecf680-0bd7-11ea-8c7c-892fc2e42a4e.png)
步进器不显示，这个是什么问题呀

**Comment by rex-zsd** [comment]
默认slot不需要写名字…………

**Comment by fang7665955** [comment]
好吧   确实是
