### ISSUE TITLE
根据新手上路中的命令无法获取最新的组件，例如:image 麻烦提供一下获取最新版的命令或更新一下新手上路，谢谢

### ISSUE THREAD

**Issue by SomeOneNoBrain** [youzan/vant-weapp#2351]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater?repo=VantWeapp
![1574301120(1)](https://user-images.githubusercontent.com/34363060/69293809-f66efe00-0c44-11ea-9557-5e39bf6c8231.jpg)

**Comment by chenjiahan** [comment]
可以通过 npm i vant-weapp@1.0.0-beta.4 -S 安装 1.0 beta 版本，正式版会在近期发布
