### ISSUE TITLE
[Bug Report] van-tab在返回上一页面报错

### ISSUE THREAD

**Issue by linhaibo147** [youzan/vant-weapp#2352]
### 设备
微信开发者工具

### VantWeapp 版本
1.0.0-beta.4

### 基础库版本
2.9.1

### 如果是 UI 问题，截图链接（多图回车分隔）

![截图](https://sm.ms/image/aQYd9lwjIZvA84s)

### 请提供核心代码片段链接
https://sm.ms/image/aQYd9lwjIZvA84s

### 描述问题
在截图链接有，初步怀疑是netTick回调问题，能初始化，但在返回上一页时就报错。
没有核心代码片段，引入组件然后返回上一页就可复现

**Comment by rex-zsd** [comment]
#2335
