### ISSUE TITLE
我使用van-goods-action，右边显示不完整，超出去了，有什么东西能控制宽度吗？我是新手才学习

### ISSUE THREAD

**Issue by wangben5** [youzan/vant-weapp#2354]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater?repo=VantWeapp

[](url)

**Comment by rex-zsd** [comment]
issue格式不规范，先关闭了。

**Comment by rex-zsd** [comment]
学习代码建议扫下readme的码，加群交流，issue是反馈问题的地方哈。
