### ISSUE TITLE
[Bug Report] search组件获取不到值

### ISSUE THREAD

**Issue by woytu** [youzan/vant-weapp#2356]
### 设备
微信开发者工具v1.02.1911202

### VantWeapp 版本
1.0.0-beta.4

### 基础库版本
2.9.3

- 经测试是发现基础库版本问题，使用2.9.3以下版本就没有问题

### 请提供核心代码片段链接
https://gist.github.com/woytu/a9bc25230b8d7f0d28d58443be0ed220

### 描述问题
请看截图，而且输入框右侧清除控件也没有自动启用 

![](https://i.loli.net/2019/11/21/LfTSH5wa62xU4QN.png)

**Comment by woytu** [comment]
可能是由于缓存原因，换一个环境就自动好了

**Comment by rex-zsd** [comment]
微信开发者工具的bug，下降基础库到2.9.2以下。
