### ISSUE TITLE
[Feature Request] Radio checked class提升至最顶层, 而不是仅icon有checked class

### ISSUE THREAD

**Issue by WhiteMinds** [youzan/vant-weapp#2358]
### 这个功能解决了什么问题
slot内容在checked时的自定义样式, 目前是必须依赖onChange, 然后去给它加class

### 建议的API是什么样的
无, 直接改动class位置即可

**Comment by rex-zsd** [comment]
不是很合理，要动态控制slot的样式。
可以动态设置`label-class`，也可以直接在你插入的slot上增加样式，应该不强依赖checked-class的增加。
