### ISSUE TITLE
van-search search事件获取不到value值

### ISSUE THREAD

**Issue by fang7665955** [youzan/vant-weapp#2360]
```
<van-search value="{{ searchText }}" placeholder="请输入内容" 
  bind:search="onSearch" bind:change="onSearchChange"/>
```
![image](https://user-images.githubusercontent.com/30946999/69341387-79737100-0ca4-11ea-90c2-14bc3f437acf.png)

van-search search事件获取不到value值，并且change事件根本就不执行，这是什么原因？

**Comment by woytu** [comment]
同issue https://github.com/youzan/vant-weapp/issues/2356

不要使用最新基础库版本

**Comment by fang7665955** [comment]
那用哪一个？ 0.x？吗

**Comment by woytu** [comment]
> 那用哪一个？ 0.x？吗

注意基础库版本和vantweapp版本不是指同一个

**Comment by fang7665955** [comment]
我都搞糊涂了 到底用哪一个呀？能给个地址码，谢谢

**Comment by fang7665955** [comment]
![image](https://user-images.githubusercontent.com/30946999/69409074-4207d180-0d43-11ea-9990-e0024d194d25.png)
这个版本不对吗

**Comment by woytu** [comment]
你用了微信开发工具没有？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"世外之人"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月22日(星期五) 下午3:54
收件人:&nbsp;"youzan/vant-weapp"<vant-weapp@noreply.github.com&gt;;
抄送:&nbsp;"woytu"<admin@woytu.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [youzan/vant-weapp] van-search search事件获取不到value值 (#2360)




我都搞糊涂了 到底用哪一个呀？能给个地址码，谢谢

**Comment by frei-x** [comment]
把微信开发者工具基础库由2.93调为2.92就好了, 微信坑
