### ISSUE TITLE
[Feature Request] van-dropdown-menu

### ISSUE THREAD

**Issue by glauca** [youzan/vant-weapp#2361]
### 这个功能解决了什么问题
获取van-dropdown-menu折叠/打开的状态

### 建议的API是什么样的
返回van-dropdown-menu折叠/打开的状态

**Comment by rex-zsd** [comment]
下版本会新增 `open` `opened` `close` `closed`事件，可以通过事件获知每个 dropdown-item 的打开关闭状态。
