### ISSUE TITLE
vant-weapp的Uploader组件的preview-size属性出现重复单位

### ISSUE THREAD

**Issue by shiyachao** [youzan/vant-weapp#2362]
vant-weapp的Uploader组件的preview-size属性不管设置成数字还是数字加单位，最后生成的值都是例如100pxpx，导致设置无效；为什么不提供预览图片的外部样式，或者preview-size能提供宽高设置，毕竟不是所有上传的地方都是正方形

**Comment by rex-zsd** [comment]
重复单位这个问题没有复现出来，设置数字或字符串都是正常的。

**Comment by rex-zsd** [comment]
vant-weapp的所有组件都开启了`addGlobalClass: true`的，可以在页面或者`styleIsolation: shared`的组件中覆盖默认样式。
可以参考微信的[文档](https://developers.weixin.qq.com/miniprogram/dev/framework/custom-component/wxml-wxss.html)

**Comment by chenjiahan** [comment]
这个问题前两天有同学提 PR 修复了，下个版本就 ok 了

https://github.com/youzan/vant-weapp/pull/2340
