### ISSUE TITLE
[Bug Report] van-cell组件使用slot（default）自定义value没效果

### ISSUE THREAD

**Issue by lxk0301** [youzan/vant-weapp#2363]
### 设备
微信开发工具1.02.1910120 Windows 64，真机也一样

### VantWeapp 版本
1.0.0-beta.4

### 基础库版本
2.9.1

### 如果是 UI 问题，截图链接（多图回车分隔）

![Snipaste_2019-11-22_10-55-56.png](https://i.loli.net/2019/11/22/dHNhzvSXQRk1EoD.png)

### 请提供核心代码片段链接
https://gist.github.com/lxk0301/c252305908ec57cebe81aa1b569df70a

### 描述问题
van-cell组件使用slot（default）自定义value没效果，value区域空白，cell没有设置value属性

**Comment by rex-zsd** [comment]
default slot是没有name的，直接插入就可以了。
