### ISSUE TITLE
[Bug Report] tab标签页苹果端会遮挡部分主题内容

### ISSUE THREAD

**Issue by LookMeLovely** [youzan/vant-weapp#2365]
### 设备
iphone

### VantWeapp 版本
1.0.0-beta.4

### 基础库版本
2.9.2

### 如果是 UI 问题，截图链接（多图回车分隔）

![截图](<a)

![截图](href="https://sm.ms/image/TEw8BFOsDmJ9bVR")

![截图](target="_blank"><img)

![截图](src="https://i.loli.net/2019/11/22/TEw8BFOsDmJ9bVR.png")

![截图](></a>)

### 请提供核心代码片段链接
https://github.com/youzan/vant

### 描述问题
tab标签页苹果端会遮挡部分主题内容

**Comment by rex-zsd** [comment]
图片都挂了没传上来，重新传一下吧。
