### ISSUE TITLE
[Bug Report] button的disabled属性不起作用

### ISSUE THREAD

**Issue by neo20** [youzan/vant-weapp#2366]
### 设备
all

### VantWeapp 版本
1.0.0-beta.4

### 基础库版本
2.9.3

### 请提供核心代码片段链接
https://www.yuque.com/lgnm0a/cibtt6/ls7nkp

### 描述问题
<van-button disabled="false" slot="button" size="small" type="primary" bindtap="sendMsg">发送验证</van-button>
按钮为灰色禁用状态。只有去掉disabled属性时才是不禁用的状态。但是我必须使用disabled属性。因为
<van-button {{ disabled_status }} slot="button" size="small" type="primary" bindtap="sendMsg">发送验证</van-button>
编译会报错。

相关文档：
https://youzan.github.io/vant-weapp/#/button#api

**Comment by rex-zsd** [comment]
disabled禁用的是`bind:click`时间，bindtap是原生事件。

**Comment by neo20** [comment]
感谢。是我理解不到位

**Comment by rex-zsd** [comment]
自动类型转换确实是微信小程序的一个坑。
理论上小程序是有自动类型转换的，但是实际上`String``Number``Boolean`互转的时候小程序总会出现各种不符合预期的情况…………

**Comment by rex-zsd** [comment]
自动类型转换确实是微信小程序的一个坑。
理论上小程序是有自动类型转换的，但是实际上`String``Number``Boolean`互转的时候小程序总会出现各种不符合预期的情况…………

**Comment by rex-zsd** [comment]
自动类型转换确实是微信小程序的一个坑。
理论上小程序是有自动类型转换的，但是实际上`String``Number``Boolean`互转的时候小程序总会出现各种不符合预期的情况…………
