### ISSUE TITLE
van-field不支持双向绑定的问题

### ISSUE THREAD

**Issue by daiyifei** [youzan/vant-weapp#2368]
#1751 
原生组件在e.detail.value取值而field组件是e.detail，导致在使用uniapp,wepy之类框架时无法实现双向绑定。
内置 behaviors` wx://form-field` 应该只有form的submit事件有用，很多时候并不需要form，是否可以加个选项，可以让返回字段跟原生组件一样呢？

**Comment by basstk** [comment]
手机端是OK的,在微信的开发者工具里会出现无法绑定跟获取到值的情况

**Comment by Hyejeongdd** [comment]
> 手机端是OK的,在微信的开发者工具里会出现无法绑定跟获取到值的情况

手机端也是实效的 可以看看你的demo吗

**Comment by rex-zsd** [comment]
已经支持了小程序原生的双向绑定
