### ISSUE TITLE
[Bug Report] van-sidebar active索引计数异常，当数据重载(setData)后未从0开始

### ISSUE THREAD

**Issue by anythink-wx** [youzan/vant-weapp#2369]
### 设备
iOS12

### VantWeapp 版本
1.0.0-beta.4

### 基础库版本
2.3.0

### 请提供核心代码片段链接
https://gist.github.com/anythink-wx/f87b313099f2a4159c31068ad878a799

### 描述问题
第一次渲染pageData.cate 如有5个元素， 当数据重载后（页面不刷新，只是执行 setData），索引会从6-7-8-9 继续导致 active 获取不正确。

**Comment by rex-zsd** [comment]
请贴下js部分的代码哈

**Comment by anythink-wx** [comment]
@rex-zsd 已经更新到 代码片段链接中。
