### ISSUE TITLE
[Bug Report] notify不显示内容

### ISSUE THREAD

**Issue by leo95123** [youzan/vant-weapp#2371]
### 设备
所有

### VantWeapp 版本
1.0.0-beta.4

### 基础库版本
*

### 如果是 UI 问题，截图链接（多图回车分隔）

![截图](https://i.postimg.cc/0jN61TSH/TIM-20191125095645.png)

### 请提供核心代码片段链接
https://gist.github.com/leo95123/66de93c569e717034b1531d4c0becd31

### 描述问题
notify可以正常显示，但是不能显示内容。

**Comment by rex-zsd** [comment]
example小程序没有问题，目前的信息不足以继续排查。
