### ISSUE TITLE
[Bug Report] grid宫格组件同时设置square和gutter属性后，间距未能生效

### ISSUE THREAD

**Issue by a20086115** [youzan/vant-weapp#2373]
### 设备
华为畅享9s

### VantWeapp 版本
1.0.0-beta.4

### 基础库版本
2.9.1

### 如果是 UI 问题，截图链接（多图回车分隔）

![微信截图_20191125115237.png](https://i.loli.net/2019/11/25/ZTjv1BS4ysm8VHq.png)

### 请提供核心代码片段链接
https://gist.github.com/a20086115/9a24f81438b17c9af6c618eca41eadd1

### 描述问题
单独设置square和gutter属性都可以生效，但是当我同时设置square和gutter属性后，间距未能生效。

**Comment by a20086115** [comment]
我在本地修改测试后提交了一个pr#2375

**Comment by rex-zsd** [comment]
grid还有另外一个问题也待修，我另外提个pr吧
👍 感谢pr
