### ISSUE TITLE
van-uploader multiple="true" 不能多张勾选

### ISSUE THREAD

**Issue by guanmu666** [youzan/vant-weapp#2374]
<van-uploader file-list="{{ fileList }}" bind:afterRead="afterRead" multiple="true" />，用的wepy框架，点击后勾选图片，多张选择只能选中一张

**Comment by rex-zsd** [comment]
`multiple` 或者 `:multiple="true"` 试试？

**Comment by guanmu666** [comment]
> `multiple` 或者 `:multiple="true"` 试试？

还是不可，是小程序的问题么

**Comment by rex-zsd** [comment]
还有版本是什么？不按模板提issue简直要命。

**Comment by guanmu666** [comment]
> 还有版本是什么？不按模板提issue简直要命。

抱歉...我直接下的github上的压缩包，可能是1.0.0-beta.4？

**Comment by rex-zsd** [comment]
测试了一下wepy@1.6.0 + vant-weapp@1.0.0-beta.4可以多张上传。
查查其他原因吧。

**Comment by LookMeLovely** [comment]
现在解决了吗，我这里也有这个问题，不能勾选多张
