### ISSUE TITLE
tabs标签页-默认第一个标签无法初始化动态数据

### ISSUE THREAD

**Issue by creedclub** [youzan/vant-weapp#2377]
### 设备
移动端

### VantWeapp 版本
1.0.0-beta.4

### 基础库版本
1.0.0-beta.4

### 请提供核心代码片段链接
https://gist.github.com/

### 描述问题
tab标签页初始化，比如总共三个标签页面，标签内容为动态请求的数据，初始化，第一个标签无法显示数据，只有切换标签之后，才可以显示数据。

**Comment by Dianian** [comment]
我也遇到了这个问题

**Comment by rex-zsd** [comment]
@Dianian @creedclub 麻烦提供下代码

**Comment by Dianian** [comment]
<van-tabs bind:change="onChange">
  <van-tab title="标签 1">内容 1</van-tab>
  <van-tab title="标签 2">内容 2</van-tab>
  <van-tab title="标签 3">内容 3</van-tab>
  <van-tab title="标签 4">内容 4</van-tab>
</van-tabs>
Page({
  onChange(e) {
    console.log(e);
//第一次进来无法初始化，切换标签后显示前一个标签的 name与title
  }
});
@rex-zsd

**Comment by Dianian** [comment]
`<van-tabs  bind:change="onChange">
  <van-tab title="标签 1">内容 1</van-tab>
  <van-tab title="标签 2">内容 2</van-tab>
  <van-tab title="标签 3">内容 3</van-tab>
  <van-tab title="标签 4">内容 4</van-tab>
</van-tabs>
Page({
  onChange(e) {
     console.log(e);
     //第一次进来无法初始化，切换标签后显示前一个tab的name与title
  }
});`

**Comment by Dianian** [comment]
`<van-tabs bind:change="onChange"> <van-tab title="标签 1">内容 1</van-tab> <van-tab title="标签 2">内容 2</van-tab> <van-tab title="标签 3">内容 3</van-tab> <van-tab title="标签 4">内容 4</van-tab> </van-tabs> Page({ onChange(e) { console.log(e); //第一次进来无法初始化，切换标签后显示前一个tab的name与title } });` @rex-zsd

**Comment by jiangyaoxinjoy** [comment]
我也遇到了这个问题

**Comment by rex-zsd** [comment]
跟些+1之类的回复对解决问题毫无帮助呀………………
@Dianian 这段代码太不全面了，看不出问题是什么……

**Comment by alexshu11** [comment]
有没有个可以外部调用的方法来改变tab的index?  因为只改变index的话, tab是不会切换的, 只有在点击tab的时候才会触发切换

**Comment by rex-zsd** [comment]
@alexshu11 可以动态修改`active`属性的

**Comment by jiangyaoxinjoy** [comment]
我也遇到这个问题，我把组件内部选择的样式删掉了，外部定义选中的样式。动态的index就有效了，然后点击再改变index。不知道有没有bug。





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"alexshu11"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月29日(星期五) 下午4:29
收件人:&nbsp;"youzan/vant-weapp"<vant-weapp@noreply.github.com&gt;;
抄送:&nbsp;"星辰大海"<2209620497@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [youzan/vant-weapp] tabs标签页-默认第一个标签无法初始化动态数据 (#2377)




有没有个可以外部调用的方法来改变tab的index?  因为只改变index的话, tab是不会切换的, 只有在点击tab的时候才会触发切换

**Comment by jiangyaoxinjoy** [comment]
我回错了，我刚才说的是van-sidebar部分



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "rex"<notifications@github.com&gt;; 
发送时间: 2019年11月29日(星期五) 下午4:50
收件人: "youzan/vant-weapp"<vant-weapp@noreply.github.com&gt;; 
抄送: "星辰大海"<2209620497@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [youzan/vant-weapp] tabs标签页-默认第一个标签无法初始化动态数据 (#2377)




@alexshu11 可以动态修改active属性的

**Comment by rex-zsd** [comment]
@creedclub @Dianian 
可以看下beta.5是否有修复你们的问题？

**Comment by Dianian** [comment]
@rex-zsd  昨天试了已经修复，谢谢

**Comment by rex-zsd** [comment]
虽然还是没明白问题是什么…………太难了 😢
