### ISSUE TITLE
tabbar页面内容怎么换

### ISSUE THREAD

**Issue by devondahon** [youzan/vant-weapp#2378]
我新建了一个项目，安装了vant-weapp, 然后按照说明书使用了tabbar。tabbar可以按但是页面内容怎么换？ 是要建立不同的组件(component)还是页面(page)。建立了之后怎么实行转换呢？

**Comment by rex-zsd** [comment]
查看文档示例或者加群沟通，issue是反馈问题的地方哈。

**Comment by devondahon** [comment]
文档示例不足，不显示怎么换内容。怎么加群沟通？
