### ISSUE TITLE
[Bug Report] van-field input在ios上出现遮挡

### ISSUE THREAD

**Issue by sonofmagic** [youzan/vant-weapp#2379]
### 设备
iphone 7 plus

### VantWeapp 版本
1.0.0-beta.4

### 基础库版本
2.9.1

### 如果是 UI 问题，截图链接（多图回车分隔）

![截图](https://i.loli.net/2019/11/25/tOY5DU1ZXdl4zj9.png)

### 请提供核心代码片段链接
https://gist.github.com/sonofmagic/c097fe217392ca565de782d7e3f14ddd

### 描述问题
在iphone 7 plus 的ios上，使用 这个组件并开启 button slot 或者right-icon 时，会生效padding-left:6px的样式，造成了图片中的效果，本人的解决方案为，将padding-left改为0px，同时给input-class加一个padding-right:6px；可解决ios的问题

**Comment by rex-zsd** [comment]
你的文字为什么是靠右的？是自己修改了？
代码片段请提供你使用的代码，不要贴vant-weapp的代码。

**Comment by sonofmagic** [comment]
<van-field value="{{financingValue}}" input-align="right" type="digit" placeholder-style="text-align:right" maxlength="{{50}}" placeholder="请输入金额">
      <view slot="label">金额</view>
      <view slot="button">
        元人民币
      </view>
    </van-field>


data={
    financingValue: 1000,
}

代码是这样的，试了一下，似乎是用的时候样式比较复杂，纯这样写没啥问题
