### ISSUE TITLE
小程序上按钮样式button: not([size='mini'])造成按钮样式错乱

### ISSUE THREAD

**Issue by ruoxiaodian** [youzan/vant-weapp#2380]
<img width="1405" alt="image" src="https://user-images.githubusercontent.com/28801943/69532774-7f719680-0fb1-11ea-806c-6762f1dcafca.png">

**Comment by rex-zsd** [comment]
微信小程序并不支持这么复杂的选择器，这样写很容易造成样式问题。可以看下微信的[文档](https://developers.weixin.qq.com/miniprogram/dev/framework/view/wxss.html)

**Comment by rex-zsd** [comment]
如果需要自定义部分样式，可以通过开放的外部样式类，或者直接在页面的wxss中直接覆盖对应样式。
