### ISSUE TITLE
[Bug Report] Dropdown内部不能使用icon

### ISSUE THREAD

**Issue by DuodenumL** [youzan/vant-weapp#2381]
### 设备
模拟器

### VantWeapp 版本
1.0.0-beta.4

### 基础库版本
2.9.3

### 如果是 UI 问题，截图链接（多图回车分隔）

![截图](https://sm.ms/image/uVm9I2POlL1s3Kf)

### 请提供核心代码片段链接
https://gist.github.com/DuodenumL/9a0656ff86ae00f2ba9bd08b3f13e8b0

### 描述问题
我想使用Dropdown实现一个下拉的效果，然后自定义里面的内容。如代码所示，当内容中包含icon组件时，icon不会被展示出来。

**Comment by rex-zsd** [comment]
图挂了，可以再上传一下吗？

**Comment by DuodenumL** [comment]
![image](https://user-images.githubusercontent.com/14165108/69607432-7816b100-0fe2-11ea-95f9-5b2decdebef2.png)
箭头的地方应该有icon

**Comment by rex-zsd** [comment]
@DuodenumL  通过slot插入内容的话，这个应该不是DropdownMenu的问题，而是图标未显示的问题
可以看下是不是样式影响了，或者字体文件加载失败的原因。
开发者工具上有时会出现字体文件加载失败的情况，可以在真机上试一下的。
