### ISSUE TITLE
用npm怎么安装1.0版本？

### ISSUE THREAD

**Issue by devondahon** [youzan/vant-weapp#2385]
如果用Git下载：
```
git clone https://github.com/youzan/vant-weapp.git
```
然后再.json文件里加需要用的模块链接，下面的错误就出现：
<img width="370" alt="Capture d’écran 2019-11-26 à 2 21 03 PM" src="https://user-images.githubusercontent.com/612946/69604795-63293480-1059-11ea-83ee-dae4586b22fd.png">

===

<img width="567" alt="Capture d’écran 2019-11-26 à 12 52 45 PM" src="https://user-images.githubusercontent.com/612946/69601047-d4fb8100-104d-11ea-874a-2f40431fd1f4.png">

**Comment by JakeLaoyu** [comment]
> npm i vant-weapp@x.x.x -S --production
