### ISSUE TITLE
[Bug Report] 整合到uniapp中后要无法通过样式变量修改样式

### ISSUE THREAD

**Issue by yah0130** [youzan/vant-weapp#2391]
### 设备
iphone

### VantWeapp 版本
0.5.23

### 基础库版本
0.5.23

### 请提供核心代码片段链接
https://gist.github.com/yah0130/15132df424e6b8405dcb35ec028947b7

### 描述问题
我想修改tab的margin-bottom但是无效，代码如下：
.van-tabbar-item {
  --tabbar-item-margin-bottom: 0px;
}

**Comment by rex-zsd** [comment]
0.5.23不支持css变量，升级到1.0.0-beta.2以上即可。
