### ISSUE TITLE
关于van-image 的问题

### ISSUE THREAD

**Issue by zhoufanglu** [youzan/vant-weapp#2392]
`van-image` 如何使用原始图片大小？
```html
<van-image
                            use-error-slot
                            :src="i"
                            width="100%"
                            height="100%"
                            lazy-load
                            fit="none"
                            show-menu-by-longpress="true"
                    >
                        <text slot="error">加载失败</text>
                    </van-image>
```
现在效果如下
![DT$3XZQ1X5C$9EU{{(UDJ0T](https://user-images.githubusercontent.com/24451091/69619235-3d5e5880-1076-11ea-80aa-9efbda7c6f80.png)

请问有可能实现吗？

**Comment by rex-zsd** [comment]
可以试试不设置`width`和`height`

**Comment by zhoufanglu** [comment]
> 可以试试不设置`width`和`height`

不设置的话连图片都没有

**Comment by rex-zsd** [comment]
emmm…………仔细看了一下是这样的，目前不支持原始大小

**Comment by zhoufanglu** [comment]
> emmm…………仔细看了一下是这样的，目前不支持原始大小

好吧，谢谢回答。

**Comment by zhoufanglu** [comment]
在`<van-popup>`组件内嵌套了`<van-image>`
动态绑定`height`和`width`无效！ 

**如果高度和宽度写死是显示的。** 

代码如下图
![M18O721 DW~C5SFIQ@T`WST](https://user-images.githubusercontent.com/24451091/69690237-0afc3c00-1106-11ea-9a67-a0389c4f9757.png)

`src`路径都是对的

渲染的`img`对象如下
![BR)VH 42VD0RN3@YY}%R{41](https://user-images.githubusercontent.com/24451091/69690380-91b11900-1106-11ea-86f7-b4069a74c735.png)

**Comment by rex-zsd** [comment]
想了一下，小程序的image组件是有默认宽高300 * 250的，即使不设置`width`和`height`，也不会是图片自身的大小。
要显示原图大小，必须先通过`wx.getImageInfo`获取到图片大小，再动态设置`width`和`height`。
beta.5将会支持动态设置`width`和`height`属性。

**Comment by zhoufanglu** [comment]
> 想了一下，小程序的image组件是有默认宽高300 * 250的，即使不设置`width`和`height`，也不会是图片自身的大小。
> 要显示原图大小，必须先通过`wx.getImageInfo`获取到图片大小，再动态设置`width`和`height`。
> beta.5将会支持动态设置`width`和`height`属性。

好的谢谢。
