### ISSUE TITLE
城市三级联动，动态获取城市数据处理，视图层显示空白

### ISSUE THREAD

**Issue by Wumei222** [youzan/vant-weapp#2396]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater?repo=VantWeapp

**Comment by rex-zsd** [comment]
可能跟 #2420 是相同的问题，文档有错误，去掉属性前面的`:`即可。
