### ISSUE TITLE
通过扫码直接打开时候非运算改变属性不起作用！这是不是源于vant内部构造原因吗

### ISSUE THREAD

**Issue by ruoxiaodian** [youzan/vant-weapp#2401]
<img width="885" alt="image" src="https://user-images.githubusercontent.com/28801943/69693387-24a28100-1110-11ea-8d22-bc3b53c9f419.png">

**Comment by rex-zsd** [comment]
没看懂是什么意思………………

**Comment by ruoxiaodian** [comment]
😂 &nbsp;扫码直接打开某个页面时候；这个页面的vant组件show属性的值 不能使用非运算符；比如isMember是可以的 &nbsp;!isMember不可以



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "rex"<notifications@github.com&gt;; 
发送时间: 2019年11月27日(星期三) 下午2:33
收件人: "youzan/vant-weapp"<vant-weapp@noreply.github.com&gt;; 
抄送: "若"<526963089@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [youzan/vant-weapp] 通过扫码直接打开时候非运算改变属性不起作用！这是不是源于vant内部构造原因吗 (#2401)




没看懂是什么意思………………

**Comment by rex-zsd** [comment]
应该没有这种道理…………怀疑是有其他的问题
可以在下面显示一下`{{ !isMember }}`看看是什么内容

**Comment by ruoxiaodian** [comment]
isMember初始值为false；普通的点击跳转页面是没有这个问题；也打印了!isMember 是false但是 组件还是按照初始值显示出来了；

**Comment by rex-zsd** [comment]
可以试下去除其它无关的代码，仅保留最简单的popup使用，看下问题在哪里。
