### ISSUE TITLE
使用swipe-cell后，无法监听到touchend事件

### ISSUE THREAD

**Issue by jiangen1016** [youzan/vant-weapp#2402]
`<view class="swipe-cell-item" right-width="{{ 48 }}" class="swipe-cell-pp"
                        bindtouch:start='dragStart' bind:touchmove='dragMove' bind:touchend='dragEnd'
                       >
                        <view class="swipe-cell-point"></view>
                        <van-swipe-cell>
                            <text>列表1</text>
                            <text>30s</text>
                            <view class="swipe-delete" slot="right">删除</view>
                        </van-swipe-cell>
                    </view>`

最近在做一个拖拽排序的功能，列表侧滑删除，无论在外层监听还是van-swipe-cell监听，都无法监听到touchend事件
"vant-weapp": "^0.5.16"

**Comment by rex-zsd** [comment]
是的，为了阻止左右滑动时页面上下滚动，内部catch了touchmove事件。

**Comment by jiangen1016** [comment]
> 是的，为了阻止左右滑动时页面上下滚动，内部catch了touchmove事件。

那请问有什么解决方案吗？

**Comment by rex-zsd** [comment]
大致有2个方案
- swipe-cell 内部再把事件抛出来
- 不再 catch 事件，绕过这个问题
第1个方案比较实际一点，预计下个1.0.0-beta.5版本可支持
你的版本还在0.5.16，推荐可以先自己修改下源码

**Comment by jiangen1016** [comment]
> 大致有2个方案
> 
> * swipe-cell 内部再把事件抛出来
> * 不再 catch 事件，绕过这个问题
> 
> 第1个方案比较实际一点，预计下个1.0.0-beta.5版本可支持
> 你的版本还在0.5.16，差距有点大不好升级，推荐可以先自己修改下源码

好的，多谢指导。
