### ISSUE TITLE
[Bug Report] Field输入框在手动移动光标位置后光标会被移动到句首

### ISSUE THREAD

**Issue by Bing573** [youzan/vant-weapp#2404]
### 设备
IPhone6s

### VantWeapp 版本
1.0.0-beta.4

### 基础库版本
2.7.4

### 如果是 UI 问题，截图链接（多图回车分隔）

![截图](https://i.loli.net/2019/11/27/C84Yxt3mpIA9ywR.gif)

### 请提供核心代码片段链接
https://gist.github.com/Bing573/1347d0b4f816e14f36299d8414d77eb7

### 描述问题
当滑动光标的后，光标会被移动到句首。

**Comment by rex-zsd** [comment]
field内部使用的就是原生的input，也没有能力操作光标位置
可以用原生input测试看看，有问题的话去微信开放社区提个问题吧~
