### ISSUE TITLE
<van-tabs>change 事件会在界面渲染时多次调用

### ISSUE THREAD

**Issue by echokh** [youzan/vant-weapp#2412]
<van-tabs>change 事件会在界面渲染时多次调用，代码如下
vanTabChange: function(event) {
    console.log("多次调用！！！")
  },
我的标签为五个，会打印四次“多次调用”

**Comment by frei-x** [comment]
我也是这样的,可能你的tab是循环出来的

**Comment by echokh** [comment]
tab循环出来是什么意思

**Comment by echokh** [comment]
> 我也是这样的,可能你的tab是循环出来的

tab循环出来是什么意思

**Comment by rex-zsd** [comment]
初始多次渲染的问题已经有修复，将在bera.5版本中放出。

**Comment by shimangdian** [comment]
已更新到1.0.2缺并没有修复

**Comment by echokh** [comment]
> 已更新到1.0.2缺并没有修复

已经修复了，你的框架更新一下

**Comment by shimangdian** [comment]
> > 已更新到1.0.2缺并没有修复
> 
> 已经修复了，你的框架更新一下

更新框架？什么意思？我使用npm update @vant/weapp 升级的

**Comment by duoWB** [comment]
请问解决了吗，使用的是1.2.2还是会出现

**Comment by echokh** [comment]
> 请问解决了吗，使用的是1.2.2还是会出现

官方已经解决了
