### ISSUE TITLE
swipe-cell 怎么监听滑动的事件

### ISSUE THREAD

**Issue by c98c** [youzan/vant-weapp#2413]
![image](https://user-images.githubusercontent.com/52164455/69714029-9692be80-1140-11ea-827e-2aeec7d1e026.png)

![image](https://user-images.githubusercontent.com/52164455/69714043-a0b4bd00-1140-11ea-93ec-9f50a91de71c.png)

获取swipecell实例后怎么弄

**Comment by rex-zsd** [comment]
如何调用自定义组件的方法请查阅微信小程序的[文档](https://developers.weixin.qq.com/miniprogram/dev/framework/custom-component/events.html)
