### ISSUE TITLE
[Feature Request] 希望swipe-cell组件左右滑动能够控制

### ISSUE THREAD

**Issue by idenet** [youzan/vant-weapp#2414]
### 这个功能解决了什么问题
比如购物车我只需要左滑删除不需要右滑

### 建议的API是什么样的
close-swipe 传入string 支持 right、left

**Comment by rex-zsd** [comment]
已经是支持的，仔细看下[文档](https://youzan.github.io/vant-weapp/#/swipe-cell#fang-fa)
