### ISSUE TITLE
[Feature Request] 请问为什么VantWeapp的组件比vant的组件少？

### ISSUE THREAD

**Issue by yunan01** [youzan/vant-weapp#2416]
### 这个功能解决了什么问题
请问为什么VantWeapp的组件比vant的组件少？未来会逐步增加么？

### 建议的API是什么样的
希望VantWeapp组件可以和vant组件数量一样多

**Comment by rex-zsd** [comment]
1.0版本将会补齐除了业务组件外的所有组件，目前已经放出beta.4版本，可以关注一下。
