### ISSUE TITLE
van-steps的active-icon 和inactive-icon的值都是数组，请问怎么写，还写字符串嘛？ctive-icon 和inactive-icon的值不是默认的图标，那怎么，文档也没有提供slot

### ISSUE THREAD

**Issue by Lightopus** [youzan/vant-weapp#2417]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater?repo=VantWeapp
<van-steps
  steps="{{ steps }}"
  active="{{ active }}"
  active-icon="success"
  active-color="#38f"
  inactive-icon=“？”
/>

**Comment by Lightopus** [comment]
van-steps的active-icon 和inactive-icon的值都是数组，请问怎么写，还写字符串嘛？ctive-icon 和inactive-icon的值不是默认的图标，<van-icon name="close" />而是通过
<van-icon name="https://b.yzcdn.cn/vant/icon-demo-1126.png" />
那怎么 active-icon 和inactive-icon的值怎么写，而且他们的值是数组
，文档也没有提供slot

**Comment by rex-zsd** [comment]
issue格式不合规范。
对使用方法有疑问的，仔细看下文档，先复制代码演示里的代码跑下看看。
