### ISSUE TITLE
[Bug Report] vant-tabs sticky属性有一定几率遮挡tab内容

### ISSUE THREAD

**Issue by jerryyan1990** [youzan/vant-weapp#2418]
### 设备
Android,微信开发者工具

### VantWeapp 版本
1.0.0-beta.3

### 基础库版本
2.9.4

### 如果是 UI 问题，截图链接（多图回车分隔）

![截图](https://i.loli.net/2019/11/28/gjVpDE3KPG4qusR.png)

![截图](https://i.loli.net/2019/11/28/jIvbDCWqAQrFcpO.png)

### 请提供核心代码片段链接
https://gist.github.com/jerryyan1990/091d784ed401718880bb43dd90ac1756

### 描述问题
如图所示，tabs使用了sticky属性后，经常会出现tabs头部遮挡了部分正文内容。暂没发现出现规律，但出现频率挺高的。

**Comment by frei-x** [comment]
降低基础库版本

**Comment by jerryyan1990** [comment]
> 降低基础库版本

使用2.8.3或者2.6.6 依然是有这个问题的，最后我试了2.9.4也有 所以填的2.9.4

**Comment by Lindysen** [comment]
请问是一开始就出现，还是滚动之后才出现这种情况

**Comment by Lindysen** [comment]
> ### 设备
> Android,微信开发者工具
> 
> ### VantWeapp 版本
> 1.0.0-beta.3
> 
> ### 基础库版本
> 2.9.4
> 
> ### 如果是 UI 问题，截图链接（多图回车分隔）
> ![截图](https://camo.githubusercontent.com/2c60299c5ae5b9d86062ecdef5986f44ef089526/68747470733a2f2f692e6c6f6c692e6e65742f323031392f31312f32382f676a56704445334b504734717573522e706e67)
> 
> ![截图](https://camo.githubusercontent.com/0ade1c2211aaff000c0d0623d3bcd4c73e448c0a/68747470733a2f2f692e6c6f6c692e6e65742f323031392f31312f32382f6a497662444357714151724663704f2e706e67)
> 
> ### 请提供核心代码片段链接
> https://gist.github.com/jerryyan1990/091d784ed401718880bb43dd90ac1756
> 
> ### 描述问题
> 如图所示，tabs使用了sticky属性后，经常会出现tabs头部遮挡了部分正文内容。暂没发现出现规律，但出现频率挺高的。

请问是一开始就出现，还是滚动之后才出现这种情况

**Comment by jerryyan1990** [comment]
被挡住的情况是一开始就出现，出现后无论滚动还是什么的依旧保持这样。

**Comment by jerryyan1990** [comment]
> > ### 设备
> > Android,微信开发者工具
> > ### VantWeapp 版本
> > 1.0.0-beta.3
> > ### 基础库版本
> > 2.9.4
> > ### 如果是 UI 问题，截图链接（多图回车分隔）
> > ![截图](https://camo.githubusercontent.com/2c60299c5ae5b9d86062ecdef5986f44ef089526/68747470733a2f2f692e6c6f6c692e6e65742f323031392f31312f32382f676a56704445334b504734717573522e706e67)
> > ![截图](https://camo.githubusercontent.com/0ade1c2211aaff000c0d0623d3bcd4c73e448c0a/68747470733a2f2f692e6c6f6c692e6e65742f323031392f31312f32382f6a497662444357714151724663704f2e706e67)
> > ### 请提供核心代码片段链接
> > https://gist.github.com/jerryyan1990/091d784ed401718880bb43dd90ac1756
> > ### 描述问题
> > 如图所示，tabs使用了sticky属性后，经常会出现tabs头部遮挡了部分正文内容。暂没发现出现规律，但出现频率挺高的。
> 
> 请问是一开始就出现，还是滚动之后才出现这种情况
被挡住的情况是一开始就出现，出现后无论滚动还是什么的依旧保持这样。

**Comment by quan01994** [comment]
我现在的解决办法 不用tabs自带的 sticky 直接在tabs外部套了一层 van-sticky 。。。

**Comment by GalaxyChueng** [comment]
> 我现在的解决办法 不用tabs自带的 sticky 直接在tabs外部套了一层 van-sticky 。。。

这样不会导致tab里面slot的内容也会变成sticky的吗

**Comment by quan01994** [comment]
> > 我现在的解决办法 不用tabs自带的 sticky 直接在tabs外部套了一层 van-sticky 。。。
> 
> 这样不会导致tab里面slot的内容也会变成sticky的吗

因为我的内容是写在tab外部的。tab只是起到一个切换。
