### ISSUE TITLE
城市三级联动显示空白

### ISSUE THREAD

**Issue by wbjeln** [youzan/vant-weapp#2420]
城市联动组件空白
wxml
<van-area
  :area-list="{{ areaList }}"
  title="选择地区"
  bind:confirm="clickArea"
  bind:cancel="closeArea"
/>
JS
var areaList = require( "../../assets/js/area.js")
console.log(areaList)
Page({
  /**
   * 页面的初始数据
   */
  data: {
    areaList: areaList,//地址表
｝

**Comment by rex-zsd** [comment]
areaList格式正确？
wxml是怎么写的？

**Comment by leehave** [comment]
建议把van-area组件文档按example里的wxml及data写出来，
`<van-area
      title="选择地址"
      columns-num="{{ 3 }}"
      loading="{{ loading }}"
      area-list="{{ areaList }}"
      :columns-placeholder="{{ ['请选择', '请选择', '请选择'] }}"
      bind:change="onChangeAddress"
      bind:confirm="onConfirmAddress"
      bind:cancel="onCloseAddress"
    />`
当wxml里的loading不声明时会出现空白情况

**Comment by wbjeln** [comment]
知道原因了 官网
可以通过columns-placeholder属性配置每一列的占位提示文字
<van-area
  :area-list="{{ areaList }}"
  :columns-placeholder="{{ ['请选择', '请选择', '请选择'] }}"
  title="标题"
/>
我复制了这里  这个应该是vue 上的  小程序没有“：” 官网建议改掉

**Comment by rex-zsd** [comment]
文档问题吗，好的，感谢反馈

**Comment by wbjeln** [comment]
还有一个问题 三级联动不流畅  卡卡的 是什么原因 其他的都正常

**Comment by rex-zsd** [comment]
试试真机上预览下，应该不会卡的
