### ISSUE TITLE
tabbar怎么整合在小程序中

### ISSUE THREAD

**Issue by 3326Bai** [youzan/vant-weapp#2421]
请问组件中的tabber怎么整合到小程序，看了小程序官网文档中的自定义tabbar的步骤，但是结合vant中的tabbar还是不知道怎么整到一块，求解答~

**Comment by rex-zsd** [comment]
文档里有代码片段，关于如何结合van-tabbar

**Comment by 3326Bai** [comment]
> 文档里有代码片段，关于如何结合van-tabbar

文档里面我都看了，小程序的自定义tabbar也看了，但是还是没有找到结合的地方，可以附上您说的详细地址吗

**Comment by changziyu** [comment]
同问，求示例

**Comment by qindj** [comment]
https://youzan.github.io/vant-weapp/#/tabbar#jie-he-zi-ding-yi-tabbar

这不是么？
