### ISSUE TITLE
[Feature Request] 希望slider组件增加区间滑动

### ISSUE THREAD

**Issue by idenet** [youzan/vant-weapp#2424]
### 这个功能解决了什么问题
比如筛选价格区间

### 建议的API是什么样的
value="[min, max]"

**Comment by candyAndBella** [comment]
附议，并且希望能有重置方法。比如初始化是【0，100】，拖动两个锚点，选择了【30，60】。然后点击了重置按钮，把值重置为【0,100】两个锚点也要同时回到0，和100的位置

**Comment by husky-wdy** [comment]
2021年8月27号，这个功能还是没有，可能是官方不维护了？

**Comment by chenjiahan** [comment]
官方还在维护，精力有限，欢迎 PR

**Comment by shenjingnan** [comment]
@wangbaiwang 已纳入1.8.4版本里程碑

**Comment by shenjingnan** [comment]
已在 `v1.8.4` 中支持
