### ISSUE TITLE
[Bug Report] Search 搜索不反应

### ISSUE THREAD

**Issue by devondahon** [youzan/vant-weapp#2427]
按照说明书关于[监听事件](https://developers.weixin.qq.com/miniprogram/dev/framework/custom-component/events.html#%E7%9B%91%E5%90%AC%E4%BA%8B%E4%BB%B6)，我下面的这个编码看起来没问题但console.log还是没反应。我百度找不到答案，vant-weapp的微信交流群也从来没反应过，所以我只能在这里重新问一下我下面的编码为什么没反应。

是vant-weapp搜索模块的BUG还是我的编码哪里要改一改？

**index.wxml**
```
<van-search value="{{ searchValue }}" bind:change="onSearch" />
```

**index.js**
```
Page({
  data: {
    searchValue: ''
  },
  onSearch: function(e) {
    console.log('onSearch...')
  }
})
```

**Comment by rex-zsd** [comment]
降低基础库到2.9.2及以下，2.9.3开发者工具有input事件不触发的bug。
