### ISSUE TITLE
[Bug Report] DropdownMenu无法获取到当前选中对象的value

### ISSUE THREAD

**Issue by cc5432165** [youzan/vant-weapp#2429]
### 设备
Android

### VantWeapp 版本
1.0.0-beta.4

### 基础库版本
2.9.4

### 请提供核心代码片段链接
https://i.loli.net/2019/11/29/mqrJgYxHheTA6XS.png

### 描述问题
按照官方代码演示中的基础代码

点击切换下拉选项时，data中value1、value2的值没有发生变化，无法获取当前选中对象的值，
也没有提供一个事件来获取当前的对象属性。

**Comment by rex-zsd** [comment]
选中选项时会触发`change`事件，看下文档说明。
