### ISSUE TITLE
zanui-weapp的样式覆盖

### ISSUE THREAD

**Issue by liuxuhui** [youzan/vant-weapp#243]
### zanui-weapp的样式覆盖

** *提交bug* **

** 例如我简单引用一个按钮：
`<zan-button type="primary">确认付款</zan-button>`

但是在具体的业务场景中，我希望覆写样式，比如我额外写了
`.zan-btn--primary｛font-size:18px｝`

会因为#shadowDom的屏蔽作用，无法生效。
组件本身也没有class的入参。
请问应该如何实现样式覆盖的操作？

**Comment by tim0991** [comment]
+1

**Comment by jianping314** [comment]
补充：只有button是这个名称引入外部样式，个别组件例如cell根本就没提供外部样式入口。

**Comment by liberty-m** [comment]
+1 样式重置不了

**Comment by liberty-m** [comment]
求解 cell 根本无法重置样式...

**Comment by yuzexing** [comment]
+1
感觉还需要结合2.0的方式使用...

**Comment by Gitsifu** [comment]
在标签中使用style属性可以修改组件部分样式

**Comment by Es201n** [comment]
求救，手贱升级了2.0，现在样式成一坨si了，求救啊

**Comment by laravuel** [comment]
都解决了吗？组件样式无法修改还怎么玩？完全不能愉快玩耍了

**Comment by harryliuy** [comment]
组件自定义样式有没有DEMO，试了几种可能的写法都不行啊。。

**Comment by chenjiahan** [comment]
目前 zanui-weapp 已进行全新的品牌升级，更名为 Vant Weapp，组件和 API 都有较大的变化。

对 zanui-weapp 的讨论，请移步至 https://github.com/youzan/zanui-weapp 仓库
