### ISSUE TITLE
[Bug Report] 子页面使用van-tabs,，返回上级页面后报错：Cannot read property 'getComputedName' of undefined

### ISSUE THREAD

**Issue by zhi-jian** [youzan/vant-weapp#2433]
### 设备
微信开发者工具

### VantWeapp 版本
1.0.0-beta.4

### 基础库版本
2.8.1

### 请提供核心代码片段链接
https://developers.weixin.qq.com/s/fy44ffmj78dI

### 描述问题
微信小程序原生写法，子页面使用的van-tabs，点击手机左上角自带的返回按钮，返回到上一级页面时报错：```
Cannot read property 'getComputedName' of undefined;at api nextTick callback function；
TypeError: Cannot read property 'getComputedName' of undefined；
at ye.trigger (http://127.0.0.1:55721/appservice/npm/vant-weapp/dist/tabs/index.js:146:21)
    at Function.<anonymous> (http://127.0.0.1:55721/appservice/npm/vant-weapp/dist/tabs/index.js:204:16)
```

**Comment by rex-zsd** [comment]
1.0.0-beta.5已经修复了，可以升级下试试

**Comment by zhi-jian** [comment]
谢谢，1.0.0.5可以正常使用了

**Comment by zhi-jian** [comment]
> 谢谢，1.0.0.5可以正常使用了

？

**Comment by zhi-jian** [comment]
> 1.0.0-beta.5已经修复了，可以升级下试试

谢谢，1.0.0-beta.5可以正常使用了

**Comment by SaveUpStrength** [comment]
找了好久，百度根本找不出问题

**Comment by zhi-jian** [comment]
> 找了好久，百度根本找不出问题

1.0.0-beta.5 版本已经修复了，你重新下载试试

**Comment by jamccc** [comment]
![image](https://user-images.githubusercontent.com/33343495/70383127-baa59980-19a3-11ea-9ce3-36f4e884cc0f.png)
没有1.0.0-beta.5这个版本呀

**Comment by jamccc** [comment]
用npm view 没有看到1.0.0-beta.5这个版本呀

**Comment by rex-zsd** [comment]
@jamccc 看下文档 是@vant/weapp

**Comment by zhi-jian** [comment]
> 用npm view 没有看到1.0.0-beta.5这个版本呀

https://youzan.github.io/vant-weapp/#/popup   打开这个，在右上角有版本
