### ISSUE TITLE
[Bug Report] tabs组件BUG

### ISSUE THREAD

**Issue by alexshu11** [youzan/vant-weapp#2435]
### VantWeapp 版本
1.0.0-beta.5

### 描述问题
(1小时前才更新的beta5)

虽然beta4中tabs组件的index无法动态绑定的问题在beta5中得到了解决, 但是在tab中使用dialog popup等组件时, 模态框只会出现在第一个tab页面中, 在其他tab中并不会出现模态框. 也不会出现任何position为fix的组件. 都只会出现在第一个tab页面中.

**Comment by rex-zsd** [comment]
没理解的很具体…………按issue格式提供下代码和截图吧~

**Comment by alexshu11** [comment]
如果在第二个tab页面点击开启对话框操作(如下图),包括dialog popup等,均无反应, 包括position为fixed的元素,  均不可见
![image](https://user-images.githubusercontent.com/28819872/69925611-1a0b3180-14ec-11ea-9e52-3897f2182b76.png)
但是切换到第一个tab页面时, 对话框出现了.... 
![image](https://user-images.githubusercontent.com/28819872/69925675-58085580-14ec-11ea-8d63-250a1ffdfa80.png)

**Comment by LookMeLovely** [comment]
是啊，坑死了，上次还好好的，突然就不行了，第二个tab页有一个下拉框，拉开后出现在第一个tab页，服了

**Comment by LookMeLovely** [comment]
这个bug也太扯了，下拉不能在tab标签里用根本

**Comment by LookMeLovely** [comment]
beta3是可以的，但是图片上传选择后真机不能多选，beta4图片选择是ok的，但是tab标签中不可以使用下拉组件了，样式会彻底错乱

**Comment by rex-zsd** [comment]
![d7kiv-j9a3g](https://user-images.githubusercontent.com/8767877/69946878-66c02e00-1527-11ea-822d-f97a6385a2f8.gif)
@alexshu11 尝试了一下你说的几个场景，没发现有什么问题，是不是使用姿势的问题？

**Comment by alexshu11** [comment]
在使用beta4的时候确实是没有这个问题的...  但是在beta5中就出现了...  重写了demo还是有这个问题... 
  只能通过把tab里的页面拿出来用if来曲线救国才能解决这个...  @rex-zsd

**Comment by alexshu11** [comment]
是在加入了动画属性animated后出现的这个问题,如果去掉这个属性恢复了正常...  还有在加入sticky属性后下拉会有闪动...  @rex-zsd

**Comment by rex-zsd** [comment]
开启`animated`后，下面的内容区会用transform来控制当前显示位置，会影响`fixed`元素的表现。

**Comment by rex-zsd** [comment]
如果内容中包含`fixed`元素的，推荐不要开启`animated`属性。
因为`transform`、`will-change`这些动画所需的样式属性都会影响`fixed`元素的。
@alexshu11
