### ISSUE TITLE
npm 命令引入，引入的组件不全

### ISSUE THREAD

**Issue by 14778** [youzan/vant-weapp#2436]
使用npm i @vant/weapp -S --production引入，文件夹有些组件没有下载下来。例如uploader组件，siderbar组件等

**Comment by zx870283980** [comment]
一样遇到了

**Comment by v0per** [comment]
是的，+1

**Comment by felixglow** [comment]
+1，我是下载zip包，然后拷贝到小程序里了

**Comment by rex-zsd** [comment]
确认下版本是不是1.0.0-beta.5吧
install检查了一下都是有的……
