### ISSUE TITLE
icon命名

### ISSUE THREAD

**Issue by exelin** [youzan/vant-weapp#2437]
有点尴尬，也许不算什么问题，但是我确实遇到了。

icon里奖牌的英文，一眼瞄过去就直接用了，结果不显示，排查好久，发现我写的是medal，而咱们的名字是medel

遇到这个问题折磨一些时间，确实比较难堪。命名当然可以随便安排，不过反常识还是会影响体验，所以提出来作为参考。辛苦

**Comment by chenjiahan** [comment]
这里确实是一个拼写错误 🤣 我们会在后续版本添加正确拼写的名称，同时兼容原有的名称

**Comment by rex-zsd** [comment]
哈哈哈 😃
