### ISSUE TITLE
van-button 组件无法关联小程序的form 表单组件，vant框架中没有对应的form组件，导致表单处理这一块不是很顺畅

### ISSUE THREAD

**Issue by lebornjose** [youzan/vant-weapp#2438]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

```wxml
  <form bindsubmit="formSubmit">
       <van-field center clearable label="手机号" placeholder="请输入手机号"
               type="number"
            > </van-field>
          <van-button type="info" form-type='submit'>保存设置</van-button>
  </form>
```

>   formSubmit 方法无法被触发。
>  将van-button 换成小程序的button 则可以触发 formSubmit 方法

https://youzan.github.io/vant-issue-generater?repo=VantWeapp

**Comment by rex-zsd** [comment]
表单组件都是带了表单behavior的，看下原生表单相关的文档吧~
还有自定义组件是无法支持`form-type`的，参考微信小程序的文档。
