### ISSUE TITLE
1.0.0-beta.5 wepy框架使用van-dialog async-close不管用

### ISSUE THREAD

**Issue by guanmu666** [youzan/vant-weapp#2439]
<van-dialog
      use-slot="true"
      width="640rpx"
      height="1200rpx"
      show="{{ photorDialog }}"
      :show-cancel-button="true"
      async-close=‘true’
      bind:close="photorClose"
      bind:confirm="selectPhoter"
    >

**Comment by rex-zsd** [comment]
`async-close`接受的是`boolean`类型，要么传`async-close`，要么传`:async-close='true'`
