### ISSUE TITLE
beta4，tab标签不能使用下拉，beta3图片上传只能选择单张

### ISSUE THREAD

**Issue by LookMeLovely** [youzan/vant-weapp#2442]
beta4：tab标签中不可以使用下拉组件，当第二个tab中使用下拉，点击后，下拉列表会出现在第一个tab页中，
beta3：图片上传不能选择多张，每次只能选择一张

**Comment by LookMeLovely** [comment]
太扯了，最后选择了beta3，但是图片上传组件不能选择单张，beta5无法npm下载，报错，beta4和3是可以下载的

**Comment by LookMeLovely** [comment]
beta4的tab标签还总是报错，TypeError: Cannot read property 'getComputedStyle' of undefined

**Comment by LookMeLovely** [comment]
beta4中的tab标签吸顶功能，当页面启用上拉加载时，吸顶会在添加数据是失效，被拉上去，beta3没有遇到这种问题

**Comment by LookMeLovely** [comment]
beta3，弹出框，确认按钮少半截

**Comment by rex-zsd** [comment]
tab组件的问题和图片不能上传多张的问题在beta.5都有修复了，升级到beta.5就可以了。

**Comment by rex-zsd** [comment]
升级不上去的问题，你看下你指向的npm源是不是没有同步最新的beta.5资源。
