### ISSUE TITLE
new Date(). getTime()获取毫秒单位时间戳，用倒计时，还需要转换吗？

### ISSUE THREAD

**Issue by zx870283980** [youzan/vant-weapp#2443]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater?repo=VantWeapp

**Comment by rex-zsd** [comment]
没看懂issue的标题，`time`应该传的是倒数时间的毫秒数，没看出跟`new Date(). getTime()`有什么关系。
