### ISSUE TITLE
【BUG REPORT】<van-tab>标签下Popup弹出层高度会随内容增加而变化

### ISSUE THREAD

**Issue by echokh** [youzan/vant-weapp#2445]
【BUG REPORT】<van-tab>标签下Popup弹出层高度会随内容增加而变化

**Comment by echokh** [comment]
例如在页签1下有10条数据，整个弹出层的最下方会在第10条数据处，一旦到达最底部数据上拉刷新，弹出层会急促扩大

**Comment by rex-zsd** [comment]
没代码没截图，很难理解你的意思。
光看字面意思，popup高度随内容高度变化而变化很正常吧？不希望这样的话给列表套个容器限定高度就可以了。
