### ISSUE TITLE
[Feature Request] Vant-weapp search组件的disabled和readonly属性优化建议

### ISSUE THREAD

**Issue by Hyejeongdd** [youzan/vant-weapp#2448]
### 这个功能解决了什么问题
disabled 是禁用输入框 readonly是只读 两者在UI的表现是一样的 当这两种属性启用时 所有的Event都不会执行 个人以为disabled属性时所有Event都不会执行 而readonly的时候 Event时可以执行的 比如说bind:focus 

### 建议的API是什么样的
disabled = true , 不执行event ，readonly = true , 执行event

**Comment by rex-zsd** [comment]
`disabled`和`readonly`在事件上的差异化目前还是受限于原生input没有`readonly`属性，无法实现。
目前仅仅是在样式上有做区分。
