### ISSUE TITLE
[Bug Report] Overlay组件未实现"嵌入内容"功能

### ISSUE THREAD

**Issue by WhiteMinds** [youzan/vant-weapp#2449]
### 设备
安卓

### VantWeapp 版本
1.0.0-beta.4

### 基础库版本
2.6.6

### 请提供核心代码片段链接
https://gist.github.com/WhiteMinds/83aa2629f4b5f05f27525d02a90b3d88

### 描述问题
查看了该组件的实现代码, 其中并未实现slot

**Comment by rex-zsd** [comment]
文档里是未提供slot的，组件实例使用的是vant的，顶部已标明会有部分出入。

**Comment by WhiteMinds** [comment]
@rex-zsd 这个slot不太好实现吗, 感觉没有slot的话, 似乎用途不多..

**Comment by rex-zsd** [comment]
应该可以支持的
没有slot也差不多吧，可以把overlay放在后面，再用内容覆盖上去，可以参考下van-popup的实现。

**Comment by mihuartuanr** [comment]
……同样的疑惑，不能嵌入的遮罩…
