### ISSUE TITLE
[Feature Request] slider的value除了是百分比，是不是还可以支持传值？

### ISSUE THREAD

**Issue by lopaz** [youzan/vant-weapp#2450]
当前：value是当前进度百分比，取值范围为 0-100

虽然百分比和值之间可以转换，但有的时候这种转换是没有必要的，比如做音频播放的进度条，(min, max) = (0, 120) 120表示时长两分钟，需要监听播放器播放进度然后来更新进度条，播放器给的是当前播放的位置，比如10s, 110s，直接给value赋值10, 110是特别自然的事情，要转换成百分比有点别扭。

建议：
  增加一个percent属性，用来表示百分比；
  value表示当前值；
这样两种就都能支持了，根据使用场景选择最合适用就行。

**Comment by rex-zsd** [comment]
还是麻烦换算一下吧，要做值的话需要另一套`max` `min` `value`了，感觉不是很有必要。
