### ISSUE TITLE
[Bug Report] van-image组件在beta.4升级beta.5版本 ios出现问题

### ISSUE THREAD

**Issue by sonofmagic** [youzan/vant-weapp#2459]
### 设备
iphone 7 plus

### VantWeapp 版本
1.0.0-beta.4

### 基础库版本
2.9.1

### 请提供核心代码片段链接
https://codepen.io/sonofmagic/pen/yLyyPLm

### 描述问题
从1.0.0 beta.4 -> beta.5 发现原先4显示出来的图像，5显示不出来了，ios有这个问题，安卓没有，真机调试之后，发现ios 进入了onError里面，使用原生的image一直是好的。

**Comment by SunXingZ** [comment]
我也遇到这个问题,原因是:在iOS真机上,如果image组件设置了webp="{{true}}",则会在图片的src前追加webp字符串,即图片的src="webphttps://image.xxx.cn",在van-image组件中默认是设置了webp属性的,所以加载这样的链接会触发onError事件导致显示不了图片,实际上这个时候如果图片本身是webp格式的是可以正常显示出来的,只不过wx:if="{{!error}}"隐藏了,如果图片格式不是webp格式的,则始终不会显示,因为链接加上webp之后访问不到.
