### ISSUE TITLE
[Bug Report] tabs组件BUG

### ISSUE THREAD

**Issue by Airam1016** [youzan/vant-weapp#2467]
### 设备
iphone6

### VantWeapp 版本
1.0.0-beta.4

### 基础库版本
2.9.4

### 如果是 UI 问题，截图链接（多图回车分隔）

![11.jpg](https://i.loli.net/2019/12/04/UQnOCe24BZoG1vD.jpg)

![22.jpg](https://i.loli.net/2019/12/04/xPIfQNtqyjWhzR1.jpg)

![33.jpg](https://i.loli.net/2019/12/04/Ms7ydEbpIiShzok.jpg)

### 请提供核心代码片段链接
https://gist.github.com/Airam1016/2b213b4cc6640f9a0c96b0862dad4250

### 描述问题
tabs组件使用sticky属性后，数据异步加载写入，吸顶效果会消失，并且在页面初始化时，bind:change事件多次触发

**Comment by rex-zsd** [comment]
多次触发的问题在beta.5有修复，可以升级一下

**Comment by rex-zsd** [comment]
遮挡的问题与 #2418 重复了，先关闭了。
