### ISSUE TITLE
[Bug Report] button的block属性，发生了冲突

### ISSUE THREAD

**Issue by wangzj141** [youzan/vant-weapp#2468]
### 设备
iPhone X

### VantWeapp 版本
0.5.24

### 基础库版本
2.9.4

### 如果是 UI 问题，截图链接（多图回车分隔）

![截图](https://i.loli.net/2019/12/04/1mH6gKjZXbQyhoE.png)

![截图](https://i.loli.net/2019/12/04/BIdTOnzLfMyjGxc.png)

![截图](https://i.loli.net/2019/12/04/cVyj4sYulZxAknH.png)

![截图](https://i.loli.net/2019/12/04/31aVCcs2GQNY9Dh.png)

### 请提供核心代码片段链接
https://gist.github.com/wangzj141/a4e9093a3c2fae5168bad543fd227237

### 描述问题
使用了block属性，但是无效。查了一下原因，应该是下面这个样式的优先级大于block的
button: not([size='mini']) {}

**Comment by rex-zsd** [comment]
这个`button:not([size='mini'])`的样式，是你自己写的吧…………
这个应该不是vant-weapp的问题，你改下代码不要覆盖就可以了。

**Comment by qiyu2580** [comment]
![image](https://user-images.githubusercontent.com/1301580/70374220-4202f680-192b-11ea-9017-8340216ca626.png)

在app.json文件中把"style": "v2"去了
