### ISSUE TITLE
[Bug Report] textarea上面被遮挡

### ISSUE THREAD

**Issue by fang7665955** [youzan/vant-weapp#2469]
### 设备
本地测试 iphone

### VantWeapp 版本
1.0.0-beta.4

### 基础库版本
2.9.2

### 如果是 UI 问题，截图链接（多图回车分隔）

![截图](https://user-images.githubusercontent.com/30946999/70063454-c0f1e980-1622-11ea-9963-57a29200511c.png)

### 请提供核心代码片段链接
https://i.loli.net/2019/12/04/FLrZnaqzKcu8NbP.png

### 描述问题
textarea最上面被遮挡

**Comment by rex-zsd** [comment]
不确定这个是否是原生textarea就有的bug，能否修复存疑

**Comment by GPPoseidon999** [comment]
官方组件有样式问题在修复中
https://developers.weixin.qq.com/community/develop/issue/177
https://developers.weixin.qq.com/community/develop/issue/96
在修复列表的3 4页
https://developers.weixin.qq.com/community/develop/issueList?page=4&type=%E4%BF%AE%E5%A4%8D%E4%B8%AD&block=bug

**Comment by abrahamgreyson** [comment]
问题在微信开发者工具中存在，基础库 2.7.7， 但是在 iPhone 中不存在。

**Comment by VitalLzj** [comment]
<img width="448" alt="图片" src="https://user-images.githubusercontent.com/19515035/75131285-385c8400-570d-11ea-854d-92410524d05c.png">
ios上的样式目测就出现在这个css上
