### ISSUE TITLE
关于button的固定宽度问题

### ISSUE THREAD

**Issue by yangnum** [youzan/vant-weapp#2473]
新版本中button有了固定最小宽度，在很多组件中样式会错乱 比如GoodsAction。后续有没有计划修复这个问题呢

**Comment by rex-zsd** [comment]
具体是怎么个错乱法？目前看demo中是ok的
可以贴下图和代码看下~

**Comment by yangnum** [comment]
![bottonbug](https://user-images.githubusercontent.com/47867962/70201992-25ac6180-1753-11ea-8889-554c0cc625d4.png)

`  <van-goods-action>
    <van-goods-action-icon icon="shop-o" text="首页" bind:click="onClickIcon" />
    <van-goods-action-icon icon="cart-o" text="购物车" bind:click="onClickIcon" />
    <van-goods-action-icon icon="like-o" text="收藏" />
    <van-goods-action-button size="large" text="加入购物车" type="warning" />
    <van-goods-action-button size="large" text="立即购买" />
  </van-goods-action>`

**Comment by yangnum** [comment]
http://oayalan.178mr.com/bottonbug.png
[http://oayalan.178mr.com/bottonbug.png](url)

**Comment by yangnum** [comment]
@rex-zsd http://oayalan.178mr.com/bottonbug.png

**Comment by rex-zsd** [comment]
很奇怪，van-goods-action-button是没有`size`属性的
而且van-goods-action-button的UI样式看起来与demo中不太一样
可以确认一下代码引入版本什么的是不是有问题
![image](https://user-images.githubusercontent.com/8767877/70202413-9011d180-1754-11ea-886f-57e5cc1a61aa.png)

**Comment by chenjiahan** [comment]
是不是设置了微信样式 "style": "v2，可以去掉试试

**Comment by yangnum** [comment]
@chenjiahan 好像是的， 谢谢啊

**Comment by rex-zsd** [comment]
🤕 看来兼容v2要提上日程了，进展可以关注下 #1937 这个issue。
