### ISSUE TITLE
DropdownMenu 前端动态赋值，Title怎么跟着变动Name

### ISSUE THREAD

**Issue by w1243347117** [youzan/vant-weapp#2474]
DropdownMenu 前端动态赋值，Title怎么跟着变动Name，类似于用js模拟下拉框选择事件

**Comment by rex-zsd** [comment]
动态传入选项对应的value，title位置会自动显示对应选项的text的。

**Comment by w1243347117** [comment]
option1: [
      { text: 'TCP/UDP', value: -1 },
      { text: 'TCP', value: 0 },
      { text: 'UDP', value: 1 }
    ],
dropValue1: -1,
通过前端设置选项值的时候title并不会变动
this.setData({ dropValue1: 1 });

**Comment by rex-zsd** [comment]
可以确认下版本是不是 1.0.0-beta.6 哈，之前的版本不支持动态设置`value`属性。

**Comment by w1243347117** [comment]
什么时候升的级，我昨天才刚更新到5.0,刚刷新了一下可以看到到6.0的更新记录了

**Comment by rex-zsd** [comment]
上午刚发的哈，可以升级一下

**Comment by w1243347117** [comment]
好的 谢谢
