### ISSUE TITLE
DropdownMenu 下拉卡顿

### ISSUE THREAD

**Issue by kcssc** [youzan/vant-weapp#2477]
### 设备
华为荣耀9

### VantWeapp 版本
0.5.24

### 基础库版本
1.0.0-beta.6

### 请提供核心代码片段链接
https://www.baidu.com/

### 描述问题
DropdownMenu  下拉卡顿 延时3秒 1.0.0-beta.6才出现的，1.0.0-beta.4原先没有这种情况

**Comment by rex-zsd** [comment]
可以提供下核心代码和传参吗？我们在对应数据下复现下问题。

**Comment by kcssc** [comment]
<van-dropdown-menu>
  <van-dropdown-item value="{{ value1 }}" options="{{ option1 }}" />
  <van-dropdown-item value="{{ value2 }}" options="{{ option2 }}" />
</van-dropdown-menu>
Page({
  data: {
    option1: [
      { text: '全部商品', value: 0 },
      { text: '新款商品', value: 1 },
      { text: '活动商品', value: 2 }
    ],
    option2: [
      { text: '默认排序', value: 'a' },
      { text: '好评排序', value: 'b' },
      { text: '销量排序', value: 'c' }
    ],
    value1: 0,
    value2: 'a'
  }
});
官网的这个例子 在我手机上下拉卡的不行

**Comment by rex-zsd** [comment]
是预览吗，还是真机调试？
如果是真机调试的，可以试试用预览，真机调试的时候UI是会比正常慢很多的。

**Comment by kcssc** [comment]
感谢，我打开的环境是 真机调试，预览挺顺畅的；
另外 预览环境下，组件的引用写在app.json里，白屏，一直三个点加载，把组件引用分别写在页面上才可正常预览。是小程序本身的兼容问题吗

**Comment by rex-zsd** [comment]
不确定是什么问题，可以看下console面板有没有什么提示或者报错，或者请下缓存，关闭开发者工具重新打开试试。
