### ISSUE TITLE
van-picker 组件怎么设置选中项的颜色？其他未选中项的颜色？

### ISSUE THREAD

**Issue by rewiner** [youzan/vant-weapp#2478]
van-picker 组件怎么设置选中项的颜色？其他未选中项的颜色？

类名 | 说明
-- | --
custom-class | 根节点样式类
active-class | 选中项样式类
toolbar-class | 顶部栏样式类
column-class | 列样式类

外部的样式类只有custom-class有效，其他无效。

**Comment by rex-zsd** [comment]
小程序的外部样式类作用优先级是不确定的，一般都需要在后面加`!important`保证优先级。

**Comment by rewiner** [comment]
谢谢！嗯，可以。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"rex"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月5日(星期四) 下午4:03
收件人:&nbsp;"youzan/vant-weapp"<vant-weapp@noreply.github.com&gt;;
抄送:&nbsp;"广州网站建设"<1615050687@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [youzan/vant-weapp] van-picker 组件怎么设置选中项的颜色？其他未选中项的颜色？ (#2478)




小程序的外部样式类作用优先级是不确定的，一般都需要在后面加!important保证优先级。

**Comment by zhangmingwalker1633** [comment]
我设置 pickerBackgroundColor: '#2d2a4a', 不生效，蒙层的颜色怎么设置可以使未选中的区域渐变色趋近于黑色背景色.
pickerMaskColor和pickerLoadingMaskColor设置颜色不生效
![image](https://user-images.githubusercontent.com/33444081/166952662-3b34c2aa-82d8-4708-8279-6185043b99f5.png)
