### ISSUE TITLE
点击小程序左上角返回,tab会报错Cannot read property 'getComputedName' of undefined;at api nextTick callback function TypeError: Cannot read property 'getComputedName' of undefined

### ISSUE THREAD

**Issue by ZMPSophia** [youzan/vant-weapp#2480]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater?repo=VantWeapp
![image](https://user-images.githubusercontent.com/29793307/70219142-44285200-177f-11ea-9ee1-e7212e909b3d.png)
![image](https://user-images.githubusercontent.com/29793307/70219743-4ccd5800-1780-11ea-84a6-63e827bc8c09.png)
VM111028:1 thirdScriptError
Cannot read property 'getComputedName' of undefined;at api nextTick callback function
TypeError: Cannot read property 'getComputedName' of undefined
    at be.trigger (http://127.0.0.1:17431/appservice/miniprogram_npm/@vant/weapp/tabs/index.js:147:29)
    at Function.<anonymous> (http://127.0.0.1:17431/appservice/miniprogram_npm/@vant/weapp/tabs/index.js:200:24)
    at http://127.0.0.1:17431/appservice/__dev__/WAService.js:1:125668
    at Function.Lp (http://127.0.0.1:17431/appservice/__dev__/WAService.js:1:998368)
    at http://127.0.0.1:17431/appservice/__dev__/WAService.js:1:125668
    at http://127.0.0.1:17431/appservice/__dev__/WAService.js:1:96246

**Comment by rex-zsd** [comment]
可以升级到最新版本beta.6，这个报错的问题在beta.5修复了。
