### ISSUE TITLE
[Bug Report] open-type属性为share的button点击后回调值内的dataset为空

### ISSUE THREAD

**Issue by Skura23** [youzan/vant-weapp#2483]
设备
本地测试 iphone

VantWeapp 版本
1.0.0-beta.4

基础库版本
2.9.2

如果是 UI 问题，截图链接（多图回车分隔）
截图

请提供核心代码片段链接

描述问题
Button组件问题, button设置open-type属性为share时, 点击button触发onShareAppMessage事件, 事件回调值内dataset为空

期望:
期望能像小程序一样点击open-type属性为share的按钮后, 在onShareAppMessage里能获取到绑定在button上的data-相关值

**Comment by MartinLongYW** [comment]
能说说为什么携带不了参数么，在share状态下，不携带参数，在列表类分享无法实现分享功能，只能使用原生的按钮。

**Comment by rex-zsd** [comment]
> 能说说为什么携带不了参数么，在share状态下，不携带参数，在列表类分享无法实现分享功能，只能使用原生的按钮。

触发节点的问题哈

**Comment by zq12580** [comment]
问题有解决吗  目前还是携带不了  求正确携带方式
