### ISSUE TITLE
[Bug Report] 构建脚本问题

### ISSUE THREAD

**Issue by guojingwen** [youzan/vant-weapp#2484]
### 设备
window电脑

### VantWeapp 版本
1.0.0-beta.4

### 基础库版本
2.8.2

### 请提供核心代码片段链接
https://github.com/youzan/vant-weapp/blob/dev/build/compiler.js

### 描述问题
gulp.watch 在window电脑上有兼容性问题，npm run dev的时候文件不会触发监听，应该使用'gulp-watch'

**Comment by rex-zsd** [comment]
看了一下`gulp-watch`已经2年没有更新了，应该不会使用这个了……
