### ISSUE TITLE
重置组件的样式 老是无效啊 能不能给个说明！

### ISSUE THREAD

**Issue by Y-ching** [youzan/vant-weapp#2485]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater?repo=VantWeapp

**Comment by rex-zsd** [comment]
外部样式类的优先级是未定的，需要加`!important`，这一点微信小程序的官方文档已经明确说明了，可以查阅一下。

**Comment by Y-ching** [comment]
好的 谢谢


| |


|
|
yangchin9@126.com
|
签名由网易邮箱大师定制
在2019年12月6日 13:45，rex<notifications@github.com> 写道：

外部样式类的优先级是未定的，需要加!important，这一点微信小程序的官方文档已经明确说明了，可以查阅一下。
