### ISSUE TITLE
[Bug Report] Loading 不显示文字

### ISSUE THREAD

**Issue by Skura23** [youzan/vant-weapp#2487]
### 设备
调试器 ios 安卓

### VantWeapp 版本
0.5.23

### 基础库版本
2.9.2

### 请提供核心代码片段链接
https://gist.github.com/

### 描述问题
<van-loading size="24px">加载中...</van-loading> 这段代码, 渲染到页面上时不显示标签内文字'加载中...'

**Comment by rex-zsd** [comment]
Loading支持slot是1.0.0新增的功能哈，0.x 版本的不支持的。
可以升级一下到1.0.0-beta版本，近期将会发布1.0.0正式版。
