### ISSUE TITLE
[BUG REPORT] <van-tabs>中sticky失效问题

### ISSUE THREAD

**Issue by echokh** [youzan/vant-weapp#2488]
[新建文本文档.txt](https://github.com/youzan/vant-weapp/files/3930677/default.txt)
代码结构见文档

**Comment by rex-zsd** [comment]
用法看着很奇怪，`van-tabs`里没有用`van-tab`吗？

**Comment by echokh** [comment]
> 用法看着很奇怪，van-tabs里没有用van-tab吗？
 sorry,代码没处理好
[新建文本文档.txt](https://github.com/youzan/vant-weapp/files/3930748/default.txt)

**Comment by rex-zsd** [comment]
几个变量的内容也贴一下吧，isDataInited、busiList这些


 原始邮件 
发件人: echokh<notifications@github.com>
收件人: youzan/vant-weapp<vant-weapp@noreply.github.com>
抄送: rex<rexkaneki@gmail.com>; Comment<comment@noreply.github.com>
发送时间: 2019年12月6日(周五) 14:42
主题: Re: [youzan/vant-weapp] [BUG REPORT] <van-tabs>中sticky失效问题 (#2488)


用法看着很奇怪，van-tabs里没有用van-tab吗？
 sorry,代码没处理好
 新建文本文档.txt

**Comment by echokh** [comment]
> 几个变量的内容也贴一下吧，isDataInited、busiList这些
将界面数据一并发送，谢谢
[新建文本文档.txt](https://github.com/youzan/vant-weapp/files/3930772/default.txt)

**Comment by rex-zsd** [comment]
![oc2xf-h1xwi](https://user-images.githubusercontent.com/8767877/70385968-33215000-19ce-11ea-88b1-b978c572619b.gif)
用你的代码和数据没有复现问题，建议再检查一下 @vant/weapp 的版本吧。

**Comment by W-tomoe** [comment]
遇到同样问题，请问你解决了吗

**Comment by echokh** [comment]
> 遇到同样问题，请问你解决了吗

对的，我这个也是这样的问题，还在研究

**Comment by maplehsu** [comment]
异步加载数据这个sticky 还没解决吗？ 我们自己解决也改不了官方库啊关键是
