### ISSUE TITLE
1.0.0-beta.4版本使用tabs 跟tab标签，从二级页面返回一级页面的时候报错，切回0.x版本不会

### ISSUE THREAD

**Issue by 14778** [youzan/vant-weapp#2490]
报错信息如下：

Cannot read property 'getComputedName' of undefined;at api nextTick callback function
TypeError: Cannot read property 'getComputedName' of undefined

**Comment by rex-zsd** [comment]
升级到最新的 @vant/weapp@1.0.0-beta.6版本可解决哈

**Comment by imziyang** [comment]
@rex-zsd  好像 beta.6 版本还没有更新到 npm
