### ISSUE TITLE
van-tabs 上面有其他视图。在滑动到上面一部分点击的时候 。会进行乱跳

### ISSUE THREAD

**Issue by homeabc** [youzan/vant-weapp#2491]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater?repo=VantWeapp

**Comment by homeabc** [comment]
![屏幕快照 2019-12-06 下午4 34 06](https://user-images.githubusercontent.com/22024211/70308451-41dcfb00-1846-11ea-897d-b0675724796d.png)

**Comment by rex-zsd** [comment]
这个静态图，想说明什么呢？
