### ISSUE TITLE
[Feature Request] 为 SwipeCell 组件添加通过 open 方法主动打开单元格的示例

### ISSUE THREAD

**Issue by rex-zsd** [youzan/vant-weapp#2494]
### 这个功能解决了什么问题
目前组件文档中缺少 open 方法的示例，待完善

### 建议的API是什么样的
在 example 中添加通过 open 方法主动打开单元格的示例

在 README.md 中添加通过 open 方法主动打开单元格的代码示例

**Comment by candyAndBella** [comment]
vant-weapp 也需要这个功能，通过点击，调用open，打开单元格

**Comment by candyAndBella** [comment]
mpvue开发微信小程序，引入了vant-wepap的van-swipe-cell组件，想要调用open方法。不知道怎么调用。以下方法会报错
this.selectComponent('#mySwipe').open('right');
