### ISSUE TITLE
骨架屏的row啥时候可以自定义高度

### ISSUE THREAD

**Issue by 14778** [youzan/vant-weapp#2495]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater?repo=VantWeapp

**Comment by rex-zsd** [comment]
issue格式不规范。
Vant Weapp 所有的组件都添加了 `addGlobalClass: true`，接受外部修改，可以查阅下相关微信文档。
