### ISSUE TITLE
mpvue中使用van-uploader，无法触发事件

### ISSUE THREAD

**Issue by teri5354** [youzan/vant-weapp#2500]
1、在mpvue中使用van-uploader组件，bind:before-read="test"修改@efore-read="test"
2、use-before-read为true
选择图片后，无法进入到test函数中，测试了after-read也是一样的

**Comment by rex-zsd** [comment]
mpvue不支持事件名中间带`-`的，mpvue未修复这个bug前，只能自行修改vant-weapp源码。
