### ISSUE TITLE
[Feature Request] 希望可以用rpx来规范小程序

### ISSUE THREAD

**Issue by deajax** [youzan/vant-weapp#2502]
### 这个功能解决了什么问题
rpx可以使各个终端设备的分辨率和UI能尽量的保持一致性。

### 建议的API是什么样的
希望可以用rpx来规范小程序，这样能使各个终端设备的分辨率和UI能尽量的保持一致性。否则在小设备入iphone5下，字体会变得很大，且很多内容会超出。

**Comment by rex-zsd** [comment]
暂时不会考虑用rpx，需要rpx的可以用postcss插件自行转换。
搜索一下历史issue有详细说明。
