### ISSUE TITLE
关于DropdownMenu  

### ISSUE THREAD

**Issue by bcmaidou** [youzan/vant-weapp#2505]
我在mpvue下使用vant-weapp时，用到了DropdownMenu  这个组件，进行了数据绑定。但是初始化页面时，页面没有转中值
![微信截图_20191209111911](https://user-images.githubusercontent.com/36757019/70404690-d2e5e900-1a75-11ea-8dea-42118e0a71f8.png)
![微信截图_20191209111930](https://user-images.githubusercontent.com/36757019/70404691-d37e7f80-1a75-11ea-85b2-cf89faa786c4.png)
![微信截图_20191209111944](https://user-images.githubusercontent.com/36757019/70404692-d4171600-1a75-11ea-83c4-bdc60ea50a46.png)

**Comment by rex-zsd** [comment]
可以升级下@vant/weapp到最新的1.0.0-beta.6，这个问题已经修复了的。
