### ISSUE TITLE
van-submit-bar iponex的适配问题

### ISSUE THREAD

**Issue by yangnum** [youzan/vant-weapp#2507]
<van-submit-bar price="{{ 3050 }}" safe-area-inset-bottom="{{true}}" button-text="提交订单" bind:submit="onSubmit" />

在iphone11 上是这样的。。。。
![微信图片_20191209192115](https://user-images.githubusercontent.com/47867962/70431956-16ae1200-1ab9-11ea-884c-dccaaf16a12e.jpg)

**Comment by yangnum** [comment]
<van-submit-bar price="{{ 3050 }}" safe-area-inset-bottom="{{true}}" button-text="提交订单" bind:submit="onSubmit" />

**Comment by rex-zsd** [comment]
看下是不是受外部样式的影响？
