### ISSUE TITLE
button的size只能控制文字大小，不能控制按钮大小

### ISSUE THREAD

**Issue by rjhan** [youzan/vant-weapp#2509]
button的size只能控制文字大小，不能控制按钮大小

**Comment by keventseng** [comment]
我今天也发现了，好像是没有覆盖user agent stylesheet导致的。

**Comment by rjhan** [comment]
> 我今天也发现了，好像是没有覆盖user agent stylesheet导致的。

我把  app.json 里面的"style": "v2" 取消掉就好了，貌似还没有对升级后的UI做兼容

**Comment by rex-zsd** [comment]
#1937
