### ISSUE TITLE
tabs的三个bug，1.sticky无效。 2.滚动某个tab内容，其他tab的内容也会滚动。3.切换tab再返回无法返回原来浏览的位置

### ISSUE THREAD

**Issue by W-tomoe** [youzan/vant-weapp#2510]
## 1.sticky问题 
代码如下
```
<template>
    <div>
        <p class="p"></p>
        <van-tabs :active='active'  color='#0A86F8' titleActiveColor='#0A86F8'  animated swipeable sticky>
            <van-tab title="问答">
            </van-tab>

            <van-tab title="课程">
            </van-tab>

            <van-tab title="活动">
            </van-tab>
        </van-tabs>
        <p class="p"></p>

        <div>
            <van-sticky>sticky</van-sticky>
        </div>
        
        <p class="p"></p>
    </div>
</template>


<script>
export default {
    data () {
        return {
            active: 0,

        }
    },
    methods: {
        
    }
}
</script>


<style lang="scss" scoped>
p{
    height: 1000px;
}
</style>

```
-- 修改源码解决  
![image](https://user-images.githubusercontent.com/30516083/70507178-ce4d2d80-1b66-11ea-9702-73f364e59cc9.png)

## 问题2和3  
![222](https://user-images.githubusercontent.com/30516083/70508352-43b9fd80-1b69-11ea-9abe-182b5ec37038.gif)

vant 版本：1.0.0-beta.6
mpvue版本:  1.0.0

**Comment by frei-x** [comment]
我的换了1.0新版后 激活样式不生效,
还有下拉菜单也是....糟心

**Comment by W-tomoe** [comment]
> 我的换了1.0新版后 激活样式不生效,
> 还有下拉菜单也是....糟心

我倒是没有遇到这个问题，设置如下试试
1. active：激活项 
2. color：激活下边框颜色 
3. titleActiveColor: 激活字体颜色

**Comment by frei-x** [comment]
sticky我直接用原生的了, 兼容性还可以

**Comment by echokh** [comment]
一样的问题，等待修复

**Comment by W-tomoe** [comment]
> sticky我直接用原生的了, 兼容性还可以
@frei-x  ios部分旧机型不能兼容，慎用

**Comment by W-tomoe** [comment]
> sticky我直接用原生的了, 兼容性还可以

@frei-x  ios部分旧机型不兼容，慎用

**Comment by rex-zsd** [comment]
@W-tomoe 问题一是没问题的，sticky只在container区域会吸顶，一旦container不可见，就会取消吸顶。
这样修改会导致sticky始终吸顶。

**Comment by rex-zsd** [comment]
问题2、3与 #1867 应该是相同的问题。

**Comment by NineSu** [comment]
> @W-tomoe 问题一是没问题的，sticky只在container区域会吸顶，一旦container不可见，就会取消吸顶。
> 这样修改会导致sticky始终吸顶。

问题1我这边会有问题,调试发现需要page 的 onPageScroll 事件必须声明. 可以没有实现,但一定要加上,不然sticky就会失效

**Comment by callmesoul** [comment]
3.需要自己去记录滚动高度，然后切换的时候用wx.pageScrollTo去返回高度
