### ISSUE TITLE
[Bug Report] @vant/weapp/image/index

### ISSUE THREAD

**Issue by sdspgy** [youzan/vant-weapp#2512]
### 设备
微信开发者工具

### VantWeapp 版本
1.0.0-beta.4

### 基础库版本
2.9.3

### 描述问题
这个组件，图片显示不出来，宽高都为0

**Comment by rex-zsd** [comment]
组件引入是不是有问题？截下开发者工具的wxml部分看下，组件Shadow DOM是否有正常渲染。

**Comment by rex-zsd** [comment]
估计还是引入问题，检查一下哈。
