### ISSUE TITLE
[Feature Request] Card 商品卡片

### ISSUE THREAD

**Issue by yueyunyue** [youzan/vant-weapp#2513]
### 这个功能解决了什么问题
只有点击图片才会调整，从功能上来说不合适

### 建议的API是什么样的
点击整个模块就可以调整，同时增加点击事件

**Comment by rex-zsd** [comment]
没看懂…………“调整”是什么意思？

**Comment by rex-zsd** [comment]
如果是希望在整个卡片上增加点击事件，直接监听就可以了，内部没有catch`tap`事件。
```
<van-card bindtap="onTap">
...
</van-card>
```
