### ISSUE TITLE
[Feature Request] steps 激活index设置为数组，可以多个步骤同时处于激活状态

### ISSUE THREAD

**Issue by echokh** [youzan/vant-weapp#2515]
[Feature Request] steps 激活index设置为数组，可以多个步骤同时处于激活状态

**Comment by rex-zsd** [comment]
感觉不太合理…………多个步骤同时激活不像是步骤条的场景。

**Comment by echokh** [comment]
> 感觉不太合理…………多个步骤同时激活不像是步骤条的场景。

提出一个场景：在企业流程审批中，某个节点需要多人同时同意才能提交下一步审批，就可能会用到这个

**Comment by rex-zsd** [comment]
那是不是多人的审批在一个节点好一点，类似这个这个样子？
![image](https://user-images.githubusercontent.com/8767877/70606526-9f52bc80-1c37-11ea-82b4-69afe2549a60.png)

**Comment by echokh** [comment]
emm，这样合理，感谢回复

**Comment by echokh** [comment]
> 那是不是多人的审批在一个节点好一点，类似这个样子？
> ![image](https://user-images.githubusercontent.com/8767877/70606526-9f52bc80-1c37-11ea-82b4-69afe2549a60.png)
这样合理，感谢回复
