### ISSUE TITLE
[Bug Report] 为什么用到小程序后，不管icon图标还是商品导航等组件，都会·样式乱掉

### ISSUE THREAD

**Issue by hyyky** [youzan/vant-weapp#2518]
### 设备
window

### VantWeapp 版本
0.5.25

### 基础库版本
最新

### 请提供核心代码片段链接
https://youzan.github.io/vant-weapp/#/goods-action

### 描述问题
为什么用到小程序后，不管icon图标还是商品导航等组件，都会·样式乱掉。每次都要重新调整样式，很坑

**Comment by rex-zsd** [comment]
未提供代码和截图，看不出是什么问题哈……可以看看是不是开启了小程序的style:v2，关掉试试。
