### ISSUE TITLE
index-bar

### ISSUE THREAD

**Issue by ldlw** [youzan/vant-weapp#2522]
只定义A,B,C,点击其他字母报 Cannot read property 'data' of undefined; [Component] Event Handler Error @ dist/index-bar/index#onClick
TypeError: Cannot read property 'data' of undefined

**Comment by liaowenke** [comment]
索引字符列表也只生成A,B,C

**Comment by xumeihong** [comment]
index-bar组件文字不显示呢  文档原例   https://user-images.githubusercontent.com/42311523/71052283-d409cb00-2185-11ea-90ef-380ae3854821.png

开发工具是微信开发者工具    基础库版本为2.9.1
