### ISSUE TITLE
[Bug Report] Dialog组件样式问题

### ISSUE THREAD

**Issue by unimits** [youzan/vant-weapp#2527]
### 设备
Flyme 8.0

### VantWeapp 版本
1.0.0-beta.4

### 基础库版本
2.9.4

### 如果是 UI 问题，截图链接（多图回车分隔）

![截图](https://i.loli.net/2019/12/12/3kJt9rQzvoPudFI.jpg)

### 请提供核心代码片段链接
https://gist.github.com/unimits/579377de6e041b944318dfc36b142d8d.js

### 描述问题
Dialog组件样式问题，按钮不正常。

**Comment by unimits** [comment]
已找到问题，在app.json中，目前的vant-weapp v1.0.0版本不能增加配置项："style": "v2"，否则会造成上述问题。但是默认生成的小程序模板会有这个配置。

**Comment by rex-zsd** [comment]
可以先关闭`style:v2`哈
