### ISSUE TITLE
tabs onClick事件name取不到值

### ISSUE THREAD

**Issue by superlbr** [youzan/vant-weapp#2529]
event.detail里面只有{x,y}

**Comment by rex-zsd** [comment]
issue格式不符合规范，请使用生成器创建issue哈。

**Comment by superlbr** [comment]
在wepy2里click不行，把this.trigger('click')替换成tap就可以
吐槽下：change、click等事件都触发了input事件，不知道干啥的。click事件也触发change事件。。。

**Comment by rex-zsd** [comment]
wepy应该是转换了事件名 把cluck事件名转换成tap了

**Comment by superlbr** [comment]
@rex-zsd 不尽然，this.trigger(input)的时候，click就调用了
