### ISSUE TITLE
vant-weapp的swipecell组件，通过点击事件打开单元格

### ISSUE THREAD

**Issue by candyAndBella** [youzan/vant-weapp#2531]
bind:open是单元格打开时执行的方法。
我想做一个效果，在小程序里，通过bindclick事件调用了一个方法，来打开单元格，如下
toOpenCell:function() {
        this.selectComponent('#myswipe').open('right');
    },
现在是没有任何效果的

**Comment by candyAndBella** [comment]
![微信图片_20191213144810](https://user-images.githubusercontent.com/34698384/70776689-bec52300-1db8-11ea-9b74-04c7f1177278.jpg)
![微信图片_20191213144806](https://user-images.githubusercontent.com/34698384/70776699-c5ec3100-1db8-11ea-9ccc-dbc5bbb2f9a6.jpg)

**Comment by GPPoseidon999** [comment]
你想要的是代码主动控制开关吗

**Comment by GPPoseidon999** [comment]
> bind:open是单元格打开时执行的方法。
> 我想做一个效果，在小程序里，通过bindclick事件调用了一个方法，来打开单元格，如下
> toOpenCell:function() {
> this.selectComponent('#myswipe').open('right');
> },
> 现在是没有任何效果的

我试了可以的呀没有问题的 有具体代码吗

**Comment by GPPoseidon999** [comment]
> bind:open是单元格打开时执行的方法。
> 我想做一个效果，在小程序里，通过bindclick事件调用了一个方法，来打开单元格，如下
> toOpenCell:function() {
> this.selectComponent('#myswipe').open('right');
> },
> 现在是没有任何效果的

**Comment by GPPoseidon999** [comment]
> bind:open是单元格打开时执行的方法。
> 我想做一个效果，在小程序里，通过bindclick事件调用了一个方法，来打开单元格，如下
> toOpenCell:function() {
> this.selectComponent('#myswipe').open('right');
> },
> 现在是没有任何效果的

![demo](https://user-images.githubusercontent.com/28697192/70777868-d225bd80-1dbb-11ea-9832-e640c8343f48.gif)

**Comment by rex-zsd** [comment]
实测`open`方法没问题的，是不是selectComponent没有选择到这个组件还是其他原因？

**Comment by candyAndBella** [comment]
> 实测`open`方法没问题的，是不是selectComponent没有选择到这个组件还是其他原因？

mpvue开发微信小程序，引入了vant-wepap的van-swipe-cell组件，想要调用open方法。不知道怎么调用。以下方法会报错
this.selectComponent('#mySwipe').open('right');

**Comment by SunKechang** [comment]
this.$mp.page.selectComponent(‘#mySwipe’).open("right")

**Comment by SunKechang** [comment]
> > 实测`open`方法没问题的，是不是selectComponent没有选择到这个组件还是其他原因？
> 
> mpvue开发微信小程序，引入了vant-wepap的van-swipe-cell组件，想要调用open方法。不知道怎么调用。以下方法会报错
> this.selectComponent('#mySwipe').open('right');

this.$mp.page.selectComponent(‘#mySwipe’).open("right")
