### ISSUE TITLE
[Bug Report] van-tabs配合van-popup使用，当van-tabs使用了animated属性后，van-popup只会出现在第一个tab页

### ISSUE THREAD

**Issue by ZhongMingKun** [youzan/vant-weapp#2532]
### 设备
pc、mi mix2、iphoneX

### VantWeapp 版本
1.0.0-beta.4

### 基础库版本
2.7.0

### 如果是 UI 问题，截图链接（多图回车分隔）

![image](https://user-images.githubusercontent.com/33282718/70776904-6a6e7300-1db9-11ea-8f89-6f605e2657e4.png)

![image](https://user-images.githubusercontent.com/33282718/70776940-79552580-1db9-11ea-8b1e-b62f83c05724.png)

### 请提供核心代码片段链接
https://gitee.com/ZMK_2017/vant-tabs-animated-prop-bug/tree/master

### 描述问题
van-tabs配合van-popup使用，当van-tabs使用了animated属性后，van-popup只会出现在第一个tab页

**Comment by rex-zsd** [comment]
是这样的，建议内部有固定定位的元素的这种场景不要开启`animated `哈。
`animated`依赖`transform`属性，而`transform`会影响`fixed`定位的元素，无法规避。
