### ISSUE TITLE
使用uniapp +vant写小程序使用tab组件时遇到的两个问题

### ISSUE THREAD

**Issue by littleBelle** [youzan/vant-weapp#2533]
uniapp +vant
问题一：设置绑定当前选中的标签页无效
问题二：文字过长的title设置ellipsis=false文字还是会省略
![f78c9e97ad92bf6c8044daa6bc8f55c](https://user-images.githubusercontent.com/53242999/70778031-482a2480-1dbc-11ea-9b97-10d9a0813305.png)
![78620353d3219bbe3878f261456a21d](https://user-images.githubusercontent.com/53242999/70778053-55dfaa00-1dbc-11ea-86c7-cd2467878c8a.png)
![8fa323dc86c6f3784a02a42fc3d62a7](https://user-images.githubusercontent.com/53242999/70778063-5a0bc780-1dbc-11ea-8fdd-be6ad371c326.png)
麻烦大佬指点我该怎么做，多谢多谢

**Comment by littleBelle** [comment]
![image](https://user-images.githubusercontent.com/53242999/70778148-89bacf80-1dbc-11ea-8be0-5dcafe8d21d5.png)
![image](https://user-images.githubusercontent.com/53242999/70778162-94756480-1dbc-11ea-8870-4cc7f26ff74f.png)
![image](https://user-images.githubusercontent.com/53242999/70778173-9c350900-1dbc-11ea-9c87-95f16f3a8f06.png)

**Comment by littleBelle** [comment]
![image](https://user-images.githubusercontent.com/53242999/70780322-cc31db80-1dbf-11ea-8649-dff25486bf2a.png)

**Comment by littleBelle** [comment]
第一个问题解决了，应该改成active=“active”。
麻烦大佬指导一下第二个问题，谢谢

**Comment by rex-zsd** [comment]
实测原生小程序demo中没有问题
`ellipsis`这个属性是1.0.0版本新增的，检查一下是不是版本问题？
如果确认版本没问题的话，可能与uni-app一起使用时有bug，需要再查一下。
