### ISSUE TITLE
[Bug Report] Grid 宫格组件文字超过4个布局就会变形

### ISSUE THREAD

**Issue by wenj91** [youzan/vant-weapp#2534]
### 设备
安卓

### VantWeapp 版本
1.0.0-beta.4

### 基础库版本
v1.0.0-beta.4

### 如果是 UI 问题，截图链接（多图回车分隔）

![截图](https://sm.ms/image/aU4rmCgyLYzoD68)

### 请提供核心代码片段链接
https://sm.ms/image/aU4rmCgyLYzoD68

### 描述问题
Grid 宫格组件文字超过4个布局就会变形

**Comment by GPPoseidon999** [comment]
> ### 设备
> 安卓
> 
> ### VantWeapp 版本
> 1.0.0-beta.4
> 
> ### 基础库版本
> v1.0.0-beta.4
> 
> ### 如果是 UI 问题，截图链接（多图回车分隔）
> ![截图](https://camo.githubusercontent.com/aa5c036114478d66136a2c69c3599113b0a29925/68747470733a2f2f736d2e6d732f696d6167652f615534726d4367794c597a6f443638)
> 
> ### 请提供核心代码片段链接
> https://sm.ms/image/aU4rmCgyLYzoD68
> 
> ### 描述问题
> Grid 宫格组件文字超过4个布局就会变形

设置的列数较多每列宽度较小，多个文字换行导致高度增加 出现上述情况
你可以使用自定义内容 自己控制里面的元素大小宽度 解决上述问题

**Comment by GPPoseidon999** [comment]
> ### 设备
> 安卓
> 
> ### VantWeapp 版本
> 1.0.0-beta.4
> 
> ### 基础库版本
> v1.0.0-beta.4
> 
> ### 如果是 UI 问题，截图链接（多图回车分隔）
> ![截图](https://camo.githubusercontent.com/aa5c036114478d66136a2c69c3599113b0a29925/68747470733a2f2f736d2e6d732f696d6167652f615534726d4367794c597a6f443638)
> 
> ### 请提供核心代码片段链接
> https://sm.ms/image/aU4rmCgyLYzoD68
> 
> ### 描述问题
> Grid 宫格组件文字超过4个布局就会变形

van-grid-item 上添加 use-slot 属性

**Comment by 358xiaoyihezemin** [comment]
> ### 设备
> 安卓
> 
> ### VantWeapp 版本
> 1.0.0-beta.4
> 
> ### 基础库版本
> v1.0.0-beta.4
> 
> ### 如果是 UI 问题，截图链接（多图回车分隔）
> ![截图](https://camo.githubusercontent.com/aa5c036114478d66136a2c69c3599113b0a29925/68747470733a2f2f736d2e6d732f696d6167652f615534726d4367794c597a6f443638)
> 
> ### 请提供核心代码片段链接
> https://sm.ms/image/aU4rmCgyLYzoD68
> 
> ### 描述问题
> Grid 宫格组件文字超过4个布局就会变形

遇到了同样的问题   请问你解决掉了吗？

**Comment by wenj91** [comment]
没解决，把字体字数强行改同样了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "何泽民（hezemin）"<notifications@github.com&gt;; 
发送时间: 2020年1月15日(星期三) 下午2:07
收件人: "youzan/vant-weapp"<vant-weapp@noreply.github.com&gt;; 
抄送: "zlw420"<1541683150@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [youzan/vant-weapp] [Bug Report] Grid 宫格组件文字超过4个布局就会变形 (#2534)



 
设备
 
安卓
 
VantWeapp 版本
 
1.0.0-beta.4
 
基础库版本
 
v1.0.0-beta.4
 
如果是 UI 问题，截图链接（多图回车分隔）
 

 
请提供核心代码片段链接
 
https://sm.ms/image/aU4rmCgyLYzoD68
 
描述问题
 
Grid 宫格组件文字超过4个布局就会变形
  
遇到了同样的问题   请问你解决掉了吗？
