### ISSUE TITLE
van-tabs 组件在小程序的问题

### ISSUE THREAD

**Issue by q867427795** [youzan/vant-weapp#2537]
<van-tabs line-width="20" sticky="{{true}}" color="#000000" ellipsis="{{false}}" border="{{false}}" active="{{ active }}" bind:click="onChange">
				<van-tab title-style="font-size:32rpx;" wx:for="{{orderlist}}" wx:for-index="ind" title="{{item.title}}" wx:key="{{item.key}}">
				</van-tab>
		</van-tabs>

以上为页面代码
设置粘性布局后，通过便利<van-tab>组件

![image](https://user-images.githubusercontent.com/16067273/70845964-92c8a100-1e8f-11ea-9d39-645759a607ef.png)

如果第一个页面的数据没有超过页面，那么点击第二个页面往下滑动的时候，会出现这样的问题

![image](https://user-images.githubusercontent.com/16067273/70845937-57c66d80-1e8f-11ea-86e6-c8857affb027.png)

上面是理想的效果图，下面那张是实际的效果图

![image](https://user-images.githubusercontent.com/16067273/70845944-6d3b9780-1e8f-11ea-9ad8-10db19bffa26.png)

**Comment by q867427795** [comment]
在页面上返回后，会提示这个错误
![image](https://user-images.githubusercontent.com/16067273/70848452-d7af0080-1eac-11ea-9f3b-728c46aa6796.png)

**Comment by q867427795** [comment]
页面返回后。会提示这个错误

Cannot read property 'getComputedName' of undefined;at api nextTick callback function
TypeError: Cannot read property 'getComputedName' of undefined

**Comment by rex-zsd** [comment]
第1个问题有issue在跟进咯 #2310
第2个问题已经修复了，升级到1.0.0正式版即可。

**Comment by wujingquan** [comment]
tabs/index.ts
![image](https://user-images.githubusercontent.com/22289015/71226329-7d7fc680-2316-11ea-9f96-ca63055e4dea.png)
我也遇到该问题，暂时这样整了，等大佬修复。
