### ISSUE TITLE
[Bug Report] 通过组件调用Dialog时，Props中的confirm-button-color不生效

### ISSUE THREAD

**Issue by Lan-megumi** [youzan/vant-weapp#2538]
### 设备
微信小程序开发者工具

### VantWeapp 版本
0.5.27

### 基础库版本
2.9.4

### 如果是 UI 问题，截图链接（多图回车分隔）

![截图](https://sm.ms/delete/M3zQax94SqpU61umjPHZdO2YRt)

![截图](https://sm.ms/delete/rO5EGp3DbJeoRjaxd9PhQY1Zn6)

### 请提供核心代码片段链接
https://sm.ms/delete/M3zQax94SqpU61umjPHZdO2YRt

### 描述问题
在自定义组件中通过组件调用Dialog时，Props中的confirm-button-color不生效
代码片段的推荐网址上不去....萌新第一次提交只好把代码放截图里了

**Comment by Lan-megumi** [comment]
```
<van-dialog 
         use-slot show="{{ showDialog }}" 
         show-cancel-button
         confirm-button-open-type="getUserInfo" 
         bind:close="dialogOnClose" 
         bind:confirm="dialogClick"
         close-on-click-overlay="{{ true }}" 
         show-cancel-button="{{ true }}" 
         confirm-button-text="删除"
         confirm-button-color="ED2C05" 
         title="提示">            
        </van-dialog>
```

**Comment by JakeLaoyu** [comment]
#ED2C05

**Comment by Lan-megumi** [comment]
> #ED2C05

也是不行

**Comment by JakeLaoyu** [comment]
0.5.27 是 没有这个 属性的，你看的是 1.x的文档

**Comment by Lan-megumi** [comment]
> 0.5.27 是 没有这个 属性的，你看的是 1.x的文档

！啊这样的啊...那怎么看版本的？
这个0.5.27貌似是自动填的不是我填的

**Comment by JakeLaoyu** [comment]
所以你用的是什么版本

**Comment by Lan-megumi** [comment]
> 所以你用的是什么版本

另外一个同事拷贝的，不太清楚呢，有没有什么方法可以看到....

**Comment by JakeLaoyu** [comment]
看node_modules 里的包

**Comment by Lan-megumi** [comment]
> 看node_modules 里的包

"_id": "vant-weapp@0.5.23" 
这个？

**Comment by JakeLaoyu** [comment]
这个就是 0.x，看0.x 的文档

**Comment by Lan-megumi** [comment]
> 这个就是 0.x，看0.x 的文档

我看了下文档，文档上快速入手装的是0.x的，1.x怎么装？是没还没出么

**Comment by JakeLaoyu** [comment]
https://youzan.github.io/vant-weapp/#/intro

1.x 的包更名为 @vant/weapp，注意不能平滑升级，有不兼容改动，需要看 changelog
