### ISSUE TITLE
van-button 如何提交表单数据？

### ISSUE THREAD

**Issue by hellotomat** [youzan/vant-weapp#2539]
van-button 如何提交表单数据？
form-type='submit' 不能用？
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater?repo=VantWeapp

**Comment by rex-zsd** [comment]
查阅一下微信小程序文档，收微信限制，自定义文件内的button的form-type属性是无效的。
