### ISSUE TITLE
Uploader 文件上传 安卓调用无法直接摄像头

### ISSUE THREAD

**Issue by shuichilanglang** [youzan/vant-weapp#2541]
图片选取模式，当accept为image类型时设置capture可选值为camera可以直接调起摄像头
accept 选为image
capture 选为camera
弹出的是有拍照和选择照片功能
能不能直接调用拍照或者屏蔽掉选择照片

**Comment by JoxHero** [comment]
accept 选为image
capture 选为camera,真机测试无法直接调起摄像头，点击没反应
