### ISSUE TITLE
[Bug Report] 弹窗出现时页面上环形进度条在遮罩层之上

### ISSUE THREAD

**Issue by GuyYQ** [youzan/vant-weapp#2542]
### 设备
ipnone6/小米9/华为P20

### VantWeapp 版本
1.0.0-beta.4

### 基础库版本
2.9.4

### 如果是 UI 问题，截图链接（多图回车分隔）

![截图](https://i.loli.net/2019/12/16/tITDyYWVu6p1cEd.jpg)

![截图](https://i.loli.net/2019/12/16/XjPOFpHvwtruoaQ.png)

### 请提供核心代码片段链接
https://sm.ms/image/XjPOFpHvwtruoaQ

### 描述问题
页面上设置了环形进度条<van-circle speed="100" value="90" stroke-width="6" text="90" color="#28ECE6" layer-color="transparent" /> 点击页面出现弹窗时，进度条显示在弹窗上，未被遮罩遮住van-dialog

**Comment by rex-zsd** [comment]
circle内部使用了canvas，canvas是原生组件，普通的view是无法覆盖的。
所以这个问题无解，只能采取其他方法规避。

**Comment by galikeoy** [comment]
> circle内部使用了canvas，canvas是原生组件，普通的view是无法覆盖的。
> 所以这个问题无解，只能采取其他方法规避。

小程序原生组件更新了，canvas添加了2d属性，支持同层渲染，向web规范看齐了，希望vant可以根据属性更新一下

**Comment by nihaoye** [comment]
我也遇到同样的问题，求解

**Comment by galikeoy** [comment]
> 我也遇到同样的问题，求解

可以用cover-view覆盖，我的需求很复杂，直接用支持2d属性的echarts 饼图代替了此组件

**Comment by nihaoye** [comment]
我现在是用一个不可见的canvas画出来，然后导出成base64放到图片上，只是动画没法用，不过不影响
