### ISSUE TITLE
grid 九宫格的图标可以调整size大小吗

### ISSUE THREAD

**Issue by Richter-hzl** [youzan/vant-weapp#2546]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater?repo=VantWeapp

**Comment by rex-zsd** [comment]
`icon`暂时不支持自定义`size`哈。
可以通过`slot`自己传入`van-icon`来控制大小的。
