### ISSUE TITLE
[Bug Report] SwipeCell 滑出可以执行open事件   滑走不回执行close 事件

### ISSUE THREAD

**Issue by huyajie** [youzan/vant-weapp#2547]
### 设备
手机 、模拟器

### VantWeapp 版本
1.0.0

### 基础库版本
2.9.4

### 请提供核心代码片段链接
https://gist.github.com/huyajie/6570d258f4a878e4531d1e3c1c70174c

### 描述问题
SwipeCell 
滑出可以执行open事件 ，滑走不回执行close 事件  。
点击 空白处可以执行close

**Comment by JakeLaoyu** [comment]
滑动关闭不会触发 `close`，只有开启 `async-close` 并且点击按钮时 才会触发

**Comment by candyAndBella** [comment]
mpvue开发微信小程序，引入了vant-wepap的van-swipe-cell组件，想要调用open方法。不知道怎么调用。以下方法会报错
this.selectComponent('#mySwipe').open('right');

**Comment by JakeLaoyu** [comment]
```js
this.$mp.page.selectComponent('#mySwipe').open('right')
```

**Comment by huyajie** [comment]
@JakeLaoyu   这边需求是滑出的时候   要对那条内容改变       关闭的时候 在改变回来  有好的办法吗

**Comment by candyAndBella** [comment]
> ```js
> this.$mp.page.selectComponent('#mySwipe').open('right')
> ```

您好，我试过了，还是不行
