### ISSUE TITLE
[Bug Report] van-grid组件border参数不起作用

### ISSUE THREAD

**Issue by hellotomat** [youzan/vant-weapp#2549]
### 设备
小程序

### VantWeapp 版本
1.0.0

### 基础库版本
1.0.0

### 如果是 UI 问题，截图链接（多图回车分隔）

![截图](https://i.loli.net/2019/12/17/QEZsvSynHUNDgu9.png)

### 请提供核心代码片段链接
https://sm.ms/image/QEZsvSynHUNDgu9

### 描述问题
 <van-grid column-num="3" border="false" clickable="true"> 
</van-grid>
border=false的时候 参数不起作用，依然显示border 
请注意：GitHub Gist 地址无法访问，里面地址是截图的地址

**Comment by JakeLaoyu** [comment]
无法复现，提供一下代码

```html
<van-grid border="{{ false }}">
    <van-grid-item icon="photo-o" text="文字" wx:for="{{ 4 }}" wx:key="*this" />
</van-grid>
```

**Comment by hellotomat** [comment]
找到了原因了boolean值必须{{false}}或{{true}}这么写
