### ISSUE TITLE
[Bug Report] 修改sidebar边框激活颜色

### ISSUE THREAD

**Issue by leejing4766465** [youzan/vant-weapp#2552]
### 设备
iphone6

### VantWeapp 版本
1.0.0

### 基础库版本
2.9.0

### 如果是 UI 问题，截图链接（多图回车分隔）

![截图](https://i.loli.net/2019/12/18/5fz6JgayCiNoHIe.jpg)

### 请提供核心代码片段链接
http://www.xiaoyuan666.cn:8087/gitbucket/john/tao8h-wxmini/blob/master/pages/category/category.wxml

### 描述问题
我想把这个sidebar的边框颜色从红色改为绿色

**Comment by JakeLaoyu** [comment]
代码地址需要登录，请提供一个可以访问的

**Comment by rex-zsd** [comment]
可以通过CSS变量`--sidebar-selected-border-color`修改边框颜色哈，具体查阅[定制主题](https://youzan.github.io/vant-weapp/#/theme)的文档。
