### ISSUE TITLE
van-popup弹出层闪退问题

### ISSUE THREAD

**Issue by hj34sd** [youzan/vant-weapp#2553]
点击弹出层之后显示瞬间退出，无法正常使用
代码如下
<template>

    <view>
            <van-cell title="快捷报单通道" value="" size="large" label="通过下列表格快速记录你的订单" />
            <van-cell title="请选择时间"  bind:click="showPopup"/>

            <van-popup
            show="{{ show }}"
            position="bottom"
            custom-style="height: 40%"
            bind:close="onClose"
            >
                <van-datetime-picker
                    type="date"
                    value="{{ currentDate }}"
                    bind:input="onInput"
                    min-date="{{ minDate }}"

                />
            </van-popup>

            <van-cell-group>
                
                <van-field
                    value="{{ username }}"
                    
                    clearable
                    label="用户名"
                    icon="question-o"
                    placeholder="请输入用户名"
                    
                />

                <van-field
                    value="{{ password }}"
                    type="password"
                    label="密码"
                    placeholder="请输入密码"
                    
                />
            </van-cell-group>
        
        <view slot="footer">
             <van-button size="large" type="danger">提交数据</van-button>
        </view>
    </view>

</template>

<script>

import wepy from 'wepy'
export default class Newadd extends wepy.mixin {
    data = {
        currentDate: new Date().getTime(),
        minDate: 10,
        show: false
    }

    config = {
    }

    methods = {
        showPopup() {
            this.setData({ show: true });
        },

        onClose() {
            this.setData({ show: false });
        },
        onInput(event) {
            this.setData({
                currentDate: event.detail
            });
        }
    }

    onLoad() {
        console.log('获取首页数据')
    }
}
</script>

<style lang='less'>

</style>

**Comment by rex-zsd** [comment]
有点神奇，测试没有复现这个问题
