### ISSUE TITLE
van-goods-action太长了.超出屏幕

### ISSUE THREAD

**Issue by pjy1711040554** [youzan/vant-weapp#2555]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater?repo=VantWeapp
![QzpcVXNlcnNcbzBvMG9cQXBwRGF0YVxSb2FtaW5nXERpbmdUYWxrXDI1OTU3MTMxNl92MlxJbWFnZUZpbGVzXDE1NzY3MjE4MDcwMjRfQjM4RTQxRjAtQUExOS00MjIxLUI3NDQtQkJEMjI4RDAyRTQ5LnBuZw==](https://user-images.githubusercontent.com/50440825/71139270-ae91c580-2248-11ea-902e-5606de921cd5.png)

**Comment by JakeLaoyu** [comment]
请使用模板创建 https://youzan.github.io/vant-issue-generater?repo=VantWeapp，便于我们排查
