### ISSUE TITLE
mpvue库，使用vant-weapp，如何获取某个组件的实例

### ISSUE THREAD

**Issue by candyAndBella** [youzan/vant-weapp#2556]
mpvue开发微信小程序，引入了vant-wepap的van-swipe-cell组件，想要调用open方法。不知道怎么调用。以下方法会报错
this.selectComponent('#mySwipe').open('right');

**Comment by rex-zsd** [comment]
使用小程序框架的，可以去相应框架的文档中搜索API哈。
https://github.com/Meituan-Dianping/mpvue/issues/605
