### ISSUE TITLE
[Bug Report] Tabs的属性sticky设置了无效

### ISSUE THREAD

**Issue by wzhq0598** [youzan/vant-weapp#2562]
### 设备
Android

### VantWeapp 版本
1.0.0

### 基础库版本
2.7.0

### 请提供核心代码片段链接
https://gist.githubusercontent.com/wzhq0598/962c4250e742be4fffb393c233ed868a/raw/d8ddce3d42da2bae6692828735a10e039d2b9251/gistfile1.txt

### 描述问题
van-tabs 设置了sticky，但无效

**Comment by rex-zsd** [comment]
`sticky`吸顶仅在内容区有效，如果`van-tab`内没有内容，即高度为0，是不会发生吸顶的，可以看下demo中组件的行为哈。

**Comment by liuruiqi1993** [comment]
我用的1.0.0-beta.4
因为 tabs 》index.js 里的这一句吧，
`container: function () { return _this.createSelectorQuery().select('.van-tabs'); }`
sticky以van-tabs为容器，但我不会改，于是直接把index.wxml里的`container="{{ container }}"`去掉了
