### ISSUE TITLE
[Bug Report] 内置样式

### ISSUE THREAD

**Issue by Grainfills** [youzan/vant-weapp#2564]
### 设备
微信开发者工具

### VantWeapp 版本
1.0.0

### 基础库版本
1.0.0

### 如果是 UI 问题，截图链接（多图回车分隔）

![截图](https://image-1257003685.cos.ap-guangzhou.myqcloud.com/picgo/20191220105853.png)

![截图](https://image-1257003685.cos.ap-guangzhou.myqcloud.com/picgo/20191220110609.png)

### 请提供核心代码片段链接
https://youzan.github.io/vant-weapp/#/common

### 描述问题
为什么多行文本截断不处理数字和字母呢。。。。？？？？word-break请添加一下

**Comment by Grainfills** [comment]
请添加一个word-break，或者说一下为什么不做处理的考虑

**Comment by rex-zsd** [comment]
这个需要的话，自己增加一下样式就好了。

**Comment by Grainfills** [comment]
好的👌

rex <notifications@github.com> 于2019年12月28日周六 下午9:53写道：
