### ISSUE TITLE
checkbox 里面嵌套数量加减事件   选中状态来回点击几次 checkbox 事件失效

### ISSUE THREAD

**Issue by huipo22** [youzan/vant-weapp#2567]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater?repo=VantWeapp
checkbox 里面嵌套数量加减事件   选中状态来回点击几次 checkbox 事件失效

**Comment by JakeLaoyu** [comment]
为加减事件绑定 `catchtap`

**Comment by huipo22** [comment]
catch:change 不行吗?

**Comment by JakeLaoyu** [comment]
冒泡到 checkbox 的是哪个事件

**Comment by huipo22** [comment]
<van-checkbox-group value="{{ result }}" **catch:change="onChange"** class="Box" wx:if="{{cartList.length!==0}}" style="margin-bottom: 50px">
        <view wx:for="{{cartList}}" wx:for-item="item" wx:key="unique" class="checkBox">
            <van-checkbox name="{{item.goods_id}}-{{item.present_price}}-{{item.num}}-{{item.id}}"></van-checkbox>
            <van-card title="{{item.goods_name}}" thumb="{{resourse+item.goods_img}}" style="flex:1">
                <view slot="bottom" class="goodContent">
                    <view class="left">
                        <text class="">{{'¥'+item.present_price}}</text>
                    </view>
                    <view class="right">
                        <view class="stepper">
                            <van-stepper value="{{item.num}}" min="0" async-change data-goodId="{{item.id}}" data-goodNum="{{item.num}}" **catch:change="goodChange"** />
                        </view>
                    </view>
                </view>
            </van-card>
        </view>
    </van-checkbox-group>

**Comment by huipo22** [comment]
[a3e99b6330210baf3c21a640cce9a7e1.zip](https://github.com/youzan/vant-weapp/files/3987144/a3e99b6330210baf3c21a640cce9a7e1.zip)

**Comment by JakeLaoyu** [comment]
只有 点击事件会触发 checkbox

**Comment by rex-zsd** [comment]
在stepper上劫持一下tap事件即可避免干扰checkbox。
