### ISSUE TITLE
Uploader上传组件开启multiple多选属性后，加入限制上传数量是5个  第一次上传2张，第二次上次4张，并没有限制，还是上传了6张

### ISSUE THREAD

**Issue by akastronger** [youzan/vant-weapp#2568]
代码如下（以组件形式调用）：
<template>
  <div class="img-upload" @click="clickContent">
    <van-uploader
      v-model="imgArr"
      :before-read="beforeRead"
      :max-count="maxCount"
      deletable
      :accept="accept"
      multiple
      class="pb-16"
      @delete="onDelete()"
    />
  </div>
</template>

<script>
import { Uploader } from 'vant';
import axios from 'axios';		// 引入axios
import { Toast } from 'vant';	// 引入Toast
import { bridge_upload } from '@/config/bridge';

export default {
  name: 'LImgupLoader',
  components: {
    vanUploader: Uploader
  },
  props: {
    // 图片绑定值
    picArr: {
      type: Array,
      default: function() {
        return [];
      },
      require: true
    },
    // 文件上传数量限制
    maxCount: {
      type: Number,
      default: 1
    },
    // 接受的文件类型
    accept: {
      type: String,
      default: 'image/*'
    }
  },
  data() {
    return {
      imgArr: []
    };
  },
  computed: {

  },
  watch: {
    picArr: {
      immediate: true,
      handler(val, oldVal) {
        this.imgArr = JSON.parse(JSON.stringify(val));
      },
      deep: true
    }
  },

  mounted() {},

  methods: {
    clickContent() {
      bridge_upload();
    },
    beforeRead(file) {
      console.log('beforeRead--', file);
      if (Array.isArray(file) && file.length) {
        if (file.length > this.maxCount) {
          Toast(`图片不能超过${this.maxCount}张`);
          return;
        }
        file.forEach(item => {
          // 文档上此用法在真机上出现bug item.type !== 'image/jpeg'
          // if (item.type !== 'image/jpeg') {
          //   Toast('请上传图片格式');
          //   return false;
          // }
          this.upload(item);
        });
      } else {
        // if (file.type !== 'image/jpeg') {
        //   Toast('请上传图片格式');
        //   return false;
        // }
        this.upload(file);
      }
    },
    upload(file) {
      // new 一个FormData格式的参数
      const tokenURL = 'https://api.linhuiba.com/qiniu/app-token/linhuiba-certs';
      const domain = 'https://cert.linhuiba.com/';
      const params = new FormData();
      params.append('file', file);

      const config = {
        headers: { // 添加请求头
          'Content-Type': 'multipart/form-data'
        }
      };
      axios.get(tokenURL).then(res => {
        const token = res.data.result;
        params.append('token', token);
        // 把 uploadUrl 换成自己的 上传路径
        axios.post('https://upload.qiniup.com', params, config).then(res => {
          if (res && res.data && res.status === 200) {
            this.imgArr.push({
              url: `${domain}/${res.data.key}`,
              file_name: file.name,
              isImage: true // 图片需要加此参数才可以，详见vant
            });
            this.$emit('update:picArr', this.imgArr);
          } else {
            // 否则 Toast 提示
            Toast.fail(res.data && (res.data.msg));
          }
        });
      });
    },
    onDelete() {
      this.$emit('update:picArr', this.imgArr);
    }
  }
};

</script>
<style lang='scss' scoped>
</style>

**Comment by JakeLaoyu** [comment]
整理一下代码格式

**Comment by akastronger** [comment]
`
<template>
  <div class="img-upload" @click="clickContent">
    <van-uploader
      v-model="imgArr"
      :before-read="beforeRead"
      :max-count="maxCount"
      deletable
      :accept="accept"
      multiple
      class="pb-16"
      @delete="onDelete()"
    />
  </div>
</template>

<script>
import { Uploader } from 'vant';
import axios from 'axios';		// 引入axios
import { Toast } from 'vant';	// 引入Toast
import { bridge_upload } from '@/config/bridge';

export default {
  name: 'LImgupLoader',
  components: {
    vanUploader: Uploader
  },
  props: {
    // 图片绑定值
    picArr: {
      type: Array,
      default: function() {
        return [];
      },
      require: true
    },
    // 文件上传数量限制
    maxCount: {
      type: Number,
      default: 1
    },
    // 接受的文件类型
    accept: {
      type: String,
      default: 'image/*'
    }
  },
  data() {
    return {
      imgArr: []
    };
  },
  computed: {

  },
  watch: {
    picArr: {
      immediate: true,
      handler(val, oldVal) {
        this.imgArr = JSON.parse(JSON.stringify(val));
      },
      deep: true
    }
  },

  mounted() {},

  methods: {
    clickContent() {
      bridge_upload();
    },
    beforeRead(file) {
      console.log('beforeRead--', file);
      if (Array.isArray(file) && file.length) {
        if (file.length > this.maxCount) {
          Toast(`图片不能超过${this.maxCount}张`);
          return;
        }
        file.forEach(item => {
          // 文档上此用法在真机上出现bug item.type !== 'image/jpeg'
          // if (item.type !== 'image/jpeg') {
          //   Toast('请上传图片格式');
          //   return false;
          // }
          this.upload(item);
        });
      } else {
        // if (file.type !== 'image/jpeg') {
        //   Toast('请上传图片格式');
        //   return false;
        // }
        this.upload(file);
      }
    },
    upload(file) {
      // new 一个FormData格式的参数
      const tokenURL = 'https://api.linhuiba.com/qiniu/app-token/linhuiba-certs';
      const domain = 'https://cert.linhuiba.com/';
      const params = new FormData();
      params.append('file', file);

      const config = {
        headers: { // 添加请求头
          'Content-Type': 'multipart/form-data'
        }
      };
      axios.get(tokenURL).then(res => {
        const token = res.data.result;
        params.append('token', token);
        // 把 uploadUrl 换成自己的 上传路径
        axios.post('https://upload.qiniup.com', params, config).then(res => {
          if (res && res.data && res.status === 200) {
            this.imgArr.push({
              url: `${domain}/${res.data.key}`,
              file_name: file.name,
              isImage: true // 图片需要加此参数才可以，详见vant
            });
            this.$emit('update:picArr', this.imgArr);
          } else {
            // 否则 Toast 提示
            Toast.fail(res.data && (res.data.msg));
          }
        });
      });
    },
    onDelete() {
      this.$emit('update:picArr', this.imgArr);
    }
  }
};

</script>
<style lang='scss' scoped>
</style>
`

**Comment by akastronger** [comment]
![1576832556(1)](https://user-images.githubusercontent.com/27852310/71243200-c6ea0900-234a-11ea-9506-fc7dd4d4b0fc.jpg)
![1576832582(1)](https://user-images.githubusercontent.com/27852310/71243201-c7829f80-234a-11ea-8ca9-a19bd474a320.jpg)
![1576832618(1)](https://user-images.githubusercontent.com/27852310/71243202-c7829f80-234a-11ea-97d4-49bcf64a6903.jpg)

**Comment by JakeLaoyu** [comment]
`file-list` 参数没传

**Comment by akastronger** [comment]
file-list传了

**Comment by JakeLaoyu** [comment]
代码呢

**Comment by akastronger** [comment]
我写了个通用组件作为上传图片组件   v-model 绑定的值是通过父组件props传过来监听的

**Comment by JakeLaoyu** [comment]
issue不符合规范，请上传代码

**Comment by akastronger** [comment]
我重新编辑了下 麻烦帮忙看看

**Comment by JakeLaoyu** [comment]
`v-model="imgArr"` 这个组件不支持 v-model
