### ISSUE TITLE
van-sticky 不能平滑的吸顶，总是会闪一下，再吸顶

### ISSUE THREAD

**Issue by amyhuangxbd** [youzan/vant-weapp#2569]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater?repo=VantWeapp

**Comment by amyhuangxbd** [comment]
并且会有吸顶失败情况

**Comment by rex-zsd** [comment]
#2310
