### ISSUE TITLE
vantweapp swipe-cell按照官网配置不显示侧滑按钮

### ISSUE THREAD

**Issue by liufengcuit** [youzan/vant-weapp#2570]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater?repo=VantWeapp

  <van-swipe-cell right-width="{{ 65 }}" left-width="{{ 65 }}">
    <view slot="left">选择</view>
    <van-cell-group>
      <van-cell title="单元格" value="内容" />
    </van-cell-group>
    <van-cell-group>
      <van-cell title="单元格" value="内容" />
    </van-cell-group>
    <view slot="right">删除</view>
  </van-swipe-cell>
以上这段代码不生效

**Comment by JakeLaoyu** [comment]
请使用模板创建 issue
