### ISSUE TITLE
[Feature Request] van-swipe-cell设置点击左滑出现的按钮，改变rightWidth不能立即生效

### ISSUE THREAD

**Issue by chengaobin** [youzan/vant-weapp#2571]
### 这个功能解决了什么问题
van-swipe-cell设置点击左滑出现的按钮，改变rightWidth不能立即生效

### 建议的API是什么样的
van-swipe-cell设置点击左滑出现的按钮 rightWidth立即生效

**Comment by JakeLaoyu** [comment]
需要 rightWidth 是实时的？

**Comment by chengaobin** [comment]
> 需要 rightWidth 是实时的？

就是类似微信删除消息那种效果，点击删除，删除区域会变长

**Comment by JakeLaoyu** [comment]
微信不是区域变长了，是 删除 按钮变大了

**Comment by chengaobin** [comment]
> 微信不是区域变长了，是 删除 按钮变大了

那vant这个目前能实现这样的效果么

**Comment by chengaobin** [comment]
> 微信不是区域变长了，是 删除 按钮变大了

我仅仅修改我删除按钮的长度，并不能起作用

**Comment by JakeLaoyu** [comment]
vant-weapp 还不支持实时 rightWidth，修改按钮长度的代码可以贴出来看下

**Comment by chengaobin** [comment]
const { position, instance } = event.detail
        switch (position) {
          case 'left':
          case 'cell':
            instance.close()
            break
          case 'right':
            debugger
            if (!this.confirmDel) {
              this.scrollLength = 105
              this.confirmDel = true
              // instance.close()
            } else {

            }
            break
        }
scrollLength 原长度为65，点击删除按钮后设置为105

**Comment by chengaobin** [comment]
> vant-weapp 还不支持实时 rightWidth，修改按钮长度的代码可以贴出来看下

confirmDel是控制按钮的class类的，true的情况设置为105的宽度，scrollLength 是rightWidth的变量

**Comment by chengaobin** [comment]
> > vant-weapp 还不支持实时 rightWidth，修改按钮长度的代码可以贴出来看下
> 
> confirmDel是控制按钮的class类的，true的情况设置为105的宽度，scrollLength 是rightWidth的变量
![image](https://user-images.githubusercontent.com/14012804/71246428-95287080-2351-11ea-8930-56b8b3c203da.png)

**Comment by JakeLaoyu** [comment]
mpvue  么

**Comment by JakeLaoyu** [comment]
按钮的代码看下

**Comment by chengaobin** [comment]
> 按钮的代码看下

wepy ,
![image](https://user-images.githubusercontent.com/14012804/71246784-5a730800-2352-11ea-98a1-f205a0297ef3.png)

**Comment by JakeLaoyu** [comment]
改变按钮不能无法撑开滑动宽度，打开时 需要有足够的宽度才行。

实时 `rightWidth` 我们后面考虑支持

**Comment by chengaobin** [comment]
> 改变按钮不能无法撑开滑动宽度，打开时 需要有足够的宽度才行。
> 
> 实时 `rightWidth` 我们后面考虑支持

目前的情况下，暂时无法实现这样的效果是吧

**Comment by JakeLaoyu** [comment]
> > 改变按钮不能无法撑开滑动宽度，打开时 需要有足够的宽度才行。
> > 实时 `rightWidth` 我们后面考虑支持
> 
> 目前的情况下，暂时无法实现这样的效果是吧

可以做到微信那种，打开时有两个按钮，点击删除时，删除 覆盖另一个按钮。你可以在这个方向试一下

**Comment by chengaobin** [comment]
> > > 改变按钮不能无法撑开滑动宽度，打开时 需要有足够的宽度才行。
> > > 实时 `rightWidth` 我们后面考虑支持
> > 
> > 
> > 目前的情况下，暂时无法实现这样的效果是吧
> 
> 可以做到微信那种，打开时有两个按钮，点击删除时，删除 覆盖另一个按钮。你可以在这个方向试一下

好的。我试试，谢谢
