### ISSUE TITLE
[Bug Report] swipeCell和cellGroup不能显示

### ISSUE THREAD

**Issue by liufengcuit** [youzan/vant-weapp#2572]
### 设备
小米9、微信开发者工具

### VantWeapp 版本
1.0.0

### 基础库版本
2.9.4

### 请提供核心代码片段链接
https://gist.github.com/

### 描述问题
 <van-swipe-cell right-width="{{ 65 }}" left-width="{{ 65 }}">
    <view slot="left">选择</view>
    <van-cell-group>
      <van-cell title="单元格" value="内容" />
    </van-cell-group>
    <van-cell-group>
      <van-cell title="单元格2" value="内容2" />
    </van-cell-group>
    <view slot="right">删除</view>
  </van-swipe-cell>
直接把官方写的例子放进代码中不能正常运行《链接打不开，代码直接贴在这里》

**Comment by JakeLaoyu** [comment]
可以用 https://gitee.com/gists 创建代码片段

**Comment by liufengcuit** [comment]
https://gitee.com/cuit_lf/codes/68m4e9qbk73cyfpr0jh5v90 @JakeLaoyu

**Comment by liufengcuit** [comment]
> https://gitee.com/cuit_lf/codes/68m4e9qbk73cyfpr0jh5v90

van-swipe-cell的宽高都是0

**Comment by JakeLaoyu** [comment]
有没有开启使用 npm 模块，或者是否用了 mpvue 之类的框架

**Comment by JakeLaoyu** [comment]
![image](https://user-images.githubusercontent.com/16181940/71246465-affae500-2351-11ea-9067-2da6303e1f9a.png)

**Comment by liufengcuit** [comment]
button都显示了，就是这个侧滑组件不显示 @JakeLaoyu

**Comment by JakeLaoyu** [comment]
我这边无法复现，看看有没有报错或者 dom 渲染的是什么

**Comment by rex-zsd** [comment]
应该还是组件引入的问题，看下shadowRoot是否正常渲染？
