### ISSUE TITLE
[Bug Report] van-tag 中 需要引入van-icon组件

### ISSUE THREAD

**Issue by wyyxdgm** [youzan/vant-weapp#2574]
### 设备
所有

### VantWeapp 版本
1.0.0

### 基础库版本
1.0.0-beta.4

### 请提供核心代码片段链接
https://codepen.io/gmcode/pen/oNgZqgw

### 描述问题
van-tag 中closeable为true时用到van-icon组件，但是没有引入

**Comment by JakeLaoyu** [comment]
`van-icon` 在哪用的，代码里没体现
