### ISSUE TITLE
DropdownMenu 选择完后，如何高亮或自定义title的样式？

### ISSUE THREAD

**Issue by amyhuangxbd** [youzan/vant-weapp#2575]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater?repo=VantWeapp

**Comment by amyhuangxbd** [comment]
怎么自定义每个dropdownitem的宽度？
目前只有title-class，item上的class

**Comment by rex-zsd** [comment]
查看[样式覆盖文档](https://youzan.github.io/vant-weapp/#/custom-style)
