### ISSUE TITLE
组件使用问题

### ISSUE THREAD

**Issue by zzbk** [youzan/vant-weapp#2577]
这是找来的npm install --save vant-weapp@1.0.0-beta.0，
我稍作修改npm install --save vant-weapp@1.0.0-beta.4，
npm导入的weapp@1.0.0最后一次更新版本是多少啊，我这使用导入 的时候uploader图片不回显、submit-bar样式也并不是官网上的样式？怎么搞的？希望能解决我的疑惑，谢谢！

**Comment by JakeLaoyu** [comment]
新包改名为 @vant/weapp
