### ISSUE TITLE
[Bug Report] van-grid-item同时使用插槽和跳转时报错

### ISSUE THREAD

**Issue by hbxtchenqian** [youzan/vant-weapp#2578]
### 设备
微信开发者工具

### VantWeapp 版本
1.0.0

### 基础库版本
2.9.4

### 如果是 UI 问题，截图链接（多图回车分隔）

![截图](https://i.loli.net/2019/12/23/KTe6zG8jV92uWas.png)

### 请提供核心代码片段链接
https://i.loli.net/2019/12/23/KTe6zG8jV92uWas.png

### 描述问题
https://i.loli.net/2019/12/23/KTe6zG8jV92uWas.png

**Comment by rex-zsd** [comment]
`switchTab`后面多了一个空格。
