### ISSUE TITLE
Skeleton 希望 增加左边图片，右边文字排版

### ISSUE THREAD

**Issue by lyq027** [youzan/vant-weapp#2580]
Skeleton 希望 增加左边图片，右边文字排版

**Comment by Lindysen** [comment]
目前就是左边图片，右边文字的排版

**Comment by Lindysen** [comment]
> Skeleton 希望 增加左边图片，右边文字排版

目前就是左边图片，右边文字的排版

**Comment by lyq027** [comment]
我的意思是类似左边大图，右边文字，像新闻列表那种排版，而不是左边头像那种 @Lindysen

**Comment by Lindysen** [comment]
> 我的意思是类似左边大图，右边文字，像新闻列表那种排版，而不是左边头像那种 @Lindysen

提供一个图片，说明一下

**Comment by Lindysen** [comment]
> > 我的意思是类似左边大图，右边文字，像新闻列表那种排版，而不是左边头像那种 @Lindysen
> 
> 提供一个图片，说明一下

你可以试试 avatar-size,avatar-shape  这两个属性能否实现目标效果

**Comment by lyq027** [comment]
[https://user-images.githubusercontent.com/13057438/71454244-bc0bfa00-27ca-11ea-87bf-ac83ed651e40.png](url)

**Comment by lyq027** [comment]
![](https://user-images.githubusercontent.com/13057438/71454244-bc0bfa00-27ca-11ea-87bf-ac83ed651e40.png)
类似这种 @Lindysen
