### ISSUE TITLE
icon希望新增一个减的图标

### ISSUE THREAD

**Issue by wwwmomo** [youzan/vant-weapp#2583]
![image](https://user-images.githubusercontent.com/32353382/71344037-7d90f800-259c-11ea-9fae-fb29258e0b0d.png)
强迫症犯了，刚好做商品的加减，有加无减。。。

**Comment by rex-zsd** [comment]
图标是单独的`@vant/icon`包维护的，可以去vant那里[提个issue](https://github.com/youzan/vant/issues/new)
