### ISSUE TITLE
第二个van-tab下使用van-notice-bar不滚动

### ISSUE THREAD

**Issue by zoubihai** [youzan/vant-weapp#2588]
<van-tabs active="{{ active }}" color="#ff6400" tab-class="tab-class" tab-active-class="tab-active-class" class="order-tabs">
			<van-tab title="每日福利">
			
			</van-tab>
			<van-tab title="上屏专属">
      
         <van-notice-bar 
        text="足协杯战线连续第2年上演广州德比战，上赛季半决赛上恒大以两回合5-3的总比分淘汰富力。"
         />
			</van-tab>
		</van-tabs>
在第二个van-tab标签下使用van-notice-bar ，van-notice-bar 不滚动了

**Comment by rex-zsd** [comment]
notice-bar组件依赖初始化时获取自身样式数据来开启动画，放在tab里面初始化就失效了。
因为小程序组件缺少相关的生命周期，组件内部是无法解决这个问题的。
可以用`wx:if`手动控制一下notice-bar组件，在显示时渲染组件，让组件成功初始化。
