### ISSUE TITLE
[Feature Request] 是否考虑加入rpx支持

### ISSUE THREAD

**Issue by etarel** [youzan/vant-weapp#2590]
### 这个功能解决了什么问题
支持rpx: 
我看以前有issue提过把单位换成px, 被否决了, 那是否考虑兼容rpx单位呢.
wxss里还是用px, 有样式设置的component添加一个单位设置的参数.

### 建议的API是什么样的

```
<van-component size="{{ 32 }}" unit="rpx"  />
```
或
```
<van-component size="{{ '32rpx' }}" />
```

**Comment by rex-zsd** [comment]
大多数组件的`size`属性应该是可以传`32rpx`这样的值的。
如果发现有某个组件不支持的，可以再提issue过来哈。
