### ISSUE TITLE
[Bug Report] Dialog.confirm 确认按钮超出页面

### ISSUE THREAD

**Issue by lcsoftware** [youzan/vant-weapp#2592]
### 设备
微信小程序

### VantWeapp 版本
1.0.1

### 基础库版本
小程序基础库 2.8.1

### 请提供核心代码片段链接
https://gitee.com/yuemanwan/dashboard/projects/yuemanwan/MiniApp/blob/master/NApp/miniprogram/pages/customers/order/list.js

### 描述问题
微信小程序内如下调用，其实GoodsAction组件也存在类似问题
Dialog.confirm({
            title: '标题',
            message: '弹窗内容'
        }).then(() => {
            console.log('============ ok ')
        }).catch(() => { 
            console.log('============ cancel')
        });

**Comment by Airam1016** [comment]
我也发现了这个问题，我把基础库降到2.7.7就可以了

**Comment by linlinNB** [comment]
我也发现了，还没办法覆盖掉样式

**Comment by linlinNB** [comment]
@Airam1016 但是在真机运行的时候，因为微信版本的问题，这个问题还会复现出现。

**Comment by linlinNB** [comment]
@lcsoftware 请问你现在解决了吗？

**Comment by chenjiahan** [comment]
参见 https://github.com/youzan/vant-weapp/issues/2178

**Comment by rex-zsd** [comment]
😢

**Comment by lcsoftware** [comment]
@linlinNB 
app.json 删除 "style": "v2" 可以解决

**Comment by linlinNB** [comment]
@lcsoftware @chenjiahan 谢谢解惑

**Comment by WDShan** [comment]
新手，反映个情况，如果app.json 删除 "style": "v2" ，引用button，cell控件会出现样式不生效的情况出现，得此失彼，还望各位大佬解答
