### ISSUE TITLE
[Bug Report] van-datetime-picker结合van-popup用时设置初始值不起作用

### ISSUE THREAD

**Issue by ChangeZhang** [youzan/vant-weapp#2593]
### 设备
ios

### VantWeapp 版本
1.0.1

### 基础库版本
2.7.0

### 请提供核心代码片段链接
https://gist.github.com/ChangeZhang/dbbf41e6a458b9aa09f8d9a44a497438

### 描述问题
van-datetime-picker结合van-popup用时设置初始值不起作用

**Comment by ChangeZhang** [comment]
用的是滴滴的 mpx框架

**Comment by ChangeZhang** [comment]
直接把van-datetime-picker组件放在页面上时 没有问题

**Comment by a1029382825** [comment]
应该是因为组建中使用了小程序获取元素大小和位置的api,van-popup组件没有打开时组件没有渲染,导致获取失败,我在van-popup组件中使用van-tabs时,初始时没有办法在第一个tab下面显示代表选中横线

**Comment by ChangeZhang** [comment]
@rex-zsd

**Comment by rex-zsd** [comment]
@ChangeZhang 上传一个代码片段吧，搞各种框架环境很头疼

**Comment by ChangeZhang** [comment]
@rex-zsd 框架的问题，跟vant-weapp无关  关闭了。麻烦了。
