### ISSUE TITLE
field字数统计怎么使用

### ISSUE THREAD

**Issue by liuxiaodi** [youzan/vant-weapp#2594]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater?repo=VantWeapp

文档上面有field的字数统计演示，但是相应怎么使用并没有说明，请问是怎么使用？

**Comment by rex-zsd** [comment]
字数统计是 Vant 的功能，Vant Weapp 暂未支持的。

**Comment by galikeoy** [comment]
文档上的的演示demo，是vant的，所以，看看效果就好，以底部api为主
