### ISSUE TITLE
表单中提样使用提交按钮

### ISSUE THREAD

**Issue by ycqqcom** [youzan/vant-weapp#2595]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater?repo=VantWeapp

我在微信小程序中使用
` <form bindsubmit="updatecompany"><van-button type="info">信息按钮</van-button</form>`

怎样才能提交表单到updatecompany当中？

**Comment by ycqqcom** [comment]
`<van-button type="info" block  bind:click="update_company" >更新信息</van-button>`
已解决，原来用bind:click="方法名"。
但是方法名下面如何接收多个input的值呢？

**Comment by rex-zsd** [comment]
可以把参数挂在`van-button`上，`data-xx`的形式，在事件中自己获取一下。
