### ISSUE TITLE
[Bug Report] process属性show-pivot不起作用

### ISSUE THREAD

**Issue by xichunjie** [youzan/vant-weapp#2600]
### 设备
微信开发者工具，vivox7

### VantWeapp 版本
1.0.1

### 基础库版本
2.9.4

### 如果是 UI 问题，截图链接（多图回车分隔）

![截图](https://i.loli.net/2019/12/26/oDa3ChtkYMslgy7.png)

### 请提供核心代码片段链接
https://gitee.com/tian_xuan/codes/tos1hj5uvz8fbyi0gdmw623

### 描述问题
process属性show-pivot不起作用，设置了false还是有数字

**Comment by Lindysen** [comment]
> ### 设备
> 微信开发者工具，vivox7
> 
> ### VantWeapp 版本
> 1.0.1
> 
> ### 基础库版本
> 2.9.4
> 
> ### 如果是 UI 问题，截图链接（多图回车分隔）
> ![截图](https://camo.githubusercontent.com/c26c7c64fcbe648980cb526c3f86db76dbb36118/68747470733a2f2f692e6c6f6c692e6e65742f323031392f31322f32362f6f4461334368746b594d736c6779372e706e67)
> 
> ### 请提供核心代码片段链接
> https://gitee.com/tian_xuan/codes/tos1hj5uvz8fbyi0gdmw623
> 
> ### 描述问题
> process属性show-pivot不起作用，设置了false还是有数字

核心代码片段链接打不开

**Comment by xichunjie** [comment]
<van-progress style="width:75%;margin-left:10%;margin-top:100rpx;" percentage="50" stroke-width="8" show-pivot="false" />代码就这个

**Comment by xichunjie** [comment]
@Lindysen 代码就这个<van-progress style="width:75%;margin-left:10%;margin-top:100rpx;" percentage="50" stroke-width="8" show-pivot="false" />

**Comment by xichunjie** [comment]
@Lindysen `<van-progress style="width:75%;margin-left:10%;margin-top:100rpx;" percentage="50" stroke-width="8" show-pivot="false" />`代码就这个

**Comment by JakeLaoyu** [comment]
show-pivot="{{ false }}"

**Comment by xichunjie** [comment]
@JakeLaoyu 额。。我之前也这么设置的，不过还是有，刚才我又试了下，可以了，不好意思啊
