### ISSUE TITLE
[Bug Report] van-tabs 动态异步添加 tab 时后，tabs下方的高亮线没有更新

### ISSUE THREAD

**Issue by KawayAlpaka** [youzan/vant-weapp#2604]
### 设备
开发环境

### VantWeapp 版本
1.0.1

### 基础库版本
2.9.0

### 如果是 UI 问题，截图链接（多图回车分隔）

![截图](https://i.loli.net/2019/12/26/hsSj1EnCXm3cZOV.png)

### 请提供核心代码片段链接
https://gist.github.com/KawayAlpaka/73d442edf0e66014988fd1cf8679b121

### 描述问题
van-tabs 动态异步添加 tab 时后，tabs下方的高亮线没有更新。
页面初始化时，data中有一个 type，页面完全载入后，异步添加了几个 type，tabs渲染出来后，下面的红线位置没有根据tab的增加调整位置和长度

**Comment by frei-x** [comment]
我之前也发现了这个问题 , tab是根据数据动态生成的

**Comment by gromit1sm** [comment]
+1.... ![image.png](https://i.loli.net/2019/12/31/LqAegYhxbadD4Ji.png)

**Comment by gromit1sm** [comment]
下划横线很长应该是初始化只有一个tab 的原因

**Comment by sherryQwl** [comment]
tab全部是异步添加的，没有默认tab，tabs下方没有高亮线。报错说没有width
![image](https://user-images.githubusercontent.com/29192185/93964613-a5fb8c00-fd92-11ea-8ee3-417c16e5b526.png)

**Comment by Yangwenhua44** [comment]
> tab全部是异步添加的，没有默认tab，tabs下方没有高亮线。报错说没有width。哪位大佬帮忙看看
> ![image](https://user-images.githubusercontent.com/29192185/93964613-a5fb8c00-fd92-11ea-8ee3-417c16e5b526.png)

必须得设置有横线,不设置不行,或者设置有误也不行
