### ISSUE TITLE
[Bug Report] 微信开发者工具mac版本van-swipe-cell侧滑卡死

### ISSUE THREAD

**Issue by jiangen1016** [youzan/vant-weapp#2608]
### 设备
微信开发者工具

### VantWeapp 版本
1.0.1

### 基础库版本
2.9.4

### 如果是 UI 问题，截图链接（多图回车分隔）

![截图](https://i.loli.net/2019/12/26/hmK8qnrpovlRGCf.gif)

### 请提供核心代码片段链接
https://gist.github.com/jiangen1016/f96cbb17c44572816bb5a3924ee092f5

### 描述问题
升级版本库至1.0.1 后，开发者工具van-swipe-cell滑动很卡，开发者各个版本都试过了，mac版本的卡，Windows的测试正常，android真机测试正常，ios真机测试正常。

**Comment by jiangen1016** [comment]
[截图连接](https://i.loli.net/2019/12/26/hmK8qnrpovlRGCf.gif)

**Comment by yaoshanliang** [comment]
同，请问解决了吗？
