### ISSUE TITLE
能否提供几个list的模版例子

### ISSUE THREAD

**Issue by neozhu** [youzan/vant-weapp#2609]
用list展示数据非常的常用，但作为纯开发的，对UI这块实在是太弱了比如参考常见的类似股票显示的
------------------------------------
股票名称              最新价格      涨幅
股票代码
------------------------------------
不同的字体样式，对齐方式，外加一些背景和小的tag标记
类似《蚂蚁财富》app 的显示样式
card 样式 最好是能作出taobao，天猫 app 里的样式。
当然了如果能做出来出点钱也是应该的

**Comment by JakeLaoyu** [comment]
暂时没有计划提供
