### ISSUE TITLE
cell 组件无法重置样式加了 !important也无效

### ISSUE THREAD

**Issue by liberty-m** [youzan/vant-weapp#261]
cell 组件无法重置样式加了 !important也无效 
请问有提供相应的样式入口方案吗? 求解

**Comment by veking** [comment]
也遇到过这样的问题，而且引入外部样式也不行，如card组件无法修改thumb图片大小，参考微信官方的文档，组件外部样式是存在这种问题，但是没有提供解决方案，难道只能重新自定义组件吗？是否还有其它方式？
![image](https://user-images.githubusercontent.com/10131151/40344671-6c92e9b6-5dc8-11e8-95cc-f4c30af74e91.png)

**Comment by pangxie1991** [comment]
具体需要重置什么样的样式？
类似 cell，其实只是一个简单的容器
card 现在只支持自定义根节点样式，没有开放各个元素内部自定义的。这个也是微信的限制，除非给每个元素都加上外部样式类。但是这样就限制死了组件了。

**Comment by liberty-m** [comment]
就是重置成我要要的样式 但是覆盖不了 就是无法自定义 
比如 .btn{color:red} 我想改成 .btn{color:green}无法修改的

**Comment by laravuel** [comment]
对啊，这是一个问题

**Comment by chenjiahan** [comment]
目前 zanui-weapp 已进行全新的品牌升级，更名为 Vant Weapp，组件和 API 都有较大的变化。

对 zanui-weapp 的讨论，请移步至 https://github.com/youzan/zanui-weapp 仓库
