### ISSUE TITLE
[Feature Request] Vant-Button组件click传参

### ISSUE THREAD

**Issue by Lan-megumi** [youzan/vant-weapp#2614]
### 这个功能解决了什么问题
如果用Bind:click的话似乎无法得到 data-*，貌似bind:click也不支持 function(params) 直接往括号 里传参的写法，如果是这样的话怎么传参？难道要用回 bindtap？如果是这样实在有点可惜...如果有别的方法可以告诉我，我也不确定有没有别的方法

### 建议的API是什么样的
有一个类似 data-*这样的api，这个*可以是固定的，这样可以直接往里面写入值（静态的，比如Number、Boolean、String）
------
当然我也只是刚用小程序不足一个月的前端开发者...以前用的Vue写的很舒服
另外官方何时开通QQ群啊...微信的二维码国内看不到啊啊啊啊
找人交流都没有

**Comment by galikeoy** [comment]
我也是刚写小程序
1. bind:click在回调参数中可以得到data-*
2. bind:click只可以填写函数名，传参以data-*的形式
为什么要用回bindtap？官方文档写了，加不加冒号含义都不变

**Comment by Lan-megumi** [comment]
> 我也是刚写小程序
> 
> 1. bind:click在回调参数中可以得到data-*
> 2. bind:click只可以填写函数名，传参以data-*的形式
>    为什么要用回bindtap？官方文档写了，加不加冒号含义都不变

啊是可以哦...
看来我被那个久远的issue的误导了
https://github.com/youzan/vant-weapp/issues/691

不过回过头又看了下
那个issue是在使用 open-type 的时候无法获取到 data-
