### ISSUE TITLE
[Bug Report] 下拉菜单异步加载后 默认选中的项不显示在菜单中

### ISSUE THREAD

**Issue by zreux** [youzan/vant-weapp#2616]
### 设备
Android

### VantWeapp 版本
1.0.1

### 基础库版本
2.9.4

### 如果是 UI 问题，截图链接（多图回车分隔）

![截图](https://i.loli.net/2019/12/27/CcjPvHIxdQzshTR.png)

### 请提供核心代码片段链接
https://gist.githubusercontent.com/zreux/3422df59b6e4840c6e05ceebf2caf77f/raw/bf0eeebce823523a77c7167dea2f7ea72c098a4b/vant%2520debug

### 描述问题
从服务器异步加载下拉列表的选项 并设置第一项为默认选中 下拉菜单的选中标题为空 不会变成默认选择的标题
如果将下拉菜单选择项直接写在代码中 则不会出现该问题

**Comment by JakeLaoyu** [comment]
无法复现

```javascript
Page({
  data: {
    option1: [],
    option2: [],
    value1: 0,
    value2: 'd'
  },

  onReady() {
    setTimeout(() => {
      this.setData({
        option1: [
          { text: '全部商品', value: 1 },
          { text: '新款商品', value: 2 },
          { text: '活动商品', value: 3 }
        ],
        option2: [
          { text: '默认排序', value: 'a' },
          { text: '好评排序', value: 'b' },
          { text: '销量排序', value: 'c' }
        ],
      });

      this.setData({
        value1: 1,
        value2: 'a'
      });
    }, 1000);
  }
});
```

![Kapture 2020-01-12 at 13 05 54](https://user-images.githubusercontent.com/16181940/72214411-4af37300-353c-11ea-8c5d-b4a3fee2c25b.gif)
