### ISSUE TITLE
[Bug Report] dialog对话框确认按钮溢出导致文字不居中

### ISSUE THREAD

**Issue by Michel111** [youzan/vant-weapp#2617]
### 设备
iphoneX

### VantWeapp 版本
1.0.1

### 基础库版本
2.80-2.91

### 如果是 UI 问题，截图链接（多图回车分隔）

![截图](https://sm.ms/image/OV5Yvba8TqgycXD)

### 请提供核心代码片段链接
https://gist.github.com/Michel111/f54324308739d3b17e6651dda37b81dc

### 描述问题
微信官方给button设置了新的样式 button:not([size='mini']) ，其中 的width导致了文字不居中，对许多老项目造成影响，建议修复

**Comment by rex-zsd** [comment]
在配置文件中去除`style: "v2"`即可
#1937
