### ISSUE TITLE
[Bug Report] field控件添加slot展现不对

### ISSUE THREAD

**Issue by Donald-Chun** [youzan/vant-weapp#2618]
### 设备
iPhoneXS iOS 13.3, WeChat 7.0.8

### VantWeapp 版本
1.0.1

### 基础库版本
2.9.4(2019.12.23 19:01:27)

### 请提供核心代码片段链接
https://gist.github.com/Donald-Chun/7c33d11f96b09c96a07cb941afaefc3d

### 描述问题

用的就是官方文档里的代码，展现的结果，和官方展现出来的结果不一致。

**Comment by Donald-Chun** [comment]
找到问题了。把app.js里的 "style":"v2" 去掉就好了。希望官方能兼容。

**Comment by rex-zsd** [comment]
#1937
