### ISSUE TITLE
steps组件样式错误

### ISSUE THREAD

**Issue by liuxiaodi** [youzan/vant-weapp#2619]
在小程序页面中使用steps。
代码如下:
data: {
    active: 1,
    steps: [
      { text: '步骤一' },
      { text: '步骤二' },
      { text: '步骤三' },
      { text: '步骤四' },
      { text: '步骤五' }
    ]
  }

<van-steps
    steps="{{ steps }}"
    active="{{ active }}"
  />
“步骤一”的空白会遮盖“步骤二”，导致“步骤二”的文字显示不全。依次类推，步骤三，步骤四也被遮住

**Comment by Lindysen** [comment]
无法复现，可以提供代码片段
