### ISSUE TITLE
tabs组件文案找不到自定义的说明。右边的案例有。

### ISSUE THREAD

**Issue by kongta** [youzan/vant-weapp#2622]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater?repo=VantWeapp

**Comment by rex-zsd** [comment]
以左边文档为准哈，预览顶部有提示了，显示的是vant的预览，部分功能与vant-weapp不一致的。

**Comment by kongta** [comment]
> 以左边文档为准哈，预览顶部有提示了，显示的是vant的预览，部分功能与vant-weapp不一致的。

也就是说小程序版本没自定义吗。。。

**Comment by rex-zsd** [comment]
是的

**Comment by kongta** [comment]
> 是的

好的谢谢大佬回复。希望以后可以加上
