### ISSUE TITLE
icon错乱

### ISSUE THREAD

**Issue by Wang-ll** [youzan/vant-weapp#2624]
使用npm构建后，发现之前使用的icon例如search、send-gift-o等都发生了错乱，并且和之前单独下载时的wxss文件作比较，发现里面的内容确实不一致

https://youzan.github.io/vant-issue-generater?repo=VantWeapp

**Comment by rex-zsd** [comment]
issue格式不符，未提供截图、核心代码等，demo小程序也未复现问题。
