### ISSUE TITLE
[Bug Report] van-tab里的fixed元素在真机上隐藏

### ISSUE THREAD

**Issue by gromit1sm** [youzan/vant-weapp#2625]
### 设备
iPhone 11 iOS 13.3

### VantWeapp 版本
1.0.2

### 基础库版本
2.9.4

### 如果是 UI 问题，截图链接（多图回车分隔）

![截图](https://sm.ms/image/hTx1CmkKotzbWyR)

![截图](https://sm.ms/image/CcQuZqFvPJl7RfH)

![截图](https://sm.ms/image/5kz2VbREyCQG68Z)

### 请提供核心代码片段链接
https://gist.github.com/gromit1sm/b08a9175961b95f0543a7ffdc7ad1e2d

### 描述问题
van-tab下fixed元素在iPhone11 iOS13.3下不能显示

**Comment by gromit1sm** [comment]
![image.png](https://i.loli.net/2019/12/31/hTx1CmkKotzbWyR.png)
![image.png](https://i.loli.net/2019/12/31/CcQuZqFvPJl7RfH.png)
![image.png](https://i.loli.net/2019/12/31/5kz2VbREyCQG68Z.png)

**Comment by gromit1sm** [comment]
![截图](https://i.loli.net/2019/12/31/hTx1CmkKotzbWyR.png)
![截图](https://i.loli.net/2019/12/31/5kz2VbREyCQG68Z.png)
![截图](https://i.loli.net/2019/12/31/CcQuZqFvPJl7RfH.png)

**Comment by JakeLaoyu** [comment]
这是小程序渲染的问题
tab content 高度没有达到 定位元素的位置，在手机上显示不出来。或者吧 定位元素放到外层

**Comment by gromit1sm** [comment]
> 这是小程序渲染的问题
> tab content 高度没有达到 定位元素的位置，在手机上显示不出来。或者吧 定位元素放到外层

谢谢回复！我的用你说的第二种方法暂时解决了问题
