### ISSUE TITLE
微信小程序van-button绑定 form-type="submit"，点击按钮无效

### ISSUE THREAD

**Issue by jiayuxiaochaoren** [youzan/vant-weapp#2628]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater?repo=VantWeapp

**Comment by rex-zsd** [comment]
看下微信的文档哈，自定义组件上`form-type`是没有用的
