### ISSUE TITLE
在 vant-weapp 中 添加插槽无效，希望可以尽快回复方案，在线等

### ISSUE THREAD

**Issue by ColelAi** [youzan/vant-weapp#2631]
文档地址
https://youzan.github.io/vant-weapp/#/steps#api

在 vant-weapp 中 添加插槽无效，希望可以尽快回复方案，在线等

`
<van-steps steps="{{ uinfo.steps }}" active="{{ active }}" id="qqqaaa" direction="vertical" active-color="#ee0a24"  >
      <van-button slot="button" class="pretel" size="small" type="primary" bindtap="addtel">保存到通讯录</van-button>
</van-steps>
`

**Comment by rex-zsd** [comment]
是无效的呀…………文档中没有体现可以用slot吧

**Comment by ColelAi** [comment]
> 是无效的呀…………文档中没有体现可以用slot吧

我直接在组件中去添加了slot

**Comment by ColelAi** [comment]
> 是无效的呀…………文档中没有体现可以用slot吧

我直接在依赖中去添加了slot，现在可以了
