### ISSUE TITLE
[Bug Report] Vant-weapp field textarea报错

### ISSUE THREAD

**Issue by Hyejeongdd** [youzan/vant-weapp#2632]
### 设备
所有设备

### VantWeapp 版本
1.0.2

### 基础库版本
2.10.0

### 请提供核心代码片段链接
https://gist.github.com

### 描述问题
控制台报错 VM887:1 insertTextArea:fail not support

**Comment by Lindysen** [comment]
核心代码片段 好像看不了

> ### 设备
> 所有设备
> 
> ### VantWeapp 版本
> 1.0.2
> 
> ### 基础库版本
> 2.10.0
> 
> ### 请提供核心代码片段链接
> https://gist.github.com
> 
> ### 描述问题
> 控制台报错 VM887:1 insertTextArea:fail not support

核心代码片段好像看不了

**Comment by Hyejeongdd** [comment]
> 核心代码片段 好像看不了
> 
> > ### 设备
> > 所有设备
> > ### VantWeapp 版本
> > 1.0.2
> > ### 基础库版本
> > 2.10.0
> > ### 请提供核心代码片段链接
> > https://gist.github.com
> > ### 描述问题
> > 控制台报错 VM887:1 insertTextArea:fail not support
> 
> 核心代码片段好像看不了



> 核心代码片段 好像看不了
> 
> > ### 设备
> > 所有设备
> > ### VantWeapp 版本
> > 1.0.2
> > ### 基础库版本
> > 2.10.0
> > ### 请提供核心代码片段链接
> > https://gist.github.com
> > ### 描述问题
> > 控制台报错 VM887:1 insertTextArea:fail not support
> 
> 核心代码片段好像看不了

好像是微信调试基础库的问题 代码参照官网demo即可

**Comment by rex-zsd** [comment]
https://developers.weixin.qq.com/community/develop/doc/000e24c12f8cb8df1fb9691f356000
