### ISSUE TITLE
[Bug Report] pop弹出框过度动画缺失

### ISSUE THREAD

**Issue by henryWuHZ** [youzan/vant-weapp#2636]
### 设备
iphoneXr

### VantWeapp 版本
1.0.2

### 基础库版本
2.10.0

### 请提供核心代码片段链接
https://youzan.github.io/vant-weapp/#/intro

### 描述问题
官方组件示例小程序，popup过度动画缺失，有时候第一次点击有动画，但是连续点击动画缺失；

**Comment by JakeLaoyu** [comment]
无法复现

**Comment by pandaApe** [comment]
Hi @jackieyk 
Vant 官方组件示例小程序 和文档的实例对比一下。[https://youzan.github.io/vant-weapp/#/popup]( https://youzan.github.io/vant-weapp/#/popup)

小程序上都没有动画的。

**Comment by neozhu** [comment]
是不是把基础版本降低看看，我发现基础版本存在一些兼容问题

**Comment by amou-zeng** [comment]
是的。官版也有这个问题

**Comment by rex-zsd** [comment]
@amou-zeng 请问可复现的是什么设备呢？
