### ISSUE TITLE
这个错误怎么消掉？

### ISSUE THREAD

**Issue by chunbobo** [youzan/vant-weapp#2646]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater?repo=VantWeapp

![image](https://user-images.githubusercontent.com/16535982/71783111-012afa00-301d-11ea-8651-1b4a9e1b544b.png)

**Comment by rex-zsd** [comment]
这个是微信开发者工具加载字体文件的时候偶发的问题，真机上不会出现。
开发者工具上可以刷新一下，应该会消失。
