### ISSUE TITLE
[Bug Report] DropdownMenu 的change事件无反映

### ISSUE THREAD

**Issue by lbs2016** [youzan/vant-weapp#2647]
### 设备
微信开发工具

### VantWeapp 版本
1.0.2

### 基础库版本
2.6.4

### 请提供核心代码片段链接
http://zanshi.buneng.com/

### 描述问题

<van-dropdown-menu onTitleTap="onMenuChange">
  <van-dropdown-item title-class="工种" value="{{skillType}}" data-list="skillType" change="onMenuChange" options="{{skillTypes}}" />
  <van-dropdown-item value="{{ skillType }}" options="{{ skillTypes }}" />
</van-dropdown-menu>

 onMenuChange(e) {
        console.log('onMenuChange', e);
    },

操作菜单后，无log生成

**Comment by Lindysen** [comment]
无法看到核心代码片段
