### ISSUE TITLE
[Bug Report] app.json使用"style": "v2"配置后弹窗组件的button大小不对

### ISSUE THREAD

**Issue by feifeiwuxian** [youzan/vant-weapp#2648]
### 设备
iphone6s

### VantWeapp 版本
1.0.1

### 基础库版本
2.9.4

### 如果是 UI 问题，截图链接（多图回车分隔）

![截图](https://sm.ms/image/m94VFpcs8RjPr1I)

### 请提供核心代码片段链接
https://gist.github.com/feifeiwuxian/e796124128e89cdc16b72b8fb66bf815

### 描述问题
app.json使用"style": "v2"配置后弹窗组件的button大小不对，导致偏移

**Comment by rex-zsd** [comment]
暂时不要开启`"style": "v2"`哈，开启以后微信强制加上了很多样式，难以覆盖的。
