### ISSUE TITLE
低版本升级到高版本项目报错

### ISSUE THREAD

**Issue by juqingzhenfuza** [youzan/vant-weapp#2649]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater?repo=VantWeapp

**Comment by juqingzhenfuza** [comment]
以前用的是低版本的vantui现在想升级到高版本后报错很多怎么解决

**Comment by rex-zsd** [comment]
issue格式不规范额，也不说具体是什么问题，没办法帮助你了。
建议进微信群跟群友交流一下哈。
