### ISSUE TITLE
DropdownMenu 

### ISSUE THREAD

**Issue by AnKangZhouWei** [youzan/vant-weapp#2650]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater?repo=VantWeapp
使用DropdownMenu组件，如果筛选菜单不是在页面顶部 ，页面向上滚动的时候筛选下会随着滚动条滚动，不受控制，因为下拉筛选是fixed

**Comment by JakeLaoyu** [comment]
https://youzan.github.io/vant-issue-generater?repo=VantWeapp 请使用模板提交
