### ISSUE TITLE
[BUG REPORT] tabs组件未考虑内容后加载的问题，导致sticky属性无效

### ISSUE THREAD

**Issue by echokh** [youzan/vant-weapp#2651]
设备
Android

VantWeapp 版本
1.0.0

基础库版本
2.8.0
在界面初始化时对container进行初始化，导致填充后内容的高度没有加进来

**Comment by Maconzhang** [comment]
ios 也会

**Comment by echokh** [comment]
> ios 也会

是的

**Comment by Lindysen** [comment]
fix #2674

**Comment by wxuonline** [comment]
刚碰到这个问题，临时解决方案：

1. 在<van-tabs>元素中添加监听变化的数据：
       `:sticky-data="activeData" ` (uni-app写法)
2. 在wxcomponents\tabs\index.js中增加props：

    `stickyData: Object,`
3. 在wxcomponents\tabs\index.wxml中<van-sticky>元素上增加传递变化数据：
    `sticky-data="{{ stickyData }}"`
4. 修改wxcomponents\sticky\index.js
    增加props:  `stickyData: Object,`
    监听数值变化： `watch: {
        stickyData(newVal, oldVal) {
            if (newVal !== oldVal) {
                this.observeContainer();
            }
        }
    },`
_（有问题欢迎补充）_

**Comment by echokh** [comment]
我是在数据加载完之后对container重新赋值
  let tabs = Util.getComponent("#apptabs");
    if (Util.isDef) {
      tabs.setData({
        container: () => tabs.createSelectorQuery().select('.van-tabs')
      });
    }

**Comment by Maconzhang** [comment]
> 刚碰到这个问题，临时解决方案：
> 
> 1. 在van-tabs元素中添加监听变化的数据：
>    `:sticky-data="activeData" ` (uni-app写法)
> 2. 在wxcomponents\tabs\index.js中增加props：
>    `stickyData: Object,`
> 3. 在wxcomponents\tabs\index.wxml中van-sticky元素上增加传递变化数据：
>    `sticky-data="{{ stickyData }}"`
> 4. 修改wxcomponents\sticky\index.js
>    增加props:  `stickyData: Object,`
>    监听数值变化： `watch: { stickyData(newVal, oldVal) { if (newVal !== oldVal) { this.observeContainer(); } } },`
>    _（有问题欢迎补充）_

vant 是哪个版本？

**Comment by wxuonline** [comment]
> > 刚碰到这个问题，临时解决方案：
> > 
> > 1. 在van-tabs元素中添加监听变化的数据：
> >    `:sticky-data="activeData" ` (uni-app写法)
> > 2. 在wxcomponents\tabs\index.js中增加props：
> >    `stickyData: Object,`
> > 3. 在wxcomponents\tabs\index.wxml中van-sticky元素上增加传递变化数据：
> >    `sticky-data="{{ stickyData }}"`
> > 4. 修改wxcomponents\sticky\index.js
> >    增加props:  `stickyData: Object,`
> >    监听数值变化： `watch: { stickyData(newVal, oldVal) { if (newVal !== oldVal) { this.observeContainer(); } } },`
> >    _（有问题欢迎补充）_
> 
> vant 是哪个版本？

12月10号clone的代码，应该是1.0.0

**Comment by maplehsu** [comment]
this.tab = this.selectComponent('#tab')
      this.tab.setData({
        container: () => this.tab.createSelectorQuery().select('.van-tabs')
      })

目前这么解决的。但是太傻了。希望官方赶快修复

**Comment by Maconzhang** [comment]
> this.tab = this.selectComponent('#tab')
> this.tab.setData({
> container: () => this.tab.createSelectorQuery().select('.van-tabs')
> })
> 
> 目前这么解决的。但是太傻了。希望官方赶快修复

能否稍微具体点，container是指？

**Comment by maplehsu** [comment]
> > this.tab = this.selectComponent('#tab')
> > this.tab.setData({
> > container: () => this.tab.createSelectorQuery().select('.van-tabs')
> > })
> > 目前这么解决的。但是太傻了。希望官方赶快修复
> 
> 能否稍微具体点，container是指？

#tab 就是你在那个组件起一个id， 然后container 你看他源码tab初始化就是用的这个，只不过重新赋值一下，我理解的，进入页面初始化一次tab，然后异步数据tab没有内容无法触发吸顶，然后在数据回来的时候又重新初始化了一次，现在就有内容了。可以获取高度了。

**Comment by rex-zsd** [comment]
小程序目前监测不到slot内容的变化，下版本会尝试用其他方式绕过这个问题。

**Comment by hansenlou** [comment]
希望尽快解决，现在用到tabs的地方很多哦

> 小程序目前监测不到slot内容的变化，下版本会尝试用其他方式绕过这个问题。

**Comment by kingeight** [comment]
碰到同样的问题，主要是observer返回的是上一个tab页的高度，如果当前tab页的高度大于上一个tab页，在页面滚动到上一个tab页高度的时候会触发订阅事件，具体就是sticky/index.js代码里这一段：
`
               containerObserver.observe(ROOT_ELEMENT, res => {
                  if (this.data.disabled) {
                        return;
                    }
                    this.setFixed(res.boundingClientRect.top);
                });
`

事实上，当这里的res.boundingClientRect的top绝对值大于上一个tab页高度的时候，setFiexed方法就会取消粘性布局，解决方法很简单，把上述代码的if判断条件改成下面这样：
`
if (this.data.disabled || (res.boundingClientRect.top < 0 && res.boundingClientRect.bottom<0)) {
         return;
 }
`

**Comment by aymfx** [comment]
wepy这个临时解决方案
wx.nextTick(() => {
            this.$wx.selectComponent('.cate-tabs').updateContainer()
          })
