### ISSUE TITLE
[Bug Report] mpvue submit bar price 不能绑定变量

### ISSUE THREAD

**Issue by gtyang** [youzan/vant-weapp#2653]
### 设备
模拟器

### VantWeapp 版本
1.0.2

### 基础库版本
1.0.2

### 请提供核心代码片段链接
https://gist.github.com/

### 描述问题
    <van-submit-bar
      :price="10030"
      button-text="入库"
      @submit="onSubmit">
      <van-checkbox :value="allChecked" checked-color="#07c160" @change="selectAll">全选</van-checkbox>              
    </van-submit-bar>

:price="3050"

可以正常显示价格，但是都是需要绑定一个变量的啊，比如这段代码中的

:price="total" 就会显示 NaN

其他的控件是能正常工作的，比如上面的 checkbox

**Comment by JakeLaoyu** [comment]
![image](https://user-images.githubusercontent.com/16181940/72137391-b9fa8b80-33c5-11ea-85f7-7264f64e1c9b.png)
![image](https://user-images.githubusercontent.com/16181940/72137399-bbc44f00-33c5-11ea-804e-78e141fe0a58.png)
无法复现

**Comment by gtyang** [comment]
我犯错误了，没问题。。。
