### ISSUE TITLE
一个页面有两个日期选择器，当重新选择其中一个时，在去选择另外一个时，默认选中的值是根据第一个选中值的索引选中，v-model就无效了，我是想根据v-model的值来设置选择器默认选中的值，请问这个问题怎么解决？

### ISSUE THREAD

**Issue by dynelly** [youzan/vant-weapp#2654]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater?repo=VantWeapp

**Comment by rex-zsd** [comment]
isseu格式不符，无法确认你的问题。
小程序也不支持`v-model`。
