### ISSUE TITLE
picker多级联动时，第二列values变化时，defaultIndex设置无效

### ISSUE THREAD

**Issue by FuXiuyang** [youzan/vant-weapp#2656]
picker多级联动时，第二列values变化时，defaultIndex设置无效。defaultIndex即便设置成功，但是前端页面依然显示数组中第0个元素值。
![image](https://user-images.githubusercontent.com/20715755/71995590-cd96dc80-3275-11ea-82aa-42516ceba7a7.png)
![image](https://user-images.githubusercontent.com/20715755/71995618-d7b8db00-3275-11ea-81a3-3d4cabc33af8.png)
比如我从图一变成图二，我先将第一列从2020年滑动到2019年。
逻辑处理：将第二列可选年份由2020年变成[2019, 2020]两个年份。设置方式通过setColumnValues方法。
我希望的目标结果是：第二列保持2020年。
我的实现方式是：设置第二列的defaultIndex=1
目前的结果是：defaultIndex=1设置成功后，第二列依然展示2019年

**Comment by rex-zsd** [comment]
`defaultIndex`是用来设置默认项的，不是用来指定当前的选中项的。
