### ISSUE TITLE
[Bug Report] sizeType="['compressed']" 无法上传压缩图片

### ISSUE THREAD

**Issue by hihuangwei** [youzan/vant-weapp#2660]
### 设备
所有设备

### VantWeapp 版本
1.0.2

### 基础库版本
2.10.0

### 请提供核心代码片段链接
https://youzan.github.io

### 描述问题
sizeType="['compressed']" 无法上传压缩图片

**Comment by Lindysen** [comment]
sizeType="{{ ['compressed'] }}"
