### ISSUE TITLE
在tab标签里使用position: fixed;不会相对于屏幕定位的问题

### ISSUE THREAD

**Issue by wangyinpeng123** [youzan/vant-weapp#2664]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater?repo=VantWeapp

**Comment by JakeLaoyu** [comment]
https://youzan.github.io/vant-issue-generater?repo=VantWeapp  请使用模板创建issue
