### ISSUE TITLE
图片上传组件编译错误

### ISSUE THREAD

**Issue by tanwenchao** [youzan/vant-weapp#2665]
<van-uploader :file-list="step1.fileList" :max-count="1" @after-read="afterRead">

编译后的index.vue.wxml
<van-uploader file-list="{{step1.fileList}}" max-count="{{1}}" bindafter-read="handleProxy" data-eventid="{{'4'}}" data-comkey="{{$k}}" class="_van-uploader data-v-db48d7a2"></van-uploader>

bindafter-read这里出了问题

**Comment by JakeLaoyu** [comment]
补充一下什么问题

**Comment by tanwenchao** [comment]
使用mpvue + vant
使用van-button的时候传入disabled样式有效 但是点击事件仍然可以执行

使用van-uploader的时候van-uploader :file-list="step1.fileList" :max-count="1" @after-read="afterRead" afterRead没有收到子组件的通信 无回调。  看编译后的文件编译成了bindafter-read="handleProxy"  似乎少了个冒号

**Comment by JakeLaoyu** [comment]
mpvue 事件不支持中划线，使用驼峰看看

**Comment by tanwenchao** [comment]
还是不行 按钮组件disabled属性也没用 什么情况

**Comment by tanwenchao** [comment]
纳尼 $emit 全都不行了 value也无法双向绑定了 onchang的event也是个undefind 什么情况
是我版本不对吗

**Comment by JakeLaoyu** [comment]
代码截图发一下

**Comment by tanwenchao** [comment]
<van-uploader :max-count="1" @after-read="afterRead"&gt;
      <!-- <div class="img"&gt;
        <img src="/static/auth/zhengmian.png" alt="" style="width: 121px; height: 81px"&gt;
      </div&gt;
      <div class="text"&gt;上传身份证正面</div&gt; --&gt;
    </van-uploader&gt;




  编译后 bindafter-read   兄弟少了个冒号啊

**Comment by JakeLaoyu** [comment]
小程序官方文档允许没有冒号
就算是有问题，也是mpvue编译的问题
