### ISSUE TITLE
submit-bar在示例中是圆形button，实际无法改成圆形button

### ISSUE THREAD

**Issue by Accusr** [youzan/vant-weapp#2667]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater?repo=VantWeapp

**Comment by JakeLaoyu** [comment]
vant-weapp 目前默认还不是 圆形按钮，可以使用 button-class 覆盖样式
