### ISSUE TITLE
Stepper 建议增加一个延迟change功能

### ISSUE THREAD

**Issue by lyq027** [youzan/vant-weapp#2668]
Stepper在购物车数量变化时，我们是走数据库的
如果手快，连点，会多次请求
希望有做一个连点延迟change功能，减少网络请求次数

**Comment by JakeLaoyu** [comment]
这个需要你们在代码里自己做 防抖，不适合放在基础库中

**Comment by PeacefulGemini** [comment]
自己做了防抖后，长按+/-按钮直到变化到最大（小）值后等1s松手，overLimit绑定的函数会一直触发，不会停止，这个问题有遇到吗？
