### ISSUE TITLE
[Bug Report] 建议将基础组件也放到开发指南里面，这样方便开发者快速使用，如van-info

### ISSUE THREAD

**Issue by kevincwj2008** [youzan/vant-weapp#2671]
### 设备
所有设备

### VantWeapp 版本
1.0.3

### 基础库版本
2.10.0

### 请提供核心代码片段链接
无代码

### 描述问题
建议将基础组件也放到开发指南里面，这样方便开发者快速使用，如van-info，再使用的发现van-icon里使用了van-info，但是没有任何文档有关于此组件的介绍及使用。

**Comment by JakeLaoyu** [comment]
没暴露的 组件 只是作为通用的辅助组件，不建议使用

**Comment by kevincwj2008** [comment]
> 没暴露的 组件 只是作为通用的辅助组件，不建议使用

如果不建议使用是否可以考虑添加新徽章组件来弥补这块组件缺失的问题？

**Comment by JakeLaoyu** [comment]
可以考虑，不过目前没有这个计划
