### ISSUE TITLE
官网无法访问了？

### ISSUE THREAD

**Issue by onlyoneyanyan** [youzan/vant-weapp#2672]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater?repo=VantWeapp

**Comment by chenjiahan** [comment]
可能是国内访问 Github 网络波动，可以访问我们的 gitee 镜像:

http://vant-contrib.gitee.io/vant-weapp

**Comment by onlyoneyanyan** [comment]
更新版本问题？ 我使用 npm 安装 ，怎么可以升级到 最新的1.0 版本？

**Comment by JakeLaoyu** [comment]
```sh
npm i @vant/weapp@1.0.3 -S --production
```

大版本会有不兼容更新，留意更新日志

**Comment by rex-zsd** [comment]
#2678
