### ISSUE TITLE
[Bug Report] 组件里自带的字体图标

### ISSUE THREAD

**Issue by WEBhslv** [youzan/vant-weapp#2673]
### 设备
微信开发者工具

### VantWeapp 版本
1.0.3

### 基础库版本
2.10.0

### 如果是 UI 问题，截图链接（多图回车分隔）

![截图](https://i.loli.net/2020/01/13/ETRwzU8Ylmun2kX.png)

![截图](https://i.loli.net/2020/01/13/y9futSH12wo7pC6.png)

### 请提供核心代码片段链接
https://i.loli.net/2020/01/13/h34eyLQqp9JNvts.png

### 描述问题
VM302:1 Failed to load font https://img.yzcdn.cn/vant/vant-icon-d3825a.woff2
net::ERR_CACHE_MISS

**Comment by rex-zsd** [comment]
看下[微信文档](https://developers.weixin.qq.com/miniprogram/dev/api/ui/font/wx.loadFontFace.html)，工具里提示 Faild to load font可以忽略。
