### ISSUE TITLE
[Bug Report] van-tabs耗时操作获取数据时sticky无效

### ISSUE THREAD

**Issue by zljt1314** [youzan/vant-weapp#2674]
### 设备
所有

### VantWeapp 版本
1.0.2

### 基础库版本
2.8.1

### 请提供核心代码片段链接
https://git.weixin.qq.com/zljt1314/lurenjia/blob/master/miniprogram/pages/test

### 描述问题
van-tabs耗时操作获取数据时sticky无效

**Comment by jamesyu89** [comment]
我试过，没有调用api请求sticky属性一样无效

**Comment by maplehsu** [comment]
没有人遇到这问题吗？管理员
