### ISSUE TITLE
[Bug Report] 北京地区  官网打不开 

### ISSUE THREAD

**Issue by xuzhaopengsyl** [youzan/vant-weapp#2676]
### 设备
PC  手机  无线和4G网络全打不开  多人测试

### VantWeapp 版本
1.0.3

### 基础库版本
1.03

### 请提供核心代码片段链接
https://youzan.github.io/vant-weapp/#/quickstart

### 描述问题
上周六有人反馈打不开了 今天多人在北京不同地点不同设备  不同网络都打不开官网

**Comment by chenjiahan** [comment]
参见 https://github.com/youzan/vant-weapp/issues/2672
