### ISSUE TITLE
vant weapp 的 icon 为啥能用远程的字体图标啊？

### ISSUE THREAD

**Issue by zopi4455** [youzan/vant-weapp#2679]
设备
所有

VantWeapp 版本
1.0.0

基础库版本
所有

请提供核心代码片段链接
https://youzan.github.io/vant-weapp/#/icon

描述问题
vant weapp 的 icon 为啥能用远程的字体图标啊？
url用的是 url(https://img.yzcdn.cn/vant/vant-icon-0bc654.woff2)
@font-face {
  font-weight: 400;
  font-family: vant-icon;
  font-style: normal;
  font-display: auto;
  src: url(https://img.yzcdn.cn/vant/vant-icon-0bc654.woff2) format("woff2"), url(https://img.yzcdn.cn/vant/vant-icon-0bc654.woff) format("woff"), url(https://img.yzcdn.cn/vant/vant-icon-0bc654.ttf) format("truetype")
}

**Comment by zopi4455** [comment]
我用的是自己的服务器（https://erp.avic-mr.com/avic/avicmobileapp/fonts/font-awesome/webfonts/fa-duotone-900.woff2），开发工具正常，但是真机调试不显示

**Comment by zopi4455** [comment]
我用的是自己的服务器（https://erp.avic-mr.com/avic/avicmobileapp/...），开发工具正常，但是真机调试不显示

**Comment by gromit1sm** [comment]
你域名加入信任域名没有

**Comment by rex-zsd** [comment]
这个看下微信的文档吧~

**Comment by zopi4455** [comment]
> 你域名加入信任域名没有

真机调试是可以跳过域名的。不过我还是加入了 服务器域名 和 业务域名

**Comment by zopi4455** [comment]
> 你域名加入信任域名没有


> 你域名加入信任域名没有

真机调试是可以跳过域名的。不过我还是加入了 服务器域名 和 业务域名。
还是不行，开发者工具正常显示，真机调试和体验版都不行，不知道为啥。
哥们有好的建议吗？

**Comment by zopi4455** [comment]
> 这个看下微信的文档吧~

请问，哪里有这种介绍啊？
