### ISSUE TITLE
[Bug Report] circle组件size属性未加入rpx支持

### ISSUE THREAD

**Issue by zkl2333** [youzan/vant-weapp#2682]
### 设备
dev

### VantWeapp 版本
1.0.3

### 基础库版本
2.9.4

### 如果是 UI 问题，截图链接（多图回车分隔）

![截图](https://i.loli.net/2020/01/15/aJNQE64VXTbUC2D.png)

### 请提供核心代码片段链接
https://gist.github.com/zkl2333/f7be90e33db1f3bb1f001059af6760bf

### 描述问题
看文档说支持字符串，实际使用传入"40rpx"报错，查源码发现只支持number属性。

**Comment by rex-zsd** [comment]
circle组件使用了canvas相关的API，只支持数字类型的参数，所以`rpx`应该是支持不了了，后续会更新文档。
