### ISSUE TITLE
[Bug Report] 文档里又说cell支持default slot,我看了下源码，确定没有

### ISSUE THREAD

**Issue by wayhe-chenchao** [youzan/vant-weapp#2684]
### 设备
所有

### VantWeapp 版本
1.0.3

### 基础库版本
2.9.4

### 如果是 UI 问题，截图链接（多图回车分隔）

![截图](https://sm.ms/image/d9Ulf2usvaeQ5gL)

![截图](https://sm.ms/image/BTR7jnvpYXidSQ3)

### 请提供核心代码片段链接
https://github.com/youzan/vant-weapp/blob/dev/lib/cell/index.wxml

### 描述问题
对着文档使用cell组件，想要实现自定义value,于是使用slot=default，发现不生效，其余slot都没问题，怎么弄都不对，于是想看源码，发现没实现这个slot

**Comment by JakeLaoyu** [comment]
把你调用的代码发一下

**Comment by frei-x** [comment]
看错了 , 不用谢slot属性 ,直接插进去
```
<van-cell
      size="large"
      title="请添加免单节商品或优惠券"
      bind:tap="openPicker"
      data-name="b_age"
      is-link
      center="{{true}}"
    >
      <view>哈哈</view>
</van-cell>
````

**Comment by wayhe-chenchao** [comment]
我自己改了源码，已经可以了


chao.chen@wayhe.com
 
发件人： Jake
发送时间： 2020-01-15 16:22
收件人： youzan/vant-weapp
抄送： wayhe-chenchao; Author
主题： Re: [youzan/vant-weapp] [Bug Report] 文档里又说cell支持default slot,我看了下源码，确定没有 (#2684)
把你调用的代码发一下
