### ISSUE TITLE
vant 部考虑出react  的移动端版本吗

### ISSUE THREAD

**Issue by miyaliunian** [youzan/vant-weapp#2690]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater?repo=VantWeapp

**Comment by Lindysen** [comment]
这里是 vant-weapp

**Comment by Lindysen** [comment]
这里是 vant-weapp

**Comment by miyaliunian** [comment]
我的意思是vant 不考虑出react版本的移动端UI组件库吗？
我相信有很多人 都有我这样的需求

**Comment by chenjiahan** [comment]
暂时没有计划噢
