### ISSUE TITLE
DatetimePicker 时间选择 使用异常

### ISSUE THREAD

**Issue by WEBhslv** [youzan/vant-weapp#2692]
设备
IOS

VantWeapp 版本
1.0.3

基础库版本
2.10.0
DatetimePicker 时间选择 使用异常 
滑动选择时间，没有滑动后，他自己会上下跳动

**Comment by Lindysen** [comment]
> 设备
> IOS
> 
> VantWeapp 版本
> 1.0.3
> 
> 基础库版本
> 2.10.0
> DatetimePicker 时间选择 使用异常
> 滑动选择时间，没有滑动后，他自己会上下跳动

无法复现，麻烦提供一下核心代码

**Comment by WEBhslv** [comment]
> > 设备
> > IOS
> > VantWeapp 版本
> > 1.0.3
> > 基础库版本
> > 2.10.0
> > DatetimePicker 时间选择 使用异常
> > 滑动选择时间，没有滑动后，他自己会上下跳动
> 
> 无法复现，麻烦提供一下核心代码

<van-datetime-picker
  type="date"
  value="{{ currentDate }}"
  bind:input="onInput"
  min-date="{{ minDate }}"
  formatter="{{ formatter }}"
/>
Page({
  data: {
    currentDate: new Date().getTime(),
    minDate: new Date().getTime(),
    formatter(type, value) {
      if (type === 'year') {
        return `${value}年`;
      } else if (type === 'month') {
        return `${value}月`;
      }
      return value;
    }
  },

  onInput(event) {
    this.setData({
      currentDate: event.detail
    });
  }
});
就是官网的源代码，难道我是直接下载文件，把dist文件复制到项目里的出现了问题？
