### ISSUE TITLE
[Bug Report] 引入"van-steps"会导致无法预览

### ISSUE THREAD

**Issue by ZH-Hf** [youzan/vant-weapp#2693]
### 设备
小米mix3

### VantWeapp 版本
1.0.3

### 基础库版本
2.10.0

### 请提供核心代码片段链接
https://github.com/youzan/vant-weapp/blob/dev/dist/steps/index.js

### 描述问题
在app.json中 加入  "van-steps": "path/to/@vant/weapp/dist/steps/index",则会导致手机无法预览和调试,但在开发工具中没有问题

**Comment by JakeLaoyu** [comment]
请提供报错信息

**Comment by rex-zsd** [comment]
引入路径的问题吧` "van-steps": "path/to/@vant/weapp/dist/steps/index"`这里配置的应该是实际的路径。

**Comment by ZH-Hf** [comment]
不是路径问题,在开发工具中没问题的,但是在使用手机预览时会一直卡在加载界面,调试时提示 "cmdId 1005, errcode 1"

**Comment by JakeLaoyu** [comment]
@ZH-Hf  可能和 组件库无关https://developers.weixin.qq.com/community/develop/doc/000cc45e5c83b08968970020b56000?highLine=cmdid%25201005
