### ISSUE TITLE
[Bug Report] 请问如何优雅的修改grid-item内容部分的样式

### ISSUE THREAD

**Issue by lrd7512369** [youzan/vant-weapp#2695]
### 设备
MacBook pro

### VantWeapp 版本
1.0.1

### 基础库版本
2.9.4

### 请提供核心代码片段链接
https://github.com/youzan/vant-weapp/blob/dev/packages/grid-item/index.less

### 描述问题
请问如何优雅的修改grid-item内容部分的样式，例如去掉padding，设置背景颜色为透明

**Comment by JakeLaoyu** [comment]
参考 https://youzan.github.io/vant-weapp/#/custom-style
