### ISSUE TITLE
[Bug Report] van-button添加disabled还可以点击

### ISSUE THREAD

**Issue by BeYourself666** [youzan/vant-weapp#2696]
### 设备
华为荣耀9

### VantWeapp 版本
1.0.3

### 基础库版本
2.9.4

### 请提供核心代码片段链接
https://github.com/youzan/vant-weapp/blob/dev/packages/button/index.wxml

### 描述问题
van-button添加disabled属性后样式变灰了，但还可以点击。

**Comment by JakeLaoyu** [comment]
请提供你的代码
