### ISSUE TITLE
[Bug Report] VanButton属性Size无效问题

### ISSUE THREAD

**Issue by jcute** [youzan/vant-weapp#2697]
### 设备
开发环境

### VantWeapp 版本
1.0.3

### 基础库版本
2.10.0

### 如果是 UI 问题，截图链接（多图回车分隔）

[https://i.loli.net/2020/01/17/eolXYyA9ZkpxVnb.png](url)
[https://i.loli.net/2020/01/17/nKq3Bj9LskRcOvT.png](url)

### 请提供核心代码片段链接
https://sm.ms/image/vrES3mqJ7aB2Rid

### 描述问题
van-button size属性 设置mini 和 small 除了文字有变化 . 按钮本身大小没有任何变化

**Comment by flxa888** [comment]
去掉app.json中的style:"v2"的设置

**Comment by coolhao** [comment]
> ### 设备
> 开发环境
> 
> ### VantWeapp 版本
> 1.0.3
> 
> ### 基础库版本
> 2.10.0
> 
> ### 如果是 UI 问题，截图链接（多图回车分隔）
> [https://i.loli.net/2020/01/17/eolXYyA9ZkpxVnb.png](url)
> [https://i.loli.net/2020/01/17/nKq3Bj9LskRcOvT.png](url)
> 
> ### 请提供核心代码片段链接
> https://sm.ms/image/vrES3mqJ7aB2Rid
> 
> ### 描述问题
> van-button size属性 设置mini 和 small 除了文字有变化 . 按钮本身大小没有任何变化
开发环境：
微信开发工具 stable v1.02.1911180
"@vant/weapp": "^1.0.3"

![TIM截图20200118214714](https://user-images.githubusercontent.com/8363780/72664727-1d2a9480-3a3c-11ea-99a2-151c908a131f.png)

**Comment by gepengscu** [comment]
小程序默认样式覆盖导致的。加个包裹可以解决

```
<!--pages/demo/demo.wxml-->
<view class="floating-layer">
  <view class="round-button">
    <van-button type="info" round icon="plus" size="normal" />
  </view>
</view>
```

```
/* demo.wxss */

.floating-layer {
  position: absolute;
  z-index: 1000;
  top: 0px;
  left: 0px;
  width: 100%;
  height: 100%;
}

.round-button {
  background-color: transparent;
  border: none;
}

.round-button .van-button { 
  position: fixed;
  right: 30rpx;
  bottom: 30rpx;
  width: 84rpx;
  height: 84rpx;  
  /* opacity: .8; */
}
```
