### ISSUE TITLE
[Feature Request] 希望能在field中加入click事件

### ISSUE THREAD

**Issue by jackytse** [youzan/vant-weapp#2699]
### 这个功能解决了什么问题
https://youzan.github.io/vant-weapp/#/picker picker的文档中有一个搭配弹出层使用的案例，但是我翻看了sample 源码，并没有找到这个案例，要实现这个案例的话，需要field 组件增加click 事件，或者是用cell 来实现（需要改一些样式，比较繁琐），个人建议是用第一个方案

### 建议的API是什么样的
picker 组件增加 bind:click 事件

**Comment by rex-zsd** [comment]
这个只需要开启`readonly`然后监听原生的`bindtap`时间就可以了，不需要新增api。
