### ISSUE TITLE
vant icon问题

### ISSUE THREAD

**Issue by gnr2009** [youzan/vant-weapp#2700]
使用vant icon提示: VM17:1 Failed to load font https://img.yzcdn.cn/vant/vant-icon-0bc654.woff2
net::ERR_CACHE_MISS
回来又把vant组件重置了一遍,用npm编译要有这样的问题,看了源码,也没什么问题,接受不了爆红,怎么解决啊

**Comment by rex-zsd** [comment]
这个报错可以无视，具体查看[微信文档](https://developers.weixin.qq.com/miniprogram/dev/api/ui/font/wx.loadFontFace.html)
