### ISSUE TITLE
微信 基础库 2.10.1 版本 button按钮block不起作用

### ISSUE THREAD

**Issue by accardo** [youzan/vant-weapp#2701]
测试 微信 基础库2.8 版本以下都好用

<van-button type="danger" block>按钮</van-button>
width: 100%; 的时候不起作用
width: 100% !important;  才可以

"usingComponents": {
  "van-goods-action": "path/to/@vant/weapp/dist/goods-action/index",
  "van-goods-action-icon": "path/to/@vant/weapp/dist/goods-action-icon/index",
  "van-goods-action-button": "path/to/@vant/weapp/dist/goods-action-button/index"
}

同样有这个问题

![image](https://user-images.githubusercontent.com/12389303/72714446-ae6b4980-3ba9-11ea-8f9a-54884443cc15.png)

**Comment by Mrzy** [comment]
+1

**Comment by rex-zsd** [comment]
去除`"style": "v2"`，讨论见[微信开发者社区](https://developers.weixin.qq.com/community/develop/doc/000c4a39ef801063fa09ca7cd51800?_at=1565112606070)
