### ISSUE TITLE
微信小程序中vant-weapp如何声明ellipsis为false？

### ISSUE THREAD

**Issue by Leslie-Wong-H** [youzan/vant-weapp#2706]
## 设备
Android
## VantWeapp 版本
1.0.0-beta.4

官方文档中tabs props有说明可以声明ellipsis为false来显示被省略掉的标签标题。然而，ellipsis属性的默认值为true，无法像默认值为false其他布尔值属性那样在"<tabs " 后面加个属性名就行，
自己试了下面两种声明方式，都无效，请指明正确方法。
```
<van-tabs sticky animated swipeable :ellipsis="false" border="false">
```
```
 <van-tabs sticky animated swipeable ellipsis="false" border="false">
```
## 结果：
![image](https://user-images.githubusercontent.com/27696701/72808638-ee5b2b00-3c94-11ea-9d49-3e5b2a64c17e.png)

**Comment by Lindysen** [comment]
ellipsis="{{ false }}"

**Comment by wanghanwanghan** [comment]
解决了吗
