### ISSUE TITLE
[Bug Report] uploader组件disabled设置true后无法隐藏上传按钮

### ISSUE THREAD

**Issue by hihuangwei** [youzan/vant-weapp#2716]
### 设备
安卓、苹果、开发 工具都不行

### VantWeapp 版本
1.0.4

### 基础库版本
2.10.1

### 请提供核心代码片段链接
https://youzan.github.io/vant-weapp

### 描述问题
`<van-uploader file-list="{{ fileList }}" disabled="{{ true }}" />`

**Comment by Lindysen** [comment]
添加一个禁用置灰样式更合理
