### ISSUE TITLE
[Bug Report] 【Enhancement】slider值范围较大时滑起来摩擦力很大

### ISSUE THREAD

**Issue by CACppuccino** [youzan/vant-weapp#2717]
### 设备
All

### VantWeapp 版本
1.0.4

### 基础库版本
2.8.3

### 请提供核心代码片段链接
https://github.com/youzan/vant-weapp/blob/dev/dist/slider/index.js

### 描述问题
在设置slider值为较大值时，如600，slider滑起来会非常难滑

**Comment by 1sm23** [comment]
设置`slider max`时值较小时又太容易滑了

**Comment by zkl2333** [comment]
我是设置0-100然后自己映射数据

**Comment by HanksHu** [comment]
也遇到了这个问题，如果和0~100映射的话，写起来也怪怪的

**Comment by Yvan7123** [comment]
同遇到这个问题，我这边写的时时间条、不太好转化为0-100

**Comment by TheSunset** [comment]
这个问题 可以到slider组件的js文件里找到这个方法
`onTouchMove: function (event) {
            var _this = this;
            if (this.data.disabled)
                return;
            if (this.dragStatus === 'start') {
                this.$emit('drag-start');
            }
            this.touchMove(event);
            this.dragStatus = 'draging';
            this.getRect('.van-slider').then(function (rect) {

                var diff = (_this.deltaX / rect.width) * 100;

                _this.newValue = _this.startValue + diff;
                _this.updateValue(_this.newValue, false, true);
            });
        },`
把上面的diff 后面乘的100 换成 _this.data.max 即可
