### ISSUE TITLE
[Bug Report] 微信小程序构建npm后目录变化导致的import问题

### ISSUE THREAD

**Issue by HissYu** [youzan/vant-weapp#2718]
### 设备
\*

### VantWeapp 版本
1.0.4

### 基础库版本
\*

### 请提供核心代码片段链接
https://gist.github.com/HissYu/96bc425b3f789a520febf3aa5f812f81

### 描述问题
在微信小程序中构建后的模块文件夹内不含dist一级，使用 给出/vscode自动补全 的路径会导致小程序本身报错，手动删除路径中的dist又会导致tsc编译错误

**Comment by HissYu** [comment]
又试了一下实际上没有dist也不行，虽然不报错，但是界面加载不出来
只能定位到miniprogram_npm目录下的toast文件么

**Comment by rex-zsd** [comment]
这个问题似乎很难解决，typecript依赖node_modules里的内容，而小程序的npm依赖的是miniprogram_npm…………

**Comment by rex-zsd** [comment]
```
{
  "basrUrl": '.',
  "paths": {
      "@vant/weapp/*": ["./node_modules/@vant/weapp/dist/*"]
  },
  ...
```

从npm构建的角度很难解决，可以在tsconfig中将`@vant/weapp`强行指向`@vant/weapp/dist`目录。

后续会把这部分添加到quickstart文档中
