### ISSUE TITLE
Tab标签页 红色提示线 颜色如何修改

### ISSUE THREAD

**Issue by VampireCrazy** [youzan/vant-weapp#2723]
![图片](https://user-images.githubusercontent.com/27774863/73917704-e89f4f80-48fa-11ea-83cb-af9b6b62ffce.png)

**Comment by rex-zsd** [comment]
可以看下[样式覆盖的文档](https://youzan.github.io/vant-weapp/#/custom-style)

**Comment by rex-zsd** [comment]
通过解除样式隔离，覆盖`.van-tabs__line`的`background-color`
或者使用css变量，修改`--tabs-bottom-bar-color`的定义
