### ISSUE TITLE
van-field password属性问题

### ISSUE THREAD

**Issue by VampireCrazy** [youzan/vant-weapp#2725]
van-field  在 password 属性情况下 
输入密码内容 然后使用“clearable属性按钮”删除密码为空 
bind:blur 方法获取到的密码内容为删除前的内容而不是空值
（默认类型下的话 可以正常获取到空值）

**Comment by rex-zsd** [comment]
van-field对他们的处理都是一样的，看起来似乎是小程序的问题，我们看看是否有绕过的方法。

**Comment by rex-zsd** [comment]
vant这边应该没办法了，blur时间会原样抛出原生input的`event.detail`。
可以试试对`password`类型的记录change事件时获取到的值为准。
