### ISSUE TITLE
icon  组件不显示图标右上角小红点

### ISSUE THREAD

**Issue by pmingjie** [youzan/vant-weapp#2727]
版本：1.0.4
调试基础库：2.10.1
代码： `<van-icon name="chat" dot />`

问题：并无法像文档示例那样显示小红点，必须填入 info 字段内容才可以。

**Comment by rex-zsd** [comment]
demo小程序里是ok的，设置`dot`属性即可，是引入的问题？

**Comment by pmingjie** [comment]
我复制的是 dist 里的，而且复制最近几版的会出现 icon 变小的问题。排查后发现最近几版的icon 的  font-size 是空的
