### ISSUE TITLE
在两个tabs里面，第二个tab使用submit bar，显示却在第一个tab里

### ISSUE THREAD

**Issue by Jing-Li** [youzan/vant-weapp#2731]
设备
iphone 6s

VantWeapp 版本
1.0.5

如题， 根据 官网https://youzan.github.io/vant-weapp/#/tab 弄了两个tab 第二个tab 放的submit bar 但是却显示在第一个tab里

**Comment by Jing-Li** [comment]
确定了 是加了animated 属性才会这样

**Comment by rex-zsd** [comment]
嗯 这种场景可以去掉`animated`属性，transform会对fixed造成影响的
