### ISSUE TITLE
我想知道我想用微信开发者工具看一下你们给的示例工程

### ISSUE THREAD

**Issue by wangzhehehu** [youzan/vant-weapp#2732]
目前是安装完成导入后，报错，无法找到组件

Component is not found in path "@vant/weapp/dist/image/index" (using by "pages/goods/index");onAppRoute
Error: Component is not found in path "@vant/weapp/dist/image/index" (using by "pages/goods/index")
    at G (http://127.0.0.1:23626/appservice/__dev__/WAService.js:2:1535999)

具体有什么步骤吗

**Comment by rex-zsd** [comment]
参考快速上手的步骤一步步来哈

**Comment by jiejia** [comment]
一步步来还是错的，但是把“@vant/weapp/dist/image/index” 改成 @vant/weapp/image 就对了，
可以解释下吗

**Comment by luanweijie** [comment]
小程序应该需要构建才可以，所以是不是小程序只认识miniprogram_npm目录，node_modules目录是不认识的，所以dist目录小程序也找不到？
我说的对么
