### ISSUE TITLE
按钮样式在"libVersion": "2.10.1"下显示有问题

### ISSUE THREAD

**Issue by neozhu** [youzan/vant-weapp#2735]
按钮的大小宽度变成100%的样式，在panel控件的foot 中的大小也出了问题，只能在2.3.0下是能正常显示的。不知道要怎么修改样式表文件，还是请作者能看一下问题。

**Comment by neozhu** [comment]
我测试了一下最高支持到2.7.7 是正常的，但现在切换到以上的版本按钮样式都出问题了

**Comment by rex-zsd** [comment]
看一下快速上手的文档，去掉`"style": "v2"`

**Comment by neozhu** [comment]
谢谢指点
