### ISSUE TITLE
Bug  DropdownMenu滑动导致底层数据滑动

### ISSUE THREAD

**Issue by LiLingS** [youzan/vant-weapp#2737]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater?repo=VantWeapp

一个顶部是DropdownMenu，其他事for循环，如果点击DropdownMenu，弹出框，滑动menu内容部分，会导致底层for循环的时候也一起滑动

**Comment by rex-zsd** [comment]
遮罩层不会禁止底层的页面滚动的，如果介意的话，可以把底层的列表放在小程序的`scroll-view`组件里试试哈。
