### ISSUE TITLE
[Bug Report] wx.nextTick报错

### ISSUE THREAD

**Issue by MrQiYin** [youzan/vant-weapp#2738]
### 设备
模拟器

### VantWeapp 版本
1.0.5

### 基础库版本
1.9.91

### 如果是 UI 问题，截图链接（多图回车分隔）

![截图](https://i.loli.net/2020/02/10/CoiT7GSOcnbpYQP.png)

### 请提供核心代码片段链接
https://gist.github.com/MrQiYin/6cb1539fd84585fcd40df86b5d0c34aa

### 描述问题
wx.nextTick最低要求版本是2.2.3，使用1.9.91最低版本调试，报错导致无法得到预期效果，如van-field的清空输入框，1.9.91就无法清空。查找项目，还有很多地方均有使用wx.nextTick。

**Comment by rex-zsd** [comment]
1.0的最低版本要求已经升到2.3啦，如果有1.9.9的兼容要求的话可以使用0.x版本哦

**Comment by MrQiYin** [comment]
> 1.0的最低版本要求已经升到2.3啦，如果有1.9.9的兼容要求的话可以使用0.x版本哦

那能否在GitHub上的基础库版本那儿更新一下。。比如0.x=>1.9.90，1.0=>2.3，目前只写了1.9.9，但是我却更新到了1.0.5。。有点儿尴尬。。
