### ISSUE TITLE
时间选择器能不能增加一个year的类型呢

### ISSUE THREAD

**Issue by 741075253** [youzan/vant-weapp#2740]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater?repo=VantWeapp

**Comment by rex-zsd** [comment]
如果单纯只想选择年份的话，数据比较简单的，不如直接用picker组件吧。

**Comment by 741075253** [comment]
不是，选择年只是需求之一，现在所拥有的类型都会覆盖；使用picker实现应该会复杂一点

**Comment by 741075253** [comment]
> 
> 
> 如果单纯只想选择年份的话，数据比较简单的，不如直接用picker组件吧。

不是，选择年只是需求之一，现在所拥有的类型都会覆盖；使用picker实现应该会复杂一点

**Comment by rex-zsd** [comment]
额，datetimepicker近期应该不会增加新的type。
用picker写的话也还好吧，自备一下选项数据就可以了
