### ISSUE TITLE
[Bug Report] Popup 弹出层显示异常

### ISSUE THREAD

**Issue by lacker159** [youzan/vant-weapp#2745]
### 设备
Android WeChat 7.0.10

### VantWeapp 版本
1.0.5

### 基础库版本
2.10.1

### 如果是 UI 问题，截图链接（多图回车分隔）

![截图](https://s2.ax1x.com/2020/02/11/179Aht.jpg)

![截图](https://s2.ax1x.com/2020/02/11/179ung.jpg)

![截图](https://s2.ax1x.com/2020/02/11/179KBQ.jpg)

### 请提供核心代码片段链接
https://github.com/lacker159/20200211/tree/master

### 描述问题
Popup 弹出层下面有 van-field 标签且type属性是"textarea"时，会出现异常情况。比如，field 中的文字会穿透Popup图层显示、field可以获取焦点。

**Comment by rex-zsd** [comment]
看下[文档说明](https://youzan.github.io/vant-weapp/#/field#zhen-ji-shang-placeholder-wei-shi-me-hui-gai-guo-popup-deng-qi-ta-zu-jian)哈

**Comment by leoshuaige** [comment]
我也遇到这个问题了，不知道怎么解决，楼上的说看文档，我仔细的看了好几遍，也没有看出说明名堂，第一次接触微信小程序，可能是我太菜的原因吧。有谁知道的，麻烦发个邮件1010503593@qq.com 万分感谢

**Comment by lacker159** [comment]
> 我也遇到这个问题了，不知道怎么解决，楼上的说看文档，我仔细的看了好几遍，也没有看出什么名堂，第一次接触微信小程序，可能是我太菜的原因吧。有谁知道的，麻烦发个邮件[1010503593@qq.com](mailto:1010503593@qq.com) 万分感谢

![image](https://user-images.githubusercontent.com/43429655/77553680-10b93100-6ef0-11ea-908b-60a5ca909d17.png)

**Comment by lacker159** [comment]
> 我也遇到这个问题了，不知道怎么解决，楼上的说看文档，我仔细的看了好几遍，也没有看出什么名堂，第一次接触微信小程序，可能是我太菜的原因吧。有谁知道的，麻烦发个邮件[1010503593@qq.com](mailto:1010503593@qq.com) 万分感谢

![image](https://user-images.githubusercontent.com/43429655/77553864-4eb65500-6ef0-11ea-94e6-4018d8bc84ad.png)

**Comment by lacker159** [comment]
> 我也遇到这个问题了，不知道怎么解决，楼上的说看文档，我仔细的看了好几遍，也没有看出什么名堂，第一次接触微信小程序，可能是我太菜的原因吧。有谁知道的，麻烦发个邮件[1010503593@qq.com](mailto:1010503593@qq.com) 万分感谢

这里有一个补偿方法，你可以试试。
链接：
http://www.imooc.com/article/details/id/286400
上面两幅图的链接分别是：
https://youzan.github.io/vant-weapp/#/field
https://developers.weixin.qq.com/miniprogram/dev/component/native-component.html

**Comment by wyl530197181** [comment]
解决了吗   现在感觉这个问题都没人解决
