### ISSUE TITLE
宫格间距大小设置

### ISSUE THREAD

**Issue by yrz0816** [youzan/vant-weapp#2747]
gutter 设置为0后 间距还感觉大  还有办法缩小吗

**Comment by yrz0816** [comment]
![1581478956(1)](https://user-images.githubusercontent.com/15374950/74301064-c9863f00-4d8c-11ea-958e-986a0263a5c9.jpg)

**Comment by rex-zsd** [comment]
gutter设为0就没有间距了呀，为什么还感觉大？

**Comment by rex-zsd** [comment]
如果指的是grid-item的内边距，可以自定义`--grid-item-content-padding`css变量修改
