### ISSUE TITLE
radio示例代码有误，icon-disabled应为label-disabled

### ISSUE THREAD

**Issue by andurils** [youzan/vant-weapp#2751]
代码示例有误
禁用文本点击章节处属性设置有误，
通过设置**label-disabled**属性可以禁用单选框文本点击
<van-radio-group value="{{ radio }}" bind:change="onChange">
  <van-radio name="1" **icon-disabled**>单选框 1</van-radio>
  <van-radio name="2" **icon-disabled**>单选框 2</van-radio>
</van-radio-group>
https://youzan.github.io/vant-weapp/#/radio

**Comment by rex-zsd** [comment]
感谢反馈
