### ISSUE TITLE
vant-circle组件在小程序中直接使用，当value为0 时，显示与demo样式不一致

### ISSUE THREAD

**Issue by alia-clj** [youzan/vant-weapp#2759]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater?repo=VantWeapp

**Comment by rex-zsd** [comment]
这个是小程序和h5的实现api不一致导致的，暂时不会不会与vant完全一致哈。
