### ISSUE TITLE
card组件  使用custom-class设置背景色无效

### ISSUE THREAD

**Issue by ppasj** [youzan/vant-weapp#2761]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater?repo=VantWeapp

**Comment by rex-zsd** [comment]
issue格式不规范
样式覆盖的用法请查看样式覆盖部分的文档哈
https://youzan.github.io/vant-weapp/#/custom-style
