### ISSUE TITLE
[Feature Request] 希望Notify可以设置top，以便在使用自定义导航栏时可以保持和使用默认导航栏时一致的用户体验

### ISSUE THREAD

**Issue by lopaz** [youzan/vant-weapp#2764]
### 这个功能解决了什么问题
使用默认导航栏时，Notify是从导航栏下方弹出的；但是当使用自定义导航栏时，Notify则是从手机显示区域的最顶端弹出的，使用safeAreaInsetTop也只是多空出了一个状态栏的高度，仍无法获得和使用默认导航栏一致的体验

### 建议的API是什么样的
Notify添加一个top属性，当使用自定义导航栏时，开发者自己设置top的值。

**Comment by rex-zsd** [comment]
不需要哈，实现你的需要只需要控制好Notify的`zIndex`低于自定义导航栏的`z-index`就可以了。

**Comment by lopaz** [comment]
@rex-zsd 我试了下，如果自定义导航栏的z-index比Notify的大，结果就是Notify被遮住，完全不可见。
Notify始终是top: 0，这意味着改变z-index并不能改变弹出的位置（屏幕顶端）。

**Comment by lopaz** [comment]
@rex-zsd 麻烦重新打开下这个issue，zIndex只能解决notify和自定义导航栏的层级问题，只有支持设置top才能实现notify从自定义导航栏底部弹出的效果（使用safeAreaInsetTop实现不了）。
