### ISSUE TITLE
vant weapp的calendar日历组件的问题

### ISSUE THREAD

**Issue by zbebe** [youzan/vant-weapp#2765]
vant weapp的开发者你好：我用笔记本电脑访问vant weapp的展示库和用ipad访问相同的vant weapp的展示库，同一个链接，同一个页面，怎么显示的展示组件有很多不同呢？比如说，在ipad上能够显示calendar日历组件，但是在笔记本win10OS上怎么就没有这个日组件呢？我还是很需要日历这个组件的。请给予指点，谢谢

**Comment by rex-zsd** [comment]
vant weapp暂时还没有calendar组件哈，目前仅vant有calendar组件，vant weapp会在后续的版本中跟进。
