### ISSUE TITLE
[Bug Report] tabs结合popup使用BUG

### ISSUE THREAD

**Issue by chaseway** [youzan/vant-weapp#2767]
### 设备
手机

### VantWeapp 版本
1.0.5

### 基础库版本
2.10.1

### 请提供核心代码片段链接
https://developers.weixin.qq.com/s/GN5EabmD72fY

### 描述问题
第一次显示时，tabs的默认标签的底部条不显示

**Comment by rex-zsd** [comment]
可以手动在tabs上加个`wx:if`控制一下，在弹窗出现时才显示tabs组件
因为tabs组件会在初始化时计算底部条样式，弹窗内的tabs初始化时不会渲染，导致了这个问题。

**Comment by chaseway** [comment]
> 可以手动在tabs上加个`wx:if`控制一下，在弹窗出现时才显示tabs组件
> 因为tabs组件会在初始化时计算底部条样式，弹窗内的tabs初始化时不会渲染，导致了这个问题。

试了下wx:if还是不行
