### ISSUE TITLE
[Bug Report] van-index-bar点击索引栏，内容被遮挡

### ISSUE THREAD

**Issue by XiaoLeaf** [youzan/vant-weapp#2768]
### 设备
iPhone6

### VantWeapp 版本
1.0.5

### 基础库版本
2.10.1

### 如果是 UI 问题，截图链接（多图回车分隔）

![截图](https://sm.ms/image/HyeSs9w4c3k6bo2)

### 请提供核心代码片段链接
https://github.com/XiaoLeaf/van-issue.git

### 描述问题
van-index-bar与van-tabs结合使用，van-tabs使用sticky属性，点击van-index-bar的索引栏，会导致内容被遮挡。

**Comment by XiaoLeaf** [comment]
没有官方人员答复么？？？

**Comment by rex-zsd** [comment]
图破了……

**Comment by XiaoLeaf** [comment]
> 图破了……

https://leaf1202.oss-cn-beijing.aliyuncs.com/issue.png，截图地址

**Comment by XiaoLeaf** [comment]
> 图破了……
截图地址
https://leaf1202.oss-cn-beijing.aliyuncs.com/issue.png
