### ISSUE TITLE
[Bug Report] VantComponent里面mapKeys 是否有漏洞

### ISSUE THREAD

**Issue by jsmgg** [youzan/vant-weapp#2770]
### 设备
所有

### VantWeapp 版本
1.0.5

### 基础库版本
2.1.3

### 请提供核心代码片段链接
https://github.com/youzan/vant-weapp/blob/master/packages/common/component.ts

### 描述问题
https://github.com/youzan/vant-weapp/blob/master/packages/common/component.ts
VantComponent里面mapKeys 方法的定义中，使用下面语句判断属性是否需要合并感觉欠妥。
if (source[key])

比如现在icon组件中props里的info属性默认null，就不会复制到properties中，导致传到info组件时候，info字段为undefined。【微信中没有复现，很奇怪，我们使用的自家的小程序平台，你们可以看看是否需要修改】

**Comment by rex-zsd** [comment]
应该没有这个问题吧，mapKeys这个方法只是为了把vantOptions给map到小程序标准的options，不会对props内部的属性做修改的，再看看？
https://github.com/youzan/vant-weapp/blob/master/packages/common/component.ts#L22
