### ISSUE TITLE
van-circle的value递减步长为小数时有问题

### ISSUE THREAD

**Issue by phoenixor** [youzan/vant-weapp#2771]
我准备做一个倒计时工具，van-circle套一个van-count-down，van-count-down使用示例中的自定义样式，在change事件中改变van-circle的value值。
初始时间time=25分钟即1500秒，计算出van-circle的递减步长为step=100/1500=0.06666666666无限。
在change事件中每次给value赋值为=上一次value值-step。
这样运行效果是圆环不停地闪，本来以为是动画太慢，把speed设置成step，运行之后van-circle没变化了。请问有什么解决方案？？
![image](https://user-images.githubusercontent.com/6568115/74661235-83890b00-51d2-11ea-94dc-47858aca50a2.png)

**Comment by rex-zsd** [comment]
这个是使用姿势的问题了，可以把speed设置为`0`或者`1000`以上，就不会出现闪烁了
因为设置了value之后内部也会有一个过渡效果的，然后外部快速的设置，导致了闪烁现象。

**Comment by phoenixor** [comment]
> 这个是使用姿势的问题了，可以把speed设置为`0`或者`1000`以上，就不会出现闪烁了
> 因为设置了value之后内部也会有一个过渡效果的，然后外部快速的设置，导致了闪烁现象。

但是value最大是100，speed=value/s，每秒刷新一次怎么设置成1000以上？？？

**Comment by LitChi666** [comment]
设置了0关闭动画，才没有你说的闪烁。

**Comment by LitChi666** [comment]
设置其他的1000没区别

**Comment by phoenixor** [comment]
> 设置了0关闭动画，才没有你说的闪烁。

speed=0还能动吗？

**Comment by inaruto** [comment]
自定义样式    小时计算有偏差

**Comment by inaruto** [comment]
![image](https://user-images.githubusercontent.com/46149052/89503082-9d59f100-d7f8-11ea-9cfc-7149d4c781bc.png)
