### ISSUE TITLE
iOS 13.4 beta版界面渲染不出来，但是点击相应都在

### ISSUE THREAD

**Issue by sssssunying** [youzan/vant-weapp#2774]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater?repo=VantWeapp

**Comment by rex-zsd** [comment]
issue格式不规范，渲染不出来是在开发预览还是真机预览还是线上小程序呢？
可以提供一下核心代码和截图吗？
