### ISSUE TITLE
通过npm安装问题

### ISSUE THREAD

**Issue by pettercat** [youzan/vant-weapp#2776]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater?repo=VantWeapp
安装后用微信开发工具预览提示664，缺失上传node_modules/@vant目录下的全部文件，但是可以通过上传，然后node_modules目录在开发工具目录中看不到了，但是它是存在的

**Comment by rex-zsd** [comment]
没看懂，npm安装在npm install之后需要在开发者工具上点npm构建的，上传的时候不会上传node_modules/@vant的

**Comment by pettercat** [comment]
噢谢谢，当时我是初学者，是我工具的问题，现在解决了，感谢你们的项目。



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "rex"<notifications@github.com&gt;; 
发送时间: 2020年2月21日(星期五) 中午11:37
收件人: "youzan/vant-weapp"<vant-weapp@noreply.github.com&gt;; 
抄送: "楞仔荣"<2259963996@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [youzan/vant-weapp] 通过npm安装问题 (#2776)




没看懂，npm安装在npm install之后需要在开发者工具上点npm构建的，上传的时候不会上传node_modules/@vant的
