### ISSUE TITLE
[Feature Request] npm下载后不存在Uploader组件

### ISSUE THREAD

**Issue by jiutianliminwang** [youzan/vant-weapp#2780]
### 这个功能解决了什么问题
上传文件

### 建议的API是什么样的
无

**Comment by rex-zsd** [comment]
下载的版本是什么？报错信息是怎么样的？核心代码可以提供一下吗？

**Comment by jiutianliminwang** [comment]
最新版本，没报错，是找不到这个组件

**Comment by jiutianliminwang** [comment]
"vant-weapp": "^0.5.27"

**Comment by rex-zsd** [comment]
vant-weapp是0.x的旧版本，看下[文档的安装部分](https://github.com/youzan/vant-weapp#%E5%AE%89%E8%A3%85)，下载`@vant/weapp`最新版本哈。
