### ISSUE TITLE
[Bug Report] van-tabs sticky

### ISSUE THREAD

**Issue by anihCevol** [youzan/vant-weapp#2782]
### 设备
IOS

### VantWeapp 版本
1.0.5

### 基础库版本
2.9.4

### 请提供核心代码片段链接
https://youzan.github.io/vant-weapp/#/tab

### 描述问题
使用sticky后：假如第一个 tab的内容高度为100px,向下滑动页面时，tab标题到顶部会吸顶，切换到第二个tab（内容高度200px），向下滑动时，tab标题栏也可以吸顶，但继续下滑高度大于100px，就是第一个tab内容高度时，tab标题栏就不吸顶了。

**Comment by xiaodong86** [comment]
请问 还在修复嘛 我这边也遇到了这个情况
