### ISSUE TITLE
[Bug Report] 关于search快速输入时，文字丢失问题

### ISSUE THREAD

**Issue by yangjh168** [youzan/vant-weapp#2784]
### 设备
andriod

### VantWeapp 版本
1.0.6

### 基础库版本
2.9.4

### 如果是 UI 问题，截图链接（多图回车分隔）

![截图](https://sm.ms/image/LkZeQwGSd6PisvV)

### 请提供核心代码片段链接
https://github.com/youzan/vant-weapp/blob/dev/lib/field/index.js

### 描述问题
在手机上外置ID读卡器，当刷卡时，搜索框search组件会快速输入读卡器读到的数字，但是搜索框输入的数字并非ID读卡器真实的数字，存在数据丢失问题。查询源码方知：search基于filed组件上开发，但是filed组件的oninput事件中，emitChange存在延迟操作问题（wx.nextTick），所以在快速输入时，会丢失部分输入数据；

**Comment by rex-zsd** [comment]
#2189 跟这个issue应该是同一个问题哈
