### ISSUE TITLE
vant像素单位如何适配多端

### ISSUE THREAD

**Issue by jone8881** [youzan/vant-weapp#2785]
### 设备
ipad、iphone

### VantWeapp 版本
1.0.6

### 基础库版本
1.0.6

### 请提供核心代码片段链接
https://github.com/youzan/vant-weapp/blob/dev/packages/goods-action-button/index.less

### 描述问题
1、vant的组件源码样式像素单位都用的是px，不是rpx，请问vantWeapp是如何适配不同分辨率终端下的字体大小的？
2、全都用px，在ipad上文字会不会显示太小？
3、我在项目中用到vant的组件需要覆写样式的，应该用什么像素单位？
烦请解答一下，非常谢谢！

**Comment by rex-zsd** [comment]
1. 不同端字体大小相同
2. 可以覆盖样式自行调整
3. px、rpx都可以的
