### ISSUE TITLE
package.json 和 node_modules 必须在 miniprogram 目录下是什么意思？

### ISSUE THREAD

**Issue by lvshutao** [youzan/vant-weapp#2789]
使用开发者工具创建的新项目(ts)目录结构如下
```
root/
    |-- miniprogram
    |-- node_modules
    |-- package.json
    |-- ...
```
vant weapp 快速上手中第一步就说 ”需要注意的是 package.json 和 node_modules 必须在 miniprogram 目录下“。

可是 `miniprogram` 目录下并没有 `package.json` 和 node_modules 目录呀，这是不是说要先 `cd miniprogram` 然后 `npm init` 自己初始化一下？（我试了直接 cd miniprogram 然后直接 `npm i @vant/weapp -S --production`，发现被安装到了 `root/package.json` 中去了）

注：之所有有这个困惑，是因为在项目中导入 vant-weapp 后，在开发者工具中测试完成正常，但是一上传预览版，就总是提示 `Component is not found in path "@vant/weapp/button" (using by "miniprogram_npm/@vant/weapp/info/index"); on AppRoute。也不知道是哪里错了

**Comment by rex-zsd** [comment]
按小程序官方的教程，`node_modules`和`package.json`要在`miniprogram`里面的，不然npm构建会提示找不到可构建的库。

**Comment by rex-zsd** [comment]
也就是说官方创建的初始目录结构是有问题的，按照初始的目录结构没办法npm构建。

**Comment by phoenixor** [comment]
> 使用开发者工具创建的新项目(ts)目录结构如下
> 
> ```
> root/
>     |-- miniprogram
>     |-- node_modules
>     |-- package.json
>     |-- ...
> ```
> 
> vant weapp 快速上手中第一步就说 ”需要注意的是 package.json 和 node_modules 必须在 miniprogram 目录下“。
> 
> 可是 `miniprogram` 目录下并没有 `package.json` 和 node_modules 目录呀，这是不是说要先 `cd miniprogram` 然后 `npm init` 自己初始化一下？（我试了直接 cd miniprogram 然后直接 `npm i @vant/weapp -S --production`，发现被安装到了 `root/package.json` 中去了）
> 
> 注：之所有有这个困惑，是因为在项目中导入 vant-weapp 后，在开发者工具中测试完成正常，但是一上传预览版，就总是提示 `Component is not found in path "@vant/weapp/button" (using by "miniprogram_npm/@vant/weapp/info/index"); on AppRoute。也不知道是哪里错了

我按照快速上手教程做了，但是导入notify组件时ts报找不到组件，但是使用又正常，说明路径没错。
![image](https://user-images.githubusercontent.com/6568115/76619871-daca9300-6566-11ea-9103-d8b085cb30b5.png)
tsconfig.json配置如下
![image](https://user-images.githubusercontent.com/6568115/76619861-d3a38500-6566-11ea-8e96-b86934dc9c33.png)

**Comment by YikSanChan** [comment]
@rex-zsd 请问可以帮忙提供一个正确的初始目录结构吗？谢谢
