### ISSUE TITLE
tab&tabs在h5内容不显示

### ISSUE THREAD

**Issue by whoopsHzh** [youzan/vant-weapp#2791]
![image](https://user-images.githubusercontent.com/32846446/75403609-2c5a0780-5943-11ea-9ed1-2137f1c946fd.png)

小程序可以正常显示：
![image](https://user-images.githubusercontent.com/32846446/75403649-44318b80-5943-11ea-87a2-bede426bcf6b.png)

h5的切换tab，tabs中的内容不显示
![image](https://user-images.githubusercontent.com/32846446/75403649-44318b80-5943-11ea-87a2-bede426bcf6b.png)

**Comment by rex-zsd** [comment]
h5的issue可以在[这里](https://github.com/youzan/vant)提交
