### ISSUE TITLE
[Bug Report] picker组件未选中选项没有置灰

### ISSUE THREAD

**Issue by NPCBOSS** [youzan/vant-weapp#2792]
### 设备
微信开发者工具 

### VantWeapp 版本
1.0.5

### 基础库版本
2.10.2

### 如果是 UI 问题，截图链接（多图回车分隔）

![截图](https://i.loli.net/2020/02/27/W78QDgXlPKmGAFS.png)

### 请提供核心代码片段链接
https://gitee.com/npcboss/codes/knlp6cj5bmtouafid309h80

### 描述问题
vantWeapp中picker组件，未选中项背景没有变成灰色，和选中项是相同颜色，区分度不大

**Comment by babizhu** [comment]
同样的问题
