### ISSUE TITLE
vant Calendar PullRefresh  刷新冲突 

### ISSUE THREAD

**Issue by zhanghongyi001** [youzan/vant-weapp#2794]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。
全局使用 PullRefresh 组件时 Calendar 组件无法使用 滚动选择
https://youzan.github.io/vant-issue-generater?repo=VantWeapp

**Comment by chenjiahan** [comment]
Vue 的问题请到 vant 仓库下按照模板创建 issue
