### ISSUE TITLE
[Bug Report] van-popup和van-tab混用显示不正常

### ISSUE THREAD

**Issue by TSjianjiao** [youzan/vant-weapp#2796]
### 设备
全部

### VantWeapp 版本
1.0.6

### 基础库版本
全部

### 如果是 UI 问题，截图链接（多图回车分隔）

![截图](https://i.loli.net/2020/02/28/RfJENH1xYUpVv7z.png)

### 请提供核心代码片段链接
https://gist.github.com/1e095f87d78348fe8f476f257cc54b48.git

### 描述问题
详情见gist，问题主要是因为`tabs`实际宽度超过了一屏，而`popup`是固定的`left:0`，虽然`popup`提供了自定义遮罩样式，可是其他使用了`popup`的组件没有提供自定义遮罩样式的属性

**Comment by rex-zsd** [comment]
看gist的内容，其实是需要给 dropdown 增加自定义内部popup样式的api

**Comment by TSjianjiao** [comment]
> 
> 
> 看gist的内容，其实是需要给 dropdown 增加自定义内部popup样式的api

对 可以先提供`popup`的自定样式接口
