### ISSUE TITLE
[Bug Report] 使用van-collapse-item手风琴模式时，name属性设置为{{ index }}，onLoad时不生效

### ISSUE THREAD

**Issue by wisting967** [youzan/vant-weapp#2797]
### 设备
微信开发者工具

### VantWeapp 版本
1.0.5

### 基础库版本
2.10.1

### 请提供核心代码片段链接
https://github.com/wisting967/assistantUI-v/blob/master/pages/accountbook/index.wxml

### 描述问题
代码片段如下：
```
    <van-collapse value="{{ activeName }}" bind:change="onChange" accordion>
      <van-collapse-item wx:for="{{ feeDetail }}" wx:key="FeeDetailTime" title="{{ item.feeDetailItem }}" name="{{ index  + 1 }}" value="{{ item.feeDetailValue }}">
        <van-cell title="日期" value="{{ item.FeeDetailTime }}-{{ index }}" />
        <van-cell title="流水" value="{{ item.feeDetailType }}{{ item.feeDetailValue }}" border="{{ false }}"/>
      </van-collapse-item>
    </van-collapse>
```

数据初始化：
```
Page({
  data: {
        activeName: '1'
  }
})
```
1、在页面加载时，第一条并不会展开，必须要手工点击才能展开（之后手工设置没有问题）
2、如果不用wx:for循环，直接写死指定第一条数据的name属性为1，则页面加载时，可以默认展开
刚开始学习，不知道是否使用方法有问题？

[update]:
如果不用{{ index }}，而使用数组中的某一个唯一值，如{{ item.varName }}，则没有问题

**Comment by rex-zsd** [comment]
这里是因为你的name设置的是数字，但是`activeName`却是字符串`'1'`，所以才会有没有展开的问题。
