### ISSUE TITLE
请问下 share icon 实际的样子，和文档上给的怎么不一样

### ISSUE THREAD

**Issue by greedying** [youzan/vant-weapp#2798]
如题。

文档上是一个弯曲箭头

实际上是一个圆圈加小箭头
![1](https://user-images.githubusercontent.com/7993339/75604717-a2fb2e80-5b16-11ea-90d9-109a9a16d1b9.png)

**Comment by rex-zsd** [comment]
具体图标以演示小程序为准哈，文档右侧的示例是h5 vant的，可能会有些不一致。
