### ISSUE TITLE
小程序导入nofity组件提示找不到模块

### ISSUE THREAD

**Issue by phoenixor** [youzan/vant-weapp#2802]
通过npm安装的，按照快速上手方法编译npm了，按照文档引入了notify模块，使用正常，但是页面ts文件提示找不到模块。
![image](https://user-images.githubusercontent.com/6568115/75623178-89271d80-5be2-11ea-98df-c5507d121933.png)
![image](https://user-images.githubusercontent.com/6568115/75623193-a1973800-5be2-11ea-9d99-058df16bb13b.png)
![image](https://user-images.githubusercontent.com/6568115/75623201-b1168100-5be2-11ea-925f-9c667f98a615.png)

**Comment by rex-zsd** [comment]
https://youzan.github.io/vant-weapp/#/quickstart#bu-zou-san-xiu-gai-tsconfig.json
看下快速上手文档，是不是tsconfig.json没有修改？

**Comment by phoenixor** [comment]
> 看下[快速上手文档](https://youzan.github.io/vant-weapp/#/quickstart#bu-zou-san-xiu-gai-tsconfig.json)，是不是tsconfig.json没有修改？

修改了，快速上手的4个步骤都做了，组件使用正常没有报错，就是ts提示找不到模块，很奇怪

**Comment by rex-zsd** [comment]
贴下代码看看？

**Comment by phoenixor** [comment]
> 贴下代码看看？
上面已经有页面引用代码了，在页面onShow()里面使用Notify()，下面是tsconfig.json
![image](https://user-images.githubusercontent.com/6568115/75623412-a3fa9180-5be4-11ea-8180-22713d0fdb36.png)

**Comment by rex-zsd** [comment]
这就棘手了…………
ts提示找不到是因为开发者工具npm构建后，`node_modules/@vant/weapp/dist` 会被复制到 `miniprogram_npm/@vant/weapp` 下面
按这个思路调整下tsconfig.json试试看？

**Comment by rex-zsd** [comment]
感觉可能是因为你的目录结构不同导致的

**Comment by phoenixor** [comment]
> 感觉可能是因为你的目录结构不同导致的

我通过微信开发者工具生成的ts项目模板，你看下目录结构
![image](https://user-images.githubusercontent.com/6568115/75623571-3b141900-5be6-11ea-9969-623b070ca752.png)

**Comment by SeLiNnnn** [comment]
请问下ts里该怎么用呢 
Could not find a declaration file for module '../../miniprogram_npm/@vant/weapp/notify/notify'. '.........../miniprogram/miniprogram_npm/@vant/weapp/notify/notify.js' implicitly has an 'any' type.
