### ISSUE TITLE
van-dropdown-item 获取选中的值

### ISSUE THREAD

**Issue by LerLxl** [youzan/vant-weapp#2806]
![image](https://user-images.githubusercontent.com/49472459/75650634-76b7ed00-5c91-11ea-9fa5-02b7b6a2d3cd.png)
![image](https://user-images.githubusercontent.com/49472459/75650643-7f102800-5c91-11ea-87ea-af42dff409e3.png)
![image](https://user-images.githubusercontent.com/49472459/75650647-83d4dc00-5c91-11ea-82b2-d5c7b19b7eb1.png)
![image](https://user-images.githubusercontent.com/49472459/75650656-89cabd00-5c91-11ea-814e-7cdaaac18bfb.png)
如何获取选中的值 与后台交互呢

**Comment by rex-zsd** [comment]
可以看下文档，`change`事件可以获取选中值。

**Comment by LerLxl** [comment]
van-card 使用thumb-link 跳转路由 如何传值



在 2020-03-02 14:39:50，"rex" <notifications@github.com> 写道：

可以看下文档，change事件可以获取选中值。
