### ISSUE TITLE
[Bug Report] 按钮宽度被拉长了，宽度有问题

### ISSUE THREAD

**Issue by damon-kong** [youzan/vant-weapp#2807]
### 设备
微信开发工具

### VantWeapp 版本
1.0.6

### 基础库版本
2.10.2

### 如果是 UI 问题，截图链接（多图回车分隔）

![截图](http://111.229.48.117/zdtPic/merchant/cover/NS6VfUVWULqTEcWexPnH.jpg)

### 请提供核心代码片段链接
https://gitee.com/damoncat/miniproject-b/blob/master/pages/order-manage/index.wxml

### 描述问题
UI图片是我重新搞了个空白项目重新npm进去的，也是这个问题，就是按钮无缘无故被拉长还不能修改长度= =，这个问题我2019年12月份npm搞的一个版本是没有的，今天是2020年3月2号就出来了，麻烦看一下谢谢

**Comment by rex-zsd** [comment]
看一下快速上手，把`app.json`内的`"style": "v2"`去除掉。
这个样式是微信v2自带的样式，不是vant weapp添加的。

**Comment by damon-kong** [comment]
额，解决了，很感谢！
