### ISSUE TITLE
Uploader 图片预览

### ISSUE THREAD

**Issue by yrz0816** [youzan/vant-weapp#2809]
从afterRead方法中拿到图片地址 用原生image可以正确显示 赋值给fileList无法显示  网络图片正常显示 是我设置的有问题吗
  afterRead:function(event){
    console.log(event)
    this.setData({
      fileList: [{ url: event.detail.path, name: '图片2',isImage: true}]
    })
  } 删除按钮也没反应  是写的有问题吗

**Comment by yrz0816** [comment]
页面代码 <van-uploader  file-list="{{ fileList }}"  max-count="1"  accept="image" bind:after-read="afterRead" />

**Comment by zgia** [comment]
请问您是如何解决这个问题的？我也遇到了，使用微信开发工具时，afterRead和delete均没有响应。

**Comment by yrz0816** [comment]
不知道您所说的跟我遇到的是否是一个问题&nbsp;&nbsp;afterRead和delete方法需要自己去写方法&nbsp;修改展示的列表&nbsp; 达到页面变化




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "zgia"<notifications@github.com&gt;; 
发送时间: 2020年3月14日(星期六) 中午1:24
收件人: "youzan/vant-weapp"<vant-weapp@noreply.github.com&gt;; 
抄送: "李含"<lihan369@qq.com&gt;; "State change"<state_change@noreply.github.com&gt;; 
主题: Re: [youzan/vant-weapp] Uploader 图片预览 (#2809)





 
请问您是如何解决这个问题的？我也遇到了，使用微信开发工具时，afterRead和delete均没有响应。
