### ISSUE TITLE
[Bug Report] Dialog.confirm样式错误

### ISSUE THREAD

**Issue by shenboran** [youzan/vant-weapp#2810]
### 设备
Android

### VantWeapp 版本
1.0.6

### 基础库版本
2

### 如果是 UI 问题，截图链接（多图回车分隔）

![截图](https://user-images.githubusercontent.com/10139725/75690044-2f574e00-5cdd-11ea-843c-7ab865bd9692.png)

### 请提供核心代码片段链接
https://github.com/youzan/vant-weapp/blob/dev/dist/dialog/index.wxss

### 描述问题
Dialog.confirm样式错误

**Comment by rex-zsd** [comment]
app.json中的`"style": "v2"`去除了吗？
