### ISSUE TITLE
van-card  响应式问题 点击图片 跳转路由 如何传值

### ISSUE THREAD

**Issue by LerLxl** [youzan/vant-weapp#2814]
![image](https://user-images.githubusercontent.com/49472459/75746870-7e8d9500-5d56-11ea-9648-d13c685a11a8.png)
![image](https://user-images.githubusercontent.com/49472459/75746922-9ebd5400-5d56-11ea-9466-2570ad49df8d.png)
切换预览屏幕 位置右边会空一块

**Comment by rex-zsd** [comment]
与[wx.navigateTo](https://developers.weixin.qq.com/miniprogram/dev/api/route/wx.navigateTo.html)的url参数格式一致哈
