### ISSUE TITLE
[Bug Report] switch组件在cell组件下不是逾期高度和位置偏移

### ISSUE THREAD

**Issue by zopi4455** [youzan/vant-weapp#2815]
### 设备
所有

### VantWeapp 版本
1.0.0

### 基础库版本
2.10.0

### 如果是 UI 问题，截图链接（多图回车分隔）

https://i.loli.net/2020/03/03/R2ID5lvJyLdgV9A.png

![截图](https://i.loli.net/2020/03/03/37LI1cFNdBJZ2fa.png)

![截图](https://i.loli.net/2020/03/03/ebhCzJt4YMTwX8F.png)

### 请提供核心代码片段链接
https://youzan.github.io/vant-weapp/#/switch

### 描述问题
switch 组件在 cell 组件下不是逾期高度和位置偏移（导致整个 cell 变高了）。
图1为不是逾期高度，图2位位置偏移，图3为代码
应该是忘记在 switch 根节点添加 vertical-align 属性了，原来的组件 switch-cell 是添加样式 vertical-align:middle 的。建议添加 vertical-align: text-top;

**Comment by rex-zsd** [comment]
可以通过外部样式类`custom-class`自行添加一下，`vertical-align`这种属性不太适合放在组件里。
原来的`switch-cell`是内部组合了`cell`和`switch`并添加了部分样式的。

**Comment by CalmHarbin** [comment]
> 可以通过外部样式类`custom-class`自行添加一下，`vertical-align`这种属性不太适合放在组件里。
> 原来的`switch-cell`是内部组合了`cell`和`switch`并添加了部分样式的。

为啥我使用 custom-class无效 
![image](https://user-images.githubusercontent.com/34387163/93075967-2ea26a00-f6b9-11ea-9ec9-b26b82fd11f0.png)

![image](https://user-images.githubusercontent.com/34387163/93077282-29deb580-f6bb-11ea-891b-f277a07fbdec.png)

渲染出来的根本就没有自定义的类
