### ISSUE TITLE
wepy2.0 使用 dialog 组件 报未找到van-dialog节点

### ISSUE THREAD

**Issue by george-es** [youzan/vant-weapp#2820]
wepy升级2.0后，引入 vant 组件，使用 dialog 时，报未找到 van-dialog 节点，请确认 selector 及 context 是否正确

2.0以下是正常的
![image](https://user-images.githubusercontent.com/29953244/75848175-5cf6e100-5e1c-11ea-949b-5e1bd58fa2bd.png)

**Comment by zehuichan** [comment]
漏了
`<van-dialog id="van-dialog" />`

**Comment by george-es** [comment]
> 漏了
> `<van-dialog id="van-dialog" />`

**Comment by george-es** [comment]
@zehuichan 没漏，在第五行呢

**Comment by zehuichan** [comment]
@george-es sorry，图床坏了，没看到

**Comment by ItsNikkiZeng** [comment]
我也是遇到这个问题,目前怎么调都没用,请问有解决吗,json文件有配置,import也引入了,组件也放置wxml文件中了

**Comment by rex-zsd** [comment]
组件里使用需要传`context`的哈，看下文档，wepy里应该是传`this.$wx`。

**Comment by george-es** [comment]
@rex-zsd 不行的，我特意看了源码，它搜索不到这个dom，不知道是不是底层问题

**Comment by george-es** [comment]
@ItsNikkiZeng 2.0以下不会，我现在的解决方法是通过show来实现

**Comment by rex-zsd** [comment]
实测了wepy`2.0.0-alpha.9`是可以的

**Comment by rex-zsd** [comment]
不过我试的是通过按钮点击来触发toast，在ready阶段调用，涉及wepy生命周期的问题，可能ready时toast组件尚未被渲染。

**Comment by rex-zsd** [comment]
如果是这样的话，vant weapp这边完全是无能为力的。建议还是回退wepy吧，wepy已经alpha一年多了没release正式版……建议还是不要头铁

**Comment by george-es** [comment]
@rex-zsd  你说ready时 toast 组件未渲染，那么是怎么成功的呢?

**Comment by BongBongBang** [comment]
我用的remax调用，也报这个问题。不指定selector还好，一旦指定了，传入context也没用。看过源码，传不传selector在调用微信小程序selector时，没什么大区别，郁闷。
