### ISSUE TITLE
[Feature Request] 如何将组件在小程序中做成响应式的，px转rpx，请教一下，谢谢

### ISSUE THREAD

**Issue by lmfuture** [youzan/vant-weapp#2822]
### 这个功能解决了什么问题
如何将组件在小程序中做成响应式的，px转rpx，请教一下有没有好的方案，谢谢

### 建议的API是什么样的
如何将组件在小程序中做成响应式的，px转rpx，请教一下有没有好的方案，谢谢

**Comment by rex-zsd** [comment]
#892
