### ISSUE TITLE
现在都在走多端开发,能否兼容多端小程序呢?

### ISSUE THREAD

**Issue by chenxyhz** [youzan/vant-weapp#2823]
目前来说以前一直是单独拿来写源生微信小程序,现在小小程序市场越来越火,各种平台都推出自己的小程序,现在都拿uni-app去开发多端,能否让vant支持多端的小程序规则呢?或者说直接出一个什么支付宝的版,百度等等的版本呢?

**Comment by rex-zsd** [comment]
暂时不会考虑支持其它端哈
