### ISSUE TITLE
[Feature Request] Popup 弹出层能否加一个固定的标题栏，关闭按钮也能固定

### ISSUE THREAD

**Issue by freechen** [youzan/vant-weapp#2824]
### 这个功能解决了什么问题
目前的在popup层中放入的内容多的话，向上滑动，关闭按钮也向上移动，能否方便固定。另外能否添加固定的标题栏。

### 建议的API是什么样的
标题栏可固定，可设置或不设置。

**Comment by rex-zsd** [comment]
需要固定标题栏，可以使用ActionSheet组件哈
内滚动可以自行添加样式控制的

**Comment by Jingfx** [comment]
Popup 弹出层，在【右侧】弹出时能否加一个固定的按钮？
