### ISSUE TITLE
[Bug Report] How to import Dialog in wechat miniprogram typescript project

### ISSUE THREAD

**Issue by agoni1212** [youzan/vant-weapp#2825]
### 设备
Android

### VantWeapp 版本
1.0.7

### 基础库版本
2.10.2

### 请提供核心代码片段链接
https://github.com/agoni1212/testwechat/

### 描述问题
微信小程序，使用 typescript ，如何 import Dialog 函数
编译提示如下错误，但功能能正常使用，但在真机调试或上传部署时就不行了

VM8586:1 miniprogram/pages/index/index.ts:3:20 - error TS7016: Could not find a declaration file for module '../../miniprogram_npm/@vant/weapp/dialog/dialog'. 'D:/miniprogram/ams/miniprogram/miniprogram_npm/@vant/weapp/dialog/dialog.js' implicitly has an 'any' type.

3 import Dialog from "../../miniprogram_npm/@vant/weapp/dialog/dialog";

这里"../../miniprogram_npm/@vant/weapp/dialog/dialog"，因为缺少 TS 的类型申明，所以会报 Could not find a declaration file for module

但TS 的类型申明如下图目录结构 ， 后改成
import Dialog from "@vant/weapp/dialog/dialog"; （@vant/weapp 在tsconfig里已经配置了）
就报找不到了

> error TS2307: Cannot find module '@vant/weapp/dialog/dialog'.

![image.png](https://i.loli.net/2020/03/05/3XTM68Z2uAnCgyK.png)

**Comment by rex-zsd** [comment]
截图里没看到tsconfig.json文件，是在上层？
总之是把`node_modules/@vant/weapp/*`重定义到`node_modules/@vant/weapp/dist/*`就可以了，具体得看你的node_modules的位置哈。
