### ISSUE TITLE
[Bug Report] UI的example示例显示不正常

### ISSUE THREAD

**Issue by ZSX-JOJO** [youzan/vant-weapp#2826]
### 设备
微信开发者工具

### VantWeapp 版本
1.0.7

### 基础库版本
2.3.0

### 如果是 UI 问题，截图链接（多图回车分隔）
![1.jpg](https://i.loli.net/2020/03/05/IAcBSVrDTpRJw6n.png)
![2.jpg](https://i.loli.net/2020/03/05/P6XCD8QIa2pwil4.png)

### 请提供核心代码片段链接
https://gist.github.com/ZSX-JOJO/1293992b955ed503170570bc9f995c76

### 描述问题
直接导入example文件夹会报错,复制dist文件夹到example也会报错,注释报错的地方之后可以打开example的例子,但是例子显示不正常.我截图了.
应该很多人都遇到这个问题了吧,不知道为什么没反映的,打扰了,抱歉.

**Comment by rex-zsd** [comment]
报错信息是什么？

**Comment by ZSX-JOJO** [comment]
这是我重新clone下来的,直接将example文件导入报错如下,所以我才复制进去dist文件夹,也便出现了开始反馈的问题,打扰了.
![直接导入example.png](https://i.loli.net/2020/03/06/PA9Rv2UZ4ulhozB.png)

**Comment by ZSX-JOJO** [comment]
> 报错信息是什么？

我截图了,看一下.

**Comment by rex-zsd** [comment]
导入`example`之后，是不是没有运行`npm run dev`？
从报错信息来看是找不到`dist`目录下的组件

**Comment by ZSX-JOJO** [comment]
> 导入`example`之后，是不是没有运行`npm run dev`？
> 从报错信息来看是找不到`dist`目录下的组件

其实这个安装依赖环境,编译,骤我也做了,但是也报错....,所以最后我才直接复制dist文件夹到example里的,算了只是官方示例罢了,也许就我倒霉吧,最开始我以为npm代理的原因,我关闭了npm代理,换了淘宝的源看了下npm也没出现错误,我有点强迫症,打扰了,我过会再试试,要是还不行也就这样了.
