### ISSUE TITLE
field组件的value属性有问题

### ISSUE THREAD

**Issue by gmhejob1** [youzan/vant-weapp#2828]
组件的VALUE属性不是双向绑定吗？输入数据后，data对象里相应的字段更本不更新啊？！是BUG ?

https://youzan.github.io/vant-issue-generater?repo=VantWeapp

**Comment by rex-zsd** [comment]
仔细看下文档，小程序并不支持双向绑定。

**Comment by ldsenow** [comment]
小程序版本2.9.2开始支持双向绑定 把编译版本提高就行了
