### ISSUE TITLE
VM171:1 Page is not constructed because it is not found.

### ISSUE THREAD

**Issue by igo9go** [youzan/vant-weapp#2833]
运行example时，部门页面打不开

![image](https://user-images.githubusercontent.com/11486721/76075642-501eec80-5fd8-11ea-8a86-5bc5636b483c.png)

**Comment by rex-zsd** [comment]
可以跑下`npm run dev`，然后点下清除缓存重新编辑，或者关闭开发者工具重新打开试试。
