### ISSUE TITLE
[Bug Report] 使用 pick 组件时编译失败

### ISSUE THREAD

**Issue by mambahao** [youzan/vant-weapp#2834]
### 设备
macbook

### VantWeapp 版本
1.0.7

### 基础库版本
2.2.2

### 描述问题
使用 pick 组件，编译失败, 信息如下

Module not found: Error: Can't resolve './toolbar' in '/x/node_modules/@vant/weapp/dist/picker'
 @ ./node_modules/@vant/weapp/dist/picke/xxr/index.wxml?packageName=main&resourcePath=/xxx/node_modules/@vant/weapp/dist/picker/index.js (./node_modules/@mpxjs/webpack-plugin/lib/content-loader.js?{"type":"template","index":"0"}!./node_modules/@vant/weapp/dist/picker/index.wxml?packageName=main&resourcePath=/xxx/node_modules/@vant/weapp/dist/picker/index.js) 1:36-361

**Comment by rex-zsd** [comment]
使用了什么小程序框架吗？

**Comment by stillyu** [comment]
使用remax框架，同样有这个警告

**Comment by zgia** [comment]
使用wepy 2.0 框架 + 微信开发者工具 RC v1.02.2003121，还会报错：找不到`./toolbar.wxml`。

错误提示：
WXMLRT_$gwx:./components/vant/picker/index.wxml:import:9:2: Path `./toolbar.wxml` not found from `./components/vant/picker/index.wxml`.

index.wxml:
import src="./toolbar.wxml"

请问如何解决？

**Comment by YInJunWen** [comment]
> 使用remax框架，同样有这个警告

你好 请问你解决了吗
