### ISSUE TITLE
cover-view套van-button在真机不显示？

### ISSUE THREAD

**Issue by phoenixor** [youzan/vant-weapp#2836]
页面是canvas图表，靠下方是一个悬浮按钮，为了不让图表挡住按钮，使用cover-view套van-button实现，在模拟器显示正常，但是在真机不显示按钮。
![image](https://user-images.githubusercontent.com/6568115/76144838-065d0180-60bf-11ea-90b3-6935c36047aa.png)
![image](https://user-images.githubusercontent.com/6568115/76144843-17a60e00-60bf-11ea-804b-ecc5eac8b261.png)

**Comment by rex-zsd** [comment]
看下微信小程序的文档，cover-view内部只能使用cover-view和cover-image。
