### ISSUE TITLE
tab加了name属性有问题

### ISSUE THREAD

**Issue by gmhejob1** [youzan/vant-weapp#2837]
tab加了name属性后，第一次开页面，默认的TAB内容不显示，需要点击 一下相应TAB内容才会显示，去了NAME属性后就没事了

https://youzan.github.io/vant-issue-generater?repo=VantWeapp

**Comment by Lindysen** [comment]
可以提供一下核心代码，不然不便排查问题

**Comment by rex-zsd** [comment]
确认下你的`name`和`value`的值是一致的吗？

**Comment by gmhejob1** [comment]
name和VALUE一样不一样都不行


我不在项目里用，随便建了个测试页面，只写了一个TAB组件测试，也是这样，加了NAME属性，第一次打开页面，默认TAB里的内容不显示，需要手动点一下默认的TAB才都正常




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"rex"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月9日(星期一) 上午10:28
收件人:&nbsp;"youzan/vant-weapp"<vant-weapp@noreply.github.com&gt;;
抄送:&nbsp;"AWP"<13923833@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [youzan/vant-weapp] tab加了name属性有问题 (#2837)




确认下你的name和value的值是一致的吗？

**Comment by rex-zsd** [comment]
核心代码？

**Comment by gmhejob1** [comment]
以下是没有name属性的



这个是有name属性的





以下是随便测试的语句，一个毛病

这是第 一次打开页面



点击test1后的





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"rex"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月9日(星期一) 中午12:14
收件人:&nbsp;"youzan/vant-weapp"<vant-weapp@noreply.github.com&gt;;
抄送:&nbsp;"AWP"<13923833@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [youzan/vant-weapp] tab加了name属性有问题 (#2837)




核心代码？

**Comment by rex-zsd** [comment]
![image](https://user-images.githubusercontent.com/8767877/76182726-e897b580-6200-11ea-824d-64803c269cfe.png)
图都没有传上来哈

**Comment by gmhejob1** [comment]
这回呢?怎么会没有照片呢。。。。。


以下是没有name属性的



这个是有name属性的





以下是随便测试的语句，一个毛病

这是第 一次打开页面



点击test1后的





------------------ 原始邮件 ------------------
发件人:&nbsp;"rex"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月9日(星期一) 中午12:14
收件人:&nbsp;"youzan/vant-weapp"<vant-weapp@noreply.github.com&gt;;
抄送:&nbsp;"AWP"<13923833@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [youzan/vant-weapp] tab加了name属性有问题 (#2837)




核心代码？

**Comment by rex-zsd** [comment]
一样，一片空白
