### ISSUE TITLE
Dialogt弹框按钮不整齐，右侧确定按钮往右边跑

### ISSUE THREAD

**Issue by Sarmay** [youzan/vant-weapp#2838]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater?repo=VantWeapp
Dialogt弹框按钮不整齐，右侧确定按钮往右边跑，

**Comment by rex-zsd** [comment]
确认下`app.json`，应该是`"style": "v2"`没去除。
