### ISSUE TITLE
[Bug Report] VM5291:1 未找到 van-toast 节点，请确认 selector 及 context 是否正确

### ISSUE THREAD

**Issue by ItsNikkiZeng** [youzan/vant-weapp#2839]
### 设备
微信开发工具

### VantWeapp 版本
1.0.7

### 基础库版本
 "@vant/weapp": "^1.0.7",

### 请提供核心代码片段链接
https://youzan.github.io/vant-issue-generater/dist/#/zh-CN?repo=VantWeapp

### 描述问题
其他组件引入没问题,就这个组件引入说一直没找到节点

**Comment by rex-zsd** [comment]
提供一下你的核心代码，这样是看不出问题的。

**Comment by ItsNikkiZeng** [comment]
我发现是在小程序的component的用不了

**Comment by rex-zsd** [comment]
component内使用是需要传`context`参数的，看下文档哈。
