### ISSUE TITLE
什么时候能生成正常的d.ts文件

### ISSUE THREAD

**Issue by fangkyi03** [youzan/vant-weapp#2840]
### 这个功能解决了什么问题
在taro小程序中 引入vant以后 没有任何补全 麻烦的要死

### 建议的API是什么样的
输入代码的时候 能有补全

**Comment by rex-zsd** [comment]
dist下有完整的.d.ts定义呀，仔细看下。

**Comment by fangkyi03** [comment]
![image](https://user-images.githubusercontent.com/30390014/76185788-3dd8c480-620b-11ea-8f0b-574ba6e8df5c.png)
并没有 你看button这种组件 我想拿到里面的click等事件 都没办法

**Comment by fangkyi03** [comment]
只有非常非常少的几个文件 有d.ts 其他都是空的

**Comment by rex-zsd** [comment]
`Toast`、`Dialog`这种方法类的都是有定义的。但是专门为Taro等框架提供组件的属性定义我们暂时不会提供哈。
