### ISSUE TITLE
假如只用到其中的某几个控件，应该怎么安装呢？

### ISSUE THREAD

**Issue by Small-Years** [youzan/vant-weapp#2843]
通过 npm 安装会安装所有的组件，没有用到的组件不知道会不会占用小程序包的大小，但是文件太多看着也很不舒服

**Comment by rex-zsd** [comment]
无需担心，开发者工具只会上传用到的代码。

**Comment by Small-Years** [comment]
经验证，使用npm安装之后会占用很大体积，导致小程序包超限，有单独使用某个控件的方法吗？
