### ISSUE TITLE
[Feature Request] 希望添加和vue版本类似的calendar组件

### ISSUE THREAD

**Issue by xyx650** [youzan/vant-weapp#2844]
一直在使用vant组件库，觉得非常小巧精致。项目中H5端和小程序端均有涉及，希望在vant weapp中加入和h5端风格一致的calendar组件。

希望vant越来越好 ^-^

最后弱弱的咨询一下，vant weapp文档中页面中的小程序组件示例代码和嵌在文档中的iframe是怎么实现的？ vue项目的已从github项目分析得知使用vant-cli构建compiler文件夹中的demo，但不知小程序中的Demo、是如何实现....

**Comment by rex-zsd** [comment]
1.1.0有计划添加的

**Comment by rex-zsd** [comment]
小程序和vue版本是共用的demo

**Comment by xyx650** [comment]
> 小程序和vue版本是共用的demo

意思是weapp版本的文档demo里面需要使用vue的语法而不能使用小程序的语法，可以这样理解吗
