### ISSUE TITLE
[Bug Report] Checkbox 复选框 的水平排列无效

### ISSUE THREAD

**Issue by zgia** [youzan/vant-weapp#2847]
### 设备
微信开发工具 Stable v1.02.1911180

### VantWeapp 版本
1.0.7

### 基础库版本
2.10.2

### 请提供核心代码片段链接
https://gist.github.com/zgia/36f793f5d592855ab1cdccb61522d660

### 描述问题
Checkbox 复选框 的水平排列无效，搜索了脚本，checkbox-group中没有处理“direction="horizontal"”的部分，请问如何解决？

**Comment by Lindysen** [comment]
小程序这边暂未支持，右边的图是vant 里面的示例
