### ISSUE TITLE
[Bug Report] Area 和 TextArea 重叠

### ISSUE THREAD

**Issue by agoni1212** [youzan/vant-weapp#2849]
### 设备
Andriod

### VantWeapp 版本
1.0.7

### 基础库版本
2.10.3

### 如果是 UI 问题，截图链接（多图回车分隔）

![截图](https://i.loli.net/2020/03/11/WPp6woxzgn3AX74.jpg)

### 请提供核心代码片段链接

`<view class="baco_field__title">详情地址</view>
        <van-field name="addr_desc" value="{{ addr_desc }}" type="textarea" custom-style="margin-top: -6px;font-size: 16px;" placeholder=" 请填写企业详情地址" clearable autosize />`

### 描述问题
Area 和 TextArea 重叠

https://i.loli.net/2020/03/11/WPp6woxzgn3AX74.jpg

**Comment by rex-zsd** [comment]
看下文档的常见问题部分，这个是小程序的特性导致的，目前无解。
