### ISSUE TITLE
[Bug Report] 文件上传uploader某些图片不显示预览图

### ISSUE THREAD

**Issue by edc599** [youzan/vant-weapp#2850]
### 设备
iphone11和小程序开发工具

### VantWeapp 版本
1.0.7

### 基础库版本
2.10.3

### 如果是 UI 问题，截图链接（多图回车分隔）

![截图](https://i.loli.net/2020/03/11/H41ZEP6xsXmyzcq.png)

![截图](https://i.loli.net/2020/03/11/2JFYu7KlBAL1MWC.png)

![截图](https://i.loli.net/2020/03/11/PQpFOwo9VYKyGUu.png)

### 请提供核心代码片段链接
https://gist.github.com/edc599/f9b7ba271e1edfffce0aee5b3983f89f

### 描述问题
图片链接没问题，但是预览图加载不出来

**Comment by zgia** [comment]
请教一个问题，使用微信开发者工具，wepy框架，选择文件后，没有回调before-read、after-read方法。

`<van-uploader file-list="{{ fileList }}"
                    use-before-read
                    bind:before-read="beforeReadImage"
                    bind:after-read="afterReadImage"
                    bind:click-preview="clickPreviewImage"
                    bind:delete="deleteImage" />`

`beforeReadImage(event) {
      console.log('beforeReadImage', event)
    },

    afterReadImage(event) {
      console.log('afterReadImage', event)
    }`
请教您遇到这样的问题了吗？

**Comment by edc599** [comment]
> 请教一个问题，使用微信开发者工具，wepy框架，选择文件后，没有回调before-read、after-read方法。
> 
> `<van-uploader file-list="{{ fileList }}" use-before-read bind:before-read="beforeReadImage" bind:after-read="afterReadImage" bind:click-preview="clickPreviewImage" bind:delete="deleteImage" />`
> 
> ` beforeReadImage(event) { console.log('beforeReadImage', event) }`
> `afterReadImage(event) { console.log('afterReadImage', event) }`
> 请教您遇到这样的问题了吗？

我的after-read是没问题的

**Comment by Lindysen** [comment]
可以给fileList 里面的 每个item 加上 isImage: true，或者图片后缀变成小写的jpg..
