### ISSUE TITLE
[Bug Report] mpvue使用外部样式类覆盖tab样式问题

### ISSUE THREAD

**Issue by zxyxueyuan** [youzan/vant-weapp#2854]
### 设备
模拟器 真机

### VantWeapp 版本
1.0.7

### 基础库版本
2.10.3

### 如果是 UI 问题，截图链接（多图回车分隔）

![截图](https://i.loli.net/2020/03/13/AN2ef6iutEB3cF4.png)

![截图](https://i.loli.net/2020/03/13/l5i1wXHST4qjRhV.png)

### 请提供核心代码片段链接
https://gist.github.com/zxyxueyuan/60d2b3e15ad51cefbe965b38491bbf90

### 描述问题
感谢有赞

<van-tabs
    active="1"
    @change="onChange"
    tab-class="special-tab"
    tab-active-class="special-tab-active"
  >
    <van-icon slot="nav-right" name="search" custom-class="right-nav" @click="onClickNavRight" />
    <van-tab
      v-for="(item,index) in tabs4"
      :key="index"
      :title="'标签 '   item"
      :dot="index === 1"
      :info="index === 2 ? 99 : null"
    >
      <view class="content">{{ '内容'   item }}</view>
    </van-tab>
  </van-tabs>

1.0.7文档中，Tab 标签页下方含有外部样式类tab-active-class，我想改变文字的大小和文字的颜色
微信扫码体验时，Tab 下方是能看见样式是可以改变的，我下载了1.0.7源码发现了这段代码，移植到我的项目中
但是效果却没有出现，mpvue使用了less，详细的代码在链接中，想请教一下，出现这个问题的解决办法。

--tab-active-text-color 这个倒是可以改变颜色，我还想改变字体

麻烦了

**Comment by zxyxueyuan** [comment]
找到了解决办法

<style>
.tab-active {
  color: #6ac9c3 !important;
  font-size: 36rpx !important;
}
</style>

因为下面还有style lang="less" scoped，看着有点粗糙，有没有其他的解决办法呢

**Comment by rex-zsd** [comment]
如果是scope的问题的话，除了这个方法，可以看看mpvue支不支持`/deep/`语句。
