### ISSUE TITLE
[Bug Report]     Toast

### ISSUE THREAD

**Issue by wubaibin** [youzan/vant-weapp#2855]
### 设备
iphone xr & 大部分手机

### VantWeapp 版本
1.1.0-beta.2

### 基础库版本
1.0.7

### 请提供核心代码片段链接
https://youzan.github.io/vant-weapp/#/toast

### 描述问题
Toast.loading({ });Toast.clear();在小程序中配合使用，有时Toast.clear();会失效导致一直显示在加载(大概十次有一次会失效)

**Comment by rex-zsd** [comment]
使用的代码是怎么样的？是否存在时序问题呢？

**Comment by xiawenI** [comment]
出现了同样的问题，偶现；一个页面初始化时调用了多个接口，每个接口都写了
`Toast.loading({
        mask: true,
        message: '加载中...',
        duration: 0
      });`
并在每个接口回调成功之后`Toast.clear();`，在页面跳转的时候，接口请求完了，Toast 也没有消失；

**Comment by kingfront** [comment]
遇到了同样的问题

**Comment by rex-zsd** [comment]
可能是接口速度较快，`loading`与`clear`的调用时间非常接近，导致关闭失效。
可以试试在`wx.nextTick`或者`setTimeout`内调用`clear`试试看？

**Comment by yoyo837** [comment]
clear 能单独 clear 单个 Toast吗? 实例方法? 目前文档只看到静态方法

**Comment by yoyo837** [comment]
从源码找到了
