### ISSUE TITLE
示例源代码居然有这个<demo-block>

### ISSUE THREAD

**Issue by lj374055610** [youzan/vant-weapp#2857]
能不能全部放dist里面 或者直接就把样式封装在组件里面， 官网的展示的样式 好多都要这个

**Comment by rex-zsd** [comment]
这个是示例demo用的组件，不会放到dist里面哈。

**Comment by lj374055610** [comment]
现在问题是 你们的官网展示给我们的样式 我得用，比如van-action-sheet  官网展示的样式就可以，当我想用的时候我居然要用你那个demo-block  ，而且不只这个组件，好多组件想要你们官网那个效果都要引用这个demo-block ,

**Comment by rex-zsd** [comment]
demo-block并不影响组件样式，只是demo文档的排版而已。
