### ISSUE TITLE
Grid 宫格使用 use-slot 无效

### ISSUE THREAD

**Issue by 13615817501** [youzan/vant-weapp#2859]
![image](https://user-images.githubusercontent.com/23720587/76613998-2c205580-655a-11ea-8c6d-6bd84657e5b7.png)

![image](https://user-images.githubusercontent.com/23720587/76614062-46f2ca00-655a-11ea-9b20-1babdfa4e73d.png)

**Comment by rex-zsd** [comment]
从截图和代码来看，这个是生效了呀？

**Comment by 13615817501** [comment]
> 从截图和代码来看，这个是生效了呀？

没有生效，不加use-slotye 也是这个效果，加了也是这个效果，加了不应该是直接显示在方形里面么而不是外面

**Comment by rex-zsd** [comment]
从截图和代码来看，`use-slot`是有效的，否则不会显示中间的内容的。

**Comment by 13615817501** [comment]
> 之所以显示在外面，是因为你标签闭合有问题，`<van-grid-item use-slot />`仔细检查一下代码。

好的谢谢
