### ISSUE TITLE
ts开发小程序到底如何配置vant的tsconfig.json才不报错？

### ISSUE THREAD

**Issue by phoenixor** [youzan/vant-weapp#2861]
使用微信小程序开发工具生成的ts模板，目录结构如下：
![image](https://user-images.githubusercontent.com/6568115/76622750-0f414d80-656d-11ea-9df1-4ddc1805a8fa.png)
按照“快速上手”文档做了所有工作，在引用Notify组件时ts报错，但是组件使用正常，说明路径没问题。
![image](https://user-images.githubusercontent.com/6568115/76622832-457ecd00-656d-11ea-93af-6bdad92b237c.png)
tsconfig.json配置路径如下：
![image](https://user-images.githubusercontent.com/6568115/76622868-5596ac80-656d-11ea-875a-5a1d6951d649.png)
这是miniprogram目录结构，vant-weapp安装在这里
![image](https://user-images.githubusercontent.com/6568115/76622923-6d6e3080-656d-11ea-9afe-cab6cd59cac9.png)

到底怎么配置ts，全网查不到错误原因

**Comment by rex-zsd** [comment]
把`@vant/weapp/*`指向`node_modules/@vant/weapp/dist/*`即可。
如果没有生效的话，看一下目录结构是否是正确的，以及`tsconfig.json`配置文件是否生效？

**Comment by phoenixor** [comment]
> node_modules

我的node_modules不在根目录啊，你这是文档的示例，能不能看看我的目录结构再回复

**Comment by rex-zsd** [comment]
我的意思不是`node_modules`在根目录，而是指向`node_modules`的位置哈。

**Comment by phoenixor** [comment]
> node_modules

我知道是指向node_modules位置啊，你看我的目录结构，我配置的路径有问题吗？？？

**Comment by rex-zsd** [comment]
`baseUrl`和`paths`是`compilerOptions`内的属性，你把它写在了顶级，这样是有问题的。

**Comment by phoenixor** [comment]
> `baseUrl`和`paths`是`compilerOptions`内的属性，你把它写在了顶级，这样是有问题的。

还真是，这是小程序工具自动生成的ts模板啊！！
