### ISSUE TITLE
DatetimePicker在IOS下无法同时使用min-date和max-date

### ISSUE THREAD

**Issue by youngbo-china** [youzan/vant-weapp#2867]
1.0.7版本下的DatetimePicker
微信基础版本库2.8.1
ios:13.3.1

同时使用min-date和max-date只有1970年一项可选

**Comment by rex-zsd** [comment]
没看懂你的意思，可以贴下代码和截图示意一下？

**Comment by youngbo-china** [comment]
<van-datetime-picker
  type="datetime"
  min-date="1960-1-1"
  max-date="2030-1-1"
/>
![image](https://user-images.githubusercontent.com/3402405/76727077-f4015880-678d-11ea-8cb4-121fa319170a.png)
只有这一项了

**Comment by youngbo-china** [comment]
<van-datetime-picker
  type="datetime"
  min-date="1960-1-1"
  max-date="2030-1-1"
/>
在iphone上

**Comment by rex-zsd** [comment]
仔细看下文档，`min-date`和`max-date`是需要传入`number`类型的时间戳的哈。

**Comment by rex-zsd** [comment]
仔细看下文档，`min-date`和`max-date`是需要传入`number`类型的时间戳的哈。
