### ISSUE TITLE
弹出层与选择器的配合使用 警告VM20379:1 未找到 van-toast 节点，请确认 selector 及 context 是否正确

### ISSUE THREAD

**Issue by MARIOMARUI** [youzan/vant-weapp#2871]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater?repo=VantWeapp

**Comment by rex-zsd** [comment]
麻烦提供下核心代码哈，包括`js``wxml``json`这些

**Comment by rex-zsd** [comment]
再看下文档吧，推测是组件中使用没有传`context`的问题。
