### ISSUE TITLE
ActionSheet在真机上弹出速度太慢，至少有3s的延迟后才会出来，开发工具上无异常

### ISSUE THREAD

**Issue by xiansiguang** [youzan/vant-weapp#2875]

**Comment by rex-zsd** [comment]
是否使用了真机调试？真机调试是会比预览慢的，不是vant weapp的问题哈。

**Comment by xiansiguang** [comment]
嗯嗯，用预览看就正常了，第一次开发小程序，不好意思哈发自我的华为手机-------- 原始邮件 --------发件人： rex <notifications@github.com>日期： 2020年3月17日周二 晚上7:17收件人： youzan/vant-weapp <vant-weapp@noreply.github.com>抄送： xiansiguang <747163821@qq.com>, Author <author@noreply.github.com>主    题： Re: [youzan/vant-weapp] ActionSheet在真机上弹出速度太慢，至少有3s的延迟后才会出来，开发工具上无异常 (#2875)

是否使用了真机调试？真机调试是会比预览慢的，不是vant weapp的问题哈。

**Comment by rex-zsd** [comment]
小问题~
