### ISSUE TITLE
[Bug Report] button中数字的样式不正常

### ISSUE THREAD

**Issue by richchen** [youzan/vant-weapp#2877]
### 设备
iphone7

### VantWeapp 版本
1.0.6

### 基础库版本
2.6.6

### 如果是 UI 问题，截图链接（多图回车分隔）

![截图](https://i.loli.net/2020/03/17/uGDtMl5pc2NjodL.jpg)

### 请提供核心代码片段链接
https://gist.github.com/richchen/c7dd2e4a8872710c8fb96b8c888821af

### 描述问题
van-button中的数字样式会明显不正常（iphone7，iphone11都有这个问题，android手机未测试）；button中带数字的需求挺常见的，比如我们的需求中有些提交订单的按钮上会有价格，希望能尽快解决！

**Comment by rex-zsd** [comment]
图中的数字样式有什么不正常吗？

**Comment by richchen** [comment]
van button里是类似宋体的 正常button或者view中的都是类似雅黑的 明显的不一样 我们产品接受不了van button里的数字样式。。我也感觉van button里的数字样式怪怪的 在vant的其他组件里没有这种问题 麻烦让技术研究下。。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: rex <notifications@github.com&gt;
发送时间: 2020年3月17日 19:19
收件人: youzan/vant-weapp <vant-weapp@noreply.github.com&gt;
抄送: richchen <842289456@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[youzan/vant-weapp] [Bug Report] button中数字的样式不正常 (#2877)





 
图中的数字样式有什么不正常吗？

**Comment by rex-zsd** [comment]
![WechatIMG37](https://user-images.githubusercontent.com/8767877/76854771-af0f1c00-688a-11ea-9011-2755814e719c.jpeg)

![WechatIMG38](https://user-images.githubusercontent.com/8767877/76854886-df56ba80-688a-11ea-81a5-67f00f6ded81.jpeg)

测试了一下，把按钮字体调成跟默认button一样的`18px`，显示的效果跟原生button是一样的。

**Comment by rex-zsd** [comment]
应该不是vant weapp的问题，确认下是不是自提大小的关系，或者是不是有全局设置什么`font-family`之类的。
