### ISSUE TITLE
[Bug Report] 按钮中的数字样式问题

### ISSUE THREAD

**Issue by richchen** [youzan/vant-weapp#2881]
### 设备
iphone7

### VantWeapp 版本
1.0.6

### 基础库版本
2.6.6

### 如果是 UI 问题，截图链接（多图回车分隔）

![截图](https://i.loli.net/2020/03/19/HV2aWLFrDUS61dJ.jpg)

![截图](https://i.loli.net/2020/03/19/lU6jC5GFqPIu8gk.jpg)

### 请提供核心代码片段链接
https://gist.github.com/richchen/6b2074c8f3d1ceda6bc2d9b1b35406d3

### 描述问题
前两天提过这个问题，你们那边说没问题，但是你们给的结果是在安卓手机上测试的结果啊，我这个问题只在ios上有问题好像？

我已经找到原因，答案在第二张截图中，这应该是微信小程序的一个小bug，只要显示的指定button的lang属性，lang属性的值不等于zh_CN或zh_TW，那button中的数字样式在ios中都是有问题的。

因为van-button封装都是显示指定的lang值而且默认值是en，所以只要开发者没有指定van-button的lang值为zh_CN或zh_TW，那如果在van-button中使用数字，都是会有问题的。

**Comment by rex-zsd** [comment]
那应该是小程序的bug了，因为小程序的文档里lang的默认值就是'en'，所以van-button默认设置了'en'。
但是iOS上实际并不是，导致了这个问题吧。
https://developers.weixin.qq.com/miniprogram/dev/component/button.html

**Comment by rex-zsd** [comment]
![WechatIMG3](https://user-images.githubusercontent.com/8767877/77034741-aaab4600-69e5-11ea-98b2-d196c28d8da1.jpeg)
试了一下iPhone XS Max，也是没问题的

**Comment by rex-zsd** [comment]
vant weapp这边可以去除`lang`的默认值，兼容小程序的bug。

**Comment by richchen** [comment]
对的 就是这个意思 用户传入lang的时候再去给van-button设置lang属性




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"rex"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月19日(星期四) 中午1:31
收件人:&nbsp;"youzan/vant-weapp"<vant-weapp@noreply.github.com&gt;;
抄送:&nbsp;"陈建忠"<842289456@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [youzan/vant-weapp] [Bug Report] 按钮中的数字样式问题 (#2881)





 
vant weapp这边可以去除lang的默认值，兼容小程序的bug。

**Comment by richchen** [comment]
我看到你们去除了lang的默认值，但是实际上并没有移除lang这个属性，所以问题依然存在，只要设置了lang并且lang不是zh_CN或zh_TW就会有问题

可以考虑在open-type='getUserInfo'的情况下再设置lang；或者把lang默认设为'zh_CN'，在open-type='getUserInfo'的情况下再设置lang='en'


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"rex"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月19日(星期四) 中午1:31
收件人:&nbsp;"youzan/vant-weapp"<vant-weapp@noreply.github.com&gt;;
抄送:&nbsp;"陈建忠"<842289456@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [youzan/vant-weapp] [Bug Report] 按钮中的数字样式问题 (#2881)





 
vant weapp这边可以去除lang的默认值，兼容小程序的bug。
