### ISSUE TITLE
[Bug Report] popup弹出层里面写的东西 会出现模糊的情况

### ISSUE THREAD

**Issue by fangkyi03** [youzan/vant-weapp#2885]
### 设备
模拟器

### VantWeapp 版本
1.1.0-beta.2

### 基础库版本
2.10.3

### 请提供核心代码片段链接
http://a.com

### 描述问题
  <van-popup
        show={isShowJoinModal}
        custom-style={'border-radius:'   Taro.pxTransform(20)}
      >
        <View className={styles.joinModal}>
          <View style={{fontSize:Taro.pxTransform(30),color:'#666666'}}>
            我们为您选择加入的小区挑选了
            <Text style={{ fontSize: Taro.pxTransform(36), color:'#333333'}}>23</Text>
            个团长 听说，跟着靠谱的小区团长可知道更多新 鲜农产品上架消息，享受超值低价优惠~
          </View>
          <View className={styles.joinModalFoot}>
            <View className={styles.joinModalButton} onClick={this.onJoin}>去加入喜欢的团</View>
            <View style={{ fontSize: Taro.pxTransform(30), color:'#666666'}} onClick={this.onSee}>先不加入团</View>
          </View>
        </View>
      </van-popup>
里面出来的东西很模糊

![image](https://user-images.githubusercontent.com/30390014/77040345-b5b8a300-69f2-11ea-84a4-86325f54a44d.png)

**Comment by fangkyi03** [comment]
个人感觉是popup的阴影挡在上面了

**Comment by rex-zsd** [comment]
这个问题倒是第一次遇见，可以上传个代码片段看看不？
