### ISSUE TITLE
NavBar的fixed设置为true，直接把下面的内容挡住了

### ISSUE THREAD

**Issue by zszjszlk2** [youzan/vant-weapp#2887]
作为导航栏应该能有吸顶效果吧？能否增加？
![1](https://user-images.githubusercontent.com/46711557/77057244-a47d8f80-6a0e-11ea-9971-75c903e96c9f.png)

**Comment by rex-zsd** [comment]
fixed之后，是需要开发者自己给页面设定`padding-top`把内容顶下去的。

**Comment by rex-zsd** [comment]
这个应该没有问题吧……

**Comment by zszjszlk2** [comment]
> 这个应该没有问题吧……

岂不是要动态获取导航栏的高度，然后才能设定合适的padding。
我看colorui的导航栏是可以直接使用的，不是有个css样式叫做吸顶的吗，vant应该加一个吧……

**Comment by rex-zsd** [comment]
colorui的nav对应的是Tab，不是NavBar哈

**Comment by rex-zsd** [comment]
vant weapp可以给fixed状态的nav bar填充一个占位块，占住顶部的位置。

**Comment by zszjszlk2** [comment]
![微信图片_20200319213101](https://user-images.githubusercontent.com/46711557/77072832-43af8080-6a29-11ea-9525-815c9aee16b7.png)
还有这好像有个hover-class，我代码层面无法把它去除~~

**Comment by agoni1212** [comment]
@zszjszlk2 你是怎么把它顶上最上面的，我通过custom-class设置padding-top 无效

**Comment by zszjszlk2** [comment]
> @zszjszlk2 你是怎么把它顶上最上面的，我通过custom-class设置padding-top 无效

在他下面加多一个view来顶开，话说导航栏高度是怎么计算的，vant这里封装的不好啊，对面colorui的随拿随用。
但是我已经用了vant的不好改了。

**Comment by agoni1212** [comment]
可能的问题是在这里

`  created() {`
       `   const { statusBarHeight } = wx.getSystemInfoSync();`
       `   this.setData({ statusBarHeight });`
  `},`

这是官方说明：

created | Function | 否 | 组件生命周期函数-在组件实例刚刚被创建时执行，**注意此时不能调用 setData )**

**Comment by rex-zsd** [comment]
> 可能的问题是在这里
> 
> ` created() {`
> ` const { statusBarHeight } = wx.getSystemInfoSync();`
> ` this.setData({ statusBarHeight });`
> `},`
> 
> 这是官方说明：
> 
> created | Function | 否 | 组件生命周期函数-在组件实例刚刚被创建时执行，**注意此时不能调用 setData )**

vant weapp内部的`created`不对应小程序的`created`哈
