### ISSUE TITLE
[Bug Report] van-datetime-picker

### ISSUE THREAD

**Issue by pengxAlone** [youzan/vant-weapp#2888]
### 设备
开发者工具

### VantWeapp 版本
1.0.7

### 基础库版本
2.10.3

### 请提供核心代码片段链接
https://developers.weixin.qq.com/s/Fi8UqZmZ7hfj

### 描述问题
van-datetime-picker 组件value如果是在小程序page生命周期的函数里赋值，会直接卡死小程序，而且滑动选择日期特别困难。

**Comment by rex-zsd** [comment]
生命周期的问题造成datetime-picker一直在两个value之间来回触发事件

**Comment by OnlyYu1996** [comment]
加上一个定时器就可以了

https://developers.weixin.qq.com/s/cWX1aumW7bgT

**Comment by rex-zsd** [comment]
datetime-picker内部触发input事件是异步的
data中设置初始值，同时页面onLoad中设置新值时，会造成新旧值不断相互顶替。
这个问题组件内部无法解决，可以在onLoad设置值时用wx.nextTick套一下。
