### ISSUE TITLE
[Bug Report] Circle 环形进度条遮住了Tabbar和DatetimePicker组件

### ISSUE THREAD

**Issue by siminture** [youzan/vant-weapp#2889]
### 设备
iPhone

### VantWeapp 版本
1.1.0-beta.2

### 基础库版本
2.10.3

### 请提供核心代码片段链接
https://youzan.github.io/vant-weapp/#/circle
https://youzan.github.io/vant-weapp/#/datetime-picker

### 描述问题
放图实在麻烦：Circle 环形进度条的层级太高，遮住了Tabbar和DatetimePicker、DropdownMenu等组件，可能其它弹出类组件都会被遮住。

**Comment by rex-zsd** [comment]
circle实现使用了canvas，而canvas是原生组件，层级是不能被覆盖的。只能等待小程序官方支持同层渲染才能解决这个问题了。
相关文档可以看下https://developers.weixin.qq.com/miniprogram/dev/component/canvas.html

**Comment by rex-zsd** [comment]
看了一下2.9.0开始canvas支持了同层渲染，可以支持一下

**Comment by siminture** [comment]
恩恩，感谢。
