### ISSUE TITLE
[Bug Report] field中的input 无法铺满 导致可输入范围很小

### ISSUE THREAD

**Issue by fangkyi03** [youzan/vant-weapp#2891]
### 设备
all

### VantWeapp 版本
1.1.0-beta.2

### 基础库版本
2.10.3

### 请提供核心代码片段链接
http://a.com

### 描述问题
```
 <van-search
        background={'#f2f2f2'}
        placeholder="请输入搜索关键词"
        input-align="center"
        shape={'round'}
        use-action-slot={true}
        content-class={styles.input}
        field-class={styles.field}
        onChange={this.onChange}
        onSearch={this.onSearch}
      >
        <View
          slot="action"
          style={{ color: '#00BE39' }}
          onClick={this.onSearchDown}
        >
          搜索
        </View>
      </van-search>
```
这个时候 search中的input没有铺满整个search组件 只有很小的一个范围 这就导致 可输入范围很小

**Comment by Lindysen** [comment]
看不到核心代码，导致看不到你样式，无法排查问题

**Comment by fangkyi03** [comment]
![image](https://user-images.githubusercontent.com/30390014/77180648-34056a00-6b05-11ea-84e3-682a7c24f4bb.png)
input的点击范围只有这么点 右边空白处空间都是浪费的 我那个代码就只有那么点 没其他东西

**Comment by fangkyi03** [comment]
缺少一个判断 如果右边没有内容的时候 
![image](https://user-images.githubusercontent.com/30390014/77181512-6794c400-6b06-11ea-8c8a-29a70f5dbdf5.png)
你们的这边应该撑大 不然可点击范围就非常小

**Comment by rex-zsd** [comment]
> 缺少一个判断 如果右边没有内容的时候
> ![image](https://user-images.githubusercontent.com/30390014/77181512-6794c400-6b06-11ea-8c8a-29a70f5dbdf5.png)
> 你们的这边应该撑大 不然可点击范围就非常小

![image](https://user-images.githubusercontent.com/8767877/77218681-e7537a80-6b68-11ea-9ede-50396b91b843.png)
看了一下demo，input的宽度是占满的，应该没有这个问题。
还有从你的截图来看，vant weapp的代码是被改写过的吗？我们组件里没有给input套view，也没有`isShowInput`这个变量的，可以看看是不是改写造成的问题。

**Comment by fangkyi03** [comment]
嗯 好的 多谢
