### ISSUE TITLE
 Cannot find module '@vant/weapp/toast/toast'.

### ISSUE THREAD

**Issue by luyonglie** [youzan/vant-weapp#2893]
在typescrip 开发时，导入toast   import Toast from '@vant/weapp/toast/toast';  编译提示错误信息
 Cannot find module '@vant/weapp/toast/toast'.

**Comment by rex-zsd** [comment]
贴下代码和配置哈

**Comment by rex-zsd** [comment]
估计是tsconfig的`path`配置的问题，可以再调整一下试试看哈。
