### ISSUE TITLE
关于在微信开发中引用 dist 文件夹使用 Dialog 弹出框 的 Dialog.confirm 时，中间分割线位置偏移的问题

### ISSUE THREAD

**Issue by xuxiaowei-com-cn** [youzan/vant-weapp#2897]
微信项目中仅引用了 vant-weapp v1.1.0，使用 Dialog.confirm 时，中间分割线位置偏移，解决办法：
`
.van-dialog__button.van-hairline--right {
  width: 50%;
}
`

**Comment by Lindysen** [comment]
可以截图看下效果，我这边没复现

**Comment by Lindysen** [comment]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater?repo=VantWeapp
