### ISSUE TITLE
如何在原生微信小程序框架下使用Toast，已经试过但是失败。

### ISSUE THREAD

**Issue by zi1987zi** [youzan/vant-weapp#2900]
![image](https://user-images.githubusercontent.com/20487443/77254824-672f3100-6c9e-11ea-88eb-2fd008dc7ff0.png)
![image](https://user-images.githubusercontent.com/20487443/77254841-7f9f4b80-6c9e-11ea-989c-f3eef8a5e9e9.png)
![image](https://user-images.githubusercontent.com/20487443/77254908-d442c680-6c9e-11ea-82b0-911f663f3935.png)
![image](https://user-images.githubusercontent.com/20487443/77254920-e45aa600-6c9e-11ea-990e-0595c8122ca3.png)

**Comment by zi1987zi** [comment]
1.按照官方文档在页面json中已经添加van-toast引用，2.在wxml布局中也是用了<van-toast>3.在js中使用selectCompent方法引用van-toast得到一个对象，使用文档中fail或者success方法，报错。疑问：在原生微信小程序框架怎么使用这个组件，button啥的我已经使用成功了，这个带id的组件我怎么弄都用不了，接触小程序不久，望高手赐教怎么整，网上资料也少。谢谢。

**Comment by MeloGuo** [comment]
应该在 JS 文件中也引入 Vant 提供的 Toast 方法，不要自己 selectComponent。
`import Toast from 'path/to/@vant/weapp/toast/toast'`
这里官方文档写的也有问题，
![image](https://user-images.githubusercontent.com/22138516/77274166-4bed1180-6cf0-11ea-84b8-ae5f1a9ec5c4.png)

**Comment by rex-zsd** [comment]
> 1.按照官方文档在页面json中已经添加van-toast引用，2.在wxml布局中也是用了3.在js中使用selectCompent方法引用van-toast得到一个对象，使用文档中fail或者success方法，报错。疑问：在原生微信小程序框架怎么使用这个组件，button啥的我已经使用成功了，这个带id的组件我怎么弄都用不了，接触小程序不久，望高手赐教怎么整，网上资料也少。谢谢。

默认id是`van-toast`不是`vantoast`，也不是通过`selectComponent`来调用方法的。
不知道怎么使用的话可以直接复制文档示例的代码下来修改。

**Comment by rex-zsd** [comment]
> 应该在 JS 文件中也引入 Vant 提供的 Toast 方法，不要自己 selectComponent。
> `import Toast from 'path/to/@vant/weapp/toast/toast'`
> 这里官方文档写的也有问题，
> ![image](https://user-images.githubusercontent.com/22138516/77274166-4bed1180-6cf0-11ea-84b8-ae5f1a9ec5c4.png)

文档写的是没有问题的，`import Toast from 'path/to/@vant/weapp/toast/toast'`这种引入方式只在npm构建的情况下使用，如果不是npm构建的话需要加`dist`的。

**Comment by Dazhenga** [comment]
> > 应该在 JS 文件中也引入 Vant 提供的 Toast 方法，不要自己 selectComponent。
> > `import Toast from 'path/to/@vant/weapp/toast/toast'`
> > 这里官方文档写的也有问题，
> > ![image](https://user-images.githubusercontent.com/22138516/77274166-4bed1180-6cf0-11ea-84b8-ae5f1a9ec5c4.png)
> 
> 文档写的是没有问题的，`import Toast from 'path/to/@vant/weapp/toast/toast'`这种引入方式只在npm构建的情况下使用，如果不是npm构建的话需要加`dist`的。

感谢，刚解决了刚入门小程序开发的困惑
