### ISSUE TITLE
File not found

### ISSUE THREAD

**Issue by joychine** [youzan/vant-weapp#2901]
想用微信开发工具打开看下，发现报错。。file not found 
Error：
in file ：./dist/action-sheet/index.wxss
File not fount: ..\common\index.wxss
编译.wxss文件错误，错误信息如上可在控制台查看更详细信息

**Comment by rex-zsd** [comment]
还有其它信息么？比如操作步骤，`common\index.wxss`文件是否存在

**Comment by joychine** [comment]
我已经发现啥问题了，新版本的微信小程序工具，生成的代码没有dist目录

**Comment by rex-zsd** [comment]
好的哈

**Comment by joychine** [comment]
> 好的哈

不行还是有问题，我搞串了，还是那个问题，我就是按官方操作“
在开发者工具中预览
# 安装项目依赖
npm install

# 执行组件编译
npm run dev
打开微信开发者工具，把vant-weapp/example目录添加进去就可以预览示例了。 ”
example目录下有生成dist，然后当前node js版本v12.16.1
npm版本v6.13.4
微信开发者工具v1.02.1911180

**Comment by iT-lijun** [comment]
原因：是windows路径分割符 \\ 导致的问题

解决：在**vant-weapp/build/complier.js** 第36行 补刀 

            const relativePathWin = relativePath.replace(/\\/g, '/');
            contents = `@import '${relativePathWin}';${contents}`;

**Comment by gitxiongpan** [comment]
@iT-lijun  我尝试了你的solution还是不行.我试了替换或者是添加你的代码到vant-weapp/build/complier.js 还是会有报错

**Comment by gitxiongpan** [comment]
![image](https://user-images.githubusercontent.com/45360805/77851148-25b0ff80-7223-11ea-98e5-fc31f58312d5.png)

**Comment by gitxiongpan** [comment]
@iT-lijun  抱歉.原来是我没有完全用对你给的代码.
我替换的时候没有删除原来的 
`contents = `@import '${relativePath}';${contents}`;`
导致了带windows路径分割符 \ 的import仍然存在.
`          if (!file.path.includes('packages' + path.sep + 'common')) {
            const relativePath = path.relative(
              path.normalize(`${file.path}${path.sep}..`),
              baseCssPath
            );
            const relativePathWin = relativePath.replace(/\\/g, '/');
            contents = `@import '${relativePathWin}';${contents}`;
          }
          return contents;
`
按照上面的整段代码替换就好了
