### ISSUE TITLE
tab下scroll-view无法触发scroll-view自定义下拉刷新事件

### ISSUE THREAD

**Issue by peng20017** [youzan/vant-weapp#2902]
我知道scroll-view无法触发页面的下拉刷新，但是微信更新了 scroll-view的自定义下拉刷新事件，不放在tab下可以正常使用，在tab下下拉触发不了，我移除了部分样式，但问题还是没有解决，只有把内容放到了tab外部，然后用hidden 控制，才触发了scroll-view的自定义下拉刷新事件。

**Comment by Lindysen** [comment]
可以提供下核心代码

**Comment by jiaxin11** [comment]
可否有提供解决方案

**Comment by rex-zsd** [comment]
先提供下代码和截图，看下具体是什么问题吧？

**Comment by jiaxin11** [comment]
设备
开发者工具

VantWeapp 版本
1.1.0

基础库版本
2.10.3

请提供核心代码片段链接
https://developers.weixin.qq.com/s/SdhEyemT7ngr

描述问题
tab下scroll-view无法触发scroll-view自定义下拉刷新事件

**Comment by rex-zsd** [comment]
> 设备
> 开发者工具
> 
> VantWeapp 版本
> 1.1.0
> 
> 基础库版本
> 2.10.3
> 
> 请提供核心代码片段链接
> https://developers.weixin.qq.com/s/SdhEyemT7ngr
> 
> 描述问题
> tab下scroll-view无法触发scroll-view自定义下拉刷新事件

尝试了一下，手动控制scroll-view的显示可以触发事件，但是正常的确不会触发。
https://github.com/youzan/vant-weapp/blob/141996b35e8e66edc6b545542d32181f0e6faa5b/packages/tab/index.wxml#L5-L7
在组件里改了一下，去掉这里的`display`和`wx:if`也可以正常触发，推测是微信在初始化scroll-view的时候做了一些相关逻辑，而嵌套在slot内的时候无法正常初始化导致的。
```
<van-tab title="标签 1">
  默认交互动画：
  <scroll-view
    wx:if="{{ active === 0 }}"
    ....
```

**Comment by rex-zsd** [comment]
目前 vant weapp 内部应该解决不了这个问题，可以手动控制一下显隐藏，或者把内容放到van-tab外面

**Comment by LCBbest** [comment]
> 目前 vant weapp 内部应该解决不了这个问题，可以手动控制一下显隐藏，或者把内容放到van-tab外面

你好 
<scroll-view
wx:if="{{ active === 0 }}"
这样写我这还是不可以实现下拉刷新。只有去掉tab/index.wxml里面的内容才可以实现下拉刷新。还有 您说的放在tab外面，怎么实现呢。

**Comment by imleon** [comment]
如果把 scroll-view 拿到 van-tab 外面的话，像 swipeable 这些属性就没法实现了，有什么其他好的办法不
