### ISSUE TITLE
同一个组件用两个popup怎么配置

### ISSUE THREAD

**Issue by Jizihe88** [youzan/vant-weapp#2904]
同一个组件中，点击一个按钮是底部划出popup，点击另外一个按钮是普通弹出popup如何配置

**Comment by rex-zsd** [comment]
如果内容不一样的话，可以写两个`van-popup`分别控制
如果内容一样的话，可以用一个`van-popup`就好，动态设置一下`position`

**Comment by Jizihe88** [comment]
底部划出的好使，但是页面弹出的没有反应&nbsp; &nbsp;








------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"rex"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月24日(星期二) 中午11:18
收件人:&nbsp;"youzan/vant-weapp"<vant-weapp@noreply.github.com&gt;;
抄送:&nbsp;"小贺"<1085855915@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [youzan/vant-weapp] 同一个组件用两个popup怎么配置 (#2904)





 
如果内容不一样的话，可以写两个van-popup分别控制
 如果内容一样的话，可以用一个van-popup就好，动态设置一下position

**Comment by rex-zsd** [comment]
可以提供一下代码，看下是什么问题

**Comment by rex-zsd** [comment]
demo小程序是ok的，可以直接copy一下文档里的示例代码再修改。
