### ISSUE TITLE
[Bug Report] IndexBar内容为图片时 标题吸顶错位

### ISSUE THREAD

**Issue by chouchouguai** [youzan/vant-weapp#2907]
### 设备
微信开发者工具Stable v1.02.1911180

### VantWeapp 版本
1.0.2

### 基础库版本
 v1.02.1911180

### 如果是 UI 问题，截图链接（多图回车分隔）

![截图](https://sm.ms/image/2NgV7aWGUHkBCYO)

### 请提供核心代码片段链接
https://gitee.com/chouchouguai126/codes/6lt4cb3f0yx58hvr2pioe72

### 描述问题
滚动时标题错位

**Comment by rex-zsd** [comment]
因为IndexBar滚动吸顶依赖初始化的时候的rect计算，可以给image设置一下`height`，应该可以解决。
为了支持动态加载的内容，IndexBar需要在滚动时实时获取各个IndexAchor的rect，可能会造成滚动卡顿，所以应该不会支持哈，
