### ISSUE TITLE
Calendar 弹出时 默认选择日期的设置

### ISSUE THREAD

**Issue by hopeworker** [youzan/vant-weapp#2910]
### 这个功能解决了什么问题
当设置了 minDate和maxDate后，Canlendar组件弹出时，是从 minDate开始显示的。
如果日期范围设置得比较大的话，用户想定位到 特定日期 ，就需要滚动很久才能找到。

### 建议的API是什么样的
在初始化的时候，提供一个配置项 来配置 当前显示的日期。
目前有一个   default-date的配置项，不知道是否 就是用来实现这个功能的。但是好像没有生效。

**Comment by rex-zsd** [comment]
`default-date`是用来设置初始选中项的，可以用这个实现你的需求。
demo实测是有效的，没有生效的话可以看下文档，是不是使用姿势的问题。

**Comment by hopeworker** [comment]
真机测试确实有效，谢谢！

**Comment by JX-Zhuang** [comment]
我设置了default-date ，Canlendar组件弹出时，是从 minDate开始显示的。
