### ISSUE TITLE
你好开发组 好像api文档https出现问题了

### ISSUE THREAD

**Issue by majinfeng8520** [youzan/vant-weapp#2911]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater?repo=VantWeapp

**Comment by diyanshan** [comment]
https://youzan.github.io/vant-weapp  
无法访问到此网站

**Comment by zoubihai** [comment]
我这边也访问不了

**Comment by rex-zsd** [comment]
文档是托管在`github.io`上的，其实是在访问github的资源。
如果访问不了的话…………可能是被墙了

**Comment by rex-zsd** [comment]
可以挂下梯子再访问试试看哈

**Comment by zoubihai** [comment]
挂梯子可以访问，谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"rex"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月26日(星期四) 下午5:43
收件人:&nbsp;"youzan/vant-weapp"<vant-weapp@noreply.github.com&gt;;
抄送:&nbsp;"让脚步飞一会"<1208842419@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [youzan/vant-weapp] 你好开发组 好像api文档https出现问题了 (#2911)





 
可以挂下梯子再访问试试看哈

**Comment by chenjiahan** [comment]
参见 https://github.com/youzan/vant/issues/5920
