### ISSUE TITLE
现在官网访问不了了,能不能换个站点?

### ISSUE THREAD

**Issue by LadyChatterleyLover** [youzan/vant-weapp#2912]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater?repo=VantWeapp

**Comment by JakeLaoyu** [comment]
http://vant-contrib.gitee.io/vant-weapp/#/intro

**Comment by JakeLaoyu** [comment]
参见 #2678
