### ISSUE TITLE
[Bug Report] 小程序加入calendar组件后页面加载缓慢

### ISSUE THREAD

**Issue by lining0723** [youzan/vant-weapp#2913]
### 设备
iphone X 版本13.4

### VantWeapp 版本
1.1.0

### 基础库版本
2.10.3

### 请提供核心代码片段链接
https://developers.weixin.qq.com/s/ajLpS9mQ7Hgw

### 描述问题
加入calendar组件后真机页面加载缓慢，注释之后则加载速度正常，为保证用户体验只能在页面加载的时候设置了wx：if隐藏，1s后才开始加载calendar组件。

**Comment by rex-zsd** [comment]
真机调试是会慢很多的，是微信开发者工具的问题，预览或者发布后不会这么慢的。
