### ISSUE TITLE
[Feature Request] upload增加进度条

### ISSUE THREAD

**Issue by Satlantisy** [youzan/vant-weapp#2915]
### 这个功能解决了什么问题
多图上传或者视频上传增加进度条显示比较人性化，特别是文件比较大时。

### 建议的API是什么样的
希望能集成在upload组件内，针对单个图片分别显示上传进度，增加环形或者条形进度显示。

**Comment by rex-zsd** [comment]
后面会新增对上传状态文案显示的支持。
但是具体的上传进度还是需要开发者自己计算，因为上传文件这部分逻辑是不在组件内的。

**Comment by Satlantisy** [comment]
> 后面会新增对上传状态文案显示的支持。
> 但是具体的上传进度还是需要开发者自己计算，因为上传文件这部分逻辑是不在组件内的。

谢谢！希望能尽快支持 ：）
