### ISSUE TITLE
[Bug Report] uploader组件无法触发afterRead

### ISSUE THREAD

**Issue by dd01wangzhenzhen** [youzan/vant-weapp#2916]
### 设备
win小程序开发工具

### VantWeapp 版本
1.1.0

### 基础库版本
2.10

### 描述问题
uploader组件无法触发afterRead

模板文件代码
<van-uploader file-list="{{ fileList }}" bind:after-read="afterRead" />

js代码
Page({
  data: {
    fileList: []
  },
  afterRead(event) {
    const { file } = event.detail;
    // 当设置 mutiple 为 true 时, file 为数组格式，否则为对象格式
    wx.uploadFile({
      url: 'https://example.weixin.qq.com/upload', // 仅为示例，非真实的接口地址
      filePath: file.path,
      name: 'file',
      formData: { user: 'test' },
      success(res) {
        // 上传完成需要更新 fileList
        const { fileList = [] } = this.data;
        fileList.push({ ...file, url: res.data });
        this.setData({ fileList });
      }
    });
  }
});

**Comment by dingling001** [comment]
查看源码之后 发现 在134行的 判断文件大小时 方法下面 return之后的代码没有运行 删除后 好了

**Comment by shellus** [comment]
我也是类似的问题
但这表明了一个问题，那就是在mp-vue中，组件内的异常不会显示在控制台。

**Comment by dd01wangzhenzhen** [comment]
我close这个issue的原因是我在真机上运行是可以了，未深究原因
