### ISSUE TITLE
为什么icon图标引入进去没显示了

### ISSUE THREAD

**Issue by zoukkk** [youzan/vant-weapp#2917]
### 设备
小程序

### VantWeapp 版本
1.1.0

### 基础库版本
2.10.3

### 如果是 UI 问题，截图链接（多图回车分隔）

![截图](https://sm.ms/image/Dl5J6ew7zS2HyNs)

![截图](https://sm.ms/image/HPvfmZJLAuFzhlk)

### 请提供核心代码片段链接
https://github.com/zoukkk/iconbug

### 描述问题
引入vant tabbar组件之后  三列里面有搜索icon会显示 其他不会显示  另外的也是一样

**Comment by rex-zsd** [comment]
https://github.com/zoukkk/iconbug/blob/bb6939971b4bba9e8cf60fc0e8442d591c15a5d3/pages/index/index.json#L2-L5
因为根本没有引入icon组件，自然不会显示。

**Comment by zoukkk** [comment]
我使用的icon配置的tabbar 为什么不会显示呢
