### ISSUE TITLE
[Bug Report] V1.1.0中感觉transition组件无法使用

### ISSUE THREAD

**Issue by fps2tao** [youzan/vant-weapp#2919]
![20200329121947.png](https://i.loli.net/2020/03/29/1tlXTyD6Vo97bgp.png)
![20200329121820.png](https://i.loli.net/2020/03/29/E6INQBOWYJFnfx8.png)

**Comment by rex-zsd** [comment]
可以上传一下代码片段看一下

**Comment by rex-zsd** [comment]
demo小程序没有问题，应该还是使用姿势的问题。
参考组件文档调整一下代码试试吧。

**Comment by fps2tao** [comment]
好的好的,谢谢解答,我这边仔细看下文档!!
