### ISSUE TITLE
count-down 希望增加 传延迟时间的功能 比如 我在订单列表 想要每分钟刷新一次 在订单详情 就是每秒刷新一次

### ISSUE THREAD

**Issue by fangkyi03** [youzan/vant-weapp#2921]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater?repo=VantWeapp

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
