### ISSUE TITLE
建议对 tab 文档进行补充

### ISSUE THREAD

**Issue by jinzhanye** [youzan/vant-weapp#2922]
https://youzan.github.io/vant-weapp/#/tab#tong-guo-ming-cheng-pi-pei

文档有一节是这样的

```
### 通过名称匹配
在标签指定 `name` 属性的情况下，`active` 的值为当前标签的 `name`，默认启用第一个标签
```

但并没有说明如果指定了 name 属性就不能使用 index 当作 `active`，实际上情况是如果指定了 name 属性如果使用 index 当作 `active`，指定会失效，不会出现高亮 tab。建议对文档进行补充

**Comment by gromit1sm** [comment]
van-tabs 里有个`offsetTop`属性，文档里一直没标出来，我就在这里也一起说了.
```
  offsetTop: {
            type: Number,
            value: 0
        },
```

**Comment by chenjiahan** [comment]
好滴👌
