### ISSUE TITLE
微信小程序使用下拉菜单DropdownMenu组件后点击后下拉会很慢才显示

### ISSUE THREAD

**Issue by ZhangYun12** [youzan/vant-weapp#2925]

**Comment by Lindysen** [comment]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater?repo=VantWeapp

**Comment by rex-zsd** [comment]
如果是真机调试，响应慢正常现象，不是代码原因。
