### ISSUE TITLE
[Bug Report] 在wepy/cli@2.0.0-alpha.25里面用1.1.0版本出现 Uncaught TypeError: Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by cielu** [youzan/vant-weapp#2928]
### 设备
微信开发者工具 mac 上

### VantWeapp 版本
1.1.0

### 基础库版本
all

### 如果是 UI 问题，截图链接（多图回车分隔）

![image.png](https://i.loli.net/2020/03/31/91nQNra5vOYpxuM.png)

### 请提供核心代码片段链接
https://github.com/youzan/vant-weapp/blob/dev/dist/common/component.js

### 描述问题
在1.0.5的时候还没有这个问题，更新到1.1.0就出现这问题了。。。

Uncaught TypeError: Cannot read property 'name' of undefined

**Comment by cielu** [comment]
1.0.7也有这问题，应该是更新 component.js 代码后出现的，麻烦处理一下

**Comment by cielu** [comment]
另外，van-action-sheet 在弹出来之后，我在每个地方点击都会触发 close 事件，不晓得什么情况

**Comment by rex-zsd** [comment]
上传一下代码片段看一下吧

**Comment by cielu** [comment]
@rex-zsd  好像不是代码片段的问题啊，就是升级到1.1.0 就出现 name undefined 了，1.0.5没这问题，我看你们的源码，component.js 都改变了

**Comment by rex-zsd** [comment]
https://developers.weixin.qq.com/s/A0A1shmI7vgs
尝试了一下，完全没有问题的
如果你看源码看出是什么问题的话欢迎反馈哈。
