### ISSUE TITLE
[Feature Request] dropdown-item 的 Option 结构可自定义

### ISSUE THREAD

**Issue by agoni1212** [youzan/vant-weapp#2930]
### 这个功能解决了什么问题
dropdown-item 的 Option 结构目前是固定的，希望可以指定option 对象对应的属性名

### 建议的API是什么样的
text-key: text对应的数据属性
value-key: value对应的数据属性
icon-key:  icon对应的数据属性

**Comment by rex-zsd** [comment]
这个应该不会支持，开发者自己map一下字段名就可以
