### ISSUE TITLE
[Bug Report] van-calendar的默认日期格式？

### ISSUE THREAD

**Issue by gromit1sm** [youzan/vant-weapp#2931]
### 设备
*

### VantWeapp 版本
1.1.0

### 基础库版本
*

### 如果是 UI 问题，截图链接（多图回车分隔）

![截图](https://i.loli.net/2020/03/31/v2TNI9j7ybeosuW.png)

### 请提供核心代码片段链接
https://youzan.github.io/vant-weapp/#/calendar

### 描述问题
请问`van-calendar` `type=range`的默认日期`default-date`是什么格式？传了几个都不对

**Comment by rex-zsd** [comment]
看一下[组件文档](https://youzan.github.io/vant-weapp/#/calendar#api)，`default-date`接受的的是`number`类型的时间戳。

**Comment by gromit1sm** [comment]
> 看一下[组件文档](https://youzan.github.io/vant-weapp/#/calendar#api)，`default-date`接受的的是`number`类型的时间戳。

![](https://i.loli.net/2020/04/01/3kVjAWJ92LHZPvs.png) 是这样吗

**Comment by gromit1sm** [comment]
> 看一下[组件文档](https://youzan.github.io/vant-weapp/#/calendar#api)，`default-date`接受的的是`number`类型的时间戳。

找到原因了,设置的默认如果小于当前日期,那么必须设置`min-date`,而且`min-date` 必须小于设置的默认日期的`start-date`

**Comment by JoshuaFeng5** [comment]
在react 版本里面 ，怎么又变成了， string 模式， string 又是什么格式太奇怪了
