### ISSUE TITLE
DropdownMenu 下拉菜单与Field 输入框placeholder冲突，UI显示不友好

### ISSUE THREAD

**Issue by HRCONNECT** [youzan/vant-weapp#2932]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater?repo=VantWeapp

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
