### ISSUE TITLE
van-sidebar和van-sidebar-item 在苹果手机的IOS系统下无法显示，但安卓手机又是正常的，为什么？

### ISSUE THREAD

**Issue by nja2101851** [youzan/vant-weapp#2933]
<van-tab title="点餐" >          
          <van-sticky>
            <scroll-view scroll-y class="type-scroll">
              <van-sidebar active-key="{{ typeActiveKey }}" bind:change="typeChange">            
                <block wx:for="{{ typeList }}" wx:key="index">
                  <van-sidebar-item title="{{item.typeName}}" dot="{{item.dot}}"/>
                </block>
              </van-sidebar>
            </scroll-view>            
            <scroll-view scroll-y class="menu-scroll">   
              <view class="space-10"></view>           
              <block wx:for="{{orderItemList}}" wx:key="index" wx:if="{{item.typeId==typeShowId}}">                
                <view class="item-card">                 
                  <view class="card-img">
                    <image src="{{baseUrl}}{{item.imgUrl}}"></image>                    
                  </view>
                  <view class="card-right">
                    <view class="right-top">
                      {{item.itemName}}
                    </view>
                    <view class="right-mid">{{item.notices}}</view>
                    <view class="right-bot">
                      <view class="item-price">
                        <text>￥{{item.price}}</text>
                      </view>
                      <view class="item-num">
                        <van-stepper value="{{ item.num }}" min="0" max="99" disable-input bind:change="itemNumChange" data-id="{{item.itemId}}" />
                      </view>
                    </view>
                  </view>                  
                </view>
                <view class="space-10"></view>
              </block>
            </scroll-view> 
          </van-sticky>             
        </van-tab>

**Comment by rex-zsd** [comment]
![image](https://user-images.githubusercontent.com/8767877/78103086-88221f80-741e-11ea-8c71-b035fcc13a80.png)
在iPhoneXsMax上查看demo小程序是没问题的。
应该还是引用或者使用姿势原因造成的，再检查一下吧。
