### ISSUE TITLE
需求：日历组件官方可以加上今天的class类名。方便改今天的状态样式

### ISSUE THREAD

**Issue by lukaijin** [youzan/vant-weapp#2934]

**Comment by rex-zsd** [comment]
为了维护成本考虑，暂时不会给日历组件增加外部样式类。
可以参考一下[文档](https://youzan.github.io/vant-weapp/#/custom-style#jie-chu-yang-shi-ge-chi)，使用解除样式隔离或CSS变量的方式来覆盖组件样式。
