### ISSUE TITLE
ts中使用Dialog编译失败,error TS2722: Cannot invoke an object which is possibly 'undefined'.

### ISSUE THREAD

**Issue by YuxingXie** [youzan/vant-weapp#2937]
Cannot invoke an object which is possibly 'undefined'.

how to resolve it?

**Comment by rex-zsd** [comment]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater?repo=VantWeapp
