### ISSUE TITLE
[Bug Report] 提交表单的时候亲测部分数据丢失

### ISSUE THREAD

**Issue by yht520** [youzan/vant-weapp#2942]
### 设备
华为p9

### VantWeapp 版本
1.0.0-beta.4

### 基础库版本
2.10.4

### 请提供核心代码片段链接
https://developers.weixin.qq.com/s/rQ8Jbim870g7

### 描述问题
手写输入的时候，输入完毕，点击手写框上方结束手写，然后blur会触发，change不会触发，点击submit按钮提交，change的数据和submit的数据都少了后面手写输入的字，blur是正常的。联系我qq1822789526

**Comment by yht520** [comment]
![6E78A127-A256-4E4F-93E1-4132BC58D191](https://user-images.githubusercontent.com/20833627/78160503-a287e780-7476-11ea-8d9f-54682e5719a2.png)

**Comment by Lindysen** [comment]
http://vant-contrib.gitee.io/vant-weapp/#/field 文档中有提到手写输入的问题

**Comment by Lindysen** [comment]
这是微信小程序的 input 组件本身的问题，如果需要兼容手写输入法的场景，可以在 blur 事件中取到输入的值。相关的讨论可以查看微信开放社区
