### ISSUE TITLE
[Bug Report] popup在swipe-cell中使用时的样式问题

### ISSUE THREAD

**Issue by wjw99830** [youzan/vant-weapp#2943]
### 设备
小程序模拟器、iPhone X

### VantWeapp 版本
1.1.0

### 基础库版本
2.8.1

### 如果是 UI 问题，截图链接（多图回车分隔）

![截图1](https://i.loli.net/2020/04/02/vBblhSX46uxKjJD.png)

![截图2](https://i.loli.net/2020/04/02/kv4c71zPSgj5bMe.png)

### 请提供核心代码片段链接
https://gitee.com/pigwang/codes/46s7953iflwrxeap2zj8t59

### 描述问题
在cell中使用popup不会有问题，但是在swipe-cell中使用popup无法正常显示popup的预期样式，popup没有根据屏幕来定位，而是根据swipe-cell来定位

**Comment by rex-zsd** [comment]
swipe-cell是有用到`transform`的，会对绝对定位造成影响。
可以把popup移到swipe-cell外面使用哈。
