### ISSUE TITLE
在使用van-grid的时候，发现van-grid-item 没有 内联样式, 导致内容无法显示

### ISSUE THREAD

**Issue by xiaojinping** [youzan/vant-weapp#2947]
在使用van-grid的时候，发现van-grid-item 没有 内联样式, 导致内容无法显示
具体见附图 ，
重现链接
http://spa.niuwa360.com/#/feeds?type=hot

![微信图片_20200402162815](https://user-images.githubusercontent.com/29969183/78227046-40bf9000-74ff-11ea-943b-72b5f59c9f00.png)

图片上传之后，不知道能不能打开，
我附上线上的附图地址。
http://yhwh1.oss-cn-shanghai.aliyuncs.com/spa_ihv5imrdhr.png

**Comment by rex-zsd** [comment]
这个是vant不是vant weapp吧。
issue指路 https://github.com/youzan/vant/issues
