### ISSUE TITLE
Popup 请增加一个click-icon事件

### ISSUE THREAD

**Issue by demonclan** [youzan/vant-weapp#2948]
当触发【click-overlay】事件时会同时触发【close】事件，这导致我无法正常处理我的业务逻辑，如下图
<img width="332" alt="批注 2020-04-02 180434" src="https://user-images.githubusercontent.com/6886218/78236555-ba11af80-750c-11ea-98f9-44213b0a1001.png">

点击该图标后需要弹出另外一个Popup 并隐藏自身，因此需要监听【close-icon】的触发事件，查阅官方文档并未发现有可监听的方式，是否有其他方式可以解决该需求？

**Comment by rex-zsd** [comment]
可以隐藏掉popup本身的关闭图标，顶部栏完全自定义就可以了。
我们不想给popup提供太多内容上的功能，尽量只聚焦弹出的功能哈。

**Comment by demonclan** [comment]
> 可以隐藏掉popup本身的关闭图标，顶部栏完全自定义就可以了。
> 我们不想给popup提供太多内容上的功能，尽量只聚焦弹出的功能哈。

好的，谢谢您。我自行通过别的方式处理！
