### ISSUE TITLE
[Bug Report] Calendar日历显示错误Cannot read property '0' of null

### ISSUE THREAD

**Issue by linliyuan** [youzan/vant-weapp#2949]
截图如下：
![image](https://user-images.githubusercontent.com/37769385/78272000-81d79480-753f-11ea-8456-f1239ff2f040.png)
前提：已经是用nmp引入过的，使用过cell等其他的组件都没有问题，就只有这个Calendar出了问题，劳烦看看了！
只是简单的按文档那样子引入了  选择日期区间  的例子：
js代码
`Page({
  data: {
    date: '',
    show: false
  },

  onShow() {
    this.setData({ show: true });
  },
  onClose() {
    this.setData({ show: false });
  },
  formatDate(date) {
    date = new Date(date);
    return `${date.getMonth() + 1}/${date.getDate()}`;
  },
  onConfirm(date) {
    const [start, end] = date;
    this.setData({
      show: false,
      date: `${this.formatDate(start)} - ${this.formatDate(end)}`
    });
  }
});`

wxml：
`<van-cell title="选择日期区间" value="{{ date }}" bind:click="onShow" />
<van-calendar
        show="{{ show }}"
        type="range"
        bind:close="onClose"
        bind:confirm="onConfirm"
/>`

json：
`{
  "usingComponents": {
    "van-calendar": "@vant/weapp/calendar/index",
    "van-cell": "@vant/weapp/cell/index",
    "van-cell-group": "@vant/weapp/cell-group/index"
  }
}`

**Comment by rex-zsd** [comment]
看了一下是初始化的时候报错，不影响功能使用，下版本将会修复
