### ISSUE TITLE
[Bug Report] van-button 回调参数不携带

### ISSUE THREAD

**Issue by calfelephant** [youzan/vant-weapp#2953]
### 设备
微信开发者工具

### VantWeapp 版本
1.1.0

### 基础库版本
1.1.0

### 请提供核心代码片段链接
https://gitee.com/chenshiwen0831/test.git

### 描述问题
van-button  的  open-type为share时，data-xx 的参数无法携带到 onShareAppMessage  的 target中

**Comment by rex-zsd** [comment]
#2483

**Comment by rex-zsd** [comment]
可以关注下这个issue
