### ISSUE TITLE
[Bug Report] 日期选择value值失效

### ISSUE THREAD

**Issue by imdwpeng** [youzan/vant-weapp#2955]
### 设备
android

### VantWeapp 版本
1.1.0

### 基础库版本
1.1.0

### 如果是 UI 问题，截图链接（多图回车分隔）

![截图](https://i.loli.net/2020/04/03/y2GQeZhP1ncBFIO.png)

### 请提供核心代码片段链接
https://i.loli.net/2020/04/03/gcCHn5vl24VLPpx.png

### 描述问题
希望默认显示选中项，比如我此时选中2020年2月1日，希望能够传value进去直接选中此日期

**Comment by imdwpeng** [comment]
https://sm.ms/image/y2GQeZhP1ncBFIO

**Comment by imdwpeng** [comment]
效果图 https://sm.ms/image/y2GQeZhP1ncBFIO

**Comment by MeetzhDing** [comment]
遇到了类似的问题，当使用value="{{object.time}}"格式时，触发了innerValue和value不一致的问题。
object中的time值是在onload时动态设置的，尝试使用固定的值时没有发现此问题。
