### ISSUE TITLE
[Bug Report] IndexBar 在Custom Nav 情况下，点击右边的anchor时，定位不准确

### ISSUE THREAD

**Issue by agoni1212** [youzan/vant-weapp#2956]
### 设备
Android

### VantWeapp 版本
1.1.0

### 基础库版本
2.10.3

### 请提供核心代码片段链接
https://youzan.github.io/vant-weapp/#/index-bar

### 描述问题
IndexBar 在Custom Nav 情况下，点击右边的anchor时，定位不准确
在pagescorll 事件中，可以通过set scrollTop 的值 加上 navHeight 的定位
但在点击右边anchor时，有定位上移的问题，就是差了navHeight的高度

**Comment by rex-zsd** [comment]
开启custom nav时可以自行设置`sticky-offset-top`属性为navHeight的高度哈。
