### ISSUE TITLE
VANT组件中所有带有“-”的$emit事件在mpvue中都不会执行解决方法！ 比如click-overlay、click-item、click-nav

### ISSUE THREAD

**Issue by AK47-dadada** [youzan/vant-weapp#2961]
解决方案就是：去除 “-”
this.$emit('clicknav', { index: index });
@:clicknav="onClickNav"
望知悉

**Comment by rex-zsd** [comment]
mpvue一直都有的bug，可以自行修改下载下来的vant weapp的代码哈
