### ISSUE TITLE
Calendar Confirm Botton 无法设置居中

### ISSUE THREAD

**Issue by Near-Tam** [youzan/vant-weapp#2962]
如题，日历的确认按钮放在最左侧了。请问是否有属性可以设置居中
相关代码
<van-cell title="选择日期" value="{{ date }}" bind:click="onDisplay"/>
  <van-calendar color="rgb(255, 84, 18)" show="{{ show }}" bind:close="onClose" bind:confirm="onConfirm"/>

![image](https://user-images.githubusercontent.com/23352749/78558819-d764b780-7845-11ea-878a-91ded5a3f93b.png)

**Comment by rex-zsd** [comment]
估计是app.json中`style:v2`未去除

**Comment by Near-Tam** [comment]
好的，谢谢，已解决

**Comment by VenpleD** [comment]
咋解决的呀？
