### ISSUE TITLE
小程序这个问题怎么解决

### ISSUE THREAD

**Issue by Awxm** [youzan/vant-weapp#2964]
VM4211:1 Failed to load font https://img.yzcdn.cn/vant/vant-icon-d3825a.woff2
net::ERR_CACHE_MISS

**Comment by Awxm** [comment]
这个问题困扰很久了 作者帮帮忙

**Comment by arlindar1030** [comment]
同样的问题，卡在这

**Comment by rex-zsd** [comment]
![image](https://user-images.githubusercontent.com/8767877/78648885-392d2c00-78ef-11ea-9bf7-82f147cbe59e.png)
文档里已经有说明了哈
