### ISSUE TITLE
[Bug Report] tab组件在真机上向后切换的时候会有闪烁

### ISSUE THREAD

**Issue by JXlinger** [youzan/vant-weapp#2967]
### 设备
手机 真机

### VantWeapp 版本
1.2.0

### 基础库版本
2.10.3

### 请提供核心代码片段链接
https://youzan.github.io/vant-weapp/#/tab

### 描述问题
tab组件在真机上向后切换的时候会有闪烁，你们官方演示也一样闪烁，能不能解决一下

**Comment by zxl0108** [comment]
这个我也遇到了

**Comment by JXlinger** [comment]
> 这个我也遇到了

**Comment by JXlinger** [comment]
> 这个我也遇到了

关键是他们官方示例也这样，而且也没人管这个，也没人回复

**Comment by zxl0108** [comment]
你这边目前怎么解决的呢?我试了下苹果好像就没问题

**Comment by cqzongjian** [comment]
我也遇到了，苹果上也是有问题等
