### ISSUE TITLE
[Bug Report] DropdownItem Events  的事件是怎么绑定的，比如说open 

### ISSUE THREAD

**Issue by modalone** [youzan/vant-weapp#2968]
### 设备
iPhone x

### VantWeapp 版本
1.2.0

### 基础库版本
1.2.0

### 请提供核心代码片段链接
http://115.236.161.138/frontend/wz-logistics-miniapp.git

### 描述问题
<van-dropdown-item id="" title="{{checkedVEHICLETYPETitle}}" open='openDropItem'> open事件无法触发，bind:open 同样也无法触发，请指教，谢谢

**Comment by rex-zsd** [comment]
贴下代码吧

**Comment by modalone** [comment]
<van-cell title="{{publishType=='ZX'?'车型(可多选)':'车型'}}"  arrow-direction="down" class='gongxutype mark'>
      <view slot="">
        <van-dropdown-menu active-color='#00D1AC' open='openDropItem' >
          <van-dropdown-item id="" title="{{checkedVEHICLETYPETitle}}" bind:open='openDropItem' disabled="{{publishType == 'WH'||publishType == 'LL'||publishType == 'JK'}}">
            <van-checkbox-group value="{{ checkedVEHICLETYPE }}" catch:change="changeUnion"  class="tag" data-item='checkedVEHICLETYPE'>
              <van-checkbox shape="square" icon-size='30rpx' checked-color="#00D1AC" name="{{item.key}}" wx:for="{{VEHICLETYPE}}" wx:key="index">{{item.value}}</van-checkbox>
            </van-checkbox-group>
          </van-dropdown-item>
        </van-dropdown-menu>
      </view>
    </van-cell>
像这样，嵌套在van-cell里面，open不能触发

**Comment by modalone** [comment]
> <van-cell title="{{publishType=='ZX'?'车型(可多选)':'车型'}}"  arrow-direction="down" class='gongxutype mark'>
      <view slot="">
        <van-dropdown-menu active-color='#00D1AC' open='openDropItem' >
          <van-dropdown-item id="" title="{{checkedVEHICLETYPETitle}}" bind:open='openDropItem' disabled="{{publishType == 'WH'||publishType == 'LL'||publishType == 'JK'}}">
            <van-checkbox-group value="{{ checkedVEHICLETYPE }}" catch:change="changeUnion"  class="tag" data-item='checkedVEHICLETYPE'>
              <van-checkbox shape="square" icon-size='30rpx' checked-color="#00D1AC" name="{{item.key}}" wx:for="{{VEHICLETYPE}}" wx:key="index">{{item.value}}</van-checkbox>
            </van-checkbox-group>
          </van-dropdown-item>
        </van-dropdown-menu>
      </view>
    </van-cell>

`像这样，嵌套在van-cell里面，open不能触发``

**Comment by rex-zsd** [comment]
事件是绑定在dropdown-item上的
```
<van-dropdown-item 
  bind:open="onOpen" 
  value="{{ value }}" 
  options="{{ option }}" 
/>
```

example测试可以触发，可以看下是否是JS侧写的有问题

**Comment by modalone** [comment]
这个属于自定义内容了，外层套了van-cell ，所以我怀疑是不是嵌套影响了事件绑定，像上文说的，我最开始也是绑定在dropdown-item上的，但是确实没有反应，

**Comment by Lth1234567** [comment]
直接绑定在dropdown-item 也没触发呀 请问这个怎么解决呀
