### ISSUE TITLE
使用ts提示不具有任何构造签名或调用签名

### ISSUE THREAD

**Issue by joesdu** [youzan/vant-weapp#2970]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater?repo=VantWeapp
使用ts提示不具有任何构造签名或调用签名
看了下所有的index.d.ts全是导出空对象.建议改善一下.

**Comment by rex-zsd** [comment]
vant weapp 提供的方法如`Toast` `Dialog`有提供定义
组件不会提供定义哈

**Comment by joesdu** [comment]
> vant weapp 提供的方法如`Toast` `Dialog`有提供定义
> 组件不会提供定义哈

建议提供完整的ts的支持

**Comment by joesdu** [comment]
> vant weapp 提供的方法如`Toast` `Dialog`有提供定义
> 组件不会提供定义哈

用微信原生的开发方式,不给定义倒是没啥,但是我用React在开发,😂没有定义就一直会提示异常,不过倒是不影响使用.
