### ISSUE TITLE
[Bug Report] 使用van-transition时，进入页面时，不显示数据；切换tab后，可正常显示

### ISSUE THREAD

**Issue by LittleWhiteMouse9527** [youzan/vant-weapp#2971]
### 设备
iphone 7 plus

### VantWeapp 版本
1.2.0

### 基础库版本
2.9.5

### 如果是 UI 问题，截图链接（多图回车分隔）

![截图](https://sm.ms/image/ZLo3wEQp9Vmdg4N)

### 请提供核心代码片段链接
https://gitee.com/bestob/codes/grt719wcoa648jk0ylhxe77

### 描述问题
我想在一个列表上使用动画，于是加了van-transition，点击tab可以切换列表。测试发现，首次进入界面时，列表被隐藏了，无法显示，切换tab没有这个问题。

**Comment by LittleWhiteMouse9527** [comment]
[https://sm.ms/image/ZLo3wEQp9Vmdg4N](url)

**Comment by rex-zsd** [comment]
代码和图片都访问不了，补一下吧~
