### ISSUE TITLE
calendar日历组件点击确认报错如下图所示，好像是组件封装的问题？

### ISSUE THREAD

**Issue by godsan1** [youzan/vant-weapp#2972]
你好开发者，我在使用日历组建的时候，点击确认，结果报了以下错误：
r[Symbol.iterator] is not a function; [Component] Event Listener Error @miniprogram_tools/dist/calendar/index#(anonymous)

![image](https://user-images.githubusercontent.com/43042815/78667362-5ff95b80-790b-11ea-9999-5d5f463413fc.png)

**Comment by godsan1** [comment]
有人咩？是bug吗还是我用的不对，我好像是按照文档的来的，组件界面弹出来都是正常的

**Comment by rex-zsd** [comment]
看这日志似乎不是组件的报错，而是`confirm`事件处理函数内的报错？

**Comment by rex-zsd** [comment]
看这日志似乎不是组件的报错，而是`confirm`事件处理函数内的报错？

**Comment by rex-zsd** [comment]
可以看下`onConfirm`内是怎么处理的。

**Comment by godsan1** [comment]
谢谢你的提醒@rex-zsd！我看了一下，的确是因为里面我用的别人的案例有问题，导入的start时间和end时间没有赋值到位~后面改好就正常了，谢谢！
