### ISSUE TITLE
建议增加跟Vant Mobile端同样的下拉刷新组件

### ISSUE THREAD

**Issue by kevincwj2008** [youzan/vant-weapp#2975]
建议增加跟Vant Mobile端同样的下拉刷新组件，现在小程序很多地方需要这个组件。

**Comment by NineSu** [comment]
小程序基础库2.10.1已经对scroll-view添加下拉刷新支持。。

**Comment by liushangdev** [comment]
同求，上拉加载控件

**Comment by rex-zsd** [comment]
可以使用原生 scroll-view 的 `bindrefresherpulling` 事件 或页面的 `onPullDownRefresh` 事件
由 vant weapp 提供的话，对这两种功能的选择是无法决定的。
