### ISSUE TITLE
如果将Tab 标签页【line】嵌套进popup，active设置正确，active的标签页下面没有红线

### ISSUE THREAD

**Issue by gwjtssy** [youzan/vant-weapp#2977]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater?repo=VantWeapp

如果将Tab 标签页【line】嵌套进popup，active设置正确，active的标签页下面没有红线

**Comment by eiyoyo** [comment]
@gwjtssy 这个问题解决了吗？我昨天提的相同问题Issue都被关了，也不知道是为啥，最新的1.2.1仍有这个问题

**Comment by rex-zsd** [comment]
@eiyoyo  因为重复了

**Comment by eiyoyo** [comment]
12天过去了这个人都不回复，就一直等着他呀@rex-zsd

**Comment by eiyoyo** [comment]
@rex-zsd 你们已经在解决了还是在等着楼主回复呀？

**Comment by zongwong** [comment]
这个解决了吗.最新1.2.2好像问题依旧,popup中使用tabs的sticky 好像也不行吧?

**Comment by rex-zsd** [comment]
目前只能select到tabs组件，然后调用一下`setLine`方法，重新渲染下划线了。
因为小程序生命周期的缺陷，tabs内目前感知不到组件被渲染出来的时机。
所以将tabs嵌套在popup等组件内动态渲染时总会出现这个问题。

**Comment by Smile-shop** [comment]
![image](https://user-images.githubusercontent.com/28338313/89896593-49904300-dc10-11ea-9049-350eadc10e86.png)
![image](https://user-images.githubusercontent.com/28338313/89896625-5a40b900-dc10-11ea-8150-816ba5515161.png)
亲测在调起popup的时候重新调用tabs组件的setLine方法可以解决

**Comment by rex-zsd** [comment]
下版本 `setLine` 方法将会重命名为 `resize`，并写入文档作为正式的解决办法哈。
