### ISSUE TITLE
[Bug Report] calendar日历组件性能问题

### ISSUE THREAD

**Issue by mw248** [youzan/vant-weapp#2978]
### 设备
华为mate 20

### VantWeapp 版本
1.2.0

### 基础库版本
2.10.4

### 请提供核心代码片段链接
https://youzan.github.io/vant-weapp/#/calendar

### 描述问题
页面上把原来使用的datetimePicker替换成了calendar组件后，真机上运行要3秒左右才能加载出来，选择日期过程中，点选1天后，要点了后1-2秒日历组件才响应，页面原使用datetimePicker没有该问题。

**Comment by rex-zsd** [comment]
用的是真机调试？真机调试卡是正常的，试试用预览。

**Comment by mw248** [comment]
用的是预览，没有使用真机调试

**Comment by rex-zsd** [comment]
使用代码是怎么样的，提供一下吧
可能是选择范围过大导致的

**Comment by mw248** [comment]
发现是可选择范围过大导致的，之前设置的是10年，时间范围改小到半年后，现在加载速度正常了，thks
