### ISSUE TITLE
DatetimePicker在开发环境日期组件可以上下滚动 但在真机上不能上下滚动

### ISSUE THREAD

**Issue by liberty-m** [youzan/vant-weapp#298]
DatetimePicker在开发环境日期组件可以上下滚动 但在真机上不能上下滚动
显示默认时间 ''年 01月 ''日 00时 00分 00秒
请问哪里有问题呢

**Comment by rex-zsd** [comment]
可以提供下代码样例什么的吗？没有信息很难帮你定位到问题。

**Comment by realywithoutname** [comment]
如果能够提供一个代码片段更好解决。或者看下 demo 中的使用

**Comment by chenjiahan** [comment]
目前 zanui-weapp 已进行全新的品牌升级，更名为 Vant Weapp，组件和 API 都有较大的变化。

对 zanui-weapp 的讨论，请移步至 https://github.com/youzan/zanui-weapp 仓库
