### ISSUE TITLE
[Bug Report] van-swipe-cell 触发不了open事件 能触发close事件

### ISSUE THREAD

**Issue by YJHecho** [youzan/vant-weapp#2981]
### 设备
iOS

### VantWeapp 版本
1.2.0

### 基础库版本
1.2.0

### 请提供核心代码片段链接
https://github.com/youzan/vant-weapp/issues/2980

### 描述问题
van-swipe-cell 触发不了open事件 能触发close事件

**Comment by rex-zsd** [comment]
demo小程序并没有问题`open`事件可以正常触发，看贴的代码应该没问题。
可以再看下是否是其它因素影响的。
