### ISSUE TITLE
想问下原生小程序用vant  组件怎么使用rpx进行适配

### ISSUE THREAD

**Issue by vvvgo** [youzan/vant-weapp#2982]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater?repo=VantWeapp

**Comment by rex-zsd** [comment]
可以搜下历史issue，有推荐用postcss插件进行单位转换
