### ISSUE TITLE
[Feature Request] DatetimePicker 时间选择  type==time时，不能使用时间选项格式化函数吗？

### ISSUE THREAD

**Issue by OnlyYu1996** [youzan/vant-weapp#2989]
### 这个功能解决了什么问题
默认的只能是时分的数字形式，无法在时间后面添加单位格式，目前使用格式化函数的话，会返回 aN:aN

### 建议的API是什么样的
可以像设置 选择日期（年月）一样，添加时间格式函数

**Comment by rex-zsd** [comment]
提供一下小程序片段和截图。
才好分析问题
