### ISSUE TITLE
[Bug Report] 对于事件的疑惑

### ISSUE THREAD

**Issue by CQCcq** [youzan/vant-weapp#2992]
### 设备
ipone

### VantWeapp 版本
1.2.0

### 基础库版本
mpx2.0

### 请提供核心代码片段链接
https://github.com/CQCcq/personalMpx

### 描述问题
  <view > 
       <van-tree-select
          items="{{ items }}"
          main-active-index="{{ mainActiveIndex }}"
          active-id="{{ activeId }}"
          max="{{ max }}"
          bind:click-nav="onClickNav"
          bind:click-item="onClickItem"
        />
    </view>

该事件我如何在mpx定义并且可以编译到微信小程序？？？

**Comment by rex-zsd** [comment]
这个可以查阅下mpx的文档，看mpx是如何使用原生小程序组件的哈。
