### ISSUE TITLE
[Bug Report] 引入picker组件，编译时提示找不到toolbar.wxml

### ISSUE THREAD

**Issue by zgia** [youzan/vant-weapp#2994]
### 设备
微信开发者工具 RC v1.02.2003121

### VantWeapp 版本
1.2.0

### 基础库版本
2.10.2

### 请提供核心代码片段链接
```
<config>
{
    navigationBarTitleText: 'xxx管理',
    usingComponents: {
      'van-popup': '~@/components/vant/popup/index',
      'van-picker': '~@/components/vant/picker/index'
    }
}
</config>
```

### 描述问题

使用wepy 2 小程序开发框架。git clone下载vant组件，复制到components/vant

引入picker组件，编译时提示：

> WXMLRT_$gwx:./components/vant/picker/index.wxml:import:9:2: Path ./toolbar.wxml not found from ./components/vant/picker/index.wxml.

查看编译后的weapp目录，toolbar.wxml没有被编译，请问如何解决？

**Comment by rex-zsd** [comment]
这个问题 vant weapp估计解决不了，只能等wepy那边解决啦。

**Comment by santiagochen** [comment]
直接把import的内容拷贝到index.wxml里面，不用import就可以。
