### ISSUE TITLE
van-action-sheet很多属性和事件不管用？？？

### ISSUE THREAD

**Issue by wutao9510** [youzan/vant-weapp#2995]
van-action-sheet很多属性和事件不管用，bind:getuserinfo="getUserInfo"，根本不执行

https://youzan.github.io/vant-issue-generater?repo=VantWeapp

**Comment by rex-zsd** [comment]
demo小程序没有问题，没有设置`openType`？

**Comment by wutao9510** [comment]
有，我都照着文档写的，我又不是新手




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "rex"<notifications@github.com&gt;; 
发送时间: 2020年4月12日(星期天) 中午1:22
收件人: "youzan/vant-weapp"<vant-weapp@noreply.github.com&gt;; 
抄送: "羽翼畅畅"<yuycc@foxmail.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [youzan/vant-weapp] van-action-sheet很多属性和事件不管用？？？ (#2995)





 
demo小程序没有问题，没有设置openType？

**Comment by wutao9510** [comment]
> demo小程序没有问题，没有设置`openType`？
有，我都照着文档写的，我又不是新手
