### ISSUE TITLE
企业微信van-dropdown-menu 自定义组件用 <ww-open-data>不能转换为姓名

### ISSUE THREAD

**Issue by Huangzhe** [youzan/vant-weapp#2996]
代码如下：openID 显示还是openID,不能转换为姓名
<van-dropdown-menu >
		
		<van-dropdown-item title="项目经理" value="{{ value }}" options="{{ pms }}" >
        <view>
        	<ww-open-data corpid="{{corpid}}" openid="{{value}}" type="userName"/> </view>
        </van-dropdown-item>
		
	</van-dropdown-menu>

**Comment by rex-zsd** [comment]
ww-open-data的问题跟 vant weapp没有关系吧…………
