### ISSUE TITLE
van-tabs 设置sticky 没起作用

### ISSUE THREAD

**Issue by huipo22** [youzan/vant-weapp#2997]
<van-tabs active="{{ active }}" bind:change="goodChange" **sticky** style="width:100%">
		<van-tab title="{{item.name}}" wx:for="{{goodType}}" wx:for-item="item" name="{{item.id}}" color="#00a046">
			
			<view>
				<van-card title="{{items.goods_name}}" desc="{{items.remark}}" class="card" wx:for="{{goodGoods}}" wx:for-item="items" catch:tap="{{items.goods_num==0?'':'goodSelect'}}" data-goodid="{{items.id}}" title-class="cardTitle">
					<view class="subscrbeImg" slot="thumb">
						<van-image width="100%" height="100%" src="{{resourse+items.goods_img}}" fit="contain" class="{{items.goods_num==0?'zhezhao':''}}"></van-image>
					</view>
					<view slot="bottom" class="cart-bo">
						<view class="priceBox">
							<view class="se_price">
								<rich-text class="" nodes="{{filter.priceFilter(items.present_price)}}"></rich-text>
								元/{{items.goods_spec}}
							</view>
							<view style="text-decoration:line-through;">
								{{items.original_price}}元/{{items.goods_spec}}
							</view>
						</view>
						<view class="volumn">
							已售
							<view class="red">{{items.goods_volume_false}}</view>
							{{items.goods_spec}}
						</view>
						<view class="cartIcon" wx:if="{{items.goods_num!==0}}">
							<image src="../../dist/icon2/cartLink.png" style="width:30px;height:30px" catch:tap="addCart" data-cart="{{items}}" data-goodid="{{items.id}}" mode="aspectFit" lazy-load="true"></image>
						</view>
					</view>
				</van-card>
			</view>
			
		</van-tab>
	</van-tabs>

**Comment by rex-zsd** [comment]
代码贴的一片混乱…………
可以看下demo小程序是否有这个问题？

**Comment by 1sm23** [comment]
<van-tabs>上加个offset-top试试，设个数值
