### ISSUE TITLE
[Bug Report] 输入框的auto-focus不起作用

### ISSUE THREAD

**Issue by gaofengxu888** [youzan/vant-weapp#3000]
### 设备
IPhone8 plus

### VantWeapp 版本
1.2.0

### 基础库版本
2.10.4

### 请提供核心代码片段链接
https://gitee.com/Buu_G/fantuantuan-miniprograme

### 描述问题
在我的项目中点击最上面的搜索会打开一个新的页面，新的页面有个搜索框，需要一进来自动获取焦点并弹出键盘。因为看到search不支持auto-focus	，但是输入框支持。便用输入框代替，但是仍然无法进入到页面以后自动获取焦点并打开键盘。目前才开始开发。代码量很少，可以很容易定位到我代码的具体位置

**Comment by rex-zsd** [comment]
https://gitee.com/Buu_G/fantuantuan-miniprograme/blob/master/pages/search/index.wxml#L6
看下微信的文档，组件属性不是这么设置的
