### ISSUE TITLE
[Feature Request] Tab 标签页利用数据循环时不显示

### ISSUE THREAD

**Issue by Linxiaodong13579** [youzan/vant-weapp#3006]
### 这个功能解决了什么问题
可以灵活利用数据循环来展示标签

### 建议的API是什么样的
添加数据循环的API与相应的 绑定值方法

**Comment by rex-zsd** [comment]
https://github.com/youzan/vant-weapp/blob/dev/example/pages/tab/index.wxml#L4
example就是用循环的，并没有问题哈。
