### ISSUE TITLE
field组件setShowClear方法问题

### ISSUE THREAD

**Issue by Gokeyoung** [youzan/vant-weapp#3009]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater?repo=VantWeapp

field组件setShoClear方法：
```
setShowClear() {
            const { clearable, readonly } = this.data;
            const { focused, value } = this;
            this.setData({
                showClear: clearable && focused && !!value && !readonly
            });
        },
```
```
const { focused, value } = this
//是不是改为this.data
//const { focused, value } = this.data
```
`focused`字段会为`undefined`
```
console.log(clearable && focused && !!value && !readonly) //undefined
```
控制台会一直打印 `Setting data field "showClear" to undefined is invalid.`

https://github.com/youzan/vant-weapp/blob/ede3a674aef193de3565e393406038bbb97078e8/dist/field/index.js#L86

**Comment by rex-zsd** [comment]
`focused`和`value`为了性能考虑是挂在this上的，取值没有问题。
undefined的问题我们优化一下哈。
