### ISSUE TITLE
[Feature Request] van-button添加form type

### ISSUE THREAD

**Issue by Satlantisy** [youzan/vant-weapp#3010]
### 这个功能解决了什么问题
在form表单内，van-button不能提交表格。希望能加入form type点击按钮提交表格。

### 建议的API是什么样的
跟原生一致即可。

**Comment by rex-zsd** [comment]
https://developers.weixin.qq.com/miniprogram/dev/component/button.html#Bug-Tip
看下小程序官方文档，目前还无法支持这个特性。
虽然更新日志中写v2.10.3版本基础库支持了，但是实测是不行的。
