### ISSUE TITLE
Uploader组件里面的bind:before-read事件，第一个参数file对象，没有type属性，只有path跟size

### ISSUE THREAD

**Issue by SuperIron** [youzan/vant-weapp#3013]
设备
开发者工具

VantWeapp 版本
1.2.1

基础库版本
2.10.4

请提供核心代码片段链接
官方demo就是这样

描述问题
Uploader组件里面的bind:before-read事件，第一个参数file对象，没有type属性，只有path跟size

**Comment by Lindysen** [comment]
若有多个 Uploader 可以用 name 来区分，before-read返回的文件类型是可以通过 accept 属性得知的

**Comment by cgChen1995** [comment]
> 若有多个Uploader可以用名称来区分，before-read返回的文件类型是可以通过accept属性知道的
我也遇到了这个问题，afterRead函数返回的文件path不是我上传的文件路径，也显示不了图片，这是为什么？怎么才能看到上传的文件？
![QQ截图20200503210646](https://user-images.githubusercontent.com/64302655/80915041-0f4a1680-8d82-11ea-8bdb-2697bfd52ec4.png)
