### ISSUE TITLE
[Bug Report] van-popup配合van-tabs使用时，van-tabs的active参数失效

### ISSUE THREAD

**Issue by eiyoyo** [youzan/vant-weapp#3015]
### 设备
微信开发者工具

### VantWeapp 版本
1.2.1

### 基础库版本
2.10.4

### 如果是 UI 问题，截图链接（多图回车分隔）

![截图](https://sm.ms/image/7rs4NoOmtTPkcqC)

### 请提供核心代码片段链接
https://github.com/eiyoyo/vantDebug

### 描述问题
van-popup配合van-tabs使用时，van-tabs的active参数失效，导致本该启用的标签无任何效果。

**Comment by Lindysen** [comment]
#2977

**Comment by Lindysen** [comment]
#2977
