### ISSUE TITLE
[Feature Request] upload组件增加图片视频二选一

### ISSUE THREAD

**Issue by Satlantisy** [youzan/vant-weapp#3016]
### 这个功能解决了什么问题
在上传媒体时，如果排两个按钮，一个上传图片，一个上传视频，会显得很拥挤。希望能实现类似微信朋友圈那种，上传时由用户的第一个选择来判断是图片还是视频。在UI上也会显得很简洁。

### 建议的API是什么样的
类似upload其他的Props，增加一个auto-choose之类

**Comment by Lindysen** [comment]
> ### 这个功能解决了什么问题
> 在上传媒体时，如果排两个按钮，一个上传图片，一个上传视频，会显得很拥挤。希望能实现类似微信朋友圈那种，上传时由用户的第一个选择来判断是图片还是视频。在UI上也会显得很简洁。
> 
> ### 建议的API是什么样的
> 类似upload其他的Props，增加一个auto-choose之类

是希望可以在手机相册选择时，同时支持选择图片和视频吗

**Comment by Satlantisy** [comment]
> > ### 这个功能解决了什么问题
> > 在上传媒体时，如果排两个按钮，一个上传图片，一个上传视频，会显得很拥挤。希望能实现类似微信朋友圈那种，上传时由用户的第一个选择来判断是图片还是视频。在UI上也会显得很简洁。
> > ### 建议的API是什么样的
> > 类似upload其他的Props，增加一个auto-choose之类
> 
> 是希望可以在手机相册选择时，同时支持选择图片和视频吗

是的，就是点击upload，出现手机相册，如果选择了图片，那视频就不能选，反之亦然。辛苦了！
