### ISSUE TITLE
[Feature Request] upload继续添加图片时不要删除之前所选

### ISSUE THREAD

**Issue by Satlantisy** [youzan/vant-weapp#3017]
### 这个功能解决了什么问题
假设max-count设置为9，在某些场景下，用户选择了8张图片，想继续添加一张，希望能实现不删除之前所选，类似朋友圈发图。

### 建议的API是什么样的
增加一个props，如：keep-file-selected，类型：boolean

**Comment by rex-zsd** [comment]
没看懂你的需求是什么…………

**Comment by Satlantisy** [comment]
> 没看懂你的需求是什么…………

upload组件，设置max-count=“9”，先选择了8张图，然后再继续选择1张，期望的效果是有9张上传，但实际是第一次选的8张图没了，只有第二次选的那张。每次选择图片都会刷新fileList。

**Comment by rex-zsd** [comment]
看下文档，选择第9张图以后把file推入到`fileList`就可以了。
