### ISSUE TITLE
1.2.1版本的 uploader 组件选择图片后要等好久才会触发 bind:before-read 事件

### ISSUE THREAD

**Issue by painkiller0513** [youzan/vant-weapp#3020]
今天升级到了 1.2.1 版本，发现个问题，uploader 选择 9 张图片后，要等 4～6 秒才会触发 bind:before-read 事件。这会使得预览图推迟显示。

**Comment by rex-zsd** [comment]
vant weapp内部没有对图片做什么预处理，不耗时的。
所以这里应该是微信API本身的耗时。
