### ISSUE TITLE
van-switch 开关 ，开了再关，不切换回白色

### ISSUE THREAD

**Issue by Marty-chen** [youzan/vant-weapp#3022]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater?repo=VantWeapp

**Comment by rex-zsd** [comment]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater?repo=VantWeapp

**Comment by Windancer** [comment]
简单说就是inactive-color设置后没生效,我也遇到了.但是官网例子却是好的很奇怪.
