### ISSUE TITLE
[Bug Report] Collapse 折叠面板 is-link文档显示错误

### ISSUE THREAD

**Issue by swy1996** [youzan/vant-weapp#3025]
### 设备
微信小程序

### VantWeapp 版本
1.2.1

### 基础库版本
2.9.2

### 请提供核心代码片段链接
https://github.com/youzan/vant-weapp/blob/dev/dist/collapse-item/index.js

### 描述问题
js文件中props为isLink 文档中为is-link 望修改文档

**Comment by rex-zsd** [comment]
没有问题哈，看下小程序官方文档。

**Comment by swy1996** [comment]
![代码内容](https://i.loli.net/2020/04/15/z9BhIAjmduMJ3WS.png)
![文档内容](https://i.loli.net/2020/04/15/23IkDrZnuxqBw8y.png)
文档和代码内的命名不同 右侧箭头显示和消失是控制不了的 还请查看
