### ISSUE TITLE
H5版上传文件，打开安卓手机之后不能录制视频，苹果则可以。希望看下

### ISSUE THREAD

**Issue by CherryLeee** [youzan/vant-weapp#3027]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater?repo=VantWeapp

**Comment by rex-zsd** [comment]
![Uploading image.png…]()
mate30测下来没问题，如果是部分机型的问题，应该没法解决。
`accept="video"`时这里调的是`wx.chooseVide`的官方API。
