### ISSUE TITLE
[Feature Request] upload上传监控

### ISSUE THREAD

**Issue by Satlantisy** [youzan/vant-weapp#3029]
### 这个功能解决了什么问题
厚着脸皮问一句，有没有文档展示下上传监控是如何实现的？我试了把现有的上传监控改成vant的upload，总是报错“wx.cloud.uploadFile(...).onProgressUpdate is not a function”，实在没办法啦 T_T

### 建议的API是什么样的
随意

**Comment by rex-zsd** [comment]
应该是一样的吧，vant的uploader并不处理上传的逻辑，只有获取文件和展示的逻辑。
