### ISSUE TITLE
子组件无法使 vant weapp 组件生效

### ISSUE THREAD

**Issue by legiongeneral** [youzan/vant-weapp#3030]
我看了 uniapp 引用 vant weapp 的方法，也就是在 pages.json 中配置页面的 usingComponents 属性引入vant weapp的组件，但是这个方式 vant weapp 组件只在当前页面生效，如果页面里 import 的其他组件就无法让 vant weapp 组件生效了

例如：
在 uniapp 的 pages.json 里配置了当前页面 pages/help/list 的 usingComponents 属性，引用了 van-cell-group 和 van-cell 仅在 pages/help/list 里生效
{
"path": "pages/help/list",
"style": {
"navigationBarTitleText": "平台规则",
"usingComponents": {
"van-cell-group": "/wxcomponents/vant-weapp/cell-group/index",
"van-cell": "/wxcomponents/vant-weapp/cell/index"
}
}
}
如果 pages/help/list 里面又有通过 import header from '@/components/header' 引入的 header 子组件也使用了 vant weapp 组件，那么此 header 组件里的 vant weapp 组件就没法生效了

**Comment by rex-zsd** [comment]
可以去uniapp看下引用小程序原生组件的方法，这个应该不是vant weapp可以解决的问题。
