### ISSUE TITLE
[Bug Report] tab在动态与静态相结合生成时，如设置animated，tab内容错乱

### ISSUE THREAD

**Issue by arlindar1030** [youzan/vant-weapp#3034]
### 设备
微信开发者工具/iphone xmax

### VantWeapp 版本
1.2.1

### 基础库版本
2.10.4

### 请提供核心代码片段链接
https://youzan.github.io/vant-weapp/#/tab

### 描述问题
如下，在这种tab结构中，会出现tab内容错乱，现象是：「静态内容」出现在最后一个tab下，而动态tab的内容都为空白。
移除animated属性后就正常了。

```
<van-tabs swipeable sticky animated active="{{activeTab}}" bind:change="onTabChange">
    <van-tab title="{{item.title}}" wx:for="{{tabs}}" wx:key="name" name="{{item.name}}">
         <view>{{item.content}}</view>
    </van-tab>
    <van-tab title="静态tab" name="dy">
        <view>静态内容</view>
    </van-tab>
</van-tabs>
```

**Comment by JXlinger** [comment]
tab组件好多问题啊，之前我发过一个关于tab向后切的是会有闪烁的lssues，没人回答，今天发现被删了，既然做，就把态度拿出来

**Comment by rex-zsd** [comment]
![Jietu20200624-163227-HD](https://user-images.githubusercontent.com/8767877/85522607-7379b000-b638-11ea-8ceb-a3bf4d8ec7b6.gif)
测试了一下1.3.2de的版本，没有复现问题，可以看下是不是 `activeTab` 的初始值有问题？

**Comment by rex-zsd** [comment]
@JXlinger 关闭是因为有重复 issue 哈，可以关注 #3290 这个
