### ISSUE TITLE
[Bug Report] package/wxs/bem.wxs修改内容后，example/wxs/bem.wxs不能实时更新

### ISSUE THREAD

**Issue by beishangxiangyou** [youzan/vant-weapp#3039]
### 设备
Windows7

### VantWeapp 版本
1.2.1

### 基础库版本
2.3.0

### 请提供核心代码片段链接
https://github.com/youzan/vant-weapp/blob/dev/build/compiler.js

### 描述问题
复现步骤：
1、npm run dev
2、修改package/wxs/bem.wxs中代码，期望example/wxs/bem.wxs能够实时变更，实际上没有实时变更
3、https://github.com/youzan/vant-weapp/blob/dev/build/compiler.js中的 gulp.watch(`${src}/**/*.wxs`, copier(exampleDir, 'wxs'));代码貌似没有效果

**Comment by rex-zsd** [comment]
mac测试没有问题，可能是windows平台下的问题？
如果找到解决方法的话，欢迎提pr哈 👍
