### ISSUE TITLE
标签页与索引页混合使用，自动吸顶就不好使了

### ISSUE THREAD

**Issue by yzyssb** [youzan/vant-weapp#3041]
![image](https://user-images.githubusercontent.com/21114180/79723557-8d390700-8318-11ea-85c5-e1bc01ea16d1.png)

**Comment by rex-zsd** [comment]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater?repo=VantWeapp

没看懂问题是什么，可以用issue生成器补充一下代码等信息哈
