### ISSUE TITLE
van-tabbar的safe-area-inset-bottom无效    iPhonex没有预留的空间

### ISSUE THREAD

**Issue by 13615817501** [youzan/vant-weapp#3042]
![image](https://user-images.githubusercontent.com/23720587/79726324-2f5aee00-831d-11ea-90c1-de294bc7466b.png)

**Comment by rex-zsd** [comment]
demo小程序是ok的，没有提供代码无法定位问题，可以确认下是不是将`safe-area-inset-bottom`设为`false`了？
