### ISSUE TITLE
Stepper 开启long-press	在安卓上无法停止

### ISSUE THREAD

**Issue by haliuhei** [youzan/vant-weapp#3043]
测试手机小米2s，vant版本1.2.2
直接在微信小程序打开vant weapp官方demo。打开步进器
在小米2s上测试发现（例如基础用法），经常性手已经离开屏幕了，但是步进器的值还在一直增长。
ios正常

**Comment by rex-zsd** [comment]
按照issue模板格式，提供一下核心代码吧

**Comment by haliuhei** [comment]
代码是你们自己的代码，我只是在手机上打开的是你们的vant小程序
