### ISSUE TITLE
[Bug Report] 多个van-dropdown-item布局，本次下拉点击的item会导致上次下拉无法再次重新选择

### ISSUE THREAD

**Issue by Irvinghua** [youzan/vant-weapp#3044]
`<van-dropdown-menu>
 
    <van-dropdown-item id="item1" value="{{ value1 }}" options="{{ option1 }}" />
   
    <van-dropdown-item id="item2" value="{{ value2 }}" options="{{ option2 }}" />
    
</van-dropdown-menu>`

版本信息:VantWeapp 1.2.1/1.2.2

选用以上布局，进行以下操作：
1.先点击id为item1的下拉菜单，展开下拉选项进行选值
2.再点击id为item2的下拉菜单，展开下拉选项进行选值
3.再次点击id为item1的下拉菜单，展开下拉选项进行选值，无法执行选择动作，效果和disabled一样

**Comment by rex-zsd** [comment]
这个例子挺复杂的，可以上传个代码片段吗？

**Comment by XJayXU** [comment]
我也碰到了相同了问题

**Comment by XJayXU** [comment]
![image](https://user-images.githubusercontent.com/33300489/81369475-1f1c7e80-9125-11ea-924e-8f57910edf29.png)
![image](https://user-images.githubusercontent.com/33300489/81369501-35c2d580-9125-11ea-95ef-92af131ce7da.png)
![image](https://user-images.githubusercontent.com/33300489/81369520-3f4c3d80-9125-11ea-9d0f-fbc0c4708756.png)
先点击价格的某一个选项后 打开户型点击某一个选项后 再打开价格 点击没有任何反应

**Comment by XJayXU** [comment]
经测试 好像是上个dropdown-item依旧覆盖在最外层的原因以致于点击失效

**Comment by xiaxilou** [comment]
表示遇见同样的问题

**Comment by xiaxilou** [comment]
请问一下，您现在有解决方案吗

**Comment by chonghu** [comment]
碰见同样的问题，有解决方案么？

**Comment by zibuyu1** [comment]
我也遇到了，我是这样解决的
```vue
<van-dropdown-item 
                :style="{display: categoryShow ? 'block' : 'none'}" 
                @close="categoryShow=false" 
                @open="categoryShow=true">
</van-dropdown-item>
```

**Comment by XJayXU** [comment]
> 我也遇到了同款问题，我加个样式解决了这个
> 
> ```
> < van-dropdown-item  
>                 ：style = “ {display ： categoryShow ？ ' block ' ： ' none ' } ”  
>                 ：options = “ list ” 
>                 ：value = “ value ” 
>                 @ close = “ categoryShow = false ”  
>                 @ open = “ categoryShow = 真正的“>
> </ van-dropdown-item >
> ```

可以通过categoryShow1 categoryShow2 categoryShow3等来分别控制每个下拉菜单的显示隐藏 方法如上述代码即可 亲测有效

**Comment by wenyuanSun** [comment]
小程序不支持这些就很难受

**Comment by lidongqing112** [comment]
![image](https://user-images.githubusercontent.com/69141872/109586939-30fe6080-7b41-11eb-9c47-b1c844eb4361.png)

https://blog.csdn.net/wakaka112233/article/details/108274514

不知道你说的和我遇到的这个是不是一样的，解决方案

**Comment by yzqzy** [comment]
@lidongqing112  确实是 uni-app 解析的问题。
