### ISSUE TITLE
[Bug Report] 页面在跳转到其它分包时tabs的头部会消失

### ISSUE THREAD

**Issue by wj-1222** [youzan/vant-weapp#3045]
### 设备
微信小程序编辑器   iphoneX

### VantWeapp 版本
1.2.2

### 基础库版本
2.10.3

### 请提供核心代码片段链接
https://github.com/wj-1222/vant-weapp-tabs-cs

### 描述问题
tabs的tab在第一个时，页面进行页面跳转其它分包时候，tab标签头部会消失导致其它标签内部的内容暴露出来在第一个下面

**Comment by rex-zsd** [comment]
问题原因是在页面redirect的时候，当前页面的组件会逐渐被销毁。
因为tabs默认是显示第一个tab的，在这个过程中，第一个tab会逐渐从标签1变为标签4。
然后销毁的时间比较短，小程序渲染的时候可能会把几次渲染行为合并在一起，把后面的几个tab一起显示出来了。
这个问题比较难解…………

**Comment by wj-1222** [comment]
可以视觉效果达到吗？在组件被销毁阶段active为1的时候默认把其他的隐藏

**Comment by rex-zsd** [comment]
这不是组件内部可以掌控的，组件内的逻辑的确是按顺序逐个显示第一个tab，但是小程序在处理的时候做合并渲染了。
