### ISSUE TITLE
下拉菜单点开后，滚动页面，弹出的菜单依然还在

### ISSUE THREAD

**Issue by dzlishen** [youzan/vant-weapp#3046]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater?repo=VantWeapp
如题，在下拉菜单点开后，不点它，然后滚动页面，这时候菜单就显示在页面的固定位置。一直都在，怎么让它隐藏呢。

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
