### ISSUE TITLE
步骤条文字描述部分颜色未发生变化

### ISSUE THREAD

**Issue by hongcareer** [youzan/vant-weapp#3050]
### 设备
模拟器、小米手机

### VantWeapp 版本
1.2.2

### 基础库版本
1.0.7

### 如果是 UI 问题，截图链接（多图回车分隔）

![截图](https://sm.ms/image/b1oFEykBfsGA4WS)

### 请提供核心代码片段链接
https://sm.ms/image/b1oFEykBfsGA4WS

### 描述问题
步骤条文字颜色未随active状态发生变化，所有状态的字体颜色均为同一种颜色（代码片段不嫩给提供，请查看截图）

**Comment by rex-zsd** [comment]
demo是没问题的，可以看下是不是使用方式或者样式覆盖了的问题？
