### ISSUE TITLE
[Bug Report] upload组件accept为all弹出聊天对话框

### ISSUE THREAD

**Issue by Satlantisy** [youzan/vant-weapp#3051]
### 设备
Macbook / iPhone

### VantWeapp 版本
1.2.2

### 基础库版本
2.10.4

### 请提供核心代码片段链接
https://youzan.github.io/vant-weapp/#/uploader

### 描述问题
试了下upload组件，把accept值为all时，期望能选择图片视频，但是真机测试确是弹出聊天列表，可以选某个聊天记录的文件。不应该是打开相册吗？

能不能设置accept = ['image','video']这样，能自由组合的？

**Comment by rex-zsd** [comment]
`accept`为`all` 或 `file` 时是从会话中选取文件的，如果需要选择图片和视频可以传`media`

**Comment by Satlantisy** [comment]
> `accept`为`all` 或 `file` 时是从会话中选取文件的，如果需要选择图片和视频可以传`media`

谢谢，是不是还没更新，传media不起作用
