### ISSUE TITLE
van-calendar在设置min-data后，在页面载入时，明显变慢，有没有解决的办法？

### ISSUE THREAD

**Issue by xumiaojun** [youzan/vant-weapp#3052]
van-calendar在设置min-data后，在页面载入时，明显变慢，有没有解决的办法？

**Comment by mw248** [comment]
把日期范围缩小，就没有性能问题了

**Comment by rex-zsd** [comment]
目前只能把日期范围缩小了，因为小程序的API没有h5灵活，所以这部分暂时有欠缺。

**Comment by liknzero** [comment]
不是将日期范围缩小就行了的，有min-date的时候有个警告是，setDate数据过大，超过2M了，如果没有min_date就不会有这个性能问题
![image](https://user-images.githubusercontent.com/32669328/83257771-9e164b80-a1e7-11ea-83ff-69bf32794cb1.png)

**Comment by laozhizi** [comment]
我也遇到了相同的问题，官方也没有什么建议方案吗？我觉得不用所有的数据一次性加载完成吧，异步加载也没问题吧。
