### ISSUE TITLE
[Feature Request] 希望van-calendar 支持提醒当日是否有事件

### ISSUE THREAD

**Issue by 1sm23** [youzan/vant-weapp#3053]
### 这个功能解决了什么问题
日期day下面有红点显示,提醒当日是否有事件

### 建议的API是什么样的
传入一个当日有事件的日期列表, 如[1,13,22], 
![image.png](https://i.loli.net/2020/04/23/qTgEmW36NfnUKxt.png)

**Comment by rex-zsd** [comment]
可以利用`formatter`插入`topInfo`或`bottomInfo`的形式来实现，用样式覆盖来处理下样式。
