### ISSUE TITLE
[Feature Request] upload九宫格图片增加拖拽排列

### ISSUE THREAD

**Issue by Satlantisy** [youzan/vant-weapp#3054]
### 这个功能解决了什么问题
增加体验。
多图上传顺序错了可以直接在UI上拖拽重新排列，不需要删除再重新选择。

### 建议的API是什么样的
draggable

**Comment by rex-zsd** [comment]
评估了一下，实现拖拽会使组件的复杂度上升很多，但是收益不是特别大。
暂时应该不会支持了。
