### ISSUE TITLE
移动端使用Dialog 弹出框 的组件调用  使用下拉框会出现下拉菜单被遮挡的

### ISSUE THREAD

**Issue by hnsh** [youzan/vant-weapp#3056]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater?repo=VantWeapp
![Uploading image.png…]()

**Comment by rex-zsd** [comment]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater?repo=VantWeapp
