### ISSUE TITLE
[Bug Report] upload组件 accept="media" 不起作用

### ISSUE THREAD

**Issue by Satlantisy** [youzan/vant-weapp#3057]
### 设备
Macbook / iPhone

### VantWeapp 版本
1.2.2

### 基础库版本
2.10.4

### 请提供核心代码片段链接
https://youzan.github.io/vant-weapp/#/uploader#accept-de-he-fa-zhi

### 描述问题
看到能传media很开心，终于可以一个按钮选图片视频了，但是测试下为啥不起作用，还是直接打开聊天列表。
npm update了之后也不行，看了下github的代码，貌似没有加入media呀？

**Comment by rex-zsd** [comment]
提供一下使用的代码片段哈

**Comment by yqwoe** [comment]
这个问题解决了吗？ios一样的
```
<van-uploader bind:delete="cancelImagePreview" accept="media" deletable="{{ true }}" capture="['camera']" preview-image="{{true}}" file-list="{{ fileList }}" bind:after-read="afterRead" />
```
点击上传会弹出微信聊天框

**Comment by Satlantisy** [comment]
> 这个问题解决了吗？ios一样的
> 
> ```
> <van-uploader bind:delete="cancelImagePreview" accept="media" deletable="{{ true }}" capture="['camera']" preview-image="{{true}}" file-list="{{ fileList }}" bind:after-read="afterRead" />
> ```
> 
> 点击上传会弹出微信聊天框

还没……

**Comment by Satlantisy** [comment]
> 提供一下使用的代码片段哈

代码片段跟@yqwoe的一样的

**Comment by arlindar1030** [comment]
是的，我这边设置为media了，打开是file的效果

**Comment by Duckweedforever** [comment]
> 提供一下使用的代码片段哈

我也遇到了此类问题 设置为media后打开的是微信聊天 有什么办法解决吗？

**Comment by Duckweedforever** [comment]
> > 提供一下使用的代码片段哈
> 
> 代码片段跟@yqwoe的一样的

我也遇到了此类问题 设置为media后打开的是微信聊天 有什么办法解决吗？

**Comment by Duckweedforever** [comment]
> 提供一下使用的代码片段哈

我也遇到了这类问题设置为media后打开的是微信聊天有什么办法解决吗？
