### ISSUE TITLE
[Bug Report] van-circle组件与wx:for使用时，color属性循环了两遍，且在第二遍的时候才会绑定属性值

### ISSUE THREAD

**Issue by sharksb** [youzan/vant-weapp#3062]
### 设备
微信开发工具

### VantWeapp 版本
1.2.2

### 基础库版本
2.10.3

### 请提供核心代码片段链接
https://github.com/sharksb/giftedImpression/tree/master/pages/myReport

### 描述问题
van-circle组件与wx:for使用时，color属性循环了两遍，且在第二遍的时候才会出现属性值

**Comment by xichunjie** [comment]
@sharksb 我这边三个列表切换，其中一个列表还要折叠，导致van-circle出现显示错位，不显示等问题

**Comment by rex-zsd** [comment]
这里如图所示的代码没有出现问题，可能是历史问题或是数据的问题？

```js
Page({
  data: {
    value: 25,
    list: [
      {
        color: 'red',
      },
      {
        color: 'green',
      },
      {
        color: 'yellow',
      },
    ],
  },
});
```

```html
<van-circle wx:for="{{ list }}" color="{{ item.color }}" value="{{ value }}" text="{{ value }}%" />
```

![image](https://user-images.githubusercontent.com/8767877/108471770-d8200400-72c6-11eb-99d9-9df2a2854bb5.png)
