### ISSUE TITLE
[Bug Report] tabs手机上切换的时候界面加载十分缓慢

### ISSUE THREAD

**Issue by cgChen1995** [youzan/vant-weapp#3065]
### 设备
小米6

### VantWeapp 版本
1.2.2

### 基础库版本
2.10.2

### 如果是 UI 问题，截图链接（多图回车分隔）

[](![截图](https://sm.ms/image/es9fJQziDNauSWA))

### 请提供核心代码片段链接
https://github.com/cgChen1995/-.git

### 描述问题
手机上浏览的时候，点击tabs切换非常缓慢（数据早就已经加载完了），本地浏览速度正常，数据量也不大，在100条数据以内
![微信截图_20200425153422](https://user-images.githubusercontent.com/64302655/80307690-3a21f100-87fd-11ea-9239-89abf4c4aece.png)

**Comment by rex-zsd** [comment]
是真机预览还是发布后在真机上测试？

**Comment by cgChen1995** [comment]
真机预览我根据网上的提示，修改了tabs组件的wxml文件源码，稍微快了一点，但是还是很慢，点击切换之后，需要至少7s才能加载出来

**Comment by rex-zsd** [comment]
把代码片段和UI图补一补吧，图破了，代码链接也是404……

**Comment by rex-zsd** [comment]
如果是真机调试的话是很慢的，可以用预览

**Comment by cgChen1995** [comment]
代码更改设置了，现在可以看了

**Comment by cgChen1995** [comment]
没有用真机进行调试，只是预览，我用的是体验版看的

**Comment by cgChen1995** [comment]
小程序浏览地址
https://open.weixin.qq.com/sns/getexpappinfo?appid=wx923d1af3dfb1094c&amp;path=pages/main/main.html&from=singlemessage#wechat-redirect

**Comment by cgChen1995** [comment]
问题我找到了，是界面渲染的层级过多，所以加载慢，之前是这样用的
`<van-tabs active="{{ active }}" bind:change="onChange">
  <van-tab title="标签 1" wx:for="{{items}}" wx:for-index="idx" wx:for-item="item">
       <view class="content" wx:for="{{shops}}">内容</view>
  </van-tab>
</van-tabs>
这样就很卡了
修改之后是这样的
<van-tabs active="{{ active }}" bind:change="onChange">
  <van-tab title="标签 1" wx:for="{{items}}" wx:for-index="idx" wx:for-item="item">
       
  </van-tab>
</van-tabs>
<view class="content" wx:for="{{shops}}">内容</view>
这样虽然加载起来快了，但是tabs里面的左右滑动效果就没了，有什么办法可以解决这个问题吗？

`

**Comment by cgChen1995** [comment]
我想要加载的快，而且又那些效果

**Comment by rex-zsd** [comment]
可以试试把内容放到tabs的外面，比如
```html
<van-tabs active="{{ active }}" bind:change="onChange">
    <van-tab
      wx:for="{{ tabs }}"
      wx:key="index"
      title="{{ '标签 ' + item }}"
    />
</van-tabs>
<view wx:if="{{ active === 0 }}>内容1</view>
<view wx:if="{{ active === 1 }}>内容2</view>
<view wx:if="{{ active === 2 }}>内容3</view>
```

**Comment by rex-zsd** [comment]
哦 上面的代码就是这个意思，没格式化好没看出来
左右滑动指的是animated还是下划线的滑动？
这样用应该不会影响下划线的滑动的，但是content部分的animated效果应该要自己实现了。

**Comment by cgChen1995** [comment]
自己写js实现吗？还是通过<scroll-view></scroll-view>实现？vant-tabs的js里面有可以引用的方法供使用的吗？

**Comment by rex-zsd** [comment]
tabs内部没有`animated`相关的方法可以引用，这个是使用`css`实现的。
网上搜一搜，这种效果的代码应该挺多的。
