### ISSUE TITLE
图片上传能否批量进行

### ISSUE THREAD

**Issue by dzlishen** [youzan/vant-weapp#3067]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater?repo=VantWeapp
图片上传能否批量进行呢？

**Comment by rex-zsd** [comment]
图片上传是开发者自己控制的，想批量上传没问题呀。
uploader的`mutiple`设为true，获取多张图片，再自己处理下批量上传就可以了。
