### ISSUE TITLE
样式覆盖

### ISSUE THREAD

**Issue by ryanmans** [youzan/vant-weapp#3068]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater?repo=VantWeapp
在小程序中使用组件, 采用了文档的方式实现样式覆盖, 没有效果. 是否没有接触样式隔离?
 <van-button  type="primary">主要按钮</van-button>
.van-button--primary {
  border-radius: 30rpx;
  font-size: 20px;
  color: red !important;
}

**Comment by rex-zsd** [comment]
如果没有生效，可以尝试天加 !important提高优先级看下。
可以点开wxml看下stlye是否有作用到相应的节点上
