### ISSUE TITLE
[Bug Report] 求助：新接手一个小程序项目，如何查看引用的 vant-weapp 版本？

### ISSUE THREAD

**Issue by veking** [youzan/vant-weapp#3078]
### 设备
无

### VantWeapp 版本
1.2.2

### 基础库版本
无

### 如果是 UI 问题，截图链接（多图回车分隔）

![截图](https://s1.ax1x.com/2020/04/27/JRsAiT.jpg)

### 请提供核心代码片段链接
https://github.com/youzan/vant-weapp

### 描述问题
本问题无法完全按照表单要求填写，请见谅。

问题：新接手一个微信小程序项目，发现里面引用了 vant-weapp 目录，现在无法确定所使用的版本号，给维护工作带来很多不便。
项目使用的是文件引入方式，没有使用npm方式，没有任何配置文件，前开发人员已离职。
截图为引入的文件目录结构，查看了很多文件没有找到相关说明和版本号信息。

请提示下是否存在版本号查看的文件，或者如何确定所引用的版本号。

万分感谢！！！

**Comment by rex-zsd** [comment]
图破了，重新上传一下吧

**Comment by veking** [comment]
> 图破了，重新上传一下吧

已更新图片。

**Comment by Satlantisy** [comment]
> ### 设备
> 无
> 
> ### VantWeapp 版本
> 1.2.2
> 
> ### 基础库版本
> 无
> 
> ### 如果是 UI 问题，截图链接（多图回车分隔）
> ![截图](https://camo.githubusercontent.com/90f61a22a826066a88f88857c7f5fd206658814a/68747470733a2f2f73312e617831782e636f6d2f323032302f30342f32372f4a52734169542e6a7067)
> 
> ### 请提供核心代码片段链接
> https://github.com/youzan/vant-weapp
> 
> ### 描述问题
> 本问题无法完全按照表单要求填写，请见谅。
> 
> 问题：新接手一个微信小程序项目，发现里面引用了 vant-weapp 目录，现在无法确定所使用的版本号，给维护工作带来很多不便。
> 项目使用的是文件引入方式，没有使用npm方式，没有任何配置文件，前开发人员已离职。
> 截图为引入的文件目录结构，查看了很多文件没有找到相关说明和版本号信息。
> 
> 请提示下是否存在版本号查看的文件，或者如何确定所引用的版本号。
> 
> 万分感谢！！！

用npm吧 方便省事

**Comment by Satlantisy** [comment]
> > 图破了，重新上传一下吧
> 
> 已更新图片。

用 npm 吧 方便省事

**Comment by rex-zsd** [comment]
应该是0.x的版本，1.0.0中`badge`已经重命名成`sidebar`了

**Comment by veking** [comment]
> 应该是0.x的版本，1.0.0中`badge`已经重命名成`sidebar`了

好的，多谢。
