### ISSUE TITLE
van-submit-bar组件在iphoneX上面显示的时候，样式变了，其他安卓手机正常显示

### ISSUE THREAD

**Issue by cgChen1995** [youzan/vant-weapp#3079]
iphoneX显示结果
![111](https://user-images.githubusercontent.com/64302655/80335362-a6950280-8886-11ea-83c1-5810e493ea7b.png)
小米6显示结果
![222](https://user-images.githubusercontent.com/64302655/80335368-ac8ae380-8886-11ea-898e-f3daba94094c.jpg)

**Comment by rex-zsd** [comment]
#3080
