### ISSUE TITLE
[Bug Report] van-submit-bar组件在iphoneX上面显示的时候，样式变了，其他安卓手机正常显示

### ISSUE THREAD

**Issue by cgChen1995** [youzan/vant-weapp#3080]
### 设备
iphoneX

### VantWeapp 版本
1.2.2

### 基础库版本
2.10.2

### 如果是 UI 问题，截图链接（多图回车分隔）

iphoneX显示结果
![111](https://user-images.githubusercontent.com/64302655/80335362-a6950280-8886-11ea-83c1-5810e493ea7b.png)
小米6显示结果
![222](https://user-images.githubusercontent.com/64302655/80335368-ac8ae380-8886-11ea-898e-f3daba94094c.jpg)

### 请提供核心代码片段链接
https://github.com/cgChen1995/iphone-

### 描述问题
van-submit-bar组件在iphoneX上面显示的时候，样式变了，其他安卓手机正常显示
购物车结算按钮被挤到下面去了

**Comment by cgChen1995** [comment]
问题已解决，通过js判断一下是否为iphoneX，然后控制样式就行了

**Comment by rex-zsd** [comment]
submit-bar的iOS底部安全区是通过`padding-bottom`的形式，又另外加`padding-bottom`时可能会有问题。
