### ISSUE TITLE
van-popup组件中使用van-search，如果出事不显示van-popup组件会导致van-search输入框自动失去焦点

### ISSUE THREAD

**Issue by suweien** [youzan/vant-weapp#3086]
<van-popup
    show="{{ vantPopupShow }}"
    position="right"
    custom-style="width: 100%; height: 100%;"
  >
    <view style="display: flex; height: 100%; width: 100%; position: relative; overflow: hidden;">
      <view style="position: absolute; top: 0; right: 0; left: 0; height: 200rpx;">
        <van-search
          value="{{ searchValue }}"
          shape="round"
          focus="{{true}}"
          background="#4fc08d"
          placeholder="请输入搜索关键词"
          bind:change="handleSearchValueChange"
        >
</van-popup>
vantPopupShow初始值置为false，导致小程序页面 未绑定OnInput，一致失去焦点

**Comment by suweien** [comment]
点击输入框  弹出键盘，又立马收起

**Comment by suweien** [comment]
VM33:2 Do not have onInput handler in current page: pages/home/oa/chapter. Please make sure that onInput handler has been defined in pages/home/oa/chapter, or pages/home/oa/chapter has been added into app.json

**Comment by glntlq** [comment]
请问后面是怎么解决的呀
