### ISSUE TITLE
[Bug Report]vant组件中的变量使用wxs语法，在微信开发者工具中可以正常显示，真机模拟及预览，页面无法渲染

### ISSUE THREAD

**Issue by SummerOrange** [youzan/vant-weapp#3088]
**设备**
微信开发工具、iphone7P

**VantWeapp 版本**
1.2.2

**基础库版本**
2.10.4

**核心代码片段**
wxml:
```
<wxs src="../../utils/tools.wxs" module="tools" />
<van-calendar
            min-date="{{ tools.minDate }}"  -- 这句的tools用的wxs，在真机调试或预览时，就无法渲染了
            max-date="{{ maxDate }}"   -- 这句ok
            default-date="{{[maxDate]}}"
            show="{{ show }}"
            type="range"
            bind:close="onClose"
            bind:confirm="onConfirm"  />
```
tools.wxs:
```
var minDate = getDate('2019-1-1').getTime()
module.exports = {
  minDate: minDate
};
```
.json、.js文件的内容和官方文档中[【Calendar 日历 -- 选择日期区间】](https://youzan.github.io/vant-weapp/#/calendar#xuan-ze-ri-qi-qu-jian) 代码一样

**问题描述**
`min-date="{{ tools.minDate }}" ` ： 这句的tools用的wxs，在真机调试或预览时，就无法渲染了
`min-date="{{ minDate }}"`：换成这种写法就不会出现真机调试无法渲染问题

你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater?repo=VantWeapp

**Comment by rex-zsd** [comment]
测试了一下，这段代码复现不了问题，都是可以渲染的
但是要注意，`minDate`和`maxDate`的区间最好不要设的太大，会导致渲染量大大增加，性能不好的手机可能需要很长时间才能渲染出来。
