### ISSUE TITLE
下拉框dropdown嵌套索引indexBar，indexBar无法跳转锚点且底部Z区域不可正常显示

### ISSUE THREAD

**Issue by hathawayssm** [youzan/vant-weapp#3089]
**问题1：**
按照官方demo与api，自定义索引列表

index.wxml文件对应部分：
`
<van-index-bar
        index-list="{{ airportCodeIndexList }}"
        scroll-top="{{ scrollTop }}">
        <view wx:for="{{ airportCodeIndexList }}" wx:key="index">
          <van-index-anchor use-slot="{{ true }}" index="{{ item }}">
            <text>{{ item }}</text>
          </van-index-anchor>
          <van-cell title="文本" />
          <van-cell title="文本" />
          <van-cell title="文本" />
        </view>
      </van-index-bar>
`
index.js文件对应部分
`
const airportCodeIndexList = [];
const charCodeOfA = 'A'.charCodeAt('0');
for (let i = 0; i < 26; i++) {
  airportCodeIndexList.push(String.fromCharCode(charCodeOfA + i));
}
....
airportCodeIndexList,
scrollTop: 0,
...
onPageScroll(event) {
    this.setData({
      scrollTop: event.scrollTop
    });
  },
`
最终的实现效果，页面显示正常。但点击字母，页面无法定位锚点，也无css效果。
源码部分如
`
anchor.scrollIntoView(this.scrollTop);
this.$emit('select', anchor.data.index);
`
获取数据正常。

问题二：
indexBar绑定数组A~Z时，Z部分消失，百度发现很多人有这个问题，其他人通过调整样式实现。
附链接
https://blog.csdn.net/qq_30424359/article/details/97396570

**Comment by hathawayssm** [comment]
你好，上述两个问题我已解决，是dropdown下拉框嵌套indexBar，indexBar才失效。这个属于bug吗

**Comment by rex-zsd** [comment]
这个的确是bug，原因是小程序不支持监听任意view的滚动，也没有方法获取view的滚动位置。
所以IndexBar仅支持在页面内滚动，任何在view内滚动的行为都是不支持的。

**Comment by rex-zsd** [comment]
以小程序目前的API，无法支持嵌套在view内滚动使用哈。

**Comment by StephenKe** [comment]
> 以小程序目前的API，无法支持嵌套在view内滚动使用哈。

建议在官方文档内把这个bug贴出来
