### ISSUE TITLE
van-search组件绑定有问题

### ISSUE THREAD

**Issue by XJayXU** [youzan/vant-weapp#3090]
![image](https://user-images.githubusercontent.com/33300489/80465716-17631a00-896e-11ea-95f8-89950c490b9f.png)

**Comment by XJayXU** [comment]
还有时间选择组件

**Comment by rex-zsd** [comment]
应该不是vant weapp的问题，因为vant weapp没有用`in`操作符，也没有`markerId`这个变量…………
因为没有代码，没法帮你看了。
检查下自己的代码或者看看是不是其他框架/库的影响吧。

**Comment by XJayXU** [comment]
可是我直接用的就是官方的demo啊 整个所有的文件夹都是官方的东西 没有其他框架啊

**Comment by XJayXU** [comment]
![image](https://user-images.githubusercontent.com/33300489/80554025-6f496180-89fe-11ea-98fb-0561d1cb15bf.png)
是不是因为是uniapp的原因导致这一问题 也就是vant-webapp不兼容uniapp
