### ISSUE TITLE
[Bug Report] popup点击关闭时报错TypeError: Cannot set property 'top' of undefined

### ISSUE THREAD

**Issue by Patrick-Jun** [youzan/vant-weapp#3091]
### 设备
微信开发者工具

### VantWeapp 版本
1.2.2

### 基础库版本
2.10.4

### 请提供核心代码片段链接
https://gist.github.com/Patrick-Jun/25b93b9f0df0dd643dfaed85786bf077

### 描述问题
这是在一个组件内部是用的popup，功能上是没有问题的，也能正常关闭。只是每次点击关闭弹窗时，均会报这个错误。

**Comment by rex-zsd** [comment]
popup内部没有读取`.top`属性，不像是组件内抛的，看了下报错信息是从`WAService.js`微信的js里面抛出来的，是不是有其他因素导致了报错？
