### ISSUE TITLE
van-dropdown-menu在遮罩层之外可以滚动页面

### ISSUE THREAD

**Issue by Fiestar** [youzan/vant-weapp#3097]
![image](https://user-images.githubusercontent.com/37931780/80556795-5c875a80-8a07-11ea-87d9-9212a2281a76.png)
![image](https://user-images.githubusercontent.com/37931780/80556820-732db180-8a07-11ea-8b08-693caf424aae.png)

**Comment by rex-zsd** [comment]
#3099
