### ISSUE TITLE
遮罩层滑动穿透

### ISSUE THREAD

**Issue by Accusr** [youzan/vant-weapp#3099]
遮罩层滑动穿透的问题能否解决呀，即使有遮罩层还是能滑动下面的view，这个有解决的方案吗？谢谢

**Comment by zhengbaofeng** [comment]
我跟你遇到了同样的问题。。解决了吗

**Comment by kingslary** [comment]
我也遇到这个问题，很难受，弹出层如果内容多的时候，滚动到底部，然后在底部区域滑动时会触发底层页面的滑动，90%的概率发生。

**Comment by moailaoz** [comment]
弹出时给下层页面添加position:fixed

**Comment by rex-zsd** [comment]
[文档说明](https://youzan.github.io/vant-weapp/#/popup#zu-jian-gun-dong-chuan-tou-gai-zen-me-jie-jue)已增加。
