### ISSUE TITLE
[Feature Request] Date-picker 可否支持自定义添加一个选项

### ISSUE THREAD

**Issue by dpp050700** [youzan/vant-weapp#3101]
### 这个功能解决了什么问题
自定义 Date-picker 选项

### 建议的API是什么样的
比如 年月日时分秒选择，时分秒 可以选择 未知
比如年分选择可以添加 至今、一年前 等选项

**Comment by rex-zsd** [comment]
暂时不会支持，特殊需求可以用Picker组件来自行实现哈。
