### ISSUE TITLE
支持百度、支付宝、抖音吗

### ISSUE THREAD

**Issue by kknono** [youzan/vant-weapp#3110]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater?repo=VantWeapp

**Comment by rex-zsd** [comment]
目前只支持微信小程序哦

**Comment by bytrix** [comment]
什么时候能支持抖音小程序？
