### ISSUE TITLE
van-circle使用时，如果有popup，没有被遮盖

### ISSUE THREAD

**Issue by los0128** [youzan/vant-weapp#3112]
van-circle使用时，如果有popup，没有被遮盖，请问能不能解决

**Comment by rex-zsd** [comment]
van-circle内用到canvas了，原生组件层级是最高的无法覆盖。
可以把`type`设为`2d`开启同层渲染，不过要注意`2d`只支持基础库2.9.0以上。

**Comment by xichunjie** [comment]
把type设为2d了还是没有被popup覆盖，这是怎么回事 @rex-zsd

**Comment by rex-zsd** [comment]
#3168 目前canvas 2d还有些问题，下个版本将会修复 @xichunjie
