### ISSUE TITLE
[Bug Report] sticky组件嵌套在固定高度的scroll-view内部时失效

### ISSUE THREAD

**Issue by kingeight** [youzan/vant-weapp#3114]
### 设备
iphone

### VantWeapp 版本
1.2.2

### 基础库版本
2.10.3

### 请提供核心代码片段链接
https://gist.github.com/kingeight/899d32232aa1827c3100dba9176037be

### 描述问题
使用tabs组件的时候，使用sticky属性想要将tab栏设置成粘性布局，但是项目里面tabs组件是嵌套在一个固定高度（实际上是屏幕高度减去一个固定值）的scroll-view里，这个时候粘性布局无法正常工作

**Comment by rex-zsd** [comment]
目前sticky仅支持在页面内使用，不支持嵌套在view内滚动使用哈。
后续sticky组件会开放`scrollTop`属性，使scroll-view中可以正常工作。

**Comment by kingeight** [comment]
> 目前sticky仅支持在页面内使用，不支持嵌套在view内滚动使用哈。
> 后续sticky组件会开放`scrollTop`属性，使scroll-view中可以正常工作。

明白。我看了下page-scroll的源码，目前监听的是page的scroll动作，确实不支持嵌套使用sticky

**Comment by rex-zsd** [comment]
是的，小程序目前的DOM API比较匮乏，理论上来说，只能支持page和scroll-view。
