### ISSUE TITLE
能不能减少下组件的依赖 ？

### ISSUE THREAD

**Issue by miwei230** [youzan/vant-weapp#3117]
有个时候，只想用框架的部分功能，比如日期时间选择，多选等微信没有的组件，还有大分部的组件没有使用到，抱着减少项目文件size心态去剔除不需要的文件；于是去dist目录下找对应组件；最后发现组件中还引入了第二组件，又再去找第二个组件目录，又发现第二个组件引入了第三个组件...；层层下来结果还是引入了一堆组件。

**Comment by 1sm23** [comment]
这正是组件的意义
