### ISSUE TITLE
[Bug Report] Transition 失效

### ISSUE THREAD

**Issue by mustars** [youzan/vant-weapp#3118]
### 设备
所有机型

### VantWeapp 版本
1.2.2

### 基础库版本
2.11.0

### 请提供核心代码片段链接
https://youzan.github.io/vant-weapp/#/transition

### 描述问题
好像是从v1.2.0开始Transition就失效了。设置show也不行。内容不会显示。
代码：
《van-transition show》
  内容
《/van-transition》

中括号换英文括号

**Comment by mustars** [comment]
<van-transition show>
  内容
</van-transition>

内容不会显示

**Comment by kingeight** [comment]
初始化的时候无法显示，你试试这样写：
<van-transition show="{{show}}">内容</van-transition>

show初始值是true也不会显示，当你更改show的值后就会显示了。。。因为代码里只监视了show值变化。如果要实现，可以修改mixins/transition.js文件中定义Behavior中加入ready事件监视，添加如下代码:
`ready:function(){
          if(this.data.show==true){
            this.enter();
          }
        }`

**Comment by mustars** [comment]
> 初始化的时候无法显示，你试试这样写：
> `<van-transition show="{{show}}">内容</van-transition>`
> 
> show初始值是true也不会显示，当你更改show的值后就会显示了。。。因为代码里只监视了show值变化。如果要实现，可以修改mixins/transition.js文件中定义Behavior中加入ready事件监视，添加如下代码:
> `ready:function(){ if(this.data.show==true){ this.enter(); } }`

搞定！！感谢。
