### ISSUE TITLE
npm创建出错

### ISSUE THREAD

**Issue by sw2233dfkdsjkd** [youzan/vant-weapp#3119]
Error: EPERM: operation not permitted, rename
"D:wx\Cminiprogram npm' ->
"D:wxiCminiprogramlniniprogram. npmtrror:
EPERM: operation not permitted, rename
"D:wx\Cminiprogram npm' ->
"D:wxiCminiprogramlniniprogram. npm'

**Comment by rex-zsd** [comment]
没有权限，看起来……不像是 vant weapp 的问题吧
