### ISSUE TITLE
van-popup 在最新版7.0.14微信中  显示与隐藏有时候会卡顿

### ISSUE THREAD

**Issue by ludetao** [youzan/vant-weapp#3120]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater?repo=VantWeapp
![image](https://user-images.githubusercontent.com/20348969/81385473-f789de00-9145-11ea-932f-733fe66b31c4.png)

**Comment by zongwong** [comment]
我也遇到这个问题了,但是不知道是微信的版本问题 还是 vant的bug 还是自己代码的bug?

**Comment by pangxiaofu** [comment]
我在van-popup里面用了van-tab如果数据量大的话就会非常卡顿

**Comment by futing2019** [comment]
我用van-popup 也会出现卡顿。之前没有这个问题。 希望官方解决

**Comment by KePingHub** [comment]
我的也是，我是van-popup 结合 van-datetime-picker一起使用，响应速度很慢
