### ISSUE TITLE
请问小程序中，不能使用vant的swiper吗？dist文件里面没有这个轮播图

### ISSUE THREAD

**Issue by leenannan** [youzan/vant-weapp#3121]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater?repo=VantWeapp

**Comment by rex-zsd** [comment]
vant weapp 没有 swiper 组件呢，可以使用原生的轮播图组件哈。
