### ISSUE TITLE
[Bug Report] van-slider min属性失效

### ISSUE THREAD

**Issue by 1sm23** [youzan/vant-weapp#3122]
### 设备
IDE/iPhone 11

### VantWeapp 版本
1.3.0

### 基础库版本
2.11.0

### 请提供核心代码片段链接
https://gist.github.com/1sm23/88881e786d6f72730e2016a1864f9b28.js

### 描述问题
van-slider min属性设置无效

**Comment by rex-zsd** [comment]
按照你的代码，最小值是`20`，没有问题。
你可能对这个属性的含义有误解，`min`定义的是最左边的点代表的值，而不是限制左侧20%不可到达。
