### ISSUE TITLE
[Bug Report] WXSS编译警告: VM24862:1 Some selectors are not allowed in component wxss 

### ISSUE THREAD

**Issue by fanshuai** [youzan/vant-weapp#3123]
##### 相关信息
- VantWeapp版本：1.3.0
- 设备：微信开发者工具 & iPhone X
- 小程序基础库版本：2.11.0

##### 重现步骤
```
1. app.wxss 中引用：@import './miniprogram_npm/@vant/weapp/common/index.wxss';
2. app.json usingComponents 引用@vant/weapp所有组件
```

##### 结果
- 控制台显示警告
```
Some selectors are not allowed in component wxss, including tag name selectors, ID selectors, and attribute selectors.(./miniprogram_npm/@vant/weapp/skeleton/index.wxss:1:1)
```
<img width="1289" alt="截屏2020-05-09 上午4 48 56" src="https://user-images.githubusercontent.com/1005487/81448086-66038600-91b0-11ea-8319-a16d9a2e9ac9.png">

##### 问题
- 想问下这个是否符合预期？或者有什么使用或配置上的优化建议？

**Comment by shellus** [comment]
![image](https://user-images.githubusercontent.com/3044880/81467602-544fcc00-920c-11ea-92fa-448e7edb7b4d.png)

同样遇到这个问题

**Comment by arlindar1030** [comment]
同样，今天更新到1.3.0后，就出了一百多个这个报警

**Comment by rex-zsd** [comment]
#3131
可以关注这个issue，重复的就关闭了
