### ISSUE TITLE
vant weapp search组件无法取到值

### ISSUE THREAD

**Issue by duanjiaqing** [youzan/vant-weapp#3125]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater?repo=VantWeapp

**Comment by xiaxilou** [comment]
表示一样，然后用原生写了

**Comment by Lindysen** [comment]
无法复现，提供一下示例代码
