### ISSUE TITLE
在uniapp中使用weapp，有些组件可以正常使用，有些组件就不行，比如下拉框和搜索框，输入框，这些点击事件上，都会报markid的错误，还请查看一下

### ISSUE THREAD

**Issue by xiaxilou** [youzan/vant-weapp#3126]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater?repo=VantWeapp

**Comment by rex-zsd** [comment]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater?repo=VantWeapp

**Comment by rex-zsd** [comment]
请用开发者工具生成一下代码片段提供下哈，这个issue标题太宽泛了。

**Comment by xiaxilou** [comment]
您好，首先很抱歉，没有想到会以邮箱通知我，不好意思，至于问题，我下午回给你回一个消息，目前不在公司，很抱歉了



在 2020-05-11 13:04:12，"rex" <notifications@github.com> 写道：

你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater?repo=VantWeapp
