### ISSUE TITLE
[Feature Request] Card 商品卡片 没有营销信息代码示例

### ISSUE THREAD

**Issue by cgChen1995** [youzan/vant-weapp#3127]
### 这个功能解决了什么问题
想在card组件的左上角加一个tag标签，vant weapp版没有看到代码
vant版里面看到有这个功能，vant weapp版后期会不会加这个功能？我觉得那个效果挺好看的

### 建议的API是什么样的
card组件的左上角加一个tag标签

**Comment by Lindysen** [comment]
vant-weapp Card 组件支持 tag 标签的 API 文档中有的

**Comment by cgChen1995** [comment]
是https://youzan.github.io/vant-weapp/#/card 里面吗？没看到啊

**Comment by Lindysen** [comment]
![image](https://user-images.githubusercontent.com/33708359/81495816-a9134580-92e5-11ea-9bc2-958afb42c526.png)

**Comment by cgChen1995** [comment]
你发的图片看不了，vant里面是有的，但是vant weapp里面没看到

**Comment by cgChen1995** [comment]
![微信截图_20200513154438](https://user-images.githubusercontent.com/64302655/81785312-bf611180-9530-11ea-9689-15394cc3c9d6.png)
我想要营销信息里的标签效果
不是自定义内容里面的那种标签
