### ISSUE TITLE
在使用tabs组件时，type为默认的line类型，设置border="false"后，tabs上下边框依然存在。

### ISSUE THREAD

**Issue by RussellCao824** [youzan/vant-weapp#3129]
代码为：
`<van-tabs border="false" active="a">
    <van-tab title="默认排序" name="a"></van-tab>
    <van-tab title="家庭成员" name="b"></van-tab>
    <van-tab title="账单类别" name="c"></van-tab>
    <van-tab title="待审核" name="d"></van-tab>
  </van-tabs>`

**Comment by rex-zsd** [comment]
`border`接受的是`boolean`类型的值，`border="{{ false }}"`这样。

**Comment by RussellCao824** [comment]
> `border`接受的是`boolean`类型的值，`border="{{ false }}"`这样。

明白了，多谢。
