### ISSUE TITLE
【bug】1.3.0版本警告太多了呀，看着很不舒服

### ISSUE THREAD

**Issue by zszjszlk2** [youzan/vant-weapp#3131]
![警告](https://user-images.githubusercontent.com/46711557/81502296-b8a78400-930f-11ea-8703-7512144baf12.png)

**Comment by 1sm23** [comment]
组件wxss里有些选择器无效

**Comment by rex-zsd** [comment]
1.3.0增加了全局字体，使用了`page`选择器导致的。
这个要考虑一下，不一定会调整。

**Comment by Sean-Wang** [comment]
看着很不舒服，希望能修复这些警告输出。

**Comment by bigmeow** [comment]
全局字体可以让用户自己单独在app.wxss里面引入吧

**Comment by b1ngx** [comment]
影响查看调试信息

**Comment by NineSwordsMonster** [comment]
望处理下，真的太影响调试了

**Comment by s1min** [comment]
> 1.3.0增加了全局字体，使用了`page`选择器导致的。
> 这个要考虑一下，不一定会调整。

不一定调整，那就一直这么多警告吗 :-(

**Comment by chenjiahan** [comment]
下个版本会移除内置的全局字体

**Comment by muuubooo** [comment]
附议附议~
确实太多了不是舒不舒服的问题，客观影响console的可读性了
希望能够调整这一设置

**Comment by fanshuai** [comment]
计划什么时候发布呢
🙏

**Comment by chenjiahan** [comment]
已在 1.3.1 版本修复

**Comment by muuubooo** [comment]
> 已在 1.3.1 版本修复

感谢！
已升级~
