### ISSUE TITLE
upload组件 accept="media" 不起作用点击上传会弹出微信聊天框

### ISSUE THREAD

**Issue by Duckweedforever** [youzan/vant-weapp#3132]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater?repo=VantWeapp

**Comment by rex-zsd** [comment]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater?repo=VantWeapp
