### ISSUE TITLE
[Bug Report] 动画组件初始化以及卡顿

### ISSUE THREAD

**Issue by kingeight** [youzan/vant-weapp#3133]
### 设备
小米8

### VantWeapp 版本
1.3.0

### 基础库版本
1.3.0

### 请提供核心代码片段链接
https://gist.github.com/kingeight/67ae9bd690d0a8ba9977a23a8ad7fc13

### 描述问题
transition组件，如果初始化的时候show的值是ture，实际上还是没有显示组件。
另外这个组件在部分安卓机上卡顿非常严重，例如小米8

**Comment by silvergray** [comment]
求解决

**Comment by DOVEMM** [comment]
求解决呀

**Comment by mikasaYw** [comment]
v1.6.2
重构的内容貌似只是改变移动端绑定的过程  初始化true不显示的问题并没有解决

**Comment by zaxlct** [comment]
同样遇到该问题。。。还是老实手写吧

**Comment by icytailu** [comment]
> 同样遇到该问题。。。还是老实手写吧

https://github.com/youzan/vant-weapp/issues/3816
