### ISSUE TITLE
[思考] packages目录中，父子组件为什么使用插槽做嵌套，和不是直接在组件内搭配好

### ISSUE THREAD

**Issue by duyu123** [youzan/vant-weapp#3135]
### 设备
windows

### VantWeapp 版本
1.3.0

### 基础库版本
1.3.0

### 请提供核心代码片段链接
https://github.com/youzan/vant-weapp/tree/dev/packages/dropdown-menu

### 描述问题
比如 dropdown-menu/dropdown-item 是父子组件关系，为什么不在dropdown-menu组件中嵌套完成，而是使用slot方式在上层做嵌套，是有特别的逻辑吗？

**Comment by rex-zsd** [comment]
…………嵌套使用可定制性更强，内部全包的话，配置数据会非常复杂
