### ISSUE TITLE
goods-action-icon的color属性被移除了

### ISSUE THREAD

**Issue by XiaoLeaf** [youzan/vant-weapp#3136]
在最新的1.3.0和1.2.2版本中goods-action-icon的color属性被移除。想了解一下为什么移除这个属性呢？

**Comment by rex-zsd** [comment]
…………并没有移除呀，文档中有，实测也是有效的

**Comment by XiaoLeaf** [comment]
> …………并没有移除呀，文档中有，实测也是有效的
文档中确实有写这个属性，但是最新版本的js文件和wxml文件中并没有color属性
