### ISSUE TITLE
[Bug Report] Circle组件在列表渲染时type属性无法设置为2d

### ISSUE THREAD

**Issue by doge-liang** [youzan/vant-weapp#3139]
### 设备
微信开发者工具

### VantWeapp 版本
1.3.0

### 基础库版本
2.11.0

### 如果是 UI 问题，截图链接（多图回车分隔）

![截图](https://i.loli.net/2020/05/12/l5WvLD3tFKT2yUR.png)

### 请提供核心代码片段链接
https://github.com/doge-liang/TimeKeeper/blob/master/miniprogram/pages/project/project.wxml

### 描述问题
使用列表渲染多个Circle组件的时候，type="2d"设置失效，控制台出现没使用canvas 2d的警告，因此无法和popup组件同级渲染；

**Comment by doge-liang** [comment]
上图和仓库的代码没写，是上传代码的时候添加，但是实际加上去的确没有效果

**Comment by doge-liang** [comment]
抱歉，是我自己的失误，type=2d应该是生效了，是我的popup写错了……但是控制台的警告一直都有，应该是正常的。

**Comment by xichunjie** [comment]
设置了type=2d，popup弹出能覆盖吗？我下载了你的项目，运行在android手机上，还是不能覆盖circle

**Comment by xichunjie** [comment]
@doge-liang 设置了type=2d，popup弹出能覆盖吗？我下载了你的项目，运行在android手机上，还是不能覆盖circle
