### ISSUE TITLE
[Bug Report] van-datetime-picker  真机无法显示

### ISSUE THREAD

**Issue by hehehai** [youzan/vant-weapp#3140]
## 问题
在小程序开发工具中使用无问题，真机调试无问题，真实环境下（安卓）无法显示日期选择器里的日期
![image](https://user-images.githubusercontent.com/12692552/81762537-6e84f500-94ff-11ea-96d1-b1efb7c98d66.png)
![image](https://user-images.githubusercontent.com/12692552/81762542-717fe580-94ff-11ea-8c33-e3d5d2a95b72.png)

## 环境
设备：安卓
VantWeapp 版本：1.2.0
基础库版本：2.10.4

## 部分代码
```html
<!-- 时间选择 -->
<view catchtouchmove="{{true}}">
	<van-popup show="{{ pickerTimeModel.show }}" position="bottom" custom-style="height: 40%" bind:close="handlePickerTimeClose">
		<van-datetime-picker title="年/月/日 时:分" data-type="datetime" type="datetime" value="{{ model.timeRange[pickerTimeModel.type] }}" cancel-button-text="清空" min-date="{{ pickerTimeModel.minDate }}" max-date="{{ pickerTimeModel.maxDate }}" bind:confirm="handlePickerTimeConfirm" bind:cancel="handlePickerTimeClear" />
	</van-popup>
</view>
```

```js
model: {
	orderId: '',
    mediaName: '',
    orderTitle: '',
    customerName: '',
    timeRange: {
        type: 'put',
        start: null,
       	end: null
    }
},

// 时间选择器
pickerTimeModel: {
   show: false,
   type: '',
   maxDate: wx.$day().valueOf(),
   minDate: wx.$day('2019-6-1').valueOf(),
},
```
这里时间选择器 value 的默认值是 null，

## 尝试
- 不用pop：开发及真机调试可显示，真实环境（安卓）无法显示日期选择器里的日期
- 不使用mindate和maxdate：开发及真机调试可显示，真实环境（安卓）无法显示日期选择器里的日期

**Comment by hehehai** [comment]
@chenjiahan @rex-zsd @pangxie1991

**Comment by HateTomatoes** [comment]
我也出现这个问题，看了源码后发现只是一个安全判断的问题。
``` 
   formatter: {
      type: null,
      value: defaultFormatter,
    },
```
props里的`formatter`默认值没生效，导致`updateColumns`函数报错
```
updateColumns() {
      const { formatter = defaultFormatter } = this.data
      const results = this.getOriginColumns().map((column) => ({
        values: column.values.map((value) => formatter(column.type, value)),
      }));
      return this.set({ columns: results });
    },
```
如上述函数的`const { formatter = defaultFormatter } = this.data`写法存在安全隐患，因为`this.data.formatter`是为`null`而不是`undefined`，所以解构后`formatter`值为`null`，调用后直接报错。
为什么props里的`formatter`默认值没生效？我还没找到原因，目前只能自己改下源码解决这问题了。

**Comment by hehehai** [comment]
@HateTomatoes 好吧，我没有仔细去看，目前是使用了原生的微信组件，仅支持了 年月日，不过当前业务下够用了。

**Comment by rex-zsd** [comment]
#3352 1.4.0已经修复咯

**Comment by towry** [comment]
如果是用了 tarojs，出现开发者工具或者真机无法显示 van-datetime-picker 的情况，解决办法是给组件的所有 props 都传递一个默认值，默认值可以查看 van-datetime-picker 里的源码。
