### ISSUE TITLE
[Bug Report] tabs sticky无效

### ISSUE THREAD

**Issue by yuu2lee4** [youzan/vant-weapp#3143]
### 设备
微信开发者工具

### VantWeapp 版本
1.3.0

### 基础库版本
2.9.4

### 请提供核心代码片段链接
https://gist.github.com/

### 描述问题
如果在tabs上使用wx:if 在某个条件下 再显示tabs  这个时候sticky就无效，目前的只能用hidden先解决着

**Comment by rex-zsd** [comment]
tabs依赖组件初始化的时候监听页面的滚动事件，如果推迟了组件的初始化时机，就会无法监听。
目前这个还无法解决，可以用`hidden`来隐藏组件。
