### ISSUE TITLE
[Bug Report] van-popup的bug

### ISSUE THREAD

**Issue by PinkYun** [youzan/vant-weapp#3144]
### 设备
ios  安卓  开发者工具

### VantWeapp 版本
0.4.9

### 基础库版本
2.11.0

### 如果是 UI 问题，截图链接（多图回车分隔）

![截图](https://img.xingxiovip.com/WechatIMG441.png)

### 请提供核心代码片段链接
https://www.baidu.com

### 描述问题
在页面引用了va-popup组件，偶发性的出现遮罩成时效了，直接把结果显示出来

**Comment by shijiali1** [comment]
为什么使用这个组件  真机调试十分卡顿  请问这是正常的吗

**Comment by rex-zsd** [comment]
transition 组件重构过，目前应该没有问题了。
