### ISSUE TITLE
van-field不支持v-model，原生input是可以支持的

### ISSUE THREAD

**Issue by teri5354** [youzan/vant-weapp#3146]
在mpvue里面，使用van-field并不支持v-model属性。
如果使用原生的input是可以支持的，以下代码在mpvue环境下运行测试过
`<input type="text" placeholder="test11111" v-model="test1" />   正常使用
      <van-field
        placeholder="test222222"
        v-model="test2"
      /> 无法使用`

**Comment by rex-zsd** [comment]
可以使用`bind:input`事件哈，vant weapp是不支持绑定原生小程序组件的。

**Comment by teri5354** [comment]
不能用input，在某些安桌机型下面，如果输入完，立马点击旁边按钮，此时反应有延时，会导致被吞掉后面字符，增加了blur也不行。最好改成支持v-model的

**Comment by teri5354** [comment]
> 可以使用`bind:input`事件哈，vant weapp是不支持绑定原生小程序组件的。

不能用input，在某些安桌机型下面，如果输入完，立马点击旁边按钮，此时反应有延时，会导致被吞掉后面字符，增加了blur也不行。最好改成支持v-model的
