### ISSUE TITLE
[Feature Request] Card 商品卡片里面没找到营销示例的代码

### ISSUE THREAD

**Issue by cgChen1995** [youzan/vant-weapp#3147]
### 这个功能解决了什么问题
业务需求

### 建议的API是什么样的
Card 商品卡片里面没找到自定义营销示例标签的代码（想自定义slot="tag"）
![微信截图_20200513154438](https://user-images.githubusercontent.com/64302655/81785312-bf611180-9530-11ea-9689-15394cc3c9d6.png)

**Comment by rex-zsd** [comment]
vant weapp并不支持thumb-tag的，因为`tag`属性与 vant 的`tag`重名了。
修改会造成 breaking change，1.x版本将不会支持。
可以用`thumb`slot自己实现一下。
