### ISSUE TITLE
uploader组件预览属性file-list问题

### ISSUE THREAD

**Issue by liruili** [youzan/vant-weapp#3148]
file-list预览图集合属性对应的属性值名称只能是fileList，否则将不会起作用，请问这是什么情况，倘若一个页面中有两组图片上传的，这将没法使用

**Comment by rex-zsd** [comment]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater?repo=VantWeapp

**Comment by lys623** [comment]
> file-list预览图集合属性对应的属性值名称只能是fileList，否则将不会起作用，请问这是什么情况，倘若一个页面中有两组图片上传的，这将没法使用

请问解决了吗？我也遇到这个问题
