### ISSUE TITLE
SubmitBar 提交订单栏 Iphone X以上 显示问题

### ISSUE THREAD

**Issue by latiaoJW** [youzan/vant-weapp#3149]
SubmitBar 提交订单栏 
safe-area-inset-bottom 的padding应该给父元素（带background:#fff;）；不然会出现白背景高度没变导致字体溢出

**Comment by rex-zsd** [comment]
SubmitBar的`safe-area-inset-bottom`并不是用`padding`实现的，而是加入一个额外的元素用`height`实现的。
没有提供版本信息，是历史版本？可以升级到最新版本看下
