### ISSUE TITLE
[Feature Request] 希望增加暗黑模式

### ISSUE THREAD

**Issue by Satlantisy** [youzan/vant-weapp#3151]
### 这个功能解决了什么问题
手机端暗黑（夜晚）模式开始普及，希望组件能增加全局黑色模式，根据手机模式自动开启或者手动开启，同时希望能提供黑白两种的配色方案那就最好啦。

### 建议的API是什么样的
dark-mode

**Comment by rex-zsd** [comment]
这个目前暂时不会考虑呢
