### ISSUE TITLE
Sticky 粘性布局 问题

### ISSUE THREAD

**Issue by ColelAi** [youzan/vant-weapp#3152]
Sticky 粘性布局  应用到列表中会出问题，会加载缓慢，然后就出出现短暂未加载情况
详情图下图 http://imgs.kongjz.com/d45a0a14d2a459b7f94a3e8de04ce06.png

**Comment by rex-zsd** [comment]
看起来是手机性能不足导致的渲染问题，不像是组件的问题吧
