### ISSUE TITLE
Calendar如何动态设置formatter？

### ISSUE THREAD

**Issue by Hymango** [youzan/vant-weapp#3153]
虚心问一个问题

原生小程序，Calendar日历组件内，如何动态设置formatter（根据数据情况展示不同的效果）？

**Comment by rex-zsd** [comment]
`formatter`是个函数，在里面处理你的分支逻辑就可以。
可以扫码加群交流一下哈。

**Comment by Abbotton** [comment]
我也有这样的需求，当用户签到之后，将签到日期设置为选中状态，也就是formatter中`day`的type为middle或者start或者end.

**Comment by Abbotton** [comment]
@Hymango 经测试，可以通过动态设置formatter来解决这个问题。
```js
this.setData({
    formatter:function(){
        // 业务代码
    }
})
```

**Comment by Hymango** [comment]
@Abbotton 好的，谢谢。我也是尝试用这种方式处理的，没来得及close和回复。
