### ISSUE TITLE
Tab置于Popup里active样式初始化不显示

### ISSUE THREAD

**Issue by MiaNaNa** [youzan/vant-weapp#3155]
Tab标签页在放置于popup内部时，初始化进入页面的时active属性不显示，点击切换到其他tab时恢复正常，置于外部则没有这个问题。

**Comment by rex-zsd** [comment]
这个问题受限于小程序的机制，目前从组件库层面无法解决。
后面会新增文档说明来规避。

**Comment by MiaNaNa** [comment]
感谢您的回复，惊叹于你们的处理速度，希望vant生态发展的越来越好。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"rex"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月19日(星期二) 下午5:44
收件人:&nbsp;"youzan/vant-weapp"<vant-weapp@noreply.github.com&gt;;
抄送:&nbsp;"单葛尧"<shangeyao@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [youzan/vant-weapp] Tab置于Popup里active样式初始化不显示 (#3155)





 
这个问题受限于小程序的机制，目前从组件库层面无法解决。
 后面会新增文档说明来规避。

**Comment by rex-zsd** [comment]
可以这样处理，使得 van-tabs 内部的 ready 生命周期能够与实际渲染同步。
```html
<van-popup show="{{ show }}">
  <van-tabs wx:if="{{ show }}">
    <van-tab title="标签 1">内容 1</van-tab>
    <van-tab title="标签 2">内容 2</van-tab>
    <van-tab title="标签 3">内容 3</van-tab>
    <van-tab title="标签 4">内容 4</van-tab>
  </van-tabs>
</van-popup>
```

**Comment by ssly** [comment]
@rex-zsd 
<van-tabs wx:if="{{ show }}">，这个方法并不奏效

**Comment by rex-zsd** [comment]
@ssly 提供下代码，机型，截图等信息

**Comment by ssly** [comment]
![image](https://user-images.githubusercontent.com/24356145/88141087-7fe82d00-cc25-11ea-81a6-7e0baab30a79.png)
@rex-zsd 

是在Mac模拟器上面看的。
