### ISSUE TITLE
事件名称问题

### ISSUE THREAD

**Issue by happygx** [youzan/vant-weapp#3157]
在mpvue框架当中使用vant weapp中带-的事件不生效，但是将源码中的事件名称改为驼峰就可以正常使用了。
![image](https://user-images.githubusercontent.com/26782679/82193584-282cfd00-9928-11ea-92f6-97f595d0cd14.png

**Comment by rex-zsd** [comment]
https://github.com/Meituan-Dianping/mpvue/issues/1746
mpvue那边已经有反馈了，不过mpvue已经停止维护了，这个问题应该是无法解决了。

**Comment by rex-zsd** [comment]
只能手动修改源码为符合mpvue事件名的格式了。
