### ISSUE TITLE
[Help Wanted]Calendar日历formatter中能否内嵌html标签？

### ISSUE THREAD

**Issue by YLDJack** [youzan/vant-weapp#3160]
最近在做一个健身打卡的小程序，想要实现一个如下效果的日历：
![image](https://user-images.githubusercontent.com/16235124/82205743-9af2a400-9939-11ea-8fdb-2f2099b44486.png)
我想在 day.topInfo 和 day.bottomInfo 分别放上一个van-tag.想问一下大家在原生框架中，有没有什么好的方法实现？

**Comment by rex-zsd** [comment]
不可能，小程序目前不支持渲染html片段。

**Comment by StephenCMZ** [comment]
你好，请问问题解决了吗？

**Comment by YLDJack** [comment]
目前没有解决
