### ISSUE TITLE
[Bug Report] button组件disabled属性不能阻止再次点击吗

### ISSUE THREAD

**Issue by zhuo-xiang** [youzan/vant-weapp#3161]
### 设备
iOS 10.3.3

### VantWeapp 版本
1.3.0

### 基础库版本
2.11.0

### 请提供核心代码片段链接
https://youzan.github.io/vant-weapp/#/button

### 描述问题
button组件 用true和false控制 disabled 样式有变灰色, 但是不能阻止再次点击, 请问这个disabled只能控制button的样式嘛

**Comment by liushangdev** [comment]
可以控制 bind:click 不能控制 bindtap

**Comment by zhuo-xiang** [comment]
![WX20200519-105115](https://user-images.githubusercontent.com/61954852/82279369-f74bd700-99be-11ea-8cd4-1ccba87a8f94.png)
我觉得可以在这里再次写明一下
