### ISSUE TITLE
[Bug Report] van-popup显示错位问题

### ISSUE THREAD

**Issue by linkscope** [youzan/vant-weapp#3162]
### 设备
iPhone X

### VantWeapp 版本
1.3.0

### 基础库版本
2.11.0

### 请提供核心代码片段链接
https://developers.weixin.qq.com/s/7nlWNsmi74hC

### 描述问题
使用van-tabs创建四个标签导航，第四个标签是一个组件，当在第四个tab标签内使用van-popup弹出层会在第一个tab页显示

**Comment by rex-zsd** [comment]
目前是无解的，可以自行搜索一下`transform`与`position: fixed`的关系。
建议不要将popup等全局弹窗类的组件放置在tab内部。

**Comment by kiccer** [comment]
@rex-zsd 
以 `popup` 组件为例，目前是遮罩层和窗体为同级，两者都是固定定位，窗体自身有 `transform` 属性，导致窗体内的元素没法正常使用固定定位。我构思 `popup` 可否换种方式实现：

* 窗体为遮罩层的子元素
* 遮罩层通过 `flex` 将窗体居中或置顶或置底
* 窗体自身不需要固定定位和 `transform` 居中

这样改动后，不影响目前的功能，且窗体中的元素也可以正常使用固定定位功能了。

**Comment by rex-zsd** [comment]
> @rex-zsd
> 以 `popup` 组件为例，目前是遮罩层和窗体为同级，两者都是固定定位，窗体自身有 `transform` 属性，导致窗体内的元素没法正常使用固定定位。我构思 `popup` 可否换种方式实现：
> 
> * 窗体为遮罩层的子元素
> * 遮罩层通过 `flex` 将窗体居中或置顶或置底
> * 窗体自身不需要固定定位和 `transform` 居中
> 
> 这样改动后，不影响目前的功能，且窗体中的元素也可以正常使用固定定位功能了。

popup 是可以没有遮罩层的

**Comment by kiccer** [comment]
@rex-zsd
> > 以 `popup` 组件为例，目前是遮罩层和窗体为同级，两者都是固定定位，窗体自身有 `transform` 属性，导致窗体内的元素没法正常使用固定定位。我构思 `popup` 可否换种方式实现：
> > 
> > * 窗体为遮罩层的子元素
> > * 遮罩层通过 `flex` 将窗体居中或置顶或置底
> > * 窗体自身不需要固定定位和 `transform` 居中
> > 
> > 这样改动后，不影响目前的功能，且窗体中的元素也可以正常使用固定定位功能了。
> 
> popup 是可以没有遮罩层的

这没关系，也是可以实现的：

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        .mask {
            display: flex;
            justify-content: center;
            align-items: center;
            position: fixed;
            top: 50%;
            left: 50%;
            width: 0;
            height: 0;
        }

        .popup {
            width: 300px;
            max-width: 300px;
            min-width: 300px;
            min-height: 300px;
            background-color: #ccc;
            white-space: nowrap; /* 强制一行也不会让弹窗变大 */
        }
    </style>
</head>
<body>
    <button>这是一个按钮，可以点击</button>

    <div class="mask">
        <div class="popup">
            这是一个弹窗，没有遮罩，可以点击背后内容 <br>
            这是一个弹窗，没有遮罩，可以点击背后内容 <br>
            这是一个弹窗，没有遮罩，可以点击背后内容 <br>
            这是一个弹窗，没有遮罩，可以点击背后内容 <br>
            这是一个弹窗，没有遮罩，可以点击背后内容 <br>
            这是一个弹窗，没有遮罩，可以点击背后内容 <br>
            这是一个弹窗，没有遮罩，可以点击背后内容 <br>
            这是一个弹窗，没有遮罩，可以点击背后内容 <br>
            这是一个弹窗，没有遮罩，可以点击背后内容 <br>
            这是一个弹窗，没有遮罩，可以点击背后内容 <br>
            这是一个弹窗，没有遮罩，可以点击背后内容 <br>
            这是一个弹窗，没有遮罩，可以点击背后内容 <br>
            这是一个弹窗，没有遮罩，可以点击背后内容 <br>
            这是一个弹窗，没有遮罩，可以点击背后内容 <br>
            这是一个弹窗，没有遮罩，可以点击背后内容 <br>
            这是一个弹窗，没有遮罩，可以点击背后内容 <br>
            这是一个弹窗，没有遮罩，可以点击背后内容 <br>
        </div>
    </div>
</body>
</html>
```

**Comment by echokh** [comment]
> > @rex-zsd
> > 以 `popup` 组件为例，目前是遮罩层和窗体为同级，两者都是固定定位，窗体自身有 `transform` 属性，导致窗体内的元素没法正常使用固定定位。我构思 `popup` 可否换种方式实现：
> > 
> > * 窗体为遮罩层的子元素
> > * 遮罩层通过 `flex` 将窗体居中或置顶或置底
> > * 窗体自身不需要固定定位和 `transform` 居中
> > 
> > 这样改动后，不影响目前的功能，且窗体中的元素也可以正常使用固定定位功能了。
> 
> popup 是可以没有遮罩层的

请问这个问题修改过了吗？我也遇到了这个问题

**Comment by kiccer** [comment]
没有重新打开issues，应该是没有修改打算了= =

**Comment by echokh** [comment]
> 没有重新打开issues，应该是没有修改打算了= =
那你是怎么处理的？我把内容和tabs放在了同级，通过wx：if进行控制的
