### ISSUE TITLE
Tabbar固定在页面底部的时候 Tabbar以上内容无法拉到最底下

### ISSUE THREAD

**Issue by huoshidehua** [youzan/vant-weapp#3166]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater?repo=VantWeapp

**Comment by rex-zsd** [comment]
页面样式请自行调整哈，可以给底部加一个边距。
