### ISSUE TITLE
[Bug Report] datetime-picker组件，无故跳动bug

### ISSUE THREAD

**Issue by F5F5** [youzan/vant-weapp#3169]
### 设备
华为Mate 30 5G/华为Mate 30 Pro 5G

### VantWeapp 版本
1.3.0

### 基础库版本
2.11.0

### 如果是 UI 问题，截图链接（多图回车分隔）

![截图](https://sm.ms/image/CzjdB5F8YiD3qks)

### 请提供核心代码片段链接
https://gist.github.com/F5F5/ae5456911133d13e275307de5f176c6f

### 描述问题
华为手机，使用datetime-picker，会一直触发input事件，试了三台都会这样，三星和iPhone未复现
bug详情见动图
https://sm.ms/image/CzjdB5F8YiD3qks

**Comment by F5F5** [comment]
发现在华为手机上，confirm事件 执行早于 input和change事件？？？

**Comment by rex-zsd** [comment]
#3206
相同问题，可以关注下这个
