### ISSUE TITLE
[Bug Report] van-field 放在 van-dialog 中，弹出时 placeholder 的字会抖一下。

### ISSUE THREAD

**Issue by zkl2333** [youzan/vant-weapp#3172]
### 设备
开发者工具

### VantWeapp 版本
1.2.2

### 基础库版本
2.10.1

### 如果是 UI 问题，截图链接（多图回车分隔）

![截图](https://i.loli.net/2020/05/21/WVbCaUZBJuI3Nx8.gif)

### 请提供核心代码片段链接
https://gist.github.com/zkl2333/01cbc5792d850f838b00e519074894d3

### 描述问题
`van-field`放在`van-dialog`中，弹出时`placeholder`的字会抖一下。

**Comment by rex-zsd** [comment]
dialog内部有input时，`transition`属性不可以用默认的`scale`，否则会出现这个问题。
这个是由于小程序原生组件的特性导致的，不是组件库的问题。

**Comment by zkl2333** [comment]
> dialog内部有input时，`transition`属性不可以用默认的`scale`，可以使用`fade`或`none`，否则会出现这个问题。
> 这个是由于小程序原生组件的特性导致的，不是组件库的问题。

谢谢
