### ISSUE TITLE
[Bug Report] DropdownMenu下拉列表滑动到底后，下方页面会滚动

### ISSUE THREAD

**Issue by z1156727502** [youzan/vant-weapp#3173]
### 设备
华为p10pro

### VantWeapp 版本
1.3.0

### 基础库版本
^2.9.0

### 如果是 UI 问题，截图链接（多图回车分隔）

![截图](官方小程序示例有同样问题)

### 请提供核心代码片段链接
官方小程序示例有同样问题

### 描述问题
DropdownMenu下拉列表滑动到底后，下方页面会跟着滚动。
官方小程序示例有同样问题

**Comment by rex-zsd** [comment]
#3175
重复问题，可以关注那个issue
