### ISSUE TITLE
popup 组件滑动穿透

### ISSUE THREAD

**Issue by yufanhui999** [youzan/vant-weapp#3175]
使用popup 组件自定义弹窗（弹窗内部有滑动内容）之后，滑动时，能够滑动整个页面。

**Comment by SHUN-YI** [comment]
我也遇到过这个问题，希望尽早修复

**Comment by rex-zsd** [comment]
小程序的组件内部是无法修改全局样式的，所以这个问题组件内目前没有好的处理办法。

**Comment by rex-zsd** [comment]
后续会增加文档来说明如何规避这个问题。

**Comment by haliuhei** [comment]
popup弹出时给遮罩下元素添加 position:fixed
