### ISSUE TITLE
typescript 定义文件 哪里有维护？

### ISSUE THREAD

**Issue by nbsupermario** [youzan/vant-weapp#3177]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater?repo=VantWeapp

**Comment by rex-zsd** [comment]
`Dialog` `Toast`等提供的方法是有API定义的，组件的props、methods、这些都是没有定义的，因为小程序并不支持。
