### ISSUE TITLE
[Bug Report] van-field input type="number" type="digit"和微信官方是反的？

### ISSUE THREAD

**Issue by ChangeZhang** [youzan/vant-weapp#3178]
### 设备
华为mate30

### VantWeapp 版本
1.3.0

### 基础库版本
2.5.2

### 如果是 UI 问题，截图链接（多图回车分隔）

https://sm.ms/image/ha3HdMlAfTZ8jb4

https://sm.ms/image/9GYt4F3fUpuyQWC

### 请提供核心代码片段链接
https://sm.ms/image/9GYt4F3fUpuyQWC

### 描述问题
van-field input type="number" type="digit"和微信官方是反的？
微信官方 type="digit" 是带小数点的数字键盘
vant-weapp<van-field v-model="digit" type="digit" label="整数" /> 是整数 type="number" 是小数??

**Comment by rex-zsd** [comment]
`type`属性是透传的，没有任何处理，跟微信官方是一致的。
