### ISSUE TITLE
1.3.0的文档中，分类选中组件中有徽标的例子，但是无法实现。

### ISSUE THREAD

**Issue by hukuangjie** [youzan/vant-weapp#3181]
1.3.0的文档中，分类选中组件中有徽标的例子，但是无法实现。侧边导航的例子中也有徽标，且可以实现。

**Comment by rex-zsd** [comment]
分类选中是什么组件？请按格式提交issue。

你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater?repo=VantWeapp

**Comment by SnowWinterMaye** [comment]
![image](https://user-images.githubusercontent.com/10673970/83380470-9d143280-a410-11ea-97ae-751462a5ab98.png)

这个吧？  示例上有徽标，但是实际上没有api支持。
看了源码，tree-select 这个组件内 的  van-sidebar-item 未提供 dot或info相关的prop，所以实际上是不支持的。
不知道后学迭代有没有计划？

**Comment by hukuangjie** [comment]
> ![image](https://user-images.githubusercontent.com/10673970/83380470-9d143280-a410-11ea-97ae-751462a5ab98.png)
> 
> 这个吧？ 示例上有徽标，但是实际上没有api支持。
> 看了源码，tree-select 这个组件内 的 van-sidebar-item 未提供 dot或info相关的prop，所以实际上是不支持的。
> 不知道后学迭代有没有计划？

是的，就是这个问题。。。我在标题中把「分类选择」打成了「分类选中」

**Comment by 1207915357** [comment]
是的,我也碰到这个问题

**Comment by holmehai** [comment]
到源码的tree-select/index.wxml 里面新增这一段 可以新增数字徽标，点也相同，有个地方需要注意，van-sidebar的源码根据
info !== null来显示，所以0也会显示0，需要处理一下；

`    <van-sidebar active-key="{{ mainActiveIndex }}" bind:change="onClickNav" custom-class="van-tree-select__nav__inner">
      <van-sidebar-item
        **info="{{ item.info }}"**
        wx:for="{{ items }}"
        wx:key="index"
        custom-class="main-item-class"
        active-class="main-active-class"
        disabled-class="main-disabled-class"
        title="{{ item.text }}"
        disabled="{{ item.disabled }}"
      />
    </van-sidebar>`

**Comment by Eunknight** [comment]
> 到源码的tree-select/index.wxml 里面新增这一段 **info="{{ item.info }}"** 可以新增数字徽标，点也相同，有个地方需要注意，van-sidebar的源码根据info !== null来显示，所以0也会显示0，需要处理一下；
> 
> ` <van-sidebar active-key="{{ mainActiveIndex }}" bind:change="onClickNav" custom-class="van-tree-select__nav__inner"> <van-sidebar-item info="{{ item.info }}" wx:for="{{ items }}" wx:key="index" custom-class="main-item-class" active-class="main-active-class" disabled-class="main-disabled-class" title="{{ item.text }}" disabled="{{ item.disabled }}" /> </van-sidebar>`

处理0可以这么处理
info="{{ item.info?tiem.info:null }}
