### ISSUE TITLE
[Bug Report] dialog 文档错误 custom-class 在文档中写成了 class-name

### ISSUE THREAD

**Issue by GitHub-Haisheng** [youzan/vant-weapp#3183]
### 设备
开发设备

### VantWeapp 版本
1.3.0

### 基础库版本
2.11.0

### 请提供核心代码片段链接
https://gist.github.com/GitHub-Haisheng/8db74f5f9f729f3fd0659fbac236639b

### 描述问题
自定义的 属性写错  custom-class

**Comment by GitHub-Haisheng** [comment]
用函数的方法可以 className 在自己定义的样式中 需要增加 dialog-index-- 前缀  
background-color: red !important; 加 !important 才生效。 我再使用别的组建的时候 不用加 在这里耽搁了好久  可以在文档中备注一下
用 Props  class-name 的形式确实没有子定义的class

**Comment by GitHub-Haisheng** [comment]
多方试了一下  在方法中调用 dialog
Props 方式的 class-name 一直加不上

暂时使用是在 方法中就使用 Options 的 className  在书写样式的时候加 dialog-index-- 前缀 以及 !important

**Comment by rex-zsd** [comment]
额，文档没问题吧，你没理解外部样式类和props的区别…………
文档中有写在自定义组件中使用dialog，`class-name`是无效的。

**Comment by shiyuanzheng** [comment]
页面里使用也是无效，加dialog-index--可以解决
