### ISSUE TITLE
使用商品卡片和提交订单栏出现了遮挡错误

### ISSUE THREAD

**Issue by liuxianghua1** [youzan/vant-weapp#3184]

**Comment by liuxianghua1** [comment]
上传不了图片

**Comment by liuxianghua1** [comment]
![575A177B-BCB9-4188-9A15-832B9ABC8875](https://user-images.githubusercontent.com/52877028/82732207-5f434a00-9d3e-11ea-85b9-d344da023b0e.png)
![4D93C8F3-952C-499C-9E26-75D8406A215B](https://user-images.githubusercontent.com/52877028/82732208-679b8500-9d3e-11ea-8be7-cf4f15f25282.png)
![0D93D70F-9EE4-4396-8064-56DEF2745F07](https://user-images.githubusercontent.com/52877028/82732209-68ccb200-9d3e-11ea-8a86-8713816f0792.png)

**Comment by rex-zsd** [comment]
不是组件库的问题吧…………给页面上下留出固定空间就可以了
