### ISSUE TITLE
[Bug Report] calendar文档网页无法访问

### ISSUE THREAD

**Issue by YikSanChan** [youzan/vant-weapp#3187]
### 设备
macbook

### VantWeapp 版本
1.3.1

### 基础库版本
无关

### 请提供核心代码片段链接
https://youzan.github.io/vant-weapp/#/calendar

### 描述问题
https://youzan.github.io/vant-weapp/#/calendar 无法访问

**Comment by YikSanChan** [comment]
可以访问 https://vant-contrib.gitee.io/vant-weapp/#/calendar

我的ip是 136.25.26.108

与 https://github.com/youzan/vant/issues/5567 有关

**Comment by rex-zsd** [comment]
目前应该已经恢复了，昨天更新文档的时候似乎把calendar弄丢了。
