### ISSUE TITLE
[Bug Report] 使用van-dropdown-menu和scrollView后scrolView不可以滑动了

### ISSUE THREAD

**Issue by baiyidjp** [youzan/vant-weapp#3188]
### 设备
iPhoneX

### VantWeapp 版本
1.3.1

### 基础库版本
2.9.2

### 描述问题
			<van-dropdown-menu active-color="#5a2b81">
				<van-dropdown-item :value="currentRoomValue" :options="roomNameValues"></van-dropdown-item>
			</van-dropdown-menu>
			<scroll-view scroll-y="true" :show-scrollbar="true" :style="{height: '600px'}"></scroll-view>

跟scrollView同级，为了不滑动dropdown，正常滑动没我让你踢，但是点击一次dropdown后，scrollView就不可滑动了，整个小程序卡死

**Comment by baiyidjp** [comment]
找到原因了，是因为z-index默认为10，点击之后再消失虽然overflow:hidden，但是还占有位置，scrollView无法滑动，我在调试的时候把z-index取消就可以滑动，但是看源码使用z-index的地方是方法，无法在外部动态的改变。
请教一个解决方案

**Comment by baiyidjp** [comment]
现在我在item的index.js中修改了源码解决了，外部改变z-index
`    toggle(show, options = {}) {
      const { showPopup } = this.data;
      if (typeof show !== 'boolean') {
        show = !showPopup;
      }
      if (show === showPopup) {
        return;
      }
      this.setData({
        transition: !options.immediate,
        showPopup: show,
      });
      if (show) {
        this.parent.getChildWrapperStyle().then((wrapperStyle) => {
          this.setData({ wrapperStyle, showWrapper: true });
          this.rerender();
        });
      } else {
				this.parent.getChildWrapperStyle().then((wrapperStyle) => {
				  this.setData({ wrapperStyle, showWrapper: false });
				  this.rerender();
				});
        // this.rerender();
      }
    },`

**Comment by baiyidjp** [comment]
现在我在item的index.js中修改了源码解决了，外部改变z-index
![image](https://user-images.githubusercontent.com/12672573/82775330-fb25a080-9e79-11ea-95d1-99e4dda61487.png)

**Comment by rex-zsd** [comment]
`z-index`是 dropdown-menu 的 prop，可以在外部设置的。

**Comment by baiyidjp** [comment]
> `z-index`是 dropdown-menu 的 prop，可以在外部设置的。

是可以设置，外部设置了，内部不会更新，所以我在这个地方让menu消失的时候在重新获取一下子组件的样式，拿到最新的z-index
