### ISSUE TITLE
[Bug Report] Slider onDrag 会报warning

### ISSUE THREAD

**Issue by zkl2333** [youzan/vant-weapp#3189]
### 设备
ide

### VantWeapp 版本
1.3.1

### 基础库版本
2.11.1

### 请提供核心代码片段链接
https://developers.weixin.qq.com/s/vrrvFBmE7ghF

### 描述问题
```
VM475:1 Component "index/index" does not have a method "onDrag" to handle event "drag".
```

**Comment by rex-zsd** [comment]
wxml中定义了`bind:drag="onDrag"`，但是js中没有定义`onDrag`方法，非组件问题。

**Comment by zkl2333** [comment]
> wxml中定义了`bind:drag="onDrag"`，但是js中没有定义`onDrag`方法，非组件问题。

在`index.js`中定义了`onDrag`的，您再看看代码片段,，我检查过了。

**Comment by rex-zsd** [comment]
确认了一下，这个warn只在页面初始化的时候会报一次，意思是页面内没有定义方法来处理`drag`事件。
但是后续的功能是正常的，推测是微信侧的问题。
