### ISSUE TITLE
swipe-cell组件，点击van-swipe-cell之外位置无法触发onClose事件

### ISSUE THREAD

**Issue by changziyu** [youzan/vant-weapp#3193]
VantWeapp 版本
1.3.0

基础库版本
2.11.0

请提供核心代码片段链接

  onClose(event) {
    let filepath = event.target.dataset.filepath
    const {
      position,
      instance
    } = event.detail;
    
    switch (position) {
      case 'left':
      case 'cell':
      case 'outside':
        instance.close()
        break;
      case 'right':
        Dialog.confirm({
          message: '确定删除吗？',
        }).then(() => {
          this.data.notes.splice(this.data.notes.findIndex(e => e.filePath === filepath), 1)
          wx.setStorageSync('notes', this.data.notes)
          this.updateNotes()
          instance.close()
          Toast.success('删除成功')
        });
        break;
    }
  },

描述问题
循环显示多条数据，点击当前条目左侧，中间、右侧都可以触发关闭事件。但是第其它条目或页面其它部分时，无法触发关闭事件。页面效果一直停在滑出后不动

![image](https://user-images.githubusercontent.com/6790811/82790863-5cac3600-9e9f-11ea-91b6-43982d20f444.png)

![image](https://user-images.githubusercontent.com/6790811/82790661-017a4380-9e9f-11ea-8400-87cace82433e.png)

**Comment by rex-zsd** [comment]
小程序是不支持`position: outside `的，因为小程序不支持动态监听整个页面的点击事件。
