### ISSUE TITLE
[Bug Report] dropdownMenu

### ISSUE THREAD

**Issue by honglb** [youzan/vant-weapp#3197]
### 设备
微信开发者工具

### VantWeapp 版本
1.3.1

### 基础库版本
2.9.2

### 请提供核心代码片段链接
https://gitee.com/gdh1027/codes/h2mepkybrqxcw9aondsij18

### 描述问题
自定义内容部分会出现点击无效， 在点击第一个dropdownitem, 在点击后一个，全一个dropdownitem会点击无效

**Comment by Lindysen** [comment]
看不了代码片段

**Comment by honglb** [comment]
> 看不了代码片段



> 看不了代码片段

现在可以看了吗 我刚才点了下 可以看

**Comment by rex-zsd** [comment]
@honglb 
访问是404的，用微信开发者工具上传一下代码片段吧。

**Comment by honglb** [comment]
用的uni-app，微信开发者工具的代码片段没用过，我发个附件给你吧，看下能重现不




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"rex"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月27日(星期三) 下午3:35
收件人:&nbsp;"youzan/vant-weapp"<vant-weapp@noreply.github.com&gt;;
抄送:&nbsp;"簡丶"<1145206050@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [youzan/vant-weapp] [Bug Report] dropdownMenu (#3197)





 
@honglb
 访问是404的，用微信开发者工具上传一下代码片段吧。

**Comment by lyq027** [comment]
同上，出现一样的问题。两个dropdownitem,先点击前一个dropdownitem时正常，然后点击后一个dropdownitem，再想点击前一个dropdownitem就无反应了。后一个dropdownitem还正常

**Comment by BoqinDu** [comment]
我也遇到了上楼说的问题。两个dropdownitem,先点击前一个dropdownitem时正常，然后点击后一个dropdownitem，再想点击前一个dropdownitem就无反应了。我试了如果是三个的话 只要点了最后一个，前两个都不能点了请问这么解决

**Comment by rex-zsd** [comment]
所以…………没有一个人上传代码片段吗…………

**Comment by honglb** [comment]
> 所以…………没有一个人上传代码片段吗…………

突然发现在uni-app中才会这样， 我贴了你们的自定义内容的官网代码也会这样，后一个dropdownitem会让前一个dropdownitem的点击无效

**Comment by 2013z** [comment]
同上...点了一个事件可以用 然后再点另一个菜单，还是可以用，再切回原来的菜单，就点击无法触发了.....

**Comment by 2013z** [comment]
有人解决了吗，好闹心啊。用分类选择树来套用item就没有问题了，暂时这样搞。稍微看了一下 好像是层级覆盖的问题导致的。第二次回点的时候zindex导致的问题...

**Comment by honglb** [comment]
> 有人解决了吗，好闹心啊。用分类选择树来套用item就没有问题了，暂时这样搞。稍微看了一下 好像是层级覆盖的问题导致的。第二次回点的时候zindex导致的问题...

没有， 自己手撸了个， 你想解决给他提供下你的代码片段，我的不知道为啥看不了

**Comment by auven** [comment]
我这样修改之后就可以了， https://github.com/youzan/vant-weapp/issues/3277#issuecomment-643557710

**Comment by rex-zsd** [comment]
至今没有人能够上传可用的代码片段，甚至没有人在issue中贴任何代码。
先关闭了

**Comment by auven** [comment]
是 uni-app 底层的问题，已给他们提交 [issues](https://github.com/dcloudio/uni-app/issues/1802) 了，暂时可以将 `@vant/weapp/dropdown-item/index.wxml` 里面的 `van-popup` 的事件改成驼峰写法 `afterEnter` 和 `afterLeave` 就可以了
