### ISSUE TITLE
[Bug Report] 可关闭的标签如何使用？怎么接关闭事件？

### ISSUE THREAD

**Issue by LittleRain** [youzan/vant-weapp#3200]
### 设备
小程序

### VantWeapp 版本
1.3.1

### 基础库版本
无

### 请提供核心代码片段链接
https://github.com/LittleRain/uistone

### 描述问题
可关闭的标签如何使用？怎么接关闭事件？在文档中没有相关的描述

**Comment by Lindysen** [comment]
看不了核心代码片段

**Comment by LittleRain** [comment]
> 看不了核心代码片段

核心片段和我的问题没什么大关系，现在不知道怎么用关闭的标签，所以代码里还没有加这块的功能

**Comment by rex-zsd** [comment]
这部分的文档有缺失，我们会尽快补充一下
