### ISSUE TITLE
van-button在disabled情况下不应该有点击效果（背景色变化）

### ISSUE THREAD

**Issue by kevincwj2008** [youzan/vant-weapp#3201]
在小程序中使用van-button，disabled情况下，点击按钮有背景色变化的效果，但是demo上没有，直接把demo的按钮复制到小程序中，也是有点击效果的

**Comment by Lindysen** [comment]
Button 提供的是 click 事件而不是原生 tap 事件，按钮禁用时，click 事件不会触发，tap 事件依然会触发。
