### ISSUE TITLE
[Feature Request] Uploader 可否会增加上传图片时，自定义裁剪固定尺寸功能？

### ISSUE THREAD

**Issue by cgChen1995** [youzan/vant-weapp#3202]
### 这个功能解决了什么问题
业务需求

### 建议的API是什么样的
Uploader 可否会增加上传图片时，裁剪固定尺寸功能？（裁剪的时候，图片可以自由拖动裁剪区域）

**Comment by rex-zsd** [comment]
暂时不会实现图片裁剪，可以自行实现以下。
从 van-uploader 拿到图片以后自行在canvas上做裁剪即可。
