### ISSUE TITLE
DropdownMenu后续是否增加排序功能，以及只有文字的功能

### ISSUE THREAD

**Issue by HalcyonDaysssss** [youzan/vant-weapp#3203]
DropdownMenu后续是否增加排序功能，以及只能文字的功能
效果如下
![image](https://user-images.githubusercontent.com/24239032/82874038-fb9c6500-9f67-11ea-992a-44f1a0458d69.png)

**Comment by Lindysen** [comment]
这边不太理解你想要的 feature 希望表达更具体点

**Comment by HalcyonDaysssss** [comment]
新增一个类似价格排序的功能，你看我发的图，价格旁边有排序的图片，点击升序降序

**Comment by rex-zsd** [comment]
暂时不会支持排序，这个交互与dropdown-menu的点击切换是冲突的。
