### ISSUE TITLE
[Feature Request] Instance.method 无校验类型

### ISSUE THREAD

**Issue by luckymore** [youzan/vant-weapp#3205]
### 这个功能解决了什么问题
![image](https://user-images.githubusercontent.com/5390013/82886983-e8929080-9f79-11ea-8ecf-7f220efe5a2f.png)
1. this.get(1) 校验类型 
2. this上的属性，有代码提示

### 建议的API是什么样的
packages/definitions/index.ts 30行，改成这样，可以
```js
  methods?: Methods & ThisType<CombinedComponentInstance<Data, Props, Methods>>;
  // methods?: Methods & Weapp.MethodOption<Instance>;
```

**Comment by rex-zsd** [comment]
#3924 已支持
