### ISSUE TITLE
van-popup  overlay

### ISSUE THREAD

**Issue by nggl** [youzan/vant-weapp#3210]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater?repo=VantWeapp
the wx, using form and `van-field`, van-field[type=textarea]; as time, the field placeholer while through the overlay. like this ...
![QQ图片20200527162504](https://user-images.githubusercontent.com/42204800/82995797-a7ac8180-a036-11ea-8e96-ae0623d83b00.jpg)

**Comment by rex-zsd** [comment]
目前无解，[文档](https://youzan.github.io/vant-weapp/#/field#chang-jian-wen-ti)有说明，可以看一下。
