### ISSUE TITLE
[Feature Request] VantWeap list组件

### ISSUE THREAD

**Issue by tianr1190** [youzan/vant-weapp#3211]
### 这个功能解决了什么问题
在1.3.1的版本中，没有找到list组件，不知道是开发者们遗漏了还是出于什么原因没有做VantWeap的list组件。

### 建议的API是什么样的
比如文章的列表，或者图文类型的列表，或者是图片列表之类的。

**Comment by Satlantisy** [comment]
用panel grid cell 或者其他组件很快就能搭一个出来

**Comment by rex-zsd** [comment]
list是需要监听页面的滚动事件的，在小程序内实现很复杂。
可以自行用其他组件拼一下哈。
