### ISSUE TITLE
uni-app打包vant组件库报错

### ISSUE THREAD

**Issue by xuxiaoyang883** [youzan/vant-weapp#3217]
![批注 2020-05-29 105326](https://user-images.githubusercontent.com/46732297/83216833-cd539b00-a19c-11ea-92bf-229950f0f479.jpg)
:class 不支持 utils.bem('checkbox__icon',[shape,{disabled,checked:value}]) 语法

**Comment by rex-zsd** [comment]
这里vant weapp使用了wxs的，可以去uni-app咨询下是否能够支持，非组件库问题哈。
