### ISSUE TITLE
[Bug Report] nav-tabs中有scroll-view,下拉刷新失效

### ISSUE THREAD

**Issue by LCBbest** [youzan/vant-weapp#3220]
### 设备
模拟器，真机

### VantWeapp 版本
1.3.1

### 基础库版本
1.3.1

### 请提供核心代码片段链接
https://developers.weixin.qq.com/s/SdhEyemT7ngr

### 描述问题
nav-tabs中添加scroll-view,下拉刷新失效。单独拿出scroll-view就可以

**Comment by rex-zsd** [comment]
微信的问题导致的，可以把scroll-view外置到tabs外部使用。

**Comment by LCBbest** [comment]
> 微信的问题导致的，可以把scroll-view外置到tabs外部使用。

你好有具体的例子吗，怎么放到外面呢，是否会影响正常的tab使用
