### ISSUE TITLE
微信使用问题反馈

### ISSUE THREAD

**Issue by zack542** [youzan/vant-weapp#3223]
问题一：
    如下代码
<van-grid column-num="3" icon-size="5rem" > <van-grid-item badge="100" icon="https://yanxuan.nosdn.127.net/c6fd8835a6400b7da7a016ad85506b69.png" text="文字" /> <van-grid-item icon="photo-o" text="文字" /> <van-grid-item icon="photo-o" text="文字" /> <van-grid-item icon="photo-o" text="文字" /> </van-grid>
在网页中能正常生效badge和 icon-size 但是在微信小程序中缺不能生效，无法改变里面图片的大小
我导入的组件如下
`{
"navigationBarBackgroundColor":"#00BEAF",
"usingComponents": {
"van-grid": "/dist/grid/index",
"van-grid-item": "/dist/grid-item/index"

}
}`
最开始我以为是我代码问题，结果我去下载了官方示例程序vant-weapp ，然后直接在vant-weapp的example中去 加上这两个属性也无效，如果无效我该这么设置图片大小
问题二：
 在问题一的基础上，我直接去设置van-grid-item 的样式也是无效的。。。。。。
需求：要么van-grid-item 能够比较好的实现比如京东淘宝那个图片文字比列，然后可以自由控制图片圆角以及透明，要么可以提供很方便的控制方法控制图片大小。

**Comment by rex-zsd** [comment]
问题一下个版本会新增`icon-size`和`badge`属性。
问题二可以看下文档中样式覆盖部分来自定义样式。
