### ISSUE TITLE
[Bug Report] van-tab 中使用 popup，ios 真机popup 会被覆盖。

### ISSUE THREAD

**Issue by NiLinli** [youzan/vant-weapp#3225]
### 设备
iphone8

### VantWeapp 版本
1.3.1

### 基础库版本
2.11.1

### 如果是 UI 问题，截图链接（多图回车分隔）

![截图](https://i.loli.net/2020/06/01/CzQpT8GMbncEd2v.png)

![截图](https://i.loli.net/2020/06/01/jtcqJbkzWRKfCiO.png)

### 请提供核心代码片段链接
https://gist.github.com/NiLinli/289a6738b9e3c9a392eb7673af89610f

### 描述问题
在 van-tab 标签内部放入 popup 相关的组件, popup 在模拟器上面显示正常，在ios 真机上面只会显示van-tab 高度的那一部分，其余的部分被覆盖了。

**Comment by NiLinli** [comment]
![模拟器](https://user-images.githubusercontent.com/25059127/83380986-05174880-a412-11ea-9dd4-6d48d371d4d2.png)
![真机ios](https://user-images.githubusercontent.com/25059127/83380997-0a749300-a412-11ea-845f-10e494dc4737.png)

**Comment by york17** [comment]
我这边也出现了同样的问题。目前van-tab的页面中使用组件，并且组件中使用popup，（popup里面加入actionsheet、picker等），会被底部的一些区域给挡住。设置了 popup的z-index也没有效果。
测试了一下，是在组件中使用popup会这样，但是在最外层，添加popup不会出现。

**Comment by Edward-Zhou** [comment]
遇到同样的问题，van-tab 加popup时，组件中使用popup会显示空白，把popup放到最外层可以显示，但是小程序背景会变成全黑。

**Comment by rex-zsd** [comment]
建议是不要把 popup 嵌套在 tab 内使用，因为 tab 内使用了 `transform` 样式，会对 `position: fixed`产生影响。
这个属于 CSS 规范的一部分，可以查询一下相关的文章。

**Comment by rex-zsd** [comment]
这种场景可以尝试把内容整体放到 tab 外面，仅用 tab 做标题部分。
