### ISSUE TITLE
<van-field>的type="digit" ，请问支持负数吗？

### ISSUE THREAD

**Issue by babizhu** [youzan/vant-weapp#3226]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater?repo=VantWeapp

<van-field>的type="digit" ，请问支持负数吗？

**Comment by rex-zsd** [comment]
`type=digit` 时field的行为与原生input是相同的。据我所知，应该是不支持负数的。
