### ISSUE TITLE
[Feature Request] 建议uploader组件增加视频预览的功能

### ISSUE THREAD

**Issue by shiyu123** [youzan/vant-weapp#3227]
### 这个功能解决了什么问题
上传视频的时候，可以像上传图片一样，展示视频的缩略图（在中间加个播放按钮用来区分图片），且具备预览功能（点击视频缩略图时video全屏并播放）。

### 建议的API是什么样的
增加一些输入属性，用来控制全屏video的输入属性以及是否开启视频预览等等。

**Comment by TomSonghang** [comment]
是啊 ,现在上传时经常同时又视频和图片两个结合,不过我昨天自己重新修改了这个组件,获取封面图之后再这个图片上加个播放的icon,然后点击该图片跳转新页面播放;

**Comment by younth** [comment]
mark

**Comment by TomSonghang** [comment]
> 是啊 ,现在上传时经常同时又视频和图片两个结合,不过我昨天自己重新修改了这个组件,获取封面图之后再这个图片上加个播放的icon,然后点击该图片跳转新页面播放;

我自个重新在组件上进行了调整,支持上传视频和预览;

**Comment by rex-zsd** [comment]
#3594 挺早之前已经有 pr 支持了，忘了关闭这个 issue……

**Comment by Git-zyn-Hub** [comment]
在哪里增加isVideo属性啊？我在before-read或after-read给file加上isVideo都不行。需要更新到某个版本号吗？
