### ISSUE TITLE
[Bug Report] 下拉菜单无法触发打开事件

### ISSUE THREAD

**Issue by SHUN-YI** [youzan/vant-weapp#3233]
### 设备
小米6

### VantWeapp 版本
1.3.1

### 基础库版本
2.10.4

### 请提供核心代码片段链接
https://github.com/youzan/vant-weapp/blob/dev/example/pages/dropdown-menu/index.js

### 描述问题
下拉菜单无法触发打开和关闭事件
用bindopen不行，bindclosed也不行。

<view class="swiper-tab" >
      <van-dropdown-menu active-color="#fea424"  style="position:relative; width:100%;" >
        <van-dropdown-item value="{{ value1 }}"  options="{{ stairClass }}" bindchange='onchange1' bindopen='openDropDown' bindclosed="closeDropDown"/>
        <van-dropdown-item value="{{ value2 }}"  options="{{ showSecondaryClass }}" bindchange='onchange2' bindopen='openDropDown' bindclosed="closeDropDown"/>
      </van-dropdown-menu>
    </view>

### 疑问
是不是我写法问题？

**Comment by rex-zsd** [comment]
实测没有问题，可以正常触发，因为没有提供代码，所以帮不了你更多了。
可以检查一下是不是事件挂错了节点，事件是在dropdown-item上触发的。
