### ISSUE TITLE
[Feature Request] 微信小程序的Uploader组件可否提供外部样式用于覆盖删除按钮icon和上传区域的样式

### ISSUE THREAD

**Issue by Sramler** [youzan/vant-weapp#3234]
### 这个功能解决了什么问题
微信小程序的Uploader组件可否提供外部样式用于覆盖删除按钮icon和上传区域的样式

### 建议的API是什么样的
提供外部样式用于覆盖删除按钮icon和上传区域的样式

**Comment by rex-zsd** [comment]
可以查看一下文档样式覆盖部分，解除一下样式隔离，就可以覆盖样式了。
