### ISSUE TITLE
请问是否有计划支持暗黑模式？

### ISSUE THREAD

**Issue by pampa0629** [youzan/vant-weapp#3237]
自己一个个设置颜色太费劲了，最好能有一个统一的开关配置，就如同微信小程序官方的做法：“"darkmode":true”。谢谢

你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater?repo=VantWeapp

**Comment by rex-zsd** [comment]
暂时没有计划哦
小程序的 `darkmode` 也是需要手动指定 `theme.json` 配置的。
