### ISSUE TITLE
[Bug Report] circle 组件设置 type="2d" 时动态改变值，手机上显示空白

### ISSUE THREAD

**Issue by Teemwu** [youzan/vant-weapp#3239]
### 设备
小米6，iPhone7

### VantWeapp 版本
1.3.2

### 基础库版本
2.11.1

### 如果是 UI 问题，截图链接（多图回车分隔）

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/16522288/83726684-78b98f80-a676-11ea-92ba-d30ed3986ed2.gif)

### 请提供核心代码片段链接
https://github.com/youzan/vant-weapp/blob/dev/example/pages/circle/index.js

### 描述问题
运行官方 example 时，circle 组件设置 type="2d" 并动态改变值，手机上圆环显示空白

**Comment by rex-zsd** [comment]
确实，模拟器上ok，但是真机上会出现这个问题
