### ISSUE TITLE
NoticeBar 通告栏 支持无缝滚动么

### ISSUE THREAD

**Issue by ding-love-yu** [youzan/vant-weapp#3241]
现在公告滚动结束之前有大量留白 是否可以做到无缝滚动呢
![image](https://user-images.githubusercontent.com/16078611/83726931-d8b03600-a676-11ea-9e75-45ac8e92be24.png)
现在我的解决办法是重复公告内容100次然后再赋值给公告组件，这不过是一个取巧的行为，希望有支持无缝滚动的参数0.0

**Comment by rex-zsd** [comment]
暂时不会在组件内支持呢，还是自行实现一下哈。
