### ISSUE TITLE
[Bug Report] uploader 点击删除触发上传

### ISSUE THREAD

**Issue by shiyu123** [youzan/vant-weapp#3243]
### 设备
开发者工具、华为 Nova 5 Pro

### VantWeapp 版本
1.3.2

### 基础库版本
2.11.1

### 请提供核心代码片段链接
https://youzan.github.io/vant-weapp/#/uploader

### 描述问题
uploader 点击最后一张预览图的删除按钮时会触发上传

**Comment by jeffWorker** [comment]
1.是否实现bind:delete
2.bind:tap ->catch:tap
