### ISSUE TITLE
IndexBar 索引栏

### ISSUE THREAD

**Issue by nslgit** [youzan/vant-weapp#3244]
### 这个功能解决了什么问题
当设置了【van-index-bar】的父标签样式为固定高度和超出可以滚动后，IndexBar 索引栏的效果丢失（无法检测到滚动事件）
父标签样式：{height: calc300rpx;overflow: scroll;}
<viwe>
<van-index-bar scroll-top="{{ scrollTop }}">
		<view wx:for="{{ indexList }}" wx:for-item="item" wx:key="item">
			<van-index-anchor index="{{ item }}" />
			<van-cell title="文本" />
			<van-cell title="文本" />
			<van-cell title="文本" />
		</view>
</van-index-bar>
</view>

### 建议的API是什么样的
这个会限制一些场景的使用，如果可以希望能够完善它

**Comment by rex-zsd** [comment]
很可惜，这个无法支持。
index-bar监听的是页面的滚动，因为受限于小程序的API。不可能找到最近可滚动的父元素，也不能监听任意可滚动元素的滚动事件。
随意设置元素内滚动，是会有问题的。
