### ISSUE TITLE
Field 输入框，使用tpe='digit'时，iOS调起纯数字键盘，输入数字时，键盘一直闪，

### ISSUE THREAD

**Issue by zhaoqiucui** [youzan/vant-weapp#3245]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater?repo=VantWeapp

**Comment by rex-zsd** [comment]
键盘这个不是组件可以控制的，是小程序原生行为。
