### ISSUE TITLE
[Feature Request]希望组件内能使用rpx

### ISSUE THREAD

**Issue by Satlantisy** [youzan/vant-weapp#3246]
这个功能解决了什么问题

在不同尺寸的手机设备上布局视觉统一。

建议的API是什么样的

在组建内增加一个prop，或者全局配置 比如size-unit: px / rpx

**Comment by rex-zsd** [comment]
rpx暂时不会直接支持，可以搜下历史issue，使用编译转换的方式将px转为rpx。
