### ISSUE TITLE
建议增加 “Sku 商品规格” 组件

### ISSUE THREAD

**Issue by huangfengjing** [youzan/vant-weapp#3247]
vant移动版的这个组件非常好用：https://youzan.github.io/vant/#/zh-CN/sku
但是在 weapp 版本中没有，希望能支持

**Comment by mw248** [comment]
还有其它的业务组件，像address,coupon这些都非常好使，希望能同步增加

**Comment by cuzfinal** [comment]
是的，需要这个组件。

**Comment by Lindysen** [comment]
暂无计划支持
