### ISSUE TITLE
search组件中添加view作为label的slot，可以对这个view进行监听吗？

### ISSUE THREAD

**Issue by BEATING-HEART** [youzan/vant-weapp#3248]
你好，我在search组件中，添加了一个view组件，作为label的slot，然后，我希望对这个view组件进行bindtap事件监听，然而我失败了。请问是不是不支持这样用呀

**Comment by rex-zsd** [comment]
监听自己的view肯定是可以的，估计是代码姿势的问题。
可以扫下项目首页的二维码加群沟通一下。
