### ISSUE TITLE
van-tabs与scroll-view 结合自适应问题（百分比）

### ISSUE THREAD

**Issue by pursuelu** [youzan/vant-weapp#3251]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater?repo=VantWeapp

百分比传承到van-tabs中就出现问题了，如果van-tabs换成百分比的view就没问题，所以基本确认需要设置van-tabs

**Comment by rex-zsd** [comment]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater?repo=VantWeapp
