### ISSUE TITLE
[Bug Report] uploader组件的after-read方法在真机和微信开发者工具中的执行顺序不一致

### ISSUE THREAD

**Issue by chilo-hzl** [youzan/vant-weapp#3252]
### 设备
荣耀V20

### VantWeapp 版本
1.3.2

### 基础库版本
2.11.1[410]

### 请提供核心代码片段链接
https://github.com/chilo-hzl/codeBUG_link/blob/master/uploader%E7%BB%84%E4%BB%B6%E5%9C%A8%E7%9C%9F%E6%9C%BA%E5%92%8C%E5%BC%80%E5%8F%91%E8%80%85%E5%B7%A5%E5%85%B7%E4%B8%AD%E7%9A%84%E6%89%A7%E8%A1%8C%E9%A1%BA%E5%BA%8F%E4%B8%8D%E4%B8%80%E8%87%B4

### 描述问题
在微信开发者工具中，执行uploader的after-read方法时先执行了onShow方法，后执行了after-read的方法

在真机环境下执行uploader的after-read方法时先执行了after-read方法，后执行了onShow方法，

**Comment by rex-zsd** [comment]
会有什么影响吗？这个行为估计跟微信有关系

**Comment by chilo-hzl** [comment]
> 会有什么影响吗？这个行为估计跟微信有关系

因为我的写的代码逻辑跟执行顺序有关，所以不一样的话代码会不被正确执行

我今天又用iphone x真机调试了一下，和微信开发者工具端的执行的顺序一致，估计是安卓端和苹果端的差异，而开发者工具模拟环境更接近于iPhone，但我这只是猜测，因为我没有用大量的安卓机和苹果机做测试

我打算换一个思路重新写逻辑，官方人员如果觉得这算不上是一个issue的话可以关闭这个issue

**Comment by TomSonghang** [comment]
页面的onShow事件好像跟哪个端没关系吧,不过onShow事件确实不好控制,我很少用它,以前修改完下一个页面,返回需要刷新用到,现在跳转api也加上了页面通信了
