### ISSUE TITLE
uni+vue+ts 开发, vant-webapp具体怎么使用呢?

### ISSUE THREAD

**Issue by lz-web** [youzan/vant-weapp#3253]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。
1. 目前用uni+vue+ts 开发了一个新项目, 因为要兼容h5端, 考虑用vant-weapp的时候, 小程序和h5有两个开发版本,现在不知道该如何使用, 如果有解决方案请告知
2. 看到已有一个关于mpvue的issues,  但是和vuecli 创建的项目使用不太一致
总而言之,就是想知道在vue+uni的开发里可以使用vant-weapp吗? 如何使用? 如果不能,可以给个建议吗

**Comment by lz-web** [comment]
![image](https://user-images.githubusercontent.com/55732016/83984583-5c646e00-a968-11ea-8ed6-4ac74ad0432e.png)

**Comment by rex-zsd** [comment]
这个库不是vant weapp团队开发的，应该是基于vant weapp修改的，可以去那边咨询一下哈。
