### ISSUE TITLE
tabs sticky属性在navbar custom情况下距离有问题

### ISSUE THREAD

**Issue by WuJiY** [youzan/vant-weapp#3255]
"navigationStyle": "custom", 情况下 tabs 如果设置sticky 距离顶部 距离会有问题
![image](https://user-images.githubusercontent.com/183884/83993348-b9bae800-a985-11ea-8d25-89ea2c42ed49.png)
上面的字都没了

**Comment by rex-zsd** [comment]
`"navigationStyle": "custom"` 的状态下，顶部状态栏也会算入整个页面。
可以给 van-tabs 组件设置 `offset-top` 属性，留出顶部状态栏的高度即可。
比如这样
```
<van-tabs sticky offset-top="{{ 44 }}">
  ...
</van-tabs>
```

**Comment by WuJiY** [comment]
谢谢

**Comment by sbbs3626** [comment]
> `"navigationStyle": "custom"` 的状态下，顶部状态栏也会算入整个页面。
> 可以给 van-tabs 组件设置 `offset-top` 属性，留出顶部状态栏的高度即可。
> 比如这样
> 
> ```
> <van-tabs sticky offset-top="{{ 44 }}">
>   ...
> </van-tabs>
> ```
> 
> 具体的值看你页面顶部的高度而定

这个不同机型的只能通过JS来计算吗？

**Comment by rex-zsd** [comment]
> > `"navigationStyle": "custom"` 的状态下，顶部状态栏也会算入整个页面。
> > 可以给 van-tabs 组件设置 `offset-top` 属性，留出顶部状态栏的高度即可。
> > 比如这样
> > ```
> > <van-tabs sticky offset-top="{{ 44 }}">
> >   ...
> > </van-tabs>
> > ```
> > 
> > 
> > 具体的值看你页面顶部的高度而定
> 
> 这个不同机型的只能通过JS来计算吗？

不需要 JS 呀，你的自定义状态栏是多高，就设置多少就可以了

**Comment by sbbs3626** [comment]
> > > `"navigationStyle": "custom"` 的状态下，顶部状态栏也会算入整个页面。
> > > 可以给 van-tabs 组件设置 `offset-top` 属性，留出顶部状态栏的高度即可。
> > > 比如这样
> > > ```
> > > <van-tabs sticky offset-top="{{ 44 }}">
> > >   ...
> > > </van-tabs>
> > > ```
> > > 
> > > 
> > > 具体的值看你页面顶部的高度而定
> > 
> > 
> > 这个不同机型的只能通过JS来计算吗？
> 
> 不需要 JS 呀，你的自定义状态栏是多高，就设置多少就可以了

navbar ip8下高度是66，ip x+下高度是88，刚看了文档，没看到可以自定义navbar高度
