### ISSUE TITLE
使用van-field组件属性为clearable的时候，小程序控制台有警告

### ISSUE THREAD

**Issue by liumaowen** [youzan/vant-weapp#3257]
`<van-field  clearable />`

![{E2143809-DA33-48BE-8BED-B746BB4DD435}_20200609093628](https://user-images.githubusercontent.com/33195986/84096574-d95d1980-aa34-11ea-8eb5-e78511657903.jpg)

**Comment by 1sm23** [comment]
`clearable="{{true}}"`试试

**Comment by liumaowen** [comment]
@1sm23 没有变化，还是会有警告，应该是组件里的代码有问题，定位到组件代码片段miniprogram_npm\@vant\weapp\field\index.js，
`setShowClear: function () {
            var _a = this.data, clearable = _a.clearable, readonly = _a.readonly;
            var _b = this, focused = _b.focused, value = _b.value;
            this.setData({
                showClear: clearable && focused && !!value && !readonly
            });
        }`

**Comment by rex-zsd** [comment]
这个告警在最新版本已经处理了的，可以升级一下哈。
