### ISSUE TITLE
ts如何正确引入Vantjs库

### ISSUE THREAD

**Issue by korrelx** [youzan/vant-weapp#3258]
引入后在微信开发者工具上编译后报错：
module "pages/index/@vant/weapp/dist/dialog/dialog" is not defined
我的配置都是根据文档配置的，这是我的引入方式：
import Dialog from '@vant/weapp/dist/dialog/dialog';

**Comment by Wyatex** [comment]
试了好久，要在tsconfig.json配置：
```
    "paths": {
      "@vant/weapp/*": ["./node_modules/@vant/weapp/dist/*"]
    }
```
就没有报错了
