### ISSUE TITLE
van-dropdown-menu关闭后不能点击

### ISSUE THREAD

**Issue by 1129zaj** [youzan/vant-weapp#3259]
van-dropdown-menu点击关闭弹窗之后，之前被覆盖的区域不能被点击了

**Comment by rex-zsd** [comment]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater?repo=VantWeapp

**Comment by auven** [comment]
@1129zaj 

是 uni-app 底层的问题，已给他们提交 [issues](https://github.com/dcloudio/uni-app/issues/1802) 了，你可以将 `@vant/weapp/dropdown-item/index.wxml` 里面的 `van-popup` 的事件改成驼峰写法 `afterEnter` 和 `afterLeave` 就可以了
