### ISSUE TITLE
关于vant-weapp组件会增加表格功能吗

### ISSUE THREAD

**Issue by 15735517450** [youzan/vant-weapp#3260]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater?repo=VantWeapp

**Comment by 15735517450** [comment]
类似于element类型的表格，一些有查看类型的小程序经常会用到表格

**Comment by rex-zsd** [comment]
表格组件暂时不会支持呢。
