### ISSUE TITLE
[Bug Report] Datetime 组件，选择某一列数据时其他列数据自动变动；使用 Popup 组件时，Field 组件在 type="textarea" 时遮罩无效，焦点仍能获取。

### ISSUE THREAD

**Issue by resyin** [youzan/vant-weapp#3261]
### 设备
MI8 (MIUI 11.0.2)

### VantWeapp 版本
1.3.2

### 基础库版本
2.8.1

### 如果是 UI 问题，截图链接（多图回车分隔）

![截图](https://i.loli.net/2020/06/09/U5y9XZFakLq8EN2.gif)

### 请提供核心代码片段链接
https://github.com/resyin/vant-datetime-bugs

### 描述问题
Datetime 组件，选择某一列数据时其他列数据自动变动；
使用 Popup 组件时，Field 组件在 type="textarea" 时遮罩无效，焦点仍能获取。
以上问题在开发工具不会出现，真机下出现。
详情见代码段，appid请使用自己的。

**Comment by rex-zsd** [comment]
textarea 的问题是原生组件的限制，无法绕过。
datetime-picker 的问题我们尝试复现一下。

**Comment by HoJun626** [comment]
你好, 我也出现了这个datetime-picker的问题, 需要在性能较差的低端安卓机复现, 性能较好的手机出现问题的概率就低很多.

**Comment by rex-zsd** [comment]
好的

**Comment by rex-zsd** [comment]
datetime-picker 的问题与其他 issue 反馈的相同，重复的先关闭了
