### ISSUE TITLE
uniapp 小程序引入vantweapp 使用组件DropdownMenu，点击下拉菜单点击任意地方遮罩层不消失

### ISSUE THREAD

**Issue by HalcyonDaysssss** [youzan/vant-weapp#3262]
使用组件DropdownMenu，点击下拉菜单点击任意地方遮罩层"效果"消失，class "van-dropdown-item van-dropdown-item--down" 依旧存在，导致整个页面无法点击!!!

**Comment by rex-zsd** [comment]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater?repo=VantWeapp

**Comment by auven** [comment]
@HalcyonDaysssss  

是 uni-app 底层的问题，已给他们提交 [issues](https://github.com/dcloudio/uni-app/issues/1802) 了，你可以将 `@vant/weapp/dropdown-item/index.wxml` 里面的 `van-popup` 的事件改成驼峰写法 `afterEnter` 和 `afterLeave` 就可以了
