### ISSUE TITLE
[Feature Request]计划做小程序里form的表单验证吗？

### ISSUE THREAD

**Issue by harryliuy** [youzan/vant-weapp#3267]

**Comment by Satlantisy** [comment]
表单验证貌似不属于UI的范畴吧

**Comment by harryliuy** [comment]
> 表单验证貌似不属于UI的范畴吧

vue版本就有噢

**Comment by rex-zsd** [comment]
vant weapp 这边考虑的是微信原生就是有 form 组件的，并且目前 vant weapp 的表单组件已经通过 `wx://form-field` 很好的支持 原生form 的特性。
所以暂时不会考虑像 vant 一样自己做一个 form，可以观望一下微信官方是否会给 form 提供表单校验功能，如果官方长时间内都不会支持， vant weapp 可能会推出自己的 form 组件。

**Comment by www295686243** [comment]
> vant weapp 这边考虑的是微信原生就是有 form 组件的，并且目前 vant weapp 的表单组件已经通过 `wx://form-field` 很好的支持 原生form 的特性。
> 所以暂时不会考虑像 vant 一样自己做一个 form，可以观望一下微信官方是否会给 form 提供表单校验功能，如果官方长时间内都不会支持， vant weapp 可能会推出自己的 form 组件。

2021了 会有出的计划吗？

**Comment by mouday** [comment]
2021年7月了，请问有计划吗？

**Comment by trojanyao** [comment]
2022.08.17：官方 form 貌似还没有表单验证，Vant 会做吗？

**Comment by msy031** [comment]
2023.08.22：官方 form 貌似还没有表单验证，Vant 会做吗？

**Comment by daniel-lij** [comment]
2023年10月31号：官方 form 貌似还没有表单验证，Vant 会做吗？

**Comment by wsslqdr** [comment]
2023年11月25号：官方 form 貌似还没有表单验证，Vant 会做吗？

**Comment by parade0393** [comment]
2024年1月4日：官方 form 貌似还没有表单验证，Vant 会做吗？

**Comment by GF-Huang** [comment]
2024年9月6日：官方 form 貌似还没有表单验证，Vant 会做吗？
