### ISSUE TITLE
[Feature Request]建议 tabs组件支持自定义(Slot)  tab的title

### ISSUE THREAD

**Issue by ethanbing** [youzan/vant-weapp#3268]
建议 tabs组件支持自定义（Slot）tab的title
有些title是双排文字，或者需要icon等，需要自定义内容,
现在无法自定义

**Comment by Satlantisy** [comment]
双排title我也需要

**Comment by rex-zsd** [comment]
受限于小程序的API，目前tabs没法支持title的slot

**Comment by zakioy** [comment]
很希望能加上slot，现在市面上很多项目都有加上icon，增加体验效果。

**Comment by anming-john** [comment]
现在支持了吗
