### ISSUE TITLE
小程序 中使用 tabs info 提示信息默认显示没有在右上角

### ISSUE THREAD

**Issue by FBIN-SPACE** [youzan/vant-weapp#3272]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater?repo=VantWeapp

**Comment by rex-zsd** [comment]
info信息是显示在右侧的，而不是右上角的哈。
