### ISSUE TITLE
SwipeCell 滑动单元格

### ISSUE THREAD

**Issue by d875708765** [youzan/vant-weapp#3273]
SwipeCell 滑动单元格需要导入 "van-cell": "@vant/weapp/cell/index", 这个包 然后还没有样式 左边和右边的样式

https://youzan.github.io/vant-issue-generater?repo=VantWeapp

**Comment by rex-zsd** [comment]
van-swipe-cell是不需要依赖van-cell的。
左侧和右侧的内容是需要自己写插入slot的，使用姿势可以看下组件文档哈。
