### ISSUE TITLE
[Feature Request] van-field输入框里面输入的值能否支持slot自定义?

### ISSUE THREAD

**Issue by cgChen1995** [youzan/vant-weapp#3274]
### 这个功能解决了什么问题
van-field输入框里面输入的值能否支持slot自定义?比如自定义插入图片，输入文件搜索

### 建议的API是什么样的

类似于微信发起群聊时选择好友的搜索框
![a704d84ef80ad58e484f3d69f585d75](https://user-images.githubusercontent.com/64302655/84254200-7c9c5480-ab43-11ea-9ba3-3c1ee1fbf5bd.jpg)

**Comment by rex-zsd** [comment]
这个应该不会支持了，可以自己拼一下。
以图中为例，左侧放选中的头像，右侧放 van-field
