### ISSUE TITLE
uniapp使用card组件 slot num生成的位置不对

### ISSUE THREAD

**Issue by HalcyonDaysssss** [youzan/vant-weapp#3276]
代码如下:
`<van-card tag="标签" price="10.00" desc="描述信息" title="商品标题">
                  <view slot="num">
                    <text>x222</text>
                  </view>
                </van-card>`
![image](https://user-images.githubusercontent.com/24239032/84340235-cc762c80-abd2-11ea-8b3b-642593e9d404.png)
![image](https://user-images.githubusercontent.com/24239032/84340245-d26c0d80-abd2-11ea-884e-f84494e06d82.png)

**Comment by rex-zsd** [comment]
num 的 slot 是不会附加样式的，可以自己加一个`float: right;`的样式上去哈。
