### ISSUE TITLE
[Bug Report] dropdown-item组件onClosed事件无效

### ISSUE THREAD

**Issue by 720t** [youzan/vant-weapp#3277]
### 设备
所有

### VantWeapp 版本
1.3.2

### 基础库版本
2.9.2

### 请提供核心代码片段链接
https://github.com/720t/vant-bug

### 描述问题
dropdown-item组件onClosed事件无效

**Comment by auven** [comment]
经测试，发现是 `van-popup` 的 `after-enter` 和 `after-leave` 不执行导致的。。。

你可以修改 `@vant/weapp/transition.js` 第 110 行，加上一行底下的代码，以此给 `van-popup` 加上两个自定义事件 `entered` 和 `leaveed`。
```
this.$emit(`${this.status}ed`)
```

然后修改 `@vant/weapp/dropdown-item/index.wxml` 第20 行，加上以下两行代码就可以了
```
    bind:entered="onOpened"
    bind:leaveed="onClosed"
```

**Comment by rex-zsd** [comment]
@720t 你的代码片段只是复制了文档的基础用法，没有监听任何事件呀。
还有事件名是`closed`而不是`onClosed`。

**Comment by auven** [comment]
是 uni-app 底层的问题，已给他们提交 [issues](https://github.com/dcloudio/uni-app/issues/1802) 了
