### ISSUE TITLE
[Feature Request] van-popup 可否增加手势操作

### ISSUE THREAD

**Issue by Satlantisy** [youzan/vant-weapp#3278]
### 这个功能解决了什么问题
全面屏手机普及，手势关闭popup很方便，app上有很多类似的popup都是手势下滑关闭，不知道小程序上容不容易实现。

### 建议的API是什么样的
增加一个prop，比如gesture之类，对于从底部弹出的popup可以下滑关闭。

**Comment by rex-zsd** [comment]
看了一圈，web 这边的组件似乎很少有手势操作的交互，vant weapp 也暂时不考虑支持哈。
