### ISSUE TITLE
[Bug Report] collapse组件收起展开非常缓慢

### ISSUE THREAD

**Issue by godlanbo** [youzan/vant-weapp#3279]
### 设备
安卓 7.0.14

### VantWeapp 版本
1.3.0

### 基础库版本
开发工具没有问题，真机问题

### 请提供核心代码片段链接
https://developers.weixin.qq.com/s/aJYop1mh7YiB

### 描述问题
在真机上，折叠和展开collapse组件非常缓慢，多个手机测试均有这个问题，官方demo的代码拷贝下来出现同样问题。

**Comment by rex-zsd** [comment]
可以提供一下测试的机型不？我们测试一下，应该是跟性能有关系。

**Comment by godlanbo** [comment]
> 可以提供一下测试的机型不？我们测试一下，应该是跟性能有关系。

ios下不会出现此情况，我们的测试机小米9和华为p10都出现此情况

**Comment by LeachZhou** [comment]
荣耀也是，也不知道是不是数据量的问题，6个分组，总数据200条，折叠一下要延迟2秒

**Comment by godlanbo** [comment]
> 荣耀也是，也不知道是不是数据量的问题，6个分组，总数据200条，折叠一下要延迟2秒

我一开始也以为是数据量的问题，但是后来将数据暂时置空，还是会出现明显的延迟；而且就算是数据的问题，我们在ios机型上测试同一组数据是不会出现卡顿延迟的=。=，所以我觉得应该不是数据量的问题。

**Comment by LeachZhou** [comment]
我在issue又搜索了其他的提问，发现源码里非手风琴模式根据some来进行运算，而同样的数据，手风琴模式延迟要好很多

**Comment by godlanbo** [comment]
> 我在issue又搜索了其他的提问，发现源码里非手风琴模式根据some来进行运算，而同样的数据，手风琴模式延迟要好很多

我也看了源码，确实是遍历的模式来处理的，但是我将数据置空也会出现问题，这就是我无法理解的了，而且，若是代码算法导致的问题，模拟器应该会先反应出来吧，模拟器上一切正常=。=

**Comment by ys152452** [comment]
> 可以提供一下测试的机型不？我们测试一下，应该是跟性能有关系。

近期会修改吗。

**Comment by smrsmr** [comment]
我是遇到这个问题 
设备
小米9
安卓 7.0.16

VantWeapp 版本
1.3.3

**Comment by MGsniper** [comment]
@rex-zsd 努比亚NX616J上也非常卡。在IOS系统上就体验就没有大问题。

**Comment by Ezreal147** [comment]
小程序基础库：2.11.3，
vant-weapp版本：1.3.3，
测试手机：小米10 pro，
折叠面板展开的响应速度很快，但是折叠速度相当慢，可能有一两秒，但是在开发者工具上延迟没这么大

**Comment by haliuhei** [comment]
1个月过去了，解决了吗

**Comment by rex-zsd** [comment]
经过几个机型的比对，目前的情况是iPhone XR、华为mate30没有出现动画滞后的问题，小米8、小米10都有动画滞后的问题。
测试了v1.0.0版本，以及所有带动画的组件，也有相同的问题。
应该是最近微信基础库的更新导致部分机型上动画性能的下降。
我们要研究下如何兼容这个情况

**Comment by Soonze** [comment]
使用的华为P40Pro也存在折叠面板卡顿问题，希望尽快解决。需要注意的是今天替换的GitHub上的版本出现的，之前使用的是uniapp插件库里下载的vant组件库，没有卡顿问题，但是那个版本太老了，不支持css变量。

**Comment by rex-zsd** [comment]
下版本将使用 animation 重构动画部分，避免部分机型卡顿的问题。
至于 van-transition 及相关的组件，因为必须依赖 setTimeout 来实现动画效果，暂时没有办法处理。

**Comment by bytekent** [comment]
我也碰到这个问题了 请问有解吗

**Comment by proper128** [comment]
重构了一个项目，也遇到这个问题，感觉是跟哪个插件冲突导致了。

**Comment by vioao** [comment]
还是遇到了这个问题，版本 1.6.8。荣耀 10。
请问是哪个版本解决了啊？

**Comment by akkentt** [comment]
> 还是遇到了这个问题，版本 1.6.8。荣耀 10。
> 请问是哪个版本解决了啊？

我更新最新版的测试，这个问题以及解决了
@vioao

**Comment by vioao** [comment]
@akkentt 是 1.6.8 吗？我真机上还是有这问题.

**Comment by a2291249652** [comment]
@vioao  你的解决了吗？

**Comment by victorymakes** [comment]
@a2291249652 升级最新版微信框架就 OK 了。
