### ISSUE TITLE
Calendar日历组件添加横向滚动

### ISSUE THREAD

**Issue by zzkung** [youzan/vant-weapp#3280]
现在的Calendar日历组件只支持纵向滚动，能否支持横向滚动。日历组件横向滚动的需求会比较大。

**Comment by rex-zsd** [comment]
横向滚动可以支持哦，不过近期比较忙，应该会暂缓支持

**Comment by zzkung** [comment]
好嘞

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: rex <notifications@github.com>
发送时间: Tuesday, June 16, 2020 9:02:41 PM
收件人: youzan/vant-weapp <vant-weapp@noreply.github.com>
抄送: zzkung <zzkung@outlook.com>; Author <author@noreply.github.com>
主题: Re: [youzan/vant-weapp] Calendar日历组件添加横向滚动 (#3280)


横向滚动可以支持哦，不过近期比较忙，应该会暂缓支持

―

**Comment by chenjiahan** [comment]
@rex-zsd 目前我们没有横向滚动的交互，得找交互同学碰下

**Comment by rex-zsd** [comment]
> @rex-zsd 目前我们没有横向滚动的交互，得找交互同学碰下

😢

**Comment by zzkung** [comment]
横向滚动还没有时间安排支持吗？

**Comment by TENYIYI** [comment]
横向滚动还没有时间安排支持吗？

**Comment by rex-zsd** [comment]
凉咯，这个支持不上了

**Comment by zhaozhinan** [comment]
横向滚动的需求比较大 希望能得到支持

**Comment by Liu-zhong-liang** [comment]
还没 支持吗 横向滚动刚需啊
