### ISSUE TITLE
[Feature Request] van-uploader上传视频完成之后，没办法预览视频吗？

### ISSUE THREAD

**Issue by cgChen1995** [youzan/vant-weapp#3281]
### 这个功能解决了什么问题
van-uploader上传视频完成之后，没办法预览视频吗？

### 建议的API是什么样的
van-uploader上传视频完成之后，没办法预览视频吗？

**Comment by TomSonghang** [comment]
前天刚做,好像是不可以;需要你自己去修改一下组件,我是拿到视频封面图之后再加个播放icon,点击直接跳新页面播放视频

**Comment by cgChen1995** [comment]
我现在用的是上传成功之后，把截取视频的一张图片放上去的，但是点击图片的时候，弹出来的是预览图，如果不启用预览图，点击预览事件又无法执行，有没有办法在点击预览图的时候，不弹出预览图并且可以执行预览图的事件？我打算自己做一个遮罩层，遮罩层里面播放视频

**Comment by rex-zsd** [comment]
#3227 发现有重复 issue，可以关注下这个哈
