### ISSUE TITLE
dialog confirm的弹出窗怎么是歪的呀

### ISSUE THREAD

**Issue by BEATING-HEART** [youzan/vant-weapp#3282]
dialog的confirm弹出窗怎么是歪的呀！
![image.png](https://i.loli.net/2020/06/14/BwaE7yLSHfYubhV.png)

**Comment by BEATING-HEART** [comment]
将appjson中的style：v2删掉，就正常了

**Comment by rex-zsd** [comment]
嗯，快速上手文档里有些，可以看一下
