### ISSUE TITLE
请问下van-checkbox-group复选框的value动态改变没有选中是怎么回事？已经有值，没有发现那里问题

### ISSUE THREAD

**Issue by LitChi666** [youzan/vant-weapp#3283]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater?repo=VantWeapp

**Comment by LitChi666** [comment]
<van-checkbox-group    value="{{ exam.multiple[type.index].answer}}" bind:change="onChangeMultiple"    disabled="{{disabled}}" data-index="{{type.index}}">
                                <van-checkbox name="{{t}}" style="margin-top: 10px"  wx:for="{{exam.multiple[type.index].options}}" wx:key="i" wx:for-index="i" wx:for-item="t" shape="square">
                                    {{arr[i]+t}}
                                </van-checkbox>
                            </van-checkbox-group>

**Comment by LitChi666** [comment]
复选框代码
```
<van-checkbox-group    value="{{ exam.multiple[type.index].answer}}" bind:change="onChangeMultiple"    disabled="{{disabled}}" data-index="{{type.index}}">
                                <van-checkbox name="{{t}}" style="margin-top: 10px"  wx:for="{{exam.multiple[type.index].options}}" wx:key="i" wx:for-index="i" wx:for-item="t" shape="square">
                                    {{arr[i]+t}}
                                </van-checkbox>
                            </van-checkbox-group>
```

**Comment by rex-zsd** [comment]
是否有在`onChangeMultiple `中给`exam.multiple[type.index].answer`赋值，贴下JS代码吧？

**Comment by LitChi666** [comment]
> 是否有在`onChangeMultiple `中给`exam.multiple[type.index].answer`赋值，贴下JS代码吧？

```
onChangeMultiple(e){
    let index=e.currentTarget.dataset.index;
    let exam=this.data.exam;
    exam.multiple[index].answer=e.detail;
    this.setData({exam:exam});
  },
```
我做的是考试的多选题，切换到下一题然后又到上一题刚刚选中的没有选中，就是这个问题，单选题的可以

**Comment by rex-zsd** [comment]
case感觉比较复杂，麻烦用开发者工具上传一个[代码片段](https://developers.weixin.qq.com/miniprogram/dev/devtools/minicode.html)吧

**Comment by LitChi666** [comment]
> case感觉比较复杂，麻烦用开发者工具上传一个[代码片段](https://developers.weixin.qq.com/miniprogram/dev/devtools/minicode.html)吧
可以了，之前需要设置两次值

**Comment by LitChi666** [comment]
Button 我看的有新增form-type属性，使用了<van-button type="primary" block  form-type=‘’submit‘’ >submint</van-button>没有触发form组件的submint事件苦恼，搞得我又用原生的button可以触发，求大佬赐教

**Comment by rex-zsd** [comment]
@LitChi666 `form-type`要求小程序基础库在`2.10.3`以上的，可以看下是不是基础库没有满足。

**Comment by yongxinxu** [comment]
> > case感觉比较复杂，麻烦用开发者工具上传一个[代码片段](https://developers.weixin.qq.com/miniprogram/dev/devtools/minicode.html)吧
> > 可以了，之前需要设置两次值

请问这个是怎么解决的呢？我遇到了类似的问题

**Comment by LitChi666** [comment]
> > > case感觉比较复杂，麻烦用开发者工具上传一个[代码片段](https://developers.weixin.qq.com/miniprogram/dev/devtools/minicode.html)吧
> > > 可以了，之前需要设置两次值
> 
> 请问这个是怎么解决的呢？我遇到了类似的问题

我的是值已经是有了，视图没更新

**Comment by yongxinxu** [comment]
> > > > case感觉比较复杂，麻烦用开发者工具上传一个[代码片段](https://developers.weixin.qq.com/miniprogram/dev/devtools/minicode.html)吧
> > > > 可以了，之前需要设置两次值
> > 
> > 
> > 请问这个是怎么解决的呢？我遇到了类似的问题
> 
> 我的是值已经是有了，视图没更新

我的也是，值一直都在。我是把多选放在弹出层里，在点击了其他多选后，返回之前点击过的多选，就选中显示不出来，但是值都在那里。

**Comment by wangfpp** [comment]
这个问题官方有解决吗？ 或者有其他解决方案吗? 源码看不出来。。。
