### ISSUE TITLE
van-tabs切换问题

### ISSUE THREAD

**Issue by L-Y-hua** [youzan/vant-weapp#3288]
使用van-tabs进行切换tab,当active由 0->1 或0->2，这样切换的话，会改变自动回到页面的顶部，（逆向切换就不会 如：2->0  ）有什么办法可以停留在页面的当前位置呢？实现正向切换跟逆向切换的效果一致呢？

**Comment by rex-zsd** [comment]
#3290
跟这个issue其实是一个问题，就目前小程序的机制来说，没有什么好的办法可以规避。
