### ISSUE TITLE
[Bug Report] panel面板布局错位

### ISSUE THREAD

**Issue by liulalala** [youzan/vant-weapp#3289]
### 设备
调试器

### VantWeapp 版本
1.3.2

### 基础库版本
2.10.4

### 如果是 UI 问题，截图链接（多图回车分隔）

![截图](https://sm.ms/image/8GFaYyKOW1usHeI)

### 请提供核心代码片段链接
https://youzan.github.io/vant-weapp/#/panel

### 描述问题
使用https://youzan.github.io/vant-weapp/#/panel 相同的代码，无论是基础用法还是高级用法，都会错位。试了好几个版本还是会错位~

**Comment by Satlantisy** [comment]
图挂了

**Comment by liulalala** [comment]
![image](https://user-images.githubusercontent.com/23302557/85038684-7b110300-b1b9-11ea-85dc-e28c6196f16b.png)

**Comment by rex-zsd** [comment]
panel 组件的内容部分是不带任何样式的，需要开发者自己定义，demo中也是有加 `padding` 样式的哈。
