### ISSUE TITLE
[Bug Report] 小程序van-tabs组件切换时 tab渲染bug

### ISSUE THREAD

**Issue by chuichui9527** [youzan/vant-weapp#3290]
### 设备
ios  微信版本7.0.13 安卓最新版本也是

### VantWeapp 版本
1.3.2

### 基础库版本
2.10.4

### 如果是 UI 问题，截图链接（多图回车分隔）

![截图](https://s1.ax1x.com/2020/06/18/NZNgC6.png)

![截图](https://s1.ax1x.com/2020/06/18/NZNgC6.png)

![截图](https://imgchr.com/i/NZN4DH)

### 请提供核心代码片段链接
https://youzan.github.io/vant-weapp/#/tab

### 描述问题
小程序van-tabs组件切换时 tab 同时渲染重叠 并且 还有点闪  切换的时候  ！也就是当点击 tabs切换的时候或者（先点第一个tabs 然后点第三个来回重复几次）  当前隐藏的tab和显示的tab同时存在，然后隐藏的tab消失，猜测是 切换tab状态this.setData(current)同时进行导致！官网简单的例子都是这个样子

**Comment by shuqingbao** [comment]
代码图片链接https://s1.ax1x.com/2020/06/18/NZNgC6.png

bug  重现gif https://imgchr.com/i/NZN4DH

**Comment by rex-zsd** [comment]
是有这个问题，因为在各个tab中设置显示/隐藏，导致了这个问题。
目前没有什么好的思路去解。

**Comment by chuichui9527** [comment]
目前我这边修改的是先让所有需要隐藏的tab 先渲染 ，然后再延迟50ms 渲染选中的tab，问题消失了 但是总感觉怪怪的，切换会有短暂的停顿 治标不治本

**Comment by rex-zsd** [comment]
是的，这里要么会有闪烁，并且页面自动滚到顶部，要么会同时渲染2个tab。

**Comment by panyushan2019** [comment]
解决了吗 兄弟  我也是和你一样的问题
