### ISSUE TITLE
步进器van-stepper设置了最大值和最小值，但是点击输入仍然可以输入超限制数字

### ISSUE THREAD

**Issue by XuRenee** [youzan/vant-weapp#3291]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater?repo=VantWeapp

**Comment by rex-zsd** [comment]
blur时会做校验的，不在范围内的会自动修正。
