### ISSUE TITLE
Button 按钮的form-type为submit 为啥没有触发form组件，你们有用吗？之前是没有form-type这个属性的

### ISSUE THREAD

**Issue by LitChi666** [youzan/vant-weapp#3292]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater?repo=VantWeapp

**Comment by rex-zsd** [comment]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater?repo=VantWeapp
