### ISSUE TITLE
[Bug Report] 小程序开发工具导入vantweapp源码跑不起来

### ISSUE THREAD

**Issue by xgxchina** [youzan/vant-weapp#3294]
### 设备
微信小程序开发工具

### VantWeapp 版本
1.3.2

### 基础库版本
2.3.0

### 请提供核心代码片段链接
https://github.com/xgxchina/XGX.git/example

### 描述问题
在https://github.com/youzan/vant-weapp下载源码，按照提示导入vant-weapp/example目录到微信小程序开发工具中，先按照yarn add @vant/weapp --production在根目录安装，并按照提示启用开发工具npm模块，进行编译。一直无法正常预览

**Comment by rex-zsd** [comment]
使用的姿势是错误的哈
看下文档的[预览部分](https://github.com/youzan/vant-weapp#%E5%9C%A8%E5%BC%80%E5%8F%91%E8%80%85%E5%B7%A5%E5%85%B7%E4%B8%AD%E9%A2%84%E8%A7%88)

**Comment by xgxchina** [comment]
改如何进行预览呢？？

**Comment by xgxchina** [comment]
好吧，还要npm run dev后才能导入
