### ISSUE TITLE
Button 我看的有新增form-type属性，使用了<van-button type="primary" block  form-type=‘’submit‘’ >submint</van-button>没有触发form组件的submint事件苦恼，搞得我又用原生的button可以触发，求大佬赐教

### ISSUE THREAD

**Issue by LitChi666** [youzan/vant-weapp#3295]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater?repo=VantWeapp

**Comment by rex-zsd** [comment]
确保组件库版本最新、小程序基础库版本在 `2.10.3` 以上就可以正常工作。
没有提供更多信息没法精确定位原因了。
