### ISSUE TITLE
[Bug Report] Dialog与Tab组件一起使用时，Dialog不能正常显示

### ISSUE THREAD

**Issue by fengxinlu** [youzan/vant-weapp#3296]
### 设备
IOS

### VantWeapp 版本
1.3.2

### 基础库版本
2.10.3

### 如果是 UI 问题，截图链接（多图回车分隔）

![截图](https://sm.ms/image/nlAR2r48Me5v3TG)

### 请提供核心代码片段链接
https://gist.github.com/fengxinlu/981a12b743b57f1c388043671ad89a78

### 描述问题
Tab组件中嵌入了Dialog组件 Dialog组件不能正常显示

**Comment by rex-zsd** [comment]
Tab组件中不能嵌套Dialog使用哈，可以搜索下历史issue，由于`transform`对`position: fixed`的影响，样式是不会如预期的。
