### ISSUE TITLE
Checkbox 复选框搭配单元格组件使用会有个别需要点击两次才会选中这个怎么解决？

### ISSUE THREAD

**Issue by LitChi666** [youzan/vant-weapp#3298]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater?repo=VantWeapp

**Comment by rex-zsd** [comment]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater?repo=VantWeapp
