### ISSUE TITLE
DropdownMenu 最新版关闭延迟很明显，安卓机型

### ISSUE THREAD

**Issue by akaiya** [youzan/vant-weapp#3299]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater?repo=VantWeapp

**Comment by rex-zsd** [comment]
dropdown-menu近几个版本没有调整过呢，可能跟 #3299 是类似的问题？

**Comment by rex-zsd** [comment]
可以关注下 #3299 这个

**Comment by akaiya** [comment]
3299这个就是我提出的问题呀



在 2020-06-24 15:21:38，"rex" <notifications@github.com> 写道：

可以关注下 #3299 这个
