### ISSUE TITLE
npm方式引入vant-weapp，如何js中使用Dialog或Notify

### ISSUE THREAD

**Issue by snailscoder** [youzan/vant-weapp#3300]
微信小程序使用npm方式引入vant-weapp，文档中提示引入方式：
import Dialog from 'path/to/@vant/weapp/dist/dialog/dialog';

但目前不管怎么写引入目录都提示module "node_modules/@vant/weapp/dist/notify/notify" is not defined，请问这个import应该如何引入，能否明确一下。

**Comment by Satlantisy** [comment]
npm引入，构建完了之后 我的引入路径是 /miniprogram_npm/@vant/weapp/notify/index 你试一下

**Comment by snailscoder** [comment]
> npm引入，构建完了之后 我的引入路径是 /miniprogram_npm/@vant/weapp/notify/index 你试一下

感谢恢复。问题已经解决。我看官方给了路径
import Dialog from 'path/to/@vant/weapp/dist/dialog/dialog'; 多了一层dist.

**Comment by budinggegg** [comment]
同踩坑了，我来详细描述一下坑在哪：
用小程序开发工具编译完组件后的组件地址：
miniprogram（这是根）/miniprogram_npm/@vant/weapp/这下面是全部组件的子目录了
容易犯错的地方：
应该用的文件夹：
miniprogram_npm 正确的，这下面其实没有dist目录
node_modules 错误的
容易跳坑的地方有2：
1，用了node_modules这个目录下的东西，这下面确实有dist目录所以看官方文档时容易导致选这个这个目录下的东西，但这个是没有用npm构建过的组件，所以会报：Error: module "node_modules/@vant/weapp/dist/dialog/dialog.js" is not defined，其实应该使用miniprogram_npm下的东西才对，这样会跳第二个坑
2，官方文档：import Dialog from 'path/to/@vant/weapp/dist/dialog/dialog';这是不是官方文档写错了，是小程序开发工具版本迭代导致的，以前确实会编译出一个dist文件夹，后来版本编译后会少这个文件夹所以正确路径是
import Dialog from '../../miniprogram_npm/@vant/weapp/dialog/dialog';

**Comment by liyang-it** [comment]
现在版本更新了，不是这样用的 。源文档: import Dialog from 'path/to/@vant/weapp/dist/dialog/dialog';
现在已经改成 : import Dialog from '../../miniprogram_npm/@vant/weapp/dialog/dialog'

**Comment by jeffcaiz** [comment]
以前直接用JS写，是这么用的，可以的。不确定最新版本vant weapp有无修改

```javascript
import Dialog from '@vant/weapp/dialog/dialog';
```

但是新一个版本上了TypeScript，就不行了，折腾中。`gulp-typescript-path-resolver`这个包看起来有点希望

**Comment by oooing** [comment]
> 同踩坑了，我来详细描述一下坑在哪：
> 用小程序开发工具编译完组件后的组件地址：
> miniprogram（这是根）/miniprogram_npm/@vant/weapp/这下面是全部组件的子目录了
> 容易犯错的地方：
> 应该用的文件夹：
> miniprogram_npm 正确的，这下面其实没有dist目录
> node_modules 错误的，这是没用npm构建前的组件目录，没试过删了有没有影响
> 容易跳坑的地方有2：
> 1，用了node_modules这个目录下的东西，这下面确实有dist目录所以看官方文档时容易导致选这个这个目录下的东西，但这个是没有用npm构建过的组件，所以会报：Error: module "node_modules/@vant/weapp/dist/dialog/dialog.js" is not defined，其实应该使用miniprogram_npm下的东西才对，这样会跳第二个坑
> 2，官方文档：import Dialog from 'path/to/@vant/weapp/dist/dialog/dialog';这是不是官方文档写错了，是小程序开发工具版本迭代导致的，以前确实会编译出一个dist文件夹，后来版本编译后会少这个文件夹所以正确路径是
> import Dialog from '../../miniprogram_npm/@vant/weapp/dialog/dialog';

还需要注意，小程序js里支持相对路径；还有要在js里直接调用dialog，还要在wxml添加<van-dialog id="van-dialog" />，

**Comment by liyang-it** [comment]
其实不用这样也可以，随便放一个路径，然后 直接引入就可以了，我测试了一下，没有用num构建，直接就把dist文件放到项目里面，然后json直接引入也可以用




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Pitt"<notifications@github.com&gt;; 
发送时间: 2021年1月12日(星期二) 中午11:25
收件人: "youzan/vant-weapp"<vant-weapp@noreply.github.com&gt;; 
抄送: "LiYang"<1922802352@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [youzan/vant-weapp] npm方式引入vant-weapp，如何js中使用Dialog或Notify (#3300)





  
同踩坑了，我来详细描述一下坑在哪：
 用小程序开发工具编译完组件后的组件地址：
 miniprogram（这是根）/miniprogram_npm/@vant/weapp/这下面是全部组件的子目录了
 容易犯错的地方：
 应该用的文件夹：
 miniprogram_npm 正确的，这下面其实没有dist目录
 node_modules 错误的，这是没用npm构建前的组件目录，没试过删了有没有影响
 容易跳坑的地方有2：
 1，用了node_modules这个目录下的东西，这下面确实有dist目录所以看官方文档时容易导致选这个这个目录下的东西，但这个是没有用npm构建过的组件，所以会报：Error: module "node_modules/@vant/weapp/dist/dialog/dialog.js" is not defined，其实应该使用miniprogram_npm下的东西才对，这样会跳第二个坑
 2，官方文档：import Dialog from 'path/to/@vant/weapp/dist/dialog/dialog';这是不是官方文档写错了，是小程序开发工具版本迭代导致的，以前确实会编译出一个dist文件夹，后来版本编译后会少这个文件夹所以正确路径是
 import Dialog from '../../miniprogram_npm/@vant/weapp/dialog/dialog';
  
还需要注意，小程序js里支持相对路径；还有要在js里直接调用dialog，还要在wxml添加，
 
&mdash;
