### ISSUE TITLE
嘿;-)可以加入滑动一块区域，改变其高度或宽度吗？

### ISSUE THREAD

**Issue by yoeelove** [youzan/vant-weapp#3301]
希望能加入滑动一块区域改变其展示的宽高。
场景如:一开始只是展示一项列表，当用户向上滑动后显示更多内容

https://youzan.github.io/vant-issue-generater?repo=VantWeapp

**Comment by hiyoee** [comment]
![Screenshot_2020_0622_172359](https://user-images.githubusercontent.com/58132697/85271338-4056e580-b4ad-11ea-8741-4b2a69a0791e.png)
![Uploading Screenshot_2020_0622_172427.png…]()

**Comment by hiyoee** [comment]
![IMG_20200622_173002](https://user-images.githubusercontent.com/58132697/85271911-06d2aa00-b4ae-11ea-9880-3e8c74534b86.jpg)

**Comment by rex-zsd** [comment]
额，这个你可以自己实现一下，组件库不会提供这样的功能。
