### ISSUE TITLE
[Bug Report] van-popup IOS微信7.1.13 position="top" 内超过2个输入框，输入框不显示内容

### ISSUE THREAD

**Issue by liukefeng553** [youzan/vant-weapp#3303]
### 设备
IOS 微信版本号7.1.13

### VantWeapp 版本
1.3.2

### 基础库版本
2.11.2

### 请提供核心代码片段链接
https://github.com/liukefeng553/vant-test/blob/master/pages/index/index.wxml

### 描述问题
<van-popup show="{{ true }}" position="center">
  <input name="address" placeholder="请输入地址"></input>
  <input name="username" placeholder="请输入姓名"></input>
</van-popup>
position="center"
两个输入框都显示placeholder，并且都能输入内容

<van-popup show="{{ true }}" position="center">
  <input name="address" placeholder="请输入地址"></input>
  <input name="username" placeholder="请输入姓名"></input>
</van-popup>
换成position="top"
地址栏则不能输入内容，并且placeholder不显示

**Comment by liukefeng553** [comment]
IOS微信7.1.12没有这个问题

**Comment by rex-zsd** [comment]
iOS目前最新的微信版本是7.0.13吧，没有7.1.13呢。
测试了一下iPhone11上的微信7.0.13，是没问题的。
这个问题看起来像是微信的bug，输入框属于原生组件，很可能跟popup这种含动画的组件产生冲突。
