### ISSUE TITLE
[Feature Request] tab 标签页 标题能提供插槽吗？或者有其他办法显示一个副标题吗？

### ISSUE THREAD

**Issue by pushuo** [youzan/vant-weapp#3304]
### 这个功能解决了什么问题
可以 对标题添加一个 副标题，更加灵活。现在很多场景，标题下面都会有一个副标题。

### 建议的API是什么样的
通过 title 插槽可以自定义标签内容。 建议想 对应 VUE 的UI 库 添加一个 插槽 <template #title> <van-icon name="more-o" />选项 </template>

**Comment by rex-zsd** [comment]
受限于小程序的机制，目前tab的标签是无法支持slot的。
