### ISSUE TITLE
[Bug Report] uniapp中使用datetime-picker 组件问题

### ISSUE THREAD

**Issue by minghaozz** [youzan/vant-weapp#3305]
### 设备
PC调试

### VantWeapp 版本
1.3.2

### 基础库版本
2.11.2

### 如果是 UI 问题，截图链接（多图回车分隔）

![截图](https://i.loli.net/2020/06/23/NSrkpjdyh4uEHP2.png)

![截图](https://i.loli.net/2020/06/23/O3DNSr4UwfmlYhP.png)

![截图](https://i.loli.net/2020/06/23/dXIZJz82VaA1yhj.png)

### 请提供核心代码片段链接
https://github.com/minghaozz/vantweapp/blob/master/check.vue

### 描述问题
uniapp 结合 vant-weapp 的时候 第一次 点击 弹出时间选择器的时候 设置当前选中值无效 报图中的错 当前时间选择不会改变 还是默认的0时，
但是当我弹出时间选择器不关闭，在代码里动态修改 value的值 当前选中值 就可以生效 并且不会报错 
刷新页面 再次点击 就又报第一张图的错了

**Comment by rex-zsd** [comment]
麻烦用开发者工具上传一下代码片段吧，没有uni-app的开发环境

**Comment by minghaozz** [comment]
uniapp 中用了 vant-weapp 0  0 改成用vant 就不报错了
