### ISSUE TITLE
van-swipe-cell  怎么用

### ISSUE THREAD

**Issue by qwerlh** [youzan/vant-weapp#3306]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater?repo=VantWeapp
基础用法里面 右滑只有一个按键  如何添加第二个键？
如果点击右滑有两个按键 怎么自定义 异步关闭

**Comment by qwerlh** [comment]
第二个键的样式 该怎么添加

**Comment by rex-zsd** [comment]
右侧slot内插入两个按键即可。
