### ISSUE TITLE
van-field什么时候才能支持v-model？？？

### ISSUE THREAD

**Issue by teri5354** [youzan/vant-weapp#3308]
不能用input事件，经实际测试，在某些安桌机型下面，如果输入完，立马点击旁边按钮，此时反应有延时，会导致被吞掉后面字符，增加了blur事件也不行。原生input组件是支持双向数据绑定的，van-field到底啥时候能升级啊？迫切需求

**Comment by rex-zsd** [comment]
van-field 支持微信的简易双向绑定的，
```
<van-field model:value="{{ value }}" />
``
你提到的`v-model`是vue的语法，在小程序中是不可能支持的。

**Comment by teri5354** [comment]
> van-field 支持微信的简易双向绑定的，
> 
> ```
> <van-field model:value="{{ value }}" />
> ``
> 你提到的`v-model`是vue的语法，在小程序中是不可能支持的。
> ```

<input type="text" placeholder="test11111" v-model="test1" />这样写我测试过的，用的mpvue，百分百可以。就是用van-filed不行

**Comment by rex-zsd** [comment]
mpvue的双向绑定仅支持mpvue的组件，是不支持原生自定义组件的

**Comment by peachapp** [comment]
你好，你这个问题怎么解决的呢。我们用mpvue+vant we app也遇到这个问题了。/(ㄒoㄒ)/~~
