### ISSUE TITLE
switch-cell没有文件夹使用不了这个组件

### ISSUE THREAD

**Issue by diaohuimiao** [youzan/vant-weapp#3312]

**Comment by rex-zsd** [comment]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater?repo=VantWeapp

**Comment by rex-zsd** [comment]
vant weapp 是没有 switch-cell 组件的

**Comment by diaohuimiao** [comment]
有办法处理吗

**Comment by rex-zsd** [comment]
可以自己用 switch 和 cell 组件搭建一下，vant 那边 switch-cell 也已经是不建议使用的状态，而是推荐自己组装。
