### ISSUE TITLE
[Bug Report] Calendar日历在区间选择模式下超出max-range后无提示弹出

### ISSUE THREAD

**Issue by chuanghan** [youzan/vant-weapp#3320]
### 设备
微信开发者工具

### VantWeapp 版本
1.3.3

### 基础库版本
2.7.0

### 请提供核心代码片段链接
https://gist.github.com/chuanghan/f696f0c564aab8956914df94286ba4a1

### 描述问题
van-calendar组件按照文档设置了日历区间选择模式下的max-range和range-prompt后，选择超出区间的日期后没有Toast弹出。控制台显示错误提示：“未找到 van-toast 节点，请确认 selector 及 context 是否正确”。请检查错误原因。

**Comment by onliyouLZ** [comment]
对，我也发现这个bug了

**Comment by kuyaaaa** [comment]
+1

**Comment by cutie6** [comment]
+1，官方赶紧修复下吧，报错如下：
![image](https://user-images.githubusercontent.com/20717515/89163886-e4ea3e00-d5a8-11ea-8181-a974ca0f231e.png)
