### ISSUE TITLE
小程序 使用npm安装，没有image组件

### ISSUE THREAD

**Issue by 1037055457** [youzan/vant-weapp#3323]
小程序基础库：2.11.3
vant-weapp版本：1.3.3

我从“miniprogram_npm” —— “vant-weapp”文件夹下找，就是没有image组件，其他的组件都有

**Comment by gsy13213009** [comment]
同样的问题，请问怎么解决的？ @1037055457

**Comment by 1037055457** [comment]
> 同样的问题，请问怎么解决的？ @1037055457

先检查小程序中的“package.json”文件，看下“dependencies”中的vant版本，我的之前是0.X版本的，要更新到1.0版本以上才有的

**Comment by 1037055457** [comment]
> > 同样的问题，请问怎么解决的？ @1037055457
> 
> 先检查小程序中的“package.json”文件，看下“dependencies”中的vant版本，我的之前是0.X版本的，要更新到1.0版本以上才有的

或者你重新构建下npm应该就有了
