### ISSUE TITLE
[Bug Report] 有赞的职位详情链接点进去报错了哟~

### ISSUE THREAD

**Issue by zhang1024899756** [youzan/vant-weapp#3324]
### 设备
pc

### VantWeapp 版本
1.3.3

### 基础库版本
0

### 请提供核心代码片段链接
https://app.mokahr.com/apply/youzan/6252#/job/96f5d2c7-e657-4d31-9244-195edc443a7f?_k=jf2141

### 描述问题
这个链接进去报错
https://app.mokahr.com/apply/youzan/6252#/job/96f5d2c7-e657-4d31-9244-195edc443a7f?_k=jf2141

**Comment by rex-zsd** [comment]
https://app.mokahr.com/apply/youzan/3750
貌似这个才是对的吧

**Comment by chenjiahan** [comment]
感谢反馈，后续会修正下

**Comment by rex-zsd** [comment]
哈，原来是readme上面贴的链接
