### ISSUE TITLE
TypeError: wx.nextTick is not a function

### ISSUE THREAD

**Issue by itshu** [youzan/vant-weapp#3326]
你好：我用微信开发者工具里面，总是出现这个错误：
VM4804:1 thirdScriptError
wx.nextTick is not a function; [Component] Property Observer Error @ miniprogram_npm/@vant/weapp/notice-bar/index#observer
TypeError: wx.nextTick is not a function
    at r.observer (http://127.0.0.1:17701/appservice/miniprogram_npm/@vant/weapp/notice-bar/index.js:15:12)

这个错误是不是在正式环境就没有了？

**Comment by rex-zsd** [comment]
[nextTick](https://developers.weixin.qq.com/miniprogram/dev/api/ui/custom-component/wx.nextTick.html)是微信基础库2.2.3加入的API，需要确定一下你设定的基础库是否在这个版本以上。

**Comment by zphtown** [comment]
具体操作，修改小程序代码project.config.json文件libVersion 为 2.2.3即可，如果小程序上线的话，还要在小程序后台-【设置】-【基础库最低版本设置】，里面修改版本
