### ISSUE TITLE
为什么不用cover-view代替view来制作 类似ActionSheet这种弹出层

### ISSUE THREAD

**Issue by kongdemin** [youzan/vant-weapp#3328]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater?repo=VantWeapp

在用到canvans时会被 图标穿透

**Comment by rex-zsd** [comment]
cover-view只支持嵌套 cover-view、cover-image、button，限制太大了点。
