### ISSUE TITLE
npm run start 时候报错

### ISSUE THREAD

**Issue by zhangyuanzhao** [youzan/vant-weapp#3331]
These dependencies were not found:

* vant/es/slidebar-item in ./src/config/components.js
* vant/es/slidebar-item/style in ./src/config/components.js

**Comment by zhangyuanzhao** [comment]
没人解决我的问题吗？

**Comment by rex-zsd** [comment]
额，是不是提错仓库了，这里是 vant weapp，从你贴的代码来看，应该是 vant 的？
指路 https://github.com/youzan/vant
