### ISSUE TITLE
[Bug Report] 使用<van-uploader>组件时，发现@after-read事件不起作用

### ISSUE THREAD

**Issue by yellowswf** [youzan/vant-weapp#3332]
### 设备
微信开发者工具 v1.03.2005140

### VantWeapp 版本
1.3.3

### 基础库版本
2.11.2

### 请提供核心代码片段链接
https://github.com/youzan/vant-weapp/blob/v1.3.3/dist/uploader/index.js

### 描述问题
【mpvue+vant weapp】 下使用<van-uploader>组件时，发现@after-read事件不起作用，mothod中的方法没有调用。
换成@afterRead也不行。

使用方式如下：
<van-uploader name="1" :file-list="fileList" @after-read="uploadImg" @delete="del(e)" />
....
    methods: {
        uploadImg(event) {
            cosnole.log(event);

        },
}

**Comment by rex-zsd** [comment]
使用mpvue时，事件名中间带`-`的是无法触发的。
可以修改下载下来的vant weapp的代码，将事件名改为不带`-`的。
