### ISSUE TITLE
SwipeCell 滑动单元格 创建列表 100个 侧滑卡顿

### ISSUE THREAD

**Issue by WangSongAA** [youzan/vant-weapp#3334]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater?repo=VantWeapp

**Comment by rex-zsd** [comment]
创建节点数过多时一定会卡顿的，可以控制一下列表内同时存在的组件个数。

**Comment by WangSongAA** [comment]
我有100条数据  必须加载完   你说咋办   侧滑动画该优化了

**Comment by pangm98** [comment]
这个问题确实存在，个人也写了个不是很完美的版本，将就用着的，希望官方可以完善一下

**Comment by symnetry** [comment]
超过3个开始卡顿 我当前节点数为10个 已经相较楼主少了一个数量级了 明显感觉到卡顿 
```
<van-swipe-cell right-width="{{ 65 }}">
	<van-cell-group>
		<van-cell border="{{ false }}" value="pplitem" >
			<view slot="title" class="secondpermission">
				remarks
			</view>
		</van-cell>				
	</van-cell-group>
	<view class="btn red" slot="right">delete</view>
</van-swipe-cell>
```
像这样创建5个就已经卡了 （-小程序 -iphone8 ）
