### ISSUE TITLE
如果我只想引用一个组件的话,能否有类似按需引入的功能啊?

### ISSUE THREAD

**Issue by TomSonghang** [youzan/vant-weapp#3336]

**Comment by rex-zsd** [comment]
小程序只会上传在 json 中配置的组件，按需加载不需要做额外的处理的。

**Comment by nikolausliu** [comment]
@rex-zsd 并不是哦，小程序会上传miniprogram_npm里的所有文件，而小程序编译工具并不会识别你在app.json或page.json里引用了哪些组件，而是把所有组件都编译到miniprogram_npm文件夹里。我今天亲自测试的，话说我在另一个地方也看到了你同样的回答，你测试过吗？

**Comment by iniself** [comment]
官方有回答吗？

**Comment by rex-zsd** [comment]
> 官方有回答吗？

那只能手动在目录中删除不用的组件了

**Comment by cafehaus** [comment]
vant和小程序官方都不支持，可以使用这个 npm 包：vant-tree-shaking，使用说明参考 https://www.npmjs.com/package/vant-tree-shaking
