### ISSUE TITLE
[Bug Report] DropdownMenu 下拉菜单如何禁止原页面滚动

### ISSUE THREAD

**Issue by 824750130** [youzan/vant-weapp#3338]
### 设备
苹果与安卓

### VantWeapp 版本
1.3.3

### 基础库版本
2.11.2

### 请提供核心代码片段链接
https://gitee.com/swz1886/codes/ocwej1rzfqap72n9l5gsb47

### 描述问题
DropdownMenu打开时原页面依旧可以滚动,请问如何禁止滚动？

**Comment by chenjiahan** [comment]
小程序的问题请到 vant-weapp 仓库下反馈，感谢配合

**Comment by 824750130** [comment]
这里不是vant-weapp 仓库吗

**Comment by chenjiahan** [comment]
sorry，看走眼了🤣

**Comment by rex-zsd** [comment]
哈哈哈哈

**Comment by rex-zsd** [comment]
gitee 上的代码是 404，看不到哈。
可以看下 [popup的文档](https://youzan.github.io/vant-weapp/#/popup#zu-jian-gun-dong-chuan-tou-gai-zen-me-jie-jue)，小程序上滚动穿透的问题在组件库内部无法很完美的解决，所以需要开发者自行处理。
