### ISSUE TITLE
[Bug Report] Collapse-item折叠面板的部分属性不生效

### ISSUE THREAD

**Issue by Ezreal147** [youzan/vant-weapp#3339]
### 设备
pc和安卓手机

### VantWeapp 版本
1.3.3

### 基础库版本
2.11.3

### 请提供核心代码片段链接
https://github.com/Ezreal147/van-weapp-bug/blob/master/bug.wxml

### 描述问题
collapse-item折叠面板的right-icon插槽无效，不显示这个slot。collapse-item的is-link属性设置为false也不生效，右侧箭头和点击反馈仍然在

**Comment by rex-zsd** [comment]
要注意 `is-link` 是 `boolean` 类型，这里写成 `is-link="false"` 是无效的，应该写成 `is-link="{{ false }}"` 。
而 right-icon 插槽不生效也是因为 `is-link` 的原因，将 `is-link` 设置为 `false` 之后，right-icon 插槽即可正常生效，
