### ISSUE TITLE
Field 输入框 能增加自定义 input slot 吗

### ISSUE THREAD

**Issue by zehuichan** [youzan/vant-weapp#3340]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater?repo=VantWeapp

**Comment by rex-zsd** [comment]
目前不会考虑，input 是 field 组件的核心，如果替换 input，倒不如自己新写一个组件了。
