### ISSUE TITLE
vant-field双向绑定怎么用的

### ISSUE THREAD

**Issue by neozhu** [youzan/vant-weapp#3341]
谁能给个例子，官方例子中没有，又说实现了双向绑定，但我试了很多，都没有实现

**Comment by haliuhei** [comment]
model:value="{{ value }}"
[https://developers.weixin.qq.com/miniprogram/dev/framework/view/two-way-bindings.html](https://developers.weixin.qq.com/miniprogram/dev/framework/view/two-way-bindings.html)

**Comment by JohnYuanhao** [comment]
在vue中不适用啊，会提示` Interpolation inside attributes has been removed. Use v-bind or the colon shorthand instead`

**Comment by haliuhei** [comment]
> 在vue中不适用啊，会提示` Interpolation inside attributes has been removed. Use v-bind or the colon shorthand instead`

你用vue ,不应该使用vue版本的 vant吗

**Comment by JohnYuanhao** [comment]
> > 在vue中不适用啊，会提示` Interpolation inside attributes has been removed. Use v-bind or the colon shorthand instead`
> 
> 你用vue ,不应该使用vue版本的 vant吗

是mpvue+vantweapp

**Comment by xiongzixiao** [comment]
> > > 在vue中不适用啊，会提示` Interpolation inside attributes has been removed. Use v-bind or the colon shorthand instead`
> > 
> > 
> > 你用vue ,不应该使用vue版本的 vant吗
> 
> 是mpvue+vantweapp，不过无所谓了，已经自己实现了

能问下怎么实现的么？
