### ISSUE TITLE
[Bug Report] 联系人组件

### ISSUE THREAD

**Issue by hhxiaohei** [youzan/vant-weapp#3343]
### 设备
所有设备

### VantWeapp 版本
1.3.3

### 基础库版本
1.0.0

### 请提供核心代码片段链接
```js
<van-contact-card
  :type="cardType"
  :name="currentContact.name"
  :tel="currentContact.tel"
  @click="showList = true"
/>
```

### 描述问题
请问联系人组件怎么添加自定义字段 现在只有2个字段 不满足业务需求 谢谢

**Comment by rex-zsd** [comment]
vant weapp 没有 contactCard 呢，去 vant 那边问问？https://github.com/youzan/vant
