### ISSUE TITLE
wepy2.0框架中引用 tab组件 点击事件失效

### ISSUE THREAD

**Issue by chenjunjie12** [youzan/vant-weapp#3345]
wepy2.0版本中引用tab组件的时候，官网上提供的绑定事件处理方法，只能获取到van-tabs标签的下标，van-tab的下标获取不到

**Comment by Hug125** [comment]
这个是由于点击事件bind:click被wepy翻译成了bind:tap,导致无法正确的调用组件的对应方法。
目前的补救措施是在van-tab的源码里把bind:clck换成一个别的方法名，绕开wepy的翻译就可以了。
