### ISSUE TITLE
[Feature Request] 希望能给 NoticeBar 增加关闭事件

### ISSUE THREAD

**Issue by bianyukun1213** [youzan/vant-weapp#3346]
### 这个功能解决了什么问题
NoticeBar 关闭后能够实现自定义的操作

### 建议的API是什么样的
bind:close="onClose"

**Comment by Lindysen** [comment]
我的理解是当设置left-icon 为close之后，触发点击事件 就是关闭操作吧。或者你说具体点 你的想法

**Comment by bianyukun1213** [comment]
> 我的理解是当设置left-icon 为close之后，触发点击事件 就是关闭操作吧。或者你说具体点 你的想法

是的，没错。

**Comment by Lindysen** [comment]
那我 issue 关嘞，应该不需要单独增加 close
