### ISSUE TITLE
[Bug Report] filed组件有值时重新聚焦 输入键盘被隐藏

### ISSUE THREAD

**Issue by zxk175** [youzan/vant-weapp#3347]
### 设备
IQOO Pro

### VantWeapp 版本
1.3.3

### 基础库版本
2.11.3

### 如果是 UI 问题，截图链接（多图回车分隔）

![截图](https://i.loli.net/2020/07/07/oKX7eiFNGEU6gQm.gif)

![image](https://user-images.githubusercontent.com/10259995/86754803-be9db500-c073-11ea-8790-9869b68393a2.png)

### 描述问题
filed组件有值时重新聚焦 输入键盘被隐藏

**Comment by rex-zsd** [comment]
键盘这种属于小程序的原生交互了，vant weapp 这边应该是无法影响的。
