### ISSUE TITLE
请问Cell 单元格 的van-cell的高度要怎么设置

### ISSUE THREAD

**Issue by doublebin** [youzan/vant-weapp#3348]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater?repo=VantWeapp

**Comment by rex-zsd** [comment]
通过 `custom-style` 属性或者 `custom-class` 外部样式类都可以的哈。

**Comment by CreatoCode** [comment]
但是title，label，value及righit-icon不会跟着调整啊。只是想高一点而已，确要重写整个cell。
