### ISSUE TITLE
[Feature Request] 【需求】van-field在内容可视的条件下弹出系统密码键盘。

### ISSUE THREAD

**Issue by ch-boogeyman** [youzan/vant-weapp#3349]
### 这个功能解决了什么问题
登录的时候可以看见密码，并且使用密码键盘比较安全！

### 建议的API是什么样的
0

![密码键盘](https://user-images.githubusercontent.com/46711557/86877665-e5aec200-c119-11ea-98ac-bdc0c37a1ab3.png)

**Comment by rex-zsd** [comment]
小程序目前的情况，这个需求没办法实现，键盘类型与 `password` 类型是强关联的。
可以尝试在点击显示密码时在 `password` 类型的输入框上面盖一层 view，用来显示已输入的内容。

**Comment by masicheng** [comment]
> 小程序目前的情况，这个需求没办法实现，键盘类型与 `password` 类型是强关联的。 可以尝试在点击显示密码时在 `password` 类型的输入框上面盖一层 view，用来显示已输入的内容。

密码框二次输入时，在iOS系统中会清空之前输入的内容，这种怎么处理比较好
