### ISSUE TITLE
[Feature Request] 如何使用阿里的iconfont

### ISSUE THREAD

**Issue by nnhym** [youzan/vant-weapp#3350]
### 这个功能解决了什么问题
扩展icon

### 建议的API是什么样的
使用class引入好解决。通过属性引入怎么解决？例如：`<van-tabbar-item icon="iconfont home">首页</van-tabbar-item>`，图标无法显示

**Comment by 1sm23** [comment]
`tabbar-item`引用的`van-icon`改成你自己的iconfont

**Comment by 1sm23** [comment]
> `tabbar-item`引用的`van-icon`改成你自己的iconfont

```json
"van-icon": "/components/ss-icon/index"
```

**Comment by nnhym** [comment]
大概明白你的意思了，就是自己封装一个icon组件，替换掉van-icon，其实我是想在一个组件里面兼容van-icon，和iconfont同时使用

**Comment by 1sm23** [comment]
> 大概明白你的意思了，就是自己封装一个icon组件，替换掉van-icon，其实我是想在一个组件里面兼容van-icon，和iconfont同时使用

vant那点icon用手指都能数过来 , 直接用自己的就行了,实在不行vant在iconfont上传了他们的图标,你找找加入包里面其实就是一个新的带有vant图标而且又有自己的图标的组件了

**Comment by nnhym** [comment]
@1sm23 okok，非常感谢！

**Comment by nnhym** [comment]
> `tabbar-item`引用的`van-icon`改成你自己的iconfont

试了一下这样封装只能解决<van-icon>标签引用自定义icon；<van-tabbar-item icon="iconfont home">这种方式，自定义的icon不能使用，使用的还是原始的van icon
