### ISSUE TITLE
需求:van-cell 加一个左边是头像或图片右边是文字说明这样的布局

### ISSUE THREAD

**Issue by neozhu** [youzan/vant-weapp#3353]
这个也很常用,也很简单,但无奈就是弄出来不协调,不好看,能否请专业人员做一个例子.谢谢

**Comment by Satlantisy** [comment]
van-cell 的icon-slot可以用image组件变成头像 大小为50px title位置用于头像名字 我的就是这么做的

**Comment by neozhu** [comment]
谢谢回复
