### ISSUE TITLE
[Bug Report] grid badge设置数字后位置没有居中

### ISSUE THREAD

**Issue by haliuhei** [youzan/vant-weapp#3355]
### 设备
iphoneX

### VantWeapp 版本
1.3.3

### 基础库版本
2.11.3（微信7.0.13）

### 如果是 UI 问题，截图链接（多图回车分隔）

![截图](https://user-images.githubusercontent.com/57513459/86995285-2cb0bc00-c1db-11ea-84ec-e4f217630fe8.png)

### 请提供核心代码片段链接
https://youzan.github.io/vant-weapp/#/grid

### 描述问题
badge设置数字后数字位置没有居中
使用微信打开vantweapp。
```
<van-grid column-num="2">
  <van-grid-item icon="home-o" text="文字" dot />
  <van-grid-item icon="search" text="文字" badge="99 " />
</van-grid>
```

**Comment by rex-zsd** [comment]
badge的位置是在图标右上方的，设计如此，如果需要在中间的话可以用slot自定义一下哈。

**Comment by haliuhei** [comment]
> badge的位置是在图标右上方的，设计如此，如果需要在中间的话可以用slot自定义一下哈。

原意是反馈下 红色区域里 的数字垂直方向 有点偏上 了
