### ISSUE TITLE
[Bug Report] 如何调整van-tree-select的高度

### ISSUE THREAD

**Issue by qggcs** [youzan/vant-weapp#3356]
### 设备
iphone 6s plus/iphone X

### VantWeapp 版本
1.3.3

### 基础库版本
2.11.3

### 如果是 UI 问题，截图链接（多图回车分隔）

![截图](https://i.loli.net/2020/07/09/X9Tk6dS187KEgPN.png)

![截图](https://i.loli.net/2020/07/09/WjBywxazDIdAn6q.png)

### 请提供核心代码片段链接
https://youzan.github.io/vant-weapp/#/tree-select

### 描述问题
是这样的，本人使用vant-tree-select组件开发小程序页面，发现无法使用内联样式或者类调整该组件的高度，而vant的移动端库该组件提供了height属性，而小程序端该组件并未提供height属性，是否有好的解决方案，调整小程序端vant-tree-select组件的高度？使得能充满整个屏幕

**Comment by rex-zsd** [comment]
vant weapp 的 tree-select 也是有 `height` 属性的，不过文档里没体现，属性含义和 vant 是一致的。
之后补下文档。
