### ISSUE TITLE
都2020年，还不增加一个减法的icon吗？

### ISSUE THREAD

**Issue by peterPan520** [youzan/vant-weapp#3360]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater?repo=VantWeapp

都2020年，还不增加一个减法的icon吗？

**Comment by rex-zsd** [comment]
icon也可以使用其他字体的哈，不一定需要@vant/icons内置。
