### ISSUE TITLE
[Bug Report] vant weapp组件库bug

### ISSUE THREAD

**Issue by sakura5208** [youzan/vant-weapp#3361]
### 设备
无

### VantWeapp 版本
1.3.3

### 基础库版本
1.3.3

### 请提供核心代码片段链接
https://youzan.github.io/vant-weapp/#/dialog

### 描述问题
当dialog组件的确认框处于打开状态时，再通过左侧导航栏切换到其他组件时右边模拟器显示的还是dialog组件打开的确认框

**Comment by sakura5208** [comment]
提交bug

**Comment by rex-zsd** [comment]
没看懂，可以详细描述一下或者上传下代码片段吗？

**Comment by sakura5208** [comment]
这是一个vant weapp组件库的显示bug，不影响使用
