### ISSUE TITLE
vant小程序版有轮播图组件吗

### ISSUE THREAD

**Issue by jw18805155299** [youzan/vant-weapp#3363]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater?repo=VantWeapp

**Comment by rex-zsd** [comment]
vant weapp 没有轮播图组件，因为微信已经有[原生组件](https://developers.weixin.qq.com/miniprogram/dev/component/swiper.html)了
