### ISSUE TITLE
Card组件如何设置点击事件？

### ISSUE THREAD

**Issue by WxYoung** [youzan/vant-weapp#3367]
https://youzan.github.io/vant-weapp/#/card
文档中没有event的事件，只有使用thumb-link 或者 增加vue-button的方式执行js，有绑定整个card的click事件吗?

ps:已尝试   <van-card > 代码中加入bind:click="xxx"的方法，测试无效

**Comment by Lindysen** [comment]
微信中没有click 事件，只有tap，可以试试tap
