### ISSUE TITLE
action-sheet跟field的textarea层级怎么解决啊

### ISSUE THREAD

**Issue by Liulei1201** [youzan/vant-weapp#3372]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater?repo=VantWeapp

**Comment by rex-zsd** [comment]
小程序本身的限制，是没办法解决的，只能绕过，比如在弹层渲染时隐藏field
可以看下[文档说明](https://youzan.github.io/vant-weapp/#/field#zhen-ji-shang-placeholder-wei-shi-me-hui-gai-guo-popup-deng-qi-ta-zu-jian)
