### ISSUE TITLE
Circle渲染完数据会出现百分比条抖动问题，进度条一下一上，怎么解决

### ISSUE THREAD

**Issue by LitChi666** [youzan/vant-weapp#3373]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater?repo=VantWeapp

**Comment by thorn929** [comment]
有小数点就会抖动比如， 8.5%

**Comment by thorn929** [comment]
> 你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。
> 
> https://youzan.github.io/vant-issue-generater?repo=VantWeapp

有小数点就会抖动比如， 8.5%

**Comment by rex-zsd** [comment]
circle 组件基于 canvas 实现，图形是一次绘制成型的。
出现抖动的情况，可能是传入的 `value` 值一直在来回变化，不断重新渲染。或者原生 canvas 内部绘制有抖动，如上面提到的小数点情况。
这方面 circle 组件基本没有什么可优化的余地，建议在使用的时候考虑这些情况。

**Comment by thorn929** [comment]
> circle 组件基于 canvas 实现，图形是一次绘制成型的。
> 出现抖动的情况，可能是传入的 `value` 值一直在来回变化，不断重新渲染。或者原生 canvas 内部绘制有抖动，如上面提到的小数点情况。
> 这方面 circle 组件基本没有什么可优化的余地，建议在使用的时候考虑这些情况。

我已经复现了，和canvas无关哈 ，  如果传入的浮点数，你们逻辑写的有问题，一直不停赋值

**Comment by TengFeiHao** [comment]
这个是因为，源码内部在写动画的时候，做了+1 -1 的操作判断相等的时候才会终止绘制，小数点肯定不会有相等的情况导致出现这个问题，应该是动画的原因
