### ISSUE TITLE
[Bug Report] vant-uploader：接收类型是media或是video，真机（ios和android）测试时它不会打开我的相册或者拍摄功能

### ISSUE THREAD

**Issue by YGRZ-0806** [youzan/vant-weapp#3375]
### 设备
ios和android

### VantWeapp 版本
1.4.0-beta.1

### 基础库版本
Uploader 文件上传

### 请提供核心代码片段链接
https://youzan.github.io/vant-weapp/#/uploader

### 描述问题
vant-uploader：接收类型是media或是video，真机（ios和android）测试时它不会打开我的相册或者是拍摄功能，而是微信的最近联系人列表呢？

**Comment by rex-zsd** [comment]
demo 的 uploader 组件将 `accept` 设置为 `media` 或 `vedio` 是正常的。
可以上传一个代码片段吗？
