### ISSUE TITLE
[Bug Report] SwipeCell 右侧多个按钮的使用文档

### ISSUE THREAD

**Issue by agoni1212** [youzan/vant-weapp#3376]
### 设备
Android

### VantWeapp 版本
1.3.3

### 基础库版本
2.10.0

### 请提供核心代码片段链接
https://youzan.github.io/vant-weapp/#/swipe-cell

### 描述问题
文档并没有提及如果 右侧有多个按钮的帮助文档。如果右侧有多个按钮，在close事件中，如何知道点击的是右侧哪个按钮？
能否提供一小段demo ，谢谢

**Comment by rex-zsd** [comment]
close事件并不关心slot内插入几个按钮，只有位置参数。
如果右侧有多个按钮，就不必监听 `close` 事件了，监听按钮抛出的事件即可。
比如
```
<van-swipe-cell right-width="{{ 100 }}" left-width="{{ 65 }}">
  <block slot="right">
    <van-button bind:click="onPin">置顶</van-button>
    <van-button bing:click="onDelete">删除</van-button>
  </block>
</van-swipe-cell>
```
