### ISSUE TITLE
[Feature Request] 日历组件的每个月份的展示能否是切换形式以及显示农历日期？

### ISSUE THREAD

**Issue by Spring456** [youzan/vant-weapp#3379]
### 这个功能解决了什么问题
在移动端页面展示时，很多时候因为页面长度有限，需要切换每个月份来展现。对于农业类的app需要展示农历日期

### 建议的API是什么样的
无

**Comment by rex-zsd** [comment]
目前不会支持农历呢

**Comment by cnfczn** [comment]
都2023年了，还没有支持呢
