### ISSUE TITLE
[Feature Request] 希望van-notice-bar增加关闭事件

### ISSUE THREAD

**Issue by ch-boogeyman** [youzan/vant-weapp#3380]
### 这个功能解决了什么问题
某些不是非常重要的通知，为避免反复打扰用户，在关闭的时候传出事件让用户选择是否不再提醒。
顺便传出this,data,text方便设置缓存。

### 建议的API是什么样的
this.triggerEvent('close', this.data.text)

![0](https://user-images.githubusercontent.com/46711557/87384156-9fe87280-c5cd-11ea-9ffb-8ecc18601028.png)

**Comment by rex-zsd** [comment]
将会新增 `close` 事件，但是不会传出 `text` 等组件入参哈，可以通过 `dataset` 自行处理一下。

**Comment by ch-boogeyman** [comment]
> 将会新增 `close` 事件，但是不会传出 `text` 等组件入参哈，可以通过 `dataset` 自行处理一下。

可
