### ISSUE TITLE
van-popup在小米手机自带浏览器中背景蒙层闪现一下消失？

### ISSUE THREAD

**Issue by Mosowe** [youzan/vant-weapp#3381]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater?repo=VantWeapp

**Comment by rex-zsd** [comment]
跟 #3279 应该是相同问题，最新微信基础库在部分机型下动画性能有严重下降。
可以关注下那个 issue

**Comment by Mosowe** [comment]
> 跟 #3279应该是相同问题，最新微信基础库在部分机型下动画性能有严重下降.
> 可以关注下那个问题

不是微信浏览器，是一般的小米手机自带浏览器，跟微信基础库没关系的
