### ISSUE TITLE
[Feature Request] van-uploader图片模式下，希望加入图片名称的显示。

### ISSUE THREAD

**Issue by wonailmy** [youzan/vant-weapp#3382]
### 这个功能解决了什么问题
大量的业务场景下，用户希望对自身拍摄的照片进行一个描述。同时期望能在页面上直观显示出来！
使用van-uploader的时候，在非图片模式下，name会在预览框底部展示出来。但图片模式下却不能。

### 建议的API是什么样的
van-uploader 组件通过配置 file-list，直接利用其name属性即可。

**Comment by scmyxj** [comment]
van-uploader 组件通过配置 file-list，直接利用其name属性即可。

**Comment by xinghp** [comment]
实测不行，无效

**Comment by rex-zsd** [comment]
以目前 vant ui 的设计规范，没有计划给图片支持显示额外的文案哦。
