### ISSUE TITLE
[Bug Report] van-tag在van-cell中的自动换行在右侧留出了大量空白

### ISSUE THREAD

**Issue by milesmore** [youzan/vant-weapp#3387]
### 设备
模拟器

### VantWeapp 版本
1.3.3

### 基础库版本
2.11.3

### 如果是 UI 问题，截图链接（多图回车分隔）

![截图](https://i.loli.net/2020/07/14/kDEcCHh2Zu9FwrU.png)

### 请提供核心代码片段链接
https://gist.github.com/milesmore/b10ecb9a9ac95f48dd5bfb5618b01ae3

### 描述问题
根据文档的写法在van-cell中使用van-tag，在tag中字数较多时，tag的自动换行在右侧留出了大量空白。不知道修改哪里能使tag中每一行显示更多的字后再换行？谢谢

**Comment by rex-zsd** [comment]
可以使用 `extra` 插槽哈，`title` 插槽在存在 `value` 时仅占据左侧空间。
