### ISSUE TITLE
[Bug Report] Tab 标签页在安卓手机下无法自适应高度

### ISSUE THREAD

**Issue by chuckyukai** [youzan/vant-weapp#3389]
### 设备
安卓 9

### VantWeapp 版本
1.3.3

### 基础库版本
2.11.3

### 请提供核心代码片段链接
https://gist.github.com/chuckyukai/691b478c9d11cc48ec724813fc636eb4

### 描述问题
当标签页内容高度不同的时候，从高度高的选项切换到高度低的选项，容器告诉还是最高的那个高度。这个问题在iOS下没有出现。

**Comment by rex-zsd** [comment]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater?repo=VantWeapp
