### ISSUE TITLE
vant van-cell中嵌入了一个van-field导致点击van-cell中的事件 唤醒不到嵌入的input的焦点

### ISSUE THREAD

**Issue by ZeroZC** [youzan/vant-weapp#3390]
![image](https://user-images.githubusercontent.com/31943066/87518603-0eebc700-c6b3-11ea-83db-6338ba525bcd.png)
![image](https://user-images.githubusercontent.com/31943066/87518691-2dea5900-c6b3-11ea-89fe-aab46c3d768b.png)

**Comment by ZeroZC** [comment]
点击第二次才能找到焦点

**Comment by sasikeya** [comment]
[问题图](https://img.esenyun.com/images/20200716/944c40a5df99466b9cf09a281a25a2d2.jpg) 我这边是下拉菜单中用了search 也出现了同样的问题

**Comment by rex-zsd** [comment]
@ZeroZC 测试原生小程序当中一次即可 focus，看下是否是mpvue导致的问题吧。

**Comment by rex-zsd** [comment]
@sasikeya 你的问题看起来不太一样。
dropdown-menu 是有一个展开的组件的，input作为原生组件，在含有位移动画的节点中渲染的时候，是会产生位置偏移的。
dropdown-menu 暂时不支持自定义展开动画的效果，可以把 `duration` 设为0，取消动画试试。
