### ISSUE TITLE
vant-button的点击效果

### ISSUE THREAD

**Issue by Sramler** [youzan/vant-weapp#3391]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater?repo=VantWeapp

请问小程序组件vant-button的点击效果怎么修改呢

**Comment by rex-zsd** [comment]
描述太模糊，不理解是什么问题，可以扫下主页二维码加微信群交流哈。
