### ISSUE TITLE
van-image-preview 图片预览，两个手操作，边左滑边放大，图片会错位，应该在左滑的时候禁止放大，放大的时候禁止左滑

### ISSUE THREAD

**Issue by baijing19920921** [youzan/vant-weapp#3395]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater?repo=VantWeapp
van-image-preview 图片预览，两个手操作，边左滑边放大，图片会错位，应该在左滑的时候禁止放大，放大的时候禁止左滑

**Comment by rex-zsd** [comment]
是不是提错 issue 了，vant weapp 并没有 image-preview 组件，vant 是有的。
指路 https://github.com/youzan/vant/issues
