### ISSUE TITLE
[Bug Report] stepper设置max和step的问题

### ISSUE THREAD

**Issue by forget1** [youzan/vant-weapp#3396]
### 设备
所有移动手机设备

### VantWeapp 版本
1.3.3

### 基础库版本
2.11.0

### 请提供核心代码片段链接
https://gist.github.com/forget1/037de17e29b5ca9f517778bed79018c6

### 描述问题
设置step为2 ，max为13时，点击增加，会得到13这个结果，我希望是只能到12之后就不能继续向上增加。这个问题请问怎么解决

**Comment by rex-zsd** [comment]
如果有这种需求的话，可以将max设置为step的倍数。
