### ISSUE TITLE
日历组件首次显示不是默认日期所在的月而是第一个月

### ISSUE THREAD

**Issue by tanglm4346** [youzan/vant-weapp#3402]

**Comment by tanglm4346** [comment]
我的设置：最小日期是两年前    最大日期是两年后，默认日期是今天。首次显示是两年前的7月

**Comment by rex-zsd** [comment]
测试首次是显示到默认日期所在的月的，暂未复现问题。

**Comment by ATaurenRideRocket** [comment]
如果是平铺的话需要在mounted中添加重置方法
this.$nextTick(() => {
      this.$refs.calendar.reset();
    });

**Comment by JokerAn** [comment]
<van-calendar
        v-model="pickRangeShow"
        :default-date="null"
        type="range"
        :min-date="minDate"
        :max-date="maxDate"
       />
minDate: new Date('1950/01/05'),
      maxDate: new Date('2030/11/30'),
pickRangeShow:true
![image](https://user-images.githubusercontent.com/23717175/116063961-23d09e80-a6b8-11eb-8152-47ecaa7f8a2f.png)

**Comment by JokerAn** [comment]
哪个测试没测出来就给关闭了啊！！！
