### ISSUE TITLE
不能在v-for中使用van-collapse

### ISSUE THREAD

**Issue by xicaiZhou** [youzan/vant-weapp#3404]
在开发中，尝试在v-for中使用van-collapse，发现有如下bug。
只有点击最后一个item的时候才会展示出内容。其他均无。
具体代码如下：
        <van-collapse accordion :value="activeName" @change="onChange">
          <div class="file-item" v-for="(item,index) in this.loanFileVoList" :key="index">
            <van-collapse-item title="有赞微商城" :name="index">提供多样店铺模板，快速搭建网上商城</van-collapse-item>
          </div>
        </van-collapse>
data() {
    return {
      loanFileVoList: [],
      activeName: 0
    };
    onChange(event) {
      this.activeName = event;
    },

**Comment by rex-zsd** [comment]
![Jietu20200721-114743-HD](https://user-images.githubusercontent.com/8767877/88010849-69b86f00-cb48-11ea-987a-b2f308a10803.gif)
测试了一下，并没有复现这个问题，可以查看下是否是代码代码逻辑或列表数据的问题？
