### ISSUE TITLE
[Bug Report] van-area：三列联动的时候第二列不能选中，总是会回选至初始的选项

### ISSUE THREAD

**Issue by bks233** [youzan/vant-weapp#3405]
### 设备
红米note8 pro

### VantWeapp 版本
1.4.0

### 基础库版本
2.11.3

### 请提供核心代码片段链接
https://gitee.com/bks233/codes/84phz2kvs3foby0wxu9i7100

### 描述问题
van-area：三列联动的时候第二列不能选中，总是会回选至初始的选项

**Comment by AlexzZzNM** [comment]
刚好今天遇到了看了下应该是第一栏和第二栏的索引共用了.你可以找到@vant/weapp/area/index.js  201行的If语句中删掉indexes.push(this.getIndex('province', code));暂时解决

**Comment by lengxiaotian** [comment]
也是遇到同样的问题了，看官方的没问题，哎，自己的的试了很多次，还是不对！
应该是一个BUG，官方没更新！

**Comment by SuperTaric** [comment]
`
if (this.data.columnsNum >= 2) {
  stack.push(picker.setColumnValues(1, city, false));
  // indexes.push(this.getIndex('province', code));
  indexes.push(this.getIndex('city', code));
  if (city.length && code.slice(2, 4) === '00') {
    [{ code }] = city;
  }
}
`
将这一行的province改为city
