### ISSUE TITLE
小程序中使用遮盖层组件，结构show=true能显示，但是遮盖层样式没有生效

### ISSUE THREAD

**Issue by skaural** [youzan/vant-weapp#3408]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater?repo=VantWeapp

**Comment by rex-zsd** [comment]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater?repo=VantWeapp
