### ISSUE TITLE
[Bug Report] van-uploader accept为media时真机上传视频时的大小及时间限制

### ISSUE THREAD

**Issue by Pankzou** [youzan/vant-weapp#3409]
### 设备
华为p20pro

### VantWeapp 版本
1.3.2

### 基础库版本
2.7.2

### 请提供核心代码片段链接
https://gitee.com/pankzou/codes/8cdqe3x5p4lohw1yfbm2987

### 描述问题
给van-uploader设置accept为media，设置max-size为10485760时（10M），在开发者工具中，可以正常判断视频文件的大小，在真机上上传一个超过10M的视频并不触发oversize监听，打印选择后的文件，size是被压缩过的，我并没有设置compressed压缩设置。compressed压缩设置也只有在accept为video才会被设置上

**Comment by rex-zsd** [comment]
gitee点进去404，

**Comment by rex-zsd** [comment]
`type= sizeType ` 时 `sizeType` 默认是 `['original', 'compressed']`，是开启压缩的，可以把它设置为 `['original']` 关闭压缩.
