### ISSUE TITLE
[Bug Report] van-field和van-popup同时使用使用bug

### ISSUE THREAD

**Issue by jiaxiongTang** [youzan/vant-weapp#3412]
### 设备
Android

### VantWeapp 版本
1.4.0

### 基础库版本
2.11.2

### 如果是 UI 问题，截图链接（多图回车分隔）

![截图](<a)

![截图](href="https://sm.ms/image/MK69ReiaByTIDgF")

![截图](target="_blank"><img)

![截图](src="https://i.loli.net/2020/07/20/MK69ReiaByTIDgF.png")

![截图](></a>)

![截图](<a)

![截图](href="https://sm.ms/image/osZGcq7QNS6ItyV")

![截图](target="_blank"><img)

![截图](src="https://i.loli.net/2020/07/20/osZGcq7QNS6ItyV.png")

![截图](></a>)

### 请提供核心代码片段链接
https://youzan.github.io/vant-weapp/#/popup

### 描述问题
van-field使用type=textarea时输入框中的内容会在van-popup上层显示，且只在Android手机出现bug

**Comment by rex-zsd** [comment]
看下[文档说明](https://youzan.github.io/vant-weapp/#/field#zhen-ji-shang-placeholder-wei-shi-me-hui-gai-guo-popup-deng-qi-ta-zu-jian),textarea是原生组件，受到原生组件的限制的。
