### ISSUE TITLE
[Feature Request] 希望在DatetimePicker文档和API中添加[秒]

### ISSUE THREAD

**Issue by HebutShuji** [youzan/vant-weapp#3413]
### 这个功能解决了什么问题
在timepicker中datetime类型中，如果精确到秒，可以和web端系统时间"YY-MM-DD HH-mm-SS"进行数据上的同步

### 建议的API是什么样的
DatetimePicker时间选择组件中API[columns-order]自定义列排序数组, 子项可选值为year、month、day、hour、minute、second

**Comment by HebutShuji** [comment]
磕头了 砰砰砰

**Comment by niulin1991** [comment]
加1

**Comment by rex-zsd** [comment]
秒暂时应该不会支持了，抱歉哈

**Comment by HebutShuji** [comment]
请问那可以支持自定义类型吗 我在秒的地方自己定义一列。。。^^_

**Comment by rex-zsd** [comment]
可以用picker组件实现一下
