### ISSUE TITLE
[Bug Report] van-datetime-picker  组件 无法获取实例， 也无法获取change事件下的组件进行相应的更新等操作

### ISSUE THREAD

**Issue by zhaodaxian** [youzan/vant-weapp#3420]
### 设备
苹果

### VantWeapp 版本
1.4.0

### 基础库版本
2.12.0

### 请提供核心代码片段链接
https://github.com/zhaodaxian/vant-bug

### 描述问题
您好， 我是需要在小程序中 使用 van-datetime-picker 组件， 然后在change事件中 需要使用getValues 事件来更新数据
，我看上面说需要获取实例， this.selectComponent('.control-count-down')   我使用这种方法获取实例但是实例中并没有getValues () 这个方法

**Comment by zhaodaxian** [comment]
也并没change事件中的其他方法，大佬求支援，我真的不知道自己哪里错啦

**Comment by zhaodaxian** [comment]
即便是通过event 传参的方式 event.getValues() 这样也获取不到实例啊

**Comment by zhaodaxian** [comment]
![image](https://user-images.githubusercontent.com/35218887/88070027-c8abd180-cba4-11ea-9554-cf7e86d57584.png)

**Comment by rex-zsd** [comment]
`event.detail.getValues`，小程序的事件，值都是在`event.detail`里的。
