### ISSUE TITLE
IndexBar 右侧Anchor滑动过快时 onTouchMove 事件对Anchor索引赋值出错

### ISSUE THREAD

**Issue by ChobitsSP** [youzan/vant-weapp#3422]
### 设备
iphone xs

### VantWeapp 版本
1.4.0

### 基础库版本
1.4.0

### 请提供核心代码片段链接
https://github.com/youzan/vant-weapp/blob/dev/lib/index-bar/index.js#L249

### 描述问题
滑动过快时 onTouchMove 事件对Anchor索引赋值出错 导致索引显示错乱(最终结果是正确的)
我们修改源码 对onTouchMove加上防抖(lodash.debounce 30毫秒)后解决此问题

**Comment by 1037055457** [comment]
我遇到了这样的一个问题，当【A-Z】字母索引都有的时候，但是其中某个字母没有对应的列表时，此时点击它下一个字母，呈现的结果是：**列表是显示出下一个字母的内容，但字母索引选中的是上一个字母的状态..依次点下去都出现这样的问题了，当出现多个情况时，索引赋值差距会越来越大**

**Comment by wjwjq** [comment]
当indexbar与van-tabs一起使用时，设置van-tabs的sticky属性为true, 通过索引滚动时，会出现闪白问题。 可通过官方示例过复现。
设备
iphone 12

**Comment by landluck** [comment]
> 我遇到了这样的一个问题，当【A-Z】字母索引都有的时候，但是其中某个字母没有对应的列表时，此时点击它下一个字母，呈现的结果是：列表是显示出下一个字母的内容，但字母索引选中的是上一个字母的状态..依次点下去都出现这样的问题了，当出现多个情况时，索引赋值差距会越来越大

建议单独提个issue，提供一下信息进行解决

**Comment by landluck** [comment]
> 当indexbar与van-tabs一起使用时，设置van-tabs的sticky属性为true, 通过索引滚动时，会出现闪白问题。 可通过官方示例过复现。 设备 iphone 12

单独提交issue，提供一下示例

**Comment by landluck** [comment]
> 

可以描述更清晰点，或者提供一个复现视频协助定位问题

**Comment by landluck** [comment]
issue 反馈时间太久，无法复现问题，如后续遇到同样的问题建议提供小程序代码片段后重新提交 issue 协助排查
