### ISSUE TITLE
[Bug Report] van-popup无法遮盖van-tabbar

### ISSUE THREAD

**Issue by Satlantisy** [youzan/vant-weapp#3423]
### 设备
开发工具和iPhone

### VantWeapp 版本
1.4.0

### 基础库版本
2.12.0

### 请提供核心代码片段链接
https://youzan.github.io/vant-weapp/#/tabbar

### 描述问题
popup、action-sheet和tabbar三个组件同时使用，popup和action-sheet无法覆盖popup，无论z-index调到多高都不起作用。

**Comment by rex-zsd** [comment]
tabbar是原生组件，受原生组件限制，可以看下[微信官方文档](https://developers.weixin.qq.com/miniprogram/dev/component/native-component.html)哈。

**Comment by Satlantisy** [comment]
> tabbar是原生组件，受原生组件限制，可以看下[微信官方文档](https://developers.weixin.qq.com/miniprogram/dev/component/native-component.html)哈。

我用的是van-tabbar呀，不是原生的tabbar。

**Comment by Satlantisy** [comment]
> > tabbar是原生组件，受原生组件限制，可以看下[微信官方文档](https://developers.weixin.qq.com/miniprogram/dev/component/native-component.html)哈。
> 
> 我用的是van-tabbar呀，不是原生的tabbar。

没事了，明白了

**Comment by spiritelf** [comment]
那能控制van-tabbar动态显示隐藏吗？
