### ISSUE TITLE
[Bug Report] DropdownMenu 下拉菜单中添加Search组件会出现input上移

### ISSUE THREAD

**Issue by sasikeya** [youzan/vant-weapp#3428]
### 设备
IOS

### VantWeapp 版本
1.4.0

### 基础库版本
2.11.3

### 如果是 UI 问题，截图链接（多图回车分隔）

![截图](https://img.esenyun.com/images/20200723/d6d3244ea39c4eb2874c61b6319d1d3a.png)

### 请提供核心代码片段链接
https://developers.weixin.qq.com/s/47tgJ3mp76je

### 描述问题
开发者工具没问题，真机就会出现
在下拉菜单中添加Search之类的组件 只要下面还有别的组件 输入框就会出现上移 无法点击

**Comment by rex-zsd** [comment]
测试了一下 vant weapp 这边没有什么能做的
在浮层中直接嵌套 input 时，iOS也会出现相同的问题。
应该是因为 input 作为原生组件，在动画显隐藏时，渲染有问题。
可以尝试下给 search 组件加上 `wx:if`，在切换到这一项，内容显示时，再手动显示 search 让其渲染。
