### ISSUE TITLE
tab的border建议可以设置

### ISSUE THREAD

**Issue by yuu2lee4** [youzan/vant-weapp#343]
我记得之前是没有border的，有的时候不需要border，或者tab与其他元素排一排的时候 需要父组件去设置border就很尴尬了

**Comment by chenjiahan** [comment]
目前 zanui-weapp 已进行全新的品牌升级，更名为 Vant Weapp，组件和 API 都有较大的变化。

对 zanui-weapp 的讨论，请移步至 https://github.com/youzan/zanui-weapp 仓库
