### ISSUE TITLE
[Bug Report] 紧急 - textarea在van-popup中显示有问题

### ISSUE THREAD

**Issue by Satlantisy** [youzan/vant-weapp#3431]
### 设备
iPhone Xs Max

### VantWeapp 版本
1.4.0

### 基础库版本
2.12.0

### 如果是 UI 问题，截图链接（多图回车分隔）

![截图](https://sm.ms/image/BSNGkx2ajDe7y3Q)

![截图](https://sm.ms/image/w6hGZUBnbeAsVSC)

![截图](https://sm.ms/image/yjMfuUvmYseJNzZ)

### 请提供核心代码片段链接
https://developers.weixin.qq.com/s/xOy834mT7tjF

### 描述问题
textarea组件在van-popup内会出现两种不正常的情况，不清楚是popup问题还是textarea的问题。
1. 设置autosize后，textarea自动增高，第一行和第二行文字会被覆盖或者显示不完整。
2. 拉起popup后设置focus=true拉起键盘不起作用，但很奇怪只有第一次弹出popup不会拉起键盘，之后就可以了。

如果textarea不在popup内就没问题。开发工具内一切正常，真机调试才出现。

**Comment by Satlantisy** [comment]
https://sm.ms/image/yjMfuUvmYseJNzZ
https://sm.ms/image/BSNGkx2ajDe7y3Q
https://sm.ms/image/w6hGZUBnbeAsVSC

**Comment by rex-zsd** [comment]
1. `autosize` 属性对应着原生 textarea 的 `auto-height`，行为是原生处理的，vant weapp 这边没法影响。
2. `focus` 也是 textarea 的原生属性，textarea 作为原生组件，嵌套在浮层内是会出现一些意外的问题的。

第1个问题可以尝试给 popup 的 `duration` 设置为0，取消位移动画，可能对改善 textarea 位移的问题有帮助。

**Comment by Satlantisy** [comment]
> 1. `autosize` 属性对应着原生 textarea 的 `auto-height`，行为是原生处理的，vant weapp 这边没法影响。
> 
> 2. `focus` 也是 textarea 的原生属性，textarea 作为原生组件，嵌套在浮层内是会出现一些意外的问题的。
> 
> 
> 
> 第1个问题可以尝试给 popup 的 `duration` 设置为0，取消位移动画，可能对改善 textarea 位移的问题有帮助。

我自己写了个简单的popup，把vant的textarea放在里面没有问题。
那问题应该是在van-popup里了。

**Comment by vic091** [comment]
华为手机p30 ， 当拉起popup时，页面中的textarea内容会高亮？其他手机没有问题
