### ISSUE TITLE
tabbar上面还有固定栏问题

### ISSUE THREAD

**Issue by spiritelf** [youzan/vant-weapp#3432]
![image](https://user-images.githubusercontent.com/8556186/88352143-5a753380-cd8b-11ea-97d8-dc461752e8b8.png)

使用自定义tabbar以后，上面那一栏有什么方法可以和底部固定在一起？
之前原生的使用bottom：0就可以。

**Comment by rex-zsd** [comment]
`bottom: 50px` 这样？留出底部tabbar的距离

**Comment by spiritelf** [comment]
用了自定义tabbar，滚动条无法滚动到最下面部分内容？？
