### ISSUE TITLE
[Bug Report] dropDownMenu下拉框问题

### ISSUE THREAD

**Issue by hj009** [youzan/vant-weapp#3437]
### 设备
微信开发者工具

### VantWeapp 版本
1.4.0

### 基础库版本
1.4.0

### 请提供核心代码片段链接
https://github.com/youzan/vant-weapp/issues/new

### 描述问题
uniapp 引用 vant weapp 1.4.0   下拉菜单使用后会多一个透明遮罩层，主页内容无法进行其他操作,使用1.0.0版本则没有该现象

**Comment by auven** [comment]
@hj009  uniapp 的问题   https://github.com/dcloudio/uni-app/issues/1802
