### ISSUE TITLE
请问那可以支持自定义类型吗 我在秒的地方自己定义一列。。。^^_

### ISSUE THREAD

**Issue by HebutShuji** [youzan/vant-weapp#3438]
请问那可以支持自定义类型吗 我在秒的地方自己定义一列。。。^^_

_Originally posted by @HebutShuji in https://github.com/youzan/vant-weapp/issues/3413#issuecomment-664091065_

**Comment by rex-zsd** [comment]
可以自行用picker组件实现一下的
