### ISSUE TITLE
微信小程序van-action-sheet不生效

### ISSUE THREAD

**Issue by win434545299** [youzan/vant-weapp#3439]
您好，微信小程序中使用van-action-sheet不生效，我只是把官方页面的demo粘贴进小程序里面，额外增加了title，发现怎么样都不展示数据，点击事件什么的全无效...万望大神帮解决一下，我现在的vant版本是1.3.2，微信小程序的开发版本是2.12.0

**Comment by rex-zsd** [comment]
使用姿势的问题，扫下首页的二维码进群咨询吧。
提issue也不遵守格式，没办法帮你定位问题了。

**Comment by win434545299** [comment]
好的，谢谢
