### ISSUE TITLE
van-field的label-class 不生效

### ISSUE THREAD

**Issue by LCBbest** [youzan/vant-weapp#3440]
van-field的label-class 不生效
![image](https://user-images.githubusercontent.com/12879534/88507251-92d87400-d00e-11ea-8341-13ed747379a8.png)
![image](https://user-images.githubusercontent.com/12879534/88507259-9835be80-d00e-11ea-8b76-093fd978fa23.png)

**Comment by rex-zsd** [comment]
这里用 `width` 是无法覆盖的，因为原样式是通过 `min-width` 和 `max-width` 来控制宽度。
可以用 van-field 组件的 `title-width` 属性来定制。
