### ISSUE TITLE
[Bug Report] popup结合picker使用时响应延迟

### ISSUE THREAD

**Issue by xuonly0501** [youzan/vant-weapp#3441]
### 设备
iphone8

### VantWeapp 版本
1.3.3

### 基础库版本
2.9.4

### 请提供核心代码片段链接
https://developers.weixin.qq.com/s/GTcpIbmb73jw

### 描述问题
popup结合picker使用时响应慢，需要3~5秒左右

**Comment by 601460003** [comment]
我也遇到这个问题，最后用原生小程序picker 解决了
