### ISSUE TITLE
导入van-calendar控件，iOS真机测试导致页面空白，退出后无法点击

### ISSUE THREAD

**Issue by WuDevin** [youzan/vant-weapp#3442]
<van-calendar
 title="请选择日期区间"
 poppable="{{ true }}"
 show-confirm="{{ true }}" 
 show="{{ calendarShow }}"
 position="bottom"
 type="range"
 bind:close="calendarClosed"
 bind:confirm="calendarConfirmed"
 confirm-text="确定"
 confirm-disabled-text='请选择区间'
 color = '#099fff'
 show-mark ="{{false}}"
 show-subtitle ="{{false}}"
 min-date = '{{beginTime}}'
 maxDate = '{{curTime}}'
 default-date = '{{[startTime,endTime]}}'
/>

**Comment by TyroneLao** [comment]
我也碰到了，iPhone6s，ios14.4；vant 1.7.2；微信8.0.1
