### ISSUE TITLE
popup弹出层问题

### ISSUE THREAD

**Issue by Honker-Cybersecurity** [youzan/vant-weapp#3444]
使用该弹出层的时候，如果有遮盖输入框，那么输入框的placeholder属性里面的文字能够显示出来，并且能够点击聚焦输入框。这该如何解决？

**Comment by rex-zsd** [comment]
输入框是[原生组件](https://developers.weixin.qq.com/miniprogram/dev/component/native-component.html)，这个没办法覆盖的。
只能手动判断在弹层弹出来的时候，把下面的输入框隐藏掉

**Comment by Honker-Cybersecurity** [comment]
> 输入框是[原生组件](https://developers.weixin.qq.com/miniprogram/dev/component/native-component.html)，这个没办法覆盖的。
> 只能手动判断在弹层弹出来的时候，把下面的输入框隐藏掉

好的，谢谢你
