### ISSUE TITLE
[Bug Report] Tabbar 在fixed的情况下，能否生成一个跟tabbar高度一样的节点？

### ISSUE THREAD

**Issue by kinder1995** [youzan/vant-weapp#3445]
### 设备
iphone X

### VantWeapp 版本
1.4.1

### 基础库版本
2.12

### 请提供核心代码片段链接
https://github.com/kinder1995/vant-tabbar

### 描述问题
tabbar是自定义组件，开启了适配iphone x的时候，底部tabbar的高度跟iphone 8的不一致，导致在页面调用的时候拉到底部会有一点遮挡到内容。
可不可以在开启的时候默认生成一个节点？这个节点就是tabbar的高度。
又或者怎么获取tabbar的高度？

**Comment by oloshe** [comment]
我也遇到这个问题，有个叫env(safe-area-inset-bottom)的css值可以获取iphoneX的底部安全区域。但是还是希望可以直接在组件获取到高度。
