### ISSUE TITLE
[Bug Report] calendar设置min-date时存在严重性能问题

### ISSUE THREAD

**Issue by tomliuchangsha** [youzan/vant-weapp#3446]
### 设备
Android,IOS

### VantWeapp 版本
1.4.1

### 基础库版本
2.12.0

### 请提供核心代码片段链接
https://gist.github.com/tomliuchangsha/da4ee38bb4314c2c54a013efff82e2db

### 描述问题
如果仅设置min-date，而不设置max-date将导致加载非常缓慢。设置max-date(即使设置文档中的默认值)后，加载速度恢复正常。

**Comment by rex-zsd** [comment]
```
<van-calendar
  show="{{ show }}"
  min-date="{{ minDate }}"
  default-date="{{ defaultDate }}"
/>
Page({
  data: {
    show: false,
    minDate: new Date(2010, 0, 1).getTime()，
    defaultDate: new Date().getTime()
  },
});
```

这里 `minDate` 设置在了 10 年前，会造成页面上渲染大量的 view，会存在严重的性能问题的。
这一点已经在文档里有说明了，可以将 `minDate` 与 `maxDate` 的区间尽可能缩小。

**Comment by sjdong** [comment]
是否可以考虑增加监听页面当前渲染的元素，将超出屏幕的元素通过wx:if或者Hidden影藏？这样是否有助于减少性能问题？
