### ISSUE TITLE
tabs 的吸顶效果bug

### ISSUE THREAD

**Issue by lixindada** [youzan/vant-weapp#3448]
tabs 里面的数据如果是动态获取的 那么吸顶效果就会失效
![image](https://user-images.githubusercontent.com/27477476/88774324-dd482500-d1b5-11ea-9d6c-3555b7019906.png)

**Comment by rex-zsd** [comment]
sticky 的吸顶都是实时计算的，动态渲染实测也是没有问题的。
没有完整可运行的代码片段，暂时无法继续排查了。
