### ISSUE TITLE
[Bug Report] 在popup里放入collapse组件，第一次加载时没有数据渲染出来

### ISSUE THREAD

**Issue by 908705107** [youzan/vant-weapp#3449]
### 设备
windows

### VantWeapp 版本
1.4.0

### 基础库版本
2.11.3

### 如果是 UI 问题，截图链接（多图回车分隔）

![截图](https://sm.ms/image/dsyi5glYJcLptz3)

![截图](https://sm.ms/image/4sDYQSPU9Vqnlzd)

### 请提供核心代码片段链接
https://github.com/908705107/vantweapp_bug.git

### 描述问题
在popup里放入collapse组件，第一次加载时没有数据渲染出来，要再次点击收起和展开后才能渲染页面，看到另一个issue的解决方案是把van-collapse 通过 wx:if 控制和popup同步，我尝试后还是没有渲染出页面

**Comment by 908705107** [comment]
代码截图：
https://sm.ms/image/dsyi5glYJcLptz3
https://sm.ms/image/4sDYQSPU9Vqnlzd

**Comment by hjt911026** [comment]
我在popup里放area三联显示的时候第二列和第三列有时候不显示，奇怪的是有时候会显示。

**Comment by 908705107** [comment]
> 我在popup里放area三联显示的时候第二列和第三列有时候不显示，奇怪的是有时候会显示。

奇怪了，我也有时候显示有时候不显示。。用了 wx:if感觉还是解决不了这个问题

**Comment by arlindar1030** [comment]
我的也是，今天从1.3升级上来Collapse就这样了。

**Comment by 908705107** [comment]
> 我的也是，今天从1.3升级上来Collapse就这样了。

我改源码解决了，看这篇文章http://www.chenlinshan.com/#/ArticleDetail?Id=1290672553907458048

**Comment by arlindar1030** [comment]
> > 我的也是，今天从1.3升级上来Collapse就这样了。
> 
> 我改源码解决了，看这篇文章http://www.chenlinshan.com/#/ArticleDetail?Id=1290672553907458048

谢谢兄弟
