### ISSUE TITLE
列表van-swipe-cell 组件里面使用 van-action-sheet组件会出现每个列表单独弹出action-sheet

### ISSUE THREAD

**Issue by TomSonghang** [youzan/vant-weapp#3452]
在列表里面使用van-swipe-cell组件实现左滑删除功能,在单个列表里面又有一个van-action-sheet组件;然而点击弹出的时候却在单个列表内容框里弹出来,而且每个列表都能弹出来;我在van-swipe-cell组件上设置disabled属性为true之后恢复正常

**Comment by rex-zsd** [comment]
看下`transfrom`与`position: fixed`的关系。

**Comment by rex-zsd** [comment]
含动画的组件内，尽量避免使用全局定位的样式。
这个场景可以将van-action-sheet移动到van-swipe-cell外面。
