### ISSUE TITLE
2020/07/30 访问不了

### ISSUE THREAD

**Issue by 601460003** [youzan/vant-weapp#3453]
https://youzan.github.io/vant/#/zh-CN/dropdown-menu  无法访问此网站youzan.github.io 拒绝了我们的连接请求。
请试试以下办法：

检查网络连接
检查代理服务器和防火墙
ERR_CONNECTION_REFUSED

**Comment by MENGJ1E** [comment]
我也访问不了了

**Comment by 601460003** [comment]
> 我也访问不了了

都两天了 硬生生的去看源码 接着写 哭死了

**Comment by liuxiaohui1218** [comment]
文档访问不了,中国IP被封了吗？

**Comment by rex-zsd** [comment]
看下项目首页，有贴国内镜像文档呀
