### ISSUE TITLE
Toast.clear() 有时候失效

### ISSUE THREAD

**Issue by Lemon71** [youzan/vant-weapp#3455]
我现在是这样写的
小程序全局的请求方法中，每次请求前都会调用Toast方法弹起loading，然后请求完成（无论成功失败）的时候就会调用Toast.clear() 把弹框清除
每个页面都有复制一段一样的<van-toast id="van-toast"> 节点

然后出现的问题是，有时候能正常清除，有时候无法正常清除，甚至超过了设定的60s，toast依然存在
电脑调试工具没出现这个问题，手机端有时候会有这个问题，想调试都调试不了

是我写法有什么问题吗，但是电脑端100%没问题，手机端90%没问题，但是有10%就很难受了

**Comment by herfrain** [comment]
更新之后会抛出 incongruent status: enter 错误，然后有时也还是不能关闭toast
