### ISSUE TITLE
最近这个域名地址访问不了？ https://youzan.github.io/

### ISSUE THREAD

**Issue by spiritelf** [youzan/vant-weapp#3457]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater?repo=VantWeapp

**Comment by badjone** [comment]
我这一样

**Comment by chenjiahan** [comment]
最近 Github 在国内部分地区的访问出现了问题，建议访问国内镜像站点：https://vant-contrib.gitee.io/vant-weapp/

**Comment by rex-zsd** [comment]
可以看下首页readme，有贴国内镜像网站的。

**Comment by spiritelf** [comment]
VM195:1 Failed to load font https://img.yzcdn.cn/vant/vant-icon-d3825a.woff2
net::ERR_CACHE_MISS    小程序里这个还经常报错

**Comment by rex-zsd** [comment]
@spiritelf 
[文档](https://youzan.github.io/vant-weapp/#/icon#chang-jian-wen-ti)里都有说明哈，请仔细看下。
