### ISSUE TITLE
Area 省市区选择。三联显示的时候，第二列（市列）拖拽滚动，松手就回弹。

### ISSUE THREAD

**Issue by hjt911026** [youzan/vant-weapp#3461]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。
https://vant-contrib.gitee.io/vant-weapp/#/area

**Comment by rex-zsd** [comment]
1.4.1已修复了，升级下即可哈。
