### ISSUE TITLE
在微信小程序里，Field 输入框修改type属性的值为number idcard textarea digit类型无效

### ISSUE THREAD

**Issue by 1877127808** [youzan/vant-weapp#3469]
在微信小程序里，Field 输入框修改type属性的值为number idcard textarea digit类型无效，还有你们的网站现在用电信网络访问不了

**Comment by rex-zsd** [comment]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater?repo=VantWeapp
