### ISSUE TITLE
Uploader 文件上传组件微信小程序环境下无法使用删除功能

### ISSUE THREAD

**Issue by sweetsmile888** [youzan/vant-weapp#3471]
微信小程序环境下使用的效果：
![bug1](https://user-images.githubusercontent.com/23272503/89159351-f1b76380-d5a1-11ea-8143-f8ba2c28a38b.jpg)
代码如下
` <van-field
        value=""
        disabled
        label="身份证"
        border="false"
        required="true"
      />
      <view style="width:94%;margin:0 auto;border:none;margin-top:10px">
        <van-uploader
          file-list="{{ idcard }}"
          bind:after-read="afterReadidcard"
          max-count="2"
          accept="image"
          border="none"
        />
      </view>
     <van-field
        value=""
        label="营业执照"
        disabled
        border="false"
        required="true"
      />
      <view style="width:94%;margin:0 auto;border:none;margin-top:10px">
        <van-uploader
          file-list="{{ certificate }}"
          bind:after-read="afterReadcertificate"
          max-count="2"
          accept="image"
          border="none"
        />
      </view>`

**Comment by rex-zsd** [comment]
看代码，缺少 `delete` 事件的监听。
删除需要监听 `delete` 事件，并在回调函数中自行删除数据。
`delete` 事件的参数可以看下文档哈。
