### ISSUE TITLE
dateTimePicker 设置 type=“time” 且使用 formatter 时取值错误

### ISSUE THREAD

**Issue by Teemwu** [youzan/vant-weapp#3474]
https://github.com/youzan/vant-weapp/blob/e5e9b27ba4a7fce9ee0748b9f00da608b2343948/packages/datetime-picker/index.ts#L298-L299
改为：
```javascript
       value = `${parseInt(data.columns[0].values[indexes[0]],10)}:${parseInt(data.columns[1]
          .values[indexes[1]],10)}`;
```
即可。

**Comment by rex-zsd** [comment]
此处 `value` 必须是未被 formatter 的值，否则可能会造成结果错误
你的问题是什么呢？

**Comment by Teemwu** [comment]
抱歉，重新拉取仓库代码下来跑已经没问题了。
之前问题可能是我本地修改源码增加自定义功能时产生了错误，跟主仓库没关系。
