### ISSUE TITLE
[Bug Report] 小程序QuickType Bar填充验证码无效或填充不全（高概率）

### ISSUE THREAD

**Issue by cole1993** [youzan/vant-weapp#3477]
### 设备
安卓和ios（安卓有时能跳出quick type，有时是复制验证码，复制粘贴的话没问题）

### VantWeapp 版本
1.4.2

### 基础库版本
2.11.3

### 请提供核心代码片段链接
https://gist.github.com/cole1993/

### 描述问题
获取验证码后，在输入法上点击验证码，大概率会出现验证码填充失败或填充不全的情况，小概率又能填充完整的验证码

**Comment by rex-zsd** [comment]
这个应该是小程序原生的问题，vant weapp这边没有什么能做的。

**Comment by cole1993** [comment]
可是目前我只在自己的小程序上遇到过这个问题，其他的小程序上没碰到过（特意去测试了很多个）
