### ISSUE TITLE
vant-tabs异步渲染的tab从其他页面点击进来时选中状态无法切换

### ISSUE THREAD

**Issue by Kalo-c** [youzan/vant-weapp#3478]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater?repo=VantWeapp

**Comment by rex-zsd** [comment]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater?repo=VantWeapp
