### ISSUE TITLE
[Bug Report] van-tabs标签页上下滑动时切换页面另一个页面滑动到同样位置了

### ISSUE THREAD

**Issue by Webchenchangjian** [youzan/vant-weapp#3479]
### 设备
安卓手机

### VantWeapp 版本
1.4.1

### 基础库版本
2.12.0

### 请提供核心代码片段链接
https://gitee.com/xiao_chen1/codes/h2q0mzi9j3gsedvo6587n58

### 描述问题
在手机上页面使用vant tab标签栏组件时发现，当在第一个页签内容(列表)中，上下滑动到某个位置时，切换第二个页签，发现其内容也是滑动到同样位置了，反之亦然，一开始以为是动态加载数据影响的，换成本地静态数据测试依然是这样，这是不是组件的bug，页签之间切换，各自内容应该是相对独立展现的，求教如何解决

**Comment by zcjunblog** [comment]
这你需要的应该是  触发change事件时顺便让scroll滚到到顶部
`   uni.pageScrollTo({
                    scrollTop: 0,
                    duration: 0
                })`

**Comment by 13938417646** [comment]
> ### 设备
> 安卓手机
> 
> ### VantWeapp 版本
> 1.4.1
> 
> ### 基础库版本
> 2.12.0
> 
> ### 请提供核心代码片段链接
> https://gitee.com/xiao_chen1/codes/h2q0mzi9j3gsedvo6587n58
> 
> ### 描述问题
> 在手机上页面使用vant tab标签栏组件时发现，当在第一个页签内容(列表)中，上下滑动到某个位置时，切换第二个页签，发现其内容也是滑动到同样位置了，反之亦然，一开始以为是动态加载数据影响的，换成本地静态数据测试依然是这样，这是不是组件的bug，页签之间切换，各自内容应该是相对独立展现的，求教如何解决

你好，请问你这个问题解决了么？

**Comment by rex-zsd** [comment]
微信小程序的原生行为如此，不是 vant weapp 可以改变的。

**Comment by callmesoul** [comment]
3.需要自己去记录滚动高度，然后切换的时候用wx.pageScrollTo去返回高度
