### ISSUE TITLE
[Bug Report] 1.4.1 - 1.4.3的更新日志都没有更新

### ISSUE THREAD

**Issue by MGsniper** [youzan/vant-weapp#3483]
### 设备
PC

### VantWeapp 版本
1.4.3-beta.0

### 基础库版本
2.11.3

### 请提供核心代码片段链接
https://youzan.github.io/vant-weapp/#/changelog

### 描述问题
希望更新一下 更新日志。 目前vant weapp的小问题蛮多的，希望看一下最新版本有没有相应的解决。麻烦了>..<

**Comment by a497771654** [comment]
一直等官网更新，结果发现是代码更新了，日志没更新 @

**Comment by MGsniper** [comment]
==。感觉大佬们很忙，vant主干还是很活跃的，weapp版就有点乏了的感觉

**Comment by rex-zsd** [comment]
最近github的api一直连不上，changelog生成不出来= =
