### ISSUE TITLE
开发文档怎么打开不了了？

### ISSUE THREAD

**Issue by tang9716** [youzan/vant-weapp#3484]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater?repo=VantWeapp

**Comment by tang9716** [comment]
![image](https://user-images.githubusercontent.com/46391090/89369855-d703fc80-d711-11ea-95cd-9d40bd6cfb41.png)
默认怎么选中了B

**Comment by tang9716** [comment]
![image](https://user-images.githubusercontent.com/46391090/89369881-e71bdc00-d711-11ea-9e07-855a697d82f5.png)
怎么还能选中C的呢

**Comment by tang9716** [comment]
代码：<van-index-bar index-list="{{letterList}}" scroll-top="{{scrollTop}}">
    <van-index-anchor index="{{item}}" use-slot="true" wx:for="{{letterList}}" wx:if="{{userList[index].list}}" wx:key="index">
      {{item}}
      <van-cell wx:for="{{userList[index].list}}" wx:key="index" wx:for-item="items" title="{{items.name}}"></van-cell>
    </van-index-anchor>
</van-index-bar>
letterList是A到Z加#
userList是用户数据

**Comment by tang9716** [comment]
<van-index-bar index-list="{{letterList}}" scroll-top="{{scrollTop}}">
    <van-index-anchor index="{{item}}" use-slot="true" wx:for="{{letterList}}" wx:if="{{userList[index].list}}" wx:key="index">
      {{item}}
      <van-cell wx:for="{{userList[index].list}}" wx:key="index" wx:for-item="items" title="{{items.name}}"></van-cell>
    </van-index-anchor>
</van-index-bar>

**Comment by tang9716** [comment]
![image](https://user-images.githubusercontent.com/46391090/89369999-36620c80-d712-11ea-9be6-5553f2870e02.png)

**Comment by Wendy-WX** [comment]
同问，开发文档打不开了

**Comment by rex-zsd** [comment]
最近 github 被墙的厉害，可以访问国内镜像站哈。
https://vant-contrib.gitee.io/vant-weapp/#/intro
