### ISSUE TITLE
swiper-cell 小程序卡顿

### ISSUE THREAD

**Issue by lttao** [youzan/vant-weapp#3488]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater?repo=VantWeapp
swiper-cell 在小程序滑动打开删除 感觉掉帧似的

**Comment by rex-zsd** [comment]
是真机调试，还是预览，还是线上？

**Comment by rex-zsd** [comment]
使用真机调试的话，性能较差是正常的，仅用于测试逻辑。
性能方面的测试可以使用预览哈。
swipe-cell的使用css transition来实现渐变动画，性能上应该不会有太大的问题，除非页面上同时存在大量的组件，这种情况没有什么好的解法，推荐减少页面上的节点数哈。

**Comment by lttao** [comment]
预览和线上 慢慢滑动时 ios8P 是不是手机刷新率太低了导致

**Comment by lttao** [comment]
小程序官方拓展组件weui 的slideview 滑动性能会好些 同样的手机上不会那么卡帧 但移动端只喜欢用 vant
