### ISSUE TITLE
zan-field 的border 不显示的bug

### ISSUE THREAD

**Issue by hapyli** [youzan/vant-weapp#349]
### zan-field 的border 不显示的bug

***提交bug* **

** 多行 zan-field 的情况下，其border不显示**

**Comment by zyongLiu** [comment]
官方Demo中也有这个问题

**Comment by chenjiahan** [comment]
目前 zanui-weapp 已进行全新的品牌升级，更名为 Vant Weapp，组件和 API 都有较大的变化。

对 zanui-weapp 的讨论，请移步至 https://github.com/youzan/zanui-weapp 仓库
