### ISSUE TITLE
新人发现的一个小问题。

### ISSUE THREAD

**Issue by Supercca** [youzan/vant-weapp#3490]
开发指南上面有地方文字介绍错误。

https://youzan.github.io/vant/?source=vuejsorg#/zh-CN/divider
![image](https://user-images.githubusercontent.com/24471677/89500066-a09eae00-d7f3-11ea-87b6-d9fc47cc6112.png)

**Comment by rex-zsd** [comment]
额，反馈错仓库了，这边是vant weapp，你反馈的是vant的问题。
指路 https://github.com/youzan/vant
