### ISSUE TITLE
文档链接打不开

### ISSUE THREAD

**Issue by mango-Yu** [youzan/vant-weapp#3491]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater?repo=VantWeapp

https://youzan.github.io/vant-weapp    文档链接打不开
![image](https://user-images.githubusercontent.com/24276050/89548912-3eb56700-d83a-11ea-9f1a-8ea01c593b92.png)

**Comment by BlaaECR** [comment]
Please add the following four records in the hosts file of the C:\Windows\System32\drivers\etc directory
185.199.110.153 youzan.github.io
185.199.108.153 youzan.github.io
185.199.111.153 youzan.github.io
185.199.109.153 youzan.github.io

**Comment by rex-zsd** [comment]
https://vant-contrib.gitee.io/vant-weapp/#/intro
或者可以访问境内的镜像站
