### ISSUE TITLE
[Bug Report] vant tabs index.js 报错

### ISSUE THREAD

**Issue by 1workspace** [youzan/vant-weapp#3492]
### 设备
小程序开发模拟器最新版1.03.2006090， 微信基础库2.12.0

### VantWeapp 版本
1.4.3-beta.1

### 基础库版本
2.12.0

### 请提供核心代码片段链接
https://github.com/youzan/vant-weapp/blob/v1.4.3-beta.1/dist/tabs/index.js#L254

### 描述问题
我跟新了最新的库，当小程序加载后Console 报错。

offsetLeft - (navRect.width - tabRect.width) / 2
type error 。 cannot read property width of undefined
/vant/tabs/index.js:280:61

我做了 tabRect ？ offsetLeft - (navRect.width - tabRect.width) / 2 ： offsetLeft - (navRect.width - 0) / 2
错误消失。 是navRect 有没有定义的情况存在。

**Comment by Smi1e96** [comment]
问题在于没有默认的currentIndex 你可以试下[null改为0 ](https://github.com/youzan/vant-weapp/blob/v1.4.3-beta.1/dist/tabs/index.js#L103)就可以了

**Comment by 1workspace** [comment]
@Smi1e96 
我只负责汇报BUG 
我自己现在只做了一下简单容错。 
`tabRect ？ offsetLeft - (navRect.width - tabRect.width) / 2 ： offsetLeft - (navRect.width - 0) / 2`

**Comment by Smi1e96** [comment]
> @Smi1e96
> 我只负责汇报BUG
> 我自己现在只做了一下简单容错。
> `tabRect ？ offsetLeft - (navRect.width - tabRect.width) / 2 ： offsetLeft - (navRect.width - 0) / 2`
> 
> 你的方法更好，谢谢。现在先用你的办法

其实是这里出的问题 我现在尝试给他修复了
![image](https://user-images.githubusercontent.com/31199247/89706351-5b1ae600-d997-11ea-945c-c2056e00aa71.png)

**Comment by Smi1e96** [comment]
> @Smi1e96
> 我只负责汇报BUG
> 我自己现在只做了一下简单容错。
> `tabRect ？ offsetLeft - (navRect.width - tabRect.width) / 2 ： offsetLeft - (navRect.width - 0) / 2`
> 
> 你的方法更好，谢谢。现在先用你的办法

currentIndex改为0 active为名称会选不中 建议这样修复:smile:
currentIndex还是为null setCurrentIndexByName函数这样
![image](https://user-images.githubusercontent.com/31199247/89707181-69b8cb80-d99e-11ea-9e56-3df93b959af6.png)
