### ISSUE TITLE
[Bug Report] van-image在mpx中使用出现问题

### ISSUE THREAD

**Issue by ouxiong** [youzan/vant-weapp#3495]
### 设备
默认

### VantWeapp 版本
1.4.3

### 基础库版本
默认

### 请提供核心代码片段链接
https://youzan.github.io/vant-weapp/#/image

### 描述问题
mpx中引入，使用如下
![1.jpg](https://i.loli.net/2020/08/07/TmuIbgSKnFBkv61.jpg)
微信开发者工具提示错误如下：
![2.jpg](https://i.loli.net/2020/08/07/BT3FP9fYWIvihE1.jpg)
随便测试几个组件，不排除其他组件也有问题

**Comment by rex-zsd** [comment]
这个要看下mpx的文档，是如何使用第三方原生组件的姿势。
vant weapp 这边应该暂时没有什么能做的
