### ISSUE TITLE
van-switch-cell

### ISSUE THREAD

**Issue by mango-Yu** [youzan/vant-weapp#3497]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater?repo=VantWeapp
小程序里引用没有 van-switch-cell
![image](https://user-images.githubusercontent.com/24276050/89664136-44c64900-d909-11ea-95b2-4a40ec71e913.png)

**Comment by rex-zsd** [comment]
vant weapp 是没有 switch-cell 的，vant 的 switch-cell 也已经不推荐使用。
推荐使用 switch 和 cell 自行组合一下哈。
