### ISSUE TITLE
[Bug Report] collapse 卡顿 

### ISSUE THREAD

**Issue by Liulei1201** [youzan/vant-weapp#3499]
### 设备
所有设备

### VantWeapp 版本
1.4.3

### 基础库版本
2.11.3

### 请提供核心代码片段链接
https://developers.weixin.qq.com/s/ALwegume7rjg

### 描述问题
折叠面板用到真机上会很卡顿；不用代码片段，官网的体验二维码也是很卡顿；就是关闭的时候有延迟问题；怎么解决；

**Comment by rex-zsd** [comment]
确定使用的是1.4.3最新版？之前使用的 setTimeout 近期在微信上有卡顿，已经重构为小程序的 animation 了，测试是流畅的。

**Comment by rex-zsd** [comment]
这个代码片段在小米8、mate30、iPhoneX上测试都是流畅的。

**Comment by Liulei1201** [comment]
谢谢，已解决；更新了就好了；

**Comment by a2291249652** [comment]
我这是最新的，但是也出现了这个问题
