### ISSUE TITLE
那个vantweapp的自定义Navbar导航栏，在手机上键盘弹起的时候，顶没了，有解决办法吗

### ISSUE THREAD

**Issue by AngelTl** [youzan/vant-weapp#3500]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater?repo=VantWeapp
那个vantweapp的自定义Navbar导航栏，在手机上键盘弹起的时候，导航栏顶没了，有解决办法吗

**Comment by rex-zsd** [comment]
没办法的，自定义顶部栏算作页面的一部分
