### ISSUE TITLE
[Bug Report] tab横向滚动 底部条宽度 滑动值计算错误

### ISSUE THREAD

**Issue by youdianfan** [youzan/vant-weapp#3504]
### 设备
小米9,微信开发工具 iphone6

### VantWeapp 版本
1.4.3

### 基础库版本
2.3.0

### 如果是 UI 问题，截图链接（多图回车分隔）

![截图](https://i.loli.net/2020/08/10/ho2kUNudiQwPt8e.png)

### 请提供核心代码片段链接
https://gitee.com/inydf/vant-weapp-tabs-bug.git

### 描述问题
![image.png](https://i.loli.net/2020/08/10/ho2kUNudiQwPt8e.png)

官方demo

tabs6: [1, 2, 3, 4, 5, 6, 7, 8, 9]
tab/index.js增加一下tabs个数或者swipe-threshold设置4,即可复现此问题

底部条实际滑动最大值为屏幕宽度
点击标签9底部条实际未滑动到响应位置

**Comment by srcker** [comment]
我也遇到了 
![image](https://user-images.githubusercontent.com/6512197/89781945-e1295f00-db46-11ea-809f-17b42d3942f8.png)

**Comment by youdianfan** [comment]
@srcker  等待修复吧,可以用把底部宽度条先隐藏掉,自己写一个样式,不影响使用,等待修复吧

**Comment by youdianfan** [comment]
@srcker  经过测试1.4.2版本没有此类问题,可以下载1.4.2版本使用
