### ISSUE TITLE
你好，调研个问题

### ISSUE THREAD

**Issue by lichunze** [youzan/vant-weapp#3505]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater?repo=VantWeapp
我是在uni插件市场看见你们的，tips上说
vant-weapp 仅支持小程序/App ,暂不支持H5 。
意思就是说利用uni除了h5，其他小程序及app都支持，是吗

**Comment by rex-zsd** [comment]
额，uniapp 插件市场的跟我们没有关系呢
vant weapp 仅支持微信小程序哈
