### ISSUE TITLE
[Bug Report] Dialog，当message内容足够多时，内容可上下滚动，出现滚动条，但滚动条在滚动结束后不会消失

### ISSUE THREAD

**Issue by anihCevol** [youzan/vant-weapp#3507]
### 设备
已知：模拟器 安卓真机

### VantWeapp 版本
1.4.2

### 基础库版本
2.9.4

### 请提供核心代码片段链接
https://vant-contrib.gitee.io/vant-weapp/#/dialog#api

### 描述问题
Dialog，当message内容足够多时，内容可上下滚动，出现滚动条，但滚动条在滚动结束后不会消失
![20200811162341](https://user-images.githubusercontent.com/42430384/89874876-0a9dc580-dbef-11ea-9c72-fbadcc12d9bf.jpg)

**Comment by anihCevol** [comment]
期望：像页面级滚动条一样，默认不显示滚动条，滚动时出现滚动条，滚动结束滚动条隐藏

**Comment by rex-zsd** [comment]
小程序的默认行为，vant weapp 没有对滚动做处理的哈。

**Comment by anihCevol** [comment]
![20200812192121](https://user-images.githubusercontent.com/42430384/90009786-4ad57480-dcd1-11ea-8195-8018dd082185.jpg)

**Comment by anihCevol** [comment]
感觉 这两个属性和van-dialog__message overflow-y: auto冲突，在页面调试去掉这个两个属性就正常了 但我尝试覆盖这两个地方的overflow属性，并未生效。
