### ISSUE TITLE
添加日历不可以用，不会显示出来

### ISSUE THREAD

**Issue by luyongchun** [youzan/vant-weapp#3508]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater?repo=VantWeapp
将日历组件："van-calendar": "@vant/weapp/calendar/index"添加完成，有时候能显示日历，有时候显示出来的日历也没有确认按钮，我想隐藏掉确认按钮供其使用的时候也是一样，点了日历没反应，不知道为什么，。还有几个组件，就是下拉菜单那个，按照方法步骤使用了是没有效果的。一点都没有，连title都没有出现，给view指定宽高都没有用。还用到了日期选择器的，但是不适用，我并不会用，用起来还是拉伸了布局那些，我不知道该怎么用好这个组件

**Comment by rex-zsd** [comment]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater?repo=VantWeapp
