### ISSUE TITLE
给tabs设置宽度并居中后 line位置错误

### ISSUE THREAD

**Issue by Thckl** [youzan/vant-weapp#3509]
如题![image](https://user-images.githubusercontent.com/35649828/89875884-6583ec80-dbf0-11ea-81c1-ce16b2bbf178.png)

**Comment by srcker** [comment]
用1.4.2

**Comment by Thckl** [comment]
> 用1.4.2

可以 谢谢  原来是新版的的问题

**Comment by rex-zsd** [comment]
#3504
重复 issue 先关闭了
