### ISSUE TITLE
官方文档好像没有给出swipe 的使用方法

### ISSUE THREAD

**Issue by zqzy** [youzan/vant-weapp#3510]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

官方文档好像没有给出swipe 的使用方法

**Comment by rex-zsd** [comment]
vant weapp 没有 swipe 组件的哈

**Comment by yangjingchuang** [comment]
> vant weapp 没有 swipe 组件的哈

演示中是有的啊

**Comment by DerrickTel** [comment]
@rex-zsd 演示中有，文档没有
