### ISSUE TITLE
NavBar无法修改arrow颜色和大小

### ISSUE THREAD

**Issue by qwerlp** [youzan/vant-weapp#3514]
![image](https://user-images.githubusercontent.com/42144393/90088373-5d8f8e00-dd51-11ea-9b3f-40d20f7380f4.png)
颜色只能这样修改，大小不知道怎么修改

**Comment by rex-zsd** [comment]
大小也是有 css 变量的 `--nav-bar-arrow-size`，不过目前存在 bug 未生效，将在下版本修复。
