### ISSUE TITLE
[Bug Report] 微信真机调试 白屏 其他正常预览

### ISSUE THREAD

**Issue by xlanghejianfeng** [youzan/vant-weapp#3520]
### 设备
IOS

### VantWeapp 版本
1.4.4

### 基础库版本
2.8.3

### 请提供核心代码片段链接
https://gitee.com/shanghai_luojin/pms-boss-wxapp/blob/master/miniprogram/app.json

### 描述问题
你好，我在小程序(ts)里引入了van npm方式，在微信开发者工具中 模拟 预览 上传体验版都没问题，但是真机调试出现白屏，如果用微信自己组件没问题，请明示下 具体原因 是相关组件没上传至微信 找不到目录还是？？

**Comment by rex-zsd** [comment]
gitee 访问 404了，看不到代码，是私有仓库？

**Comment by xlanghejianfeng** [comment]
嗯 你好，我写了demo感觉不是vant的问题&nbsp; 是微信开发者环境的问题，预览 上传 模拟器 都是好的 就是真机调试 界面啥都没&nbsp;
用vConsole打出来
Framework inner error (expect FLOW_APPLY_PROPERTY but get another)


TypeError undefined is not an object(evaluating 'window.__DOMTree__.addListener)


困扰了好多天了 能帮忙看看么 感谢&nbsp; 这个错误也不知道具体啥位置的undefined


小程序是typescript的&nbsp;&nbsp;
ios调试


IOS13.6
微信版本 7.0.15
基础库 2.12.1




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "youzan/vant-weapp"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月19日(星期三) 下午2:34
收件人:&nbsp;"youzan/vant-weapp"<vant-weapp@noreply.github.com&gt;;
抄送:&nbsp;"何建峰"<717560379@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [youzan/vant-weapp] [Bug Report] 微信真机调试 白屏 其他正常预览 (#3520)





 
gitee 访问 404了，看不到代码，是私有仓库？

**Comment by rex-zsd** [comment]
额，好的哈

这个可以看下错误栈，看是其他第三方库报的还是小程序内部报出来的
看是否有哪个库调用了 `window.__DOMTree__.addListener` 这个方法

**Comment by xlanghejianfeng** [comment]
全局搜了下 没地方看到有个方法引用， 关键小程序 线上提交也审核过了 也没问题&nbsp; 就是开发工具里《真机调试》很奇怪&nbsp;
expect FLOW_APPLY_PROPERTY but get another
get&nbsp;anotherExpect FLOW_CREATE_NODE but&nbsp;get&nbsp;another


这样就是调试起来不方便&nbsp; 多机型的话 不能立马定位问题，


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "youzan/vant-weapp"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月19日(星期三) 下午4:21
收件人:&nbsp;"youzan/vant-weapp"<vant-weapp@noreply.github.com&gt;;
抄送:&nbsp;"何建峰"<717560379@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [youzan/vant-weapp] [Bug Report] 微信真机调试 白屏 其他正常预览 (#3520)





 
额，好的哈
 
这个可以看下错误栈，看是其他第三方库报的还是小程序内部报出来的
 看是否有哪个库调用了 window.__DOMTree__.addListener 这个方法
