### ISSUE TITLE
NavBar导航栏组件，当底部输入框点击弹起键盘时，导航栏会被顶出屏幕

### ISSUE THREAD

**Issue by wangweifan** [youzan/vant-weapp#3521]
Describe the bug
NavBar导航栏组件，当底部输入框点击弹起键盘时，导航栏会被顶出屏幕

Screenshots
![微信图片_20200812104603](https://user-images.githubusercontent.com/22409524/90219997-e71a8b00-de39-11ea-86db-1579bae8f64f.jpg)

![微信图片_20200812104609](https://user-images.githubusercontent.com/22409524/90220019-f0a3f300-de39-11ea-9924-7c8cbb6649e2.jpg)

Environment

Device: 苹果8plus
Browser: 小程序
Vant Version: 1.3.0
Reproduce
无

**Comment by rex-zsd** [comment]
导航栏属于页面的一部分，被顶出屏幕是正常的现象。

**Comment by wangweifan** [comment]
> 导航栏属于页面的一部分，被顶出屏幕是正常的现象。

有没有办法让他补顶出去屏幕？就想原生的导航栏一样

**Comment by rex-zsd** [comment]
没有办法的
