### ISSUE TITLE
[Bug Report] van-tag在wepy中使用高度问题

### ISSUE THREAD

**Issue by wang-Jiawei** [youzan/vant-weapp#3524]
### 设备
微信开发者工具

### VantWeapp 版本
1.4.4

### 基础库版本
2.12.0

### 如果是 UI 问题，截图链接（多图回车分隔）

!(https://sm.ms/image/BuIeFSKNV6Qang8)  https://sm.ms/image/AKQP3xFEdJnmfsp

### 请提供核心代码片段链接
http://www.baiewqeqw.com

### 描述问题
<van-tag type="danger">
          测试
        </van-tag>
https://sm.ms/image/BuIeFSKNV6Qang8  图片链接 
flex 布局， 因为高度问题不对齐

**Comment by rex-zsd** [comment]
看起来不是 vant weapp 组件内部的问题？外部使用 flex 布局导致元素水平不齐的问题，可以自行处理一下哈。
