### ISSUE TITLE
您好，为什么@import '@vant/weapp/common/index.wxss';报错啊。

### ISSUE THREAD

**Issue by happyqian** [youzan/vant-weapp#3525]
如题

**Comment by rex-zsd** [comment]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater?repo=VantWeapp

一句话的反馈信息量不足，没办法帮助你咯。
