### ISSUE TITLE
组件，想要自定义样式，不生效？

### ISSUE THREAD

**Issue by candyAndBella** [youzan/vant-weapp#3526]
以Stepper 步进器 为例，想要加号和减号，背景色是黄色。

1.在组件上，直接用style不生效。
<van-stepper :value="number" style="background:#FADB14" />

2.文档上，组件最下面，有外部样式类，不知道怎么使用，我写在组件上，也不生效。
<van-stepper :value="{{ 1 }}" plusClass=“myclass” />
.myclass{background:#FADB14}

![微信截图_20200816132538](https://user-images.githubusercontent.com/34698384/90327349-7b652900-dfc5-11ea-862f-b46db79bd61e.png)
![微信截图_20200816132640](https://user-images.githubusercontent.com/34698384/90327351-7bfdbf80-dfc5-11ea-9382-2a558d623dd7.png)
![微信截图_20200816133648](https://user-images.githubusercontent.com/34698384/90327363-92a41680-dfc5-11ea-8668-5501a7af986a.png)

**Comment by rex-zsd** [comment]
https://youzan.github.io/vant-weapp/#/custom-style
文档上有详细的样式覆盖的说明了哈。

**Comment by candyAndBella** [comment]
按照官网的这两种方法，试过了，不生效
1.直接在页面的样式文件中覆盖样式
<van-button type="primary">主要按钮</van-button>
/* page.wxss */
.van-button--primary {
  font-size: 20px;
  background-color: pink;
}

2.使用外部样式类：
<van-cell
  title="单元格"
  value="内容"
  title-class="cell-title"
  value-class="cell-value"
/>
.cell-title {
  color: pink !important;
  font-size: 20px !important;
}

.cell-value {
  color: green !important;
  font-size: 12px !important;
}

**Comment by candyAndBella** [comment]
给有赞提过好多次issue，我发现有赞关issue的速度真是NO.1。不管我这边解决不解决，都是回复一句就直接关了

**Comment by JakeLaoyu** [comment]
https://developers.weixin.qq.com/miniprogram/dev/framework/custom-component/wxml-wxss.html#%E5%A4%96%E9%83%A8%E6%A0%B7%E5%BC%8F%E7%B1%BB

![image](https://user-images.githubusercontent.com/16181940/90587838-e7859e00-e20c-11ea-8d76-715a16b97a2a.png)


看一下微信样式覆盖的文档，需要在组件上传入

**Comment by rex-zsd** [comment]
@candyAndBella issue不是一个聊天的地方哈，尤其是使用姿势的问题。
很多issue来回回复几天，情况说不清楚，可运行的代码片段也提供不出来，是非常浪费时间的。这个就是微信交流群存在的意义。

回到这个 case，文档里提供了三种样式覆盖方法，每一种都有链接官方文档、code示例。你反应还是用不起来，又不提供代码，那希望我们能提供什么样的协助呢？

**Comment by rex-zsd** [comment]
其实新建 issue 这里已经很明白的贴了
>>> 你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。
>>> https://youzan.github.io/vant-issue-generater?repo=VantWeapp

**Comment by candyAndBella** [comment]
我的按钮是黄底黑字，圆角。
![微信截图_20200819113147](https://user-images.githubusercontent.com/34698384/90589206-279a5000-e210-11ea-930e-ce77c89c1c55.png)
![微信截图_20200819113304](https://user-images.githubusercontent.com/34698384/90589210-29641380-e210-11ea-9498-5468ac616931.png)
![微信截图_20200819113508](https://user-images.githubusercontent.com/34698384/90589215-2b2dd700-e210-11ea-9ee1-34c7d7713991.png)

**Comment by candyAndBella** [comment]
stepper样式，我是去vant文件夹，改了index.less的源码实现的。因为plus-class控制不生效
![微信截图_20200819113805](https://user-images.githubusercontent.com/34698384/90589576-fec68a80-e210-11ea-938d-029cfbb3dfe6.png)
![微信截图_20200819114138](https://user-images.githubusercontent.com/34698384/90589650-2158a380-e211-11ea-87ac-1e5cfb320428.png)

**Comment by candyAndBella** [comment]
感谢，我去试一下

**Comment by candyAndBella** [comment]
> https://developers.weixin.qq.com/miniprogram/dev/framework/custom-component/wxml-wxss.html#%E5%A4%96%E9%83%A8%E6%A0%B7%E5%BC%8F%E7%B1%BB
> 
> ![image](https://user-images.githubusercontent.com/16181940/90587838-e7859e00-e20c-11ea-8d76-715a16b97a2a.png)
> 
> 看一下微信样式覆盖的文档，需要在组件上传入

感谢，我去试一下

**Comment by rex-zsd** [comment]
> stepper样式，我是去vant文件夹，改了index.less的源码实现的。因为plus-class控制不生效
> ![微信截图_20200819113805](https://user-images.githubusercontent.com/34698384/90589576-fec68a80-e210-11ea-938d-029cfbb3dfe6.png)
> ![微信截图_20200819114138](https://user-images.githubusercontent.com/34698384/90589650-2158a380-e211-11ea-87ac-1e5cfb320428.png)

既然用了 mpvue，那么开始就要反馈出来。
样式这里写了 `scoped`，覆盖是肯定不会生效了。

**Comment by candyAndBella** [comment]
> > stepper样式，我是去vant文件夹，改了index.less的源码实现的。因为plus-class控制不生效
> > ![微信截图_20200819113805](https://user-images.githubusercontent.com/34698384/90589576-fec68a80-e210-11ea-938d-029cfbb3dfe6.png)
> > ![微信截图_20200819114138](https://user-images.githubusercontent.com/34698384/90589650-2158a380-e211-11ea-87ac-1e5cfb320428.png)
> 
> 既然用了 mpvue，那么开始就要反馈出来。
> 样式这里写了 `scoped`，覆盖是肯定不会生效了。

好的，我去试一下

**Comment by candyAndBella** [comment]
> > stepper样式，我是去vant文件夹，改了index.less的源码实现的。因为plus-class控制不生效
> > ![微信截图_20200819113805](https://user-images.githubusercontent.com/34698384/90589576-fec68a80-e210-11ea-938d-029cfbb3dfe6.png)
> > ![微信截图_20200819114138](https://user-images.githubusercontent.com/34698384/90589650-2158a380-e211-11ea-87ac-1e5cfb320428.png)
> 
> 既然用了 mpvue，那么开始就要反馈出来。
> 样式这里写了 `scoped`，覆盖是肯定不会生效了。

好的，我去试一下，感谢
