### ISSUE TITLE
van-collapse 折叠面板 右侧内容是否可以添加点击事件???

### ISSUE THREAD

**Issue by lhbfilwmyseve** [youzan/vant-weapp#3527]
van-collapse 折叠面板 右侧内容是否可以添加点击事件?/??

![image](https://user-images.githubusercontent.com/18702699/90330096-d8b8a480-dfdc-11ea-8f1d-63de8a9b78f9.png)

**Comment by rex-zsd** [comment]
监听 `van-collapse` 上的 `change` 事件就可以啦，会将选中项的 `name` 或 `index` 抛出来的

**Comment by doublebin** [comment]
请问解决了吗。如果我右边内容加一个switch事件，监听不到啊。
