### ISSUE TITLE
van-circle 在指定type为2d时，在真机运行时报错

### ISSUE THREAD

**Issue by lwy121810** [youzan/vant-weapp#3530]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater?repo=VantWeapp

van-circle 在指定type为2d时，在真机运行时报错：

wxml文件：
```
<view class="content">
	<view class="circle-container">
		<van-circle type='2d' value="80">
		</van-circle>
	</view>
</view>
```

<img width="812" alt="截屏2020-08-17 下午3 43 30" src="https://user-images.githubusercontent.com/16394109/90370701-690bed80-e0a0-11ea-848c-1e89440b1732.png">

**Comment by rex-zsd** [comment]
测试未复现，demo 小程序中 ”基础用法“ 的 circle 就是 `2d` 的，可以看下是否有问题。
这个报错截图看起来是微信内部而不是 vant weapp 的，可以看下是否是基础库版本过低造成的。
