### ISSUE TITLE
van-submit-bar如何触发form的submit事件呢

### ISSUE THREAD

**Issue by dzlishen** [youzan/vant-weapp#3534]
如何触发form的submit事件呢
<form bindsubmit="formSubmit" bindreset="formReset">
<van-cell-group>
<van-submit-bar
	label = "费用合计："
	price="{{ price }}"
	button-text="提交预约"
        bind:submit="onSubmit"
>
</van-submit-bar>
</van-cell-group>
</form>

**Comment by rex-zsd** [comment]
目前是不支持的，后续可以安排增加 `form-type` 属性支持下这个

**Comment by rex-zsd** [comment]
https://developers.weixin.qq.com/miniprogram/dev/component/form.html#wx-form-field-button
很遗憾，按照微信现在的设计，嵌套2层组件之后，`form-type`属性是不会生效的。
所以这个特性目前暂时没有办法支持了。
