### ISSUE TITLE
van-submit-bar 

### ISSUE THREAD

**Issue by NineSu** [youzan/vant-weapp#3535]
van-submit-bar 当价格为0时，
![image](https://user-images.githubusercontent.com/27474230/90497623-dd668f80-e179-11ea-83c0-82cb71083e3a.png)
priceStrArr[1]是不存在的。不导致出现undefined。
我已加上默认值~

**Comment by rex-zsd** [comment]
https://github.com/youzan/vant-weapp/blob/dev/packages/submit-bar/index.ts

前面是有 `toFixed` 的，即使传入的值是 `0`，`priceStrArr[1]` 也会是 `00`，而不是 `undefiend`

**Comment by NineSu** [comment]
> https://github.com/youzan/vant-weapp/blob/4a479f623490e9011c43e3849843d7875c41aa03/packages/submit-bar/index.ts#L46-L51
> 
> 前面是有 `toFixed` 的，即使传入的值是 `0`，`priceStrArr[1]` 也会是 `00`，而不是 `undefiend`

![image](https://user-images.githubusercontent.com/27474230/90748046-424df100-e304-11ea-998c-75277695627c.png)
可是就是会为undefined呢。一个是小程序开发者工具，一个是chrome。。目前只是在开发者工具发现这个问题。我也没有看真机会不会有这个问题。不过加上总会保险一丢丢吧
