### ISSUE TITLE
不想开源就不要浪费别人的时间

### ISSUE THREAD

**Issue by boringwork** [youzan/vant-weapp#3537]
连个vant-demo都跑不起来，一大堆路径错误，修正路径了，也就button，image能用，放个 checkbox 点上都没反应，datetimepicker 压根就不显示，赶紧闭源吧，别浪费别人时间了

**Comment by chenjiahan** [comment]
不爱用可以不用。

**Comment by JakeLaoyu** [comment]
处理你这条issue 都是浪费时间。**先学会怎么提问题**
