### ISSUE TITLE
steps组件，能否加个属性，能够从下往上高亮？

### ISSUE THREAD

**Issue by candyAndBella** [youzan/vant-weapp#3538]
steps 垂直方向，默认的时候，高亮是从上往下的。期望高亮的样式是从下往上的。
如图，希望是步骤1和步骤2高亮，步骤3和步骤4是灰色的
![image](https://user-images.githubusercontent.com/34698384/90594606-671b6900-e21d-11ea-9b56-70b226e11528.png)

**Comment by rex-zsd** [comment]
从下往上的样式目前应该是不会支持了，可以下载源码修改或者自行实现组件哈。

**Comment by candyAndBella** [comment]
> 从下往上的样式目前应该是不会支持了，可以下载源码修改或者自行实现组件哈。

我现在是自己写的，如果你们出了组件，我就不用每次都自己写了。我有两个项目都用到这个效果了。应该很常规的功能吧。
希望你跟技术人员反馈一下
