### ISSUE TITLE
 你好请教一下 array.wxs文件中  array.constructor === 'Array'   这里的'Array' 是不是应该为 Array

### ISSUE THREAD

**Issue by jjsnc** [youzan/vant-weapp#3540]
return array && array.constructor === 'Array';  这里右侧的'Array' 是不是应该为Array

**Comment by rex-zsd** [comment]
并不是，可以看下[官方文档](https://developers.weixin.qq.com/miniprogram/dev/reference/wxs/06datatype.html#array)
