### ISSUE TITLE
van-dropdown 外部设置padding,margin,height 会导致下拉显示错误

### ISSUE THREAD

**Issue by Thckl** [youzan/vant-weapp#3542]
![微信图片_20200820151129](https://user-images.githubusercontent.com/35649828/90728651-d6fe2200-e2f7-11ea-9c09-3fb8a1b27ad1.png)
![微信图片_20200820151140](https://user-images.githubusercontent.com/35649828/90728655-d9607c00-e2f7-11ea-9d95-d43bd6788b89.png)

**Comment by Thckl** [comment]
中间的高度 相当于padding的高度

**Comment by rex-zsd** [comment]
可以提供下代码片段？截图没看懂什么意思

**Comment by Thckl** [comment]
> 可以提供下代码片段？截图没看懂什么意思

已经解决了 我重写了getChildWrapperStyle方法 在计算的时候加入距离顶部的高度
![0cc8edcea855928fbab4de9e260d8a1](https://user-images.githubusercontent.com/35649828/91704649-7780fb80-ebae-11ea-8fec-9a5f0002fc84.png)

**Comment by rex-zsd** [comment]
ok 的
