### ISSUE TITLE
pciker组件在触发change事件时，一列数据和两列返回的value不一致

### ISSUE THREAD

**Issue by biubiubiuyyl** [youzan/vant-weapp#3544]
pciker组件在触发change事件时，一列数据和两列返回的value不一致？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？

**Comment by rex-zsd** [comment]
是的
