### ISSUE TITLE
[Feature Request] van-tabs 建议用swiper

### ISSUE THREAD

**Issue by holai** [youzan/vant-weapp#3545]
### 这个功能解决了什么问题
van-tabs 进行却换的时候太多死板，一滑就切换 开启动画也是

### 建议的API是什么样的
希望能使用swiper  进行切换  可以有更好的体验

### 展示一下新功能的大致用法，代码片段链接（GitHub Gist）
https://gitee.com/houlaidelu/codes/e5bwj7afct8psqirkgy4629

**Comment by rex-zsd** [comment]
原生 swiper 效果的确挺好，但是很可惜，swiper 目前还不支持嵌套自定义组件，再在自定义组件内使用 swiper-item 的用法。
所以 vant weapp 这边无法用 swiper 实现 tab 了。
