### ISSUE TITLE
[Feature Request] 一些业务组件是不是不可以用

### ISSUE THREAD

**Issue by xt981224** [youzan/vant-weapp#3547]
### 这个功能解决了什么问题
请问vant中的业务组件Sku这些是不是在小程序中不支持

### 建议的API是什么样的
请问vant中的业务组件Sku这些是不是在小程序中不支持

**Comment by johnqiuwan** [comment]
+1

**Comment by rex-zsd** [comment]
vant weapp 没有计划提供业务组件的哈
