### ISSUE TITLE
求助 Calendar 组件的起始日Props参数是什么？文档中没有找到

### ISSUE THREAD

**Issue by muuubooo** [youzan/vant-weapp#3552]
Calendar 组件的起始日对应的Props是什么？文档中没有找到

**Comment by zcjunblog** [comment]
min-date | 可选择的最小日期 

max-date | 可选择的最大日期


default-date | 默认选中的日期，type为multiple或range时为数组

**Comment by muuubooo** [comment]
> min-date | 可选择的最小日期
> 
> max-date | 可选择的最大日期
> 
> default-date | 默认选中的日期，type为multiple或range时为数组

可能是我没表达清楚
我想问的应该叫做周起止日期
就是每周 是周一开始 还是周日开始
默认是头部和排序是
日 一 二 三 四 五 六

我希望的是
一 二 三 四 五 六 日

**Comment by rex-zsd** [comment]
目前还没有这个参数，后续可以支持

**Comment by muuubooo** [comment]
> 目前还没有这个参数，后续可以支持

那目前文档里这个 “自定义周起始日”的demo 是完全需要自己去想办法改么
https://imgur.com/Pnb3IUK
https://imgur.com/AQaN78T

**Comment by usernameddd** [comment]
对呀，官方文档中有设置周起始日的演示例子，但是没有相关代码，就只是给我们看看？
能不能将演示例子的实现代码也考虑放在github上，感谢大佬！
@rex-zsd 
https://vant-contrib.gitee.io/vant-weapp/#/calendar

**Comment by muuubooo** [comment]
> 对呀，官方文档中有设置周起始日的演示例子，但是没有相关代码，就只是给我们看看？
> 能不能将演示例子的实现代码也考虑放在github上，感谢大佬！
> @rex-zsd
> https://vant-contrib.gitee.io/vant-weapp/#/calendar

之前是web版有，移动版vant没有。
现在1.64应该是已经加上了吧

**Comment by usernameddd** [comment]
> > 对呀，官方文档中有设置周起始日的演示例子，但是没有相关代码，就只是给我们看看？
> > 能不能将演示例子的实现代码也考虑放在github上，感谢大佬！
> > @rex-zsd
> > https://vant-contrib.gitee.io/vant-weapp/#/calendar
> 
> 之前是web版有，移动版vant没有。
> 现在1.64应该是已经加上了吧

现在就是最新版1.6.4，官方使用文档中没有这个例子的代码，且经过查阅该项目给出的example下的page/calendar下的wxml文件中也是没有那一个设置周起始日的例子的，好像就是凭空出来的，找不到来处。也看了日历组件的prop，没有一个明确是指明用来配置周起始日的参数。

**Comment by zhuyuesen** [comment]
借楼问一下，这个功能啥时候能支持，现在 1.6.8 版本还没有

**Comment by chenjiahan** [comment]
已在 1.6.9-beta.0 版本支持
