### ISSUE TITLE
van-dropdown-menu closed方法没回调 但是close方法有回调

### ISSUE THREAD

**Issue by Evans-Cai** [youzan/vant-weapp#3553]
van-dropdown-menu closed方法没回调 但是close方法有回调 change方法有效

**Comment by Evans-Cai** [comment]
我给 这个方法加了重新设置 wrapperStyle 以消除默认注入的 z-index、top、bottom，style
onC，lose() {
      this.$emit('close');
      setTimeout(_ => {
        this.setData({ wrapperStyle: '', showWrapper: false });
      }, this.parent.data.duration + 50)
},

**Comment by rex-zsd** [comment]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater?repo=VantWeapp
