### ISSUE TITLE
Picker组件会有如下的warning

### ISSUE THREAD

**Issue by rdsuncn** [youzan/vant-weapp#3556]
./miniprogram_npm/vant-weapp/picker/index.wxml
 wx:key="{{ index }}" does not look like a valid key name (did you mean wx:key="index" ?)
  32 |     catch:touchmove="noop"
  33 |   >
> 34 |     <picker-column
     |      ^
  35 |       class="van-picker__column"
  36 |       wx:for="{{ isSimple(columns) ? [columns] : columns }}"
  37 |       wx:key="{{ index }}"

**Comment by rex-zsd** [comment]
这里不太符合小程序的新模板语法，下个版本将会修改。

**Comment by rex-zsd** [comment]
https://github.com/youzan/vant-weapp/blob/25705fdee54909896a0ca103f4abc8782e08d418/packages/picker/index.wxml#L16

看了下，9个月以前这个写法已经被调整了，是用的很老的版本？可以更新到最新版本看下哈。
