### ISSUE TITLE
[Bug Report] Toast Error:  incongruent status: leave

### ISSUE THREAD

**Issue by akaQZM** [youzan/vant-weapp#3557]
### 设备
微信开发者工具

### VantWeapp 版本
1.4.4

### 基础库版本
2.12.1

### 请提供核心代码片段链接
https://developers.weixin.qq.com/s/nO6PUTmb7kjB

### 描述问题
Toast组件先初始化，然后clear()，之后再实例化一次，控制台报错。
Error: incongruent status: leave

**Comment by rex-zsd** [comment]
是这样的，toast 的 `clear` 是异步过程，调用之后，会在动画完成后才真正消失。
这里 `clear` 与 `Toast` 一起调用，展示逻辑会比消失逻辑先执行。
内部判断这里不应该销毁 toast 实例，会抛出你看到的这个错误。
![image](https://user-images.githubusercontent.com/8767877/91274570-78322000-e7b1-11ea-9fb0-2e21342e5514.png)

在这个场景，报错可以忽略的哈。
