### ISSUE TITLE
steps组件，怎么显示图片

### ISSUE THREAD

**Issue by chenguzhen87** [youzan/vant-weapp#3558]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater?repo=VantWeapp

**Comment by chenguzhen87** [comment]
貌似不支持图片显示

**Comment by rex-zsd** [comment]
`activeIcon` 和 `inactiveIcon` 直接传图片链接就可以了。
