### ISSUE TITLE
anction-sheet 在actions过多的时候真机上显示部分空白

### ISSUE THREAD

**Issue by izumiiAoba** [youzan/vant-weapp#3560]
![image](https://user-images.githubusercontent.com/39220621/91276671-6dc55580-e7b4-11ea-8f6a-316bd3c3231f.png)

**Comment by rex-zsd** [comment]
example 并不会被截断，是因为自己加了样式导致的？
代码片段提供下看下

**Comment by shenjianzch** [comment]
我也遇到同样的问题 不是所有的iphone 机子都这样 我在iphone7 plus上是这样的 超过可视范围内的选项都看不见了 点一下就都出现了

**Comment by shenjianzch** [comment]
@rex-zsd 你可以试试看

**Comment by izumiiAoba** [comment]
- 只是普通的使用组件，没有在页面中对action-sheet加入样式
- 在上线的版本里，只要是超过可视范围的都是这样（iPhoneXR和iPhoneX），但是在开发者工具以及真机调试的时候都不会
```js
<van-action-sheet
  show="{{ templateNameSelectShow }}"
  actions="{{ templateNameSelectActions }}"
  bind:close="onSelectClose"
  bind:select="onTemplateNameSelect"
  data-select-show-name="templateNameSelect"
/>
```
```js
// templateNameSelectActions是对象数组
{
    id: 1,
    name: "xxx",
}
```

**Comment by izumiiAoba** [comment]
使用`van-popup`和`van-picker`替换，可以在iPhone的测试中正常显示。
