### ISSUE TITLE
文档描述错误 - FieId 输入框组件

### ISSUE THREAD

**Issue by Niangao-Warren** [youzan/vant-weapp#3561]
FieId 输入框组件 - Events 说明
`event.detail.value` 当前输入值; ——> `event.detail.detail.value` 当前输入值;
![描述的回调参数](https://user-images.githubusercontent.com/15097607/91279152-bfbbaa80-e7b7-11ea-93e4-a8843fd833de.png)
![实际的回调参数](https://user-images.githubusercontent.com/15097607/91279774-820b5180-e7b8-11ea-90fc-5482599bccd7.png)

**Comment by rex-zsd** [comment]
可以本地跑下 example 里的 demo小程序，是符合文档的。
看下是不是自己做了什么处理或者使用了什么框架包装了事件模型导致的？
