### ISSUE TITLE
相比较 vant vue ，vant-weapp 的业务组件太弱了少了不止2-3 个组件

### ISSUE THREAD

**Issue by johnqiuwan** [youzan/vant-weapp#3567]
相比较 vant vue ，vant-weapp 的业务组件太弱了少了不止2-3 个组件。

看到有很多人都在提及需要加 swiper， 加 sku，官方回复也是自相矛盾。
当有人提及需要添加swiper时，回复swiper在小程序中已经有了此类组件不会考虑（好像现在表示为new component 标签了）
当有人提及添加sku，回复是没有考虑添加

那么问题是添加哪个组件与否取决的标准是什么，前提是为什么 vant vue 和  vant weapp 会区别对待？实在不理解，相信很多人也有和我类似的问题，请官方回复一下，也好让我们知道后续是否会添加诸如 contact，coupon，sku 等等这些即在小程序组件中没有，而且vant vue 已经支持但是 vant weapp 没有的，希望能给出一个 timeline

**Comment by rex-zsd** [comment]
基本的原则是这样的
1. 业务组件不会添加，后续 vant 也会将 sku 移出仓库放到独立的包
2. 微信小程序已有的组件不会添加，避免重复造轮子

**Comment by johnqiuwan** [comment]
业务组件在 vue 比小程序更加的完善，那小程序已有组件不开发能理解，那业务组件为什么区别对待呢？期待回复

**Comment by chenjiahan** [comment]
Vant 维护者的精力是有限的，这些有限的精力需要分配给 issue 处理、功能迭代、bug 修复、新增组件等方面。我们会把有限的精力分配到优先级更高的事情上。而 Vant 里的业务组件是特定时期的产物，并不是我们现在发展的重心。

举个例子，VantWeapp 里没有 Sku 组件和日历组件时，我们会优先考虑开发日历组件，因为日历组件是基础组件，更具通用性，能满足更多场景的需求，而 Sku 组件只在特定场景下适用。

总的来说，不做 Sku （或其他业务组件）是权衡的结果，我们要把精力花在更主流的场景上。

**Comment by johnqiuwan** [comment]
感谢你的回复。

一方面您的回复没有解答到我的问题，我的问题是相比较  vue vant 为什么差异对待？按照您的逻辑精力有限，挑普适性高的作为更高的优先级，那在你们内部的权重 vue的普适性高于小程序，所以vue 配有更多好的业务组件？

另一方面您提到的是时期特定产物，那如果你们当时开发就是给vue 用的，那就可以理解。
但是用户这边在issue看到有很多类似的组件需求

**Comment by chenjiahan** [comment]
并不是差异对待，Vant 里的业务组件是 17 年提供的，VantWeapp 是 18 年才开始做的。

另外有需求不等于一定要满足，比如产品向你提了 100 个需求，你肯定不会全部都做。
