### ISSUE TITLE
添加SwipeCell 滑动单元格组件时候页面不显示任何内容。

### ISSUE THREAD

**Issue by hssis** [youzan/vant-weapp#3570]
![image](https://user-images.githubusercontent.com/54617433/91539489-fd513c80-e94b-11ea-8e47-5bb7061bcba0.png)
![image](https://user-images.githubusercontent.com/54617433/91539547-1528c080-e94c-11ea-9791-8dc7a6ae85ae.png)

**Comment by rex-zsd** [comment]
用的是什么版本呢？还有可复现的代码片段也上传下提供一下哈。
demo小程序中是没有问题的，推测还是版本或者姿势问题

**Comment by iblackly** [comment]
> 用的是什么版本呢？还有可复现的代码片段也上传下提供一下哈。
> demo小程序中是没有问题的，推测还是版本或者姿势问题

目前 1.5.0 确实啥也不现实!!!

**Comment by LesliesCheung** [comment]
当前版本确实什么也看不到
