### ISSUE TITLE
也许不算bug，组件嵌套组件，被嵌套的组件中的vant组件的custom-class样式必须加important才能覆盖

### ISSUE THREAD

**Issue by tigertany** [youzan/vant-weapp#3571]
如果是page直接用component，custom-class不加important也可以覆盖原样式，
page->component->van-button

如果中间再套一层component，custom-class不加important就覆盖不了了。
page->component->component->van-button

**Comment by rex-zsd** [comment]
推荐是都加上 `!important`，官方文档有说明外部样式类的优先级是不确定的。
