### ISSUE TITLE
Switch搭配单元格使用这个例子没代码啊

### ISSUE THREAD

**Issue by taotao6** [youzan/vant-weapp#3572]
Switch开关这个组件里，就这个没代码示例

**Comment by taotao6** [comment]
问题解决了，用插槽

**Comment by qqli007** [comment]
@taotao6 能否贴下代码看下，谢谢了

**Comment by Windancer** [comment]
> @taotao6 能否贴下代码看下，谢谢了

<van-cell wx:if="{{storeDetail != null}}" center title="{{storeDetail.name}}" label="{{storeDetail.contact.address}}">
    <van-switch slot="right-icon" checked="{{ checked }}" active-color="#07c160" inactive-color="#ee0a24"
    active-value="take_out" inactive-value="self"  bind:change="onChange"/>
  </van-cell>

**Comment by Windancer** [comment]
> @taotao6 能否贴下代码看下，谢谢了

`<van-cell wx:if="{{storeDetail != null}}" center title="{{storeDetail.name}}" label="{{storeDetail.contact.address}}">
    <van-switch slot="right-icon" checked="{{ checked }}" active-color="#07c160" inactive-color="#ee0a24"
    active-value="take_out" inactive-value="self"  bind:change="onChange"/>
  </van-cell>`
