### ISSUE TITLE
tab组件使用 nav-class设置背景，tab item数量多的时候滑动背景色消失

### ISSUE THREAD

**Issue by mayingyun** [youzan/vant-weapp#3576]
tab组件使用 nav-class设置背景，tab item数量多的时候滑动背景色消失，具体代码和效果如下：
![1598836004199](https://user-images.githubusercontent.com/6906903/91674031-9a3cf100-eb69-11ea-8d99-138ff5ca20e8.jpg)
![1598836008067](https://user-images.githubusercontent.com/6906903/91674037-a163ff00-eb69-11ea-8fe9-999b6bb9a159.jpg)
滑动超过屏幕宽的时候背景是就没了。

**Comment by rex-zsd** [comment]
可以在 `tab-class` 上添加背景色，或者用 `--tabs-nav-background-color` 变量来控制。
