### ISSUE TITLE
优化：日历组件，当前日期被确认按钮遮挡

### ISSUE THREAD

**Issue by xin907074783** [youzan/vant-weapp#3578]
建议优化：日历组件
存在问题：当前日期如31号会被确认按钮遮挡
![image](https://user-images.githubusercontent.com/39476578/91707061-dbf18a00-ebb1-11ea-81cc-5d9fc6cb61e0.png)

**Comment by landluck** [comment]
该问题最新版本没复现，如能复现可以提供小程序代码片段后重新打开 issue
