### ISSUE TITLE
van-tabs  设置ellipsis为false 时  会导致 底部条定位出错

### ISSUE THREAD

**Issue by Thckl** [youzan/vant-weapp#3579]
van-tabs  设置ellipsis为false 时  会导致 底部条定位出错
![9b6c57ebad7f1eb0883b4a7293e9523](https://user-images.githubusercontent.com/35649828/91707356-41457b00-ebb2-11ea-9cc0-fd7c0526718e.png)
![badb371e54ac3fef20e3c90efc1cd42](https://user-images.githubusercontent.com/35649828/91707362-4276a800-ebb2-11ea-8f84-3a1d20dc114a.png)

**Comment by mw248** [comment]
tab是4个字时，底部条居左显示，而不是居中，指定line-width值后，底部条样式就会错乱

**Comment by liswn** [comment]
.van-tabs__wrap--scrollable .van-tabs__nav--complete
{
  padding: 0 !important;
}

**Comment by dulltackle** [comment]
> tab是4个字时，底部条居左显示，而不是居中，指定line-width值后，底部条样式就会错乱

朋友, 我猜测你指定 `line-width` 是类似这样 `line-width="40rpx"`, 这样指定的结果就像你说的一样, 底部条居左显示, 如下图

![Q1.png](https://i.loli.net/2020/11/22/E3VKCvie6yamJSZ.png)

这样指定实际上是有一定的问题的, 因为在文档中关于 `line-width` 的信息如下

line-width | 底部条宽度 (px) | string \| number | 40px | -
-- | -- | -- | -- | --

而且在 `tabs` 组件源码中, 底部条的位置是在 `JS` 文件中用 `'transform: translateX(' + left +'px)'` 实现, 而此处的 `left` 是基于 `line-width` 进行一系列运算后(单位都是统一的 `px`)得到的

可以看出 `line-width` 的单位限定为 `px` 所以在给 `line-width` 设值时

*  `string` 格式: `line-width="20"`
* `number` 格式: `line-width={{ 20 }}`

这样就可以成功指定宽度了

![S1.png](https://i.loli.net/2020/11/22/dEc6k3ivzOyLDBs.png)
