### ISSUE TITLE
dist里面已经没有image组件了，是把这个组件下掉了还是怎么呢，如果已经下掉了，麻烦文档也更新一下

### ISSUE THREAD

**Issue by AbigaiL533** [youzan/vant-weapp#3581]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater?repo=VantWeapp

**Comment by rex-zsd** [comment]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater?repo=VantWeapp

看了下是有的
