### ISSUE TITLE
希望Tabs及Tab标签能添加100%自适应高度或fill填充高度

### ISSUE THREAD

**Issue by DipSyJava** [youzan/vant-weapp#3582]
每次tab都需要通过js计算出高度，然后固定tab的高，而wx的windowHeight在不同版本下，时不时抽风 获取的高度都不一致，导致计算错误

**Comment by rex-zsd** [comment]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater?repo=VantWeapp

没看懂你的意思，组件内部并没有设定 tab 的高度，完全由内容高度自行撑开。
