### ISSUE TITLE
原生button在vant组件的popup组件里不显示按钮文字

### ISSUE THREAD

**Issue by Boobeaxh** [youzan/vant-weapp#3583]
设备
IOS

VantWeapp 版本
1.0.0-beta.0

基础库版本
2.10.2

如果是 UI 问题，截图链接（多图回车分隔）

![img1](https://user-images.githubusercontent.com/48114831/91927665-af05ba00-ed0c-11ea-8fb6-0513ff99572d.png)

![img2](https://user-images.githubusercontent.com/48114831/91927669-b0cf7d80-ed0c-11ea-9d74-bd1750869a65.png)

描述问题
原生button在vant组件的popup组件里不显示按钮文字，只有点击别的位置，或者等了会才会现实出按钮文字，这个问题体现在IOS的体验版和线上版本上，开发者工具不会出现这个问题，看上图底部的按钮位置

**Comment by rex-zsd** [comment]
上传一下代码片段吧，看起来是比较复杂的问题
