### ISSUE TITLE
害，小程序Stepper 步进器 直接给他设置value无效，都是默认从最小值开始

### ISSUE THREAD

**Issue by 1446186483** [youzan/vant-weapp#3586]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater?repo=VantWeapp

**Comment by Boobeaxh** [comment]
怎么会无效呢，可能是你的写法有问题，建议上代码看看

**Comment by 1446186483** [comment]
<van-stepper value="{{buyNum}}" max="{{goodInfoData.inventory}}" integer bind:change="numChange" focus="{{ true}}" />

**Comment by 1446186483** [comment]
> 怎么会无效呢，可能是你的写法有问题，建议上代码看看
<van-stepper value="{{GoodsNum}}" max="{{goodInfoData.inventory}}" integer bind:change="numChange" focus="{{ true}}" />

**Comment by 1446186483** [comment]
> 怎么会无效呢，可能是你的写法有问题，建议上代码看看

<van-stepper value="{{GoodsNum}}" max="{{goodInfoData.inventory}}" integer bind:change="numChange" focus="{{ true}}" />

**Comment by 1446186483** [comment]
<van-stepper value="{{GoodsNum}}" max="{{goodInfoData.inventory}}" integer bind:change="numChange" focus="{{ true}}" />

**Comment by 1446186483** [comment]
_<van-stepper value="{{buyNum}}" max="{{goodInfoData.inventory}}" integer bind:change="numChange" focus="{{ true}}" />_

**Comment by 1446186483** [comment]
### `<van-stepper value="{{buyNum}}" max="{{goodInfoData.inventory}}" integer bind:change="numChange" focus="{{ true}}" />`

**Comment by 1446186483** [comment]
### 就这一小段啊，没有其他的
`<van-stepper value="{{goodsNum}}" max="{{goodInfoData.inventory}}" integer bind:change="numChange" focus="{{ true}}" />`

**Comment by 1446186483** [comment]
#害，手写了一个居然还有bug，我的天呐

**Comment by rex-zsd** [comment]
………………所以是使用姿势问题是么？
