### ISSUE TITLE
[Bug Report] dialog.d.ts 描述疑惑🤔

### ISSUE THREAD

**Issue by 3lang3** [youzan/vant-weapp#3587]
### 设备
ip6

### VantWeapp 版本
1.4.2

### 基础库版本
2.12.1

### 请提供核心代码片段链接
https://github.com/youzan/vant-weapp/blob/6f07fe68ccdd2f383e3bf019de120f27ea1d534b/dist/dialog/dialog.d.ts#L37-L48

### 描述问题
开发中使用Dialog.alert ts编译器报 不能调用可能是未定义的对象。
我看d.ts描述文件 alert确实是可选方法。。。为啥要这样呢

**Comment by 3lang3** [comment]
然后又看了下toast的描述文件，发现是符合预期的。
https://github.com/youzan/vant-weapp/blob/6f07fe68ccdd2f383e3bf019de120f27ea1d534b/dist/toast/toast.d.ts#L18-L25

**Comment by rex-zsd** [comment]
所以你的代码呢？

**Comment by 3lang3** [comment]
啊 这。。
这个描述文件还要代码吗

**Comment by rex-zsd** [comment]
额，误解了你的意思……
这里是定义写的有问题，下个版本调整哈。
