### ISSUE TITLE
建议van-dropdown-menu组件添加一个属性，可以隐藏标题栏，只通过方法控制下拉菜单的显示与隐藏

### ISSUE THREAD

**Issue by a1029382825** [youzan/vant-weapp#3589]
建议van-dropdown-menu组件添加一个属性，可以隐藏标题栏，只通过方法控制下拉菜单的显示与隐藏
或者添加一个custom-class?

**Comment by rex-zsd** [comment]
看下文档，通过 `toggle` 方法可以手动控制下拉菜单的显示与隐藏。

**Comment by a1029382825** [comment]
@rex-zsd 我说的意思是，不要显示头部，因为有很多是点击搜索旁边的筛选按钮打开，现在没办法隐藏头部，我改了源码height:0;overflow:hidden;
