### ISSUE TITLE
[Bug Report] dialog嵌套input后input的自动聚焦失效

### ISSUE THREAD

**Issue by zcjunblog** [youzan/vant-weapp#3590]
### 设备
三星s9 手机

### VantWeapp 版本
1.5.0

### 基础库版本
2.12.2

### 请提供核心代码片段链接
https://developers.weixin.qq.com/s/MLtm9bmI7yk9

### 描述问题
dialog嵌套input后input的自动聚焦(focus属性)失效

**Comment by rex-zsd** [comment]
首先，input 的自动聚焦 是 `auto-focus` 而不是 `focus`
其次，浮层弹出是需要时间的，页面渲染时还不存在 input，`auto-focus` 是不会生效的

正确的做法是在浮层显示后，手动将 `focus` 属性设置为 `true`

**Comment by rex-zsd** [comment]
比如

```wxml
<van-dialog
  use-slot
  title="标题"
  show="{{ show }}"
  show-cancel-button
  confirm-button-open-type="getUserInfo"
  bind:close="onClose"
>
  <input 
    maxlength="5" 
    focus="{{ focus }}"  
    class="input" 
    type="number" 
    placeholder="待输入" 
  />
</van-dialog>
```

```js
Page({
  data: {
    show: false,
    focus: false
  },

  onLoad() {
    setTimeout(() => {
      this.setData({
        show: true
      });

      setTimeout(() => {
        this.setData({
          focus: true
        });
      }, 100);
    }, 1000);
  },

  onClose() {
    this.setData({ close: false });
  },
});
```

**Comment by zcjunblog** [comment]
> 比如
> 
> ```
> <van-dialog
>   use-slot
>   title="标题"
>   show="{{ show }}"
>   show-cancel-button
>   confirm-button-open-type="getUserInfo"
>   bind:close="onClose"
> >
>   <input 
>     maxlength="5" 
>     focus="{{ focus }}"  
>     class="input" 
>     type="number" 
>     placeholder="待输入" 
>   />
> </van-dialog>
> ```
> 
> ```js
> Page({
>   data: {
>     show: false,
>     focus: false
>   },
> 
>   onLoad() {
>     setTimeout(() => {
>       this.setData({
>         show: true
>       });
> 
>       setTimeout(() => {
>         this.setData({
>           focus: true
>         });
>       }, 100);
>     }, 1000);
>   },
> 
>   onClose() {
>     this.setData({ close: false });
>   },
> });
> ```
感谢

**Comment by youtiao66** [comment]
+1 我也遇到了该问题，感谢 issue 作者和 `rex-zsd`
