### ISSUE TITLE
DatetimePicker 时间选择 android机卡顿

### ISSUE THREAD

**Issue by ancoka** [youzan/vant-weapp#3591]
Popup 弹出层内使用DatetimePicker时间选择 android 机卡顿

**Comment by rex-zsd** [comment]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://youzan.github.io/vant-issue-generater?repo=VantWeapp

**Comment by rex-zsd** [comment]
要注意 `min-date` 跟 `max-date` 的区间是否过大，区间过大会导致渲染的节点数大幅增加。
