### ISSUE TITLE
[Bug Report] van-progress值为0时会被挡住

### ISSUE THREAD

**Issue by hegelsu** [youzan/vant-weapp#3592]
### 设备
模拟器

### VantWeapp 版本
1.5.0

### 基础库版本
2.12.2

### 如果是 UI 问题，截图链接（多图回车分隔）

![截图](https://i.loli.net/2020/09/07/ASxeGztNKwZ3cOW.png)

### 请提供核心代码片段链接
https://sm.ms/image/ASxeGztNKwZ3cOW

### 描述问题
`<van-progress percentage="{{0}}" />`
值为0时会被挡住

**Comment by Jack-scl** [comment]
我也遇到这个问题，请问是否已经修改呢？

**Comment by Jack-scl** [comment]
@rex-zsd 我也遇到这个问题，请问是否已经修改呢？

**Comment by hegelsu** [comment]
@rex-zsd 为啥都更新好几个版本了，这个Bug就得不到修复呢？

**Comment by rex-zsd** [comment]
@hegelsu 不好意思，之前把这个 issue 看漏了，下版本将会修复这个问题哈。
