### ISSUE TITLE
[Feature Request] 无法直接设置主题色变量

### ISSUE THREAD

**Issue by Lynn-cc** [youzan/vant-weapp#3596]
### 这个功能解决了什么问题
我们站点有自己的颜色定义：红、蓝、绿、橙。但是这些颜色在vant的var里，分散到了各个具体的组件的变量下，无法一次性批量替换vant的主题色值为我们的站点色值。

### 建议的API是什么样的
可以一次性自定义全站基础色值

**Comment by rex-zsd** [comment]
用 sass 或者 less 的话，可以把变量集中设置在 theme 文件中。
各个组件引用 theme.less 或 theme.sass 即可。
