### ISSUE TITLE
[Feature Request] field组件中placeholder属性内容多时，可以折行全部显示

### ISSUE THREAD

**Issue by yfyyrh** [youzan/vant-weapp#3597]
### 这个功能解决了什么问题
placeholder属性内容多时，内容显示不全的问题

### 建议的API是什么样的
placeholder属性内容多时，可以折行全部显示，或者增加属性可设置placeholder折行显示

**Comment by rex-zsd** [comment]
微信并不支持对 placeholder 做复杂的样式设置，目前仅能设置 `font-size` `color` 等。
这行这样复杂的样式是无法实现的。
