### ISSUE TITLE
[Bug Report] dialog组件显示不完全

### ISSUE THREAD

**Issue by Huhui-coder** [youzan/vant-weapp#3599]
### 设备
ios

### VantWeapp 版本
1.5.0

### 基础库版本
1.5.0

### 如果是 UI 问题，截图链接（多图回车分隔）

![截图](https://i.loli.net/2020/09/09/1e3REn2s9dKBPCa.png)

### 请提供核心代码片段链接
https://github.com/Huhui-coder/takeawayShop/blob/master/src/pages/index/components/product-list.vue

### 描述问题
左边列表部分是一个 TreeSelect 分类选择组件,dialog 组件被遮挡了，没显示完全。

**Comment by budinggegg** [comment]
这个用zIndex | z-index 层级试试能解决不，工具里看好像不是官方文档写的100，是2000，改成100甚至10试试看

**Comment by Huhui-coder** [comment]
> 这个用zIndex | z-index 层级试试能解决不，工具里看好像不是官方文档写的100，是2000，改成100甚至10试试看

试过了呢，不是z-index 可以解决的问题

**Comment by Huhui-coder** [comment]
> 这个用zIndex | z-index 层级试试能解决不，工具里看好像不是官方文档写的100，是2000，改成100甚至10试试看

重点是在安卓上是ok的，在IOS上才会出现这种情况。

**Comment by rex-zsd** [comment]
应该跟 vant weapp 没有关系。
在 iOS 上 `overflow: hidden;` 是会导致内部 `position: fixed;` 定位的元素也一并被隐藏的，看图就是这个现象。

**Comment by KeepClamm** [comment]
你好，请问最后这个问题怎么解决的呢，我出现了跟你一样的问题。在安卓上是可以的，在ios上显示就有问题
