### ISSUE TITLE
小程序使用该组件时，安卓正常，IOS系统，出现该组件随屏幕滑动异常，该如何解决（问题所指 是 ：van-circle 环形进度条插件）

### ISSUE THREAD

**Issue by theForagingPawns** [youzan/vant-weapp#3602]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater?repo=VantWeapp

**Comment by theForagingPawns** [comment]
问题所指  是 ：van-circle  环形进度条插件

**Comment by rex-zsd** [comment]
不提供代码我们是没办法定位问题的……

你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater?repo=VantWeapp
