### ISSUE TITLE
[Bug Report] IOS系统中，van-circle 环形进度条随屏幕滚动条滚动，安卓机型正常

### ISSUE THREAD

**Issue by WangXinYu-China** [youzan/vant-weapp#3603]
### 设备
iphone 8 plus

### VantWeapp 版本
1.5.0

### 基础库版本
2.7.0

### 如果是 UI 问题，截图链接（多图回车分隔）

![截图](https://sm.ms/image/zIPEc1Yhe6WoQTD)

![截图](https://sm.ms/image/GdFL9x3gaBT4fAr)

### 请提供核心代码片段链接
https://github.com/theForagingPawns/vant-help/blob/master/IssueCode

### 描述问题
IOS系统中，van-circle 环形进度条随屏幕滚动条滚动，安卓机型正常

**Comment by lantongzi** [comment]
咋整 我现在也是这样

**Comment by lantongzi** [comment]
我把cavas 画完后转成图片 在套一个图片组件解决了
![image](https://user-images.githubusercontent.com/22415412/96797257-72179300-1432-11eb-9664-98d15cb60817.png)
![image](https://user-images.githubusercontent.com/22415412/96797559-83f93600-1432-11eb-845a-9b7c577dd41e.png)

**Comment by theForagingPawns** [comment]
> 我把cavas 画完后转成图片 在套一个图片组件解决了
> ![image](https://user-images.githubusercontent.com/22415412/96797257-72179300-1432-11eb-9664-98d15cb60817.png)
> ![image](https://user-images.githubusercontent.com/22415412/96797559-83f93600-1432-11eb-845a-9b7c577dd41e.png)

干到这么晚么，通宵了吧。感谢提供的解决方案兄弟，3Q

**Comment by lantongzi** [comment]
不客气 @theForagingPawns

**Comment by Kuro-liu** [comment]
@lantongzi 大佬，我照写咋不行，设计转前端小白一枚

**Comment by xxxmj-xx** [comment]
您好,这个js方法是写在哪个Js页面,canvas还是index,具体位置是哪里?请指教一下,看着vant的js代码有点蒙

**Comment by WangXinYu-China** [comment]
不好意思，时间太久记不清了，再去看看其他文章吧


在2021年8月9日 ***@***.***> 写道：

您好,这个js方法是写在哪个Js页面,canvas还是index,具体位置是哪里?请指教一下,看着vant的js代码有点蒙

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by xxxmj-xx** [comment]
好的,谢谢.

**Comment by xxxmj-xx** [comment]
我照着代码写好后,页面中的环形图会先短暂出现一次,然后环形图就不出现了

**Comment by WangXinYu-China** [comment]
抱歉哈，长时间不看忘记了。暂时没时间再去看了，再去找找其他博客看下~


在2021年8月12日 ***@***.***> 写道：

我照着代码写好后,页面中的环形图会先短暂出现一次,然后环形图就不出现了

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by xxxmj-xx** [comment]
> 抱歉，长时间不看忘记了。暂时没时间再去看看，再去找其他博客看下~在2021年8月12日***@***.***> 写道：我照着代码写好后，页面中的环形图会先出现一次，然后环形图出现了——你收到这个是因为有人提到了你。直接回复此邮件，在 GitHub 上查看，或取消订阅。使用适用于 iOS 或 Android 的 GitHub Mobile 随时随地分类通知。

我百度了好多,这个问题一直找不到解决办法.其他博客也没有

**Comment by WangXinYu-China** [comment]
我去找下相关代码，你看下~稍等


在2021年8月12日 ***@***.***> 写道：

***@***.***> 写道：我照着代码写好后，页面中的环形图会先出现一次，然后环形图出现了——你收到这个是因为有人提到了你。直接回复此邮件，在 GitHub 上查看，或取消订阅。使用适用于 iOS 或 Android 的 GitHub Mobile 随时随地分类通知。

我百度了好多,这个问题一直找不到解决办法.其他博客也没有

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by WangXinYu-China** [comment]
把你邮箱发我下，我拉你进我的项目


在2021年8月12日 ***@***.***> 写道：
我去找下相关代码，你看下~稍等


在2021年8月12日 ***@***.***> 写道：

***@***.***> 写道：我照着代码写好后，页面中的环形图会先出现一次，然后环形图出现了——你收到这个是因为有人提到了你。直接回复此邮件，在 GitHub 上查看，或取消订阅。使用适用于 iOS 或 Android 的 GitHub Mobile 随时随地分类通知。

我百度了好多,这个问题一直找不到解决办法.其他博客也没有

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by xxxmj-xx** [comment]
> 把你邮箱发我下，我拉你进我的项目在2021年8月12日***@***.***> 留言：我去找下相关代码，你看下~稍等在2021年8月12日***@***.***>发文：***@***.***>发文：我照着代码写好后，页面中的环形图会先出现一次，然后这个场景图出现了——你收到是因为回复了你。直接此邮件，在GitHub上查看，或取消订阅。适用于iOS或Android的GitHub Mobile随时随地通知。我百度了很多，这个问题一直找不到解决办法。其他博客也没有——你收到这个是因为有人提到了你。直接回复此邮件，在 GitHub 上查看，或取消订阅。使用适用于 iOS 或 Android 的 GitHub Mobile 随时随地分类通知。

web_xmj@163.com.多谢

**Comment by WangXinYu-China** [comment]
在2021年8月12日 ***@***.***> 写道：

***@***.***> ***@***.******@***.******>发文：我照着代码写好后，页面中的环形图会先出现一次，然后这个场景图出现了——你收到是因为回复了你。直接此邮件，在GitHub上查看，或取消订阅。适用于iOS或Android的GitHub Mobile随时随地通知。我百度了很多，这个问题一直找不到解决办法。其他博客也没有——你收到这个是因为有人提到了你。直接回复此邮件，在 GitHub 上查看，或取消订阅。使用适用于 iOS 或 Android 的 GitHub Mobile 随时随地分类通知。

***@***.***多谢

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ipconfig12138** [comment]
好家伙,同样问题了

**Comment by johnsonwong666** [comment]
是怎么样的操作步骤，demo页面测试滚动没有发现什么异常，可以提供一个复现代码片段过来吗？

**Comment by johnsonwong666** [comment]
没有复现。由于较长时间没有提供复现代码片段，此issue暂时关闭，若还有问题请提新的issue,并附带复现代码片段排查。
