### ISSUE TITLE
[Bug Report] van-uploader组件设置capture和sizeType无效

### ISSUE THREAD

**Issue by baidonghui** [youzan/vant-weapp#3605]
### 设备
怀疑设备无关：VIVO X5、小米8、红米NOTE5、开发者工具等

### VantWeapp 版本
1.5.0

### 基础库版本
2.13.0

### 如果是 UI 问题，截图链接（多图回车分隔）

![截图](https://s1.ax1x.com/2020/09/11/wNngeg.png)

![截图](https://s1.ax1x.com/2020/09/11/wNnLTJ.png)

### 请提供核心代码片段链接
https://developers.weixin.qq.com/s/MpEbwhmC7Rk5

### 描述问题
不能指定capture和sizeType，后端接收的图片都是好多M...

**Comment by budinggegg** [comment]
遇到同样的坑，capture="camera"或capture="['camera']"均会导致组件无效，点击图标无任何动作和反馈，电脑预览和开发工具都直接打开文件夹
真机调试iphone7 ios13.7
代码：
<van-uploader
name="1"
multiple
accept="image"
capture="['camera']"
bind:delete="delete"
bind:after-read="afterRead"
bind:click-preview="clickPreview" 
file-list="{{ fileList1 }}"
max-count="6" 
/></van-cell-group>

**Comment by rex-zsd** [comment]
按照小程序的语法，合法的写法是

```html
<van-uploader
  accept="image"
  capture="{{ ['camera'] }}"
  size-type="{{ ['compressed'] }}"
/>
```

**Comment by budinggegg** [comment]
非常感谢
