### ISSUE TITLE
popup+picker，真机调试安卓/IOS卡顿严重，有什么解决方式

### ISSUE THREAD

**Issue by fangyezhengwen** [youzan/vant-weapp#3608]
如题，开发工具不卡，真机测试巨卡

**Comment by fangyezhengwen** [comment]
好吧没人解决……已经放弃还是用原生自己写吧。一搜好几个人都反馈过，也不知道各位大佬是不是都是顺畅无比，总之我真机测试都很卡，即便是写死数据测试。

**Comment by rex-zsd** [comment]
没有提供代码完全没办法定位问题 ……
`1.4.4` 优化过 popup 卡的问题，可以试试吧
