### ISSUE TITLE
Picker 如何设置name属性呢，让表单bindsubmit可以读取选中的信息。

### ISSUE THREAD

**Issue by lazyphp** [youzan/vant-weapp#3609]
微信小程序官方的picker示例，可以设置name，然后通过bindsubmit 方法可以得到选中的信息。

vant weapp我看官方文档目前没有name设置的。我网上搜索好久，都没找到解决方法。

目前打算将confirm，change事件得到的值，传入一个隐藏的 表单。这样bindsubmit 就可以直接获取选中的内容了。

**Comment by rex-zsd** [comment]
[文档](https://youzan.github.io/vant-weapp/#/picker) 里没有提到有 `name` 属性吧……
picker 是不支持 form 的，只能通过事件获取值哈
