### ISSUE TITLE
小程序Dialog弹不出来

### ISSUE THREAD

**Issue by taotao6** [youzan/vant-weapp#3610]
电脑上没问题，手机上很卡顿，有时候还弹不出来

你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater?repo=VantWeapp

**Comment by rex-zsd** [comment]
不提供代码完全无法定位问题哈

你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater?repo=VantWeapp
