### ISSUE TITLE
1.5.0版本  slot 插槽组件样式丢失

### ISSUE THREAD

**Issue by dahuaCao** [youzan/vant-weapp#3612]
<van-swipe-cell right-width="{{ 65 }}" left-width="{{ 65 }}">
  <view slot="left">选择</view>
  <van-cell-group>
    <van-cell title="单元格" value="内容" />
  </van-cell-group>
  <view slot="right">删除</view>
</van-swipe-cell>

根据官网实例引用组件，在微信开发者工具中查看样式丢失，slot 具名插槽中没有class类

**Comment by rex-zsd** [comment]
没看到是什么版本什么组件…………

你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater?repo=VantWeapp
