### ISSUE TITLE
van-popup组件https://youzan.github.io/vant-weapp/#/popup

### ISSUE THREAD

**Issue by FuYiCai** [youzan/vant-weapp#3613]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater?repo=VantWeapp
我复制网站demo<van-popup show="{{ show }}" bind:close="onClose">内容</van-popup>；点击蒙版弹层为啥不会自己关闭呢？

**Comment by rex-zsd** [comment]
不提供代码完全无法定位问题哈

你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater?repo=VantWeapp
