### ISSUE TITLE
在taro中整合vant-weapp, 生成模版元素上面怎么出现多个相同的class名称

### ISSUE THREAD

**Issue by ecpanda** [youzan/vant-weapp#3615]
![Snip20200918_2](https://user-images.githubusercontent.com/31544666/93546131-be376980-f994-11ea-8b53-feda65206202.png)

如图所示，我使用的是van-field组件，但是查看wxml发现，元素上面怎么会有两个van-cell类，原本就是这样吗？还是我整合的问题。

**Comment by rex-zsd** [comment]
正常，可以看下微信的文档关于模板和样式的部分

**Comment by ecpanda** [comment]
okay. 感谢回复
