### ISSUE TITLE
DatetimePicker安卓机上面的性能问题

### ISSUE THREAD

**Issue by loca-spirit** [youzan/vant-weapp#3617]
安卓机
DatetimePicker动效是不是没有采取节流？年月日组件，我快速多次切换日，然后快速多次切换月，组件动画反复执行多次，以至于回调函数要等动画结束好久后才执行，这个时候我的窗口可能已经关了，但是值还没有获取到。

苹果机上面很顺畅

用的mpx框架

是否

**Comment by a563905150** [comment]
> 安卓机
> DatetimePicker动效是不是没有采取节流？年月日组件，我快速多次切换日，然后快速多次切换月，组件动画反复执行多次，以至于回调函数要等动画结束好久后才执行，这个时候我的窗口可能已经关了，但是值还没有获取到。
> 
> 苹果机上面很顺畅
> 
> 用的mpx框架
> 
> 是否

同样遇到这个问题，请问你找到解决方案了吗

**Comment by loca-spirit** [comment]
> > 安卓机
> > DatetimePicker动效是不是没有采取节流？年月日组件，我快速多次切换日，然后快速多次切换月，组件动画反复执行多次，以至于回调函数要等动画结束好久后才执行，这个时候我的窗口可能已经关了，但是值还没有获取到。
> > 苹果机上面很顺畅
> > 用的mpx框架
> > 是否
> 
> 同样遇到这个问题，请问你找到解决方案了吗

没有啊，准备下个迭代换为we-ui组件，不用有赞了。
