### ISSUE TITLE
[Bug Report] datetime-picker组件确定按钮有时往上滑会找不到

### ISSUE THREAD

**Issue by yangzhongkai-mt** [youzan/vant-weapp#3618]
### 设备
所有

### VantWeapp 版本
1.5.0

### 基础库版本
2.10.3

### 如果是 UI 问题，截图链接（多图回车分隔）

![截图](https://sm.ms/image/fcSDI6bxuJptkKL)

### 请提供核心代码片段链接
https://github.com/youzan/vant-weapp/tree/dev/lib/datetime-picker

### 描述问题
datetime-picker组件选择时间时确定按钮有时往上滑会找不到，往下也滑不回来。

**Comment by rex-zsd** [comment]
未提供代码片段，图也破了，不能知道是什么问题。
