### ISSUE TITLE
[Bug Report] van-picker这个组件选中根本不能按照官网说的来搞

### ISSUE THREAD

**Issue by baizhi1989** [youzan/vant-weapp#3619]
### 设备
ONEPLUS 5T

### VantWeapp 版本
1.4.4

### 基础库版本
2.12.2

### 描述问题
这玩意坑死个人,多列下拉无法选中,动态设置值可以,设置默认选择哪些内容就完蛋,按照网上教程放到onReady里设置默认值 在真机上也是时好时坏,这个下拉选择默认值,坑了我好几天了啊,咋没人修这个大BUG啊

**Comment by rex-zsd** [comment]
未提供代码片段，看不懂是什么问题。
