### ISSUE TITLE
Picker 选择器的属性show-toolbar不起作用

### ISSUE THREAD

**Issue by CHIMtao** [youzan/vant-weapp#3621]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater?repo=VantWeapp

Picker 选择器的属性show-toolbar不起作用

**Comment by rex-zsd** [comment]
demo 小程序是没问题的，应该是使用姿势的问题。
没有贴使用代码，帮不了你了。

**Comment by santiagochen** [comment]
错误: WXMLRT_$gwx:./components/vant/picker/index.wxml:import:9:2: Path ./toolbar.wxml not found from ./components/vant/picker/index.wxml.
解决方案: 直接把import的内容拷贝到index.wxml里面，不用import就可以。
