### ISSUE TITLE
van-picker 在自定义组件里使用时，custom-class以及active-class等类属性设置无效，会被自动加上'picker--'前缀，再按照加上前缀的类名修改样式无效

### ISSUE THREAD

**Issue by lee-yzlsxs** [youzan/vant-weapp#3622]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater?repo=VantWeapp

**Comment by rex-zsd** [comment]
有前缀是小程序自己的内部行为，不影响功能。

你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater?repo=VantWeapp

**Comment by lee-yzlsxs** [comment]
仔细看了一下文档，在自定义组件加上stylelsolation: 'shared'的属性就行了
.js 文件
options: {
    styleIsolation: 'shared'
  },

**Comment by tieniu1** [comment]
> 仔细看了一下文档，在自定义组件加上stylelsolation: 'shared'的属性就行了 .js 文件 options: { styleIsolation: 'shared' },

字母写错了，是 ```styleIsolation: 'shared',```
