### ISSUE TITLE
vant popup 弹出层不兼容ios 11版本以下怎么办

### ISSUE THREAD

**Issue by liao-heng12** [youzan/vant-weapp#3623]
popup 弹出后 显示遮罩层 背景可以改动 弹出层的内容无法滚动

**Comment by rex-zsd** [comment]
没有这样的问题吧，应该是你对内容设置样式的原因。
没有按模板提交 issue，没办法继续排查了。

**Comment by liao-heng12** [comment]
没有 就是ios 11版本一下 就会  以上的手机都没有这个问题
