### ISSUE TITLE
像checkbox这个组件的bind:change事件如何阻止冒泡事件？

### ISSUE THREAD

**Issue by DwyanWade** [youzan/vant-weapp#3624]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater?repo=VantWeapp

**Comment by rex-zsd** [comment]
看是需要阻止什么事件，以 `tap` 事件为例，可以直接在组件上监听 `catch:tap` 来阻止。

**Comment by bhwebxu** [comment]
> 
> 
> 看是需要阻止什么事件，以 `tap` 事件为例，可以直接在组件上监听 `catch:tap` 来阻止。

![image](https://user-images.githubusercontent.com/1984499/96420796-8425e580-1228-11eb-82d2-80a849d81129.png)
你好，我想阻止checkbox冒泡到jumpVipInfo，以你上面回复catch:tap，在checkbox组件上怎么写？
![image](https://user-images.githubusercontent.com/1984499/96420992-c9e2ae00-1228-11eb-9c20-e500f1091df5.png)
吗？

**Comment by marquisXuan** [comment]
请问解决了么?

**Comment by popcoins-design** [comment]
请问解决了嘛
