### ISSUE TITLE
能否添加按钮仿点击事件属性

### ISSUE THREAD

**Issue by oliverliu365** [youzan/vant-weapp#3625]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater?repo=VantWeapp
能否添加按钮仿点击事件属性

**Comment by rex-zsd** [comment]
没看懂，什么是按钮仿点击事件属性？
