### ISSUE TITLE
van-popup input placeholder不显示无法获取焦点

### ISSUE THREAD

**Issue by zhengbaofeng** [youzan/vant-weapp#3626]
小程序在popup中使用input 标签placeholder不会显示并且input 无法获取焦点不能输入

**Comment by rex-zsd** [comment]
https://developers.weixin.qq.com/s/vpDECymB7tkhs

上传了一个代码片段，实测并不会有这种情况

**Comment by kiccer** [comment]
同疑同问

**Comment by kiccer** [comment]
发现在IOS中存在这个问题
