### ISSUE TITLE
[Bug Report] 【重要】部分组件微信小程序体验评分过低

### ISSUE THREAD

**Issue by huzedong2015** [youzan/vant-weapp#3629]
### 设备
微信开发工具

### VantWeapp 版本
1.4.0

### 基础库版本
2.12.2

### 请提供核心代码片段链接
https://www.baidu.com

### 描述问题
工具Audits检测,
比如：upload组件删除存在以下几点。
1、存在使用 css ':active' 伪类来实现点击态
**2、存在可点击元素的响应区域过小。（应该是删除按钮）**

现在小程序审核可能是以为第2点审核不通过。

### 微信体验评分
https://developers.weixin.qq.com/miniprogram/dev/framework/audits/accessibility.html#2.%20%E9%81%BF%E5%85%8D%E4%BD%BF%E7%94%A8:active%E4%BC%AA%E7%B1%BB%E6%9D%A5%E5%AE%9E%E7%8E%B0%E7%82%B9%E5%87%BB%E6%80%81

**Comment by mw248** [comment]
真机操作，删除很难点中，有一半机率点不中，点成了预览。没有之前旧版本的删除图标好用，并且旧版本的外观也是普通人一看就懂，自说明的样式，现在这半圆，看了得犹豫一下，关键是区域太小点不中，让人恼火

**Comment by rex-zsd** [comment]
体验问题不会导致小程序审核不通过的。
点击区域过小的问题可优化哈。
