### ISSUE TITLE
原生小程序app.js引入Toast求助

### ISSUE THREAD

**Issue by puppetsheep** [youzan/vant-weapp#3632]
在app.js中引入Toast，只能使用`Toast()`，而无法使用`Toast.fail` 或`Toast.success`等，请问如何正确全局引入Toast ?

**Comment by rex-zsd** [comment]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater?repo=VantWeapp
