### ISSUE TITLE
【BUG】van-image组件 src 路径不能使用本地绝对路径且也不能相对路径，相对路径需要多加../../向上两层才可以找到正确地址。

### ISSUE THREAD

**Issue by mobistark** [youzan/vant-weapp#3634]
【BUG】van-image组件 src 路径不能使用本地绝对路径且也不能相对路径，相对路径需要多加../../向上两层才可以找到正确地址。

**Comment by mobistark** [comment]
补充下，src使用绝对路径，开发工具不会报错，模拟器可以显示出来图，但真机不显示。
src使用相对页面路径开发工具则会报错。但需要多加个../../ ，不然他是找到的/miniprogram_npm/@vant/这个下面的目录。

**Comment by rex-zsd** [comment]
相对路径肯定是以组件位置起始的，关于绝对路径的情况，请按照微信小程序的规则来。
另外，小程序中是不推荐使用本地图片的，本地资源将占用小程序包大小，影响启动性能的。
