### ISSUE TITLE
构建npm之后报错

### ISSUE THREAD

**Issue by gong123yan** [youzan/vant-weapp#3637]
[ miniprogram_npm/@vant/weapp/popup/index.json 文件内容错误] miniprogram_npm/@vant/weapp/popup/index.json: ["usingComponents"]["van-overlay"]: "../overlay/index" 未找到

**Comment by rex-zsd** [comment]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater?repo=VantWeapp
