### ISSUE TITLE
van-calendar 能否添加一个属性，最好支持数组，填写不可选日期

### ISSUE THREAD

**Issue by candyAndBella** [youzan/vant-weapp#3638]
像挂号平台，可以预约未来7天中的某一天，但是这7天中，有些日期已约满，为不可选状态。

**Comment by rex-zsd** [comment]
看下[文档](https://youzan.github.io/vant-weapp/#/calendar#day-shu-ju-jie-gou)，通过 `formatter` 可将日期的 `type` 设置为 `disabled` 来实现禁用。
