### ISSUE TITLE
构建npm后打包上传miniprogram_npm超过2M,如何分包上传

### ISSUE THREAD

**Issue by chenyaohua** [youzan/vant-weapp#3639]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater?repo=VantWeapp

**Comment by rex-zsd** [comment]
可以将非首页的页面都配置到分包，组件库这类基础依赖最好是在主包内。
如果有大量组件没有使用到的，可以手动在 miniprogram_npm 内删除掉减小体积。

**Comment by Windancer** [comment]
我也遇到这个问题，希望能有解决方案
