### ISSUE TITLE
tab组件的active值，重置active值只能生效一次？

### ISSUE THREAD

**Issue by lazyphp** [youzan/vant-weapp#3641]
我用tab组件，做了一个动态加载行为。当加载未完成时，tab切换不应该马上完成切换行为。可实际情况是，
例如：
现有 3个tab选项。点第二个tab，由于网络加载需要， onChange和onClick，在未完成时，active值我强制设置回去0 . 待加载完成后，我在设置回当前的 event.detail.index 。

可实际上，active值重置一次后，就无法在强制重置切换的位置了。

**Comment by rex-zsd** [comment]
> 你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。
> 
> http://vant-contrib.gitee.io/vant-issue-generater?repo=VantWeapp

上传一下代码片段重新提个 issue 吧。
