### ISSUE TITLE
[Bug Report] van-field 禁用状态不显示值

### ISSUE THREAD

**Issue by AmadeusSys** [youzan/vant-weapp#3642]
### 设备
Mac

### VantWeapp 版本
1.5.0

### 基础库版本
2.13.0

### 请提供核心代码片段链接
https://github.com/youzan/vant-weapp/tree/dev/example/pages/field

### 描述问题
在Mac系统PC微信小程序，使用van-field设置disabled属性后value内容不显示，Android手机端，开发者工具端均正常

**Comment by rex-zsd** [comment]
可以扫下首页的 demo 小程序看下，应该是不会不显示的。
![image](https://user-images.githubusercontent.com/8767877/94358488-f1d06d00-00d3-11eb-8adb-88b4e964e9cd.png)

**Comment by AmadeusSys** [comment]
![image](https://user-images.githubusercontent.com/25811397/95185864-de23b580-07fb-11eb-8a1e-6a9e48daf5d6.png)
是小程序PC端

**Comment by AmadeusSys** [comment]
![Uploading image.png…]()

**Comment by lzq932765726** [comment]
我跟你的问题是一样的，ios14+版本全部是不行，我换成readonly属性就可以正常赋值，因为你是disabled的所有我把所有的v-model换成了:value,有机会交流一下了！
