### ISSUE TITLE
[Bug Report] Steps 步骤条 完成步骤文字颜色不能保持高亮，希望您能提供方法更改，谢谢！

### ISSUE THREAD

**Issue by budinggegg** [youzan/vant-weapp#3644]
### 设备
iphone7

### VantWeapp 版本
1.5.0

### 基础库版本
2.13

### 如果是 UI 问题，截图链接（多图回车分隔）

![截图](https://i.loli.net/2020/09/27/nXZs6tKSakov3Li.png)

### 请提供核心代码片段链接
https://gist.github.com/budinggegg/16a63206ca30b51df1e63c849bded56a

### 描述问题
步骤条如果用户不按顺序操作，高亮文字也只是当前完成步骤，其他完成步骤颜色都会是未高亮，本人材浅未能研究初怎么改，需求是所有完成步骤的文字都保持激活状态的高亮颜色，不会因为下一步变成灰色，完成后颜色不改变，保持激活状态颜色。希望得到您的帮助，谢谢！

**Comment by rex-zsd** [comment]
可以看下样式覆盖部分的[文档](https://youzan.github.io/vant-weapp/#/custom-style#shi-yong-css-bian-liang)
steps 提供了 `--step-finish-text-color` 的变量，可以用来修改已完成的选择的颜色。

**Comment by budinggegg** [comment]
搞定了，非常感谢！

**Comment by rex-zsd** [comment]
😃

**Comment by budinggegg** [comment]
用了这个变量有个新问题，比如四步骤，我先完成第四步骤，之前未完成的步骤也全部高亮，有没有办法实现只高亮已完成的步骤，并且完成其他步骤时已完成的步骤高亮，未完成的步骤灰暗?

**Comment by rex-zsd** [comment]
不可以，steps 必须是按顺序执行的。

**Comment by budinggegg** [comment]
非常感谢！我提交了Feature Request，希望以后能够实现吧！
