### ISSUE TITLE
[Bug Report] 依旧Steps 步骤条 完成不能保持高亮，用finish变量，未完成也高亮，求解！谢谢！

### ISSUE THREAD

**Issue by budinggegg** [youzan/vant-weapp#3647]
### 设备
iphone7

### VantWeapp 版本
1.5.0

### 基础库版本
2.12

### 如果是 UI 问题，截图链接（多图回车分隔）

![截图](https://i.loli.net/2020/09/27/96yMFL8QA4IuYtO.png)

### 请提供核心代码片段链接
https://gist.github.com/budinggegg/16a63206ca30b51df1e63c849bded56a

### 描述问题
使用--step-finish-text-color后，步骤条如果用户不按顺序操作，当前激活步骤前所有步骤都是finish状态，即便是未完成也会高亮，是否能实现某步骤完成才成为finish状态，比如text和desc都可以去赋值改变，是否能单独定义每个步骤的完成状态呢?求解！求解！谢谢！

**Comment by rex-zsd** [comment]
#3644
