### ISSUE TITLE
[Feature Request] Steps 步骤条 实现非顺序步骤验证模式

### ISSUE THREAD

**Issue by budinggegg** [youzan/vant-weapp#3648]
### 这个功能解决了什么问题
用户非顺序操作能够验证过往操作完成情况，目前的Steps组件是循环验证，用户不按顺序操作时可以赋值显示操作是否完成，但不能单独高亮完成步骤或，单独赋值某步骤的样式

### 建议的API是什么样的
在已有steps数组里增加一个active验证每一步骤是否完成，不论用户操作是否按顺序，都能正确验证用户执行的步骤是否完成，只是把需求写在了代码注释里，谢谢！

### 展示一下新功能的大致用法，代码片段链接（GitHub Gist）
https://gist.github.com/budinggegg/16a63206ca30b51df1e63c849bded56a

**Comment by rex-zsd** [comment]
steps 不按顺序激活的需求目前我们不考虑支持哈。
