### ISSUE TITLE
[Bug Report] Toast.clear()有时候无效,吐司无法去除

### ISSUE THREAD

**Issue by longzhu123** [youzan/vant-weapp#3649]
### 设备
安卓和苹果

### VantWeapp 版本
1.3.0

### 基础库版本
2.11

### 请提供核心代码片段链接
https://gist.github.com/longzhu123/29acd75c05ba3bcc617392126909eda3

### 描述问题
在请求中,
先使用
        Toast.loading({
            duration: 0,
            mask: true,
            message: '加载中...'
        });
在wx.request的succes方法中调用  Toast.clear();

有时候Toast.clear();无效,loading框一直存在

**Comment by lantongzi** [comment]
建议直接使用微信的  wx.showToast()

**Comment by DaZiYuan** [comment]
wx.showToast()不好看。
Toast.loading()
// 中间不要停顿
Toast.clear()
很容易重现，中间等待一下就不会出问题

**Comment by rex-zsd** [comment]
可以用 `wx.nextTick` 包裹一下，避免显示和清除之间的间隔时间过短。
微信的 `setData` 是异步的，当 `loading` 之后立即调用 `clear `，有可能 `clear` 时 toast 尚未显示出来，导致 `clear` 失效

```js
Toast.loading();

getDataFromRemote(() => {
  wx.nextTick(() => {
    Toast.clear();
  });
});
```
