### ISSUE TITLE
在List 组件与 PullRefresh 组件结合使用是，下来出现两个加载中.....

### ISSUE THREAD

**Issue by goHaoliyou** [youzan/vant-weapp#3650]
描述一下问题
List 组件与 PullRefresh 组件结合使用是，下来出现两个加载中.....
van-pull-refresh下有个van-loading, van-list__loading里也有个loading, loading-text=""已设空了。
![图片](https://user-images.githubusercontent.com/27000085/94527593-caaba400-0269-11eb-87b7-2935824524aa.png)

[环境]

设备: chrome浏览器,safari浏览器，小米手机,,,,,都有
基础库版本: 2.10.8

**Comment by rex-zsd** [comment]
vant weapp 没有 List 组件呀，提错 issue 了？
指路 [vant](https://github.com/youzan/vant/issues)
