### ISSUE TITLE
button细边框问题

### ISSUE THREAD

**Issue by yahaoli** [youzan/vant-weapp#3651]
.van-hairline:after {
  position: absolute;
  box-sizing: border-box;
  -webkit-transform-origin: center;
  transform-origin: center;
  content: " ";
  pointer-events: none;
  top: -50%;
  right: -50%;
  bottom: -50%;
  left: -50%;
  border: 0 solid #eee;
  -webkit-transform: scale(.5);
  transform: scale(.5)
}
最新版丢失了 transform-origin: center;导致布局错乱

**Comment by mw248** [comment]
+1，同样的问题，终于有人提了
