### ISSUE TITLE
[Feature Request] 类型提示定义

### ISSUE THREAD

**Issue by DreamPWJ** [youzan/vant-weapp#3655]
### 这个功能解决了什么问题
现在开发中类型定义可以让编辑器自动提示 极大提高开发效率  组件属性每次都要上官网查看确认效率极低  尤其适用Taro这种先进的基于TypeScript方式开发 ，编辑器一直提示红色波浪线，组件大量的属性都要去文档上查看。习惯了先进开发回到这种原始开发实在不适应

### 建议的API是什么样的
类型定义  编辑器根据定义提示组件属性  大量的index.d.ts都是空的 index.d.ts完成

**Comment by rex-zsd** [comment]
vant weapp 是基于原生小程序语法开发的小程序组件库，不会为 taro 特别编写组件定义的哈。

**Comment by DreamPWJ** [comment]
不要带框架偏见好不？  这个是类型定义和Taro没关系

**Comment by DreamPWJ** [comment]
请问index.d.ts大量的空着是为了啥？  没有编辑器类型提示开发效率真的很低啊

**Comment by rex-zsd** [comment]
因为原生小程序并不支持组件的类型定义

**Comment by DreamPWJ** [comment]
好吧  开发效率真的好低 一下回到几年前

**Comment by DreamPWJ** [comment]
之前用taro ui类型提示很完美 也可支持多端  唯一缺点就是维护不给力

**Comment by DreamPWJ** [comment]
![image](https://user-images.githubusercontent.com/16730031/94662369-e03cce80-033a-11eb-99ec-d80164efbd4f.png)
已去微信小程序社区提了@rex-zsd

**Comment by liaokaime** [comment]
4年后过来挖坟，写标签时仍然没有编辑器提示props，好难受
