### ISSUE TITLE
[Bug Report] Dialog 弹出框 通过组件调用 Dialog 时van-dialog内容过多无法滑动，无法显示底部按钮

### ISSUE THREAD

**Issue by budinggegg** [youzan/vant-weapp#3656]
### 设备
iphone7

### VantWeapp 版本
1.5.1

### 基础库版本
2.13

### 如果是 UI 问题，截图链接（多图回车分隔）

![截图](https://i.loli.net/2020/10/04/oFt8Cq2ZDY7MdBl.jpg)

### 请提供核心代码片段链接
https://gist.github.com/budinggegg/b19e6bdc533e2254b01fef13d1b75656

### 描述问题
通过组件调用 Dialog 时van-dialog内嵌套其他组件，当容过多时Dialog 无法滑动，尝试过很多方法也无法下拉，导致无法显示底部按钮

**Comment by budinggegg** [comment]
这个用zIndex | z-index 层级试试能解决不，工具里看好像不是官方文档写的100，是2000，改成100甚至10试试看

**Comment by rex-zsd** [comment]
dialog 内容高度是有限制的，最大高度为屏幕高度的100%，不可以无限制撑高。
这里自行请为中间部分设置最大高度和滚动样式。
