### ISSUE TITLE
van-button 使用hairline属性 显示错乱

### ISSUE THREAD

**Issue by chenzhao951012** [youzan/vant-weapp#3657]
![微信图片_20201010180203](https://user-images.githubusercontent.com/44046234/95652333-c06b8e80-0b22-11eb-9ec5-477f15c6e659.png)
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater?repo=VantWeapp

**Comment by rex-zsd** [comment]
最新版本已经修复细边框问题咯，可以升级下哈。

**Comment by chenzhao951012** [comment]
你好&nbsp; 我的已经更新到最新了&nbsp; 还是没用好 小程序上面使用的
