### ISSUE TITLE
uploader组件切换为image可以正常选择图片，切换为file时无法选择文件

### ISSUE THREAD

**Issue by yonguoli** [youzan/vant-weapp#3658]
你好，我在微信小程序中，使用van-uploader组件。在小程序中，定义了三个tab，分别是（小程序名：AO打印）文件、打印、我的。van-uploader放在文件这个tab页中。
1、小程序登录后，如果不切换到打印、我的这两个tab页，则上传选择无论是image还是file，均可以正常选择图片或文件。
2、小程序登录后，如果切换到文印、我的。再返回到文件这个tab页，操作上传。此时如果是image则可以正常选择图片。但如果是file，则再也无法选择文件了。

以上问题，非常紧急，特请求支持！小程序二维码，请在www.aoprint.cn右上角扫码再现。谢谢，谢谢，谢谢~~~

http://vant-contrib.gitee.io/vant-issue-generater?repo=VantWeapp

**Comment by rex-zsd** [comment]
![1602592173593614](https://user-images.githubusercontent.com/8767877/95862448-85bd5c80-0d95-11eb-855a-1d90d2a2b982.gif)
目前是无法复现，`file` 和 `image` 均可正常选择。

**Comment by yonguoli** [comment]
这两天没上来，怎么把我的关闭了呢？我的手机是小米5Plus的，登录后，先切换到我的，然后再在文件里上传，此时无法选择文件（只有再次切换到别的导航页时，才弹出 选择一个聊天）

**Comment by yonguoli** [comment]
能否加我微信，请教你一下呢：Fudaheng
