### ISSUE TITLE
[Bug Report] Tab添加动画(animated)后会导致DropdownMenu下拉选项位置错误

### ISSUE THREAD

**Issue by iblackly** [youzan/vant-weapp#3659]
### 设备
EMU,ANDROID,IOS

### VantWeapp 版本
1.5.1

### 基础库版本
2.3.13

### 如果是 UI 问题，截图链接（多图回车分隔）

![截图](https://i.loli.net/2020/10/10/vl1n9YjMtPzWGxO.png)

![截图](https://i.loli.net/2020/10/10/wdKfah8s36omNAJ.png)

### 请提供核心代码片段链接
https://developers.weixin.qq.com/s/7Zcrr0m17dlC

### 描述问题
Tab添加动画(animated)后会导致DropdownMenu下拉选项位置错误

**Comment by rex-zsd** [comment]
添加 `animated` 属性后，将会给 tabs 的 content 部分添加 `transform` 属性，这将创建一个新的堆叠上下文，使内部的 `position: fixed` 不再按照视窗固定定位。

**Comment by rex-zsd** [comment]
下个版本不再使用 `transform` 实现动画
