### ISSUE TITLE
van-uploader bind:before-read的回调参数并没有event.detail.file.type属性

### ISSUE THREAD

**Issue by azhaaa** [youzan/vant-weapp#3661]
van-uploader bind:before-read的回调参数并没有event.detail.file.type属性，导致bind:before-read方法没有任何作用，根本看不到上传的文件是什么类型的，根本不能做一个上传前文件校验

**Comment by rex-zsd** [comment]
`type` 仅在 `accept` 为 `all` `media` `file` 等多种类型的场景下才会返回，对于 `image` `video` 单类型的是不会返回的。
这部分文档实例代码有误，将在下版本修正。

**Comment by albb58** [comment]
media也不能返回，试了只有all可以

**Comment by rex-zsd** [comment]
下版本将对 uploader 做优化，使得返回数据更统一。
