### ISSUE TITLE
[Feature Request] 未提供SKU 选择组件

### ISSUE THREAD

**Issue by walkingsanduo** [youzan/vant-weapp#3662]
### 这个功能解决了什么问题
开发小程序的商城程序中，商详页的 “sku选择组件” 未提供，就是商详页，可以选择颜色尺寸，购买数量等那个组件，在vue版的链接为https://youzan.github.io/vant/#/zh-CN/sku
希望可以提供；

### 建议的API是什么样的
"usingComponents": {
  "van-card": "@vant/weapp/card/sku"
}

**Comment by rex-zsd** [comment]
可以搜下历史 issue，sku 组件已经明确目前暂不提供咯。
