### ISSUE TITLE
[Bug Report] van-tabs 选项卡切换 闪动

### ISSUE THREAD

**Issue by panyushan2019** [youzan/vant-weapp#3665]
### 设备
所有设备

### VantWeapp 版本
1.5.1

### 基础库版本
2.12.2

### 请提供核心代码片段链接
http://vant-contrib.gitee.io/vant-weapp/#/tab

### 描述问题
选项卡切换时 屏幕会闪动 会跳动一下 用户体验很不好 感觉是渲染的问题

**Comment by SherryLJX** [comment]
这个bug我改了好久好久   原来是组件的问题T^T

**Comment by FlexibleHha** [comment]
有什么fix方案吗，闪动确实不友好

**Comment by FlexibleHha** [comment]
> 这个bug我改了好久好久 原来是组件的问题T^T
这个闪动的bug，有解决方案吗。

**Comment by panyushan2019** [comment]
> > 这个bug我改了好久好久 原来是组件的问题T^T
> > 这个闪动的bug，有解决方案吗。

你可以用他的tab标签  但是内容不要放在tab里面 在下面自己写

**Comment by panyushan2019** [comment]
> 有什么fix方案吗，闪动确实不友好

你可以用他的tab标签 但是内容不要放在tab里面 在下面自己写

**Comment by FlexibleHha** [comment]
> > > 这个bug我改了好久好久 原来是组件的问题T^T
> > > 这个闪动的bug，有解决方案吗。
> 
> 你可以用他的tab标签 但是内容不要放在tab里面 在下面自己写

好的，我试一下！！

**Comment by FlexibleHha** [comment]
> > 有什么fix方案吗，闪动确实不友好
> 
> 你可以用他的tab标签 但是内容不要放在tab里面 在下面自己写

感谢了

**Comment by younth** [comment]
re

**Comment by rex-zsd** [comment]
#3290
合并一下重复 issue，可以关注上面这个哈

**Comment by jimolangyaleng** [comment]
确实不友好，希望高版本能够修复
