### ISSUE TITLE
Field 输入框 有时是搜索 有时是选定

### ISSUE THREAD

**Issue by liao-heng12** [youzan/vant-weapp#3666]
Field 输入框    输入 "内蒙古"关键字后  键盘是只有选定和下一个以及其它键 没有搜索   要在后面多打几个字或者把多打的字删掉才能出来搜索 
代码如下：
<form action="javascript:return true">
      <van-search
        v-model="words"
        type="search"
        placeholder="请输入资讯关键字"
        @search="Search"
        shape="round" />
 </form>
在微信小程序运行
架构：vue2.9  
框架：vant
手机：iphone x max  
型号：MT752CH/A

**Comment by rex-zsd** [comment]
是提错 issue 了？看起来是反馈 vant 的问题。
[指路](https://github.com/youzan/vant/issues)
