### ISSUE TITLE
van-dialog 点击确定关闭弹框

### ISSUE THREAD

**Issue by victor2016** [youzan/vant-weapp#3667]
请问在使用van-dialog嵌套组件时，默认是点击确定不改变show值也会关闭dialog弹框吗？

<van-dialog
  use-slot
  title="标题"
  show="{{ show }}"
  show-cancel-button
  bind:close="onClose"
  bind:confir="onConfirm"
>
  <image src="https://img.yzcdn.cn/1.jpg" />
</van-dialog>

**Comment by rex-zsd** [comment]
是的，在 `asyncClose` 为 `false` 时，Dialog 将会从内部关闭弹框。

**Comment by wangfpp** [comment]
为什么不交给开发者控制？？
