### ISSUE TITLE
[Bug Report] vant-tabs sticky吸顶后关于tab栏选中后的样式位置bug

### ISSUE THREAD

**Issue by a2774206** [youzan/vant-weapp#3670]
### 设备
任意

### VantWeapp 版本
1.5.0

### 基础库版本
任意

### 请提供核心代码片段链接
https://vant-contrib.gitee.io/vant-weapp/#/tab

### 描述问题
bug复现：<br>
1.页面padding 30rpx（页面最外层内边距）<br>
2.van-tabs开启属性 swipeable animated sticky<br>
3.van-tab数量4-5个（正好没有滚动条）<br>
4.第一个标签下滚动到开启吸顶，然后点击其他标签，选中状态的位置发生了侧歪。（bug复现）<br>
当tab数量多（可以横向滚动的时候），就没有问题。<br>

**Comment by xsw911213** [comment]
我是这么设置完之后，根本就不起作用

`<van-tabs id="tabs" sticky offset-top="{{ indexTop }}" border="{{false}}"  nav-class="tab-line" line-width="30" bind:click="checkTab" >
      <van-tab title="推荐" prop="activityRecommend" custom-class="tab-style"></van-tab>
      <van-tab title="最新" prop="activityNew" custom-class="tab-style"></van-tab>
      <van-tab title="热门" prop="activityHot" custom-class="tab-style"></van-tab>
    </van-tabs>`

**Comment by rex-zsd** [comment]
开启滚动时下划线样式错误的问题已经修复了，可以升级到最新版本看下哈。

**Comment by MakerFace** [comment]
同样遇到，添加动画animated之后，tabs之间间隔很大
![before image](https://user-images.githubusercontent.com/19760290/117647495-9c0e8800-b1bf-11eb-9a4f-33b46b845c3e.png)
![after image](https://user-images.githubusercontent.com/19760290/117647395-7ed9b980-b1bf-11eb-9c86-3d9e48b2cbc3.png)
