### ISSUE TITLE
[Bug Report] 字体无法访问

### ISSUE THREAD

**Issue by evanwu66** [youzan/vant-weapp#3671]
### 设备
IOS

### VantWeapp 版本
1.5.1

### 基础库版本
2.12.1

### 请提供核心代码片段链接
https://img.yzcdn.cn/vant/vant-icon-eeb192.woff2

### 描述问题
Failed to load font https://img.yzcdn.cn/vant/vant-icon-eeb192.woff2
net::ERR_CACHE_MISS

**Comment by rex-zsd** [comment]
可以看下[文档](https://youzan.github.io/vant-weapp/#/icon#chang-jian-wen-ti)，这个错误提示忽略即可。
