### ISSUE TITLE
[Bug Report] @types/wechat-miniprogram 不应该放到 package.json的"devDependencies"里

### ISSUE THREAD

**Issue by bigmeow** [youzan/vant-weapp#3672]
### 设备
无

### VantWeapp 版本
1.5.1

### 基础库版本
无

### 请提供核心代码片段链接
https://github.com/youzan/vant-weapp/blob/9aaba79c73a856f32e7b997209cef10326f7fc9a/package.json#L49

### 描述问题
首先可以知道npm安装的VantWeapp的toast组件是对外暴露了toast.d.ts，toast.d.ts是使用了@types/wechat-miniprogram的声明的：
https://github.com/youzan/vant-weapp/blob/8f21b5ed17a6a5e46aa19b72d7b4bf7de339cc74/dist/toast/toast.d.ts#L1
但是在package.json中，却没有将@types/wechat-miniprogram作为生产依赖安装：
https://github.com/youzan/vant-weapp/blob/9aaba79c73a856f32e7b997209cef10326f7fc9a/package.json#L49
这就导致了项目里使用import方式引入Toast组件的地方，就会报错，说找不到 `找不到“wechat-miniprogram”的类型定义文件`:
```ts
import Toast from "@vant/weapp/toast/toast";
```

而已有项目里使用的微信d.ts却并不是`@types/wechat-miniprogram`, 而是 `miniprogram-api-typings`

![image.png](https://i.loli.net/2020/10/15/JnCxBpjWkoY2fZD.png)

所以，个人觉得解决办法是下面之一：
1.删掉组件中的 ` /// <reference types="wechat-miniprogram" />`
2. 将 `@types/wechat-miniprogram` 添加到 "dependencies" 中而不是 "devDependencies"

**Comment by rex-zsd** [comment]
👍

**Comment by bigmeow** [comment]
升级后有个新的问题：
项目里用的 `miniprogram-api-typings`, 它和 vant用的`@types/wechat-miniprogram`是同一个库，只不过`@types/wechat-miniprogram`发布版本会更慢一些。项目里同时存在这2个会有冲突：
![image.png](https://i.loli.net/2020/10/16/ZUInwEjpgMsfXi6.png)

项目之所以不用`@types/wechat-miniprogram`是因为它更新慢，毕竟是国外的别人的仓库，发版不归自己，按照微信的迭代速度，肯定是选微信自己的独立 npm 包
@rex-zsd

**Comment by bigmeow** [comment]
如果给 `tsconfig.json`增加配置：
```json
{
  "skipLibCheck": true,
}
```
这样可以跳过冲突，然后又会产生新的问题，某些本来没有问题的声明突然失效了，经过比对后发现还是版本问题：
`@types/wechat-miniprogram` 存在bug, 而这bug在`miniprogram-api-typings`中已经修复发版...
建议还是弃用`@types/wechat-miniprogram`吧

**Comment by rex-zsd** [comment]
换用 `@types/wechat-miniprogram` 的原因主要是它不需要额外配置。
发版的问题是有点蛋疼，最近再观察看看吧，如果落后太多的话，准备下下个版本切回来。

**Comment by bigmeow** [comment]
3.x 这个版本变动比较大，bug也相对多了一些，我跑去微信那边催他们更新 `@types/wechat-miniprogram`

**Comment by c9n** [comment]
https://github.com/youzan/vant-weapp/issues/3699
