### ISSUE TITLE
van-sidebar和van-card如何共存？

### ISSUE THREAD

**Issue by zhd9307** [youzan/vant-weapp#3675]
你好，我尝试创建一个van-grid，然后把van-sidebar放左边，把van-card放右边，但是无法调整两边宽度，sidebar会自动在左边产生一个margin。

想问一下应该怎么设置wxss，使得左边sidebar 和右边商品卡片的宽度可以大致处于2：8的比例？谢谢

**Comment by DennisJKF** [comment]
用van-row和van-col

**Comment by rex-zsd** [comment]
sidebar 和 card 组件都没有自带 margin 样式的哈。
可以自己调试下样式看看，用 rol 和 col 组合也可以的。
