### ISSUE TITLE
tabs组件在动态tab时，下标红线异常

### ISSUE THREAD

**Issue by Unximarks** [youzan/vant-weapp#3676]
![image](https://user-images.githubusercontent.com/16741161/96107511-14091e00-0f0f-11eb-8124-b13705ed4927.png)

vant webapp 所有版本都试过都有问题，基础库2.12.2。

**Comment by Unximarks** [comment]
异常主要不是长度，而是位置不会跑到第一个去，点击后会变正常

**Comment by a2774206** [comment]
> 异常主要不是长度，而是位置不会跑到第一个去，点击后会变正常

是不是开启吸顶了。而且没有滚动条。

**Comment by Unximarks** [comment]
> > 异常主要不是长度，而是位置不会跑到第一个去，点击后会变正常
> 
> 是不是开启吸顶了。而且没有滚动条。

没有开吸顶，就是很正常的界面出现时调用一个接口去获取tab数据，然后下划线就那样，这么普通的需求不会就我遇见了吧

**Comment by Unximarks** [comment]
特地回去试了下，0.x版本是没问题，1.x版本在tabs的数据动态改一下的话下划线会出现异常

**Comment by rex-zsd** [comment]
下版本将会新增导出 `resize` 方法，使动态的场景下外部可以通过手动调用的方式设置下划线。
