### ISSUE TITLE
Vant Weapp 的组件库可否跟Vant移动端的同步？

### ISSUE THREAD

**Issue by byedear** [youzan/vant-weapp#3679]
两者的不同处就是业务组件那边  

比如：Vant移动端那有编辑地址组件   Vant Weapp里面没有

再比如：Vant移动端那有Sku商品规格组件  Vant Weapp里面没有  

因为是新手前端  所以对自定义组件可能不太会  所以想问下不知道可否两个组件库同步下。。。

http://vant-contrib.gitee.io/vant-issue-generater?repo=VantWeapp

**Comment by rex-zsd** [comment]
vant 那边之所以有业务组件其实是历史原因，立项初期将内部用的业务组件直接放在开源库里面了。
所以 vant weapp 这边 对于 Sku、AddressEdit 这些业务组件是不会跟进的。
