### ISSUE TITLE
van-uploader 最新版accept问题

### ISSUE THREAD

**Issue by albb58** [youzan/vant-weapp#3680]
van-uploader accept为media时，没有name，同时最新的1.5.2版本，accept为media时，虽热有type了，但是wx.uploadFile不会执行，为all时就可以执行

**Comment by rex-zsd** [comment]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater?repo=VantWeapp

请按照格式提issue哦
