### ISSUE TITLE
[Feature Request] tabbar如何自定义背景？现在好像连透明都不是

### ISSUE THREAD

**Issue by KuoKongQingYun** [youzan/vant-weapp#3681]
### 设备
Android

### VantWeapp 版本
1.5.2

### 基础库版本
2.12.2

### 描述问题
tabbar如何自定义背景？现在好像连透明都不是，除了自己修改组件源码，只能是纯白吗？

**Comment by rex-zsd** [comment]
默认背景色是白色，可通过 CSS 变量 `--tabbar-background-color` 修改背景色，详情请查看[文档](https://youzan.github.io/vant-weapp/#/theme)
