### ISSUE TITLE
[Bug Report] 微信开发者工具 npm 构建不通过

### ISSUE THREAD

**Issue by LanceZhu** [youzan/vant-weapp#3682]
### 设备
Windows 10

### VantWeapp 版本
1.5.2

### 基础库版本
2.13.1

### 请提供核心代码片段链接
https://github.com/youzan/vant-weapp/blob/31aacedd5b8d9ebf2419afc77993d7fbfe841e0d/package.json#L98

### 描述问题
VantWeapp 1.5.2 版本中 dependency 中引入的 @types/wechat-miniprogram，导致微信开发者工具中构建 npm失败。

**node_modules**

![image](https://user-images.githubusercontent.com/26158863/96397522-53c85200-11fc-11eb-8430-e87544e86863.png)

**构建 npm 失败**

![image](https://user-images.githubusercontent.com/26158863/96397640-7bb7b580-11fc-11eb-9bbb-8993e14a3bec.png)

**Comment by rex-zsd** [comment]
忽略即可，`@types/wechat-miniprogram` 不需要被构建，微信目前没有提供 npm 构建的筛选过滤。
