### ISSUE TITLE
小程序版的没有轮播组件吗

### ISSUE THREAD

**Issue by quavario** [youzan/vant-weapp#3685]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater?repo=VantWeapp

**Comment by rex-zsd** [comment]
轮播请使用[微信原生组件](https://developers.weixin.qq.com/miniprogram/dev/component/swiper.html) vant weapp 不再重复造轮子
