### ISSUE TITLE
tabs如何设置默认选中项

### ISSUE THREAD

**Issue by cjyCJ** [youzan/vant-weapp#3686]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater?repo=VantWeapp

**Comment by rex-zsd** [comment]
请看[文档](https://youzan.github.io/vant-weapp/#/tab#dai-ma-yan-shi)
