### ISSUE TITLE
[Feature Request] calendar日历组件 日期选择可用性的运行时动态设置

### ISSUE THREAD

**Issue by oioixia** [youzan/vant-weapp#3688]
### 这个功能解决了什么问题
在min-date 和max-date之间，可以根据运行数据，动态地设置可用性，也就是设置Day 数据结构中的type为"disabled" 。例如：设置min-date="2020-10-1",max-date="2020-10-10",但根据运行数据，需要设置"2020-10-8"为不可选择

### 建议的API是什么样的
dates['2020-10-8'].type="disabled"

**Comment by rex-zsd** [comment]
已支持的特性，请查看[文档](https://youzan.github.io/vant-weapp/#/calendar#day-shu-ju-jie-gou)
