### ISSUE TITLE
van-card没有onreachbottom的binding

### ISSUE THREAD

**Issue by zhd9307** [youzan/vant-weapp#3690]
您好，

我用vancard的时候商品拉到底没有能触发onreachbottom的事件，请问应该如何设置？我在左边设置了一个van-sidebar，右边是van-card。拉动右边没法触底刷新了。

`

<view class="container">
  <view class="nav_left">

    <van-sidebar active-key="{{ activeKey }}" bind:change="onChange">
      <van-sidebar-item title="推荐" />
      <van-sidebar-item title="进店必买" />
      <van-sidebar-item title="随便点都好吃" />
      <van-sidebar-item title="还有这些吃吃" />
      <van-sidebar-item title="随便点都好喝" />
      <van-sidebar-item title="还有这些喝喝" />
      <van-sidebar-item title="招牌组合" />
    </van-sidebar>

  </view>

  <view class="nav_right">

    <view>
      <swiper indicator-dots="true" indicator-active-color="#FFA940" autoplay="true" interval="3500" circular="true">
        <block wx:for="{{tops}}" wx:key="_id">
          <swiper-item>
            <image src="{{item.image}}" mode="aspectFill" class="slide-image"></image>
          </swiper-item>
        </block>
      </swiper>
    </view>
    <view wx:for="{{list}}" wx:key="_id">
      <van-card price="{{item.price}}" desc="{{item.detail}}" data-id="{{item._id}}" tag="{{item.tags}}"
        title="{{item.title}}" thumb="{{item.image}}" origin-price="{{item.cross_price}}" thumb-mode lazy-load="true"
        bindtap="toDetail">
        <view class="addBtn" slot="footer">
          <van-button type="primary" color="#FFA940" size="mini" catchtap="addCart" data-item="{{item}}">加入购物车
          </van-button>
        </view>
      </van-card>
    </view>
  </view>

</view>

<van-notify id="van-notify" />`

`page{
  height:100%;
  width:100%;
  background: #f7f8fa;
}
/*总体主盒子*/
.container {
  position: absolute;
  width: 100%;
  height: 100%;
  overflow: hidden;
  background: #f7f8fa;

}
 
/*左侧栏主盒子*/
.nav_left{
  position: absolute;
  /*设置行内块级元素（没使用定位）*/
  display: inline-block;
  width: 20%;
  height: 100%;
  /*主盒子设置背景色为灰色*/
  text-align: center;
  overflow: scroll;
  background: #f7f8fa;

}

/*右侧栏主盒子*/
.nav_right{
  /*右侧盒子使用了绝对定位*/
  position: absolute;
  top: 0;
  right: 0;
  flex: 1;
  /*宽度75%，高度占满，并使用百分比布局*/
  width: 80%;
  height: 100%;
  box-sizing: border-box;
  overflow: scroll;
  background: #f7f8fa;

  

}

.cart{
  padding: 5rpx;
  background: #FFA940;
  border-radius: 50%;
  width: 100%;
}`

**Comment by rex-zsd** [comment]
`onReachBottom` 和组件库完全没关系，请看[微信文档](https://developers.weixin.qq.com/miniprogram/dev/reference/api/Page.html#onReachBottom)
