### ISSUE TITLE
[Bug Report] field组件label-class变量未加入模板标签内

### ISSUE THREAD

**Issue by manyee-dev** [youzan/vant-weapp#3691]
### 设备
一般设备

### VantWeapp 版本
1.5.1

### 基础库版本
2.12.1

### 请提供核心代码片段链接
https://github.com/youzan/vant-weapp/blob/master/lib/field/index.wxml

### 描述问题
field组件的label-class变量名未加入模板标签内，导致设置label-class后生成标签内不会包含 自定义label-class，设置效果无效。看了一下，1.4.0版本加入这个功能时就忘记加了，之前有其他人提了类似的issue，但是你们可能理解错了关闭了，看了一下最新1.5.2暂时还没有加入，请检查一下谢谢！

**Comment by manyee-dev** [comment]
`<view wx:if="{{ label }}" class="{{ utils.bem('field__label', { disabled }) }}" slot="title">
    {{ label }}
  </view>`
这里的class内的'label-class'没加进去

**Comment by rex-zsd** [comment]
你对 `label-class` 的生效逻辑理解有误，使其生效的代码是这里`https://github.com/youzan/vant-weapp/blob/7d74a169fe73ab8a7c1940695380961981aa26e9/packages/field/index.wxml#L17`

**Comment by manyee-dev** [comment]
> 你对 `label-class` 的生效逻辑理解有误，使其生效的代码是[这里](https://github.com/youzan/vant-weapp/blob/7d74a169fe73ab8a7c1940695380961981aa26e9/packages/field/index.wxml#L17)
> https://github.com/youzan/vant-weapp/blob/7d74a169fe73ab8a7c1940695380961981aa26e9/packages/field/index.wxml#L17
感谢您的回复，实际测试了一下cell组件：
cell中title-solt生效时，在cell标签内声明的title-class无效， code中添加了'test-class'
![image](https://user-images.githubusercontent.com/61569217/96691942-0f81b100-13b8-11eb-9f39-209c5263eccf.png)
渲染后
![image](https://user-images.githubusercontent.com/61569217/96692413-96cf2480-13b8-11eb-9762-b4bc8d0db939.png)
说回field ，我手动把源码的 title-solt位置的标签内的class添加了'label-class'，渲染结果是有传入的自定义label-class的。
如果有错误感谢指正！

**Comment by manyee-dev** [comment]
不好意思，建议您动手去试试，没加就是没加，不是生效逻辑问题，插槽生效时 title-class不参与渲染，您说的逻辑这个时候有什么意义呢？真的建议您认真review

**Comment by kawaiiz** [comment]
> 不好意思，建议您动手去试试，没加就是没加，不是生效逻辑问题，插槽生效时 title-class不参与渲染，您说的逻辑这个时候有什么意义呢？真的建议您认真review

![image](https://user-images.githubusercontent.com/25151442/97961076-9178cd80-1ded-11eb-87dc-5adf35a402a7.png)
可以通过 .你的类名 .van-field__label添加你想要的样式

**Comment by manyee-dev** [comment]
> > 不好意思，建议您动手去试试，没加就是没加，不是生效逻辑问题，插槽生效时 title-class不参与渲染，您说的逻辑这个时候有什么意义呢？真的建议您认真review
> 
> ![image](https://user-images.githubusercontent.com/25151442/97961076-9178cd80-1ded-11eb-87dc-5adf35a402a7.png)
> 可以通过 .你的类名 .van-field__label添加你想要的样式

这是手动在外部添加的，知道的，谢谢。但是源码本来有这个变量，他没加进去，加了的话 "label-class"属性是可以直接生效的，他可能误会我的意思了，我本地改了源码是没问题的

**Comment by rex-zsd** [comment]
将在下版本修复，感谢反馈

**Comment by hongmaoxiao** [comment]
确实没生效，"@vant/weapp": "1.6.8" 依然没有生效

**Comment by hongmaoxiao** [comment]
> > 不好意思，建议您动手去试试，没加就是没加，不是生效逻辑问题，插槽生效时 title-class不参与渲染，您说的逻辑这个时候有什么意义呢？真的建议您认真review
> 
> ![image](https://user-images.githubusercontent.com/25151442/97961076-9178cd80-1ded-11eb-87dc-5adf35a402a7.png)
> 可以通过 .你的类名 .van-field__label添加你想要的样式

现在已经把.van-field__label改掉了，很尴尬
