### ISSUE TITLE
van-field 的 show-word-limit 的bug

### ISSUE THREAD

**Issue by lmh0506** [youzan/vant-weapp#3692]
如果文字大量的复制粘贴显示会有如下问题，用maxlength限制后， 字符长度还是300，如果删除一个字符后显示会正常
![image](https://user-images.githubusercontent.com/24320015/96693576-fd087700-13b9-11eb-9525-da4cc15027c9.png)

**Comment by rex-zsd** [comment]
maxlength 这个是微信的原生行为，vant weapp 这边没有什么可做的呢

**Comment by lmh0506** [comment]
> maxlength 这个是微信的原生行为，vant weapp 这边没有什么可做的呢

好吧，了解了
