### ISSUE TITLE
根据文档安装的依赖包没有找到日历组件

### ISSUE THREAD

**Issue by DuyinLoo88** [youzan/vant-weapp#3693]
未找到calendar组件

http://vant-contrib.gitee.io/vant-issue-generater?repo=VantWeapp
![Uploading image.png…]()

**Comment by rex-zsd** [comment]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater?repo=VantWeapp
