### ISSUE TITLE
版本低于v2.10.4的vue用tabbar before-change 本地运行可以 打包后却用不了  为什么本地运行时可以呢

### ISSUE THREAD

**Issue by mqyxgwk8135156** [youzan/vant-weapp#3695]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater?repo=VantWeapp

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
