### ISSUE TITLE
小程序提供的业务组件对比Vant要少

### ISSUE THREAD

**Issue by xiaodun** [youzan/vant-weapp#3697]
各位大佬好，我们这边业务相当在有赞小程序的基础上做扩展,开发需要用到"Sku 商品规格"和"Coupon 优惠券"这两个业务组件。

之前在定制h5的时候是有提供的，所以想要咨询下，这两个组件有计划要提供吗？ 提供的话大概是什么时候？

万分感谢!

**Comment by rex-zsd** [comment]
这两个业务组件没有计划哦

**Comment by xiaodun** [comment]
> 这两个业务组件没有计划哦

是出于怎么样的考量不计划支持呢

**Comment by rex-zsd** [comment]
搜索一下历史 issue 吧，解答过好多次了
