### ISSUE TITLE
[Bug Report] 微信开发工具构建项目失败

### ISSUE THREAD

**Issue by cnlt** [youzan/vant-weapp#3699]
### 设备
微信开发工具

### VantWeapp 版本
1.5.2

### 基础库版本
2.13.1

### 如果是 UI 问题，截图链接（多图回车分隔）

![截图](https://i.loli.net/2020/10/23/iV1Io5bX9ugNp6H.png)

### 请提供核心代码片段链接
https://sm.ms/image/NxJLbHSvkrj8qFu

### 描述问题
在构建的时候就报错了
![微信截图_20201023111938.png](https://i.loli.net/2020/10/23/iV1Io5bX9ugNp6H.png)

**Comment by 1037055457** [comment]
我的也构建失败了..  不过我的提示是
Error:ENOTEMPTY:directory not empty,rmdir 'E:\miniprogram_npm\@vant\weapp\common\style'

**Comment by qq517351411** [comment]
一样构建失败  直接复制进去就行了 不用 构建了

**Comment by lamguang** [comment]
我也构建npm失败，以上情况都有。

**Comment by lamguang** [comment]
使用node v10.22.1

**Comment by keel** [comment]
同样的问题，看了对应的目录，里面只有index.d.ts

**Comment by dreamZhf** [comment]
有人解决么？

**Comment by 1207934561** [comment]
我是显示构建完成，组件也能使用，但是提示 /node_modules/@types/wechat-miniprogram/index.js:未找到npm包入口文件，不知道会不会有什么影响

**Comment by renlzrz** [comment]
每次微信工具构建报的错都不一样

**Comment by 13938417646** [comment]
同样的问题，这样会有什么影响么

**Comment by 13938417646** [comment]
忽略即可，@types/wechat-miniprogram 不需要被构建，微信目前没有提供 npm 构建的筛选过滤。

**Comment by linlei1990527** [comment]
我也遇到了楼主的问题

**Comment by rex-zsd** [comment]
下版本去除 @types/wechat-miniprogram 的依赖。
这个包构建失败是可忽略的，但容易造成误解。
