### ISSUE TITLE
[Feature Request] Popup 在自定义 NavBar 下，怎么设置top 值 

### ISSUE THREAD

**Issue by agoni1212** [youzan/vant-weapp#3701]
### 这个功能解决了什么问题
Popup 在自定义 NavBar 下，怎么设置top 值 ，使popup 的内容不被  navbar 遮挡

### 建议的API是什么样的
style : top

现在我是放了一个占位

**Comment by rex-zsd** [comment]
`position="top"` 的 popup 可以设置 `custom-style="top: 100px;"` 来留出顶部空间。

**Comment by agoni1212** [comment]
`position="right"` 的情况下，怎么设置？

**Comment by rex-zsd** [comment]
`position="right"` 时，垂直方向是居中的，跟自定义 NavBar 有什么关系？

**Comment by agoni1212** [comment]
> `position="right"` 时，垂直方向是居中的，跟自定义 NavBar 有什么关系？

如果内容不居中，出现上下滚动条的情况下，在自定义NavBar的时候，是上面的数据是被 NavBar 挡住的

我设置了样式 ` custom-style="width: 80%; height: 100%;"`
