### ISSUE TITLE
使用toast组件设置duration为0时报incongruent status: leave  

### ISSUE THREAD

**Issue by w1561778301** [youzan/vant-weapp#3703]
代码中设置toast组件的展示时长duration:0报
![image](https://user-images.githubusercontent.com/69661617/97266002-9fb17180-1862-11eb-8545-6a97ec5c0345.png)这个错误

**Comment by rex-zsd** [comment]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater?repo=VantWeapp
