### ISSUE TITLE
[Bug Report] 原生微信小程序使用uploader组件，bind:delete事件不触发

### ISSUE THREAD

**Issue by shaww0930** [youzan/vant-weapp#3704]
### 设备
微信开发者工具

### VantWeapp 版本
1.4.0

### 基础库版本
2.13.1

### 请提供核心代码片段链接
https://gist.github.com/shaww0930/5f325e93e675cf5a3e07ef87fa8ff1be

### 描述问题
原生微信小程序使用uploader组件，bind:delete事件不触发

**Comment by rex-zsd** [comment]
提供的不是可运行的代码片段，这几行代码无法看出是否有错误。
可以看下我们提供的 example 实例项目，`delete` 事件是可以正常触发的。
