### ISSUE TITLE
[Bug Report] 构建 npm 提示 未找到 npm 包入口文件

### ISSUE THREAD

**Issue by zhangjie2012** [youzan/vant-weapp#3706]
### 设备
微信开发工具

### VantWeapp 版本
1.5.2

### 基础库版本
2.12.0

### 描述问题
使用 npm 安装 `@vant/weapp` 之后，构建 npm 提示：`node_modules/@types/wechat-miniprogram/index.js: 未找到npm包入口文件。`

1.5.0 版本也有此问题，但是之前是没这个问题的，今晚重新安装构建之后就出现这个问题了。期间升级了一次微信开发者工具（目前版本为：1.03.2010240）。

**Comment by linlei1990527** [comment]
我也遇到这个问题，退回到1.5.1就行了

**Comment by zhangjie2012** [comment]
我之前装的 1.5.0 也有这个问题。

**Comment by zhangjie2012** [comment]
@linlei1990527 你是对的。我回退了，就好了。

**Comment by rex-zsd** [comment]
@types/wechat-miniprogram 仅提供代码提示，构建失败忽略即可
