### ISSUE TITLE
Tabs，直接设置active无效，1.5.0无此问题

### ISSUE THREAD

**Issue by 04swjxy** [youzan/vant-weapp#3709]
在无点击操作的情况下，直接this.setData({ activeTab: 'newValue' })，视图不会更新。1.5.0无此问题
版本：1.5.1，1.5.2
工具：微信开发工具
基础库版本：2.4.4

**Comment by rex-zsd** [comment]
未复现问题，提供一下代码片段吧

**Comment by zuonidelaowang** [comment]
我也有这个问题， 之前用的1.5.0是没问题的 升级1.5.2版本 初始化状态不能选中

**Comment by zuonidelaowang** [comment]
> 在无点击操作的情况下，直接this.setData({ activeTab: 'newValue' })，视图不会更新。1.5.0无此问题
> 版本：1.5.1，1.5.2
> 工具：微信开发工具
> 基础库版本：2.4.4

解决了吗？

**Comment by rex-zsd** [comment]
> 我也有这个问题， 之前用的1.5.0是没问题的 升级1.5.2版本 初始化状态不能选中

上传个代码片段？

**Comment by zuonidelaowang** [comment]
> > 我也有这个问题， 之前用的1.5.0是没问题的 升级1.5.2版本 初始化状态不能选中
> 
> 上传个代码片段？

这里 https://developers.weixin.qq.com/s/C3YqqCmT7ilH

**Comment by rex-zsd** [comment]
好的

**Comment by anglepan** [comment]
我也遇到此问题，初始化状态不能选中；就是简单初始setdata，activeTab不行

**Comment by rex-zsd** [comment]
> > > 我也有这个问题， 之前用的1.5.0是没问题的 升级1.5.2版本 初始化状态不能选中
> > 
> > 
> > 上传个代码片段？
> 
> 这里 https://developers.weixin.qq.com/s/C3YqqCmT7ilH

根据这个代码片段，目前判断是 mpx 框架下会有问题，原生小程序是 ok 的，具体原因还待查。

**Comment by zuonidelaowang** [comment]
> 我也遇到此问题，初始化状态不能选中；就是简单初始setdata，activeTab不行

分享一个代码片段上来看看！

**Comment by zuonidelaowang** [comment]
> > > > 我也有这个问题， 之前用的1.5.0是没问题的 升级1.5.2版本 初始化状态不能选中
> > > 
> > > 
> > > 上传个代码片段？
> > 
> > 
> > 这里 https://developers.weixin.qq.com/s/C3YqqCmT7ilH
> 
> 根据这个代码片段，目前判断是 mpx 框架下会有问题，原生小程序是 ok 的，具体原因还待查。

我退回1.5.0版本了！

**Comment by rex-zsd** [comment]
@zuonidelaowang @anglepan 你们都使用了 mpx 是么？

**Comment by zuonidelaowang** [comment]
> @zuonidelaowang @anglepan 你们都使用了 mpx 是么？

我用的是mpx

**Comment by cumt-robin** [comment]
原生小程序还是不行，用的1.6.2版本，退回算了，什么时候修复呢？

**Comment by zuonidelaowang** [comment]
> 原生小程序还是不行，用的1.6.2版本，退回算了，什么时候修复呢？

提供一个代码片段上来，让作者看看，目前还没复现出来问题，修复不了

**Comment by cumt-robin** [comment]
> > 原生小程序还是不行，用的1.6.2版本，退回算了，什么时候修复呢？
> 
> 提供一个代码片段上来，让作者看看，目前还没复现出来问题，修复不了

很简单，active="{{activeTab}}" 想让第二个默认选中，结果还是第一个，没什么代码好发的了

**Comment by zuonidelaowang** [comment]
> > > 原生小程序还是不行，用的1.6.2版本，退回算了，什么时候修复呢？
> > 
> > 
> > 提供一个代码片段上来，让作者看看，目前还没复现出来问题，修复不了
> 
> 很简单，active="{{activeTab}}" 想让第二个默认选中，结果还是第一个，没什么代码好发的了

哦！

**Comment by cumt-robin** [comment]
原生小程序也一样，npm构建方式使用的，暂时只能用1.5.0版本了

@rex-zsd

**Comment by rex-zsd** [comment]
@cumt-robin 是否设置了 `info` 属性？如果是的话，应该跟 #3817 是一个问题，从 1.6.2 引入，与这个 issue 不是一个问题。

**Comment by mikasaYw** [comment]
v1.6.2版本  没有设置info属性  active无作用 transition初始化无作用
原生，wepy2.0 都没有效果

**Comment by rex-zsd** [comment]
@mikasaYw  原生小程序的版本传个代码片段上来？
