### ISSUE TITLE
文档Cell组件标签点击没有效果

### ISSUE THREAD

**Issue by zhanghaifeng213** [youzan/vant-weapp#3710]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater?repo=VantWeapp

文档Cell组件标签点击没有效果
![image](https://user-images.githubusercontent.com/26516275/97822813-fc44de80-1cf1-11eb-970c-a6773d6cc078.png)

**Comment by rex-zsd** [comment]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater?repo=VantWeapp
