### ISSUE TITLE
Cell icon 如何调整图标大小呢

### ISSUE THREAD

**Issue by Jack-scl** [youzan/vant-weapp#3728]
在cell组件中，哪个属性可以调整图标大小呢？
![image](https://user-images.githubusercontent.com/32790815/97936488-979f8780-1db6-11eb-8580-ae7717171c35.png)

**Comment by rex-zsd** [comment]
可使用 CSS 变量 `--cell-icon-size`，详见[文档](https://youzan.github.io/vant-weapp/#/theme)

**Comment by Jack-scl** [comment]
具体应该写呢？还是不太清楚
<van-cell title="意见反馈" icon="comment-circle-o" size="large" is-link link-type="navigateTo" url="/pages/feedback/feedback" />

**Comment by Jack-scl** [comment]
<van-cell title="意见反馈" icon="comment-circle-o" size="large" is-link link-type="navigateTo" url="/pages/feedback/feedback" />
