### ISSUE TITLE
toast组件建议新增onShow,onHide两个回调函数

### ISSUE THREAD

**Issue by wkl007** [youzan/vant-weapp#373]
*新增功能*

options参数建议新增onShow,onHide两个回调函数

*使用场景*

比如toast消失后跳转页面的相关操作

*目前解决方法*

>  Toast({
                type: 'success',
                message: '操作成功',
                selector: '#zan-toast-test',
                timeout: 1000
              })
              setTimeout(() => {
                //返回上一页面
                wx.navigateBack({
                  delta: 1
                })
              }, 1000)

*期望用法*

> Toast({
                type: 'success',
                message: '操作成功',
                selector: '#zan-toast-test',
                timeout: 1000,
                onShow: () => {
                  //toast显示
                },
                onHide: () => {
                  //toast隐藏
                  wx.navigateBack({
                    delta: 1
                  })
                }
              })

**Comment by chenjiahan** [comment]
目前 zanui-weapp 已进行全新的品牌升级，更名为 Vant Weapp，组件和 API 都有较大的变化。

对 zanui-weapp 的讨论，请移步至 https://github.com/youzan/zanui-weapp 仓库
