### ISSUE TITLE
van-tabs  sticky offset-top 吸顶单位疑问

### ISSUE THREAD

**Issue by pengxAlone** [youzan/vant-weapp#3731]
此处吸顶以px作为单位，在一些应用场景特别难用， 就是上面还有一个以rpx做单位吸顶的广告位，那van-tabs这里的吸顶会和上面的不能很好的衔接

**Comment by rex-zsd** [comment]
因为是否吸顶是需要 js 进行计算的，而微信的 API 目前返回的是 px 单位的数字。
这种情况下，是不可能支持 rpx 单位的。
