### ISSUE TITLE
[Bug Report] van-field组件在安卓手机上报错

### ISSUE THREAD

**Issue by stlswm** [youzan/vant-weapp#3732]
### 设备
安卓华为p30

### VantWeapp 版本
1.5.2

### 基础库版本
2.14.0

### 请提供核心代码片段链接
http://stlswm.cdmanjing.com/article/show_2_2_22.html

### 描述问题
当使用英文输入法**（一定要是英文输入法）输入内容，不要选择候选词（切记）**，点击屏幕空白地方（很多SB用户就有这个习惯，无语半刻...），输入的内容没有触发bind:input的事件，且程序报错:Do not have onInput handle in current page
手机型号：华为p30
微信版本：7.0.19
调试基础库：2.14.0
出现概率：100%
重现步骤：
1、打开官方demo，在基础用法上实现一个bind:input事件
2、输入法切换到英文模式，任意输入内容，不点击候选词，点击页面空白地方
3、出现错误
我试过微信原生组件在安卓和IOS都没有这个问题，使用van-field组件在安卓手机上有问题，IOS正常。

**Comment by rex-zsd** [comment]
与 #3736 相同，已向微信社区反馈，可关注这个 issue 中的链接
