### ISSUE TITLE
日历组件

### ISSUE THREAD

**Issue by MDistance** [youzan/vant-weapp#3733]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater?repo=VantWeapp
小程序中的vant没有日历组件吗

**Comment by MDistance** [comment]
小程序中的vant没有日历组件吗

**Comment by zcjunblog** [comment]
> 小程序中的vant没有日历组件吗

van-calendar 不就是    文档:[Calendar 日历](https://youzan.github.io/vant-weapp/#/calendar)

**Comment by rex-zsd** [comment]
有日历组件的哈，上面的大哥已经贴了文档地址了。
