### ISSUE TITLE
安卓使用Vue版本的uploader组件上传视频时不会压缩视频

### ISSUE THREAD

**Issue by Sue666666** [youzan/vant-weapp#3734]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater?repo=VantWeapp

**Comment by rex-zsd** [comment]
额，提错 issue 啦，这里是 vant weapp。
应该向 vant 提 issue。
