### ISSUE TITLE
DropdownMenu的close-on-click-outside在小程序上失效

### ISSUE THREAD

**Issue by OYass** [youzan/vant-weapp#3735]
weapp的DropdownMenu，在点击菜单意外的区域时无法关闭菜单。小程序基础库2.12.2

**Comment by rex-zsd** [comment]
dropdown-menu 是只有点击菜单或者灰色蒙层部分才会关闭的哈。
点击其它区域组件是感知不到的，这个是小程序的机制限制导致的，目前无法解决的。
