### ISSUE TITLE
field组件的事件问题

### ISSUE THREAD

**Issue by BryantKawhi** [youzan/vant-weapp#3736]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater?repo=Vanfield

**华为手机上，且是自带的华为键盘**

微信小程序中有多个field组件时，在某个field中（A）随便输入英文字符，然后点击其他的field（B）获取到焦点；这时field(A)的change事件并不能被触发。

测试小程序原生的input组件   不存在该问题

**Comment by rex-zsd** [comment]
经测试，这个场景触发了微信的 BUG。

在 field 英文输入不选词即切换焦点时，微信小程序触发的不是 van-field 组件内部的 `onInput` 事件，而是直接尝试触发页面上的同名事件。

将原生 input 组件嵌套在任意自定义组件内，再在页面上使用，即可复现。

![image](https://user-images.githubusercontent.com/8767877/98443274-4fc98900-2145-11eb-9730-fd398b18e1a0.png)

目前这个问题 vant weapp 无法处理，只能向微信反馈。

**Comment by rex-zsd** [comment]
可复现的代码片段 https://developers.weixin.qq.com/s/nIF7iGmJ7Klx

**Comment by rex-zsd** [comment]
社区反馈可见 https://developers.weixin.qq.com/community/develop/doc/00042813f8c818d5813bf2eab5ec00
后续可关注这个地址哈
