### ISSUE TITLE
[Bug Report] area组件第三列code长度大于6选择错误

### ISSUE THREAD

**Issue by 751468644** [youzan/vant-weapp#3737]
### 设备
微信开发者工具

### VantWeapp 版本
1.5.0

### 基础库版本
2.132.2

### 请提供核心代码片段链接
https://cdn.asyjchina.com/5b6u5L h5Zu 54mHXzIwMjAxMTA3MTEyNDE0LnBuZzE2MDQ3MTk0NjE=

### 描述问题
根据国家统计局最新发布的广东省东莞市县区行政号，长度为9位，在选择广东省东莞市县区的时候会一直回弹到请选择县区的第一个选项

**Comment by rex-zsd** [comment]
[民政部官网](http://www.mca.gov.cn//article/sj/xzqh/2020/202011/202011060901.html)上还是6位号码呀？
9位比6位多包含乡镇街道级别，vant 是仅支持省市区6位码的哈
