### ISSUE TITLE
popup弹出层动画失效

### ISSUE THREAD

**Issue by zhanghaibo911** [youzan/vant-weapp#3741]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater?repo=VantWeapp
扫码体验官方vant-weapp示例,华为荣耀20手机,微信版本7.0.20中的popup弹出层动画时有时无,体验不好

**Comment by rex-zsd** [comment]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater?repo=VantWeapp
