### ISSUE TITLE
微信开发者工具构建 npm 包提示 @types 未找到 npm 包入口文件

### ISSUE THREAD

**Issue by dulltackle** [youzan/vant-weapp#3743]
设备
Windows 10 微信开发者工具 1.03.2010240

VantWeapp 版本
1.5.2

基础库版本
2.14.0

描述问题

按照 Vant Weapp 文档中快速上手章节进行操作, 执行到微信开发者工具构建 npm 包时, 提示 `@types` 未找到 npm 包入口文件, 具体情况如图所示

![问题.png](https://i.loli.net/2020/11/10/st8b5yKLcwfCRnY.png)

**Comment by rex-zsd** [comment]
#3699
相同问题，参考这个 issue
