### ISSUE TITLE
actions 中item添加className,在wxml 中查看会追加两个相同的class 在元素上

### ISSUE THREAD

**Issue by webxmsj** [youzan/vant-weapp#3744]
https://github.com/youzan/vant-weapp/blob/3d3af763c1708c333be9a92df06436d3de81e5e5/packages/action-sheet/index.wxml#L32
actions
![image](https://user-images.githubusercontent.com/40289489/98669103-da9bc500-238b-11eb-9eb8-1803b5fb2ada.png)

结果
![image](https://user-images.githubusercontent.com/40289489/98669030-bd66f680-238b-11eb-8908-e6fc3b7ec3de.png)

actions 中item添加className,在wxml 中查看会追加两个相同的class 在元素上

**Comment by rex-zsd** [comment]
这个是微信小程序本身的机制，忽略即可。
vant weapp 开启了设置允许外部样式覆盖，此时小程序会将 class 复制一份，实际无影响。
```js
addGlobalClass: true
```
