### ISSUE TITLE
如何隐藏组件？

### ISSUE THREAD

**Issue by artzers** [youzan/vant-weapp#3745]
小程序的组件是拥有hidden这个属性，然后我添加这个属性到组件，比如cell，是无法隐藏组件的。请问应该怎么做？

<van-cell title="title" title-width="10em" visible="{{true}}" >
  <van-switch input model:checked="{{ val}}"  size="24px" />
</van-cell>

**Comment by rex-zsd** [comment]
直接使用 `wx:if` 进行隐藏就可以了。
`hidden` 仅对原生组件有效，对自定义组件是无效的哈。

**Comment by WuXianShi** [comment]
> 使用直接`wx:if`进行隐藏就可以了。
> `hidden`仅对原生组件有效，对自定义组件是无效的哈。

那对于频繁操作的内容用wx:if是不是很影响性能？
