### ISSUE TITLE
[Bug Report] van-tab切换标签下划线不能对应显示

### ISSUE THREAD

**Issue by WangYu007** [youzan/vant-weapp#3748]
### 设备
android,ios

### VantWeapp 版本
1.4.3

### 基础库版本
不知道

### 如果是 UI 问题，截图链接（多图回车分隔）

![截图](https://i.loli.net/2020/11/11/jYBIPVZ8tE1iDrx.png)

### 请提供核心代码片段链接
https://gitee.com/wyloveyou/sxt-miniprogram/blob/master/pages/manage/manage.wxml

### 描述问题
van-tab超过4项时，切换标签后面的标签下划线不能对应显示。例如：本来是切换到语文项，但是下划线没有滑过来，但是对应的内容是正确的.

**Comment by now915** [comment]
下划线初始位置不正确

**Comment by rex-zsd** [comment]
1.4.3 的历史问题已经修复啦，可以升级一下哈。

**Comment by rex-zsd** [comment]
可升级到 1.4.4 及以上的版本
