### ISSUE TITLE
1.6.0 Npm构造 vant-picker 少了emit方法

### ISSUE THREAD

**Issue by xumiaojun** [youzan/vant-weapp#3749]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater?repo=VantWeapp

 emit: function (event) {
            var type = event.currentTarget.dataset.type;
            if (this.simple) {
                this.$emit(type, {
                    value: this.getColumnValue(0),
                    index: this.getColumnIndex(0)
                });
            }
            else {
                this.$emit(type, {
                    value: this.getValues(),
                    index: this.getIndexes()
                });
            }
        },

**Comment by muuubooo** [comment]
正出现同样的问题， 
bind:cancel / bind:confirm
都会显示
does not have a method "emit" to handle event "tap".

**Comment by rex-zsd** [comment]
ok，今天将会再发布一个版本修复这个问题

**Comment by githubzyl** [comment]
上面那个绑定cancel和confirm事件的问题解决了吗？我现在还没法用

**Comment by xumiaojun** [comment]
> 上面那个绑定cancel和confirm事件的问题解决了吗？我现在还没法用

在npm构造的文件包里的picker， index里面 加上 这个方法 emit: function (event) {
var type = event.currentTarget.dataset.type;
if (this.simple) {
this.$emit(type, {
value: this.getColumnValue(0),
index: this.getColumnIndex(0)
});
}
else {
this.$emit(type, {
value: this.getValues(),
index: this.getIndexes()
});
}
},

**Comment by qqccyv** [comment]
> 正出现同样的问题， picker组件
> bind:cancel / bind:confirm
> 都会显示
> does not have a method "emit" to handle event "tap".
我也遇到了。。。
Component "miniprogram_npm/@vant/weapp/picker/index" does not have a method "emit" to handle event "tap".

**Comment by rex-zsd** [comment]
1.6.1 已发布

**Comment by msforest** [comment]
问题解决了吗？我用了1.6.1，还是不行呢
```
<van-popup show="{{ isUp }}" position="bottom" custom-style="height: 40%" bind:close="toggleLocation">
    <van-area area-list="{{ areaList }}" item-height="{{30}}" visible-item-count="{{5}}" bind:cancel="toggleLocation"
      bind:confirm="cityFn" />
  </van-popup>
```
哪位高人帮忙看看

**Comment by msforest** [comment]
> > 上面那个绑定cancel和confirm事件的问题解决了吗？我现在还没法用
> 
> 在npm构造的文件包里的picker， index里面 加上 这个方法 emit: function (event) {
> var type = event.currentTarget.dataset.type;
> if (this.simple) {
> this.$emit(type, {
> value: this.getColumnValue(0),
> index: this.getColumnIndex(0)
> });
> }
> else {
> this.$emit(type, {
> value: this.getValues(),
> index: this.getIndexes()
> });
> }
> },

@xumiaojun 问下你用1.6.1解决了吗？我使用1.6.1，还是报同样的错误，可以帮忙看看吗

**Comment by muuubooo** [comment]
> > > 上面那个绑定cancel和confirm事件的问题解决了吗？我现在还没法用
> > 
> > 
> > 在npm构造的文件包里的picker， index里面 加上 这个方法 emit: function (event) {
> > var type = event.currentTarget.dataset.type;
> > if (this.simple) {
> > this.$emit(type, {
> > value: this.getColumnValue(0),
> > index: this.getColumnIndex(0)
> > });
> > }
> > else {
> > this.$emit(type, {
> > value: this.getValues(),
> > index: this.getIndexes()
> > });
> > }
> > },
> 
> @xumiaojun 问下你用1.6.1解决了吗？我使用1.6.1，还是报同样的错误，可以帮忙看看吗

cancel 和 confirm 的event 解决了吧。我试过了，但印象中还有其他的问题，我就马上在正式项目回滚了1.5.2
