### ISSUE TITLE
vant1.6.0 field组件label属性为空时，也占用label左侧文本空间

### ISSUE THREAD

**Issue by yik7707** [youzan/vant-weapp#3750]
> 如题：vant1.6.0 field组件label属性为空时，也占用空间。
> 1.6.0的之前的版本没问题，不写时候文本框向左对齐
麻烦开发者将新的样式变回原来

**Comment by yik7707** [comment]
max-width: 6.2em;
    min-width: 6.2em;
    margin-right: 12px;
以上片段代码出现的问题

**Comment by ytxbnahn** [comment]
遇到相同问题 影响了search组件

**Comment by Sean-Wang** [comment]
同样遇到 Search 组件 placeholder 字体向右对齐的异常，即便调用 input-align 属性。
