### ISSUE TITLE
[Bug Report] van-goods-action组件为 iPhoneX 留出底部安全距离样式错误

### ISSUE THREAD

**Issue by XSJXSJ111** [youzan/vant-weapp#3753]
### 设备
iphone12

### VantWeapp 版本
1.5.2

### 基础库版本
2.13.2

### 如果是 UI 问题，截图链接（多图回车分隔）

![截图](https://i.loli.net/2020/11/12/9TmkNZKgUxALoMI.jpg)

### 请提供核心代码片段链接
https://github.com/youzan/vant-weapp/blob/dev/dist/goods-action/index.wxss

### 描述问题
van-goods-action组件设置为 iPhoneX 留出底部安全距离样式属性safe-area-inset-bottom时，会出现内部内容溢出组件的问题，经查述组件内部设置了padding-bottom: env(safe-area-inset-bottom);css属性而组件高度height为固定的50px以至于在iPhone X系列手机导致溢出问题

**Comment by rex-zsd** [comment]
默认情况下 `box-sizing` 的默认值应该是 `content-box`，可能是部分机型的问题或是外部样式覆盖了。
下版本将增加显式声明哈。
