### ISSUE TITLE
[Bug Report] Tab 标签页组件想在tab中显示换行的两条数据，应该怎么实现？数据都是动态获取的

### ISSUE THREAD

**Issue by forget1** [youzan/vant-weapp#3757]
### VantWeapp 版本
1.5.1

### 基础库版本
2.14.0

### 请提供核心代码片段链接
https://gist.github.com/forget1/1aa08d57fc690267ce443a0f112a2721

### 描述问题
假如返回数据是```name /n desc```这种，正常放在tab里的话是显示为一行的，我想让这个数据显示为两行的话，现在应该怎么弄...是修改tab-class吗？谢谢

**Comment by rex-zsd** [comment]
由于小程序的机制，vant weapp 的 tab 目前无法提供 title 的slot，只有通过样式处理一种方法。
传入的 `title` 中带上换行符 `\n`
再通过 `tab-class` 设置样式使换行符生效，比如
```css
white-space: pre-line;
```
