### ISSUE TITLE
[Bug Report] 我想问问Field 输入框只数据数字根本没用，但是PC演示那里正常，想干嘛？

### ISSUE THREAD

**Issue by evanwu66** [youzan/vant-weapp#3758]
### 设备
chrome

### VantWeapp 版本
1.6.1

### 基础库版本
2.13.2

### 请提供核心代码片段链接
https://doc.mini.talelin.com/component/form/input.html

### 描述问题
Field 输入框，明明在小程序就无效，在PC那里的demo硬是搞出来误导用户，几个意思？

**Comment by NNorLand** [comment]
我感觉PCdemo这里是iframe套的移动端的demo，这块展示不了小程序的语法，想看真正支持的小程序demo，需要自己扫码小程序看。小程序上是不支持的。。

**Comment by rex-zsd** [comment]
真实案例请使用微信扫码体验。文档网站上的demo是用vant实现，仅供示意。

**Comment by rex-zsd** [comment]
贴的代码链接是linui的，跟vant weapp无关？
