### ISSUE TITLE
datetimepicker组件，安卓曲面屏快速滑动选择时间后，会自己跳动

### ISSUE THREAD

**Issue by ZzZzZzMy** [youzan/vant-weapp#3759]
datetimepicker组件，安卓曲面屏快速滑动选择时间后，会自己跳动，去掉绑定value，和bind:input后就没问题

http://vant-contrib.gitee.io/vant-issue-generater?repo=VantWeapp

**Comment by smrsmr** [comment]
vantWebapp 1.5.2
小米 9
微信版本 7.0.20
也出现这种情况

**Comment by inputherf** [comment]
小米10也这个问题，

**Comment by anming-john** [comment]
我也遇到这个问题， 解决了吗 现在这个还有人维护吗

**Comment by ZzZzZzMy** [comment]
没解决，最后我换成微信自己官方的选择时间组件了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "youzan/vant-weapp"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月11日(星期五) 下午3:13
收件人:&nbsp;"youzan/vant-weapp"<vant-weapp@noreply.github.com&gt;;
抄送:&nbsp;"1041951643"<1041951643@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [youzan/vant-weapp] datetimepicker组件，安卓曲面屏快速滑动选择时间后，会自己跳动 (#3759)





 
我也遇到这个问题， 解决了吗 现在这个还有人维护吗

**Comment by landluck** [comment]
https://github.com/youzan/vant-weapp/issues/3206
