### ISSUE TITLE
日历组件没有横向滑动吗，现在都是直接平铺，但是会展示好多个，希望可以加一下日历横向滑动

### ISSUE THREAD

**Issue by AHAyayaya** [youzan/vant-weapp#3761]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater?repo=VantWeapp

**Comment by rex-zsd** [comment]
目前日历组件是纵向滑动的交互，横向滑动暂时应该不会支持哈。
