### ISSUE TITLE
1.6.1版本的Area组件不展示区了，只展示省和市

### ISSUE THREAD

**Issue by githubzyl** [youzan/vant-weapp#3762]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater?repo=VantWeapp

**Comment by rex-zsd** [comment]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater?repo=VantWeapp

**Comment by lihui994399414** [comment]
遇到了同样的问题，请问怎么处理的呢
