### ISSUE TITLE
vant的cell组件，建议右侧内容添加可以局左居中居右的

### ISSUE THREAD

**Issue by 1020431880** [youzan/vant-weapp#3763]
vant的cell组件，建议右侧内容添加可以局左居中居右的，很多情况下一个表单的右侧是包含输入框，复选框，或者直接文案显示，这种都是需要局左的，而现在的想满足的话要么改样式，要么自定义，或者slot，并不能直接设置，如果右侧的文字能直接通过属性设置水平位置就好了

**Comment by rex-zsd** [comment]
还是可以通过外部样式类自定义一下的哈，考虑了一下目前暂时不想为这个增加一个属性
