### ISSUE TITLE
希望在wx.chooseMedia的时候添加mediaType 属性

### ISSUE THREAD

**Issue by liuchuancong** [youzan/vant-weapp#3765]
```
case 'media':
      return new Promise((resolve, reject) => {
        wx.chooseMedia({
          count: multiple ? Math.min(maxCount, 9) : 1,
          mediaType: mediaType, //<--
          sourceType: capture,
          maxDuration,
          sizeType,
          camera,
          success: resolve,
          fail: reject,
        });
      });
```
这样就可以只选['video'],解决chooseVideo 拿不到 file.thumbTempFilePath

**Comment by liuchuancong** [comment]
组件van-uploader

**Comment by rex-zsd** [comment]
虽然微信官方文档上没有写，但是 `wx.chooseVideo` 是会返回 `thumbTempFilePath ` 的，可以在 `thumb` 字段中获取到哈。
![image](https://user-images.githubusercontent.com/8767877/99942674-05821200-2dab-11eb-9ca6-5710f7272cd4.png)

**Comment by rex-zsd** [comment]
所以 `mediaType` 不需要手动指定的哈，希望上传视频的时候直接指定 `accept` 为 `video` 就好了。

**Comment by liuchuancong** [comment]
微信官方的bug  在使用 wx.chooseVideo 开发工具会返回thumbTempFilePath 字段，而在真机上是没有的，测试发现只有wx.chooseMedia时会返回这个字段
