### ISSUE TITLE
最新的npm包中picker下的index.js少了emit方法

### ISSUE THREAD

**Issue by Kalo-c** [youzan/vant-weapp#3766]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater?repo=VantWeapp

**Comment by rex-zsd** [comment]
可升级 1.6.1 版本，已修复 `emit` 不存在的问题

**Comment by Kalo-c** [comment]
我从1.4.4版本中拿到了这个方法...0.0...

**Comment by rex-zsd** [comment]
啊这，版本差距略大

**Comment by Kalo-c** [comment]
方法是一样的
