### ISSUE TITLE
notice-bar会出现文字显示不全及全部消失的问题

### ISSUE THREAD

**Issue by AFAP** [youzan/vant-weapp#3768]
notice-bar在显示100多个字的时候会显示不全，具体能显示出来多少个没有一个定数，不同的手机有不同的表现……
另外就是在第一个页面显示跑马灯的时候，打开第二个页面，再返回，有概率出现跑马灯能容全部不显示的情况

**Comment by rex-zsd** [comment]
提供的信息太少了，没办法查问题，按照模板重新提下 issue 哈。

你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater?repo=VantWeapp

**Comment by ThomasWang2014** [comment]
有解决吗？Android手机上遇到同样问题，iOS手机正常
