### ISSUE TITLE
van-dialog 使用API调用Dialog.stopLoading()后继续点击确认不执行函数

### ISSUE THREAD

**Issue by hqy1204** [youzan/vant-weapp#3769]
## vant 版本
1.6.1

# 环境
微信开发工具 Stable  1.0.3

## 复现步骤

1. 微信代码片段 https://developers.weixin.qq.com/s/kbGcsZma77ly
2. 点击打开dialog
3. 点击确认后，执行stopLoading()后再次点击确认。
4. 效果:再次点击后并没有stopLoading();

**Comment by rex-zsd** [comment]
实际上，这是因为 `Promise` 仅会触发一次状态变更，即 `then` 中的逻辑只会执行一次。

**Comment by rex-zsd** [comment]
通过事件可以绕开这个问题，我们将在考虑之后决定这里是否要修改，或者不处理仅增加文档提示。

**Comment by rex-zsd** [comment]
下版本将增加新的属性 `before-close` 用来处理异步关闭，旧的 `async-close` 不推荐使用了哈。
