### ISSUE TITLE
DatetimePicker组件怎么控制'支持可选择时间区域限制'

### ISSUE THREAD

**Issue by stupidWall** [youzan/vant-weapp#377]
### 请认真写 ISSUE 的标题，会用于生成 change log。

**请确认是需要 *新增功能* 还是 *提交bug* **

** 如果是 bug，请提供复现步骤，可能的话，可以在 [https://jsfiddle.net](https://jsfiddle.net) 或者类似平台上提供一个 demo **

**Comment by stupidWall** [comment]
add content

**Comment by stupidWall** [comment]
过去的年份，怎么控制没得选择

**Comment by rex-zsd** [comment]
目前暂不支持选择时间限制

**Comment by chenjiahan** [comment]
目前 zanui-weapp 已进行全新的品牌升级，更名为 Vant Weapp，组件和 API 都有较大的变化。

对 zanui-weapp 的讨论，请移步至 https://github.com/youzan/zanui-weapp 仓库
