### ISSUE TITLE
npm run dev构建失败

### ISSUE THREAD

**Issue by chengkaii** [youzan/vant-weapp#3770]
![image](https://user-images.githubusercontent.com/10311041/99768482-ca2fdb00-2b3f-11eb-9595-1aa23c171907.png)

**Comment by rex-zsd** [comment]
看下是否是 node_modules 依赖安装的问题，报错的是 weapp-serve 依赖的 koa 库，跟 vant weapp 没什么关系。

**Comment by chengkaii** [comment]
> 看下是否是 node_modules 依赖安装的问题，报错的是 weapp-serve 依赖的 koa 库，跟 vant weapp 没什么关系。

依赖不是npm install自动安装的么，这个应该用不着手动设置什么吧
