### ISSUE TITLE
van-popup 里面嵌套微信的textarea 在安卓上无法设置字体大小

### ISSUE THREAD

**Issue by chenzhao951012** [youzan/vant-weapp#3771]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater?repo=VantWeapp

**Comment by rex-zsd** [comment]
看不明白是什么问题，按模板重新提个 issue 哈

你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater?repo=VantWeapp
