### ISSUE TITLE
[Bug Report] indexbar 索引栏动态渲染之后出错

### ISSUE THREAD

**Issue by djh-djh** [youzan/vant-weapp#3773]
### 设备
微信开发者工具

### VantWeapp 版本
1.6.1

### 基础库版本
2.14.0

### 请提供核心代码片段链接
https://github.com/djh-djh/WX-Want/blob/master/dhpw/pages/address_list/address_list.wxml

### 描述问题
微信小程序使用vant weapp 的indexBar索引栏 动态渲染时出错

**Comment by chaserzz** [comment]
请问你是什么错误，我的结构和你一样，IndexBar无法滚动。如果给外面包裹scroll-view则右侧索引栏点击无效

**Comment by landluck** [comment]
可以尝试下最新版本是否有问题，如还有问题可以重新提交 issue 提供小程序代码片段协助排查
