### ISSUE TITLE
[Bug Report] 子组件内调用popup无法遮罩父组件

### ISSUE THREAD

**Issue by xiaoshangmin** [youzan/vant-weapp#3774]
### 设备
iPhone7

### VantWeapp 版本
1.6.1

### 基础库版本
2.10.3

### 如果是 UI 问题，截图链接（多图回车分隔）

![截图](https://i.loli.net/2020/11/23/wNBYKPs3bxcugeW.jpg)

### 描述问题
子组件内调用popup无法遮罩父组件的Tab 标签页

**Comment by Qzhor** [comment]
![image](https://user-images.githubusercontent.com/19885698/99924705-46abff00-2d76-11eb-9b37-df4536322742.png)
the same, huawei p10

**Comment by rex-zsd** [comment]
![popup](https://user-images.githubusercontent.com/8767877/101019676-472f6b80-35a8-11eb-9892-e2d01ff76ced.gif)
demo 小程序中未复现问题，因为没有提供代码片段，无法进一步排查问题
可以检查一下是否是本地样式覆盖导致的哈

**Comment by yingzhiji** [comment]
我也遇到了，只有 ios 才会有这个问题

**Comment by a20086115** [comment]
我也遇到了，只有 ios 才会有这个问题 @rex-zsd

**Comment by jiyingzhi** [comment]
@a20086115 调试了一下，这个是 iOS 自己的问题，在子组件内 fixed 定位是相对于根元素的，不是 page，暂时解决办法是把 popup 这类组件提升到页面组件中
