### ISSUE TITLE
[Bug Report] 安卓上面van-popup里面嵌套textarea 无法设置placeholder字体大小

### ISSUE THREAD

**Issue by chenzhao951012** [youzan/vant-weapp#3776]
### 设备
安卓机

### VantWeapp 版本
1.6.1

### 基础库版本
1.6.1

### 如果是 UI 问题，截图链接（多图回车分隔）

![截图](https://sm.ms/image/hS2yXHdjOgotvL8)

### 请提供核心代码片段链接
https://gist.github.com/chenzhao951012/d8a8eed9b192b05531d6ae04380a8a29

### 描述问题
安卓上面van-popup里面嵌套textarea 无法设置placeholder字体大小  value值可以修改大小

**Comment by rex-zsd** [comment]
图没传上来，挂了。试了一下 mate30 没复现。
确认下不嵌套在 van-popup 内时，textarea 设置 placeholder 的 `font-size` 有效么？
看起来不太像是组件库的问题呢。

**Comment by chenzhao951012** [comment]
你好,如果不嵌套的话是可以的------------------&nbsp;原始邮件&nbsp;------------------
















发件人:                                                                                                                        "youzan/vant-weapp"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月23日(星期一) 下午5:54
收件人:&nbsp;"youzan/vant-weapp"<vant-weapp@noreply.github.com&gt;;
抄送:&nbsp;"缪海槐"<787251775@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [youzan/vant-weapp] [Bug Report] 安卓上面van-popup里面嵌套textarea 无法设置placeholder字体大小 (#3776)





 
图没传上来，挂了。试了一下 mate30 没复现。
 确认下不嵌套在 van-popup 内时，textarea 设置 placeholder 的 font-size 有效么？
 看起来不太像是组件库的问题呢。

**Comment by rex-zsd** [comment]
从开发者工具传个代码片段上来看看吧

**Comment by chenzhao951012** [comment]
https://developers.weixin.qq.com/s/qDf0I6mi7ymF 你好代码片段连接




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "youzan/vant-weapp"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月23日(星期一) 晚上7:35
收件人:&nbsp;"youzan/vant-weapp"<vant-weapp@noreply.github.com&gt;;
抄送:&nbsp;"缪海槐"<787251775@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [youzan/vant-weapp] [Bug Report] 安卓上面van-popup里面嵌套textarea 无法设置placeholder字体大小 (#3776)





 
从开发者工具传个代码片段上来看看吧

**Comment by chenzhao951012** [comment]
https://developers.weixin.qq.com/s/ihf&nbsp; 你好用这个




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "youzan/vant-weapp"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月23日(星期一) 晚上7:35
收件人:&nbsp;"youzan/vant-weapp"<vant-weapp@noreply.github.com&gt;;
抄送:&nbsp;"缪海槐"<787251775@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [youzan/vant-weapp] [Bug Report] 安卓上面van-popup里面嵌套textarea 无法设置placeholder字体大小 (#3776)





 
从开发者工具传个代码片段上来看看吧

**Comment by rex-zsd** [comment]
这个场景确实可以复现，推测是 popup 组件带入场动画，使得原生组件 textarea 的 placeholder 渲染有问题。
目前组件无法兼容处理这个问题。

**Comment by rex-zsd** [comment]
一个可行的方法是延迟 textarea 的渲染，在 `after-enter` 事件触发后再显示 textarea 组件。

具体代码可以查看代码片段 https://developers.weixin.qq.com/s/T8aYs9mZ75mY。
