### ISSUE TITLE
[Feature Request] uploader 组件添加 loading 状态

### ISSUE THREAD

**Issue by axetroy** [youzan/vant-weapp#3779]
### 这个功能解决了什么问题
这个 loading 是组件级别的，而不是全局的 loading。

主要是有些上传很慢的时候，等待太久，体验非常不好，有个 loading 起码知道在上传

### 建议的API是什么样的
<van-uploader :loading="true"/>

**Comment by rex-zsd** [comment]
上传逻辑是由开发者自行完成的，组件内不包含。
需要全局 loading 自行使用 `van-toast` 组件或 `wx.showLoading` API 即可，不需要 uploader 组件的支持。
