### ISSUE TITLE
[Feature Request] 单选框复选框label建议margin-left改成padding-left，建议再加一个inline模式

### ISSUE THREAD

**Issue by diyializhen** [youzan/vant-weapp#3780]
### 这个功能解决了什么问题
比如我需要选择男女时，内容很少，希望该单选框两个选项只占一行。现在margin-left的空隙点击无法触发，而通过样式改成一行，且文字较少时，如 ○   男  ○   女 这个空隙就相对影响较大，很容易点到无法触发值的改变

### 建议的API是什么样的
对应的group组件上添加一个inline属性

**Comment by rex-zsd** [comment]
复选框横排有点奇怪。
单选框组将在下版本增加 `direction` 支持水平排列。
