### ISSUE TITLE
swipe-cell的高度问题

### ISSUE THREAD

**Issue by BryantKawhi** [youzan/vant-weapp#3782]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater?repo=VantWeapp

swipe-cell的高度如何随着内容高度伸缩呢？只能写死一个高度吗

**Comment by rex-zsd** [comment]
swipe-cell 不会影响 left、right 和默认 slot 的高度。
只需要为 left 和 right 设置固定宽度即可哈。
