### ISSUE TITLE
[Bug Report] picker组件，取消、确认按钮报错，内部js没有定义emit方法

### ISSUE THREAD

**Issue by zhangjunlin6666** [youzan/vant-weapp#3784]
### 设备
所有

### VantWeapp 版本
1.6.1

### 基础库版本
2.14.0

### 请提供核心代码片段链接
https://github.com/youzan/vant-weapp/blob/dev/packages/picker/toolbar.wxml

### 描述问题
使用popup套用picker组件时，点击取消、确认按钮报错Component "miniprogram_npm/@vant/weapp/picker/index" does not have a method "emit" to handle event "tap"，翻看源码发现，没有定义emit方法，望修复！

**Comment by rex-zsd** [comment]
1.6.1 已修复了，升级版本即可。

**Comment by emptyO** [comment]
v1.6.4同样问题

**Comment by emptyO** [comment]
v.1.6.4抛出同样错误，求解

**Comment by rex-zsd** [comment]
@emptyO 上传下代码片段哈

**Comment by zhangjunlin6666** [comment]
@emptyO 你把node_modules以及编译后的小程序node包删掉，完了重新npm i，重新编译
