### ISSUE TITLE
uni转H5后的时候运行报错 version.js:3 Uncaught TypeError: Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by zhangchangwei** [youzan/vant-weapp#3785]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater?repo=VantWeapp

请问是怎么回事呢，是否支持H5呢

![image](https://user-images.githubusercontent.com/7691964/100220416-4ec09600-2f52-11eb-94e3-4ad1c0d99409.png)

**Comment by rex-zsd** [comment]
不支持 h5 哈，仅支持微信小程序。
