### ISSUE TITLE
请问，上传组件为什么没有放开批量选择图片功能。

### ISSUE THREAD

**Issue by sijinglei** [youzan/vant-weapp#3786]
虽然前端配置了multiple属性，但是你们上传调用那里为什么没有加这个属性。
![image](https://user-images.githubusercontent.com/18141435/100241863-21ceac00-2f6f-11eb-9a79-46faec0bae37.png)
这里缺少一个可以多选的配置，还希望早日优化！！

**Comment by rex-zsd** [comment]
没看懂什么意思，`count` 就是多选状态时的可选张数呀。
可以看下[微信文档](https://developers.weixin.qq.com/miniprogram/dev/api/media/image/wx.chooseImage.html)
不知道你写的”这个属性“是什么属性
