### ISSUE TITLE
[Feature Request] 上传组件选择拍照时无法使用自定义拍照界面呢

### ISSUE THREAD

**Issue by nameglass** [youzan/vant-weapp#3787]
### 这个功能解决了什么问题
选择拍照时能自定义相机拍照

### 建议的API是什么样的
开发一个可以调用自定义拍照界面的函数

**Comment by rex-zsd** [comment]
上传组件不支持相机自定义拍照呢。
有这种需求可以参照[微信官方文档](https://developers.weixin.qq.com/miniprogram/dev/component/camera.html)自行实现的哈。
