### ISSUE TITLE
[Bug Report] Calendar 下滑 最多下滑六个月

### ISSUE THREAD

**Issue by xstxhjh** [youzan/vant-weapp#3788]
### 设备
微信开发者工具

### VantWeapp 版本
1.6.1

### 基础库版本
1.5.0

### 请提供核心代码片段链接
https://github.com/xstxhjh

### 描述问题
Calendar 下滑 最多下滑六个月，即便范围超过180也没有用

**Comment by rex-zsd** [comment]
![calendar](https://user-images.githubusercontent.com/8767877/101019119-71ccf480-35a7-11eb-95ae-9de4e1da17e1.gif)
给 demo 小程序设置了 2 年的跨度，并没有发现问题。
请检查一下设置的范围是否有问题哈。
