### ISSUE TITLE
[Feature Request] Uploader 文件上传 删除icon 自持自定义大小

### ISSUE THREAD

**Issue by xueyan1** [youzan/vant-weapp#3789]
### 这个功能解决了什么问题
1.当上传图片只有一张，而图片很大的时候，删除按钮会太小。无法点击

### 建议的API是什么样的
    iconSize: {
          type: String,
          value: '16px',
        },

**Comment by rex-zsd** [comment]
下版本将能够是用 CSS 变量 `--uploader-delete-icon-size` 控制删除图标的大小。
是用姿势可见 [文档](https://youzan.github.io/vant-weapp/#/theme)
