### ISSUE TITLE
*新增功能*checkbox如果能支持选中颜色的配置就更好了

### ISSUE THREAD

**Issue by qwelao7** [youzan/vant-weapp#379]
### 请认真写 ISSUE 的标题，会用于生成 change log。

**请确认是需要 *新增功能* 还是 *提交bug* **

**Comment by chenjiahan** [comment]
目前 zanui-weapp 已进行全新的品牌升级，更名为 Vant Weapp，组件和 API 都有较大的变化。

对 zanui-weapp 的讨论，请移步至 https://github.com/youzan/zanui-weapp 仓库
