### ISSUE TITLE
ImagePreview 组件没有

### ISSUE THREAD

**Issue by Master-gg-02** [youzan/vant-weapp#3790]
ImagePreview 组件可以增加上吗，uploader有预览的功能，可以拆分出来吗

**Comment by Master-gg-02** [comment]
小程序有 wx.ImagePreview 这个api可以直接使用

**Comment by rex-zsd** [comment]
直接调用原生的 `wx.previewImage` API就可以啦，不需要 vant weapp 单独提供预览组件的哈。
