### ISSUE TITLE
[Bug Report] 选择完整时间类型时显示异常

### ISSUE THREAD

**Issue by mawei75** [youzan/vant-weapp#3793]
### 设备
开发者工具

### VantWeapp 版本
1.6.2

### 基础库版本
2.8.2

### 如果是 UI 问题，截图链接（多图回车分隔）

![截图](https://i.loli.net/2020/11/30/rHMmo5xb9XOTkzR.png)

![截图](https://i.loli.net/2020/11/30/z79QB1VoYU8SEPJ.png)

![截图](https://i.loli.net/2020/11/30/gcm6n3irPlydbU5.png)

### 请提供核心代码片段链接
https://gist.github.com/mawei75/6a12bb56c727e0235e9194686aa1a964

### 描述问题
年选择列没有显示，其他列无法选择

**Comment by rex-zsd** [comment]
`maxDate` 比 `minDate` 还小，这时候是不会有可选项的哈。
