### ISSUE TITLE
[Bug Report] van-uploader 使用 accept="media" ios真机点击无效，在开发者工具中没有问题

### ISSUE THREAD

**Issue by MisterBowie** [youzan/vant-weapp#3794]
### 设备
apple 8

### VantWeapp 版本
1.6.2

### 基础库版本
2.14.0

### 请提供核心代码片段链接
https://gist.github.com/MisterBowie/9eac712dc88682b71a0d9101eb8ed26a

### 描述问题
van-uploader 使用 accept="media" ios真机点击无效，在开发者工具中没有问题

**Comment by rex-zsd** [comment]
设备是 ios 8? 确定是基础库是2.14.0.么？

**Comment by MisterBowie** [comment]
![image](https://user-images.githubusercontent.com/22372554/100585901-44731300-3329-11eb-8cd2-baed0e556965.png)
是的

**Comment by MisterBowie** [comment]
设备是苹果8  系统是13.5.1

**Comment by rex-zsd** [comment]
额，不是开发者工具的基础库，而是设备上的微信的基础库版本。
微信只支持基础库 2.10.0 以上调用 [`wx.chooseMedia`](https://developers.weixin.qq.com/miniprogram/dev/api/media/video/wx.chooseMedia.html)

**Comment by MisterBowie** [comment]
![image](https://user-images.githubusercontent.com/22372554/100592539-3249a280-3332-11eb-8db5-b5f2b7689ddf.png)
我的版本是2.10.4，

**Comment by rex-zsd** [comment]
vant weapp 这边只是简单调用微信的 API，并没有什么预处理。
推测是微信侧的问题，可以试试直接调用 `wx.chooseMedia`，看看是否也有问题

**Comment by MisterBowie** [comment]
好的
