### ISSUE TITLE
van-dialog 自定义时图片绝对定位，超出部分不见了

### ISSUE THREAD

**Issue by coder-liulin** [youzan/vant-weapp#3796]
在自定义弹出框时，使用绝对定位，里面设置的图片超出部分部件了

你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater?repo=VantWeapp

![image](https://user-images.githubusercontent.com/35750509/100611903-07b91300-334d-11eb-87e0-10f6413ad916.png)

代码如下：
``
<van-dialog use-slot 
class-name="daiya_dialog" 
show="{{ show }}" 
show-confirm-button="{{false}}" 
custom-style="width: 477rpx;">
<cover-view class="custom_dialog">
    <cover-image src="../../assets/images/tip.png" class="tip_image" />
  </cover-view>
</van-dialog>
``

**Comment by rex-zsd** [comment]
弹窗设置了 `overflow: hidden` 超出部分会隐藏的

**Comment by coder-liulin** [comment]
谢谢
