### ISSUE TITLE
van-tabs需求

### ISSUE THREAD

**Issue by BryantKawhi** [youzan/vant-weapp#3798]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater?repo=VantWeapp
van-tabs能不能支持一下每一个tab的自定义，以便实现类似这种的需求
![图片](https://user-images.githubusercontent.com/29621842/100704600-b9555400-33e0-11eb-9a89-e1c55af057d4.png)

**Comment by rex-zsd** [comment]
由于小程序的机制限制，DOM 是无法移动的，所以这个需求无法实现。
