### ISSUE TITLE
[Bug Report] van-uploader 上传组件返回值修改了？

### ISSUE THREAD

**Issue by pushuo** [youzan/vant-weapp#3800]
### 设备
ios

### VantWeapp 版本
1.6.2

### 基础库版本
2.12.0

### 请提供核心代码片段链接
https://youzan.github.io/vant-weapp/#/uploader#yin-ru

### 描述问题
van-uploader 上传组件返回值已经变化，请检查。
<a href="https://sm.ms/image/DeOsgIoBEpm2wVA" target="_blank"><img src="https://i.loli.net/2020/12/01/DeOsgIoBEpm2wVA.png" ></a>

**Comment by rex-zsd** [comment]
demo 中视频和图片都没有问题，请检查你的组件库版本哈。

**Comment by hyfdemo** [comment]
我服了!上线版本就出在这个问题上,你们把file.path改成file.url能写在升级日志里吗???

**Comment by cole1993** [comment]
> 我服了!上线版本就出在这个问题上,你们把file.path改成file.url能写在升级日志里吗???

升级了组件发现上传不行了，原来如此..
