### ISSUE TITLE
[Feature Request] Field组件 Right-icode 能否加强成可以自定义的

### ISSUE THREAD

**Issue by echokh** [youzan/vant-weapp#3801]
### 这个功能解决了什么问题
可以自定义右侧的图表，灵活度更高

### 建议的API是什么样的
Field 添加右侧自定义组件

**Comment by rex-zsd** [comment]
`right-icon` 本就支持自定义插槽，请看 [文档](https://youzan.github.io/vant-weapp/#/field#slot) 哈

**Comment by echokh** [comment]
> `right-icon` 本就支持自定义插槽，请看 [文档](https://youzan.github.io/vant-weapp/#/field#slot) 哈

您可能没理解我的意思哈，简单来说我能不能把right换成文字，我目前的业务场景是这样的：label标题需要带单位导致太长影响美观，所以我想能不能在右侧换成文字，可能会好一些

**Comment by rex-zsd** [comment]
插槽内可以放置任意的元素，文字当然可以。
不了解的话可以看微信的[官方文档](https://developers.weixin.qq.com/miniprogram/dev/framework/custom-component/wxml-wxss.html#%E7%BB%84%E4%BB%B6-wxml-%E7%9A%84-slot)哈。

**Comment by echokh** [comment]
> 插槽内可以放置任意的元素，文字当然可以。
> 不了解的话可以看微信的[官方文档](https://developers.weixin.qq.com/miniprogram/dev/framework/custom-component/wxml-wxss.html#%E7%BB%84%E4%BB%B6-wxml-%E7%9A%84-slot)哈。

感谢耐心解答，我研究一下
