### ISSUE TITLE
当tabs不被放在顶部时，向后切换标签卡会导致页面被挤下去

### ISSUE THREAD

**Issue by WSAIK** [youzan/vant-weapp#3803]
库：VanWeapp
类型：bug
设备：ios14.2
VantWeapp 版本：1.6.2
基础库版本：2.11.1
截图链接：https://sm.ms/image/B1INcOgpVqj5DhZ
描述：当tabs不被放在顶部时，向后切换标签卡会导致页面被挤下去，需要重新向上滑出页面
![tabs_bug](https://user-images.githubusercontent.com/35627043/100841425-3c92aa80-34b2-11eb-9c9f-6d58fc80ed42.gif)

**Comment by rex-zsd** [comment]
切换时瞬间底部没有内容导致页面自动顶上去，组件库是无法解决的。
可以开启 `animated `，使 content 部分始终有内容渲染。

**Comment by WSAIK** [comment]
谢答，尝试加入animated无效（没有进行其它测试了，不确定是否为我这边的问题）；向前切换正常，只有向后切换会出现此情况。目前已通过设置min-height解决

**Comment by rex-zsd** [comment]
好的哈，这个问题目前组件库这边确实是没办法处理。
小程序不像 h5，逻辑与渲染之间是存在一定延迟的，在从前一个 tab 切换到后一个的时候，会有一瞬间 content 部分没有内容，
页面高度不够的话就会自动顶上去了。
目前看给页面增加 `min-height` 的确是最后的办法了。
