### ISSUE TITLE
[Bug Report] 自定义组件，使用外部样式，会加上组件的名称

### ISSUE THREAD

**Issue by Sun-Target** [youzan/vant-weapp#3804]
### 设备
mac pro

### VantWeapp 版本
1.6.2

### 基础库版本
1.6.2

### 请提供核心代码片段链接
https://gitee.com/sunrifa_tf/lines-planning.git

### 描述问题
自定义组件，使用外部样式，会加上组件的名称，会在外部样式前面加上组件名称，例如（.sd-green-plainbtn -> .serviceblock--sd-green-plainbtn），加上了serviceblock，导致外部样式失效
https://sm.ms/image/OEZSd9kKpXJa6eF

**Comment by rex-zsd** [comment]
这是微信小程序本身的机制，会为 class 加上前缀，不影响 class 的行为的。
使用外部样式类请注意加上 `!important` 否则相同样式属性很可能不生效。
