### ISSUE TITLE
van-area第二列选中了又会回弹

### ISSUE THREAD

**Issue by KuoKongQingYun** [youzan/vant-weapp#3806]
版本:1.6.2
van-area的columns-num设置为2
但是不管选择第二列的哪一个选项，都会弹回第一个。
我搜索issues发现以前1.4.0的时候有这个BUG，但是我用的是1.6.2，怎么还是有这个BUG呢？

**Comment by rex-zsd** [comment]
![output](https://user-images.githubusercontent.com/8767877/101017387-fa966100-35a4-11eb-8665-d34ad082b425.gif)
demo 上没有复现呢，请检查一下使用的版本哈

**Comment by KuoKongQingYun** [comment]
大概知道怎么回事了，直辖市的原因，我针对直辖市没有使用占位符，
参考：http://www.mca.gov.cn/article/sj/xzqh/2020/2020/2020112010001.html

所以第二列的行政代码不是XXXX00，而是XXXX0X导致的问题，
例如110000北京市下面是110101东城区。
而van-area貌似默认约定第二列必须是XXXX00
