### ISSUE TITLE
[Bug Report] van-datetime-picker使用year-month的时候有异常

### ISSUE THREAD

**Issue by lixiaolang12000** [youzan/vant-weapp#3807]
### 设备
any

### VantWeapp 版本
1.6.2

### 基础库版本
2.14.0

### 请提供核心代码片段链接
https://gist.github.com/lixiaolang12000/8a828507926b267552ee734fb95bdcf7

### 描述问题
当van-datetime-picker的type设置成year-month的时候，代码中有bug导致异常
@vant/weapp/datetime-picker/index.js 第317行
详情请参考代码片段，有详细注解

**Comment by youhehe** [comment]
1.6.2版本在getTrueValue中增加了undefined判断，已修复这个问题，看下本地的代码库是不没有更新？

**Comment by lixiaolang12000** [comment]
确实是本地包版本不对，感谢
