### ISSUE TITLE
[Bug Report] tab标签下划线初始位置错误

### ISSUE THREAD

**Issue by WangYu007** [youzan/vant-weapp#3810]
### 设备
微信电脑客户端

### VantWeapp 版本
1.5.0

### 基础库版本
no

### 如果是 UI 问题，截图链接（多图回车分隔）

![截图](https://i.loli.net/2020/12/04/5DMHKvSGX7ypzsN.png)

### 请提供核心代码片段链接
https://gitee.com/wyloveyou/sxt-miniprogram.git

### 描述问题
van-tabs标签在微信电脑客户端预览时初始位置错误，如图所示，切换后位置正确，在手机端正常。还有下划线的长度可以跟随文字的长度吗？

**Comment by rex-zsd** [comment]
可以升级到最新版本看下，新增了 `resize` 方法，可以在动态渲染组件下换线位置不对时手动设置。
下划线的长度不可以跟随文字长度，但是可以通过 `line-width` 属性设置固定长度。

**Comment by a2774206** [comment]
> 可以升级到最新版本看下，新增了 `resize` 方法，可以在动态渲染组件下换线位置不对时手动设置。
> 下划线的长度不可以跟随文字长度，但是可以通过 `line-width` 属性设置固定长度。

1.6.3版本依旧有该 bug

**Comment by rex-zsd** [comment]
demo 目前没有这个问题，目前只能给点大致的建议，不一定符合你的场景：
在动态渲染 van-tabs 或者 tab 的个数是动态生成的时候，下划线位置是无法保证正确的。
可以手动调用 `resize` 方法重绘下划线。
这部分详见[文档]。

如果不是这个场景，还需要帮忙查原因的话，就用开发者工具传个代码片段上来哈。

**Comment by rex-zsd** [comment]
gitee 点进去是 404，所以目前只能给出上面的建议哈

**Comment by Liam6666** [comment]
resize is not a function，根本找不到这个方法
