### ISSUE TITLE
[Bug Report] Transition 初始化无作用,节点被隐藏

### ISSUE THREAD

**Issue by mikasaYw** [youzan/vant-weapp#3816]
### 设备
所有机型

### VantWeapp 版本
1.6.2

### 基础库版本
2.x

### 请提供核心代码片段链接
https://youzan.github.io/vant-weapp/#/transition

### 描述问题
Transition 页面初始化未true时无作用,且节点被隐藏
#3133 中说明重构了Transition，但是好像只是优化了动画执行时绑定的逻辑，并未对初始化不显示进行修复

**Comment by SamChangi** [comment]
你把源文件transition下index.js中transition(true) => transition(false)就OK了，setData()的缘故 @mikasaYw

**Comment by icytailu** [comment]
刚刚试了一下在不改源代码的基础上 根据上面老哥提供的信息可以先默认设置  show 为 false,然后在onLoad中setData({show:true})也可以
wxml
```html
<van-transition show="{{ show }}">
	内容
</van-transition>
```
js
```js
Page({
  data: {
    show: false,
  },
onLoad: function (options) {
    this.setData({
      show: true,
    });
  },
});

```
