### ISSUE TITLE
[bug Collapse 折叠面板  ] 组件收起展开非常缓慢 在真机上有延迟

### ISSUE THREAD

**Issue by zhaolejin** [youzan/vant-weapp#3820]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater?repo=VantWeapp

**Comment by rex-zsd** [comment]
collapse 的动画基于微信的 wx.createAnimation 实现，因为需要 `setData`，可能造成一些性能问题。
后期将使用 [关键帧动画](https://developers.weixin.qq.com/miniprogram/dev/framework/view/animation.html#%E5%85%B3%E9%94%AE%E5%B8%A7%E5%8A%A8%E7%94%BB) 实现新的动画效果。

**Comment by a2291249652** [comment]
请问有解决的方案吗？
