### ISSUE TITLE
[Bug Report] popup组件在pc工具上能正常显示，在手机上无法显示

### ISSUE THREAD

**Issue by kawaiiz** [youzan/vant-weapp#3828]
### 设备
iphone11 ,华为mate30

### VantWeapp 版本
1.6.2

### 基础库版本
ios 14.2 wechat7.0.18 wechatLib 2.14.1 , android wechat7.0.10.1580 wechatLib 2.10.4

### 如果是 UI 问题，截图链接（多图回车分隔）

![截图](https://i.loli.net/2020/12/09/AmqiKWhX2adZopY.jpg)

![截图](https://i.loli.net/2020/12/09/NgAKmk4cB8U92xb.jpg)

![截图](https://i.loli.net/2020/12/09/RlQWXV4FnBbUdKu.png)

### 请提供核心代码片段链接
https://developers.weixin.qq.com/s/tIPvrsmV7jmQ

### 描述问题
popup组件在pc工具上能正常显示，在手机上无法显示。
我同时引用了 button ,popup,dialog,
pc端都能出来，
手机预览则只有button能出来。

**Comment by rex-zsd** [comment]
2 个使用姿势问题

- 未在 `app.json` 中去除 `style: "v2"`，请看 [快速上手](https://youzan.github.io/vant-weapp/#/quickstart#bu-zou-er-xiu-gai-app.json)

- 嵌套内容，却未设置 `use-slot` 属性，请看 [组件文档](https://youzan.github.io/vant-weapp/#/dialog#zu-jian-diao-yong)

**Comment by kawaiiz** [comment]
> * ，

[修改后的代码片段](https://developers.weixin.qq.com/s/b3uCIum27fmG)
修改后还是不能显示。 修改处 1.app.json 中去除 style: "v2"。 2. van-dialog组件添加use-slot 属性

**Comment by kawaiiz** [comment]
> 2 个使用姿势问题
> 
> * 未在 `app.json` 中去除 `style: "v2"`，请看 [快速上手](https://youzan.github.io/vant-weapp/#/quickstart#bu-zou-er-xiu-gai-app.json)
> * 嵌套内容，却未设置 `use-slot` 属性，请看 [组件文档](https://youzan.github.io/vant-weapp/#/dialog#zu-jian-diao-yong)

当show="{{show}}"  控制show的值可以显示， 但是 如果  show="{{true}}" 这是不能显示的。

**Comment by Kuro-liu** [comment]
请问解决了么？之前的版本不存在这个问题

**Comment by quyuan-fore** [comment]
遇到同样的问题，已解决，提供一下我的解决方法：
如果基于 popup 的组件，如actionsheet 等（包括popup），show的初始值设置为true（包括 wxml中 “{{true}}” 或 js中对应值设为true），则在真机无法显示，猜测是mounted之类的时序问题

简单说就是show的初始值不要设置为true

**Comment by Kuro-liu** [comment]
data里show的初始设置为false，onload里设置成ture，真机测试有效
