### ISSUE TITLE
小程序文档网站挂了

### ISSUE THREAD

**Issue by webxiaoma** [youzan/vant-weapp#3829]
访问时间：2020-12-9 14:51:40
网站地址：https://vant-contrib.gitee.io/vant-weapp

网站挂了

**Comment by ChangeZhang** [comment]
@rex-zsd

**Comment by AdolphGithub** [comment]
访问时间：2020-12-9 15:11:40
网站地址：https://vant-contrib.gitee.io/vant-weapp

网站挂了

**Comment by chenjiahan** [comment]
已恢复
