### ISSUE TITLE
控制台出现 this.$options is not function 

### ISSUE THREAD

**Issue by KenNaNa** [youzan/vant-weapp#3830]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater?repo=VantWeapp

错误：

![image](https://user-images.githubusercontent.com/39817783/101598140-ac64e000-3a32-11eb-8f50-2230dbcf54c5.png)

错误定位：

![image](https://user-images.githubusercontent.com/39817783/101598194-c0104680-3a32-11eb-84f3-3349d5ef3734.png)

解决：

![image](https://user-images.githubusercontent.com/39817783/101598368-049be200-3a33-11eb-9b1f-a36202db0621.png)

**Comment by rex-zsd** [comment]
这里是 vant weapp，提错 issue 了哈
