### ISSUE TITLE
[Bug Report] picker组件不显示

### ISSUE THREAD

**Issue by 44326334** [youzan/vant-weapp#3832]
### 设备
微信开发工具

### VantWeapp 版本
1.6.3

### 基础库版本
2.14.1

### 请提供核心代码片段链接
https://developers.weixin.qq.com/s/yJT5hsmb7dmW

### 描述问题
配合popup使用picker，但picker组件没有显示

![image](https://user-images.githubusercontent.com/16300548/101600004-ade3d780-3a35-11eb-80bf-f967dc872679.png)

**Comment by kawaiiz** [comment]
#3828  我昨天出现popup组件不行，dialog组件也不行（dialog组件最外层就是popup）.

**Comment by rex-zsd** [comment]
使用姿势的问题

代码片段的 js 部分写的是

```js
Page({
  data: {
    data: {
      columns: ['杭州', '宁波', '温州', '嘉兴', '湖州'],
    },
    show: false,
  },
});
```

模板里却是

```html
<van-picker columns="{{ columns }}" bind:change="onChange" />
```

数据未对应，模板调整下即可

```html
<van-picker columns="{{ data.columns }}" bind:change="onChange" />
```

**Comment by 44326334** [comment]
修改了， 报Cannot read property 'then' of undefined
![image](https://user-images.githubusercontent.com/16300548/101738746-91ad6c80-3b01-11eb-9e1b-b8546890909b.png)
@rex-zsd
