### ISSUE TITLE
[Bug Report] Tab标签页下划线不显示

### ISSUE THREAD

**Issue by thisbing** [youzan/vant-weapp#3834]
### 设备
Samsung S9 

### VantWeapp 版本
1.6.2

### 基础库版本
2.10.4

### 如果是 UI 问题，截图链接（多图回车分隔）

![20201210-164936.jpg](https://i.loli.net/2020/12/10/v4oGmSEUxOdJhzL.jpg)
![20201211-085603.jpg](https://i.loli.net/2020/12/11/W1PB7vR8OXadtCY.jpg)

### 请提供核心代码片段链接
https://vant-contrib.gitee.io/vant-weapp/#/tab

### 描述问题
在 Vant-Weapp 官网扫码打开演示程序，发现 Tab 标签页的下划线没有显示（点击切换内容变了但下换线还是没有显示），另外一种为 ”card“ 的样式风格可以正常显示。
手机系统为： Android 10 
微信版本为：7.0.10

**Comment by rex-zsd** [comment]
三星测试机暂时不太好找

**Comment by rex-zsd** [comment]
测试了我们这边唯一一个三星测试机，是无异常的……恐怕很难复现了
Galaxy S9+ 
One UI 2.1
Android 10
微信 7.0.21
