### ISSUE TITLE
能否详细说明一下tabbar使用方法？

### ISSUE THREAD

**Issue by a516117636** [youzan/vant-weapp#3835]
看不太懂文档中tabbar使用方法。小程序官方文档中的tabbar使用方法很简单，但是我看见很多人在issue中提问，都不是很明白van-tabbar如何使用。按照文档中的写法确实能写出tabbar,可是该如何切换标签页呢，能否在这里或者在文档中详细说明？另外我使用github首页中的二维码申请进入交流群很多天了，还是没有消息，能否拉我一下，感谢！

**Comment by rex-zsd** [comment]
请看文档上附的代码片段哈，有完整的使用案例
