### ISSUE TITLE
[Bug Report] 你们到底测没测试过？列表数据都没有创建

### ISSUE THREAD

**Issue by 44326334** [youzan/vant-weapp#3840]
设备
微信开发工具

VantWeapp 版本
1.6.3

基础库版本
2.14.1

请提供核心代码片段链接
https://developers.weixin.qq.com/s/hJHsYvm17qmY

![image](https://user-images.githubusercontent.com/16300548/101857691-0d132a80-3ba3-11eb-8342-bc4a38e8183c.png)

**Comment by rex-zsd** [comment]
代码片段报错跑不起来。不会使用，可以多看看文档。
如果需要人手把手帮你纠正代码错误，建议你还是别用了哈。
