### ISSUE TITLE
van-button中使用open-type="share"不起任何作用

### ISSUE THREAD

**Issue by zzhn6** [youzan/vant-weapp#3844]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater?repo=VantWeapp
![image](https://user-images.githubusercontent.com/29200763/101915521-b0465d00-3c00-11eb-88e2-39d948eef327.png)

**Comment by rex-zsd** [comment]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater?repo=VantWeapp
