### ISSUE TITLE
tabbar能否点击icon前后显示两张不同的本地icon？

### ISSUE THREAD

**Issue by a516117636** [youzan/vant-weapp#3846]
tabbar上的icon使用本地图片时，选中后只有文字变色，图标无法变色。既然这样，如何做到点击icon前后显示两张不同的图片？

**Comment by WebRookie** [comment]
> tabbar上的icon使用本地图片时，选中后只有文字变色，图标无法变色。既然这样，如何做到点击icon前后显示两张不同的图片？

你是如何在icon上引用的本地图片？

**Comment by a516117636** [comment]
> > tabbar上的icon使用本地图片时，选中后只有文字变色，图标无法变色。既然这样，如何做到点击icon前后显示两张不同的图片？
> 
> 你是如何在icon上引用的本地图片？

文档中没写可以引用本地图片，但我传入本地路径也能成功显示，只是存在以上问题。但应该可以更换图片，我这两天忙没弄这个事。

**Comment by rex-zsd** [comment]
tabbar-item 为正常与激活态提供了2个 slot，可以分别传入自定义的图标。
具体见[文档](https://youzan.github.io/vant-weapp/#/tabbar#zi-ding-yi-tu-biao)哈

**Comment by WebRookie** [comment]
> tabbar-item 为正常与激活态提供了2个 slot，可以分别传入自定义的图标。
> 具体见[文档](https://youzan.github.io/vant-weapp/#/tabbar#zi-ding-yi-t

> tabbar-item 为正常与激活态提供了2个 slot，可以分别传入自定义的图标。
> 具体见[文档](https://youzan.github.io/vant-weapp/#/tabbar#zi-ding-yi-tu-biao)哈

嗯嗯，icon引入的问题我找到了，是路径引用的问题，不能使用相对路径，必须从根路径开始
