### ISSUE TITLE
tab info 显示异常

### ISSUE THREAD

**Issue by willzha** [youzan/vant-weapp#3847]
具体描述见: 
https://github.com/youzan/vant-weapp/issues/3817

1.6.3版本还是有这个问题

**Comment by rex-zsd** [comment]
![721608109771_ pic](https://user-images.githubusercontent.com/8767877/102328083-9078b580-3fc1-11eb-9afd-afeea34b53a5.jpg)
真机测试 ok，不知道你是否是没有升级版本。
