### ISSUE TITLE
[Bug Report] 子组件使用vant-tabs，tab中内容使用slot插槽。父组件传入元素，只有第一个active的tab生效，其他tab未插入传来人元素

### ISSUE THREAD

**Issue by Tzyito** [youzan/vant-weapp#3848]
### 设备
微信开发者工具

### VantWeapp 版本
1.6.3

### 基础库版本
1.6.2

### 请提供核心代码片段链接
https://sm.ms/image/GMVIF6nD1eQfwo3

### 描述问题
tab切换后父组件传来的数据，在子组件的tab中使用slot失效，具体图片如https://sm.ms/image/GMVIF6nD1eQfwo3 和 https://sm.ms/image/MKXZDm1SJlW7fA4

**Comment by rex-zsd** [comment]
跟 vant weapp 没有关系，这是你自己的2个组件之间的 slot 传递行为
