### ISSUE TITLE
[Feature Request] vant-tabs这个组件可以提供content的slot插槽吗？

### ISSUE THREAD

**Issue by Tzyito** [youzan/vant-weapp#3849]
### 这个功能解决了什么问题
通过切换tab，渲染不同的内容。这些内容来自外部父组件写的不同的view标签。

### 建议的API是什么样的
如代码所示

### 展示一下新功能的大致用法，代码片段链接（GitHub Gist）
https://gist.github.com/Tzyito/c24dc00e1395d16886b0315f1143576a

**Comment by rex-zsd** [comment]
看起来似乎跟 vant weapp 没有什么关系，这是你自己开发的组件间的 slot 传递
