### ISSUE TITLE
小程序Tab标签页 通过名称匹配 无效，设置active为数值也无法选中，一直初始默认是第一个

### ISSUE THREAD

**Issue by xiaomiza** [youzan/vant-weapp#3850]
小程序Tab标签页 通过名称匹配 无效，设置active为数值也无法选中，一直初始默认是第一个

**Comment by qqccyv** [comment]
同样遇到这个问题 只要设置了van-tab的name标识符 van-tabs的active属性就失效了  无论设置名称还是数值(数值无效是文档说明了的)  取消设置的name标识符 就可以通过设置数值正常设置默认选中  在1.6.1版本

**Comment by hanozhang** [comment]
遇到同样问题

**Comment by rex-zsd** [comment]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater?repo=VantWeapp

**Comment by haoguangkuo** [comment]
遇到同样的问题，不设置name，赋值也没有匹配选中状态，值已经改变。1.6.4
