### ISSUE TITLE
用小程序引用vant weapp的type等所有方法都是灰色，感觉没起作用

### ISSUE THREAD

**Issue by xfaxb** [youzan/vant-weapp#3851]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater?repo=VantWeapp

不明所以，特来求助

**Comment by rex-zsd** [comment]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater?repo=VantWeapp
