### ISSUE TITLE
van-grid组件动态加载数据样式问题，怎么解决

### ISSUE THREAD

**Issue by Hands6898** [youzan/vant-weapp#3852]
![微信图片_20201214214232](https://user-images.githubusercontent.com/65145253/102091302-9e132b80-3e59-11eb-95e8-d3671516c5a6.png)
![微信图片_20201214214240](https://user-images.githubusercontent.com/65145253/102091313-a3707600-3e59-11eb-8331-4d64274f51f3.png)

你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater?repo=VantWeapp

**Comment by rex-zsd** [comment]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater?repo=VantWeapp

**Comment by rex-zsd** [comment]
未提供代码片段，不知道你是如何使用的，没办法查了。
只能大概给点建议，可以试试使所有块的高度保持一致。

**Comment by jintou111** [comment]
也遇到了这个问题
