### ISSUE TITLE
结合echars使用时,日历会置于图表底部 使用弹出层放入echars图表show属性不会触发

### ISSUE THREAD

**Issue by z1450** [youzan/vant-weapp#3854]
http://vant-contrib.gitee.io/vant-issue-generater?repo=VantWeapp
结合echars使用时,日历会置于图表底部
 使用弹出层放入echars图表时show属性不会触发显示

**Comment by rex-zsd** [comment]
没看懂什么意思，可以上传一个代码片段？

**Comment by z1450** [comment]
在结合使用echars的时候，我要进行日期选择，使用Calendar 组件的时候echars图表层级过高会将Calendar 给覆盖

**Comment by rex-zsd** [comment]
正产现象，小程序中 echars 是用 canvas 实现的，canvas 是原生组件，层级比所有元素都高，与 `z-index` 无关。

只有一个办法，在显示浮层的时候，将 echars 先隐藏。
