### ISSUE TITLE
[Bug Report] van-area组件中 <import src="./toolbar.wxml" />失效not found

### ISSUE THREAD

**Issue by 245375200** [youzan/vant-weapp#3855]
### 设备
win10

### VantWeapp 版本
1.6.3

### 基础库版本
2.11.1

### 请提供核心代码片段链接
https://github.com/youzan/vant-weapp/blob/dev/dist/picker/index.wxml

### 描述问题
我使用的vant小程序组件，编译的时候提示小程序组件里面的wxml的import标签识别不了。主要的表现如下图，本身van-picker组件弹出上方时有”取消“和"确认"按钮，但是因为import指令没剩下，导致van-picker中没有导入toolbar那一部分。所以工具栏那一部分显示不出来。

**Comment by rex-zsd** [comment]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater?repo=VantWeapp

请附上你的小程序代码片段或者贴下使用的代码，这样一堆文字完全定位不了问题，帮不了你了哈。

**Comment by rex-zsd** [comment]
从可能的角度推测你的小程序是否非原生的？比如 wepy、mpvue 等，某些框架是不支持原生的 `template` 语法的，需要注意了。
