### ISSUE TITLE
vant weapp怎样解决冒泡问题

### ISSUE THREAD

**Issue by MouKim** [youzan/vant-weapp#3856]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater?repo=VantWeapp

**Comment by rex-zsd** [comment]
请查阅微信小程序官方文档哈，事件冒泡跟 vant weapp 没什么关系。

**Comment by rex-zsd** [comment]
比如你想阻止 tap 事件继续向上冒泡，自行 catch 掉就行了
```html
<van-button bind:click="onClick" catch:tap="noop">hello world</van-button>
```

**Comment by masicheng** [comment]
当disabled属性为true时catch:tap事件还是会触发，这个正常么？
