### ISSUE TITLE
[Bug Report] vant-circle组件在小程序中的异常

### ISSUE THREAD

**Issue by FengHaiSheng** [youzan/vant-weapp#3859]
### 设备
小米9

### VantWeapp 版本
1.6.2

### 基础库版本
2.14.1

### 如果是 UI 问题，截图链接（多图回车分隔）

<a href="https://sm.ms/image/1RFg63odW7C9iax" target="_blank">课堂报告跳跃问题.gif</a>

### 请提供核心代码片段链接
http://xxx.com

### 描述问题
<van-circle value="{{ 30 }}"  size="103" stroke-width="16" text="1/1" color="#FFC000" speed="{{1000}}" layer-color="#ffffff" />

1. BUG：组件内部的文字出现了异常跳动
2. Feature：圆形内部的文字颜色需要可以自定义

**Comment by rex-zsd** [comment]
为了使文字能够覆盖 canvas，中间文字使用的是 cover-view 原生组件。
给原生组件增加动画效果可能出现各种情况，不是组件库可以控制的行为哈。
