### ISSUE TITLE
这里的宽度设置会导致小程序页面宽度超过100%，左右晃动

### ISSUE THREAD

**Issue by frontbear** [youzan/vant-weapp#386]
https://github.com/youzan/zanui-weapp/blob/a36d6606d3cb945b3aa851b733240254a4d1f8ee/packages/common/_mixins.pcss#L3-L8

https://github.com/youzan/zanui-weapp/blob/c57d8811e99ae9a4573004a91070b68361355fc0/packages/cell/index.pcss#L13-L15

**Comment by frontbear** [comment]
@rex-zsd 使用zanui的cell组件会出现小程序页面左右晃动的情况。我只好fork了一份，然后提交了一个commit尝试解决 https://github.com/frontbear/zanui-weapp/commit/7a7145e20e234e0dceb5f4f3b473fe9a2ed76aa5 我的这个调整并不是好的解决办法，但是能保证页面不会再左右晃动

**Comment by xiejinpeng007** [comment]
我这边使用 field 会遇到同样的问题。

**Comment by skltzjt** [comment]
.zan-field::after里的left:15px删掉就好了

**Comment by chenjiahan** [comment]
目前 zanui-weapp 已进行全新的品牌升级，更名为 Vant Weapp，组件和 API 都有较大的变化。

对 zanui-weapp 的讨论，请移步至 https://github.com/youzan/zanui-weapp 仓库
