### ISSUE TITLE
[Bug Report] icon使用发现一个错误

### ISSUE THREAD

**Issue by YellowBear0513** [youzan/vant-weapp#3860]
### 设备
手机

### VantWeapp 版本
1.6.3

### 基础库版本
2.13.1

### 请提供核心代码片段链接
https://github.com/youzan/vant-weapp

### 描述问题
文档中使用日历icon，描述的是van-icon name="calendar-o" ，使用发现不显示icon。
查询到源码中使用的是van-icon-calender-o ，calendar拼写错误

**Comment by rex-zsd** [comment]
使用的不是最新版本？最新版本 name 是正确的。
