### ISSUE TITLE
[Bug Report] dialog组件形式 before-close回调不执行

### ISSUE THREAD

**Issue by Confetti7** [youzan/vant-weapp#3861]
设备
手机

VantWeapp 版本
1.6.3

基础库版本
2.8.1

现象
van-dialog before-close不执行

```html
<van-dialog   
   use-slot
   title="免密登录" 
   show="{{ dialogShow }}" 
   show-cancel-button 
   before-close="{{ beforeClose }}" 
   bind:close="onClose" 
   confirm-button-open-type="getUserInfo" 
   bind:getuserinfo="onGetUserInfo">
        <van-field value="{{ phone }}" label="手机号" placeholder="请输入手机号" 
        error-message="{{ errorMsg }}" border="{{ false }}" />
</van-dialog>
```

```js
// 关闭拦截
beforeClose() {
        debugger;
        return false;
},
```

**Comment by hanozhang** [comment]
同遇到此问题，原因为onClose方法不存在， 应改为this.close()
```
    onClickOverlay() {
      this.onClose("overlay")
    },
    close(action) {
      this.setData({ show: false })
      wx.nextTick(() => {
        this.$emit("close", action)
        const { callback } = this.data
        if (callback) {
          callback(action, this)
        }
      })
    },
```

**Comment by Confetti7** [comment]
> 同遇到此问题，原因为onClose方法不存在， 应改为this.close()
> 
> ```
>     onClickOverlay() {
>       this.onClose("overlay")
>     },
>     close(action) {
>       this.setData({ show: false })
>       wx.nextTick(() => {
>         this.$emit("close", action)
>         const { callback } = this.data
>         if (callback) {
>           callback(action, this)
>         }
>       })
>     },
> ```

新版本的vant是有这个事件的，我看源码里也已经定义了

**Comment by rex-zsd** [comment]
@Confetti7  实测可触发没问题，推测你把 `beforeClose` 方法放错了位置，要注意小程序只有 `data` 中的值可传入模板，`methods` 中的方法在模板中是无法拿到的。


```js
Page({
  data: {
    beforeClose() {
      console.log('##');
      return false;
    }
  }
});
```

**Comment by rex-zsd** [comment]
如果是方法调用则直接传入即可

```js
Page({
  methods: {
    whatever() {
      Dialog.confirm({
  title: '标题',
  message: '弹窗内容'
  beforeClose: (action) => new Promise((resolve) => {
  setTimeout(() => {
    if (action === 'confirm') {
      resolve(true);
    } else {
      // 拦截取消操作
      resolve(false);
    }
  }, 1000);
});
});
      
    }
  }
});
```

**Comment by Confetti7** [comment]
@rex-zsd 很明显我这个用的是组件方式啊

**Comment by Confetti7** [comment]
感谢解答

**Comment by Confetti7** [comment]
我定义在了data外层，和data同级

**Comment by tonokim** [comment]
> @Confetti7 实测可触发没问题，推测你把 `beforeClose` 方法放错了位置，要注意小程序只有 `data` 中的值可传入模板，`methods` 中的方法在模板中是无法拿到的。
> 
> ```js
> Page({
>   data: {
>     beforeClose() {
>       console.log('##');
>       return false;
>     }
>   }
> });
> ```

这种情况下，如何调用method下的方法呢

**Comment by effortcheep** [comment]
> > @Confetti7 实测可触发没问题，推测你把 `beforeClose` 方法放错了位置，要注意小程序只有 `data` 中的值可传入模板，`methods` 中的方法在模板中是无法拿到的。
> > ```js
> > Page({
> >   data: {
> >     beforeClose() {
> >       console.log('##');
> >       return false;
> >     }
> >   }
> > });
> > ```
> 
> 这种情况下，如何调用method下的方法呢



> > @Confetti7 实测可触发没问题，推测你把 `beforeClose` 方法放错了位置，要注意小程序只有 `data` 中的值可传入模板，`methods` 中的方法在模板中是无法拿到的。
> > ```js
> > Page({
> >   data: {
> >     beforeClose() {
> >       console.log('##');
> >       return false;
> >     }
> >   }
> > });
> > ```
> 
> 这种情况下，如何调用method下的方法呢

> 有一个折中的方法
> 
> > > ```js
> > > Page({
> > > 	data: {
> > > 		beforeClose(action) {
> > >                   if (action === 'confirm') {
> > >                          return false;
> > >                    }
> > > 			return true;
> > > 		}
> > > 	},
> > >  methods: {
> > >   onConfirm() {
> > >         if (不通过校验) { 
> > >         } else {
> > >            // 处理事情 然后  把 dailog 的show 设置成 false 
> > >         }
> > >   }
> > >  }
> > > });
> > > ```
