### ISSUE TITLE
[Feature Request]  Field能增加百分比的属性吗？

### ISSUE THREAD

**Issue by echokh** [youzan/vant-weapp#3863]
### 这个功能解决了什么问题
业务处理过程中经常遇到要展示百分比的情景，能否对Filed增加相应的属性？

### 建议的API是什么样的
percent：{
type:Boolean,
value:false
}

**Comment by rex-zsd** [comment]
没看懂，展示百分比是什么意思？

**Comment by rex-zsd** [comment]
如果业务经常遇到，可以截个成果图看下

**Comment by echokh** [comment]
![Uploading QQ图片20201216173410.png…]()

**Comment by echokh** [comment]
不知道您能否看到

**Comment by rex-zsd** [comment]
看不到的，要等 uploading.. 提示结束，变为一个连接了以后，再提交 comment

**Comment by echokh** [comment]
![微信图片_20201216175435](https://user-images.githubusercontent.com/25023024/102332999-c9b42400-3fc7-11eb-8dca-01072c479233.jpg)

**Comment by rex-zsd** [comment]
OK 能看到了，但是这不需要增加新属性，直接使用 `right-icon` 插槽即可。
```html
<van-cell-group>
    <van-field
      label="用户名"
      placeholder="请输入用户名"
      bind:click-icon="onClickIcon"
    >
      <view slot="right-icon">%</view>
    </van-field>
    <van-field
      type="password"
      label="密码"
      placeholder="请输入密码"
    >
      <view slot="right-icon">吨</view>
    </van-field>
```

**Comment by rex-zsd** [comment]
效果如图
![image](https://user-images.githubusercontent.com/8767877/102333829-e6049080-3fc8-11eb-945e-e158a7ea6aaa.png)

**Comment by echokh** [comment]
> OK 能看到了，但是这不需要增加新属性，直接使用 `right-icon` 插槽即可。
> 
> ```
> <van-field
>   label="用户名"
>   placeholder="请输入用户名"
>   bind:click-icon="onClickIcon"
> >
>   <view slot="right-icon">%</view>
> </van-field>
> <van-field
>   type="password"
>   label="密码"
>   placeholder="请输入密码"
> >
>   <view slot="right-icon">吨</view>
> </van-field>
> ```

对于数据的处理，想来想去好像都需要另外一个存储真实数据的属性。为什么这么说呢？假如某个值是百分数，显示30%，但其实它的真实值是0.3，不知道您能不能理解我的意思

**Comment by rex-zsd** [comment]
显示值跟后端直接下发的值不同，自行处理一下就行啦。
这种逻辑应该不需要组件库来支持的。

**Comment by echokh** [comment]
> 显示值跟后端直接下发的值不同，自行处理一下就行啦。
> 这种逻辑应该不需要组件库来支持的。

明白啦
