### ISSUE TITLE
vant支付宝小程序版

### ISSUE THREAD

**Issue by martianyi** [youzan/vant-weapp#3864]
我们使用 antmove 对 vant-weapp 做了转换，维护了一个支付宝小程序的版本，已经稳定运行一年多了，最近也跟进到最新的版本。感兴趣的用户可以试用。

作者大大，不知道是否可以在README里增加一个链接^^ https://github.com/ant-move/Vant-Aliapp

**Comment by martianyi** [comment]
https://github.com/youzan/vant-weapp/pull/3873

**Comment by rex-zsd** [comment]
很棒 🎉
