### ISSUE TITLE
Dialog 弹出框，beforeClose到底写在哪里，按照官方的方法都执行不了

### ISSUE THREAD

**Issue by xiaomiza** [youzan/vant-weapp#3870]
Dialog 弹出框，beforeClose到底写在哪里，按照官方的方法都执行不了

**Comment by rex-zsd** [comment]
请按照issue模板附上代码片段哈

**Comment by xiaomiza** [comment]
`  const beforeClose = (action) => new Promise((resolve) => {
      setTimeout(() => {
        if (action === 'confirm') {
          resolve(true);
        } else {
          // 拦截取消操作
          resolve(false);
        }
      }, 1000);
    });
    Dialog.confirm({
      title: '标题',
      message: '弹窗内容',
      beforeClose
    });
`

**Comment by xiaomiza** [comment]
## ISSUE TEMPLATE 

- [ ] 

- [ ] const beforeClose = (action) => new Promise((resolve) => {

      setTimeout(() => {
        if (action === 'confirm') {
          resolve(true);
        } else {
          // 拦截取消操作
          resolve(false);
        }
      }, 1000);
    });
    Dialog.confirm({
      title: '标题',
      message: '弹窗内容',
      beforeClose
    });
Duplicate of #

**Comment by xiaomiza** [comment]
`const beforeClose = (action) => new Promise((resolve) => {`

      setTimeout(() => {
        if (action === 'confirm') {
          resolve(true);
        } else {
          // 拦截取消操作
          resolve(false);
        }
      }, 1000);
    });
    Dialog.confirm({
      title: '标题',
      message: '弹窗内容',
      beforeClose
    });
