### ISSUE TITLE
Dialog 弹出框，beforeClose到底写在哪里，按照官方的方法都执行不了

### ISSUE THREAD

**Issue by xiaomiza** [youzan/vant-weapp#3871]
` <van-dialog id="van-dialog" />`

`const beforeClose = (action) => new Promise((resolve) => {`

      setTimeout(() => {
        if (action === 'confirm') {
          resolve(true);
        } else {
          // 拦截取消操作
          resolve(false);
        }
      }, 1000);
    });

**Comment by rex-zsd** [comment]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater?repo=VantWeapp

**Comment by towry** [comment]
的确不管用

**Comment by xiaomiza** [comment]
感谢您的来信，已收到。
