### ISSUE TITLE
vant-field 绑定 bind:input bind:change 事件全部失效

### ISSUE THREAD

**Issue by hongmaoxiao** [youzan/vant-weapp#3872]
设备
所有设备

VantWeapp 版本
1.6.3

基础库版本
2.14.0

请提供核心代码片段链接

描述问题
微信小程序2.14.0下Field组件的事件全部失效不会触发

**Comment by rex-zsd** [comment]
未复现 2.14.0 基础库下事件失效的问题。
未提供代码没法继续排查，推测还是使用姿势问题哈。

**Comment by rex-zsd** [comment]
补个真机测试的图
![image](https://user-images.githubusercontent.com/8767877/102582583-e1adb400-413d-11eb-81ee-0944e909b768.png)

**Comment by hongmaoxiao** [comment]
恩，确实是我个人代码问题  这个问题提得草率了 打搅了
