### ISSUE TITLE
Bug: 填写 Field 时使用键盘中的确认按钮无法正确调用处理函数

### ISSUE THREAD

**Issue by upupming** [youzan/vant-weapp#388]
### 填写 Field 时使用键盘中的确认按钮无法正确调用处理函数

<details><summary>wxml 文件</summary>

```xml
<view class="container">
  <zan-panel title="{{language.fillInInfo}}">
    <zan-cell-group>
      <zan-field
        id="stuId"
        title="{{language.stuId.title}}"
        placeholder="{{language.stuId.placeholder}}"
        value="{{ stuId }}"
        inputType="number"
        bind:change="syncValue"
      ></zan-field>
      <zan-field
        id="stuName"
        title="{{language.stuName.title}}"
        placeholder="{{language.stuName.placeholder}}"
        value="{{ stuName }}"
        inputType="text"
        bind:change="syncValue"
      ></zan-field>
    </zan-cell-group>
  </zan-panel>
  <zan-button-group>
    <zan-button type="primary" bind:btnclick="saveInfo">
      {{language.save}}
    </zan-button>
  </zan-button-group>
</view>
<zan-toast id="login-status"></zan-toast>

```
</details>

我使用的是 `syncValue` 来处理 `change` 事件，一旦值发生改变就同步到页面的 data 中。

<img src=https://user-images.githubusercontent.com/24741764/43353096-fd80152a-9261-11e8-8b16-cdf5cf03bcc0.png height=400>

在我按下键盘中的『√』时，出现了下面的错误：

<img src=https://user-images.githubusercontent.com/24741764/43353098-152a209e-9262-11e8-9f80-376b87c6285d.png height=400>

看样子它是想调用 `handleFieldChange` 函数，但是我并没有定义这个函数，而是绑定的 `syncValue` ，它理应去调用 `syncValue`  这个函数。

+ 个人建议

    这个『√』通常来说的想法是保存当前所有输入，希望能实现一下直接存储数据到当前已输入的 Field 的数据到 `value` 中。

**Comment by rex-zsd** [comment]
额，你用的zanui是啥版本

**Comment by upupming** [comment]
目前测试了最新版 https://github.com/youzan/zanui-weapp/commit/c57d8811e99ae9a4573004a91070b68361355fc0 ，还是存在这个问题，我不得不在 js 文件里面加一个 `handleFieldChange ` 来处理这个事件。
https://github.com/upupming/HITMers/blob/1d8d7a7d534917c7e89f208ed2c0c188e33fbfc0/client/pages/info/index.js#L40

**Comment by chenjiahan** [comment]
目前 zanui-weapp 已进行全新的品牌升级，更名为 Vant Weapp，组件和 API 都有较大的变化。

对 zanui-weapp 的讨论，请移步至 https://github.com/youzan/zanui-weapp 仓库
