### ISSUE TITLE
[Feature Request] vant weapp Dialog 弹出框执行完确认事件之后，窗口总是默认关闭了，beforeClose虽然阻止关闭了，但是一直在转圈，不能重新点击确认按钮了

### ISSUE THREAD

**Issue by cgChen1995** [youzan/vant-weapp#3880]
### 这个功能解决了什么问题
解决窗口不关闭，并且可以重新点击确认按钮

### 建议的API是什么样的
vant weapp Dialog 弹出框执行完确认事件之后，窗口总是默认关闭了，beforeClose虽然阻止关闭了，但是一直在转圈，不能重新点击确认按钮了，
beforeClose能不让确认按钮转圈吗，让它可以再次点击，或者有没有什么别的办法可以解决窗口不关闭，并且可以重新点击确认按钮的方法

**Comment by rex-zsd** [comment]
在 `beforeClose` 中 `return false;` 或 `return Promise.resolve(false);` 就可以停止 loading

**Comment by cgChen1995** [comment]
wxml:
`<van-dialog use-slot z-index="100" title="{{showName}}" show="{{ show }}" show-cancel-button show-confirm-button show-cancel-button="取消" confirm-button-text="确定" show-cancel-button bind:close="onClose" bind:confirm="onConfirm" beforeClose="beforeClose">
    <van-cell-group>
      <van-cell title="名称" border="{{false}}" />
      <van-field value="{{ form.lease_name }}" error="{{formVerify.is_lease_name}}" placeholder="请输入用户名" border="{{ false }}" bind:change="onChangeleaseName" />
      <view wx:if="{{menuType==2}}">
        <van-cell title="所属父级菜单" border="{{false}}" />
        <van-cell title="{{ form.lease_type_name==''?'请选择':form.lease_type_name }}" bind:click="onSelectShowType" border="{{ false }}" is-link />
        <van-cell title="是否显示" border="{{false}}">
          <view>
            <van-switch checked="{{ form.is_lease_main==1 }}" bind:change="onChangeisLeaseMain" />
          </view>
        </van-cell>

        <van-cell title="是否开启" border="{{false}}">
          <view>
            <van-switch checked="{{ form.is_lease==1 }}" bind:change="onChangeisLease" />
          </view>
        </van-cell>
      </view>
    </van-cell-group>`
js:`Page({  data: {
    beforeClose:true,
     }});`
我自定义的弹窗，怎么在beforeClose 中设置return false; 或 return Promise.resolve(false);呢？

**Comment by cgChen1995** [comment]
用自定义的弹窗，不管怎么写，都在转圈

**Comment by rex-zsd** [comment]
参考下 example 的代码哈，实测没问题。
