### ISSUE TITLE
Tab 标签页在真机调试时卡顿  在小程序模拟器时不卡顿

### ISSUE THREAD

**Issue by MuGongziya** [youzan/vant-weapp#3885]
[卡顿视频.zip](https://github.com/youzan/vant-weapp/files/5721953/default.zip)

这是录屏文件

**Comment by MuGongziya** [comment]
体验版小程序不卡顿，，就在真机调试时候卡顿

**Comment by rex-zsd** [comment]
“真机调试” 还是 ”预览“? 真机调试时开发者工具要和真机进行数据交换，卡顿是正常的，可以用预览进行真机测试。

**Comment by rex-zsd** [comment]
看录屏是真机调试没错了，可以换预览，应该就不会卡顿了。

**Comment by MuGongziya** [comment]
> 看录屏是真机调试没错了，可以换预览，应该就不会卡顿了。

刚刚试了，，预览确实不卡，，然后体验版也没有卡顿，就调试卡顿，一开始插入的是静态数据不卡，就没注意，，然后今天加入新数据真机调试时候 就卡顿了

**Comment by wujohns** [comment]
同样的问题，在切换tab时尤为卡顿

**Comment by wujohns** [comment]
预览模式也是一样的
