### ISSUE TITLE
button里面custom-style设置第一个属性设置无效

### ISSUE THREAD

**Issue by zoubihai** [youzan/vant-weapp#3900]
![image](https://user-images.githubusercontent.com/19750129/102969177-37b09c00-4530-11eb-89e0-f9593d6ae8e3.png)
![image](https://user-images.githubusercontent.com/19750129/102969280-62025980-4530-11eb-8d1e-96813d75e36d.png)
width前面需要加“；”

**Comment by rex-zsd** [comment]
将在下版本修复哈

**Comment by zoubihai** [comment]
你好，我想知道那个版本是正确的，不然我现在所有使用这个样式的地方都要加“；”


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "youzan/vant-weapp"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月23日(星期三) 下午3:08
收件人:&nbsp;"youzan/vant-weapp"<vant-weapp@noreply.github.com&gt;;
抄送:&nbsp;"让脚步飞一会"<1208842419@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [youzan/vant-weapp] button里面custom-style设置第一个属性设置无效 (#3900)





 
将在下版本修复哈

**Comment by rex-zsd** [comment]
可以退回 v1.6.3 的版本

**Comment by zoubihai** [comment]
好的，谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "youzan/vant-weapp"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月23日(星期三) 下午3:13
收件人:&nbsp;"youzan/vant-weapp"<vant-weapp@noreply.github.com&gt;;
抄送:&nbsp;"让脚步飞一会"<1208842419@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [youzan/vant-weapp] button里面custom-style设置第一个属性设置无效 (#3900)





 
可以退回 v1.6.3 的版本
