### ISSUE TITLE
tabbar缺少点击事件和动画展示功能

### ISSUE THREAD

**Issue by a516117636** [youzan/vant-weapp#3901]
例如在今日头条app中，tabbar点击一下可以切换，再次点击当前tabbar图标触发刷新事件，同时tabbar图标显示相应刷新动画。我看了官方文档，没有发现tabbar点击事件，也没有动画展示功能。请问可以实现这两个功能吗？

**Comment by rex-zsd** [comment]
监听 van-tabbar-item  的 `tap` 事件就可以了，判断与当前激活项相同就做刷新的操作。
