### ISSUE TITLE
[Bug Report] uniapp结合vant weapp使用，编译时报错

### ISSUE THREAD

**Issue by ifelseZ** [youzan/vant-weapp#3904]
### 设备
HbuilderX2.9.8

### VantWeapp 版本
1.6.4

### 基础库版本
1.6.4

### 请提供核心代码片段链接
https://github.com/youzan/vant-weapp/tree/dev/dist

### 描述问题
1、问题描述：uniapp结合vant weapp使用，编译时报错：(36:193) Unclosed bracket
解决方式：dist/icon/index.wxss 和 icon/index.vue 中的url前面要加空格
2、问题描述：uniapp结合vant weapp使用，编译时报错：TypeError: Cannot read property 'split' of undefined
解决方式：dist/common/version.js 中
return compareVersion(system.SDKVersion, '2.9.0') >= 0;
改为 
return system.SDKVersion==undefined?false:compareVersion(system.SDKVersion, '2.4.0') >= 0;

**Comment by rex-zsd** [comment]
问下使用场景是什么呢？还是微信小程序吗？还是用 uniapp 编译到其他渠道使用了?

**Comment by ifelseZ** [comment]
> 问下使用场景是什么呢？还是微信小程序吗？还是用 uniapp 编译到其他渠道使用了?
（1）这条bug是运行到H5的报错。
（2）运行到微信小程序的话，不能使用uniapp的easycom，只能使用usingComponents的方式一个个引入，不然也会报错。具体看链接：https://blog.csdn.net/zdq357104345/article/details/111656549
我不知道这是uniapp的错还是，vant-weapp的原因，我用vant-weapp以前的版本使用easycom的时候是可以编译的，也会语法错误就是了，不知道是不是你们最新的版本引用方式上做了改变导致的

**Comment by whl-gh** [comment]
设备
VSCode 编辑器、iphone11  ios v14.0.1

VantWeapp 版本
1.6.4

微信调试基础库版本
2.14.1

描述问题
1、van-overlay 组件在使用的时候报错，模拟器好着，其他框架如 mpvue 等都可以正常显示，手机截图如下：
`vue
<van-overlay :show="true" :z-index="1000" />
`
![3dae08f05595a11874cda83e0484d43](https://user-images.githubusercontent.com/48339784/103117357-fbeb1300-46a4-11eb-9fde-76b1a3c81e2d.jpg)

**Comment by whl-gh** [comment]
An SelectorQuery call is ignored because no proper page or component is found. Please considering using ‘SelectorQuery.in’ to specify a proper one.

**Comment by ifelseZ** [comment]
> 设备
> VSCode 编辑器、iphone11 ios v14.0.1
> 
> VantWeapp 版本
> 1.6.4
> 
> 微信调试基础库版本
> 2.14.1
> 
> 描述问题
> 1、van-overlay 组件在使用的时候报错，模拟器好着，其他框架如 mpvue 等都可以正常显示，手机截图如下：
> `vue <van-overlay :show="true" :z-index="1000" /> `
> ![3dae08f05595a11874cda83e0484d43](https://user-images.githubusercontent.com/48339784/103117357-fbeb1300-46a4-11eb-9fde-76b1a3c81e2d.jpg)

我看不到你的图，我使用的是HBuilderX2.9.8，VantWeapp 1.6.4，你可以试一下，肯定是有问题的，网上已经很多人有提出来了，我也是根据搜索结果解决好这些问题了，但是我想要用npm 的方式引用vant weapp ，所以还是需要你们官方解决一下，请根据我说的步骤操作一下

**Comment by ifelseZ** [comment]
> 设备
> VSCode 编辑器、iphone11 ios v14.0.1
> 
> VantWeapp 版本
> 1.6.4
> 
> 微信调试基础库版本
> 2.14.1
> 
> 描述问题
> 1、van-overlay 组件在使用的时候报错，模拟器好着，其他框架如 mpvue 等都可以正常显示，手机截图如下：
> `vue <van-overlay :show="true" :z-index="1000" /> `
> ![3dae08f05595a11874cda83e0484d43](https://user-images.githubusercontent.com/48339784/103117357-fbeb1300-46a4-11eb-9fde-76b1a3c81e2d.jpg)

可以查看链接：https://blog.csdn.net/zdq357104345/article/details/111614247

**Comment by whl-gh** [comment]
> > 设备
> > VSCode 编辑器、iphone11 ios v14.0.1
> > VantWeapp 版本
> > 1.6.4
> > 微信调试基础库版本
> > 2.14.1
> > 描述问题
> > 1、van-overlay 组件在使用的时候报错，模拟器好着，其他框架如 mpvue 等都可以正常显示，手机截图如下：
> > `vue <van-overlay :show="true" :z-index="1000" /> `
> > ![3dae08f05595a11874cda83e0484d43](https://user-images.githubusercontent.com/48339784/103117357-fbeb1300-46a4-11eb-9fde-76b1a3c81e2d.jpg)
> 
> 我看不到你的图，我使用的是HBuilderX2.9.8，VantWeapp 1.6.4，你可以试一下，肯定是有问题的，网上已经很多人有提出来了，我也是根据搜索结果解决好这些问题了，但是我想要用npm 的方式引用vant weapp ，所以还是需要你们官方解决一下，请根据我说的步骤操作一下



> 设备
> VSCode 编辑器、iphone11 ios v14.0.1
> 
> VantWeapp 版本
> 1.6.4
> 
> 微信调试基础库版本
> 2.14.1
> 
> 描述问题
> 1、van-overlay 组件在使用的时候报错，模拟器好着，其他框架如 mpvue 等都可以正常显示，手机截图如下：
> `vue <van-overlay :show="true" :z-index="1000" /> `
> ![3dae08f05595a11874cda83e0484d43](https://user-images.githubusercontent.com/48339784/103117357-fbeb1300-46a4-11eb-9fde-76b1a3c81e2d.jpg)

问题找到了，还是需要修改源码解决这个bug：
在vant组件库的如下文件中修改：
dist/common/utils.js
`javascript
export function requestAnimationFrame(cb) {
  const systemInfo = getSystemInfoSync();
  if (systemInfo.platform === 'devtools') {
    return setTimeout(() => {
      cb();
    }, 1000 / 30);
  }
  // 源码
  // return wx
  //   .createSelectorQuery()
  //   .selectViewport()
  //   .boundingClientRect()
  //   .exec(() => {
  //     cb();
  //   });
  // 修改之后代码
  // 程序初次加载路由栈为空，这个时候需要把当前任务加到下一个队列中去执行
  setTimeout(() => {
    // 获取当前路由栈
    const pages = getCurrentPages()
    let selector = wx.createSelectorQuery()
    if (pages.length > 0) {
      selector = selector.in(pages[pages.length - 1].$vm)
    }
    selector
    .selectViewport()
    .boundingClientRect()
    .exec(() => {
      cb();
    });
  }, 0)
}
`

**Comment by whl-gh** [comment]
> > > 设备
> > > VSCode 编辑器、iphone11 ios v14.0.1
> > > VantWeapp 版本
> > > 1.6.4
> > > 微信调试基础库版本
> > > 2.14.1
> > > 描述问题
> > > 1、van-overlay 组件在使用的时候报错，模拟器好着，其他框架如 mpvue 等都可以正常显示，手机截图如下：
> > > `vue <van-overlay :show="true" :z-index="1000" /> `
> > > ![3dae08f05595a11874cda83e0484d43](https://user-images.githubusercontent.com/48339784/103117357-fbeb1300-46a4-11eb-9fde-76b1a3c81e2d.jpg)
> > 
> > 
> > 我看不到你的图，我使用的是HBuilderX2.9.8，VantWeapp 1.6.4，你可以试一下，肯定是有问题的，网上已经很多人有提出来了，我也是根据搜索结果解决好这些问题了，但是我想要用npm 的方式引用vant weapp ，所以还是需要你们官方解决一下，请根据我说的步骤操作一下
> 
> > 设备
> > VSCode 编辑器、iphone11 ios v14.0.1
> > VantWeapp 版本
> > 1.6.4
> > 微信调试基础库版本
> > 2.14.1
> > 描述问题
> > 1、van-overlay 组件在使用的时候报错，模拟器好着，其他框架如 mpvue 等都可以正常显示，手机截图如下：
> > `vue <van-overlay :show="true" :z-index="1000" /> `
> > ![3dae08f05595a11874cda83e0484d43](https://user-images.githubusercontent.com/48339784/103117357-fbeb1300-46a4-11eb-9fde-76b1a3c81e2d.jpg)
> 
> 问题找到了，还是需要修改源码解决这个bug：
> 在vant组件库的如下文件中修改：
> dist/common/utils.js
> `javascript export function requestAnimationFrame(cb) { const systemInfo = getSystemInfoSync(); if (systemInfo.platform === 'devtools') { return setTimeout(() => { cb(); }, 1000 / 30); } // 源码 // return wx // .createSelectorQuery() // .selectViewport() // .boundingClientRect() // .exec(() => { // cb(); // }); // 修改之后代码 // 程序初次加载路由栈为空，这个时候需要把当前任务加到下一个队列中去执行 setTimeout(() => { // 获取当前路由栈 const pages = getCurrentPages() let selector = wx.createSelectorQuery() if (pages.length > 0) { selector = selector.in(pages[pages.length - 1].$vm) } selector .selectViewport() .boundingClientRect() .exec(() => { cb(); }); }, 0) } `

通过 wx.nextTick 替代 setTimeout 也可以实现

**Comment by ifelseZ** [comment]
> > > > 设备
> > > > VSCode 编辑器、iphone11 ios v14.0.1
> > > > VantWeapp 版本
> > > > 1.6.4
> > > > 微信调试基础库版本
> > > > 2.14.1
> > > > 描述问题
> > > > 1、van-overlay 组件在使用的时候报错，模拟器好着，其他框架如 mpvue 等都可以正常显示，手机截图如下：
> > > > `vue <van-overlay :show="true" :z-index="1000" /> `
> > > > ![3dae08f05595a11874cda83e0484d43](https://user-images.githubusercontent.com/48339784/103117357-fbeb1300-46a4-11eb-9fde-76b1a3c81e2d.jpg)
> > > 
> > > 
> > > 我看不到你的图，我使用的是HBuilderX2.9.8，VantWeapp 1.6.4，你可以试一下，肯定是有问题的，网上已经很多人有提出来了，我也是根据搜索结果解决好这些问题了，但是我想要用npm 的方式引用vant weapp ，所以还是需要你们官方解决一下，请根据我说的步骤操作一下
> > 
> > 
> > > 设备
> > > VSCode 编辑器、iphone11 ios v14.0.1
> > > VantWeapp 版本
> > > 1.6.4
> > > 微信调试基础库版本
> > > 2.14.1
> > > 描述问题
> > > 1、van-overlay 组件在使用的时候报错，模拟器好着，其他框架如 mpvue 等都可以正常显示，手机截图如下：
> > > `vue <van-overlay :show="true" :z-index="1000" /> `
> > > ![3dae08f05595a11874cda83e0484d43](https://user-images.githubusercontent.com/48339784/103117357-fbeb1300-46a4-11eb-9fde-76b1a3c81e2d.jpg)
> > 
> > 
> > 问题找到了，还是需要修改源码解决这个bug：
> > 在vant组件库的如下文件中修改：
> > dist/common/utils.js
> > `javascript export function requestAnimationFrame(cb) { const systemInfo = getSystemInfoSync(); if (systemInfo.platform === 'devtools') { return setTimeout(() => { cb(); }, 1000 / 30); } // 源码 // return wx // .createSelectorQuery() // .selectViewport() // .boundingClientRect() // .exec(() => { // cb(); // }); // 修改之后代码 // 程序初次加载路由栈为空，这个时候需要把当前任务加到下一个队列中去执行 setTimeout(() => { // 获取当前路由栈 const pages = getCurrentPages() let selector = wx.createSelectorQuery() if (pages.length > 0) { selector = selector.in(pages[pages.length - 1].$vm) } selector .selectViewport() .boundingClientRect() .exec(() => { cb(); }); }, 0) } `
> 
> 通过 wx.nextTick 替代 setTimeout 也可以实现

你们解决问题后，发布新的版本我再去验证下，希望这两个问题能都修复一下

**Comment by rex-zsd** [comment]
@whl-gh  无关问题请另开 issue 反馈哈。

**Comment by rex-zsd** [comment]
> > 问下使用场景是什么呢？还是微信小程序吗？还是用 uniapp 编译到其他渠道使用了?
> > （1）这条bug是运行到H5的报错。
> > （2）运行到微信小程序的话，不能使用uniapp的easycom，只能使用usingComponents的方式一个个引入，不然也会报错。具体看链接：https://blog.csdn.net/zdq357104345/article/details/111656549
> > 我不知道这是uniapp的错还是，vant-weapp的原因，我用vant-weapp以前的版本使用easycom的时候是可以编译的，也会语法错误就是了，不知道是不是你们最新的版本引用方式上做了改变导致的

![image](https://user-images.githubusercontent.com/8767877/103122994-935c6000-46bd-11eb-978c-7fb5ad952049.png)

uni-app 的文档已经把条件描述的很清楚了，easycom 只适用于 `.vue` 结尾的组件，但是 vant weapp 提供的是 [原生组件](https://developers.weixin.qq.com/miniprogram/dev/framework/custom-component/)。
不是上个版本能否使用的问题，设计上就不是这样使用的。

**Comment by rex-zsd** [comment]
uni-app 使用原生组件请参考 [小程序组件支持](https://uniapp.dcloud.io/frame?id=%e5%b0%8f%e7%a8%8b%e5%ba%8f%e7%bb%84%e4%bb%b6%e6%94%af%e6%8c%81)

**Comment by ifelseZ** [comment]
> uni-app 使用原生组件请参考 [小程序组件支持](https://uniapp.dcloud.io/frame?id=%e5%b0%8f%e7%a8%8b%e5%ba%8f%e7%bb%84%e4%bb%b6%e6%94%af%e6%8c%81)

看最初的问题描述，是HBuilderX2.9.8，VantWeapp 1.6.4下，运行H5编译报错，这个问题的bug，那这个问题有没有办法解决一下？

**Comment by ifelseZ** [comment]
@rex-zsd 
HBuilderX2.9.8，VantWeapp 1.6.4下，运行H5编译报错
1、问题描述：uniapp结合vant weapp使用，编译时报错：(36:193) Unclosed bracket
解决方式：dist/icon/index.wxss 和 icon/index.vue 中的url前面要加空格
2、问题描述：uniapp结合vant weapp使用，编译时报错：TypeError: Cannot read property 'split' of undefined
解决方式：dist/common/version.js 中
return compareVersion(system.SDKVersion, '2.9.0') >= 0;
改为
return system.SDKVersion==undefined?false:compareVersion(system.SDKVersion, '2.4.0') >= 0;

**Comment by ifelseZ** [comment]
@rex-zsd 
使用HBuilderX2.9.8，uniapp+vant-weapp，运行到H5环境下，比如Chrome，就会在组件目录下自动生成vue文件，比如/dist/button下面生成index.vue,所以使用easycom的方式引入是没有问题的，但是运行到微信小程序的环境，就会报错需要使用usingComponents方式来引用组件才不会报错，那这个问题不是vant-weapp的问题？
