### ISSUE TITLE
[Bug Report] vant-slider组件在display:flex下的特效问题

### ISSUE THREAD

**Issue by ken30huang** [youzan/vant-weapp#3905]
### 设备
PC桌面、手机端

### VantWeapp 版本
1.6.4

### 基础库版本
2.12.2

### 如果是 UI 问题，截图链接（多图回车分隔）

[https://i.loli.net/2020/12/24/AxPaLJoEjT93dbX.png](https://i.loli.net/2020/12/24/AxPaLJoEjT93dbX.png)

![微信截图_20201224112611.png](https://i.loli.net/2020/12/24/AxPaLJoEjT93dbX.png)

### 请提供核心代码片段链接
https://gitee.com/huangkai19/code_bugs/issues/I2ANTE

### 描述问题
vant-slider包含在display:flex的元素下，无法实现拖动效果

**Comment by rex-zsd** [comment]
用 `custom-class` 给组件加上固定宽度即可，外层加了 `display:flex;` 以后，内部的相对宽度都会失效的。

```html
<view>没包含在diplay：flex下</view>
<van-slider bind:change="onChange" />
<view style="display: flex;padding-top:80px ">
  <view>包含在diplay：flex下</view>
  <view style="margin-top:40px">
    <van-slider custom-class="slider-in-flex" bind:change="onChange" />
  </view>
</view>
```

```css
.slider-in-flex {
  width: 100px;
}
```
