### ISSUE TITLE
[Feature Request] 日历组件可否直接定位到当前日期位置

### ISSUE THREAD

**Issue by kongliya** [youzan/vant-weapp#3906]
### 这个功能解决了什么问题
日历组件想上滑选择之前的时间 设置min-date以后发现 直接是min-date的位置 而不是当前今天的日期 需要一只往下滑 对用户体验来说是很不友好的  因为现在的小程序ui库没有比vant更好使的 所以这是个建议 谢谢～

### 建议的API是什么样的
无

**Comment by rex-zsd** [comment]
上传一下代码片段哈

**Comment by kongliya** [comment]
`<template>
  <div class="container">
    <div class="calendar-container">
      <van-calendar
        show-title="{{ false }}"
        poppable="{{ false }}"
        show-confirm="{{ false }}"
        show-mark="{{ false }}"
        class="calendar"
        color="#FFC947"
        formatter="{{ formatter }}"
        @select="handleTapDate"
        min-date="{{ minDate }}"
        max-date="{{ maxDate }}"
      />
    </div>
  </div>
</template>

<script>
import wepy from "@wepy/core"

wepy.page({
  data: {
    date: "",
    show: true,
    clockedDate: {},
    formatter(day) {
      return day
    },
    minDate: null,
    maxDate: null
  },
  methods: {
    reloadCalendar(selectDate = getDate(new Date())) {
      const [selectY, selectM, selectD] = selectDate
      const todayYear = new Date().getFullYear()
      const todayMonth = new Date().getMonth() + 1
      const todayDate = new Date().getDate()
      this.formatter = day => {
        const [year, month, date] = getDate(day.date)
        const oYear = day.date.getFullYear()
        const oMonth = day.date.getMonth() + 1
        const oDate = day.date.getDate()

        if (selectY === year && selectM === month && selectD === date) {
          day.type = "selected"
          return day
        }
        if (c[year] && c[year][month] && c[year][month][date]) {
          day.type = "middle"
          return day
        }

        if (oYear === todayYear && oMonth === todayMonth && oDate === todayDate) {
          day.text = "今天"
          return day
        }

        day.type = ""
        return day
      }
    }
  }
})

async function initCalendar() {
  initMinAndMax.call(this)
}

function initMinAndMax() {
  // let date = new Date(Date.now() - 1000 * 3600 * 24 * 30 * 1)
  const [year, month] = getDate()
  this.minDate = new Date("1990-1-1").getTime()
  this.maxDate = new Date().getTime()
}

const getDate = (_date = new Date()) => {
  const year = _date.getFullYear()
  const month = _date.getMonth() + 1
  const date = _date.getDate()
  return [year, month, date]
}

const getMonthDate = (_date = new Date()) => {
  const year = _date.getFullYear()
  const month = _date.getMonth() + 1
  return [year, month]
}
</script>
`

试试这个 从项目里摘出来的

**Comment by kongliya** [comment]
`
<template>
  <div class="container">
    <div class="calendar-container">
      <van-calendar
        show-title="{{ false }}"
        poppable="{{ false }}"
        show-confirm="{{ false }}"
        show-mark="{{ false }}"
        class="calendar"
        color="#FFC947"
        formatter="{{ formatter }}"
        @select="handleTapDate"
        min-date="{{ minDate }}"
        max-date="{{ maxDate }}"
      />
    </div>
  </div>
</template>

<script>
import wepy from "@wepy/core"

wepy.page({
  data: {
    date: "",
    show: true,
    clockedDate: {},
    formatter(day) {
      return day
    },
    minDate: null,
    maxDate: null
  },
  methods: {
    reloadCalendar(selectDate = getDate(new Date())) {
      const [selectY, selectM, selectD] = selectDate
      const todayYear = new Date().getFullYear()
      const todayMonth = new Date().getMonth() + 1
      const todayDate = new Date().getDate()
      this.formatter = day => {
        const [year, month, date] = getDate(day.date)
        const oYear = day.date.getFullYear()
        const oMonth = day.date.getMonth() + 1
        const oDate = day.date.getDate()

        if (selectY === year && selectM === month && selectD === date) {
          day.type = "selected"
          return day
        }
        if (c[year] && c[year][month] && c[year][month][date]) {
          day.type = "middle"
          return day
        }

        if (oYear === todayYear && oMonth === todayMonth && oDate === todayDate) {
          day.text = "今天"
          return day
        }

        day.type = ""
        return day
      }
    }
  }
})

async function initCalendar() {
  initMinAndMax.call(this)
}

function initMinAndMax() {
  // let date = new Date(Date.now() - 1000 * 3600 * 24 * 30 * 1)
  const [year, month] = getDate()
  this.minDate = new Date("1990-1-1").getTime()
  this.maxDate = new Date().getTime()
}

const getDate = (_date = new Date()) => {
  const year = _date.getFullYear()
  const month = _date.getMonth() + 1
  const date = _date.getDate()
  return [year, month, date]
}

const getMonthDate = (_date = new Date()) => {
  const year = _date.getFullYear()
  const month = _date.getMonth() + 1
  return [year, month]
}
</script>

`

试试这个 从项目里摘出来的

**Comment by rex-zsd** [comment]
目前日历组件的机制是初始化时定位到默认选中的日期，可以设置一下 `default-date` 为当前时间，就可以自动定位了哈。

**Comment by wjbd** [comment]
因为有的情况下，查日期是向上查的，所以在未设置defalut-date的情况下，希望可以自动定位到当前月份的
现在有办法解决了吗？

**Comment by why-ztc** [comment]
因为有的情况下，查日期是向上查的，所以在未设置defalut-date的情况下，希望可以自动定位到当前月份的
现在有办法解决了吗？

**Comment by why-ztc** [comment]
> 目前日历组件的机制是初始化时定位到默认选中的日期，可以设置一下 `default-date` 为当前时间，就可以自动定位了哈。

但是并不想要默认有选中日期
