### ISSUE TITLE
[Bug Report] van-tabbar placeholder属性无效

### ISSUE THREAD

**Issue by Barrycca** [youzan/vant-weapp#3908]
### 设备
iphoneXR

### VantWeapp 版本
1.6.4

### 基础库版本
2.7.2

### 请提供核心代码片段链接
https://gist.github.com/Barrycca/ea59d041773d867d707f1345f2dfca56.js

### 描述问题
van-tabbar placeholder属性无效

**Comment by a516117636** [comment]
兄弟，你帮我把我的问题也问了，感谢

**Comment by WebRookie** [comment]
不止是tabbar，还有van-field 类型设置为textarea的时候，苹果的placeholder也是无效的

**Comment by a516117636** [comment]
为什么这么久官方都没人回复一下呢？这个问题能解决吗？

**Comment by rex-zsd** [comment]
@a516117636 因为没有人按照 issue 格式上传代码片段，无法得知你们是怎么写的代码。

**Comment by rex-zsd** [comment]
示例工程测试没问题，因为没有人提供代码片段，无法得知问题的具体情况。

请注意 `placeholder` 与 `fixed` 必须搭配使用，并且站位元素是在组件位置，而不是页面底部。
