### ISSUE TITLE
在微信小程序里，Field 输入框修改type属性的值为number idcard textarea digit类型无效

### ISSUE THREAD

**Issue by a516117636** [youzan/vant-weapp#3909]

**Comment by Odyssey166** [comment]
遇到同样问题。例如：<van-field model:value="{{question_id}}" type="number" placeholder="请输入" />，却可以输入文本（字母或汉字）。微信开发者工具的调试基础库版本：2.14.0

**Comment by WebRookie** [comment]
> 遇到同样问题。例如：`<van-field model:value="{{question_id}}" type="number" placeholder="请输入" />`，却可以输入文本（字母或汉字）。微信开发者工具的调试基础库版本：2.14.0

我也遇见了这个问题，没办法，设置了一个输入的验证方法....

**Comment by Odyssey166** [comment]
貌似找到问题所在。按照微信小程序官方文档（https://developers.weixin.qq.com/miniprogram/dev/component/input.html），type的值为number时，调用“数字输入键盘”。vant-weapp Field组件在苹果或者安卓系统测试都是调用“数字输入键盘”，只是用微信开发者工具调试时出现问题，可以随便输入罢了。

**Comment by rex-zsd** [comment]
可以看下微信小程序官方文档哈，请在真机测试 `type`。

**Comment by qiangzi7723** [comment]
+1 刚刚也遇到了这个问题，估计真是开发者工具能复现
