### ISSUE TITLE
van-tabs组件，无法获取被选中van-tab宽度，或者动态设置底部条的宽度

### ISSUE THREAD

**Issue by zyh362048474** [youzan/vant-weapp#3911]
获取被选中的van-tab宽度，进行动态设置van-tab-line的宽度，这样tab标题和底部条能保证一致的宽度，而不是固定的40px

        var query = wx.createSelectorQuery().in(this);
        query.select('.van-tab').boundingClientRect().exec(res => {
            console.log(res)
        });

通过class选择器无法获取到van-tab，输出结果null

**Comment by rex-zsd** [comment]
`SelectorQuery` 是无法穿透自定义组件的，要选中组件内的节点，`in` 必须设置正确。
可以用 `selectComponent` 选取到 tabs 组件，再 `in(vanTabs)`。

**Comment by zyh362048474** [comment]
已解决获取标题宽度的问题，但是现在底部条动态设置长度后，有时会出现底部条与标题文字错位的问题
        var _this = this;
        var tabs = this.selectComponent('#tabs');
        var query = this.createSelectorQuery().in(tabs);
        query.selectAll('.van-tab').boundingClientRect().exec(res => {
            // console.log(res)
            this.setData({
                lineWidth: res[0][index].width
            })
        });
