### ISSUE TITLE
小程序panel 面板的怎样自定义title、desc、status。看文档有点没明白。

### ISSUE THREAD

**Issue by MuGongziya** [youzan/vant-weapp#3912]
![QQ截图20201228115147](https://user-images.githubusercontent.com/66168501/103188416-55e91400-4903-11eb-89d4-4b1d783b0e6f.png)

![QQ截图20201228120927](https://user-images.githubusercontent.com/66168501/103188981-9a75af00-4905-11eb-9274-693047c2b0ed.png)
这样写感觉又不对

**Comment by rex-zsd** [comment]
slot 只有整体的 `header`，内部不区分 title、desc、status。

**Comment by rex-zsd** [comment]
```html
<van-panel>
  <view slot="header">
    hello world!
  </view>
</van-panel>
```
