### ISSUE TITLE
[Bug Report] Toast.clear()清除提示会报错

### ISSUE THREAD

**Issue by dongzhiwei1990** [youzan/vant-weapp#3914]
### 设备
安卓

### VantWeapp 版本
1.6.4

### 基础库版本
2.14.1

### 如果是 UI 问题，截图链接（多图回车分隔）

![截图](https://taozhimall-test.oss-cn-qingdao.aliyuncs.com/materialCenter/2020-12-28/7de9e370a6b749ac85e8a364f154f6c6.png)

### 请提供核心代码片段链接
https://gitee.com/vant-contrib/vant-weapp/issues/I2AI2M#note_3905261

### 描述问题
在微信onLoad、onShow这些生命周期使用Toast.clear()清除提示，会报错 Error: incongruent status: enter;

**Comment by rex-zsd** [comment]
可以忽略，这个 error 是动画渲染时序异常时抛出的。
显示、清除间隔过短时可能出现
