### ISSUE TITLE
van-field在ios真机中 placeholder-style的opacity属性不生效，在模拟器和安卓都正常

### ISSUE THREAD

**Issue by WebRookie** [youzan/vant-weapp#3915]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater?repo=VantWeapp

**Comment by rex-zsd** [comment]
`placeholder-style` 并不支持所有的 css 样式的。这个请参考小程序官方文档哈。
对于这个属性 vant weapp 这边只是透传。
