### ISSUE TITLE
[Bug Report] 自定义tabbar

### ISSUE THREAD

**Issue by JImumu** [youzan/vant-weapp#3916]
### 设备
开发工具

### VantWeapp 版本
1.6.4

### 基础库版本
2.14.1

### 请提供核心代码片段链接
https://developers.weixin.qq.com/s/tC4f5XmO7Xmh

### 描述问题
切换页面后，tabbar的active状态不对

**Comment by rex-zsd** [comment]
非组件 bug，用法有误。
关于自定义 tabbar，直接参考文档中的[代码片段](https://youzan.github.io/vant-weapp/#/tabbar#jie-he-zi-ding-yi-tabbar)即可哈。

**Comment by DingXuefeng** [comment]
我也遇到同样的问题了。解决办法是再onShow()里面添加`this.getTabBar().init();`. 采用的是custom-tab-bar模式。
