### ISSUE TITLE
[Bug Report] van-search 无法点击问题

### ISSUE THREAD

**Issue by liuhonbin** [youzan/vant-weapp#3917]
### 设备
iOS

### VantWeapp 版本
1.6.4

### 基础库版本
2.13.1

### 请提供核心代码片段链接
https://gitee.com/liudachu/vant-search-bug.git

### 描述问题
我在iOS上面使用这个控件，是在手机上面输入搜索关键字后进行一个页面跳转，然后在返回到有这个搜索控件的页面后，这个页面的搜索框无法点击聚焦，让我再次输入值，只能重启小程序，这个搜索框才能再次使用，但是我在微信开发工具里面没有遇到这个问题

**Comment by rex-zsd** [comment]
试了一下，使用原生 input 也可以复现，应该不是 vant weapp 的问题，可以去微信开发者社区咨询一下哈。

```html
<input placeholder="请输入案件号或手机号" />
```

```js
Page({
  onLoad() {
    setTimeout(() => {
      wx.navigateTo({
        url: '../searchInfo/searchInfo?vaule=',
      });
    }, 5000);
  }
});
```
