### ISSUE TITLE
集成到小程序使用时，涉及到上拉或者下拉还有弹框的组件。拖动遮罩层以外的区域底部还是会跟着滚动

### ISSUE THREAD

**Issue by bxwl** [youzan/vant-weapp#3918]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater?repo=VantWeapp

https://user-images.githubusercontent.com/33548468/103273160-9b880880-49f9-11eb-9e28-706c1284c49b.mp4

**Comment by rex-zsd** [comment]
从组件库的角度目前无解，可以查看 [文档说明](https://youzan.github.io/vant-weapp/#/popup#zu-jian-gun-dong-chuan-tou-gai-zen-me-jie-jue)
