### ISSUE TITLE
DatetimePicker bindchange事件延迟问题（Android）

### ISSUE THREAD

**Issue by kelly-yjx** [youzan/vant-weapp#3920]
![code](https://user-images.githubusercontent.com/39786949/103337981-e49e9200-4ab7-11eb-8419-145ca91fdc56.png)
文件：miniprogram_npm@vant\weapp\datetime-picker\index.js
`return this.set({ innerValue: value })
      .then(function () {
        return _this.updateColumns();
       })
       .then(function () {
        return picker.setValues(values);
       })`
使用this.set的原因是什么，因为this.set()是promise函数所以会出现调用事件出现延迟，我把它改为this.setDate()再回调.then里面的方法change事件暂时不会出现延迟了；不知道这样改会不会出现其他的问题

**Comment by rex-zsd** [comment]
小程序里的数据传递都是异步逻辑，出现延迟是正常的。
这样改可能会造成数据错误哈。

**Comment by LCBbest** [comment]
> 小程序里的数据传递都是异步逻辑，出现延迟是正常的。
> 这样改可能会造成数据错误哈。

那有什么好的解决方法，用户选择时间后 不会等待的。
