### ISSUE TITLE
[Bug Report] van-dialog组建确认按钮字体颜色问题

### ISSUE THREAD

**Issue by Caotudou** [youzan/vant-weapp#3922]
### 设备
移动设备

### VantWeapp 版本
1.6.4

### 基础库版本
2.11.0

### 如果是 UI 问题，截图链接（多图回车分隔）

![截图](https://i.loli.net/2020/12/30/94fd8hnuF2Py5Os.png)

![截图](https://i.loli.net/2020/12/30/sQcZN5xMJutH8bY.png)

![截图](https://i.loli.net/2020/12/30/Nd7TVJg8KlAuUbF.png)

### 请提供核心代码片段链接
无

### 描述问题
文档上默认的颜色和实际代码中的不一致

**Comment by rex-zsd** [comment]
文档错误，将会在下版本更新
