### ISSUE TITLE
1.6.4 vant weapp Area 省市区选择 app 不显示 小程序正常

### ISSUE THREAD

**Issue by lc666666432** [youzan/vant-weapp#3923]
1.6.4 vant weapp Area 省市区选择 app 不显示 小程序正常

**Comment by rex-zsd** [comment]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater?repo=VantWeapp
