### ISSUE TITLE
无法获取下拉菜单选中的值

### ISSUE THREAD

**Issue by z1450** [youzan/vant-weapp#3926]
<van-dropdown-menu >
                    <van-dropdown-item value="{{ value1 }}" options="{{ option1 }}" bind:change="onSwitch1Change"/>
     </van-dropdown-menu>
 option1: [
      { text: '全部商品', value: 0 },
      { text: '新款商品', value: 1 },
      { text: '活动商品', value: 2 },
    ],
我想获取下拉菜单选中 text 怎么获取

**Comment by rex-zsd** [comment]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater?repo=VantWeapp

**Comment by z1450** [comment]
<van-dropdown-item value="{{ value1 }}" options="{{ option1 }}" />
怎么监听 下拉选框列表的变化
