### ISSUE TITLE
van-tabs下划线不居中

### ISSUE THREAD

**Issue by zoubihai** [youzan/vant-weapp#3930]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater?repo=VantWeapp
![image](https://user-images.githubusercontent.com/19750129/103506679-48e69a80-4e98-11eb-9c7e-e998b06cae7f.png)
当切换点击之后正常了
![image](https://user-images.githubusercontent.com/19750129/103506720-63b90f00-4e98-11eb-974c-505fa3be3cf6.png)

**Comment by rex-zsd** [comment]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater?repo=VantWeapp
