### ISSUE TITLE
下拉菜单建议

### ISSUE THREAD

**Issue by wh2271222402** [youzan/vant-weapp#3931]
在下拉菜单中自定义内容，当内容有改变时，下拉菜单标题的颜色能保持和展开一致，或者能有一个属性控制下拉菜单的标题颜色

**Comment by rex-zsd** [comment]
使用 `--dropdown-menu-title-active-text-color` 与 `--dropdown-menu-option-active-color` 变量即可自定义哈，具体查看 [定制主题](https://youzan.github.io/vant-weapp/#/theme)
