### ISSUE TITLE
[Bug Report] van-field type=textarea输入之后内容有时候显示有时候不显示且无法聚焦

### ISSUE THREAD

**Issue by tengerfly** [youzan/vant-weapp#3934]
### 设备
ios，安卓都有发生

### VantWeapp 版本
1.6.4

### 基础库版本
2.9.4

### 如果是 UI 问题，截图链接（多图回车分隔）

![截图](https://sm.ms/image/neoyFX1K3DbrPQu)

### 请提供核心代码片段链接
https://gist.github.com/tengerfly/b4e16a571a3975a8e11f2fcdb10ba983

### 描述问题
图片中的故障现象是已经输入了内容的 查看wxml显示value是有值的  但是页面是没有的
并且聚焦的时候无法聚焦  聚焦会键盘弹起然后又隐藏

**Comment by rex-zsd** [comment]
用微信开发者上传一下可复现的代码片段，并提供下可复现的设备型号哈。
