### ISSUE TITLE
微信中能否增加popover

### ISSUE THREAD

**Issue by PLONGJ** [youzan/vant-weapp#3935]
目前web端3.0 已经有popover，请问官方大神，能否微信端也能支持popover组件

**Comment by chenjiahan** [comment]
微信里不太好实现，暂时不计划支持

**Comment by xiaosa66** [comment]
> 微信里不太好实现，暂时不计划支持

请问坑在哪里呢？我们产品想要个小弹窗，我现在说服不了他改用其他交互🤣

**Comment by chenjiahan** [comment]
小程序里实现 Popover 的定位计算不太方便呢，如果是直接固定位置的话倒没问题

**Comment by xiaosa66** [comment]
感谢 👍
