### ISSUE TITLE
微信小程序图标问题

### ISSUE THREAD

**Issue by Nick091608** [youzan/vant-weapp#3936]
### 设备
iPhone11

### VantWeapp 版本
1.6.4

### 基础库版本
1.7.0

### 请提供核心代码片段链接
https://youzan.github.io/vant-weapp/#/icon

### 描述问题
开始以为代码问题，经研究发现是weapp的delete-o这个图标的问题，使用<van-icon name="delete-o" />内置delete-o图标在微信小程序端不显示，换个其他的name都能正常显示，微信开发者工具也不显示

**Comment by rex-zsd** [comment]
1.6.4 版本是有 `delete-o` 这个图标的，未提供代码片段，无法进一步排查，推测是组件库版本问题，升级到最新版本看下哈。
