### ISSUE TITLE
progress在不同vant-weapp版本下的表现不一，高版本出现问题

### ISSUE THREAD

**Issue by xlfz123** [youzan/vant-weapp#3937]
### 设备
iphonexs

### VantWeapp 版本
1.6.3

### 基础库版本
2.10.3

### 如果是 UI 问题，截图链接（多图回车分隔）

![weapp107.jpeg](https://i.loli.net/2021/01/05/voYZTCQlKp3z924.jpg)

![weapp163.jpeg](https://i.loli.net/2021/01/05/rQ76mznZHdbgXaN.jpg)

### 请提供核心代码片段链接
https://github.com/youzan/vant-weapp/tree/dev/packages/progress

### 描述问题
相同的逻辑代码，在旧版本1.0.7中，progress可以使得文字百分比部分和progress高度一致（weapp107.jpeg），但是新版本中文字百分比部分和progress却不同高度，显示不一致（weapp163.jpeg）。

**Comment by rex-zsd** [comment]
使用的代码片段请提供一下哈

**Comment by xlfz123** [comment]
<view style="padding: 50rpx 0 0 0; width:100%;">
          <van-progress style="" percentage="{{percentWarn}}" color="#ff6666" pivot-text="{{pivotWarn}}" stroke-width="{{strokeWidth}}" track-color="#F8F8F8"/>
          <van-progress style="" percentage="{{percentRun}}" color="#3bafda" pivot-text="{{pivotRun}}" stroke-width="{{strokeWidth}}" track-color="#F8F8F8"/>
          <van-progress style="" percentage="{{percentTotal}}" color="#8cc152" pivot-text="{{pivotTotal}}" stroke-width="{{strokeWidth}}" track-color="#F8F8F8"/>
</view>



data: {
    //tabbar
    activeTabbar: 0,    
    hiddenSection0: false,
    hiddenSection1: true,
    hiddenSection2: true,
    hiddenSection3: true,
    //第一页
    //......
    percentWarn: 10,
    percentRun: 10,
    percentTotal: 100,
    pivotWarn: '报警:' + devValue.pracData.warnSec,
    pivotRun: '完成:' + devValue.pracData.runSec,
    pivotTotal: '计划:' + devValue.pracData.totalSec,
    strokeWidth: 25,
    //第二页
    //......  },


onReady: function () {
    var that = this;

    wx.getSystemInfo({
      success: function (res) {
        console.log(res);

        //初始化屏幕尺寸          
        screenHeight = res.windowHeight;
        screenWidth = res.windowWidth;


        //设置progress StrokeWidth
        var pxPerRpx = screenWidth / 750;
        that.setData({ strokeWidth: 80*pxPerRpx });             
        

        
        //更新显示
        that.updateShow();

        
        that.startConnect();
      }
    });
  },



               that.setData({
                percentTotal: 100,
                pivotWarn: '报警:' + warnSec,
                pivotRun: '完成:' + runSec,
                pivotTotal: '计划:' + totalSec,
              })

              var percentWarn = Math.round(warnSec * 100 / totalSec);
              if (percentWarn > 10) {
                that.setData({ percentWarn: percentWarn });
              }else{
                that.setData({ percentWarn: 10 });
              }

              var percentRun = Math.round(runSec * 100 / totalSec);
              if (percentRun > 10) {
                that.setData({ percentRun: percentRun });
              }else{
                that.setData({ percentRun: 10 });
              }

              if(that.data.optionTrainValue != totalSec){
                that.setData({optionTrainValue: totalSec});
              }

**Comment by rex-zsd** [comment]
旧版本是存在 bug 的，pivot 元素位置错误，导致你之前可以这样使用组件，1.6.3 之后已经修复了 bug。

**Comment by rex-zsd** [comment]
如果还想应用这样的样式，需要自行覆盖 pivot 元素的样式，可以查阅一下 [样式覆盖](https://youzan.github.io/vant-weapp/#/custom-style) 文档

**Comment by xlfz123** [comment]
谢谢你的回复。说实话，我对HTML，CSS这些不熟，写样式也是都参考你们代码写的。所以我计划还是用1.0.7版本开发。
