### ISSUE TITLE
[Bug Report] Dialog组件配置项无效

### ISSUE THREAD

**Issue by ding-love-yu** [youzan/vant-weapp#3938]
### 设备
小程序开发者工具

### VantWeapp 版本
1.6.4

### 基础库版本
2.14.1

### 请提供核心代码片段链接
https://sm.ms/image/lh9LnxdzOtRp8JN
https://sm.ms/image/gHonJxVCIRe67YG

### 描述问题
文档说明"确认""按钮默认颜色是蓝色的,但是现在是红色的,经过配置项配置也不起作用,效果如下述链接图中所示:
https://sm.ms/image/lh9LnxdzOtRp8JN
https://sm.ms/image/gHonJxVCIRe67YG

**Comment by Candane** [comment]
use-title-slot配置后无效，use-slot可以正常使用，有碰到这个问题吗

**Comment by rex-zsd** [comment]
设置了 `title` 时 `use-title-slot` 不生效的哈。

**Comment by rex-zsd** [comment]
`confirm-button-color` 是组件参数而非方法参数，在 Dialog 方法中是无效的。
默认颜色目前是蓝色，文档未修改，将在下版本中同步修改。

**Comment by rex-zsd** [comment]
#3925 已修正，将在下版本发布文档

**Comment by ding-love-yu** [comment]
> `confirm-button-color` 是组件参数而非方法参数，在 Dialog 方法中是无效的。
> 默认颜色目前是蓝色，文档未修改，将在下版本中同步修改。

我这边使用的时候怎么默认按钮的颜色是红色的呢?

**Comment by Candane** [comment]
我默认也是红色发自我的荣耀手机-------- 原始邮件 --------发件人： ding-love-yu <notifications@github.com>日期： 2021年1月7日周四 10:04收件人： youzan/vant-weapp <vant-weapp@noreply.github.com>抄送： candane <396785031@qq.com>, Comment <comment@noreply.github.com>主    题： Re: [youzan/vant-weapp] [Bug Report] Dialog组件配置项无效 (#3938)



confirm-button-color 是组件参数而非方法参数，在 Dialog 方法中是无效的。

默认颜色目前是蓝色，文档未修改，将在下版本中同步修改。



我这边使用的时候怎么默认按钮的颜色是红色的呢?

**Comment by Candane** [comment]
并没有设置title，最后我使用use-slot然后在自己重新布局解决了发自我的荣耀手机-------- 原始邮件 --------发件人： rex <notifications@github.com>日期： 2021年1月7日周四 10:00收件人： youzan/vant-weapp <vant-weapp@noreply.github.com>抄送： candane <396785031@qq.com>, Comment <comment@noreply.github.com>主    题： Re: [youzan/vant-weapp] [Bug Report] Dialog组件配置项无效 (#3938)

设置了 title 时 use-title-slot 不生效的哈。

**Comment by rex-zsd** [comment]
> > `confirm-button-color` 是组件参数而非方法参数，在 Dialog 方法中是无效的。
> > 默认颜色目前是蓝色，文档未修改，将在下版本中同步修改。
> 
> 我这边使用的时候怎么默认按钮的颜色是红色的呢?

默认就是红色，文档修正 pr 已合并，将在下版本发布。

**Comment by rex-zsd** [comment]
> 并没有设置title，最后我使用use-slot然后在自己重新布局解决了发自我的荣耀手机-------- 原始邮件 --------发件人： rex <notifications@github.com>日期： 2021年1月7日周四 10:00收件人： youzan/vant-weapp <vant-weapp@noreply.github.com>抄送： candane <396785031@qq.com>, Comment <comment@noreply.github.com>主 题： Re: [youzan/vant-weapp] [Bug Report] Dialog组件配置项无效 (#3938) 设置了 title 时 use-title-slot 不生效的哈。 —You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.

可以重新提个 issue，提供完整的代码片段和复现示意图哈。

**Comment by rex-zsd** [comment]
> 并没有设置title，最后我使用use-slot然后在自己重新布局解决了发自我的荣耀手机-------- 原始邮件 --------发件人： rex <notifications@github.com>日期： 2021年1月7日周四 10:00收件人： youzan/vant-weapp <vant-weapp@noreply.github.com>抄送： candane <396785031@qq.com>, Comment <comment@noreply.github.com>主 题： Re: [youzan/vant-weapp] [Bug Report] Dialog组件配置项无效 (#3938) 设置了 title 时 use-title-slot 不生效的哈。 —You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.

一行文字就指望找到问题，不限时哈。
