### ISSUE TITLE
[Bug Report] 【急急急】返回上一页面时，van-field卡顿或直接点不动

### ISSUE THREAD

**Issue by huangjinhui123** [youzan/vant-weapp#3939]
### 设备
ios

### VantWeapp 版本
1.6.4

### 基础库版本
2.14.1

### 如果是 UI 问题，截图链接（多图回车分隔）

![截图](https://sm.ms/image/P9cxH5ZQo8wTAY1)

![截图](https://sm.ms/image/9cgpsvz247ZXAKt)

### 请提供核心代码片段链接
https://github.com/huangjinhui123/vant-help2/blob/main/README.md

### 描述问题
1.问题描述图片在我提供的github项目地址中。
2.简单说，就是我从A页面跳转到B页面，然后从B页面返回的时候，A页面的数据框就有点卡，再次跳转到B页面，然后再返回A页面，A页面的输入框就点不动了。

**Comment by mw248** [comment]
在IOS上同样遇到该问题，field出现无法点进去输入

**Comment by huangjinhui123** [comment]
是啊，都急死了。项目马上就上线，我们就用的vant，领导成天崔，现在换根本来不及，我以为我用法有问题，刚刚建立了一个新的项目，什么都没有就一个首页，一个默认的日志页面，来回跳转结果输入框直接点不动了。

**Comment by rex-zsd** [comment]
这个场景下原生 input 就是有问题的，上周刚有同样的 issue 提上来过。

**Comment by rex-zsd** [comment]
见 #3917
