### ISSUE TITLE
页面【pages/icon/index]错误Error: module "dist/@vant/icons/src/config" is not defined

### ISSUE THREAD

**Issue by yyget** [youzan/vant-weapp#3942]
win10 
vant-weapp 1.6.4
小程序基础课2.8.1

import icons from '../../dist/@vant/icons/src/config';
这里报错了
运行了下边的命令，还是报错
npm init
npm install --production
npm i @vant/weapp -S --production

**Comment by yyget** [comment]
dist 文件也拷贝到小程序目录了，还是这个问题

**Comment by rex-zsd** [comment]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater?repo=VantWeapp
