### ISSUE TITLE
uploader component can not work on iPhone tablet

### ISSUE THREAD

**Issue by 549773668** [youzan/vant-weapp#3943]
### 设备
iPhone

### VantWeapp 版本
1.6.3

### 基础库版本
2.12.2

### 请提供核心代码片段链接
https://gist.github.com/549773668/c7f5a50db312eeea25575a3399170935

### 描述问题
Uploader component can not work on iPhone tablet. And I found that the sourceType in wx.chooseImage was an empty array. The source code is in uploader/utils.js. After I changed the sourceType to ['album', 'camera'], a fixed value, it works.

**Comment by rex-zsd** [comment]
`sourceType` 取自传入的 `capture` 参数，默认值即为 `['album', 'camera']`。
由于没有提供代码片段，无法确定是你传入的 `capture` 有误还是桌面版微信的 prop 默认值不起作用。

**Comment by 549773668** [comment]
我这边是安卓和模拟器都没问题，iPhone真机就不能用，我看到capture进来为空数组。

**Comment by 549773668** [comment]
解决了，关了吧，开发自己设置了capture属性...

**Comment by xinyi61** [comment]
> 解决了，关了吧，开发自己设置了capture属性...

能分享下解决方案吗？遇到同样的问题
