### ISSUE TITLE
[Bug Report] Dialog use-title-solt无效

### ISSUE THREAD

**Issue by Candane** [youzan/vant-weapp#3944]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

# 设备

小程序开发者工具

# VantWeapp 版本

1.6.3

# 基础库版本

2.13.2

# 核心代码片段

## 使用title情况

![title](https://i.loli.net/2021/01/07/kGHBdqwJs5YNUxg.jpg)

## 使用use-title-slot情况

![use-title-slot](https://i.loli.net/2021/01/07/uFnTUm124kH5CKp.jpg)

## 最终使用use-slot实现效果

![dialog](https://i.loli.net/2021/01/07/gWtH8JZOdi3wMnk.jpg)

**Comment by rex-zsd** [comment]
姿势问题

```html
<van-dialog
  use-slot
  use-title-slot
  show="{{ show }}"
>
  <view>content</view>
  <view slot="title">title</view>
</van-dialog>
```

**Comment by Candane** [comment]
> 姿势问题
> 
> ```
> <van-dialog
>   use-slot
>   use-title-slot
>   show="{{ show }}"
> >
>   <view>content</view>
>   <view slot="title">title</view>
> </van-dialog>
> ```

好的，谢谢，看了文档使用use-slot，以为只设置use-title-slot的情况下，默认slot也是use-title-slot
