### ISSUE TITLE
[Feature Request] 请问通过npm方式引入@vant/weapp，如何在js文件中使用Dialog或Notify

### ISSUE THREAD

**Issue by felixfujing** [youzan/vant-weapp#3945]
### 这个功能解决了什么问题
请问通过npm方式引入@vant/weapp，如何在js文件中使用Dialog或Notify。基础库版本：2.14.1。@vant/weapp版本：^1.6.4。
// import Dialog from '/miniprogram_npm/@vant/weapp/dialog/dialog';
以上这种引入方式不会触发Dialog.confirm({})

### 建议的API是什么样的
如题所示，请问该怎么解决？？

**Comment by rex-zsd** [comment]
请查看 [文档](https://youzan.github.io/vant-weapp/#/dialog)

**Comment by felixfujing** [comment]
import Dialog from '../../miniprogram_npm/@vant/weapp/dialog/dialog';

// Dialog.alert({
    //   title: '标题',
    //   message: '弹窗内容',
    //   theme: 'round-button',
    // }).then(() => {
    //   // on close
    // });

这样引用都弹不出来

**Comment by yoyo837** [comment]
> 请查看 [文档](https://youzan.github.io/vant-weapp/#/dialog)

文档是看了, path/to 指哪里呀?
