### ISSUE TITLE
[Bug Report] 在scroll-view中开启滑动特效，Field样式出现错误

### ISSUE THREAD

**Issue by WEI4D** [youzan/vant-weapp#3948]
### 设备
IPHONE XR IOS 13

### VantWeapp 版本
1.6.4

### 基础库版本
2.12.2

### 如果是 UI 问题，截图链接（多图回车分隔）

![截图](https://sm.ms/delete/QbgUuoBYxztOwK7IhCRDrf2s4v)

### 请提供核心代码片段链接
https://gitee.com/chenweid/codes/vrxbtwjhzqsyekpdca3l279

### 描述问题
1.scroll-view开启滑动特效
2.使用scroll-view的scroll-into-view属性自动滑动
3.滑动到指定位置后，返回使用Field组件的页面
4.Field组件显示错误

**Comment by rex-zsd** [comment]
图破了，代码链接也打不开
请使用 微信开发者工具 上传代码片段哈
