### ISSUE TITLE
[Bug Report] Area 省市区选择

### ISSUE THREAD

**Issue by guosenlin1026** [youzan/vant-weapp#3950]
### 设备
安卓 ios

### VantWeapp 版本
1.6.4

### 基础库版本
1.6.4

### 请提供核心代码片段链接
https://github.com/youzan/vant-demo

### 描述问题
Area 省市区组件，三级联动情况下，如第二级是多个时，二级数量小于6个时，导致二级不能滑动。

**Comment by rex-zsd** [comment]
提供下代码片段哈
