### ISSUE TITLE
[Bug Report] Field组件border属性无效；文档错误

### ISSUE THREAD

**Issue by microkof** [youzan/vant-weapp#3951]
### 设备
开发者工具、RedMi Note 8

### VantWeapp 版本
1.6.4

### 基础库版本
2.14.1

### 请提供核心代码片段链接
https://youzan.github.io/vant-weapp/#/field

### 描述问题
虽然也想提供个链接，但真不知道写什么。

1. border默认是true，但并没有看到有border。加了\<van-cell-group\>当然是有边框，但是这又不是Field的边框。

2. Field的focus在开发者工具中无效，在真机有效。

3. 文档里“插入按钮”的范例里有个`center`属性，Field并没有这个属性。

**Comment by rex-zsd** [comment]
关于边框应该是存在误解，van-field 的 `border` 并不是全包围的边框，而是指下面的这条线
![image](https://user-images.githubusercontent.com/8767877/104981602-e36fdd80-5a43-11eb-8a7f-d496a22c1bee.png)

**Comment by rex-zsd** [comment]
如果需要全包围的边框，外面套一层 van-cell-group 即可

**Comment by rex-zsd** [comment]
`center` 属性是存在的，文档未列出，将在下版本修复
