### ISSUE TITLE
swipe里面放video，ios端新增的视频document.getElementById().play()无法播放

### ISSUE THREAD

**Issue by Rookie2333** [youzan/vant-weapp#3952]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater?repo=VantWeapp
lazy-render设为true或者新增swipe-item都无法在onChange()方法中通过代码让下一个视频播放，而列表中原有的视频却可以通过代码让它播放实现跟抖音一样的效果

**Comment by rex-zsd** [comment]
提错 issue 了？这里是 vant weapp 小程序组件库，没有 `document.getElementById().play()` 这种 API 的。
