### ISSUE TITLE
tabbar无法生成一个等高的占位元素，附小程序片段

### ISSUE THREAD

**Issue by a516117636** [youzan/vant-weapp#3953]
基于vant weapp官方的tabbar示例小程序片段，仅修改了元素“示例页面1”的高度，配置了fixed和placeholder属性都为true，发现最后一个“示例页面1”元素仍被tabbar遮挡。placeholder属性并未生成一个等高的占位元素。修改后的小程序片段如下。再不解决这个问题老板要发飙了。。。。下面是小程序片段：
https://developers.weixin.qq.com/s/i27Migmi7ond

**Comment by rex-zsd** [comment]
升级下版本吧，你用的版本太低了，不支持占位。

**Comment by a516117636** [comment]
> 升级下版本吧，你用的版本太低了，不支持占位。

请问您是说升级vant weapp还是小程序基础库？

**Comment by rex-zsd** [comment]
升级 vant weapp 组件库的版本

**Comment by a516117636** [comment]
> 升级 vant weapp 组件库的版本

亲测无效。升级vant weapp到最新版1.6.4后，使用微信官方开发工具重新构建，依旧无法生成等高占位元素。

**Comment by rex-zsd** [comment]
再上传一下代码片段吧

**Comment by a516117636** [comment]
> 再上传一下代码片段吧

我们的小程序使用NPM引入的vant weapp，官方示例通过什么方式没看太明白。目前来看确实无法生成等高占位元素，能否你自己试一下？或者更新官方文档tabbar的小程序片段。

**Comment by a516117636** [comment]
能解决吗这个问题？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？

**Comment by rex-zsd** [comment]
光看文字没法排查问题哈

**Comment by a516117636** [comment]
官方文档tabbar小程序片段用的vant weapp什么版本？能更新那个片段吗？

**Comment by a516117636** [comment]
官方示例通过什么方式引入的weapp也没说啊，我怎么改啊。

**Comment by a516117636** [comment]
你确定你那边能生成等高占位元素？？？？？还是在逗我玩？？？

**Comment by rex-zsd** [comment]
1.6.2 开始就支持了，请看 [更新日志](https://youzan.github.io/vant-weapp/#/changelog) 哈

**Comment by a516117636** [comment]
那能更新官方文档tabbar小程序片段吗，我看更新后的代码行吗

**Comment by rex-zsd** [comment]
ok 的，下版本将会更新 tabbar 的代码片段

**Comment by a516117636** [comment]
大约什么时候能更新？很急啊
