### ISSUE TITLE
[Bug Report] Icon组件里并没有“revoke”、“font-o”等图标

### ISSUE THREAD

**Issue by microkof** [youzan/vant-weapp#3955]
### 设备
开发者工具、RedMi Note 8

### VantWeapp 版本
1.6.4

### 基础库版本
2.14.1

### 请提供核心代码片段链接
https://youzan.github.io/vant-weapp/#/icon

### 描述问题
尽管文档里有revoke、font-o等图标的预览，但是代码里并没有提供。其他图标没有一一测试。不知道是不是我打开姿势有问题。

**Comment by rex-zsd** [comment]
图标库将在下版本更新哈

**Comment by rex-zsd** [comment]
1.6.5 已发布
