### ISSUE TITLE
postcss-pxtorem  搭配  vant    设置 rootValue = 75适配不了

### ISSUE THREAD

**Issue by Youngggg** [youzan/vant-weapp#3957]
rootValue 设置成75 之后  vant 组件样式缩小了一倍！ ，想处理成 75 （习惯写 750的设计稿），都不兼容！！

**Comment by rex-zsd** [comment]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater?repo=VantWeapp
