### ISSUE TITLE
weapp中van-tab在onLoad设置active，显示值改变但是tab标签显示依然默认第一个

### ISSUE THREAD

**Issue by zyh362048474** [youzan/vant-weapp#3958]
`<van-tabs id="tabs" active="{{ active }}" bind:change="selectChange" ellipsis="{{false}}" swipeable
        title-active-color="green" color="green" line-height="1px" line-width="{{lineWidth}}px">
        <van-tab title="预约中{{ active }}"></van-tab>
        <van-tab title="处理中"></van-tab>
        <van-tab title="已完成"></van-tab>
    </van-tabs>`

  onLoad: function (options) {
        // 通过传值选择默认显示tab
        var index = options.index
        this.setData({
            active: index
        })
    }

不论是通过name还是索引index都无法改变data中默认的active显示

**Comment by marquisXuan** [comment]
我也是遇到了同样的问题=。=

**Comment by marquisXuan** [comment]
vant 版本号
1.64
1.65

**Comment by marquisXuan** [comment]
解决了。
@zyh362048474 

能找到tabs/index.js 这个文件。找到 setCurrentIndexByName 方法。里面做一个判断。我这么处理后，就正常工作了。
```js
setCurrentIndexByName: function (name) {
            var _a = this.children,
                children = _a === void 0 ? [] : _a;
            var matched = children.filter(function (child) {
                let computedName = child.getComputedName();
                return (computedName != null ? computedName.toString() : "") === name;
            });
            if (matched.length) {
                this.setCurrentIndex(matched[0].index);
            }
        },
```

**Comment by marquisXuan** [comment]
源码文件 ts 版的是这样

```ts
setCurrentIndexByName(name) {
      const { children = [] } = this;
      const matched = children.filter((child: TrivialInstance) => {
        const computedName =
          child.getComputedName() !== null
            ? child.getComputedName().toString()
            : '';
        const paramName = name !== null ? name.toString() : '';
        return computedName === paramName;
      });
```
