### ISSUE TITLE
[Bug Report] vant-dailog 组件模式调用，before-close属性需要在data中定义，那么怎么实现点击确定，表单验证后关闭dailog呢？

### ISSUE THREAD

**Issue by yangyuanftl** [youzan/vant-weapp#3959]
### 设备
无

### VantWeapp 版本
1.6.4

### 基础库版本
2.14.1

### 请提供核心代码片段链接
https://gist.github.com/yangyuanftl/25735ff22185c3d33fc0dc261c6b4b60

### 描述问题
vant-dailog 组件模式调用，before-close属性需要在data中定义，那么怎么实现点击确定，表单验证后关闭dailog呢？

**Comment by rex-zsd** [comment]
业务逻辑请自己实现哈，我们无法帮你解决。
`data` 中定义和 `methods` 中定义的方法一样都是可以访问 `this` 的，没有什么差别。

**Comment by yangyuanftl** [comment]
> 业务逻辑请自己实现哈，我们无法帮你解决。
> `data`中定义和`methods`中定义的方法一样都是可以访问`this`的，没有什么区别。

data中怎么调用this

**Comment by rex-zsd** [comment]
…………

```js
Page({
	data: {
		beforeClose() {
                         this.doSomeThing();
			return false;
		}
	},
       doSomeThing() {
       }
});
```

**Comment by yangyuanftl** [comment]
> …………
> 
> ```js
> Page({
> 	data: {
> 		beforeClose() {
>                          this.doSomeThing();
> 			return false;
> 		}
> 	},
>        doSomeThing() {
>        }
> });
> ```

访问不到this对象的

**Comment by effortcheep** [comment]
> > …………
> > ```js
> > Page({
> > 	data: {
> > 		beforeClose() {
> >                          this.doSomeThing();
> > 			return false;
> > 		}
> > 	},
> >        doSomeThing() {
> >        }
> > });
> > ```
> 
> 访问不到this对象的


有一个折中的方法
> > ```js
> > Page({
> > 	data: {
> > 		beforeClose(action) {
> >                   if (action === 'confirm') {
>>                          return false;
>>                    }
> > 			return true;
> > 		}
> > 	},
>>  methods: {
>>   onConfirm() {
>>         if (不通过校验) { 
>>         } else {
>>            // 处理事情 然后  把 dailog 的show 设置成 false 
>>         }
>>   }
>>  }
> > });
> > ```

**Comment by shady-xia** [comment]
before-close 中确实访问不到 this， 这一点很不方便，我遇到这种需求都是手写的按钮

**Comment by yezibao1991** [comment]
> before-close 中确实访问不到 this， 这一点很不方便，我遇到这种需求都是手写的按钮

```
beforeClose="{{changeNickname}}"

onLoad: function (options) {
    this.setData({
      changeNickname: this.changeNickname.bind(this),
    })
  },
```

这个就没问题了

**Comment by rex-zsd** [comment]
我记得之前是可行的，但现在确实访问不到 `this` 了，不好意思。

可以用上面的方法，通过 `setData` 将 `beforeClose` 设置到 data 中。

**Comment by BlueGalaxyForest** [comment]
我觉得有个非常好的办法你可以试一下:
wxml:
![image](https://github.com/youzan/vant-weapp/assets/95743709/7993e727-0e63-43f2-9511-c96d1fe330da)

js->onLoad(options)钩子函数
![image](https://github.com/youzan/vant-weapp/assets/95743709/5c2f69cc-740b-422f-ba31-b0731c037695)

js->beforeClose(action)自定义函数,tips:这个函数与onLoad钩子函数同级,无须写到data:{}里面
![image](https://github.com/youzan/vant-weapp/assets/95743709/12888344-3acb-418c-9514-25d13eea690a)

**Comment by BlueGalaxyForest** [comment]
其中show="{{showDialog}}"的showDialog你需要在data:{}里面定义,例如点击一个按钮后,把showDialog变量设为true,才能显示Dialog组件,记住代码中注意下面的情况,否则我的示例会失效:
1. 删除 import Dialog from '@vant/weapp/dialog/dialog'; 这条语句,因为Dialog的相关函数优先级比beforeClose函数更高,会导致beforeClose明明写在data:{}也不触发:
```js
// 代码中凡是类似这样的代码全部删掉,你需要把控制权掌握在你的手里,否则你的beforeClose会失效
Dialog.confirm({
  title: '标题',
  message: '弹窗内容',
})
  .then(() => {
    // on confirm
  })
  .catch(() => {
    // on cancel
  });
```
