### ISSUE TITLE
[Bug Report] 现在的创建画布接口已经被废弃,微信更新了新的接口

### ISSUE THREAD

**Issue by 5097677** [youzan/vant-weapp#3960]
### 设备
手机

### VantWeapp 版本
1.6.4

### 基础库版本
2.14.3

### 请提供核心代码片段链接
https://developers.weixin.qq.com/s/7Sh81lmL7Lno

### 描述问题
现在的创建画布接口已经被废弃,微信更新了新的接口

**Comment by rex-zsd** [comment]
之前已经适配了的，唯一用到 canvas 的 circle 组件在开启 `type="2d"` 时即会使用新版画布 API 哈。

**Comment by 5097677** [comment]
> 之前已经适配了的，唯一用到 canvas 的 circle 组件在开启 `type="2d"` 时即会使用新版画布 API 哈。

`<van-circle
	value="{{ info_detail.percentage }}"
	layer-color="#eeeeee"
	color="#1088FF"
	text="{{ info_detail.percentage_text }}%"
	size="70"
	type="2d"
/>`

type="2d"是这样用法吗？
加上之后,进度圈好像是被绝对定位定死了,会跟随着页面滑动
