### ISSUE TITLE
微信小程序啥用vant-dialog，点击确定，如何阻止弹出关闭

### ISSUE THREAD

**Issue by panhongfeng** [youzan/vant-weapp#3961]
wxml：
```html
<van-dialog 
id="van-dialog" 
use-slot 
title="用户须知" 
show="{{ showDialog }}"
beforeClose="beforeClose">
  <view class="dialog-content">
  </view>
</van-dialog>
```
js：这个方法写在了Page页面下，与data同级
```js
beforeClose() {
          new Promise((resolve) => {
            setTimeout(() => {
              if (action === 'confirm') {
                resolve(true);
              } else {
                // 拦截取消操作
                resolve(false);
              }
            }, 1000);
          });
        },
```
无怎么怎么搞都无法阻止窗口关闭，请问是哪里出了问题。

**Comment by rex-zsd** [comment]
请按 issue 模板提供必要的信息哈，基础库版本、组件库版本等

**Comment by rex-zsd** [comment]
这样的写法是错的，请看 [文档](https://youzan.github.io/vant-weapp/#/dialog#yi-bu-guan-bi) 哈。

```html
<van-dialog 
id="van-dialog" 
use-slot 
title="用户须知" 
show="{{ showDialog }}"
before-close="{{ beforeClose }}">
  <view class="dialog-content">
  </view>
</van-dialog>
```

```js
Page({
  data: {
    beforeClose() {
          new Promise((resolve) => {
            setTimeout(() => {
              if (action === 'confirm') {
                resolve(true);
              } else {
                // 拦截取消操作
                resolve(false);
              }
            }, 1000);
          });
        },
  }
})
```

**Comment by panhongfeng** [comment]
按照您给的案例，依旧阻止不了关闭，debugger beforeClose 根本就不进去，点了确定，立马就关闭了提示框，太难受了，你们有案例么。这个功能真饿太难受了。
`Page({

  /**
   * 页面的初始数据
   */
  data: {
    showDialog: false,
    background: ['/img/timg2.jpeg', '/img/timg2.jpeg', '/img/timg2.jpeg'],
    beforeClose(action) {
      debugger
      new Promise((resolve) => {
        setTimeout(() => {
          if (action === 'confirm') {
            resolve(true);
          } else {
            // 拦截取消操作
            resolve(false);
          }
        }, 1000);
      });
    },

  },`

页面很简单：，但就是不行，这个问题你们文档上根本就找不到，文档过了好多遍，难受啊
`<van-dialog 
id="van-dialog" 
use-slot 
title="用户须知" 
show="{{ showDialog }}"
before-close="{{ beforeClose }}">
  <view class="dialog-content">
  </view>
</van-dialog>`

**Comment by panhongfeng** [comment]
文档只有在js 引入dialog的时候去阻止，但是页面上直接写`van-dialog`的，怎么都阻止不了。

**Comment by citrusjunoss** [comment]
> 文档只有在js 引入dialog的时候去阻止，但是页面上直接写`van-dialog`的，怎么都阻止不了。

微信小程序的properties不支持传递function, 所以你传递的beforeClose 在dialog 接收一直未null

**Comment by ArmyMedalMei** [comment]
@citrusjunoss 

通过组件调用 Dialog 时，支持以下 Props:
beforeClose | 关闭前的回调函数，返回 false 可阻止关闭，支持返回 Promise | (action) => boolean \| Promise
-- | -- | --
但是在官方文档 中，确实有Props 是这样的，这个问题应该被打开

**Comment by citrusjunoss** [comment]
你可以提个pr帮他把文档优化下，我之前想搞来着，最近有点忙。

**Comment by ArmyMedalMei** [comment]
确实没有办法通过Props的方式阻止弹出框关闭

**Comment by ArmyMedalMei** [comment]
async-close="{{true}}" 属性上这样设置就可以手动进行关闭

**Comment by wangfpp** [comment]
我用手工Hank的方式解决了
他非要修改我父组件传进去的`show` 我就以其人之道还治其人之身
```javascript
 <van-dialog
      use-slot
      title="新增自定义商品"
      show="{{ showDialog }}"
      show-cancel-button
      bind:close="onClose"
      async-close="{{true}}"
      bind:confirm="confirmAddProduct"
      beforeClose="{{beforeCloseEvent}}"
      class="add_product_dialog"
    >

confirmAddProduct({detail}) {
    let { productForm } = this.data;
    let nameLen = productForm.value.length;
    if(!(nameLen > 0 && nameLen <= 20)) {
      this.setData({
        'productForm.errorMsg': "请输入20字以内的名称"
      })
     //这样操作会报错同时会有界面闪一下  但是整体功能是可以运行的
       detail.dialog.setData({
        show: true
      })
    }
  },
```
