### ISSUE TITLE
[Bug Report] 引入组件失败：miniprogram/app.json: ["usingComponents"]["van-button"]: "@vant/weapp/button/index" 未找到

### ISSUE THREAD

**Issue by MalavitaC** [youzan/vant-weapp#3962]
### 设备
开发者工具

### VantWeapp 版本
1.6.4

### 基础库版本
2.8.2

### 请提供核心代码片段链接
https://gist.github.com/MalavitaC/c1ae5d114c3f227b8b13e87acab1dff0

### 描述问题
![项目结构](https://user-images.githubusercontent.com/38742840/104608686-26852600-56bd-11eb-952d-f833cccab09c.png)
按照官方文档-快速上手操作后开发者工具报错：
> [ miniprogram/app.json 文件内容错误] miniprogram/app.json: ["usingComponents"]["van-button"]: "@vant/weapp/button/index" 未找到

**Comment by TheDavidZheng** [comment]
重新构建一下npm

**Comment by MalavitaC** [comment]
试过了，还是这个报错

**Comment by dingshangshang** [comment]
微信小程序官方得问题，至少有一年以上了，目前还没解决

**Comment by rex-zsd** [comment]
对于 typescript 的项目，在 1.03.2012120 版本的开发者工具上，按照快速上手的步骤操作，是可以正常开始项目的。

**Comment by rex-zsd** [comment]
看截图猜测，报错的原因是 npm 构建生成的 miniprogram_npm 目录没有在 miniprogram 目录内。
看下是否漏加了这段配置

![image](https://user-images.githubusercontent.com/8767877/105139494-5b680180-5b31-11eb-9d8d-c07246becefe.png)

**Comment by yoyo837** [comment]
![image](https://user-images.githubusercontent.com/6134547/143172466-3f43970c-e216-411d-b80c-c0c7e54f5382.png)


菜鸟问一下 path/to 也写上去吗?

**Comment by du0wen** [comment]
> 看截图猜测，报错的原因是 npm 构建生成的 miniprogram_npm 目录没有在 miniprogram 目录内。 看下是否漏加了这段配置
> 
> ![image](https://user-images.githubusercontent.com/8767877/105139494-5b680180-5b31-11eb-9d8d-c07246becefe.png)

加了这个配置后，要把默认在根目录生成的miniprogram_npm这个目录删除掉之后，再重新npm构建，就会成功，此时发现miniprogram_npm目录已经在miniprogram目录下出现，此时再重新编译，即可成功
