### ISSUE TITLE
ShareSheet里面有个openType:share,这怎么用啊

### ISSUE THREAD

**Issue by taotao6** [youzan/vant-weapp#3964]
调用不了微信分享啊

**Comment by rex-zsd** [comment]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater?repo=VantWeapp

**Comment by Simingchen** [comment]
遇到同样问题

**Comment by Simingchen** [comment]
openType:share 不可用 

openType | 按钮 open-type，可用于实现分享功能，可选值为 share
-- | --


<van-share-sheet
  show="{{ showShare }}"
  title="立即分享给好友"
  options="{{ options }}"
  bind:select="onSelect"
  bind:close="onClose"
/>
Page({
  data: {
    showShare: false,
    options: [
      { name: '微信', icon: 'wechat', openType: 'share' },
      

    ],
  },
