### ISSUE TITLE
小程序使用骨架屏问题

### ISSUE THREAD

**Issue by Yuiane** [youzan/vant-weapp#3966]
![image](https://user-images.githubusercontent.com/19179519/104819081-3b50ed80-5866-11eb-8730-1bb18199fad8.png)
需要请求对row的属性读取

**Comment by rex-zsd** [comment]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater?repo=VantWeapp
