### ISSUE TITLE
【样式问题】van-button

### ISSUE THREAD

**Issue by jFinong** [youzan/vant-weapp#3967]
http://vant-contrib.gitee.io/vant-issue-generater?repo=VantWeapp

通过computed.rootStyle生成的style和用户提供的customStyle 之间缺少分号

![image](https://user-images.githubusercontent.com/18418224/104848257-1a989e80-591f-11eb-9939-15d60e921a39.png)

**Comment by rex-zsd** [comment]
1.6.5 已修复
