### ISSUE TITLE
van-cell title无效

### ISSUE THREAD

**Issue by xiaomiza** [youzan/vant-weapp#3968]
使用IndexBar 索引栏， <van-cell title="文本" /> title里面的文字渲染不出来，有遇到同样情况的吗？ 
![Snipaste_2021-01-18_15-26-19](https://user-images.githubusercontent.com/34223918/104884669-b79c1b80-59a1-11eb-9fe2-a871ed3406b8.png)

**Comment by rex-zsd** [comment]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater?repo=VantWeapp

**Comment by rex-zsd** [comment]
看代码是 `van-cell` 组件未引入
