### ISSUE TITLE
[Feature Request] dialog的show是否应该内部控制？

### ISSUE THREAD

**Issue by citrusjunoss** [youzan/vant-weapp#3970]
### 这个功能解决了什么问题
dialog的show 应该完全交给父组件来控制的，数据单向流动，而在dialog/index.ts 中，为什么要操作show属性呢，这样就很难进行自主控制了显示隐层了。比如说目前的点击confirm内部实现了关闭，必须通过beforeClose或者asycClose 中止这个操作，然而beforeClose只能用于Function 调用。组件式调用无法使用，而asyncClose 终止后，按钮处于loading状态，无法恢复。

### 建议的API是什么样的
所以建议不要在组件内部操作props.

**Comment by rex-zsd** [comment]
`beforeClose ` 同时也是 prop，可以直接给组件传入的。
```html
<van-dialog before-close="{{ beforeClose }}" />
```

```js
Page({
  data: {
    beforeClose() {
      // do something
    }
  }
});
```

**Comment by suncunhu** [comment]
好烦啊，把show老老实实的交给用户去控制不行么？非要自作聪明

**Comment by suncunhu** [comment]
或者在文档上注释说明一下，show在confirm的时候是被组件控制了。

**Comment by wangfpp** [comment]
不太好的方式解决了这个问题
https://github.com/youzan/vant-weapp/issues/3961#issuecomment-863851704
