### ISSUE TITLE
带color属性的组件 在使用custom-style时候 color参数结尾必须带“;”封号。不然拼接会出错

### ISSUE THREAD

**Issue by ruoxiaodian** [youzan/vant-weapp#3974]
<img width="926" alt="WeChat75d8cf4c438f96c1af9bdf3b66c104fc" src="https://user-images.githubusercontent.com/28801943/104998674-95b89c80-5a66-11eb-8727-6a7cccfb7f56.png">

**Comment by rex-zsd** [comment]
上版本的 bug，1.6.5 已修复啦
