### ISSUE TITLE
[Bug Report] swipe-cell组件滑动后右或左边的单元格无样式

### ISSUE THREAD

**Issue by yik7707** [youzan/vant-weapp#3977]
### 设备
安卓

### VantWeapp 版本
1.6.5

### 基础库版本
2.14.3

### 如果是 UI 问题，截图链接（多图回车分隔）

![截图](https://sm.ms/image/Gib8HLlKWdroUsR)

### 请提供核心代码片段链接
https://gitee.com/yik7707/question-feedback/issues/I2DZR3

### 描述问题
swipe-cell组件滑动后右或左边的单元格无样式,，希望官方增加默认适合的样式

**Comment by rex-zsd** [comment]
slot 的样式是完全自定义的，组件不会增加样式的哈
