### ISSUE TITLE
[Bug Report] datetime-picker组件不显示toolbar

### ISSUE THREAD

**Issue by sculover** [youzan/vant-weapp#3978]
### 设备
微信开发者工具

### VantWeapp 版本
1.6.5

### 基础库版本
2.14.0

### 请提供核心代码片段链接
https://gist.github.com/sculover/c3f1a2a539bf374531daec434e02300c

### 描述问题
datetime组件 不显示toolbar

https://sm.ms/image/cVgaGdEJ5sbhXyC

**Comment by sculover** [comment]
![image](https://user-images.githubusercontent.com/2181686/105043284-4d1dd500-5aa0-11eb-96b8-57de4a28e431.png)
![image](https://user-images.githubusercontent.com/2181686/105043311-5a3ac400-5aa0-11eb-843f-7558eea83cb4.png)
有点不明白为什么这里要用template
在picker组件里，用了include，但是微信小程序官方文档include是这么说的
![image](https://user-images.githubusercontent.com/2181686/105043491-90784380-5aa0-11eb-8958-c8e4f8a842f2.png)
`include 可以将目标文件除了 <template/> <wxs/> 外的整个代码引入`
那就是说toolbar.wxml里的代码在引入的时候都被忽略了吧？

**Comment by Jintao-Qu** [comment]
picker也不显示tool-bar

**Comment by sculover** [comment]
> picker也不显示tool-bar

对的 datetime-picker最终还是引用的picker组件。

**Comment by rex-zsd** [comment]
1.6.5 有此 bug，将尽快在下版本修复哈

**Comment by rex-zsd** [comment]
#3973

**Comment by rex-zsd** [comment]
1.6.6 已修复了，忘记关闭 issue
