### ISSUE TITLE
微信小程序 中引入"van-dialog": "@vant/weapp/dialog/index"      报错

### ISSUE THREAD

**Issue by liuhu1172694787** [youzan/vant-weapp#3979]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater?repo=VantWeapp

"pages/index/@vant/weapp/dist/dialog/dialog.js" is not defined

但是点击Ctrl确实可以找到这个位置   但是就是报错

求解答

**Comment by liuhu1172694787** [comment]
![image](https://user-images.githubusercontent.com/26894635/105137975-307cae00-5b2f-11eb-98ea-c1622b05f502.png)

**Comment by liuhu1172694787** [comment]
![QQ截图20210120145354](https://user-images.githubusercontent.com/26894635/105138077-57d37b00-5b2f-11eb-92e1-59fbee091b1f.png)

**Comment by rex-zsd** [comment]
js 是不支持 npm 包的，只能使用相对路径。
如果需要这样引用的话需要改用 typescript 的。

**Comment by liuhu1172694787** [comment]
那可以请问一下，应该怎么引入呢？可以给举一个例子吗？

**Comment by bigmeow** [comment]
@liuhu1172694787 
tsconfig.json配置
```json
{
    "compilerOptions": {
        "paths": {
            "@vant/weapp/*": ["./node_modules/@vant/weapp/dist/*"]
        }
    }
}

```

使用时:
```ts
import Dialog from "@vant/weapp/dialog/dialog";
```

http://cheers-mp.com

**Comment by ghostcode** [comment]
> js 是不支持 npm 包的，只能使用相对路径。
> 如果需要这样引用的话需要改用 typescript 的。

官网的例子是不是应该把 dist 目录去掉。
