### ISSUE TITLE
sticky 使用offset-top小程序报错

### ISSUE THREAD

**Issue by zhuchangfeng** [youzan/vant-weapp#3980]
van-sticky offset-top="{{ navBarHeight }}"
其中 navBarHeight是一个数字，报错了
    if (offsetTop >= root.top) {
          _this.setDataAfterDiff({ fixed: true, height: root.height });
          _this.transform = 0;
        } else {
          _this.setDataAfterDiff({ fixed: false });
        }
这里报错了

**Comment by rex-zsd** [comment]
请按照 issue 格式补全一下信息哈

**Comment by zhuchangfeng** [comment]
感谢回复，感觉应该是基础库太高了我降低2.77就可以了

**Comment by rex-zsd** [comment]
好的哈
