### ISSUE TITLE
使用van-grid遇到问题

### ISSUE THREAD

**Issue by JIE-JIE-JIANG** [youzan/vant-weapp#3981]
在安卓手机上显示正常，微信开发工具模拟苹果手机也正常，但是在真正的手机上出现item被拉长的情况
![image](https://user-images.githubusercontent.com/51015520/105150473-c7516680-5b3f-11eb-910b-7fd53ae1a929.png)
正常显示如下
![image](https://user-images.githubusercontent.com/51015520/105150534-d9330980-5b3f-11eb-9dac-722d46e76eaa.png)
代码使用如下
![image](https://user-images.githubusercontent.com/51015520/105150585-e94ae900-5b3f-11eb-9ad0-881325aa0de4.png)

**Comment by rex-zsd** [comment]
![WechatIMG82](https://user-images.githubusercontent.com/8767877/105818648-21e03c00-5ff2-11eb-944c-99e77df899e7.jpeg)
demo 真机上未复现问题，看截图你有修改过组件的样式？没有提供这部分的代码没办法继续排查，可以自查一下哈。
