### ISSUE TITLE
Area 省市区选择

### ISSUE THREAD

**Issue by Lazy33** [youzan/vant-weapp#3983]
![1](https://user-images.githubusercontent.com/62047198/105178883-9125de00-5b63-11eb-98fd-9155c02d3758.jpg)

这里没有 逗号

![2](https://user-images.githubusercontent.com/62047198/105178866-8bc89380-5b63-11eb-8f04-37a1d658263b.png)

二级目录始终无法划到第一个选项
@vant 版本不清楚

**Comment by Lazy33** [comment]
![1](https://user-images.githubusercontent.com/62047198/105179021-c0d4e600-5b63-11eb-868a-aa12ce916c23.jpg)
![2](https://user-images.githubusercontent.com/62047198/105179025-c2061300-5b63-11eb-96c1-9542833dc294.png)

**Comment by Lazy33** [comment]
`
![1](https://user-images.githubusercontent.com/62047198/105179139-e661ef80-5b63-11eb-8dff-ddc2b6c5facb.jpg)
![2](https://user-images.githubusercontent.com/62047198/105179145-e82bb300-5b63-11eb-97f3-4f4db63cb16a.png)

`

**Comment by rex-zsd** [comment]
文档问题，下版本修复哈
