### ISSUE TITLE
[Bug Report] van-uploader preview-size capture 无效

### ISSUE THREAD

**Issue by yrz0816** [youzan/vant-weapp#3986]
### 设备
小米 k20

### VantWeapp 版本
1.0.0-beta.4

### 基础库版本
2.12.2

### 如果是 UI 问题，截图链接（多图回车分隔）

![截图](https://sm.ms/image/6Vq8JcztMQmDHax)

### 请提供核心代码片段链接
https://gist.github.com/yrz0816/ce25e5a1fe59c6bb9c0835914087a787

### 描述问题
preview-size 设置大小无效   当accept为image类型时设置capture为camera时无法调起摄像头

**Comment by rex-zsd** [comment]
1.0.0-beta.4 版本 `preview-size` 与 `capture` 存在 bug，可以升级到 1.0.1 以上的版本哈。
