### ISSUE TITLE
请问uni-app 使用vant-weapp 可以同时编译到h5和小程序吗，编译到h5，使用组件一直有问题

### ISSUE THREAD

**Issue by huwenjun0622** [youzan/vant-weapp#3987]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater?repo=VantWeapp

**Comment by rex-zsd** [comment]
#3989 
可以查看这个 issue 的回复哈
