### ISSUE TITLE
Collapse 折叠面板快速点击bug

### ISSUE THREAD

**Issue by zhuyonghao** [youzan/vant-weapp#3988]
首次进入，快速多次点击折叠面板，显示不出内容
vant，最新版本1.6.4

**Comment by rex-zsd** [comment]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater?repo=VantWeapp

**Comment by rex-zsd** [comment]
请按照模板创建 issue 哈
