### ISSUE TITLE
[Bug Report] uni-app 使用此ui库是否可直接编译到h5 ,或者只能支持小程序

### ISSUE THREAD

**Issue by huwenjun0622** [youzan/vant-weapp#3989]
### 设备
hbuilderX 3.0.5
### VantWeapp 版本
1.6.5

### 基础库版本
1.6.5

### 如果是 UI 问题，截图链接（多图回车分隔）

![截图](https://sm.ms/image/muVj3gMWelxE6NL)

### 请提供核心代码片段链接
https://gist.github.com/huwenjun0622/eebeb60b59b29dcb218ee82f390ed7a2

### 描述问题
uni-app 使用此ui库是否可直接编译到h5 ,或者只能支持小程序, 如果能支持h5，请帮忙看一下图片上反应的问题，谢谢

**Comment by rex-zsd** [comment]
只支持微信小程序的，不可编译到 h5 使用哈。
h5 的话请使用 [vant](https://github.com/youzan/vant)。
