### ISSUE TITLE
[Bug Report] DatetimePicker会自动滚动

### ISSUE THREAD

**Issue by victor2016** [youzan/vant-weapp#3990]
### 设备
安卓手机

### VantWeapp 版本
1.6.6

### 基础库版本
2.14.1

### 如果是 UI 问题，截图链接（多图回车分隔）

![截图](https://sm.ms/image/8eulTcS2bdxsJrt)

![截图](https://sm.ms/image/w6xAt3GovCk7zFu)

### 请提供核心代码片段链接
https://gitee.com/yexue/codes/z4cq91mrj3gaxd2siov6582

### 描述问题
在安卓端使用小程序进行日期选择时，如果滚动力度过大，然后不操作，这个组件就会一直滚，图一是问题，图二为小程序链接，可以进行安卓手机测试

**Comment by Esullivan-y** [comment]
相同的问题

**Comment by Jeana-f** [comment]
相同的问题 请问解决了吗

**Comment by jominr** [comment]
在安卓端使用小程序进行日期选择时，滚动几下后，组件就像永动机一样一直滚来滚去。
相同的问题，如有收到这条消息，麻烦回复告知！

**Comment by jominr** [comment]
很高兴收到您的来信O(∩_∩)O我将及时处理。---------------------------------祝：开心快乐，工作顺利！乔敏
