### ISSUE TITLE
[Bug Report] ShareSheet分享面板弹出页面可滑动

### ISSUE THREAD

**Issue by Hanwencc** [youzan/vant-weapp#3991]
ShareSheet分享面板弹出后，在面板内上下滑动，页面内容可滑动。
微信版本：IOS7.0.21

**Comment by rex-zsd** [comment]
已知问题，以小程序目前的机制，组件库无法解决。
可以查看 [文档说明](https://youzan.github.io/vant-weapp/#/popup#chang-jian-wen-ti)
