### ISSUE TITLE
建议改进tabbar文档

### ISSUE THREAD

**Issue by DingXuefeng** [youzan/vant-weapp#3992]
刚开始用小程序，看了一下好像很多小白都会遇到这个问题。开这个帖子希望帮到后来人。可以考虑添加到vant-weapp的文档或者FAQ里面。
#3916 #3835 #3843 #3764 #1656 #625 

tabbar有多种原理。最简单的一种原理是直接把多个tab以view的形式放在一个wxml里面，根据active的状态选择显示/不显示各个view。废话不多说，直接看[方案一](https://github.com/DingXuefeng/weapp-van-tabbar-samePage)。这个方案的问题是页面会过大，而big file smells bad。

另一种原理就是使用微信小程序官方的tabbar功能。**这种原理不需要你在任何wxml文件里面添加<van-tabbar>组件.**，只需要你在`app.json`里面添加"tabBar"字段。如果你图简单，只需要在app.json里添加tabBar，里面只有一个list，各项只需要pagePath和text即可。这样就做出来简单的tabBar。这种最简单，什么都不用考虑，但是比较丑。demo在这里：[方案二](https://github.com/DingXuefeng/weapp-tabbar-official)

接下来我们想要用有赞的tabBar。先把app.json的tabbar字段里添加‘custom: true'，然后在pages同级目录下创建一个`custom-tab-bar` 目录，然后创建一个`index`组件（腾讯把名字hard coded到代码里面了，自定义tab-bar只能是这个目录下的这个组件。）接下来tabbar长什么样子就跟app.json里面的tabBar.list没有关系了，于是我把list里各项的text也删了，只保留pagePath。

一个常见的问题是要点两下“active”的标签颜色才是对的。解决方案是调用“getTabBar().init()"。demo在这里：[方案三](https://github.com/DingXuefeng/weapp-vant-tabbar-full)

相信有了三个demo就可以依葫芦画瓢了。

keyword：vant tabbar 微信小程序

**Comment by DingXuefeng** [comment]
更新：
方案三如果提示“init”没有定义，那是因为这个init是我自己定义的。
另外初始tab的颜色还是不对。而且swtichTab不支持queryString。我决定还是采用方案一。

初始tab颜色不对的bug非常奇怪。如果我把
```
<van-tabbar active="{{ active }}" bind:change="onChange">
```
改成
```
<van-tabbar active="{{ 0 }}" bind:change="onChange">
```
那么第一个tab颜色就是蓝色了，是对的，所以猜测可能是因为初次渲染时active还没有初始化。

但是如果我在index.js里面如果设置active的初始值为1，初始的tab也确实为第二个tab，所以在渲染tab的时候active的值是可以读取的。

非常迷惑。弃疗了。还是用方案一好了。

**Comment by rex-zsd** [comment]
文档里一直有这个代码片段的链接呀，没看懂有什么问题
[文档地址](https://youzan.github.io/vant-weapp/#/tabbar#jie-he-zi-ding-yi-tabbar)

**Comment by liuzhenji** [comment]
赞一下楼主👍。文档确实没有涵盖所有信息素，有些信息要自己从别的地方（如：issue、code snippet）才能获悉。

**Comment by YanYRzeng** [comment]
楼主  初次tarbar 有闪烁问题
