### ISSUE TITLE
Toast嵌套使用报错

### ISSUE THREAD

**Issue by ArmyMedalMei** [youzan/vant-weapp#3993]
微信小程序组件：
Toast.loading({
      message: '订单生成中...',
      forbidClick: true,
      onClose: () => {
        Toast.success('订单提交成功')
      }
    });

`VM16493 WAService.js:2 Error: incongruent status: leave
    at se.checkStatus (transition.js? [sm]:127)
    at transition.js? [sm]:109
    at Function.<anonymous> (utils.js? [sm]:20)
    at :35139/appservice/<setTimeout callback function>
    at VM16493 WAService.js:2
    at VM16493 WAService.js:2`

**Comment by rex-zsd** [comment]
这个报错可以忽略，下版本将会把 error 修改为 warning
