### ISSUE TITLE
popup问题

### ISSUE THREAD

**Issue by lichunze** [youzan/vant-weapp#3995]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater?repo=VantWeapp
![image](https://user-images.githubusercontent.com/24243394/105580485-97b48f80-5dc7-11eb-8d31-38a8cdad7c39.png)
![image](https://user-images.githubusercontent.com/24243394/105580489-a4d17e80-5dc7-11eb-9740-637ec33315c8.png)
![image](https://user-images.githubusercontent.com/24243394/105580495-b450c780-5dc7-11eb-9150-f21a3e18ae1f.png)

我想关闭popup，文档说close-on-click-overlay默认是true，然后bind:close后微信开发者工具说 没有处理事件“close”

**Comment by lichunze** [comment]
![image](https://user-images.githubusercontent.com/24243394/105580566-0c87c980-5dc8-11eb-9d7e-3b54cdbc9598.png)
![image](https://user-images.githubusercontent.com/24243394/105580570-14476e00-5dc8-11eb-9361-faf9b98af8d4.png)

**Comment by rex-zsd** [comment]
这个 warn 的意思是 pages/aid/details 中不存在 `onClose` 方法，所以 `isShow` 没有变化仍是 `true`。
与组件库应当是无关的，检查下自己的代码即可哈。

**Comment by lichunze** [comment]
原来文档是微信的写法，知道自己哪里的原因，感谢。
