### ISSUE TITLE
[Feature Request] vant-field右侧slot支持更丰富的组件

### ISSUE THREAD

**Issue by lim42snec** [youzan/vant-weapp#3996]
### 这个功能解决了什么问题
vant-field右侧slot只支持button和icon，能否增加更多的组件支持，比如switch、原生picker等等。加入swicth后，可控制当前field输入状态，用户体验较好。目前有什么较好的方法实现？最好能给出示例代码。

### 建议的API是什么样的
无

**Comment by rex-zsd** [comment]
slot 内部放什么都可以啊，不限制内容的。

```html
<van-field>
  <van-switch slot="icon" />
</van-field>
```

**Comment by lim42snec** [comment]
应该是原始表述不准确，能否实现下述效果，并且picker箭头向下，field默认内字体、行距都大一点，谢谢！
![image](https://user-images.githubusercontent.com/14806821/105849432-56b4b900-601b-11eb-89ec-86cdb490bb1d.png)

**Comment by rex-zsd** [comment]
一样的，slot 内想放什么就可以放什么，没有任何限制。

```html
<van-field>
  <block slot="icon">
    <van-picker />
    <van-switch  />
  </block>
</van-field>
```
