### ISSUE TITLE
[Bug Report] icon 组件在微信小程序真机无法显示

### ISSUE THREAD

**Issue by JIANGYUNPU** [youzan/vant-weapp#3997]
### 设备
ios 安卓

### VantWeapp 版本
1.6.6

### 基础库版本
1.6.6

### 请提供核心代码片段链接
http://vant-contrib.gitee.io/vant-issue-generater/?repo=VantWeapp#/zh-CN?repo=VantWeapp&type=Bug并不是代码问题

### 描述问题
icon 组件在微信小程序真机无法显示，并且你们官方的小程序icon组件也是不显示，请问这是什么情况？

**Comment by rex-zsd** [comment]
CDN 域名被部分省份的运营商封了，目前原因不明，可以在 app.wxss 中添加如下代码暂时解决，待运营商解封后去除。

```
@font-face {
  font-weight: normal;
  font-family: 'vant-icon-temp';
  font-style: normal;
  font-display: auto;
  src: url('https://img01.yzcdn.cn/vant/vant-icon-84f687.woff2') format('woff2'),
    url('https://img01.yzcdn.cn/vant/vant-icon-84f687.woff') format('woff'),
    url('https://img01.yzcdn.cn/vant/vant-icon-84f687.ttf') format('truetype');
}

.van-icon {
  font-family: 'vant-icon-temp' !important;
}
```

**Comment by JIANGYUNPU** [comment]
> CDN域名被部分省份的运营商封了，目前原因不明，可以在app.wxss中添加如下代码暂时解决，待运营商解封后移除。
> 
> ```
> @font-face {
>   font-weight: normal;
>   font-family: 'vant-icon-temp';
>   font-style: normal;
>   font-display: auto;
>   src: url('https://img01.yzcdn.cn/vant/vant-icon-84f687.woff2') format('woff2'),
>     url('https://img01.yzcdn.cn/vant/vant-icon-84f687.woff') format('woff'),
>     url('https://img01.yzcdn.cn/vant/vant-icon-84f687.ttf') format('truetype');
> }
> 
> .van-icon {
>   font-family: 'vant-icon-temp' !important;
> }
> ```

好的谢谢

**Comment by rex-zsd** [comment]
1.6.7 版本已替换新的 CDN 地址，请升级修复哈。

**Comment by yisibl** [comment]
考虑一下使用 iconfont.cn 的 CDN？

**Comment by chenjiahan** [comment]
@yisibl 感谢建议，近期我们会评估一下切换到 iconfont

**Comment by yisibl** [comment]
@chenjiahan 好的，需求可以直接和我提哈。

**Comment by chenjiahan** [comment]
好滴~

**Comment by chenjiahan** [comment]
@yisibl 遇到一点小问题，这两个图标在 iconfont.cn 上无法上传（上传后显示空白），我和设计同学按照 [图标绘制](https://www.iconfont.cn/help/detail?spm=a313x.7781069.1998910419.16&helptype=draw) 看了一下，没发现问题。你能帮忙看一下吗

图标设计稿：[icon.zip](https://github.com/youzan/vant-weapp/files/6497934/icon.zip)

**Comment by yisibl** [comment]
> @yisibl 遇到一点小问题，这两个图标在 iconfont.cn 上无法上传（上传后显示空白），我和设计同学按照 [图标绘制](https://www.iconfont.cn/help/detail?spm=a313x.7781069.1998910419.16&helptype=draw) 看了一下，没发现问题。你能帮忙看一下吗
> 
> 图标设计稿：[icon.zip](https://github.com/youzan/vant-weapp/files/6497934/icon.zip)

操作系统和浏览器版本是？

**Comment by yisibl** [comment]
我看了一下默认导出会有`<use>` 标签，当前 iconfont 还不支持 ，需要全部转换为 path

```
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="1000" height="1000" viewBox="0 0 1000 1000">
  <defs>
    <path id="share-a" d="M577.281091,140.476711 C577.281091,117.842966 590.490967,112.122802 607.095905,128.007575 L931.54035,438.624859 C948.001255,454.406752 948.124712,479.941731 931.848992,495.661896 L606.787263,809.406751 C590.490967,825.126916 577.281091,819.324447 577.281091,796.855311 L577.281091,632.760661 C101.54035,632.760661 56,881.361484 56,881.361484 C56,881.361484 48.659692,379.406751 577.281091,304.591936 L577.281091,140.476711 Z"/>
  </defs>
  <use fill="#323233" xlink:href="#share-a"/>
</svg>
```

**Comment by chenjiahan** [comment]
了解~ 是开启了 Sketch 的蒙版功能，导致有 `use` 标签，去掉蒙版就可以上传了。

建议这里可以完善一下错误提示喔，或者给在帮助手册里给一些提示指引。

**Comment by chenjiahan** [comment]
图标库已迁移至 iconfont.cn，感谢 @yisibl ~

**Comment by yisibl** [comment]
> 了解~ 是开启了 Sketch 的蒙版功能，导致有 `use` 标签，去掉蒙版就可以上传了。
> 
> 建议这里可以完善一下错误提示喔，或者给在帮助手册里给一些提示指引。

感谢建议哈，后面考虑直接支持 `use` 标签的。

**Comment by yisibl** [comment]
@chenjiahan 感觉你可以传一个到 iconfont 图标库，也可以更好的宣传 vant 项目：https://www.iconfont.cn/collections/index?spm=a313x.7781069.1998910419.4

**Comment by chenjiahan** [comment]
可以滴~ 我晚点搞一下
