### ISSUE TITLE
组件的内置图标怎么突然不能显示了

### ISSUE THREAD

**Issue by heixax** [youzan/vant-weapp#3999]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater?repo=VantWeapp

**Comment by Hank-Zhou** [comment]
官网的图片都蹦了 : P

**Comment by youupiup** [comment]
难顶哦，全图标都没了，求快点解决呀

**Comment by Hank-Zhou** [comment]
> 难顶哦，全图标都没了，求快点解决呀

@font-face {
  font-weight: normal;
  font-family: 'vant-icon-temp';
  font-style: normal;
  font-display: auto;
  src: url('https://img01.yzcdn.cn/vant/vant-icon-84f687.woff2') format('woff2'),
    url('https://img01.yzcdn.cn/vant/vant-icon-84f687.woff') format('woff'),
    url('https://img01.yzcdn.cn/vant/vant-icon-84f687.ttf') format('truetype');
}

.van-icon {
  font-family: 'vant-icon-temp' !important;
}

**Comment by Hank-Zhou** [comment]
> 难顶哦，全图标都没了，求快点解决呀

前个issue给出的暂时解决方法

**Comment by nihaoye** [comment]
我也是

**Comment by he429134733** [comment]
升级最新版就好了

**Comment by rex-zsd** [comment]
#3997 看下这个 issue 哈
