### ISSUE TITLE
如何在开发插件中,引入weapp呢

### ISSUE THREAD

**Issue by xumengyin** [youzan/vant-weapp#4000]
我们需要开发一些界面 作为微信小程序插件供第三方嵌入，请问如何在开发插件中,引入weapp呢

**Comment by rex-zsd** [comment]
小程序插件不支持 npm 引入。
可以下载代码，将 `dist` 目录拷贝至项目中，使用相对路径的方式引入使用哈。

**Comment by xumengyin** [comment]
谢了哥们
