### ISSUE TITLE
[Bug Report] 下拉菜单overlay属性设置false无效果

### ISSUE THREAD

**Issue by TangXiaoDouL** [youzan/vant-weapp#4008]
### 设备
微信开发工具

### VantWeapp 版本
1.6.6

### 基础库版本
1.6.6

### 请提供核心代码片段链接
https://segmentfault.com/q/1010000039095685

### 描述问题
使用下拉菜单。在van-dropdown-menu组件上设置overlay设置为false没有效果，包括close-on-click-overlay设置为false也没效果

**Comment by nemo-shen** [comment]
<van-dropdown-menu overlay="{{ false }}">...</van-dropdown-menu>
