### ISSUE TITLE
textfield下边缘没有横线

### ISSUE THREAD

**Issue by UltimatePea** [youzan/vant-weapp#401]
### 请认真写 ISSUE 的标题，会用于生成 change log。

**请确认是需要 *新增功能* 还是 *提交bug* **

** 如果是 bug，请提供复现步骤，可能的话，可以在 [https://jsfiddle.net](https://jsfiddle.net) 或者类似平台上提供一个 demo **

<img width="377" alt="image" src="https://user-images.githubusercontent.com/9295852/43680265-8b3b34ba-9804-11e8-8825-32c370a08a13.png">
<img width="668" alt="image" src="https://user-images.githubusercontent.com/9295852/43680270-a44de86c-9804-11e8-85f5-82af47e93281.png">

**Comment by UltimatePea** [comment]
<img width="355" alt="image" src="https://user-images.githubusercontent.com/9295852/43682306-0fcb1814-983f-11e8-8d22-e6748e8aa0de.png">

**Comment by UltimatePea** [comment]
该问题仅在开发者工具中出现，不在真机上出现

**Comment by rex-zsd** [comment]
可以在开发者工具中尝试切换一下不同分辨率的机型。
因为开发者工具对1px线的渲染有问题，某些分辨率下会不显示，真机上应该没问题的。

**Comment by melodicdeath** [comment]
@UltimatePea 真机上也是有这问题的

**Comment by melodicdeath** [comment]
@UltimatePea @rex-zsd 真机上也是有问题的
![screenshot_20180808-210349](https://user-images.githubusercontent.com/7873135/43838844-1206165c-9b4f-11e8-8936-dc863f427510.png)

**Comment by melodicdeath** [comment]
@UltimatePea @rex-zsd 真机上也是有问题的

  <zan-panel>
    <form bindsubmit="formSubmit" bindreset="formReset">
      <zan-field
        name="name"
        placeholder="账号">
      </zan-field>
      <zan-field
        name="password"
        placeholder="密码"
        input-type="password">
      </zan-field>
      <zan-field
        name="password"
        placeholder="密码"
        input-type="password">
      </zan-field>
      <button type="primary" form-type="submit">登录</button>
    </form>
  </zan-panel> 

没有加样式

![screenshot_20180808-211255](https://user-images.githubusercontent.com/7873135/43839177-0dcef7ce-9b50-11e8-85ec-2f10edbd63e3.png)

**Comment by rex-zsd** [comment]
@melodicdeath 多个field组件一起使用时需要用cell-group组件包裹，可以参考[文档](https://youzan.github.io/zanui-weapp/#/zanui/form/field)

**Comment by melodicdeath** [comment]
@rex-zsd 加了也没用，我是根据你们源码来的。你们的源码在我手机上跑起来也没有下划线。
最后一个示例：“Form表单中的field应用”
![screenshot_20180809-211539](https://user-images.githubusercontent.com/7873135/43901253-9f43285a-9c19-11e8-9ddf-01c0d61b87aa.png)

**Comment by rex-zsd** [comment]
@melodicdeath 示例源码就是没有下划线的，因为没有使用cell-group组件包裹

**Comment by chenjiahan** [comment]
目前 zanui-weapp 已进行全新的品牌升级，更名为 Vant Weapp，组件和 API 都有较大的变化。

对 zanui-weapp 的讨论，请移步至 https://github.com/youzan/zanui-weapp 仓库
