### ISSUE TITLE
[Bug Report] icon组件字体图标无法显示

### ISSUE THREAD

**Issue by yangccxi** [youzan/vant-weapp#4010]
### 设备
所有安卓机型

### VantWeapp 版本
1.4.3

### 基础库版本
2.10.0

### 请提供核心代码片段链接
https://github.com/yangccxi/test/blob/main/vant%20weapp

### 描述问题
icon组件字体图标无法显示
<van-cell title="性别" value="男" is-link />
右边箭头无法显示

**Comment by duanzhichao** [comment]
想不到把,有赞cnd全挂了

**Comment by Amoo3** [comment]
从这周一开始  vant Weapp的所有icon全挂了

**Comment by rex-zsd** [comment]
1.6.7 版本已替换新的 CDN 地址，请升级修复哈。

**Comment by yangccxi** [comment]
好的，谢谢


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "youzan/vant-weapp"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月27日(星期三) 下午4:04
收件人:&nbsp;"youzan/vant-weapp"<vant-weapp@noreply.github.com&gt;;
抄送:&nbsp;"日山CC"<447363090@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [youzan/vant-weapp] [Bug Report] icon组件字体图标无法显示 (#4010)





 
1.6.7 版本已替换新的 CDN 地址，请升级修复哈。
