### ISSUE TITLE
[Bug Report] van-tabs下的激活样式tab-active-class设置字体颜色color无效

### ISSUE THREAD

**Issue by kiluarlin** [youzan/vant-weapp#4013]
### 设备
微信开发者工具

### VantWeapp 版本
1.6.6

### 基础库版本
1.6.6

### 请提供核心代码片段链接
https://github.com/youzan/vant-weapp/tree/dev/lib/tab

### 描述问题
van-tabs下的激活样式tab-active-class设置字体颜色color无效

**Comment by rex-zsd** [comment]
测试无问题，因为没有提供代码片段，无从得知是否是使用姿势的问题。

```html
<van-tabs tab-active-class="active">
    <van-tab>
       content
    </van-tab>
  </van-tabs>
```

```css
.active {
  color: red !important;
}
```
