### ISSUE TITLE
在编译ts时出现 error TS2724: 'WechatMiniprogram' has no exported member named 'GetSystemInfoSyncResult'. Did you mean 'GetBatteryInfoSyncResult'?

### ISSUE THREAD

**Issue by dooioomoo** [youzan/vant-weapp#4014]
我想准备vant-wrapp的样式环境，尝试手动运行了npx gulp -f build/compiler.js --series buildEs buildLib,出现错误：

packages/common/utils.ts:18:35 - error TS2724: 'WechatMiniprogram' has no exported member named 'GetSystemInfoSyncResult'. Did you mean 'GetBatteryInfoSyncResult'?

其实我是想自己编译并输出到一个路径里去。

有什么好的办法可以解决这个问题？

**Comment by rex-zsd** [comment]
我这边没出现这样的问题，`WechatMiniprogram` 是由微信官方的 `miniprogram-api-typings` 包提供的定义。
可以看下是否是依赖安装方面的问题哈。

**Comment by rex-zsd** [comment]
https://github.com/youzan/vant-weapp/commit/51aff18deaff0e59d22ae1a8796ccb0be0a3fdb8

1.6.9 已修复哈
