### ISSUE TITLE
既然都Open Source,像Empty、Icon等应该用svg格式

### ISSUE THREAD

**Issue by yingyingxiong** [youzan/vant-weapp#4015]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater?repo=VantWeapp

**Comment by rex-zsd** [comment]
小程序不支持 svg 的哈，所以只能使用图片。

**Comment by rzshuo** [comment]
小程序支持SVG
