### ISSUE TITLE
v2.12.6版本 <van-area>控件 省市区 选择区域不显示（空白），但是能选到值

### ISSUE THREAD

**Issue by developerZzzZ** [youzan/vant-weapp#4016]
<van-popup v-model="areaShow" position="bottom" :style="{ width: '100%',height: '50%' }">
      <van-area :area-list="areaList" @confirm="areaConfirm" @cancel="areaCancel"/>
</van-popup>

**Comment by rex-zsd** [comment]
看起来反馈的是 vant 而不是 vant weapp 的问题？
 出门左转 [vant](https://github.com/youzan/vant/issues) 哈
