### ISSUE TITLE
[Bug Report] action-sheet组件action数据的openType=“contact”后某些属性例如sessionFrom无效

### ISSUE THREAD

**Issue by henrylu** [youzan/vant-weapp#4020]
### 设备
iphone, android

### VantWeapp 版本
1.6.7

### 基础库版本
2.14.4

### 请提供核心代码片段链接
https://github.com/youzan/vant-weapp/blob/dev/lib/action-sheet/index.wxml

### 描述问题
https://github.com/youzan/vant-weapp/blob/dev/lib/action-sheet/index.wxml
这里的代码：lang, sessionFrom, sendMessageTitle等属性设置了后没有效果。应该修改为 item.lang, item.sessionFrom, item.sendMessageTitle ...

**Comment by rex-zsd** [comment]
#4021
感谢 pr 🎉
