### ISSUE TITLE
Toast.loadding调用之后使用Toast.clear(); 报错

### ISSUE THREAD

**Issue by ArmyMedalMei** [youzan/vant-weapp#4022]
Error: incongruent status: enter
    at se.checkStatus (transition.js? [sm]:127)
    at transition.js? [sm]:88
    at Function.<anonymous> (utils.js? [sm]:20)
    at :50170/appservice/<setTimeout callback function>
    at VM890 WAService.js:2
    at VM890 WAService.js:2

**Comment by rex-zsd** [comment]
这个报错可忽略哈。它是用来检查动画组件的当前状态是否争取的，即在组件隐藏时不再进行后续动画。
