### ISSUE TITLE
van-datetime-picker组件，拉动后，一直来回跳动，无法解决

### ISSUE THREAD

**Issue by zzhn6** [youzan/vant-weapp#4025]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater?repo=VantWeapp

**Comment by Vict-star** [comment]
遇到了同样的bug

**Comment by HumanSean** [comment]
百度了一下发现说，把input事件改为change即可

**Comment by zzhn6** [comment]
没用



---原始邮件---
发件人: "Human Sean"<notifications@github.com&gt;
发送时间: 2021年2月10日(周三) 晚上9:34
收件人: "youzan/vant-weapp"<vant-weapp@noreply.github.com&gt;;
抄送: "zzhn6"<1197520188@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [youzan/vant-weapp] van-datetime-picker组件，拉动后，一直来回跳动，无法解决 (#4025)




 
百度了一下发现说，把input事件改为change即可

**Comment by HumanSean** [comment]
这是我的写法。input和change获取的参数是不同的。的确不会来回跳动了，不过如果拉动太快的话，动画效果还是怪怪的
```js
onInput({ detail }) {
    this.currentDate = new Date(detail.getValues().join('-')).getTime();
}
```

**Comment by zzhn6** [comment]
我修改后，感觉还是有跳动，效果不是很好



---原始邮件---
发件人: "Human Sean"<notifications@github.com&gt;
发送时间: 2021年2月10日(周三) 晚上10:27
收件人: "youzan/vant-weapp"<vant-weapp@noreply.github.com&gt;;
抄送: "zzhn6"<1197520188@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [youzan/vant-weapp] van-datetime-picker组件，拉动后，一直来回跳动，无法解决 (#4025)




 
这是我的写法。input和change获取的参数是不同的。的确不会来回跳动了，不过如果拉动太快的话，动画效果还是怪怪的
 onInput({ detail }) {     this.currentDate = new Date(detail.getValues().join('-')).getTime(); }

**Comment by HyperLife1119** [comment]
问题依然存在
