### ISSUE TITLE
[Bug Report] van-popup内容溢出无法触摸滚动

### ISSUE THREAD

**Issue by SuperMao00** [youzan/vant-weapp#4028]
### 设备
开发者工具、Honor9

### VantWeapp 版本
1.6.7

### 基础库版本
2.14.4

### 请提供核心代码片段链接
https://gitee.com/supermao9527/weapp-example1.git

### 描述问题
van-popup中的内容超出容器无法触摸滚动，只能鼠标滚轮滚动。

**Comment by rex-zsd** [comment]
https://user-images.githubusercontent.com/8767877/106856865-209dc600-66fa-11eb-8c24-7293bb6a277d.mp4

提供下可复现的机型？测试 mate30 未复现问题。

popup 组件没有对内部溢出的行为做限制，理论上不会有这个问题。

**Comment by SuperMao00** [comment]
>  1612422184693064.mp4 
> 提供下可复现的机型？测试 mate30 未复现问题。
> 
> popup 组件没有对内部溢出的行为做限制，理论上不会有这个问题。

荣耀9和开发版的微信开发者工具，看了下weapp依赖版本是1.5.3才出现这个问题，1.5.2没有这个问题

**Comment by github-gordon** [comment]
> > 1612422184693064.mp4
> > 提供下可复现的机型？测试 mate30 未复现问题。
> > popup 组件没有对内部溢出的行为做限制，理论上不会有这个问题。
> 
> 荣耀9和开发版的微信开发者工具，看了下weapp依赖版本是1.5.3才出现这个问题，1.5.2没有这个问题
你好，这个问题解决了么，我这边不论使用什么版本，都不能点击滚动

**Comment by landluck** [comment]
没有能复现，如能复现可以提供下复现代码 以及 复现设备 后重新打开 issue
