### ISSUE TITLE
step 组件支持点击事件

### ISSUE THREAD

**Issue by huiyiqun** [youzan/vant-weapp#403]
### 请认真写 ISSUE 的标题，会用于生成 change log。

**请确认是需要 *新增功能* 还是 *提交bug* **

新增功能

** 如果是 bug，请提供复现步骤，可能的话，可以在 [https://jsfiddle.net](https://jsfiddle.net) 或者类似平台上提供一个 demo **

目测工作量不大，感觉我可以帮忙实现？

**Comment by huiyiqun** [comment]
http://html51.com/info-21260-1/ 这里这份代码实现了类似的功能，稍微抽象一下即可。

**Comment by huiyiqun** [comment]
@pangxie1991 我打算花一会儿时间实现一个 pr，有什么建议吗？

大致是打算添加一个 bind:tap 用于添加回调函数，回调函数传一个参数，把 steper 对应的 object 传进去。

**Comment by chenjiahan** [comment]
目前 zanui-weapp 已进行全新的品牌升级，更名为 Vant Weapp，组件和 API 都有较大的变化。

对 zanui-weapp 的讨论，请移步至 https://github.com/youzan/zanui-weapp 仓库
