### ISSUE TITLE
[Feature Request] DropdownMenu 下拉菜单点击或设置选中的值为什么是按下标位置来的，而不是按数据项里的value来选中的？

### ISSUE THREAD

**Issue by cgChen1995** [youzan/vant-weapp#4031]
### 这个功能解决了什么问题
DropdownMenu 下拉菜单点击或设置选中的值为什么是按下标位置来的，而不是按数据项里的value来选中的？

### 建议的API是什么样的
DropdownMenu 下拉菜单点击或设置选中的值为什么是按下标位置来的，而不是按数据项里的value来选中的？
如果是按下标来选中的，那要value有什么作用呢？

**Comment by landluck** [comment]
确认后是根据 value 值来进行选中的，如确认有问题，可以提供能否复现的小程序代码片段后重新打开issue
