### ISSUE TITLE
[Bug Report] 关于自定义组件内使用vant组件，vant组件大小被限制问题

### ISSUE THREAD

**Issue by a2774206** [youzan/vant-weapp#4035]
### 设备
任意

### VantWeapp 版本
1.5.3

### 基础库版本
2.12.2

### 如果是 UI 问题，截图链接（多图回车分隔）

https://i.loli.net/2021/02/03/Iq1UwEKZOMy7ARj.jpg

https://i.loli.net/2021/02/03/lbzLdtjFam57TgP.jpg

### 请提供核心代码片段链接
https://sm.ms/image/Iq1UwEKZOMy7ARj

### 描述问题
小程序自定义组件内使用vant组件后，vant组件大小会被页面内元素限制大小。
ui截图：轮播使用自定义组件，自定义组件内有vant dialog组件。（dialog组件只能在轮播组件内显示）
目前猜测是组件fxied定位下使用了transform，堆叠上下文的创建，该元素会影响其子元素的固定定位。设置了 position:fixed 的子元素将不会基于 viewport 定位，而是基于这个父元素。

**Comment by rex-zsd** [comment]
是这个原因，由于轮播效果会使用 `transform`，对弹窗类组件都是有影响的。
由于小程序目前的机制，vant weapp 这边没有什么好的方法解决，只能由开发者手动处理，将弹窗组件移出轮播。
