### ISSUE TITLE
van-tab 开启动画 结合van-goods-action 使用出现 fixed 定位方式 无法切换

### ISSUE THREAD

**Issue by w3cui** [youzan/vant-weapp#4037]
复现：微信小程序模拟器中就可以复现
版本：1.6.7
bug视频：https://sr.ffquan.cn/dtk_www/20210205/c0ebfnf6vrkaepv402900normal video.mp4

源码错误：https://github.com/youzan/vant-weapp/blob/dev/lib/goods-action/index.wxss

请大佬尽快修复

**Comment by rex-zsd** [comment]
视频挂了，document not found，调整一下链接吧

**Comment by w3cui** [comment]
地址可以直接复制下来
试试这个地址 ： https://sr.ffquan.cn/dtk_www/20210205/c0ebq976vrkaepv4029g0normalvideo.mp4

**Comment by rex-zsd** [comment]
我理解这个跟组件库关系不大，对于 tab 切换的场景，固定定位的元素都需要手动处理的。

**Comment by w3cui** [comment]
我这边用样式去覆盖 覆盖不上，不清楚是什么原因

https://sr.ffquan.cn/dtk_www/20210205/c0edlun6vrkaepv402a00.png

**Comment by rex-zsd** [comment]
#4038 见这边的回复哈，自行把 goods-action 的样式覆盖掉就可以了。
