### ISSUE TITLE
[Bug Report] van-tab 开启动画 结合van-goods-action 使用出现 底部无法切换

### ISSUE THREAD

**Issue by w3cui** [youzan/vant-weapp#4038]
### 设备
微信小程序模拟器中就可以复现

### VantWeapp 版本
1.6.7

### 基础库版本
1.6.7

### 如果是 UI 问题，截图链接（多图回车分隔）

![截图](https://sr.ffquan.cn/dtk_www/20210205/c0ebfnf6vrkaepv402900normal)

![截图](video.mp4)

![截图](https://www.soogif.com/toolshare/V598e4d4fbb1e06d)

### 请提供核心代码片段链接
https://github.com/youzan/vant-weapp/blob/dev/lib/goods-action/index.wxss

### 描述问题
注意下方的按钮切换，左右按钮不跟随切换。  我排查原因是：
@import '../common/index.wxss';
.van-goods-action{position:fixed;right:0;bottom:0;left:0;display:-webkit-flex;display:flex;-webkit-align-items:center;align-items:center;box-sizing:initial;height:50px;height:var(--goods-action-height,50px);background-color:#fff;background-color:var(--goods-action-background-color,#fff)}.van-goods-action--safe{padding-bottom:env(safe-area-inset-bottom)}

.van-goods-action设置了 left为0 和right为0 用的是fixed 定位导致的。
修复方案： left 为0移除 right为0移除 并设置宽度100%

视频录制：[https://sr.ffquan.cn/dtk_www/20210205/c0ebfnf6vrkaepv402900normal video.mp4](点击查看)

请尽快修复一下

**Comment by rex-zsd** [comment]
这种特殊场景，通过 [样式覆盖](https://youzan.github.io/vant-weapp/#/custom-style) 自行处理一下即可哈。
