### ISSUE TITLE
[Feature Request] Uploader支持附件

### ISSUE THREAD

**Issue by superlbr** [youzan/vant-weapp#4039]
### 这个功能解决了什么问题
需要很多常用文件的上传，比如doc、excel、mp3、pdf

### 建议的API是什么样的
Discuz Q支持选择聊天会话，并上传提及的文件

**Comment by rex-zsd** [comment]
微信目前的 API，从本地存储中只支持选择图片、视频等媒体资源，不支持如 doc、excel 等其他类型文件的。
van-uploader 目前的 `type` 支持的 `file` 类型是基于 [wx.chooseMessageFile](https://developers.weixin.qq.com/miniprogram/dev/api/media/image/wx.chooseMessageFile.html) 实现，只能从会话中选取资源，而不能从设备存储中任意上传资源。

**Comment by superlbr** [comment]
van-uploader的变通实现是可取，覆盖90%的需求

**Comment by superlbr** [comment]
留个口子，自定义呗
