### ISSUE TITLE
【bug】 Vant Weapp 中Tab标签问题

### ISSUE THREAD

**Issue by 13611994420** [youzan/vant-weapp#4041]
1、点击tab标签后页面总是会回到顶部的问题，感觉整个页面刷新了
2、tab标签页有没有内置的上拉加载与下拉刷新功能？

**Comment by rex-zsd** [comment]
1. 提供信息不足，无法回答
2. van-tab 没有上拉、下拉功能哈

**Comment by 13611994420** [comment]
thank

发自我的iPhone
