### ISSUE TITLE
[Bug Report] 小程序如何共用一个van-picker，并且回显已经选中的值？

### ISSUE THREAD

**Issue by very-xiu** [youzan/vant-weapp#4042]
### 设备
ios、Android

### VantWeapp 版本
1.6.7

### 基础库版本
1.6.7

### 请提供核心代码片段链接
https://gist.github.com/very-xiu/3a9c358173c29869a7322f8cd84a7a9c

### 描述问题
其中一个表单已经选中的值，另一个表单继续下拉选择，然后再重新选择上一个表单的下拉选择，picker里面如何回显上一个表单中已经选中的值？

**Comment by rex-zsd** [comment]
可以看下文档的 [方法](https://youzan.github.io/vant-weapp/#/picker#fang-fa) 部分，通过获取 van-picker 的组件实例并调用方法可以设置选中项的。

**Comment by very-xiu** [comment]
> 可以看下文档的[方法](https://youzan.github.io/vant-weapp/#/picker#fang-fa)部分，通过获取van-picker的组件实例并调用方法可以设置放置项的。

好的，谢谢
