### ISSUE TITLE
[Bug Report] goodsAction样式显示错误

### ISSUE THREAD

**Issue by forget1** [youzan/vant-weapp#4051]
### 设备
小米10，iPhone系列

### VantWeapp 版本
1.6.7

### 基础库版本
2.12.

### 如果是 UI 问题，截图链接（多图回车分隔）

![截图](https://i.loli.net/2021/02/19/yORTQGZEz6fJAIV.png)

### 请提供核心代码片段链接
https://gist.github.com/forget1/4db4cc8b65e31193471867d4bafc2404

### 描述问题
升级vant-weapp版本到1.6.7之后，goodsAction部分样式显示异常，怀疑和在[https://github.com/youzan/vant-weapp/pull/3654](https://github.com/youzan/vant-weapp/pull/3654)提交中添加的`display: flex;`有关

**Comment by rex-zsd** [comment]
跟这个 pr 应该没关系，这里只是减少了节点层级，去除了 content 元素并将 content 的样式合并至根节点，与原来是等价的。

看了代码片段，原因应该在 [这里](https://gist.github.com/forget1/4db4cc8b65e31193471867d4bafc2404#file-goodsaction-L17)，按钮是自定义的并且外层包裹了一层 view，需要自行处理下样式了哈。

如图，使用 van-goods-action-button 是没有问题的。
![image](https://user-images.githubusercontent.com/8767877/108978482-975c2c80-76c4-11eb-924e-b6d21ae56ce0.png)
