### ISSUE TITLE
[Bug Report]van-circle和van-calendar同时使用时,van-circle出现层叠问题

### ISSUE THREAD

**Issue by qihui1223** [youzan/vant-weapp#4052]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater?repo=VantWeapp

设备
iphone11

VantWeapp 版本
1.6.7

基础库版本
2.15.0

![image](https://user-images.githubusercontent.com/26089593/108589693-93659d00-739a-11eb-9917-186a096abf45.png)
van-circle和van-calendar同时使用时,当加点日历组件时,环形进度条没有被日历的遮罩层挡住,而是直接显示在最上方

**Comment by rex-zsd** [comment]
van-circle 内部使用 canvas 实现，canvas 是原生组件，层级是无法被其他元素覆盖的。
可以设置 `type="2d"` 使用 `2d` 模式开启同层渲染应该可以解决哈。

**Comment by shaofahui** [comment]
但是设置对circle的canvas设置为2d后，没有环绕的样式了

**Comment by shaofahui** [comment]
但是设置后，circle就失去了它环绕的样式了
