### ISSUE TITLE
[Bug Report] van-uploader组件不显示微信头像

### ISSUE THREAD

**Issue by youupiup** [youzan/vant-weapp#4054]
### 设备
安卓、苹果

### VantWeapp 版本
1.6.7

### 基础库版本
2.10.4

### 如果是 UI 问题，截图链接（多图回车分隔）

![截图](https://sm.ms/image/mQqzIFn825jrYNs)

### 请提供核心代码片段链接
https://github.com/youupiup/issueDemo.git

### 描述问题
van-uploader组件不显示微信头像，微信头像地址他识别不到，然后就直接显示了链接了，不显示图片

**Comment by rex-zsd** [comment]
请查看文档 [图片预览](https://youzan.github.io/vant-weapp/#/uploader#tu-pian-yu-lan) 部分，手动设置 `isImage` 属性哈。
