### ISSUE TITLE
[Bug Report] SwipeCell组件close事件，右滑没有触发

### ISSUE THREAD

**Issue by icytailu** [youzan/vant-weapp#4055]
### 设备
iphoneXs

### VantWeapp 版本
1.6.7

### 基础库版本
2.15.0

### 请提供核心代码片段链接
https://github.com/icytailu/bug/issues/1

### 描述问题
SwipeCell组件close事件没有触发，open是可以触发的，
左滑打开后，点击可以触发close事件，右滑没有触发close事件

**Comment by rex-zsd** [comment]
`close` 事件并不是在右滑时触发，而是在点击两侧滑动内容时触发。
可以查看组件文档的 [异步关闭](https://youzan.github.io/vant-weapp/#/swipe-cell#yi-bu-guan-bi) 部分哈。
