### ISSUE TITLE
form 不能获取到 radio 到值,  input 的可以.  

### ISSUE THREAD

**Issue by janjon** [youzan/vant-weapp#406]
form 不能获取到 radio 到值,  input 的可以.

**Comment by rex-zsd** [comment]
可以贴下代码片段吗？

**Comment by chenjiahan** [comment]
目前 zanui-weapp 已进行全新的品牌升级，更名为 Vant Weapp，组件和 API 都有较大的变化。

对 zanui-weapp 的讨论，请移步至 https://github.com/youzan/zanui-weapp 仓库

**Comment by janjon** [comment]
`data = {
    id: '',
    name: '',
    serviceItems: [
      {name: '修', value: '修', checked: 'true'},
      {name: '买', value: '买'},
      {name: '卖', value: '卖'}
    ],
    phone: '',
  }`
`<vant-panel title='选择服务类型'>
        <vant-radio name='type' items="{{ serviceItems }}"></vant-radio>
      </vant-panel>`

name为 type 表单提交输出的 内容 为 "",   vant 没有 radio 组件哦
