### ISSUE TITLE
[Feature Request] 级联选择器需求

### ISSUE THREAD

**Issue by changwenbo** [youzan/vant-weapp#4060]
### 这个功能解决了什么问题
解决了日常项目中，树形结构数据级联选择的问题，平时使用的也非常多，希望提供相关支持。

### 建议的API是什么样的
树形结构数据，可选择到任意一级，支持多选和单选

**Comment by waycowei** [comment]
+1

**Comment by landluck** [comment]
https://youzan.github.io/vant-weapp/#/cascader 已支持
