### ISSUE TITLE
popup里面无法拖动问题

### ISSUE THREAD

**Issue by kaipat** [youzan/vant-weapp#4063]
overlay里的catch:touchmove="noop"会阻止popup里面的元素拖动，建议优化

**Comment by rex-zsd** [comment]
https://github.com/youzan/vant-weapp/blob/dev/packages/popup/index.wxml#L12

可以看下 popup 内的 content 与 van-overlay 是平行关系，且 van-overlay 层级更低，所以 van-overlay 内部 `catch:touchmove` 并不会阻止 popup  内容区的元素拖动哈。
