### ISSUE TITLE
[Bug Report] van-field的input事件不返回光标位置cursor，原生已经支持了

### ISSUE THREAD

**Issue by cumt-robin** [youzan/vant-weapp#4064]
![image](https://user-images.githubusercontent.com/30487257/109002934-cf259d00-76e1-11eb-8ef5-260468e50552.png)

**Comment by landluck** [comment]
`v1.10.12`版本已支持

**Comment by cumt-robin** [comment]
您的邮件我已收到！  我会在第一时间内回复您！非常感谢！
