### ISSUE TITLE
van-datetime-picker组件type="year-month"时，选择年份出现bug

### ISSUE THREAD

**Issue by zongrenCode** [youzan/vant-weapp#4065]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater?repo=VantWeapp项目中

文件https://github.com/youzan/vant-weapp/blob/dev/packages/datetime-picker/index.ts

改变前出现的问题
![image](https://user-images.githubusercontent.com/38056993/109018570-339d2800-76f3-11eb-92e5-4f41d14e4370.png)

注释代码修改为以下图片中代码，不会出现bug

![image](https://user-images.githubusercontent.com/38056993/109017075-cb9a1200-76f1-11eb-88be-18aa523848de.png)

**Comment by nemo-shen** [comment]
@zongrenCode 和 #4120 相同
