### ISSUE TITLE
自定义底部导航占位符不生效

### ISSUE THREAD

**Issue by a731734358** [youzan/vant-weapp#4069]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

自定义组件底部导航
查看元素占位元素存在   但底部导航有一个 tab-bar 标签的父元素  宽高都为0  不知道什么原因

http://vant-contrib.gitee.io/vant-issue-generater?repo=VantWeapp

**Comment by rex-zsd** [comment]
开启微信的自定义底部导航以后，底部导航就脱离了页面布局了，此时占位元素是不会生效的哈。
