### ISSUE TITLE
[Bug Report] dialog内嵌field[type=textarea]的placeholder显示和预期不符且无法修改

### ISSUE THREAD

**Issue by ahuang** [youzan/vant-weapp#4071]
### 设备
微信开发者工具，安卓手机都有

### VantWeapp 版本
1.5.3

### 基础库版本
2.15.0

### 如果是 UI 问题，截图链接（多图回车分隔）

![截图](https://i.loli.net/2021/03/02/VmPSaXDT5yEpjFY.png)

### 请提供核心代码片段链接
https://github.com/ahuang/vantweapptest

### 描述问题
van-dialog内嵌套van-field[type=texterea] 时， 
1. input的placeholder样式显示不对，(期望颜色是灰色，字体小点。实际颜色是黑色，字体较大)
2. 无法通过placeholder-style修改

**Comment by wywsoor** [comment]
同样的问题期待修复

**Comment by nijiong** [comment]
同样的问题期待修复

**Comment by fdj94** [comment]
VantWeapp 版本 1.7.1  还是会出现这个问题

**Comment by qiuziGirl** [comment]
> VantWeapp 版本 1.7.1 还是会出现这个问题

微信原生组件的问题，用原生的 textarea 也有这个问题

**Comment by thankslyh** [comment]
VantWeapp 版本
1.6.8

基础库版本
2.21.3

我这的现象是首次打开popup placeholder的颜色会继承自父级，输入字删除后placeholder颜色正常

![image](https://user-images.githubusercontent.com/94101777/150506875-3ee58233-1a02-4a5a-9b31-3e464a98e0bc.png)
![image](https://user-images.githubusercontent.com/94101777/150506923-ca12ebe8-624e-4242-b211-b8b0c1069c25.png)
![image](https://user-images.githubusercontent.com/94101777/150507391-e108f32c-7666-4635-b00e-8ad24b026f2c.png)
![image](https://user-images.githubusercontent.com/94101777/150507752-a95d7278-b05e-4f01-95ba-a9692e5dd0dd.png)

**Comment by thankslyh** [comment]
![image](https://user-images.githubusercontent.com/94101777/150519498-5be46a73-2a4d-44dc-8ce5-ee230baf141c.png)
![image](https://user-images.githubusercontent.com/94101777/150519529-b9f95bdf-17a4-4488-9e02-4f10f0648102.png)
可以这样尝试解决一下

**Comment by johnsonwong666** [comment]
没有复现，可以提供一下复现小程序代码片段吗？

**Comment by johnsonwong666** [comment]
没有复现。由于较长时间没有提供复现代码片段，此issue暂时关闭，若能复现请提新的issue,并附带复现代码片段排查。
