### ISSUE TITLE
[Bug Report] calender选择后展示错误

### ISSUE THREAD

**Issue by zhangchuanbo** [youzan/vant-weapp#4073]
### 设备
PC端vant小程序演示版、手机端小程序演示版

### VantWeapp 版本
1.6.8

### 基础库版本
2.13.0

### 如果是 UI 问题，截图链接（多图回车分隔）

![截图](https://i.loli.net/2021/03/03/Tz7yRiQog6rkqlb.png)

### 请提供核心代码片段链接
https://github.com/youzan/vant-weapp/tree/dev/dist/calendar

### 描述问题
在小程序中calender日历组件选择完成之后显示为NAN

**Comment by linus-lin** [comment]
有人处理一下这个问题吗？小程序正式版会有这个问题吗？我用体验版，android 没问题，iphone复现了

**Comment by tidjean** [comment]
Same here, only on Iphone...

**Comment by landluck** [comment]
可以用最新版本试一下，我这边没有复现，如能复现，可以提供代码片段 和 设备信息后重新打开 issue
