### ISSUE TITLE
[Bug Report] vant 的复选框组如何使用自定义图标  如何确定某个选项是否被选中

### ISSUE THREAD

**Issue by yuanhuanwebfront** [youzan/vant-weapp#4074]
### 设备
iphone6

### VantWeapp 版本
1.6.8

### 基础库版本
2.15.0

### 请提供核心代码片段链接
https://gist.github.com/yuanhuanwebfront/320dc7958fa373e7734dab5cfe6010bd

### 描述问题
我的这种写法没有生效

**Comment by rex-zsd** [comment]
只有 wxml 部分的代码，没办法分析到问题哈。
可以看 [组件文档](https://youzan.github.io/vant-weapp/#/checkbox)，直接复制“复选框组”的代码下来，再逐步修改。
