### ISSUE TITLE
[Bug Report] icon 无法显示

### ISSUE THREAD

**Issue by LvJing520** [youzan/vant-weapp#4076]
### 设备
微信开发者工具

### VantWeapp 版本
1.6.8

### 基础库版本
1.6.8

### 如果是 UI 问题，截图链接（多图回车分隔）

![截图](https://sm.ms/image/WiTsPCrG8z4BnIS)

### 请提供核心代码片段链接
https://sm.ms/image/RG8SXUvmHbAwe9M

### 描述问题
在uniapp上使用vant-weapp，iconfont无法显示

**Comment by chenjiahan** [comment]
小程序本身是支持 iconfont 的，建议将此问题反馈给 uni-app
