### ISSUE TITLE
[Bug Report] GoodsAction 商品导航 底部安全距离

### ISSUE THREAD

**Issue by JhouXu** [youzan/vant-weapp#4083]
### 设备
iphoneX  

### VantWeapp 版本
1.6.8

### 基础库版本
2.14.4

### 如果是 UI 问题，截图链接（多图回车分隔）

![截图](https://i.loli.net/2021/03/11/QNbMSc1kT2Lv59a.png)

![截图](https://i.loli.net/2021/03/11/3ZVjkqLRhoWQd4T.png)

### 请提供核心代码片段链接
https://github.com.cnpmjs.org/JhouXu/guiyi.git

### 描述问题
在iphoneX上，安全距离显示塌陷，在左侧的icon图标可以正常显示，但是在右侧的button上就显示出上半部分的背景没有了。(当前页面路径是pages/goodslist)

**Comment by nemo-shen** [comment]
@JhouXu 

- 提供的核心代码片段链接失效
- 开发者工具iPhone11调试未复现
- iPhone11真机调试未复现
