### ISSUE TITLE
[Bug Report] NoticeBar 通告栏组件bug

### ISSUE THREAD

**Issue by XieWuHen** [youzan/vant-weapp#4084]
### 设备
开发者工具、安卓手机

### VantWeapp 版本
1.6.8

### 基础库版本
2.16.0

### 请提供核心代码片段链接
https://developers.weixin.qq.com/s/mnACoImF7Bo8

### 描述问题
1、滚动速度不准确；
2、文本不溢出时也同样滚动，并没有自动检测文本是否溢出；

**Comment by XieWuHen** [comment]
因为代码片段分享有大小限制，所以请在小程序开发工具中先npm下载并构建vant

**Comment by li-chang-ping** [comment]
文本不溢出时也同样滚动这个问题，改一下代码就行了，源代码有一个小的逻辑错误，定位到文件 `miniprogram_npm\@vant\weapp\notice-bar\index.js`,将 76 行的

```js
if (scrollable || wrapRect.width < contentRect.width) {
  ......
}
```

改为


```js
if (scrollable && wrapRect.width < contentRect.width) {
  ......
}
```

就行了 @XieWuHen

**Comment by XieWuHen** [comment]
@li-chang-ping 谢谢，问题解决了☺
