### ISSUE TITLE
日历组件formatter函数里获取不到this里的变量

### ISSUE THREAD

**Issue by shanghaobo** [youzan/vant-weapp#4087]
日历组件配置formatter后，在formatter函数里打印this里的变量是undefined，是怎么回事？

**Comment by shanghaobo** [comment]
`<template>
	<view>
		<van-calendar
		  title="日历"
		  class="calendar"
		  :formatter="formatter"
		  :poppable="false"
		  :other="a"
		>
		</van-calendar>
	</view>
</template>

<script>
	export default{
		data(){
			return{
				a:123
			}
		},
		mounted(){
			console.log('xxx=',this.a);
		},
		methods:{
			formatter(day){
				console.log('a',this.other);
				return day;
			}
		}
	}
</script>

<style>
</style>
`
打印出来是`undefined`

**Comment by shanghaobo** [comment]
```
<template>
	<view>
		<van-calendar
		  title="记录日历"
		  class="calendar"
		  :formatter="formatter"
		  :poppable="false"
		  :other="a"
		>
		</van-calendar>
	</view>
</template>

<script>
	export default{
		data(){
			return{
				a:123
			}
		},
		mounted(){
			console.log('xxx=',this.a);
		},
		methods:{
			formatter(day){
				console.log('a',this.other);
				return day;
			}
		}
	}
</script>

<style>
</style>

```
打印出来是undefined

**Comment by rex-zsd** [comment]
mpvue 不清楚问题的逻辑是什么。
在原生小程序中，data 内虽然可以定义方法，但是方法无法访问到组件实例，即以下的代码是有问题的
```js
Page({
  data: {
    formatter() {
      console.log(this);
    }
  }
});
```
可以使用如下的方法来使 `formatter` 能正常访问到 `this`
```js
Page({
  data: {},

  attached() {
    this.setData({
      formatter() {
        console.log(this);
      }
    });
  }
});
```

**Comment by rex-zsd** [comment]
mpvue 也可以按照上面代码的思路调整下看能否访问到 this。
