### ISSUE TITLE
[Bug Report] van-area数据渲染不出来

### ISSUE THREAD

**Issue by Jason318** [youzan/vant-weapp#4088]
### 设备
iPhone11

### VantWeapp 版本
1.6.8

### 基础库版本
最新版

### 请提供核心代码片段链接
https://git.weixin.qq.com/Jason318/vantweappdemo.git

### 描述问题
现在的问题是：空白显示，area.js格式和官网要求的一样，我也打印了一下，areaList也获取到了数据，就是不显示任何东西，就连标题、取消和确定按钮都不显示，麻烦帮忙看下是什么原因。

**Comment by Jason318** [comment]
各位老板，有时间看看我这个问题啊

**Comment by AgoniNemo** [comment]
同样的问题
