### ISSUE TITLE
[Feature Request] 如何动态创建对话框

### ISSUE THREAD

**Issue by yangshuyi** [youzan/vant-weapp#4090]
### 这个功能解决了什么问题
能否做到不通过在wxml引入van-dialog的情况下，通过js的方式动态创建对话框，并进行展示

### 建议的API是什么样的
能否做到不通过在wxml引入van-dialog的情况下，通过js的方式动态创建对话框，并进行展示

**Comment by rex-zsd** [comment]
小程序不存在动态创建 DOM 的能力，wxml 预先引入组件是必要的哈。
