### ISSUE TITLE
[Bug Report] van-action-sheet滚动会引起下层page的滚动

### ISSUE THREAD

**Issue by czl0325** [youzan/vant-weapp#4091]
### 设备
模拟器

### VantWeapp 版本
1.6.8

### 基础库版本
2.15.0

### 请提供核心代码片段链接
https://gist.github.com/czl0325/64e01dd9c852df15326727f5ae2ba511

### 描述问题
van-action-sheet选项过多，当滚动到顶部后，再往下拉，会触发page的下拉刷新，如果page有开启enablePullDownRefresh的话，当滚动到底部，再往上拉，会触发page向上滚动。

**Comment by rex-zsd** [comment]
参考这里的 [文档说明](https://youzan.github.io/vant-weapp/#/popup#zu-jian-gun-dong-chuan-tou-gai-zen-me-jie-jue)，小程序目前没有办法很好地处理滚动穿透的问题。
如果确认你的弹层内部不存在滚动的场景，可以用如下的方法禁止滚动。

```html
<van-action-sheet catch:touchmove="noop" />
```
