### ISSUE TITLE
微信小程序van-button的disabled属性为true时仍能触发点击事件

### ISSUE THREAD

**Issue by HWT-coder** [youzan/vant-weapp#4092]
请问是将点击事件绑定在了组件的div里了吗

**Comment by rex-zsd** [comment]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater?repo=VantWeapp

没有提供代码没办法定位问题哈。
猜测你使用了 `bindtap` 而不是 `bind:click` 来监听点击事件，`disabled` 属性禁止的点击事件是 `click`。

**Comment by Vekaco** [comment]
楼上正解
