### ISSUE TITLE
ImagePreview 图片预览在组件复用是预览多图之后单图片

### ISSUE THREAD

**Issue by BlackJackSen** [youzan/vant-weapp#4095]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。
前提 封装公共组件复用  设置startPosition为当前点击图片索引
http://vant-contrib.gitee.io/vant-issue-generater?repo=VantWeapp
![image](https://user-images.githubusercontent.com/50441255/110939082-d00c2f00-836f-11eb-88e4-7ef3969d23ed.png) 

问题描述  
单个图片和多个图片存在的时候，点击多个图片区域索引非0的图片 再次点击 单个图片区域显示异常

**Comment by BlackJackSen** [comment]
![image](https://user-images.githubusercontent.com/50441255/110939419-5b85c000-8370-11eb-8a38-acbfe6fee306.png)

**Comment by BlackJackSen** [comment]
官网看到了，解决下问题啊！

**Comment by Serifx** [comment]
你说的是否是 [Vant](https://github.com/youzan/vant)，而不是 Vant-weapp。

请转 vant 再确认下吧
