### ISSUE TITLE
使用popup+微信原生的tabBar，popup show的时候出现还能展示tabBar的内容问题

### ISSUE THREAD

**Issue by wendylan** [youzan/vant-weapp#4096]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater?repo=VantWeapp

**Comment by rex-zsd** [comment]
原生底部导航是原生组件，层级上不属于页面的一部分了，想要遮挡是不可能实现的哈。
