### ISSUE TITLE
[Bug Report] 组件内部Button 的 hover-class样式无法去除

### ISSUE THREAD

**Issue by eastyu** [youzan/vant-weapp#4098]
### 设备
iOS 14

### VantWeapp 版本
1.6.8

### 基础库版本
1.6.8

### 请提供核心代码片段链接
https://gist.github.com/eastyu/38c94bf61ba254ad6ba069eabfaec7d8

### 描述问题
有一些组件比如GoodsAction 商品导航，内部的button具有hover-class样式，外部无法删除或者自定义

**Comment by rex-zsd** [comment]
`hover-class` 是一个特殊的 class，不可以跨组件传递。
可以查看一下 [样式覆盖](https://youzan.github.io/vant-weapp/#/custom-style) 部分的文档，通过解除样式隔离等方法进行样式定制哈。
