### ISSUE TITLE
建议修改 index-bar文档

### ISSUE THREAD

**Issue by likaixuan** [youzan/vant-weapp#4100]
![image](https://user-images.githubusercontent.com/17825609/111407316-9b50fc80-870e-11eb-93d0-97c37a5e8c5c.png)

增加cell的引入，不引入cell是会渲染不出内容的

**Comment by rex-zsd** [comment]
没有必要吧，这一节是说明如何引入 IndexBar 组件。
Cell 组件并不是使用 IndexBar 所必须引入的组件，示例中使用 Cell 组件只是为了免去一些基本的样式处理。开发者完全可以不引入 Cell 组件，而自行定义需要渲染的选项样式。

**Comment by simplesilence** [comment]
非常同意，这文档写的跟狗屎一样，没有cell啥也渲染不出来，导致从别的组件库转过来的同学，一头雾水，谁没事干要把他的文档从头读到尾再开始开发
