### ISSUE TITLE
picker滑动卡顿

### ISSUE THREAD

**Issue by Axu96** [youzan/vant-weapp#4101]
![image](https://user-images.githubusercontent.com/28865316/111434691-cbae9000-873a-11eb-990e-6959abd3a9c3.png)
picker卡顿  因为有一个undefined   
![image](https://user-images.githubusercontent.com/28865316/111434626-ba658380-873a-11eb-9a10-04af1133bedf.png)
缺少这个传参
![image](https://user-images.githubusercontent.com/28865316/111434828-fc8ec500-873a-11eb-9718-0f7e1aa1880d.png)
导致这个文件里面没取到值

**Comment by eastyu** [comment]
@Axu96 参考这个PR https://github.com/youzan/vant-weapp/pull/4099
