### ISSUE TITLE
[Bug Report] 拍照界面重启后无法将值重新赋值到界面上

### ISSUE THREAD

**Issue by duxingzhe** [youzan/vant-weapp#4103]
### 设备
苹果8 ios13.6

### VantWeapp 版本
1.6.8

### 基础库版本
518

### 请提供核心代码片段链接
https://gist.github.com/duxingzhe/317685f02d90bf4ddd6c50a126cf00e9

### 描述问题
在上传图片的时候，如果使用vant-field组件输入了字符串，然后拍照上传图片，界面会重新加载。这时，后台打印console日志，发现对应的值还是存在，但是必须外部赋值。所以，依旧是vant-field双向绑定的问题。

**Comment by KiteWorld** [comment]
我的也是这样，找到解决的办法了吗？太难了。

**Comment by duxingzhe** [comment]
修改控件的组件代码，设置一个在外面赋值的函数，所附代码写了，要判断一下。

**Comment by landluck** [comment]
替换 wx.chooseImage 为 wx.chooseMedia 能解决选择图片页面刷新问题，提供的 uploader 组件内部已替换，如还有问题可以提供一个小程序复现代码片段协助排查
