### ISSUE TITLE
[Bug Report] dropdown-menu下拉菜单连续点击（左右）两边菜单栏动画过渡问题

### ISSUE THREAD

**Issue by yik7707** [youzan/vant-weapp#4104]
### 设备
微信开发者工具

### VantWeapp 版本
1.6.8

### 基础库版本
2.16.0

### 请提供核心代码片段链接
https://gitee.com/yik7707/question-feedback/issues/I3C8J3

### 描述问题
dropdown-menu下拉菜单连续点击（左右）两边菜单栏动画过渡问题，连续操作（点击左边再点右边），两次动画收缩再弹出，希望得到解决

**Comment by johnsonwong666** [comment]
升级到最新版本试试。真机和模拟器测试了一下，左右快速切换没有复现。
