### ISSUE TITLE
手风琴增加size="large"属性

### ISSUE THREAD

**Issue by mayong49277** [youzan/vant-weapp#4105]
![image](https://user-images.githubusercontent.com/9914424/111858730-2b44af80-8976-11eb-82d7-cb66feb4cb62.png)

建议给手风琴组件加入size=large属性，否则整体布局效果无法统一

**Comment by landluck** [comment]
该属性已支持

**Comment by mayong49277** [comment]
***@***.***的邮件已收到，我会尽快回复或与您联系。
