### ISSUE TITLE
没有人遇到一些带有遮罩层组件的点击蒙层不能关闭的问题吗？

### ISSUE THREAD

**Issue by 17610532757** [youzan/vant-weapp#4106]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater?repo=VantWeapp

**Comment by rex-zsd** [comment]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater?repo=VantWeapp
