### ISSUE TITLE
[Bug Report] van-search在华为手机自带键盘无法获取值

### ISSUE THREAD

**Issue by Virczz** [youzan/vant-weapp#4107]
### 设备
huawei p40 pro

### VantWeapp 版本
1.6.8

### 基础库版本
2.15

### 描述问题
![微信截图_20210322183452.png](https://i.loli.net/2021/03/22/DM93HufhRPBYNpG.png)
在键盘输入时,van-search如果不点击键盘上的JL，直接点击键盘的搜索按钮，van只会获取到"021"。

微信自带输入框监听了onconfirm，同样的操作，可以获取到"021JL"。

 van-field也有这个问题。

**Comment by nemo-shen** [comment]
@Virczz 图片碎了。。。

**Comment by Virczz** [comment]
直接使用 onSearch或 onSearchClick中的参数，会存在这个问题。但是如果用data保存了onSearchChange中的数据，在onSearch或 onSearchClick中是可以正常获取到的
