### ISSUE TITLE
[Bug Report] DropDownMenu下拉菜单组件，文档提供的change事件无效

### ISSUE THREAD

**Issue by Zebra-web** [youzan/vant-weapp#4108]
### 设备
微信开发者工具，Android真机

### VantWeapp 版本
1.6.8

### 基础库版本
2.14.0

### 请提供核心代码片段链接
https://gist.github.com/Zebra-web/ba570a4901b9c7dbb010c7ae0877616e

### 描述问题
DropDownMenu下拉菜单组件，其中的van-dropdown-item组件，按照文档提供的change事件定义的方法没有触发，控制台没有打印value，文档提供的其他事件我也试过，同样没有触发。从官方组件示例上弄也没有效果，同时我也发现官方文档中缺少事件调用的示例。希望官方能修复该问题并完善文档

**Comment by nemo-shen** [comment]
bind:change="onChange"
