### ISSUE TITLE
pupop属性不生效

### ISSUE THREAD

**Issue by yutianmr** [youzan/vant-weapp#4112]
![image](https://user-images.githubusercontent.com/57926052/112606302-2d65ad00-8e53-11eb-8e37-7d5c44a40159.png)

**Comment by yutianmr** [comment]
:close-on-click-overlay='false'  禁止遮罩层关闭  为什么不生效？？？？？

**Comment by rex-zsd** [comment]
```
close-on-click-overlay="{{ false }}"
```
