### ISSUE TITLE
平时在编译小程序时总是会出现这个错误，请问怎么解决？

### ISSUE THREAD

**Issue by MuGongziya** [youzan/vant-weapp#4114]
虽然不影响小程序，但是还是想问问你们应该如何解决
![1](https://user-images.githubusercontent.com/66168501/112739702-028d6d00-8fa9-11eb-9d70-ee6b5a0a9220.png)

**Comment by julyL** [comment]
这个问题应该问微信，我记得只有开发者工具里面才有这个报错

**Comment by rex-zsd** [comment]
这个是开发者工具本身的问题，可以忽略，[文档](https://youzan.github.io/vant-weapp/#/icon#kai-fa-zhe-gong-ju-shang-ti-shi-faild-to-load-font-shi-shi-me-qing-kuang) 这里有说明哈。

**Comment by MuGongziya** [comment]
好的谢谢。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年4月2日(星期五) 上午9:48
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [youzan/vant-weapp] 平时在编译小程序时总是会出现这个错误，请问怎么解决？ (#4114)





 
这个是开发者工具本身的问题，可以忽略，文档 这里有说明哈。
