### ISSUE TITLE
Circle组件在ios 会随着屏幕滚动而滚动

### ISSUE THREAD

**Issue by Cysis** [youzan/vant-weapp#4117]
![image](https://user-images.githubusercontent.com/34828064/112800572-6778be00-90a2-11eb-989f-8d09074b22fa.png)

**Comment by Cysis** [comment]
第一次提问题  需要 粘贴代码片段以及其他东西吗

**Comment by rex-zsd** [comment]
van-circle 基于 canvas 实现，是一个原生组件，层级是比一般的自定义组件要高的。
要解决这个问题，可以将 van-circle 的 `type` 属性设置为 `2d`，开启同层渲染。
