### ISSUE TITLE
[Bug Report] field如何实现左右排版

### ISSUE THREAD

**Issue by xiaoxiaofan123** [youzan/vant-weapp#4118]
### 设备
开发者工具

### VantWeapp 版本
1.6.8

### 请提供核心代码片段链接
https://gist.github.com/xiaoxiaofan123/12c4fcb9e9ad6bfd2e9a8bdd08d26833

### 描述问题
按官方文档例子书写 实现的效果为label和text 上下排版，希望是左右排版
![image](https://user-images.githubusercontent.com/18550815/112824210-d8c56a80-90bc-11eb-914c-bb2a95d36631.png)

**Comment by rex-zsd** [comment]
从截图来看，组件的样式完全没有生效，可以看下是否是组件引入有问题或是开发者工具的缓存问题。
