### ISSUE TITLE
[Bug Report] uploader文件上传组件show-upload失效

### ISSUE THREAD

**Issue by yuchenbin1** [youzan/vant-weapp#4119]
### 设备
安卓、ios

### VantWeapp 版本
1.6.7

### 基础库版本
2.14.4

### 如果是 UI 问题，截图链接（多图回车分隔）

![截图](https://sm.ms/image/QOE7I85WhLw3UJb)

### 请提供核心代码片段链接
https://gitee.com/yuchenbin/codes/9ndws4j35g1ifqlyb6eu010

### 描述问题
show-load默认为true，设置为false后还是展示了文件上传的按钮，希望有api可以控制整个上传摄像头上传所在容器的显示

**Comment by nemo-shen** [comment]
无法复现
