### ISSUE TITLE
[Bug Report] van-datetime-picker组件type="year-month"时，选择年份出现bug

### ISSUE THREAD

**Issue by zongrenCode** [youzan/vant-weapp#4120]
### 设备
安卓、苹果手机

### VantWeapp 版本
1.6.8

### 基础库版本
微信小程序版本

### 请提供核心代码片段链接
https://github.com/youzan/vant-weapp/blob/dev/packages/datetime-picker/index.ts

### 描述问题
van-datetime-picker组件type="year-month"时，选择年份出现bug
        代码行中269-272中
        let date = getTrueValue(values[2]);
        if (data.type === 'year-month') {
          date = 1;
        }
改为
        let date = 1;
        if (data.type === 'year-month') {
          date = getTrueValue(values[2]);;
        }

**Comment by XBIsland** [comment]
同样遇到这个问题
![image](https://user-images.githubusercontent.com/36447895/115176378-944b4e80-a0ff-11eb-8213-adaf0e6e1c62.png)

type为year-month时
getTrueValue获取date时没做undefined校验
导致 if (data.type === 'year-month') 下面的逻辑都执行不了
date应该给个默认值

**Comment by XBIsland** [comment]
> 同样遇到这个问题
> ![图像](https://user-images.githubusercontent.com/36447895/115176378-944b4e80-a0ff-11eb-8213-adaf0e6e1c62.png)
> 
> 类型为年月时
> getTrueValue获取日期时没做未定义的校正
> 导致if（data.type ==='year-month'）下面的逻辑都执行不了
> 日期应该给个替代值

删除本地包重新 install之后可以了，应该是本地的包是旧的

**Comment by nemo-shen** [comment]
@zongrenCode `getTrueValue`是有对`undefined`进行判断的，可以看下`vant-weapp/packages/datetime-picker/index.ts` line 30
