### ISSUE TITLE
van-search组件，使用搜狗输入法输入英文时，onchange无法获取输入的内容

### ISSUE THREAD

**Issue by JImumu** [youzan/vant-weapp#4121]
android手机中，使用搜狗输入法

用户输入了英文，但是没有点击键盘内的K，这个时候点击搜索无法获取输入框里的内容
![image](https://user-images.githubusercontent.com/25128849/112955217-c78a6580-9171-11eb-81d7-df2f1454c167.png)

**Comment by JImumu** [comment]
希望可以开放input事件的监听

**Comment by JImumu** [comment]
改成input事件也木有用【无奈】

**Comment by rex-zsd** [comment]
这个是小程序原生 input 组件的问题，不是 vant weapp 的问题，所以是没有办法修复的呢。
