### ISSUE TITLE
为什么小程序组件不做rpx适配呢？

### ISSUE THREAD

**Issue by LiangQinAo** [youzan/vant-weapp#4122]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater?repo=VantWeapp

很疑惑？为什么小程序版本的vant不做rpx适配呢？

**Comment by rex-zsd** [comment]
可以搜下历史 issue 哈，已经做过多次回应了。
