### ISSUE TITLE
[Bug Report] van-dropdown-item选项超出屏幕时，手指无法触摸滑动

### ISSUE THREAD

**Issue by xiaoli-style** [youzan/vant-weapp#4125]
### 设备
iPhoneX

### VantWeapp 版本
1.6.8

### 基础库版本
2.16.0

### 如果是 UI 问题，截图链接（多图回车分隔）

![F__0@R7Z_FY__E7CJLIIDI2.png](https://i.loli.net/2021/03/31/nCB4zDsq3itEovp.png)

### 请提供核心代码片段链接
http://暂无.com/

### 描述问题
van-dropdown-item选项特别多并且超出屏幕时，在微信中手指无法触摸滑动，但在PC端的微信开发者工具中使用鼠标滚轮可以上下滑动

**Comment by landluck** [comment]
测试没有能复现，如能复现，可以提供 [小程序代码片段](https://developers.weixin.qq.com/miniprogram/dev/devtools/minicode.html) 协助排查，提供后可以重新打开 issue 或者重新提交
