### ISSUE TITLE
[Bug Report] wx.reLaunch 跳转  page-scroll  'vanPageScroller' of undefined

### ISSUE THREAD

**Issue by accardo** [youzan/vant-weapp#4127]
![image](https://user-images.githubusercontent.com/12389303/113108133-3d0c3980-9237-11eb-97b6-a68716097b37.png)

### 设备
iphone7 plus

### VantWeapp 版本
1.6.8

### 基础库版本
2.16

### 请提供核心代码片段链接
https://vant-contrib.gitee.io/vant-weapp/#/tab

### 描述问题
当使用了 tab 标签组件的时候， 使用wx.reLaunch  跳转到 tab标签页面之后   调用了 page-scroll库才 出现 Cannot read property 'vanPageScroller' of undefined错误，
本人测试了一下 wx.reLaunch 跳转之后 page 是undefined。所以要加个判断 page 是否存在

**Comment by shenjingnan** [comment]
已在1.8.6中修复
