### ISSUE TITLE
van-cell slot

### ISSUE THREAD

**Issue by zhuyuesen** [youzan/vant-weapp#4129]
设备
微信开发者工具

VantWeapp 版本
1.6.8

基础库版本
2.16.0

请提供核心代码片段链接
https://vant-contrib.gitee.io/vant-weapp/#/cell#cell-slot

描述问题
van-cell slot value不生效

**Comment by rex-zsd** [comment]
请提供你使用组件的代码片段，否则无法找到问题所在

**Comment by zhuyuesen** [comment]
> 请提供你使用组件的代码片段，否则无法找到问题所在

`
<van-cell title="单元格">
 <view slot>这是应该出现的测试数据，但是并没有渲染出来</view>
  <van-icon slot="right-icon" name="search" class="custom-icon" />
</van-cell>
`
看官方文档，此处默认slot应该渲染为van-cell的value值，但是并没有挂载上

**Comment by zhuyuesen** [comment]
是我姿势错了，对不起
```
<van-cell title="选择时间" title-width="180rpx" >
      <van-radio-group value="{{ form.forenoon }}" direction="horizontal" bind:change="apChange">
        <van-radio name="{{true}}" checked-color="#006241">上午</van-radio>
        <van-radio name="{{false}}" checked-color="#006241">下午</van-radio>
      </van-radio-group>
    </van-cell>
```
