### ISSUE TITLE
使用wepy开发小程序，如何使用这个ui框架

### ISSUE THREAD

**Issue by wisdomQiuqiu** [youzan/vant-weapp#413]
使用wepy开发小程序，如何使用这个ui框架

**Comment by ityao** [comment]
同问, 按照说明引用好像不行,

CLI报错：找不到组件

**Comment by ityao** [comment]
写成这样在config里面声明好像可以用, 要重新启动wepy进行编译
```
export default class Index extends wepy.page {
    config = {
      navigationBarTitleText: '样例页面',
      usingComponents: {
        'van-button': '../components/vant/button/index'
      }
    }
```

**Comment by FrostyBonny** [comment]
楼上的方法依旧不行啊，显示找不到
```
Component is not found in path "components/dist/button/index" (using by "pages/mine/index")

**Comment by garvisjack** [comment]
同求，困扰很久
Component is not found in path "path/to/vant-weapp/dist/button/index" (using by "pages/main/index")

**Comment by aloneszjl** [comment]
1、跑 npm i vant-weapp -S --production
2、跑去node_modules/want-weapp 把 dist 文件夹copy到你项目src/components/dist里面去,这里我把dist名字换成van，所以是src/components/van
3、然后就可以用了，附上截图 
![image](https://user-images.githubusercontent.com/19307426/44468995-1803c300-a659-11e8-9a83-578072452b1c.png)

**Comment by Eamonnzhang** [comment]
@aloneszjl 
按照你的方法引入之后报错。。
![image](https://user-images.githubusercontent.com/9126544/44503620-d7905d80-a6c9-11e8-946c-3e8ce95e5f3d.png)

**Comment by stone009** [comment]
```button```库好像一直提示找不到文件，大家有遇到吗？

![image](https://user-images.githubusercontent.com/25975586/44517358-10482b00-a6fa-11e8-94b3-72875c2f539e.png)

这样直接也用不了
```
usingComponents: {
        'van-cell': '/components/van/cell/index',
        'van-cell-group': '/components/van/cell-group/index',
        'van-button': '/components/van/button/index'
      }
```

**Comment by 531431988** [comment]
> 1、跑 npm i vant-weapp -S --production
> 2、跑去node_modules/want-weapp 把 dist 文件夹copy到你项目src/components/dist里面去,这里我把dist名字换成van，所以是src/components/van
> 3、然后就可以用了，附上截图
> ![image](https://user-images.githubusercontent.com/19307426/44468995-1803c300-a659-11e8-9a83-578072452b1c.png)

你这种方式还用npm干嘛？直接down下载dist考进去不就完了，大家想问的应该都是如何不手动考如，如何配置

**Comment by yurizhang** [comment]
@chenjiahan 这个官方有没有什么明确的方案啊?

**Comment by Robinbiao** [comment]
请问下怎么使用js触发的toast类组件 ？？？

**Comment by teo001** [comment]
能否全局引入？

**Comment by chaim1986** [comment]
其实可以参考下minui的做法 做个类似min命令，我觉得就很不错哦，期待vant-weapp更新下。

**Comment by yushengyuan1993** [comment]
#### 同样使用wepy-cli快速生成的小程序，目前可以使用组件：
1. 直接通过 ``git` 下载 [Vant Weapp](https://github.com/youzan/vant-weapp) 源代码，并将dist目录拷贝到自己的项目中
  ```
  git clone https://github.com/youzan/vant-weapp.git
  ```
2. 将dist/目录拷贝到项目src/components/目录下面（根据自己目录接口调整）。
3. 在页面test.wpy中的config字段使用
  ```
  config = {
    usingComponents: {
      'van-popup': '../../components/dist/popup/index'
    }
  }
  ```
4. 使用，页面中：
  ```
  <van-popup show="{{ show }}" bind:close="onClose">内容</van-popup>
  ```

**Comment by echoisles** [comment]
在组件中如何使用呢 这个方法只能在 pages 中使用

**Comment by jy1989** [comment]
在app.wpy 用usingComponents引入可正常使用

**Comment by nyaapass** [comment]
> ![screenshot 2019-01-05_15-18-04](https://user-images.githubusercontent.com/17878239/50721646-c6d30800-10fd-11e9-83e5-eb5a6f9dc17d.png)
> 
> 1、通过 `npm` 安装 `vant-weapp` 后，会在 `node_modules` 出现` vant-weapp` 文件夹
> 
> 2、小程序开发工具中 ——> 工具栏 ——> 构建 `npm`， 成功后根路径生成 `miniprogram_npm` 文件夹
> 
> 3、`.json`中引入 `miniprogram_npm` 中对应的组件，而非 `node_modules` 中的
> 
> ` "usingComponents": { "van-button": "/miniprogram_npm/vant-weapp/button/index" }`

这种引入方式好像只适用于原生, wepy 的情况下似乎不行:

小程序[官方文档](https://developers.weixin.qq.com/miniprogram/dev/devtools/npm.html)中有说不允许 `node_modules` 在小程序根目录外, 而 wepy 项目的 `miniprogramRoot` 是指向 `dist` 的, 除非在 `dist` 目录里重新 `npm init` 生成 `node_modules`, 不然点击 **构建 npm** 按钮肯定会报错:

> 没有找到 node_modules 目录。

**Comment by ctcx** [comment]
建议官方跟进，毕竟现在使用wepy开发小程序的越来越多了～

**Comment by rex-zsd** [comment]
> 建议官方跟进，毕竟现在使用wepy开发小程序的越来越多了～

vant-weapp是一个小程序原生的组件库，按照wepy官方的原生组件引入方式就可以了。
还是多给wepy提提issue让他们更好地支持原生组件吧。

**Comment by BruceLeung** [comment]
> #### 同样使用wepy-CLI快速生成的小程序，目前可以使用组件：
> 1. 直接通过`git `下载[Vant Weapp](https://github.com/youzan/vant-weapp)源代码，并将dist目录拷贝到自己的项目中
> 
> ```
> git clone https://github.com/youzan/vant-weapp.git
> ```
> 1. 将DIST /目录拷贝到项目的src /组件/目录下面（根据自己目录结构调整）。
> 2. 在页面test.wpy中的配置字段使用
> 
> ```
> config = {
>   usingComponents: {
>     'van-popup': '../../components/dist/popup/index'
>   }
> }
> ```
> 1. 使用，页面中：
> 
> ```
> <van-popup show="{{ show }}" bind:close="onClose">内容</van-popup>
> ```

请问你的onClose事件在哪里注册？我的写了说找不到这个方法，不论是写在methods = {}里面还是和methods = {}同级都不行

**Comment by vm0100** [comment]
我把wepy-plugin-iview 改成了wepy-plugin-vant  可以很轻松的引入插件了 哈哈哈
使用方式见 wepy-plugin-vant(https://github.com/vm0100/wepy-plugin-vant.git "With a Title").

**Comment by ainicui** [comment]
wepy1.0引入没试过，不过wepy2.0是可以引入的，我是这样引入的
`<config>
{
    navigationBarTitleText: 'Vant小程序UI库',
    usingComponents: {
      "van-button": "module:vant-weapp/dist/button",
      "van-rate": "module:vant-weapp/dist/rate"
    }
}
</config>`

**Comment by ainicui** [comment]
wepy1.0引入没试过，不过wepy2.0是可以引入的，我是这样引入的
```
<config>
{
    navigationBarTitleText: 'Vant小程序UI库',
    usingComponents: {
      "van-button": "module:vant-weapp/dist/button",
      "van-rate": "module:vant-weapp/dist/rate"
    }
}
</config>
```

**Comment by bundlejs** [comment]
> wepy1.0引入没试过，不过wepy2.0是可以引入的，我是这样引入的
> 
> ```
> <config>
> {
>     navigationBarTitleText: 'Vant小程序UI库',
>     usingComponents: {
>       "van-button": "module:vant-weapp/dist/button",
>       "van-rate": "module:vant-weapp/dist/rate"
>     }
> }
> </config>
> ```
> 
> 补充一下，貌似用cnpm下载资源包会有问题 我是用npm就没事了

我也是这样引入的,但是dialog之类的组件遮罩层显示不正常呢

**Comment by jiangz153202** [comment]
> > wepy1.0引入没试过，不过wepy2.0是可以引入的，我是这样引入的
> > ```
> > <config>
> > {
> >     navigationBarTitleText: 'Vant小程序UI库',
> >     usingComponents: {
> >       "van-button": "module:vant-weapp/dist/button",
> >       "van-rate": "module:vant-weapp/dist/rate"
> >     }
> > }
> > </config>
> > ```
> > 
> > 
> > 补充一下，貌似用cnpm下载资源包会有问题 我是用npm就没事了
> 
> 我也是这样引入的,但是dialog之类的组件遮罩层显示不正常呢

改变引入方式 不要使用module方式 直接把lib的包引入components中 然后按照vant的示例做就好了。
"van-notify": "~@/components/lib/notify/index",

**Comment by twdp** [comment]
> wepy1.0引入没试过，不过wepy2.0是可以引入的，我是这样引入的
> 
> ```
> <config>
> {
>     navigationBarTitleText: 'Vant小程序UI库',
>     usingComponents: {
>       "van-button": "module:vant-weapp/dist/button",
>       "van-rate": "module:vant-weapp/dist/rate"
>     }
> }
> </config>
> ```
> 
> 补充一下，貌似用cnpm下载资源包会有问题 我是用npm就没事了

bind-click正常吗？我试着展示都正常，就是点击事件emit不出来

**Comment by Rongfuchuan** [comment]
我把dist文件夹copy到了components下，改名van

 usingComponents: {
    "van-tab": "~@/components/van/tab/index",
    "van-tabs": "~@/components/van/tabs/index"
  }

然后注册组件的时候报错了

 ERR! Error: Can't resolve './bem.wxs' in 'C:\Code\info-wepy\src\components\van\tab'

所有依赖都是最新的，不知道怎么回事

**Comment by ainicui** [comment]
> > wepy1.0引入没试过，不过wepy2.0是可以引入的，我是这样引入的
> > ```
> > <config>
> > {
> >     navigationBarTitleText: 'Vant小程序UI库',
> >     usingComponents: {
> >       "van-button": "module:vant-weapp/dist/button",
> >       "van-rate": "module:vant-weapp/dist/rate"
> >     }
> > }
> > </config>
> > ```
> > 
> > 
> > 补充一下，貌似用cnpm下载资源包会有问题 我是用npm就没事了
> 
> bind-click正常吗？我试着展示都正常，就是点击事件emit不出来

例如<van-dialog use-slot="true" title="标题" overlay="true" show="{{ show }}" show-cancel-button="true" confirm-button-open-type="getUserInfo" @close.user="onClose" >
    </van-dialog> 这个组件，如果添加事件的话，需要在事件名后面加.user

**Comment by higboys** [comment]
> wepy1.0引入没试过，不过wepy2.0是可以引入的，我是这样引入的
> 
> ```
> <config>
> {
>     navigationBarTitleText: 'Vant小程序UI库',
>     usingComponents: {
>       "van-button": "module:vant-weapp/dist/button",
>       "van-rate": "module:vant-weapp/dist/rate"
>     }
> }
> </config>
> ```
> 
> 补充一下，貌似用cnpm下载资源包会有问题 我是用npm就没事了

wepy2.x 引入后编译时没报错但是，小程序模拟器启动时会报../wxs/utils.wxs not found from ./components/vant/button/index.wxml
![image](https://user-images.githubusercontent.com/26639907/71446625-5aaf4100-2760-11ea-941c-4fa485c99288.png)
![image](https://user-images.githubusercontent.com/26639907/71446634-74508880-2760-11ea-8fdd-fb7a7edbb616.png)
有遇到过的吗

**Comment by higboys** [comment]
> module:vant-weapp/dist/button



> wepy1.0引入没试过，不过wepy2.0是可以引入的，我是这样引入的
> 
> ```
> <config>
> {
>     navigationBarTitleText: 'Vant小程序UI库',
>     usingComponents: {
>       "van-button": "module:vant-weapp/dist/button",
>       "van-rate": "module:vant-weapp/dist/rate"
>     }
> }
> </config>
> ```
> 
> 补充一下，貌似用cnpm下载资源包会有问题 我是用npm就没事了

![image](https://user-images.githubusercontent.com/26639907/71446702-30aa4e80-2761-11ea-85c4-66b0f95e3635.png)
![image](https://user-images.githubusercontent.com/26639907/71446718-5899b200-2761-11ea-9ebd-dce7b734a72a.png)
有遇到过的吗

**Comment by higboys** [comment]
> 写成这样在config里面声明好像可以用, 要重新启动wepy进行编译
> 
> ```
> export default class Index extends wepy.page {
>     config = {
>       navigationBarTitleText: '样例页面',
>       usingComponents: {
>         'van-button': '../components/vant/button/index'
>       }
>     }
> ```

这是wepy 1.x  2.x版本还有各种奇葩错误呢

**Comment by badjone** [comment]
等待更新ing..
