### ISSUE TITLE
[Bug Report] vant-uploader：接收类型是media或是video，真机（ios和android）测试时它不会打开我的相册或者拍摄功能

### ISSUE THREAD

**Issue by wujunyou** [youzan/vant-weapp#4130]
### 设备
andriod

### VantWeapp 版本
1.6.8

### 基础库版本
2.16.0

### 请提供核心代码片段链接
https://youzan.github.io/vant-weapp/#/uploader

### 描述问题
vant-uploader：接收类型是media或是video，真机（android）测试时它不会打开我的相册或者是拍摄功能，而是微信的最近联系人列表呢？但在微信开发工具却可以成功。 
具体代码片段就是简单的
 <van-uploader file-list="{{ mediaList }}"  
                      max-count="1" 
                      accept="all"
                      preview-size="40px"
                      bind:delete="mediaListdelete"
                      bind:after-read="mediaListupload" />

**Comment by yueyuebixa** [comment]
<van-uploader file-list="{{ mediaList }}"  
                      max-count="1" 
                      name="video"
                      accept="all"
                      preview-size="40px"
                      bind:delete="mediaListdelete"
                      bind:after-read="mediaListupload" />

**Comment by yueyuebixa** [comment]
看了其他issue也没啥帮助，真机的确出现这样的问题。。。

**Comment by yueyuebixa** [comment]
直接调用wx.chooseVideo却又没问题，脑阔疼

**Comment by helloaiway** [comment]
次问题有点严重哇，能否修一下嘛，升级了版本就不行了。

**Comment by rex-zsd** [comment]
@helloaiway 请提供代码片段哈

**Comment by landluck** [comment]
可以使用最新版本以及较新的微信基础库进行测试，如还能复现，可以提供小程序代码片段后重新打开issue
