### ISSUE TITLE
微信小程序自定义组件中，不能用id，所以报错，这怎么解决？

### ISSUE THREAD

**Issue by yuanhaotian** [youzan/vant-weapp#4131]
<van-toast id="van-toast" />
未找到 van-toast 节点，请确认 selector 及 context 是否正确

**Comment by yuanhaotian** [comment]
页面这么用了，<van-toast id="van-toast" />

**Comment by yuanhaotian** [comment]
"<van-toast id="van-toast" />" 页面这么用了

**Comment by yuanhaotian** [comment]
![屏幕快照 2021-04-03 下午8 12 12](https://user-images.githubusercontent.com/36318960/113478051-f0379580-94b8-11eb-90c6-24ec4a7c3b7c.png)

**Comment by rex-zsd** [comment]
提示很直白了，`selector` 填对了吗？在组件里使用时 `context` 填对了吗？

**Comment by marren06** [comment]
> 提示很直白了，`selector` 填对了吗？在组件里使用时 `context` 填对了吗？
selector和context怎么填写？？？？  demo也没有填这俩属性啊

![image](https://user-images.githubusercontent.com/17778482/139614217-68a0eb4d-0d5b-4cf1-acc7-68fc9266bca8.png)
