### ISSUE TITLE
在tsconfig.json设置paths路径指向node_modules,页面还是找不到路径

### ISSUE THREAD

**Issue by PLUTO06210331** [youzan/vant-weapp#4132]
// tsConfig
{
	"compilerOptions": {
		"baseUrl": ".",
		"types": [
			"@dcloudio/types",
			"miniprogram-api-typings",
			"mini-types"
		],
		"paths": {
			"@vant/weapp/*": ["./node_modules/@vant/weapp/dist/*"]
		}
	}
}

//page

import Button from "@vant/weapp/button/index";

**Comment by landluck** [comment]
可以参考 https://youzan.github.io/vant-weapp/#/quickstart 进行配置，如还有问题，建议提供个代码片段
