### ISSUE TITLE
[Bug Report] van-collapse组件搭配van-cell显示异常

### ISSUE THREAD

**Issue by lbhchangyj** [youzan/vant-weapp#4133]
### 设备
iphone12

### VantWeapp 版本
1.6.8

### 基础库版本
2.14.4

### 如果是 UI 问题，截图链接（多图回车分隔）

![截图](https://i.loli.net/2021/04/06/MjQRyxzoSFgqWA6.jpg)

![截图](https://i.loli.net/2021/04/06/uFOGcr3wosgIlSE.jpg)

### 请提供核心代码片段链接
https://gist.github.com/lbhchangyj/444969e1536fb1e38cc1420838a20d9f

### 描述问题
使用van-collapse嵌套van-cell组件，视图由根据数据生成，编辑时页面左上角出现乱码，该情况目前仅在真机调试及体验版中出现，正式版尚未发布，且在pc端调试时并未出现。

**Comment by johnsonwong666** [comment]
还在吗 按照你的代码 简化的调整了一下 没有复现你这个情况。可以提供一个最小复现片段过来嘛，之前的代码太多了，不好排查。
