### ISSUE TITLE
[Bug Report] uniapp开发微信小程序使用popup封装子组件，关闭事件无效

### ISSUE THREAD

**Issue by panghujiajia** [youzan/vant-weapp#4134]
### 设备
ios、微信开发者工具

### VantWeapp 版本
1.6.2

### 基础库版本
2.16.0

### 请提供核心代码片段链接
https://gist.github.com/panghujiajia/906ce1a30e7234928f73608eedc533fe

### 描述问题
代码片段提供的是组件的内容  
请在另一个页面中引入该组件然后运行项目，点击蒙层控制台会输出  
```TypeError: Cannot read property '__args__' of undefined```

**Comment by LangJhowe** [comment]
刚好我也在处理类似的问题,在一个组件中用到uploader,几个事件都不能用,试了好多方法,后面突然发现加上native修饰符就通了,我也试了下popup,也可以,ε=ε=ε=┏(゜ロ゜;)┛

**Comment by panghujiajia** [comment]
> 刚好我也在处理类似的问题,在一个组件中用到uploader,几个事件都不能用,试了好多方法,后面突然发现加上native修饰符就通了,我也试了下popup,也可以,ε=ε=ε=┏(゜ロ゜;)┛

亲测有效
