### ISSUE TITLE
小程序与h5版本什么时候出一个目录树呀，等了好几年了。。。

### ISSUE THREAD

**Issue by 15735517450** [youzan/vant-weapp#4135]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater?repo=VantWeapp
小程序与h5版本什么时候出一个目录树呀，这个需求也是很经常见的呀。。。

**Comment by chenjiahan** [comment]
暂无计划支持喔，抱歉~
