### ISSUE TITLE
undefined is not an object (evaluating \'o.vanPageScroller\') detached@https://miniprogram_npm/@vant/weapp/mixins/page-scroll.js:29:16

### ISSUE THREAD

**Issue by geekyzs** [youzan/vant-weapp#4137]
undefined is not an object (evaluating \'o.vanPageScroller\')
detached@https://miniprogram_npm/@vant/weapp/mixins/page-scroll.js:29:16

**Comment by black-lattice** [comment]
这个再哪个版本解决了嘛？
