### ISSUE TITLE
Button的自定义按钮样式不生效

### ISSUE THREAD

**Issue by Clish** [youzan/vant-weapp#414]
van-button的custom-class样式添加未生效, 如图:
![image](https://user-images.githubusercontent.com/5687340/44012154-affcc182-9eef-11e8-817c-8ba667566c03.png)
样式设置是下面的样子:
![image](https://user-images.githubusercontent.com/5687340/44012164-bf3e404e-9eef-11e8-90e1-6e3b28aaae01.png)
这怎么解决?

**Comment by chenjiahan** [comment]
由于微信框架的限制，目前外部样式类的优先级是不确定的，可以通过 important 临时解决
