### ISSUE TITLE
van-card slot插槽无效

### ISSUE THREAD

**Issue by yumaopiaoa** [youzan/vant-weapp#4140]
![48A%2I@AXLGYUMMMFBUO_0L](https://user-images.githubusercontent.com/34874601/114265253-617bc900-9a22-11eb-9067-3953c27869c1.png)

**Comment by nemo-shen** [comment]
@yumaopiaoa 

方便的话提供一下复现代码，这边看了下官网的示例代码是可以的

**Comment by yumaopiaoa** [comment]
解决了，是taro 里面vue的插槽和react的插槽用法不一样

**Comment by sunWhereCode** [comment]
> 解决了，是taro 里面vue的插槽和react的插槽用法不一样

react里怎么实现插槽？
