### ISSUE TITLE
[Bug Report] Tab 标签手机调试很卡

### ISSUE THREAD

**Issue by luoxiaofeng1029** [youzan/vant-weapp#4143]
### 设备
iphone 7 plus

### VantWeapp 版本
1.6.8

### 基础库版本
2.16.0

### 请提供核心代码片段链接
https://gitee.com/zhang_lai_wei/vant-weapp-tab-kadun/blob/master/html

### 描述问题
电脑开发工具不卡,7P Tab 标签手机调试很卡,点一下颜色是立马变了,但是下面的滑动块要过几秒才会过去

**Comment by rex-zsd** [comment]
查看一下是否使用了 “真机调试”，请使用 “预览”，即可避免真机卡顿的问题。
