### ISSUE TITLE
[Bug Report] datetimepicker动态设置minHour等时间限制参数时confirm回调错误时间

### ISSUE THREAD

**Issue by whitiancai** [youzan/vant-weapp#4145]
### 设备
ios

### VantWeapp 版本
1.6.4

### 基础库版本
2.14.3

### 请提供核心代码片段链接
https://github.com/youzan/vant-weap

### 描述问题
currentValue设置09:00，第一次点开时间选择组件，面板显示09:00，正常，点击确认，修改minHour为9,minMinute为0，再次点开时间选择组件，面板显示18:00，点击确认，confirm回调内返回的参数e.detail为09:00.导致用户以为自动切换到18:00，结果提交的时间还是09:00。

**Comment by nemo-shen** [comment]
@whitiancai  [v1.6.9](https://github.com/youzan/vant-weapp/releases/tag/v1.6.9) 已修复，可以试一下
