### ISSUE TITLE
[Bug Report] vant-Sticky 在组件中无法使用

### ISSUE THREAD

**Issue by KaiHavertz** [youzan/vant-weapp#4148]
### 设备
微信开发者工具/vscode

### VantWeapp 版本
1.6.8

### 基础库版本
1.6.8

### 如果是 UI 问题，截图链接（多图回车分隔）

![截图](https://gitee.com/jnrjnr/images/raw/master/image/image-20210413161501903.png)

### 请提供核心代码片段链接
https://github.com.cnpmjs.org/KaiHavertz/code.git

### 描述问题
vant-Sticky 在组件中无法使用

**Comment by liancheng-zcy** [comment]
在组件里好像就不可以，楼主找到好的解决方案了吗

**Comment by wiexin** [comment]
我也报这个错误了 继续蹲

**Comment by shenjingnan** [comment]
1.8.3已修复
