### ISSUE TITLE
[Feature Request] 建议Button按钮组件增加一个“节流防抖”功能的属性设置

### ISSUE THREAD

**Issue by henrylu** [youzan/vant-weapp#4149]
### 这个功能解决了什么问题
参考：https://www.uviewui.com/js/debounce.html
比如防止表单提交按钮被多次触发

### 建议的API是什么样的
参见Button按钮的throttle-time属性：https://www.uviewui.com/components/button.html
这个属性可以设置节流的时间间隔(一定时间内无论点击多少次，只会触发一次click事件)，单位ms

### 展示一下新功能的大致用法，代码片段链接（GitHub Gist）
https://www.uviewui.com/components/button.html

**Comment by rex-zsd** [comment]
这个没有必要在 UI 库中集成吧？限流、防抖是与 UI 完全无关的纯逻辑，任何函数都可能需要用到。

如果需要防止表单被多次提交，应该合理使用 `disabled` 属性，在提交表单时禁止按钮点击。
如果要增加节流，使用任意节流开源库实现包装一下事件处理函数即可。

```html
<van-button bind:click="onClick">默认按钮</van-button>
```

```js
Page({
  onClick: throttle(function () {
    // do something
  }, 5000),
});

```
