### ISSUE TITLE
没有form的文档

### ISSUE THREAD

**Issue by codercqw** [youzan/vant-weapp#4150]
没有form的文档，右边有form的演示

**Comment by chenjiahan** [comment]
目前 vant-weapp 没有提供 Form 组件喔，右侧演示使用的是 Vant H5 版本，所以能看到 Form 组件。

**Comment by liangxiaoxin** [comment]
什么时候会支持form组件啊？小程序没有form组件提交表单校验太麻烦了 @chenjiahan
