### ISSUE TITLE
[Feature Request] 需求：图片裁剪功能

### ISSUE THREAD

**Issue by anyi678** [youzan/vant-weapp#4151]
### 这个功能解决了什么问题
需求：图片裁剪功能

### 建议的API是什么样的
https://github.com/1977474741/image-cropper

### 展示一下新功能的大致用法，代码片段链接（GitHub Gist）
https://github.com/1977474741/image-cropper

**Comment by chenjiahan** [comment]
暂无计划支持呢

**Comment by rchlz** [comment]
我也需要

**Comment by rchlz** [comment]
> 

有没有整合起？
