### ISSUE TITLE
获取用户信息功能

### ISSUE THREAD

**Issue by liutiexin924** [youzan/vant-weapp#4153]
微信小程序推出wx.getUserProfile用来获取用户信息，vant什么时候把getUserInfo改为wx.getUserProfile呢

**Comment by zqzy** [comment]
我也是这么想的

**Comment by superlbr** [comment]
替换肯定不合适，要新增。保留兼容能力。。。

**Comment by superlbr** [comment]
替换肯定不合适，要新增。保留兼容能力。。。

**Comment by qiqingfu** [comment]
没见到文档更新呀

**Comment by rex-zsd** [comment]
#4203 已支持，预计将会随下个版本发布哈

**Comment by rex-zsd** [comment]
组件用法不变哈。
组件内部在支持 `wx.getUserProfile` 的版本中会使用 `wx. getUserProfile`，旧版本自动降级至 `getUserInfo`
