### ISSUE TITLE
[Feature Request] 建议添加table表格组件

### ISSUE THREAD

**Issue by andyFang94** [youzan/vant-weapp#4154]
### 这个功能解决了什么问题
解决小程序中展示table的方便性

### 建议的API是什么样的
建议添加table表格组件

**Comment by wangfeng211** [comment]
强烈建议添加一个table组件

**Comment by zxtlin** [comment]
强烈建议添加一个table组件

**Comment by zxtlin** [comment]
支持，建议添加一个table组件

**Comment by chenjiahan** [comment]
暂无计划支持喔，移动端 Table 不是必须的，可以考虑使用 Cell 组件
