### ISSUE TITLE
[Bug Report] 日历组件bug

### ISSUE THREAD

**Issue by 2249038142** [youzan/vant-weapp#4162]
### 设备
小米10s

### VantWeapp 版本
1.6.8

### 基础库版本
2.16.0

### 请提供核心代码片段链接
https://gist.github.com/2249038142/b014260809a1280418e413ec75b9817a

### 描述问题
日历组件，范围选择，选择同一天，自定义个颜色，出现还是默认的红色

**Comment by 2249038142** [comment]
.van-calendar__day--start-end {
    background:(自定义);
}

**Comment by nemo-shen** [comment]
@2249038142 在新版本中已修复
