### ISSUE TITLE
[Bug Report] 时间选择器bug

### ISSUE THREAD

**Issue by jasonjcwu** [youzan/vant-weapp#4163]
### 设备
小米10s

### VantWeapp 版本
1.6.8

### 基础库版本
2.16.10

### 请提供核心代码片段链接
https://gist.github.com/2249038142/c81eda68bf3645982fbdd007fa7117ad

### 描述问题
时间选择器，设置value后滑动几下，就会自动跳乱时间，感觉像settimeout没清理掉

**Comment by 2249038142** [comment]
![image](https://user-images.githubusercontent.com/38279058/115516693-f7ccac00-a2b8-11eb-94b5-18564b3b62e8.png)

**Comment by AgainstAh** [comment]
我也遇到了这个问题

**Comment by zhazhanitian** [comment]
@nemo-shen 

I hope this issue can be assigned to me to follow up

**Comment by nemo-shen** [comment]
@zhazhanitian ok~ :) welcome PR

**Comment by johnsonwong666** [comment]
还在吗？试了一下没有复现，可以提供一下复现代码嘛，查看源码没有看到有定时器相关的代码。
