### ISSUE TITLE
[Feature Request] 小程序文档快速上手关于typescript的支持需要更改，目前创建程序选择typescript会自动引入typings，再安装miniprogram-api-typings会导致声明重复，报错。

### ISSUE THREAD

**Issue by sevilen** [youzan/vant-weapp#4164]
### 这个功能解决了什么问题
解决创建typescript小程序后按照快速上手安装miniprogram-api-typings编译ts会报错，提示重复。node_modules/miniprogram-api-typings和typings/types/wx重复定义。

### 建议的API是什么样的
1. 分两种情况说明如何引入typescript  
    1). 通过创建开发者工具创建的typescript小程序，只需添加@vant//webapp的paths即可  
    2). javascript小程序可按照当前的方法引入。  

#### 如何重现
1. 通过开发者工具创建一个typescript的小程序应用
2. 通过快速上手安装vant webapp，并添加typescript支持
3. 执行npm run tsc，即可看到重复声明的error

**Comment by Wouldbrother** [comment]
“只需添加@vant//webapp的paths即可”，这里怎么弄的呢，可以帮我出个详细的ts引入vant-weapp流程吗，安装文档快速上手的步骤我弄了好多次都弄不明白

**Comment by XiaopingHu** [comment]
### tsconfig.json文件中添加以下设置：
```
{
    "compilerOptions": {
        ...
        "baseUrl": ".",
        "paths": {
            "@vant/weapp/*":["node_modules/@vant/weapp/dist/*"]
        }
    }
}
```
### 组件引用时：
```
{
     ...
      "usingComponents": {
          "van-toast": "@vant/weapp/toast/index"
      }
}
```
### 在ts文件使用import方式导入
```
//以Toast组件为例，官方给出的导入方法会报错
import Toast from '@vant/weapp/toast/toast'
```
# 使用import导入Toast有个问题：
```
//如以下方式导入，编译时报：Cannot find type definition file for 'miniprogram-api-typings'.错误
//这是因为没有安装miniprogram-api-typings引起，虽然程序还是可以正常运行
//解决方法是：找到node_modules/@vant/weapp/dist/toast/toast.d.ts文件，删除这行代码：
// "/// <reference types="miniprogram-api-typings" />" 即可
import Toast from '@vant/weapp/toast/toast'
```

**Comment by Liu-wenxiang** [comment]
导入是进来了用了
```
// @ts-ignore
import Toast from '@vant/weapp/toast/toast';
```
但提示
`toast.js? [sm]:48 未找到 van-toast 节点，请确认 selector 及 context 是否正确`
而且确认`<van-toast id="van-toast" />`是加上的

**Comment by Liu-wenxiang** [comment]
已解决，`<van-toast id="van-toast" />`不能加载自定义组件里，必须放在Page页面

**Comment by hopefuture** [comment]
> ### tsconfig.json文件中添加以下设置：
> ```
> {
>     "compilerOptions": {
>         ...
>         "baseUrl": ".",
>         "paths": {
>             "@vant/weapp/*":["node_modules/@vant/weapp/dist/*"]
>         }
>     }
> }
> ```
> 
> ### 组件引用时：
> ```
> {
>      ...
>       "usingComponents": {
>           "van-toast": "@vant/weapp/toast/index"
>       }
> }
> ```
> 
> ### 在ts文件使用import方式导入
> ```
> //以Toast组件为例，官方给出的导入方法会报错
> import Toast from '@vant/weapp/toast/toast'
> ```
> 
> # 使用import导入Toast有个问题：
> ```
> //如以下方式导入，编译时报：Cannot find type definition file for 'miniprogram-api-typings'.错误
> //这是因为没有安装miniprogram-api-typings引起，虽然程序还是可以正常运行
> //解决方法是：找到node_modules/@vant/weapp/dist/toast/toast.d.ts文件，删除这行代码：
> // "/// <reference types="miniprogram-api-typings" />" 即可
> import Toast from '@vant/weapp/toast/toast'
> ```

期待官方更新最新版本，去掉miniprogram-api-typings 引起的冲突

**Comment by xjphhh** [comment]
> 已解决，`<van-toast id="van-toast" />`不能加载自定义组件里，必须放在Page页面

确实，我也是放在外面components文件夹里，导入组件就不显示，路径一直报错是在pages/components/xxx，不知道为什么前面路径要拼接上pages

**Comment by wubiandaxian** [comment]
新开项目碰到了这个问题，依旧不知道怎么解决，编译不通过。
现在项目中有 typings文件夹，安装的也有miniprogram-api-typings，但是去掉任何一个，依旧会报错。这个应该怎么设置

**Comment by landluck** [comment]
`Cannot find type definition file for 'miniprogram-api-typings' ` 这个报错我按照文档并没有复现，出现该问题可以手动安装 `yarn add -D miniprogram-api-typings` 依赖解决

**Comment by johnsonwong666** [comment]
<img width="1250" alt="image" src="https://github.com/youzan/vant-weapp/assets/64689255/2e85aff7-6a97-4d05-83f1-f4b52439cf41">
<img width="816" alt="image" src="https://github.com/youzan/vant-weapp/assets/64689255/c8f217af-d9aa-4655-ab1c-7040610682ee">
新建微信小程序的时候，选择ts模板，目前按照官方文档步骤走下来，仅需要修改tsconfig.json path/to/node_modules/@vant/weapp 为 node_modules/@vant/weapp/dist/*，开发时即可有ts类型声明，typings和miniprogram-api-typings无冲突报错。
