### ISSUE TITLE
[Feature Request] Collapse增加init事件

### ISSUE THREAD

**Issue by thisismykingdomcome** [youzan/vant-weapp#4166]
### 这个功能解决了什么问题
解决在onReady中使用wx.createSelectorQuery获取collapse组件高度错误的问题。（获取的高度为收缩时的高度，但我默认就是展开的，目前是延时获取）

### 建议的API是什么样的
事件名称：init；
携带参数：key (每个collapse组件的key值)；

**Comment by rex-zsd** [comment]
可以监听一下 `open` 事件，第一次触发时即为初始化完成。
