### ISSUE TITLE
关于组件库问题

### ISSUE THREAD

**Issue by a20070322** [youzan/vant-weapp#417]
# 恳请回答如下几个问题
*  Vant Weapp 与 zanui-weapp 有什么差异 ？
*  Vant Weapp 是否还是有赞提供技术支持还是个人开发者提供技术支持
*  Vant Weapp 目前没有 zanui-weapp 的组件的功能多 后续是否还会增加
*  zanui-weapp  是小程序电商组件库 那Vant Weapp 的业务场景 或者 理念又是什么

**Comment by chenjiahan** [comment]
1. Vant Weapp 是在 Zanui Weapp 和 Vant 的基础上开发的
2. Vant、Vant Weapp、Zanui Weapp 都是有赞提供技术支持的
3. 近期内会增加很多组件
4. 更强大的小程序电商组件库

**Comment by a20070322** [comment]
感谢您的回答，期待vant-weapp组件的完善和更强大

**Comment by duanjianan** [comment]
组件更新有确切的时间么  最近有个项目想要用

**Comment by kenberkeley** [comment]
有赞团队可以考虑兼容 taro / mpvue，由此一套 UI 组件可以通跑两端

**Comment by duanjianan** [comment]
个人感觉Taro是目前最走心的小程序框架了，真的可以考虑兼容

**Comment by jerossh** [comment]
缺了我需要的时间，多了我已经解决的全国城市选择
