### ISSUE TITLE
checkbox回显的问题

### ISSUE THREAD

**Issue by BryantKawhi** [youzan/vant-weapp#4173]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater?repo=VantWeapp
使用checkboxgroup的value显示之前选中的项，checkbox的显示的条数splice一部分（eg开始有10个，截取5个），就会出现不选中的情况，如果不截取就会选中。

checkboxgroup上的value包含有截取后的内容

**Comment by rex-zsd** [comment]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater?repo=VantWeapp
