### ISSUE TITLE
日历控件->选择日期区间，开始日期与结束日期为同一天的情况

### ISSUE THREAD

**Issue by ersan1114** [youzan/vant-weapp#4174]
日期区间只能选择多天，而在实际使用过程中（例：出差填报选择出差日期）会遇到当天去当天回的情况。希望能扩展此功能，让日期区间支持开始时间和结束时间为同一天的选择。

**Comment by booboom** [comment]
![image](https://user-images.githubusercontent.com/24515720/115985131-fa8f1000-a5dc-11eb-97cb-c427d66ca3c2.png)
多看文档
