### ISSUE TITLE
[Bug Report] 多次调用dialog只弹一次窗

### ISSUE THREAD

**Issue by 3roman** [youzan/vant-weapp#4175]
### 设备
IPHONE8

### VantWeapp 版本
1.6.8

### 基础库版本
2.16.0

### 请提供核心代码片段链接
https://gist.github.com/lim42snec/c8640bfe6c7bf823b87be082f59ba231

### 描述问题
多次调用dialog只弹出一次，上述代码只显示“第二次调用”。正常逻辑应该是第一个弹窗出现后点击确认按钮，紧接着出现第二个弹窗；不点击则不应弹出第二个窗。

**Comment by rex-zsd** [comment]
你描述的是组件的正常逻辑，因为 2 次调用指向同一个 Dialog 实例，并行调用时总会以最后一次调用的效果为准。
如果实现你希望的串行逻辑，可将代码修改为

```js
Dialog.alert({
    message: '第一次调用',
  }).then(() => {
    Dialog.alert({
      message: '第二次调用',
    });
});
```
