### ISSUE TITLE
[Bug Report] taro-vue 下calendar组件formatter函数不生效

### ISSUE THREAD

**Issue by booboom** [youzan/vant-weapp#4176]
### 设备
微信开发者工具

### VantWeapp 版本
1.6.8

### 基础库版本
2.16.1

### 如果是 UI 问题，截图链接（多图回车分隔）

![截图](https://i.loli.net/2021/04/25/iwm5n3pIf7Yj8Ao.png)

### 请提供核心代码片段链接
https://github.com/booboom/code-snippet/blob/master/taro-vue-vant-weapp/calenddar.md

### 描述问题
taro-vue版本：
 "@tarojs/components": "~3.0.29",
 "@tarojs/runtime": "~3.0.29",
 "@tarojs/taro": "~3.0.29",
"@tarojs/mini-runner": "~3.0.29",
"@tarojs/webpack-runner": "~3.0.29",
"babel-preset-taro": "~3.0.29",

**Comment by guozhaolong** [comment]
taro react试了也不生效，没有被触发

**Comment by lihengdao** [comment]
so, what‘s the problem?

**Comment by landluck** [comment]
vant weapp 是基于微信小程序原生开发， 没有针对 taro 进行适配，因此不保证各个组件在 taro 下的可用性。

如果你在 taro 中使用 Vant 遇到问题，建议向 taro 进行反馈

**Comment by Luxiaoren** [comment]
可以先给formatter 传递一个 为null的变量，然后 打开日历后，延迟更改这个变量为 正确的函数，
templete:

:formatter="vanCalendarFormatterFun"

vue data:

 vanCalendarFormatterFun: null,

onLoad: 

this.vanCalendarFormatterFun = 正确的处理函数
