### ISSUE TITLE
[Bug Report] NumberKeyboard 没有相关使用文档

### ISSUE THREAD

**Issue by youyou12344** [youzan/vant-weapp#4178]
### 设备
pc

### VantWeapp 版本
1.6.8

### 基础库版本
-

### 如果是 UI 问题，截图链接（多图回车分隔）

![截图](-)

### 请提供核心代码片段链接
https://youzan.github.io/vant-weapp/#/changelog

### 描述问题
https://youzan.github.io/vant-weapp/#/changelog 官网说明文档中没有 NumberKeyboard 是不能用了吗？

**Comment by chenjiahan** [comment]
参见 https://github.com/youzan/vant-weapp/issues/4227
