### ISSUE TITLE
[新需求]关于当 Canlendar 的 type 为 range 时超出范围的需求

### ISSUE THREAD

**Issue by VenusPP** [youzan/vant-weapp#4181]
场景：酒店平台小程序当用户想选择入住时间范围为30天，但当前最大支持入住范围为一周，此时PM要求超出范围时给个showModel提示，点击showModel上提供的电话可直接联系酒店入住。

**Comment by nemo-shen** [comment]
@VenusPP 近期支持~

**Comment by nemo-shen** [comment]
@VenusPP 新版本已修复
