### ISSUE TITLE
Dialog弹框异

### ISSUE THREAD

**Issue by 15602009197** [youzan/vant-weapp#4183]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater?repo=VantWeapp
Dialog弹框异步关闭中resolve(false);是错误的，应该是resolve(true);

**Comment by chenjiahan** [comment]
resolve(false)  表示取消关闭，没问题的

**Comment by 15602009197** [comment]
没有，直接一个按钮绑定事件弹框，确定可以&nbsp; &nbsp;取消就不行。 把else里改为false之后就可以了



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年4月29日(星期四) 晚上9:16
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [youzan/vant-weapp] Dialog弹框异 (#4183)






关闭#4183.

—
您正在接收此消息，因为您编写了线程。
直接回复此邮件，在GitHub上查看，或取消订阅.
