### ISSUE TITLE
[Feature Request] 希望教程文档页面能禁止监听左右方向键

### ISSUE THREAD

**Issue by shinrabansyou** [youzan/vant-weapp#4184]
### 这个功能解决了什么问题
[教程文档页面](https://youzan.github.io/vant-weapp)默认监听了左右方向键，并在监听回调中进行了切换文档目录项目的操作，这对于使用windows 多桌面功能的用户实在是不友好。
windows多桌面切换时使用“ctrl + win + 左右方向键”进行各个桌面之间的切换，在切换桌面时会被网页侦听到并在切换桌面的同时切换掉当前查看的文档目录项

### 建议的API是什么样的
去除左右方向键切换目录功能

**Comment by chenjiahan** [comment]
文档已更新，可以清缓存试下
