### ISSUE TITLE
van-uploader accept="image" 小程序在ios端调用不了本地相册和相机

### ISSUE THREAD

**Issue by shuaijiabin** [youzan/vant-weapp#4192]
van-uploader accept="image" 小程序在ios端调用不了本地相册和相机

**Comment by nemo-shen** [comment]
@shuaijiabin-alive 

iphone11，官方示例，无法复现

请提供最小可复现仓库

**Comment by DannyHat** [comment]
本机开发也出现了这个问题，解决办法入下：
1.先看wxml文件中的van-uploader组件是否设置了capture属性，如果不需要设置图片来源，删除可正常。
2.如果需要设置来源，capture属性用js文件中的变量来设置，变量类型必须是数组，如['camera']。

**Comment by noteverlong** [comment]
> 



> 本机开发也出现了这个问题，解决办法入下： 1.先看wxml文件中的van-uploader组件是否设置了capture属性，如果不需要设置图片来源，删除可正常。 2.如果需要设置来源，capture属性用js文件中的变量来设置，变量类型必须是数组，如['camera']。

兄弟你真帅，你是怎么发现的？

**Comment by landluck** [comment]
测试后没有复现，如能复现可以提供小程序代码片段或者完整代码后重新打开issue
