### ISSUE TITLE
Tabs scrollLeft 多数据时后面选中后滚动距离不对

### ISSUE THREAD

**Issue by fanmucc** [youzan/vant-weapp#4202]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater?repo=VantWeapp

<van-tabs> <van-tab></van-tab> </van-tabs>

当van-tab数据多时，则选中最后几条会出现 scrollLeft位置不对。 log了计算的位置是正确的 但是并没有滚动到相应的位置。
前面的数据不受影响

**Comment by Spikef** [comment]
修复之后组件从隐藏状态切换到显示状态时，底部条位置错误的修复方案不好使了
 
https://vant-contrib.gitee.io/vant-weapp/#/tab#zu-jian-cong-yin-cang-zhuang-tai-qie-huan-dao-xian-shi-zhuang-tai-shi-di-bu-tiao-wei-zhi-cuo-wu
