### ISSUE TITLE
[Bug Report] collapse-item展开动画不执行回调

### ISSUE THREAD

**Issue by jiangxue0725** [youzan/vant-weapp#4206]
### 设备
普通设备

### VantWeapp 版本
1.6.8

### 基础库版本
2.16.1

### 请提供核心代码片段链接
https://github.com/youzan/vant-weapp/blob/master/dist/collapse-item/animate.js

### 描述问题
animate的keyframes数组有两个offset值为1，此时回调函数不会被执行。看组件逻辑这里应该是不希望清除animate，所以没有必要写回调函数

**Comment by nemo-shen** [comment]
事件监听是在van-collapse上的

```html
<van-collapse value="{{ active3 }}" data-key="active3" bind:change="onChange" bind:open="onOpen" bind:close="onClose">...</van-collapse>
```
