### ISSUE TITLE
[Bug Report] 小程序Dialog 弹出框确定和取消按钮偏移问题

### ISSUE THREAD

**Issue by wjup** [youzan/vant-weapp#4209]
### 设备
小程序

### VantWeapp 版本
1.6.8

### 基础库版本
1.6.8

### 如果是 UI 问题，截图链接（多图回车分隔）

![https://sm.ms/image/vOPt75b41mfxwAH](https://sm.ms/image/vOPt75b41mfxwAH)

### 请提供核心代码片段链接
https://gist.github.com/wjup/6cf96e14968825e574cc32468ff0276b

### 描述问题
小程序Dialog 弹出框确定和取消按钮会出现偏移，而且只有确定按钮时也不居中

**Comment by rex-zsd** [comment]
请参考 [快速上手](https://youzan.github.io/vant-weapp/#/quickstart#bu-zou-er-xiu-gai-app.json)，去除 `"style": "v2"`。
