### ISSUE TITLE
Popup 弹出层组件没有过度动画了

### ISSUE THREAD

**Issue by wi1wei** [youzan/vant-weapp#4210]
设备
iphone12 pro

VantWeapp 版本
1.6.8

基础库版本
2.16.1

描述问题
Popup+ Picker使用时之前好像都是有过度动画的，组件库示例小程序也没动画了

**Comment by nemo-shen** [comment]
iPhone11试了下无法复现

**Comment by lshunran** [comment]
是的，我也发现，扫文档首页的示例小程序里的也没动画了

**Comment by nemo-shen** [comment]
#4220 

相同问题，合并在一起讨论

**Comment by maopixin** [comment]
上次发版还是1月份，这个库停止维护了吗？
