### ISSUE TITLE
[Feature Request] Calendar日历每周从星期一开始，本地简单修改代码就能实现

### ISSUE THREAD

**Issue by xiangyuecn** [youzan/vant-weapp#4211]
### 这个功能解决了什么问题
目前Calendar源码每周只能从星期日开始显示，无法指定从星期几开始，（按照常规思维，从星期一开始可以什么都不用做，从其他星期开始至少得提供配置选项！！！）

我们将lib目录源码clone下来后直接简单修改源码即可实现自己需要从星期几开始（没有研究怎么通过配置来实现）

## 修改一：header
https://github.com/youzan/vant-weapp/blob/cde3876fb0742cacf3e481a8eb2b487dabc8709e/lib/calendar/components/header/index.js#L15
``` javascript
//根据自己需要改成下面这种，显示顺序
weekdays: ['一', '二', '三', '四', '五', '六', '日'],
```

## 修改二：month
https://github.com/youzan/vant-weapp/blob/cde3876fb0742cacf3e481a8eb2b487dabc8709e/lib/calendar/components/month/index.wxs#L12
``` javascript
//改成下面这种，这里是星期一开始
var offset = (getDate(date).getDay()||7)-1;
```

> 改两行代码即可实现每周从星期一开始显示

### 建议的API是什么样的
无api建议，本地clone lib目录后自行修改，npm安装的自行折腾源码

F1: 不过话说加一个配置也是很简单的事，有多难
F2: 日历性能问题源于这个Calendar的基础流程设计，一来就把所有日期都显示出来，能显示出二年范围的日历都够呛，目前我本地通过简单修改源码，日历只显示一个月，加了左右4个年月前进后退按钮，测试范围选择没有任何改动均能正常使用，支持任意范围，无性能问题

以上均不构成建议，仅供参考

**Comment by xiangyuecn** [comment]
#3552 #3636

**Comment by chenjiahan** [comment]
后续添加 `first-day-of-week` 属性，与 vant 一致

**Comment by zhazhanitian** [comment]
@chenjiahan 

This function has been implemented by us. Can you point this issue to me and let me close it

**Comment by chenjiahan** [comment]
@zhazhanitian done
