### ISSUE TITLE
[Bug Report] 对checkbox样式设置行高样式不生效的问题

### ISSUE THREAD

**Issue by yik7707** [youzan/vant-weapp#4215]
### 设备
windows

### VantWeapp 版本
1.6.8

### 基础库版本
2.16.1

### 如果是 UI 问题，截图链接（多图回车分隔）
https://sm.ms/image/Z1PVMymdlvfbUFS

### 描述问题
设置样式，对复选框组设置排列行高样式不生效，原因如图所示宽高为0希望能解决

对复选框组设置行高如图（宽高为0）：
https://sm.ms/image/Z1PVMymdlvfbUFS

对单选组设置行高没问题如图（因为有宽高）：
https://i.loli.net/2021/05/15/Ifs3LncGi1yNEpq.jpg

**Comment by rex-zsd** [comment]
参考一下 [样式覆盖](https://youzan.github.io/vant-weapp/#/custom-style) 文档哈。
小程序尤其注意不要给组件 tag 定义样式，一般都是不会生效的，请使用外部样式类或者样式隔离解除后给对应的 class 添加样式定义。
