### ISSUE TITLE
[Bug Report] vant-button 里面的open-type 属性不生效

### ISSUE THREAD

**Issue by waltcow** [youzan/vant-weapp#4217]
### 设备
iphone11

### VantWeapp 版本
1.6.8

### 基础库版本
2.15

### 请提供核心代码片段链接
https://github.com/youzan/vant-weapp/blob/dev/packages/button/index.wxml

### 描述问题
vant-button 里面的open-type 属性不生效

**Comment by waltcow** [comment]
下面的这行

```
disabled || loading || canIUseGetUserProfile  
```

当 **canIUseGetUserProfile** 为 **true**
如果 **openType** 为 **getphonenumber** ， **bind:getphonenumber** 将无法生效

**Comment by rex-zsd** [comment]
这个改动还未发布，1.6.8 不包含 `canIUseGetUserProfile` 的逻辑的。

**Comment by rex-zsd** [comment]
不过这里的确是有问题，感谢反馈
