### ISSUE TITLE
[Bug Report] tab组件中的popup组件显示不全

### ISSUE THREAD

**Issue by JImumu** [youzan/vant-weapp#4218]
### 设备
iphone 11

### VantWeapp 版本
1.6.8

### 基础库版本
微信版本为8.0.5

### 请提供核心代码片段链接
https://developers.weixin.qq.com/s/A5NWhmmp7Vqo

### 描述问题
在iphone 11中，tab组件中的popup组件显示不全

**Comment by nemo-shen** [comment]
@JImumu 

显示不全的意思是什么？我这边开发者工具和真机测试都没发现问题

**Comment by JImumu** [comment]
![image](https://user-images.githubusercontent.com/25128849/119287860-03c1da00-bc7a-11eb-99e7-d6be402547ec.png)
真机上的模态框没显示全，只有iphone11有这个问题

**Comment by landluck** [comment]
把 popup 嵌套在 Tabs 等组件内部使用时，可能会遇到位置错误、fixed 失效的问题。这是因为在部分浏览器中，transform 元素内部的 fixed 布局会降级成 absolute 布局，导致布局的异常，建议把 popup 组件放置到 tab 外层，通过事件唤醒，就能解决这个问题
