### ISSUE TITLE
[Bug Report] van-swipe-cell 左滑删除单元格无样式

### ISSUE THREAD

**Issue by ixcw** [youzan/vant-weapp#4225]
### 设备
微信开发者工具 1.05

### VantWeapp 版本
1.6.8

### 基础库版本
2.17.0

### 如果是 UI 问题，截图链接（多图回车分隔）

![截图](https://sm.ms/image/AIG6qUZe78ndYsV)

### 请提供核心代码片段链接
https://gist.github.com/ixcw/75c9312a23b34ada6d69a28759f1fa43

### 描述问题
van-swipe-cell 左滑删除单元格无样式，详见截图

**Comment by ixcw** [comment]
https://sm.ms/image/AIG6qUZe78ndYsV，截图链接，不知道为啥没显示

**Comment by zhazhanitian** [comment]
> [https://sm.ms/image/AIG6qUZe78ndYsV，截图链接，不知道为啥没显示](https://sm.ms/image/AIG6qUZe78ndYsV%EF%BC%8C%E6%88%AA%E5%9B%BE%E9%93%BE%E6%8E%A5%EF%BC%8C%E4%B8%8D%E7%9F%A5%E9%81%93%E4%B8%BA%E5%95%A5%E6%B2%A1%E6%98%BE%E7%A4%BA)

You can find your own place to upload pictures, and then send out the CDM address

**Comment by Goricksun** [comment]
我也遇到了同样的问题，版本是1.6.8
不管是放到Component还是Page里面效果都是一样的

**Comment by zhazhanitian** [comment]
@Goricksun Can you provide a video or picture to see the effect

**Comment by rex-zsd** [comment]
左、右 slot 都是没有样式的，需要开发者自行定义哈。
