### ISSUE TITLE
新的组件什么时候提供呢

### ISSUE THREAD

**Issue by BryantKawhi** [youzan/vant-weapp#4227]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater?repo=VantWeapp
在小程序的预览那可以看到已经新加了多个组件,但是文档上却没有，想问一下这个啥时候更新eg:
![图片](https://user-images.githubusercontent.com/29621842/119285761-5ea50280-bc75-11eb-85f5-3c8a300313b2.png)
![图片](https://user-images.githubusercontent.com/29621842/119285787-6cf31e80-bc75-11eb-83c7-32bb18687504.png)

**Comment by chenjiahan** [comment]
抱歉，这些组件目前是 H5 特有的，暂时没计划在小程序里提供。

文档展示有误，后续会修正
