### ISSUE TITLE
vant-field当disabled时候，依然可以bindtap？

### ISSUE THREAD

**Issue by Albertlws** [youzan/vant-weapp#4228]
本来想通过vant-field bindtap弹出picker时候，可是当disabled时候bindtap依然有效。
代码片段：https://developers.weixin.qq.com/s/wY6G4xmU7wqt

**Comment by nemo-shen** [comment]
这个和HTML5原生input元素是保持一致的，你可以试下`<input disabled @click="onClick" />`也是可以触发点击事件的

另外是，建议是既然已经动态处理disabled了，那么可以在onClick触发后判断disabled === true
