### ISSUE TITLE
van-tabs 使用 sticky属性，并且在van-tab使用van-sticky 会有问题

### ISSUE THREAD

**Issue by caicr** [youzan/vant-weapp#4233]
van-tabs 使用 sticky属性，并且在van-tab使用van-sticky，会导致除了第一个van-tab之外的van-tab的van-sticky高度失效。van-sticky会把内容挡住。监听事件修改的height会被设置为0

![image](https://user-images.githubusercontent.com/16498725/119757673-decaa280-bed7-11eb-81bd-67e04cb8fa71.png)

暂时处理方式，强制设置van-sticky的高度

**Comment by PPPartric** [comment]
我也碰到了这个问题，vant版本1.10.2，tab下面第一个sticky有高度渲染，其他他不下面的并没有高度。
暂时的解决方法是在tab的循环中判断是否是第一个来处理。

**Comment by johnsonwong666** [comment]
该issue 在vant-weapp2.0 解决
