### ISSUE TITLE
[Bug Report] 对于checkbox定义样式不生效问题，继续反馈

### ISSUE THREAD

**Issue by yik7707** [youzan/vant-weapp#4234]
### 设备
windows

### VantWeapp 版本
1.6.8

### 基础库版本
2.17.0

### 请提供核心代码片段链接
https://developers.weixin.qq.com/s/mBsP0Cm971qe

### 描述问题
checkbox对于定义的行高不生效，原因为宽高为0，希望能解决该问题
如对我的代码片段有问题希望，官方能发送修改好的代码片段给我，谢谢
上次反馈的链接，尝试过两种方法都不行：
https://github.com/youzan/vant-weapp/issues/4215
1、外部样式类
2、样式隔离解除后给对应的 class 添加样式定义

如下图所示
https://sm.ms/image/5UvmSFIbEHBpixj
代码片段：
https://developers.weixin.qq.com/s/mBsP0Cm971qe

**Comment by jialiangZ** [comment]
同遇到，自定义图标也不显示

**Comment by landluck** [comment]
line-height 的样式控制在 label 上，所以自定义样式可以通过 label-class 注入，或者通过类名覆盖时需要使用 label 的类名

**Comment by landluck** [comment]
> 同遇到，自定义图标也不显示

可以单独提交 issue
