### ISSUE TITLE
[Bug Report] vant-dialog 样式按钮不能自适应

### ISSUE THREAD

**Issue by BB-Code** [youzan/vant-weapp#4237]
### 设备
小程序

### VantWeapp 版本
1.6.6

### 基础库版本
1.6.6

### 如果是 UI 问题，截图链接（多图回车分隔）

![截图](https://static01.imgkr.com/temp/176dae7fd3e940a1948edf1250ad24f4.png)

### 请提供核心代码片段链接
https://static01.imgkr.com/temp/dec916aa9dd943eab68b7e4cfd48095b.png

### 描述问题
vant-dialog 样式按钮不能自适应

**Comment by nemo-shen** [comment]
@BB-Code 无法理解你说的问题，不适应是什么意思？
