### ISSUE TITLE
[Bug Report] van-icon都不显示了，也不报错

### ISSUE THREAD

**Issue by myAllDream** [youzan/vant-weapp#4239]
### 设备
微信小程序

### VantWeapp 版本
1.6.9-beta.2

### 基础库版本
2.17.0

### 描述问题
把文件下载到本地，之后引入："van-icon": "/wxcomponents/vant/icon/index"，使用<van-icon name="close" />，图标不显示也不报错，但是其他的组件这样使用都可以正常使用

**Comment by nemo-shen** [comment]
@myAllDream 参考官方用法

**Comment by jialiangZ** [comment]
> ### 设备
> 微信小程序
> 
> ### VantWeapp 版本
> 1.6.9-beta.2
> 
> ### 基础库版本
> 2.17.0
> 
> ### 描述问题
> 把文件下载到本地，之后引入："van-icon": "/wxcomponents/vant/icon/index"，使用，图标不显示也不报错，但是其他的组件这样使用都可以正常使用

我现在也遇到这个问题，完全按照官方的来也不显示图标

**Comment by nemo-shen** [comment]
@jialiangZ @myAllDream 

虽然我不知道你们为什么会不显示，感觉应该是用法问题，我这边提供一个repo，自取吧
git@github.com:nemo-shen/icon-debug-vant-weapp.git

另外现在最新版是1.6.9，建议可以升级一下
