### ISSUE TITLE
Button的size为large时不使用圆角

### ISSUE THREAD

**Issue by tat757** [youzan/vant-weapp#424]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**你需要的功能是？**
Button的size为large时不使用圆角

**你期望 API 是什么样的？**
Button的size为large时不使用圆角。zanUI有这么个功能

**Comment by chenjiahan** [comment]
Button 默认是圆角的，可以通过 square 属性设置非圆角（在下个版本支持）
