### ISSUE TITLE
打开dialog后，dialog里的输入框的placeholder字体会跳动

### ISSUE THREAD

**Issue by sinobeetle** [youzan/vant-weapp#4242]
打开dialog后，dialog里的输入框的placeholder字体会跳动

**Comment by nemo-shen** [comment]
@sinobeetle 请提供最小可复现代码

**Comment by wi1wei** [comment]
VantWeapp 版本
1.7.1
```
<van-button type="primary" bind:tap="test">test</van-button>
<van-dialog
        use-slot
        title="标题"
        show="{{ dialogShow }}"
        show-cancel-button
>
    <van-field
            placeholder="请输入"
            border="{{ false }}"
    />
</van-dialog>
```
```
Page({
    data: {
        dialogShow: false
    },
    test() {
        this.setData({
            dialogShow: true
        })
    },
});
```

https://user-images.githubusercontent.com/22729817/125057451-d4591680-e0db-11eb-9a9c-9aaaa3ac8b05.mp4

@nemo-shen

**Comment by nemo-shen** [comment]
@sinobeetle [可以看下文档说明](http://localhost:8080/#/field#textarea-de-placeholder-zai-zhen-ji-shang-wei-shi-me-hui-pian-yi)

**Comment by nemo-shen** [comment]
即使使用微信原生提供的 `<input />` 也是会有偏移的

**Comment by sinobeetle** [comment]
关闭动画可以解决





------------------ 原始邮件 ------------------
发件人: nemo-shen ***@***.***&gt;
发送时间: 2021年7月16日 01:10
收件人: youzan/vant-weapp ***@***.***&gt;
抄送: sinobeetle ***@***.***&gt;, Mention ***@***.***&gt;
主题: 回复：[youzan/vant-weapp] 打开dialog后，dialog里的输入框的placeholder字体会跳动 (#4242)





 
即使使用微信原生提供的 <input /&gt; 也是会有偏移的
