### ISSUE TITLE
[Feature Request] Uploader 文件上传 accept 选取单个图片和视频文件

### ISSUE THREAD

**Issue by accardo** [youzan/vant-weapp#4243]
### 这个功能解决了什么问题
目前只有all 选取 从客户端会话选择所有文件，有需求需要只选取客户端会话文件的视频 或者  图片。

### 建议的API是什么样的
media	图片和视频
image	图片
video	视频
file	从客户端会话选择图片和视频以外的文件
all	从客户端会话选择所有文件

看了一下源码 因为选取客户端会话文件是all， 选取文件或者视频也是 video和image 这和之前的重复了。
推荐可以在加2个类型 client-image 和 client-video

**Comment by landluck** [comment]
可以看看新增的 `media-type` 是否满足需求
