### ISSUE TITLE
Tabbar 标签栏组件右上角提示信息样式溢出了

### ISSUE THREAD

**Issue by wi1wei** [youzan/vant-weapp#4244]
设备
iphone12 pro

VantWeapp 版本
1.6.8

基础库版本
2.16.0

如果是 UI 问题，截图链接（多图回车分隔）
![IMG_2468.PNG](https://i.loli.net/2021/06/02/Ll5bUp4HgKPFv9Q.png)
![1622611965742.jpg](https://i.loli.net/2021/06/02/vM8TBXsFVgyLrRY.jpg)

请提供核心代码片段链接
`
    <van-tabbar>
        <van-tabbar-item icon="shopping-cart-o" info="{{3}}">
            购物车
        </van-tabbar-item>
    </van-tabbar>
`

描述问题
提示信息样式溢出了，示例小程序也有同样问题

**Comment by nemo-shen** [comment]
@wi1wei 建议试用1.6.9-beta.2版，官方示例小程序可以复现是因为示例小程序版本1.6.3比较落后
