### ISSUE TITLE
[Feature Request] van-card商品卡片设置高度

### ISSUE THREAD

**Issue by sahuang** [youzan/vant-weapp#4247]
### 这个功能解决了什么问题
目前商品卡片高度太大，导致卡片很空旷，不知道是否有调整卡片高度的功能？尝试设置card的custom class的高度，并没有生效。

### 建议的API是什么样的
能在根节点样式生效即可。

**Comment by nemo-shen** [comment]
@sahuang
尝试了一下，可以生效，最小代码传上来看下
