### ISSUE TITLE
Tab Props title 怎么通过 Slot 扩展？

### ISSUE THREAD

**Issue by zhounianlai** [youzan/vant-weapp#4248]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater?repo=VantWeapp
插槽怎么用？

<van-tabs >
  <van-tab wx:for="{{menuList}}" wx:key="index">
    <template slot="nav-left">
      <view class="item">
          <image src="{{item.image}}" mode="widthFix"></image>
          <text class="title">{{item.category_name}}</text>
        </view>
    </template>
  </van-tab>
</van-tabs>

**Comment by nemo-shen** [comment]
图裂了，不清楚你要表达什么，如果是自定义tab中的内容，请看文档
