### ISSUE TITLE
最需要【表单验证】，谢谢！

### ISSUE THREAD

**Issue by zhaohuwei** [youzan/vant-weapp#425]
**你需要的功能是？**
表单验证

**你期望 API 是什么样的？**
1.支持正则，支持自定义规则
2.多种形式的错误消息（desc/tip/toast）
3.blur、change等多种触发机制
4.手动验证（单个input/整个form）
5.支持异步、后台验证

**Comment by chenjiahan** [comment]
目前 Field 有提供 blur/change 等事件，也能够展示自定义的错误提示

推荐通过这些 API 去灵活定制，实现表单验证，暂时没有计划封装成一个组件
