### ISSUE TITLE
ShareSheet 分享面板

### ISSUE THREAD

**Issue by lichunze** [youzan/vant-weapp#4255]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater?repo=VantWeapp
![image](https://user-images.githubusercontent.com/24243394/121320117-718b2880-c93f-11eb-98e7-2d3b276d586b.png)

为什么options我设置了{ name: '微信', icon: 'wechat' }只会显示一个微信的按钮呢，我看文档的例子会把微信好友和朋友圈都可以显示出来

**Comment by chenjiahan** [comment]
朋友圈需要单独设置 wechat-moments 喔

**Comment by lichunze** [comment]
![image](https://user-images.githubusercontent.com/24243394/121331400-69d08180-c949-11eb-809a-0db0d11ff2f9.png)

你说的wechat-moments是在哪看到的呢，这个对于vantapp有版本要求吗

![image](https://user-images.githubusercontent.com/24243394/121331544-8e2c5e00-c949-11eb-8aff-305d499e1022.png)

**Comment by nemo-shen** [comment]
@lichunze 小程序和vant略有差异
```js
Page({
  data: {
    options: [
      { name: '微信', icon: 'wechat', openType: 'share' },
      { name: '朋友圈', icon: 'https://img.yzcdn.cn/vant/share-icon-wechat-moments.png', openType: 'share' },
      { name: '微博', icon: 'weibo' },
      { name: '复制链接', icon: 'link' },
      { name: '分享海报', icon: 'poster' },
      { name: '二维码', icon: 'qrcode' },
    ],
  }
});
```

**Comment by nemo-shen** [comment]
@lichunze 下个版本会增加 `wechat-moments` 设置朋友圈图标

**Comment by lichunze** [comment]
下次版本大约什么时候更新呢，因为这次我们开发有这个分享功能，如果时间来得及就用你们分享面板

**Comment by lichunze** [comment]
我先用你们提供的网络图片吧，后续我多多关注吧，再替换

**Comment by nemo-shen** [comment]
@lichunze 已在1.7.1中优化
