### ISSUE TITLE
[Feature Request]  van-calendar选择日期范围

### ISSUE THREAD

**Issue by caozhepeng** [youzan/vant-weapp#4257]
### 这个功能解决了什么问题
 van-calendar选择日期范围时希望可以选择开始日期和结束日期是同一天，就是一个日期的选中状态会有2种，可以参考一嗨租车小程序选择租车日期时的效果。

### 建议的API是什么样的
 van-calendar选择日期范围时希望可以选择开始日期和结束日期是同一天，就是一个日期的选中状态会有2种，可以参考一嗨租车小程序选择租车日期时的效果。

**Comment by MrLaibin** [comment]
Tips: 默认情况下，日期区间的起止时间不能为同一天，可以通过设置 allow-same-day 属性来允许选择同一天。
