### ISSUE TITLE
field组件click-icon事件不触发

### ISSUE THREAD

**Issue by hai3460377** [youzan/vant-weapp#426]
**描述一下问题**
@click-icon 不触发
修改组件源码 改成clickicon
标签上写成@clickicon就触发了

而且field源码里 useIconSlot这个props没写。。
![image](https://user-images.githubusercontent.com/13247648/44090176-df8456d8-9ffb-11e8-9108-ec136626619a.png)

结合mpvue编码时...

**Comment by hai3460377** [comment]
是在结合mpvue使用时

**Comment by chenjiahan** [comment]
useIconSlot 这个问题会在下个版本修复
click-icon 的话目测是 mpvue 的问题，请到对应仓库下提问
