### ISSUE TITLE
[Feature Request] 希望checkbox复选框可以增加direction排列方向

### ISSUE THREAD

**Issue by lzpswat** [youzan/vant-weapp#4260]
### 这个功能解决了什么问题
提供复选框的排列方向，适应更多场景。如果可以做到自适应换行就最好了，感谢。

### 建议的API是什么样的
类似于radio的direction

**Comment by nemo-shen** [comment]
@lzpswat v1.7.0将会支持direction

**Comment by nemo-shen** [comment]
@lzpswat 建议使用1.7.1
