### ISSUE TITLE
[Bug Report] TabBar的change事件无效

### ISSUE THREAD

**Issue by wojiazaiyugang** [youzan/vant-weapp#4264]
### 设备
windows

### VantWeapp 版本
1.6.9

### 基础库版本
2.17.0

### 请提供核心代码片段链接
https://gist.github.com/wojiazaiyugang/2ecdaf0b307682a807b769876c25b32c

### 描述问题
根据官方文档https://vant-contrib.gitee.io/vant-weapp/#/tabbar

tabbar点击之后会触发change事件参数包括点击的tab的index或者name
但是示例代码中tabbar组件的onChange事件没有正确传递event参数
打印的event是undefined 
经过查看代码commit，是在1.6.2中删除了change事件 https://github.com/youzan/vant-weapp/commit/22c9889d6f324c7e08c8dc0a0857b836b896995e#diff-94f4f804fa9986eba48da05a72336ecacff6e0ffe73e24e8befd1807469d5302
请问是出于什么样的考虑删除的change事件，删除了之后如何处理tabbar的切换呢

**Comment by nemo-shen** [comment]
看错了吧，`bind:change` 并没有删除，如果你有兴趣可以看下源代码

https://github.com/youzan/vant-weapp/blob/v1.6.9/packages/tabbar-item/index.ts
https://github.com/youzan/vant-weapp/blob/v1.6.9/packages/tabbar-item/index.wxml

![Jun-15-2021 23-08-25](https://user-images.githubusercontent.com/13480805/122077787-9e9f7580-ce2e-11eb-80bb-2a799e9a1936.gif)
