### ISSUE TITLE
[Bug Report] button使用icon错乱

### ISSUE THREAD

**Issue by Sunnyjson** [youzan/vant-weapp#4266]
### 设备
微信开发者工具

### VantWeapp 版本
1.6.9

### 基础库版本
1.5.1

### 请提供核心代码片段链接
https://gist.github.com/Sunnyjson/7c14e5071c6e99545462b09dfdd5a9c8

### 描述问题
van-button 使用icon属性， 赋值为wechat时，显示的图标为wechat-pay

**Comment by nemo-shen** [comment]
可能是你自己的图标库影响到了吧，官方示例没有问题

**Comment by cuizs** [comment]
确实有这个问题啊
