### ISSUE TITLE
[Feature Request] icon图标增加可以直接应用iconfont功能

### ISSUE THREAD

**Issue by y451687300** [youzan/vant-weapp#4273]
### 这个功能解决了什么问题
支持更多和自定义的icon库

### 建议的API是什么样的
同vant的使用方式相同

**Comment by nemo-shen** [comment]
@y451687300  事实上，你只要将iconfont下载到本地就可以实现扩展自定义组件库了，icon组件中我们提供了class-prefix
所以你可以这样用:
```html
<van-icon name="my-icon" class-prefix="icon" />
```
并且在你的 `index.wxss` 中包含iconfont的图标库即可

官方文档可能没有更新，但是并不妨碍使用:)

![image](https://user-images.githubusercontent.com/13480805/122445462-2a9ed200-cfd4-11eb-8837-5629a7d5a804.png)

![image](https://user-images.githubusercontent.com/13480805/122445525-38545780-cfd4-11eb-861c-4b0c50a54f27.png)

**Comment by nemo-shen** [comment]
@y451687300 文档已更新
