### ISSUE TITLE
Navbar右图标被小程序胶囊挡住

### ISSUE THREAD

**Issue by yik7707** [youzan/vant-weapp#4274]
如下图，希望能自定义右图标举例，或能slot自主添加按钮
![QQ截图20210618082821](https://user-images.githubusercontent.com/74293458/122488593-5cce2500-d010-11eb-87a3-7837d5de1aed.jpg)

**Comment by rex-zsd** [comment]
开启自定义顶部导航时，右上角固定显示胶囊，可以认为此时右侧是不可以自定义的哈。
