### ISSUE TITLE
[Bug Report] van-index-bar动态索引列表为空数组时报错Cannot read property 'height' of null

### ISSUE THREAD

**Issue by IsVivian** [youzan/vant-weapp#4277]
### 设备
任何设备

### VantWeapp 版本
1.6.9

### 基础库版本
2.16.0

### 请提供核心代码片段链接
https://github.com/youzan/vant-weapp/blob/dev/dist/index-bar/index.js

### 描述问题
索引栏和列表为接口请求的数据，加了搜索框所以会存在空列表的情况，数据为空时会报这个错误，模拟器和真机设备都会报这个错。

**Comment by nemo-shen** [comment]
@IsVivian 已在1.7.1修复
