### ISSUE TITLE
能不能提供一下比较合理的rpx适配啊

### ISSUE THREAD

**Issue by 18674801565** [youzan/vant-weapp#4278]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater?repo=VantWeapp

**Comment by nemo-shen** [comment]
VantWeapp是一个组件库，不同场景的适配策略都不太一样，适配应该交由开发者自己完成，官方出的适配方案并不能完全满足大部分开发者的诉求，收益不是特别高
