### ISSUE TITLE
[Bug Report] ios输入框在点击弹出选择框后不会自动失焦，键盘不收回。

### ISSUE THREAD

**Issue by AaronChuzb** [youzan/vant-weapp#4284]
### 设备
IphoneX

### VantWeapp 版本
1.6.8

### 基础库版本
2.14.1

### 截图

![错误1.jpg](https://i.loli.net/2021/06/21/baV2rqcGkEhxezf.jpg)

![错误2.jpg](https://i.loli.net/2021/06/21/wSsnlh12kimNxFu.jpg)

### 核心代码片段链接
https://developers.weixin.qq.com/s/9B1uDemH7mrV

### 描述问题
在输入文字后，未收起键盘的时候，点击弹出框，输入框不会自动失焦，键盘也不会自动收回，出现跟图上一样的状况，还有输入的时候，滑动屏幕有几率输入框也不会失去焦点。开发工具无法复现，只有真机调试才能复现。

**Comment by nemo-shen** [comment]
@AaronChuzb 微信小程序的问题，即使不使用组件库，使用微信的 `<input />`组件，也会出现同样的问题

### 给出的建议
可以使用组件库提供的slot:input用 `view` 重写内部的原生 `<input />`，举个🌰
```html
<van-field model:value="{{ username }}" label="姓名" placeholder="请输入姓名" required />
<van-field value="{{ political }}" label="政治面貌" placeholder="请选择政治面貌" required is-link readonly bindtap="showPickers">
  <view style="width: 100%; height: 100%;color:#c8c9cc;" slot="input">请选择政治面貌</view>
</van-field>
<button bindtap="showPickers">showPickers</button>

<van-popup z-index="99999" show="{{ showPicker }}" position="bottom" bind:close="onClose" data-id="0">
  <van-picker title="政治面貌" data-id="0"  show-toolbar columns="{{ columns }}" bind:confirm="onConfirm" bind:cancel="onClose" />
</van-popup>
```
