### ISSUE TITLE
picker组件mode属性值有哪些？是否支持年月日时分秒？

### ISSUE THREAD

**Issue by mrliuyufeng** [youzan/vant-weapp#4285]
日期是否可以选择年月日时分秒？
    <picker mode="date" bindchange="SetX_Date">
      <van-field value="{{ X_CompleteDate }}"  label="完成日期" icon="underway-o"
        placeholder="请选择完成日期" readonly />
    </picker>

**Comment by nemo-shen** [comment]
`Picker` 组件是个选择器组件，你要传什么是由你自己定的
你说的mode是什么东西我不清楚
如果你是要问题`DatetimePicker`的话可以看 `type` prop

Picker: https://vant-contrib.gitee.io/vant-weapp/#/picker
DatetimePicker: https://vant-contrib.gitee.io/vant-weapp/#/datetime-picker
