### ISSUE TITLE
小程序使用vantweapp组件的问题

### ISSUE THREAD

**Issue by tantan-alt** [youzan/vant-weapp#4286]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater?repo=VantWeapp
我是用vantweapp来开发小程序，目前使用了倒计时的组件来做一个拼团秒杀等活动组件，但是使用了之后导致电脑cpu直接占满，手机也是很烫，这种情况需要怎么解决？求回复，求翻牌
![image](https://user-images.githubusercontent.com/55870364/122891670-46f59280-d377-11eb-8d89-2f90ced2afd4.png)

**Comment by nemo-shen** [comment]
🌚emmm可能是setTimeout导致的性能问题

**Comment by j190512** [comment]
> 你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。
> 
> http://vant-contrib.gitee.io/vant-issue-generater?repo=VantWeapp
> 我是用vantweapp来开发小程序，目前使用了倒计时的组件来做一个拼团秒杀等活动组件，但是使用了之后导致电脑cpu直接占满，手机也是很烫，这种情况需要怎么解决？求回复，求翻牌
> ![image](https://user-images.githubusercontent.com/55870364/122891670-46f59280-d377-11eb-8d89-2f90ced2afd4.png)

你这是开了几个倒计时啊

**Comment by j190512** [comment]
开了几个倒计时啊

**Comment by j190512** [comment]
感觉是频繁调用了setdata的锅

**Comment by j190512** [comment]
@JesseZzz904 wxs可以

**Comment by Cream7** [comment]
wxs了解一下

**Comment by Leskur** [comment]
我认为不管用不用 wxs，把这个毫秒得计时器做成单例应该可以解决。

当然最骚得操作是：毫秒倒计时使用 gif 实现。
