### ISSUE TITLE
datetime-picker在拖动年份的时候日期不对，当前是30天，一直显示的是30天，没有变化。

### ISSUE THREAD

**Issue by dzlishen** [youzan/vant-weapp#4287]
<van-datetime-picker
  type="date"
  value="{{ curDate }}"
  bind:input="onInput"
  min-date="{{ minDate }}"
  formatter="{{ formatter }}"
/>

curDate: new Date().getTime(),
minDate: new Date(1900, 0, 1).getTime(),
maxDate: new Date().getTime(),
formatter(type, value) {
	if (type === 'year') {
			return `${value}年`;
	} 
	if (type === 'month') {
			return `${value}月`;
	}
	return value;
		},

日期拖动的时候day一直是30天，没有根据年月进行变动，控制台报错。RangeError: Invalid array length

![image](https://user-images.githubusercontent.com/4525542/122893121-9be5d880-d378-11eb-871f-70400f37925a.png)
![image](https://user-images.githubusercontent.com/4525542/122893157-a4d6aa00-d378-11eb-97bf-3c7417d5106b.png)

**Comment by dzlishen** [comment]
@shiny

**Comment by lorisong** [comment]
我也遇到同样的问题了，怎么解决的啊？
