### ISSUE TITLE
[Bug Report] 日历组件：van-calendar的显示问题

### ISSUE THREAD

**Issue by youupiup** [youzan/vant-weapp#4288]
### 设备
安卓

### VantWeapp 版本
1.6.9

### 基础库版本
2.17.3

### 如果是 UI 问题，截图链接（多图回车分隔）

![截图](https://i.loli.net/2021/06/23/yVxYTPFg5Ne8tBb.png)

![截图](https://i.loli.net/2021/06/23/6mhdKRCPNnuiVoY.png)

### 请提供核心代码片段链接
https://github.com/

### 描述问题
请问如何默认弹窗的时候就显示当前的日历页面呢？目前我的日历一弹窗显示的1月份，明显不对，因为现在是6月份了，如何才能让日历一打开就是当前6月份呢？不然用户每次都得从1月份滚动到6月份才看得到当前日期

**Comment by youupiup** [comment]
而且，已经滚动到6月份了，顶部还是显示5月份？如何解决呢？

**Comment by JIANGYUNPU** [comment]
请问你解决了吗？我也有这样的问题，另外问下，你知道小程序版的滚动事件是哪个吗？就是滚动获取当前显示的月份

**Comment by nemo-shen** [comment]
看起来好像设置了`min-date` 之后默认会选中minDate的时间

**Comment by Kareshii** [comment]
请问这个还没解决吗 赋值min-date后默认会跳到赋值的时间 而非new Date时间

**Comment by cykgxy** [comment]
> 而且，已经滚动到6月份了，顶部还是显示5月份？如何解决呢？

请问这个显示问题你解决了吗？

**Comment by shenjingnan** [comment]
已经在 `1.7.2` 中修复了

**Comment by qingyl** [comment]
1.7.2还没修复default-date默认值无法设置
