### ISSUE TITLE
[Bug Report] 预览demo报错

### ISSUE THREAD

**Issue by tumblingG** [youzan/vant-weapp#4289]
### 设备
小程序模拟器

### VantWeapp 版本
1.6.9

### 基础库版本
2.3.2

### 请提供核心代码片段链接
https://github.com/youzan/vant-weapp

### 描述问题
npm run dev之后，用小程序开发工具打开example目录 ，报这个错误：
[ app.json 文件内容错误] app.json: ["usingComponents"]["van-action-sheet"]: "./dist/action-sheet/index" 未找到(env: Windows,mp,1.05.2105272; lib: 2.3.2)

**Comment by nemo-shen** [comment]
可以根据错误描述在`example/dist`中进行排查，我这边没有遇到你说的情况

**Comment by marren06** [comment]
@nemo-shen demo 里面根本就没有dist文件夹

**Comment by dingdr** [comment]
我也碰到这个问题，报一下错误：
[ dist/action-sheet/demo/index.json 文件内容错误] dist/action-sheet/demo/index.json: ["usingComponents"]["demo-block"]: "../../../example/components/demo-block/index" 未找到(env: Windows,mp,1.05.2111300; lib: 2.6.5)

../../../example 多了一层../目录，不知怎么解决？

**Comment by yaochangliang159** [comment]
@nemo-shen  我也是，下载最新的git代码，然后打开example文件夹，就会报找不到dist文件夹的错误，我一看，dist文件夹在上一层文件夹里面呢，没有在example文件夹里面，麻烦排查一下问题啊

**Comment by tomatobybike** [comment]
@nemo-shen demo 里面根本就没有dist文件夹
