### ISSUE TITLE
从 zanui 迁移到 vant，我发现的一些问题

### ISSUE THREAD

**Issue by billLiao** [youzan/vant-weapp#429]
**我需要的功能是？**
- 之前一直使用的 zanui，并且大量的使用了 zanui 基础样式中的字体大小、颜色、加粗等样式，最近想迁移到 vant，发现基础样式没有提供
- 在 icon 中没有发现分享的 icon，这个应该是很通用的吧，保存到相册的 icon 也没有找到。 

**你期望 API 是什么样的？**
- 希望基础样式中可以提供一些关于字体大小、加粗等样式
- icon 中特别希望增加分享的 icon

**Comment by chenjiahan** [comment]
目前不提倡用基础样式来指定字体大小、颜色，所以去掉了
分享图标是有的，share
