### ISSUE TITLE
van-circle  插槽 引用需要这么写？

### ISSUE THREAD

**Issue by OneYardOneWorldLiuZ** [youzan/vant-weapp#4292]
源码中：
 <slot></slot>
外部使用插槽自定义无法赋值

修改为：
<slot name="circle"></slot>
外部使用(成功)
<view slot="circle"> xxxx<view>

**Comment by nemo-shen** [comment]
get不到你要表达的意思，建议参考文档使用 https://vant-contrib.gitee.io/vant-weapp/#/circle

**Comment by xxxs** [comment]
<van-circle
        v-model="currentRate"
        :rate="30"
        :speed="100"
      >
        <template #default>
          <div>first line</div>
          <div>Second line</div>
        </template>
      </van-circle>
