### ISSUE TITLE
[Feature Request] tabbar-item 组件建议增加url属性，以便于点击之后直接调整到指定的页面

### ISSUE THREAD

**Issue by tianr1190** [youzan/vant-weapp#4293]
### 这个功能解决了什么问题
在全局使用同一个tabbar，比如底部菜单栏的时候尤其有用。不需要重新写复杂的跳转代码。

### 建议的API是什么样的
@vant > veap > tabbar-item > index.js
props: 添加 url: String 属性。

@vant > veap > tabbar-item > index.js > methods > onClick方法的开头添加下面的代码：
 if(this.data.url){
        var url = this.data.url;
        wx.navigateTo({
          url: url,
        })
        return false;
      }

使用时，直接在van-tabbar-item 指定 url="要跳转的页面地址"

**Comment by nemo-shen** [comment]
有价值的feature

**Comment by Suzuku** [comment]
> 有价值的feature，近期支持:)

如果添加url属性，需要考虑和click事件的触发先后关系，跳转这个操作需要慎重

**Comment by landluck** [comment]
`v1.10.13` 版本已支持
