### ISSUE TITLE
uploader组件，上传文件之后无法预览，openDocument文件失败

### ISSUE THREAD

**Issue by xslong1994** [youzan/vant-weapp#4296]
应当在使用wx.openDocument之后，调用wx.downloadFile接口将文件下载到本地，同时显示的文件名称，希望能限制在最多两行
![image](https://user-images.githubusercontent.com/23650597/123245108-19dfe600-d517-11eb-979e-3e98f227c674.png)

**Comment by nemo-shen** [comment]
@xslong1994 官方示例无法复现，请给出更详细的问题描述与最小可复现代码
