### ISSUE TITLE
van-popup   close-on-click-overlay	是否在点击遮罩层后关闭

### ISSUE THREAD

**Issue by jmsdqwl** [youzan/vant-weapp#4298]
设置这个后  点击遮罩层也关闭不了
用 bind:click-overlay 的话 单独关闭 好使

closeable
关闭图标一样 无法关闭

**Comment by nemo-shen** [comment]
@jmsdqwl 请按规范提issues谢谢配合

**Comment by kingslary** [comment]
是的，没有作用，每次都要自己写个事件去绑定关闭，非常麻烦
