### ISSUE TITLE
SwipeCell 滑动单元格不能使用 rpx 单位

### ISSUE THREAD

**Issue by qihua-1996** [youzan/vant-weapp#4299]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater?repo=VantWeapp

right-width 属性设置默认就是px，无法更改尺寸，适配无法适配不同屏幕

**Comment by Dramalf** [comment]
circle也是

**Comment by sherrycxm** [comment]
引入dist，引用swipe-cell时，页面不会显示 ，<van-swipe-cell right-width="{{ 65 }}" left-width="{{ 65 }}">
  <view slot="left">选择</view>
  <van-cell-group>
    <van-cell title="单元格" value="内容" />
  </van-cell-group>
  <view slot="right">删除</view>
</van-swipe-cell> 其他组件能正常引用
