### ISSUE TITLE
search文档示例代码错误

### ISSUE THREAD

**Issue by tat757** [youzan/vant-weapp#430]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**描述一下问题**
网页小程序search有部分示例代码使用的是Vue的示例代码
https://youzan.github.io/vant-weapp/#/search

**截图**
![1](https://user-images.githubusercontent.com/7260758/44135783-14725902-a09d-11e8-814a-b7251a4fbfaa.png)
![2](https://user-images.githubusercontent.com/7260758/44135791-177678a4-a09d-11e8-86b1-b20d89d21b39.png)

**环境**
 - 设备: 网页
 - 基础库版本:
 - Vant Weapp 版本: 0.1.0

**Comment by chenjiahan** [comment]
感谢反馈~ 文档已修正
