### ISSUE TITLE
[Bug Report] IndexBar 索引栏 在 iphone pro max 上 点击右侧字母选中不正确

### ISSUE THREAD

**Issue by imtns** [youzan/vant-weapp#4300]
### 设备
iphone pro max

### VantWeapp 版本
1.6.9

### 基础库版本
2.17.3

### 如果是 UI 问题，截图链接（多图回车分隔）

![截图](https://assets.speedomes.com/image/ZRnsiqWMKBrG5Je.png)

### 请提供核心代码片段链接
https://youzan.github.io/vant-weapp/#/index-bar

### 描述问题
IndexBar Props 中的sticky属性设置为false的时候,  在真机 iphone pro max 中表现不正确，点击右侧的字母，会选中到index-1上面 。sticky设置为true则选中表现正常。。测试真机 iphone X 、iphone 11、和安卓机表现正常，只有iphone pro max 上不正确

**Comment by johnsonwong666** [comment]
iphone pro max 是哪一代的 pro max？

**Comment by johnsonwong666** [comment]
还在吗？ 可以提供一下设备型号和复现代码片段嘛？手上的测试机没有复现
