### ISSUE TITLE
[Bug Report] van-image不支持iphone Xr 13.6.1上显示webp格式图片

### ISSUE THREAD

**Issue by zhihuifanqiechaodan** [youzan/vant-weapp#4304]
### 设备
iphoneXr

### VantWeapp 版本
1.6.9

### 基础库版本
2.17.3

### 请提供核心代码片段链接
https://developers.weixin.qq.com/s/DDl3XkmM7brK

### 描述问题
webp格式图片在iphoneX型号手机会加载图片失败。

**Comment by nemo-shen** [comment]
@zhihuifanqiechaodan 对vant-image来说其实只是透传了 `src prop` 到微信小程序原生的 `<image />` 组件上。
有更详细的加载失败信息吗？比如vConsole打印出来了error？是否能提供加载失败是什么样子的？

**Comment by zhihuifanqiechaodan** [comment]
> @zhihuifanqiechaodan 对vant-image来说其实只是透传了 `src prop` 到微信小程序原生的 `<image />` 组件上。
> 有更详细的加载失败信息吗？比如vConsole打印出来了error？是否能提供加载失败是什么样子的？

没问题。

下面是打印出来的错误日志
![image](https://user-images.githubusercontent.com/39149607/123573196-1478e900-d800-11eb-871c-22b0b9f4ab3b.png)

加载失败的样式如下

![361624849373_ pic](https://user-images.githubusercontent.com/39149607/123573413-7b969d80-d800-11eb-9561-628c280460f0.jpg)

目前发现在iphone Xr  13.6.1版本会有这个问题。最新版本系统没有这个问题。

**Comment by zhihuifanqiechaodan** [comment]
> @zhihuifanqiechaodan 对vant-image来说其实只是透传了 `src prop` 到微信小程序原生的 `<image />` 组件上。
> 有更详细的加载失败信息吗？比如vConsole打印出来了error？是否能提供加载失败是什么样子的？

这样的话貌似这个问题是微信那边的bug

**Comment by nemo-shen** [comment]
@zhihuifanqiechaodan 同样的环境，用van-image和小程序image分别测试下

**Comment by chenjiahan** [comment]
iOS 13 本来就不支持 webp 图片，iOS 14.4 才开始支持的。

https://caniuse.com/?search=webp

**Comment by zhihuifanqiechaodan** [comment]
> @zhihuifanqiechaodan 同样的环境，用van-image和小程序image分别测试下

尝试过了。image加上webp属性就可以显示了。不加的话也是不显示的。

**Comment by zhihuifanqiechaodan** [comment]
> iOS 13 本来就不支持 webp 图片，iOS 14.4 才开始支持的。
> 
> https://caniuse.com/?search=webp

是 那会我也看到了。 但是小程序image组件支持webp属性， 加上以后13.6.1这个版本是可以显示的。。。

**Comment by landluck** [comment]
`v1.10.11` 已修复

**Comment by zhihuifanqiechaodan** [comment]
done
