### ISSUE TITLE
[Bug Report] GoodsAction组件 button link-type设置成reLaunch跳转，右侧按钮会变形

### ISSUE THREAD

**Issue by Mango0110** [youzan/vant-weapp#4307]
### 设备
所有设备

### VantWeapp 版本
1.6.9

### 基础库版本
1.6.9

### 如果是 UI 问题，截图链接（多图回车分隔）

![截图](https://ftp.bmp.ovh/imgs/2021/06/9aca786c1757e914.png)

### 请提供核心代码片段链接
https://gist.github.com/Mango0110/49c2313e57358bb1549e8a02cae14f6e

### 描述问题
使用GoodsAction组件，并且GoodsActionButton link-type设置成reLaunch，这时候点击跳转，最右侧的按钮会变形

**Comment by nemo-shen** [comment]
@Mango0110 没有复现你的问题，有改动过官方示例能复现吗？是不是有动过dist目录？

**Comment by Mango0110** [comment]
必现的（需要用机器看），本来想分享小程序代码片段的，提示太大了
1. 按官方引入的方式（我选择的是npm安装）
2. 引入GoodsAction组件 
3. 将GoodsActionButton 的link-type 改成 reLaunch， url记得填写
4. 用真机点击，必复现

**Comment by Mango0110** [comment]
@nemo-shen
 可能的原因是真机点击的时候，.van-goods-action-button--last 的css变量--button-border-radius ，那一瞬间就没了，所以导致变形了，我现在定死了就可以

**Comment by Mango0110** [comment]
> @Mango0110 没有复现你的问题，有改动过官方示例能复现吗？是不是有动过dist目录？

用真机点击，必现，本来想分享小程序代码片段的，提示太大了
按官方引入的方式（我选择的是npm安装）
引入GoodsAction组件
将GoodsActionButton 的link-type 改成 reLaunch， url记得填写

**Comment by Mango0110** [comment]
> @Mango0110 没有复现你的问题，有改动过官方示例能复现吗？是不是有动过dist目录？

必现的（需要用真机看）本来想分享小程序代码片段的，提示太大了

1. 按官方引入的方式（我选择的是npm安装）
2. 引入GoodsAction组件
3. 将GoodsActionButton 的link-type 改成 reLaunch， url记得填写
4. 用真机点击，必现

可能的原因是真机点击的时候，.van-goods-action-button--last 的css变量--button-border-radius ，那一瞬间就没了，所以导致变形了，我现在定死了就可以

**Comment by Mango0110** [comment]
@nemo-shen 大佬帮忙看下，有个项目着急上线，这个问题，还挺严重的，麻烦了

**Comment by nemo-shen** [comment]
@Mango0110 

emmm，虽然我能复现你说的问题，但是从组件库角度来看似乎无法作出调整。

## 如何复现
- 使用提供的demo，需要注意的是，url必须要填写真实的链接，使得reLaunch能够真正跳转
- 点击icon跳转，此时会进行reLaunch，问题复现

## 组件库内部原理
### 为什么会这样？
原因是因为微信reLaunch的时候会销毁当前页面，此时会将所有的关联节点注销，但是由于微信小程序内部的原理，应该是：
- 解除所有节点的关联
- 还未解除完已经冻结了整个页面
- 打开新页面彻底销毁原页面

### 为什么组件库无法修复
- 如果你看源码的话，可以看 `packages/goods-action/index.ts` 中的 `useChildren` 它计算出所有关联的节点。
- 进入 `packages/common/relation.ts` 看 `useChildren` 方法，可以发现核心是利用了小程序的 `Component.getRelationNodes`方法，并且关联了一些 `relations`(`unlinked` 会在reLaunch触发时解除所有组件的关联，比如`GoodsActionButton`与`GoodsAction`之间的关联关系)，当触发这些事件的时候会执行我们的`onEffect`，也就是`GoodsActionButton.updateStyle`方法
- `GoodsActionButton.updateStyle`方法主要的作用是设置 `isFirst`和`isLast`以便能正确显示圆角

### 为什么不能直接用样式处理
使用样式处理有局限性，因为在一个`GoodsAction`中会有各种其他元素，wxss无法正确判断出第一个button和最后一个button，所以需要js介入判断

## 推荐的做法
因为组件库利用js已经判断好了谁是last，所以如果需要的话你可以在wxss中写
```css
.van-goods-action-button--last{
  margin-left: 0 !important;
  --button-border-radius: 0 20px 20px 0 !important;
}
```
这样应该能解决你遇到的问题:)

**Comment by Mango0110** [comment]
> @Mango0110
> 
> emmm，虽然我能复现你说的问题，但是从组件库角度来看似乎无法作出调整。
> 
> ## 如何复现
> * 使用提供的demo，需要注意的是，url必须要填写真实的链接，使得reLaunch能够真正跳转
> * 点击icon跳转，此时会进行reLaunch，问题复现
> 
> ## 组件库内部原理
> ### 为什么会这样？
> 原因是因为微信reLaunch的时候会销毁当前页面，此时会将所有的关联节点注销，但是由于微信小程序内部的原理，应该是：
> 
> * 解除所有节点的关联
> * 还未解除完已经冻结了整个页面
> * 打开新页面彻底销毁原页面
> 
> ### 为什么组件库无法修复
> * 如果你看源码的话，可以看 `packages/goods-action/index.ts` 中的 `useChildren` 它计算出所有关联的节点。
> * 进入 `packages/common/relation.ts` 看 `useChildren` 方法，可以发现核心是利用了小程序的 `Component.getRelationNodes`方法，并且关联了一些 `relations`(`unlinked` 会在reLaunch触发时解除所有组件的关联，比如`GoodsActionButton`与`GoodsAction`之间的关联关系)，当触发这些事件的时候会执行我们的`onEffect`，也就是`GoodsActionButton.updateStyle`方法
> * `GoodsActionButton.updateStyle`方法主要的作用是设置 `isFirst`和`isLast`以便能正确显示圆角
> 
> ### 是否能移除 `unlinked` 达到效果
> 魔改组件库是可以的，但是标准组件库没办法这样做
> 原因是：
> 
> 1. 其他组件同样依赖 `useChildren` 如果改动会对其他组件造成不可预知的影响
> 2. `unlinked` 在动态减少一个button的时候也会被触发，比如原先是一个button，由于用户做了某些操作出现了两个button这样的场景，如果移除了这个 `unlinked` 代码就不工作了
> 
> ### 为什么不能直接用样式处理
> 使用样式处理有局限性，因为在一个`GoodsAction`中会有各种其他元素，wxss无法正确判断出第一个button和最后一个button，所以需要js介入判断
> 
> ## 推荐的做法
> 因为组件库利用js已经判断好了谁是last，所以如果需要的话你可以在wxss中写
> 
> ```css
> .van-goods-action-button--last{
>   margin-left: 0 !important;
>   --button-border-radius: 0 20px 20px 0 !important;
> }
> ```
> 
> 这样应该能解决你遇到的问题:)
感谢，完美的解决了我的问题，不用祭天了
