### ISSUE TITLE
[Bug Report] 小程序版本的Rate组件半星展示不完整

### ISSUE THREAD

**Issue by liucong1** [youzan/vant-weapp#4311]
### 设备
Android 微信

### VantWeapp 版本
1.6.9

### 基础库版本
1.6.9

### 如果是 UI 问题，截图链接（多图回车分隔）

![截图](https://i.loli.net/2021/07/01/lBItDzEcyKFT3G4.jpg)

### 请提供核心代码片段链接
https://gist.github.com/liucong1/964ae10ef7b4cde9dc0ca8746edb9d2f

### 描述问题
半星的展示不正常

**Comment by luck2011** [comment]
同。
检查发现半星位置样式错位了，或者高度不够，在`rate/index.wxss`里找到`.van-rate__icon--half`这个类，加个`height: 150%;`就先暂时解决了~

**Comment by shenjingnan** [comment]
升级至 1.7.2

**Comment by luck2011** [comment]
@liucong1 升级了吗 我看问题还在
