### ISSUE TITLE
为什么不做一个类似这个card控件

### ISSUE THREAD

**Issue by neozhu** [youzan/vant-weapp#4312]
![image](https://user-images.githubusercontent.com/1549611/124133460-6e093e00-dab4-11eb-8574-e9b13531b616.png)
圆角/直角 加阴影
这个就非常有用

**Comment by chenjiahan** [comment]
Vant 中 CellGroup 的 inset 属性可以实现该效果，Vant Weapp 也可以加一下~ @nemo-shen

**Comment by AaronChuzb** [comment]
这种自己写几行代码实现貌似更能自定义

**Comment by neozhu** [comment]
@AaronChuzb 不瞒你说我对vue里面自定义css真的一窍不通，调一个样式半天整不出要给满意的

**Comment by nemo-shen** [comment]
@neozhu @AaronChuzb 将会在 `v1.7.2` 开始支持

**Comment by neozhu** [comment]
非常感谢
