### ISSUE TITLE
van-uploader accept="all"时，直接调起微信聊天窗口

### ISSUE THREAD

**Issue by dybxin** [youzan/vant-weapp#4314]
相关的示例就是使用的官方文档上提供的最新的示例：

```
<van-uploader file-list="{{ fileList }}"  accept="all" />
```

vant-weapp版本: 1.6.9

**Comment by wywsoor** [comment]
解决了吗

**Comment by dybxin** [comment]
@wywsoor 没有

**Comment by shenjingnan** [comment]
只有通过会话调起的才支持all
https://developers.weixin.qq.com/miniprogram/dev/api/media/image/wx.chooseMessageFile.html

**Comment by nemo-shen** [comment]
只有通过会话调起的才支持all
https://developers.weixin.qq.com/miniprogram/dev/api/media/image/wx.chooseMessageFile.html
