### ISSUE TITLE
[Bug Report] van-grid宫格组件bug 使用参数  icon-prefix="van-icon" 这样才会正常显示

### ISSUE THREAD

**Issue by supermebing** [youzan/vant-weapp#4317]
### 设备
微信开发者工具和iphone x

### VantWeapp 版本
1.7.0

### 基础库版本
2.17.0

### 请提供核心代码片段链接
https://developers.weixin.qq.com/s/0B4anzmD76rT

### 描述问题
van-grid组件不显示默认图标  
怀疑是 icon-prefix 参数没有默认“van-icon” 导致
<van-grid-item icon="coupon-o" text="导航一"/>
<van-grid-item icon="coupon-o" icon-prefix="van-icon" text="导航二"/>
上面两行代码 
导航二才会正确显示图标
请官方确认

**Comment by supermebing** [comment]
解决方法一致  等官方更新版本即可

**Comment by nemo-shen** [comment]
@supermebing 已在1.7.1修复，可以试一下~
