### ISSUE TITLE
为何vant 没有zanui 组件库丰富

### ISSUE THREAD

**Issue by imminmin** [youzan/vant-weapp#432]
**你需要的功能是？**
1. 发现vant相比zanui少了很多组件，例如： Tab、Radio、时间选择器、select、Dialog等组件。而这些又是很常用的组件；
2. vant相对与zanui，很多组件样式变动很大，例如：Loading、step等，而zanui的样式要比vant更丰富一点，以后vant会同步更新吗？

**你期望 API 是什么样的？**
同步两者样式与功能，并且完善文档，希望文档可以写的更详细一点

**Comment by chenjiahan** [comment]
参见 https://github.com/youzan/vant-weapp/issues/417，组件近期会完善
