### ISSUE TITLE
[Bug Report] v1.7.0 layout 中col组件宽度错误

### ISSUE THREAD

**Issue by Liu-Ya** [youzan/vant-weapp#4321]
### 设备
iPhoneX

### VantWeapp 版本
1.7.0

### 基础库版本
2.16.1

### 请提供核心代码片段链接
https://developers.weixin.qq.com/s/hwsjeAmS7Jrt

### 描述问题
col `width:2400%/24` 无效

![image](https://user-images.githubusercontent.com/23520283/124529869-fe8da880-de3d-11eb-9d3a-6f6f2e368cc9.png)

**Comment by nemo-shen** [comment]
@Liu-Ya 已在1.7.1修复，可以试一下~
