### ISSUE TITLE
Grid GridItem Props ->icon-prefix不能省略？vant-weapp版本1.7

### ISSUE THREAD

**Issue by heyqiang** [youzan/vant-weapp#4323]
这样不能显示图标的。`<van-grid-item icon="photo-o" text="文字" />`

必须要`<van-grid-item icon-prefix="van-icon" icon="photo-o" text="文字" />`

**Comment by agoni1212** [comment]
duplicate issue #4317 
will be fixed in v1.7.1 #4318
