### ISSUE TITLE
field表单只显示输入框其他什么都不显示，怎么回事

### ISSUE THREAD

**Issue by DaiRenQiang** [youzan/vant-weapp#433]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**描述一下问题**
field表单只显示输入框其他什么都不显示，怎么回事

**截图**
如果是 UI 问题，请提供具体截图
![image](https://user-images.githubusercontent.com/23715736/44205227-42044380-a188-11e8-965a-df3f5e49a173.png)

**环境**
 - 设备: 
 - 基础库版本: 
 - Vant Weapp 版本:

**Comment by chenjiahan** [comment]
麻烦贴一下代码

**Comment by rex-zsd** [comment]
可以参考一下demo小程序，看看demo小程序是不是同样有问题。

**Comment by DaiRenQiang** [comment]
谢谢，只不过很遗憾的是我已经投靠了 iView
