### ISSUE TITLE
IOS上多个Field组件来回点击时输入框会自动失去焦点

### ISSUE THREAD

**Issue by laozb** [youzan/vant-weapp#4330]
设备 iphone12mini
系统版本IOS14.5

复现场景：Vant自家的Vant组件库演示小程序

小程序中点开**Field输入框**模块，基础用法下面的自定义类型下有 用户名 密码 两个field，在这两个field之间来回点击 就会出现自动失焦的现象，iphone输入法会先弹起，然后自动收起来

**Comment by landluck** [comment]
该问题微信原生 input 就存在问题，组件层暂时没有办法解决，可以关注微信社区 https://developers.weixin.qq.com/community/develop/doc/000ea63d99887841b3cbe922b56800?_at=1656923325476
