### ISSUE TITLE
[Discussion] Vant support for Lark Gadget.

### ISSUE THREAD

**Issue by syy11955** [youzan/vant-weapp#4334]
### 这个功能解决了什么问题
When developing Lark Gadget the other day, I want to find a UI library but their is not a project supported. I want to make Vant-Larkapp and comtribute to support Lark Gadget. I wonder if it is necessary for this project.

### 建议的API是什么样的
Change wx APIs to tt APIs. This change will also support Tiktok apps.

**Comment by chenjiahan** [comment]
You can fork vant-weapp repo and add Lark/Tiktop apps support, I think there are more differences between these two miniprogram platform.

**Comment by syy11955** [comment]
Yeah, there are differences. I am going to work on it. I wonder if I want to create a new version for Lark miniprogram, should I open PR or just maintain the project in my forked repo?

**Comment by chenjiahan** [comment]
Just maintain in the forked repo
