### ISSUE TITLE
[Bug Report] 小程序运维报错

### ISSUE THREAD

**Issue by wuyve** [youzan/vant-weapp#4338]
### 设备
android

### VantWeapp 版本
1.5.3

### 基础库版本
2.18.0

### 请提供核心代码片段链接
https://sm.ms/image/cEWztCKXQRkbi2l

### 描述问题
小程序运维报警：https://sm.ms/image/cEWztCKXQRkbi2l，请问怎么解决呢？

**Comment by nemo-shen** [comment]
@wuyve 看不到你提供的核心代码片段
