### ISSUE TITLE
文档错误 ？

### ISSUE THREAD

**Issue by chunbobo** [youzan/vant-weapp#434]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**描述一下问题**
https://youzan.github.io/vant-weapp/#/cell

**截图**
![image](https://user-images.githubusercontent.com/16535982/44209323-b72a4580-a195-11e8-84b8-f6e41ac90d17.png)

复制到小程序中无法正常显示，改成view后成功显示，是我环境有问题还是文档有问题？

**Comment by chenjiahan** [comment]
感谢反馈，文档已修正
