### ISSUE TITLE
[Bug Report] IndexBar索引栏与Collapse折叠面板一起使用时冲突，右侧索引定位异常

### ISSUE THREAD

**Issue by AnglusWang** [youzan/vant-weapp#4342]
### 设备
模拟器、真机iPhone X

### VantWeapp 版本
1.6.8

### 基础库版本
2.11.0

### 如果是 UI 问题，截图链接（多图回车分隔）

![截图](https://z3.ax1x.com/2021/07/16/WM3958.png)

### 请提供核心代码片段链接
https://gist.github.com/AnglusWang/502d2ad3a39a06358e15ecb91ebea738

### 描述问题
如问题截图所示，IndexBar索引栏与Collapse折叠面板一起使用时，当折叠面板状态有一个以上展开时，索引栏高度计算定位时就会出现异常。不管是上下滑动页面时还是直接点击右侧索引栏时都是一样的结果。

**Comment by shenjingnan** [comment]
https://vant-contrib.gitee.io/vant-weapp/#/index-bar#qian-tao-zai-gun-dong-yuan-su-zhong-indexanchor-shi-xiao
