### ISSUE TITLE
[Bug Report] van-tab 组件中 shouldShow 判断错误

### ISSUE THREAD

**Issue by chengww5217** [youzan/vant-weapp#4344]
### 设备
所有设备

### VantWeapp 版本
1.7.1

### 基础库版本
所有版本

### 请提供核心代码片段链接
https://github.com/chengww5217/vant-tabs-bug

### 描述问题
当在 `van-tabs` 中使用 animated 属性时会因为 `van-tab` 
中 `shouldShow` 属性判断错误导致前一个 tab 页面还能显示在 下一个 tab 页面中。

错误代码：
https://github.com/youzan/vant-weapp/blob/dev/packages/tab/index.ts#L53

`shouldShow` 中应该修改为：`shouldShow: active || !parentData.animated,`

**Comment by chenjiahan** [comment]
当父组件有 transform 样式时，内部的 fixed 元素会被降级为 absolute 元素，建议把 fixed 元素放到外部去，单独进行控制
