### ISSUE TITLE
[Bug Report] van-popup弹窗消失，蒙层还在

### ISSUE THREAD

**Issue by MaiKurakiTT** [youzan/vant-weapp#4348]
### 设备
Honor V10

### VantWeapp 版本
1.7.1

### 基础库版本
2.18.0

### 请提供核心代码片段链接
https://gist.github.com/MaiKurakiTT/ce5fd67e6199bfad37b84942c4eb0301

### 描述问题
https://flowplus.meituan.net/v1/mss_a002ed9fc97544cebd70304686903863/cube/1626603227214.mp4

弹窗弹出后，此时show：true，未点击“取消”/“确认”按钮，返回上一页，再次进入此页面时初始化数据，此时show：false，弹窗消失，蒙层还在，返回再次进入就好了。

模拟器偶尔复现。安卓和ios都能复现。

**Comment by MaiKurakiTT** [comment]
这个大概什么时候能修复呀

**Comment by Hunglulu** [comment]
直接改源码，我用dropdown-item下拉菜单，遇到类似的问题，解决方式，找到源码的dropdown-item文件里的index.js，找到onClose方法，添加this.setData({ showWrapper: false });看下关闭的触发是哪个事件，在那个事件里把整个组件删除掉

**Comment by landluck** [comment]
最新版本没有看到这个问题了，可以重新尝试下，如还有问题，可以重新打开 issue，提供下复现信息
