### ISSUE TITLE
[Bug Report] tabs的info属性背景和文字位置不对

### ISSUE THREAD

**Issue by seedada** [youzan/vant-weapp#4350]
### 设备
微信开发者工具 iPhone12promax

### VantWeapp 版本
1.7.1

### 基础库版本
2.18.0

### 如果是 UI 问题，截图链接（多图回车分隔）

![截图](https://sm.ms/image/dl5AYDXj362WebF)

### 请提供核心代码片段链接
https://developers.weixin.qq.com/s/xJI0mUmq78rF

### 描述问题
tabs的info属性设置后文字和背景不在一个位置，文字紧贴着title值的后面

**Comment by YongTaiSin** [comment]
> ### 设备
> 微信开发者工具 iPhone12promax
> 
> ### VantWeapp 版本
> 1.7.1
> 
> ### 基础库版本
> 2.18.0
> 
> ### 如果是 UI 问题，截图链接（多图回车分隔）
> ![截图](https://camo.githubusercontent.com/cf1b69e7bacf05e72a794b10a8674edfb5732eb77cca4237a64ac34aa8e9aad2/68747470733a2f2f736d2e6d732f696d6167652f646c35415944586a33363257656246)
> 
> ### 请提供核心代码片段链接
> https://developers.weixin.qq.com/s/xJI0mUmq78rF
> 
> ### 描述问题
> tabs的info属性设置后文字和背景不在一个位置，文字紧贴着title值的后面

请问解决了吗 我发现最新版1.9.2也是 设置badge文字显示不出来

**Comment by landluck** [comment]
看了一下新版本没有这个问题，可以更新一下版本，如果还有问题请重新打开或者提交 issue

**Comment by landluck** [comment]
看了一下新版本没有这个问题，可以更新一下版本，如果还有问题请重新打开或者提交 issue
