### ISSUE TITLE
van-tabs组件 Tabs Slot问题

### ISSUE THREAD

**Issue by Boyka-SS** [youzan/vant-weapp#4351]
请问，van-tabs组件是默认会占据整个一行吗，可不可以有别的元素与其共行啊，还有的就是，Tabs Slot这个实在是理解不了，能否给个具体的例子呢？

**Comment by shenjingnan** [comment]
如果你要的是这种并列的话，是可以的
![image](https://user-images.githubusercontent.com/13480805/127195962-c28b10ee-22bf-45b3-9f6e-54b0f15c00df.png)

如果你是要在nav左右增加可以用 `nav-left` `nav-right`
![image](https://user-images.githubusercontent.com/13480805/127196231-ffa0b97d-155d-4462-9882-f90d29589eb6.png)


```html
<van-tabs active="{{ 1 }}" bind:change="onChange">
  <view slot="nav-left">左侧内容</view>
  <view slot="nav-right">右侧内容</view>
  <van-tab
    wx:for="{{ tabs4 }}"
    wx:key="index"
    title="{{ '标签 ' + item }}"
  >
    <view class="content" slot="tab">
      <view>{{ item }}</view>
      <view>内容</view>
    </view>
  </van-tab>
</van-tabs>
```

**Comment by Boyka-SS** [comment]
你好，第一个是不是在van-tabs组件外部添加了view容器，然后通过控制父容器，来实现并列的？
