### ISSUE TITLE
[Bug Report] uploader组件在accept=all的情况下 唤醒微信会话进行文件选取

### ISSUE THREAD

**Issue by kevinh458** [youzan/vant-weapp#4352]
### 设备
Iphone 5

### VantWeapp 版本
1.7.2

### 基础库版本
2.18.0

### 请提供核心代码片段链接
https://gist.github.com/2574021892/b3887e632037456a2b781996ba37c69d

### 描述问题
uploader组件accept=all 时会唤醒微信会话进行文件选取。开发工具上没有问题 二维码预览时会有问题。请问这个情况 如果小程序发布通过后也是唤醒会话进行文件选取么。accept=media不能支持我选取文件 我还需要选取录音文件

**Comment by shenjingnan** [comment]
因为只有chooseMessageFile能支持all
https://developers.weixin.qq.com/miniprogram/dev/api/media/image/wx.chooseMessageFile.html
