### ISSUE TITLE
Calendar 日历自定义日期文案

### ISSUE THREAD

**Issue by liuxia11230** [youzan/vant-weapp#4358]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater?repo=VantWeapp
formatter 放在data中。但是一般的需求都是拿到数据后进行自定义文案。如何在获取数据后在定义文案

**Comment by shenjingnan** [comment]
https://vant-contrib.gitee.io/vant-weapp/#/calendar#zi-ding-yi-ri-qi-wen-an
