### ISSUE TITLE
[Bug Report] cell-group inset 属性不生效

### ISSUE THREAD

**Issue by deltacat** [youzan/vant-weapp#4359]
### 设备
iphoneX

### VantWeapp 版本
1.7.2

### 基础库版本
2.15.0

### 如果是 UI 问题，截图链接（多图回车分隔）

![截图](https://user-images.githubusercontent.com/4793228/126587296-528c36cb-060d-4bd6-928b-5f6bbe540aef.png)

### 核心代码片段

```html
    <van-cell-group inset title="系统通知">
      <van-cell title="todo..." value="hahaha">
      </van-cell>
      <van-cell title="todo..." value="hahaha">
      </van-cell>
    </van-cell-group>
```

### 描述问题

更新至 1.7.2 后尝试使用cell-group inset 属性，UI 并未生效。如上图所示

**Comment by shenjingnan** [comment]
@deltacat 确定下重新构建了没有
![image](https://user-images.githubusercontent.com/13480805/127178587-e37438ad-786c-4b72-9d89-5acd2b7ad323.png)
