### ISSUE TITLE
组件自适应屏幕   px->rpx

### ISSUE THREAD

**Issue by EasonShi** [youzan/vant-weapp#436]
**你需要的功能是？**
全部　px 改成　rpx
不清楚是不是伪需求

**Comment by herowind** [comment]
> 用rpx会限制布局方式。
> 如果有很强的需求，postcss有各种插件可以帮助你把px转成rpx。

WUX框架用的就是rpx也不错，尤其现在小程序支持平板，px看上去确实不太舒服，希望vanui以后能出各rpx版的
