### ISSUE TITLE
微信小程序 DatetimePicker设置min-date 1970年之前无效，只到1970年；

### ISSUE THREAD

**Issue by chybcool** [youzan/vant-weapp#4362]
**设备**
微信开发者工具 iphone/安卓

**VantWeapp 版本**
1.7.2

**基础库版本**
2.18.0

**如果是 UI 问题，截图链接（多图回车分隔）**
无

**请提供核心代码片段链接**
<van-popup show="{{ calendarShow }}" position="bottom">
      <van-datetime-picker
        type="date"
        value="{{ currentDate }}"
        min-date="{{ minDate }}"
        bind:input="change"
      />
    </van-popup>

data:{
     mindate:new Date(1950,1,1).getTime(),
      currentDate:new Date().getTime()
}

**描述问题**
微信小程序 DatetimePicker设置min-date 1970年之前无效，只到1970年；无法设置到如上定义的1950年；即使用负数也不行；

**Comment by shenjingnan** [comment]
了解一下unix时间戳 https://baike.baidu.com/item/unix%E6%97%B6%E9%97%B4%E6%88%B3/2078227?fr=aladdin
