### ISSUE TITLE
自定义custom-tab-bar 在安卓真机上不显示 ，但在开发工具上是正常的

### ISSUE THREAD

**Issue by chybcool** [youzan/vant-weapp#4363]
**设备**
微信开发者工具 iphone/安卓

**VantWeapp 版本**
1.7.2

**基础库版本**
2.18.0

**如果是 UI 问题，截图链接（多图回车分隔）**
无

**请提供核心代码片段链接**
<template>
  <cover-view class="tab-bar">
    <van-tabbar active="{{ active }}" bind:change="onChange" class="barbody" >
      <van-tabbar-item wx:for="{{list}}" wx:key="text">
        <image
          slot="icon"  
          src="{{ item.iconPath }}"
          mode="aspectFit"
          style="width:30px;height:30px;"
        />
        <image
          slot="icon-active"
          wx:if="{{active===index}}"
          src="{{ item.selectedIconPath }}"
          mode="aspectFit"
          style="width:30px;height:30px;"
        />
        {{item.text}}
      </van-tabbar-item>
    </van-tabbar>
  </cover-view>
</template>

    properties:{
      active:{
        type:Number,
        value:2
      }

     onChange(e) {
        console.log(e,'e')
        wx.switchTab({
          url: this.list[e.detail].pagePath
        })
        this.active=e.detail
     }

//组件中调用
<custom-tab-bar active="{{active}}" />
  active:0,

  "custom-tab-bar":"../custom-tab-bar/index",

<style lang="scss">
  .tab-bar {
    position: fixed;
    bottom: 0;
    left: 0;
    right: 0;
    width: 100%;
    z-index: 99;
  }

</style>

<script type="application/json">
  {
    "component": true,
    "usingComponents": {
      "van-tabbar": "@vant/weapp/tabbar/index",
      "van-tabbar-item": "@vant/weapp/tabbar-item/index"
    }
  }
</script>

**描述问题**
自定义custom-tab-bar 在安卓真机上不显示 ，但在开发工具上是正常的

**Comment by shenjingnan** [comment]
@chybcool 图裂了
