### ISSUE TITLE
Radiogroup在Dialog中使用，IOS15上表现异常

### ISSUE THREAD

**Issue by yangmengyu2021** [youzan/vant-weapp#4364]
设备
微信开发者工具 iphone

VantWeapp 版本
1.7.2

基础库版本
2.18.0

**各个radio切换时，之前被选中的radio会出现黑色对勾，如下视频：**

https://user-images.githubusercontent.com/87807185/126620483-ac826126-078f-40e3-ba34-df42176d9028.mp4

部分代码：

![image](https://user-images.githubusercontent.com/87807185/126620711-6348949a-effd-4db4-835e-2126de831398.png)

**Comment by yangmengyu2021** [comment]
如有不明，请联系微信：xzymy2020

**Comment by johnsonwong666** [comment]
xr ios15测试没有复现， 可以提供一个复现的小程序代码片段吗？

**Comment by johnsonwong666** [comment]
author反馈已解决
