### ISSUE TITLE
哈喽，大佬们。其他我不问，我就想问一下官网老挂掉，是什么原因，运维工资给的不够么？

### ISSUE THREAD

**Issue by Nassicy** [youzan/vant-weapp#4367]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater?repo=VantWeapp

**Comment by chenjiahan** [comment]
官方是部署在 gitee pages 上的，昨晚 gitee 那边有问题，导致官网无法访问。

可以访问 Github 镜像：https://youzan.github.io/vant-weapp/#/home
