### ISSUE TITLE
[Bug Report] 微信小程序中 同时使用popup和tarbar组件的问题

### ISSUE THREAD

**Issue by QingjiuQAQ** [youzan/vant-weapp#4370]
### 设备
小程序编译器/iphone12/小米11

### VantWeapp 版本
1.6.2

### 基础库版本
2.16.1

### 请提供核心代码片段链接
https://gitee.com/mrzhangll/for-vant-issue.git

### 描述问题
在同时使用vant的popup和tarbar组件的时候 想要实现popup显示在tarbar上面一个层级 实际上tarbar层级高 通过z-index属性控制无效

**Comment by shenjingnan** [comment]
这样吗？我好像使用没什么问题
![image](https://user-images.githubusercontent.com/13480805/127774241-76944aa0-8754-4b53-a8bf-8ac201b301c2.png)
