### ISSUE TITLE
[Bug Report] upload组件回显的图片怎么添加token验证？

### ISSUE THREAD

**Issue by stayinwind88** [youzan/vant-weapp#4371]
### 设备
iPhone12

### VantWeapp 版本
1.6.8

### 基础库版本
2.18.0

### 请提供核心代码片段链接
https://developers.weixin.qq.com/s/o3d6D8my7Usr

### 描述问题
项目访问静态资源需要通过token验证 通过downloadFile获取静态资源赋值给fileList的url时 图片无法显示

**Comment by shenjingnan** [comment]
这个应该是业务逻辑吧
