### ISSUE TITLE
Dialog组件调用弹出框class-name无效

### ISSUE THREAD

**Issue by jidilang** [youzan/vant-weapp#4373]
### 设备
微信开发者工具

### VantWeapp 版本
1.7.2

### 基础库版本
2.17.0

### 如果是 UI 问题，截图链接（多图回车分隔）

![截图](https://sm.ms/delete/SWOAKXpUaEM5CYrDb7eZkgz2iw)

### 请提供核心代码片段链接
https://sm.ms/delete/xKnuEvloNei9GdRM81jSAIYJ42

### 描述问题
Dialog组件调用弹框class-name无效，使用class就可以

**Comment by shenjingnan** [comment]
好像是正常的
![image](https://user-images.githubusercontent.com/13480805/127773968-8f56807f-044b-48a5-9384-1fce3cb987e3.png)
![image](https://user-images.githubusercontent.com/13480805/127773980-c07731de-1ca7-44e2-9481-13157703a673.png)
