### ISSUE TITLE
uni-app开发app端无法正常使用van-area组件以及没有van-address-edit组件库

### ISSUE THREAD

**Issue by TheKingOfTime** [youzan/vant-weapp#4374]
![截图](https://user-images.githubusercontent.com/46626448/127636802-6dca77f9-bd47-4be9-a610-06c4b6f0b39d.png)
![image](https://user-images.githubusercontent.com/46626448/127636861-4b9dd13f-ce98-4bd0-a5fb-57db32e9be8c.png)
入图无法正常使用地址组件；
求尽快支持van-address-edit组件库

**Comment by chenjiahan** [comment]
暂无计划支持
