### ISSUE TITLE
[Bug Report] 日历组件calendar 时间标题异常

### ISSUE THREAD

**Issue by carrykingdow** [youzan/vant-weapp#4375]
### 设备
全系设备

### VantWeapp 版本
1.7.2

### 基础库版本
最新版本

### 如果是 UI 问题，截图链接（多图回车分隔）

![截图](https://res.woalive.com/minip/test/jaCYzcyThh.png)

### 请提供核心代码片段链接
https://youzan.github.io/vant-weapp/#/calendar

### 描述问题
日历组件滚动底部后 当前日期的月份与 title 月份不符。（怀疑监听滚动条的精度导致的）

**Comment by shenjingnan** [comment]
图片裂了
如果是说滚动到底部后，由于月份的高度不够所以明明在3月，但是title显示2月，这个应该是和vant同样的
![image](https://user-images.githubusercontent.com/13480805/127773201-a152c670-4cdf-4aa5-a80c-b43b57a58ee7.png)

**Comment by shenjingnan** [comment]
> 图片裂了
> 如果是说滚动到底部后，由于月份的高度不够所以明明在3月，但是title显示2月，这个应该是和vant同样的

emm，看到你的图了，因为是根据这个月份的区块top判断显示哪个月份的，所以你稍微移动下top触顶就是对的了，这个应该不是bug
你可以想象成这个屏幕里有两个月份区域，那这个时候title显示肯定是判断哪个over top就显示哪个月份的title，你的截图时候虽然有大约98%已经在显示1月了（这是我们人眼观测到的），但是逻辑上其实还是在12月份上
![image](https://user-images.githubusercontent.com/13480805/127773563-0b282e2a-7eea-4e1b-9339-31c4340d71e1.png)

**Comment by carrykingdow** [comment]
emmm...我也是这么想的 但是有时候已经滑到底了 因此也无法重新触发标题的更新了。我现在只能在最后一个月份下面加了一个垫片🤣
