### ISSUE TITLE
[Bug Report] popup内容溢出后，不能触屏滚动

### ISSUE THREAD

**Issue by github-gordon** [youzan/vant-weapp#4377]
### 设备
widonws 11, ios

### VantWeapp 版本
1.7.2

### 基础库版本
2.15.0

### 请提供核心代码片段链接
https://github.com/github-gordon/test_code/blob/main/1.txt

### 描述问题
van-popup中的内容超出容器无法触摸滚动，只能鼠标滚轮滚动。

**Comment by shenjingnan** [comment]
popup本身显示的时候就是禁止滚动的，他的遮罩层是使用的 `<overlay />` 组件实现的，而 overlay 内部有 `catch:touchmove="noop"`

如果你希望高度可以显示的正常点，可以
```html
  <van-popup
    show="{{ true }}"
    custom-style="height: 20%"
  >
    内容
  </van-popup>
```
这个example在文档上有类似的

**Comment by github-gordon** [comment]
我现在 需要的效果，是能够滚动，这个popup不能支持么

**Comment by github-gordon** [comment]
> popup本身显示的时候就是禁止滚动的，他的遮罩层是使用的 `<overlay />` 组件实现的，而 overlay 内部有 `catch:touchmove="noop"`
> 
> 如果你希望高度可以显示的正常点，可以
> 
> ```
>   <van-popup
>     show="{{ true }}"
>     custom-style="height: 20%"
>   >
>     内容
>   </van-popup>
> ```
> 
> 这个example在文档上有类似的

我现在需要的是能滚动的效果，这个popup就不能支持了么

**Comment by shenjingnan** [comment]
通过修改 `lock-scroll` 控制是否禁止滚动， `1.8.3` 将会支持

**Comment by shenjingnan** [comment]
1.8.3新增lock-scroll属性
