### ISSUE TITLE
van-notice-bar 文档属性错误

### ISSUE THREAD

**Issue by jimingzhuang** [youzan/vant-weapp#4380]
van-notice-bar background属性无效，查看组件内部发现参数名变更为backgroundColor,请及时更新文档

**Comment by shenjingnan** [comment]
不是的，我们对外提供的是 `background` 内部还预设了 `backgroundColor` 建议使用 `background`
你所说的 **无效** 可能是其他原因导致的

![image](https://user-images.githubusercontent.com/13480805/128046639-37b80c7c-32c2-4c60-a139-030ebe4dacd0.png)
![image](https://user-images.githubusercontent.com/13480805/128046697-6f59c663-ffa0-49e5-ad2c-fe5f5c00bb13.png)
![image](https://user-images.githubusercontent.com/13480805/128046780-67e8a2c0-6aa6-43c2-90cd-9bb804706e87.png)
