### ISSUE TITLE
[Bug Report] van-cell-group的click事件不能触发

### ISSUE THREAD

**Issue by Michael-py001** [youzan/vant-weapp#4381]
### 设备
小程序开发者工具/手机微信小程序

### VantWeapp 版本
1.7.2

### 基础库版本
2.18

### 请提供核心代码片段链接
https://codesandbox.io/s/vant-issue-moban-forked-hifmy

### 描述问题
代码在sandbox可以执行，但是Weaapp版本在uniapp开发的小程序中，这个van-cell-group不能触发click事件，也就是@click不能触发点击，要@click.native才能触发，在mpvue开发的小程序中没有出现这种情况，uniapp编辑器和vant weapp版本都是最新的1.7.2，请问是uniapp的编译问题吗？还是有bug?

**Comment by shenjingnan** [comment]
看问题描述像是uniapp的问题
