### ISSUE TITLE
[Bug Report] 基础库 2.18 以上版本提示大量 warning

### ISSUE THREAD

**Issue by MuGongziya** [youzan/vant-weapp#4390]
![image](https://user-images.githubusercontent.com/66168501/128584657-0aeee053-c2de-476a-84ac-6558b7165b18.png)
![image](https://user-images.githubusercontent.com/66168501/128584678-2c4af5d0-cb18-47f8-b09d-012f28c43a8e.png)

在开发时候，控制台突然输出这些信息，表示看不懂，但是控件都能正常运行。

**Comment by dongyuying** [comment]
开发工具-切换调试基础库，控制台就不会警告信息了

**Comment by MuGongziya** [comment]
> 开发工具-切换调试基础库，控制台就不会警告信息了

设置成2.15就好了   一开始用的2.19  感谢

**Comment by muuubooo** [comment]
咨询了官方，回复是
“基础库最近完善了校验逻辑，出现提示一般是因为slot 没找到或者 properties 的类型不对，请按照提示修改代码”

也希望vant这边能按照后续的标准跟进

**Comment by MuGongziya** [comment]
好的&nbsp; 谢谢



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年8月10日(周二) 晚上8:50
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [youzan/vant-weapp] 突然有很多警告，不知道是什么意思 (#4390)




 
咨询了官方，回复是
 “基础库最近完善了校验逻辑，出现提示一般是因为slot 没找到或者 properties 的类型不对，请按照提示修改代码”
 
也希望vant这边能按照后续的标准跟进
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by chenjiahan** [comment]
后续会优化此问题

**Comment by shenjingnan** [comment]
建议先将@vant/weapp升级至最新版，部分warning是由于历史版本引起的

**Comment by MuGongziya** [comment]
好的谢谢



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年8月26日(周四) 晚上10:30
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [youzan/vant-weapp] [Bug Report] 基础库 2.18 以上版本提示大量 warning (#4390)




 
***@***.***/weapp升级至最新版，部分warning是由于历史版本引起的
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by maidou883** [comment]
修复了吗？已经升级到"@vant/weapp": "^1.9.1"  微信基础库版本2.20.0 还是会提示 vant  [Component] slot "" is not found.

**Comment by Cream7** [comment]
每日一问，修复了吗？

**Comment by MuGongziya** [comment]
不知道，现在没开发小程序了



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年11月11日(星期四) 中午11:40
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [youzan/vant-weapp] [Bug Report] 基础库 2.18 以上版本提示大量 warning (#4390)






每日一问，修复了吗？

—
您正在接收此消息，因为您创建了该线程。
直接回复此邮件，在 GitHub 上查看或取消订阅.
GitHub Mobile 上的分流通知监督办或机器人.

**Comment by sRect** [comment]
还是一堆的警告

**Comment by Chaslee4** [comment]
还是有同样的警告

**Comment by MuGongziya** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Chas ***@***.***&gt;; 
发送时间: 2021年11月29日(星期一) 上午10:00
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [youzan/vant-weapp] [Bug Report] 基础库 2.18 以上版本提示大量 warning (#4390)





 
还是有同样的警告
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by sun948534670** [comment]
警告仍然存在

**Comment by Jackwew** [comment]
每日一问，解决了吗？

**Comment by xiaofeng1998025** [comment]
每日一问，解决了吗？

**Comment by eminoda** [comment]
每日一问，解决了吗？vant-dialog，vant-toast，van-overlay

**Comment by shenjingnan** [comment]
### Warning: the type of property "xxx" is illegal
是由于使用了小程序提供的 `optionalTypes` 导致，然而看起来小程序自身的 `optionalTypes`能力已失效
**我们已经移除了这个属性，用 `type: null` 代替多种类型**

### Warning: slot "" is not found
部分情况下，并不需要通过slot改变组件内容，但是由于小程序内部不能通过判断是否存在slot来实现是否需要渲染slot的逻辑，因此只要在组件内部添加了slot，但是外部又没使用就会warning
**目前，针对这种类型的warning无法解决，需要看微信后续会提供什么样的方式处理**

**Comment by sdlddr** [comment]
网上已有人给出了解决方案，
<view wx:else style="display:none"><slot /></view>
能否一直不解决，就看官方够不够懒了

**Comment by avilang** [comment]
@nemo-shen @chenjiahan 
不止警告，微信开发工具还报错了
![image](https://user-images.githubusercontent.com/10380760/180416957-802cacc3-3197-4a56-80a3-814c7590d6d7.png)

**Comment by yuchenyue** [comment]
20221117还是存在

**Comment by yoyo837** [comment]
问题仍然在，此问题应该至少保留一个open的issue来跟踪

**Comment by yoyo837** [comment]
建议 reopen
