### ISSUE TITLE
van-stepper 在购物车应用出现的问题

### ISSUE THREAD

**Issue by pi-qoatyn** [youzan/vant-weapp#4392]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater?repo=VantWeapp
[https://tdb-1252441773.cos.ap-nanjing.myqcloud.com/tsdmall/20210810113835.png](url)
在购物车中多件产品,第二件产品数量设置1件,
然后第一件产品数量减1,为0的情况删除此件产品.

图片中红色圈中的数量和步进器数量不符

**Comment by qiangzi7723** [comment]
我刚刚也遇到了这个问题，确定了是step组件的问题。只要是删除，就会出现这个BUG

**Comment by qiangzi7723** [comment]
加上async-change属性就可以解决了。不过应该也算是BUG了

**Comment by pi-qoatyn** [comment]
非常感谢！

曾志强 ***@***.***> 于2021年8月11日周三 上午11:49写道：

**Comment by chenjiahan** [comment]
请按照模板创建 issue，感谢配合
