### ISSUE TITLE
[Bug Report] Calendar默认日期default-date设置不生效

### ISSUE THREAD

**Issue by NRMrYang** [youzan/vant-weapp#4396]
### 设备
模拟器(IPhone X)、安卓真机(红米K30U)

### VantWeapp 版本
1.7.2

### 基础库版本
2.17.0

### 如果是 UI 问题，截图链接（多图回车分隔）

![截图示例](https://sm.ms/image/lrizKevIoVpLAUN)

### 请提供核心代码片段链接
https://gist.github.com/NRMrYang/c3caa31011a7be095ba6db14fed05c5c

### 描述问题
各位开发者好，目前发现将默认日期设置为七天后，但显示仍为当天，不知是我写法有问题还是组件问题，烦请各位看一眼，十分感谢

**Comment by NRMrYang** [comment]
截图示例图床地址：https://sm.ms/image/lrizKevIoVpLAUN
不知道为什么似乎被吞了

**Comment by coder0608** [comment]
这是 bug 么，无语了 ，那个日历 ，能不能再优化一下，还是啥的，加载页面的速度，大大影响了体验感

**Comment by shenjingnan** [comment]
1.8.3已修复

**Comment by NRMrYang** [comment]
> 1.8.3已修复

感谢，辛苦了
