### ISSUE TITLE
所有icon不显示

### ISSUE THREAD

**Issue by WGKLoveStudy** [youzan/vant-weapp#4399]
设备
微信小程序开发工具及真机

VantWeapp 版本
1.7.2

基础库版本
2.17.0

描述问题
所有icon都不显示，包括组件内包含icon的，例如search的搜索小图标，
报错：[渲染层网络层错误] Failed to load font https://img01.yzcdn.cn/vant/vant-icon-84f687.woff2
查看之前问题，重新设置了如下cdn，还是不显示，点击cdn链接提示Document not found

> @font-face {
  font-weight: normal;
  font-family: 'vant-icon-temp';
  font-style: normal;
  font-display: auto;
  src: url('https://img01.yzcdn.cn/vant/vant-icon-84f687.woff2') format('woff2'),
    url('https://img01.yzcdn.cn/vant/vant-icon-84f687.woff') format('woff'),
    url('https://img01.yzcdn.cn/vant/vant-icon-84f687.ttf') format('truetype');
}
.van-icon {
  font-family: 'vant-icon-temp' !important;
}

**Comment by chenjiahan** [comment]
这个报错没有影响的，参见 https://vant-contrib.gitee.io/vant-weapp/#/icon#chang-jian-wen-ti

CDN 链接我测试了没问题，示例工程里也能正常加载，建议检查下是否是其他原因
