### ISSUE TITLE
小程序支持iPad了，能否将组件样式单位px改为rpx

### ISSUE THREAD

**Issue by dearhulu** [youzan/vant-weapp#440]
小程序支持iPad了，能否将组件样式单位px改为rpx, 不然在iPad上面看上去字体太小了或者不协调

**Comment by rex-zsd** [comment]
可以找些postcss插件把px转成rpx，比如[postcss-px2units](https://www.npmjs.com/package/postcss-px2units)之类的。

**Comment by kingdle** [comment]
建议改rpx

**Comment by pengsamkee** [comment]
建议改成rpx啊，不同设备显示不一致啊
