### ISSUE TITLE
[Feature Request] van-search组件的清除控件增加自定义图标或url

### ISSUE THREAD

**Issue by zhihuifanqiechaodan** [youzan/vant-weapp#4400]
### 这个功能解决了什么问题
解决不同企业对于统一图标样式的要求

### 建议的API是什么样的
期望能够是一个插槽，能够编辑大小并放置url和icon

**Comment by zhihuifanqiechaodan** [comment]
并且清除控件是否能在输入框有内容的时候一直显示，而不是在获取焦点的时候根据输入框是否有内容显示。 或者做成一个属性可以控制

**Comment by shenjingnan** [comment]
已在 `v1.8.4` 中支持

**Comment by zhihuifanqiechaodan** [comment]
> 已在 `v1.8.4` 中支持

nice！
