### ISSUE TITLE
[Bug Report] 在taro vue vant weapp源码项目中，引用vant weapp中时间选择器组件，formatter和filter属性传参无法接收，无法正常使用 

### ISSUE THREAD

**Issue by lubo-fline** [youzan/vant-weapp#4403]
### 设备
手机

### VantWeapp 版本
1.8.0

### 基础库版本
小程序基础库: 8.0.3 使用框架: Vue 2  Taro v3.2.10

### 请提供核心代码片段链接
https://github.com/lubo-fline/meeting

### 描述问题
在页面中引入

<van-datetime-picker
                type="time"
                :value="dateTimePicker.time"
                :min-hour=" 8 "
                :max-hour='19'
                :filter=" filter "
                @confirm='timeConfirm'
                @cancel='isShowPicker=""'
            />
在methods中或者data中添加变量

filter(type, options){
            console.log(options)
            if (type === 'minute') {
                return options.filter((option) => option % 30 === 0);
            }
            return options;
        },
会发现console没有执行，并且组件中时间没有过滤。
在vant weapp组件源码中create里获取filter属性为undefined

在日期组件中添加 :formatter='formatter'
在data或者methods中添加对应属性值

formatter(type, value) {
                if (type === 'year') {
                    return `${value}年`;
                } 
                if (type === 'month') {
                    return `${value}月`;
                }
                return value;
            },
运行后页面报错

VM728 WAService.js:2 Unhandled promise rejection TypeError: formatter is not a function
    at index.js? [sm]:115
    at Array.map (<anonymous>)
    at index.js? [sm]:115
    at Array.map (<anonymous>)
    at vt.updateColumns (index.js? [sm]:114)
    at index.js? [sm]:311
    at VM728 WAService.js:2
    at r (VM728 WAService.js:2)(env: Windows,mp,1.05.2107221; lib: 2.17.0)
在日期组件中同样接收不到传过来的方法

期望结果：期望可以告知如何传函数类属性，并且可以正常传

实际结果：vant组件接收不到方法类属性，不知道是写法不对还是有问题。

**Comment by chenjiahan** [comment]
重复 issue：https://github.com/youzan/vant-weapp/issues/4176

**Comment by lihengdao** [comment]
how to solve this?

**Comment by lubo-fline** [comment]
https://github.com/youzan/vant-weapp/issues/4176
没有看到如何解决呀？

**Comment by lubo-fline** [comment]
> 重复 issue：#4176

没有看到如何解决呀？
