### ISSUE TITLE
[Bug Report] van-transition中使用van-sticky初始渲染bug

### ISSUE THREAD

**Issue by zhihuifanqiechaodan** [youzan/vant-weapp#4410]
### 设备
iphone

### VantWeapp 版本
1.8.2

### 基础库版本
2.17.3

### 请提供核心代码片段链接
https://developers.weixin.qq.com/s/4VwMtEmb7tsp

### 描述问题
页面中使用van-transition中嵌套van-sticky初始渲染位置不对。第一次渲染会默认处于吸顶，滑动后消失

**Comment by zhihuifanqiechaodan** [comment]
还有van-transition包裹的scroll-view会导致安卓机器无法定位到scroll-into-view

**Comment by landluck** [comment]
`v1.10.22` 已修复

**Comment by zhihuifanqiechaodan** [comment]
> `v1.10.22` 已修复

mark
