### ISSUE TITLE
[Bug Report] utils_1.getToday is not a function

### ISSUE THREAD

**Issue by willowramirez** [youzan/vant-weapp#4412]
正常引用 `"van-calendar": "@vant/weapp/calendar/index"` 组件，
编译出来的功能会报`utils_1.getToday is not a function`错

![image](https://user-images.githubusercontent.com/22291238/130024825-de0d288d-aa32-4e22-937f-b5faeba0006a.png)

![image](https://user-images.githubusercontent.com/22291238/130025091-5fc6d4bd-79a6-4797-ba2b-67c135a2ecd0.png)

**Comment by shenjingnan** [comment]
无法复现你说的问题，提供一下使用的vant-weapp版本，设备版本和最小可复现代码
