### ISSUE TITLE
Cannot read property 'vanPageScroller' of undefined

### ISSUE THREAD

**Issue by strangebank** [youzan/vant-weapp#4413]
Cannot read property 'vanPageScroller' of undefined

https://developers.weixin.qq.com/community/develop/doc/000e60d7b04c00cfc4bb003d95b000

**Comment by shenjingnan** [comment]
提供下最小复现代码？按照提供的链接尝试复现没成功，我思路不对？

我的理解是：
- 有两个页面
- 用tabbar控制两个页面切换（这里尝试了小程序原生tabbar和 `<Tabbar />`组件）
- 首先在tab2页面，点击tab2页面上的button，wx.reLaunch自己（tab2页面）
- tabbar切换到tab1页面
- 重新切会tab2页面
- 点击tab2上的button
