### ISSUE TITLE
[Bug Report] IndexBar 在Popup弹出层中使用时，滚动时 索引和列表对应不上

### ISSUE THREAD

**Issue by xiaoyu-666** [youzan/vant-weapp#4414]
### 设备
小米8屏幕指纹版  微信版本8.0.10

### VantWeapp 版本
1.8.2

### 基础库版本
2.19.1

### 如果是 UI 问题，截图链接（多图回车分隔）

![截图](https://sm.ms/image/5cB1ra376SkAdVz)

### 请提供核心代码片段链接
https://gist.github.com/xiaoyu-666/ea45d038d40491a197f03cfbd3318978

### 描述问题
微信小程序版的IndexBar 在Popup弹出层中使用时 索引和列表对应不上，列表上面的索引位置不准确。感觉在popup里面就都不太好使了。

**Comment by shenjingnan** [comment]
https://vant-contrib.gitee.io/vant-weapp/#/index-bar#qian-tao-zai-gun-dong-yuan-su-zhong-indexanchor-shi-xiao
