### ISSUE TITLE
van-tabs van-tab标签内容下写任意自定义组件含vant 组件 会报 [Component] slot "" is not found.

### ISSUE THREAD

**Issue by njt1340953658** [youzan/vant-weapp#4415]
![image](https://user-images.githubusercontent.com/28036916/130191567-2fd39867-d5e7-4df6-9254-8fdec997b030.png)
van-tabs van-tab标签内容下写任意自定义组件含vant 组件 会报 [Component] slot "" is not found.

**Comment by jasaec** [comment]
相同问题 另外还有大量 property received type-uncompatible value: 警告

**Comment by chenjiahan** [comment]
新版基础库的 warning 统一在这个 issue 中跟进：https://github.com/youzan/vant-weapp/issues/4390
