### ISSUE TITLE
grid中的按钮如何添加open-type功能？

### ISSUE THREAD

**Issue by bytrix** [youzan/vant-weapp#4416]
### 这个功能解决了什么问题
支持open-type功能

### 建议的API是什么样的
```
<van-grid-item open-type="xxx"></van-grid-item>
```

**Comment by shenjingnan** [comment]
`<Grid />` 内部是由 `<view />` 实现的，不具有 `open-type` 能力，但是你可以通过slot能力自定义成期望的效果
