### ISSUE TITLE
[Feature Request] DropdownMenu能否有办法阻止弹出菜单？

### ISSUE THREAD

**Issue by bytrix** [youzan/vant-weapp#4419]
### 这个功能解决了什么问题
比如说菜单项只有一个的情况下，就没必要弹出菜单

### 建议的API是什么样的
onTitleTap() {
  return false; // 不弹出菜单
}

**Comment by landluck** [comment]
`v1.10.12` 版本已支持 `use-before-toggle` 属性可以解决该问题
