### ISSUE TITLE
【BUG】van-search组件在有遮盖物时，点击时，会穿透遮盖物使输入框获取到焦点

### ISSUE THREAD

**Issue by yangmengyu2021** [youzan/vant-weapp#4420]
设备 iphone xs max IOS 15 beta版
系统版本IOS14.5

复现场景：van-search组件在有遮盖物时，点击时，会穿透遮盖物使输入框获取到焦点。 比如隔着遮罩层点击van-search，会使输入框获取到焦点

**Comment by shenjingnan** [comment]
设备 iphone11
IOS14.4

提供两种解决方案：
1. 在遮罩层上添加 `z-index: 2`，目前测试出来小程序的原生 `<input />` 组件可能有一个层级设置，通过这种方式可以规避
2. 如果遮罩层说的是弹窗之类，有一个 `show` 变量控制，可以在 `show: true` 时给 `<search />` 设置 `disabled: true`

**Comment by yangmengyu2021** [comment]
@nemo-shen 如果在所有可能的遮罩层上做改动，在页面比较复杂的时候较为麻烦，有无可能在search组件层面解决呢？
