### ISSUE TITLE
collapse 折叠面板快速点击多次无法打开 官方实例可以出现

### ISSUE THREAD

**Issue by yddhero** [youzan/vant-weapp#4422]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater?repo=VantWeapp

**Comment by shenjingnan** [comment]
iphone11 无法复现

**Comment by yddhero** [comment]
https://user-images.githubusercontent.com/53631390/130710168-12a046a0-d8fb-4b9d-be11-c900e6178d1e.mp4

安卓11

**Comment by yddhero** [comment]
> iphone11无法复现


https://user-images.githubusercontent.com/53631390/130710255-bbcdc087-4e8d-49e9-aa56-da8c98d2d6ef.mp4

**Comment by shenjingnan** [comment]
已在v1.9.2中修复
