### ISSUE TITLE
[Feature Request] DropdownMenu 下拉菜单，点击后能不能不弹出选项？

### ISSUE THREAD

**Issue by kongxy6** [youzan/vant-weapp#4428]
### 遇到了什么问题：
就是有这样一个使用场景，我想点击某个van-dropdown-item，直接跳转路由。

而现在的情况是，点击van-dropdown-item后，会弹出一个遮罩页面，这个页面可以自定义内容。我的需求是想不让他弹出子菜单，直接跳转路由。

有一种解决方案是取消van-dropdown-menu的overlay，但是这样吧所有的菜单的遮罩都取消了，体验又不太好。但是又没有可以关闭单个van-dropdown-item的overlay的API。

主要还是学艺不精，有没有什么css，能把单个van-dropdown-item的overlay取消掉。

还有一种方法是disabled掉van-dropdown-item，但是又没办法响应点击事件了。。。

### 目前的解决办法：
就是使用bind:open事件，在打开的时候，赶紧手动关闭，然后手动跳转路由，不过遮罩的overlay还是会闪一下。

### 希望：
能求一段可以取消某个菜单弹出子菜单的代码，且能响应点击事件。

而且有一点很操蛋，看了看代码，item的overlay是从menu传过来的，理论上应该每个item都能加一个overlay的属性吧，应该不是很难吧，可惜自己不会改。。真痛苦。

**Comment by qihua-1996** [comment]
直接使用点击时间不就行了？

**Comment by kongxy6** [comment]
> 直接使用点击时间不就行了？

点击事件，它依然会弹出overlay。不是说响应不住点击事件，是点了之后这个组件本身会弹出子菜单，子菜单的背景是个overlay，不想让这个overlay展示。

**Comment by landluck** [comment]
https://github.com/youzan/vant-weapp/issues/4419

**Comment by landluck** [comment]
`v1.10.12` 版本已支持 `use-before-toggle` 属性可以解决该问题
