### ISSUE TITLE
[Bug Report] tabbar被echarts图表遮挡问题

### ISSUE THREAD

**Issue by nwdsl1982** [youzan/vant-weapp#4429]
### 设备
IOS、Android

### VantWeapp 版本
1.6.9

### 基础库版本
2.19.1

### 如果是 UI 问题，截图链接（多图回车分隔）
图1<br/>
![截图](https://i.loli.net/2021/08/25/6QR5hJLKPYgpD1l.jpg)
<br/>图2
![截图](https://i.loli.net/2021/08/25/Zc4hY3xDWkFnEPu.jpg)

### 请提供核心代码片段链接
https://git.weixin.qq.com/nwdsl/dzm-weapp

### 描述问题
正常情况如图1,当图表滚动到页面底部时就会挡住tabbar，如图2，经测试设置z-index无效<br/>
相关issue：<br/>
https://github.com/youzan/vant-weapp/issues/2790<br/>
https://github.com/ecomfe/echarts-for-weixin/issues/349

**Comment by shenjingnan** [comment]
看下类似的历史issue #3112

**Comment by shenjingnan** [comment]
主要原因是因为echart用的原生canvas，导致这道了tabbar

**Comment by shenjingnan** [comment]
可以把tabbar也设置成原生的
