### ISSUE TITLE
field组件在form表单中的submit事件无法获取值

### ISSUE THREAD

**Issue by chasel34** [youzan/vant-weapp#443]
**描述一下问题**
form表单中的field组件通过form表单的submit事件无法获取值，将field组件中所有的currentValue替换为value后可获取到值。
可能的原因：通过wx://form-field获取的是组件data中的value属性的值。

**环境**
 - 设备:  pc 微信开发者工具v1.02.1808100
 - 基础库版本:  2.2.3
 - Vant Weapp 版本: v0.1.0

**Comment by chenjiahan** [comment]
感谢反馈，已经在 0.1.1 版本修复这个问题
