### ISSUE TITLE
[Feature Request] van-tab 组件的title希望可以使用slot自定义

### ISSUE THREAD

**Issue by AlwaysLoveme** [youzan/vant-weapp#4431]
### 这个功能解决了什么问题
van-tab 组件的title 可以自定义，比如加入icon

### 建议的API是什么样的
```
<van-tab >
    <view slot="title">title</view>
    内容 2
</van-tab>
```

**Comment by shenjingnan** [comment]
增加这个特性周期会有点长，需要重写 `<Tab />` 组件

**Comment by chen9091** [comment]
van-tab组件 wx:for循环 title 赋不上值

**Comment by JunGaJang** [comment]
这个太需要了。想在旁边加状态啥的，完全不行。

**Comment by zhihuifanqiechaodan** [comment]
> 这个太需要了。想在旁边加状态啥的，完全不行。

有赞大裁员。现在的issues不知道啥时候才有空解决。

**Comment by landluck** [comment]
https://github.com/youzan/vant-weapp/issues/4757

**Comment by nsnsqk** [comment]
两年了，大哥们，这个title slot还没有加上吧
