### ISSUE TITLE
vant样式单位是px，小程序开发的时候需要统一使用rpx来适配不同屏幕

### ISSUE THREAD

**Issue by MynameisRobin** [youzan/vant-weapp#4432]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater?repo=VantWeapp

**Comment by shenjingnan** [comment]
gulp、webpack等构建工具可以满足你的需求

**Comment by MynameisRobin** [comment]
我希望最好不使用额外的工具就能满足这个需求，等待你们vant以后的迭代吧！~
