### ISSUE TITLE
mpvue支持

### ISSUE THREAD

**Issue by wangwei123** [youzan/vant-weapp#444]
1. 能否支持mpvue呢，看起来mpvue会成为主流
2. 有个叫touchUI的，组件很丰富，能否参考借鉴一下呢

**Comment by zhaohuwei** [comment]
mpvue已经能支持小程序自定义组件，换言之也就支持了vant-weapp。
目前还有少数兼容性问题，其实可以自己解决一下。

**Comment by GodStream** [comment]
直接npm安装引入，组件并没有生效

**Comment by ruixiu** [comment]
touchUI和https://meili.github.io/min/index.html可像，不知道谁抄的谁

**Comment by vopdoo** [comment]
我在mpvue 中使用vant-weapp 
使用方式如下：

1. 参照 文档 https://youzan.github.io/vant-weapp/#/quickstart 中的方式二，把vant-weapp中的dist目录复制到mpvue 目录结构中的static下且重命名为vant

2. 执行 npm run dev 命令行中没有报错,会在

3. 打开小程序开发者工具，notify toast 会报错

![image](https://user-images.githubusercontent.com/42235710/44639951-4d116c00-a9f1-11e8-9e16-d867dedae18e.png)

目录结构为：

![image](https://user-images.githubusercontent.com/42235710/44639984-7d590a80-a9f1-11e8-9a55-33033af714e3.png)

@chenjiahan  @zhaohuwei  帮我看一下这一个问题，谢谢

**Comment by ldybecklee** [comment]
我写了个wepy版本的vant weapp例子,有兴趣的可以了解下
https://github.com/ldybecklee/wepy-vant-demo

**Comment by zhaohuwei** [comment]
@vopdoo 那个是展开对象的语法不支持，写成兼容的语法或者引入loader转换掉。

**Comment by vopdoo** [comment]
@zhaohuwei 
我更新了问题的描述，并把(...) 语法修改了，会出现后续的错误

@chenjiahan 可否指导一下这个问题呢

**Comment by zhaohuwei** [comment]
@vopdoo 然后这样引入 import Notify from '../../../static/vant/notify/notify';
（这要多谢@chenjiahan 在新版分开写了）

**Comment by vopdoo** [comment]
@zhaohuwei 
import Notify from '../../../static/vant/notify/notify'; 就可以了分开了
非常感谢你 我的这个问题 已经解决

@chenjiahan  

可以更新一下文档上的说明，可以减少使用者一些弯路

**Comment by xxxsimons** [comment]
[mpvue-vant](https://github.com/xxxsimons/mpvue-vant) 在mpvue中无缝接入vant weapp组件库，做的总结。

**Comment by maxiangsai** [comment]
动态给vant组件绑定数据不行啊

**Comment by rex-zsd** [comment]
@maxiangsai 具体是哪个组件？

**Comment by maxiangsai** [comment]
> @maxiangsai 具体是哪个组件？

field的value之类的动态绑定失效

**Comment by zhaohuwei** [comment]
> > @maxiangsai 具体是哪个组件？
> 
> field的value之类的动态绑定失效

原生是可以动态绑定的，如果用了mpvue，需要自己做change事件处理，赋值给变量。

**Comment by nan1010082085** [comment]
> mpvue 最新版 不是说项目目录跟小程序一致吗？用的时候在main.json中引用
```
"usingComponents": {
        "van-row": "../../../static/vant/dist/row/index",
        "van-col": "../../../static/vant/dist/col/index",
        "van-tabbar": "../../../static/vant/dist/tabbar/index",
        "van-tabbar-item": "../../../static/vant/dist/tabbar-item/index",
        "van-icon": "../../../static/vant/dist/icon/index"
    }
```

**Comment by mynameismaosheng** [comment]
mpvue-loader 1.1.2
引用Notify
`import Notify from '../../static/static/vant/notify/notify'`
命令窗口报错
`* ../../static/static/vant/notify/notify in ./node_modules/_babel-loader@7.1.5@babel-loader/lib!./node_modules/_mpvue-loader@1.1.4@mpvue-loader/lib/selector.js?type=script&index=0!./src/pages/hall/index.vue`
求救

**Comment by rex-zsd** [comment]
尝试了一下mpvue中使用vant-weapp，目前发现几个mpvue的坑：
1. vant-weapp必须放在static目录下，否则会报各种`not defined`的错。
2. 使用vant-weapp组件的外部样式类时必须去掉vue组件`style`标签的`scoped`属性，否则外部样式无法起作用。
3. vant-weapp组件抛出的事件中如果有`-`，mpvue中无法捕获，目前无解。

**Comment by duxphp** [comment]
> 尝试了一下mpvue中使用vant-weapp，目前发现几个mpvue的坑：
> 
> 1. vant-weapp必须放在static目录下，否则会报各种`not defined`的错。
> 2. 使用vant-weapp组件的外部样式类时必须去掉vue组件`style`标签的`scoped`属性，否则外部样式无法起作用。
> 3. vant-weapp组件抛出的事件中如果有`-`，mpvue中无法捕获，目前无解。
> 4. vant-weapp表单组件内部有抛出`input`事件，但是mpvue不支持`v-model`双向绑定，需要手动监听`input`事件赋值。

双向绑定这有有办法处理么？

**Comment by rex-zsd** [comment]
@duxphp mpvue现在不支持把`v-model`映射到原生组件抛出的`input`事件，所以没办法只能拆开写。

**Comment by wkl007** [comment]
> 我这有个mpvue版本的vant weapp例子,有兴趣的可以了解下
> https://github.com/wkl007/mpvue-vant-weapp

**Comment by 1429880240** [comment]
@wkl007 你的config.js那个是什么

**Comment by wkl007** [comment]
@1429880240 那个只是首页的数据而已

**Comment by luyangyanga** [comment]
@vopdoo 我也是这样做的  但是组件就是不生效   没有样式   也没有报错  请问大佬是什么原因啊

**Comment by nan1010082085** [comment]
左侧目录中vant-webappui放在static下
![image](https://user-images.githubusercontent.com/26052449/49560122-2c3fa780-f94c-11e8-824b-7d17af2d1c15.png)
在每一个页组件中以下结构 man.json 使用
![image](https://user-images.githubusercontent.com/26052449/49560163-44afc200-f94c-11e8-9411-e9d410484096.png)
//使用
{
    "navigationBarTitleText": "首页",
    "usingComponents": {
        "van-row": "../../../static/vant/dist/row/index",
        "van-col": "../../../static/vant/dist/col/index",
        "van-tabbar": "../../../static/vant/dist/tabbar/index",
        "van-tabbar-item": "../../../static/vant/dist/tabbar-item/index",
        "van-icon": "../../../static/vant/dist/icon/index"
    }
}

唯一有点尴尬的是这 .json 并没有代码提示 写起来懵比 不是那么流畅

**Comment by mynameismaosheng** [comment]
> 左侧目录中vant-webappui放在static下
> ![image](https://user-images.githubusercontent.com/26052449/49560122-2c3fa780-f94c-11e8-824b-7d17af2d1c15.png)
> 在每一个页组件中以下结构 man.json 使用
> ![image](https://user-images.githubusercontent.com/26052449/49560163-44afc200-f94c-11e8-9411-e9d410484096.png)
> //使用
> {
> "navigationBarTitleText": "首页",
> "usingComponents": {
> "van-row": "../../../static/vant/dist/row/index",
> "van-col": "../../../static/vant/dist/col/index",
> "van-tabbar": "../../../static/vant/dist/tabbar/index",
> "van-tabbar-item": "../../../static/vant/dist/tabbar-item/index",
> "van-icon": "../../../static/vant/dist/icon/index"
> }
> }
> 
> 唯一有点尴尬的是这 .json 并没有代码提示 写起来懵比 不是那么流畅

json里可以用绝对地址  /static/vant/...
组件内部职能  ../../../static/...

**Comment by wangyang0210** [comment]
https://www.cnblogs.com/wangyang0210/p/10449915.html

**Comment by hyx0217** [comment]
> 直接npm安装引入，组件并没有生效

建议使用git clone下来再复制dist到你的目录下。

**Comment by afishhhhh** [comment]
mpvue 的事件映射是 click->tap，如果一个 disabled 按钮 @click，还是能触发事件

**Comment by kid1412621** [comment]
Notify 组件内部用了小程序的 getCurrentPages 方法, 然而 [mpvue 不支持](https://github.com/Meituan-Dianping/mpvue/issues/558)

**Comment by xinconan** [comment]
> mpvue-loader 1.1.2
> 引用Notify
> `import Notify from '../../static/static/vant/notify/notify'`
> 命令窗口报错
> `* ../../static/static/vant/notify/notify in ./node_modules/_babel-loader@7.1.5@babel-loader/lib!./node_modules/_mpvue-loader@1.1.4@mpvue-loader/lib/selector.js?type=script&index=0!./src/pages/hall/index.vue`
> 求救
> 我现在 import 引什么都是这样报错

遇到同样问题，有解决方法吗？

**Comment by wanganxp** [comment]
建议改造为uni-app的无dom vue插件，这样就可以全端使用了。现在使用小程序用vant weapp，再编译到h5时，又得换vant ui，太麻烦了，只好弃vant了。

**Comment by TrevorYS** [comment]
请问mpvue里面vant怎么转换rpx
