### ISSUE TITLE
Overlay 遮罩层 lock-scroll 属性 测试不起作用

### ISSUE THREAD

**Issue by Odyssey166** [youzan/vant-weapp#4448]
请参见issue #4253：
[](https://github.com/youzan/vant-weapp/issues/4253)

将 "@vant/weapp"升级到了 "^1.8.2", 代码也做了如下调整：`<van-overlay show="{{showframe1}}" lock-scroll="false">`，但无论是在微信开发者工具中，还是苹果、安卓真机测试，都依然如故，老问题仍然没有得到解决。``

**Comment by shenjingnan** [comment]
`<van-overlay show="{{showframe1}}" lock-scroll="{{ false }}">`

**Comment by Odyssey166** [comment]
It works! 谢谢大牛指点！
