### ISSUE TITLE
[Bug Report] Tab标签页面，设置背景色问题

### ISSUE THREAD

**Issue by Killometer** [youzan/vant-weapp#4449]
### 设备
all

### VantWeapp 版本
1.8.3

### 基础库版本
2.19.2

### 如果是 UI 问题，截图链接（多图回车分隔）

![截图](https://i.loli.net/2021/09/02/fD9adcxJ5iFzRBw.png)

### 请提供核心代码片段链接
https://gist.github.com/Killometer/02a944a3a50f2f976b109c0a042ba352

### 描述问题
意图：
-想设置标签背景为透明色，只显示出最底层的图片。

问题：
-但是当设置标签背景色为透明时，还会有显示标签底部的白色。

**Comment by shenjingnan** [comment]
试试用css3变量 --tabs-nav-background-color: transparent
