### ISSUE TITLE
tab info属性，使用后样式有问题

### ISSUE THREAD

**Issue by zzhn6** [youzan/vant-weapp#4450]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater?repo=VantWeapp
![image](https://user-images.githubusercontent.com/29200763/131810178-55d290c3-8a0e-4c76-8194-ce99e0c853e1.png)

**Comment by shenjingnan** [comment]
重复 #4350
