### ISSUE TITLE
van-uploader 请问如何在打开上传页面的时候自动显示文件选择窗口？

### ISSUE THREAD

**Issue by Yookey** [youzan/vant-weapp#4451]
这种场景还是挺常见的：在打开上传页面的时候自动显示文件选择窗口，或者在点击上传按钮的时候判断如果没有选择上传的文件也会自动打开文件选择窗口。
希望能有这样的功能，感谢！

**Comment by shenjingnan** [comment]
这样的场景目前不会支持
