### ISSUE TITLE
van-calendar超过时间范围提示文案

### ISSUE THREAD

**Issue by CoolCola** [youzan/vant-weapp#4456]
![image](https://user-images.githubusercontent.com/13797082/132078640-655b1979-831e-4bc3-8e9a-c19d9feb4318.png)

<van-calendar :type="type" v-if="type === 'range'" safe-area-inset-bottom ref="calendar" :max-range="maxRange" :show-subtitle="false" :default-date="defaultDate" :min-date="minDate" :max-date="maxDate" allow-same-day color="#7076fe" class="calendar" :poppable="false" @close="toggle(false)"
				@confirm="onConfirm" />
超过60天提示文案没有消失，一直存在

**Comment by shenjingnan** [comment]
已在1.8.5中修复
