### ISSUE TITLE
1.7.1  van-field focus 属性没反应

### ISSUE THREAD

**Issue by dongyuying** [youzan/vant-weapp#4457]
1.7.1 van-field focus 属性没反应

**Comment by shenjingnan** [comment]
如果你是问 **为什么开发者工具中 focus会失效？**
答：field内部基于小程序的input组件封装，目前input组件在开发者工具和真机中表现不一致（该问题官方已知，[提供入口](https://developers.weixin.qq.com/community/develop/doc/00082264574ba0ec86cba01e751814?highLine=%25E5%25BE%25AE%25E4%25BF%25A1%25E5%25BC%2580%25E5%258F%2591%25E8%2580%2585%25E5%25B7%25A5%25E5%2585%25B7%2520input%2520focus))

目前我这边测试真机中field能自动聚焦，开发者工具中不能
