### ISSUE TITLE
vant-weapp导出插件的时候，可否使用ES6的语法，可以有更好的兼容性。

### ISSUE THREAD

**Issue by zhaohuwei** [youzan/vant-weapp#446]
**描述一下问题**
目前【vant-weapp】导出模块，使用了nodejs的语法，如：module.exports = Notify;
希望能使用ES6语法：export default Notify;或：export {Notify};
谢谢！

**环境**
 - Vant Weapp 版本: 0.1.0

**Comment by zhaohuwei** [comment]
【zan ui】时期，组件的js文件和插件导出的js文件是分开写，这样也有更好的兼容性，希望这一点可以在【vant-weapp】保留。

**Comment by zhaohuwei** [comment]
【zanui】时期，组件的js文件和插件导出的js文件是分开写，这样也有更好的兼容性，希望这一点可以在【vant-weapp】保留。

**Comment by chenjiahan** [comment]
export 的用法确实可以调整，会在下个版本优化
对于『组件的js文件和插件导出的js文件分开写』这个点，不是很了解分开有什么好处

**Comment by chenjiahan** [comment]
已在 0.2.0 版本优化
