### ISSUE TITLE
[Bug Report] button宽高无法调节，style无效

### ISSUE THREAD

**Issue by bfbz** [youzan/vant-weapp#4469]
### 设备
Iphone XR

### VantWeapp 版本
1.8.4

### 基础库版本
2.18.0

### 如果是 UI 问题，截图链接（多图回车分隔）

![截图](https://sm.ms/image/hfJ7XRAZmveS5L3)

### 请提供核心代码片段链接
https://sm.ms/image/2MnC78EV46lqaYv

### 描述问题

代码：

  <view style="margin: 10rpx;">
    <van-button style="width: 100%;" icon="https://img.yzcdn.cn/vant/logo.png" type="info">
      个人中心
    </van-button>
    <van-image width="100%" height="90rpx" src="https://img.yzcdn.cn/vant/cat.jpeg" />
  </view>

**Comment by shenjingnan** [comment]
```html
<van-button custom-style="height: 100px; width: 200px; font-size: 20px;" type="primary">主要按钮</van-button>
```
![image](https://user-images.githubusercontent.com/13480805/132679114-34af89bc-5822-4b8d-a3eb-a163e649193b.png)
