### ISSUE TITLE
collapse item的clickable属性文档没有说明用途

### ISSUE THREAD

**Issue by hanju** [youzan/vant-weapp#4471]
我的需求是能够单独响应某个collapse item的点击事件，而不是通过父节点van-collapse的change或者open函数。看到文档上说collapse item的有个clickable属性，但是没有任何具体说明。

**Comment by shenjingnan** [comment]
文档上有解释，如果不清楚可以写下demo测下效果，`collapse` 内部是使用的 `cell` 组件，所以直接用 `cell` 看就可以了
```html
<van-cell clickable="{{ false }}" title="单元格" value="内容" />
<van-cell clickable="{{ true }}" title="单元格" value="内容" />
```
