### ISSUE TITLE
[Feature Request] van-goods-action控件

### ISSUE THREAD

**Issue by zxtlin** [youzan/vant-weapp#4479]
### 这个功能解决了什么问题
van-goods-action自定义是否固定底部，是否生成占位符

### 建议的API是什么样的
van-goods-action希望增加类似Tabbar的属性fixed（是否固定在底部），placeholder（是否生成占位元素），GoodsActionButton希望类似Button一样可以自定义是否圆角

**Comment by shenjingnan** [comment]
van-goods-action 默认即是fixed
