### ISSUE TITLE
[Bug Report] Grid控件问题

### ISSUE THREAD

**Issue by zxtlin** [youzan/vant-weapp#4481]
### 设备
安卓

### VantWeapp 版本
1.8.4

### 基础库版本
1.8.4

### 如果是 UI 问题，截图链接（多图回车分隔）

![截图](https://i.loli.net/2021/09/11/D4XqtsYRbwKnH1y.png)

### 请提供核心代码片段链接
https://github.com/zxtlin/DEMO.git

### 描述问题
用grid控件显示数据，文本为['发出商品统计规则设置', '标准销售', '出货计划', '标准出货','应收发票']，第2行的菜单会因为第一行文本太长导致浮动到第2列

**Comment by shenjingnan** [comment]
### 原因分析
小程序默认会在自定义组件外包一层普通节点，这层节点自定义组件内部比较难控制（可以控制，但官方不会支持），导致无法像 `vant` 一样直接使用 `flex` 布局达到效果。在 `vant-weapp` 中我们是通过 `width百分比来控制` 而 vant则是 `通过flex-basis` 来控制

### 如何解决
使用 [虚拟化组件节点](https://developers.weixin.qq.com/miniprogram/dev/framework/custom-component/wxml-wxss.html#%E8%99%9A%E6%8B%9F%E5%8C%96%E7%BB%84%E4%BB%B6%E8%8A%82%E7%82%B9)，但需要组件库升级小程序基础库至 `v2.11.2`，目前 `vant-weapp` 最低支持的基础库版本是 `v2.6.5` 所以很遗憾，现阶段无法支持，我们会在合适的时机将基础库提升至该版本 @chenjiahan 

### 临时方案
别灰心，如果你愿意或正在使用小程序基础库`v2.11.2`及以上版本，[我这边提供了一个分支](https://github.com/nemo-shen/vant-weapp/tree/hotfix/grid_use_virtualHost_0924)，你可以 `clone` && `yarn build` 出你期望的 `grid` 效果 have fun :)~

<img width="1440" alt="grid-flex" src="https://user-images.githubusercontent.com/13480805/134546168-ac617496-c1a1-4dde-ba84-2d05397f5bd8.png">

**Comment by shenjingnan** [comment]
@chenjiahan 感觉虚拟组件节点可以尝试下\~对性能优化也有好处耶~

能少一层无用节点，数量应该挺可观的，每个自定义组件都有一个，如果能去掉，嵌套节点数量会下降，而且更接近web

**Comment by chenjiahan** [comment]
这个特性确实很合适，可以放到下个大版本里默认开启~
