### ISSUE TITLE
van-notice-bar flex布局内，文字不显示

### ISSUE THREAD

**Issue by changhuaC** [youzan/vant-weapp#4482]
### 设备
iphone

### VantWeapp 版本
1.8.4

### 基础库版本
2.19.2

### 请提供核心代码片段链接
https://vant-contrib.gitee.io/vant-weapp/#/notice-bar

### 描述问题
van-notice-bar在flex布局容器内，bar中的内文字不显示

**Comment by shenjingnan** [comment]
需要在组件上定义style，试试这样，vant-weapp建议使用最新版 1.8.4和1.8.5已经被废弃

```html
  <view style="display: flex;">
    <van-notice-bar
      text="{{ text }}"
      left-icon="volume-o"
      style="width: 100%"
    />
  </view>
```
