### ISSUE TITLE
[Bug Report] 通过组件 size 属性传值时，带有 px、rpx 等单位出现无法正常渲染

### ISSUE THREAD

**Issue by prosaically** [youzan/vant-weapp#4492]
### 设备
微信开发工具 RC 1.05.21009101

### VantWeapp 版本
1.8.5

### 基础库版本
2.19.4

### 如果是 UI 问题，截图链接（多图回车分隔）

![截图](https://i.loli.net/2021/09/15/M2EwK6RkCSQ1IXT.png)

### 请提供核心代码片段链接
https://developers.weixin.qq.com/s/hFRrekm47XtH

### 描述问题
通过组件 size 属性传值时，带有 px、rpx 等单位出现无法正常渲染。问题出现在 V1.8.5，其它版本没有这个问题。

### 代码片段说明
由于代码片段分享有大小限制，因此分享代码片段前删掉了 NPM 包。请导入代码片段后，使用 npm install ，再使用微信开发工具构建 npm 。

#### 能力有限，没分析出是哪里的问题引起。所以只能提交让各位大佬解决。

**Comment by shenjingnan** [comment]
1.8.5开始使用小程序optionalTypes特性，看起来有点问题，建议先使用1.8.3版本

**Comment by shenjingnan** [comment]
已在1.8.6修复
