### ISSUE TITLE
1.8.5 skeleton骨架屏row-width参数传值数组的问题

### ISSUE THREAD

**Issue by yik7707** [youzan/vant-weapp#4494]
如题：1.8.5 skeleton骨架屏row-width参数传值数组只显示部分骨架屏的问题
如下图代码（1.8.5版本）：
![image](https://user-images.githubusercontent.com/74293458/133435118-de18a55c-f3af-4b40-8932-edcd40ade2b6.png)
传值组件：
![image](https://user-images.githubusercontent.com/74293458/133435349-9217e38c-d7e4-4a19-842c-5ed9a3dd6d12.png)
![image](https://user-images.githubusercontent.com/74293458/133435417-f61fc754-1b8e-4f84-8e94-37495bb72f89.png)
效果显示（只显示部分骨架屏）：
![image](https://user-images.githubusercontent.com/74293458/133436131-9a43c83a-f698-493c-b35a-cee597d2708a.png)
更新之前，1.8.4版本是没问题，如下图：
![image](https://user-images.githubusercontent.com/74293458/133436176-d599739c-cf88-4698-825d-041adea5754e.png)
![image](https://user-images.githubusercontent.com/74293458/133435832-17b699a3-7d18-49f6-be26-3a876ffcaffa.png)

**Comment by shenjingnan** [comment]
建议先使用1.8.3版本

**Comment by shenjingnan** [comment]
已在1.8.6修复
