### ISSUE TITLE
[Bug Report] Radio icon-size 属性，指定单位无效

### ISSUE THREAD

**Issue by js5323** [youzan/vant-weapp#4497]
### 设备
全平台

### VantWeapp 版本
1.8.5

### 基础库版本
2.19.4

### 请提供核心代码片段链接
https://i.loli.net/2021/09/16/fzEytCj7LiIFOT6.png

`<van-radio checked-color="#18BE4B" icon-size="36rpx" name="2">test</van-radio>`

### 描述问题
设置了icon-size 无效，icon size 会变成0，只能设置纯数字，不能加单位例如：2rpx , 2px

**Comment by js5323** [comment]
查找最近的调整，发现是 iconSize 的 type 使用 optionalTypes 的更新导致
#4476

**Comment by z985690047** [comment]
我也遇到类似问题了

**Comment by shenjingnan** [comment]
已在1.8.6修复
