### ISSUE TITLE
[Bug Report] NavBar导航栏，如果放在自定义组件中 设置 fixed、placeholder 后 占位 无效

### ISSUE THREAD

**Issue by ghost** [youzan/vant-weapp#4499]
### 设备
开发者工具、安卓、ios

### VantWeapp 版本
1.8.4

### 基础库版本
2.19.4

### 请提供核心代码片段链接
https://github.com/youzan/vant-weapp/issues/4498

### 描述问题
NavBar 导航栏设置 fixed、placeholder 后 占位 无效。
当 fixed=true，placeholder =true后，下面的getRect方法返回的res ，高度是0
wx.nextTick(function () {
        utils_1.getRect(_this, '.van-nav-bar').then(function (res) {
          if (res && 'height' in res) {
            _this.setData({ height: res.height });
          }
        });
      });

**Comment by ghost** [comment]
在普通的页面中是可以的

**Comment by ssssshql** [comment]
同样遇到这个问题，非常难受，希望能够尽快解决

**Comment by landluck** [comment]
经过测试目前没有发现这个问题，如可以发现，可以提供复现小程序代码片段后重新打开 issue 或者 重新提交
