### ISSUE TITLE
DatetimePicker怎么设置格式为x月x日   时  分这种三列月日时分的格式啊？同时调整组件的宽度

### ISSUE THREAD

**Issue by ryanwlb** [youzan/vant-weapp#4500]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater?repo=VantWeapp

**Comment by shenjingnan** [comment]
https://vant-contrib.gitee.io/vant-weapp/#/datetime-picker#api

目前仅支持 `date` `time` `year-month` `datetime`
