### ISSUE TITLE
[Bug Report] Vant-weapp Calendar 日历组件 选择多个日期，设定minDate&maxDate默认选择未来的某天

### ISSUE THREAD

**Issue by 9mhz** [youzan/vant-weapp#4504]
![image](https://user-images.githubusercontent.com/64386741/133870675-fe460e20-c343-4719-9f65-69d40f1a3f2d.png)
![image](https://user-images.githubusercontent.com/64386741/133870687-326cbf0f-b0ab-4bfa-b68b-bea800faefcf.png)
![image](https://user-images.githubusercontent.com/64386741/133870702-9bdf4132-a6cc-426e-9cfb-95d43fbb24df.png)
会默认选择一个9月29日，很诡异，wxml在标签属性里删掉minDate就不会出现这个问题了。
我尝试了新建代码片段或新建项目，结果都安装不上Weapp,所以见谅没有按照流程提交issue，建议官方可以做一个【如何新建代码片段复现Vant-Weapp Bug】的教程，这样可以大幅提高issue的质量

**Comment by shenjingnan** [comment]
@LevanaS 可以新建个repo，然后把地址贴过来我看下

**Comment by johnsonwong666** [comment]
可以提供一个小程序代码片段过来吗

**Comment by johnsonwong666** [comment]
看你代码的意思应该是想设置最小日期在3天前，最大日期9天后，多选。 试了一下没有发现复现，如果还能复现的话请再发起一个issue，并带上小程序代码片段排查。
