### ISSUE TITLE
[Bug Report] van-uploader 使用 accept="media" pc端点击无效

### ISSUE THREAD

**Issue by bianleiming** [youzan/vant-weapp#4505]
### 设备
电脑

### VantWeapp 版本
1.8.5

### 基础库版本
2.16.1

### 请提供核心代码片段链接
https://gist.github.com/bianleiming/178cd9f5d6a970eeb027fadd0b8b53bd

### 描述问题
pc端小程序 van-uploader 使用 accept="media"，点击无效。app端和开发者工具都没问题。
pc端小程序基础库版本：2.16.1，pc微信版本：3.3.5.50

**Comment by shenjingnan** [comment]
尝试了下，好像是可以点击的，升级下vant-weapp或者开发者工具试试？

**Comment by bianleiming** [comment]
问题原因找到了，是pc端wx.chooseMedia的maxDuration属性不能设置超过10。我使用的时候设置的是30，所以失效了。这个属性在pc端保持默认值就可以了
