### ISSUE TITLE
uploader组件的previewSize属性，更新后不支持rpx，属性设置rpx会导致组件大小变为0

### ISSUE THREAD

**Issue by zmd1993** [youzan/vant-weapp#4506]
### 设备
所有设备

### VantWeapp 版本
1.8.5

### 基础库版本
所有版本

### 如果是 UI 问题，截图链接（多图回车分隔）

![截图](https://sm.ms/image/EGWvfVb1kTO2Xa5)

### 请提供核心代码片段链接
http://gitlab.wxbig.cn:8080/web-front/marketapplets

### 描述问题
uploader更新后privewSize设置rpx单位无效。望尽快修复，已经导致更新后线上项目不可用。

**Comment by shenjingnan** [comment]
已在1.8.6修复

**Comment by zmd1993** [comment]
checkbox也是这样，所以你们检查下，新增了属性的组件吧。
