### ISSUE TITLE
[Bug Report] skeleton组件异常

### ISSUE THREAD

**Issue by he-kuang** [youzan/vant-weapp#4511]
### 设备
H5

### VantWeapp 版本
1.8.6

### 基础库版本
1.8.5

### 请提供核心代码片段链接
https://github.com/youzan/vant-weapp/blob/dev/lib/skeleton/index.wxml

### 描述问题
在uniapp下skeleton组件中的小程序编译后的vue文件for循环异常 里面的key为item.index 但是数组内并无index导致报错 
顺便请教一下该库是如何将wxml转为vue的 谢谢大佬

**Comment by shenjingnan** [comment]
看起来这个需要去uniapp提问，vant-weapp是一个纯的小程序组件库

**Comment by he-kuang** [comment]
> 看起来需要去uniapp提问，vant-weapp是一个纯的小程序组件库

好吧我研究了一下确实是uniapp的转换问题
