### ISSUE TITLE
[Bug Report] Calendar 日历组件自定义特定日期的样式的API未公布给开发者

### ISSUE THREAD

**Issue by tinysimple** [youzan/vant-weapp#4512]
### 设备
全部设备（设备无关性）

### VantWeapp 版本
1.8.6

### 基础库版本
2.14.4

### 请提供核心代码片段链接
https://github.com/youzan/vant-weapp/blob/dev/lib/calendar/components/month/index.wxml

### 描述问题
项目需要对日历组件中特定日期进行自定义定制样式，查看官方Calendar组件中的所有API，皆无一特定支持更改特定日期的样式，于是本着二次开发的初衷去查看源码，发现源码是支持对特定日期进行自定义样式的，但是未在API中写出来，导致开发者根本不知道有这个功能，使很多开发者在选择日历组件库时就将该组件直接放弃，转而使用其他支持这一特性的组件。这个特定就是【Day数据结构】中可以设置【className】，通过formatter属性可以自定义 Day 对象的内容。这样就能满足对特定日期的自定义样式的需求了。
预期：希望官方尽快将此API属性补充进文档中以供开发者在进行组件选择的时候有更多的考虑，能够提高该组件的使用率。也能满足开发者的一些定制化需求，谢谢！

**Comment by shenjingnan** [comment]
已在1.9.1中更新
