### ISSUE TITLE
[Bug Report] tabs组件active为空字符("")， 默认激活位置不对

### ISSUE THREAD

**Issue by huzedong2015** [youzan/vant-weapp#4513]
### 设备
开发工具

### VantWeapp 版本
1.8.7

### 基础库版本
2.18.1

### 请提供核心代码片段链接
https://gist.github.com/huzedong2015/5b0d98c8efd2e00f454e7c272816d990

### 描述问题
按正常的话默认应该会激活第一个，但是没有

**Comment by huzedong2015** [comment]
```
<van-tabs active="" color="#bba087">
  <van-tab title="全部" name=""></van-tab>
  <van-tab title="卡券" name="a"></van-tab>
  <van-tab title="礼包" name="b"></van-tab>
</van-tabs>
```

**Comment by shenjingnan** [comment]
已在1.9.0中修复

**Comment by isfk** [comment]
> 已在1.9.0中修复
并没有修复啊，1.9.1 最新了，还是会出现 位置不对的现象
@nemo-shen 

<img width="250" alt="iShot2021-09-30 10 32 19" src="https://user-images.githubusercontent.com/70327450/135376270-2df3ef56-1cf8-4df5-ae13-68631182baa1.png">

```
{
  "dependencies": {
    "@vant/weapp": "^1.9.1"
  }
}
```

**Comment by javascripet** [comment]
并没修复啊...默认第一个是歪的
