### ISSUE TITLE
[Bug Report] search组件的输入框会穿透popup组件而获得焦点

### ISSUE THREAD

**Issue by yangmengyu2021** [youzan/vant-weapp#4516]
### 设备
iOS 15

### VantWeapp 版本
1.8.7

### 基础库版本
最近2个月来发布的所有基础库均可复现

### 如果是 UI 问题，截图链接（多图回车分隔）

![WX20210924-115313@2x.png](https://i.loli.net/2021/09/24/ghx5HD2amGSQJ1e.png)

![1632455613684.jpg](https://i.loli.net/2021/09/24/x3PR21NGgtrnydi.jpg)

### 请提供核心代码片段链接
https://sm.ms/image/ghx5HD2amGSQJ1e

### 描述问题
search组件的输入框会穿透popup组件而获得焦点。复现方法：将一个popup覆盖到一个search组件上，点击popup上面盖住输入框的位置，此时search可以获取到焦点，非常影响交互体验。

**Comment by yangmengyu2021** [comment]
![WX20210924-115313@2x.png](https://i.loli.net/2021/09/24/ghx5HD2amGSQJ1e.png)
![1632455613684.jpg](https://i.loli.net/2021/09/24/x3PR21NGgtrnydi.jpg)

**Comment by zxtlin** [comment]
应该是search组件的 input 组件是原生组件的问题引起的问题

**Comment by shenjingnan** [comment]
@yanglbme  看下历史issue

https://github.com/youzan/vant-weapp/issues/4420#issuecomment-905220176
