### ISSUE TITLE
最新代码里还有没改完的 .theme代码，导致build出错

### ISSUE THREAD

**Issue by caglance** [youzan/vant-weapp#4519]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater?repo=VantWeapp
![image](https://user-images.githubusercontent.com/28804065/134673007-4ebfd0ea-e3f5-4939-a577-90428cc48b91.png)

**Comment by chenjiahan** [comment]
感谢反馈，已修正
