### ISSUE TITLE
搜索组件无法获取值

### ISSUE THREAD

**Issue by Jinsheng-Peng** [youzan/vant-weapp#452]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**描述一下问题**
描述一下你遇到的问题，包括复现方式、导致结果

搜索组件无法获取值
页面代码
`  <van-search value="{{ value }}" placeholder="请输入店名关键词" use-action-slot 
  bind:change="onSearchfunction"
  bind:search="onSearchfunction">
    <view slot="action" bind:tap="onSearchfunction">地图搜索</view>
  </van-search>`

三个事件都用了用同一个函数，只有change可以正常取值。
slot的tap返回的是坐标，bind:search 返回的是空值
`onSearchfunction: function(event) {
    console.log(event);
}`

**截图**
如果是 UI 问题，请提供具体截图
![_20180822001349](https://user-images.githubusercontent.com/16498476/44414442-630dcf80-a5a0-11e8-9bae-c8edda0b7d10.png)

![_20180822003857](https://user-images.githubusercontent.com/16498476/44415777-d402b680-a5a3-11e8-9b3b-85fd7e803eb7.png)

直接在官方的demo做吧 也是同样的问题 获取不到值
![_20180822002003](https://user-images.githubusercontent.com/16498476/44415836-f5fc3900-a5a3-11e8-8452-da94e0a270b9.png)

**环境**
 - 设备: 
 - 基础库版本: 
 - Vant Weapp 版本:

**Comment by chenjiahan** [comment]
这个搜索按钮是用户自定义的，上面的事件也是和组件没有关联的

建议在 change 事件中保存 search 的 value

**Comment by matteao03** [comment]
我遇到了同样的问题

**Comment by kyle11235** [comment]
> 这个搜索按钮是用户自定义的，上面的事件也是和组件没有关联的
> 
> 建议在 change 事件中保存 search 的 value

change事件不被触发

**Comment by rex-zsd** [comment]
降低基础库版本到2.9.2及以下，开发者工具2.9.3有input事件不触发的bug。

**Comment by suminhohu** [comment]
> 降低基础库版本到2.9.2及以下，开发者工具2.9.3有input事件不触发的bug。

确实是这样 感谢~
