### ISSUE TITLE
[Bug Report] vant weapp Collapse 打开回收很缓慢?

### ISSUE THREAD

**Issue by a2291249652** [youzan/vant-weapp#4523]
### 设备
小米9

### VantWeapp 版本
1.8.7

### 基础库版本
2.19.5

### 请提供核心代码片段链接
https://developers.weixin.qq.com/s/5ZgRjBmZ7it6

### 描述问题
Collapse在开发者工具上没有问题，但是在真机调试上会有两三秒的打开或者关闭的延迟，在小米9，iphone12都有出现

**Comment by a2291249652** [comment]
VantWeapp 版本我给记错了是1.8.2

**Comment by shenjingnan** [comment]
已在v1.9.2中修复
