### ISSUE TITLE
[Bug Report] navBar设置为fixed时，挡住小程序默认的下拉刷新三个点

### ISSUE THREAD

**Issue by maYunLaoXi** [youzan/vant-weapp#4525]
### 设备
ios android

### VantWeapp 版本
1.8.3

### 基础库版本
2.15.0

### 如果是 UI 问题，截图链接（多图回车分隔）

![截图](https://gitee.com/maYunLaoXi/image/raw/master/macbook13/IMG_0600.jpg)

![截图](https://gitee.com/maYunLaoXi/image/raw/master/macbook13/IMG_0599.jpg)

### 请提供核心代码片段链接
https://gist.github.com/maYunLaoXi/3b2ebe78ccacb1255f06c3cdba82034c

### 描述问题
navBar设置为fixed时，挡住小程序默认的下拉刷新三个点，

**Comment by shenjingnan** [comment]
小程序使用 `position: fixed` 的原因，不是 `<NavBar />` 组件问题，你换成 `<view />` 组件自定义下样式同样的效果

**Comment by maYunLaoXi** [comment]
> 小程序使用 `position: fixed` 的原因，不是 `<NavBar />` 组件问题，你换成 `<view />` 组件自定义下样式同样的效果

看样子只能自己写下接刷新样式了
