### ISSUE TITLE
[Bug Report] van-popup和van-picker配合使用，van-popup不能关闭

### ISSUE THREAD

**Issue by Jidahan** [youzan/vant-weapp#4531]
### 设备
微信开发者工具和ios11，其他没测

### VantWeapp 版本
1.9.0

### 基础库版本
xxx

### 请提供核心代码片段链接
https://gist.github.com/Jidahan/78e5c704337c305d349e453ef40fe5e8

### 描述问题
van-popup和van-picker配合使用，van-popup不能关闭

**Comment by shenjingnan** [comment]
用提供的代码片段跑了下是正常的，检查下实际使用过程中是不是有问题？

**Comment by Jidahan** [comment]
我在模拟器和真机都试了 不能关闭 点击关闭会更新好几次状态

**Comment by Jidahan** [comment]
@nemo-shen

**Comment by Jidahan** [comment]
@nemo-shen https://gitee.com/v6688/wechat-mini 我建了个仓库 辛苦帮忙看一下
