### ISSUE TITLE
[Bug Report] 首页文档白屏

### ISSUE THREAD

**Issue by zhangjiahao93** [youzan/vant-weapp#4533]
### 设备
pc

### VantWeapp 版本
1.9.0

### 基础库版本
*

### 请提供核心代码片段链接
https://vant-contrib.gitee.io/vant-weapp/#/

### 描述问题
访问 https://vant-contrib.gitee.io/vant-weapp/#/
更换浏览器，清除缓存，使用代理访问均为白屏

**Comment by xuanyanwow** [comment]
同上，并且找不到文档仓库的地址，无法本地查看，，，，影响工作，唉

**Comment by shenjingnan** [comment]
已经恢复了哦，刷新下
