### ISSUE TITLE
[Bug Report] 请问文档仓库是否没有开源？

### ISSUE THREAD

**Issue by xuanyanwow** [youzan/vant-weapp#4534]
### 设备
0

### VantWeapp 版本
1.9.0

### 基础库版本
0

### 请提供核心代码片段链接
https://vant-contrib.gitee.io/vant-weapp/#/

### 描述问题
框架文档经常性出问题，gitee和github都无法访问正常，想知道是否有文档仓库，直接在本地构建文档系统，或者直接看文档的文件，不然没办法工作了。。。

**Comment by shenjingnan** [comment]
文档白屏问题已经恢复了~，另外如果需要本地构建文档的话可以clone项目，`yarn && yarn dev`
