### ISSUE TITLE
popup结合picker使用时响应延迟2-3s

### ISSUE THREAD

**Issue by CoolCola** [youzan/vant-weapp#4536]
![image](https://user-images.githubusercontent.com/13797082/135059333-b4d96511-7065-4414-bb28-f722c7e96ec4.png)

<van-popup :show="popupShow" position="bottom">
		<van-picker :columns="columns" :value-key="bindName" @cancel="onCancel" @confirm="onConfirm"
		 confirm-button-text="确认" cancel-button-text="取消" :show-toolbar="true" />
	</van-popup>

**Comment by shenjingnan** [comment]
延迟是什么意思？popup弹出picker之后picker选择时间有迟钝吗？

**Comment by shenjingnan** [comment]
https://user-images.githubusercontent.com/13480805/135399269-5cd951d4-5486-499e-aa54-62e6911fc760.mp4

测了下，没发现你说的延迟问题，怀疑是不是你自己项目中其他原因导致的
