### ISSUE TITLE
button 无法提交表单触发form 的bindsubmit事件

### ISSUE THREAD

**Issue by Jinsheng-Peng** [youzan/vant-weapp#454]
**你需要的功能是？**
button 无法提交表单触发form 的bindsubmit事件

表单提交是任何一个app都会用到的功能！

**你期望 API 是什么样的？**

实现原生的button formType即可。
 <button formType="submit">Submit</button>

**Comment by chenjiahan** [comment]
微信暂不支持，详见 https://developers.weixin.qq.com/miniprogram/dev/component/button.html 底部

**Comment by amou-zeng** [comment]
所以弃用vant-button
