### ISSUE TITLE
[Bug Report] van-dropdown-item组件 open事件绑定后会连续触发两次

### ISSUE THREAD

**Issue by WeibinZheng** [youzan/vant-weapp#4540]
### 设备
小程序开发工具1.05.2109101

### VantWeapp 版本
1.9.0

### 基础库版本
2.12.2

### 请提供核心代码片段链接
https://developers.weixin.qq.com/s/Cn2X5Gmj7UtA

### 描述问题
van-dropdown-item组件 open事件绑定后会连续触发两次
<van-dropdown-item popup-style="max-height: 500rpx;" value="{{ currentLeave }}" options="{{ levelOptions }}" bindopen="onLeaveOpen" />
bindopen事件会连续触发两次

**Comment by xchuan530** [comment]
遇到同样问题

**Comment by xchuan530** [comment]
遇到同样问题，解决了吗？

**Comment by suguoyao** [comment]
@xchuan530 我改用`bind:opened`就解决了

**Comment by landluck** [comment]
`v1.10.11` 已修复
