### ISSUE TITLE
h5使用field会报<include>标签警告,小程序没问题，这是为啥？

### ISSUE THREAD

**Issue by Joan428** [youzan/vant-weapp#4543]
![image](https://user-images.githubusercontent.com/48681179/135248123-8a80829d-a9e3-45ee-a860-9095efa17e7c.png)

**Comment by shenjingnan** [comment]
这个是vant-weapp

**Comment by Joan428** [comment]
> 这个是vant-weapp

所以h5是不能用的吗？因为我在网上有看过说h5也能使用微信小程序组件的文章，以为h5也可以使用
