### ISSUE TITLE
[Bug Report] van-circle组件穿透了van-popup组件

### ISSUE THREAD

**Issue by mengxin-FE** [youzan/vant-weapp#4544]
### 设备
iOS&Android

### VantWeapp 版本
1.9.1

### 基础库版本
2.19.4

### 请提供核心代码片段链接
https://github.com/youzan/vant-weapp/issues/3112

### 描述问题
van-circle组件 与van-popup组件同时使用时，van-circle会透过van-popup组件，即全屏遮罩层无法挡住van-circle组件

**Comment by shenjingnan** [comment]
历史issue已经回答了

**Comment by answer33** [comment]
设置属性 type="2d" 支持同层渲染
