### ISSUE TITLE
van-picker default-index 失效

### ISSUE THREAD

**Issue by s2mh** [youzan/vant-weapp#4546]
一个页面中，有两个地方使用了 van-picker。第一次打开一个 picker 时，default-index 有起作用。在另一个地方打开 picker 后 default-index 失效。

``` css
<van-action-sheet show="{{showSelections}}" bind:click-overlay="onSelectCancel">
  <van-picker columns="{{selections}}" bind:cancel="onSelectCancel" bind:confirm="onSelectConfirm" 
  visible-item-count="{{visibleSelectionCount}}" default-index="{{defaultSelectionIndex}}" show-toolbar />
</van-action-sheet>
```

https://user-images.githubusercontent.com/7028526/135416098-47df6710-de65-481c-b8da-597b704c0791.mp4

**Comment by shenjingnan** [comment]
感觉像是业务代码问题，检查下自己的代码是否正常工作？

**Comment by s2mh** [comment]
> 感觉像是业务代码问题，检查下自己的代码是否正常工作？

default-index 只在 create 时生效，能不能支持在显示的时候也设置 index？多个数据源共用一个组件的是需要用到
![微信截图_20220115102802](https://user-images.githubusercontent.com/7028526/149605575-de4cbe29-f6c0-43c9-a233-e553612afc9f.png)

**Comment by kingdsa** [comment]
试试在van-action-sheet 上加一个wx:if  wx:if的条件和show的条件一样
