### ISSUE TITLE
关于 van-dropdown-item 高度的问题

### ISSUE THREAD

**Issue by s2mh** [youzan/vant-weapp#4547]
页面使用了自定义的 tabbar，van-dropdown-item 超出屏幕高度的情况下，底部会被 tabbar 遮住。
http://vant-contrib.gitee.io/vant-issue-generater?repo=VantWeapp
![微信截图_20210930163459](https://user-images.githubusercontent.com/7028526/135419038-93fbb004-89b9-4fca-b004-af40c46343df.png)

**Comment by s2mh** [comment]
``` css
<van-dropdown-menu class="topBar" active-color="var(--blue)" z-index="{{0}}">
  <van-dropdown-item id="item" wx:for="{{itemGroup}}" wx:for-index="groupIndex" wx:for-item="group" wx:if="{{group.filterable}}" title="{{group.title}}">
   </van-dropdown-item>
</van-dropdown-menu>
```

**Comment by yuyuko233** [comment]
我的tabbar也是会遮住页面内容

**Comment by landluck** [comment]
`v1.10.14` 版本新增 `safe-area-tab-bar` 属性支持在自定义 tabbar 时防止被覆盖

**Comment by GF-Huang** [comment]
我想盖住原生 tabbar 怎么做？`safe-area-tab-bar="false"` 无效。

![image](https://github.com/user-attachments/assets/e6232be7-f711-4c3c-88ed-8fcdd64aff65)


```xml
<van-cell title="展示弹出层" is-link bind:click="showPopup" />
<van-popup show="{{show}}" safe-area-tab-bar="false" position="bottom" bind:close="onClose">
  内容
</van-popup>
```
