### ISSUE TITLE
van-card组件，内容能不能默认设置为垂直居中对齐？

### ISSUE THREAD

**Issue by lihengdao** [youzan/vant-weapp#4548]
[https://iknow-pic.cdn.bcebos.com/242dd42a2834349b9a6ff215dbea15ce36d3be31](url)
如图，你们可不可以默认设置为垂直居中对齐？

**Comment by shenjingnan** [comment]
`<VanCard />`是商品卡片组件，从左至右展示商品图片和信息应该是符合预期的。如果有必要，一些外部样式类也许能帮助到你
