### ISSUE TITLE
[Bug Report] DropdownMenu的下拉菜单滑动时与顶部菜单分离

### ISSUE THREAD

**Issue by bytrix** [youzan/vant-weapp#4552]
### 设备
微信小程序

### VantWeapp 版本
1.9.1

### 基础库版本
2.20.0

### 如果是 UI 问题，截图链接（多图回车分隔）

![截图](https://z3.ax1x.com/2021/10/06/4xmduq.png)

![截图](https://sm.ms/image/TsNkJ7PMXmf35I8)

### 请提供核心代码片段链接
https://gitee.com/bytrix/vant-dropdown-bug

### 描述问题
DropdownMenu的下拉菜单滑动时与顶部菜单分离，十分紧急，请尽快回复！！！！！！！！！

**Comment by zxtlin** [comment]
我也碰到了有时候会分离，但大部分情况是正常的

**Comment by bytrix** [comment]
> 我也碰到了有时候会分离，但大部分情况是正常的

我不是有时候，是每次都分离，解决方法是用一个透明的div阻止事件冒泡

**Comment by landluck** [comment]
DropdownMenu 在弹出的时候会覆盖菜单下面的所有区域，不会覆盖整个屏幕，所以菜单所在的区域是可以随意滚动的，而组件是无法阻止未覆盖的区域进行滚动的，建议弹出下拉菜单是可以阻止页面滚动，例如给外层 view 标签添加 `catch:touchmove="noop"` 或者 给外层 view 添加 `overflow:hidden`
