### ISSUE TITLE
[Bug Report] 关于van-field中type为textarea后样式出问题

### ISSUE THREAD

**Issue by xiaobaogeit** [youzan/vant-weapp#4553]
### 设备
三星Galaxy S9

### VantWeapp 版本
1.9.1

### 基础库版本
2.19.6

### 如果是 UI 问题，截图链接（多图回车分隔）

![截图](https://i.loli.net/2021/10/06/5EAGVfCUPOWtsTJ.jpg)

![截图](https://i.loli.net/2021/10/06/2Labre4fjnU5gRN.jpg)

### 请提供核心代码片段链接
https://gist.github.com/xiaobaogeit/b0167eaee5497f527af58521c6cf2833

### 描述问题
其他前提：
1. `van-field`中的`type`为`textarea`
2. ~~`van-field`中有`show-word-limit`属性~~
3. 本问题是结合使用`van-action-sheet`才发现的
4. 点击预览或者体验版都会出现
5. 如果真机调试模式，请不要使用`V2`版本，此只能再`V1`版本看出问题

**Comment by zhanglong12138** [comment]
textarea 是原生组件 显示在最上层了 如果换 cover-view 用的多了 又会造成卡顿
当有浮层或遮罩的时候 开发者可以自行使用 hidden 隐藏原生组件 诸如上面的 textarea 
这块工程标准化还是挺困难的 需要结合业务去搞逻辑

**Comment by shenjingnan** [comment]
原生组件的层级问题，input可以通过always-embed解决，但是textarea官方没有提供
