### ISSUE TITLE
[Bug Report] van-field 不支持原生always-embed属性

### ISSUE THREAD

**Issue by MakeBetterMe** [youzan/vant-weapp#4554]
### 设备
iPhone

### VantWeapp 版本
1.9.1

### 基础库版本
2.16.1

### 请提供核心代码片段链接
https://gist.github.com/MakeBetterMe/dd541897c3498b5b871c130d4eb789b0

### 描述问题
1.因为不支持原生always-embed属性，如果表单项过长，滚动的时候，输入框文字会发生错位，同时滚动会偶尔卡死
2.在多个输入框之间来回切换的话，也会导致键盘莫名其妙消失
3.我直接在源码处加入always-embed属性，就好使了，还是希望vant本身扩展出这个属性接收

**Comment by shenjingnan** [comment]
v1.9.2已支持
