### ISSUE TITLE
van-calendar有没有要优化一下的，如果选的时间范围较长，加载很慢

### ISSUE THREAD

**Issue by CoolCola** [youzan/vant-weapp#4560]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater?repo=VantWeapp

**Comment by pandamo** [comment]
个人建议：
minDate和maxDate的默认值都设置成当前时间戳：
 minDate:new Date().getTime(),
 maxDate:new Date().getTime(),
 
在点击显示日历的事件内，根据自己需要重新设置minDate和 maxDate，这样对页面加载时间有帮助

**Comment by lavender1026** [comment]
同样也遇到一样的问题，最小时间一年内最大时间当前时间，进页面能卡3s以上。。。

**Comment by Sylvia-00** [comment]
> 个人建议： minDate和maxDate的默认值都设置成当前时间戳： minDate:new Date().getTime(), maxDate:new Date().getTime(),
> 
> 在点击显示日历的事件内，根据自己需要重新设置minDate和 maxDate，这样对页面加载时间有帮助

试了没用

**Comment by Chevsky-G** [comment]
如果年份差距很大 比如现在是2024 我要选择1986这种差距很大的日期范围要滑很久，有没有什么别的办法可以快速切换年份
