### ISSUE TITLE
Page中使用van-index-bar，滚动页面时无法触发onPageScroll事件

### ISSUE THREAD

**Issue by MrQiYin** [youzan/vant-weapp#4561]
没找到其他朋友有这个问题的，仅分享解决办法以及想法

van-index-bar中mixins有混入一个pageScrollMixin，pageScrollMixin是手动赋值了Page的onPageScroll事件来监听页面的滚动，但是如果Page未定义onPageScroll方法，那么页面滚动时pageScrollMixin的onPageScroll方法不会被触发，导致吸顶的锚点永远是第一个，猜测可能是小程序框架在页面load时保存了未定义的onPageScroll，于是直接写了一个空的onPageScroll方法后van-index-bar正常了。

**Comment by shenjingnan** [comment]
感谢分享
