### ISSUE TITLE
这个针对微信小程序的ui，为什么没有用rpx单位呢？

### ISSUE THREAD

**Issue by makk24** [youzan/vant-weapp#4562]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater?repo=VantWeapp

**Comment by shenjingnan** [comment]
可以通过构建工具，在打包过程中自行处理。具体处理方法可使用搜索引擎获取
