### ISSUE TITLE
[Bug Report] van-grid-item使用use-slot后，badge属性失效

### ISSUE THREAD

**Issue by XinwenCheng** [youzan/vant-weapp#4564]
### 设备
iOS、Android

### VantWeapp 版本
1.9.1

### 基础库版本
2.17.3

### 请提供核心代码片段链接
http://no.com

### 描述问题
```
<van-grid-item badge="99" use-slot>
  <image src="./images/icon_task_today.png" class="taskIcon" />
  <span>今日数量</span>
</van-grid-item>
```

van-grid-item使用use-slot后，设置badge也显示不出来。请问，这种情况下，应该如何设置badge呢？

**Comment by shenjingnan** [comment]
如果你使用了slot来实现 `GridItem` 那么就需要自己实现 `badge` 了。因为 `badge` 是 `GridItem` 的一个 `props`，如果需要自定义，则组件会将所有UI交由开发者自行实现。你可以参考源码自行实现 `badge`
