### ISSUE TITLE
[Bug Report] van-nav-bar 底部白线 :border="false" 设置无效

### ISSUE THREAD

**Issue by Septillions** [youzan/vant-weapp#4570]
### 设备
微信小程序

### VantWeapp 版本
1.9.1

### 基础库版本
2.20.0

### 如果是 UI 问题，截图链接（多图回车分隔）

![截图](https://i.loli.net/2021/10/19/r2JG7OcIWxDsZwp.png)

### 请提供核心代码片段链接
https://gist.github.com/Septillions/e309edfd2a4537ecdb1ef1c3a6a8629e

### 描述问题
当背景设为透明时，底部会出现一条白线，设置 border 也无效

**Comment by shenjingnan** [comment]
border="{{ false }}"
