### ISSUE TITLE
[Bug Report] van-tabs type="card" 数量超过5个，样式异常

### ISSUE THREAD

**Issue by yishen-yishen** [youzan/vant-weapp#4573]
### 设备
微信小程序 | oneplus 8t

### VantWeapp 版本
1.9.1

### 基础库版本
2.20.0

### 如果是 UI 问题，截图链接（多图回车分隔）

![截图](https://i.loli.net/2021/10/21/5CY3njkQb7a8GSA.png)

![截图](https://i.loli.net/2021/10/21/AIJBaCye1FzRSt5.png)

### 请提供核心代码片段链接
https://developers.weixin.qq.com/s/tIhkVdmb7vuo

### 描述问题
van-tabs type="card" 数量超过5个，样式异常

**Comment by shenjingnan** [comment]
已在v1.9.2中修复

**Comment by yishen-yishen** [comment]
> 已在v1.9.2中修复

感谢！

**Comment by zhihuifanqiechaodan** [comment]
1.92版本修复完成还有其他bug，如果在第一个tab左滑，就不能够在右滑动了。 如果在最后一个tab继续右滑，就不能左滑了。
