### ISSUE TITLE
tabs的lazy-render属性是否无效，

### ISSUE THREAD

**Issue by wekerSnail** [youzan/vant-weapp#4574]
### 设备
开发工具

### VantWeapp 版本
1.9.1

### 基础库版本
2.20

### 请提供核心代码片段链接
https://gitee.com/vant-contrib/vant-weapp/blob/dev/packages/tabs/index.ts

### 描述问题
使用lazy-render属性之后没有效果，看文档使用默认的配置应该也是默认开启的，但是不管配不配置，组件内容都会一次全部加载，查看源码中也未看到有相关的实现，想问一下是目前还不具备该功能吗

**Comment by mouday** [comment]
+1，也想知道这个需要怎么解决

**Comment by vlay1314** [comment]
根本就没有实现这个功能，VUE的版本就有，小程序的就有没有
