### ISSUE TITLE
vant 支持 字节小程序吗

### ISSUE THREAD

**Issue by wangsijian555** [youzan/vant-weapp#4577]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater?repo=VantWeapp

**Comment by chenjiahan** [comment]
不支持喔

**Comment by Rabbitzzc** [comment]
构建后使用相对路径引入
