### ISSUE TITLE
[Bug Report] toast的type指定为html无法渲染成html

### ISSUE THREAD

**Issue by evestorm** [youzan/vant-weapp#4578]
### 设备
模拟器-所有

### VantWeapp 版本
1.9.1

### 基础库版本
2.20.0

### 如果是 UI 问题，截图链接（多图回车分隔）

![截图](https://raw.githubusercontent.com/evestorm/show/master/WX20211025-183109%402x.png)

### 请提供核心代码片段链接
https://gist.github.com/evestorm/5552f5dd0fe223b8dcfc15e7d7dd1b3d

### 描述问题
在使用 vant 的 webapp 版本时发现一个bug，当我使用 toast 组件想要把内容显示成 html 类型时，会展示成文本。而我的预期是展示html

**Comment by shenjingnan** [comment]
将会在下个版本支持

**Comment by shenjingnan** [comment]
v1.9.2已支持

**Comment by evestorm** [comment]
> v1.9.2已支持

awesome~ 赞一个！
