### ISSUE TITLE
[Bug Report] 小程序使用tabbar切换时会闪烁!

### ISSUE THREAD

**Issue by wudachen123** [youzan/vant-weapp#4580]
### 设备
小米civi

### VantWeapp 版本
1.9.1

### 基础库版本
v1.9.1

### 请提供核心代码片段链接
https://youzan.github.io/vant-weapp/#/tabbar

### 描述问题
就是你们官方的案例，直接拿过来，切换tabbar时会闪烁！和小程序文档里的自定义tabbar遇到的同样的问题! 怎么解决啊！！！！

**Comment by shenjingnan** [comment]
tabbar本质上就是点击之后改变active状态改变颜色，没理解闪烁是什么意思？

**Comment by wi1wei** [comment]
可能是switchTab的原因？
https://user-images.githubusercontent.com/22729817/139616590-db9703a6-782a-4046-9f57-5b302e1174b2.mp4

**Comment by shenjingnan** [comment]
@wi1wei 看你的视频，应该是点击之后将整个页面重新加载成另外页面了，并不是tabbar导致的，你去掉tabbar用API形式切换页面应该也是如此

**Comment by wudachen123** [comment]
那该怎么解决呢？我确实是使用了tabbar，并且产生了不友好的用户体验，这对于我和我的团队来说是一件很糟糕的事，那么我们该怎么解决掉这个问题呢?




NO&nbsp;MORNING
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "youzan/vant-weapp"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月4日(星期四) 下午2:19
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [youzan/vant-weapp] [Bug Report] 小程序使用tabbar切换时会闪烁! (Issue #4580)





 
@wi1wei 看你的视频，应该是点击之后将整个页面重新加载成另外页面了，并不是tabbar导致的，你去掉tabbar用API形式切换页面应该也是如此
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
