### ISSUE TITLE
PX2RPX

### ISSUE THREAD

**Issue by diaoseo** [youzan/vant-weapp#4585]
组件是为了微信而创建的，然而书写的长度单位居然是PX，我看到了很多其他使用者在这里提问。为何没有RPX的版本。有些回答是需要使用者自身去使用NPM工具来修改代码再重新打包。可是作为一个实用工具，使用不就是为了方便吗？如果我还需要学会如何转换成RPX属性才能使用。岂不是本末倒置了，大多数人使用自定义组件是为了方便自己(减少框架代码的复写或编写)，我们知道RPX会导致某些情况下显示模糊，RPX设计出来不就是为了适配一切设备吗？作为开发者，模糊和位置不对对于某些情况来说，模糊有时候不是什么大问题，适配一切屏幕所需要的取舍仅仅是可能会变模糊。综上所述，烦请能否同步编译一个rpx版本。
github使用不多，能力有限，再提个建议。作为一个我千挑万选之中选中的一个组件库，看了不少，vant算是做的不错的一个，建议做出黑暗模式。众所周知OLED屏幕显示深色内容能比显示亮色内容更省电，屏幕才是移动设备的用电大户。使用黑暗模式后能为节能减排所作出的巨大贡献，就在弹指之间。感谢提供vant，这个组件库很好用。我会一直用下去，待我有能力之时，一定会来支持这个项目的建设。

**Comment by shenjingnan** [comment]
通过一些编译工具你可以将 `px` 转换成你任意想要的 计算单位，而组件库因其通用性，并不会为其特别转换某类计算单位，该类问题有很多重复issue，你可以先看下历史issue
