### ISSUE TITLE
【求助】dropdownmenu 如何固定在页面头部

### ISSUE THREAD

**Issue by dany1** [youzan/vant-weapp#4592]
前端小白想请教一下dropdownmenu如何固定在页面的头部？现在dropdownmenu会随着页面一起滑动

<van-dropdown-menu  active-color="#1989fa" >
  <van-dropdown-item value="{{ rangeValue }}" options="{{ rangeOption }}" bind:change="onRangeChange" />
  <van-dropdown-item value="{{ finishValue }}" options="{{ finishOption }}" bind:change="onFinishChange" />
</van-dropdown-menu>

<block wx:for="{{list}}" wx:key="id">
    <van-cell-group inset custom-class="success__cell-group">
      <van-cell title="{{item.roomName}}" use-label-slot="{{true}}">
        <view slot="label">
          <view class="success__user-info">
            <text>{{item.applyUserName}}</text>
            <text id="{{item.id}}" data-item="{{item.applyUserMobile}}" bindtap="onPhoneClick" class="success__mobile">{{item.applyUserMobile}}{{ '\n' }}</text>
          </view>
        </view>
      </van-cell>
    </van-cell-group>
</block>

**Comment by shenjingnan** [comment]
`position: fixed`
