### ISSUE TITLE
[Bug Report] 快速上手教程错误（2021-11-1 22:48分亲测）

### ISSUE THREAD

**Issue by hugselina2019** [youzan/vant-weapp#4593]
### 设备 / 浏览器
win10 64 / chrome

### Vant 版本
2.12.31

### Vue 版本
3.2.20

### 重现链接
<a href="https://youzan.github.io/vant-weapp/#/quickstart" target="_blank">https://youzan.github.io/vant-weapp/#/quickstart</a>

### 描述问题
1、用开发者工具新建小程序项目打开官方文档 快速上手 根据步骤 进行第一步、第二步、第三步</br>
2、第四步开始报错 一直找不到@vant/weapp/package.json, 很奇怪？ 明明就在那里啊？， 于是一通百度， 各种方法都试了一遍 未果</br>
3、删掉所有 重新开始 OK Go: npm init ; npm i @vant/weapp -S --production ; 到这里 应该是第三步了 去修改project.config.json。 这时灵机一动 先去npm构建， 然后修改project.config.json。 成功了！ 后续引入van-button成功。。。。。。就。。 很迷？</br>

**（然后第二次证明不是步骤顺序的问题，是目录结构和安装命令的问题，详情请看下面的回复，已破案）**

4、now 为了引入vant 引了一个多小时。。。。亲测结果 快速上手的第三步 第四步 顺序应该颠倒一下

**Comment by j787701730** [comment]
@hugselina2019 👍.  迷. 之前折腾两次, 放弃了.

**Comment by shenjingnan** [comment]
@hugselina2019 @j787701730 我录了个视频，好像没发现教程的步骤有什么问题？前四步逻辑应该是正确的，要改了配置之后你构建npm才可以呀

链接: https://pan.baidu.com/s/1zDwBYOVS0Y5jdvngVLVkBQ 提取码: qv7v

**Comment by hugselina2019** [comment]
> @hugselina2019 @j787701730 我录了个视频，好像没发现教程的步骤有什么问题？前四步逻辑应该是正确的，要改了配置之后你构建npm才可以呀
> 
> 链接: https://pan.baidu.com/s/1zDwBYOVS0Y5jdvngVLVkBQ 提取码: qv7v

十分感谢老哥的SP，我去下载了也仔细看了，发现老哥C的是云开发项目。我是没有使用云开发。问题大概找到了 我这就去C两个项目对比一下目录结构，十分感谢老哥。 顺带羡慕下mac /捂脸

**Comment by hugselina2019** [comment]
> @hugselina2019 @j787701730 我录了个视频，好像没发现教程的步骤有什么问题？前四步逻辑应该是正确的，要改了配置之后你构建npm才可以呀
> 
> 链接: https://pan.baidu.com/s/1zDwBYOVS0Y5jdvngVLVkBQ 提取码: qv7v

首先我试了一下云开发， 然后npm xxx 进行123, 4。 到第四步构建 依旧报错了 一脸懵逼， 然后回看了一下大哥的SP 发现大哥用的是yarn... 然后我删掉了node_modules 重新使用yarn命令安装， 然后构建， 然后成功了。。。发现yarn后平级多了一个package.json
![image](https://user-images.githubusercontent.com/20763416/142369026-99967839-5f71-41bf-a1db-e7d69da03a41.png)

我这就试一下不用云开发yarn安装， 如果可以 那就是它的npm包少了个package.json .... 这也太难受了

然后我回来了。
npm构建提示 如下
![image](https://user-images.githubusercontent.com/20763416/142369691-615792c3-f486-401a-9380-13481b1af807.png)
对比后发现两个目录构造确实不同 .而且npm安装后没有package.json ，yarn安装后是有的
所以破案了，
它需要使用云开发（要那个miniprograme的目录） + yarn安装(要根目录的package.json)
希望对后面的小伙伴有用吧

**Comment by hugselina2019** [comment]
> @hugselina2019 👍. 迷. 之前折腾两次, 放弃了.

破案了 请看相关回复

**Comment by hugselina2019** [comment]
这是最终不使用/使用云开发 的项目目录对比图，
![image](https://user-images.githubusercontent.com/20763416/142370058-ab41b6f7-6f27-4947-a845-40add7853d4a.png)

最后删减到如下图可以正常运行 **无报错 无warning,** 由此可以得出结论 即使不使用云开发 不使用yarn也是可以达成目的的。
即按照下图来进行目录改动
![image](https://user-images.githubusercontent.com/20763416/142376744-65450c7b-093a-42e3-94ed-768e243e7ed9.png)
### 最终结论
![image](https://user-images.githubusercontent.com/20763416/142377335-9b872d6b-0d6e-4ce3-a9d6-2d084576067b.png)
