### ISSUE TITLE
自定义样式类 不能覆盖组件的样式类 而是被组件类覆盖

### ISSUE THREAD

**Issue by zhanglong12138** [youzan/vant-weapp#4594]
例如：DropdownMenu 组件

对子组件 van-dropdown-item 设置样式类 title-class 

在控制台发现 class 的加载顺序 是开发者加的自定义类加载在前 组件样式类加载在后

![image](https://user-images.githubusercontent.com/20243414/140017934-6a7c7162-83a7-4504-8c5a-a3969a6aaf82.png)

其中的 titleclass 是开发者自定义类 希望可以覆盖组件原有的样式 虽然可以用 important 关键词解决 但不是最佳解决方案

**Comment by marren06** [comment]
+1

**Comment by marren06** [comment]
> 例如：DropdownMenu 组件
> 
> 对子组件 van-dropdown-item 设置样式类 title-class
> 
> 在控制台发现 class 的加载顺序 是开发者加的自定义类加载在前 组件样式类加载在后
> 
> ![image](https://user-images.githubusercontent.com/20243414/140017934-6a7c7162-83a7-4504-8c5a-a3969a6aaf82.png)
> 
> 其中的 titleclass 是开发者自定义类 希望可以覆盖组件原有的样式 虽然可以用 important 关键词解决 但不是最佳解决方案

请问下 
![image](https://user-images.githubusercontent.com/17778482/144390595-5b9e1b5c-d752-4fdb-90cb-f6a7499f4e87.png)
1 默认字体样式怎么修改，API没暴露API ，样式覆盖修改不起作用
2.选项默认cell横线怎么去除  API没暴露API ，样式覆盖修改不起作用

**Comment by landluck** [comment]
titleClass 这个设计有点问题，今天下午会发布 v1.10.7，可以使用下面图中所示自定义样式类实现需求
![image](https://user-images.githubusercontent.com/27060081/202606342-398f77bc-f6e4-47ad-9e34-925173325c6f.png)

**Comment by landluck** [comment]
`v1.10.7` 已发布
