### ISSUE TITLE
[Feature Request] 小程序隐私保护指引审核不过，提示有实际未使用的权限

### ISSUE THREAD

**Issue by xinoski** [youzan/vant-weapp#4596]
### 这个功能解决了什么问题
小程序项目，使用了vant Weapp组件，用于实现某些弹窗样式和功能。
但小程序提交审核时，新增的隐私保护指引中，检测出小程序使用了头像/昵称、图片、文件读取等权限。我们的小程序实际并为使用，经核实可能是由于引入vant组件调用引起。

### 建议的API是什么样的
可否提供关闭vant组件调用某些权限的方法。避免小程序实际功能并为使用的权限，被微信检测到。

**Comment by shenjingnan** [comment]
跟vant-weapp应该没关系，官方小程序走发布流程没出现类似问题，建议检查自己的项目是否合理

**Comment by fzudust** [comment]
我也遇到这个问题了，搜了代码，只有vant组件里用到了

**Comment by hzyhbk** [comment]
我也遇到这个问题了，搜了代码，只有vant组件里用到了

**Comment by hzyhbk** [comment]
照着这个[文档](https://developers.weixin.qq.com/miniprogram/dev/framework/user-privacy/miniprogram-intro.html)，搜索`miniprogram_npm/@vant/weapp` 里面用到的所有接口，把代码删了就行

**Comment by chenjiahan** [comment]
@nemo-shen 这个问题可以再验证下哈

**Comment by shenjingnan** [comment]
@chenjiahan 这issue修不动了。。。小程序的隐私保护指引好像是说获取用户信息、分享、上传文件都算，如果组件库层面去解决这个问题的话，那我们得把 ActionSheet涉及到获取用户信息的和分享那块的代码阉割掉，然后上传组件下掉。要么就是开发者自己去填写微信小程序平台发布时候的指引。。。

**Comment by fzudust** [comment]
> @chenjiahan 这issue修不动了。。。小程序的隐私保护指引好像是说获取用户信息、分享、上传文件都算，如果组件库层面去解决这个问题的话，那我们得把 ActionSheet涉及到获取用户信息的和分享那块的代码阉割掉，然后上传组件下掉。要么就是开发者自己去填写微信小程序平台发布时候的指引。。。

能不能做成组件和功能按需加载呢？

**Comment by shenjingnan** [comment]
已在文档中增加隐私保护相关说明

自2021年11月1日起[《个人信息保护法》](https://baike.baidu.com/item/%E4%B8%AA%E4%BA%BA%E4%BF%A1%E6%81%AF%E4%BF%9D%E6%8A%A4%E6%B3%95/8343360?fr=aladdin)正式实施，微信根据有关部门的相关要求增强了对用户隐私信息的保护。
因此开发者在小程序发布时，需根据微信[《用户隐私保护指引填写说明》](https://developers.weixin.qq.com/miniprogram/dev/framework/user-privacy)自行填写完整信息

**Comment by peiili** [comment]
> 跟vant-weapp应该没关系，官方小程序走发布流程没出现类似问题，建议检查自己的项目是否合理

是action-sheet中有调用用户信息的行为，但是这个组件可能在当前项目中没有用过
