### ISSUE TITLE
van-uploader微信小程序黑边问题

### ISSUE THREAD

**Issue by KangLinDDD** [youzan/vant-weapp#4601]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater?repo=VantWeapp
目前用van-uploader上传视频时会有小黑边，加上objectFit="cover" 就可以了
![image](https://user-images.githubusercontent.com/38040659/140328489-d7aa3f9c-8d5b-48d7-ade6-490daa712a5b.png)
感谢vant团队

**Comment by KangLinDDD** [comment]
目前用的vant版本是1.9.1 video标签还没有加这个熟悉，图中是我自己加的，感谢

**Comment by KangLinDDD** [comment]
而且微信小程序的vant教程里面，van-field没有写error-message的对齐方式，扣源码才发现errorMessageAlign ，文档能更新一下吗感谢

**Comment by johnsonwong666** [comment]
你是在微信小程序里面内嵌h5使用vant的video组件吗？ 可以提供一段复现代码吗？

**Comment by landluck** [comment]
`v1.10.21` 已支持 videoFit 属性
