### ISSUE TITLE
使用你们这个库貌似必须把app.json里面的style属性改为v1啊？如果是v2的话，有些button控件就会出现样式错乱情况

### ISSUE THREAD

**Issue by yaochangliang159** [youzan/vant-weapp#4604]
比如demo项目里的以下代码：
  <van-cell-group>
    <van-field
      value="{{ sms }}"
      center
      clearable
      label="短信验证码"
      placeholder="请输入短信验证码"
      use-button-slot
      border="{{ false }}"
    >
      <van-button slot="button" size="small" type="primary" custom-class="button">发送验证码</van-button>
    </van-field>
  </van-cell-group>
在style为v2的情况下，button样式乱了，直接占了屏幕一半的距离，如果在style为v1的情况下，样式是合适的。
我的问题是：既然微信小程序新建项目默认有style为v2，微信官方这么做有他们的想法，那么是不是可以理解为这个组件库没有兼容微信小程序的更新呢？

**Comment by yaochangliang159** [comment]
出现样式错乱的代码如下：
`  <van-cell-group>
    <van-field
      value="{{ sms }}"
      center
      clearable
      label="短信验证码"
      placeholder="请输入短信验证码"
      use-button-slot
      border="{{ false }}"
    >
      <van-button slot="button" size="small" type="primary" custom-class="button">发送验证码</van-button>
    </van-field>
  </van-cell-group>`

**Comment by yoyo837** [comment]
![image](https://user-images.githubusercontent.com/6134547/143841165-302d6e69-b79e-4c5a-a6cb-80111ac9c512.png)

**Comment by yoyo837** [comment]
还没兼容v2

**Comment by yoyo837** [comment]
我路过的, 不是维护者, 不要着急关嘛.
