### ISSUE TITLE
[Bug Report] van-toast 样式异常问题

### ISSUE THREAD

**Issue by maybeee19** [youzan/vant-weapp#4611]
### 设备
微信开发者工具及手机

### VantWeapp 版本
1.9.2

### 基础库版本
2.20.2

### 如果是 UI 问题，截图链接（多图回车分隔）

![截图](https://i.loli.net/2021/11/11/l17UPNWV8DGLqko.png)

### 请提供核心代码片段链接
https://developers.weixin.qq.com/s/KI8r0Jmy7nu3

### 描述问题
操作路径
1. npm i @vant/weapp -S --production
2. 构建NPM
微信开发者工具代码片段: https://developers.weixin.qq.com/s/KI8r0Jmy7nu3

**Comment by shenjingnan** [comment]
使用1.10.0
