### ISSUE TITLE
vant-weapp关于toast样式的问题。

### ISSUE THREAD

**Issue by fyb19920630** [youzan/vant-weapp#4612]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater?repo=VantWeapp
![1636695294(1)](https://user-images.githubusercontent.com/37892034/141415508-8545ef1b-6686-4070-b08f-cff8c1864e0f.jpg)
跟以前的样式相比较。确实不好看，希望可以改回以前的版本

**Comment by shenjingnan** [comment]
1.10.0已修复
