### ISSUE TITLE
小程序ide的基础库版本 2.20.1 起，所有样式都丢失（wxs执行异常）

### ISSUE THREAD

**Issue by wubinsheng2017** [youzan/vant-weapp#4614]
2.20.1版本开始，发现vant的样式全部丢失。
调查后发现，是项目的 app.json 中”按需注入“的属性导致：
"lazyCodeLoading": "requiredComponents"

表现是，在源码 wxs/bem.wxs 中添加console.log之后，
只有”WXSRT:join cell van-cell“日志输出，
没有”[WXS Runtime info] join cell van-cell “日志输出

将其属性lazyCodeLoading去除后，问题就解决了。
但根本原因还不是很清楚，大家一起讨论下？

**Comment by 1257041477** [comment]
按照博主的设置，已解决问题

**Comment by ghost** [comment]
顶楼主 问题解决

**Comment by brownfoxsir** [comment]
问题解决

**Comment by wubinsheng2017** [comment]
经过验证，新版小程序ide无此问题

**Comment by brownfoxsir** [comment]
> 经过验证，新版小程序ide无此问题

还真是，我之前用的这个版本的，检查更新提示我是最新的。。。。
![image](https://user-images.githubusercontent.com/38450626/145773798-c107ec46-421f-492b-81af-dec49cc8ca33.png)
去官网下载了1.05.2111300版本好了。。。。。

**Comment by PlayerYK** [comment]
1.05.2111300版本，不能用 class 的私有方法。我又回退了

**Comment by changzhengithub** [comment]
ide最新版试了没用，是基础库版本问题，从2.20.0之后就不行了，低版本的都OK
