### ISSUE TITLE
[Bug Report] taro引用SwipeCell，插槽无效果

### ISSUE THREAD

**Issue by LoSoleil** [youzan/vant-weapp#4616]
### 设备
微信小程序

### VantWeapp 版本
1.9.2

### 基础库版本
无

### 如果是 UI 问题，截图链接（多图回车分隔）

![截图](https://i.loli.net/2021/11/15/4ACBzWdi3feVa2m.png)

### 请提供核心代码片段链接
https://sm.ms/image/Cz3O84KPw95Gcom

### 描述问题
taro引用SwipeCell，插槽无效果，可以滑动，但是无法写入插槽

**Comment by shenjingnan** [comment]
重复issue
