### ISSUE TITLE
Calendar组件在某些机型上渲染日期为空白，需手指滑动后才显示

### ISSUE THREAD

**Issue by XKF** [youzan/vant-weapp#4617]
不知道是系统还是手机原因，此问题每次都是必现的，网上也有其他人发现过，大都推测是外层popup未设高度时的高度计算问题，但终归不能每次靠强制样式覆盖去解决，希望这个bug可以重视优化解决下

必现机型：iphone13 mini (iOS15)，iphone13 pro (iOS15)
vant版本：2.12.31
vue版本：2.6.11
重现链接：私密链接暂无法提供，可自行跑个简单调用组件的demo

**Comment by pandamo** [comment]
Calendar不需要套在popup里面，另外个人建议：
minDate和maxDate的默认值都设置成当前时间戳：
 minDate:new Date().getTime(),
 maxDate:new Date().getTime(),
 
在点击显示日历的事件内，根据自己需要重新设置minDate和 maxDate，这样对页面加载时间有帮助

**Comment by XKF** [comment]
您好~您的邮件我已收到，谢谢！
