### ISSUE TITLE
vant Picker组件,不显示顶部栏,change事件拿到的值有1-2s延迟问题  (小程序 安卓机型)

### ISSUE THREAD

**Issue by liuguojun1022** [youzan/vant-weapp#4618]
### 重现链接

https://jsrun.net/5UUKp/edit#google_vignette

### Vant 版本

2.1

### 描述一下你遇到的问题。

vant Picker组件,不显示顶部栏,change事件拿到的值有1-2s延迟问题  (小程序 安卓机型)

小程序因为特别需求的 需要重写顶部  当快速点击自定义确认按钮的时候  组件change事件在安卓机型上面会出现延迟1-2秒延迟问题
苹果机型未发现  安卓机型 测试oppo 小米 华为 均有该问题
类似于该帖问题 https://developers.weixin.qq.com/community/develop/doc/00064c5b018710e8d94bd099456400

![image](https://user-images.githubusercontent.com/52098260/141730637-068c464a-38f6-464a-85cb-378f73eb47d7.png)

### 重现步骤

安卓机型 切换时间 快速点击自定义确认按钮  change事件会有延迟

### 设备/浏览器

安卓

**Comment by chenjiahan** [comment]
了解，那 issue 转到 vant-weapp 仓库下了。

**Comment by liuguojun1022** [comment]
> 了解，那 issue 转到 vant-weapp 仓库下了。

不太会搞 方便加个微信 教一下吗 蛮烦了    我的 -ll1020

**Comment by Jeana-f** [comment]
这个问题解决了吗？我也遇到这个问题了

**Comment by landluck** [comment]
> 这个问题解决了吗？我也遇到这个问题了

可以提供一个小程序代码协助排查， https://developers.weixin.qq.com/miniprogram/dev/devtools/minicode.html

**Comment by johnsonwong666** [comment]
可以提供一个小程序代码片段过来吗？

**Comment by johnsonwong666** [comment]
没有复现。由于较长时间没有提供复现代码片段，此issue暂时关闭，若还有问题请提新的issue,并附带复现代码片段排查。
