### ISSUE TITLE
小程序端。uploader 组件 after-read 中使用 this 无效！！！

### ISSUE THREAD

**Issue by pyy-alt** [youzan/vant-weapp#4621]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater?repo=VantWeapp

**Comment by shenjingnan** [comment]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。
