### ISSUE TITLE
[Bug Report] search控件input.autoFocus即将失效，请使用focus代替

### ISSUE THREAD

**Issue by mablevi** [youzan/vant-weapp#4622]
### 设备
所有设备

### VantWeapp 版本
1.9.2

### 基础库版本
2.20.2

### 请提供核心代码片段链接
https://developers.weixin.qq.com/miniprogram/dev/component/input.html

### 描述问题
search控件input.autoFocus即将失效，请使用focus代替

**Comment by shenjingnan** [comment]
根据文档使用 focus 即可，源码中保留的 autoFocus 只是为了做兼容处理，默认文档并不会提现auto-focus用法，也不推荐使用
