### ISSUE TITLE
[Bug Report] Uploader拍照后未正确成像

### ISSUE THREAD

**Issue by SaberInoryKiss** [youzan/vant-weapp#4624]
### 设备
安卓

### VantWeapp 版本
1.6.2

### 基础库版本
2.18.0

### 如果是 UI 问题，截图链接（多图回车分隔）

![image](https://user-images.githubusercontent.com/39288809/142366827-1abefd83-b587-4b99-b40d-f79be53edfd4.png)

### 请提供核心代码片段链接
https://gist.github.com/SaberInoryKiss/1b3d6d7443770e402f93f3e78fa279ff

### 描述问题
非必现，点击拍照后，小概率会出现拍照没有成像的问题。项目已经上线，时不时会出现这样的问题，很头疼。

**Comment by shenjingnan** [comment]
@SaberInoryKiss 
可能是由于拍照图片过大导致，建议可以**尝试用下微信的Uploader试试，是否能生成图片**
