### ISSUE TITLE
[建议]小程序CountDown倒计时组件建议增加一个字体颜色修改属性

### ISSUE THREAD

**Issue by AshEchoe** [youzan/vant-weapp#4625]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater?repo=VantWeapp

**Comment by shenjingnan** [comment]
[自定义样式](https://vant-contrib.gitee.io/vant-weapp/#/count-down) 应该能满足你的需求
