### ISSUE TITLE
DatetimePicker 时间选择组件 在type = time时，min-date,max-date不起作用

### ISSUE THREAD

**Issue by Angusir** [youzan/vant-weapp#4626]
DatetimePicker 时间选择组件，在type = time时，不可以选择时间段，即min-date和max-date不起作用

**Comment by shenjingnan** [comment]
如果是 `time` 类型，请使用 `(min|max)Hour` 和 `(min|max)Minute`，另外，你所用到的 `(min|max)Date`是给日期用的 这是[官方教程](https://vant-contrib.gitee.io/vant-weapp/#/datetime-picker)
