### ISSUE TITLE
cell自定义图标不显示

### ISSUE THREAD

**Issue by whlvv** [youzan/vant-weapp#4628]
@vant\weapp\cell\index.wxml
  <van-icon wx:if="{{ icon }}" name="{{ icon }}"  size="1.2em" class-prefix="{{ classPrefix }}" class="van-cell__left-icon-wrap" custom-class="van-cell__left-icon" />

@vant\weapp\cell\index.js
props: {
        formType: String,
        icon: String,
        classPrefix: {
            type: String,
            value: 'van-icon',
        }
}
![image](https://user-images.githubusercontent.com/50831414/142876680-02de5b33-6208-4da0-a173-392a3bb5cfce.png)

**Comment by shenjingnan** [comment]
请使用 [官方教程](https://vant-contrib.gitee.io/vant-weapp/#/cell) 中提供的 **Cell Slot** => **icon**
