### ISSUE TITLE
[Bug Report] van-collapse嵌套van-collapse 如何去除中间的margin

### ISSUE THREAD

**Issue by czy8187** [youzan/vant-weapp#4629]
### 设备
iPhone12

### VantWeapp 版本
1.9.2

### 基础库版本
2.21.0

### 如果是 UI 问题，截图链接（多图回车分隔）

![截图](https://i.loli.net/2021/11/23/wls7NAfbTrLC8kF.png)

![WX20211123-180449@2x.png](https://i.loli.net/2021/11/23/UxXelDa7PnVvZA6.png)

### 请提供核心代码片段链接
https://gitee.com/czy8187/codes/9um3y1sh8nolqe7wpar0c85

### 描述问题
van-collapse中嵌套van-collapse，顶部和底部有间隔，请问如何去除？详情请查看截图

**Comment by 098018** [comment]
item的内容样式

**Comment by shenjingnan** [comment]
[官方教程](https://vant-contrib.gitee.io/vant-weapp/#/collapse) 滚动至 **CollapseItem 外部样式类** `content-class `
