### ISSUE TITLE
图标显示不全

### ISSUE THREAD

**Issue by amou-zeng** [youzan/vant-weapp#463]
图标经常不显示；
`<van-icon /> <van-cell /> <van-field />` 页面切换无规律性的，需要滚动或点击才显示。

**环境**
 - 设备: IOS Apple6s
 - Vant Weapp 版本: 0.2.0

**官方小程序截图**

![8121535275232_ pic](https://user-images.githubusercontent.com/5335178/44626740-8051ed80-a954-11e8-89db-0d9cb72b7146.jpg)

**Comment by chenjiahan** [comment]
图标资源是在 cdn 上的，可能是网络延时问题

**Comment by amou-zeng** [comment]
已经转成Base64也涛声依旧！无法正常渲染，滑动或者点击才渲染，不知道什么机制

**Comment by PMExtra** [comment]
@amou-zeng 看你的描述像是异步问题，如果是wepy框架加上 `this.$apply()` 试下
