### ISSUE TITLE
[Bug Report] field   type='textarea'输入框水印被加粗 ，输入内容再清空后恢复正常 

### ISSUE THREAD

**Issue by mengbin0423** [youzan/vant-weapp#4630]
### 设备
开发者工具

### VantWeapp 版本
1.9.2

### 基础库版本
2.19.0

### 如果是 UI 问题，截图链接（多图回车分隔）

![截图](https://sm.ms/image/qItZ8C2a4snK3Gf)

### 请提供核心代码片段链接
https://gist.github.com/mengbin0423/1e57a1acec003405656a3d76adc6025b

### 描述问题
van-field   type='textarea'输入框水印被加粗 ，输入内容再清空后恢复正常

**Comment by shenjingnan** [comment]
@mengbin0423 测试了下好像并没有加粗，官方demo小程序可以复现吗
