### ISSUE TITLE
[Bug Report] 不支持滚动导航模式scrollspy

### ISSUE THREAD

**Issue by inooNgt** [youzan/vant-weapp#4631]
### 设备
iphone

### VantWeapp 版本
1.9.2

### 基础库版本
v2.1.0 

### 请提供核心代码片段链接
https://vant-contrib.oschina.io/vant/v3/#/zh-CN/tab#gun-dong-dao-hang

### 描述问题
 Tabs组件的vant-weapp版本可以支持vant的滚动导航模式scrollspy吗

**Comment by dingling001** [comment]
这个属性啥时候可以实现呀

**Comment by dingling001** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
