### ISSUE TITLE
van-switch 自定义颜色active-color 后 无论开关都会显示active-color的颜色

### ISSUE THREAD

**Issue by zhaowei8998** [youzan/vant-weapp#4633]
设备
iphone

VantWeapp 版本
^1.9.1

基础库版本
2.20.1

请提供核心代码片段链接
![image](https://user-images.githubusercontent.com/91623667/143383818-eeae7ae7-0413-492a-8c26-33d84d910428.png)

描述问题
van-switch 自定义颜色active-color 后 无论开关都会显示active-color的颜色

**Comment by shenjingnan** [comment]
使用错误

[官方教程](https://vant-contrib.gitee.io/vant-weapp/#/switch) 滚动到 `自定义颜色`

**Comment by zhaowei8998** [comment]
官方您好,之前提的问题,被关闭了,说使用错误,我研究了好久,应该不是我的问题
**文档里自定义颜色是** 
打开时的背景色 active-color="#07c160"
关闭时的背景色inactive-color="#ee0a24"
我的代码如下
<van-switch checked="{{ checked }}" active-color="#07c160" inactive-color="#ee0a24"active-value="on" inactive-value="off" bind:change="onChangeS"/>
**但是我同时用了自定义值**
打开时的值 active-value="on" 
关闭时的值 inactive-value="off"
**这时候自定义颜色就不生效了,一直显示的是**
打开时的背景色 active-color="#07c160"
