### ISSUE TITLE
[Bug Report] vantWeapp/slider

### ISSUE THREAD

**Issue by caochengming** [youzan/vant-weapp#4634]
### 设备
小程序开发工具、华为Meta40 pro

### VantWeapp 版本
1.9.2

### 基础库版本
基础库2.13.0

### 如果是 UI 问题，截图链接（多图回车分隔）

![截图](https://sm.ms/image/nC6qVDodY3EwsjP)

![截图](https://sm.ms/image/djUVMTRLgZwAzF7)

### 请提供核心代码片段链接
https://github.com/caochengming

### 描述问题
因为是公司项目不便放项目地址，
小程序原生开发，使用slider，双滑块、指定选择范围、指定步长、自定义按钮。问题出在指定选择范围，最小值设置 个位数；最大值设置 十位数；滑动的时候会出现bug，右侧按钮右侧偏移，见上图
我的代码:   <van-slider value="{{ moistureNum}}" data-type='moistureNum' min="4" max="11"  step="0.1" range   bar-height="4px" active-color="#14bab4"  binddrag="onDrag" use-button-slot >
           <view class="custom-button" slot="left-button">{{ moistureNum[0] }}</view>
           <view class="custom-button" slot="right-button">{{ moistureNum[1] }}</view>
         </van-slider>

**Comment by shenjingnan** [comment]
@caochengming 如果要 `双滑块` 并且要使用 `自定义按钮` slot 应改为 `left-button` 和 `right-button`
