### ISSUE TITLE
请问该组件样式文件如何引入？

### ISSUE THREAD

**Issue by 1257041477** [youzan/vant-weapp#4636]
请问该组件样式文件如何引入？请问该组件样式文件如何引入？请问该组件样式文件如何引入？请问该组件样式文件如何引入？请问该组件样式文件如何引入？请问该组件样式文件如何引入？请问该组件样式文件如何引入？请问该组件样式文件如何引入？请问该组件样式文件如何引入？

**Comment by yoyo837** [comment]
引用组件就引入了组件的样式

**Comment by shenjingnan** [comment]
@yxxwym [快速上手](https://vant-contrib.gitee.io/vant-weapp/#/quickstart)
