### ISSUE TITLE
Card的desc-class不生效

### ISSUE THREAD

**Issue by Jinsheng-Peng** [youzan/vant-weapp#464]
**描述一下问题**
如图，price-class  title-class 都能生效，就这个desc-class 不生效。。。

**截图**
![_20180825105825](https://user-images.githubusercontent.com/16498476/44614379-e86dda00-a855-11e8-9cbc-b629957efa55.png)

**Comment by chenjiahan** [comment]
https://github.com/youzan/vant-weapp/issues/414
