### ISSUE TITLE
van-switch 自定义颜色active-color 后 无论开关都会显示active-color的颜色 

### ISSUE THREAD

**Issue by zhaowei8998** [youzan/vant-weapp#4644]
官方您好,之前提的问题,被关闭了,说使用错误,我研究了好久,应该不是我的问题
**文档里自定义颜色是** 
打开时的背景色 active-color="#07c160"
关闭时的背景色inactive-color="#ee0a24"
我的代码如下
<van-switch checked="{{ checked }}" active-color="#07c160" inactive-color="#ee0a24"active-value="on" inactive-value="off" bind:change="onChangeS"/>
**但是我同时用了自定义值**
打开时的值 active-value="on" 
关闭时的值 inactive-value="off"
**这时候自定义颜色就不生效了,一直显示的是**
打开时的背景色 active-color="#07c160"

**Comment by shenjingnan** [comment]
@zhaowei8998 不好意思，我的问题，当时没仔细审阅你的issue，武断的判断为使用问题，将在下个版本修复该问题

**Comment by shenjingnan** [comment]
1.10.0已修复
