### ISSUE TITLE
[Bug Report] van-action-sheet没有从底部弹出

### ISSUE THREAD

**Issue by hanju** [youzan/vant-weapp#4647]
### 设备
iphone 13 Pro Max

### VantWeapp 版本
1.9.2

### 基础库版本
2.21.0

### 请提供核心代码片段链接
https://developers.weixin.qq.com/s/W4hkZem272v4

### 描述问题
在component中使用了van-action-sheet，当这个component放在swiper中时，action-sheet不能从底部弹出。

**Comment by shenjingnan** [comment]
这应该是受限于微信

**Comment by shenjingnan** [comment]
建议可以在外层放置action-sheet，swiper中通过事件触发
