### ISSUE TITLE
[Bug Report] notify能否全局调用？

### ISSUE THREAD

**Issue by JoyNop** [youzan/vant-weapp#4657]
### 设备
iPhone X

### VantWeapp 版本
1.9.2

### 基础库版本
2.21.0

### 请提供核心代码片段链接
https://gist.github.com/JoyNop/e52ae9285bb162b64fb8b3398fb6f490

### 描述问题
```javascript
import Notify from 'path/to/@vant/weapp/dist/notify/notify'; 
Notify('通知内容');
```

```html
<van-notify id="van-notify" />

```
上面这种方法在单页面是可以使用的

我想做一个全局请求拦截，让他使用notify作为全局报错提醒。全局的HTML标签插在哪里？或者demo》？

**Comment by Cream7** [comment]
不行吧

**Comment by shenjingnan** [comment]
微信应该没提供这种能力，仅限于页面级
