### ISSUE TITLE
[Bug Report] van-action-sheet在ios下没有动画

### ISSUE THREAD

**Issue by dsgvsn** [youzan/vant-weapp#4659]
### 设备
ios真机

### VantWeapp 版本
1.9.2

### 基础库版本
2.19.6

### 请提供核心代码片段链接
https://gist.github.com/dsgvsn/94ac349671f34e93f19e9874ea4a9ecc

### 描述问题
van-action-sheet在ios真机下没有动画，在安卓及开发者工具正常。

**Comment by dsgvsn** [comment]
官方demo小程序也此问题。

**Comment by hanju** [comment]
重启微信
