### ISSUE TITLE
[Bug Report] SwipeCell 滑动单元格无法实现点击空白地方自动关闭滑动状态

### ISSUE THREAD

**Issue by hongxiangping** [youzan/vant-weapp#4660]
### 设备
任何设备，包括微信开发者工具

### VantWeapp 版本
1.9.2

### 基础库版本
2.21.0

### 如果是 UI 问题，截图链接（多图回车分隔）

![截图](https://sm.ms/image/W9TytLxw4VUqkg7)

![截图](https://sm.ms/image/tq5bv6Rk3MDKAOz)

### 请提供核心代码片段链接
https://gitee.com/hongxpCode/swipe-cell-demo.git

### 描述问题
SwipeCell 滑动单元格无法实现点击空白地方自动关闭滑动状态，然而网页上的案例可以实现

**Comment by hongxiangping** [comment]
![图片](https://user-images.githubusercontent.com/34200846/144393955-bc6af9b0-77d7-4862-8d7f-85890f911ec9.png)

**Comment by hongxiangping** [comment]
![图片](https://user-images.githubusercontent.com/34200846/144394027-8e61fa3c-6867-41f7-b480-a44eaee32ba0.png)

**Comment by NRMrYang** [comment]
+1，同样有此问题，大半年了官方也不理一下嘛

**Comment by NRMrYang** [comment]
@nemo-shen 能麻烦看一下吗？滑动时微信开发者工具提示此报错，不知道是否与此有关
```
[渲染层错误] Ignored attempt to cancel a touchmove event with cancelable=false, for example because scrolling is in progress and cannot be interrupted.(env: Windows,mp,1.05.2110290; lib: 2.17.0)
```

**Comment by NRMrYang** [comment]
害，求人不如求己，后续如果有看到这个issue的，可以看下我这个博客：[https://blog.csdn.net/Mr_Yang98/article/details/125806638](https://blog.csdn.net/Mr_Yang98/article/details/125806638)

**Comment by landluck** [comment]
关点击空白地方无法关闭的问题在小程序下受限于无法监听全局事件，可以通过在页面中调用组件 close 方法来进行手动关闭，例如
```html
<view bind:tap="onCloseCell">
  <van-swipe-cell id="swipe-cell">
    <view slot="left" class="van-swipe-cell__left">选择</view>
    <van-cell-group>
      <van-cell title="单元格" value="内容" />
    </van-cell-group>
    <view slot="right" class="van-swipe-cell__right">删除</view>
  </van-swipe-cell>
</view>
```

```js
Page({
  onCloseCell() {
     const cell = this.selectComponent('#swipe-cell')

     cell.close();
  }
})
```

对于有多个 cell 的，可以使用 class 进行批量处理

**Comment by landluck** [comment]
> @nemo-shen 能麻烦看一下吗？滑动时微信开发者工具提示此报错，不知道是否与此有关
> 
> ```
> [渲染层错误] Ignored attempt to cancel a touchmove event with cancelable=false, for example because scrolling is in progress and cannot be interrupted.(env: Windows,mp,1.05.2110290; lib: 2.17.0)
> ```
至于这个问题目前看没有发现，如还有问题可以重新打开issue或者提供小程序代码片段协助排查
