### ISSUE TITLE
Dialog根据文档使用得到的效果不一样

### ISSUE THREAD

**Issue by bltccccz** [youzan/vant-weapp#4661]
按照文档使用dialog,得到的效果和预想的差距太大,app.json中的style:v2已经去除，依然如此
![1638518499(1)](https://user-images.githubusercontent.com/42707641/144566899-16f5a38e-ca95-4709-ad43-54a3e3698e5c.png)

**Comment by shenjingnan** [comment]
建议通过文档、搜索引擎、问答社区寻找使用方面的答案
