### ISSUE TITLE
[Bug Report] tabbar遮挡页面内容

### ISSUE THREAD

**Issue by yuyuko233** [youzan/vant-weapp#4662]
### 设备
开发者工具, 小米10

### VantWeapp 版本
1.9.2

### 基础库版本
2.21.0

### 如果是 UI 问题，截图链接（多图回车分隔）

![截图](https://s4.ax1x.com/2021/12/04/o05Q41.png)

### 请提供核心代码片段链接
https://pastebin.com/60PYy092

### 描述问题
tabbar启用fixed与placeholder属性还是会遮挡页面内容, 

而且在调试工具中也看到了占位元素, 但是还是会挡住页面内容

**Comment by yuyuko233** [comment]
在page元素内最后添加占位元素可以实现, 在tabbar里的就无效
`<view style="height: 84px;"></view>`

**Comment by shenjingnan** [comment]
tabbar默认z-index是1，具体参考文档

**Comment by yuyuko233** [comment]
基于官方示例, 增加页面内容还是会遮住内容
![图片](https://user-images.githubusercontent.com/20128226/147379007-79a2d7a0-9778-4ea3-b866-0bfc0d16fca8.png)
页面到底部都显示不出来最后一个

**Comment by FFFlower** [comment]
兄弟你解决了没，官方文档里面的代码片段也会遮挡

**Comment by yuyuko233** [comment]
> 兄弟你解决了没，官方文档里面的代码片段也会遮挡

没解决, 官方那边我试的也是
