### ISSUE TITLE
[Bug Report] notice-bar左边图标大小无法使用变量定义

### ISSUE THREAD

**Issue by JZ277100** [youzan/vant-weapp#4664]
### 设备
ipad

### VantWeapp 版本
1.9.2

### 基础库版本
2.20.2

### 请提供核心代码片段链接
https://gist.github.com/JZ277100/c9914eecfa66e4a2d0680a49723dbf32

### 描述问题
notice-bar  源码中icon写死了size，无法使用变量（--notice-bar-icon-size）控制，导致大屏设备上图标过小，应去掉size='16px'属性

**Comment by shenjingnan** [comment]
已在1.10.1中支持
