### ISSUE TITLE
小程序基础库2.21.0，样式不起作用了

### ISSUE THREAD

**Issue by ForDreamRush** [youzan/vant-weapp#4665]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater?repo=VantWeapp

**Comment by brownfoxsir** [comment]
https://github.com/youzan/vant-weapp/issues/4614#issue-1052522732

**Comment by changzhengithub** [comment]
要么降低版本到2.20.2之下，要么去掉app.json中按需加载"lazyCodeLoading": "requiredComponents"。

**Comment by shenjingnan** [comment]
已有相同issue，这个先关闭了
