### ISSUE TITLE
vant-search的clear方法在电脑端时失效，手机生效（即navigator.userAgent不同时，不一定产生效果）

### ISSUE THREAD

**Issue by 1114860254** [youzan/vant-weapp#4666]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater?repo=VantWeapp

**Comment by shenjingnan** [comment]
官方示例没有复现，请按规范提交issue
