### ISSUE TITLE
[Bug Report] van-circle层级最高，弹出层无法覆盖

### ISSUE THREAD

**Issue by migue821** [youzan/vant-weapp#4667]
### 设备
开发者工具，iphone13

### VantWeapp 版本
1.9.2

### 基础库版本
2.19.3

![截图](https://s2.loli.net/2021/12/08/4PqZg6brBmhyREH.png)

### 描述问题
经典问题，canvas层级最高，popup弹出层无法覆盖。
可以组件内写个方法，调用时将van-circle画成图片应该就能解决了

**Comment by shenjingnan** [comment]
微信小程序canvas是原生组件，层级高于其他自定义组件，因此会这样，建议可以到微信社区讨论
