### ISSUE TITLE
[Bug Report] NoticeBar 通知栏 文档内容错误

### ISSUE THREAD

**Issue by uudiv** [youzan/vant-weapp#4668]
### 设备
电脑端

### VantWeapp 版本
1.9.2

### 基础库版本
2.16.1

### 请提供核心代码片段链接
https://vant-contrib.gitee.io/vant-weapp/#/notice-bar

### 描述问题
文档错误，API【delay	动画延迟时间 (s)	number	1】。动画延迟时间应该为毫秒 (ms)

**Comment by chenjiahan** [comment]
这个问题已经修正过咯：https://github.com/youzan/vant-weapp/pull/4641

站点近期会更新一下
