### ISSUE TITLE
[Bug Report] van-tabs swipeable手势滑动bug

### ISSUE THREAD

**Issue by xjphhh** [youzan/vant-weapp#4669]
### 设备
微信开发者工具、真机：华为P30pro

### VantWeapp 版本
1.9.2

### 基础库版本
2.21.0

### 请提供核心代码片段链接
https://gist.github.com/xjphhh/8689dd6ce4a216e6f03667207d731ab7

### 描述问题
van-tabs启用swipeable手势滑动，当向左（或向右）滑动超过当前tabs个数时，会滑动不了，只有点击tabs切换回来才可以继续滑动。查看源码是因为如图：![image.png](https://s2.loli.net/2021/12/10/XKHT3ainp21CYOf.png)，建议修改。
同时，这只是type为line的问题，当type为card问题更大，只有初次进来可以滑动一次，接下来怎么都滑不动，查看源码发现是因为![image.png](https://s2.loli.net/2021/12/10/ZWS9C2nUViBkevb.png)。请你们紧急修复下！

**Comment by zenonux** [comment]
me too

**Comment by shenjingnan** [comment]
计划下个版本修复

**Comment by shenjingnan** [comment]
已在1.10.1中修复
