### ISSUE TITLE
微信小程序下拉菜单多个子项的遮罩层问题。

### ISSUE THREAD

**Issue by lucky0lonely** [youzan/vant-weapp#4675]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater?repo=VantWeapp
版本：1.9.2

结构：
![image](https://user-images.githubusercontent.com/46698787/145660490-2c995d34-3126-49fc-b0f3-d4db11f61fb5.png)

问题：
![image](https://user-images.githubusercontent.com/46698787/145660504-65c133f0-5d85-4ca1-94e6-dbf791716527.png)
点击第一个是没有问题的，但是如果点了第二个之后，在点第一个，那么点它的遮罩层是不会关闭的，只能点头部才可以关闭。

原因：
![image](https://user-images.githubusercontent.com/46698787/145660545-ef132898-78b3-4061-960d-4aafaf0a8d3a.png)

onClosed事件不会触发，showWrapper所有子项都是true。而且子项只是设置了opacity:0；并不是display:none;

**Comment by quizzer-xi** [comment]
这个问题解决了吗？？

**Comment by lucky0lonely** [comment]
> 这个问题解决了吗？？

该源码可以解决。

**Comment by landluck** [comment]
@closed  小程序没有这种写法吧？没有能复现问题，如能复现建议参考 https://developers.weixin.qq.com/miniprogram/dev/devtools/minicode.html 提供代码片段协助定位问题，提供后可以重新打开issue或者按照重新提交issue
