### ISSUE TITLE
[Bug Report]  [Component] slot "" is not found.

### ISSUE THREAD

**Issue by 419131433** [youzan/vant-weapp#4676]
### 设备
ios

### VantWeapp 版本
1.9.2

### 基础库版本
2.19.*

### 请提供核心代码片段链接
https://vant-contrib.gitee.io/vant-weapp/#/dropdown-menu

### 描述问题
引入van-dropdown-menu,打开选项会大量报  [Component] slot "" is not found.错误日志

**Comment by shenjingnan** [comment]
微信开发者工具的问题

**Comment by sdlddr** [comment]
小程序基础库有更新了，为什么vant不作适应呢？反而把责任推给微信官方？难道要我们去修改基础库内核？

**Comment by Yookey** [comment]
只能退回到之前的版本使用了
