### ISSUE TITLE
[Feature Request] 希望dropdown菜单项icon可以自定义

### ISSUE THREAD

**Issue by xixihhhh** [youzan/vant-weapp#4677]
### 这个功能解决了什么问题
现在菜单名右侧图标是用css写的一个箭头，不好去覆盖修改，希望能支持自定义icon

### 建议的API是什么样的
现在菜单名右侧图标是用css写的一个箭头，不好去覆盖修改，希望能支持自定义icon

**Comment by shenjingnan** [comment]
不是一个icon，而是border，暂时不会调整，先标记成feature
