### ISSUE TITLE
[Bug Report] van-circle 更新绘制时依赖他的组件位置错位

### ISSUE THREAD

**Issue by rzbdz** [youzan/vant-weapp#4681]
### 设备
Android 微信 8.0.16

### VantWeapp 版本
1.9.2

### 基础库版本
2.19.6

### 如果是 UI 问题，截图链接（多图回车分隔）
图中上面部分是 Page 就硬编码在 page 数据数据 list 里面的，而下面出现错乱的的是后面通过 onload 中 setData 进行动态更新的绘制的。
![截图](https://s2.loli.net/2021/12/14/C2yBIS6OozLNk73.png)

### 请提供核心代码片段链接
https://gist.github.com/rzbdz/b54ab739b01d6345f10163b16e3f8f82

### 描述问题
当 js 通过 setData 更新数据（圆环进度）涉及到 vant-circle 的时候会由于渲染延时引发 view 父组件不能及时计算正确长宽引发依赖于他计算位置的其余组件渲染错位根据设计，作为 inline-block 这种情况会很常见。
在模拟器没有问题，真机测试检测到这个问题，可以通过给组件内部实现的 canvas 外的 view 容器添加一个长宽限定解决问题。

重现时 
 - van-circle 大小设置为小于100 如 80时
 - 真机测试
 - 使用 flex 布局 row，内部两个 view 组件，左边是 van-circle，右边是任意有大小的组件。
 - van-circle 中的进度值在 onLoad 之后通过 setData 更新

目前的修复方法：
[fix(circle): use fixed width and height for outer view of circle #4680](https://github.com/youzan/vant-weapp/pull/4680)

**Comment by shenjingnan** [comment]
尝试用你说的复现步骤没有复现哎

**Comment by rzbdz** [comment]
> 尝试用你说的复现步骤没有复现哎

那 close 了吧，我刚刚新建了一个项目在真机上尝试最小代码复现也没有在出现这个问题。
有时间我尝试根据之前的小程序复现。
我应该可以直接包裹一个固定大小 view 避免这个问题不用修改组件代码。
