### ISSUE TITLE
[Bug Report] Sticky 粘性布局 高度失效

### ISSUE THREAD

**Issue by 490626721** [youzan/vant-weapp#4682]
### 设备
微信开发者工具

### VantWeapp 版本
1.9.2

### 基础库版本
2.21.1

### 请提供核心代码片段链接
https://gist.github.com/490626721/6a6220a4e9c894ced265f4a5d1cedefc

### 描述问题
当Sticky 的内容为 fit="widthFix" 的image图片时，Sticky 的高度识别不正常，导致下方正常文档流内容会被上方Sticky 内的图片覆盖

**Comment by johnsonwong666** [comment]
根据你提供的代码试了一下，图片占位的高度是正确，是不是你还在滚动？ 可否拍个视频 或者 最小复现片段过来？

**Comment by 490626721** [comment]
> 根据你提供的代码试了一下，图片占位的高度是正确，是不是你还在滚动？ 可否拍个视频 或者 最小复现片段过来？

已经解决，谢谢啦
