### ISSUE TITLE
[Bug Report] dialog 和 tabs 的z-index无效

### ISSUE THREAD

**Issue by huangzenghuang** [youzan/vant-weapp#4684]
### 设备
开发者工具

### VantWeapp 版本
1.9.2

### 基础库版本
2.14.4

### 请提供核心代码片段链接
https://codepen.io/huangzenghuang/pen/dyVRWdr

### 描述问题
tabs覆盖到dialog上面，设置级别无效

![image](https://user-images.githubusercontent.com/45776589/146676614-7837cc3f-e5ed-4414-a77f-9e48ae5cb0fa.png)

**Comment by shenjingnan** [comment]
官方代码尝试没有复现你说的问题
看截图 dialog 代码在 footer内部，建议提到和tabs同级试试

**Comment by roy2651** [comment]
我也遇到这个问题，在模拟器ok，在真机里面tab在dialog前面，怎么解决
