### ISSUE TITLE
[Bug Report] van-tab开启滑动，滑动的边界继续滑动，无法返回滑动。

### ISSUE THREAD

**Issue by zhihuifanqiechaodan** [youzan/vant-weapp#4689]
### 设备
iphone

### VantWeapp 版本
1.10.0

### 基础库版本
2.19.2

### 请提供核心代码片段链接
https://developers.weixin.qq.com/s/6IhrYIm37ZvR

### 描述问题
请查看代码片段，van-tab开启滑动，滑动到边界位置，继续向左或者向右滑动，然后往返滑动时无法滑动了。

**Comment by zhangyuan722** [comment]
同遇，滑到头后继续向同方向滑动一次，转场动画失效，需要点击标题切换才能生效

**Comment by shenjingnan** [comment]
已有同样的issue #4669 合并下issue下个版本解决
