### ISSUE TITLE
popup弹出层有办法让顶部的关闭按钮始终保持在顶部吗？

### ISSUE THREAD

**Issue by Ruby799** [youzan/vant-weapp#4690]
在开发小程序时，这个popup弹出层内容多会有滚动条，向下滚动的同时关闭按钮也会移动，如何保持在顶部不变
http://vant-contrib.gitee.io/vant-issue-generater?repo=VantWeapp

**Comment by zhihuifanqiechaodan** [comment]
自定义右上角关闭icon吧。定位上去。

**Comment by shenjingnan** [comment]
自定义右上角图标即可
