### ISSUE TITLE
van-field type="textarea"的时候，如果使用van-popup组件，导致field的placeholder文字上浮，而且点击文字会呼起键盘

### ISSUE THREAD

**Issue by Mo-xiaoyu** [youzan/vant-weapp#4691]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater?repo=VantWeapp

问题截图在下方网址：
https://sm.ms/image/qfV2U6oYtsHCT94

**Comment by shenjingnan** [comment]
`always-embed ` prop 看文档

**Comment by Mo-xiaoyu** [comment]
我升级到1.10版本试了，还是不行，因为我是安卓，文档说只在ios下生效，这个bug只有在真机调试才会有
