### ISSUE TITLE
[Bug Report] calendar组件显示问题

### ISSUE THREAD

**Issue by shan33** [youzan/vant-weapp#4694]
### 设备
IOS11mini、IOS11等

### VantWeapp 版本
1.10.0

### 基础库版本
2.16.1

### 如果是 UI 问题，截图链接（多图回车分隔）

![截图](真机样式：)

![截图](https://static.fuhuibao.club/szh/imgfile/szh/1640225282503/20211223100802504989.jpeg)

![截图](调试样式：)

![截图](https://static.fuhuibao.club/szh/imgfile/szh/1640225263418/20211223100743907976.png)

![截图](https://static.fuhuibao.club/szh/imgfile/szh/1640225268143/20211223100748425492.png)

### 请提供核心代码片段链接
https://gist.github.com/shan33/8a755a21933e56bf728487997a7ec5fe

### 描述问题
vant-weapp源码；
1. 调试到了1月份，但是还是12月份的标题
2. 到了2月份，显示2月份；
真机上（IOS11,IOS12mini、android）需要把月份滚动完subTitle才会改变一下；用户体验很奇怪。
具体可以看看我的UI截图调试结果；

**Comment by electron-shaders** [comment]
尝试在dist里改源码修复成功
![image](https://user-images.githubusercontent.com/53993972/147382132-7b804d0b-4aac-4219-ae84-b6f4cc5ac36b.png)

看怎么开个pr

**Comment by landluck** [comment]
`v1.10.19` 版本已修复
