### ISSUE TITLE
[Bug Report] filed组件滚动内容错位

### ISSUE THREAD

**Issue by baaaaazinga** [youzan/vant-weapp#4697]
### 设备
小米11

### VantWeapp 版本
1.10.0

### 基础库版本
2.21.2

### 如果是 UI 问题，截图链接（多图回车分隔）

![截图](https://vkceyugu.cdn.bspapp.com/VKCEYUGU-97c44012-0876-4a28-84bf-939a4ff1ca35/ffb9c750-fd24-47e8-8d27-f8b66e3081a1.gif)

### 请提供核心代码片段链接
https://developers.weixin.qq.com/s/n3ICfMmU7rvO

### 描述问题
设置filed组件的type为textarea，滚动页面&输入时，内容会错位。

**Comment by baaaaazinga** [comment]
[https://vkceyugu.cdn.bspapp.com/VKCEYUGU-97c44012-0876-4a28-84bf-939a4ff1ca35/ffb9c750-fd24-47e8-8d27-f8b66e3081a1.gif](url)

**Comment by shenjingnan** [comment]
可能是小程序官方兼容性问题，建议尝试下小米11使用官方的textarea效果

**Comment by baaaaazinga** [comment]
> 可能是小程序官方兼容性问题，建议尝试下小米11使用官方的textarea效果

使用纯原生textarea也有类似的现象，已反馈官方
