### ISSUE TITLE
[Bug Report] [Bug Report] Slider 滑块 使用 双滑块模式  有bug

### ISSUE THREAD

**Issue by dqchdjm** [youzan/vant-weapp#4698]
### 设备
小米10

### VantWeapp 版本
1.10.0

### 基础库版本
2.19.6

### 如果是 UI 问题，截图链接（多图回车分隔）

![截图](https://sm.ms/image/aMZ5oKLv7tSsDRP)

![截图](https://sm.ms/image/s9nuyYxqDFEpMed)

### 请提供核心代码片段链接
https://sm.ms/image/s9nuyYxqDFEpMed

### 描述问题
[Bug Report] Slider 滑块 使用 双滑块模式  先拉动左变，再拉动右边。偶尔左边的值会改变。。

**Comment by shenjingnan** [comment]
官方无法复现
建议
- 使用官方代码，看是否能复现
- 建一个小程序代码片段，排除所有干扰因素，确认是由于组件引起的
