### ISSUE TITLE
[Bug Report] 文件上传accept类型为media，文件列表中有视频和图片时，预览index!=0的视频时显示的不正确，且切换视频无效

### ISSUE THREAD

**Issue by zuopengcy** [youzan/vant-weapp#4699]
### 设备
微信开发工具

### VantWeapp 版本
1.10.0

### 基础库版本
2.19.4

### 请提供核心代码片段链接
https://github.com/youzan/vant-weapp/blob/dev/packages/uploader/index.ts#L195

### 描述问题
文件列表经过过滤以后，当前文件的index应该重新计算，但是195行index用的还是全部文件列表的index，导致预览视频时出现问题

**Comment by landluck** [comment]
`v1.10.10` 已修复
