### ISSUE TITLE
[Bug Report] tab过多时，slot位置偏移

### ISSUE THREAD

**Issue by lzpswat** [youzan/vant-weapp#4700]
### 设备
微信开发者工具

### VantWeapp 版本
1.7.2

### 基础库版本
2.18.0

### 如果是 UI 问题，截图链接（多图回车分隔）

![截图](https://s2.loli.net/2021/12/25/eo4iUHMnBCSr62P.png)

![截图](https://s2.loli.net/2021/12/25/9hlmz5eXMyijgWu.png)

![截图](https://s2.loli.net/2021/12/25/nQTYpbwUfM67L5o.png)

### 请提供核心代码片段链接
https://gist.github.com/lzpswat/100099a8922eb5018d258761f219d1ac

### 描述问题
tab过多时，slot位置偏移，9个tab时，slot里面内容消失。

**Comment by lovegnep** [comment]
tab过多时，背景色变化了
<img width="376" alt="image" src="https://user-images.githubusercontent.com/29669264/228254371-4fdd2877-c7ad-4de9-aa73-41dce1323f7e.png">

**Comment by johnsonwong666** [comment]
没能复现  可以提供一个小程序代码片段吗?

**Comment by johnsonwong666** [comment]
van-tabs__scroll  增加样式 width: 90%

**Comment by landluck** [comment]
`v1.10.18` 已修复
