### ISSUE TITLE
[Feature Request] 希望添加一个浮动按钮模块

### ISSUE THREAD

**Issue by alair074** [youzan/vant-weapp#4701]
### 这个功能解决了什么问题
有时候有些页面需要展示，同时需要一个或多个按钮进行复杂的搜索，需要一个悬浮按钮来解决这个问题

### 建议的API是什么样的
通过点击悬浮的按钮去触发一个弹窗或任意方法

**Comment by shenjingnan** [comment]
目前官方暂时不会增加圆形浮动按钮，建议可以自己调整样式实现效果，并不复杂
