### ISSUE TITLE
[Bug Report] SubmitBar 提交订单栏的价格格式化问题

### ISSUE THREAD

**Issue by untiny** [youzan/vant-weapp#4703]
### 设备
Windows11

### VantWeapp 版本
1.10.0

### 基础库版本
2.20.1

### 请提供核心代码片段链接
https://github.com/youzan/vant-weapp/blob/819efae7c8cfb667f4160991564b76a4fc7fda08/lib/submit-bar/index.js#L44

### 描述问题
在组件submit-bar的updatePrice函数中price被除以100导致price降低了两位数

**Comment by shenjingnan** [comment]
单位：分
