### ISSUE TITLE
小程序开发者工具重新构建npm，调试工具会报错

### ISSUE THREAD

**Issue by fmyshine** [youzan/vant-weapp#4704]
### 设备
微信开发者工具

### VantWeapp 版本
1.10.0

### 基础库版本
2.16.1

### 如果是 UI 问题，截图链接（多图回车分隔）

![截图](https://s3.bmp.ovh/imgs/2021/12/defc3f25891c2c74.png)

### 请提供核心代码片段链接
无代码，官方demo也无法使用

### 描述问题
开发者工具构建npm后，项目引用van-filed组件，调试工具会报错

**Comment by shenjingnan** [comment]
尝试了下，按照官方快速上手可以完成构建
我的环境：
mac m1
vant-weapp@1.10.0
开发者工具1.05.2112141
调试基础库2.14.1

按照官方文档，新建空目录，在开发者工具中创建新的小程序，然后按照文档操作到第四部，在app.json中引入vant-button

**Comment by fmyshine** [comment]
是部分组件引用后，开发者工具调试工具会报错，譬如van-filed组件。把基础库2.16.1切换到基础库2.19.1就正常了
