### ISSUE TITLE
不同版本库会报错报ReferenceError: outerGlobal is not defined

### ISSUE THREAD

**Issue by 2447027763** [youzan/vant-weapp#4705]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater?repo=VantWeapp
![image](https://user-images.githubusercontent.com/73216624/147488036-0fa0ef55-1b5d-4dcc-8ae2-3ca03e4b7391.png)
![image](https://user-images.githubusercontent.com/73216624/147488111-1e98e34d-256b-4e9a-a10a-89385d85293e.png)

**Comment by shenjingnan** [comment]
不是vant-weapp引起，建议自行排查
