### ISSUE TITLE
自定义组件里调用vant组件报错

### ISSUE THREAD

**Issue by 2447027763** [youzan/vant-weapp#4706]
自定义组件里面调用vant组件，然后第二次用wx.navigateTo进入不管是那一个页面调用同一个自定义组件，微信小程序模拟器就会报错，手机真机运行没问题，注释掉自定义组件就不会报错，引入的自定义组件重复进也没问题，报完错所有vant组件失效，报错截图如下
![image](https://user-images.githubusercontent.com/73216624/147519758-5ad2b43e-f4e5-42a3-983c-dbab70aed79f.png)

![image](https://user-images.githubusercontent.com/73216624/147519988-dbc835e8-cbe6-4e30-ae69-d578a82c9495.png)
![image](https://user-images.githubusercontent.com/73216624/147520002-71016410-ba01-44ae-8ee9-693da391e067.png)
![image](https://user-images.githubusercontent.com/73216624/147520065-6088cd6c-cd7b-4e74-a48d-cc3e3f6e4ee8.png)

**Comment by shenjingnan** [comment]
建议你根据error提示自行排查，大概率不是vant-weapp我问题，可以求助搜索引擎或者问答社区
