### ISSUE TITLE
关于GRID和通知栏的问题

### ISSUE THREAD

**Issue by ding00529** [youzan/vant-weapp#4707]
1、https://vant-contrib.gitee.io/vant-weapp/#/grid
grid 如何开启圆角
2、https://vant-contrib.gitee.io/vant-weapp/#/notice-bar
通知栏如何让他上翻

**Comment by shenjingnan** [comment]
不清楚你是要报告feature还是要报告bug
如果是使用方面的问题，官方文档、搜索引擎、问答社区能帮助到你，issue区无法提供使用上的帮助
