### ISSUE TITLE
小程序vant-popup组件在ios手机上被遮挡

### ISSUE THREAD

**Issue by ode911** [youzan/vant-weapp#4708]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater?repo=VantWeapp
![L9WOT6D09RBIL13JR9HI(5J](https://user-images.githubusercontent.com/34083029/147634253-09ae9b04-4d34-4a5e-a845-043d024fc1c6.png)

**Comment by shenjingnan** [comment]
这个和组件库大概率没有关系，键盘是系统组件，popup内部使用的是小程序的view组件，你可以试下用小程序原生的view组件是不是也没推上去，应该是跟手机的系统版本、小程序版本、微信版本有关系
