### ISSUE TITLE
Popup 蒙版弹出时没有禁止滚动

### ISSUE THREAD

**Issue by GodStream** [youzan/vant-weapp#471]
**你需要的功能是？**
Popup 禁止背景滚动

**你期望 API 是什么样的？**

**Comment by chenjiahan** [comment]
暂时没有在小程序内找到合适的办法阻止滚动

**Comment by feelslive** [comment]
在弹出层加上 catchtouchmove 事件

例：
<van-popup catchtouchmove="ture">我是弹窗</van-popup>

亲测 在开发者工具上没效果，但是在真机上是可以禁止背景滚动的。

**Comment by maintheme-mili** [comment]
np 感谢大佬 解决了
