### ISSUE TITLE
calendar的default-date不能定位

### ISSUE THREAD

**Issue by SmileFuture** [youzan/vant-weapp#4713]
当poppable为false，即平铺的时候，设置了最小日期min-date  然后在设置默认日期default-date，日历视图不会滚动到默认月份日期   而是停在最小日期那一页

**Comment by Caichuanming** [comment]
同问

**Comment by qiaolin-pan** [comment]
同样的问题，求解决

**Comment by Rui2017s** [comment]
同问

**Comment by JerryWang24** [comment]
巨大的坑的

**Comment by niukui** [comment]
仍然没有解决

**Comment by niukui** [comment]
我同时设置max-date,min-date,default-date， default-date 根本不生效

**Comment by JoshuaFeng5** [comment]
仍然没有解决

**Comment by johnsonwong666** [comment]
可以提供一个复现代码片段过来吗？

**Comment by johnsonwong666** [comment]
> 可以提供一个复现代码片段过来吗？

@JoshuaFeng5 @niukui

**Comment by johnsonwong666** [comment]
![image](https://github.com/youzan/vant-weapp/assets/64689255/af1f9bbd-1364-4fee-9b6f-130a4fad0ab5)
<img width="802" alt="image" src="https://github.com/youzan/vant-weapp/assets/64689255/015a4c57-bcc6-46fd-8f20-6565e4975539">
没有复现，实测开发者工具和真机渲染时，会在default-date所有的月份

**Comment by johnsonwong666** [comment]
没有复现。由于较长时间没有提供复现代码片段，此issue暂时关闭，若还有问题请提新的issue,并附带复现代码片段排查。

**Comment by JoshuaFeng5** [comment]
你要选两天的







------------------ 原始邮件 ------------------
发件人: johnsonwong666 ***@***.***&gt;
发送时间: 2023年5月10日 15:02
收件人: youzan/vant-weapp ***@***.***&gt;
抄送: JoshuaFeng5 ***@***.***&gt;, Mention ***@***.***&gt;
主题: Re: [youzan/vant-weapp] calendar的default-date不能定位 (Issue #4713)





  没有复现，实测开发者工具和真机渲染时，会在default-date所有的月份

**Comment by johnsonwong666** [comment]
> 

多选日期？可以提供一下稳定的复现代码片段吗？
@JoshuaFeng5

**Comment by JoshuaFeng5** [comment]
你现在是什么版本
我通过改写， node_modules 中 日历的代码 ***@***.***/vantui/es/calendar/index.js


在        let start = limitDateRange(startDay || now, minDate, getPrevDay(new Date(maxDate)).getTime()); 
修改为


···


            const date = startDay || now;
            const start = limitDateRange(date, minDate,allowSameDay ? date : getPrevDay(new Date(maxDate)).getTime());
···
解决了我的问题， 你可以通过搜索 你的代码， 看看是不是你们已经修复了， 如果不是的话，重复以下步骤：
1 多选日期时候，、
2，设置最大和最小日期， 
3，然后默认值 的区间都选择最大值，
打开 就会出问题。


在 2023年5月10日 ***@***.***> 写道：


多选日期？可以提供一下稳定的复现代码片段吗？

**Comment by johnsonwong666** [comment]
@JoshuaFeng5 
我测试时vant-weapp 1.10.18版本，你是vant组件库吗？vant-weapp打包产物没有/vantui/es/calendar/index.js
