### ISSUE TITLE
[Feature Request] 如何自定义dialog的button的样式？

### ISSUE THREAD

**Issue by brownfoxsir** [youzan/vant-weapp#4716]
### 这个功能解决了什么问题
我想修改一下button的样式，翻了下文档，发现theme属性可以修改，但是只能改成“round-button“, 不能自定义按钮的样式，或者能有其他自定义button按钮样式的方法吗？如果有的话烦请大佬给小弟指条明路。

### 建议的API是什么样的
类似于weui的extClass ，可以指定button的样式类

**Comment by migue821** [comment]
你可以看看vant主页，左边菜单里-样式覆盖里面的内容
