### ISSUE TITLE
请问我想在新版本中继续在微信小程序中使用废弃Panel 面板组件有什么办法吗？

### ISSUE THREAD

**Issue by jiayouzl** [youzan/vant-weapp#4725]
https://vant-contrib.gitee.io/vant-weapp/#/panel
有没有什么办法？谢谢，我现在用的是weapp最新版本。

**Comment by shenjingnan** [comment]
官方不再维护 Panel 但是Panel的代码还在，你可以用最新版中的Panel

**Comment by jiayouzl** [comment]
> 官方不再维护 Panel 但是Panel的代码还在，你可以用最新版中的Panel

感谢!~
