### ISSUE TITLE
[Bug Report] 加入display:flex属性后，van-image不显示

### ISSUE THREAD

**Issue by migue821** [youzan/vant-weapp#4726]
### 设备
微信开发者工具

### VantWeapp 版本
1.9.2

### 基础库版本
2.19.3

### 请提供核心代码片段链接
https://github.com/migue821/code/blob/main/test

### 描述问题
想让图片居中，发现加了属性后，图片就无法显示了。
如果用width="100%"的话可以实现居中，但载入时的背景也是100%宽，就很难看。

也考虑过在image-class中让其居中，但是无效

**Comment by shenjingnan** [comment]
未复现
