### ISSUE TITLE
van-calendar中row-height修改后选择样式问题

### ISSUE THREAD

**Issue by mgf69** [youzan/vant-weapp#4728]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater?repo=VantWeapp
![image](https://user-images.githubusercontent.com/43037450/148041569-4d6e6ce5-5b62-47cc-ab7b-6be291922499.png)
微信小程序中使用日历组件，修改row-height之后默认选择的样式没有自适应，该如何解决呢？
<view>
    <van-calendar
    title="日历"
    poppable="{{ false }}"
    show-confirm="{{ false }}"
    class="calendar"
    max-date="{{ maxDate }}"
    row-height="32"
    color="#ffc20e"
    show-mark="{{ false }}"
    />
</view>

**Comment by shenjingnan** [comment]
已在1.10.2中修复
