### ISSUE TITLE
tabbar z-index代码错误

### ISSUE THREAD

**Issue by fangxingguang** [youzan/vant-weapp#473]
**描述一下问题**
错误：
style="{{ zIndex ? 'style: ' + this.zIndex : '' }}"
正确：
style="{{ zIndex ? 'z-index: ' + zIndex : '' }}"

**截图**
无

**环境**
 - 设备: 
 - 基础库版本: 
 - Vant Weapp 版本:master

**Comment by chenjiahan** [comment]
感谢反馈，这里确实有疏漏，已经在 dev 分支修复
