### ISSUE TITLE
Button组件小程序中为什么loading是可点击的，不理解

### ISSUE THREAD

**Issue by super-man-gif** [youzan/vant-weapp#4730]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater?repo=VantWeapp
正常来说，我们的button不应该在loading时是不可点击状态吗

**Comment by emnabs** [comment]
![微信截图_20220903023630](https://user-images.githubusercontent.com/12934341/188216986-fc00e98e-e12f-4508-a3e1-fdbda011c5f0.png)
查看源码发现 缺少disabled属性的赋值，加上后可实现禁止点击 @super-man-gif
