### ISSUE TITLE
[Bug Report] 小程序调试基础库2.21.3不能正确编译

### ISSUE THREAD

**Issue by zyp1573** [youzan/vant-weapp#4732]
### 设备
mac mini M1

### VantWeapp 版本
1.10.1

### 基础库版本
2.21.3

### 请提供核心代码片段链接
https://gist.github.com/zyp1573/d8d133b9c93c14ecb3034755a1bf9931

### 描述问题
微信开发者工具新建一个基础小程序项目，基础库版本选择2.21.3，app.json 填写片段所示即可复现

**Comment by shenjingnan** [comment]
[demo.zip](https://github.com/youzan/vant-weapp/files/7840419/demo.zip)
应该是你自己使用问题，我按照官方快速上手走了一遍没问题

**Comment by WenWingGit** [comment]
我也是，我用的最新的开发版本，解决了吗
