### ISSUE TITLE
无法找到模块 “@vant/weapp/dist/toast/toast” 的声明文件。

### ISSUE THREAD

**Issue by baqihg** [youzan/vant-weapp#4735]
![image](https://user-images.githubusercontent.com/18044550/148653742-acefd54f-907d-4196-b37a-70c6f20b9e80.png)
看了下 node_modules 的代码里面，确实没有 d.ts 声明文件？
![image](https://user-images.githubusercontent.com/18044550/148653802-b8dd8ce6-c9ce-49f6-9197-991c2906b1d9.png)
找了整个包里面都没有看到对应的 d.ts 文件，是误删了么？

**Comment by shenjingnan** [comment]
已在1.10.2中修复

**Comment by Hhhha** [comment]
> 已在1.10.2中修复

好像还是一样

**Comment by callmegaga** [comment]
@nemo-shen 在1.11.3还是有同样错误提示
