### ISSUE TITLE
[Bug Report] DatetimePicker返回的时间没有时分秒

### ISSUE THREAD

**Issue by mijaclan** [youzan/vant-weapp#4737]
### 设备
微信者开发工具

### VantWeapp 版本
1.9.2

### 基础库版本
2.21.2

### 如果是 UI 问题，截图链接（多图回车分隔）

![截图](https://s2.loli.net/2022/01/09/vnqfaYMlHeJkmR5.png)

![截图](https://s2.loli.net/2022/01/09/KQiIJ6xzfgVtL1k.png)

### 请提供核心代码片段链接
https://github.com/youzan/vant-weapp/issues/4736

### 描述问题
DatetimePicker返回的时间没有时分秒，时间戳返回了年月日没有时分秒

**Comment by shenjingnan** [comment]
你的复现代码不对吧，没看到你用了VanDatetimePicker，官方示例测了下没问题

**Comment by mijaclan** [comment]
import React, { useEffect, useState } from 'react';
import VanPopup from '@vant/weapp/lib/popup';
import styles from '../styles/item.less';
import { Input, Text, View } from 'remax/wechat';
import VanDatetimePicker from '@vant/weapp/lib/datetime-picker';
import manba from 'manba';

const DateTime = ({
  label = 'dateTime',
  placeholder = '请选择',
  name,
  title = '选择年月日',
  type = 'datetime',
  value = null,
  onChange,
  format = 'YYYY-MM-DD HH:mm:ss',
}) => {
  const [show, setShow] = useState(false);
  const [time, setTime] = useState(null);
  let valueDate = new Date().getTime();
  const maxDate = new Date().getTime() + 24 * 3600 * 1000 * 365 * 100;
  const minDate = new Date('1970-01-01').getTime();

  useEffect(() => {
    if (value !== null) {
      setTime(value);
    }
  }, []);

  function bindConfirm(e) {
    setTime(manba(e.detail).format(format));
    setShow(false);
  }

  function bindCancel() {
    setShow(false);
  }

  return (
    <>
      <View className={styles.Item}>
        <Text className={styles.text}>{label}</Text>
        <View
          onClick={() => {
            setShow(true);
          }}
        >
          {time ? (
            <Text className={styles.tip}>
              {time}
              <Input name={name} value={time} disabled={true} style={{ display: 'none' }} />
            </Text>
          ) : (
            <Text className={styles.selectText}>{placeholder}</Text>
          )}
          <Text className={`${styles.triangleIcon} iconfont icon-a-30_xialajiantou`} />
        </View>
      </View>
      <VanPopup
        position={'bottom'}
        customStyle={'height: 50%'}
        show={show}
        bindclose={() => setShow(false)}
      >
        <VanDatetimePicker
          title={title}
          value={valueDate}
          minDate={minDate}
          maxDate={maxDate}
          bindconfirm={bindConfirm}
          bindcancel={bindCancel}
          bindchange={onChange}
          type={type}
        />
      </VanPopup>
    </>
  );
};

export default DateTime;

**Comment by mijaclan** [comment]
> 你的复现代码不对吧，没看到你用了VanDatetimePicker，官方示例测了下没问题

DateTime是关键字git屏蔽掉了

**Comment by mijaclan** [comment]
![image.png](https://s2.loli.net/2022/01/12/KlSW7nikZMq6sxG.png)

**Comment by shenjingnan** [comment]
根据快速上手文档跑一个最小demo可复现我看下，排除所有其他干扰，比如说React

代码创建个git仓库push上来，贴个链接，

**Comment by landluck** [comment]
无法复现，如还有问题，需要提供个简易demo
