### ISSUE TITLE
SwipeCell不能上下滚动

### ISSUE THREAD

**Issue by crisslin** [youzan/vant-weapp#4738]
SwipeCell不能上下滚动，何解？

**Comment by shenjingnan** [comment]
1. 官方示例 && 本地调试未复现你说的问题
2. 请检查自己的业务代码
3. 请按照规范提issue，不规范的issue将会被关闭

**Comment by crisslin** [comment]
小程序中，SwipeCell不能上下滑动，何解？
普通的Cell没问题
