### ISSUE TITLE
小程序中，SwipeCell不能上下滑动，何解？

### ISSUE THREAD

**Issue by crisslin** [youzan/vant-weapp#4744]
Version：v1.10.1
小程序中，SwipeCell不能上下滑动，何解？
SwipeCell 中，设置了左滑、右滑 展现操作按钮后，整个SwipeCell 便不能上下滑动
普通的Cell没问题

**Comment by shenjingnan** [comment]
提供最小可复现代码

**Comment by crisslin** [comment]
> 普通的Cell没问题

经过单独测试，发现是css导致无法滚动
`.van-swipe-cell {
    touch-action: none;
}`
添加该代码，是因为使用siwpecell过程中，有时候会报渲染错误
`Ignored attempt to cancel a touchmove event with cancelable=false, for example because scrolling is in progress and cannot be interrupted.`
现删除该代码后恢复正常。
---------------------------
BTW：为何通过微信开发者工具，真机调试的时候，使用vant组件的页面 比较卡顿（比如选择日期、或者滑动swipecell），发布到线上版本与体验版不会卡？

**Comment by landluck** [comment]
目前已经没有该样式，如还有问题，提供可复现的小程序代码片段后重新提交 issue，小程序代码参考 https://developers.weixin.qq.com/miniprogram/dev/devtools/minicode.html
