### ISSUE TITLE
请问后续有没有可能支持统一样式覆盖及统一props覆盖

### ISSUE THREAD

**Issue by KangLinDDD** [youzan/vant-weapp#4747]
现在很多情况下需要全局覆盖vant的一些默认样式以便实现具有企业风格的ui，目前全局样式是可以实现覆盖的，但是有没有可能props也可以实现动态配置？

就比如field的placeholder-style，如果整个项目都需要修改，就会很麻烦，而直接修改miniprogram_npm中的props value值就会很方便

**Comment by shenjingnan** [comment]
ConfigProvider

**Comment by daowojia** [comment]
ConfigProvider 只是覆盖 ConfigProvider包裹的样式, 全局body样式根本不让动态覆盖,真奇葩,也不看看element,动态覆盖多好用,

**Comment by KangLinDDD** [comment]
可以全局配置一些变量的，vant有配置一些变量，可以改的比如  --cell-vertical-padding这种

**Comment by chenjiahan** [comment]
> ConfigProvider 只是覆盖 ConfigProvider包裹的样式, 全局body样式根本不让动态覆盖,真奇葩,也不看看element,动态覆盖多好用,

Element 和 vant-weapp 不是一个维度的东西，小程序里压根没有 body 标签。

**Comment by daowojia** [comment]
走错片场了,本来是批评vant 不让覆盖 var 样式的
