### ISSUE TITLE
[Bug Report] 对应好多组件的API方法对外时无效

### ISSUE THREAD

**Issue by yunzhiheyi** [youzan/vant-weapp#4749]
### VantWeapp 版本
1.10.2

### 基础库版本
2.21.2

### 描述问题
例如：
slider组件
1、在使用时drag-start和drag-end无效，经过排查是命名的问题。改成dragstart和dragend测试有效【这个问题好多组件应该都有此问题，建议排查】
2、当slider组件max值是动态获取时，这个值一直是0，会导致组件初始化时报NuN异常

**Comment by shenjingnan** [comment]
问题1：
官方示例测试了下并没有发现drag-start有什么问题，代码中我们也写的是emit('drag-start'); 建议你可以按照官方快速上手指南跑一个demo试试

问题2：
max动态获取没什么问题，可能是你在初始的时候不是一个Number类型，建议还是传递一个值试下
