### ISSUE TITLE
[Bug Report] van-button 默认字体问题

### ISSUE THREAD

**Issue by jacksoong007** [youzan/vant-weapp#4750]
### 设备
安卓机型

### VantWeapp 版本
1.9.2

### 基础库版本
2.21.2

### 请提供核心代码片段链接
https://gitee.com/fzsong3/codes/cp6sdurv2519gxmqlh3kt41

### 描述问题
微信6.0版本开始，在IOS上的中文字体是苹方/PingFangSC，英文字体是SFUIDisplay。在安卓上的中文字体是思源黑体，英文字体是Robot。
但是使用的van-button组件么有使用“思源黑体，英文字体是Robot”，而是跟随了系统字体，导致字体显示不一致。问题截图见Gitee代码片段

**Comment by shenjingnan** [comment]
@s958024860 gitee 访问受限

**Comment by jacksoong007** [comment]
@nemo-shen 代码改为公共仓库
https://gitee.com/fzsong3/test/blob/master/van-button/index.wxml
程序截图
https://gitee.com/fzsong3/test/blob/master/van-button/van-button.jpeg

**Comment by shenjingnan** [comment]
组件库内部font-family都继承自var.less，应该不是组件库的问题，你可以看下在微信里搜索下vant-weapp看下官方示例

另外可以检查下你的业务代码

**Comment by shenjingnan** [comment]
issue我先关闭了
