### ISSUE TITLE
[Feature Request] 希望area组件增加控制tool-bar显示功能

### ISSUE THREAD

**Issue by lzpswat** [youzan/vant-weapp#4751]
### 这个功能解决了什么问题
打算用area配合DropdownMenu下拉菜单使用，发现无法关闭上面的确认取消按钮。上传了个图片进图床（https://sm.ms/image/xPitdvK2VMySQg9）

### 建议的API是什么样的
参考picker,增加个show-toolbar

**Comment by landluck** [comment]
功能已支持
