### ISSUE TITLE
[Bug Report] TS编译错误

### ISSUE THREAD

**Issue by hoperce** [youzan/vant-weapp#4755]
### 设备
微信小程序

### VantWeapp 版本
1.10.2

### 基础库版本
2.21.2

### 请提供核心代码片段链接
https://github.com/youzan/vant-weapp

### 描述问题
import { VantComponentOptions } from 'definitions/index'; => import { VantComponentOptions } from '../definitions/index';

**Comment by landluck** [comment]
具体什么情况下编译错误呢？
