### ISSUE TITLE
日历组件星期和日期不对应(vant weapp官方小程序体验版)

### ISSUE THREAD

**Issue by birdyy79** [youzan/vant-weapp#4756]
![101642082748_ pic](https://user-images.githubusercontent.com/2109243/149344674-bb34a4f0-8859-40a7-845b-2c812394f9f5.jpg)

**Comment by idleglass** [comment]
+1

**Comment by xinde** [comment]
![ddcd8d973e21d61e976fa463e7ef02d](https://user-images.githubusercontent.com/1617414/162102657-5aafc6c3-0c75-4569-84b3-a76f7ae64a57.jpg)
四月六号应该星期三  

版本 "@vant/weapp": "^1.9.2"

```js
// @vant\weapp\lib\calendar\components\month\index.wxs
 var current = getDate(date).getUTCDay() || 7; // getDay 改为 getUTCDay
```
bug已出，绩效已扣 😂
