### ISSUE TITLE
[Feature Request] tab标签页组件缺少基本的必要功能

### ISSUE THREAD

**Issue by sdlddr** [youzan/vant-weapp#4757]
### 这个功能解决了什么问题
weapp版的tab标签页，还没有自定义标题内容的功能（其它版本上已经提供了slot插槽）、以及滚动导航的功能。

### 建议的API是什么样的
下一个发布版本中，全都加上

**Comment by landluck** [comment]
https://github.com/youzan/vant-weapp/issues/4431
