### ISSUE TITLE
[Bug Report] 1.10.2版本下，tabs标签完全无效

### ISSUE THREAD

**Issue by sdlddr** [youzan/vant-weapp#4760]
### 设备
所有设备

### VantWeapp 版本
1.10.2

### 基础库版本
2.19

### 请提供核心代码片段链接
https://github.com/youzan/vant-weapp/issues

### 描述问题
1.10.2版本下，tabs标签完全无效
代码如下：
`<van-tabs sticky animated color="{{page.primaryColor}}"
 style="--font-weight-bold:bold;--tab-font-size:30rpx;--tab-active-text-color:{{page.primaryColor}}">
  <van-tab title="活动专区" info='Hot'></van-tab>
  <van-tab title="手机"></van-tab>
  <van-tab title="泛终端"></van-tab>
  <van-tab title="配件"></van-tab>
  <van-tab title="物联网"></van-tab>
  <van-tab title="权益"></van-tab>
  <van-tab title="其他"></van-tab>
</van-tabs>`

**Comment by zhihuifanqiechaodan** [comment]
tabs标签完全无效是指什么？

**Comment by sdlddr** [comment]
sticky属性完全无效

**Comment by TY-LIU** [comment]
我猜测你的父级容器用到了`scroll-view`，这个问题我上周也遇到过。
使用了`scroll-view`的自定义下拉刷新就会失效，**因为van-tabs的sticky是用的fixed，`scroll-view`自定义下拉用到了`transform`，会导致position：fixed降级为absolute，所以sticky会失效**。 如果把固定的方式改为`position: sticky` 实现，应该能彻底解决这个问题。
此处 @nemo-shen 

如果你又想使用下拉刷新，又想用到sticky，就得使用放弃使用`scroll-view`的自定义下拉刷新，改为页面整体下拉，在你页面json中加`"enablePullDownRefresh": true`，然后在`onPullDownRefresh` 和 `onReachBottom`中实现下拉刷新，上拉加载就可以了。

另外，我实在是忍不住想吐槽，哥们你提的这issue太没水平了，问题描述得含糊不清，还要别人来猜，效率极其低下。贴的代码也是就那么一点，玉帝来了都不能给你解决了，还不格式化。 而且这样的标题开发人员看到都能血压拉满，我是开发者看到这种标题直接就给关了，建议去阅读下[提问的艺术](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md)

**Comment by shenjingnan** [comment]
@landluck 确认下 <van-sticky /> 组件 `position: fixed` 是否可以调整成 `position: sticky`

**Comment by johnsonwong666** [comment]
#4922

**Comment by johnsonwong666** [comment]
该issue 在vant-weapp2.0 解决

**Comment by johnsonwong666** [comment]
补充一点。实测下来，scroll-view 里面开启下拉刷新  里面的元素的postion会无效 不管是fixed/还是sticky 这可能是官方的一个bug，社区也有讨论，如有这种场景尝试页面级别的下拉刷新。
<img width="1243" alt="image" src="https://github.com/youzan/vant-weapp/assets/64689255/64e8ebef-c21f-4e69-adb0-b7e7ccb4b28c">
