### ISSUE TITLE
[Bug Report] 复选框样式丢失，完全不能用了

### ISSUE THREAD

**Issue by sdlddr** [youzan/vant-weapp#4762]
### 设备
所有设备

### VantWeapp 版本
1.10.2

### 基础库版本
2.19

### 请提供核心代码片段链接
http://vant-contrib.gitee.io/vant-issue-generater/?repo=VantWeapp#/zh-CN?repo=VantWeapp

### 描述问题
空白的新建页面上已经完全无法重现demo中“基础用法”的样子了，定击事件无效，样式不变，且复选框应用的样式完全丢失。完全不能用了。现在更新的质量真的越来越差了。
`<van-checkbox` value="{{ checked }}" `bind:change="onChange">复选框</van-checkbox>`

**Comment by linbuxiao** [comment]
建议自己开下 PR 尝试修一下呢

**Comment by landluck** [comment]
样式问题可以提供截图哦，目前看是没有问题的
