### ISSUE TITLE
[Bug Report] popup中引用popup会出现新popup被遮挡的问题

### ISSUE THREAD

**Issue by ysllyfe** [youzan/vant-weapp#4763]
### 设备
iphone13 iphone12

### VantWeapp 版本
1.9.1

### 基础库版本
2.21.0

### 请提供核心代码片段链接
https://www.yuque.com/docs/share/dc045419-72ec-40fc-b9d1-3c3ae20fd2c4

### 描述问题
<van-popup>中包含一个component，component用van-grid构建结果，van-grid-item调用新的van-popup。但是如果van-grid-item大于一排的情况，弹出的van-popup会被最外层van-popup遮挡，如果van-grid-item在一排内（小于4）个，没有这个问题。

**Comment by landluck** [comment]
根据提供的代码没能复现，如还能复现，可以根据 https://developers.weixin.qq.com/miniprogram/dev/devtools/minicode.html 提供一个可复现的小程序代码片段后重新打开 issue
