### ISSUE TITLE
[Bug Report] 循环引用问题

### ISSUE THREAD

**Issue by YYL1999** [youzan/vant-weapp#4771]
### 设备
Mac微信开发工具

### VantWeapp 版本
1.10.2

### 基础库版本
2.21.2

### 请提供核心代码片段链接
https://codesandbox.com

### 描述问题
当使用tab组件时，会报错canIUseGroupSetData函数找不到，打断点观察npm构建后的代码发现common/utils中引入的version文件找不到，看到version和utils文件有相互引用，猜想应该是这个原因，测试将version所需要的函数直接复制过来，发现没有问题，麻烦看一下哈

**Comment by YYL1999** [comment]
同时MiniProgramError
wx.canIUse 这个函数也会报错 插件模式开发

**Comment by blinkJun** [comment]
奇怪的是小程序开发没有报错，开发小程序插件的时候就出现了。而且有段代码我完全看不懂，是不是我太菜了。

`if ((0, version_1.canIUseNextTick)()) {}`

这个是什么写法？

**Comment by YYL1999** [comment]
> 

这是打包之后的代码 看不懂正常  我现在做法是把代码copy一份 把循环引用的地方改掉了 只保留了我需要的组件

**Comment by landluck** [comment]
已修复
