### ISSUE TITLE
dialog 底部存在白色横线

### ISSUE THREAD

**Issue by xkhanhan** [youzan/vant-weapp#4773]
设备
微信小程序

VantWeapp 版本
1.10.2

基础库版本
2.17.0

截图
https://img01.yzcdn.cn/upload_files/2022/01/26/Fl8Wg8xjOjXjKQjBj2EinVkXIH0M.jpg

核心代码片段链接
html

<van-dialog
use-slot
title="邀请规则"
show="{{ isShowRule }}"
show-confirm-button="{{false}}"
catchtouchmove="ture"
custom-style="overflow: visible;"

活动时间：\n即日起至2022年4月30日\n参与规则：\n1、发型师在“先锋发型师欧莱雅PRO”小程序注册认证成功后，即可发起邀请好友活动。\n2、发型师可在活动页面，点击邀请好友按钮，将小程序卡片或邀请海报分享给好友；\n被邀请好友仅可通过发型师分享的小程序卡片或邀请海报参与活动，完成注册并认证成功，即算邀请成功。\n3、被邀请好友，需为未注册过“先锋发型师欧莱雅PRO”小程序的新用户。\n参赛规则：\n1、参加者必须为中国公民。\n2、参加者年龄须在2021年6月15前满18周岁。\n3、欧莱雅（中国）有限公司的员工以及其相关利益相关人员不得参与赛事。\n4、所有奖品不得兑换现金，亦不可转让。\n*以上活动解释权归欧莱雅（中国）有限公司 我知道了
css :
.btn-wid {
width: 91.4%;
font-weight: 800;
}

.btn-task {
margin-top: 16px;
font-size: 14px;
display: flex;
justify-content: center;
}

.btn-task_dec {
font-size: 12px;
color: #969799;
display: flex;
justify-content: center;
}

.wrapper {
display: flex;
flex-direction: column;
align-items: center;
justify-content: center;
height: 100%;
}

.wrapper-icon {
width: 100%;
margin-bottom: 15px;
display: flex;
justify-content: flex-end;
}

.dashboard-position_popup__title {
padding-top: 1vh;
display: flex;
justify-content: center;
font-size: 20px;
}

.dashboard-position_popup__desc {
display: flex;
justify-content: center;
font-size: 30rpx;
padding: 30rpx;
color: #3e3a3e;
}

.dashboard-position_popup__button {
display: flex;
justify-content: center;
width: 80%;
}

.share-dialog .van-share-sheet__options {
justify-content: space-around;
}

.invite {
width: 686rpx;
height: 560rpx;
border-radius: 16rpx;
border: 2rpx solid #EBEDF0;
margin-left: 32rpx;
margin-top: 48rpx;
}
.invite .topTip {
width: 394rpx;
height: 76rpx;
border-radius: 0 0 40rpx 40rpx;
background: #F2F3F5;
margin-left: 146rpx;
margin-bottom: 32rpx;
font-family: PingFangSC-Medium;
font-size: 32rpx;
color: #323233;
text-align: center;
line-height: 76rpx;
}

.scrollView {
height: 452rpx;
width: 686rpx;
/* padding: 0 32rpx;
box-sizing: border-box; */
}

.scrollView .item {
width: 686rpx;
height: 72rpx;
margin-bottom: 32rpx;
display: flex;
align-items: center;
position: relative;
padding: 0 32rpx;
box-sizing: border-box;
}

.scrollView .item:nth-last-child(1) {
margin-bottom: 0;
}

.scrollView .item image {
width: 72rpx;
height: 72rpx;
border-radius: 50%;
}

.scrollView .item .name {
font-family: PingFangSC-Regular;
font-size: 28rpx;
color: #323233;
margin-left: 32rpx;
width: 252rpx;
white-space: nowrap;
text-overflow: ellipsis;
overflow: hidden;
text-align: left;
}

.scrollView .item .time {
font-family: PingFangSC-Regular;
font-size: 28rpx;
color: #969799;
position: absolute;
top: 18rpx;
right: 32rpx;
}

.rule_btn {
position: absolute;
right: 0;
top: 60rpx;
opacity: 0.7;
background: #323233;
border-radius: 200rpx 0 0 200rpx;
width: 88rpx;
height: 48rpx;
font-family: PingFangSC-Regular;
font-size: 28rpx;
color: #FFFFFF;
text-align: center;
line-height: 48rpx;
}

.rule_dialog {
position: relative;
display: flex;
flex-direction: column;
align-items: center;
width: 100%;
height: 588rpx;
border-radius: 32rpx;
}

.rule_dialog .rule_scroll {
width: 526rpx;
height: 452rpx;
margin: 16rpx 0;
font-family: PingFangSC-Regular;
font-size: 28rpx;
color: #323233;
line-height: 40rpx;
}

.rule_dialog button {
width: 526rpx;
height: 72rpx;
background: #000000;
border-radius: 36rpx;
font-family: PingFangSC-Regular;
font-size: 28rpx;
color: #FFFFFF;
text-align: center;
line-height: 72rpx;
}

.rule_dialog .close {
position: absolute;
top: -164rpx;
right: 0;
}

.placeholderBox {
width: 100vw;
height: 124rpx;
background-color: #FFFFFF;
}

.placeholderBox_X {
height: 56rpx;
}

.van-dialog__footer {
display: none !important;
}

.rule_scroll .font {
font-family: PingFangSC-Medium;
margin-bottom: 8rpx;
display: inline-block;
}

.rule_scroll .bot {
margin-bottom: 32rpx;
display: inline-block;
}

描述问题
dialog 底部存在的白色横线，主要是由于 .van-dialog__footer:after 给了 1px 的白色横线，用于dialog 确认和取消 按钮的上方，但我目前的需求是不要 dialog 的按钮，那么 van-dialog__footer:after 应该是不存在，而不是 被 .van-dialog 中的 overflow：hidden 给隐藏了，

**Comment by landluck** [comment]
`v1.10.10` 已修复
