### ISSUE TITLE
[Bug Report] Popup组件custom-style属性使用display:flex导致的问题

### ISSUE THREAD

**Issue by shenghuitian** [youzan/vant-weapp#4774]
### 设备
安卓、iOS

### VantWeapp 版本
1.10.2

### 基础库版本
2.15.0

### 描述问题
背景：在van-popup的custom-style属性中使用display:flex，popup内有一个按钮，popup显示时，假设按钮在屏幕中所处的位置为(x，y)
问题：popup隐藏后，点击屏幕(x，y)的位置仍然会触发按钮的handleClick点击事件，就好像popup中的按钮还在页面最上层一样

代码：
`<van-popup show="{{ show }}" custom-style="display: flex;">
  <view bindtap="handleClick">按钮</view>
</van-popup>`

**Comment by landluck** [comment]
popup 是通过 display: none 来进行隐藏显示控制的，display: flex 覆盖掉默认样式，导致逻辑异常，建议可以在 popup 内部再包装一层来进行样式布局

**Comment by shenghuitian** [comment]
您好，您发给我的邮件已收到。
