### ISSUE TITLE
[Bug Report] windows模式下上传组件无法选中文件

### ISSUE THREAD

**Issue by chuangyi110** [youzan/vant-weapp#4775]
### 设备
windows 微信小程序

### VantWeapp 版本
1.10.2

### 基础库版本
2.19.2

### 请提供核心代码片段链接
https://gist.github.com/chuangyi110/df320c6f89f3f7687e5aadbffa115ed2#file-gistfile1-txt

### 描述问题
windows微信小程序 点击上传组件选择后无法调起上传。微信开发平台可以上传  手机端也可以上传  windows模式下无法上传

**Comment by landluck** [comment]
微信兼容问题，组件无法解决，可以在微信社区向微信反馈
