### ISSUE TITLE
内置样式无法import

### ISSUE THREAD

**Issue by wowxunlian** [youzan/vant-weapp#4776]
按照官网教程，使用内置样式前需要引入：
引入
在 app.wxss 中引入内置样式。

@import '@vant/weapp/common/index.wxss';
结果文件找不到：
[ WXSS 文件编译错误] ./app.wxss
File not found: @vant/weapp/common/index.wxss(env: Windows,mp,1.05.2111300; lib: 2.14.1)

**Comment by OnePieceJoker** [comment]
这个issue应该可以解决你的问题：#673
