### ISSUE TITLE
微信开发工具没有 『使用npm模块』 选项，安装vant 各种报错或者引入不生效

### ISSUE THREAD

**Issue by peter100u** [youzan/vant-weapp#4789]
微信开发中工具版本 1.05.2201240 最新版本，没有 详情 -> 本地设置 ->  使用npm模块 选项， 
按照vantwapp官方安装方法，引入成功，但是每次使用新的vant组件， 编译源码，模拟器不生效， 必须要 点击： 微信开发中工具 ： 工具 -> 构建npm ，才能生效，请问vant安装说明是否需要更新，才能解决我出现的问题

**Comment by 110sec** [comment]
不用叭，只要点击一次构建就用使用，你app.json里的针对组件那行设置去掉了吗

**Comment by landluck** [comment]
https://vant-contrib.gitee.io/vant-weapp/#/quickstart
