### ISSUE TITLE
[Bug Report] [Component] slot "" is not found. 

### ISSUE THREAD

**Issue by sdlddr** [youzan/vant-weapp#4790]
### 设备
所有设备

### VantWeapp 版本
1.9.2

### 基础库版本
2.19.*

### 请提供核心代码片段链接
https://github.com/youzan/vant-weapp/issues/4676

### 描述问题
很多vant组件在引入后打开会大量报 [Component] slot "" is not found.错误日志，经查是小程序基础库有更新了，那么为什么vant不作适应更新呢？反而把责任推给微信官方？难道要我们去修改基础库内核？

**Comment by chenjiahan** [comment]
参见 https://github.com/youzan/vant-weapp/issues/4390

里面有相关解释

**Comment by sdlddr** [comment]
网上已有人给出了解决方案，
`<view wx:else style="display:none"><slot /></view>`
能否一直不解决，就看官方够不够懒了
