### ISSUE TITLE
[Bug Report] stepper手动设置value无效果，通过input输入的值无法修改

### ISSUE THREAD

**Issue by jingxiawl** [youzan/vant-weapp#4791]
### 设备
微信小程序开发工具1.05.2201240

### VantWeapp 版本
1.9.2

### 基础库版本
2.13.0

### 请提供核心代码片段链接
https://gist.github.com/jingxiawl/e5a08337642a192fdd180ff3576af2a8

### 描述问题
stepper设置了value，但是通过input输入数字，再设置value的值不起效果（例如在input 输入12，我在onchange拿到输入的值之后设置value为1，但是stepper里面显示的还是12），还是显示的输入的值

**Comment by landluck** [comment]
可以开启 async-change 来手动控制输入的值
