### ISSUE TITLE
最新版的vant weapp中，引入van-field后，页面一片空白

### ISSUE THREAD

**Issue by vgri-z** [youzan/vant-weapp#4792]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater?repo=VantWeapp

**Comment by limstash** [comment]
引入 `van-picker` 和 `van-field` 后遇到了相同的问题，基础库版本调至 2.18.0 以上暂时解决

**Comment by qqccyv** [comment]
目前2.17.0-2.20.0 之间的基础库版本暂时没问题，2.20.0之后的也会空白

**Comment by 1259364843** [comment]
我也遇到同样问题，使用van-field组件，空白

**Comment by 1259364843** [comment]
> 你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。
> 
> http://vant-contrib.gitee.io/vant-issue-generater?repo=VantWeapp

**Comment by 1259364843** [comment]
> 你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。
> 
> http://vant-contrib.gitee.io/vant-issue-generater?repo=VantWeapp
这上面无法选择vant版本

**Comment by NDR0216** [comment]
最新版2.22.1有這問題 2.19.6可用

**Comment by MW-S** [comment]
把filed中引入input.wxml和textarea.wxml两个文件直接复制粘贴过来就好了，别用include,不知道是不是微信的BUG

**Comment by zhangbanghui** [comment]
> 最新版2.22.1有這問題 2.19.6可用

我基础库切换到2.19.6后可以正常使用了，但是线上用户的基础库版本不一致的话是不是还会出现这种问题，我有多个组件都出现了导入后白屏现象。

**Comment by CroMarmot** [comment]
我这 `2.22.0`也是炸的，`2.23.1` 可用

**Comment by landluck** [comment]
基础库变更引起的问题往往是微信的问题，如还有问题，请重新提交 issue

**Comment by 13873342501** [comment]
app.json里卖弄看看是不是加了 componentFramework:'glass-easel',加了这个和vant-field源码会冲突

**Comment by 13873342501** [comment]
app.json里面看看是不是加了 componentFramework:'glass-easel',加了这个和vant-field源码会冲突

**Comment by guoguottb** [comment]
van-tabs在原生小程序中引入会导致页面空白，求大神帮忙解决
