### ISSUE TITLE
使用picker拖动时感觉卡顿很严重

### ISSUE THREAD

**Issue by yefeihan** [youzan/vant-weapp#4793]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater?repo=VantWeapp

**Comment by yefeihan** [comment]
有没有什么解决办法，上传至体验版本后我用华为P40试用，拖动明显有卡顿感，没有原生丝滑

**Comment by landluck** [comment]
正常情况应该没有问题，请问是怎么使用的？
