### ISSUE TITLE
电脑端win10  uploader 上传不了文件 

### ISSUE THREAD

**Issue by lcy7** [youzan/vant-weapp#4799]
电脑端win10  uploader 上传不了文件 （用创建bug的链接选择不了vant版本，提交不了）
bug图地址： https://s2.loli.net/2022/02/17/uS7MfDnRbprFwla.png
代码图地址：https://s2.loli.net/2022/02/17/5vMRasf4KpUISgk.png

**Comment by landluck** [comment]
现在应该可以了，当时应该是微信小程序的问题，vant weapp 没有什么特殊的
