### ISSUE TITLE
小程序版本的Tab组件 没有滚动导航的功能，还是因为我没有更新到最新版本？

### ISSUE THREAD

**Issue by aAxiong** [youzan/vant-weapp#4800]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater?repo=VantWeapp

**Comment by zhushun05** [comment]
好像小程序就是没有

**Comment by yufengkz** [comment]
https://vant-contrib.gitee.io/vant-weapp/#/tab   滚动导航       小程序的demo在哪  现在还没有嘛？

**Comment by landluck** [comment]
具体是什么样的滚动导航呢
