### ISSUE TITLE
能否做一组字体class,方便我们引用

### ISSUE THREAD

**Issue by neozhu** [youzan/vant-weapp#4803]
Default:
H1 - H6
Subtitle1 Subtitle2
Body1 Body2
Button
Caption
Overline

FontFamily | String[] | Roboto, Helvetica, Arial, sans-serif | --mud-typography-default-family |  
FontWeight | Int32 | 400 | --mud-typography-default-weight |  
FontSize | String | .875rem | --mud-typography-default-size |  
LineHeight | Double | 1.43 | --mud-typography-default-lineheight |  
LetterSpacing | String | .01071em | --mud-typography-default-letterspacing |  
TextTransform | String | none | --mud-typography-default-text-transform |

**Comment by chenjiahan** [comment]
暂无计划提供喔
