### ISSUE TITLE
vant-tabs的info图标右上角提示信息显示异常

### ISSUE THREAD

**Issue by Mya123** [youzan/vant-weapp#4804]
[原应该显示的数字没有显示出来](http://vant-contrib.gitee.io/vant-issue-generater?repo=VantWeapp
)

**Comment by landluck** [comment]
无法判断问题，可以提供些代码片段

**Comment by wdpgithub** [comment]
![image](https://github.com/youzan/vant-weapp/assets/42329686/086802b7-5eb3-4def-aecb-5cbab0f9f71e)
