### ISSUE TITLE
不npm安装vant_weapp,只把需要用到的组件文件放在本地文件夹

### ISSUE THREAD

**Issue by swy0920** [youzan/vant-weapp#4809]
为了减轻代码包的大小，新建一个名为vant_weapp的文件夹，只把和dropdown相关的文件单独复制在这个文件夹中，但是发生了如图所示的样式问题，订单类型位置跑偏了，不知道是啥原因。。。
![e1eef6612651f6a2f1bc96f85776789](https://user-images.githubusercontent.com/52620500/156138123-f49ea545-97a8-461e-b131-958b7172ae43.jpg)

http://vant-contrib.gitee.io/vant-issue-generater?repo=VantWeapp

**Comment by landluck** [comment]
样式问题，建议检查下CSS文件是否正常引入了
