### ISSUE TITLE
[Feature Request] 关于[Component] slot "" is not found警报的解决方案

### ISSUE THREAD

**Issue by sdlddr** [youzan/vant-weapp#4815]
### 这个功能解决了什么问题
网上已经有人给出了解决方案，至于能否一直保持问题不解决，就看官方够不够懒了

### 建议的API是什么样的
修改所有爆出此警报的VANT组件，加上如下这段：
`<view wx:else style="display:none"><slot/></view>`

**Comment by J1Kami** [comment]
666，真的解决了，大佬，加上这段应该没什么其他影响吧？

**Comment by HWT-coder** [comment]
**我的评价是：雀食是酱紫的。**建议所有组件都加入默认的插槽，这样微信开发者工具检查就不会警告

**Comment by a531267910** [comment]
very good

**Comment by chenjiahan** [comment]
添加 `<view wx:else style="display:none"><slot/></view>` 会使整体性能降低。

因为 vant-weapp 中很多 slot 是采用了延迟渲染的，比如 Popup 弹窗里的内容。如果统一加上该写法，会导致 Popup 的内容在进入页面时就全部初始化（包括内部的子组件）。因此，考虑到性能影响，我们暂时不添加该写法。

**Comment by nanfb** [comment]
加在vant组件哪里啊大佬
