### ISSUE TITLE
van-field setdata值无效

### ISSUE THREAD

**Issue by beriattack** [youzan/vant-weapp#4819]
基础库2.21.3
Page({
  data: {
    stuName:'',
  },
onName: function(e) {
    this.setData({
      stuName:e.detail.value,
    });
  },
<van-field value="{{ stuName }}"  bind:change="onName" />
输入的时候会报
Setting data field "stuName" to undefined is invalid
而用原生<input value="{{ stuName }}"  bindinput="onName"/>就没问题

**Comment by NDR0216** [comment]
看起來沒問題，調低版本呢，調到2.20.0以下
