### ISSUE TITLE
Stepper组件的show-minus和plus无效

### ISSUE THREAD

**Issue by uiopm** [youzan/vant-weapp#4821]
https://gist.github.com/uiopm/7248baa85d0674e0578f79cfc79862ec

![image](https://user-images.githubusercontent.com/50294766/156719964-78b09387-0741-4790-bf1f-0f96fe6b7ca1.png)

设为false后仍然显示

**Comment by landluck** [comment]
`show-plus="{{ false }}"` 这样使用
