### ISSUE TITLE
button 组件中使用了 wx.getUserInfo 导致需要填写用户隐私报告

### ISSUE THREAD

**Issue by linxz** [youzan/vant-weapp#4823]
![image](https://user-images.githubusercontent.com/1132815/156885483-88ad8cf8-d4e2-4b91-9eb0-ab190e7ad29f.png)

在 **button 组件**中使用了微信获取用户相关信息的 API，目前微信对于用户隐私相关内容把控比较严格，在代码提交发布时会检测。
个人一个小工具类型的小程序，并未使用 `wx.getUserInfo`，但最终因为 **vant-weapp** 中含有相关代码，以致于要填写一份用户隐私相关的报告内容。

![image](https://user-images.githubusercontent.com/1132815/156885718-18f83818-0937-4520-8870-01ff56e12d42.png)

对于这个 API 的使用，不知具体的考虑因素是什么，是否可以考虑添加一个开关，让这类调用 API 的代码，尤其是隐私相关的 API 做处理呢？

**Comment by linxz** [comment]
![image](https://user-images.githubusercontent.com/1132815/158178143-e7531797-3828-4557-a5f8-b503157398f4.png)

虽说已经有相关声明，不过要是能够提供更多指引，让不需要用户信息的小程序不去填写相关隐私报告，那就更完美了。

**Comment by JunGaJang** [comment]
这个是微信的规定吧，当你引入了需要获取用户信息相关的控件，就得在提交审核前完善隐私信息填写。控件应该无法解决这个问题吧。我是引入后提交审核就让填写。

**Comment by landluck** [comment]
目前来说就算加开关，也会有 wx.getuserInfo 的代码，这个没有办法避免，建议提交审核前完善隐私信息填写
