### ISSUE TITLE
小程序开发时构建npm，打完的包引入组件wxml编译报错

### ISSUE THREAD

**Issue by zxxvGW** [youzan/vant-weapp#4824]
设备：Windows 10 64
VantWeapp 版本：1.10.2
调试基础库：2.22.1
微信开发者工具版本：Stable 1.05.2203030

问题描述：引入组件库构建npm完成后，引入组件，在微信开发者工具1.05.2201240 版本中同样没法在模拟器中显示对应的组件，甚至没有报错信息，然后我升级了开发工具，这才显示出报错信息，进入对应wxml文件，注释掉对应的代码就能正确显示了。
![Snipaste_2022-03-06_16-18-33](https://user-images.githubusercontent.com/51041769/156915021-fef903cf-35bd-4574-bacf-f75ef053608e.png)
![image](https://user-images.githubusercontent.com/51041769/156915029-77c37a13-3733-437e-b0ff-ec445f489016.png)
![image](https://user-images.githubusercontent.com/51041769/156915075-a9a22aae-ae04-4691-ac1b-d55f186113c9.png)

**Comment by ethanwang9** [comment]
与上述问题相同

- 系统版本：win11 x64
- 微信开发者版本：Stable 1.05.2203030
- 调试基础库：2.22.0
- vant weapp 版本：1.10.2

错误信息：

![](https://compeition-excute.oss-cn-beijing.aliyuncs.com/poss/3968af496b922a3d66fcf5580ec957ab.png)

**Comment by zxxvGW** [comment]
> 我也有这个错误
> 
> * 系统版本：win11 x64
> * 微信开发者版本：稳定版1.05.2203030
> * 调试基础库：2.22.0
> * vant weapp 版本：1.10.2
> 
> 错误信息：
> 
> ![](https://camo.githubusercontent.com/b514807c9b9ac2f3b211af776473148ef77be20b2942f32da2b494becf05381c/68747470733a2f2f636f6d70656974696f6e2d6578637574652e6f73732d636e2d6265696a696e672e616c6979756e63732e636f6d2f706f73732f33393638616634393662393232613364363666636635353830656339353761622e706e67)

我是直接注释掉了，就没报错也可以用了

**Comment by wejectchen** [comment]
相同错误，报错行注释掉能通过编译。

**Comment by huihui14569** [comment]
要怎么解决这个问题呢?急

**Comment by mengxin-FE** [comment]
微信开发者工具1.05.2203030版本 同样复现该问题

**Comment by zxxvGW** [comment]
> 要怎么解决这个问题呢?急

把报错行注释就行了

**Comment by PDieE** [comment]
差不多的问题 报错行 注释掉就编译通过了 但是全是运行时报错

**Comment by ethanwang9** [comment]
我发现将微信开发者工具退回到`1.05.2201240 | 1.06.2201240`就可以正常使用了

**Comment by sdlddr** [comment]
这个问题应该是开发者工具的问题，我已经在微信官方那边提BUG了
