### ISSUE TITLE
使用^2.12.39版本，toast在安卓快应用渠道打开时，三星手机上，会出现重叠或者尺寸扩张现象？

### ISSUE THREAD

**Issue by yangqi1993** [youzan/vant-weapp#4825]
如上标题所述，部分安卓机型例如：三星
部分渠道：安卓快应用，未使用Toast.allowMultiple();前提下，偶尔出现重影或者尺寸扩张现象
截图如下：
<img width="364" alt="image" src="https://user-images.githubusercontent.com/17038403/156952874-32d06a27-d458-4adb-8a84-20577c14f480.png">
<img width="339" alt="image" src="https://user-images.githubusercontent.com/17038403/156952897-180d0365-8b6c-478e-92be-5b0c15adeb8b.png">
想问下解决方案是否有

**Comment by landluck** [comment]
^2.12.39 vant-weapp 没有这个版本，是不是 vant 的问题，如果是 vant 可以到 vant issue 区提一下问题
