### ISSUE TITLE
Search focus属性没有生效

### ISSUE THREAD

**Issue by GodStream** [youzan/vant-weapp#483]
**描述一下问题**
Search focus属性没有生效，没有自动聚集
源码里 properties 里面没有接收 focus， 文档中有focus
本地已经修改
**环境**
 - 设备: iPhone6
 - 基础库版本: 2.2.4
 - Vant Weapp 版本: 最新

**Comment by chenjiahan** [comment]
感谢反馈，缺失漏了 focus 属性，已在 dev 分支修正
