### ISSUE TITLE
引入search模块会导致所有组件都报错

### ISSUE THREAD

**Issue by wonderful-study** [youzan/vant-weapp#4832]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater?repo=VantWeapp

**Comment by wonderful-study** [comment]
其它组件都可以引入，但是search引入就直接报错了找不到这个组件

**Comment by fncheng** [comment]
我也遇到了，没报错但是页面全空白。翻了别的issues，可能是van-field的问题，我把开发者工具的基础款调成最新2.23.0就正常显示了

**Comment by huanghong814** [comment]
就是2.22.1基础库版本不能用，全空白

**Comment by mvity** [comment]
引入 van-field  2.22基础库无法显示

**Comment by huanghong814** [comment]
I have received your email, please inform me on the QQ, thank you!我已经收到你的邮件，请在QQ上告知我，谢谢！

**Comment by landluck** [comment]
现在看了下2.22.1基础库是正常，当时应该是微信基础库的问题，如果还有问题，可以打开 或者 提交issue

**Comment by huanghong814** [comment]
I have received your email, please inform me on the QQ, thank you!我已经收到你的邮件，请在QQ上告知我，谢谢！
