### ISSUE TITLE
van-uplaoder上传视频时，在微信小程序开发工具里面是可以生成缩略图的，但是在真机里面没有

### ISSUE THREAD

**Issue by KangLinDDD** [youzan/vant-weapp#4833]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater?repo=VantWeapp
用到的vant版本是  "@vant/weapp": "^1.10.2"
<img width="1080" alt="Snipaste_2022-03-09_16-29-01" src="https://user-images.githubusercontent.com/38040659/157403128-0da1b76a-89ec-43fd-a186-b6996db323d2.png">
![1646814815(1)](https://user-images.githubusercontent.com/38040659/157403222-bded01f0-1730-4fe9-b2bc-d20e275cc035.jpg)

**Comment by landluck** [comment]
wx.chooseVideo 不会返回视频缩略图，建议使用 media 和 media-type 属性来完成视频的选取，media 支持 视频缩略图
