### ISSUE TITLE
npm安装了vant组件库，使用uni-app在h5上没有任何问题，但运行在微信开发者出现错误

### ISSUE THREAD

**Issue by Zhanbiu** [youzan/vant-weapp#4834]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater?repo=VantWeapp
![image](https://user-images.githubusercontent.com/88268390/157447664-f5e890a6-90ed-4cd7-9576-d3bbed8f2eac.png)

这种问题有解决方法吗

**Comment by landluck** [comment]
vant 组件库可以提 issue 到 vant 仓库
