### ISSUE TITLE
Calendar  低级bug

### ISSUE THREAD

**Issue by zuojing-star** [youzan/vant-weapp#4836]
min-date,max-date,default-date 同时使用，default-date无效

**Comment by landluck** [comment]
没有复现，可以参考 https://developers.weixin.qq.com/miniprogram/dev/devtools/minicode.html 提供代码片段协助定位问题

**Comment by johnsonwong666** [comment]
没能复现。可以提供一个小程序代码片段吗？

**Comment by johnsonwong666** [comment]
没有复现。由于较长时间没有提供复现代码片段，此issue关闭，若还有问题请提新的issue,并附带复现代码片段排查。
