### ISSUE TITLE
[Bug Report]van-field使用type=textarea, autosize，font-size超过18px，首次换行时会失去焦点，键盘收回

### ISSUE THREAD

**Issue by yming** [youzan/vant-weapp#4837]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater?repo=VantWeapp
van-field使用type=textarea, autosize，通过input-class设置字体大小超过18px，输入文字在第一次换行时，会失去焦点，键盘收回。此后的每次换行正常，不会失去焦点

**Comment by landluck** [comment]
没有能复现，如能复现，可以参考 https://developers.weixin.qq.com/miniprogram/dev/devtools/minicode.html 提供代码片段协助定位问题

**Comment by landluck** [comment]
如能复现，可以提供小程序代码片段后重新提交 issue
