### ISSUE TITLE
[Feature Request] [征求意见] `uploader`组件是否有必要增加`width`和`height`参数呢？

### ISSUE THREAD

**Issue by kxbin** [youzan/vant-weapp#4839]
### 这个功能解决了什么问题
现在`uploader`组件有个参数叫做`preview-size`。

目前`uploader`是将宽高都设定为`preview-size`指定的大小，也即宽高相同，这样的话`uploader`就只能是一个正方形区域。

如果我们能开放`width`和`height`参数的话，会使其更加灵活，而不仅仅只能做成正方形。

比如现在的`image`组件，就是支持`width`和`height`参数的。

### 建议的API是什么样的
```
<van-uploader
    width="200px"
    height="100px"
/>
```

### 兼容性考虑
考虑到老版本用户代码里可能有很多的`preview-size`，所以`preview-size`参数也会继续保留。

底层实现上，如果用户有指定`width`或`height`的话，就忽略`preview-size`。

没有指定`width`或`height`的话，就使用`preview-size`顶替

**Comment by kxbin** [comment]
搜索到目前有一个相关 PR #4798

**Comment by chenjiahan** [comment]
相关 PR 已合并
