### ISSUE TITLE
Tabbar和SubmitBar 如何同时存在？

### ISSUE THREAD

**Issue by JunGaJang** [youzan/vant-weapp#4840]
Tabbar和SubmitBar 如何同时存在，SubmitBar 会覆盖Tabbar。

PS：http://vant-contrib.gitee.io/vant-issue-generater 无法提交，VantWeapp 版本下拉框无法选择。

**Comment by chenjiahan** [comment]
可以覆盖一下组件样式，调整 bottom 位置

**Comment by Creatsimon** [comment]
具体怎么解决
