### ISSUE TITLE
什么时候这个组件可以提供国际化，vue3.0的有赞组件目前支持，小程序的有赞组件什么时候可以支持

### ISSUE THREAD

**Issue by youlong723687543** [youzan/vant-weapp#4841]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater?repo=VantWeapp

**Comment by chenjiahan** [comment]
暂时没有计划在 vant-weapp 中支持国际化呢
