### ISSUE TITLE
npm构建后开发工具正常，真机预览报错！

### ISSUE THREAD

**Issue by limintao** [youzan/vant-weapp#4843]
设备：macOS;

VantWeapp 版本：1.10.2;

基础库版本：2.20.3

问题描述：通过 `npm install @vant/weapp` 安装后执行开发者工具的构建npm后，在开发者工具中组件是能正常使用的，但是用真机预览或者调试都会报错！

![51647508992_ pic](https://user-images.githubusercontent.com/24197663/158778334-325ba81d-5ea9-47ad-a951-d70d94ce16b8.jpg)

<img width="452" alt="image" src="https://user-images.githubusercontent.com/24197663/158779809-65ce061e-9a70-440d-a3ad-751b760ba227.png">

<img width="504" alt="image" src="https://user-images.githubusercontent.com/24197663/158779901-de658ff7-224c-4b36-82d2-2db49e43b017.png">

**Comment by landluck** [comment]
可以点下开发者工具的 将 js 代码编译成 es5 试试
