### ISSUE TITLE
请问有组件库的UI设计稿吗

### ISSUE THREAD

**Issue by qiqingfu** [youzan/vant-weapp#4844]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater?repo=VantWeapp

**Comment by chenjiahan** [comment]
有的，https://vant-contrib.gitee.io/vant/#/zh-CN/design
