### ISSUE TITLE
van-tabs初始化时，从最左边移动到第一个标签

### ISSUE THREAD

**Issue by teri5354** [youzan/vant-weapp#4853]
<van-tabs :active="active" bind:change="onChange">
  <van-tab title="标签 1">内容 1</van-tab>
  <van-tab title="标签 2">内容 2</van-tab>
  <van-tab title="标签 3">内容 3</van-tab>
  <van-tab title="标签 4">内容 4</van-tab>
</van-tabs>

简单的非动态显示的tabs，初始化时，下划线会有一个从最左边移动到标签1的情况，以前旧版本是不会的，现在的几个版本都有这个问题（包括最新的1.10.2），一直都没有解决，这个移动的使用体验很差，希望能修正这个错误

**Comment by DingShineShine** [comment]
我也遇到了. 同 1.10.2 不知道1.10.3 有没有更新

**Comment by DingShineShine** [comment]
1.10.3 试过了, 问题还存在

**Comment by landluck** [comment]
`v1.10.8` 版本已修复

**Comment by Toni-Stark** [comment]
1.10.8并没有修复

**Comment by landluck** [comment]
> 1.10.8并没有修复

有实际升级后在真机上看一下吗
