### ISSUE TITLE
vant/weapp中的部分组件是不存在

### ISSUE THREAD

**Issue by Chihiro365** [youzan/vant-weapp#4855]
http://vant-contrib.gitee.io/vant-issue-generater?repo=VantWeapp
反馈类组件和业务组件大部分都不存在，右边导航视图显示是有的，这是等待进一步从vant开发迁移麽？还是右边导航预览图就是阉割版的vant预览图

例:pullRefresh组件weapp也是没有的吧

**Comment by chenjiahan** [comment]
右侧导航是展示的 vant h5 版本 demo 哈，vant-weapp 中有些组件是没有实现的，以左侧文档导航为准。
