### ISSUE TITLE
demo跑不起来，自己的项目引入组件也找不到路径

### ISSUE THREAD

**Issue by WilhelmZero** [youzan/vant-weapp#4856]
`[ pages/goods/index.json 文件内容错误] pages/goods/index.json: ["usingComponents"]["van-image"] 未找到(env: Windows,mp,1.05.2201240; lib: 2.23.0)`

**Comment by landluck** [comment]
具体是怎么跑的呢

**Comment by landluck** [comment]
如最新代码还能复现问题，可以重新提交 issue 或者 打开，需要提供一下更多的信息来进行排查
