### ISSUE TITLE
button type 不统一

### ISSUE THREAD

**Issue by lin-code-world** [youzan/vant-weapp#4861]
### 这个功能解决了什么问题
vantweapp V1.10.2 
    `<van-button type="default">默认按钮</van-button>`
    `<van-button type="primary">主要按钮</van-button>`
    `<van-button type="info">信息按钮</van-button>`
    `<van-button type="warning">警告按钮</van-button>`
    `<van-button type="danger">危险按钮</van-button>`

primary应该是蓝色，info建议改成success是绿色。现在primary是绿色，info是蓝色。

### 建议的API是什么样的
primary应该是蓝色，info建议改成success是绿色。现在primary是绿色，info是蓝色。

**Comment by chenjiahan** [comment]
这个是历史原因，改动的话属于 breaking change 了，未来有大版本更新时再修改
