### ISSUE TITLE
tabs组件的滚动导航怎么开启,文档中未说明但是demo里有

### ISSUE THREAD

**Issue by jackzhangrunze** [youzan/vant-weapp#4865]
下面的链接没办法选择版本,没法提交
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater?repo=VantWeapp

**Comment by chenjiahan** [comment]
右侧导航展示有问题，错误地展示了目前未支持的功能，已修复。
