### ISSUE TITLE
van-uploader 在安卓机上不能直接调用摄像头

### ISSUE THREAD

**Issue by youngyangliang** [youzan/vant-weapp#4868]
需求是直接调用摄像头拍照，不需要在相册中选照片。在使用van-uploader时，设置capture="camera" accept="image/*"两个属性，iOS机器能达到直接调用摄像头拍照的效果，而在华为安卓机上，一直会跳出弹窗，照片和视频、手机文件，进而进入相册，在相册的第一个按钮可以进入拍照模式。请问安卓机上怎么做兼容，直接进入拍照，而不要进入相册。

**Comment by Jieechng1996** [comment]
小米手机也是一样的

**Comment by landluck** [comment]
capture="{{ ['camera'] }}" accept="image", 不需要 "image/*"，如还能复现，建议提供一个小程序代码片段 或按照issue模版提供必要信息协助排查
