### ISSUE TITLE
van-tab高度百分比无效

### ISSUE THREAD

**Issue by Biswangluo** [youzan/vant-weapp#4869]
微信小程序 
tabs custom-class 设置高度100%有效 
tab custom-class 设置高度100%无效

主要想结合 scroll-view使用 必须设置高度

![微信截图_20220331164449](https://user-images.githubusercontent.com/2362450/161015093-30887ee2-df39-4081-9af5-772fabfdcf9b.png)

![微信截图_20220331164404](https://user-images.githubusercontent.com/2362450/161015063-bbdc9794-8e88-40b0-ae25-a50933da1f01.png)

**Comment by Biswangluo** [comment]
https://github.com/youzan/vant-weapp/issues/1372

只能通过JS设置高度吗 一样的问题

**Comment by johnsonwong666** [comment]
height100%是相对于父元素的高度，请确保父元素已经设置了一个明确的高度值。可以参考这里的解决方案 #1372
