### ISSUE TITLE
微信小程序、h5开发，使用的是微信小程序版的vant，van-dropdown-menu在h5不正常显示

### ISSUE THREAD

**Issue by zixuexuanyu2** [youzan/vant-weapp#4870]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater?repo=VantWeapp
![image](https://user-images.githubusercontent.com/102724615/161017821-1035bae4-6082-4329-9252-81b8cadd36a3.png)
在小程序显示如下
![image](https://user-images.githubusercontent.com/102724615/161017642-7866839a-0980-4351-a352-4ce55ad9b750.png)
在H5中运行有问题，遮罩把内容盖住了并把顶部信息也盖住了
![image](https://user-images.githubusercontent.com/102724615/161017751-20d9c1a7-d1c6-4255-b850-64f5b99bd8c3.png)

**Comment by landluck** [comment]
H5 请用 vant, 而不是 vant-weapp
