### ISSUE TITLE
stepper change事件触发两次

### ISSUE THREAD

**Issue by adufeng** [youzan/vant-weapp#4876]
van-stepper步进器中，绑定change事件，在输入框输入值后，change会触发两次，第一次触发为改变输入的值，第二次触发为输入框失焦，不知道是不是bug

**Comment by landluck** [comment]
`v1.10.8` 已修复

**Comment by kugen123** [comment]
还是会触发两次，麻了

**Comment by songyx95** [comment]
1.11.6还是会触发两次，输入框失去焦点还是会再触发一次

**Comment by songyx95** [comment]
> 1.11.6还是会触发两次，输入框失去焦点还是会再触发一次

查看了下stepper源码，原先已经删除了这个事件this.emitChange(value)，但是在1.11.6中又重新添加上了，导致change事件触发两次了
`onBlur: function (event) {
            var value = this.format(event.detail.value);
            this.setData({ currentValue: value });
            this.emitChange(value);
            this.$emit('blur', __assign(__assign({}, event.detail), { value: value }));
        },`
