### ISSUE TITLE
vant weapp 1.10.2 官方文档有几个没有呀？ Form 、 ImagePreview在左侧的文档栏都没有找到 右侧的模拟界面可以看到，希望早点补上（其它的没发现）

### ISSUE THREAD

**Issue by hugselina2019** [youzan/vant-weapp#4879]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater?repo=VantWeapp

上面的连接用不了， 选不了必填的版本号， not found 
![image](https://user-images.githubusercontent.com/20763416/161417028-c0905178-e14a-44a5-b89c-3f8c73d6a608.png)

下面是问题截图 

![image](https://user-images.githubusercontent.com/20763416/161417066-3f0cd95e-1790-41ab-81e1-6fcd5900b132.png)

![image](https://user-images.githubusercontent.com/20763416/161417102-5b464436-fe54-4993-9135-6ba567bbe293.png)

**Comment by maopixin** [comment]
右边的是vant的在线展示，毕竟网页没有办法模拟小程序吧。所以右边有的，文档没有很正常，毕竟本来vant weapp也没实现

**Comment by JunGaJang** [comment]
原来是这样，右边是vant3的不是want weapp

**Comment by maopixin** [comment]
有的组件功能也不全，还是依据文档为主，右侧就是个展示。我上次也找了半天


发自我的iPhone

**Comment by chenjiahan** [comment]
右侧导航展示有问题，错误地展示了目前未支持的组件，已修复。
