### ISSUE TITLE
NoticeBar 通知栏没有垂直滚动的使用方法

### ISSUE THREAD

**Issue by Change-now** [youzan/vant-weapp#4880]
NoticeBar 通知栏的演示案例里是可以垂直滚动的
但是api教程里却没有使用垂直滚动的参数

**Comment by quizzer-xi** [comment]
期待解决

**Comment by landluck** [comment]
演示案例中是 Vant 多个组件结合实现的，小程序暂时不会考虑实现，可以将 NoticeBar 结合原生 swiper 实现
