### ISSUE TITLE
SwipeCell 滑动单元格文档没有说清楚，这个坑一直都还在

### ISSUE THREAD

**Issue by JINBUDBUD** [youzan/vant-weapp#4881]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater?repo=VantWeapp

**Comment by chenjiahan** [comment]
没有说清楚什么？

**Comment by JunGaJang** [comment]
滑动单元格样式的问题，还有demo模拟好几个。但是实现也没说清楚。

**Comment by NRMrYang** [comment]
SwipeCell常见的坑可以看下这个：[https://blog.csdn.net/Mr_Yang98/article/details/125806638](https://blog.csdn.net/Mr_Yang98/article/details/125806638)
按钮无样式、点击空白处自动关闭、报渲染层错误三个
