### ISSUE TITLE
[Feature Request] startUpload函数执行前加一个钩子函数，类似beforeRead,新增extension字段过滤微信聊天文件类型

### ISSUE THREAD

**Issue by masicheng** [youzan/vant-weapp#4889]
### 这个功能解决了什么问题
1、startUpload执行前，例如：当accpet是'all'时可以选择是从相册选择选择图片，还是从微信聊天选择文件；
2、extension可支持在微信聊天选择文件时根据后缀名过滤文件类型；

### 建议的API是什么样的
useBeforeUpload,beforeUpload,extension

**Comment by landluck** [comment]
![image](https://user-images.githubusercontent.com/27060081/199225581-1d38e573-8e6f-441e-a5ac-0e1fa24847b6.png)

**Comment by masicheng** [comment]
不是beforeRead,beforeRead触发时是已经选择完文件了，但是我想要的是选择文件startUpload前，使用场景：比如让用户选择是从微信聊天里面选择还是从相册选择。现在如果accept是all时是只能从聊天里面选择图片
