### ISSUE TITLE
Dialog添加组件调用，没有任何反应

### ISSUE THREAD

**Issue by wqzai** [youzan/vant-weapp#4892]
![Snipaste_2022-04-14_16-44-31](https://user-images.githubusercontent.com/81562515/163348651-ed78039b-7b85-429f-a693-b8e871d2886d.png)
![Snipaste_2022-04-14_16-44-39](https://user-images.githubusercontent.com/81562515/163348666-740d9a04-83ae-4bd6-b419-d5b1799547c9.png)
![Snipaste_2022-04-14_16-44-46](https://user-images.githubusercontent.com/81562515/163348676-ff814299-7ab0-47c1-9cc7-3f261d81ab9e.png)

**Comment by landluck** [comment]
QQ 小程序确实没有做过适配，其他组件能用吗

**Comment by landluck** [comment]
QQ 小程序确实没有做过适配，如还有问题，需要提供一个小程序代码片段后重新打开issue或者重新按照模版提交
