### ISSUE TITLE
小程序文档中：展示组件：Badge组件文档没有。

### ISSUE THREAD

**Issue by sunnyfj** [youzan/vant-weapp#4893]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater?repo=VantWeapp

**Comment by chenjiahan** [comment]
文档网站的右侧导航展示有问题，错误地展示了目前未支持的组件，已修复。
