### ISSUE TITLE
van-uploader在苹果手机上无法正常播放视频；安卓手机正常播放

### ISSUE THREAD

**Issue by jiaxuan-Ji** [youzan/vant-weapp#4894]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater?repo=VantWeapp

**Comment by landluck** [comment]
https://developers.weixin.qq.com/community/develop/doc/000a4296ee0640104fdbece955f414?highLine=wx.previewMedia%2520%25E6%2597%25A0%25E6%25B3%2595%25E6%2592%25AD%25E6%2594%25BE

微信API存在问题
