### ISSUE TITLE
关于遮罩层问题求教

### ISSUE THREAD

**Issue by cangyu1993** [youzan/vant-weapp#4895]
vant的遮罩层组织了小程序自带的下拉刷新，我看组件代码是加了一个事件 
```
catch:touchmove="noop"
```
我也照着抄了一个，但是不生效，想知道还有什么配置？
有些操作我需要禁止用户触发下拉刷新

**Comment by landluck** [comment]
可以用微信的API。
![image](https://user-images.githubusercontent.com/27060081/199222299-33a3b77f-41e1-4946-b5e6-caa0e79a25e1.png)

https://developers.weixin.qq.com/miniprogram/dev/reference/configuration/page.html
