### ISSUE TITLE
uploader after-read 事件参数file没返回name属性

### ISSUE THREAD

**Issue by kalvinGit** [youzan/vant-weapp#4896]
vant-weapp版本：0.5.29
小程序基础库版本：8.0.5
问题描述：
选择文件后，触发after-read事件，通过event.detail.file获取到的信息如下：
![Snipaste_2022-04-21_15-06-04](https://user-images.githubusercontent.com/34390593/164394355-6845f766-530c-4070-9a4e-72beec394045.png)
没有返回文件名称：name属性

uploader使用代码：
<van-uploader name="upload1" file-list="{{ fileList }}" max-count="1" preview-size="120" bind:after-read="afterRead" bind:delete="deleteImg" />

**Comment by landluck** [comment]
name 属性需要在组件上先传入才可以
![image](https://user-images.githubusercontent.com/27060081/199221875-fa21fc77-8763-4daf-b8a9-53f603e8e282.png)

**Comment by Gacent** [comment]
我们需要的是上传的文件名，是上传后读出来的，api都没有给出来，这个name是死的，没有用

**Comment by landluck** [comment]
微信的API有返回文件名吗？具体文档里没看到，如果有可以发一下链接，如果微信没给的话我们也没有方法获取到的
