### ISSUE TITLE
vant的省市区选择器选择将海外单独拿出来写，选中其他选项，得到的值是是默认的第一个,

### ISSUE THREAD

**Issue by liujinwang223** [youzan/vant-weapp#4897]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。
描述一下问题
vant的省市区选择器选择将海外单独拿出来写，选中其他选项，得到的值是是默认的第一个,,

原因
可能是code码不对

环境
设备: 移动端
基础库版本: 2.6.3
http://vant-contrib.gitee.io/vant-issue-generater?repo=VantWeapp

**Comment by landluck** [comment]
例如那个省市区？

**Comment by landluck** [comment]
如还有问题，需要提供一下小程序代码片段 或者 复现代码后，重新打开issue
