### ISSUE TITLE
报出这么多问题也不处理，这小程序版是放弃治疗停更了吗？

### ISSUE THREAD

**Issue by sdlddr** [youzan/vant-weapp#4903]
这么多用户在ISSUES里报出这么多问题也不处理，这小程序版是放弃治疗停更了吗？

**Comment by FaithGit** [comment]
而且文档访问速度是异常卡顿

**Comment by comlejade** [comment]
是不是被毕业了

**Comment by chenjiahan** [comment]
由于各方面原因，目前我们能投入在 vant-weapp 上的精力确实很少，主要精力在维护 Vue 版本的 vant（并且都是业余时间）。

对于 issue 中的问题，欢迎提 Pull Refresh 来帮助 vant-weapp 修复。

**Comment by zhihuifanqiechaodan** [comment]
兄弟 没看到有赞大裁员嘛。。。能用就先用着吧。

**Comment by chenjiahan** [comment]
@FaithGit 参见 https://github.com/youzan/vant-weapp/issues/4906

**Comment by sdlddr** [comment]
这是人都快被裁得差不多了吗？
