### ISSUE TITLE
文档官网打不开了

### ISSUE THREAD

**Issue by 6c9fd** [youzan/vant-weapp#4905]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater?repo=VantWeapp
https://vant-contrib.gitee.io/vant-weapp/#/common

**Comment by chenjiahan** [comment]
访问 https://youzan.github.io/vant-weapp/ 试试

**Comment by chenjiahan** [comment]
参见 https://github.com/youzan/vant-weapp/issues/4906
