### ISSUE TITLE
picker组件

### ISSUE THREAD

**Issue by heisenberg9799** [youzan/vant-weapp#4907]
picker组件的案例：搭配弹出层使用，在源代码示例中并没有找到。

**Comment by landluck** [comment]
`<van-popup show="{{ show }}" bind:close="onClose">
          <van-picker columns="{{ columns }}" bind:change="onChange" />
</van-popup>`

**Comment by landluck** [comment]
```
<van-popup show="{{ show }}" bind:close="onClose">
    <van-picker columns="{{ columns }}" bind:change="onChange" />
</van-popup>
```
