### ISSUE TITLE
x小程序van-tabs在真机上显示不出来啥情况

### ISSUE THREAD

**Issue by 666-arch** [youzan/vant-weapp#4921]
### 重现链接

ide上测试正常，真机测试其他组件正常，唯独van-tabs不显示

### Vant 版本

1.10.2

### 描述一下你遇到的问题。

ide上测试正常，真机测试其他组件正常，唯独van-tabs不显示

### 重现步骤

ide上测试正常，真机测试其他组件正常，唯独van-tabs不显示

### 设备/浏览器

iphone 11

**Comment by wsaxq** [comment]
我也是这样！

**Comment by 666-arch** [comment]
> 我也是这样！

1.0的调试不行，换成真机调试2.0就好了
