### ISSUE TITLE
当scroll-view允许下拉刷新的时候van-sticky吸顶失效

### ISSUE THREAD

**Issue by Pal-player** [youzan/vant-weapp#4922]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater?repo=VantWeapp

issue 的库：VantWeapp
Issue 类型：bug
Issue 标题：当scroll-view允许下拉刷新的时候van-sticky吸顶失效
设备：小程序

当scroll-view移除refresher-enabled时是正常的，会吸顶。通过排查发现将offsetTop设置成event.detail.scrollTop。可以达到吸顶的效果，但是这个方式疯狂的setData。会造成页面卡顿。吸顶跳跃。效果不理想

<scroll-view refresher-enabled bind:scroll="onScroll" 
    id="scroller" >
    <van-sticky scroll-top="{{ scrollTop }}" offset-top="{{ offsetTop }}">
        <view class="position-type">
          我是吸顶的标题
        </view>
    </van-sticky>
</scroll-view>

js
onScroll(event){
    wx.createSelectorQuery()
    .select('#scroller')
    .boundingClientRect((res) => {
      console.log("scroller",res,event.detail.scrollTop);
      this.setData({
        scrollTop: event.detail.scrollTop,
        offsetTop: res.top,
      });
    })
    .exec();
  },

**Comment by johnsonwong666** [comment]
该issue 在vant-weapp2.0 解决

**Comment by johnsonwong666** [comment]
补充一点。实测下来，scroll-view 里面开启下拉刷新  里面的元素的postion会无效 不管是fixed/还是sticky 这可能是官方的一个bug，社区也有讨论，如有这种场景尝试页面级别的下拉刷新。
<img width="1243" alt="image" src="https://github.com/youzan/vant-weapp/assets/64689255/64e8ebef-c21f-4e69-adb0-b7e7ccb4b28c">

**Comment by guoyutao** [comment]
> refresher-enabled

2.0也没解决呀
