### ISSUE TITLE
van-toast轻提示怎么在app.js引用啊

### ISSUE THREAD

**Issue by YY-hub** [youzan/vant-weapp#4924]
van-toast轻提示怎么在app.js引用啊  
 van-toast id="van-toast" 这一段结构要怎么加？

**Comment by Ealrang** [comment]
在wxml文件里加个标签就行

**Comment by landluck** [comment]
第一步:   import Toast from '@vant/weapp/toast/toast';
第二步：在所有页面中添加  <van-toast id="van-toast" />
