### ISSUE TITLE
[Feature Request] van-uploader不支持图片质量压缩吗?

### ISSUE THREAD

**Issue by caozhepeng** [youzan/vant-weapp#4926]
### 这个功能解决了什么问题
van-uploader不支持图片压缩的话，那么只能使用小程序原生的canvas来实现了，基础的功能还是希望支持一下哦，要不然很鸡肋。

### 建议的API是什么样的
建议支持图片压缩，比如增加percent字段，可设置0-1的数值。

**Comment by landluck** [comment]
可以用微信原生 https://developers.weixin.qq.com/miniprogram/dev/api/media/image/wx.compressImage.html  API 手动进行压缩，组件库暂时不考虑支持
