### ISSUE TITLE
上传文件bind：after-read，调用不了函数，搜索到全是改组件源码after-read改成afterRead，没有用关键。。。

### ISSUE THREAD

**Issue by buildding** [youzan/vant-weapp#4928]

**Comment by poolKylin** [comment]
同问

**Comment by landluck** [comment]
具体怎么不能调用函数？可以描述的详细点，另外建议参考 https://developers.weixin.qq.com/miniprogram/dev/devtools/minicode.html 提供代码片段协助定位问题，提供后可以重新打开issue或者按照重新提交issue
