### ISSUE TITLE
最新小程序新建ts项目

### ISSUE THREAD

**Issue by MandyLjm** [youzan/vant-weapp#4930]
"paths": {
      "@vant/weapp/*": ["path/to/node_modules/@vant/weapp/dist/*"]
    }

此配置没有起到作用

**Comment by landluck** [comment]
建议参考微信文档 https://developers.weixin.qq.com/miniprogram/dev/devtools/npm.html 对NPM的支持，另外如还能复现，请提供复现的代码片段或demo
