### ISSUE TITLE
radio-group 上面的 disabled 变成 disabled 之后就不能变回来了

### ISSUE THREAD

**Issue by allovine** [youzan/vant-weapp#4931]
radio-group 上面的 disabled 变成 disabled 之后就不能变回来了

<van-radio-group disabled="{{isSerialChild}}" direction="horizontal" value="{{ radioValue }}" bind:change="onRadioChange">
      <van-radio name="1">单本</van-radio>
      <van-radio name="2">套书</van-radio>
      <van-radio name="3" disabled>子本</van-radio>
    </van-radio-group>

当 isSerialChild 变成 true ，再变回 false 时候，不能生效

**Comment by allovine** [comment]
![image](https://user-images.githubusercontent.com/15407088/168408879-3f79ccdd-1192-4b4a-aeee-f1dea32c57ad.png)

**Comment by Serifx** [comment]
未复现，请检查下是否是受到 `bind:change` 中逻辑影响。或者尝试升级到 vant-weapp 新版本。
