### ISSUE TITLE
van-collapse-item在ipone11上点击不出现内容

### ISSUE THREAD

**Issue by lw721** [youzan/vant-weapp#4932]
测试机型：ipone11
测试版本：1.10.3
![image](https://user-images.githubusercontent.com/33406289/168546047-879c7169-9a25-48ab-8cc4-8f280d236540.png)

![image](https://user-images.githubusercontent.com/33406289/168544517-909fb748-180f-4fd8-aad0-65b137809534.png)

bug表述：点击van-collapse-item后不显示内容
change事件触发，但是dom元素没获取到，目前只在ipone11上出现这种问题

 [代码片段](https://developers.weixin.qq.com/s/squNCimf7rzc)

希望尽快解决！！

**Comment by landluck** [comment]
vant weapp 内部并没有使用 querySelector 这个 API，看表现可能是微信底层兼容的问题，可以去微信社区反馈一下
