### ISSUE TITLE
vant-wxapp介绍页面>核心团队成员列表横向展示问题

### ISSUE THREAD

**Issue by duran-0519** [youzan/vant-weapp#4934]
请在vant-wxapp介绍页面>核心团队成员的dom元素的class名为van-doc-card下面的table标签添加display:block和overflow-y:auto

**Comment by duran-0519** [comment]
<img width="1433" alt="Snipaste_2022-05-17_16-05-48" src="https://user-images.githubusercontent.com/58040954/168761548-160a6122-e317-474d-9067-f50fe5c5bea4.png"> 这是改过的
<img width="1440" alt="Snipaste_2022-05-17_15-10-03" src="https://user-images.githubusercontent.com/58040954/168761579-48bef516-fff4-4f27-a9f1-bc9bb242446b.png"> 这是没改过的

**Comment by watsonhaw5566** [comment]
提个 Pr 试试 。
