### ISSUE TITLE
DropdownMenu 下拉菜单取消遮罩层之后，弹出层无法设置圆角

### ISSUE THREAD

**Issue by sannyin** [youzan/vant-weapp#4938]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater?repo=VantWeapp
<img width="1358" alt="image" src="https://user-images.githubusercontent.com/42018360/169632982-73ecf685-c084-4d22-950f-ad61dfa1de1b.png">
因为内部高度不会自己计算，且无法通过更改元素属性来设置内部自动计算高度。然后导致无法设置圆角

**Comment by landluck** [comment]
可以使用 custom-class 自定义class传入圆角样式
