### ISSUE TITLE
[Feature Request] van-button的事件响应增加chooseAvatar

### ISSUE THREAD

**Issue by atuxp** [youzan/vant-weapp#4939]
### 这个功能解决了什么问题
按照新的"小程序用户头像昵称获取规则调整公告" https://developers.weixin.qq.com/community/develop/doc/00022c683e8a80b29bed2142b56c01
获取用户头像"需要将 button 组件 open-type 的值设置为 chooseAvatar，当用户选择需要使用的头像之后，可以通过 bindchooseavatar 事件回调获取到获取到头像信息的临时路径。"
目前van-button似乎不能响应chooseAvatar,希望增加该功能

### 建议的API是什么样的
bind:chooseAvatar

**Comment by ElanYoung** [comment]
+1 希望兼容下

**Comment by landluck** [comment]
https://vant-contrib.gitee.io/vant-weapp/#/button 已经支持
