### ISSUE TITLE
van-tabbar组件设置active-color时，从上一页返回有问题

### ISSUE THREAD

**Issue by lin119163** [youzan/vant-weapp#4940]
van-tabbar组件设置active-color="#5bb8ff"    inactive-color="#b0b0b0"时，
从别的页面返回首页时，所有文本颜色的状态都是选中的颜色，而且点击选项还没有反应了，控制台也没有报错。 如果不设置这两个就没有问题。  
小程序版本2.24.4，UI版本1.10.3

**Comment by landluck** [comment]
没有能复现，如果还能复现帮忙搞个小程序代码片段后重新打开 issue 或者 重新创建
