### ISSUE TITLE
[Feature Request] ActionSheet增加颜色和图标定义

### ISSUE THREAD

**Issue by suningnet** [youzan/vant-weapp#4941]
### 这个功能解决了什么问题
建议actionsheet
像增加button组件一样，增加type和icon属性。
颜色根据type定义，随着按钮状态禁用自动更换对应文字颜色

### 建议的API是什么样的
actions: [
      { name: '按钮文字', type:"info" icon:"plus" }
    ],

**Comment by johnsonwong666** [comment]
![image](https://github.com/youzan/vant-weapp/assets/64689255/68bb88e3-8258-4b5e-9ff9-4c83f206b522)
颜色可以结合外部样式类和 @import '../common/style/var.less';  里面声明的button变量 写下样式就可以实现。
图标的话，目前不是通过slot或者引用van-button实现的， 改造上有一定成本。
