### ISSUE TITLE
van-uploader accept的值为media的情况下 在小程序windows版本上 弹不出文件选择框

### ISSUE THREAD

**Issue by pinker1983** [youzan/vant-weapp#4942]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater?repo=VantWeapp

**Comment by pandamo** [comment]
自行修改吧，路径： \miniprogram_npm\@vant\weapp\uploader\utils.js
72行， wx.chooseMedia传入参数的sourceType应该为mediaType

参考微信开发文档：https://developers.weixin.qq.com/miniprogram/dev/api/media/video/wx.chooseMedia.html

**Comment by landluck** [comment]
`v1.10.8` 版本增加 `media-type` 属性，可以使用解决这个问题
