### ISSUE TITLE
vant Search 组件 ios 兼容焦点问题

### ISSUE THREAD

**Issue by bai1216625169** [youzan/vant-weapp#4944]
js 改变 value 值，在ios 会有焦点问题，例如 输入22。js改变为 3333，光标会留在 前两位，   原生组件 js 重新 cursor 值可以解决，但是 search 组件操作不了 原生input cursor 值（只有ios有这个问题）

**Comment by landluck** [comment]
没有能复现，如能复现可以参考 https://developers.weixin.qq.com/miniprogram/dev/devtools/minicode.html 提供代码片段协助定位问题
