### ISSUE TITLE
slot "" is not found  怎么解决？

### ISSUE THREAD

**Issue by sunxhy** [youzan/vant-weapp#4945]
![QQ截图20220530235848](https://user-images.githubusercontent.com/12080265/171028009-a06e8f15-596e-43a6-8ccf-d7ea4692cf13.png)

**Comment by sunxhy** [comment]
没人遇到过吗？

**Comment by jasper-ops** [comment]
不用管，不是报错就行，不会影响

**Comment by sunxhy** [comment]
主要看着不爽~~~

**Comment by cisolarix** [comment]
确实好多这样的日志输出

**Comment by landluck** [comment]
最新版本已解决

**Comment by linking2014** [comment]
> 最新版本已解决

请问确定解决了吗？我这里最新版还是有看到诶

![slot is not found](http://zhaorulin.com/vant2.png)

**Comment by landluck** [comment]
之前看错了，可以看下这个 issue https://github.com/youzan/vant-weapp/issues/4815 的回复，暂时来说这个优先级不高，会先解决目前的 BUG issue
