### ISSUE TITLE
treeselect slot怎么使用

### ISSUE THREAD

**Issue by sssqwe** [youzan/vant-weapp#4946]
我想做的效果为items里面的每个object都有自己相对应的slot展示界面。
目前我的尝试在items数组里的每个object加入content变量 然后在wxml界面调用 但是没有任何效果。

**Comment by landluck** [comment]
可以提供一些代码片段补充说明下问题

**Comment by landluck** [comment]
可以在提交示例代码或者补充说明重新打开 issue
