### ISSUE TITLE
IndexBar 索引栏组件被搜索组件遮挡

### ISSUE THREAD

**Issue by SuKaiFei** [youzan/vant-weapp#4956]
### 问题如题微信小程序IndexBar 索引栏组件被搜索组件遮挡

<img width="465" alt="未命名" src="https://user-images.githubusercontent.com/16851216/171626882-d6fc2c5d-7672-4464-a1d2-a53460421893.png">

### 操作步骤
- 选择更多语音包
- 顶部被遮挡一行

<img width="465" alt="未命名" src="https://user-images.githubusercontent.com/16851216/171627355-be0929c1-1f8f-4e64-875c-fd36c5261f1b.jpg">

**Comment by landluck** [comment]
可以在顶部把 IndexBar 顶下来，加一些 padding-top
