### ISSUE TITLE
按钮禁用后仍然有点击效果

### ISSUE THREAD

**Issue by jasper-ops** [youzan/vant-weapp#4961]
开放的issues提交接口不太好使，就在这里提交了

**设备**：鸿蒙、安卓、微信开发者模拟器

**vant版本**：1.10.3 
**引入方式**：dist

**微信基础库**：2.24.4

**问题描述**：
van-button设置了'disabled'属性后，禁用后的灰色效果出现，但是仍然有点击效果，但不会触发点击事件

**Comment by landluck** [comment]
https://github.com/youzan/vant-weapp/issues/4730
