### ISSUE TITLE
tab栏减少 active还存在之前的缓存？

### ISSUE THREAD

**Issue by chenx1999** [youzan/vant-weapp#4963]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater?repo=VantWeapp
![image](https://user-images.githubusercontent.com/93581820/172789842-e16d98f2-41a8-4edd-aeba-33e25ecb4fc1.png)
![image](https://user-images.githubusercontent.com/93581820/172790129-9180b8e1-26cd-438e-a551-eabcf3b03156.png)

**Comment by chenx1999** [comment]
请问这个问题怎么解决

**Comment by jasper-ops** [comment]
得自己处理active呀

**Comment by chenx1999** [comment]
> 得自己处理active呀
这是自带的我怎么处理，选中有缓存

**Comment by jasper-ops** [comment]
> > 得自己处理active呀
> > 这是自带的我怎么处理，选中有缓存

active属性你不能操控？setData({active:0})不就行了吗
