### ISSUE TITLE
uniapp  使用field 文本框设置type 为number ,idcard  不生效

### ISSUE THREAD

**Issue by weimao520** [youzan/vant-weapp#4967]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater?repo=VantWeapp

**Comment by landluck** [comment]
一般 number ,idcard 开发工具是不会生效的，真机会生效，可以尝试一下
