### ISSUE TITLE
小程序vant-weapp van-tabs没有懒加载

### ISSUE THREAD

**Issue by vlay1314** [youzan/vant-weapp#4970]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater?repo=VantWeapp
小程序vant-weapp van-tabs没有懒加载，在van-tab标签里面添加了组件之后，在监听create方法，发现是一次性创建所有的页面，这样不会导致在页面过多的时候造成的卡顿吗？vue版本却有这个懒加载功能，是不是小程序上无法实现这样的功能？

**Comment by landluck** [comment]
可以配合 wx:if 使用

**Comment by vlay1314** [comment]
好的
