### ISSUE TITLE
van-tabs子项选中后下划线出现偏移，这种情况出现在首次加载的时候，点击其他标签之后就会恢复，（当前页面是van-tabs又嵌套了一层van-tabs）

### ISSUE THREAD

**Issue by LwcStrong** [youzan/vant-weapp#4971]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater?repo=VantWeapp
![image](https://user-images.githubusercontent.com/93753404/174517112-f0d1689a-c787-4e13-93a5-45e3fe4c67b9.png)

**Comment by landluck** [comment]
可以提供简单的复现代码片段或者小程序代码片段协排查，提供后出现按照BUG 模版重新提交
