### ISSUE TITLE
部分苹果手机使用van-uploader上传图片出错

### ISSUE THREAD

**Issue by shen111123** [youzan/vant-weapp#4972]
微信客户端版本：8.0.23，小程序基础库版本：2.24.6。系统类型：IOS。
使用van-uploader组件选择上传图片到腾讯云，正常情况下，上传成功后会返回对应腾讯云保存的一个完整的url，然后将url放入van-uploader需要的file-list的数组中。
该功能是大半年之前的，从上周开始，有个别用户反馈图片无法上传，在小程序后台也能看到有报错，但是在腾讯云上却能看到上传的图片，也能看到腾讯云返回的图片地址，但是，van-uploader组件上显示就是这个地址，而不是地址对应的图片。
安卓机以及iPhone12，iPhone X都正常（目前就两台iphone13出错，其他没出现）。
![微信截图_20220620115754](https://user-images.githubusercontent.com/29966333/174522698-a777a85b-98e7-45ca-b015-15a9737cfefd.png)
![微信图片_20220620115903](https://user-images.githubusercontent.com/29966333/174522810-7d03ea19-321c-458a-bab1-0e9f404e58b2.png)
下面的图是正常的情况
![微信截图_20220620120041](https://user-images.githubusercontent.com/29966333/174522983-10c23de8-d759-4b6b-989e-c12896b184da.png)

**Comment by shen111123** [comment]
用出问题的手机iphone13pro试了下。
发现一个问题：无法真机调试，官方社区解决方案是下Nightly的开发工具，我没下，就使用了小程序后台记录日志的方式。
最终发现出现该错误的原因：正常情况下，我给图片数组设置的值是 ['http://xxxxxxxx','http://cccccccc','http://qqqqqqqq']这种字符串数组，但是到了iphone13pro等出问题的手机里，这个图片数组值变了，[['http://xxxxxx'],['http://ccccccc'],['http://qqqqqq']]。其将我的字符串全部又包了一层，最终导致服务器后台解析数组失败

**Comment by landluck** [comment]
如果问题还能复现，可以提供一个简易代码片段，重新打开Issue，我们目前没有复现问题
