### ISSUE TITLE
Slider滑块组件快速滑动时偶现onChange事件参数的detail字段不正确

### ISSUE THREAD

**Issue by GuosXin** [youzan/vant-weapp#4974]
### **问题描述：**
用手指快速划一下Slider组件后立刻松手，会偶现onChange事件中参数的detail字段不正确，我在开发者工具上和真机上测都有这个问题。
![Dingtalk_20220621160329](https://user-images.githubusercontent.com/39106536/174755955-84a67d18-aa7f-4297-9ca0-3b0685db8815.jpg)
![Dingtalk_20220621160342](https://user-images.githubusercontent.com/39106536/174755988-29d52621-065f-4967-a2b2-7ef75b2b7a3a.jpg)
![Dingtalk_20220621160353](https://user-images.githubusercontent.com/39106536/174756170-04b235cc-ed3e-4c06-b4d3-bd532fe02ab3.jpg)
**控制台打印：**
![Dingtalk_20220621160420](https://user-images.githubusercontent.com/39106536/174756217-a3e5629b-9aaa-4c3c-8849-ac98590c96dc.jpg)

**测试设备：** iqoo neo5
**VantWeapp版本：** v1.9.2 和 v1.10.3 测试了都有这个问题
**微信开发者工具版本：** 1.06.2206090
**调试基础库版本：** 2.21.1

**Comment by landluck** [comment]
值是哪里不正确？42 输出的不对吗

**Comment by GuosXin** [comment]
> 值是哪里不正确？42 输出的不对吗

如图滚动条已经快到100了，控制台打印才42，我没有设置max，默认最大就是100，正常滑动是正常的，但是很快滑一下就会有问题

**Comment by landluck** [comment]
`v1.10.8` 版本已修复
