### ISSUE TITLE
[Feature Request] uploader 在小程序js中可以通过点击主动调用吗

### ISSUE THREAD

**Issue by pocketChao** [youzan/vant-weapp#4977]
### 这个功能解决了什么问题
一个上传功能 需要定义两个uploader 一个是图片类型的 一个是视频类型的  当没选择任何文件的时候  先弹出action sheet  让用户选择上传类型是图片还是视频  如果是图片uploader最多9张之后再上传就默认不弹出弹窗正常使用uploader的add 如果是视频最多是一个并且隐藏uploader  希望点击actionsheet的时候主动调用两个中的某一个uploader的chooseFile事件

### 建议的API是什么样的
类似vue中的  点击某个锚点 触发chooseFile 事件

**Comment by landluck** [comment]
可以通过自定义upload 上传区域 来实现
