### ISSUE TITLE
steps步骤条使用过程中的一些疑问，请指点一二，谢谢作者及所有贡献者。

### ISSUE THREAD

**Issue by hickiy** [youzan/vant-weapp#4979]
text 、desc 展示区域 是否可以在不修改组件库源码的情况下，自己二次封装扩展一个插槽用于自定义步骤条每个步骤显示的内容，或者官方是否有计划对其进行扩展。

![提问截图](https://love596310898.github.io/photo/%E6%88%AA%E5%B1%8F2022-06-22%2022.27.07.png)

**Comment by love596310898** [comment]
text 、desc 展示区域 是否可以在不修改组件库源码的情况下，自己二次封装扩展一个插槽用于自定义步骤条每个步骤显示的内容，或者官方是否有计划对其进行扩展。

**Comment by love596310898** [comment]
[https://upload-images.jianshu.io/upload_images/10453269-b0eb61f6af84a3b4.jpg?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240](url)

**Comment by landluck** [comment]
图片无法展示，可以更详细的描述一下需求
