### ISSUE TITLE
vue版本的 van-uploader 上传附件在小程序里打开 点击上传附件选不了图片

### ISSUE THREAD

**Issue by wincentytg** [youzan/vant-weapp#4982]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater?repo=VantWeapp
用vue开发的网页，网页里调用了van-uploader上传附件，发布后，在小程序的webview里打开这个网页，点击上传附件 不弹窗了，选不了附件，苹果手机上是好用的，Android手机上不行。

"vant": "^2.10.12"

**Comment by landluck** [comment]
vant 问题在 vant 项目下提交 issue
