### ISSUE TITLE
[Feature Request] 支持飞书和钉钉小程序吗

### ISSUE THREAD

**Issue by z138141855** [youzan/vant-weapp#4990]
### 这个功能解决了什么问题
请问weapp支持飞书和钉钉小程序吗

### 建议的API是什么样的
请问weapp支持飞书和钉钉小程序吗

**Comment by chenjiahan** [comment]
不支持哈，vant-weapp 只支持微信小程序

**Comment by cdz620** [comment]
飞书小程序是支持的，我已经集成进去了，详见：https://forum.microapp.bytedance.com/mini-app/posts/5fe6e701f479ca495e1d815b
@z138141855

**Comment by 649733108** [comment]
> 飞书小程序是支持的，我已经集成进去了，详见：https://forum.microapp.bytedance.com/mini-app/posts/5fe6e701f479ca495e1d815b @z138141855

飞书小程序很多功能都不兼容，比如DropdownMenu组件，就会报错找不到wx.nextTick

**Comment by relines** [comment]
> 飞书小程序是支持的，我已经集成进去了，详见：https://forum.microapp.bytedance.com/mini-app/posts/5fe6e701f479ca495e1d815b @z138141855

按照你的方法，也没成功
