### ISSUE TITLE
uniapp使用VantWeapp开发小程序版，事件全部调用无效

### ISSUE THREAD

**Issue by MxHechu** [youzan/vant-weapp#4991]
通过hbuliderX创建uniapp项目，然后引入VantWeapp开发小程序版，效果都有，但是组件提供的事件方法一个都使用不了，没办法调用
Hbulider版本:Hbulider X 3.4.18
VantWeapp版本：1.10.3
截图链接：
https://sm.ms/image/dSuKH5M3DT6LN4V
https://sm.ms/image/Hr1fYjPsyBzQbAW

请问一下，我该怎么使用提供的事件方法

**Comment by landluck** [comment]
VantWeapp 是基于原生小程序开发的组件，没有针对 uni-app 进行适配，因此不保证各个组件在 uni-app 下的可用性。

如果你在 uni-app 中使用 Vant Weapp 遇到问题，建议向 uni-app 进行反馈
