### ISSUE TITLE
action-sheet样式不兼容

### ISSUE THREAD

**Issue by yik7707** [youzan/vant-weapp#4996]
![QQ截图20220708113443](https://user-images.githubusercontent.com/74293458/177911859-2f3a5630-8f12-45af-bd4e-39f3b975aea0.png)
使用van-action-sheet和自定义van-tabbar组件当同时显示的时候，遮住了底部取消按钮，麻烦修改action-sheet样式兼容，或者增加van-tabbar的底部占位属性

**Comment by landluck** [comment]
可以先使用自定义样式解决这个问题 

https://github.com/youzan/vant-weapp/pulls

对于使用微信自定义 tabbar 的场景后续会有统一支持，覆盖所有的弹出类组件

**Comment by landluck** [comment]
`v1.10.7` 已发布
