### ISSUE TITLE
popup   bind:close 怎样避免点击遮罩层 事件冒泡

### ISSUE THREAD

**Issue by Lee981265** [youzan/vant-weapp#4997]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater?repo=VantWeapp

**Comment by landluck** [comment]
需要避免遮罩层事件冒泡的场景是？可以提供更多的信息，不规范issue即将被关闭，如有问题可以重新按照 issue 模版提交issue
