### ISSUE TITLE
uploader组件在基础库2.25.1时出现IOS无法选择文件上传

### ISSUE THREAD

**Issue by Bear-1980** [youzan/vant-weapp#5000]
### 这个功能解决了什么问题
uploader组件基础库超过2.20.1   ios真机模拟点击无响应 
wx.chooseImage 不支持基础库2.20.1以上

### 建议的API是什么样的
新增接口判断，兼容 
               case 'image':
               if (wx.canIUse('wx.chooseImage')) {
                  wx.chooseImage({
                    count: multiple ? Math.min(maxCount, 9) : 1,
                    sourceType: capture,
                    sizeType,
                    success: (res) => resolve(formatImage(res)),
                    fail: reject,
                  });
                } else {
                  wx.chooseMedia({
                    count: multiple ? Math.min(maxCount, 9) : 1,
                    sourceType: capture,
                    maxDuration,
                    sizeType,
                    camera,
                    success: (res) => resolve(formatMedia(res)),
                    fail: reject,
                  });
                }
                break;

**Comment by cyhwinner** [comment]
ios在基础库2.28下运行正常可以选择图片和拍摄，使用的是vant-weapp示例中的的uploader组件没有复现。
如果还是不行，可以提供下代码用例。
