### ISSUE TITLE
picker无法使用setColumnIndex动态设置对应列选中项的索引

### ISSUE THREAD

**Issue by hannay128** [youzan/vant-weapp#5003]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

**描述一下问题**
使用picker组件做了一个省市联动，在拿到选择省市的下标之后，想通过setColumnIndex方法定位到对应位置时，发现并不会跳转到指定的下标位置。

**截图**
![image](https://user-images.githubusercontent.com/39815483/180609168-389c81dc-40fe-431b-a4b9-f62b48a74639.png)
![image](https://user-images.githubusercontent.com/39815483/180609180-18c25a69-4cdc-4e3b-b024-7451b3283f8d.png)

**环境**
设备: 微信开发工具
基础库版本: 2.16.1
Vant Weapp 版本: 1.10.3

**Comment by landluck** [comment]
提供一个代码片段吧，暂时没有复现

**Comment by landluck** [comment]
如还能复现，麻烦提交一个小程序代码片段后重新打开 issue 或者 重新创建
