### ISSUE TITLE
Slider 滑块显示异常

### ISSUE THREAD

**Issue by ggxing** [youzan/vant-weapp#5004]
![image](https://user-images.githubusercontent.com/69560311/180733741-0749842e-c291-4395-8eb9-e83a9c1bc800.png)
![image](https://user-images.githubusercontent.com/69560311/180733811-507a3a8a-eb82-4b96-8ef8-db926141a2fd.png)
其他组件都可以正常显示和使用，滑块组件显示有问题

**Comment by landluck** [comment]
可以提供一下简单复现的demo，没有复现该问题，可能会是外层样式的影响，提供demo后可以重新打开 issue
