### ISSUE TITLE
在van-tabs中添加sticky属性后，开发者工具会报错

### ISSUE THREAD

**Issue by Zlianxin** [youzan/vant-weapp#5005]
#### 提交 issue 的库
VantWeapp

#### Issue 类型
Bug

#### 设备
微信开发者工具

#### VantWeapp 版本
1.10.3

#### 基础库版本
2.25.0

#### 核心代码片段链接
https://gitee.com/jinyun0927/question.git

#### 描述问题
在一页代码中使用多个tabs（外层通过block区分），并且每个tabs都使用了 sticky 吸顶属性。在切换到第二个tabs时，如果画面可以上下滑动，程序会报错。报错信息位：_Unhandled promise rejection TypeError: Cannot read property 'height' of null_
个人猜测是因为在切换不同tabs的时候，吸顶中监视的 onScroll 的值为null了，但不知道该怎么解决~

**Comment by juinlavigne** [comment]
请问解决了吗 我也碰到了

**Comment by johnsonwong666** [comment]
问题定位到切换tab之后，其他tab下的scroll事件依旧在触发，scroll回调里面有在获取dom的高度，但是不在可视区域，导致报错。

**Comment by johnsonwong666** [comment]
最新版本的vant-weapp没有复现问题，建议升级一下版本，如果最新版本还有复现再发起一个issue。
