### ISSUE TITLE
popup中的输入框弹出键盘后不会被顶起

### ISSUE THREAD

**Issue by gotounix** [youzan/vant-weapp#5007]
关联 https://github.com/vant-ui/vant-weapp/issues/4696

| 正常情况     | 键盘弹出后              |
| ------------ | ----------------- |
| ![1](https://user-images.githubusercontent.com/18606632/181675960-2a4bd37c-1d13-4e0b-a5f9-605047842323.jpg)     | ![2](https://user-images.githubusercontent.com/18606632/181675971-deb0b243-16cd-43b9-9232-b95cd2cdb5e7.jpg)   |

上图可看出，键盘并没有把弹出框顶起，输入框的文字却上移至其他位置。

复现步骤：popup长度超过屏幕高度，有滚动条，划到最底部，然后点击输入框。

@vant/weapp：1.10.2
调试基础库：2.25.1
微信版本：8.0.25
手机型号：华为荣耀10，华为Nova 5 Pro。

**Comment by landluck** [comment]
建议提供简单可复现的代码片段，另外可以参考微信社区类似问题 https://developers.weixin.qq.com/community/develop/article/doc/000a00e1fd0790488e6a034f156813
