### ISSUE TITLE
Vue 3 版本不兼容小程序吗？

### ISSUE THREAD

**Issue by kuajie520** [youzan/vant-weapp#5008]
网站需求是，一套代码多端运行。所以采用uniapp + vue3 + vant3，但编译到小程序后报错，是不是vue3版本不兼容导致的？

17:47:03.140 vite v2.9.14 building for development...
17:47:03.146 (node:14844) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./" in the "exports" field module resolution of the package at E:\obejct\uni-preset-vue-vite\node_modules\vuex\package.json.
17:47:03.150 Update this package.json to use a subpath pattern like "./*".
17:47:03.151 (Use node --trace-deprecation ... to show where the warning was created)
17:47:06.790 'isVNode' is not exported by node_modules/@dcloudio/uni-mp-vue/dist/vue.runtime.esm.js, imported by node_modules/@vant/use/dist/index.esm.mjs
17:47:06.803 at ../node_modules/@vant/use/dist/index.esm.mjs:79:2
17:47:06.804 77: // src/useRelation/useChildren.ts
17:47:06.818 78: import {
17:47:06.827 79: isVNode,
17:47:06.834 ^
17:47:06.834 80: provide,
17:47:06.840 81: reactive,

**Comment by a798032825** [comment]
小程序得用vantweapp，vant3是不行的

**Comment by liangdiyuan** [comment]
vantweapp 好像只支持Vue2，Vue3的没找到
