### ISSUE TITLE
DropdownMenu 不能动态修改 text 和 value 值吗 ？

### ISSUE THREAD

**Issue by YY-hub** [youzan/vant-weapp#5011]
DropdownMenu 不能动态修改 text 和 value 值吗 ？
一定要用 text 和 value ？ 不能自定义后台传过来的name?

**Comment by landluck** [comment]
新增 options 自定义字段，增加对 options 的watch

**Comment by landluck** [comment]
建议自行将数据转换一层，C端数据结构较为简单，我们一般不提供映射的配置
