### ISSUE TITLE
uploader的accept参数为media时传入参数错误

### ISSUE THREAD

**Issue by pandamo** [youzan/vant-weapp#5015]
源码路径：https://github.com/vant-ui/vant-weapp/blob/dev/lib/uploader/utils.js
72行， wx.chooseMedia传入参数的sourceType应该为mediaType

参考微信开发文档：https://developers.weixin.qq.com/miniprogram/dev/api/media/video/wx.chooseMedia.html

**Comment by Wing-9527** [comment]
源码这里没有问题，sourceType 是选择图片和视频的来源，他是通过判断 accept 选择调用 chooseImage、chooseVideo 还是 chooseMedia
