### ISSUE TITLE
输入框的auto-focus参数只有在默认设置为true才有用  按钮设置没有用

### ISSUE THREAD

**Issue by MuGongziya** [youzan/vant-weapp#5016]
输入框的auto-focus参数只有在默认设置为true才有用  通过按钮设置没有用

http://vant-contrib.gitee.io/vant-issue-generater?repo=VantWeapp无法选择 vant版本  提示not found

**Comment by landluck** [comment]
实测通过 focus 可以拉起，auto-focus 微信不支持拉起

**Comment by MyDesole** [comment]
чо бля по русски

**Comment by MuGongziya** [comment]
哈哈哈哈



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年6月27日(周四) 下午2:33
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [youzan/vant-weapp] 输入框的auto-focus参数只有在默认设置为true才有用  按钮设置没有用 (Issue #5016)




 
чо бля по русски
