### ISSUE TITLE
[Feature Request] Uploader组件支持extensions配置

### ISSUE THREAD

**Issue by czuhai** [youzan/vant-weapp#5017]
### 这个功能解决了什么问题
选择文件时，过滤掉后缀名不匹配的文件

### 建议的API是什么样的

通过组件props传入即可，譬如：
`<van-uploader extensions="{{ ['txt', 'pdf'] }}" />`

微信小程序通过`wx.chooseMessageFile()`的选项传入该配置，在选文件时会自动过滤掉不匹配的文件。

**Comment by landluck** [comment]
Uploader 支持从  客户端会话选择文件

**Comment by czuhai** [comment]
> Uploader 支持从 客户端会话选择文件

我的意思是当前版本不支持过滤，希望加一个过滤的功能 🐶

**Comment by towry** [comment]
> Uploader 支持从 客户端会话选择文件

希望能跟随微信的接口更新。

**Comment by landluck** [comment]
`v1.10.11` 已支持

**Comment by TorvaldsDB** [comment]
so how to use it? can you give us an example?
