### ISSUE TITLE
SafeArea 安全组件

### ISSUE THREAD

**Issue by accardo** [youzan/vant-weapp#5025]
希望官方出一个 SafeArea 组件，因为现在有很多都是定制化的头部或者底部。如果有SafeArea 组件进行包裹会恨方便

**Comment by chenjiahan** [comment]
这个没必要封装成组件，不过 Vant 已经提供了对应的样式类，参见 https://vant-ui.github.io/vant/#/zh-CN/style#an-quan-qu
