### ISSUE TITLE
[Feature Request] 为uploader自定义预览

### ISSUE THREAD

**Issue by leoliuxd** [youzan/vant-weapp#5032]
### 这个功能解决了什么问题
uploader自定义预览样式问题

### 建议的API是什么样的
使用slot或其他方式

**Comment by landluck** [comment]
新增 preview-cover slot 支持自定义

**Comment by leoliuxd** [comment]
> 

已经发布了吗，使用哪个版本？

**Comment by landluck** [comment]
还没，新功能

**Comment by landluck** [comment]
自定义预览？可以描述的更清晰一点，自定义图片预览还是什么内容

**Comment by landluck** [comment]
功能描述不清晰，可以添加描述信息后重新打开issue
