### ISSUE TITLE
DatetimePicker组件选择时间期间滑动滑块造成动画性能问题

### ISSUE THREAD

**Issue by yik7707** [youzan/vant-weapp#5033]
如下图，使用DatetimePicker组件配合Pop组件共同使用（注意我的测试环境在android真机上测试，模拟器的没问题，苹果系统未测试过，如滑动一次未出现，多试几次会复现动画问题），滑动滑块之后造成动画不受控制上下滑动，一直在传值造成性能问题，麻烦请排查谢谢！
![QQ截图20220903053552](https://user-images.githubusercontent.com/74293458/188239113-144e818c-c294-46ff-8799-1821ce1000bf.png)
![QQ截图20220903053552](https://user-images.githubusercontent.com/74293458/188239654-e5ba17e2-3038-4749-9e3a-5f7488f5c14a.png)

**Comment by xjy12345654** [comment]
我手机预览的时候也发现了同样的问题，快速滑动一列 2-3次 然后这列就开始乱滚动位置

**Comment by yjj5855** [comment]
我也遇到了 有的机器还会闪退...

**Comment by Tallrik** [comment]
安卓真机调试时也复现了同样的问题

**Comment by pollux611** [comment]
这个问题解决了么，真机才能复现，模拟器没问题

**Comment by yjj5855** [comment]
@pollux611 已使用微信原生picker组件

**Comment by landluck** [comment]
https://github.com/youzan/vant-weapp/issues/4729

**Comment by landluck** [comment]
https://github.com/youzan/vant-weapp/issues/3617

**Comment by tianyuanbear** [comment]
> 
我是鸿蒙3系统，只要快速短距离滑动多次，然后停下，滑动栏就有很大机率乱抖动。
还有就是滑动停止后，立即点击确定，有可能获取不到当前滑动栏的值。
