### ISSUE TITLE
被告知Arial字体为“商用需授权”字体

### ISSUE THREAD

**Issue by chuxin19** [youzan/vant-weapp#5035]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater?repo=VantWeapp
小程序项目中使用vant-weapp组件被告知**Arial**字体为“商用需授权”字体，且尚未经权利人授权，因此存在一定的法律风险等。所以只能手动把该字体从vant-weapp中删除。希望后期得到优化处理。

**Comment by chenjiahan** [comment]
在前端页面中使用 Arial font-family 应该不会有版权问题吧，像 antd / element 的组件库的默认字体家族中都是有 Arial 的

**Comment by chuxin19** [comment]
> 在前端页面中使用 Arial font-family 应该不会有版权问题吧，像 antd / element 的组件库的默认字体家族中都是有 Arial 的

我也是很莫名其妙，公司法务下发通知，告知有侵权。

**Comment by chenjiahan** [comment]
先手动删除处理吧，如果以后出现类似的 case，我们再考虑调整组件库内置的字体家族😂

**Comment by chuxin19** [comment]
> 先手动删除处理吧，如果以后出现类似的 case，我们再考虑调整组件库内置的字体家族😂

谢谢回复，收到通知的第一时间已经手动删除。
