### ISSUE TITLE
为什么今天组件库vue3版本网站打不开

### ISSUE THREAD

**Issue by IT-NuanxinPro** [youzan/vant-weapp#5038]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater?repo=VantWeapp

**Comment by IT-NuanxinPro** [comment]
今天vant组件库，vue3版本网站打不开，能解决吗

**Comment by chenjiahan** [comment]
昨天下午网站部署出现了一些问题，已经在昨晚修复了哈
