### ISSUE TITLE
 value: expected <String> but get null value. Use empty string instead.

### ISSUE THREAD

**Issue by abnereel** [youzan/vant-weapp#5044]
#版本
vantWeapp 1.10.5

#调用代码
\<van-search value="123" shape="round" placeholder="搜索" />

#错误日志
[Component] property "value" of "miniprogram_npm/@vant/weapp/field/index" received type-uncompatible value: expected <String> but get null value. Use empty string instead.
调用组件的界面是能正常显示和使用的，只是太多的这种日志看着有点烦

#开发工具
微信开发者工具

**Comment by chenjiaj** [comment]
我也遇到相同的问题，请问解决了吗

**Comment by abnereel** [comment]
手动修改源码中的search组件，props属性中添加了value: String就好了，希望官方能在下个版本中更新优化一下

**Comment by landluck** [comment]
https://github.com/youzan/vant-weapp/pull/5094
