### ISSUE TITLE
uploader的accept参数为video时,after-read回调时thumb为undefined

### ISSUE THREAD

**Issue by hunt-jo** [youzan/vant-weapp#5045]
![02db5ca7aa2cb682d5bb4f5a170b291](https://user-images.githubusercontent.com/39673436/192203832-7a39cab3-3067-4951-8403-6bf02e0c6eef.jpg)

**Comment by landluck** [comment]
没能复现，如果还有问题的话需要提供代码片段或者可复现方式

**Comment by lehelewohehe** [comment]
我也遇到了，模拟器上开发的时候没有出现，但是在真机上上传的时候出现了

**Comment by lehelewohehe** [comment]
> 没能复现，如果还有问题的话需要提供代码片段或者可复现方式

我也遇到了，模拟器上开发的时候没有出现，但是在真机上上传的时候出现了，手机型号红米k30 pro

**Comment by lehelewohehe** [comment]
> > 没能复现，如果还有问题的话需要提供代码片段或者可复现方式
> 
> 我也遇到了，模拟器上开发的时候没有出现，但是在真机上上传的时候出现了，手机型号红米k30 pro

我看了下，和accept有关系，当accept为video的时候 真机上thumb 为undefined，此时调用的是chooseVideo，但是chooseVideo返回的结果中不会有thumb 如下
![image](https://user-images.githubusercontent.com/38452294/206148444-14d9f413-3ab4-4b9c-a5aa-d85b066b633c.png)
accept是media的时候可以，此时调用的是chooseMedia 这个接口会返回thumb（微信api中的字段叫做thumbTempFilePath）
