### ISSUE TITLE
vant-weapp组件引入报错

### ISSUE THREAD

**Issue by sunWhereCode** [youzan/vant-weapp#5046]
<img width="1060" alt="image" src="https://user-images.githubusercontent.com/1262247/192423812-afbdf5f5-acb2-42e1-aea6-e6df158a8d2b.png">

taro3+vue2
组件引入方式
```
usingComponents: {
  'van-button': './components/vant-weapp/button/index',
},
```

**Comment by landluck** [comment]
vant weapp 是基于微信小程序原生环境开发，暂时没有适配过 taro，所以当出现无法使用的情况，建议提交 issue 到 taro 那边
