### ISSUE TITLE
vant-weapp文档网站无法打开了

### ISSUE THREAD

**Issue by AFAP** [youzan/vant-weapp#5047]
vant-weapp文档网站无法打开了：
https://youzan.github.io/vant-weapp

**Comment by chenjiahan** [comment]
可以访问新域名：https://vant-ui.github.io/vant-weapp/#/home

**Comment by AFAP** [comment]
> 可以访问新域名：https://vant-ui.github.io/vant-weapp/#/home

谢谢，我改下我收藏的链接地址。最好是能把vue上右上角那个小程序的友情链接地址也换下，从那里点也不对了。

**Comment by chenjiahan** [comment]
好滴，我们更新下
