### ISSUE TITLE
CountDown 倒计时  使用自定义样式 后forma时间格式 失效 

### ISSUE THREAD

**Issue by Mtao-cyc** [youzan/vant-weapp#5048]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater?repo=VantWeapp

**Comment by landluck** [comment]
建议补充一下具体是的使用方式和代码片段

**Comment by landluck** [comment]
无法判断问题，如果能复现可以提供下代码片段
