### ISSUE TITLE
IndexBar被wx:if嵌套后索引选中会失效

### ISSUE THREAD

**Issue by tanwanlanyue1** [youzan/vant-weapp#5049]
![image](https://user-images.githubusercontent.com/50123920/192933023-4a913a1b-8610-4c9e-9127-e9da8bfeaa4d.png)
点击右侧锚点跳转正常，但是选中的索引未发生改变，移除上层的wx:if就不会发生这个问题

**Comment by haojiasheng** [comment]
在page实例中增加onPageScroll方法

**Comment by landluck** [comment]
可以试试新版本，如还有问题可以提供小程序代码片段后重新打开 issue
