### ISSUE TITLE
首页的预览报错了，404

### ISSUE THREAD

**Issue by dajiahaoya** [youzan/vant-weapp#5052]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

https://vant-contrib.gitee.io/vant-weapp/#/home

**Comment by landluck** [comment]
> 你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。
> 
> https://vant-contrib.gitee.io/vant-weapp/#/home

那里报错了？可以补充一下截图信息

**Comment by gexin1** [comment]
https://vant-contrib.gitee.io/vant/v2/mobile.html?weapp=1 
404了
@landluck 请麻烦看一下
