### ISSUE TITLE
有没有Table组件

### ISSUE THREAD

**Issue by xibinglee** [youzan/vant-weapp#5054]
你好，请使用下面的链接创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

http://vant-contrib.gitee.io/vant-issue-generater?repo=VantWeapp

**Comment by landluck** [comment]
table 组件在C端使用场景和通用型较小，评估后暂时不做支持

**Comment by xibinglee** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by Chryseis** [comment]
B端sass场景都太多子表格场景，希望可以考虑加入

**Comment by xibinglee** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
