### ISSUE TITLE
Overlay 遮罩层的文档多加了一个class-name属性

### ISSUE THREAD

**Issue by xifan052** [youzan/vant-weapp#5055]
![image](https://user-images.githubusercontent.com/34504196/194748485-cc326c9d-7515-4368-a672-7aaddb3a5a08.png)

![image](https://user-images.githubusercontent.com/34504196/194748457-e39e4f51-7a8e-4976-b3e9-aeafad09fc58.png)

**Comment by landluck** [comment]
默认会增加 custom-class，不会在 props 中申明
