### ISSUE TITLE
真机调试 van-tabs  van-tab 不显示

### ISSUE THREAD

**Issue by ceiltop** [youzan/vant-weapp#5056]
iphone xr  微信版本：8.0.29   
真机调试 van-tabs  van-tab 不显示   开发者工具正常   但在你们的示例中显示又是正常的
会是什么原因导致 ？

**Comment by landluck** [comment]
可以提供下使用代码片段

**Comment by ceiltop** [comment]
已经解决了   微信小程序 真机debug的时候 显示不正常   非debug的时候  显示是正常的
