### ISSUE TITLE
field组件type设置为nikename授权昵称后不能第一时间获取文本框内容

### ISSUE THREAD

**Issue by yik7707** [youzan/vant-weapp#5058]
如题，必须再次激活增加或删除文本后才能获取文本的内容，如下图所示，field组件右侧的清除文本icon未显示代表未获取成功，激活后才获取成功
![QQ截图20221013143738](https://user-images.githubusercontent.com/74293458/195521112-8bdb290d-d6e0-4077-9304-691b12cca11b.png)
![QQ截图20221013143941](https://user-images.githubusercontent.com/74293458/195521116-079c19f4-1b33-4f00-a8dc-416d1c35fa77.png)
![QQ截图20221013144046](https://user-images.githubusercontent.com/74293458/195521121-6cdac560-5f8c-49e6-a2d7-6cee42598f68.png)
![QQ截图20221013144459](https://user-images.githubusercontent.com/74293458/195521813-a413ce90-fbf4-4cc4-bc60-5f128f0942c4.png)

**Comment by cyhwinner** [comment]
这个issue 没看懂什么意思，点了授权微信昵称反填到field后 但是data没值？

**Comment by victorykong** [comment]
是的 我也出现了 @cyhwinner

**Comment by victorykong** [comment]
@yik7707 可以先通过 slot input 解决

<img width="458" alt="image" src="https://user-images.githubusercontent.com/50655436/202127190-6e4de15f-76d3-467d-a6fd-c66f51ba734d.png">

**Comment by cyhwinner** [comment]
@victorykong 我没复现，可以提供下复现的代码

**Comment by landluck** [comment]
可以参考 https://github.com/youzan/vant-weapp/issues/5183 这个的回答，目前微信开发工具无法正常触发 input 事件，所以在开发工具上表现是不正常的，真机上应该是没有问题的
