### ISSUE TITLE
为什么搜索框的数据得不到

### ISSUE THREAD

**Issue by She-is-a-boy-and-he-is-a-gril** [youzan/vant-weapp#5061]
![image](https://user-images.githubusercontent.com/115785459/195811122-9fe16466-b094-4a24-80a8-569c5d586701.png)

**Comment by landluck** [comment]
可以补充说明如何使用获取不到数据的

**Comment by landluck** [comment]
无法复现和判断问题，如果能复现，提供下代码片段
