### ISSUE TITLE
【Bug】Stepper 键盘光标录入状态，点击+-，值会闪烁，同时不会做相应变动

### ISSUE THREAD

**Issue by edwards19900128** [youzan/vant-weapp#5062]
如标题所示，Stepper的input在focus状态下，点击 + - 按钮出现的问题，以下视频为vant的demo释例

https://user-images.githubusercontent.com/11594850/195982390-efef8264-dada-4591-a3d1-2d9830ca2460.MP4

**Comment by baoxiaowang** [comment]
点击动作视作input失去焦点，经过讨论目前认为符合预期，暂不处理
