### ISSUE TITLE
微信小程序里面vant-upload 不显示http地址的图片，

### ISSUE THREAD

**Issue by gaofeng222** [youzan/vant-weapp#5063]
小程序里面的vant-upload 官网示例可以显示http的图片
![image](https://user-images.githubusercontent.com/18065659/196078348-ff6112af-9178-49b3-a720-824b821c37bb.png)

在小程序开发工具1.06.22里面无法回显http的图片，请问要怎么修改

本地开发的时候
![image](https://user-images.githubusercontent.com/18065659/196078213-94c2b781-d8fe-41f3-99e3-02f27efc3de3.png)

**Comment by landluck** [comment]
如何测试无法显示 HTTP 图片的
