### ISSUE TITLE
[Bug Report] van-field 的绑定值修改后不显示修改后的值

### ISSUE THREAD

**Issue by alona789** [youzan/vant-weapp#5069]
### 重现链接

/***********************************index.wxml************************************************/
<van-cell-group>
  <input model:value="{{ inputValue }}" />
  <input type="text" model:value="{{ outputValue }}" disabled=""/>
  <textarea model:value="{{ outputValue }}" ></textarea>
  <van-field value="{{ message }}" type="textarea" clearable clickable placeholder="输入" autosize border="{{ false }}" model:value="{{ inputValue }}" bind:change="onChange"/>

  <van-field value="{{ message }}" type="textarea" clickable placeholder="输出" autosize border="{{ false }}" model:value="{{ outputValue }}" />
  <van-row style="text-align: center;">
    <van-col span="12">
      <van-button type="primary" size="normal" block bind:click="encode">编 码</van-button>
    </van-col>
  </van-row>
</van-cell-group>

/**********************index.ts*****************************/
Page({
  data: {
    value: '',
    inputValue: '',
    outputValue: ''
  },
  encode() {
    console.log(this.data.inputValue, Base64.encode(this.data.inputValue))
    this.setData({
      outputValue: Base64.encode(this.data.inputValue)
    });
  },
  onChange(event) {
    // event.detail 为当前输入的值
    console.log(event.detail);
    this.setData({
      outputValue: Base64.encode(event.detail)
    });
  },
})

### Vant Weapp 版本

1.10.5

### 描述一下你遇到的问题。

van-field 通过 model:value="{{ outputValue }}" 绑定data中的 outputValue 后，在方法中用 this.setData 修改 outputValue ，van-field 不显示任何值

### 重现步骤

在” 输入“ 框里输入值，可以看到 input 中显示了修改后的值，但是”输出“框里是空白的
![image](https://user-images.githubusercontent.com/37200724/197336908-7b961ff6-005b-435c-ad63-126d0a801f90.png)

**Comment by landluck** [comment]
是不是用错了？<textarea model:value="{{ outputValue }}" ></textarea> vant-weapp 不支持这么使用的

**Comment by alona789** [comment]
> 
尴尬了，是复制过来的代码忘记删除 **value="{{ message }}**，然后后面又写了个 **model:value="{{ outputValue }}" **
  <van-field **value="{{ message }}"** type="textarea" clickable placeholder="输出" autosize border="{{ false }}" model:value="{{ outputValue }}" />

**Comment by landluck** [comment]
model:value="{{ outputValue }}"  和 value 只能同时存在一个，一个 textarea 显示的值和其实际的值是一致的，不能使用 value 和 model:value="{{ outputValue }}" 来改变显示的值
