### ISSUE TITLE
官方网站怎么没有找到tabs标签页，扫码看到是有这个功能的呀

### ISSUE THREAD

**Issue by xiaomizhou66** [youzan/vant-weapp#507]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**描述一下问题**
描述一下你遇到的问题，包括复现方式、导致结果

**截图**
如果是 UI 问题，请提供具体截图

**环境**
 - 设备: 
 - 基础库版本: 
 - Vant Weapp 版本:

**Comment by chenjiahan** [comment]
本周五发布
