### ISSUE TITLE
[Bug Report]  Grid 宫格 - 自定义内容有错误

### ISSUE THREAD

**Issue by a312983516** [youzan/vant-weapp#5070]
### 重现链接

<van-grid :border="false" :column-num="3">
  <van-grid-item>
    <van-image
      src="https://fastly.jsdelivr.net/npm/@vant/assets/apple-1.jpeg"
    />
  </van-grid-item>
  <van-grid-item>
    <van-image
      src="https://fastly.jsdelivr.net/npm/@vant/assets/apple-2.jpeg"
    />
  </van-grid-item>
  <van-grid-item>
    <van-image
      src="https://fastly.jsdelivr.net/npm/@vant/assets/apple-3.jpeg"
    />
  </van-grid-item>
</van-grid>

### Vant Weapp 版本

3.6.4

### 描述一下你遇到的问题。

使用vue3

创建Grid 宫格中的“自定义内容“部分，在浏览器会给出警告：“ Failed to resolve component: van-image”，并且无法显示图片内容，整个组件变成空白

### 重现步骤

使用官方示例

### 设备/浏览器

chrome: 版本 104.0.5112.102（正式版本） （64 位）

**Comment by landluck** [comment]
vant 的问题可以在 https://github.com/youzan/vant/issues 创建issue
