### ISSUE TITLE
[Bug Report] Field 输入框type类型不生效

### ISSUE THREAD

**Issue by wthis** [youzan/vant-weapp#5071]
### 重现链接

![image](https://user-images.githubusercontent.com/98244577/197435941-0f6a16b3-e829-4979-af75-a7133fca2737.png)

### Vant Weapp 版本

1.10.4

### 描述一下你遇到的问题。

Filed输入框type类型我使用的是number，但是还是能够输入字符串

### 重现步骤

自定义type类型为number，不生效

### 设备/浏览器

微信小程序

**Comment by landluck** [comment]
开发者工具下微信原生 input 同样是能够输入字符串的，可以在真机下进行测试，真机下是只能输入数字
