### ISSUE TITLE
[Bug Report] 插件使用vant-tabs组件异常

### ISSUE THREAD

**Issue by kk-418** [youzan/vant-weapp#5072]
### 重现链接

小程序代码片段：[https://developers.weixin.qq.com/s/TToUkfmH7WDZ](小程序代码片段链接)
如异常，重新安装构建vant-weapp

### Vant Weapp 版本

1.10.5

### 描述一下你遇到的问题。

点击tab无效；console抛出异常如下
<img width="1604" alt="image" src="https://user-images.githubusercontent.com/5426729/197478806-43ad2a69-dd81-49a6-ba42-666643bf37ea.png">

### 重现步骤

1.点击其他tab标签
2.页面无反应

### 设备/浏览器

MAC OS-M1-微信开发者工具

**Comment by landluck** [comment]
目前在插件里暂不支持使用组件，原因是部分API微信不支持在插件使用，例如 wx.canIuse
![image](https://user-images.githubusercontent.com/27060081/197923914-440d200b-df04-4e28-945f-7b4fc8583ca2.png)

**Comment by landluck** [comment]
另外，上面这个报错是因为循环引用问题，这个后续会进行修复

**Comment by landluck** [comment]
https://github.com/youzan/vant-weapp/pull/5073

**Comment by landluck** [comment]
看到 PR 了
