### ISSUE TITLE
[Bug] van-overlay中使用嵌入后 真机测试无效

### ISSUE THREAD

**Issue by sufy-cn** [youzan/vant-weapp#5074]
### 重现链接

https://vant-contrib.gitee.io/vant-weapp/#/overlay

### Vant Weapp 版本

1.10.5

### 描述一下你遇到的问题。

微信小程序，一个组件中使用 遮罩层的嵌入插槽。微信开发者工具中是可以正常显示并弹出的，但是在真机测试的时候，安卓和IOS都是不会显示不会报错的

### 重现步骤

<van-button type="primary" bind:click="onClickShow">嵌入内容</van-button>
<van-overlay z-index="9999" show="{{ true }}" bind:click="onClickHide">
  <view class="wrapper">
    <view class="block" catch:tap="noop" />
  </view>
</van-overlay>

### 设备/浏览器

微信小程序中(预览/真机)测试

**Comment by landluck** [comment]
没能复现，如还有问题需要提供下可复现的方式或者代码片段
