### ISSUE TITLE
van-field 添加 type='textarea' autosize后 当值只有一行时 label 和 value  没有垂直对齐

### ISSUE THREAD

**Issue by Kai-web** [youzan/vant-weapp#5085]
### 重现链接

![企业微信截图_16673935857879](https://user-images.githubusercontent.com/59676989/199495048-3ca9bdef-d91a-4f3a-b28e-9ee9bf45b267.png)

### Vant Weapp 版本

1.6.4

### 描述一下你遇到的问题。

van-field 添加 type='textarea' autosize后 当值只有一行时 label 和 value  没有垂直对齐

### 重现步骤

![企业微信截图_16673935857879](https://user-images.githubusercontent.com/59676989/199495259-56bd2bd4-e7fa-4c51-bb12-4ed443b7319a.png)

**Comment by landluck** [comment]
可以试试新版本，看了下新版没有这个问题

**Comment by landluck** [comment]
如果还有问题可以提供一个复现代码片段
