### ISSUE TITLE
tabbar组件中css变量--tabbar-background-color在app.wxss中无法直接修改背景颜色

### ISSUE THREAD

**Issue by yik7707** [youzan/vant-weapp#5088]
### 重现链接

微信代码怕片段https://developers.weixin.qq.com/s/lzPm6zm67QDd
![QQ截图20221107022712](https://user-images.githubusercontent.com/74293458/200188554-92801da2-053f-44ef-a3b0-79d28b561555.png)

### Vant Weapp 版本

1.10.6及以下

### 描述一下你遇到的问题。

tabbar组件中css变量--tabbar-background-color在app.wxss中无法直接修改背景颜色

### 重现步骤

如下图在app.wxss中赋值在--tabbar-background-color变量中，渲染在page节点无法覆盖tabbar的背景颜色
![QQ截图20221107022030](https://user-images.githubusercontent.com/74293458/200188564-3369b2f5-d0a8-43b1-a089-9942947d22ea.png)

**Comment by landluck** [comment]
自定义 tabbar 并不在 page 命名空间下，所以通过 page {} 是无法生效的，可以用以下代码来进行覆盖
```
.van-tabbar {
  --tabbar-background-color: #000000;
}
```
