### ISSUE TITLE
Toast点击没有反应

### ISSUE THREAD

**Issue by tielei60** [youzan/vant-weapp#509]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**描述一下问题**
Toast点击没有反应

**截图**
如果是 UI 问题，请提供具体截图

**环境**
 - 设备: 小米6
 - 基础库版本: 
 - Vant Weapp 版本:演示版本

**Comment by chenjiahan** [comment]
具体问题是？

**Comment by tielei60** [comment]
就点了什么反应都没有，也不弹出东西

**Comment by chenjiahan** [comment]
看了一下，这个是示例小程序的问题，今天会更新

**Comment by chenjiahan** [comment]
已修复

**Comment by Xuhengfeng** [comment]
toast组件的toast方法怎么导入到项目中去？

**Comment by Xuhengfeng** [comment]
按照官方文档导入就报错
