### ISSUE TITLE
vantweapp 折叠面板CollapseItem 的插槽slot   right-icon不起作用

### ISSUE THREAD

**Issue by 131452167** [youzan/vant-weapp#5090]
### 重现链接

https://developers.weixin.qq.com/s/hxysHAml7GDo

### Vant Weapp 版本

1.10.3

### 描述一下你遇到的问题。

vantweapp 折叠面板CollapseItem 的插槽slot   right-icon不起作用

### 重现步骤

一上来就无法展示

### 设备/浏览器

微信开发者工具

**Comment by landluck** [comment]
![image](https://user-images.githubusercontent.com/27060081/201563040-6c9b25d4-14a6-4d20-844c-48651d1b2c2f.png)
需要将 is-link 改为 false

**Comment by 131452167** [comment]
好的  非常感谢
