### ISSUE TITLE
Dialog 弹出框className无效

### ISSUE THREAD

**Issue by yonghuicheung** [youzan/vant-weapp#5091]
### 重现链接

<img width="937" alt="image" src="https://user-images.githubusercontent.com/24872473/200461385-89c2f769-9d2a-46fe-bf65-5a0254753141.png">
<img width="1049" alt="image" src="https://user-images.githubusercontent.com/24872473/200461438-f421f53d-dda5-4b18-8257-022ec3303d0f.png">

### Vant Weapp 版本

1.10.6

### 描述一下你遇到的问题。

Dialog 弹出框className无效，查看源码也没有这个参数声明 和 读取

### 重现步骤

Dialog 弹出框className无效，使用函数调用和组件调用都无效

### 设备/浏览器

微信开发者工具

**Comment by landluck** [comment]
![image](https://user-images.githubusercontent.com/27060081/200984844-c9d849eb-fe17-44c9-9146-78963ae46cc8.png)

组件调用也无效吗？可以先用 customStyle

**Comment by yonghuicheung** [comment]
组件调用也没有效果的，暂时先在外层套了一个view修改了

**Comment by landluck** [comment]
如果你是自定义组件中使用了 Dialog 那的确是不生效的，只有在页面中直接使用才会生效，文档是有备注的

**Comment by yonghuicheung** [comment]
直接在页面中使用的，没有使用自定义组件
<img width="786" alt="image" src="https://user-images.githubusercontent.com/24872473/201105303-cf61d58b-b672-4117-8a9b-7044ba44a961.png">
<img width="895" alt="image" src="https://user-images.githubusercontent.com/24872473/201105368-d4b98f05-fece-4ba6-85a3-14b082d2772d.png">
<img width="851" alt="image" src="https://user-images.githubusercontent.com/24872473/201105669-2a4aa3ef-dc3e-4560-8f3b-f57402a6a8a5.png">

**Comment by landluck** [comment]
经过测试 通过JS 命令式调用是支持的，组件传递参数的确不生效，后续会进行排查修复

**Comment by yonghuicheung** [comment]
好的，感谢

**Comment by landluck** [comment]
![image](https://user-images.githubusercontent.com/27060081/204452938-4e6a1a57-54eb-4903-a279-94464e2f6a6f.png)
