### ISSUE TITLE
popup组件和datetimepicker组件组合滚动穿透方案

### ISSUE THREAD

**Issue by perryhong** [youzan/vant-weapp#5092]
在popup组件上加catch:touchstart，会导致datetimepicker的toolbar取消确认的点击也触发了catch:touchstart，无法触发原有绑定函数

**Comment by landluck** [comment]
可以描述清晰点，popup组件上加catch:touchstart的目的是什么，或者简单提供个代码片段后重新提交issue 或者重新打开

**Comment by stonyme** [comment]
> 可以描述清晰点，popup组件上加catch:touchstart的目的是什么，或者简单提供个代码片段后重新提交issue 或者重新打开

这个不是官方写的解决滚动穿透的方法吗？
