### ISSUE TITLE
vscode编写小程序notify问题

### ISSUE THREAD

**Issue by Owr-fri** [youzan/vant-weapp#5093]
![捕获](https://user-images.githubusercontent.com/82499393/200500221-31b8bd61-d282-4b2f-9c3f-c5071e4a8c41.PNG)
![屏幕截图 2022-11-08 152041](https://user-images.githubusercontent.com/82499393/200500227-cd161356-a904-45bf-8b16-febc2e7be10b.png)
之前可以使用，这次打开发现已经无法使用notfiy了，一直提示不是一个function

**Comment by landluck** [comment]
是升级了版本吗

**Comment by Owr-fri** [comment]
> 是升级了版本吗

是的

**Comment by landluck** [comment]
没有复现，可以提供一下代码片段之类的

**Comment by Owr-fri** [comment]
> 没有复现，可以提供一下代码片段之类的

今天就又可以使用了，迷惑...
