### ISSUE TITLE
使用weapp版vant组件，引入过后绑定v-model时会警告expected <String> but get null value. Use empty string instead.

### ISSUE THREAD

**Issue by qinzhuhe** [youzan/vant-weapp#5098]
### 重现链接

<van-search :value="keyValue" placeholder="请输入搜索关键词" />

### Vant Weapp 版本

1.10.6

### 描述一下你遇到的问题。

引入组件绑定value值后，进行调试时控制台会提示expected <String> but get null value. Use empty string instead.

解决办法，手动修改源码中的search组件，props属性中添加value: String

### 重现步骤

1）引入组件
2）绑定value
3）进行微信开发者工具进行调试
4）控制台发出警告

### 设备/浏览器

微信开发者工具

**Comment by landluck** [comment]
会在下一个版本修复，版本发布时间这周五

**Comment by landluck** [comment]
`v1.10.7` 已修复
