### ISSUE TITLE
ActionSheet 不支持 open-type 吗？

### ISSUE THREAD

**Issue by panda912** [youzan/vant-weapp#510]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**你需要的功能是？**
ActionSheet 支持 open-type 的能力。

**你期望 API 是什么样的？**
描述一下你期望的 API 形式

我看以前是支持 open-type 的，现在 vant 中被移除了，是不支持了？还是未来会加上？而且我看 Projects 里面 ActionSheet 是标记为已完成状态。

**Comment by chenjiahan** [comment]
已在 0.3.0 版本支持
