### ISSUE TITLE
[Bug Report] Calendar组件下“选择多个日期”的示例代码错误

### ISSUE THREAD

**Issue by Vich0** [youzan/vant-weapp#5103]
### 重现链接

Page({
  data: {
    **text**: '',
    show: false,
  },

  onDisplay() {
    this.setData({ show: true });
  },
  onClose() {
    this.setData({ show: false });
  },
  onConfirm(event) {
    this.setData({
      show: false,
      **date:** `选择了 ${event.detail.length} 个日期`,
    });
  },
});

### Vant Weapp 版本

1.10.7

### 描述一下你遇到的问题。

按照示例代码，无法显示“已经选择了n个日期”的文本信息，原因是data中定义文本信息的变量为text，而后续函数中不存在为text赋值的步骤，而是将值赋予date变量，应该是改动时没有仔细检查，将date改为text之后问题解决。

### 重现步骤

运行示例代码

**Comment by landluck** [comment]
`v1.10.8` 已修复
