### ISSUE TITLE
[Bug Report] Toast样式丢失

### ISSUE THREAD

**Issue by helloxz** [youzan/vant-weapp#5105]
### 重现链接

`.wxml`中的内容为：

```html
<van-toast id="van-toast" />
```

`.json`中使用了组件：

```
"van-toast": "@vant/weapp/toast/index",
```

`.js`里面调用：

```javascript
Toast.fail('一次最多支持10个IP');
```

### Vant Weapp 版本

1.10.6

### 描述一下你遇到的问题。

结果Toast的样式丢失了，如下截图。

![](https://img.rss.ink/imgs/2022/11/22/6edde2d41e2c307b.png)

### 重现步骤

1. 点击按钮
2. 调用Toast函数

### 设备/浏览器

小程序开发者工具

**Comment by landluck** [comment]
没有复现，可以提供一个小程序代码片段协助排查

**Comment by helloxz** [comment]
感谢您的答复，我这边已经解决，重新编译一次小程序后这个问题消失了，可能是小程序的BUG
