### ISSUE TITLE
[Bug Report] 改变field组件的value属性，视图没有发生变化

### ISSUE THREAD

**Issue by FlagDu** [youzan/vant-weapp#5107]
### 重现链接

~~~vue
<template>
  <view>
    <!--在这里输入，改变content的值-->
    <van-field @change="handleChange"></van-field>
  </view>

  <view>
    <!--将content传入这个van-field，期望引起视图变化-->
    <van-field :value="content"></van-field>
  </view>
</template>


<script setup lang='ts'>
import { ref } from 'vue';

const content = ref('')

function handleChange(e: any) {
  content.value = e.detail
}
</script>
~~~

### Vant Weapp 版本

1.10.7

### 描述一下你遇到的问题。

我想要使用uniapp、vite、vue3、vant-weapp来开发一个微信小程序。

具体情况见上面的代码和相应的注释所示。

PS：经过debug发现，如果改变van-button的size属性，van-button的视图会发生变化。于是我去看了一下源码，发现van-field的index.js中有一个值为ture的field属性，而van-button中没有。接着我去掉这个field属性，bug解除，修改van-field的value属性能够引起van-field的视图变化。

### 重现步骤

1. 在第一个van-field中输入内容
2. 在第二个van-field中没有内容输出

### 设备/浏览器

微信小程序

**Comment by landluck** [comment]
可以提交 issue 至 uniapp 社区，vant-weapp 目前是标准的微信小程序原生组件，暂时没有适配过 uniapp， filed 属性是会默认使用微信内置 behavior 的能力，是无法去除的  https://developers.weixin.qq.com/miniprogram/dev/framework/custom-component/behaviors.html#wx-form-field-button
