### ISSUE TITLE
8.30号更新开发者工具后，有一部分组件报错，影响项目编译

### ISSUE THREAD

**Issue by imminmin** [youzan/vant-weapp#511]
**描述一下问题**

- 8.30号更新开发者工具后，有一部分组件报错，导致项目无法编译。报错的组件step、notify、dialog、panel暂时发现这几个
- 最新的包 ， 通过开发工具打开---->vant-weapp/example---->报错：file not found: ./dist/common/index.wxss

**截图**
项目报错截图
![image](https://user-images.githubusercontent.com/30076077/45132903-417a2e00-b1c5-11e8-876b-743ae609aba5.png)
![image](https://user-images.githubusercontent.com/30076077/45132928-6373b080-b1c5-11e8-898c-a5208b6e62d6.png)

demo包报错截图
![image](https://user-images.githubusercontent.com/30076077/45132959-81d9ac00-b1c5-11e8-8459-56a20ba87fe4.png)

**环境**
 - 设备: 微信开发工具（8.30号最新版）
 - 基础库版本: 2.2.5
 - Vant Weapp 版本:当前最新版

**Comment by imminmin** [comment]
我去社区问了一下，官方给的答复是这样的，问题地址：[编译bug](https://developers.weixin.qq.com/community/develop/doc/0002ace8d84860dd2657474745bc00?jumpto=reply&parent_commentid=000400af0303d02e215707b3a5b4&commentid=000464f496cf30523557d52ea568)
![image](https://user-images.githubusercontent.com/30076077/45194168-7bf6d000-b284-11e8-8400-4e6f89db4146.png)

**Comment by chenjiahan** [comment]
感谢反馈，已经修复了这个问题
