### ISSUE TITLE
[Feature Request] ShareSheet，图标对齐问题，空间的图标增加slot，或增加背景颜色和图标颜色

### ISSUE THREAD

**Issue by xiezf77** [youzan/vant-weapp#5110]
### 这个功能解决了什么问题？

1. 图标当4个时，左右两边的边距不一样，很不美观，是否可以调整为当无须滚动时，左右边距可以是一样的？
2. 虽然可以通过链接来改变图标的颜色，但如果使用icon库的图标，图标的背景和图标的颜色都为灰色和深灰色，也很不美观

所以，建议：
1. 当图标小于或者等于4个时，是否可以提供选项居中
2. 增加图标slot，或者在options中增加背景颜色和图标颜色的定义

### 你期望的 API 是什么样子的？

···
    options: [
      { name: '微信', icon: 'wechat', openType: 'share' },
      { name: '复制链接', icon: 'link', color: 'white', bgcolor:'green' },
      { name: '二维码', icon: 'qrcode' },
    ],
<van-share-sheet show="{{ showShare }}" options="{{ options }}"  center  ... />

···

**Comment by johnsonwong666** [comment]
少于4个来均分空间，看了下目前主流社交软件都不会这么做，额外提供一个props，改造成本比较大，暂时不会支持
