### ISSUE TITLE
使用tabs,报错Maximum call stack size exceeded

### ISSUE THREAD

**Issue by iboomboom** [youzan/vant-weapp#5111]
### 重现链接

报错文件@vant/weapp/mixins/page-scroll.js? [sm]

### Vant Weapp 版本

1.10.7

### 描述一下你遇到的问题。

当使用tabs,出现如下报错：

WAServiceMainContext.js?t=wechat&s=1669428141936&v=2.27.2:1 RangeError: Maximum call stack size exceeded
    at getCurrentPage (utils.js? [sm]:103)
    at ea.onPageScroll (page-scroll.js? [sm]:7)
    at page-scroll.js? [sm]:11
    at Array.forEach (<anonymous>)
    at ea.onPageScroll (page-scroll.js? [sm]:8)
    at page-scroll.js? [sm]:11
    at Array.forEach (<anonymous>)
    at ea.onPageScroll (page-scroll.js? [sm]:8)
    at page-scroll.js? [sm]:11
    at Array.forEach (<anonymous>)(env: Windows,mp,1.06.2210310; lib: 2.27.2)

### 重现步骤

使用tabs,滚动页面时报错。

代码如下：
wxml:
```
 <van-tabs active="phone" bind:change="onTabChange" swipeable swipe-threshold="10" sticky>
    <van-tab title="手机" name="phone">
          <view wx:for="{{priceList}}" wx:key="index" class="item-price">
            <text class="product-brand"> {{item.brand}} </text>
            <text class="product-type"> {{item.type}} </text>
            <text class="product-specs"> {{item.specs}} {{item.color}}</text>
            <text class="product-color">  </text>
            <text class="product-price"> {{item.price}} </text>
          </view>

    </van-tab>
    <van-tab title="配件" name="earphone">
    </van-tab>
  </van-tabs>
```
wxss:

```
.product-brand {
  background-color: tomato;
  border-radius: 5rpx;
  color: white;
  font-size: 25rpx;
  text-align: center;
  text-justify: center;
  padding: 0 10rpx 0 10rpx;
}

.product-type {
  font-size: 30rpx;
  font-weight: 800;
  color: black;
  margin-left: 10rpx;
  flex: 1;
}

.product-specs  {
  background-color: rgb(71, 157, 255);
  border-radius: 5rpx;
  color: white;
  font-size: 25rpx;
  text-align: center;
  text-justify: center;
  padding: 0 10rpx 0 10rpx; 
}

.product-price {
  
  font-size: 30rpx;
  font-weight: 800;
  color: black;
  margin-left: 10rpx;
  margin-left: 30rpx;
}

```

数据：
priceList:[{
        category:"手机",
        brand:"苹果",
        type:"iphone 13",
        specs:"128G",
        color:"白色",
        price:"4799",
      },{
        category:"手机",
        brand:"苹果",
        type:"iphone 13",
        specs:"128G",
        color:"黑色",
        price:"4799",
      },{
        category:"手机",
        brand:"苹果",
        type:"iphone 13 pro",
        specs:"128G",
        color:"白色",
        price:"5299",
      },{
        category:"手机",
        brand:"苹果",
        type:"iphone 13 pro",
        specs:"128G",
        color:"白色",
        price:"5299",
      },{
        category:"手机",
        brand:"小米",
        type:"小米 13",
        specs:"128G",
        color:"白色",
        price:"4799",
      },{
        category:"手机",
        brand:"小米",
        type:"小米 13",
        specs:"256G",
        color:"白色",
        price:"4799",
      },{
        category:"手机",
        brand:"华为",
        type:"mate 50",
        specs:"128G",
        color:"白色",
        price:"4799",
      },{
        category:"手机",
        brand:"华为",
        type:"mate 40",
        specs:"128G",
        color:"白色",
        price:"4799",
      },{
        category:"手机",
        brand:"VIVO",
        type:"iphone 13",
        specs:"128G",
        color:"白色",
        price:"4799",
      },{
        category:"手机",
        brand:"OPPO",
        type:"iphone 13",
        specs:"128G",
        color:"白色",
        price:"4799",
      },{
        category:"手机",
        brand:"联想",
        type:"iphone 13",
        specs:"128G",
        color:"白色",
        price:"4799",
      },{
        category:"手机",
        brand:"一加",
        type:"iphone 13",
        specs:"128G",
        color:"白色",
        price:"4799",
      },{
        category:"手机",
        brand:"荣耀",
        type:"iphone 13",
        specs:"128G",
        color:"白色",
        price:"4799",
      }]

### 设备/浏览器

iphone、模拟器

**Comment by linlexing** [comment]
同上：
```
WAServiceMainContext.js?t=wechat&s=1669513811584&v=2.27.3:1 RangeError: Maximum call stack size exceeded
    at getCurrentPage (utils.js? [sm]:103)
    at ta.onPageScroll (page-scroll.js? [sm]:7)
    at page-scroll.js? [sm]:11
    at Array.forEach (<anonymous>)
    at ta.onPageScroll (page-scroll.js? [sm]:8)
    at page-scroll.js? [sm]:11
    at Array.forEach (<anonymous>)
    at ta.onPageScroll (page-scroll.js? [sm]:8)
    at page-scroll.js? [sm]:11
    at Array.forEach (<anonymous>)(env: Windows,mp,1.06.2210310; lib: 2.27.3)
```

**Comment by landluck** [comment]
可以提供一个小程序代码片段吗，我自己没复现

**Comment by landluck** [comment]
1.10.7 版本有更新 page-scroll 的逻辑，初次进去的确好像会触发爆栈的问题，可以清除开发工具缓存后重新编译NPM包试试，如果还能复现，可以提供一个小程序代码片段

**Comment by zhangyulai** [comment]
的确，page-scroll大概率会报这个错。清除开发工具缓存，重新编译NPM，依旧会报错

**Comment by landluck** [comment]
> 的确，page-scroll大概率会报这个错。清除开发工具缓存，重新编译NPM，依旧会报错

可以复现的话，可以帮忙提供一个代码片段，我这边在看一下

**Comment by aszx0413** [comment]
刚刚更新的 1.10.8 依然有这个问题啊，只要用到 van-tabs 点击切换后滚动就会出现

**Comment by landluck** [comment]
在开启微信开发工具 代码自动热重载 并且在更改页面内容时，偶发性的会出现该问题，在重新编译后该问题会消失，可以临时将 代码自动热重载 关闭，会在下个版本修复这个问题

**Comment by landluck** [comment]
`1.10.9` 已修复
