### ISSUE TITLE
Popup组件嵌套Area组件开启lock-scroll后从特定位置滚动，锁定背景滚动失效

### ISSUE THREAD

**Issue by MSamor** [youzan/vant-weapp#5117]
### 重现链接

<van-popup lock-scroll="{{true}}" z-index="{{99999}}" position="bottom" show="{{ show }}" bind:close="onClose">
  <van-area value="{{defaultCode}}"  columns-num="{{ columnsNum }}" bind:confirm="onLocationConfirm" area-list="{{ areaList }}" columns-placeholder="{{ ['请选择', '请选择', '请选择'] }}" />
</van-popup>

### Vant Weapp 版本

  "version": "1.10.5",

### 描述一下你遇到的问题。

![image](https://user-images.githubusercontent.com/47421244/204999946-d7c24845-2389-4d57-82c8-8c6fc6b38615.png)
按住红色框区域，向上或向下拖动，背景也会跟着动。没有锁定背景滚动

### 重现步骤

1. 点击popup顶部按钮区域
2. 向上或向下拖动

### 设备/浏览器

真机和模拟器均出现

**Comment by WebRookie** [comment]
你怎么解决了？

**Comment by MSamor** [comment]
> 你怎么解决了？

![image](https://user-images.githubusercontent.com/47421244/216571601-51785472-f959-4ca3-8922-a7c816e0d32c.png)
仔细看文档，我开始就是没注意到，才把issue关了的。
