### ISSUE TITLE
DatetimePicker不显示，引用之后废掉

### ISSUE THREAD

**Issue by CaoKejian** [youzan/vant-weapp#5118]
### 重现链接

https://github.com/CaoKejian/mangosteen.git

### Vant Weapp 版本

vant:3.4.8

### 描述一下你遇到的问题。

日历选择器引用后使用报错，如果使用引用的名字DatetimePicker 作为标签名，会报出 does not provide an export named 'DatetimePicker' 的错误；如果使用van-datetime-picker作为标签名（官方引用） 则什么也不显示。 测试弹出层是没有问题的。
![image](https://user-images.githubusercontent.com/113025542/205061070-b4a82f78-0e66-443a-9ad1-0c7af43ad511.png)

### 重现步骤

组件不显示

### 设备/浏览器

chrome

**Comment by landluck** [comment]
vant 的问题可以去 https://github.com/youzan/vant/issues 反馈哦
