### ISSUE TITLE
Layout 布局组件Bug

### ISSUE THREAD

**Issue by GodStream** [youzan/vant-weapp#512]
**描述一下问题**
当`<van-col />`内有image组件时，van-row的gutter设置不起作用，van-col上的style值会为undefined。

**截图**
![image](https://user-images.githubusercontent.com/23089466/45133812-d2530880-b1c9-11e8-93fc-fb16f5f94b36.png)

**环境**
 - 设备:
 - 基础库版本: 2.2.5
 - Vant Weapp 版本: 0.2.1

**Comment by chenjiahan** [comment]
未复现这个问题，建议看下是不是其他原因导致的

**Comment by GodStream** [comment]
@chenjiahan 异步获取的数据，van-col 的 style 时好时坏，是不是内部setGutter的方法设置时机问题？目前没有很好的解决办法

**Comment by GodStream** [comment]
@chenjiahan setGutter我打印了一下，有的时候并不会触发

**Comment by GodStream** [comment]
@chenjiahan row节点貌似先于col创建了，col后创建的时候，row不会监听，导致setGutter没有触发

**Comment by chenjiahan** [comment]
@GodStream

**Comment by GodStream** [comment]
```
<van-row gutter="6">
  <block wx:for="{{pictureList}}" wx:key="item.id">
    <van-col wx:if="{{index % 5 === 0}}" span="24">
      <image
        class="picture-image picture-image__small"
        lazy-load
        mode="aspectFill"
        src="{{item.imageUrl}}"
        data-id="{{item[idKey]}}"
        bind:tap="articleDetail"
      />
    </van-col>
    <van-col wx:else span="12">
      <image
        class="picture-image picture-image__small"
        lazy-load
        mode="aspectFill"
        src="{{item.imageUrl}}"
        data-id="{{item[idKey]}}"
        bind:tap="articleDetail"
      />
    </van-col>
  </block>
</van-row>
```
pictureList 为接口获取的图片列表，里面做了if的判断。
van-row 上添加 `wx:if="{{pictureList.length > 0}}"`，即可避免之前的时好时坏的bug

**Comment by chenjiahan** [comment]
这个问题的原因是 Col 动态渲染的时候，没有正确设置 gutter，已在 0.3.1 版本修复
