### ISSUE TITLE
<image> scale-down 属性在小程序上不生效

### ISSUE THREAD

**Issue by xujiujiu** [youzan/vant-weapp#5123]
### 重现链接

<van-image
  round
  width="10rem"
  height="10rem"
  fit="scale-down"
  src="https://img.yzcdn.cn/vant/cat.jpeg"
/>

### Vant Weapp 版本

1.10.8

### 描述一下你遇到的问题。

![image](https://user-images.githubusercontent.com/25719101/205197980-290ff68b-8d2c-413c-b6cc-42e8ae48fe1a.png)

![image](https://user-images.githubusercontent.com/25719101/205196919-0a66b008-6c0c-4be0-8275-64362511b7a9.png)
展示与默认的fill样式一样
看了下代码中，也没有对这个属性做匹配
![image](https://user-images.githubusercontent.com/25719101/205197191-1cb64d83-2584-414f-8e14-dc87c898d5c6.png)

### 重现步骤

该属性默认展示

### 设备/浏览器

微信开发者工具

**Comment by landluck** [comment]
小程序暂不支持该值，示例是 vant H5 组件的，该属性主要是微信 image 的 mode 属性，具体可以参考  https://youzan.github.io/vant-weapp/#/image#tu-pian-tian-chong-mo-shi
