### ISSUE TITLE
[Calendar] minDate maxDate 加入日期后渲染速度变慢。

### ISSUE THREAD

**Issue by mar105** [youzan/vant-weapp#5126]
### 重现链接

minDate: new Date().setFullYear(new Date().getFullYear() - 3);
maxDate: new Date().setFullYear(new Date().getFullYear() - 3);
我界面上有4个Calendar   界面打开时渲染要好几秒，都用new Date()，渲染就非常快，秒开。
应该是还没有点开时，渲染里面的日期区间应该是异步的，不应该影响前台渲染时间 。
或者是选择日期界面一页一页切换时加载，而不要一次性加载。

### Vant Weapp 版本

1.10.8

### 描述一下你遇到的问题。

minDate: new Date().setFullYear(new Date().getFullYear() - 3);
maxDate: new Date().setFullYear(new Date().getFullYear() - 3);
我界面上有4个Calendar   界面打开时渲染要好几秒，都用new Date()，渲染就非常快，秒开。
应该是还没有点开时，渲染里面的日期区间应该是异步的，不应该影响前台渲染时间 。
或者是选择日期界面一页一页切换时加载，而不要一次性加载。

### 重现步骤

minDate: new Date().setFullYear(new Date().getFullYear() - 3);
maxDate: new Date().setFullYear(new Date().getFullYear() - 3);
我界面上有4个Calendar   界面打开时渲染要好几秒，都用new Date()，渲染就非常快，秒开。
应该是还没有点开时，渲染里面的日期区间应该是异步的，不应该影响前台渲染时间 。
或者是选择日期界面一页一页切换时加载，而不要一次性加载。

### 设备/浏览器

微信开发者工具。

**Comment by landluck** [comment]
你的意思现在渲染很慢，然后修改怎么处理后渲染非常快？可以在描述一下问题

**Comment by mar105** [comment]
应该是页面展示到到哪个月就渲染那个月的数据。而不是一下子全部渲染。

**Comment by landluck** [comment]
Calendar 性能优化

**Comment by landluck** [comment]
https://github.com/youzan/vant-weapp/issues/4820

**Comment by landluck** [comment]
https://github.com/youzan/vant-weapp/issues/4560

**Comment by mar105** [comment]
lazy-render在weapp中没有这个属性。

**Comment by Baymaxxx** [comment]
+1  有预期修复时间么
