### ISSUE TITLE
Popup组件在iphone11,12等真机通过emit事件setData无法唤起

### ISSUE THREAD

**Issue by lmreal** [youzan/vant-weapp#5127]
### 重现链接

<img width="355" alt="image" src="https://user-images.githubusercontent.com/15649154/205450252-98901ec7-5b79-41ed-ac35-ebff49a341c5.png">

### Vant Weapp 版本

1.10.8

### 描述一下你遇到的问题。

目前在iphone11,12等真机稳定复现，emit事件中修改show属性无法唤起

### 重现步骤

1.页面返回后的emit事件中调用网络请求；
2.网络请求成功后，在setData中设置show为true，查看AppData，show的值修改为true，但是Popup组件没有弹起，查看页面元素display属性仍然为none

### 设备/浏览器

iphone11,12

**Comment by landluck** [comment]
`v1.10.9` 已修复
