### ISSUE TITLE
微信小程序 van-search 组件动态改变type

### ISSUE THREAD

**Issue by sgling** [youzan/vant-weapp#5129]
### 这个功能解决了什么问题？

把type写活，支持手机上弹出数字键盘

### 你期望的 API 是什么样子的？

![image](https://user-images.githubusercontent.com/67749033/205591256-8f952cc3-15cd-4249-bae8-1266d7070a04.png)
![image](https://user-images.githubusercontent.com/67749033/205591493-e425c0af-5100-41fa-a5bf-e8c1c2ef23ff.png)

**Comment by landluck** [comment]
什么情况下需要搜索纯数字吗
