### ISSUE TITLE
[Bug Report] tab组件无法阻止切换动作

### ISSUE THREAD

**Issue by gaojian88888888** [youzan/vant-weapp#5134]
### 重现链接

https://developers.weixin.qq.com/s/pC677nmH7mEU

### Vant Weapp 版本

1.10.8

### 描述一下你遇到的问题。

不管是click事件还是change事件的方法中return都无法阻止切换，我需要的是用户在切换时点击取消就不切换

### 重现步骤

点击tab组件，无法阻止切换事件

### 设备/浏览器

微信开发者工具

**Comment by gaojian88888888** [comment]
请问这个修改什么时候可以发版？

**Comment by landluck** [comment]
`v1.10.10` 已支持

**Comment by landluck** [comment]
https://youzan.github.io/vant-weapp/#/tab#yi-bu-qie-huan
