### ISSUE TITLE
[Bug Report] tab标签组件在使用动态数据时，第一个选中状态的下标线会偏移到最左侧

### ISSUE THREAD

**Issue by jirentech** [youzan/vant-weapp#5135]
### 重现链接

<van-tabs swipeable sticky :active="active" @change="onChange">
	<van-tab :title="item.name" v-for="(item, index) in tabList" :key="item.id">
			<navigator>链接</navigator>
	</van-tab>
</van-tabs>
<van-empty description="暂无内容" v-if="newsList.length == 0"/>

### Vant Weapp 版本

v1.10.7

### 描述一下你遇到的问题。

[tab标签组件在使用动态数据的时候，默认的active，即第一个选择状态的下标线会偏移到最左侧] 
<img width="333" alt="微信截图_20221209153054" src="https://user-images.githubusercontent.com/22573486/206651409-2064b553-1639-4053-89e2-8b53e1ab0286.png">

### 重现步骤

tab标签组件在使用动态数据（动态数据通过网络请求获得）的时候，即第一个选中状态的下标线会偏移到最左侧

### 设备/浏览器

微信开发者工具，安卓手机

**Comment by landluck** [comment]
动态数据？怎么样使用动态数据，可以参考 https://developers.weixin.qq.com/miniprogram/dev/devtools/minicode.html 提供代码片段协助定位问题

**Comment by me-o** [comment]
`<van-tabs swipeable sticky active="{{active}}" bind:change="onChange">`

**Comment by jirentech** [comment]
> 动态数据？怎么样使用动态数据，可以参考 https://developers.weixin.qq.com/miniprogram/dev/devtools/minicode.html 提供代码片段协助定位问题

动态数据就是使用网络请求获取到的数据

**Comment by landluck** [comment]
提供一个小程序代码片段吧，网络请求可以用 setTimeout 模拟

**Comment by forget1** [comment]
`this.selectComponent('#xxx').resize()`应该是可以暂时解决掉这个问题，之前用过这个方式

**Comment by jirentech** [comment]
@landluck   小程序代码片段
https://developers.weixin.qq.com/s/eVv6XEmw7QFD

**Comment by landluck** [comment]
问题已定位到，this.selectComponent('#xxx').resize() 可以临时解决，后续会修复

**Comment by landluck** [comment]
@johnsonwong666

**Comment by landluck** [comment]
`v1.10.19` 版本已修复
