### ISSUE TITLE
[Stepper] 计数器设置max无效

### ISSUE THREAD

**Issue by sangeyun** [youzan/vant-weapp#5149]
### 重现链接

<van-stepper value="{{ 5 }}" min="5" max="8" />

### Vant Weapp 版本

^1.10.8

### 描述一下你遇到的问题。
`<van-stepper value="{{ 5 }}" min="5" max="8" />`
官方的案例在真机上，设置max=”8“，输入的数字超过了8，仍然没归位

### 重现步骤

van-stepper里手输数字

### 设备/浏览器

安卓

**Comment by sangeyun** [comment]
还有这个
`<van-stepper value="0" step="0.2" decimal-length="{{ 2 }}" />`
输入**1.**  后面不会补**00**，期望结果是**1.00**

**Comment by landluck** [comment]
`v1.10.11` 已修复

**Comment by sangeyun** [comment]
> `v1.10.11` 已修复

感谢大佬，666
