### ISSUE TITLE
Cascader  一直闪动

### ISSUE THREAD

**Issue by alongcai** [youzan/vant-weapp#5150]
### 重现链接

。

### Vant Weapp 版本

1.10.9

### 描述一下你遇到的问题。

联级选择 选择过程中一直闪动

### 重现步骤

。

**Comment by landluck** [comment]
最好是能提供一个视频和发生问题的设备，目前的信息没有办法判断和排查

**Comment by alongcai** [comment]
> 最好是能提供一个视频和发生问题的设备，目前的信息没有办法判断和排查
就是按照例子一引入 选的时候一直闪，数据格式啥的都一摸一样

**Comment by alongcai** [comment]
https://user-images.githubusercontent.com/37562384/208016499-4148c427-c224-44b3-bd66-819ec8a18899.mp4

**Comment by alongcai** [comment]
就基础引用，跟示例一样。没有做任何修改

**Comment by ftxz233** [comment]
实际手机测试没有闪动，开发者工具模拟器会闪动。另外就是关闭的动画没了，以及点击遮罩层无法关闭，还有全国省区数据加载会很慢。
