### ISSUE TITLE
Tab标签页在 ActionSheet 动作面板 内首次加载时样式异常

### ISSUE THREAD

**Issue by yisirman** [youzan/vant-weapp#5153]
### 重现链接

![image](https://user-images.githubusercontent.com/15642586/207875036-ad7fbfe0-7a9e-4c1f-8952-c6e9259df587.png)

仅首次加载会出现这样问题，来回切换后会变正常

### Vant Weapp 版本

1.10.9

### 描述一下你遇到的问题。

Tab标签页在 ActionSheet 动作面板内 首次加载时 下方的线条位置偏移了

### 重现步骤

关闭所有页面，第一次进入ActionSheet，就出现了

### 设备/浏览器

微信开发工具/安卓设备

**Comment by landluck** [comment]
临时解决办法是先在 tab 外层加一个 wx:if, ActionSheet show 的时候置为 true

**Comment by landluck** [comment]
https://youzan.github.io/vant-weapp/#/tab#zu-jian-cong-yin-cang-zhuang-tai-qie-huan-dao-xian-shi-zhuang-tai-shi-di-bu-tiao-wei-zhi-cuo-wu
