### ISSUE TITLE
tab组件出现堆泄漏问题

### ISSUE THREAD

**Issue by xiaoxianglin159** [youzan/vant-weapp#5154]
### 重现链接

<van-tabs active="{{ active }}" bind:change="onChange">
  <van-tab title="标签 1">
 <view style="1500rpx"></view>
</van-tab>
  <van-tab title="标签 2">
<view style="1500rpx"></view>
</van-tab>
</van-tabs>

### Vant Weapp 版本

1.10.9

### 描述一下你遇到的问题。

修改JS随机位置,ctrl+s热重载过后,滚动页面滚动条,即可
报错内容 :RangeError: Maximum call stack size exceeded

### 重现步骤

修改JS随机位置,ctrl+s热重载过后,滚动页面滚动条,即可
报错内容 :RangeError: Maximum call stack size exceeded

### 设备/浏览器

在微信小程序开发工具上

**Comment by landluck** [comment]
这个问题 1.10.9 已经修复了，可以重新装下依赖重新编译试试

**Comment by landluck** [comment]
具体参考 https://github.com/youzan/vant-weapp/issues/5111
