### ISSUE TITLE
field组件 input 事件不支持返回值替换输入框的内容

### ISSUE THREAD

**Issue by qyhever** [youzan/vant-weapp#5155]
### 重现链接

```html
<van-field
    type="number"
    value="{{phone}}"
    placeholder="请输入"
    bind:input="{{onInput}}"
>
```

```javascript
Page({
  data: {
    phone: ''
  },
  onInput (e) {
    let value = e.detail
    if (typeof value === 'string') {
      value = value.replace(/[^\d]/g, '')
    }
    this.setData({
     phone: value  
    })
    // 这里返回值无效，输入框的并不是处理后的 value
    return value
  }
})
```
  

### Vant Weapp 版本

1.10.5

### 描述一下你遇到的问题。

field组件 input 事件不支持返回值替换输入框的内容

需求：输入框只能输入数字，但是使用 type="number"，但是使用第三方输入法还是可以输入非数字，所以在 input 事件加了个正则替换，将非数字删除掉，data中的值确实改变了，但是页面输入框的值没有改变。

微信小程序官网描述：
https://developers.weixin.qq.com/miniprogram/dev/component/input.html
![1671177948363](https://user-images.githubusercontent.com/35389587/208052351-da78df7e-bf92-47b4-9285-aab60f9f0b59.png)

### 重现步骤

输入框输入数字加非数字

**Comment by johnsonwong666** [comment]
<img width="1111" alt="image" src="https://user-images.githubusercontent.com/64689255/231157921-af760873-af08-4e3c-a87c-83ff62b12969.png">

没能复现 通过按钮点击页也获取到了过滤结果。可以提供一个完整的小程序代码片段吗？

**Comment by qyhever** [comment]
> ```
> bind:input="{{onInput}}"
> ```
抱歉，代码语法错误，小程序编译也没报错，导致事件没有触发

**Comment by johnsonwong666** [comment]
> > ```
> > bind:input="{{onInput}}"
> > ```
> 
> 抱歉，代码语法错误，小程序编译也没报错，导致事件没有触发

应该没有双花括号才对
