### ISSUE TITLE
van-radio样式错误

### ISSUE THREAD

**Issue by ZpowerQ** [youzan/vant-weapp#5156]
### 重现链接

![image](https://user-images.githubusercontent.com/99034718/208053954-313a4566-7050-41a4-b767-c1623fa1e8a7.png)

### Vant Weapp 版本

1.10.9

### 描述一下你遇到的问题。

van-radio样式错误
![image](https://user-images.githubusercontent.com/99034718/208053722-a9205529-7683-4325-8dcd-54b64ef10ab8.png)

### 重现步骤

无

### 设备/浏览器

edge

**Comment by landluck** [comment]
.json 中没注册组件吧，如还能复现提供一下小程序代码片段
