### ISSUE TITLE
[Bug Report] Grid-item use-slot时默认有padding

### ISSUE THREAD

**Issue by ustcdyw** [youzan/vant-weapp#5167]
### 重现链接

      <van-grid column-num="2" gutter="3px" border="{{false}}">
        <van-grid-item use-slot wx:for="{{ 7 }}">
          <view style="width: 100%; height: 90px; background-color: thistle;"> </view>
        </van-grid-item>
      </van-grid>

### Vant Weapp 版本

1.10.10

### 描述一下你遇到的问题。

<img width="397" alt="image" src="https://user-images.githubusercontent.com/3214479/210064856-4455cc6a-be1e-4ffd-92ca-6e5f85eab58e.png">
在use-slot时，每个grid-item默认四周都有padding，怎么消除呢？

### 重现步骤

1. 新建一个微信小程序页面
2. 将上述代码复制进去即可看到
`      
<van-grid column-num="2" gutter="3px" border="{{false}}">
        <van-grid-item use-slot wx:for="{{ 7 }}">
          <view style="width: 100%; height: 90px; background-color: thistle;"> </view>
        </van-grid-item>
      </van-grid>
`

### 设备/浏览器

微信小程序

**Comment by landluck** [comment]
可以用 content-class 自定义样式覆盖 或者 自定义 css 变量 --grid-item-content-padding: 0px 0px 来去除 padding
