### ISSUE TITLE
[Bug Report] Cascader 级联选择值匹配错误

### ISSUE THREAD

**Issue by maoweifan** [youzan/vant-weapp#5177]
### 重现链接

暂无

### Vant Weapp 版本

@vant/weapp@1.10.9

### 描述一下你遇到的问题。

Cascader 级联选择值匹配错误，value设置的为Id，但是name是相同的情况下，两个都被勾上了

### 重现步骤

<img width="1172" alt="Snipaste_2023-01-03_03-21-55" src="https://user-images.githubusercontent.com/51221758/210271599-3cefd43f-72b8-4610-97f5-9f2734087046.png">

### 设备/浏览器

微信开发者工具 && 真机

**Comment by maoweifan** [comment]
<img width="743" alt="image" src="https://user-images.githubusercontent.com/51221758/210271764-9fb03345-8305-4f64-86e2-2521335b8af3.png">

**Comment by maoweifan** [comment]
<img width="631" alt="image" src="https://user-images.githubusercontent.com/51221758/210271792-d8bfd62f-9aa9-41fe-a87f-2bcbef228e0f.png">

**Comment by landluck** [comment]
`v1.10.19` 版本已修复
