### ISSUE TITLE
notice-bar 改变字体大小，文字太多，滚动时内容显示不全

### ISSUE THREAD

**Issue by acaleph-pz** [youzan/vant-weapp#5178]
### 重现链接

<van-notice-bar left-icon="volume-o" text="新闻  ，也叫消息、资讯，是通过报纸、电台、广播、电视台等媒体途径所传播信息的 [2]  一种称谓。是记录社会、传播信息、反映时代的一种文体。新闻概念有广义与狭义之分，就其广义而言，除了发表于报刊、广播、互联网、电视上的评论与专文外的常用文本都属于新闻" style="--notice-bar-font-size:40rpx">

### Vant Weapp 版本

1.10.5

### 描述一下你遇到的问题。

notice-bar 文字过多展示不全

### 重现步骤

直接添加过多文字

### 设备/浏览器

微信开发者工具

**Comment by landluck** [comment]
提供个图片或者小程序代码片段吧

**Comment by lunaatn** [comment]
![28b236b1143c6099c4eadbaa907a96d](https://user-images.githubusercontent.com/73158039/210357862-a6668d51-4a6d-4a0c-8dce-d6187dc9e86b.jpg)

**Comment by acaleph-pz** [comment]
> 提供个图片或者小程序代码片段吧
安卓

![28b236b1143c6099c4eadbaa907a96d](https://user-images.githubusercontent.com/73158039/210358113-3c259232-9a67-4585-9799-8f9fd46c0515.jpg)
![image](https://user-images.githubusercontent.com/73158039/210358163-e0da8f31-acfe-4255-8d48-8d3e8a9bfca9.png)

**Comment by landluck** [comment]
没有能复现，可以升级下最新版本尝试复现，如还能复现可以提供下 小程序代码片段 协助排查

**Comment by landluck** [comment]
提供可以复现的小程序代码片段或者设备信息后可以重新打开 issue
