### ISSUE TITLE
calendar组件设置allow-same-day后，默认时间设置有问题

### ISSUE THREAD

**Issue by qualc** [youzan/vant-weapp#5182]
### 重现链接

```js
const startDate = new Date();
startDate.setHours(0, 0, 0, 0);
const endDate = new Date();
endDate.setHours(23, 59, 59, 999);
Page({
  data: {
    show: true,
    defaultDate: [startDate, endDate]
  },
})
```
```html
<van-calendar show="{{ show }}" default-date="{{defaultDate}}" type="range" allow-same-day />
```

### Vant Weapp 版本

1.10.9

### 描述一下你遇到的问题。

![image](https://user-images.githubusercontent.com/23722304/210517751-6a96a9b9-c7f5-46f9-820d-615835467733.png)

设置allow-same-day后， 默认开始结束时间都是当前， 但是calendar组件默认给结束时间加了1天， 通过源码分析感觉是`getInitialDate`没有处理 allow-same-day 的场景。

```
const end = this.limitDateRange(endDay || now, getNextDay(new Date(minDate)).getTime());
```

### 重现步骤

正常编译

**Comment by landluck** [comment]
`v1.10.12` 版本已修复
