### ISSUE TITLE
[Bug Report] 将 van-field 的 type 设为 nickname 时，点击微信的昵称快速选择不能将 value 通过双向绑定传到 AppData

### ISSUE THREAD

**Issue by qianxuu** [youzan/vant-weapp#5183]
### 重现链接

https://developers.weixin.qq.com/s/pQxQH2m27jFM

### Vant Weapp 版本

1.10.11

### 描述一下你遇到的问题。

将 van-field 的 type 设为 nickname 时，点击微信的昵称快速选择不能将 value 通过双向绑定传到 AppData

### 重现步骤

![image](https://user-images.githubusercontent.com/62287903/210747443-70b5187b-44d7-4023-88d3-20ca95c814b9.png)
![image](https://user-images.githubusercontent.com/62287903/210747499-28a7b9c4-c50f-4a1d-a286-672c62c58275.png)
直接点击`用微信昵称`
![image](https://user-images.githubusercontent.com/62287903/210747515-83ad4c36-f4ed-4666-ad19-20350e40186a.png)
昵称被填入后，此时输入框的清空按钮未显示，说明 AppData 那边是空的
![image](https://user-images.githubusercontent.com/62287903/210747529-9bd8ac43-d290-4d7d-b74d-b620aa99f71a.png)
调试器内查看也为空

**Comment by landluck** [comment]
https://developers.weixin.qq.com/community/develop/doc/000888f0d28378e3014ebba0a51800?highLine=input%2520nickname

经过测试开发者工具的确无法触发 input 事件，onblur 事件触发第一也获取不到值，不过真机上能够触发 input ，onblur 也能获取到值，微信官方也建议通过 真机调试，微信支持的问题，我们目前没有办法修复哦
