### ISSUE TITLE
van-cascader 动态添加数据，视图不

### ISSUE THREAD

**Issue by liulong55** [youzan/vant-weapp#5186]
### 重现链接

![18e72188026f38ff1172891a50352e7](https://user-images.githubusercontent.com/53330070/211237294-f3a0c4a9-a78b-4d7b-b358-8c4f1e3de303.png)

### Vant Weapp 版本

1.10.11

### 描述一下你遇到的问题。

  // 循环加
  setOptions(selectedOptions, data) {
    // let ddd = this.data.options
    let _options = this.data.options;
    selectedOptions.forEach((item, index) => {
      if (index) {
        //不是第一个则取下一级children
        _options = _options.children;
      }
      _options =
        _options[_options.findIndex((_item) => _item.value === item.value)];
    });
    //找到最后一级
    _options.children = data.map((item) => {
      return {
        text: item.name,
        value: item.id,
        disabled: item.disabled,
        // 是否有下级
        children: item.nodeNum > 0 ? [] : null,
      };
    });
    console.log(_options);
    console.log(this.data.options);
    this.setData({
      options: this.data.options
    })
  },

### 重现步骤

  // 循环加
  setOptions(selectedOptions, data) {
    // let ddd = this.data.options
    let _options = this.data.options;
    selectedOptions.forEach((item, index) => {
      if (index) {
        //不是第一个则取下一级children
        _options = _options.children;
      }
      _options =
        _options[_options.findIndex((_item) => _item.value === item.value)];
    });
    //找到最后一级
    _options.children = data.map((item) => {
      return {
        text: item.name,
        value: item.id,
        disabled: item.disabled,
        // 是否有下级
        children: item.nodeNum > 0 ? [] : null,
      };
    });
    console.log(_options);
    console.log(this.data.options);
    this.setData({
      options: this.data.options
    })
  },

### 设备/浏览器

微信原生小程序

**Comment by liuyong** [comment]
我遇到的问题：完整的三级省市区数据的时候会非常卡，卡个6、7秒才有响应。改成按需加载，二级城市数据出不来，数据源是已经有children数据的

**Comment by ipconfig12138** [comment]
和楼主遇到相同的问题,onchange事件动态添加children,无法渲染出来
`switch (e.detail.value.length) {
            case 2:
                userApi.addressCity(e.detail.value, (res) => {
                    let index = this.data.addressOptions.findIndex(s => s.value === e.detail.value)
                    if (res.succeeded) {
                        this.setData({
                            ['addressOptions[' + index + '].children']: res.data,
                        })
                        console.log('结束后', this.data.addressOptions);
                    }
                })

                break;
            case 4:

                break;
            case 6:

                break;

            default:
                break;
        }`

**Comment by LixHu** [comment]
有解决吗？

**Comment by LixHu** [comment]
已解决，解决方法如下，修改组件内部代码，修改内容和行数如下图：
<img width="1271" alt="image" src="https://user-images.githubusercontent.com/27951885/221876138-d99ddab6-7afb-4108-89b3-9c9fec36eef2.png">
<img width="935" alt="image" src="https://user-images.githubusercontent.com/27951885/221876210-c972806f-7e34-4aa8-bc48-63de71bc658c.png">

有大佬知道方法也可以指出来。。自己写的代码有点垃圾

**Comment by ghtx520** [comment]
楼上那位你在哪个文件改的啊?

**Comment by LixHu** [comment]
#5260

**Comment by LixHu** [comment]
> 楼上那位你在哪个文件改的啊?

#5260

**Comment by LixHu** [comment]
> 楼上那位你在哪个文件改的啊?
#5260

**Comment by landluck** [comment]
`v1.10.19` 版本已修复

**Comment by alanjiang** [comment]
我解决了， 官方还是没有修复。

cascader/index.js 这块逻辑中， 是根据你选择中的option 是否有 children 来决定是否提前关闭窗口，只需要在逻辑中作一下判断。

  onSelect: function (e) {

            console.log('==>e.currentTarget.dataset='+JSON.stringify(e.currentTarget.dataset));
            var _this = this;
            var _a = e.currentTarget.dataset, option = _a.option, tabIndex = _a.tabIndex;
            console.log('==>option='+JSON.stringify(option));
            if (option && option.disabled) {
                return;
            }
            console.log('==>next=');

            var _b = this.data, valueKey = _b.valueKey, childrenKey = _b.childrenKey;
            var tabs = this.data.tabs;
            console.log('==>this.data='+ _b.childrenKey);

            tabs[tabIndex].selected = option;
            if (tabs.length > tabIndex + 1) {
                tabs = tabs.slice(0, tabIndex + 1);
            }
            if (option[childrenKey]) {
                var nextTab = {
                    options: option[childrenKey],
                    selected: null,
                };
                if (tabs[tabIndex + 1]) {
                    tabs[tabIndex + 1] = nextTab;
                }
                else {
                    tabs.push(nextTab);
                }
                wx.nextTick(function () {
                    _this.setData({
                        activeTab: tabIndex + 1,
                    });
                });
            }
            this.setData({
                tabs: tabs,
            });
            console.log('==>setData tabs <===')
            var selectedOptions = tabs.map(function (tab) { return tab.selected; }).filter(Boolean);
            var value = option[valueKey];
            var params = {
                value: value,
                tabIndex: tabIndex,
                selectedOptions: selectedOptions,
            };
            this.innerValue = value;
            this.$emit('change', params);
            console.log('===> option = ' + JSON.stringify(option));
            console.log('==>option[childrenKey] <==='+option[childrenKey])
            if (option.type == 'school') {
            }else {
              if (!option[childrenKey]) { // 没有children 才完成
                  this.$emit('finish', params);
              }
            }

        },

  如： 我自义每个层级，如 ：在遇到选中的ITEM 是 type = 'school' 时，就不要调用父组件的 finish 方法，这个finish方法以会关闭当前的弹窗。

  if (option.type == 'school') 
 {
    }else {
              if (!option[childrenKey]) { // 没有children 才完成
                  this.$emit('finish', params);
              }
 }


![Image](https://github.com/user-attachments/assets/14e5cfc9-2a56-4c07-a7cf-0f1cf584d550)
