### ISSUE TITLE
[Bug Report] stepper 的异步变更async-change 在输入框下无效

### ISSUE THREAD

**Issue by stonyme** [youzan/vant-weapp#5188]
### 重现链接

<van-stepper value="{{ value }}" async-change bind:change="onChange" />

Page({
  data: {
    value: 1,
  },

  onChange(value) {
    Toast.loading({ forbidClick: true });

    setTimeout(() => {
      Toast.clear();
      this.setData({ 5 });
    }, 500);
  },
});

### Vant Weapp 版本

1.10.5

### 描述一下你遇到的问题。

如题，点击加减符号有效，但是手动在输入框内输入的无效，无法与数据保持同步，再次点击加减后才同步。

### 重现步骤

1.点击加减号，数据变为5，点击输入框手动输入数值，失焦后，框内的值是输入的值，不是5

**Comment by landluck** [comment]
原因是你设置的 value 固定为 5，组件无法监听 value 变更，在值变化的情况是下正常的，什么情况下会出现持续将值设置为固定的值？

**Comment by stonyme** [comment]
> 

你误解我意思了，设置为5只是用于测试，实际项目中是这样的，购物车加减，后端请求接口成功后再设置这个value,点击加减的情况下数值会变化，但是直接点击输入框输入一个会导致请求失败的值，绑定的原始数据没有改变，但是输入框的值依然是你输入的值。即使失焦后数据依然不会变回绑定的value.

**Comment by stonyme** [comment]
你可以测试一下，简而言之就是异步绑定的value,对于点击输入框手动输入不起作用。async-change只是对于加减符号的操作有用，对于直接手动输入值无效。

**Comment by landluck** [comment]
好的

**Comment by landluck** [comment]
`v1.10.12` 版本已修复

**Comment by stonyme** [comment]
> `v1.10.12` 版本已修复

你好，没有完全修复，失焦后，输入框内数字没变，需要再次点击输入框，数字才变回绑定value。

**Comment by stonyme** [comment]
> `v1.10.12` 版本已修复

https://user-images.githubusercontent.com/21095021/212591114-3b5ef868-0098-4e28-b37c-0dbcaa9a3fab.mp4

**Comment by stonyme** [comment]
@landluck  大佬，还没完全修复，还有问题。

**Comment by landluck** [comment]
有触发 setData 更新吗？组件内部是监听外层 setData 的

> @landluck 大佬，还没完全修复，还有问题。

**Comment by stonyme** [comment]
> 有触发 setData 更新吗？组件内部是监听外层 setData 的
> 
> > @landluck 大佬，还没完全修复，还有问题。

没有触发setData更新，视频中输入的数量超过库存值，setData没有触发，组件绑定的值没有改变。但是要再次聚焦才会回到绑定的值。
