### ISSUE TITLE
DropdownMenu下拉菜单选中后在微信开发者工具2.28.1以上有报错

### ISSUE THREAD

**Issue by genhaodegenhao** [youzan/vant-weapp#5189]
### 重现链接

https://developers.weixin.qq.com/s/7j8EgamF7LFO

### Vant Weapp 版本

1.10.11

### 描述一下你遇到的问题。

下拉组件引入后，在微信开发者工具2.28.1以上，选中或关闭下拉框后有报错信息TypeError: Cannot read property 'is' of undefined，切换2.28.1以下，未报错

### 重现步骤

1、点击下拉框显示
2、选中或点击空白区域，下拉框隐藏，报错

### 设备/浏览器

微信开发者工具2.28.1以上

**Comment by landluck** [comment]
https://github.com/youzan/vant-weapp/issues/5179 同类型问题，初步判断是微信基础库问题，不影响组件使用

**Comment by genhaodegenhao** [comment]
组件源码dropdown-item/index.js文件onClose方法中，this.setData({ showWrapper: false })加个定时器，无论微信基础库是哪个版本都不会报错，这跟异步有关系吗。
setTimeout(()=> {
     this.setData({ showWrapper: false });
}, 500)
