### ISSUE TITLE
Dialog then 里面进行页面的跳转不生效

### ISSUE THREAD

**Issue by yisirman** [youzan/vant-weapp#5192]
### 重现链接

Dialog.alert({
          title: 'xxxx',
          message: 'xxxxxx',
        }).then(() => {
          wx.navigateTo({
            url: '/pages/index/index',
          });
        });
      }

### Vant Weapp 版本

v1.10.11

### 描述一下你遇到的问题。

then里面的页面跳转不生效

### 重现步骤

弹窗点击确认，进入then方法，但是页面并没有跳转

**Comment by landluck** [comment]
没能复现，可以参考 [小程序代码片段](https://developers.weixin.qq.com/miniprogram/dev/devtools/minicode.html) 提供可复现 demo 协助排查

**Comment by yisirman** [comment]
> 没能复现，可以参考 [小程序代码片段](https://developers.weixin.qq.com/miniprogram/dev/devtools/minicode.html) 提供可复现 demo 协助排查

https://developers.weixin.qq.com/s/3ACGDgms70Ff

**Comment by yisirman** [comment]
是我写的有问题，分包的路径写错了

**Comment by yisirman** [comment]
是我写的有问题，分包的路径写错了
