### ISSUE TITLE
[Feature Request] image-picker image-clipper

### ISSUE THREAD

**Issue by ustcdyw** [youzan/vant-weapp#5195]
### 这个功能解决了什么问题？

image-picker更方便上传一组图片。
image-clipper在上传图片时辅助裁剪。
可以参考lin-ui的image-picker以及image-clipper
https://doc.mini.talelin.com/component/form/image-picker.html
https://doc.mini.talelin.com/component/form/image-clipper.html

### 你期望的 API 是什么样子的？

可参考lin-ui的API。
https://doc.mini.talelin.com/component/form/image-picker.html
https://doc.mini.talelin.com/component/form/image-clipper.html

**Comment by landluck** [comment]
https://youzan.github.io/vant-weapp/#/uploader
