### ISSUE TITLE
field textarea autosize 传对象时没有生效

### ISSUE THREAD

**Issue by yisirman** [youzan/vant-weapp#5196]
### 重现链接

```
<van-field model:value="{{ xxx }}" type="textarea" placeholder="请输入文本内容" 
 autosize="{ maxHeight: 200, minHeight: 100 }" maxlength="100" show-word-limit border="{{ false }}" />
```

### Vant Weapp 版本

1.10.11

### 描述一下你遇到的问题。

<img width="851" alt="image" src="https://user-images.githubusercontent.com/15642586/212335869-1714a2fe-7cca-4a08-8075-ff561ec50e68.png">

按照官网文档textarea设置autosize为一个对象，结果没有实际效果

### 重现步骤

![image](https://user-images.githubusercontent.com/15642586/212337076-4ab69ebd-efa1-440e-be71-6a80075c5192.png)

```
<van-field model:value="{{ xxx }}" type="textarea" placeholder="请输入文本内容" 
 autosize="{ maxHeight: 200, minHeight: 100 }" maxlength="100" show-word-limit border="{{ false }}" />
```

**Comment by landluck** [comment]
代码写错了，应该是 `autosize="{{ autosizeData}}"`, data 中 `autosizeData: { maxHeight: 200, minHeight: 100 }`
