### ISSUE TITLE
Icon的代码复制不一致问题

### ISSUE THREAD

**Issue by etheral12138** [youzan/vant-weapp#5197]
### 重现链接

https://vant-contrib.gitee.io/vant-weapp/#/icon

### Vant Weapp 版本

1.10.11

### 描述一下你遇到的问题。

![image](https://user-images.githubusercontent.com/109936669/212528472-d5131c3d-92bf-493a-b833-d8dc88cc2df4.png)

![image](https://user-images.githubusercontent.com/109936669/212528487-67b6bed6-d809-4844-aa7c-4cf4680e8d6a.png)

如图，复制代码时的属性显示为badge，但文档中属性为info，希望能尽早修改

### 重现步骤

点击按钮

### 设备/浏览器

浏览器

**Comment by landluck** [comment]
已修复
