### ISSUE TITLE
[Bug Report] van-field在form表单中无法获取值

### ISSUE THREAD

**Issue by Picktarget** [youzan/vant-weapp#5198]
### Vant Weapp 版本

1.10.12

### 描述一下你遇到的问题。

在小程序开发工具中可以获得form表单中的event.detail.value中绑定的属性值，在真机调试中无法获得值。目前只能通过手动的加上bind:blur来解决 bind:change也无法解决此问题

### 重现步骤

1.输入内容
2.点击提交
3.分别在小程序开发工具和真机调试中查看打印的日志

### 设备/浏览器

华为p50 pro 微信版本8.0.32

**Comment by Picktarget** [comment]
![1674095600089](https://user-images.githubusercontent.com/12743709/213341893-f6b2135f-38cb-4588-b196-a11d244bc17e.png)

**Comment by Picktarget** [comment]
![1674095653868](https://user-images.githubusercontent.com/12743709/213341983-1a386457-c646-4ea6-bb30-82e6d1cea2dd.png)

**Comment by johnsonwong666** [comment]
form是小程序原生的form组件吗？ 好像没有看到catchsubmit这个属性。可以提供一个小程序代码片段过来吗

**Comment by johnsonwong666** [comment]
没有复现。由于较长时间没有提供复现代码片段，此issue关闭，若还有问题请提新的issue,并附带复现代码片段排查。
