### ISSUE TITLE
[Bug Report] 在使用 van-popup 包含其他vant组件时，全局自定义样式无法穿透到其他vant组件

### ISSUE THREAD

**Issue by shumyun** [youzan/vant-weapp#5199]
### 重现链接

在使用 van-popup 包含其他vant组件时，全局自定义样式无法穿透到其他vant组件

### Vant Weapp 版本

1.10.11

### 描述一下你遇到的问题。

在使用 van-popup 包含其他vant组件时，全局自定义样式无法穿透到其他vant组件

### 重现步骤

`<van-popup show="{{true}}" round>
      <van-button type="default" size="small" plain>取消返回</van-button>
</van-popup>`
`page {
  --button-info-background-color: #037ef3;
  --button-info-border-color: #037ef3;
}`

**Comment by landluck** [comment]
`button-info-background-color: #037ef3; --button-info-border-color: #037ef3;` 这两个css 变量是 button 组件的type 为info时才会生效 `<van-button type="info" size="small" plain>取消返回</van-button>`
