### ISSUE TITLE
tab组件内嵌套tab组件，内层tab的底部滑块不显示

### ISSUE THREAD

**Issue by huajianjiu** [youzan/vant-weapp#5200]
### 重现链接

tab组件内嵌套tab组件，如果外层type=card，内层滑块会被遮挡，显示不出来。

### Vant Weapp 版本

1.10.12

### 描述一下你遇到的问题。

tab组件内嵌套tab组件，如果外层type=card，内层滑块会被遮挡，显示不出来。

### 重现步骤

外层tabs的type设置位card，此时内层tab的滑块就无法显示，经过检查发现是高度不够，导致滑块无法显示，怀疑是内层tab继承了外层tab的高度。
外层type=line时内层滑块正常显示
![外层type=line](https://user-images.githubusercontent.com/80043508/213839939-6324863b-0363-4bc7-8f61-af42d21fffd3.png)

外层type=card时内层滑块被盖住
![image](https://user-images.githubusercontent.com/80043508/213840174-20d0fa4a-b38b-4869-9135-b2c5e801abfb.png)

经过检查发现滑块被渲染了，但是被遮挡住了，scroll-view高度不够
![2](https://user-images.githubusercontent.com/80043508/213840006-73a0f9a7-c55d-4bd1-b1ac-741672aa1492.png)

**Comment by 370295005** [comment]
请问有遇到过切换一级tab时二级tab的滑块的位置会不正确的情况吗
![image](https://user-images.githubusercontent.com/39272235/216877777-ef6482a3-9180-4422-920a-23f0211980f0.png)

**Comment by huajianjiu** [comment]
> 请问有遇到过切换一级tab时二级tab的滑块的位置会不正确的情况吗 ![image](https://user-images.githubusercontent.com/39272235/216877777-ef6482a3-9180-4422-920a-23f0211980f0.png)

这个倒是没有，一种解决方案是自己手写一层tab，或者用其他组件库的tab，混合使用

**Comment by johnsonwong666** [comment]
可以提供一个小程序代码片段吗？ 检查一下父级的高度是不是100%

**Comment by landluck** [comment]
`v1.10.17` 已修复

**Comment by MarryWu** [comment]
![image](https://user-images.githubusercontent.com/52279162/236594124-56e7aff6-a15f-4dbb-a3f7-27c1bd17b81c.png)
为什么我引入tab和tabs时候会报错 引入其他组件就没问题

**Comment by johnsonwong666** [comment]
> 

尝试重新构建npm，确认一下 usingcompnents的引用路径
