### ISSUE TITLE
[Bug Report] van-tabs组件吸顶效果延迟

### ISSUE THREAD

**Issue by jieboom** [youzan/vant-weapp#5202]
### 重现链接

暂无

### Vant Weapp 版本

1.6.4

### 描述一下你遇到的问题。

tabs组件滚动时，tab的吸顶效果会在当次触摸滚动完全结束后开始吸顶而不是即时吸顶。
目前查看[stick实现原理](https://github.com/youzan/vant-weapp/blob/dev/dist/sticky/index.js)，内部setDataAfterDiff方法使用了wx.nextTick方法缓存了滚动事件处理，但是nextTick会在所有pageScroll事件完成之后被调用，这就造成了tabs吸顶延迟的结果。

### 重现步骤

1. 设定一个可以滚动的tabs
2. 触摸屏幕并滑动
3. 观看tab吸顶效果

### 设备/浏览器

微信小程序IDE，IOS

**Comment by johnsonwong666** [comment]
你的意思是在一个容器里面 使用tab组件 然后这个容器滚动 tabs延迟吸顶吗？ 我试了一下没问题  可以提供一个小程序代码片段吗？

**Comment by johnsonwong666** [comment]
可以提供个小程序代码片段吗？目前测试无明显的延迟现象

**Comment by johnsonwong666** [comment]
由于较长时间没有提供复现代码片段，此issue关闭，若还有问题请提新的issue,并附带复现代码片段排查。
