### ISSUE TITLE
[Feature Request] 希望支持 skyline 渲染器

### ISSUE THREAD

**Issue by yfmeii** [youzan/vant-weapp#5203]
### 这个功能解决了什么问题？

在 skyline 渲染器下正常显示

### 你期望的 API 是什么样子的？

。

**Comment by landluck** [comment]
skyline 目前问题还比较多，需要等待微信底层功能逐渐完善，组件层目前兼容成本太高，短期内应该不会支持

**Comment by yfmeii** [comment]
收到，谢谢回复
