### ISSUE TITLE
[Bug Report] Stepper 中存在重复定义属性 always-embed

### ISSUE THREAD

**Issue by zyaxuan** [youzan/vant-weapp#5204]
### 重现链接

https://github.com/youzan/vant-weapp/compare/v1.10.11...v1.10.12

### Vant Weapp 版本

1.10.12

### 描述一下你遇到的问题。

运行报警告 提示 always-embed 重复属性

### 重现步骤

运行报警告 提示 always-embed 重复属性
![Uploading 图片.png…]()

**Comment by landluck** [comment]
`v1.10.13` 版本已修复
