### ISSUE TITLE
日历组件应该如何设置在平铺模式下，固定头部的信息

### ISSUE THREAD

**Issue by xtomoya** [youzan/vant-weapp#5205]
### 这个功能解决了什么问题？

日历这个组件，在文档右侧的展示中，已经实现了平铺模式下，可以固定头部的信息，如年份，月份数，周数，这些头部信息，并且往下滑动时，头部的年份数和月份数还会相应的变化。但是这个功能应该怎么设置在文档中却没有写。所以请问应该怎么设置组件，才能达到效果呢？

### 你期望的 API 是什么样子的？

123

**Comment by landluck** [comment]
通过 限制高度来实现，page {  --calendar-height: 500px; }
