### ISSUE TITLE
日历组件默认值的问题

### ISSUE THREAD

**Issue by 1432648870** [youzan/vant-weapp#5216]
### 重现链接

![图片](https://user-images.githubusercontent.com/52401283/217157294-1b408a2b-90f5-4228-861a-20f0be42b1b4.png)
![图片](https://user-images.githubusercontent.com/52401283/217157313-6d124a1c-a1aa-410d-82ea-8eef630a08ea.png)

### Vant Weapp 版本

1.10.12

### 描述一下你遇到的问题。

日历组件会有一个默认值  当这个默认值取消选中的时候  下面的确定按钮被禁用不能进行下一步  

### 重现步骤

1.引入日历组件
2.使用可选择多值的属性
3.点击打开标签  会默认的勾选今天的日期  取消今天的日期 确定按钮禁用问题
![图片](https://user-images.githubusercontent.com/52401283/217157730-fd639275-9924-4fa8-84a1-049192338a81.png)

**Comment by landluck** [comment]
`v1.10.13` 版本已 `min-range` 属性可以进行配置
