### ISSUE TITLE
[Bug Report] cascader 点击已选择的tab返回后重新选择另一个没有children的选项会出现弹窗异常

### ISSUE THREAD

**Issue by muzhichu** [youzan/vant-weapp#5218]
### 重现链接

无

### Vant Weapp 版本

1.10.12

### 描述一下你遇到的问题。

选中级联选项（比如：江苏省，南京市）后，点击tab的【江苏省】返回上一级，然后选择没有【children】的【北京市】，cascader组件会出现高度丢失，选项内容丢失
具体如下图
![image](https://user-images.githubusercontent.com/17848645/217196133-92161e12-acdc-4401-ab6e-2b2bf5aceb58.png)
![image](https://user-images.githubusercontent.com/17848645/217196283-084cfe6b-aa21-4c3b-a720-a401e8c16aa7.png)
![image](https://user-images.githubusercontent.com/17848645/217196309-3e53d7cd-8297-480c-b404-72f836232c60.png)

### 重现步骤

测试代码如下，使用的`uniapp + vue3`写法，按官方例子
**重现步骤：**
1. `options`添加一个有`children`一个没有`children`的选项对象
2. 选择【江苏省】【南京市】选项
3. 点击`tab`的【江苏省】返回到上一级
4. 选择北京市即可复现

**原因：**
经研究原因为`cascader`组件中的`onClickTab`事件触发时没有同步更新`activeTab`值，导致此时选择没有`children`的选项时`activeTab`错乱

```
<template>
  <view>
    <van-field :value="fieldValue" is-link readonly label="地区" placeholder="请选择所在地区" @tap="onClick" />
    <van-popup :show="show" round position="bottom" @close="onClose">
      <van-cascader
        :value="cascaderValue"
        title="请选择所在地区"
        :options="options"
        @close="onClose"
        @finish="onFinish"
      />
    </van-popup>
  </view>
</template>

<script setup lang="ts">
import { ref } from 'vue'

const options = [
  {
    text: '北京市',
    value: '110000'
  },
  {
    text: '江苏省',
    value: '320000',
    children: [{ text: '南京市', value: '320100' }]
  }
]

const show = ref(false)
const fieldValue = ref('')
const cascaderValue = ref('')

const onClick = () => {
  show.value = true
}

const onClose = () => {
  show.value = false
}

const onFinish = (e: any) => {

  const { selectedOptions, value } = e.detail

  fieldValue.value = selectedOptions.map(option => option.text || option.name).join('/')

  cascaderValue.value = value
}
</script>

<style scoped></style>
```

### 设备/浏览器

IOS，微信开发者工具

**Comment by landluck** [comment]
`v1.10.13` 版本已修复
