### ISSUE TITLE
[Bug Report] van-tabs组件BUG

### ISSUE THREAD

**Issue by LiuXin-Developer** [youzan/vant-weapp#5220]
### 重现链接

https://developers.weixin.qq.com/s/0qP4bRmk70Fz

### Vant Weapp 版本

最新

### 描述一下你遇到的问题。

以下问题均在微信IOS环境有问题，Windows和安卓均正常，定位均为fixed
 一、在van-tabs组件中不设置z-index='0'，内部定位的盒子会被tab栏遮盖。
 二、加上animated属性后，tab内定位的内容不会消失。
 三、无论tabs组件里的元素z-index多高都无法覆盖页面中定位的盒子

### 重现步骤

使用ios真机调试或者预览，用苹果手机查看

### 设备/浏览器

微信小程序IOS

**Comment by landluck** [comment]
目前为了 tabs 滚动的体验所以加了 `-webkit-overflow-scrolling: touch` 属性，而在iOS13上WKWebView对这个属性 和 fixed 没有兼容好，属于系统问题，建议避免在 tabs 中使用 fixed 属性，可以放到 tabs 外部通过属性控制

**Comment by LiuXin-Developer** [comment]
> 目前为了 tabs 滚动的体验所以加了 `-webkit-overflow-scrolling: touch` 属性，而在iOS13上WKWebView对这个属性 和 fixed 没有兼容好，属于系统问题，建议避免在 tabs 中使用 fixed 属性，可以放到 tabs 外部通过属性控制

https://developer.mozilla.org/zh-CN/docs/Web/CSS/-webkit-overflow-scrolling 
![image](https://user-images.githubusercontent.com/48080203/218413203-9234cc5a-d8f6-463e-a624-9476a11e7b18.png)
只有苹果支持，而且还支持的不够好，还是不是在生产环境上用吧。或者添加一个prop控制是否添加可能会更好，避免更多的人踩坑。

**Comment by landluck** [comment]
`v1.10.14` 新增 `root-portal` 属性解决该问题

**Comment by landluck** [comment]
对于需要使用的 fixed 的组件可以使用微信 root-portal 属性脱离页面子树，解决问题，popup 在 `v1.10.14` 版本新增 ` root-portal` 用于解决 fixed 失效问题

**Comment by MarryWu** [comment]
版本1.10.17
![image](https://user-images.githubusercontent.com/52279162/236594525-087e8190-ec24-43b8-b44a-539d04eb0b2b.png)
tab和tabs组件找不到 但是包里是有的 其他组件能正常使用 我试过很多次了 也重新构建了 就是用不了
