### ISSUE TITLE
want weapp 目前能实现这样的气泡弹出框么

### ISSUE THREAD

**Issue by yisirman** [youzan/vant-weapp#5221]
### 这个功能解决了什么问题？

类似这样的
<img width="243" alt="image" src="https://user-images.githubusercontent.com/15642586/217441026-1a5e3846-8d98-4240-8537-e32139b20e8a.png">

### 你期望的 API 是什么样子的？

如上图

**Comment by landluck** [comment]
不太好实现，可以自己写个小组件就可以实现了
