### ISSUE TITLE
van-popup 组件 一个页面多次弹出之后 弹层越来越黑

### ISSUE THREAD

**Issue by 1432648870** [youzan/vant-weapp#5222]
### 重现链接

    <block wx:for="{{ editFormList }}" wx:for-index="editFormListIndex" wx:for-item="editFormListItem">
            <van-cell-group>
              <van-cell>
                <view slot="title" class="subtask-edit__title">子任务-{{ editFormListIndex+1 }}</view>
                <image wx:if="{{ editFormList.length > 1 }}" slot="right-icon" bindtap="onDelete" data-index="{{ editFormListIndex }}" data-item="{{ item }}" mode="widthFix" style="width: 36rpx; height: 36rpx;" src="/images/workSchedule/remove-red.png" />
              </van-cell>
            </van-cell-group>
            <view class="childrenBig">
              <view style="width: 25%;">任务名称<text class="txtColor">*</text></view>
              <van-field disabled wx:if="{{!editFormList[editFormListIndex].taskName}}" name='childrenName' data-editFormListIndex="{{editFormListIndex}}" bindtap="showChildrenName" placeholder="请选择子项目名称" value='{{editFormList[editFormListIndex].taskName}}' input-align="right" autosize type="textarea" style="width: 75%;text-align: right;color: #ccc;" right-icon="arrow">
              </van-field>
              <view bindtap="showChildrenName" data-editFormListIndex="{{editFormListIndex}}" style="width: 75%;text-align: right;padding-right: 15px;" wx:else>{{editFormList[editFormListIndex].taskName}}</view>
              <van-popup position="bottom" show="{{ show }}" z-index="{{ 99999 }}" overlay-style='background-color：block;opacity:0.1'>
                <view class="popHeader">
                  <view class="cancel" hover-class="cancel-hover" hover-stay-time="70" bindtap="popupClose">取消</view>
                  <view class="confirm" hover-class="confirm-hover" data-editFormListIndex="{{editFormListIndex}}" hover-stay-time="70" bindtap="popupConfirm">确定</view>
                </view>
                <view class="popupSelect">
                  <view wx:for="{{selectData }}" wx:key="index" class="popupOptions {{ item.isCheck ? 'active' : '' }}" data-value="{{ item.value }}" data-text="{{ item.label }}" data-data="{{ item }}" bindtap="optionClick">
                    <text class="optionText" style="text-align: {{ textAlign }};">{{ item.label }}</text>
                    <view class="optionIcon">
                      <van-icon name="success" wx:if="{{ item.isCheck }}" />
                    </view>
                  </view>
                </view>
                <view class="popupButton">
                </view>
              </van-popup>
            </view>
            <view class="childrenBig">
              <view style="width: 25%;">任务内容<text class="txtColor">*</text></view>
              <view style="width: 75%;">
                <van-field value="{{ editFormList[editFormListIndex].taskContent }}" data-editFormListIndex="{{editFormListIndex}}" bind:change='taskContentChange' name='childrenContent' placeholder="请输入子项目内容" autosize type="textarea" border="{{ false }}" style="width: 100%;text-align: right;color: #ccc;font-size: 15px;" input-align="right" maxlength='100' />
            
              </view>
            </view>
            <view class="childrenBig">
              <view style="width: 25%;" name='childrenPeople'>选择参与人<text class="txtColor">*</text></view>
            </view>
            <van-checkbox-group class="checkSty" value="{{ result[editFormListIndex] }}" bind:change="onChange" data-editFormListIndex="{{editFormListIndex}}" direction='vertical'>
              <block wx:for="{{ peopleList }}" wx:for-index="peopleListIndex" wx:for-item="peopleListItem">
                <van-checkbox shape="square" name="{{peopleListItem.staffId}}">{{peopleListItem.staffName}}</van-checkbox>
              </block>
            </van-checkbox-group>
          </block>

### Vant Weapp 版本

1.10.12

### 描述一下你遇到的问题。

循环嵌套里面的  随着数组下标增大  van-popup 组件的弹层越来越黑

![Uploading Snipaste_2023-02-09_11-52-05.png…]()

### 重现步骤

1.页面添加一个循环的数组，且该数据可以手动添加多组
2.循环里面有van-popup组件
3.添加数据可点击van-popup选择数据 
4.添加多组后  van-popup弹层一次比一次黑

### 设备/浏览器

苹果 安卓

**Comment by landluck** [comment]
这样其实是打开了很多个 popup， 建议不要嵌套在循环里，可以放在最外层，通过选中的参数来动态渲染内容
