### ISSUE TITLE
van-uploader组件希望增加一个showmenu参数，用于wx.previewImage的showmenu是否显示长按菜单。

### ISSUE THREAD

**Issue by RyanJeson** [youzan/vant-weapp#5223]
### 重现链接

无

### Vant Weapp 版本

1.10.12

### 描述一下你遇到的问题。

upload组件预览图片时，长按预览的图片会弹出：保存和转发的菜单弹窗。
微信小程序文档中wx.previewImage()预览图片的方法中有个参数「showmenu」，默认时true。作用于是否展示保存和转发的菜单弹窗。

### 重现步骤

无

**Comment by landluck** [comment]
`v1.10.13` 版本已支持
