### ISSUE TITLE
[Stepper] 计数器设置了max 输入值超过最大值 回弹时没有触发change事件

### ISSUE THREAD

**Issue by yisirman** [youzan/vant-weapp#5224]
### 重现链接

比如max设置最大值100，这个时候我输入了个200，会触发一次change事件，但是此次change事件的值是200
而页面上会自动变成最大值100，这个时候没有触发change事件

### Vant Weapp 版本

1.10.12

### 描述一下你遇到的问题。

比如max设置最大值100，这个时候我输入了个200，会触发一次change事件，但是此次change事件的值是200
而页面上会自动变成最大值100，这个时候没有触发change事件

### 重现步骤

1. 设置max=100
2. 输入200
3. 监听change事件

**Comment by landluck** [comment]
`v1.10.13` 版本已修复

**Comment by roy2651** [comment]
但是你上次修复了stepper修复了change后blur后触发两次的问题
