### ISSUE TITLE
vant-rate组件代码有bug,希望尽快处理[Bug Report] 请在此填写标题

### ISSUE THREAD

**Issue by Fahrenheitzz** [youzan/vant-weapp#5225]
### 重现链接

```
<view :class="(utils.bem('rate'))+' custom-class'" @touchmove="onTouchMove">
  <view v-for="(item,index) in (innerCountArray)" :key="item.index" :class="utils.bem('rate__item')" :style="style({ paddingRight: index !== count - 1 ? utils.addUnit(gutter) : null })">
```
 :key="item.index" 这块有问题

### Vant Weapp 版本

1.10.5

### 描述一下你遇到的问题。

rate组件代码key值绑定有问题，导致rateicon显示不出来，item里面并没有声明index，但是确使用了

### 重现步骤

下载，引用，就会出现问题

### 设备/浏览器

uni-app小程序编译成安卓端

**Comment by landluck** [comment]
该代码并不是vant-weapp 的源码，推测是 uni-app 转换后的，建议提交 issue 至 uni-app 处
