### ISSUE TITLE
popup组件内的元素无法获取node节点

### ISSUE THREAD

**Issue by LDH68** [youzan/vant-weapp#5226]
### 重现链接

无

### Vant Weapp 版本

1.10.8

### 描述一下你遇到的问题。

popup组件内的元素无法获取node节点,希望像vant一样增加一个lazy-render参数

### 重现步骤

在popup里node获取不到

**Comment by landluck** [comment]
具体是如何获取节点的？

**Comment by LDH68** [comment]
通过这个获取节点的
wx.createSelectorQuery().select('#the-id').boundingClientRect(function(rect){}

**Comment by landluck** [comment]
提供一个简单的小程序代码片段吧，在 popup 被弹出之前，popup 内部的节点的确是不存在的

**Comment by LDH68** [comment]
所以修复一下吧

**Comment by landluck** [comment]
popup 未弹出不加载节点本身是一种性能优化的手段，没弹出前需要获取里面的场景可以描述一下？

**Comment by LDH68** [comment]
是想做一个类似手机调节亮度，是通过点击或者滑动来调整数值，既然是一种性能优化的手段，那就没事了
