### ISSUE TITLE
[Bug Report] 通过组件调用 Dialog 时,z-index默认为1000，会覆盖toast

### ISSUE THREAD

**Issue by 9mhz** [youzan/vant-weapp#5233]
### 重现链接

<van-toast id="van-toast" zIndex="3000" />
<van-dialog  use-slot title="test" show="{{ showUserDialog }}" show-cancel-button data-show="showUserDialog" bind:close="hide" bind:confirm="onSubmit">
  <van-field model:value="{{ phone }}" center clearable label="用户手机号" placeholder="请输入手机号" border="{{ false }}" use-button-slot type="number" max-length="11">
    <van-button slot="button" size="small" type="info" bind:click="tapValidityPhone">
      校验
    </van-button>
  </van-field>
</van-dialog>

### Vant Weapp 版本

1.10.10

### 描述一下你遇到的问题。

[Bug Report] 通过组件调用 Dialog 时,z-index应默认为100，实际为2000，会覆盖toast
![image](https://user-images.githubusercontent.com/64386741/218375390-d4db08ab-80d7-441a-82ea-8d1cda87dbf0.png)

使用Toast组件的Options 提升z-index 也不起作用，依然为默认值1000

### 重现步骤

唤起弹窗，弹窗内按钮触发Toast，toast被dialog触发

### 设备/浏览器

模拟器/真机（Android）

**Comment by 9mhz** [comment]
![image](https://user-images.githubusercontent.com/64386741/218376429-2e5123ba-34b9-45a8-a08c-5ca2c3fefc1e.png)

**Comment by landluck** [comment]
目前 dialog 组件调用默认 z-index 的确为 2000，可以通过 props z-index 在组件上自定义调整，出于影响面考虑，暂时不会做更改
