### ISSUE TITLE
微信小程序<scroll-view>嵌套<van-dropdown-menu>组件使用问题

### ISSUE THREAD

**Issue by debugyou** [youzan/vant-weapp#5234]
### 重现链接

![0f680f58216febd793efde80390c2a4](https://user-images.githubusercontent.com/28646366/218415986-8a55afc8-f29f-4eb6-b018-4aadda4c5af2.png)

### Vant Weapp 版本

v1.10.13

### 描述一下你遇到的问题。

scroll-view开启自定义下拉(refresher-enabled)并且嵌套van-dropdown-menu组件使用的时候会出现高度计算不准确
![RHH)E8_ V@7)L11D7XW5OFX](https://user-images.githubusercontent.com/28646366/218415528-fe405136-150a-4bd3-b89e-733a77436048.png)

### 重现步骤

scroll-view开启自定义下拉(refresher-enabled)并且嵌套van-dropdown-menu组件使用的时候会出现高度计算不准确

**Comment by landluck** [comment]
scroll-view 需要写高度的

**Comment by debugyou** [comment]
> scroll-view 需要写高度的

设置了高度也是一样的
![693b74712be091815332b8a91f65d97](https://user-images.githubusercontent.com/28646366/218651547-4e7cc7f6-adce-4af8-8e35-f1f26e3418b8.png)
![16317f1f4f9e692db9213cdb51da30d](https://user-images.githubusercontent.com/28646366/218651569-b4d2afd0-d31b-4a9d-8498-8cddef0f68d8.png)
![271ce620da05a92f9fc5b80adeab32a](https://user-images.githubusercontent.com/28646366/218651584-c3b06078-2e66-4478-a4d2-3438f90b9e49.png)

**Comment by debugyou** [comment]
> scroll-view 需要写高度的

再次做了测试，因为小程序自定义了顶部导航，发现多出来的空白就是导航栏的高度

**Comment by debugyou** [comment]
> scroll-view 需要写高度的

这个bug能修复不

**Comment by landluck** [comment]
这两天看一下，能修的话下周一的版本修复

**Comment by debugyou** [comment]
> 这两天看一下，能修的话下周一的版本修复

非常感谢！

**Comment by landluck** [comment]
根源问题是https://developers.weixin.qq.com/community/develop/doc/0000667484c96844b83ac9c7651809，scroll-view 开启了 refresher-enabled 后会导致 fixed 失效变成 absolute，暂时没想到太好的办法解决，是否可以接受基础库大于 2.25.2

**Comment by debugyou** [comment]
> 

可以的，基础库目前是2.30.0

**Comment by landluck** [comment]
`v1.10.14` 新增  `root-portal ` 参数
