### ISSUE TITLE
真机输入框（field组件和search组件等）有多个输入框切换时候（比如用户，密码切换），就要点击2次才能获取焦点

### ISSUE THREAD

**Issue by 526589640** [youzan/vant-weapp#5235]
### 重现链接

官网小程序体验就知道了，官网的就有BUG，真机2个以上输入框切换，需要点2次才能获取焦点，开发工具是不会。可以直接扫官方小程序码体验下field和search组件就知道

### Vant Weapp 版本

1.10.13

### 描述一下你遇到的问题。

官网小程序体验就知道了，官网的就有BUG，真机2个以上输入框切换，需要点2次才能获取焦点，开发工具是不会。可以直接扫官方小程序码体验下field和search组件就知道

### 重现步骤

官网小程序体验就知道了，官网的就有BUG，真机2个以上输入框切换，需要点2次才能获取焦点，开发工具是不会。可以直接扫官方小程序码体验下field和search组件就知道

### 设备/浏览器

安卓和ios手机都会出现

**Comment by landluck** [comment]
该问题微信原生 input 就存在问题，组件层暂时没有办法解决，可以关注微信社区 https://developers.weixin.qq.com/community/develop/doc/000a48ad86c1d86d058b4be1151000?_at=1656923325476

**Comment by 526589640** [comment]
> 该问题微信原生 input 就存在问题，组件层暂时没有办法解决，可以关注微信社区 https://developers.weixin.qq.com/community/develop/doc/000a48ad86c1d86d058b4be1151000?_at=1656923325476

原生不会啊。原生输入框切换不用点2次啊

**Comment by landluck** [comment]
> 可以试下原生 input 也会有这个问题，微信社区是有类似的问题在
