### ISSUE TITLE
日历组件 区间选择器报错

### ISSUE THREAD

**Issue by wujingjin1** [youzan/vant-weapp#5236]
### 重现链接

....

### Vant Weapp 版本

1.10.13

### 描述一下你遇到的问题。

设置区间,随机会走 if (isDisabled) {
                                (date = days_1[index - 1].date); 方法导致date报错
                            }

### 重现步骤

随即设置区间

**Comment by landluck** [comment]
https://github.com/youzan/vant-weapp/issues/5165
