### ISSUE TITLE
在最新的基础库版本2.3.0使用van-datetime-picker报错

### ISSUE THREAD

**Issue by Edwin-hot** [youzan/vant-weapp#5237]
### 重现链接

使用方式
![image](https://user-images.githubusercontent.com/55945775/219271132-ecedc740-fc5a-4473-8490-958b677c5f02.png)
编译之后
![image](https://user-images.githubusercontent.com/55945775/219270765-4135ebf8-dba2-439a-914e-1575dbdc90fd.png)

### Vant Weapp 版本

1.10.13

### 描述一下你遇到的问题。

日期组件无法使用

### 重现步骤

在uniapp里面按需引入vant,并引入相应依赖包，然后编译uniapp代码，

### 设备/浏览器

微信开发者工具

**Comment by landluck** [comment]
微信原生小程序并未复现，uniapp 不在支持范围，可以在uniapp 社交提交问题反馈
