### ISSUE TITLE
Search组件

### ISSUE THREAD

**Issue by daimawanjiaA** [youzan/vant-weapp#5239]
### 重现链接

"usingComponents": {
    "van-button": "@vant/weapp/button/index"
  }

<van-search
  value="{{ value }}"
  placeholder="请输入搜索关键词"
  show-action
  bind:search="onSearch"
  bind:cancel="onCancel"
/>

### Vant Weapp 版本

1.10.13

### 描述一下你遇到的问题。

Search组件中，搜索icon和取消键出现在搜索栏外（上下），搜索栏独占一行

### 重现步骤

前端引用search组件

### 设备/浏览器

基础库2，10，4

**Comment by landluck** [comment]
没有复现，参考 https://developers.weixin.qq.com/miniprogram/dev/devtools/minicode.html 提供一个可复现的代码片段

**Comment by landluck** [comment]
复现提供小程序代码片段后可以重新打开issue
