### ISSUE TITLE
van-calendar无法关闭的问题

### ISSUE THREAD

**Issue by huweinumber1** [youzan/vant-weapp#5240]
### 重现链接

```[tasklist]
### Tasks
- [ ] Add a draft title or issue reference here
```

<van-field label="{{item.name}}" border="{{item.setting.border}}" required="{{item.required}}" bindtap="selectDate" data-formindex="{{index}}">
          <view slot="input" style="width: 100%;color: {{form[item.eName]?'#000000':'#c8c9cc'}};" >
            <block wx:if="{{item.type==='date'}}">
              {{form[item.eName]?form[item.eName]:item.setting.placeholder}}
              <van-calendar close-on-click-overlay="{{false}}" show="{{ item.setting.show }}" type="{{item.setting.type}}" bind:close="dateClose" bind:confirm="dateConfirm" data-ename="{{item.eName}}" data-formindex="{{index}}" />
            </block>
          </view>
        </van-field>

### Vant Weapp 版本

1.10.13

### 描述一下你遇到的问题。

当我将日历嵌套在文本框中时，文本框加上一个bindtap事件，打开日历弹窗后无法关闭，可以正常执行close事件，但是执行后会再次执行文本框中的bindtap事件（也就是打开弹窗事件），导致无法进行关闭，js的代码就是正常的开关弹窗，暂时没有找到是我代码的问题

### 重现步骤

点击文本框打开弹窗
点击遮罩处或者关闭按钮

**Comment by landluck** [comment]
提供一个小程序代码片段吧

**Comment by huweinumber1** [comment]
> 提供一个小程序代码片段吧

`<van-field label="{{item.name}}" border="{{item.setting.border}}" required="{{item.required}}" bindtap="selectDate" data-formindex="{{index}}">
          <view slot="input" style="width: 100%;color: {{form[item.eName]?'#000000':'#c8c9cc'}};" >
            <block wx:if="{{item.type==='date'}}">
              {{form[item.eName]?form[item.eName]:item.setting.placeholder}}
              <van-calendar close-on-click-overlay="{{false}}" show="{{ item.setting.show }}" type="{{item.setting.type}}" bind:close="dateClose" bind:confirm="dateConfirm" data-ename="{{item.eName}}" data-formindex="{{index}}" />
            </block>
          </view>
        **</van-field>`**

**Comment by landluck** [comment]
bindtap 绑定在 field 组件上，而 calendar 组件在这种情况下也属于 field 的一部分，所以建议在 <view slot="input"  这个标签下再写个 view 在calendar 没弹出来时撑满，把 bindtap 打开事件写在这个标签上面，就不会出现这个问题了

**Comment by huweinumber1** [comment]
> 
如何理解在calendar没弹出来时撑满这句话

**Comment by landluck** [comment]
需要给 view 一个宽度，撑满右边区域，增大点击范围

**Comment by huweinumber1** [comment]
> 需要给 view 一个宽度，撑满右边区域，增大点击范围

收到，谢谢
