### ISSUE TITLE
tree-select 三级联动

### ISSUE THREAD

**Issue by CallMeHiker** [youzan/vant-weapp#5242]
### 这个功能解决了什么问题？

希望vant，可以出个三级联动控件，类似网页的tree-select，2级，3级，4级皆可，定制化自由度更高。

### 你期望的 API 是什么样子的？

[
  {
    text: '所有城市',
    children: [
      {
        text: '杭州',
        id: 1002,
        children:  [
           {
             text: '西湖',
             id: 10021
           }
        ]
      },
      {
        text: '温州',
        id: 1001,
        children:  [
           {
             text: '皮革厂',
             id: 10011
           }
        ]
      }
    ]
  }
]

**Comment by landluck** [comment]
多级联动 https://youzan.github.io/vant-weapp/#/cascader 这个不满足吗

**Comment by CallMeHiker** [comment]
嗯，旧版的没看到这个控件，可以。但还是不能满足项目的业务场景，还是自己造一个吧 ^ . ^
