### ISSUE TITLE
[Feature Request] “快速上手”教程无法跑通，建议更新文档

### ISSUE THREAD

**Issue by zzz2016** [youzan/vant-weapp#5244]
### 这个功能解决了什么问题？

使用目前最新版的微信小程序 IDE（1.06.2301160），模版为官方 TS 模版。
按照“快速上手”步骤三指南，无法构建 NPM，提示找不到 NPM。
经过 debug，发现配置需改为：
`
"packNpmManually": true,
"packNpmRelationList": [
  {
    "packageJsonPath": "package.json",
    "miniprogramNpmDistDir": "./miniprogram/"
  }
],

`
注意  "packageJsonPath": "package.json", 不再需要"./"。

另外，建议在“使用”-“引入组件”模块，为微信 IDE 这套逻辑增加实例，比如引入包的地址实际为: "miniprogram_npm/xxx"，避免不熟悉微信小程序 NPM 机制的用户误以为是 "node_modules/xxx"。 

### 你期望的 API 是什么样子的？

无

**Comment by zzz2016** [comment]
update: 不是路径的问题，是新版的 IDE 必须清理一遍工作区缓存，才能正确执行

**Comment by DawLee** [comment]
遇到同样问题，清理完缓存还是提示未找到

**Comment by DawLee** [comment]
<img width="526" alt="Screenshot 2023-03-16 at 00 43 09" src="https://user-images.githubusercontent.com/26499267/225380164-2732f1aa-6ede-4974-8c11-3dff66b9c3f3.png">
