### ISSUE TITLE
radio check 组应该支持label

### ISSUE THREAD

**Issue by zeroone2005** [youzan/vant-weapp#5245]
### 这个功能解决了什么问题？

比如要横向排选择性别
性别：○ 男   ○女

### 你期望的 API 是什么样子的？

```
 <van-radio-group value="{{ user.gender }}" label="性别" direction="horizontal">
```

**Comment by landluck** [comment]
![image](https://user-images.githubusercontent.com/27060081/221398207-5c6badeb-717d-4e59-895f-cf7f881fdf92.png)
该属性已支持
