### ISSUE TITLE
给tab标签页添加样式风格选择标识

### ISSUE THREAD

**Issue by LwcStrong** [youzan/vant-weapp#5247]
### 这个功能解决了什么问题？

![image](https://user-images.githubusercontent.com/93753404/220560967-3eb231f1-d798-484d-9b0e-1576760ac7e1.png)

图中黄色标注的tab根标签背景无法跟换，可以考虑添加一个around样式标识用布尔值控制，表示是否开启圆角风格，期望样式
![image](https://user-images.githubusercontent.com/93753404/220561557-89e79911-4ef9-4ae1-8d9d-c7c0656a7fe9.png)
忘官方考虑，因为目前提供的修改样式入口无法实现期望效果

### 你期望的 API 是什么样子的？

<van-tabs around>
  <van-tab title="标签 1"></van-tab>
</van-tabs>

**Comment by LwcStrong** [comment]
<van-tabs around>
  <van-tab title="标签 1">内容 1</van-tab>
</van-tabs>

**Comment by landluck** [comment]
可以使用 `--tabs-nav-background-color` css 变量改变该背景颜色
