### ISSUE TITLE
[Bug Report] 关于picker的一些问题

### ISSUE THREAD

**Issue by Rochester-Ting** [youzan/vant-weapp#5248]
### 重现链接

https://github.com/youzan/vant-weapp/blob/dev/dist/picker/index.wxs
https://github.com/youzan/vant-weapp/blob/dev/dist/picker-column/index.wxs
这两个文件里的样式 都没加单位, 确定是这样的么?

### Vant Weapp 版本

1.10.13

### 描述一下你遇到的问题。

在使用area, picker, datepicker的时候 均无法展示ui, 于是进入看代码的时候发现样式 均未加单位, 审查元素也发现style="height:264", 是故意这样实现的么

### 重现步骤

<van-area
  area-list="{{ list }}"
  title="请选择城市"
  value="110101"
/>

**Comment by landluck** [comment]
addUnit 方法中会默认添加 px 单位，无法展示 UI 可以提供一个可复现的小程序代码片段协助排查

**Comment by landluck** [comment]
可复现时提供小程序代码片段后重新打开 issue
