### ISSUE TITLE
icon 自定义图标 不支持徽标么？

### ISSUE THREAD

**Issue by yisirman** [youzan/vant-weapp#5250]
### 重现链接

    <van-icon color="#464646" class-prefix="icon" name="payment" dot  />

### Vant Weapp 版本

v1.10.13

### 描述一下你遇到的问题。

icon 自定义图标 徽标没有显示

### 重现步骤

如上所示

**Comment by landluck** [comment]
`v1.10.14` 已修复

**Comment by yisirman** [comment]
> `v1.10.14` 已修复

这个问题修复了 但是 custom-class 却失效了 @landluck

**Comment by landluck** [comment]
可以提供一个小程序代码片段我看看是怎么用的
