### ISSUE TITLE
微信小程序注册组件时使用官方提供的注册地址报错未找到该模块

### ISSUE THREAD

**Issue by zhangsite** [youzan/vant-weapp#5251]
### 重现链接

{
  "usingComponents": {
    "van-button": "path/to/vant-weapp/dist/button/index"
  }
}

### Vant Weapp 版本

0.5.29

### 描述一下你遇到的问题。

![image](https://user-images.githubusercontent.com/92500365/221068581-8fbf4f64-01a4-4fa4-a09d-2c79c139645e.png)
["usingComponents"]["van-button"]: "path/to/vant-weapp/dist/button/index" 未找到

### 重现步骤

任意注册一个vant-weapp提供的组件

**Comment by zhangsite** [comment]
![image](https://user-images.githubusercontent.com/92500365/221080404-2e6cd85e-41ce-4c7c-99de-e653c10d0722.png)
构建npm miniprogram_npm/vant-weapp目录下没有dist文件夹

**Comment by landluck** [comment]
你是怎么安装依赖的？

**Comment by landluck** [comment]
无法复现问题，如能复现可以提供小程序代码片段后重新打开issue
