### ISSUE TITLE
tabBar组件中placeholde 固定在底部时，在标签位置没有生成一个等高的占位元素

### ISSUE THREAD

**Issue by LDH68** [youzan/vant-weapp#5259]
### 重现链接

[https://developers.weixin.qq.com/s/FGv30mmN70Gv](url)

### Vant Weapp 版本

1.10.8

### 描述一下你遇到的问题。

tabBar组件中placeholde 固定在底部时，在标签位置没有生成一个等高的占位元素

### 重现步骤

<van-tabbar active="{{ active }}" bind:change="onChange" fixed="{{true}}" placeholder="{{true}}">
  <van-tabbar-item wx:for="{{ list }}" wx:key="index" icon="{{ item.icon }}">
    {{item.text}}
  </van-tabbar-item>
</van-tabbar>

**Comment by landluck** [comment]
https://github.com/youzan/vant-weapp/issues/5272

**Comment by landluck** [comment]
原因是 tabbar 配置了 "custom": true 将 tabbar 变成微信小程序自定义tabbar了，微信将该 tabbar节点 page 节点树中抽离了出来，van-tabbar 自定义的展位高度就会失效，对于这种情况建议在全局写一个样式 page { padding-bottom: 50px } 即可解决

**Comment by LDH68** [comment]
全局写一个样式 page { padding-bottom: 50px; margin-bottom: constant(safe-area-inset-bottom); margin-bottom: env(safe-area-inset-bottom); }，显示的比以前多一点，但是没有显示完全
[https://developers.weixin.qq.com/s/efODQvmm7LGp](https://github.com/youzan/vant-weapp/issues/url)
