### ISSUE TITLE
[Bug Report] Calendar日历组件，allow-same-day时，起止选择相同日期的情况下，bind:confirm未触发

### ISSUE THREAD

**Issue by hatriotism** [youzan/vant-weapp#5262]
### 重现链接

<van-calendar 
          type="range" 
          allow-same-day 
          poppable="{{ false }}" 
          show-confirm="{{ false }}" 
          class="calendar" 
          first-day-of-week="1" 
          show-title="{{ false }}" 
          bind:confirm="onCalendarConfirm"
 />

### Vant Weapp 版本

1.10.14

### 描述一下你遇到的问题。

Calendar日历组件 在allow-same-day且show-confirm="{{ false }}"时，起止选择相同日期时，bind:confirm未触发

### 重现步骤

1. 像下面这样配置calendar：
type="range" 
allow-same-day 
poppable="{{ false }}" 
show-confirm="{{ false }}" 
first-day-of-week="1" 
show-title="{{ false }}" 
bind:confirm="onCalendarConfirm"
2. 点击同一个日期两下，使这个日期上出现“开始/结束”文案，表示这个日期既是开始日期，又是结束日期。
3. 在onCalendarConfirm中console.log一下。
4. 发现onCalendarConfirm没有被触发。

**Comment by wesweet** [comment]
可以监听select事件，手动判断一下event.detail中，数组第二项是否为null，来解决

**Comment by landluck** [comment]
`v1.10.15` 已解决
