### ISSUE TITLE
vant中tabbar的placeholder属性占位失效

### ISSUE THREAD

**Issue by xmengweb** [youzan/vant-weapp#5272]
### 重现链接

这是代码片段:https://developers.weixin.qq.com/s/J9GOssmS7RGX

```
<van-tabbar active="{{ active }}" bind:change="onChange" placeholder="{{true}}" fixed="{{true}}">
  <van-tabbar-item wx:for="{{ list }}" wx:key="index" icon="{{ item.icon }}">
    {{item.text}}
  </van-tabbar-item>
</van-tabbar>
<!-- 首先在自己的项目中发现无效,接着使用的是vant中tabbar的代码片段,将placeholder属性设置为true发现也并没有用 -->
```

### Vant Weapp 版本

1.10.14

### 描述一下你遇到的问题。

首先在自己的项目中发现无效,接着使用的是vant中tabbar的代码片段,将placeholder属性设置为true发现也并没有用

### 重现步骤

1.在index页面使用wxfor生成100个数据,有一部分数据被tabbar遮挡,使用placeholder属性依然无效

**Comment by landluck** [comment]
原因是  tabbar 配置了 `"custom": true` 将 tabbar 变成微信小程序自定义tabbar了，微信将该 tabbar节点 page 节点树中抽离了出来，van-tabbar 自定义的展位高度就会失效，对于这种情况建议在全局写一个样式 page { padding-bottom: 50px } 即可解决

**Comment by LDH68** [comment]
全局写一个样式 page { padding-bottom: 50px } ;没有用，显示的比以前多一点，但是没有显示完全

**Comment by landluck** [comment]
`
page {
    padding-bottom: 50px;
    margin-bottom: constant(safe-area-inset-bottom);
    margin-bottom: env(safe-area-inset-bottom);
}
`

**Comment by LDH68** [comment]
全局写一个样式 page { padding-bottom: 50px; margin-bottom: constant(safe-area-inset-bottom); margin-bottom: env(safe-area-inset-bottom); }，显示的比以前多一点，但是没有显示完全
[https://developers.weixin.qq.com/s/efODQvmm7LGp](url)


> `page { padding-bottom: 50px; margin-bottom: constant(safe-area-inset-bottom); margin-bottom: env(safe-area-inset-bottom); }`

**Comment by landluck** [comment]
https://developers.weixin.qq.com/s/79P9hvmT7KGj
