### ISSUE TITLE
[Bug Report] icon组件在iphone13上突然不显示了

### ISSUE THREAD

**Issue by TG-Yi** [youzan/vant-weapp#5274]
### 重现链接

 
![微信截图_20230306212957](https://user-images.githubusercontent.com/31760577/223126490-8429bc72-e409-48c9-9f59-8af95be89918.png)

### Vant Weapp 版本

1.10.2

### 描述一下你遇到的问题。

icon组件在iphone13上突然不显示了

### 重现步骤

生成环境之前一直都正常显示，这两天一个客户的iPhone13微信小程序上就不显示所有的vant-icon图标了，我们公司同型号的测试机都正常显示

### 设备/浏览器

iPhone13微信小程序，部分机型可以复现

**Comment by landluck** [comment]
你们的小程序是什么？线上能复现吗

**Comment by TG-Yi** [comment]
我们是使用uniapp开发的微信小程序，目前线上有一位客户最近出现的这个问题，之前这个客户是可以正常访问的，他的手机是iPhone13，我们使用公司的同机型测试机并没有复现这个问题




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "youzan/vant-weapp"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月7日(星期二) 上午10:04
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [youzan/vant-weapp] [Bug Report] icon组件在iphone13上突然不显示了 (Issue #5274)





 
你们的小程序是什么？线上能复现吗

**Comment by landluck** [comment]
icon 有依赖 阿里 的 iconfont 服务，如果没法复现可以让用户尝试换个网络试试

**Comment by TG-Yi** [comment]
我们也是建议客户换个网络试试，目前还没有得到反馈，我看在Issues也有类型的问题，这个icon是否可以使用本地资源访问的形式来替换远程请求


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "youzan/vant-weapp"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月7日(星期二) 上午10:15
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [youzan/vant-weapp] [Bug Report] icon组件在iphone13上突然不显示了 (Issue #5274)





 
icon 有依赖 阿里 的 iconfont 服务，如果没法复现可以让用户尝试换个网络试试

**Comment by landluck** [comment]
换成本地的话体积会比较大，会一定程度影响主包体积，影响到包下载速度，对于这种网络波动或者运营商问题，换个网络或者过几个小时都会恢复的

**Comment by TG-Yi** [comment]
好的，谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "youzan/vant-weapp"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月7日(星期二) 上午10:26
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [youzan/vant-weapp] [Bug Report] icon组件在iphone13上突然不显示了 (Issue #5274)





 
换成本地的话体积会比较大，会一定程度影响主包体积，影响到包下载速度，对于这种网络波动或者运营商问题，换个网络或者过几个小时都会恢复的
