### ISSUE TITLE
[Bug Report] 找不到模块“@vant/weapp/dialog/dialog”或其相应的类型声明。ts(2307)

### ISSUE THREAD

**Issue by lwm98** [youzan/vant-weapp#5276]
### 重现链接

![image](https://user-images.githubusercontent.com/48340898/223602175-fda58704-c92d-4f4f-90d4-07e434ca81f3.png)
![image](https://user-images.githubusercontent.com/48340898/223602232-44b44bf4-2739-4f25-a3be-3d5f7087abc6.png)
![image](https://user-images.githubusercontent.com/48340898/223602258-c74191f4-6fa3-483a-b536-23c434c13543.png)

### Vant Weapp 版本

1.10.14

### 描述一下你遇到的问题。

编辑器标线，但是能正常使用，请问还缺了啥配置吗

### 重现步骤

快速入门，一步步配置下来的

**Comment by landluck** [comment]
![image](https://user-images.githubusercontent.com/27060081/224247845-65b3e9e7-6b51-42b2-902e-8d2d26e5a0fd.png)
这个里面改成 

```json
  "paths": {
      "@vant/weapp/*": ["node_modules/@vant/weapp/dist/*"]
    },
```
