### ISSUE TITLE
icon组件显示异常

### ISSUE THREAD

**Issue by Windancer** [youzan/vant-weapp#5278]
### 重现链接

https://vant-contrib.gitee.io/vant-weapp/#/icon

### Vant Weapp 版本

1.10.14

### 描述一下你遇到的问题。

`<van-icon name="wechat" /> 显示成了 <van-icon name="wechat-pay" />，
<van-icon name="wechat-pay" />无显示`

### 重现步骤

```
<van-icon name="wechat" />
<van-icon name="wechat-pay" />
```

**Comment by landluck** [comment]
没有复现，如能复现可以提供一个小程序代码片段协助排查

**Comment by Windancer** [comment]
![image](https://user-images.githubusercontent.com/4556814/224642623-73fe850b-38a6-4c3e-ae9c-0863de9e59ee.png)

**Comment by Windancer** [comment]
wechat显示的是wechat-pay， wechat-pay没显示

**Comment by fanburger** [comment]
没复现, 我检查过woff2字体文件和源代码了, 都没有问题, 你在开发者工具里面尝试重新构建一下npm看看
![image](https://user-images.githubusercontent.com/101820556/230157486-6e1c0e83-a674-43b9-9041-9c5aeef68a46.png)

**Comment by johnsonwong666** [comment]
没有复现，重新构建一下npm看看

**Comment by johnsonwong666** [comment]
https://github.com/youzan/vant-weapp/issues/5286

**Comment by johnsonwong666** [comment]
没有复现。由于较长时间没有提供复现代码片段，此issue关闭，若还有问题请提新的issue,并附带复现代码片段排查。
