### ISSUE TITLE
[Bug 小程序] ：van-circle环形进度条问题

### ISSUE THREAD

**Issue by MengChenLee** [youzan/vant-weapp#5279]
### 重现链接

https://vant-contrib.gitee.io/vant-weapp/#/circle

### Vant Weapp 版本

1.10.14

### 描述一下你遇到的问题。

小程序渲染多个van-circle环形进度条时，canvas中的canvas-id都为"van-circle"，当实现显示和隐藏操作时会报小程序 <canvas>:canvas-id van-circle in this page has already exist

### 重现步骤

<block wx:if="{{circleShow}}">
    <van-circle value="60" color="#07c160" stroke-width="5" size="50" />
    <van-circle value="30" color="#07c160" stroke-width="5" size="50" />
    <van-circle value="50" color="#07c160" stroke-width="5" size="50" />
    <van-circle value="80" color="#07c160" stroke-width="5" size="50" />
    <van-circle value="100" color="#07c160" stroke-width="5" size="50" />
</block>

### 设备/浏览器

小小程序手机端报错

**Comment by landluck** [comment]
没有能复现，如能复现可以提供一个简单的小程序代码片段

**Comment by johnsonwong666** [comment]
没有能复现，可以提供一个简单的小程序代码片段吗？

**Comment by johnsonwong666** [comment]
没有复现。由于较长时间没有提供复现代码片段，此issue关闭，若还有问题请提新的issue,并附带复现代码片段排查。

**Comment by CaniceZ** [comment]
这个bug咋还没在，触发条件：多个组件+显隐+重新设值
