### ISSUE TITLE
van-nav-bar导航safe-area-inset-top设置为false不生效[Bug Report] 请在此填写标题

### ISSUE THREAD

**Issue by Artanis-c** [youzan/vant-weapp#5280]
### 重现链接

在小程序wxml中仅添加这个组件
<van-nav-bar
  title="图书类别"
  left-text="返回"
  right-text="按钮"
  left-arrow
  bind:click-left="onClickLeft"
  bind:click-right="onClickRight"
  safe-area-inset-top="false"
/>

### Vant Weapp 版本

1.10.14

### 描述一下你遇到的问题。

在小程序页面中引用van-nav-bar组件，组件和小程序顶部中间会有一个无法消除的高度样式，safe-area-inset-top=false 也无法消除。
样式为:padding-top:47px

### 重现步骤

在小程序页面中引用van-nav-bar组件，组件和小程序顶部中间会有一个无法消除的高度，safe-area-inset-top=false 也无法消除

### 设备/浏览器

微信小程序

**Comment by landluck** [comment]
```html
 <van-nav-bar title="标题" left-text="返回" left-arrow safe-area-inset-top="{{ false }}">
    <van-icon name="search" slot="right" custom-class="icon" size="18" />
  </van-nav-bar>
```

是这么写的吗
