### ISSUE TITLE
conflict with useExtendedLib kbone weui

### ISSUE THREAD

**Issue by lishoulong** [youzan/vant-weapp#5281]
### 重现链接

设置了 useExtendedLib kbone weui，会导致 vant-weapp 样式失效。

### Vant Weapp 版本

1.10.14

### 描述一下你遇到的问题。

vant 样式失效

### 重现步骤

app.json 去掉 style：v2，设置
 "useExtendedLib": {
    "kbone": true,
    "weui": true
  }
使用van-button 组件，样式会失效。

**Comment by johnsonwong666** [comment]
没有复现。可以提供一个代码片段吗？

**Comment by johnsonwong666** [comment]
没有复现。由于较长时间没有提供复现代码片段，此issue关闭，若还有问题请提新的issue,并附带复现代码片段排查。
