### ISSUE TITLE
Radio label 自定义文本颜色不生效

### ISSUE THREAD

**Issue by yisirman** [youzan/vant-weapp#5282]
### 重现链接

![image](https://user-images.githubusercontent.com/15642586/224461295-65a33288-5f58-4ab9-8360-0241916b54a5.png)
![image](https://user-images.githubusercontent.com/15642586/224461304-8cac5d13-768e-47f8-b24c-2a3246da9e07.png)

### Vant Weapp 版本

1.10.13

### 描述一下你遇到的问题。

通过label-class 自定义也没有生效 其他样式可以生效 字体颜色无法生效

### 重现步骤

如上所示

**Comment by fanburger** [comment]
解决方案（推荐第二种方式）：
关于方式1的更多细节请查看[官方文档](https://vant-contrib.gitee.io/vant-weapp/#/theme)；
关于方式2：因为我在 radio 的源码中看到 radio 组件的 label 部分代码其实有一个 slot，所以就直接添加一个 text 标签，可能官方也考虑到这种需求了？虽然官方提供了一个叫 label-class 的类, 但其实通过这个类设置的 color 属性时不会生效的, 具体原因可以看下面的分析.
![vant-weapp5282解决方案](https://user-images.githubusercontent.com/101820556/224509642-599c9870-ff95-41fc-bdc5-6d2e83217f66.png)

**Comment by fanburger** [comment]
# 问题分析：

我猜你代码截图中的问题其实应该是这样的🤔，你希望使用 style 或者 `.van-radio__label--right` 来进行样式覆盖，下面是关于这两种方式都不可行的原因：

## 关于直接在自定义组件上使用 style 来绑定样式的问题：

这部分问题其实微信小程序开发文档已经提到了，看这个--> [虚拟化组件节点](https://developers.weixin.qq.com/miniprogram/dev/framework/custom-component/wxml-wxss.html#%E8%99%9A%E6%8B%9F%E5%8C%96%E7%BB%84%E4%BB%B6%E8%8A%82%E7%82%B9)
据我对 `radio` 组件源码的观察, 这个组件并没有提供接收和设置 style 值的方式

## 关于使用 `.van-radio__label--right` 来进行样式覆盖的问题:
默认情况下 `.van-radio__label--right` 这个类确实是作用在 label 上的,也确实可以通过这个类去设置一些属性, 但是问题在于你在代码中的 `login.wxss`文件中定义了这个类, 那么这个类的值读取的时候就会先于组件内部的类 , 当这个类选择器与其它类选择器同时作用于一个元素并且属性产生冲突时, css 的规则是使用后读取到的类选择器的属性值. 虽然这个类排在其它类的后面,但是由于它最先被读取出来, 所以它就会被组件中的类覆盖.试试这个-- [多个类被应用的时候指向一个元素](https://developer.mozilla.org/zh-CN/docs/Learn/CSS/Building_blocks/Selectors/Type_Class_and_ID_Selectors#%E5%A4%9A%E4%B8%AA%E7%B1%BB%E8%A2%AB%E5%BA%94%E7%94%A8%E7%9A%84%E6%97%B6%E5%80%99%E6%8C%87%E5%90%91%E4%B8%80%E4%B8%AA%E5%85%83%E7%B4%A0)

关于存在样式隔离依旧可以实现组件内同名的类覆盖的问题请看这里: [组件样式隔离](https://developers.weixin.qq.com/miniprogram/dev/framework/custom-component/wxml-wxss.html#%E7%BB%84%E4%BB%B6%E6%A0%B7%E5%BC%8F%E9%9A%94%E7%A6%BB)

VantComponent 最终是调用 Component 构造器来构造页面的.

大佬们, 如有不妥, 还请指正.

**Comment by fanburger** [comment]
@yisirman

**Comment by fanburger** [comment]
@landluck 这个issues应该可以close了

**Comment by johnsonwong666** [comment]
![image](https://github.com/youzan/vant-weapp/assets/64689255/80ecc255-d521-4c51-9697-7a37cba18875)

<img width="1230" alt="image" src="https://github.com/youzan/vant-weapp/assets/64689255/591e198e-342a-4f66-97b6-65a5e872b242">
label-class 看起来没有问题呀

**Comment by johnsonwong666** [comment]
可以提供一个可以稳定复现的小程序代码片段吗？

**Comment by fanburger** [comment]
> 可以提供一个可以稳定复现的小程序代码片段吗？


平台：windows10 64位
开发者工具版本：1.03.0
https://developers.weixin.qq.com/s/B0zaTfmV7KIf
![image](https://github.com/youzan/vant-weapp/assets/101820556/93cdac62-9ecf-4007-b8e7-854971f0870b)

**Comment by johnsonwong666** [comment]
<img width="524" alt="image" src="https://github.com/youzan/vant-weapp/assets/64689255/a364238b-b4be-44c3-8f7d-94e619f7d46a">
<img width="1010" alt="image" src="https://github.com/youzan/vant-weapp/assets/64689255/eed4e7e6-65c4-42a8-8487-04b588448732">
<img width="1055" alt="image" src="https://github.com/youzan/vant-weapp/assets/64689255/7ee0f95e-c97e-4436-b2b1-9a1f7f96badc">
使用外部样式类添加!important以保证外部样式类的优先级。原因分析的话上面有大佬解释的很好。
