### ISSUE TITLE
[Bug Report] 自己封装了scroll-view实现了上拉加载下拉更新的功能，在里面嵌套了van-tabs，设置了sticky无效。

### ISSUE THREAD

**Issue by xmy1231** [youzan/vant-weapp#5283]
### 重现链接

![image](https://user-images.githubusercontent.com/10206252/224462506-4b588448-6ba7-4e9c-8e93-91fbbec45529.png)
![image](https://user-images.githubusercontent.com/10206252/224462511-b07a3538-8ff4-461d-8e19-fd250e4e1dc6.png)

### Vant Weapp 版本

1.0.14

### 描述一下你遇到的问题。

 自己封装了scroll-view实现了上拉加载下拉更新的功能，在里面嵌套了van-tabs，设置了sticky无效。

### 重现步骤

1.整个页面滑动，当滑动到tabs时，sticky固定不了。

**Comment by johnsonwong666** [comment]
样式怎么写的？ 自己写sticky的话 应该要设置一个top值

**Comment by johnsonwong666** [comment]
我试了一下 原生的scrollview里面使用van-tab 开启sticky 发现是可以吸顶的 可以提供一个小程序代码片段吗？

**Comment by johnsonwong666** [comment]
可以参考van-sticky组件在scrollview组件里面的使用。 可能的原因是scroll-view组件开启refresh容器高度变了造成sticky失效

**Comment by johnsonwong666** [comment]
#4760 
#4922

**Comment by johnsonwong666** [comment]
可以提供一个复现代码片段过来吗？

**Comment by jian263994241** [comment]
我也遇到了,  文档提供的代码无效  

```
<scroll-view scroll-y enable-back-to-top refresher-enabled refresher-triggered="{{refresherTriggered}}" bindrefresherrefresh="onPullDownRefresh" bind:scroll="onScroll" style="height: 100vh;">
  <van-sticky scroll-top="{{ scrollTop }}">
    <van-tabs title-active-color="#F04034" line-width="4em" value="{{tabActive}}" bind:change="tabChange">
      <van-tab title="自购订单" name="myOrder"></van-tab>
      <van-tab title="售卖订单" name="myGroupOrder"></van-tab>
    </van-tabs>
    <van-search shape="round" model:value="{{searchValue}}" placeholder="团购名" use-action-slot bind:search="search">
      <view slot="action" style="padding: 0 12px;" bind:tap="filter">
        <text style="margin-right:3px;">筛选</text>
        <van-icon name="filter-o" dot="{{hasFilter}}" />
      </view>
    </van-search>
  </van-sticky>
  <view class="container" style="margin-top:15px;">
    <block wx:for="{{listData}}" wx:key="orderId">
      <template is="item" data="{{ data:item }}" />
    </block>
    <empty-block description="暂无订单" wx:if="{{listData.length === 0}}" />
  </view>
</scroll-view>
```


```
onScroll(event: WXEvent) {
    this.setData({
      scrollTop: event.detail.scrollTop
    });
  },
```

**Comment by johnsonwong666** [comment]
该issue 在vant-weapp2.0 解决

**Comment by johnsonwong666** [comment]
补充一点。实测下来，scroll-view 里面开启下拉刷新  里面的元素的postion会无效 不管是fixed/还是sticky 这可能是官方的一个bug，社区也有讨论，如有这种场景尝试页面级别的下拉刷新。
<img width="1243" alt="image" src="https://github.com/youzan/vant-weapp/assets/64689255/64e8ebef-c21f-4e69-adb0-b7e7ccb4b28c">

**Comment by scancode911** [comment]
这样写试试  scroll-view里面再嵌套一层view
`<scroll-view>
  <view>
    //内容
  <view>
</scroll-view>`
