### ISSUE TITLE
使用 css ':active' 伪类来实现点击态，很容易触发，并且滚动或滑动时点击态不会消失，体验较差。建议使用小程序内置组件的 'hover-*' 属性来实现

### ISSUE THREAD

**Issue by king22222222** [youzan/vant-weapp#5285]
### 重现链接

小程序评分时报出来的问题，在很多组件都有用到active伪类

### Vant Weapp 版本

1.10.8

### 描述一下你遇到的问题。

使用 css ':active' 伪类来实现点击态，很容易触发，并且滚动或滑动时点击态不会消失，体验较差。建议使用小程序内置组件的 'hover-*' 属性来实现

### 重现步骤

小程序评分时报出来的问题，在很多组件都有用到active伪类

**Comment by johnsonwong666** [comment]
可以提供一段小程序代码片段或者录屏吗？目前体验上感觉还好

**Comment by johnsonwong666** [comment]
由于较长时间没有提供复现代码片段，此issue暂时关闭，若还有问题请提新的issue,并附带复现代码片段排查。
