### ISSUE TITLE
[Bug Report] 日历组件Calendar 星期对应

### ISSUE THREAD

**Issue by 18525570094** [youzan/vant-weapp#5286]
### 重现链接

<van-calendar class='self-cycle-calendar choose-pop' show="{{ showChooseSelfCycle }}" round="{{true}}" title="选择配送周期" type="range" max-range='{{maxCycleDay}}' min-date='{{minStartDate}}'
              default-date='{{defaultDate}}' max-date='{{maxStartDate}}' allow-same-day
              formatter="{{selfCycleFormatter}}" confirm-disabled-text="{{calendarDisabledText}}" bind:close="closeChooseSelfCycle" bind:select='onSelectDate' bind:confirm="onChooseSelfCycle" data-type="showChooseSelfCycle">
</van-calendar>

### Vant Weapp 版本

1.9.0

### 描述一下你遇到的问题。

星期对应不上，2023-03-11是星期六，
![e2d93bdcec240483d25072a2b35cd9a](https://user-images.githubusercontent.com/53560456/224597109-5445461b-5a1c-43e7-8b7e-85b53ef403ba.jpg)
![img_v2_f1f43ca6-5e94-4a84-b8dc-e6cfe519d55g](https://user-images.githubusercontent.com/53560456/224871772-2a7ad5a4-dc65-4e59-b131-6687dbbd95d9.jpg)

### 重现步骤

使用Calendar 日历组件

### 设备/浏览器

小程序

**Comment by johnsonwong666** [comment]
升级一下版本试试

**Comment by johnsonwong666** [comment]
升级一下版本试试 目前最新版本看是正常的 1.9.0版本3月11号也是星期六 可以提供一段小程序片段来看看

**Comment by johnsonwong666** [comment]
没有复现。由于较长时间没有提供复现代码片段，此issue关闭，若还有问题请提新的issue,并附带复现代码片段排查。
