### ISSUE TITLE
[Feature Request] share-sheet分享按钮绑定数据

### ISSUE THREAD

**Issue by jian263994241** [youzan/vant-weapp#5289]
### 这个功能解决了什么问题？

openType: 'share',  通过dataset 传递分享自定义配置

### 你期望的 API 是什么样子的？

```
{ name: '微信', icon: 'wechat', openType: 'share', dataset: { title: 'webxxx', path: '/aaax/xx', imageUrl: '/png/aaa.png' } },
```

**Comment by landluck** [comment]
微信分享功能是通过 Page 生命周期 onShareAppMessage 进行配置的，按钮无法实现该功能，具体配置方式参考 [onShareAppMessage](https://developers.weixin.qq.com/miniprogram/dev/reference/api/Page.html#onShareAppMessage-Object-object)

**Comment by jian263994241** [comment]
> 微信分享功能是通过 Page 生命周期 onShareAppMessage 进行配置的，按钮无法实现该功能，具体配置方式参考 [onShareAppMessage](https://developers.weixin.qq.com/miniprogram/dev/reference/api/Page.html#onShareAppMessage-Object-object)

当一个长列表页面, 里面有非常多的分享按钮 就很麻烦了, 每一项都可以分出去一个入口 . onShareAppMessage 会透传 event.target  需要从这里拿信息
