### ISSUE TITLE
递归树形选择组件

### ISSUE THREAD

**Issue by jbddmk** [youzan/vant-weapp#5293]
### 这个功能解决了什么问题？

类似于多级目录树，可通过传参实现单选、多选
[![Uploading [image.png…]()](ur
](https://element.eleme.cn/#/zh-CN/component/tree)

### 你期望的 API 是什么样子的？

<vant-tree ></vant-tree>

**Comment by landluck** [comment]
移动端中可以通过 https://youzan.github.io/vant-weapp/#/tree-select 来实现同样的功能，暂时不回增加类似B端的 tree 组件
