### ISSUE TITLE
评分组件在微信小程序中的显示问题

### ISSUE THREAD

**Issue by Github-666666** [youzan/vant-weapp#5294]
### 重现链接
// index.js
Page({
    data: {
        value: 2.5,
    },
    onChange(event) {
        this.setData({
            value: event.detail,
        });
    },
});

<view>
    <van-rate
            value="{{ value }}"
            allow-half
            void-icon="star"
            void-color="#C5C0C0"
            bind:change="onChange"
    ></van-rate>
</view>

### Vant Weapp 版本

1.10.14

### 描述一下你遇到的问题。

![image](https://user-images.githubusercontent.com/58134757/226781032-7e9dc89b-8a45-48cf-ab47-c65efc226288.png)
使用标准模板，评分组件在微信小程序中满星时没问题，半星时星星的左下角缺失，没有被红色覆盖全

### 重现步骤

无

### 设备/浏览器

鸿蒙，安卓

**Comment by landluck** [comment]
`v1.10.15` 已解决
