### ISSUE TITLE
[Bug 小程序] Stepper在进行最大值设置出现问题

### ISSUE THREAD

**Issue by Supers1st** [youzan/vant-weapp#5295]
### 重现链接

<van-stepper data-name='onOffTime' decimal-length="{{ 1 }}" max="10"  min="0" step="0.5" disable-input="true" input-width="80rpx" button-size="100rpx" value="{{ onOffTime}}" bind:change="onChangeStepper" />
		

### Vant Weapp 版本

1.10.3

### 描述一下你遇到的问题。

在进行最大值设置max="10"这种方式，会将最大值设置为十进制的2，只有这样`max="{{10}}"`才能正确设置最大值。

### 重现步骤

代码如下：
1. 使用步进器
2. 设置最大值`max="10"`

### 设备/浏览器

微信开发者工具

**Comment by Supers1st** [comment]
max="{{10}}"才能正确设置

**Comment by johnsonwong666** [comment]
没有复现。可以提供一下小程序片段吗

**Comment by Supers1st** [comment]
如下：
```javascript
<van-col span='10'>
<van-stepper data-name='onOffTime' decimal-length="{{ 1 }}" max="10" min="0" step="0.5" disable-input="true" input-width="80rpx" button-size="100rpx" value="{{ onOffTime }}" bind:change="onChangeStepper" />
</van-col>
```

**Comment by Supers1st** [comment]
> 没有复现。可以提供一下小程序片段吗

```javascript
<van-col span='10'>
<van-stepper data-name='onOffTime' decimal-length="{{ 1 }}" max="10" min="0" step="0.5" disable-input="true" input-width="80rpx" button-size="100rpx" value="{{ onOffTime }}" bind:change="onChangeStepper" />
</van-col>
```

**Comment by landluck** [comment]
`V1.10.16` 版本已修复
