### ISSUE TITLE
filed 输入框点第一个聚焦，第二个不聚焦，第三个又聚焦

### ISSUE THREAD

**Issue by xiarifqy** [youzan/vant-weapp#5297]
### 重现链接

<van-field
  label="品牌"
  model:value="{{ brand }}"
  placeholder="点击填写品牌"
/>
<van-field
  label="型号"
  model:value="{{ type}}"
  placeholder="点击填写型号"
/>

### Vant Weapp 版本

1.6.8

### 描述一下你遇到的问题。

filed 输入框点第一个聚焦，第二个不聚焦，第三个又聚焦

### 重现步骤

filed 输入框点第一个聚焦，第二个不聚焦，第三个又聚焦

**Comment by zc1003** [comment]
问题解决了嘛

**Comment by docikaci** [comment]
遇到同样的问题，输入框filed，输入第二个，不会弹出键盘，在点一次，才能弹出键盘

**Comment by docikaci** [comment]
![image](https://user-images.githubusercontent.com/7788102/229453206-44e29f8f-12b2-4e72-903e-7bf9d72cb302.png)
可以扫官方的小程序，也是同样的问题：输入框filed，输入第二个，不会弹出键盘，在点一次，才能弹出键盘

**Comment by fanburger** [comment]
这个问题不是`vant-weapp`组件库的问题，微信小程序原生的`input`组件在切换不同类型的键盘的时候就会出现这个问题, 不切换键盘类型就不会触发这个问题, 以下是代码片段链接, 可在微信开发者工具中打开, 使用手机预览验证: [原生input组件问题复现](https://developers.weixin.qq.com/s/gWTQxfma7AH7) 
![image](https://user-images.githubusercontent.com/101820556/230149226-e3e66220-509c-4ed1-9a8b-e18eddad5e4b.png)

**Comment by johnsonwong666** [comment]
微信官方社区，原生input有类似的issue，可以参考一下，此issue暂时关闭。
https://developers.weixin.qq.com/community/develop/doc/00008683d50568590f7e1da9f56800?highLine=%25E8%2581%259A%25E7%2584%25A6
https://developers.weixin.qq.com/community/develop/issue/316
