### ISSUE TITLE
Popup组件中多个Field组件在获取焦点的时候input的值和placeholder在ios设备上会抖动，并且在ios和android上都伴有延迟

### ISSUE THREAD

**Issue by A1nto** [youzan/vant-weapp#5299]
### 重现链接

<van-popup show="{{ invoicePopup }}" closeable position="bottom" bind:close="handleInvoiceClose" lock-scroll catchtouchmove="touchMove">
<van-field class="custom-filed" value="{{ invoiceData.invoiceTitle }}"
                            label="单位名称：" required type="text" clearable
                            maxlength="14" title-width="140rpx" placeholder="请填写单位名称"
                            border="{{ false }}" data-field="invoiceTitle" bind:input="handleChangeInvoiceValue"
                        />
                        <van-field class="custom-filed" value="{{ invoiceData.invoiceNumber }}"
                            label="纳税人识别号：" required type="number" clearable
                            maxlength="20" title-width="200rpx" placeholder="请填写纳税人识别号"
                            placeholder-style="color: #ee0a24;"
                            border="{{ false }}" data-field="invoiceNumber" bind:input="handleChangeInvoiceValue"
                        />
                        <van-field class="custom-filed" value="{{ invoiceData.bankAddress }}"
                            label="单位地址：" type="text" clearable
                            maxlength="50" title-width="140rpx" placeholder="请填写单位地址"
                            border="{{ false }}" data-field="bankAddress" bind:input="handleChangeInvoiceValue"
                        />
</van-popup>

### Vant Weapp 版本

1.6.8

### 描述一下你遇到的问题。

打开弹窗，获取input焦点时，值或者placeholder会抖动一下，在ios设备上特别明显，在安卓设备上切换input框时有接近800ms的延迟

### 重现步骤

获取焦点

### 设备/浏览器

ios真机

**Comment by A1nto** [comment]
https://resource.guoyuejiu.com/get/video/20230327/DmsDev_1_20230327175952413959.mp4

**Comment by johnsonwong666** [comment]
可以提供一个小程序代码片段过来吗？

**Comment by johnsonwong666** [comment]
还在嘛？更新一下vant-weapp版本试试和基础库版本
