### ISSUE TITLE
search组件 返回的detail 为空

### ISSUE THREAD

**Issue by 15669028801** [youzan/vant-weapp#530]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**描述一下问题**
search组件 返回的detail 为空。
组件的问题，和编译无关
**截图**
如果是 UI 问题，请提供具体截图

**环境**
 - 设备: 
 - 基础库版本: 2.2.5 [165]
 - Vant Weapp 版本: "^0.2.1"

**Comment by 15669028801** [comment]
好像是因为 组件之间不能共享的value，导致的null

**Comment by chenjiahan** [comment]
没复现这个问题，能否提供下复现代码

**Comment by 15669028801** [comment]
着我的代码的引用：

![image](https://user-images.githubusercontent.com/35586321/45746191-3b5c6680-bc35-11e8-96a9-209cfc84fc6a.png)

这是vant-search组件：
![image](https://user-images.githubusercontent.com/35586321/45746379-b7ef4500-bc35-11e8-87dd-018f860aa578.png)

我直接在vant-search打印出来也是undefind，所以出现了onSearch返回值为空
