### ISSUE TITLE
IOS上使用异常。Popup组件内嵌scroll-view时，并展示其他类似的结构的Popup时，显示错位，无法正常使用

### ISSUE THREAD

**Issue by worldsoon** [youzan/vant-weapp#5302]
### 重现链接

https://developers.weixin.qq.com/s/Mxgj53my7EHT

### Vant Weapp 版本

1.10.14

### 描述一下你遇到的问题。

popup A 包含 元素scroll-view

popup B 包含 元素scroll-view

当popup A 和 popup B 同事出现时会导致两个popup内容重叠显示，点击事件穿透现象

### 重现步骤

如代码片段，
1、先点击【展示弹出窗】
2、点击popup弹窗内的【添加】按钮，会弹出另外一个popup
3、发现两个popup内容重叠

### 设备/浏览器

IOS

**Comment by landluck** [comment]
可以通过 popup 配置 `root-portal ` 参数试试
