### ISSUE TITLE
[Bug Report] van-icon控件加入默认classPrefix判断有问题

### ISSUE THREAD

**Issue by brainsky** [youzan/vant-weapp#5303]
### 重现链接

该文件https://github.com/youzan/vant-weapp/blob/dev/lib/icon/index.wxs 16行判断：
`if (data.classPrefix !== 'van-icon') {
    classes.push('van-icon')
  }
`
这样造成索引不到自定义的icon图标。比如我引入自定义icon字体的classPrefix: eva , 然后我使用eva中的图标：eva-home-outline。
我用icon控件，classPrefix="eva" name="eva-home-outline"。实际上wxml中的view class ="custom-class eva van-icon eva-home-outline" 是这样的，导致索引不到自定义的icon图标。所以想知道这段代码是为什么这样判断？如果使用自定义的classPrefix为什么还需要push默认的van-icon进来呢?是不是应该判断classPrefix 为空或者没有值的时候才使用默认的van-icon更好一些呢？

### Vant Weapp 版本

1.10.14

### 描述一下你遇到的问题。

我再使用icon控件时候索引不到自定义的图标

### 重现步骤

可以随便引用外部的图标就能复现，应该是显示不了的。

**Comment by landluck** [comment]
`V1.10.16` 版本已修复
