### ISSUE TITLE
tabbar设置透明之后 怎么取消上边框

### ISSUE THREAD

**Issue by zhuhe123456** [youzan/vant-weapp#5304]
### 重现链接

<van-tabbar active="{{ selected }}" active-color="{{selectedColor}}" inactive-color="{{color}}"  border="false" style="--tabbar-background-color:{{background}};">

### Vant Weapp 版本

^1.10.14

### 描述一下你遇到的问题。

tabbar设置透明之后 上边框无法隐藏

### 重现步骤

![image](https://user-images.githubusercontent.com/7161977/228460813-7612e581-11ef-4440-acab-72499706ad9b.png)

**Comment by CrazyCatZhang** [comment]
<van-tabbar border="{{false}}"> </van-tabbar>

**Comment by CassandraCat** [comment]
```html
<van-tabbar border="{{false}}"></van-tabbar>

**Comment by zhuhe123456** [comment]
> 

多谢

**Comment by zhuhe123456** [comment]
> ```
> <van-tabbar border="{{false}}"></van-tabbar>
> ```

多谢
