### ISSUE TITLE
[Bug Report]  在uniapp中使用 DropdownMenu后页面无法滚动问题及解决

### ISSUE THREAD

**Issue by z759341385** [youzan/vant-weapp#5305]
### 重现链接

无

### Vant Weapp 版本

1.10.5

### 描述一下你遇到的问题。

在uniapp中使用DropdownMenu在激活弹出层后scroll-view组件无法滚动

resolve:  https://blog.csdn.net/weixin_46324536/article/details/128236805

### 重现步骤

在使用scroll-view 组件的页面 激活DropdownMenu弹出层

**Comment by johnsonwong666** [comment]
可能是uinapp编译后产生的问题，这个issue可以提到uniapp官方去，目前不会处理在其他平台上产生的问题。

**Comment by yhsx29** [comment]
版本：1.11.6
在 \dropdown-item\index.js 的onClose方法内添加一行代码 `this.setData({ showWrapper: false });`即可。
![微信截图_20240823110604](https://github.com/user-attachments/assets/dd8f6540-b003-4423-ab70-9213528817e6)
