### ISSUE TITLE
van-area第一列和第二列的子列表划不动

### ISSUE THREAD

**Issue by cxm-debug** [youzan/vant-weapp#5312]
### 重现链接

<van-area area-list="{{ areaList }}"  title="选择地址"
 columns-num="{{ 2 }}" bind:confirm="confirmArea"
/>

confirmArea(e) {
    this.setData({
      provinceCode: e.detail.values[0].code,
      cityCode: e.detail.values[1].code,
      areaStr: e.detail.values[0].name + "," + e.detail.values[1].name,
      isArea: false
    })
  },
数据格式：
<img width="731" alt="image" src="https://user-images.githubusercontent.com/59412714/229388938-628f9809-4ec5-4aa5-a143-e5d4242f19c4.png">

### Vant Weapp 版本

1.10.14

### 描述一下你遇到的问题。

当左边为北京和天津的时候滑动右边的列表 松手会自动弹到顶部
<img width="282" alt="image" src="https://user-images.githubusercontent.com/59412714/229388993-5b51e06a-ea8d-4e69-a123-8a335187059b.png">

### 重现步骤

1.选择北京或天津（index为0,1）
2.滑动选择左边的子列表

### 设备/浏览器

ios,android,微信开发者工具模拟器for mac

**Comment by johnsonwong666** [comment]
数据格式错了 city_list 应该是 county_list 才对 详见[@vant/area-data](https://github.com/vant-ui/vant/tree/dev/packages/vant-area-data) 的数据格式定义
