### ISSUE TITLE
DropdownMenu 下拉菜单组件切换列表无法重新渲染

### ISSUE THREAD

**Issue by KanekikehT** [youzan/vant-weapp#5314]
### 重现链接

const app = getApp()
Page({
  data: {
    // 定义三个方向的数据
    gudai: [{
        text: '第一章 天地与人论',
        value: 1,
        icon:'',
        lesson: [{
          text: '第一讲 《七月》与大地',
          img: 'http://rrt2s7opw.hn-bkt.clouddn.com/hanyuyan/%E5%8F%A4%E4%BB%A3%E6%96%87%E5%AD%A6%E5%8F%B2/picture/%E3%80%8A%E8%AF%97%E7%BB%8F%E3%80%8B.png'
        }, {
          text: '第二讲 《东山》与归家的渴望',
          img: 'http://rrt2s7opw.hn-bkt.clouddn.com/hanyuyan/%E5%8F%A4%E4%BB%A3%E6%96%87%E5%AD%A6%E5%8F%B2/picture/%E3%80%8A%E8%AF%97%E7%BB%8F%E3%80%8B.png'
        }, {
          text: '第三讲 《鹿鸣》与美政理想',
          img: 'http://rrt2s7opw.hn-bkt.clouddn.com/hanyuyan/%E5%8F%A4%E4%BB%A3%E6%96%87%E5%AD%A6%E5%8F%B2/picture/%E3%80%8A%E8%AF%97%E7%BB%8F%E3%80%8B.png'
        }, {
          text: '第四讲 《棠棣》与宗法观念',
          img: 'http://rrt2s7opw.hn-bkt.clouddn.com/hanyuyan/%E5%8F%A4%E4%BB%A3%E6%96%87%E5%AD%A6%E5%8F%B2/picture/%E3%80%8A%E8%AF%97%E7%BB%8F%E3%80%8B.png'
        }]
      },
      {
        text: '第二章 《论语》与当代人生',
        value: 2,
        icon:'',
        lesson: [{
          text: '第一讲 我们身边的孔子和《论语》',
          img: 'http://rrt2s7opw.hn-bkt.clouddn.com/hanyuyan/%E5%8F%A4%E4%BB%A3%E6%96%87%E5%AD%A6%E5%8F%B2/picture/%E3%80%8A%E8%AE%BA%E8%AF%AD%E3%80%8B%E4%B8%8E%E5%BD%93%E4%BB%A3%E4%BA%BA%E7%94%9F.png'
        }, {
          text: '第二讲 《论语》的作者及成书',
          img: 'http://rrt2s7opw.hn-bkt.clouddn.com/hanyuyan/%E5%8F%A4%E4%BB%A3%E6%96%87%E5%AD%A6%E5%8F%B2/picture/%E3%80%8A%E8%AE%BA%E8%AF%AD%E3%80%8B%E4%B8%8E%E5%BD%93%E4%BB%A3%E4%BA%BA%E7%94%9F.png'
        }, {
          text: '第三讲 孔子的理想人格',
          img: 'http://rrt2s7opw.hn-bkt.clouddn.com/hanyuyan/%E5%8F%A4%E4%BB%A3%E6%96%87%E5%AD%A6%E5%8F%B2/picture/%E3%80%8A%E8%AE%BA%E8%AF%AD%E3%80%8B%E4%B8%8E%E5%BD%93%E4%BB%A3%E4%BA%BA%E7%94%9F.png'
        }, {
          text: '第四讲 孔子思想的继承——孟子',
          img: 'http://rrt2s7opw.hn-bkt.clouddn.com/hanyuyan/%E5%8F%A4%E4%BB%A3%E6%96%87%E5%AD%A6%E5%8F%B2/picture/%E3%80%8A%E8%AE%BA%E8%AF%AD%E3%80%8B%E4%B8%8E%E5%BD%93%E4%BB%A3%E4%BA%BA%E7%94%9F.png'
        }]
      },
      {
        text: '第三章 《史记》',
        value: 3,
        icon:'',
        lesson: [{
          text: '第一讲 司马迁的家世与作《史记》的经过',
          img: 'http://rrt2s7opw.hn-bkt.clouddn.com/hanyuyan/%E5%8F%A4%E4%BB%A3%E6%96%87%E5%AD%A6%E5%8F%B2/picture/%E3%80%8A%E5%8F%B2%E8%AE%B0%E3%80%8B.png'
        }, {
          text: '第二讲 司马迁作《史记》的志意与体例',
          img: 'http://rrt2s7opw.hn-bkt.clouddn.com/hanyuyan/%E5%8F%A4%E4%BB%A3%E6%96%87%E5%AD%A6%E5%8F%B2/picture/%E3%80%8A%E5%8F%B2%E8%AE%B0%E3%80%8B.png'
        }, {
          text: '第三讲 《史记》篇章解读举隅——以《留侯世家》（节选）为例',
          img: 'http://rrt2s7opw.hn-bkt.clouddn.com/hanyuyan/%E5%8F%A4%E4%BB%A3%E6%96%87%E5%AD%A6%E5%8F%B2/picture/%E3%80%8A%E5%8F%B2%E8%AE%B0%E3%80%8B.png'
        }, {
          text: '第四讲 《史记》篇章解读举隅——以《秦始皇本纪》（节选）为例',
          img: 'http://rrt2s7opw.hn-bkt.clouddn.com/hanyuyan/%E5%8F%A4%E4%BB%A3%E6%96%87%E5%AD%A6%E5%8F%B2/picture/%E3%80%8A%E5%8F%B2%E8%AE%B0%E3%80%8B.png'
        }]
      },
      {
        text: '第四章 汉魏六朝诗与魏晋风流',
        value: 4,
        icon:'',
        lesson: [{
          text: '第一讲 汉魏六朝诗的进路',
          img: 'http://rrt2s7opw.hn-bkt.clouddn.com/hanyuyan/%E5%8F%A4%E4%BB%A3%E6%96%87%E5%AD%A6%E5%8F%B2/picture/%E6%B1%89%E9%AD%8F%E5%85%AD%E6%9C%9D%E8%AF%97%E4%B8%8E%E9%AD%8F%E6%99%8B%E9%A3%8E%E6%B5%81.png'
        }, {
          text: '第二讲 建安之杰曹植',
          img: 'http://rrt2s7opw.hn-bkt.clouddn.com/hanyuyan/%E5%8F%A4%E4%BB%A3%E6%96%87%E5%AD%A6%E5%8F%B2/picture/%E6%B1%89%E9%AD%8F%E5%85%AD%E6%9C%9D%E8%AF%97%E4%B8%8E%E9%AD%8F%E6%99%8B%E9%A3%8E%E6%B5%81.png'
        }, {
          text: '第三讲 曹植诗歌内容',
          img: 'http://rrt2s7opw.hn-bkt.clouddn.com/hanyuyan/%E5%8F%A4%E4%BB%A3%E6%96%87%E5%AD%A6%E5%8F%B2/picture/%E6%B1%89%E9%AD%8F%E5%85%AD%E6%9C%9D%E8%AF%97%E4%B8%8E%E9%AD%8F%E6%99%8B%E9%A3%8E%E6%B5%81.png'
        }, {
          text: '第四讲 六朝代表诗人',
          img: 'http://rrt2s7opw.hn-bkt.clouddn.com/hanyuyan/%E5%8F%A4%E4%BB%A3%E6%96%87%E5%AD%A6%E5%8F%B2/picture/%E6%B1%89%E9%AD%8F%E5%85%AD%E6%9C%9D%E8%AF%97%E4%B8%8E%E9%AD%8F%E6%99%8B%E9%A3%8E%E6%B5%81.png'
        }]
      },
      {
        text: '第五章 唐诗与唐诗中的唐代社会生活',
        value: 5,
        icon:'',
        lesson: [{
          text: '第一讲 唐诗中的隐逸与佛教——以王维为例',
          img: 'http://rrt2s7opw.hn-bkt.clouddn.com/hanyuyan/%E5%8F%A4%E4%BB%A3%E6%96%87%E5%AD%A6%E5%8F%B2/picture/%E5%94%90%E8%A9%A9%E4%B8%8E%E5%94%90%E8%AF%97%E4%B8%AD%E7%9A%84%E5%94%90%E4%BB%A3%E7%A4%BE%E4%BC%9A%E7%94%9F%E6%B4%BB.png'
        }, {
          text: '第二讲 唐诗中的仕宦心态——以杜甫为例',
          img: 'http://rrt2s7opw.hn-bkt.clouddn.com/hanyuyan/%E5%8F%A4%E4%BB%A3%E6%96%87%E5%AD%A6%E5%8F%B2/picture/%E5%94%90%E8%A9%A9%E4%B8%8E%E5%94%90%E8%AF%97%E4%B8%AD%E7%9A%84%E5%94%90%E4%BB%A3%E7%A4%BE%E4%BC%9A%E7%94%9F%E6%B4%BB.png'
        }, {
          text: '第三讲 唐诗中的爱情书写——以李白《清平调》为例',
          img: 'http://rrt2s7opw.hn-bkt.clouddn.com/hanyuyan/%E5%8F%A4%E4%BB%A3%E6%96%87%E5%AD%A6%E5%8F%B2/picture/%E5%94%90%E8%A9%A9%E4%B8%8E%E5%94%90%E8%AF%97%E4%B8%AD%E7%9A%84%E5%94%90%E4%BB%A3%E7%A4%BE%E4%BC%9A%E7%94%9F%E6%B4%BB.png'
        }, {
          text: '第四讲 唐诗中的围棋天地',
          img: 'http://rrt2s7opw.hn-bkt.clouddn.com/hanyuyan/%E5%8F%A4%E4%BB%A3%E6%96%87%E5%AD%A6%E5%8F%B2/picture/%E5%94%90%E8%A9%A9%E4%B8%8E%E5%94%90%E8%AF%97%E4%B8%AD%E7%9A%84%E5%94%90%E4%BB%A3%E7%A4%BE%E4%BC%9A%E7%94%9F%E6%B4%BB.png'
        }]
      },
      {
        text: '第六章 宋词',
        value: 6,
        icon:'',
        lesson: [{
          text: '第一讲 宋词与市民文化',
          img: 'http://rrt2s7opw.hn-bkt.clouddn.com/hanyuyan/%E5%8F%A4%E4%BB%A3%E6%96%87%E5%AD%A6%E5%8F%B2/picture/%E5%AE%8B%E8%AF%8D.png'
        }, {
          text: '第二讲 柳永',
          img: 'http://rrt2s7opw.hn-bkt.clouddn.com/hanyuyan/%E5%8F%A4%E4%BB%A3%E6%96%87%E5%AD%A6%E5%8F%B2/picture/%E5%AE%8B%E8%AF%8D.png'
        }, {
          text: '第三讲 苏轼',
          img: 'http://rrt2s7opw.hn-bkt.clouddn.com/hanyuyan/%E5%8F%A4%E4%BB%A3%E6%96%87%E5%AD%A6%E5%8F%B2/picture/%E5%AE%8B%E8%AF%8D.png'
        }, {
          text: '第四讲 宋词与我们不曾远离',
          img: 'http://rrt2s7opw.hn-bkt.clouddn.com/hanyuyan/%E5%8F%A4%E4%BB%A3%E6%96%87%E5%AD%A6%E5%8F%B2/picture/%E5%AE%8B%E8%AF%8D.png'
        }]
      },
      {
        text: '第七章 中国古代戏曲与元曲',
        value: 7,
        icon:'',
        lesson: [{
          text: '第一讲 中国古代文人与戏曲',
          img: 'http://rrt2s7opw.hn-bkt.clouddn.com/hanyuyan/%E5%8F%A4%E4%BB%A3%E6%96%87%E5%AD%A6%E5%8F%B2/picture/%E5%8F%A4%E4%BB%A3%E6%88%8F%E6%9B%B2%E4%B8%8E%E5%85%83%E6%9B%B2.png'
        }, {
          text: '第二讲 关汉卿与《窦娥冤》',
          img: 'http://rrt2s7opw.hn-bkt.clouddn.com/hanyuyan/%E5%8F%A4%E4%BB%A3%E6%96%87%E5%AD%A6%E5%8F%B2/picture/%E5%8F%A4%E4%BB%A3%E6%88%8F%E6%9B%B2%E4%B8%8E%E5%85%83%E6%9B%B2.png'
        }, {
          text: '第三讲 王实甫与《西厢记》',
          img: 'http://rrt2s7opw.hn-bkt.clouddn.com/hanyuyan/%E5%8F%A4%E4%BB%A3%E6%96%87%E5%AD%A6%E5%8F%B2/picture/%E5%8F%A4%E4%BB%A3%E6%88%8F%E6%9B%B2%E4%B8%8E%E5%85%83%E6%9B%B2.png'
        }, {
          text: '第四讲 将古代戏曲带进现代生活',
          img: 'http://rrt2s7opw.hn-bkt.clouddn.com/hanyuyan/%E5%8F%A4%E4%BB%A3%E6%96%87%E5%AD%A6%E5%8F%B2/picture/%E5%8F%A4%E4%BB%A3%E6%88%8F%E6%9B%B2%E4%B8%8E%E5%85%83%E6%9B%B2.png'
        }]
      },
      {
        text: '第八章 中国古典小说',
        value: 8,
        icon:'',
        lesson: [{
          text: '第一讲 中国古典小说名义与精神',
          img: 'http://rrt2s7opw.hn-bkt.clouddn.com/hanyuyan/%E5%8F%A4%E4%BB%A3%E6%96%87%E5%AD%A6%E5%8F%B2/picture/%E4%B8%AD%E5%9B%BD%E5%8F%A4%E4%BB%A3%E5%B0%8F%E8%AF%B4.png'
        }, {
          text: '第二讲 魏晋南北朝与唐代小说',
          img: 'http://rrt2s7opw.hn-bkt.clouddn.com/hanyuyan/%E5%8F%A4%E4%BB%A3%E6%96%87%E5%AD%A6%E5%8F%B2/picture/%E4%B8%AD%E5%9B%BD%E5%8F%A4%E4%BB%A3%E5%B0%8F%E8%AF%B4.png'
        }, {
          text: '第三讲 宋元小说',
          img: 'http://rrt2s7opw.hn-bkt.clouddn.com/hanyuyan/%E5%8F%A4%E4%BB%A3%E6%96%87%E5%AD%A6%E5%8F%B2/picture/%E4%B8%AD%E5%9B%BD%E5%8F%A4%E4%BB%A3%E5%B0%8F%E8%AF%B4.png'
        }, {
          text: '第四讲 由六朝小说至唐代传奇的改写——以《杨林》、《枕中记》比较为例',
          img: 'http://rrt2s7opw.hn-bkt.clouddn.com/hanyuyan/%E5%8F%A4%E4%BB%A3%E6%96%87%E5%AD%A6%E5%8F%B2/picture/%E4%B8%AD%E5%9B%BD%E5%8F%A4%E4%BB%A3%E5%B0%8F%E8%AF%B4.png'
        }]
      },
      {
        text: '第九章 《三国演义》的现代价值',
        value: 9,
        icon:'',
        lesson: [{
          text: '第一讲 《三国演义》的现代价值(上)',
          img: 'http://rrt2s7opw.hn-bkt.clouddn.com/hanyuyan/%E5%8F%A4%E4%BB%A3%E6%96%87%E5%AD%A6%E5%8F%B2/picture/%E3%80%8A%E4%B8%89%E5%9B%BD%E6%BC%94%E4%B9%89%E3%80%8B%E7%9A%84%E7%8E%B0%E4%BB%A3%E4%BB%B7%E5%80%BC.png'
        }, {
          text: '第二讲 《三国演义》的现代价值(下)',
          img: 'http://rrt2s7opw.hn-bkt.clouddn.com/hanyuyan/%E5%8F%A4%E4%BB%A3%E6%96%87%E5%AD%A6%E5%8F%B2/picture/%E3%80%8A%E4%B8%89%E5%9B%BD%E6%BC%94%E4%B9%89%E3%80%8B%E7%9A%84%E7%8E%B0%E4%BB%A3%E4%BB%B7%E5%80%BC.png'
        }]
      },
      {
        text: '第十章 中国诗歌传统与现代诗化小说',
        value: 10,
        icon:'',
        lesson: [{
          text: '第一讲 现代诗化小说与中国诗歌抒情传统的高度契合',
          img: 'http://rrt2s7opw.hn-bkt.clouddn.com/hanyuyan/%E5%8F%A4%E4%BB%A3%E6%96%87%E5%AD%A6%E5%8F%B2/picture/%E4%B8%AD%E5%9B%BD%E6%8A%92%E6%83%85%E8%AF%97%E6%AD%8C%E4%BC%A0%E7%BB%9F%E4%B8%8E%E7%8E%B0%E4%BB%A3%E8%AF%97%E5%8C%96%E5%B0%8F%E8%AF%B4.png'
        }, {
          text: '第二讲 现代诗化小说对传统抒情诗的形式借鉴',
          img: 'http://rrt2s7opw.hn-bkt.clouddn.com/hanyuyan/%E5%8F%A4%E4%BB%A3%E6%96%87%E5%AD%A6%E5%8F%B2/picture/%E4%B8%AD%E5%9B%BD%E6%8A%92%E6%83%85%E8%AF%97%E6%AD%8C%E4%BC%A0%E7%BB%9F%E4%B8%8E%E7%8E%B0%E4%BB%A3%E8%AF%97%E5%8C%96%E5%B0%8F%E8%AF%B4.png'
        }]
      },
      {
        text: '第十一章 明代广东翰林群体及其文学研究',
        value: 11,
        icon:'',
        lesson: [{
          text: '第一讲 明代广东学子的翰林之路',
          img: 'http://rrt2s7opw.hn-bkt.clouddn.com/hanyuyan/%E5%8F%A4%E4%BB%A3%E6%96%87%E5%AD%A6%E5%8F%B2/picture/%E6%98%8E%E4%BB%A3%E5%B9%BF%E4%B8%9C%E7%BF%B0%E6%9E%97%E7%BE%A4%E4%BD%93%E5%8F%8A%E5%85%B6%E6%96%87%E5%AD%A6%E7%A0%94%E7%A9%B6.png'
        }, {
          text: '第二讲 明代广东翰林的地域推尊意识',
          img: 'http://rrt2s7opw.hn-bkt.clouddn.com/hanyuyan/%E5%8F%A4%E4%BB%A3%E6%96%87%E5%AD%A6%E5%8F%B2/picture/%E6%98%8E%E4%BB%A3%E5%B9%BF%E4%B8%9C%E7%BF%B0%E6%9E%97%E7%BE%A4%E4%BD%93%E5%8F%8A%E5%85%B6%E6%96%87%E5%AD%A6%E7%A0%94%E7%A9%B6.png'
        }, {
          text: '第三讲 明代广东翰林的诗歌创作',
          img: 'http://rrt2s7opw.hn-bkt.clouddn.com/hanyuyan/%E5%8F%A4%E4%BB%A3%E6%96%87%E5%AD%A6%E5%8F%B2/picture/%E6%98%8E%E4%BB%A3%E5%B9%BF%E4%B8%9C%E7%BF%B0%E6%9E%97%E7%BE%A4%E4%BD%93%E5%8F%8A%E5%85%B6%E6%96%87%E5%AD%A6%E7%A0%94%E7%A9%B6.png'
        }]
      },
      {
        text: '第十二章 木鱼歌与广东民间说唱文学',
        value: 12,
        icon:'',
        lesson: [{
          text: '第一讲 广东民间说唱',
          img: 'http://rrt2s7opw.hn-bkt.clouddn.com/hanyuyan/%E5%8F%A4%E4%BB%A3%E6%96%87%E5%AD%A6%E5%8F%B2/picture/%E6%9C%A8%E9%B1%BC%E6%AD%8C%E5%92%8C%E7%B2%A4%E8%B0%83%E6%B0%91%E9%97%B4%E8%AF%B4%E5%94%B1.png'
        }, {
          text: '第二讲 木鱼歌',
          img: 'http://rrt2s7opw.hn-bkt.clouddn.com/hanyuyan/%E5%8F%A4%E4%BB%A3%E6%96%87%E5%AD%A6%E5%8F%B2/picture/%E6%9C%A8%E9%B1%BC%E6%AD%8C%E5%92%8C%E7%B2%A4%E8%B0%83%E6%B0%91%E9%97%B4%E8%AF%B4%E5%94%B1.png'
        }]
      },
      {
        text: '第十三章 岭南文化的活化与传播',
        value: 13,
        icon:'',
        lesson: [{
          text: '第一讲 岭南文化的内涵与传播',
          img: 'http://rrt2s7opw.hn-bkt.clouddn.com/hanyuyan/%E5%8F%A4%E4%BB%A3%E6%96%87%E5%AD%A6%E5%8F%B2/picture/%E3%80%8A%E5%B2%AD%E5%8D%97%E6%96%87%E5%8C%96%E7%9A%84%E6%B4%BB%E5%8C%96%E4%B8%8E%E4%BC%A0%E6%92%AD%E3%80%8B.png'
        }, {
          text: '第二讲 岭南文化之粤剧的活化与传播',
          img: 'http://rrt2s7opw.hn-bkt.clouddn.com/hanyuyan/%E5%8F%A4%E4%BB%A3%E6%96%87%E5%AD%A6%E5%8F%B2/picture/%E3%80%8A%E5%B2%AD%E5%8D%97%E6%96%87%E5%8C%96%E7%9A%84%E6%B4%BB%E5%8C%96%E4%B8%8E%E4%BC%A0%E6%92%AD%E3%80%8B.png'
        }, {
          text: '第三讲 岭南文化符号与文创产品传播',
          img: 'http://rrt2s7opw.hn-bkt.clouddn.com/hanyuyan/%E5%8F%A4%E4%BB%A3%E6%96%87%E5%AD%A6%E5%8F%B2/picture/%E3%80%8A%E5%B2%AD%E5%8D%97%E6%96%87%E5%8C%96%E7%9A%84%E6%B4%BB%E5%8C%96%E4%B8%8E%E4%BC%A0%E6%92%AD%E3%80%8B.png'
        }]
      },

    ],
    fx2: [{
        text: '产品课程1',
        value: 14,
        icon:'',
        lesson: [{
          text: '产品课程1第一节课'
        }]
      },
      {
        text: '产品课程2',
        value: 15,
        icon:'',
        lesson: [{
          text: '产品课程2第一节课'
        }]
      },
      {
        text: '产品课程3',
        value: 16,
        icon:'',
        lesson: [{
          text: '产品课程3第一节课'
        }]
      }
    ],
    fx3: [{
        text: '微信小程序',
        value: 17,
        icon:'',
        lesson: [{
          text: '小程序第一节课',
          url: '第一节课url'
        }, {
          text: '小程序第二节课',
          url: '第二节课url'
        }, {
          text: '小程序第三节课',
          url: '第三节课url'
        }]
      },
      {
        text: 'web前端（HTML+CSS）',
        value: 18,
        icon:'',
        lesson: [{
          text: 'web前端第一节课',
          url: '第一节课URL'
        }]
      },
      {
        text: 'Python',
        value: 19,
        icon:'',
        lesson: [{
          text: 'Python第一节课',
          url: '第一节课url'
        }, {
          text: 'Python第二节课',
          url: '第二节课url'
        }]
      },
      {
        text: 'web前端（js）',
        value: 20,
        icon:'',
        lesson: [{
          text: 'web前端（js）第一节课'
        }]
      }
    ],
    // 这里是选择器的数据
    // 这是第一栏的数据
    option1: [{
        text: '全部方向',
        value: 0,
        icon:'',
      },
      {
        text: '中国古代史',
        value: 1,
        icon:'',
      },
      {
        text: '方向二',
        value: 2,
        icon:'',
      },
      {
        text: '方向三',
        value: 3,
        icon:'',
      }
    ],
    // 这是第二栏的数据
    option2: [],
    value1: 0,
    value2: 0,
    first_id: 0,
    disabled: true,
    text1: '全部方向',
    text2: '全部课程',
  },

  // 这是页面初次加载的渲染方法
  GetAllData() {
    // 定义一个用于拼接数据的变量
    var all = [{
      text: '全部课程',
      value: 0
    }]
    var all_lesson = [...all, ...this.data.gudai, ...this.data.fx2, ...this.data.fx3]
    this.setData({
      option2: all_lesson,
      value2: all_lesson[0].value
    })
    var lesson = all_lesson.splice(1, all_lesson.length + 1)
    this.GetLesson(lesson)
    // var lesson_data = []
    // var lesson_listdata = []
    // var num = 0
    // for (let index = 0; index < lesson.length; index++) {
    //   lesson_data.push(lesson[index].lesson)
    // }
    // for (let index = 0; index < lesson_data.length; index++) {
    //   num += lesson_data[index].length
    //   for (let j = 0; j < num; j++) {
    //     if (lesson_data[index][j] == undefined) {
    //       continue;
    //     }
    //     lesson_listdata.push(lesson_data[index][j])
    //   }
    // }
    // this.setData({
    //   lesson_listdata : lesson_listdata
    // })
  },

  // 这是第一栏数据渲染的方法
  GetFirst(e) {
    // 定义一个用于拼接数据的变量
    var all = [{
      text: '全部课程',
      value: 0
    }]
    // 为第二栏的显示做准备
    var gudai = [...all, ...this.data.gudai]
    var fx2 = [...all, ...this.data.fx2]
    var fx3 = [...all, ...this.data.fx3]

    var id = e.detail
    this.setData({
      first_id: id,
    })
    // 这里是判断是否禁用第二栏选择器
    if (id == 0) {
      this.setData({
        disabled: true
      })
    } else {
      this.setData({
        disabled: false
      })
    }

    // 这里根据用户id来判断渲染哪一个方向的数据
    // 当用户切换页面的时候 记得把page清空
    switch (e.detail) {
      case 0:
        this.GetAllData()
        break;
      case 1:
        this.GetLesson(this.data.gudai)
        this.setData({
          option2: gudai,
          value2: gudai[0].value
        })
        break;
      case 2:
        this.GetLesson(this.data.fx2)
        this.setData({
          option2: fx2,
          value2: fx2[0].value
        })
        break;
      case 3:
        this.GetLesson(this.data.fx3)
        this.setData({
          option2: fx3,
          value2: fx3[0].value
        })
        break;
    }
  },

  // 这是第二栏数据渲染的方法
  GetSecond(e) {
    var first_id = this.data.first_id
    var second_id = e.detail
    var gudai = this.data.gudai.length
    var fx2 = this.data.fx2.length
    var lesson = []
    this.setData({
      second_id : second_id
    })
    switch (first_id) {
      case 1:
        if (second_id == 0) {
          this.GetLesson(this.data.gudai)
        } else {
            lesson = this.data.gudai
            this.setData({
              lesson_listdata: lesson[second_id - 1].lesson
            })
        }
        break;
      case 2:
        if (second_id == 0) {
          this.GetLesson(this.data.fx2)
        } else {
          lesson = this.data.fx2
          this.setData({
            lesson_listdata: lesson[second_id - gudai - 1].lesson
          })
        }
        break;
      case 3:
        if (second_id == 0) {
          this.GetLesson(this.data.fx3)
        } else {
            lesson = this.data.fx3
            this.setData({
              lesson_listdata: lesson[second_id - gudai - fx2 - 1].lesson
            })
          break;
        }
    }
  },

  // 封装获取课程列表数据方法
  GetLesson(lesson) {
    console.log('成功调用此方法')
      var lesson_data = []
      var lesson_listdata = []
      var num = 0
      for (let index = 0; index < lesson.length; index++) {
        lesson_data.push(lesson[index].lesson)
      }
      for (let index = 0; index < lesson_data.length; index++) {
        num += lesson_data[index].length
        for (let j = 0; j < num; j++) {
          if (lesson_data[index][j] == undefined) {
            continue;
          }
          lesson_listdata.push(lesson_data[index][j])
        }
      }
      console.log('this.data.listdata_before::',this.data.lesson_listdata)
      this.setData({
        lesson_listdata : lesson_listdata
      })
      console.log('this.data.lesson_after:',this.data.lesson_listdata)
  },

  // 跳转视频页面
  GoVideo(e) {
    console.log('user_choice:',e.currentTarget.dataset.id)
    console.log('first_id:',this.data.first_id)
    console.log('second_id:',this.data.second_id)
  },

  onLoad(options) {
    if(this.data.first_id == 0){
      this.GetAllData()
    }
    this.setData({
      avatar: app.globalData.avatar
    })
  },
})

### Vant Weapp 版本

1.10.15

### 描述一下你遇到的问题。

当用户选择第一栏的第一个选项并把进度条拉到最底的时候，这个时候用户切换成第一栏的第二个选项，此时会发现组件并没有在this.setdata的方法中重新渲染页面，数据是替换成功了但是进度条依旧是处于页面的最底端

### 重现步骤

1，点击第一栏第一个按钮
2，将页面拉倒最低
3，切换第一栏第二个按钮
4，此时会发现页面还是在最底部

### 设备/浏览器

微信开发者工具

**Comment by johnsonwong666** [comment]
可以提供一个小程序代码片段吗？

**Comment by johnsonwong666** [comment]
由于较长时间没有提供复现代码片段，此issue关闭，若还有问题请提新的issue,并附带复现代码片段排查。
