### ISSUE TITLE
dialog添加给按钮透传属性的配置项

### ISSUE THREAD

**Issue by ninja-liu** [youzan/vant-weapp#5316]
### 这个功能解决了什么问题？

通过js的Dialog接口使用dialog时，配置项内没有给confirm/cancel 按钮绑定事件的属性。目前仅能通过tag 设置bindconfirm事件等。这不利于模块的编写。
小程序中一些权限的获取，必须点击按钮。

### 你期望的 API 是什么样子的？

```js
			Dialog.confirm({
				title: "标题",
				message: "弹窗内容",
//类似配置confirm/cancel button的配置，可配置方法等事件。
				bindConfirm() {
					console.log("bindConfirm");
				},
			}).then(() => {
				// on close
			});
```

**Comment by landluck** [comment]
这里的 bindConfirm 是确认或者取消吗？如果是 .then 就是确认，.catch 就是取消

**Comment by johnsonwong666** [comment]
<img width="771" alt="image" src="https://github.com/youzan/vant-weapp/assets/64689255/b84149a0-a80c-4b8b-9ff8-470fa7878a18">
这个应该可以满足你的需求
