### ISSUE TITLE
van-tabs info文字显示错误

### ISSUE THREAD

**Issue by a243065157** [youzan/vant-weapp#5318]
### 重现链接

```
<van-tabs active="{{ active }}" color="#008BF5">
    <van-tab title="测试文字" info="333"></van-tab>
  </van-tabs>
```

### Vant Weapp 版本

1.10.15

### 描述一下你遇到的问题。

van-tabs组件使用Info属性显示文字，文字显示的位置错误

<img width="1862" alt="image" src="https://user-images.githubusercontent.com/13496515/230702870-1fcfde63-8f35-4550-b273-a7a535b95592.png">
去掉van-tab__title__info类中的display属性就正常了

### 重现步骤

```
<van-tabs active="{{ active }}" color="#008BF5">
    <van-tab title="测试文字" info="333"></van-tab>
  </van-tabs>
```

### 设备/浏览器

微信开发者中举

**Comment by fanburger** [comment]
临时修复的话可以去你小程序项目的根目录，找到`miniprogram_npm/@vant/weapp/tabs/index.wxss`文件，将最后一行`.van-tab__title__info`的`display:inline-block;`删掉（下图中选中部分）。
![image](https://user-images.githubusercontent.com/101820556/230733868-771bb163-5a8c-40b4-990c-5fe665082c5a.png)

**Comment by landluck** [comment]
正常情况下 van-info 的样式应该会覆盖掉 van-tab__tilte__info 的，我这边调试也是这样的情况，UI表现正常，你们那边能复现是有什么特殊设置吗

**Comment by fanburger** [comment]
@landluck 没有特殊设置，直接新建一个小程序项目然后使用下面的代码就能直接复现了，
- pages/index/index.wxml
```wxml
<view class="container" style="background-color: black;">
  <van-tabs active="{{ active }}" color="#008BF5">
    <van-tab title="测试文字" info="333"></van-tab>
  </van-tabs>
</view>
```
- pages/index/index.js
```js
Page({
  data: {
    active:true
  },
  onLoad() {
    
  }
})
```
![image](https://user-images.githubusercontent.com/101820556/230839065-e65ed541-711a-46af-85c2-76e16a145c98.png)

这个错误的原因很可能和 #5282 这个issues中提到的原因一样，微信小程序文档中有如下解释：[文档地址](https://developers.weixin.qq.com/miniprogram/dev/framework/custom-component/wxml-wxss.html#%E5%A4%96%E9%83%A8%E6%A0%B7%E5%BC%8F%E7%B1%BB)
![image](https://user-images.githubusercontent.com/101820556/230839771-8b891520-9bc9-4311-8596-e27e8e034035.png)

复现环境及软件版本：
- 开发平台：win 10
- 调试基础库：2.10.4~2.30.4
- node.js：v16.13.0
- vant-weapp: v1.10.15

真机预览环境及版本：
- 平台：Android 12
- 微信版本：8.0.32

**Comment by a243065157** [comment]
收到

**Comment by landluck** [comment]
该问题修复PR 已MR，本周五会发布新版本

**Comment by landluck** [comment]
`V1.10.16` 版本已修复
