### ISSUE TITLE
[Bug Report] Steps 竖向步骤条 连线会显示在icon上方

### ISSUE THREAD

**Issue by MorningK** [youzan/vant-weapp#5329]
### 重现链接

```
<van-steps
  steps="{{ steps }}"
  active="{{ active }}"
  direction="vertical"
  active-color="{{activeColor}}"
  inactive-icon="clock"
/>
```

### Vant Weapp 版本

1.10.15

### 描述一下你遇到的问题。

竖向步骤条 连线会显示在icon上方
![image](https://user-images.githubusercontent.com/21361743/231698793-56842804-ed6f-4383-910d-67c541416b4a.png)

### 重现步骤

使用`van-steps`组件设置`inactive-icon`属性为`clock`

### 设备/浏览器

macOS微信开发者工具、 Android 9 微信版本8.0.34

**Comment by fanburger** [comment]
已复现，代码片段链接[issue 5329 minicode](https://developers.weixin.qq.com/s/F3CZYrmP7oHy)正在定位问题

**Comment by fanburger** [comment]
可以给icon加一个 background-color: white 的属性临时解决一下这个问题

**Comment by fanburger** [comment]
> 可以给icon加一个 background-color: white 的属性临时解决一下这个问题

可以到 `miniprogram_npm\@vant\weapp\steps\index.wxss` 这个文件中，添加下面这几行 css代码临时解决一下

```css
.van-step__icon {
    background-color: white;
}
```
不太建议直接修改 van-icon 的样式代码，van-icon用到的地方有点多

**Comment by MorningK** [comment]
> 



> > 可以给icon加一个 background-color: white 的属性临时解决一下这个问题
> 
> 可以到 `miniprogram_npm\@vant\weapp\steps\index.wxss` 这个文件中，添加下面这几行 css代码临时解决一下
> 
> ```css
> .van-step__icon {
>     background-color: white;
> }
> ```
> 
> 不太建议直接修改 van-icon 的样式代码，van-icon用到的地方有点多

OK，显示正常了。请问什么时候会发布新版本呢？

**Comment by fanburger** [comment]
> > 
> 
> 
> 
> > > 可以给icon加一个 background-color: white 的属性临时解决一下这个问题
> > 
> > 可以到 `miniprogram_npm\@vant\weapp\steps\index.wxss` 这个文件中，添加下面这几行 css代码临时解决一下
> > 
> > ```css
> > .van-step__icon {
> >     background-color: white;
> > }
> > ```
> > 
> > 不太建议直接修改 van-icon 的样式代码，van-icon用到的地方有点多
> 
> OK，显示正常了。请问什么时候会发布新版本呢？

最近在准备找实习，有点忙🙃，这个问题修复之后我还要测试一下，其实这个问题修复起来应该不复杂，大概1周内我提个pr吧。

**Comment by landluck** [comment]
`v1.10.18` 已修复
