### ISSUE TITLE
checkbox的name不一样为什么从头插入数组，checkbox选中位置不变

### ISSUE THREAD

**Issue by yik7707** [youzan/vant-weapp#5331]
### 重现链接

https://developers.weixin.qq.com/s/2tJDpum47iHb

### Vant Weapp 版本

1.10.15

### 描述一下你遇到的问题。

如题，name是给了随机数，代码片段如链接所示

项目中遇到该场景，name是唯一身份id需要上拉翻页，name不同，从头插入渲染下去，checkbox的位置不变（该checkbox是运用的双向绑定）

项目中，出现的问题有点不一样，翻页（上页）出现相同的位置选中的情况，且原来的checkbox也是选中的

### 重现步骤

1.选中checkbox后，连续点击按钮即可复现

### 设备/浏览器
开发者模拟器/手机都复现该问题

_No response_
![QQ截图20230416004500](https://user-images.githubusercontent.com/74293458/232238734-16b2a313-396d-4fc5-8a51-4012582e68c6.png)

**Comment by johnsonwong666** [comment]
这个可能的原因是动态插入checkbox 时，我把插入对象log了一下  打印的对象都是初始的那个，需要重新选一个触发一下更新，后面看看怎么修复
![image](https://user-images.githubusercontent.com/64689255/233537724-b2fc3739-0edc-458b-91eb-f730b1b8a642.png)
![image](https://user-images.githubusercontent.com/64689255/233537763-d0ce06c4-1452-4931-94d4-b2c69e09b8b9.png)
![image](https://user-images.githubusercontent.com/64689255/233537778-6d2920da-9563-4286-935b-9453498f44aa.png)

**Comment by yik7707** [comment]
> 这个可能的原因是动态插入checkbox 时，我把插入对象log了一下 打印的对象都是初始的那个，需要重新选一个触发一下更新，后面看看怎么修复 ![image](https://user-images.githubusercontent.com/64689255/233537724-b2fc3739-0edc-458b-91eb-f730b1b8a642.png) ![image](https://user-images.githubusercontent.com/64689255/233537763-d0ce06c4-1452-4931-94d4-b2c69e09b8b9.png) ![image](https://user-images.githubusercontent.com/64689255/233537778-6d2920da-9563-4286-935b-9453498f44aa.png)

好的

**Comment by yik7707** [comment]
> > 这个可能的原因是动态插入checkbox 时，我把插入对象log了一下 打印的对象都是初始的那个，需要重新选一个触发一下更新，后面看看怎么修复 ![image](https://user-images.githubusercontent.com/64689255/233537724-b2fc3739-0edc-458b-91eb-f730b1b8a642.png) ![image](https://user-images.githubusercontent.com/64689255/233537763-d0ce06c4-1452-4931-94d4-b2c69e09b8b9.png) ![image](https://user-images.githubusercontent.com/64689255/233537778-6d2920da-9563-4286-935b-9453498f44aa.png)
> 
> 好的麻烦了

**Comment by johnsonwong666** [comment]
还在吗？我重新写了一份类似的复现代码，看一下符合你的场景吗？从头插头checkbox，看起来没有问题，感觉是不是你代码写的有问题？ 
https://developers.weixin.qq.com/s/orKpjXmR7OHu

**Comment by yik7707** [comment]
> 还在吗？我重新写了一份类似的复现代码，看一下符合你的场景吗？从头插头checkbox，看起来没有问题，感觉是不是你代码写的有问题？ https://developers.weixin.qq.com/s/orKpjXmR7OHu

上面代码片段中，改成形式就没问题了：
![image](https://user-images.githubusercontent.com/74293458/236233313-19361d0c-2e55-45d9-b4ce-96c75e87f8ff.png)
项目中，改成相同代码还是会出现相同问题，如下图：
![image](https://user-images.githubusercontent.com/74293458/236233472-4b06a7ed-252f-4923-858c-0480ccd33238.png)
从请求中得到结果，以选中address【address为网站下载地址】为name命名，大致结果如下图所示，现在不知道如何定位该问题：
下载地址例如："https://......./a955aa73830189193f316326c9a746d1/6453d7b8/video/tos/cn/tos-cn-ve-15c001-alinc2/oMU9aNjAk0Qb2iYanAIfU287hDRB1gbeDSAX0E/?a=1128&ch=54&cr=0&dr=0&lr=all&cd=0%7C0%7C0%7C0&cv=1&br=1874&bt=1874&cs=0&ds=3&ft=bvjWJkQQqU-mfJ40mo0OW_EklpPiXX_QlMVJExXFCJ0PD-I&mime_type=video_mp4&qs=0&rc=ZDk0NGk3Zmc6ZTk6Ojs1OEBpM25leGk6Zjs3aTMzNGkzM0AzLjA0MjNeXjUxLV5iMTYzYSNgcmczcjRnYWFgLS1kLWFzcw%3D%3D&l=20230504230018CDAEFDA24BE602369118&btag=e000b0000"
![image](https://user-images.githubusercontent.com/74293458/236234294-688f80bb-7843-4d0c-b65c-748f7a1dfcf6.png)
![image](https://user-images.githubusercontent.com/74293458/236250220-d775824b-091f-4989-8f19-2db05576b861.png)

**Comment by johnsonwong666** [comment]
@yik7707 
代码看起来跟你之前提供的不太一样，提供一个最小复现片段，异步请求使用定时器模拟

**Comment by yik7707** [comment]
> @yik7707 代码看起来跟你之前提供的不太一样，提供一个最小复现片段，异步请求使用定时器模拟

https://developers.weixin.qq.com/s/QNF5pYmf7xHY
上述代码片段随机获取了100多条本地数据直接传值，在顶部下拉动作触发请求模拟（注意：下拉后只有result2的数据会添加进去，再拉下则会重复添加）
如何复现：
1.先选中checkbox要下载的图片
2.然后下拉请求更多数据
3.翻页后发现新的数据选中了，老的数据是选中状态
麻烦定位问题所在

**Comment by johnsonwong666** [comment]
@yik7707 保证wx:for 的key值唯一 ， 看起来work_id可以作为唯一key值
https://developers.weixin.qq.com/s/t7JiGYmR7zHV

**Comment by yik7707** [comment]
> @yik7707 保证wx:for 的key值唯一 ， 看起来work_id可以作为唯一key值 https://developers.weixin.qq.com/s/t7JiGYmR7zHV

好的谢谢，在上面我提供的代码wx:key中修改后，选中问题没了，但是又发现一个新问题，中间有一个空缺，就是修改wx:key导致的，这又是什么情况如下图所示，麻烦从上面的提供的代码片段直接修改一下wx:key，查看bug：
![image](https://user-images.githubusercontent.com/74293458/236385432-4d2f05c8-12b9-45d5-9be6-978785696e5f.png)

**Comment by yik7707** [comment]
> > @yik7707 保证wx:for 的key值唯一 ， 看起来work_id可以作为唯一key值 https://developers.weixin.qq.com/s/t7JiGYmR7zHV
> 
> 好的谢谢，在上面我提供的代码wx:key中修改后，选中问题没了，但是又发现一个新问题，中间有一个空缺，就是修改wx:key导致的，这又是什么情况如下图所示，麻烦从上面的提供的代码片段直接修改一下wx:key，查看bug（项目中也是会出现这个bug）： ![image](https://user-images.githubusercontent.com/74293458/236385432-4d2f05c8-12b9-45d5-9be6-978785696e5f.png)

**Comment by yik7707** [comment]
> @yik7707 保证wx:for 的key值唯一 ， 看起来work_id可以作为唯一key值 https://developers.weixin.qq.com/s/t7JiGYmR7zHV

好的谢谢，在上面我提供的代码wx:key中修改后，选中问题没了，但是又发现一个新问题，中间有一个空缺，就是修改wx:key导致的，这又是什么情况如下图所示，麻烦从上面的提供的代码片段直接修改一下wx:key，查看bug（项目中也是会出现这个bug）
代码片段：
![image](https://user-images.githubusercontent.com/74293458/236385855-1fa64605-659e-401d-9296-4ed45e4da983.png)
项目中：
![image](https://user-images.githubusercontent.com/74293458/236386304-30adb72e-b0fd-45d0-88ae-8aa5f4424627.png)

**Comment by johnsonwong666** [comment]
@yik7707 控制台检索一下是什么东西 没有复现这个情况

**Comment by yik7707** [comment]
> @yik7707 控制台检索一下是什么东西 没有复现这个情况
这个空白区域在翻页的位置，我刚刚重新打开了一下我上面的代码片段修改都有

项目中的节点审查就是隔开了，光标移动到空白区域没用，审查不到元素，智能移动到上下的图片上面
![image](https://user-images.githubusercontent.com/74293458/236386511-c1483fb6-dbab-4d3e-aec5-d222c8384bba.png)
![image](https://user-images.githubusercontent.com/74293458/236386526-3548fefa-08b1-43c0-b747-b07a48e200bc.png)
项目中的appdata，没任何东西很正常：
![image](https://user-images.githubusercontent.com/74293458/236386578-cc832b84-9cb2-4df7-a11d-0f652c6150a5.png)

**Comment by johnsonwong666** [comment]
@yik7707 节点审查不到 那感觉就不是vant-weapp组件库的问题  尝试少量渲染

**Comment by yik7707** [comment]
> @yik7707 节点审查不到 那感觉就不是vant-weapp组件库的问题 尝试少量渲染

你好按你上面所说，我测试我每次加载20个翻页20个，我修改一下后台还是这种情况，问题是不应该修改wx:key修改后就出现这种情况把：
![image](https://user-images.githubusercontent.com/74293458/236388320-30f0e7a4-3dd9-4b7b-93b7-719ef7e80872.png)
![image](https://user-images.githubusercontent.com/74293458/236388226-c6168eea-9e7d-4c5a-9aae-730d26c6e837.png)

**Comment by johnsonwong666** [comment]
@yik7707 wx:key改了什么 复现代码发一下

**Comment by yik7707** [comment]
> @yik7707 节点审查不到 那感觉就不是vant-weapp组件库的问题 尝试少量渲染

我之前翻页是每次50个，并不是每次100条直接渲染太多了数据
https://developers.weixin.qq.com/s/JMR6vYme7NHy
这个空白处处于翻页后选中的位置，就在上面我提供了的代码片段就改了个wx:key，emm- -
![image](https://user-images.githubusercontent.com/74293458/236388847-3769481c-e273-44e4-b4f1-12c49af68a91.png)

**Comment by johnsonwong666** [comment]
看到了。好奇怪 key是index没问题，但是如果你的列表是动态增加的，用index作为key是不合理的，还是需要修改key值的。想办法让grid组件重新排列一下，加个loading什么的，加载完成再让check-group重新显示。

**Comment by yik7707** [comment]
> 看到了。好奇怪 key是index没问题，但是如果你的列表是动态增加的，用index作为key是不合理的，还是需要修改key值的。想办法让grid组件重新排列一下，加个loading什么的，加载完成再让check-group重新显示。

在请求setdata赋值后不就会重新渲染前面的数据吗，怎么让grid的组件重新排列，之前从来没做过这种操作

**Comment by johnsonwong666** [comment]
> > 看到了。好奇怪 key是index没问题，但是如果你的列表是动态增加的，用index作为key是不合理的，还是需要修改key值的。想办法让grid组件重新排列一下，加个loading什么的，加载完成再让check-group重新显示。
> 
> 在请求setdata赋值后不就会重新渲染前面的数据吗，怎么让grid的组件重新排列，之前从来没做过这种操作

加个flag 标识 然后check-group上面 加wx:if

**Comment by yik7707** [comment]
> > > 看到了。好奇怪 key是index没问题，但是如果你的列表是动态增加的，用index作为key是不合理的，还是需要修改key值的。想办法让grid组件重新排列一下，加个loading什么的，加载完成再让check-group重新显示。
> > 
> > 
> > 在请求setdata赋值后不就会重新渲染前面的数据吗，怎么让grid的组件重新排列，之前从来没做过这种操作
> 
> 加个flag 标识 然后check-group上面 加wx:if

flag标识加在grid上吗？我看文档没有这个flag属性？
![image](https://user-images.githubusercontent.com/74293458/236395174-4a13a100-de3e-4637-b759-d3677be97465.png)
![image](https://user-images.githubusercontent.com/74293458/236395215-59cdc8c4-4dd0-4c39-a2a9-9adc8885b890.png)

**Comment by johnsonwong666** [comment]
> > > > 看到了。好奇怪 key是index没问题，但是如果你的列表是动态增加的，用index作为key是不合理的，还是需要修改key值的。想办法让grid组件重新排列一下，加个loading什么的，加载完成再让check-group重新显示。
> > > 
> > > 
> > > 在请求setdata赋值后不就会重新渲染前面的数据吗，怎么让grid的组件重新排列，之前从来没做过这种操作
> > 
> > 
> > 加个flag 标识 然后check-group上面 加wx:if
> 
> flag标识加在grid上吗？我看文档没有这个flag属性？ ![image](https://user-images.githubusercontent.com/74293458/236395174-4a13a100-de3e-4637-b759-d3677be97465.png) ![image](https://user-images.githubusercontent.com/74293458/236395215-59cdc8c4-4dd0-4c39-a2a9-9adc8885b890.png)

flag就是个变量名 想要根据这个变量切换 显示隐藏态

**Comment by yik7707** [comment]
@johnsonwong666 这个问题，你们有时间可以排查一下vant weapp的内部代码吗，这种数据多每次都要从头排列再次重新渲染的场景这样的解决方法是有问题的

**Comment by johnsonwong666** [comment]
@yik7707 后面有时间再看了

**Comment by yik7707** [comment]
> @yik7707 后面有时间再看了

好的麻烦了，翻页的数据少就还好，如果每次增加再渲染整个数组，那性能压力都会成倍增加的

**Comment by johnsonwong666** [comment]
这个issue先关闭了，问题定位是key的原因。也欢迎你排查一下空白块的问题提个pr过来。
