### ISSUE TITLE
[Bug Report] 

### ISSUE THREAD

**Issue by jerryting** [youzan/vant-weapp#5332]
### 重现链接

   
![Uploading WX20230416-151958@2x.png…]()

### Vant Weapp 版本

1.10.15

### 描述一下你遇到的问题。

icon

### 重现步骤

升级版本到 1.10.15(之前版本1.10.10)后，iconfont 的图标都显示不了，有些和 vant icon还是串的，
注销掉 dist/icon/index.wxs 的  代码 才恢复
`function rootClass(data) {
  var classes = ['custom-class'];

  if (data.classPrefix != null) {
    classes.push(data.classPrefix);
  }

  // if (data.classPrefix !== 'van-icon') {
  //   classes.push('van-icon')
  // }

  if (isImage(data.name)) {
    classes.push('van-icon--image');
  } else if (data.classPrefix != null) {
    classes.push(data.classPrefix + '-' + data.name);
  }

  return classes.join(' ');
}`

**Comment by fanburger** [comment]
这个问题的修复 pr 已经 merge 了，应该下个版本就修复了吧
#5320

**Comment by landluck** [comment]
`V1.10.16` 版本已修复
