### ISSUE TITLE
action-sheet组件最新版本样式有错误

### ISSUE THREAD

**Issue by yik7707** [youzan/vant-weapp#5335]
### 重现链接

action-sheet代码片段：https://developers.weixin.qq.com/s/VCNdBCme7LHi

### Vant Weapp 版本

1.10.16

### 描述一下你遇到的问题。

![QQ截图20230421020803](https://user-images.githubusercontent.com/74293458/233451716-564e7028-ef6c-4ac8-832d-e755175d281b.png)
![QQ截图20230421021333](https://user-images.githubusercontent.com/74293458/233452484-885c13e1-ab12-4004-a81b-6b7aa25a87eb.png)

### 重现步骤

1.10.16版本最新右上角的×居中显示请修复，以及检查×居中显示是否运用了公共样式波及其他组件，导致更多组件出现相同问题，参照1.10.15版本修复即可

**Comment by fanburger** [comment]
@landluck 这个bug我定位到是在 #5320 这次提交中的`packages/icon/index.less`第5行新加的` position: relative;`导致的，我在你pr中标一下。

**Comment by yik7707** [comment]
@fanburger @landluck 请问下面反馈的checkbox从头插入位置不变的问题，能定位出是哪里的问题吗

**Comment by fanburger** [comment]
> @fanburger @landluck 请问下面反馈的checkbox从头插入位置不变的问题，能定位出是哪里的问题吗

稍等，我来看一看，有结果我会在 #5331 这个issue里面回复您。

**Comment by yik7707** [comment]
> > @fanburger @landluck 请问下面反馈的checkbox从头插入位置不变的问题，能定位出是哪里的问题吗
> 
> 稍等，我来看一看，有结果我会在 #5331 这个issue里面回复您。

好的麻烦了

**Comment by landluck** [comment]
`v1.10.17` 已修复
