### ISSUE TITLE
TreeSelect 分类选择

### ISSUE THREAD

**Issue by 15883854381** [youzan/vant-weapp#5336]
### 重现链接

https://vant-contrib.gitee.io/vant/#/zh-CN/tree-select

### Vant Weapp 版本

4.1.2

### 描述一下你遇到的问题。

多选模式中
======================
  v-model:active-id="activeIds"
 const activeId = ref([1, 2]);
======================

<van-tree-select
  v-model:active-id="activeIds"
  v-model:main-active-index="activeIndex"
  :items="items"
/>

import { ref } from 'vue';

export default {
  setup() {
    const activeId = ref([1, 2]);
    const activeIndex = ref(0);
    const items = [
      {
        text: '浙江',
        children: [
          { text: '杭州', id: 1 },
          { text: '温州', id: 2 },
          { text: '宁波', id: 3, disabled: true },
        ],
      },
      {
        text: '江苏',
        children: [
          { text: '南京', id: 4 },
          { text: '无锡', id: 5 },
          { text: '徐州', id: 6 },
        ],
      },
      { text: '福建', disabled: true },
    ];

    return {
      items,
      activeId,
      activeIndex,
    };
  },
};

### 重现步骤

变量名使用错误

**Comment by johnsonwong666** [comment]
请提到vant仓库里  https://github.com/youzan/vant/issues
