### ISSUE TITLE
Field 输入框 的type类型中tel->手机号格式无法主动校验

### ISSUE THREAD

**Issue by zhulinghaizhoqiaodaima** [youzan/vant-weapp#5337]
### 重现链接

![image](https://user-images.githubusercontent.com/75928200/233562487-1cfccda3-7937-429f-8671-cc0d7c308b0f.png)

### Vant Weapp 版本

1.10.16

### 描述一下你遇到的问题。

![image](https://user-images.githubusercontent.com/75928200/233562676-c8af0cc0-1fc7-4834-bd3c-6eb77e002206.png)

### 重现步骤

设置Field 输入框，type类型为tel真机情况下手机号类型不起作用无效

### 设备/浏览器

都不起效

**Comment by fanburger** [comment]
文档里面似乎没有type="tel"这个属性值吧，目前好像你只能自己写一下校验规则。

**Comment by ArriveAstral** [comment]
我是用 type="number" 属性 自己写校验规则

**Comment by zhulinghaizhoqiaodaima** [comment]
> 我是用 type="number" 属性 自己写校验规则

对啊，我是这样解决的

**Comment by zhulinghaizhoqiaodaima** [comment]
> 文档里面似乎没有type="tel"这个属性值吧，目前好像你只能自己写一下校验规则。

这个我就是tel属性我是复制官方的来着，不过目前官方已经改了。

**Comment by johnsonwong666** [comment]
目前看源码是没有提供校验的，预览是使用的vant2，文档错误了，校验考虑加入下一版本。

**Comment by zhulinghaizhoqiaodaima** [comment]
> 目前看源码是没有提供校验的，预览是使用的vant2，文档错误了，校验考虑加入下一版本。

好的，辛苦！

**Comment by johnsonwong666** [comment]
当前版本未提供校验，此issue暂时关闭。
