### ISSUE TITLE
[Bug Report] van-uploader上传视频不走回调了。

### ISSUE THREAD

**Issue by LinkerM** [youzan/vant-weapp#5340]
### 重现链接

<van-uploader compressed="{{true}}" file-list="{{ fileVideoList }}" bind:after-read="afterReadVideo" bind:delete="deleteVideo" deletable="{{ true }}" max-count="9" multiple = "{{ true }} " accept="media" upload-icon="video-o"/>

### Vant Weapp 版本

1.10.14

### 描述一下你遇到的问题。

van-uploader上传图片没有问题，会走bind:after-read的回调
上传视频就不走回调了。

### 重现步骤

点击上传，选择视频，不走回调。

**Comment by johnsonwong666** [comment]
没有复现，我自己的手机1.10.16版本回调正常触发，可以提供一个小程序代码片段来排查吗？

**Comment by LinkerM** [comment]
<van-uploader compressed="{{true}}" file-list="{{ fileVideoList }}" bind:after-read="afterReadVideo" bind:delete="deleteVideo" deletable="{{ true }}" max-count="9" multiple = "{{ true }} " accept="media" upload-icon="video-o"/>

https://user-images.githubusercontent.com/33533167/234156337-f6b24fc0-98b8-4a89-9f08-b9404ad52668.mp4

**Comment by LinkerM** [comment]
调了微信的基础库也没有用

**Comment by johnsonwong666** [comment]
<img width="1179" alt="image" src="https://user-images.githubusercontent.com/64689255/234158044-054dcbfe-2196-4ebf-b7d6-3d575492aee7.png">
用了你的代码测试了一下，回调正常触发。我的环境是1.10.16最新版本，调试基础库2.25.3，可以调整一下版本或调试一下vant-weapp源码测试一下

**Comment by johnsonwong666** [comment]
> 调了微信的基础库也没有用
<img width="1192" alt="image" src="https://user-images.githubusercontent.com/64689255/234158454-dda0b749-e27a-4c57-84aa-e5901fffc4eb.png">
用了你的代码测试了一下，回调正常触发。我的环境是1.10.16最新版本，调试基础库2.25.3，可以调整一下版本或调试一下vant-weapp源码测试一下。

**Comment by LinkerM** [comment]
都试了，都不好用。您方便的话把您好用的这个工程发给我，我这边试一下吗

**Comment by LinkerM** [comment]
17600555351@163.com邮箱

**Comment by johnsonwong666** [comment]
> 都试了，都不好用。您方便的话把您好用的这个工程发给我，我这边试一下吗

https://developers.weixin.qq.com/s/hVvESJmg7yH0

**Comment by LinkerM** [comment]
emmmm，这个我这边上传视频的也不走。

**Comment by LinkerM** [comment]
就很奇怪。我现在的环境是1.10.16最新版本，调试基础库2.25.3

**Comment by johnsonwong666** [comment]
> emmmm，这个我这边上传视频的也不走。

开发者工具重装一下？或者别人的电脑、真机试一下？我这复现不出来，不知如何排查。

**Comment by LinkerM** [comment]
好的，我试试吧

**Comment by johnsonwong666** [comment]
> 好的，我试试吧

可以了吗？

**Comment by johnsonwong666** [comment]
没有复现，暂时关闭issue，可以稳定复现时请带上代码片段方便排查问题。
