### ISSUE TITLE
[Feature Request] uploader新增在选择文件之前的事件

### ISSUE THREAD

**Issue by masicheng** [youzan/vant-weapp#5342]
### 这个功能解决了什么问题？

有的业务场景需要用户选择是从相册选择图片或着从微信聊天选择文件

### 你期望的 API 是什么样子的？

    beforeUpload(e) {
      wx.showActionSheet({
        itemList: ['从相册选择图片', '从微信聊天列表选择文件'],
        success: res => {
          // this.data.accept = ;
          this.setData({
            accept: res.tapIndex == 0 ? 'image' : 'file',
          }, () => {
            e.detail.callback(true)
          })
        }
      })
    },

**Comment by landluck** [comment]
![image](https://user-images.githubusercontent.com/27060081/234747820-eb31517d-32f4-4a91-b541-752d2dc60ff5.png)

**Comment by masicheng** [comment]
这个事件是在读取文件前，我想要在选择文件前
