### ISSUE TITLE
[Bug Report] uploader拍照使用wx.chooseImage部分iOS设备会造成刷新页面

### ISSUE THREAD

**Issue by masicheng** [youzan/vant-weapp#5343]
### 重现链接

https://developers.weixin.qq.com/s/ECsYmImk7zHc

### Vant Weapp 版本

1.10.16

### 描述一下你遇到的问题。

uploader拍照chooseImage部分iOS设备会造成刷新页面

### 重现步骤

填写form表单后拍照会reload当前页面，导致已填写的值丢失

### 设备/浏览器

iphone12

**Comment by masicheng** [comment]
切换成wx.chooseMedia可以解决

**Comment by landluck** [comment]
> 切换成wx.chooseMedia可以解决

accept 改为 `media ` 并通过 `media-type` 限制为 `['image']` 可以解决，刷新问题是微信原生问题，组件库暂时无法解决

**Comment by masicheng** [comment]
可以解决呀，目前type=image时组件库调用的是wx.chooseImage,但是该API已经停止维护了，我测试过替换成wx.chooseMedia拍照就不会存在刷新的问题

**Comment by landluck** [comment]
可以提个 PR ?

**Comment by landluck** [comment]
`v1.10.17` 已发布
