### ISSUE TITLE
[Bug Report] field bindinput方法不支持通过返回值去设置属性（value, cursor等）

### ISSUE THREAD

**Issue by p2227** [youzan/vant-weapp#5345]
### 重现链接

https://developers.weixin.qq.com/s/D3OyPImi7vHZ

### Vant Weapp 版本

1.10.16

### 描述一下你遇到的问题。

官方的input从 2.1.0 起支持，处理函数可以直接 return 一个字符串（或对象），将替换输入框的内容。这种情况下，不会引起光标错乱，但是这里的field 在bindinput 中 返回值并不生效

### 重现步骤

在两个输入框中分别输入 12345

本组件库会显示 12345
官方库显示 1234 5

期望： 与官方表现一致

![image](https://user-images.githubusercontent.com/4214942/234066252-f61d1287-edfd-4933-af9f-0f79ae3250bc.png)

**Comment by landluck** [comment]
`v1.10.18` 已支持，使用方式参考 https://youzan.github.io/vant-weapp/#/field#ti-huan-shu-ru-kuang-zhi
