### ISSUE TITLE
[Bug Report] 示例预览不了呀,导入进去各种路径不对

### ISSUE THREAD

**Issue by liqiangdada** [youzan/vant-weapp#5346]
### 重现链接

wu

### Vant Weapp 版本

1.10.16

### 描述一下你遇到的问题。

示例预览不了呀,导入进去各种路径不对
最近刚转战小程序开发,官方文档中没有对tab标签页中'滚动导航'进行说明,想导入一下示例,发现路径各种报错

### 重现步骤

1. 下载所有代码
2. vant-weapp-dev\example导入小程序开发工具
3. 报错

**Comment by landluck** [comment]
执行以下命令 `yarn && yarn dev`

**Comment by johnsonwong666** [comment]
yarn && yarn dev 完成后微信小程序工具打开example目录
