### ISSUE TITLE
[Bug Report]GoodsActionButton 商品导航 设置size没有反应

### ISSUE THREAD

**Issue by nanhupatar** [youzan/vant-weapp#5347]
### 重现链接

https://youzan.github.io/vant-weapp/#/goods-action

### Vant Weapp 版本

1.10.16

### 描述一下你遇到的问题。

看了一下源码 ，没有提供 size，按钮是默认大小的

### 重现步骤

看了一下源码 ，没有提供 size，按钮是默认大小的

### 设备/浏览器

小程序

**Comment by nanhupatar** [comment]
这是个bug ，文档中有size但是没生效，因为源码中没用

**Comment by landluck** [comment]
`v1.10.18` 已修复
