### ISSUE TITLE
[Bug Report] checkbox在uniapp下失效，无法正确显示选中的状态

### ISSUE THREAD

**Issue by CherishMvp** [youzan/vant-weapp#5348]
### 重现链接

示例代码：
      <view>
        <van-checkbox-group :value="selectedFruits" @change="onChange">
          <van-checkbox name="apple" :value="3" />
          <van-checkbox name="banana" :value="4" />
          <van-checkbox name="orange" :value="5" />
        </van-checkbox-group>

        <van-button type="primary" @click="submit">提交</van-button>
      </view>

### Vant Weapp 版本

1.10.15

### 描述一下你遇到的问题。

选择checkbox无法更新选中状态，使用uniapp原生的可以正常显示。

### 重现步骤

1.勾选项目，控制台只能打印出name
2.也无法实现取消勾选

**Comment by johnsonwong666** [comment]
uniapp平台出现的问题暂时不支持解决，请将issue提至官方。
