### ISSUE TITLE
[Bug Report] 原生小程序开发，分包内自定义components组件，组件内引入vantweapp报错

### ISSUE THREAD

**Issue by jungkook988** [youzan/vant-weapp#5349]
### 重现链接

card.json文件:
```json(0)
{
  "component": true,
  "usingComponents": {
    "van-cell": "@vant/weapp/cell/index",
    "van-cell-group": "@vant/weapp/cell-group/index"
  }
}
```
card.wxml文件：
```html(0)
<van-cell-group>
  <van-cell title="单元格" value="内容" />
  <van-cell title="单元格" value="内容" label="描述信息" border="{{ false }}" />
</van-cell-group>
```

### Vant Weapp 版本

1.10.16

### 描述一下你遇到的问题。

控台直接报错，xxxPackage/components/card/card.json undefined

![企业微信截图_16825645897467](https://user-images.githubusercontent.com/116932703/234749024-f4356312-49c7-426d-8326-9a57c72cb6f6.png)

### 重现步骤

1. 创建分包；
2. 创建components文件夹；
3. 创建card文件夹；
4. 新建Component；

![企业微信截图_16825646805132](https://user-images.githubusercontent.com/116932703/234749179-a1bbad4e-f401-4c88-b948-c43a208d2555.png)

**Comment by jungkook988** [comment]
实测，根目录下components文件夹内创建自定义组件，引入vant/weapp没有问题，分包内自定义组件引入就会报错。目前测试是所有vant/weapp的组件在分包内的自定义组件引入就会报错。

**Comment by johnsonwong666** [comment]
确认一下 usingComponents 配置的各组件引用路径

**Comment by johnsonwong666** [comment]
<img width="1257" alt="image" src="https://user-images.githubusercontent.com/64689255/235075460-621b5f58-e43b-4ac5-842a-b59e4824829f.png">
<img width="879" alt="image" src="https://user-images.githubusercontent.com/64689255/235075802-1f594502-602e-4f8e-9424-423712cafc10.png">
[下载 小程序示例（分包加载版）源码](https://res.wx.qq.com/wxdoc/dist/assets/media/demo-subpackages.b42a3adb.zip)
使用官方分包demo简单测试了一下，components是一个子包，写了一个自定义card组件，这个card使用了van-button，在image里面引入这个自定义card组件，没有发现异常，尝试重新构建一下npm
