### ISSUE TITLE
[Bug Report] 在actionsheet里面使用stepper，ios下输入数字，键盘错误

### ISSUE THREAD

**Issue by roy2651** [youzan/vant-weapp#5351]
### 重现链接

暂无

### Vant Weapp 版本

1.10.13

### 描述一下你遇到的问题。

在action-sheet里面使用自定义组件，里面包含stepper，在IOS真机演示的时候，在input框输入数字，在获取焦点的一开始，里面的焦点不跟input框平行，但是当输入数字后，键盘恢复跟input框

### 重现步骤

1.点击按钮，显示出action-sheet
![wecom-temp-117765-541973fae124f4363340c1d8ef15799f](https://user-images.githubusercontent.com/14157170/235050478-86f023db-6829-4fc5-bb64-6d8dcba18d7e.jpg)
2.点击stepper里面输入框，呼出了键盘（异常）
![wecom-temp-121733-f92e7fcfc71bdf4ea72fbcad7225f5e0](https://user-images.githubusercontent.com/14157170/235050545-43adea3a-f846-464d-919f-dd9f5a273d9b.jpg)
3.输入数字后，恢复正常显示
![wecom-temp-127911-69f7187c64bedf84592a12ce892857d7](https://user-images.githubusercontent.com/14157170/235050599-0a77ed88-e5f9-42a7-b00d-85b99e2dbb96.jpg)

### 设备/浏览器

ios下小程序

**Comment by johnsonwong666** [comment]
可以提供一个小程序代码片段过来吗？

**Comment by roy2651** [comment]
@johnsonwong666 
https://developers.weixin.qq.com/s/LHhDGOm47VHn

**Comment by johnsonwong666** [comment]
@roy2651  什么手机型号系统？ 测试xr设备没有复现

**Comment by roy2651** [comment]
> @roy2651 什么手机型号系统？ 测试xr设备没有复现

我16.4.1 微信版本8.0.37，

不会吧，我之前上体验版本，其他的手机也这样

![wecom-temp-42659-4ef1c6885bc8b4f3873ef40ced770367](https://user-images.githubusercontent.com/14157170/236729071-7b257a15-dc4f-4e02-a60e-b226d7ef820d.jpg)
![wecom-temp-66999-e767839516dddf7cec79ba2c00a11e53](https://user-images.githubusercontent.com/14157170/236729111-4cd72496-41d8-45d0-a98a-eae515f526a7.jpg)
![wecom-temp-68128-1bf76ea08ff050be6caa5ad8ef8457c7](https://user-images.githubusercontent.com/14157170/236729124-534772f0-d2e0-4935-a274-a8d3965920d0.jpg)

**Comment by johnsonwong666** [comment]
> @johnsonwong666 https://developers.weixin.qq.com/s/LHhDGOm47VHn

这个代码片段你稳定复现吗？

**Comment by roy2651** [comment]
> > @johnsonwong666 https://developers.weixin.qq.com/s/LHhDGOm47VHn
> 
> 这个代码片段你稳定复现吗？

是的

**Comment by johnsonwong666** [comment]
> > > @johnsonwong666 https://developers.weixin.qq.com/s/LHhDGOm47VHn
> > 
> > 
> > 这个代码片段你稳定复现吗？
> 
> 是的

手上测试机没有复现，感觉是键盘拉起是造成的问题

**Comment by johnsonwong666** [comment]
使用always-embed 看一下 
<img width="1149" alt="image" src="https://github.com/youzan/vant-weapp/assets/64689255/c1226af1-d69a-47bd-a4ce-54368e2634c8">
