### ISSUE TITLE
grid下拉增加数据造成的空白格问题

### ISSUE THREAD

**Issue by yik7707** [youzan/vant-weapp#5360]
### 重现链接

https://developers.weixin.qq.com/s/JMR6vYme7NHy

### Vant Weapp 版本

1.10.17

### 描述一下你遇到的问题。

回顾之前的pr：
1.循环渲染中key是index没问题，但是如果列表是动态增加的，用index作为key是不合理的，还是需要修改key值的。

2.想办法让grid组件重新排列一下，加个loading什么的，加载完成再让check-group重新显示。
缺点是：数据多了每次从头到尾渲染图片会成倍造成渲染压力和性能问题。

3.我之前翻页是每次50个，并不是每次100条直接渲染太多了数据

4.我测试我每次加载20个翻页20个，我修改一下后台还是这种情况，问题是不应该修改wx:key修改后就出现这种情况把：
![image](https://user-images.githubusercontent.com/74293458/236523535-a57aae36-0076-4892-84ea-421abd280d91.png)

### 重现步骤

wx:key为workid（唯一值）的时候（为index却不会造成空白格问题发生）
1.下拉增加数据会出现，翻页空白格的情况
麻烦请定位问题所在

### 设备/浏览器

开发模拟器

**Comment by johnsonwong666** [comment]
你之前的数据可以保证数据唯一性吗？

**Comment by yik7707** [comment]
> 你之前的数据可以保证数据唯一性吗？

workid能保证唯一性

**Comment by yik7707** [comment]
> 你之前的数据可以保证数据唯一性吗？

数据来自dy，workid来自作品id只能是唯一值

**Comment by landluck** [comment]
2.x 重构为 flex 布局可以解决问题
