### ISSUE TITLE
van-image没有给宽高就不显示了

### ISSUE THREAD

**Issue by A1nto** [youzan/vant-weapp#5361]
### 重现链接

<van-image src="XXX" /> 这样就不会显示

### Vant Weapp 版本

1.10.17

### 描述一下你遇到的问题。

<van-image src="XXX" /> 这样就不会显示

### 重现步骤

<van-image src="XXX" /> 这样就不会显示

**Comment by A1nto** [comment]
<van-image src="xxx" />没有给宽高属性就不会在页面中显示

**Comment by johnsonwong666** [comment]
提供一下复现代码

**Comment by A1nto** [comment]
`<van-image src="xxx" />`  就这样写不会显示图片

**Comment by johnsonwong666** [comment]
历史版本不传height/width 也不可以显示，源码的height/width 默认值为null 作用在外层的view上
@A1nto

**Comment by A1nto** [comment]
`/*这个不显示*/
<view style="width: 100rpx; height: auto; background-color: #ccc;">
        <van-image width="100%" height="100%" fit="cover" src="http:///p4.qhimg.com/t01ac9fe85269fd8f50.jpg" />
    </view>
    /*这个显示*/
    <van-image width="100%" height="300rpx" fit="cover" lazy-load src="http:///p4.qhimg.com/t01ac9fe85269fd8f50.jpg" use-loading-slot>
        <van-loading slot="loading" type="spinner" size="20" vertical />
    </van-image>`

**Comment by johnsonwong666** [comment]
> `/*这个不显示*/ <view style="width: 100rpx; height: auto; background-color: #ccc;"> <van-image width="100%" height="100%" fit="cover" src="http:///p4.qhimg.com/t01ac9fe85269fd8f50.jpg" /> </view> /*这个显示*/ <van-image width="100%" height="300rpx" fit="cover" lazy-load src="http:///p4.qhimg.com/t01ac9fe85269fd8f50.jpg" use-loading-slot> <van-loading slot="loading" type="spinner" size="20" vertical /> </van-image>`

父元素 height:auto，子元素 height:100%时需要根据父元素计算的 你这么写不合理

**Comment by A1nto** [comment]
这个不能像image标签那样不给宽高就能显示图片么

**Comment by johnsonwong666** [comment]
> 能

目前不支持，参考一下文档的使用

**Comment by johnsonwong666** [comment]
> 这个不能像image标签那样不给宽高就能显示图片么

目前不支持，参考一下文档的使用

**Comment by johnsonwong666** [comment]
这个issue先close了，参考文档使用。
