### ISSUE TITLE
[Feature Request] 能不能给步进器增加一个单位显示

### ISSUE THREAD

**Issue by laodengjuntuan** [youzan/vant-weapp#5363]
### 这个功能解决了什么问题？

想在步进器的数字旁边有个单位，希望能补充一个字段

### 你期望的 API 是什么样子的？

<van-stepper value="{{ 1 }}" bind:change="onChange" step="0.5" unit=“kg”/>

**Comment by landluck** [comment]
暂时不会考虑支持这样的功能，input 中增加单位会导致计算和显示处理成本比较高
