### ISSUE TITLE
关于Dialog组件异步关闭的问题

### ISSUE THREAD

**Issue by Detco** [youzan/vant-weapp#5366]
### 重现链接

https://developers.weixin.qq.com/s/DRWXh4mq7gIV

### Vant Weapp 版本

1.10.17

### 描述一下你遇到的问题。

我照着文档的原样搬出来直接使用，发现异步的取消只会停止加载状态，而不会关闭弹窗，文档演示确实可以关闭。

然后我看了看你们的关闭部分的源码发现传false只是关闭加载动画，传true不能立即关闭而且还会报错。
我不知道是不是设计成这样。那点取消该如何关闭弹窗
<img width="793" alt="截屏2023-05-09 14 16 47" src="https://user-images.githubusercontent.com/87531560/237010142-655fbd7a-447d-429d-b18a-55f0db10bdf8.png">

### 重现步骤

点击屏幕，点击取消无法关闭

### 设备/浏览器

微信开发者工具，真机调试

**Comment by johnsonwong666** [comment]
预览使用的是vant2，这部分文档预览有误。在你异步方法返回false的地方手动调用Dialog.close()关闭弹窗

**Comment by Detco** [comment]
手动调用确实可以关闭，但是因为close函数需要一个参数action，如果不传会导致报错，这里的action应该传什么。
<img width="415" alt="截屏2023-05-10 16 47 00" src="https://github.com/youzan/vant-weapp/assets/87531560/1cffe143-041b-4c85-831a-6ae82cfbdc21">
<img width="792" alt="截屏2023-05-10 16 47 15" src="https://github.com/youzan/vant-weapp/assets/87531560/475cb5db-5ee3-4a7a-b66d-e50d3f9d27ed">

**Comment by johnsonwong666** [comment]
> 手动调用确实可以关闭，但是因为close函数需要一个参数action，如果不传会导致报错，这里的action应该传什么。 <img alt="截屏2023-05-10 16 47 00" width="415" src="https://user-images.githubusercontent.com/87531560/237333169-1cffe143-041b-4c85-831a-6ae82cfbdc21.png"> <img alt="截屏2023-05-10 16 47 15" width="792" src="https://user-images.githubusercontent.com/87531560/237332626-475cb5db-5ee3-4a7a-b66d-e50d3f9d27ed.png">

这里有点问题，应该需要判断一下

**Comment by Detco** [comment]
我建议对微信小程序dialog异步关闭这部分的使用文档增加“说明”。

**Comment by Detco** [comment]
希望文档上能够将微信小程序的dialog使用说明补充上去，避免其他人使用出现问题

**Comment by mxluomx** [comment]
我也遇到这个问题了，关闭的时候报MiniProgramError这个错，怎么解决的呢

**Comment by mxluomx** [comment]
> > 手动调用确实可以关闭，但是因为close函数需要一个参数action，如果不传会导致报错，这里的action应该传什么。 <img alt="截屏2023-05-10 16 47 00" width="415" src="https://user-images.githubusercontent.com/87531560/237333169-1cffe143-041b-4c85-831a-6ae82cfbdc21.png"> <img alt="截屏2023-05-10 16 47 15" width="792" src="https://user-images.githubusercontent.com/87531560/237332626-475cb5db-5ee3-4a7a-b66d-e50d3f9d27ed.png">
> 
> 这里有点问题，应该需要判断一下

怎么解决这个问题的呢
