### ISSUE TITLE
[Bug Report] field组件：type="textarea"时，开发者工具中呈现placeholder样式有误

### ISSUE THREAD

**Issue by Xlucidator** [youzan/vant-weapp#5367]
### 重现链接

（感觉没必要片段了)

```html
<van-field
    label="体验期望"
    clearable autosize
    type="textarea"
    model:value="{{ expectValue }}"
    placeholder="简述您心中理想的计划"
 />
```

### Vant Weapp 版本

1.10.16

### 描述一下你遇到的问题。

使用field组件，type="textarea"时会出现此显示问题

![image](https://github.com/youzan/vant-weapp/assets/70893377/aead0787-58af-4bc4-b27a-16d46dbbd21d)

输入一些内容后删除，样式恢复正常

![image](https://github.com/youzan/vant-weapp/assets/70893377/cea172ce-d7cb-4b80-bd5f-011b82074f45)

此问题仅存在于微信开发者工具调试时，真机调试似乎没问题，所以不确定是不是vant的问题（）

### 重现步骤

开发者工具调试加载即可

### 设备/浏览器

微信开发者工具（个人的是Stable 1.06.2303060）

**Comment by Xlucidator** [comment]
（没细看组件的代码啊，误会的话就非常抱歉）

**Comment by johnsonwong666** [comment]
<img width="1407" alt="image" src="https://github.com/youzan/vant-weapp/assets/64689255/e3160b9c-5048-4cab-86df-2dc75d7725df">

配合popup 真机和模拟器没有复现  
官方有类似的问题 https://developers.weixin.qq.com/community/develop/doc/000c66e9c0ced83e104def3705b400?highLine=placeholder%2520%25E9%2597%25AE%25E9%25A2%2598

**Comment by Xlucidator** [comment]
哦哦多谢！（那估计就是<textarea>相关问题了

**Comment by runtop** [comment]
遇到相同问题，应该不是textarea的问题，是popup的transition动画的处理可能有问题，把popup中的wx:if="{{ inited }} 这个动态渲染改为 hidden="{{ !inited }}"   就可以了，应该动态节点处理上没完善好
@johnsonwong666
