### ISSUE TITLE
[Feature Request] 建议为steps增加插槽功能

### ISSUE THREAD

**Issue by Detco** [youzan/vant-weapp#5368]
### 这个功能解决了什么问题？

vant在小程序的组件库很常用，某些情况下如果支持插槽作用将会方便很多，希望可以考虑一下。

### 你期望的 API 是什么样子的？

步骤条内部的内容只能有标题和内容，限制的太死了，某些情况下需要显示图片或者复杂布局的时候，就非常不适合。如果可以将内容插槽话就会方便很多

**Comment by Xlucidator** [comment]
确实，急用，自己再造轮子有点慢（#4555 好像很早就有人提了）

**Comment by landluck** [comment]
目前的实现很难做内容插槽，需要完全重构后才可以，会在 2.x 版本中实现
