### ISSUE TITLE
vant-uploader上传照片无法删除

### ISSUE THREAD

**Issue by kancsdf** [youzan/vant-weapp#5369]
### 重现链接

      <van-uploader file-list="{{ fileList }}" max-count="2" deletable="{{ true }}" bind:after-read="afterRead"/>

### Vant Weapp 版本

1.10.17

### 描述一下你遇到的问题。

vant-uploader上传照片无法删除 设置了deletable="{{ true }}"也一样

### 重现步骤

无

**Comment by johnsonwong666** [comment]
需要绑定delete事件  bind:delete="delete"  回调参数event可以获取到要删除的索引，再操作一下fileList
