### ISSUE TITLE
icon 只有加号 +  ，  没有减号

### ISSUE THREAD

**Issue by CaserLee** [youzan/vant-weapp#537]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**你需要的功能是？**
icon增加 减号

购物车页面中，数量应当是可加可减的，组件不提供 减号icon 很尴尬。
请开发组考虑添加，谢谢。

**Comment by chenjiahan** [comment]
暂时没计划提供减号图标，步进器可以直接覆盖样式
