### ISSUE TITLE
使用TS开发，但是不知道event事件的类型

### ISSUE THREAD

**Issue by suzhenghui-sky** [youzan/vant-weapp#5371]
### 重现链接

没有

### Vant Weapp 版本

    "@vant/weapp": "^1.10.18"

### 描述一下你遇到的问题。

事件的event无法知晓类型；
![图片](https://github.com/youzan/vant-weapp/assets/48371536/28fb764e-03b9-446d-a7ad-1814b924b55e)

### 重现步骤

不需要

### 设备/浏览器

我在微信小程序上

**Comment by landluck** [comment]
目前没有这块的 ts 能力，可以写自己写个 interface 指定一下类型，后续考虑在 2.x 版本导出所有 ts 类型
