### ISSUE TITLE
关于van-field绑定值类型的问题

### ISSUE THREAD

**Issue by suzhenghui-sky** [youzan/vant-weapp#5374]
### 重现链接

没有。

### Vant Weapp 版本

 "@vant/weapp": "^1.10.16",

### 描述一下你遇到的问题。

  <van-field value="{{ bo.name }}" label=""  /> 我传入的值为bo.name = ''，控制警告。
![图片](https://github.com/youzan/vant-weapp/assets/48371536/5e1524d0-ce16-4eec-867d-edde21e2adbd)

### 重现步骤

没有。

### 设备/浏览器

微信小程序开发工具

**Comment by landluck** [comment]
提供一段简易的代码吧

**Comment by suzhenghui-sky** [comment]
@landluck https://gitee.com/jyjyjy28/vant-demo.git

**Comment by suzhenghui-sky** [comment]
@landluck https://gitee.com/jyjyjy28/vant-demo.git

**Comment by suzhenghui-sky** [comment]
@landluck  请问是bug吗？还是说其他问题。

**Comment by fanburger** [comment]
根据您提供的代码并没有复现bug，能不能直接提供有效的小程序代码片段呢，如果开发者工具提示代码体积超过1024kb的话可以将node_modules和miniprogram_npm这两个目录删除之后再分享。

**Comment by suzhenghui-sky** [comment]
https://developers.weixin.qq.com/s/qHsC8omS7aIo 微信小程序的片段。@fanburger

**Comment by fanburger** [comment]
> https://developers.weixin.qq.com/s/qHsC8omS7aIo 微信小程序的片段。@fanburger

这个不是bug，如果你不想看到这个警告的话可以在组件data里面添加一个计算属性同名的属性，比如computed中有一个sum，那你就在data里面也添加一个sum属性
![image](https://github.com/youzan/vant-weapp/assets/101820556/a748f3e3-57c3-4e1f-8cfe-35617a689b15)

**Comment by suzhenghui-sky** [comment]
这不是相当于有两个相同的属性？不会冲突嘛？@fanburger

**Comment by fanburger** [comment]
> 这不是相当于有两个相同的属性？不会冲突嘛？@fanburger

不会冲突呀，你看一下 `miniprogram-computed` 的文档，
https://github.com/wechat-miniprogram/computed#typescript-%E6%94%AF%E6%8C%81

**Comment by suzhenghui-sky** [comment]
> > 这不是相当于有两个相同的属性？不会冲突嘛？@fanburger
> 
> 不会冲突呀，你看一下 `miniprogram-computed` 的文档， https://github.com/wechat-miniprogram/computed#typescript-%E6%94%AF%E6%8C%81

好的，之前没有看清。
