### ISSUE TITLE
IOS上使用异常。van-action-sheet组件内嵌van-search组件时，输入框占位符变白色

### ISSUE THREAD

**Issue by zhangyuhong1** [youzan/vant-weapp#5375]
### 重现链接

<van-action-sheet show="{{ show }}" title="标题">
       <van-search value="{{ value }}" placeholder="请输入搜索关键词" />
</van-action-sheet>

### Vant Weapp 版本

1.10.4

### 描述一下你遇到的问题。

van-action-sheet组件内嵌van-search组件时，输入框占位符变白色

### 重现步骤

输入框占位符初始的时候颜色是正常的，看的出字颜色是由灰色变成白色的

### 设备/浏览器

ios

**Comment by johnsonwong666** [comment]
手上的ios测试机没有复现，你是什么设备，提供一个小程序代码片段来看一下
