### ISSUE TITLE
van-field 设置maxlength后，键盘上中文输入法每输入一个字母就算一个字符，输入满8个就不允许输入了，其实我要的是汉字

### ISSUE THREAD

**Issue by dreamsnail** [youzan/vant-weapp#5376]
### 重现链接

 <van-field name="name" value="{{ xx}}" label="名称" title-width="4.4em" placeholder="如，名称" maxlength="8" show-word-limit required  />

### Vant Weapp 版本

1.10.12

### 描述一下你遇到的问题。

 <van-field name="name" value="{{ xx}}" label="名称" title-width="4.4em" placeholder="如，名称" maxlength="8" show-word-limit required  />
van-field 设置maxlength后，键盘上中文输入法每输入一个字母就算一个字符，输入满8个就不允许输入了，其实我要的是汉字

### 重现步骤

中文输入法

**Comment by johnsonwong666** [comment]
一个字母算一个字数是合理的，你可以自己做input/change事件的监控，对你的输入进行过滤等。

**Comment by landluck** [comment]
说下手机型号以及使用的输入法的情况吧，最近这里有改动

**Comment by dreamsnail** [comment]
> 

iphone14 苹果自带输入法，我试了安卓机型也是这样的

**Comment by dreamsnail** [comment]
> 一个字母算一个字数是合理的，你可以自己做input/change事件的监控，对你的输入进行过滤等。

用户还在输入，还没有写到input的界面上

**Comment by dreamsnail** [comment]
> 说下手机型号以及使用的输入法的情况吧，最近这里有改动

iphone14 苹果自带输入法，我试了安卓机型也是这样的

**Comment by landluck** [comment]
会在这周修复

**Comment by landluck** [comment]
> > 说下手机型号以及使用的输入法的情况吧，最近这里有改动
> 
> iphone14 苹果自带输入法，我试了安卓机型也是这样的

确认了一下微信原生 input 在使用 maxlength 时表现和组件库一致 @johnsonwong666 说的是合理的，只能自行通过 change 来过滤
