### ISSUE TITLE
Cascader动态添加数据不显示

### ISSUE THREAD

**Issue by Biswangluo** [youzan/vant-weapp#5379]
### 重现链接

  <van-popup  show="{{isAddressShow}}" round position="bottom" >
        <block wx:if="{{isAddressShow}}">
        
            <van-cascader field-names="{{fieldNames}}"  active-color="#07c160" value="{{address}}" title="请选择所在地区" options="{{addressList}}" bind:close="onClose" bind:finish="onFinish" bind:change="onChange" ></van-cascader>
        </block>
    </van-popup>

    getArea(id) {
        let that=this
        let params = {
            id: id
        }
        apiJs.getArea(params).then(data => {
            data.forEach(item => {
                item.children = []
                item.id = item.ID.toString()
            });

            if (id != 0) {
                let index = that.data.addressList.findIndex(item => item.ID == id)
                console.log(index)
                    this.setData({
                        [`addressList[${index}].children`]:data
                     })
                console.log(this.data.addressList[index])
                console.log(this.data.addressList[index].children)
            } else {
                this.setData({
                    addressList:data
                 })
                 this.setData({
                    'addressList[0].children': [],
                  })
            }
        })
    },

### Vant Weapp 版本

1.10.18

### 描述一下你遇到的问题。

使用官方示例可以正常显示数据 但是切换到动态获取 无法显示数据 已确定数据正常 已经添加进去
![微信截图_20230516161119](https://github.com/youzan/vant-weapp/assets/2362450/00dd7afc-0cfe-4c8c-bf07-a4e2b3c9e9b6)

### 重现步骤

本地数据没有问题 如果用网络数据 在onChange 回调请求网络 不显示

**Comment by Biswangluo** [comment]
1.模拟生成地址数据
onLoad里面模拟生成数据
`let _options =[]
    _options.push({
        "ID": 120000,
        "ShortName": "天津",
        "children": []
    })
    _options.push({
        "ID": 130000,
        "ShortName": "河北",
        "children": []
    })

    this.setData({
        addressList:_options
     })
`
2.模拟onChange回调塞进去点数据
`onChange(e) {
        const {
            value
        } = e.detail;
        //this.getArea(value)
        const children = [
            { ShortName: '杭州市', ID: 330100 },
            { ShortName: '宁波市', ID: 330200 },
          ];
          this.setData({
              'addressList[0].children':children
           })`

3.结论 经过反复测试 如果在data里面有数据情况下 onChange怎么添加数据都没问题 如果从接口回来的数据 通过setData放进去 onChange 怎么添加都不会显示的 经过模拟 先[]在往里放数据进去 就会失效不知道问题出在何处？
求解答

**Comment by Biswangluo** [comment]
1.模拟生成地址数据
onLoad里面模拟生成数据
`let _options =[]
    _options.push({
        "ID": 120000,
        "ShortName": "天津",
        "children": []
    })
    _options.push({
        "ID": 130000,
        "ShortName": "河北",
        "children": []
    })

    this.setData({
        addressList:_options
     })
`
2.模拟onChange回调塞进去点数据
`onChange(e) {
        const {
            value
        } = e.detail;
        //this.getArea(value)
        const children = [
            { ShortName: '杭州市', ID: 330100 },
            { ShortName: '宁波市', ID: 330200 },
          ];
          this.setData({
              'addressList[0].children':children
           })`

3.结论 经过反复测试 如果在data里面有数据情况下 onChange怎么添加数据都没问题 如果从接口回来的数据 通过setData放进去 onChange 怎么添加都不会显示的 经过模拟 先[]在往里放数据进去 就会失效不知道问题出在何处？
求解答

**Comment by landluck** [comment]
`v1.10.19` 版本已修复
