### ISSUE TITLE
field 组件不能传递 custom-class 无法修改内部样式

### ISSUE THREAD

**Issue by qiphon** [youzan/vant-weapp#5383]
### 这个功能解决了什么问题？

![image](https://github.com/youzan/vant-weapp/assets/24565078/014c0b30-eb2a-4e1b-9be0-2dd0d1aaceb1)

### 你期望的 API 是什么样子的？

![image](https://github.com/youzan/vant-weapp/assets/24565078/1d29d457-629b-499b-bfdf-c0231e432785)

**Comment by johnsonwong666** [comment]
field组件目前提供以下外部样式类，暂不支持custom-class。
<img width="805" alt="image" src="https://github.com/youzan/vant-weapp/assets/64689255/ad22dbfd-f60a-404e-8db6-75c119d19c3d">

**Comment by johnsonwong666** [comment]
可以先尝试使用custom-style 去修改van-cell的样式

**Comment by landluck** [comment]
`v1.10.21` 已支持
