### ISSUE TITLE
Calendar 选择日期区间问题

### ISSUE THREAD

**Issue by JORYA-liu** [youzan/vant-weapp#5384]
### 重现链接

    <van-calendar
    show="{{ showCalendar }}"
    type="range"
    color="#106745"
    default-date="{{ timestamp }}"
    min-date="{{ minDate }}"
    max-date="{{ maxDate }}"
    formatter="{{ formatter }}"
    allow-same-day="{{ true }}"
    bind:close="hideCalendarFun"
    bind:confirm="calendarConfirm"
    />

### Vant Weapp 版本

1.10.18

### 描述一下你遇到的问题。

我现在选择日期最小值是2023-03-14， 最大日期是2023-05-12， 我想选择日期区间，但是通过formatter设置可选日期列表为["2023-03-14", "2023-03-15", "2023-03-16", "2023-04-28", "2023-05-05", "2023-05-11", "2023-05-12"]，我现在选择日期开始时间和结束时间为2023-03-14，2023-05-12，在理想情况下应该是选择此区间，但是日历会自动选择2023-03-14到2023-03-16这两个日期区间

### 重现步骤

显示日历选择，选择日期

### 设备/浏览器

安卓系统，iOS系统

**Comment by johnsonwong666** [comment]
可以提供一下复现代码片段吗？你的formatter是怎么写的

**Comment by johnsonwong666** [comment]
<img width="371" alt="image" src="https://github.com/youzan/vant-weapp/assets/64689255/fd52b9f8-738c-4863-92f0-5b903aab3b1a">
<img width="304" alt="image" src="https://github.com/youzan/vant-weapp/assets/64689255/3918775f-39cf-41a0-be55-2f6a788f72a4">
是否有传defaultDate呢？ 按照你的业务场景传入一个数组
