### ISSUE TITLE
[Bug Report] checkbox-group selected 默认值设置有误

### ISSUE THREAD

**Issue by maxthonl** [youzan/vant-weapp#5388]
### 重现链接

假设我有数据源 
``` json
{
  data: {
    employees: [
      {id: 3, name: '张三'}, 
      {id: 6, name: '李四'}, 
      {id: 9, name: '王五'}
    ], 
    selected: [3]
  }
}
```
``` wxml
<van-checkbox-group value="{{selected}}" bind:change="onChange" >
  <van-cell-group wx:for="{{employees}}" wx:key="id" wx:for-item="item">
    <van-cell clickable data-id="{{item.id}}" data-name="{{item.name}}" bind:click="onCheckboxCellClick">
      <view slot="title">{{item.name}} - {{item.id}}</view>
      <van-checkbox catch:tap="noop" slot="right-icon" id="cb-employee-{{item.id}}" name="{{item.id}}"/>
    </van-cell>
  </van-cell-group>
</van-checkbox-group>
```

### Vant Weapp 版本

1.10.18

### 描述一下你遇到的问题。

Page中的默认值没办法显示出来。目测是因为数据类型不匹配的原因，我把selected 换成 `["3"]` 即可.

这是我截取的 checkbox-group 中的一段代码， 蓝色部分是我本地的修复 `name: null` 
![image](https://github.com/youzan/vant-weapp/assets/24982504/91473a75-ea36-4b1b-8c7b-a61c7c982b2e)

### 重现步骤

渲染时即可重现

**Comment by fanburger** [comment]
文档里面有说明checkbox中的name应该是string
![image](https://github.com/youzan/vant-weapp/assets/101820556/4383baba-925d-48c7-8e5d-cf847b401c39)

**Comment by maxthonl** [comment]
> 文档里面有说明checkbox中的name应该是string ![image](https://user-images.githubusercontent.com/101820556/239911661-4383baba-925d-48c7-8e5d-cf847b401c39.png)



> 

的确是这样的， 是我没有看清楚， 真不好意思。但是建议支持其他类型的， 想象一下，我提供的场景，这个场景还是蛮常见的，如果仅仅支持string的话， 项目中就会多一些奇怪的转换，而这个转换只有查看文档才明白为啥要做这个转换。 另外什么理由导致该属性必须是string类型？

**Comment by landluck** [comment]
> > 文档里面有说明checkbox中的name应该是string ![image](https://user-images.githubusercontent.com/101820556/239911661-4383baba-925d-48c7-8e5d-cf847b401c39.png)
> 
> > 
> 
> 的确是这样的， 是我没有看清楚， 真不好意思。但是建议支持其他类型的， 想象一下，我提供的场景，这个场景还是蛮常见的，如果仅仅支持string的话， 项目中就会多一些奇怪的转换，而这个转换只有查看文档才明白为啥要做这个转换。 另外什么理由导致该属性必须是string类型？

常规情况下，表单的 name 属性都会是 string，例如原生 input，所以暂时不会考虑支持别的类型。
