### ISSUE TITLE
vant 引入 Toast失败

### ISSUE THREAD

**Issue by guozefan** [youzan/vant-weapp#5390]
### 重现链接

// pages.json
"usingComponents": {
      "van-button": "/wxcomponents/vant/button/index",
      "van-checkbox": "/wxcomponents/vant/checkbox/index",
      "van-checkbox-group": "/wxcomponents/vant/checkbox-group/index",
      "van-popup": "/wxcomponents/vant/popup/index",
      "van-toast":"/wxcomponents/vant/toast/index"
    }

// components/ xxx.vue

<template>
           <view> <van-toast id="van-toast" /></view
</template>
<script setup lang="ts">
import Toast from '@/wxcomponents/vant/toast/toast'
 Toast.fail('失败文案')
</script>

### Vant Weapp 版本

1.10.18

### 描述一下你遇到的问题。

引用报错：module 'wxcomponents/vant/toast/toast.js' is not defined, require args is '../../../wxcomponents/vant/toast/toast.js'
或者：未找到 van-toast 节点，请确认 selector 及 context 是否正确
环境是vue：3.3.4  使用vue-setup语法

### 重现步骤

1、组件引入报错
2、const handleAuthorized = () => {
   Toast.fail('失败文案')
}
3、2步骤后报错 ：未找到 van-toast 节点，请确认 selector 及 context 是否正确

**Comment by guozefan** [comment]
其他组件引用正常

**Comment by johnsonwong666** [comment]
在什么平台开发的呢？vant-weapp目前支持的是原生小程序开发。

**Comment by johnsonwong666** [comment]
请将issue提至对应平台下，目前暂不会处理其他平台出现的问题。
