### ISSUE TITLE
[Feature Request] Calendar 日历不设置默认值

### ISSUE THREAD

**Issue by PlayerYK** [youzan/vant-weapp#5392]
### 这个功能解决了什么问题？

Calendar 日历的 `default-date`  默认值是今天，这就导致日历的默认状态可能有两种情况：
1. **今天的日期不可选**时，今天不会选中;
2. **今天的日期可选**时，今天被选中。

如果可以不设置默认值，打开的日历就可以有唯一确定的状态。

### 你期望的 API 是什么样子的？

支持不设置默认时间

 `default-date="{{null}}"`

**Comment by PlayerYK** [comment]
隔壁 vant 已经支持这个特性 https://github.com/youzan/vant/issues/7013

**Comment by johnsonwong666** [comment]
打开的日历就可以有唯一确定的状态这个可以再描述具体一点吗？

**Comment by PlayerYK** [comment]
> 打开的日历就可以有唯一确定的状态这个可以再描述具体一点吗？

多谢回复，想要的效果是：不默认选中一个日期。

这样的好处就是，用户必须选择一个日期，才能进行下一步的动作。

设置 `poppable="{{ false }}"`、`show-confirm="{{ false }}"`，也就是直接在页面展示，不使用弹窗。此时只能通过 `confirm`或`select` 事件获取组件中用户选中的值。

**Comment by landluck** [comment]
`v1.10.21` 已支持
