### ISSUE TITLE
[Feature Request] 希望Field能扩大点击区域，特别是errorMsg出现的时候

### ISSUE THREAD

**Issue by p2227** [youzan/vant-weapp#5393]
### 这个功能解决了什么问题？

![image](https://github.com/youzan/vant-weapp/assets/4214942/1ab73c74-ff1e-4ab3-a762-f79f2428ab30)

我希望Field中，点击如图所示的整片高亮区域都能使得input获得焦点，尤其是当field出现errormsg的时候，一个可能的实现方式是利用官方的label控件

https://developers.weixin.qq.com/miniprogram/dev/component/label.html

### 你期望的 API 是什么样子的？

```xml
<van-field focusable />
```

一个可能的实现方式是利用官方的label控件

https://developers.weixin.qq.com/miniprogram/dev/component/label.html

**Comment by buaazyl** [comment]
支持，现在需要点最左侧才能触发输入，有时候需要点几次才能拉起键盘

**Comment by landluck** [comment]
`v1.10.21` 已支持 `name` 属性扩大点击区域

**Comment by buaazyl** [comment]
<img width="375" alt="image" src="https://github.com/youzan/vant-weapp/assets/28683081/333faf7e-83d6-42a3-a6d4-412530bead87">

error-message之前是靠左的，和输入内容对齐了，现在是改为靠右了？设置error-message-align似乎不生效

**Comment by landluck** [comment]
> <img alt="image" width="375" src="https://user-images.githubusercontent.com/28683081/252543226-333faf7e-83d6-42a3-a6d4-412530bead87.png">
> error-message之前是靠左的，和输入内容对齐了，现在是改为靠右了？设置error-message-align似乎不生效

好的，我们在看看

**Comment by landluck** [comment]
的确有这个问题，下个版本修复一下
