### ISSUE TITLE
在 app.wxss 中引入内置样式

### ISSUE THREAD

**Issue by 624385062** [youzan/vant-weapp#5394]
### 重现链接

在 app.wxss 中引入内置样式 @import "/miniprogram_npm/@vant/weapp/common/index.wxss";  总是报错  构建npm也是成功的啊  怎们办求解

### Vant Weapp 版本

1.06

### 描述一下你遇到的问题。

在 app.wxss 中引入内置样式 @import "/miniprogram_npm/@vant/weapp/common/index.wxss";  总是报错  构建npm也是成功的啊  怎们办求解

### 重现步骤

在 app.wxss 中引入内置样式 @import "/miniprogram_npm/@vant/weapp/common/index.wxss";  总是报错  构建npm也是成功的啊  怎们办求解

**Comment by johnsonwong666** [comment]
报什么错误，可以提供一下小程序代码片段吗？

**Comment by 624385062** [comment]
就是显示文件不存在

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by johnsonwong666** [comment]
<img width="1245" alt="image" src="https://github.com/youzan/vant-weapp/assets/64689255/702cb191-6a84-4980-a3fe-2a2378147030">

<img width="1245" alt="image" src="https://github.com/youzan/vant-weapp/assets/64689255/03d55b85-8228-43f3-9247-4cb3b6da2b30">
@624385062 

重新构建npm成功了吗？ 我测试了一下，看样式是正常引入的。

**Comment by 624385062** [comment]
可以了  谢谢 你是开发者吗  后续我有什么不懂的可以直接通过邮箱
发给你吗

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2023年5月26日 11:20
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [youzan/vant-weapp] 在 app.wxss 中引入内置样式 (Issue #5394)

[image]<https://user-images.githubusercontent.com/64689255/241110127-702cb191-6a84-4980-a3fe-2a2378147030.png>[image]<https://user-images.githubusercontent.com/64689255/241110008-fa9b2cc5-b162-49ee-8920-b8bd84a4b192.png>

重新构建npm成功了吗？ 我测试了一下，看样式是正常引入的。

―

**Comment by johnsonwong666** [comment]
> 

直接发起issue即可
