### ISSUE TITLE
vant Weapp的NoticeBar（通告栏）组件怎么设置垂直滚动？

### ISSUE THREAD

**Issue by 624385062** [youzan/vant-weapp#5396]
### 这个功能解决了什么问题？

vant Weapp的NoticeBar（通告栏）组件怎么设置垂直滚动？

### 你期望的 API 是什么样子的？

vant Weapp的NoticeBar（通告栏）组件怎么设置垂直滚动？ 

<van-notice-bar style="position: relative; left: 0rpx; top: -153rpx"
 wrapable
 height="100%"
 left-icon="volume-o" 
 scrollable="false"
 color="#1989fa"
 backgroundColor="#fff"
 left-icon="volume-o"
 text="{{ text }}"
 speed="{{70}}"
 scrollable="{{ false }}"
 text="有的时候难过的不是结局不够好，而是真诚没有被善待。组件怎么设置垂直滚动？

**Comment by landluck** [comment]
目前不支持垂直滚动哦，会在 2.x 中进行支持
