### ISSUE TITLE
DatetimePicker 时间选择选项过滤器默认选择时不是当前选项显示的值

### ISSUE THREAD

**Issue by changzhengithub** [youzan/vant-weapp#5401]
### 重现链接

https://vant-contrib.gitee.io/vant-weapp/#/datetime-picker

### Vant Weapp 版本

1.10.19

### 描述一下你遇到的问题。

![image](https://github.com/youzan/vant-weapp/assets/35087343/0ab45ec5-7b26-4a60-b1c6-1bbeba6fdf2c)
如图设置了分钟过滤选项为30分钟，第一次打开默认显示30分钟，实际时间还不到30分钟，但如果直接点确认，所选择的时间为当前时间，而不是上面显示的30。

### 重现步骤

1、设置分钟选项过滤为30分钟
2、直接打开点击确认获取当前值

**Comment by johnsonwong666** [comment]
好像没有复现。可以提供一个小程序代码片段过来吗？
<img width="1286" alt="image" src="https://github.com/youzan/vant-weapp/assets/64689255/b9c13351-07bf-43db-969b-5db15c536776">
