### ISSUE TITLE
Vant Weapp2.x希望在icon组件中适配黑暗模式

### ISSUE THREAD

**Issue by yik7707** [youzan/vant-weapp#5402]
### 这个功能解决了什么问题？

能够解决icon的黑暗模式情况，例如黑色icon在黑暗模式下，增加一个黑暗模式的属性赋值icon名称就可以适配黑暗模式的图标

### 你期望的 API 是什么样子的？
<van-icon class-prefix="iconfont" name="{{icon}}" dark-name=“{{dark-icon}}” />
希望增加dark-icon属性

**Comment by yik7707** [comment]
<van-icon class-prefix="iconfont" name="{{icon}}" dark-name=“{{dark-icon}}” />

**Comment by yik7707** [comment]
<van-icon class-prefix="iconfont" name="{{icon}}" dark-name=“{{dark-icon}}” />

**Comment by landluck** [comment]
会支持
