### ISSUE TITLE
[Feature Request] 请在此填写标题van-tree-select 为啥只支持2级

### ISSUE THREAD

**Issue by Yuaao** [youzan/vant-weapp#5403]
### 这个功能解决了什么问题？

van-tree-select 可以支持多级吗？api也少，应该数据有多少级就支持多少级

### 你期望的 API 是什么样子的？

children: [{ text: '杭州市', value: '330100', children: [
      {
         text: '西湖区', value: '330101',
      },{
         text: '滨江区', value: '330102',
      },{
         text: '拱墅区', value: '330103',
      },{
         text: '萧山', value: '330103',
      },
    ]}

**Comment by landluck** [comment]
目前多少级数据就支持多少级选择的，如有疑问可以提供个小程序代码片段协助排查

**Comment by Yuaao** [comment]
你们排查一下吧，目前就是只支持2 级，多一级children 都不渲染
------------------------------------------------------------------
发件人：landluck ***@***.***>
发送时间：2023年6月2日(星期五) 10:11
收件人：youzan/vant-weapp ***@***.***>
抄　送：瑜 ***@***.***>; Author ***@***.***>
主　题：Re: [youzan/vant-weapp] [Feature Request] 请在此填写标题van-tree-select 为啥只支持2级 (Issue #5403)
目前多少级数据就支持多少级选择的，如有疑问可以提供个小程序代码片段协助排查
