### ISSUE TITLE
[Bug Report] 给van-collapse-item设定background-image无效

### ISSUE THREAD

**Issue by levscaut** [youzan/vant-weapp#5404]
### 重现链接

```html
<van-collapse value="{{activeNames}}" bind:change="onChange">
<van-collapse-item wx:for="{{displayInfo}}" class="raid-info-item" style="background-image: url('/path/to/image');">
<!--display some detailed info here-->
  </van-collapse-item>
</van-collapse>
```

### Vant Weapp 版本

1.10.18

### 描述一下你遇到的问题。

给van-collapse-item设定background-image无效，无法显示出背景图片。也许我不该提一个bug的issue，但是我找了很久还是没找到给van-collapse的列表项设置背景图片的方法，希望能获得一些帮助，感谢！

### 重现步骤

运行代码即可

**Comment by johnsonwong666** [comment]
![image](https://github.com/youzan/vant-weapp/assets/64689255/714d2da4-5f29-4617-90b5-909089371798)
![image](https://github.com/youzan/vant-weapp/assets/64689255/66dd6c8f-4761-4a80-ac28-9c30c15a8fad)

尝试使用content-class

**Comment by levscaut** [comment]
> ![image](https://user-images.githubusercontent.com/64689255/242152670-714d2da4-5f29-4617-90b5-909089371798.png) ![image](https://user-images.githubusercontent.com/64689255/242152861-66dd6c8f-4761-4a80-ac28-9c30c15a8fad.png)
> 
> 尝试使用content-class

感谢解答。用您的方式确实可以实现，我试了一下对于van-collapse-item__title也可以，但是我想要是van-collapse-item这个类设置bg image，比如图上包含“标题1”的那一整条，但我试了一下用这种方式还是不行。

**Comment by johnsonwong666** [comment]
![image](https://github.com/youzan/vant-weapp/assets/64689255/159b94ac-e088-485e-b26d-c7db5b9c9d66)
<img width="343" alt="image" src="https://github.com/youzan/vant-weapp/assets/64689255/89f81ee7-42cf-4207-a8a1-fd8def99e86b">

看了下源码 你可以传一个title-class 但是整行不能覆盖 他是van-cell 组件 可能需要再定义自定义样式类

**Comment by levscaut** [comment]
> ![image](https://user-images.githubusercontent.com/64689255/242536170-159b94ac-e088-485e-b26d-c7db5b9c9d66.png) <img alt="image" width="343" src="https://user-images.githubusercontent.com/64689255/242536294-89f81ee7-42cf-4207-a8a1-fd8def99e86b.png">
> 
> 看了下源码 你可以传一个title-class 但是整行不能覆盖 他是van-cell 组件 可能需要再定义自定义样式类

感谢！我之前也试过给van-cell设置背景图片，也是不太成功；现在只好还是用原生的view组件来搞了
