### ISSUE TITLE
[Bug Report] van-field 的值不能通过value prop修改

### ISSUE THREAD

**Issue by niki571** [youzan/vant-weapp#5405]
### 重现链接

```vue
<template>
  <view>
    <van-cell-group>
      <van-field label="名称" placeholder="请输入菜谱名称" :value="name" />
    </van-cell-group>
    <van-button type="primary" size="large" round block class="save-button" @click="save"
      >保存</van-button>
  </view>
</template>

<script setup lang="ts">
import { ref } from 'vue'

const name = ref('')

function save() {
  name.value = Math.random()
}
</script>
```

### Vant Weapp 版本

1.10.16

### 描述一下你遇到的问题。

在这个小demo中，我希望点击“保存按钮”，修改van-field的值，但是并没有。

在我看了源码之后把“:value”修改为“:innerValue”后，van-field的值修改成功。

但是在整个官方文档中 https://youzan.github.io/vant-weapp/#/field ，并没有指出innerValue这个props。我认为源码或者文档两者有其一需要修改，不然开发者会浪费很多时间在这个不符合直觉的bug上。

### 重现步骤

在这个小demo中，我希望点击“保存按钮”，修改van-field的值，但是并没有。

**Comment by johnsonwong666** [comment]
<img width="1221" alt="image" src="https://github.com/youzan/vant-weapp/assets/64689255/605eeda6-1e46-45a9-9186-722ce16dc6af">
<img width="1184" alt="image" src="https://github.com/youzan/vant-weapp/assets/64689255/7496133a-7ee0-44b0-b029-0308672337ea">
在微信小程序开发者工具上测试了一下，点击保存输入框的值是变了的。看你的代码应该不是在微信小程序开发者工具上运行的，可能编译过程中有其他处理导致的，目前不会解决其他平台使用的问题，请将issue提至对应平台下。

**Comment by niki571** [comment]
我是在微信小程序运行的，vue3你再试试 @johnsonwong666

**Comment by johnsonwong666** [comment]
> 我是在微信小程序运行的，vue3你再试试 @johnsonwong666

你这个是在uniaap或者其他平台上开发的吗？目前处理的微信开发者工具上原生语法产生的问题。

**Comment by mxluomx** [comment]
> > 我是在微信小程序运行的，vue3你再试试 @johnsonwong666
> 
> 你这个是在uniaap或者其他平台上开发的吗？目前处理的微信开发者工具上原生语法产生的问
我是在uniapp上开发的，按照楼主的方法改了就好了，希望文档中增加下说明

**Comment by GRCmade** [comment]
我使用 Uniapp 进行测试，能够触发保存的操作的。

<img width="2144" alt="Image" src="https://github.com/user-attachments/assets/1bd4918c-7703-4f64-83d7-07b2c38c4c99" />
