### ISSUE TITLE
[Bug Report] 微信小程序版  使用 typescript 支持下 /component.ts 引入文件提示文件不存在

### ISSUE THREAD

**Issue by Exclusive-gfj** [youzan/vant-weapp#5406]
### 重现链接

文件路径 packages/common/component.ts
![image](https://github.com/youzan/vant-weapp/assets/25816191/0eb8c97a-5ed3-4e21-81ea-943fa7f3ade4)

### Vant Weapp 版本

1.10.19

### 描述一下你遇到的问题。

vant-weapp 微信小程序版 1.10.19 使用 typescript 支持下 packages/common/component.ts ，头部引入的 import { VantComponentOptions } from 'definitions/index'; 代码貌似好像是不对的。编译后提示无法找到
![image](https://github.com/youzan/vant-weapp/assets/25816191/f1f23211-4615-4207-8246-7a8351707d95)

### 重现步骤

import { VantComponentOptions } from 'definitions/index'; 提示 definitions/index 文件不存在

**Comment by johnsonwong666** [comment]
<img width="787" alt="image" src="https://github.com/youzan/vant-weapp/assets/64689255/39ee2d4c-f850-4608-aa9b-53011330ba1c">

这一步进行了吗 如果不行 path改成这个 "paths": { "@vant/weapp/*": ["node_modules/@vant/weapp/dist/*"] },

**Comment by Exclusive-gfj** [comment]
> <img alt="image" width="787" src="https://user-images.githubusercontent.com/64689255/242503176-39ee2d4c-f850-4608-aa9b-53011330ba1c.png">
> 这一步进行了吗 如果不行 path改成这个 "paths": { "@vant/weapp/_": ["node_modules/@vant/weapp/dist/_"] },

先是按照文档上配置的不行。然后再按照修改的建议换了还是一样

![image](https://github.com/youzan/vant-weapp/assets/25816191/a5705c77-0516-4ea0-8f05-368927093aa5)
![image](https://github.com/youzan/vant-weapp/assets/25816191/979789b0-35e0-4e2b-affc-5de6ac19b421)

也试了重新 npm install 和用微信开发者工具 重新执行 “构建 npm”

**Comment by johnsonwong666** [comment]
应该与前面一个问题类似，先close。
