### ISSUE TITLE
[Bug Report] 微信小程序 使用 typescript 支持下 common/utils.d.ts 提示 node 不存在？

### ISSUE THREAD

**Issue by Exclusive-gfj** [youzan/vant-weapp#5407]
### 重现链接

https://github.com/youzan/vant-weapp/blob/dev/dist/common/utils.d.ts

### Vant Weapp 版本

1.10.19

### 描述一下你遇到的问题。

微信小程序 使用 typescript 支持下 common/utils.d.ts 提示 node 不存在，按照官方的教程 npm install 是否还需要别的安装？

### 重现步骤

微信小程序 使用 typescript 支持下 common/utils.d.ts 提示 node 不存在

**Comment by johnsonwong666** [comment]
你现在是什么场景？无法引入组件还是想要在某个文件引入 common/utils.d.ts？尝试重新构建一下npm？

**Comment by Exclusive-gfj** [comment]
> 你现在是什么场景？无法引入组文件还是想在某个文件引入common/utils.d.ts？试试重新构建一下npm？

就正常的微信小程序项目，用微信开发者工具打开项目的时候提示这个文件有错误要求进行修改，也用微信的开发者工具 多次重新 ”构建 npm”

**Comment by johnsonwong666** [comment]
提示 node 不存在?这个错误貌似没有见过？可以提供一个小程序代码片段过来吗？

**Comment by Exclusive-gfj** [comment]
![image](https://github.com/youzan/vant-weapp/assets/25816191/e3e9f69e-c7f3-47cc-b4d2-e6d47bf1d1f8)

**Comment by Exclusive-gfj** [comment]
> 提示 node 不存在?这个错误貌似没有见过？可以提供一个小程序代码片段过来吗？
一个空的项目。就引入了vant weapp 和 miniprogram-api-typings 打开项目就提示
![image](https://github.com/youzan/vant-weapp/assets/25816191/b83d2f7c-28f8-4756-bca6-da7c531d93eb)

**Comment by Exclusive-gfj** [comment]
> 提示 node 不存在?这个错误貌似没有见过？可以提供一个小程序代码片段过来吗？

一个空的项目。就引入了vant weapp 和 miniprogram-api-typings 打开项目就提示
![image](https://github.com/youzan/vant-weapp/assets/25816191/badc95e9-a6ea-46e7-a4b2-7b0aa3fd8f91)

**Comment by johnsonwong666** [comment]
<img width="813" alt="image" src="https://github.com/youzan/vant-weapp/assets/64689255/773a7a50-bb81-4363-8651-a25f4e5f1fc6">
这一步进行了吗 如果不行 path改成这个
 "paths": {
      "@vant/weapp/*": ["node_modules/@vant/weapp/dist/*"]
    },

**Comment by Exclusive-gfj** [comment]
> <img alt="image" width="813" src="https://user-images.githubusercontent.com/64689255/242463715-773a7a50-bb81-4363-8651-a25f4e5f1fc6.png"> 这一步进行了吗 如果不行 path改成这个 "paths": { "@vant/weapp/*": ["node_modules/@vant/weapp/dist/*"] },

先是按照文档上配置的不行。然后再按照修改的建议换了还是一样

![image](https://github.com/youzan/vant-weapp/assets/25816191/649743d4-aadf-48e1-b2b9-2f1f6d067332)
![image](https://github.com/youzan/vant-weapp/assets/25816191/6fe63224-1833-4e38-b3cb-1d70a4d46282)

也试了重新 npm install 和用微信开发者工具 重新执行 “构建 npm”

**Comment by johnsonwong666** [comment]
> > <img alt="image" width="813" src="https://user-images.githubusercontent.com/64689255/242463715-773a7a50-bb81-4363-8651-a25f4e5f1fc6.png"> 这一步进行了吗 如果不行 path改成这个 "paths": { "@vant/weapp/_": ["node_modules/@vant/weapp/dist/_"] },
> 
> 先是按照文档上配置的不行。然后再按照修改的建议换了还是一样
> 
> ![image](https://user-images.githubusercontent.com/25816191/242504180-649743d4-aadf-48e1-b2b9-2f1f6d067332.png) ![image](https://user-images.githubusercontent.com/25816191/242505366-6fe63224-1833-4e38-b3cb-1d70a4d46282.png)
> 
> 也试了重新 npm install 和用微信开发者工具 重新执行 “构建 npm”

把你新建的项目分享一下吧。

**Comment by Exclusive-gfj** [comment]
> 把你新建的项目分享一下吧。

https://github.com/Exclusive-gfj/miniprogram-2

目前我直接忽略这个错误不去处理。也可以使用组件，但不知道是否会影响部分功能？

**Comment by johnsonwong666** [comment]
> > 把你新建的项目分享一下吧。
> 
> https://github.com/Exclusive-gfj/miniprogram-2
> 
> 目前我直接忽略这个错误不去处理。也可以使用组件，但不知道是否会影响部分功能？

https://developers.weixin.qq.com/miniprogram/dev/devtools/minicode.html 根据这种形式分享一个小程序代码片段吧

**Comment by Exclusive-gfj** [comment]
> > 把你新建的项目分享一下吧。
> 
> https://github.com/Exclusive-gfj/miniprogram-2



> > > 把你新建的项目分享一下吧。
> > 
> > 
> > https://github.com/Exclusive-gfj/miniprogram-2
> > 目前我直接忽略这个错误不去处理。也可以使用组件，但不知道是否会影响部分功能？
> 
> https://developers.weixin.qq.com/miniprogram/dev/devtools/minicode.html 根据这种形式分享一个小程序代码片段吧

https://developers.weixin.qq.com/s/tK0y4Emg7pID

**Comment by johnsonwong666** [comment]
> > > 把你新建的项目分享一下吧。
> > 
> > 
> > https://github.com/Exclusive-gfj/miniprogram-2
> 
> > > > 把你新建的项目分享一下吧。
> > > 
> > > 
> > > https://github.com/Exclusive-gfj/miniprogram-2
> > > 目前我直接忽略这个错误不去处理。也可以使用组件，但不知道是否会影响部分功能？
> > 
> > 
> > https://developers.weixin.qq.com/miniprogram/dev/devtools/minicode.html 根据这种形式分享一个小程序代码片段吧
> 
> https://developers.weixin.qq.com/s/tK0y4Emg7pID

这个看起来是ts类型声明的问题，使用组件应该不会有影响。

**Comment by Exclusive-gfj** [comment]
> 这个看起来是ts类型声明的问题，使用组件应该不会有影响。

好的。有什么办法能处理下吗？虽然不影响使用，但毕竟是一个报错

**Comment by landluck** [comment]
解决办法：

1.  安装类型依赖：`yarn add --dev @types/node`
2. 配置 tsconfig.json `"typeRoots": ["./node_modules/@types"],`
