### ISSUE TITLE
Uploader 开发工具上正常 真机调试时ios点击上传图标无效，安卓点击上传图标弹出选择微信聊天中的图片

### ISSUE THREAD

**Issue by Jonas949** [youzan/vant-weapp#5408]
### 重现链接

<van-uploader max-size="10485760" accept="image,video" preview-size="100" multiple file-list="{{ fileList }}" bind:after-read="afterRead" />

### Vant Weapp 版本

1.10.18

### 描述一下你遇到的问题。

uploader组件，在开发者工具上正常的，图片视频都能传，但是真机调试的时候，ios设备点击上传没有任何反应，安卓设备（小米12）点击上传弹出微信聊天，选择一个微信聊天会出现聊天中所涉及到的图片。

### 重现步骤

uploader组件使用真机调试上传图片或者视频

**Comment by Jonas949** [comment]
调试基础库为：2.32.1

**Comment by Jonas949** [comment]
<img width="379" alt="1685605322468" src="https://github.com/youzan/vant-weapp/assets/54925213/d029d230-7deb-404b-9b1d-5af108fb378a">

**Comment by Jonas949** [comment]
<img width="464" alt="1685606014721" src="https://github.com/youzan/vant-weapp/assets/54925213/529b2a74-c29d-4fbb-b1d5-ea7f74b81adc">
排查发现只要加上accept="image,video"就会出现问题 删除accept="image,video"就可以正常选择

**Comment by johnsonwong666** [comment]
目前不支持这种逗号分隔的写法，推测是这里导致的问题。
<img width="661" alt="image" src="https://github.com/youzan/vant-weapp/assets/64689255/ca02dbc8-5cb8-4123-a94e-55d1d0d3a6b9">

**Comment by Jonas949** [comment]
> 目前不支持这种逗号分隔的写法，推测是这里导致的问题。 <img alt="image" width="661" src="https://user-images.githubusercontent.com/64689255/242548677-ca02dbc8-5cb8-4123-a94e-55d1d0d3a6b9.png">

那我要怎么设置可以选择多种类型的文件？

**Comment by johnsonwong666** [comment]
> > 目前不支持这种逗号分隔的写法，推测是这里导致的问题。 <img alt="image" width="661" src="https://user-images.githubusercontent.com/64689255/242548677-ca02dbc8-5cb8-4123-a94e-55d1d0d3a6b9.png">
> 
> 那我要怎么设置可以选择多种类型的文件？

目前只能用上面哪几个，这个需要开发一下。

**Comment by johnsonwong666** [comment]
accept 传入 media 试试 ， 刚看了下源码 传media 选择的是 image 和 video 应该可以满足你的场景

**Comment by Jonas949** [comment]
> media

ok 可以的
