### ISSUE TITLE
[BUG] Tab组件报错

### ISSUE THREAD

**Issue by GodStream** [youzan/vant-weapp#541]
**描述一下问题**
```
Uncaught (in promise) TypeError: Cannot read property 'width' of undefined
```

**截图**
![image](https://user-images.githubusercontent.com/23089466/45274627-e27d2780-b4ea-11e8-9320-294c724b68c8.png)

**环境**
 - 设备: 
 - 基础库版本:  2.2.5
 - Vant Weapp 版本: 0.3.0

**Comment by GodStream** [comment]
还有 0.3.1 版本npm上没有更新

**Comment by chenjiahan** [comment]
这个问题已经在 dev 分支修复，会在 0.3.2 版本发布
