### ISSUE TITLE
Calendar 日历组件怎么让它不显示本月过去的天数（比如今天6月12号，不显示12号之前的）

### ISSUE THREAD

**Issue by lllyyy** [youzan/vant-weapp#5411]
### 重现链接

Calendar 日历组件怎么让它不显示本月过去的天数（比如今天6月12号，不显示12号之前的）

### Vant Weapp 版本

1.10.19

### 描述一下你遇到的问题。

Calendar 日历组件怎么让它不显示本月过去的天数（比如今天6月12号，不显示12号之前的）

### 重现步骤

Calendar 日历组件怎么让它不显示本月过去的天数（比如今天6月12号，不显示12号之前的）

**Comment by landluck** [comment]
暂时不支持哦，目前默认当前日期前面的日期是不能选择的，但还是会展示
