### ISSUE TITLE
联想输入框下拉列表

### ISSUE THREAD

**Issue by yisirman** [youzan/vant-weapp#5412]
### 这个功能解决了什么问题？

实现边输入边加载下拉列表数据

### 你期望的 API 是什么样子的？

![image](https://github.com/youzan/vant-weapp/assets/15642586/400e0ade-e24e-411a-8d7e-c67dba177c04)

**Comment by landluck** [comment]
这种组件偏向于 B 端交互和体验，C端组件库暂时不会考虑支持类似的组件
