### ISSUE TITLE
Cascader选择器发送网络请求后，直接进入了第二级选择，而且第一级选择不见，级联的数据是没变的

### ISSUE THREAD

**Issue by chenyunlin1** [youzan/vant-weapp#5413]
### 重现链接

页面刷新前的选项和数据
![image](https://github.com/youzan/vant-weapp/assets/102886365/eba7c3ce-e3f9-4536-8cab-827c32027169)
![image](https://github.com/youzan/vant-weapp/assets/102886365/528eddd4-c3ff-4956-9e1c-ef0692b0e4bf)
页面刷新后的选择和数据，直接进去了最后一个选项的chirdren中
![image](https://github.com/youzan/vant-weapp/assets/102886365/17a0d39a-ed43-420f-a5d2-88b0a2140733)
![image](https://github.com/youzan/vant-weapp/assets/102886365/595fc8c0-a717-49e9-bb0e-2a8a18d9f746)

### Vant Weapp 版本

1.10.15

### 描述一下你遇到的问题。

Cascader选择器发送网络请求后，页面刷新后的选择和数据，直接进去了最后一个选项的chirdren中

### 重现步骤

先扫码发送网络请求，然后点开后，级联的数据没变，但直接进入了最后一项的children中

### 设备/浏览器

微信小程序

**Comment by chenyunlin1** [comment]
求大大们快点解决呀，我看代码是没有任何问题，急用

**Comment by landluck** [comment]
升级到新版本试试

**Comment by landluck** [comment]
> 求大大们快点解决呀，我看代码是没有任何问题，急用

升级到最新版本后试试，还有问题的话提供一个小程序代码片段，异步请求可以用 setTimeout 模拟

**Comment by Yuaao** [comment]
试试nextTick
