### ISSUE TITLE
[Feature Request] 建议增加宫格可以左右滑动

### ISSUE THREAD

**Issue by hihuangwei** [youzan/vant-weapp#5415]
### 这个功能解决了什么问题？

横向格数超过一定数量可以开启左右滑动

### 你期望的 API 是什么样子的？

横向格数超过一定数量可以开启左右滑动

**Comment by chenjiahan** [comment]
这种场景是不是直接结合 Swipe 组件和 Grid 组件来使用比较合适，而不是在 Grid 里面去实现

**Comment by hihuangwei** [comment]
> 这种场景是不是直接结合 Swipe 组件和 Grid 组件来使用比较合适，而不是在 Grid 里面去实现

TDesign 的实现是比较简单。正常页面显示4格，超出的部分希望可以开启横向滚动
https://tdesign.tencent.com/miniprogram/components/grid

**Comment by landluck** [comment]
grid 目前实现存在问题，需要在 2.0 重构后增加该功能
