### ISSUE TITLE
[Feature Request] 建议新增浮动按钮组件

### ISSUE THREAD

**Issue by hihuangwei** [youzan/vant-weapp#5416]
### 这个功能解决了什么问题？

用于新增操作等
![image](https://github.com/youzan/vant-weapp/assets/3166799/f0638a04-2159-4b66-bb80-cb7503cf19b3)

### 你期望的 API 是什么样子的？

Fab 悬浮按钮
https://tdesign.tencent.com/miniprogram/components/fab

**Comment by landluck** [comment]
2.x 版本支持
