### ISSUE TITLE
[Bug Report] Toast.loding()在调用clear后无法重新触发

### ISSUE THREAD

**Issue by wkz2003** [youzan/vant-weapp#5417]
### 重现链接

Toast.loading({
        duration: 1,
        forbidClick: true,
        message: 'test',
})

### Vant Weapp 版本

1.10.17

### 描述一下你遇到的问题。

Toast.loding()在调用clear后无法重新触发

### 重现步骤

给按钮绑定的点击事件里设置显示加载，加载显示完后第二次开始都无法显示

### 设备/浏览器

安卓真机，小程序模拟iphone5设备

**Comment by johnsonwong666** [comment]
试了一下没有复现，可以提供一个小程序代码片段过来吗？

**Comment by johnsonwong666** [comment]
没有复现。由于较长时间没有提供复现代码片段，此issue暂时关闭，若还有问题请提新的issue,并附带复现代码片段排查。
