### ISSUE TITLE
滑动picker中的选项会触发页面的下拉刷新

### ISSUE THREAD

**Issue by Zhaojjjjjj** [youzan/vant-weapp#5418]
### 重现链接

https://vant-contrib.gitee.io/vant-weapp/#/datetime-picker

### Vant Weapp 版本

1.10.19

### 描述一下你遇到的问题。

微信小程序页面设置允许下拉刷新以后，向下滑动DatetimePicker 中的选项时会触发页面的下拉刷新，开发者工具有问题，真机上最近几年的手机没事儿，很久以前的红米，小米会有这个问题

### 重现步骤

page设置允许下拉刷新
引用 DatetimePicker 时间选择器

### 设备/浏览器

开发者工具

**Comment by johnsonwong666** [comment]
可以提供一个小程序代码片段过来吗？测试了一下滚动过程中没有触发onPullDownRefreshs。

**Comment by johnsonwong666** [comment]
此issue暂时关闭，开启页面级滚动，可能有几率误触，如果picker滚动中稳定触发，请提供一个小程序代码片段过来排查。

**Comment by renji566** [comment]
> 此issue暂时关闭，开启页面级滚动，可能有几率误触，如果picker滚动中稳定触发，请提供一个小程序代码片段过来排查。
我也发现了这个问题，开发者工具上有这个问题
