### ISSUE TITLE
[Bug Report] vant-uploader上传heic格式图片无法预览

### ISSUE THREAD

**Issue by srqAndwr** [youzan/vant-weapp#5420]
### 重现链接

<img width="1344" alt="image" src="https://github.com/youzan/vant-weapp/assets/79629615/d8c49784-fa02-416e-a70b-36f814d21904">

### Vant Weapp 版本

1.1018

### 描述一下你遇到的问题。

文件上传选择图片类型为heic格式的预览失败，看了下源码在用url去validate的时候正则里是没有这种格式的，但是我们在云端存储后预览的时候会转格式，现在唯一的解决办法就是手动校验heic格式去给ismage强行赋值。

### 重现步骤

上传图片heic格式兼容

### 设备/浏览器

微信开发工具

**Comment by johnsonwong666** [comment]
这个正则把heic加入进去后 你可以正常显示吗？  我看社区有相关的讨论
https://developers.weixin.qq.com/community/search?query=heic&blogcategory=0&sort=time&time=0&starttime=&endtime=&block=1&page=1&showTime=true

**Comment by srqAndwr** [comment]
> 这个正则把heic加入进去后你可以正常显示吗？ 我看社区有相关的讨论 [https://developers.weixin.qq.com/community/search?query=heic&blogcategory=0&sort=time&time=0&starttime=&endtime=&block= 1&page=1&showTime=true](https://developers.weixin.qq.com/community/search?query=heic&blogcategory=0&sort=time&time=0&starttime=&endtime=&block=1&page=1&showTime=true)

加进去也不行的，需要接转码，因为小程序不认识这种图片

**Comment by johnsonwong666** [comment]
> > 这个正则把heic加入进去后你可以正常显示吗？ 我看社区有相关的讨论 [https://developers.weixin.qq.com/community/search?query=heic&blogcategory=0&sort=time&time=0&starttime=&endtime=&block= 1&page=1&showTime=true](https://developers.weixin.qq.com/community/search?query=heic&blogcategory=0&sort=time&time=0&starttime=&endtime=&block=1&page=1&showTime=true)
> 
> 加进去也不行的，需要接转码，因为小程序不认识这种图片

那这个应该还是需要你们后端帮忙处理成可识别的类型吧 png jpg 这些

**Comment by srqAndwr** [comment]
> > > 这个正则把heic加入进去后你可以正常显示吗？ 我看社区有相关的讨论 [https://developers.weixin.qq.com/community/search?query=heic&blogcategory=0&sort=time&time=0&starttime=&endtime=&block= 1&page=1&showTime=true](https://developers.weixin.qq.com/community/search?query=heic&blogcategory=0&sort=time&time=0&starttime=&endtime=&block=1&page=1&showTime=true)
> > 
> > 
> > 加进去也不行的，需要接转码，因为小程序不认识这种图片
> 
> 那这个应该还是需要你们后端帮忙处理成可识别的类型吧 png jpg 这些

是的，感谢您的回复
