### ISSUE TITLE
van-image-preview组件在项目引入了@vant/touch-emulator的情况下应该适配桌面端鼠标滚动放大/缩小预览图片功能

### ISSUE THREAD

**Issue by LuciferGD** [youzan/vant-weapp#5421]
### 重现链接

1

### Vant Weapp 版本

1

### 描述一下你遇到的问题。

1

### 重现步骤

1

### 设备/浏览器

谷歌

**Comment by johnsonwong666** [comment]
请将issue提至对应仓库下。https://github.com/youzan/vant/issues
