### ISSUE TITLE
[Bug Report] van-grid-item使用badge设置徽标，希望优化下当前数值为0时候隐藏掉，不然就会显示着0的红色角标。

### ISSUE THREAD

**Issue by linsaw** [youzan/vant-weapp#5422]
### 重现链接

<van-grid column-num="2">
  <van-grid-item icon="home-o" text="文字" dot />
  <van-grid-item icon="search" text="文字" badge="0" />
</van-grid>

### Vant Weapp 版本

1.10.19

### 描述一下你遇到的问题。

van-grid-item使用badge设置徽标，希望优化下当前数值为0时候隐藏掉，不然就会显示着0的红色角标。

### 重现步骤

<van-grid column-num="2">
  <van-grid-item icon="home-o" text="文字" dot />
  <van-grid-item icon="search" text="文字" badge="0" />
</van-grid>

**Comment by johnsonwong666** [comment]
这个是不是可以做个判断呢？ 为0传个null

**Comment by linsaw** [comment]
> 

后面发现是可以这么处理，就是希望少写几个代码，当然内部能自己处理隐藏最好

**Comment by johnsonwong666** [comment]
这个应该还是有场景需要的，不能一下打断。
