### ISSUE TITLE
popup组件点击遮罩层失效 和关闭事件函数也不生效

### ISSUE THREAD

**Issue by LjwSrd** [youzan/vant-weapp#5424]
### 重现链接

<van-popup
  show="{{ isDropDownPopup }}"
  position="bottom"
  custom-style="height: 20%;"
  bind:close="onClose"
  close-on-click-overlay="{{true}}"
  bind:click-overlay="clickoverlay"
  bind:after-leave="onClose"
/>``
onClose() {
        console.log(123);
        let that = this
        that.setData({ isDropDownPopup: false });
      },

### Vant Weapp 版本

1.10.19

### 描述一下你遇到的问题。

关闭函数  和遮罩层函数无法关闭  没有反应

### 重现步骤

点击遮罩层无法关闭弹层

### 设备/浏览器

微信原生小程序

**Comment by johnsonwong666** [comment]
开启了 closeOnClickOverlay 吗？  可以提供一个小程序代码片段过来吗？ 官方示例目前看起来没有问题。

**Comment by Aeroxian** [comment]
企微小程序有同样的问题，设置closeOnClickOverlay后无法点击遮罩层关闭PopUp
但是遮罩层的点击事件正常执行

**Comment by Aeroxian** [comment]
vant-weapp 版本 1.10.3

**Comment by johnsonwong666** [comment]
https://developers.weixin.qq.com/miniprogram/dev/devtools/minicode.html 按照这个提供一个可复现的代码片段吧

**Comment by LjwSrd** [comment]
> 

你试着把他弄成一个独立分包

**Comment by ChHanBin** [comment]
你是怎么引用的popup组件哇？我正常引用 就报错

**Comment by johnsonwong666** [comment]
> > 
> 
> 你试着把他弄成一个独立分包

分包测试了一下 没有发现异常 控制台有没有什么报错

**Comment by johnsonwong666** [comment]
> 你是怎么引用的popup组件哇？我正常引用 就报错

"usingComponents": {
  "van-popup": "@vant/weapp/popup/index"
}
正常引入 报什么错误？

**Comment by johnsonwong666** [comment]
还在吗？提供一个复现代码看看

**Comment by johnsonwong666** [comment]
此issue暂时关闭，如能复现，请附带复现小程序代码片段用于排查。

**Comment by xiaomila521** [comment]
我也遇到这个问题了，好烦，咋都关不掉，也不报错

**Comment by johnsonwong666** [comment]
> 我也遇到这个问题了，好烦，咋都关不掉，也不报错

https://developers.weixin.qq.com/s/NwHGjamA7bM4
可以提供一下复现代码片段吗？ 这个小程序代码片段修改一下，修改成你的情况然后重新分享一下过来看一下
