### ISSUE TITLE
Dialog 弹出框 Bug

### ISSUE THREAD

**Issue by dadaguai0208** [youzan/vant-weapp#5426]
### 重现链接

https://vant-contrib.gitee.io/vant-weapp/#/dialog

### Vant Weapp 版本

1.10.19

### 描述一下你遇到的问题。

Dialog 弹出框 异步关闭部分，beforeClose前少了一个逗号，导致代码报错

### 重现步骤

Dialog 弹出框 异步关闭部分，beforeClose前少了一个逗号，导致代码报错

Dialog.confirm({
  title: '标题',
  message: '弹窗内容'
  beforeClose
});

此部分代码

### 设备/浏览器

微信开发者工具

**Comment by fanburger** [comment]
@johnsonwong666 这个应该是vant-weapp 文档写错了，文档里面少了一个逗号

**Comment by johnsonwong666** [comment]
#5437
