### ISSUE TITLE
van-cascader 异步选择了第二级地址就没反应了   

### ISSUE THREAD

**Issue by zp-techie** [youzan/vant-weapp#5427]
### 重现链接

微信小程序使用van-cascader  异步加载数据  到了第二级点选择，数据加载进去了  但是页面不展示

### Vant Weapp 版本

1.10.16

### 描述一下你遇到的问题。

微信小程序使用van-cascader  异步加载数据  到了第二级点选择，数据加载进去了  但是页面不展示

### 重现步骤

文档上也不清晰说明，很坑

### 设备/浏览器

微信小程序使用van-cascader  异步加载数据  到了第二级点选择，数据加载进去了  但是页面不展示

**Comment by johnsonwong666** [comment]
升级一下最新版本试试。

**Comment by johnsonwong666** [comment]
升级最新版本可以了嘛？如果还不行请提供一个复现代码片段来看一下，异步请求使用settimeout 模拟
