### ISSUE TITLE
van-cascader组件选择的内容不能滑动

### ISSUE THREAD

**Issue by zp-techie** [youzan/vant-weapp#5431]
### 重现链接

暂无

### Vant Weapp 版本

1.10.16

### 描述一下你遇到的问题。

van-cascader选择到第五级，上面不能华东，导致第五级显示不全
![image](https://github.com/youzan/vant-weapp/assets/29621842/835b3da0-5688-43e2-b2ee-e0038659a5a6)

### 重现步骤

van-cascader选择到第五级，上面不能华东，导致第五级显示不全

**Comment by johnsonwong666** [comment]
升级最新版本试试， 提供一段复现代码过来。刚试了一下可以正常滑动。

**Comment by johnsonwong666** [comment]
升级版本可以滑动了吗，如果还不行请提供一段复现代码过来排查，此issue暂时关闭。
