### ISSUE TITLE
[Feature Request] 建议新增这样的多选或单选组件

### ISSUE THREAD

**Issue by hihuangwei** [youzan/vant-weapp#5432]
### 这个功能解决了什么问题？

增加多选或单选按钮组件

![Screenshot_2023-06-11-01-30-15-946_com tencent mm](https://github.com/youzan/vant-weapp/assets/3166799/d3cea403-dd11-4687-9e77-5ebf3b5c11ef)

### 你期望的 API 是什么样子的？

增加多选或单选按钮组件

**Comment by landluck** [comment]
暂时不会考虑支持，可以自行实现哦

**Comment by hihuangwei** [comment]
> 暂时不会考虑支持，可以自行实现哦

这个样的组件会在筛选的场景下，非常常用

**Comment by yanqzsu** [comment]
附议
或者tag支持点击事件, 减少实现难度

**Comment by yanqzsu** [comment]
#5010
