### ISSUE TITLE
[Bug Report] 请在此填写标题

### ISSUE THREAD

**Issue by Yuaao** [youzan/vant-weapp#5435]
### 重现链接

`<van-button
        loading="{{subLoading}}"
        disabled="{{subLoading}}"
        type="info"
        bindtap="submit"
        color="#da0a27"
        >提交</van-button`

### Vant Weapp 版本

^ 1.10.18

### 描述一下你遇到的问题。

给按钮加了disabled 属性，属性也生效了，但是为啥还是能点击

### 重现步骤

按钮，提交做防止重复提交校验，加了loading 也加了 disabled 样式生效了，但是还是能点击

**Comment by johnsonwong666** [comment]
使用以下几个事件
<img width="784" alt="image" src="https://github.com/youzan/vant-weapp/assets/64689255/111bcf2f-aab0-4135-af80-92c547bc9f66">
