### ISSUE TITLE
[Bug Report] cacader每一级数据超过百条性能问题

### ISSUE THREAD

**Issue by naocanfen** [youzan/vant-weapp#5436]
### 重现链接

当层级变多时，或者每一个层级数据比较多，渲染会很慢很卡，切换tab也会卡

### Vant Weapp 版本

1.10.19

### 描述一下你遇到的问题。

当层级变多时，或者每一个层级数据比较多，渲染会很慢很卡，切换tab也会卡

### 重现步骤

当层级变多时，或者每一个层级数据比较多，渲染会很慢很卡，切换tab也会卡

### 设备/浏览器

微信小程序

**Comment by songyx95** [comment]
这个问题很好复现，随便用个第三方地图的省市区数据来测试就会出现了，渲染、切换、点击交互都会比较卡

**Comment by johnsonwong666** [comment]
计划在vant-weapp 2.0版本中加入
