### ISSUE TITLE
uploader在PC小程序无法使用

### ISSUE THREAD

**Issue by mazi233** [youzan/vant-weapp#5438]
### 重现链接

<img width="694" alt="image" src="https://github.com/youzan/vant-weapp/assets/27545582/2eb22f04-f5ba-4749-b070-e8601c4cc11d">
<img width="770" alt="image" src="https://github.com/youzan/vant-weapp/assets/27545582/41c4ae0f-54a0-4382-a892-1fad94053164">

### Vant Weapp 版本

1.10.19

### 描述一下你遇到的问题。

点击没有弹出选择文件弹框

### 重现步骤

1.点击
2.无事发生

### 设备/浏览器

PC小程序

**Comment by johnsonwong666** [comment]
<img width="359" alt="image" src="https://github.com/youzan/vant-weapp/assets/64689255/fca5bbd9-407d-43d9-ad80-d53c3e3a1cad">
<img width="1250" alt="image" src="https://github.com/youzan/vant-weapp/assets/64689255/45515587-7e7a-481a-b56a-522f8f1efb44">

试了一下示例代码，可以正常弹出，会不会基础库之类的有问题？

**Comment by mazi233** [comment]
并不是开发者工具 而是 PC小程序

**Comment by mazi233** [comment]
> <img alt="image" width="359" src="https://user-images.githubusercontent.com/64689255/245980225-fca5bbd9-407d-43d9-ad80-d53c3e3a1cad.png"> <img alt="image" width="1250" src="https://user-images.githubusercontent.com/64689255/245980334-45515587-7e7a-481a-b56a-522f8f1efb44.png">
> 试了一下示例代码，可以正常弹出，会不会基础库之类的有问题？

预览PC端小程序就不行

**Comment by johnsonwong666** [comment]
<img width="1339" alt="image" src="https://github.com/youzan/vant-weapp/assets/64689255/10823ac2-57ce-4411-98d1-a9ece8f15f0a">
我是mac操作系统的。试了下也正常弹出

**Comment by mazi233** [comment]
OSX10.13有问题，还有个用户具体什么操作系统就不清楚了 反正也不行

**Comment by ruchengwang** [comment]
我的也是这个问题，PC版微信点击上传无反应！求解决方法

**Comment by lanmao139** [comment]
是有这个问题，pc端点击无反应。

**Comment by ruchengwang** [comment]
官方怎么不回复呢

**Comment by johnsonwong666** [comment]
提供一个复现代码来看一下。或者可以找到这块对应的源码调试一下微信API回调是否正常,welcome PR。

**Comment by ruchengwang** [comment]
<van-uploader file-list="{{person.idcard_img}}" accept="image" multiple="true" max-count="1" upload-text="身份证上传" deletable="{{ true }}" bind:after-read="afterRead"   bind:delete="delFile" data-field="idcard_img" data-sheet="person" />
               


//申请人图片上传预读
    afterRead(event) {
        const {file, index} = event.detail;
        console.log(event)
        let that = this
        let count = 0;
        let type = event.currentTarget.dataset.field;
        let sheet = event.currentTarget.dataset.sheet;
        let width = event.currentTarget.dataset.width;
        // 当设置 mutiple 为 true 时, file 为数组格式，否则为对象格式
        that.uploadFiles(file, count,sheet+"."+type,width)
    },

//文件上传
 uploadFiles(imgPaths, count,type,width) {
        //console.log(imgPaths)
        var that = this;
        wx.uploadFile({
            url: app.url('entry/wxapp/UpImg'),
            filePath: imgPaths[count].url,
            name: 'file',
            formData: {
                m:'rcw_cul',
                width:width
            }, //这里是上传图片时一起上传的数据
            success: function (res) {
                let {imgs = []} = {};
                imgs.push({url:res.data}) 
                that.setData({[type]:imgs})        
            },
            fail: function (e) { },
            complete: function (e) {
                count++; //下一张
                console.log(count)
                if (count == imgPaths.length) {
                    //上传完毕，作一下提示
                    console.log('上传完毕')
                } else {
                    //递归调用，上传下一张
                    that.uploadFiles(imgPaths, String(count),type);
                }
            }
        })
    },

**Comment by ruchengwang** [comment]
/
![微信截图_20230620201251](https://github.com/youzan/vant-weapp/assets/20725920/4c6d8d27-816f-420d-9583-831bbf3ae5a0)

/

**Comment by mazi233** [comment]
提供代码也没用的 example都有问题 但是pc还没办法调试

**Comment by johnsonwong666** [comment]
手机上正常吗？什么场景需要在PC端调试？而不是开发者工具？

**Comment by mazi233** [comment]
> 手机上正常吗？什么场景需要在PC端调试？而不是开发者工具？

因为 开发工具 手机都正常 只有pc使用时候有问题

**Comment by ruchengwang** [comment]
手机上是正常的，开 发者工具正常。电脑微信点不动，PC端调试不了！

**Comment by mazi233** [comment]
> 手机上是正常的，开 发者工具正常。电脑微信点不动，PC端调试不了！

是的 哈哈

**Comment by johnsonwong666** [comment]
发一下你们线上的小程序来看看

**Comment by ruchengwang** [comment]
@johnsonwong666 找到原因了吗？有解决方法吗？

**Comment by changzhengithub** [comment]
还没有解决办法吗，官方也不回复一下

**Comment by 9Lzen** [comment]
遇到同样的问题：手机端微信打开小程序上传图片正常，电脑端打开小程序点击上传图片没反应也没报错（图片删除是有反应的）
我调试了一下发现(bind:after-read="afterRead")afterRead方法并没有进去

**Comment by johnsonwong666** [comment]
debug 了一下。现在上传图片使用的是wx.chooseFile 
<img width="406" alt="image" src="https://github.com/youzan/vant-weapp/assets/64689255/973e1187-7807-4c76-8058-1e51d7dce58c">
报错输出了这个
<img width="667" alt="image" src="https://github.com/youzan/vant-weapp/assets/64689255/21a809e8-5e52-46d2-8b51-88c602766a91">

微信小程序官方社区有相关的讨论
https://developers.weixin.qq.com/community/search?query=chooseMedia%2520pc&page=1&block=1&random=1688022066496&type=1 

上传没有反应的 跟我一样打印一个error看一下是什么问题。这个问题考虑还原成wx.chooseImage解决

**Comment by yogwang** [comment]
小程序PC端现在还不支持 `wx.chooseMessageFile ` 这个API，所以大家如果要使用 `uploader` 组件请指定 `accept` 属性。不然默认会走 `wx.chooseMessageFile` 这个API。
- [wx.chooseMessageFile() 现在支持PC端使用了吗？ | 微信开放社区](https://developers.weixin.qq.com/community/develop/doc/000c6449868da86d45bf2926856800?highLine=wx.chooseMessageFile)
- [vant-weapp/lib/uploader/utils.js at v1.10.19 · youzan/vant-weapp](https://github.com/youzan/vant-weapp/blob/v1.10.19/lib/uploader/utils.js#L57)

**Comment by ruchengwang** [comment]
@yogwang 指定accept="image" 也是不行的

**Comment by 9Lzen** [comment]
uploader组件的accept默认是image了，指不指定都没啥用目前

**Comment by 9Lzen** [comment]
我看了一下源码中的uploader组件的accept属性默认是image，所以调用的是wx.chooseMedia，
可以去码源输出一下报错信息:
![image](https://github.com/youzan/vant-weapp/assets/95624392/d7464050-f378-429f-a09c-0279cf928d37)
如果显示"chooseMedia:fail fail invalid maxDuration"，可以在咱们的wxml里面的van-uploader标签里设置一下max-duration的值为10

**Comment by yogwang** [comment]
> uploader组件的accept默认是image了，指不指定都没啥用目前

是的，应该就是 `maxDuration` 的原因了。PC端修复会比较慢，手动绑定 `<vant-uploader>`  组件的 `max-duration` 属性值为 `10` 以内看看能否解决问题，也可以改源码但是不怎么建议。

- [wx.chooseMedia一旦设置maxDuration参数，pc端的小程序，无法弹出选择文件的？](https://developers.weixin.qq.com/community/develop/doc/000ee867c50a70c705fd6c75151400)

**Comment by johnsonwong666** [comment]
maxDuration 传 10 也是没有反应
<img width="811" alt="image" src="https://github.com/youzan/vant-weapp/assets/64689255/98f676b2-01ff-4432-bcb6-d701fa3c51d0">

**Comment by yogwang** [comment]
> maxDuration 传 10 也是没有反应 <img alt="image" width="811" src="https://user-images.githubusercontent.com/64689255/250514724-98f676b2-01ff-4432-bcb6-d701fa3c51d0.png">

改成 `9` 看看？上面的人说指定为 `10` 可以解决问题，但是有一些人说小于 `10` 才行。

**Comment by johnsonwong666** [comment]
5 6 7 8 9 都试过了 这个应该是小程序官方的问题

**Comment by yogwang** [comment]
> 5 6 7 8 9 都试过了 这个应该是小程序官方的问题

我这边使用 `<van-uploader max-duration="{{10}}" file-list="{{ fileList }}" bind:after-read="afterRead" />` 设置 `max-duration` 为 `10` 可以打开弹窗的。
![image](https://github.com/youzan/vant-weapp/assets/51895542/dbd9a1a7-ddfd-41c2-a6e9-03ce4008dc69)
基础库版本 `2.32.3`

**Comment by johnsonwong666** [comment]
我是 mac os @yogwang

**Comment by yogwang** [comment]
你打开DevTools，看看 `uploader` 组件的 `maxDuration` 属性是否是小于 `10` 的。

**Comment by johnsonwong666** [comment]
> 你打开DevTools，看看 `uploader` 组件的 `maxDuration` 属性是否是小于 `10` 的。
确认过了 不管是通过props穿 还是 直接改wx.chooseMedia 的参数都是没有反应的

**Comment by yogwang** [comment]
> 确认过了 不管是通过props穿 还是 直接改wx.chooseMedia 的参数都是没有反应的

也有可能是 `max-count` 引起的，默认最大值为 `20` 但是 `uploader` 组件默认值为 `100`。直接使用 `wx.chooseMedia` 这个API看看有什么异常抛出吗？没有Mac只能靠猜测。

**Comment by johnsonwong666** [comment]
@yogwang 错误提示上面贴了 fail function cannot run on service

**Comment by yogwang** [comment]
> @yogwang 错误提示上面贴了 fail function cannot run on service

抱歉，没有注意，那完蛋了。如果不是基础库版本太低的话。也有可能是因为你的微信客户端没跟新？

[chooseMedia在MAC系统中无法使用? | 微信开放社区](https://developers.weixin.qq.com/community/develop/doc/0002cea28dc31852c46f5971f51800)
> mac端目前暂不支持此功能。

或者考虑做一下兼容？如果不支持 `wx.chooseMedia` 就改用 [wx.chooseImage](https://developers.weixin.qq.com/miniprogram/dev/api/media/image/wx.chooseImage.html)？

**Comment by landluck** [comment]
解决办法：非移动端将 wx.chooseMedia 降级为 wx.chooseImage，本周修复

**Comment by ruchengwang** [comment]
是否考虑加个图片裁切功能

**Comment by landluck** [comment]
`v1.10.21` 已修复

**Comment by hoperce** [comment]
企业微信下ios不支持chooseMedia
