### ISSUE TITLE
Vant Weapp Picker 不支持allow-html 吗？

### ISSUE THREAD

**Issue by MrXCQ** [youzan/vant-weapp#5439]
### 这个功能解决了什么问题？

![image](https://github.com/youzan/vant-weapp/assets/15794342/1796b589-e542-4d53-95af-f68f6b720fbc)

### 你期望的 API 是什么样子的？

需要支持此参数，进行渲染html 个性化定制picker的 选项内容

**Comment by landluck** [comment]
小程序无法渲染 html 内容，不会考虑支持
