### ISSUE TITLE
vue3 radio无法切换

### ISSUE THREAD

**Issue by mangdehuang** [youzan/vant-weapp#5442]
### 重现链接

![image](https://github.com/youzan/vant-weapp/assets/10792335/e043c0de-9255-4ae4-a9b0-94609a5e1a5e)

### Vant Weapp 版本

1.10.19

### 描述一下你遇到的问题。

创建两个radio 切换按钮选项 界面不更新

### 重现步骤

创建两个radio 切换按钮选项 界面不更新

**Comment by johnsonwong666** [comment]
暂不支持其他开发平台使用vant-weapp产生的问题，请将issue提至uniapp下，可能是一些编译产生的问题。
