### ISSUE TITLE
[Bug Report] Grid 设置 icon-size 高度问题

### ISSUE THREAD

**Issue by Exclusive-gfj** [youzan/vant-weapp#5443]
### 重现链接

<van-grid custom-class="graphic-nav-wrap" icon-size="100rpx" column-num="4" border="{{ false }}">
                    <block wx:for="{{content}}" wx:key="index">
                        <van-grid-item icon-size="100rpx" icon="{{ item.img }}" text="{{ item.text }}"></van-grid-item>
                    </block>
                </van-grid>

### Vant Weapp 版本

1.10.19

### 描述一下你遇到的问题。

van-grid-item  中 icon 使用图片链接， 在 <van-grid> 设置  icon-size="100rpx"  的情况下，class="van-icon van-icon--image" 渲染结果为 100rpx ， 但它的上级节点 class="van-grid-item__icon" 的高度确还是使用的 var(--grid-item-icon-size,26px) 高度，导致 van-grid-item__text 的样式错位

### 重现步骤

![image](https://github.com/youzan/vant-weapp/assets/25816191/95ce8a80-6f14-4b7c-9a20-d63fedc48551)
![image](https://github.com/youzan/vant-weapp/assets/25816191/9fe5ea3b-637d-4f3a-a14a-ed42699f1f73)

**Comment by johnsonwong666** [comment]
看到了，这个应该是icon有固定高度导致。你如果希望修改这个图片的尺寸的话，是否可以通过插槽的方式引入这个图片，然后调整一些样式？

**Comment by Exclusive-gfj** [comment]
> 看到了，这个应该是icon有固定高度导向。你如果希望修改这个图片的尺寸的话，是不是可以通过插槽的方式导入这个图片，然后调整一些样式？

目前是通过插槽的方式重写的样式，但这应该算是组件的一个bug吧，还是希望能优化下

**Comment by johnsonwong666** [comment]
van-grid-item__icon 应该是为了统一尺寸而使用的，不能去掉。同时有预留slot给开发者自定义，这个应该不算故障。
