### ISSUE TITLE
在van-action-sheet 中使用van-tabs 默认选择第一个时，底部横线会在最左边

### ISSUE THREAD

**Issue by WEBhslv** [youzan/vant-weapp#5449]
### 重现链接

![image](https://github.com/youzan/vant-weapp/assets/48741938/f550ad44-f820-4bf4-80cb-4b17919c8f32)

### Vant Weapp 版本

1.10.19

### 描述一下你遇到的问题。

在van-action-sheet 中使用van-tabs 默认选择第一个时，底部横线会在最左边

### 重现步骤

打开弹窗时

**Comment by johnsonwong666** [comment]
tab是异步的吗？ 提供一个复现代码来看一下

**Comment by WEBhslv** [comment]
> tab是异步的吗？ 提供一个复现代码来看一下

代码不太方便诶，tabs是页面首次加载的时候就已经赋值了，唤起 action-sheet 之前就已经赋值了

**Comment by johnsonwong666** [comment]
<img width="758" alt="image" src="https://github.com/youzan/vant-weapp/assets/64689255/8818f493-4f87-4f12-8f4a-6685bd735293">
定位到问题了，action-sheet没有展示的时候 会导致tab横线计算有问题。临时手动调用一下resize可以解决。

**Comment by WEBhslv** [comment]
> <img alt="image" width="758" src="https://user-images.githubusercontent.com/64689255/247465801-8818f493-4f87-4f12-8f4a-6685bd735293.png"> 定位到问题了，action-sheet没有展示的时候 会导致tab横线计算有问题。临时手动调用一下resize可以解决。



> <img alt="image" width="758" src="https://user-images.githubusercontent.com/64689255/247465801-8818f493-4f87-4f12-8f4a-6685bd735293.png"> 定位到问题了，action-sheet没有展示的时候 会导致tab横线计算有问题。临时手动调用一下resize可以解决。

谢谢
