### ISSUE TITLE
[Feature Request] GoodsAction icon新增size属性，由于button有size属性，当button设置为large时，icon会变得很小

### ISSUE THREAD

**Issue by nanhupatar** [youzan/vant-weapp#5450]
### 这个功能解决了什么问题？

由于button有size属性，当button设置为large时，icon会变得很小

### 你期望的 API 是什么样子的？

```xml
<van-goods-action>
  <van-goods-action-icon icon="chat-o" text="客服" bind:click="onClickIcon"  size="28px"/>
  <van-goods-action-icon icon="cart-o" text="购物车" bind:click="onClickIcon"  size="28px"/>
  <van-goods-action-button
    text="加入购物车"
    type="warning"
    bind:click="onClickButton"
    size="28px"
  />
  <van-goods-action-button size="large" text="立即购买" bind:click="onClickButton" />
</van-goods-action>
```

**Comment by johnsonwong666** [comment]
<img width="436" alt="image" src="https://github.com/youzan/vant-weapp/assets/64689255/7c43f777-93a3-4441-85bb-9277d50b9014">
<img width="436" alt="image" src="https://github.com/youzan/vant-weapp/assets/64689255/b7e57c8c-a2b2-4712-876d-70489caf7a59">
使用icon-class 可以满足你的场景

**Comment by nanhupatar** [comment]
> <img alt="image" width="436" src="https://user-images.githubusercontent.com/64689255/247483316-7c43f777-93a3-4441-85bb-9277d50b9014.png"> <img alt="image" width="436" src="https://user-images.githubusercontent.com/64689255/247483379-b7e57c8c-a2b2-4712-876d-70489caf7a59.png"> 使用icon-class 可以满足你的场景

感谢，这样可以解决，但是不是很符合组件本身属性。这个size应该就是可配置的

**Comment by landluck** [comment]
`v1.10.20` 已支持 size 属性
