### ISSUE TITLE
Popup 设置了close-on-click-overlay="false" 点击遮罩层还是会调用bind:close方法

### ISSUE THREAD

**Issue by yisirman** [youzan/vant-weapp#5452]
### 重现链接

close-on-click-overlay  是否在点击遮罩层后关闭

设置了该参数为false，但是点击遮罩层还是会调用bind:close方法

### Vant Weapp 版本

v1.10.19

### 描述一下你遇到的问题。

<van-popup closeable round show="{{ show }}" close-on-click-overlay="false" custom-style="height: 20%;" bind:close="onClose">

点击遮罩层还是会调用onClose方法

如何做到点击遮罩层不关闭，仅点击关闭图标才会关闭呢？

### 重现步骤

如上所示

### 设备/浏览器

微信开发者工具

**Comment by johnsonwong666** [comment]
可以提供一个复现代码看一下吗？ close-on-click-overlay="{{false}}"  是否是这么写的？ 测试了一下没有触发。

**Comment by yisirman** [comment]
> 

可以了 感谢 没有加 {{ }}
