### ISSUE TITLE
[Bug Report] IOS端上传视频无法预览

### ISSUE THREAD

**Issue by TUZI2018QH** [youzan/vant-weapp#5454]
### 重现链接
http://114.117.163.254/%E4%B8%8A%E4%BC%A0%E8%A7%86%E9%A2%91.gif

```[tasklist]
### Tasks
- [ ] Add a draft title or issue reference here
```

```html
<van-cell-group>
    <van-cell title="视频上传" value="{{videoList.length}}/1" use-label-slot> 
	<view slot="label" style="margin-top:10px">
	    <van-uploader file-list="{{ videoList }}" bind:after-read="afterReadVideo" bind:delete="onDeleteVideo" accept="video" max-count="1" max-duration="60" />
	</view>
    </van-cell>
</van-cell-group>
``` 

### Vant Weapp 版本

1.7.2、官方微信小程序示例

### 描述一下你遇到的问题。

ios端，Uploader上传视频后，点击无法预览，安卓端正常

### 重现步骤

IOS端
1.选择或拍摄视频。
2.点击预览。

### 设备/浏览器

IOS

**Comment by johnsonwong666** [comment]
是什么机型呢？手机测试机预览正常

**Comment by TUZI2018QH** [comment]
> 是什么机型呢？手机测试机预览正常

iPhone 13
IOS 16.5（20F66）

**Comment by johnsonwong666** [comment]
组件库演示的版本比较低，很久没更新了，尝试拉下代码，在微信小程序开发者工具预览用手机扫一下，看下是否正常？

**Comment by landluck** [comment]
修复过 https://github.com/youzan/vant-weapp/pull/5142 。使用 [v1.10.10](https://github.com/youzan/vant-weapp/compare/v1.10.9...v1.10.10) 版本以上

**Comment by lilin87788** [comment]
我也遇到了这个问题 了 求解决,就是官方的例子就无法预览，安卓的手机可以，苹果的不可以，有没有临时解决的办法
