### ISSUE TITLE
想要一个生成海报和裁切图片的组件

### ISSUE THREAD

**Issue by 976977577** [youzan/vant-weapp#5455]
### 这个功能解决了什么问题？

1. 开发项目时，需要做活动页面，用户需要生成海报去分享
2. 上传素材，需要裁切图片

### 你期望的 API 是什么样子的？

希望开发出来的能简单使用就能实现效果比如我再Poster组件写的内容，可以直接给我生成出一张海报图
`
<Poster>
// 我的海报页面代码
</Poster>
`

**Comment by landluck** [comment]
暂时不考虑支持
