### ISSUE TITLE
[Feature Request]Button支持getRealtimePhoneNumber

### ISSUE THREAD

**Issue by buaazyl** [youzan/vant-weapp#5459]
### 这个功能解决了什么问题？

小程序更新了按钮的open-type，增加了getRealtimePhoneNumber，用于获取实时手机号
https://developers.weixin.qq.com/miniprogram/dev/framework/open-ability/getRealtimePhoneNumber.html
希望vant可以同步支持

### 你期望的 API 是什么样子的？

```xml
<van-button type="default" open-type="getRealtimePhoneNumber" bind:getrealtimephonenumber="getPhoneNumber">默认按钮</van-button>
```

**Comment by landluck** [comment]
`v1.10.21` 已支持
