### ISSUE TITLE
SwipeCell右侧的两个按钮如何同时存在且样式不混乱

### ISSUE THREAD

**Issue by yik7707** [youzan/vant-weapp#5465]
### 这个功能解决了什么问题？

SwipeCell右侧的两个按钮如何同时存在且样式不混乱？
API没写代码片段
代码片段中有使用.van-swipe-cell__right样式，但是样式是混乱的：
https://developers.weixin.qq.com/s/yeDlVpmp7kJz
![image](https://github.com/youzan/vant-weapp/assets/74293458/3fcb31fa-9707-42f8-8c0c-30113c280363)

### 你期望的 API 是什么样子的？
如果支持请在官网列出相应的代码片段以便使用，如果不支持提出需求在2X版本中支持
右侧两个slot也不行，如代码片段所示：
```
<view slot="right">删除</view>
  <view slot="right">收藏</view>
```

**Comment by johnsonwong666** [comment]
right slot 里面放两个button 然后重写一下.van-swipe-cell__right样式 比如display:flex flex-direction:row 应该可以实现

**Comment by yik7707** [comment]
> right slot 里面放两个button 然后重写一下.van-swipe-cell__right样式 比如display:flex flex-direction:row 应该可以实现

https://developers.weixin.qq.com/s/tTnUztmf7fJ5
实现不知道哪里出了问题，应用van-button修改的type属性，没背景颜色，代码片段如上

**Comment by johnsonwong666** [comment]
<img width="630" alt="image" src="https://github.com/youzan/vant-weapp/assets/64689255/864eb31b-e718-481f-ab1f-52572abcf81b">
没有引入van-button

**Comment by yik7707** [comment]
> <img alt="image" width="630" src="https://user-images.githubusercontent.com/64689255/251017147-864eb31b-e718-481f-ab1f-52572abcf81b.png"> 没有引入van-button

好的好的一下忘了

**Comment by yik7707** [comment]
解决了
