### ISSUE TITLE
van-grid组件在部分机型的时候会导致组件不显示

### ISSUE THREAD

**Issue by shenchuangalice** [youzan/vant-weapp#5466]
### 重现链接

不需要链接

### Vant Weapp 版本

"vant": "^2.12.44"

### 描述一下你遇到的问题。

首先项目是部署的企业微信应用，我一加载页面的时候代码是写的vant-grid组件，这个问题我排查了很久都没有找到，直到最近。
部分人在加载页面的时候会遇到vant-grid组件 展示不出来界面内容，代码如下:
<van-grid :column-num="1" class="entry_main" gutter="0px">
            <van-grid-item icon="edit" text="考试中心" to="/testCenter" />
</van-grid>

后续排查的时候，使用了原生的进行编写界面，能够正常的展示界面，代码如下:
```vue
<div style="position:absolute;top: 7.5%;height: 92.5%;width: 100%;">
        <!-- 考试中心 -->
        <div style="position:relative;height:11%;" @click="goToTestCenter">
            <div style="position:absolute;left:45%;top:5%;">
                <i class="iconfont icon-zhongxinkaoshi" style="font-size:30px;color:#a792f9"></i>
            </div>
            <div style="position:absolute;left:42.5%;top:52%;">
                <span style="font-size:12px;color: black;">考试中心</span>
            </div>
            <div style="position:relative;border-bottom:1px solid #e1e1e1;width: 100%;top: 100%"></div>
        </div>
```

### 重现步骤

加载页面的时候

### 设备/浏览器

移动端，不限于苹果和安卓

**Comment by landluck** [comment]
vant 问题，可以到 [vant](https://github.com/youzan/vant/issues) 下提交 issue
