### ISSUE TITLE
van-stepper在输入为空的时候不触发change事件

### ISSUE THREAD

**Issue by lbczbl** [youzan/vant-weapp#5469]
### 重现链接

`<van-stepper value="{{i.count}}" data-index="{{index}}"
                data-idx="{{inde}}" integer  max="{{i.maxCount}}" bindchange="changeCount" button-size="40rpx" 
                bindfocus="focusInput"
                bindblur="blurInput" class="add-stepper" />`

### Vant Weapp 版本

1.10.9

### 描述一下你遇到的问题。

上述代码中value绑定的是数组列表中的count字段，比如本来绑定的count是1，现在在输入框只删除，不触发change事件，只有再点进输入框的时候能触发输入框聚焦事件，才能拿到当前输入框的value，看仓库代码中输入为空的时候直接return了
![image](https://github.com/youzan/vant-weapp/assets/37365436/28e76c6e-da8d-4610-8e0a-02192c18827b)

### 重现步骤

在输入框只删除，不触发change事件，实际当前stepper的绑定的i.count都没法改变
![image](https://github.com/youzan/vant-weapp/assets/37365436/656c166b-29e7-44eb-84e9-d4641df42bf7)

![image](https://github.com/youzan/vant-weapp/assets/37365436/17b09a36-5fec-41bb-a073-e5d308ed8534)

### 设备/浏览器

微信小程序

**Comment by daiwanxing** [comment]
你可以用 `bind:change` 来监听输入为空的变化。

**Comment by landluck** [comment]
可以使用最新的版本，在最新版本中在 input blur 时会重新计算并触发 change 事件，同步数据更新
