### ISSUE TITLE
父容器使用wx:if或者hidden，sticky粘性布局就会失效，文档里面没有写，这是正常情况还是bug？

### ISSUE THREAD

**Issue by cao1987** [youzan/vant-weapp#5470]
### 重现链接

`
<view style="height: 10000px;">    
    <view style="background-color: aqua;height: 100px;"></view>
    <view wx:if="{{show}}">
        <van-sticky>
            <button>按钮</button>
        </van-sticky>    
    </view>
</view>
`

### Vant Weapp 版本

1.10.20

### 描述一下你遇到的问题。

Sticky粘性布局会失效

### 重现步骤

父容器使用wx:if判断的时候，Sticky直接失效，父容器使用hidden的时候，初始加载完成的时候元素直接就在最顶部，这种情况是设定如此吗？能不能解决

**Comment by johnsonwong666** [comment]
父元素不渲染理论上子元素的也不会渲染的，sticky自然无效。

**Comment by cao1987** [comment]
> 

是使用了wx:if，元素经过判断后渲染出来了

**Comment by johnsonwong666** [comment]
> > 
> 
> 是使用了wx:if，元素经过判断后渲染出来了

wx:if={{false}} sticky 还出来了？

**Comment by cao1987** [comment]
> > > 
> > 
> > 
> > 是使用了wx：if，元素经过判断后渲染出来了
> 
> wx：if={{false}} sticky 还出来了？

不是啊，因为有两个盒子，每个盒子里面都有一个van-sticky 组件，我用wx:if控制不同条件下，只展示其中一个盒子，展示出来的里面的sticky 是失效的

**Comment by johnsonwong666** [comment]
https://developers.weixin.qq.com/minigame/dev/devtools/minicode.html
来个代码片段看一下 @cao1987

**Comment by cao1987** [comment]
> https://developers.weixin.qq.com/minigame/dev/devtools/minicode.html 来个代码片段看一下 @cao1987

https://developers.weixin.qq.com/s/iFje0smc7iJn
微信的代码片段默认不支持npm包，我这直接复制过去的看看能不能看得到

**Comment by johnsonwong666** [comment]
看了一下 除了hidden的时候有问题外 其他都是正常吸顶的

**Comment by johnsonwong666** [comment]
该issue 在vant-weapp2.0 解决。
