### ISSUE TITLE
[Bug Report] 在小程序无法导入样式

### ISSUE THREAD

**Issue by codecodify** [youzan/vant-weapp#5473]
### 重现链接

`/**app.wxss**/
@import '@vant/weapp/common/index.wxss';`

报错内容：
`
[ WXSS 文件编译错误] ./app.wxss
File not found: @vant/weapp/common/index.wxss(env: macOS,mp,1.06.2306020; lib: 2.32.3)
`

### Vant Weapp 版本

1.10.20

### 描述一下你遇到的问题。

在小程序能正常使用组件，但是要导入样式就提示找不到文件

### 重现步骤

1. 根据文档描述在app.wxss里导入样式，https://vant-contrib.gitee.io/vant-weapp/#/custom-style

**Comment by johnsonwong666** [comment]
![image](https://github.com/youzan/vant-weapp/assets/64689255/66900b52-9d2c-46a9-92b6-9fee41d6bb78)
![image](https://github.com/youzan/vant-weapp/assets/64689255/978cc28f-d5eb-42d4-b466-09f00100ddce)
重新构建一下npm 试试@import "/miniprogram_npm/@vant/weapp/common/index.wxss"

**Comment by codecodify** [comment]
`@import "/miniprogram_npm/@vant/weapp/common/index.wxss";`
可以了，谢谢
