### ISSUE TITLE
在微信小程序多端项目中，button组件希望支持open-type=“phoneOneClickLogin”

### ISSUE THREAD

**Issue by kingdsa** [youzan/vant-weapp#5474]
### 这个功能解决了什么问题？

https://dev.weixin.qq.com/docs/framework/dev/component/auth/phoneOneClickLogin.html
微信团队开发了微信小程序转app的功能 希望vant-weapp能支持里面的一些新的东西

### 你期望的 API 是什么样子的？

<van-button type="primary" bind:phoneoneclicklogin="btnClick" open-type="phoneOneClickLogin">本机一件登录</van-button>

**Comment by landluck** [comment]
优先级低，有需求可以提交 PR

**Comment by landluck** [comment]
非微信小程序标准能力，暂不考虑支持
