### ISSUE TITLE
<van-button> 在安卓手机原生键盘上点击下一步click事件会响应

### ISSUE THREAD

**Issue by AndyShaoxianfeng** [youzan/vant-weapp#5481]
### 重现链接

<template>
  <div :class="moduleClasses">
    <van-field
      :label="moduleData.title"
      :required="moduleData.necessaryFlag == 1"
      :rules="[
        {
          required: moduleData.necessaryFlag == 1,
          message: `请输入${moduleData.title}`
        }
      ]"
    >
      <template #input>
        <div class="column">
          <template v-for="(item, index) in rowDatas">
            <div class="row-headers" :key="index">
              <span style="margin-left: 0.05rem">{{ index + 1 + '（第' + transToChines(index + 1) + '行）' }}</span>
              <van-icon name="delete" color="red" style="margin-right: 0.05rem" @click="deleteRow(index)" />
            </div>
            <van-field
              style="margin-top: 0.1rem"
              v-for="(el, indexs) in moduleData.tableColumns"
              :label="el.columnName"
              :key="'info2-' + indexs + index"
              autosize
              :formatter="formatter"
              :value="item[indexs] ? item[indexs].rowName : ''"
              @input="val => changeName(val, index, indexs)"
              placeholder="请输入内容"
            ></van-field>
          </template>
          <van-button class="add-button" plain type="info" @click="addRow">新增一行</van-button>
        </div>
      </template>
    </van-field>
  </div>
</template>

### Vant Weapp 版本

2.12.31

### 描述一下你遇到的问题。

 <van-button> 在安卓手机原生键盘上点击下一步click事件会响应@click="addRow">

### 重现步骤

1、安卓手机原生键盘上点击下一步
2、@click="addRow"方法响应

**Comment by johnsonwong666** [comment]
vant issue 请提到vant仓库下
https://github.com/youzan/vant/issues
