### ISSUE TITLE
[Bug Report] weapp微信小程序中van-cell中的Cell 外部样式类custom-class、value-class等无法插入

### ISSUE THREAD

**Issue by Yetongge** [youzan/vant-weapp#5485]
### 重现链接

<van-cell custom-class="a"></van-cell>

### Vant Weapp 版本

1.10.21

### 描述一下你遇到的问题。

使用van-cell组件时Cell 外部样式类custom-class、value-class等无法插入

### 重现步骤

使用Cell 外部样式类custom-class、value-class等

### 设备/浏览器

微信开发者工具1.06.230681

**Comment by johnsonwong666** [comment]
无法插入是什么意思？ 不生效嘛？
![image](https://github.com/youzan/vant-weapp/assets/64689255/895b5e7c-b809-4337-843d-95437d31148a)
<img width="1101" alt="image" src="https://github.com/youzan/vant-weapp/assets/64689255/498a3632-b5ac-4d6f-aea9-011eeaebf068">

**Comment by Yetongge** [comment]
没有显示到标签里面




小葛
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "youzan/vant-weapp"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月12日(星期三) 下午5:57
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [youzan/vant-weapp] [Bug Report] weapp微信小程序中van-cell中的Cell 外部样式类custom-class、value-class等无法插入 (Issue #5485)





 
无法插入是什么意思？ 不生效嘛？

**Comment by johnsonwong666** [comment]
@Yetongge 可以详细一点嘛 没有明白你的意思。
