### ISSUE TITLE
[Feature Request] 日历组件calendar的formatter中topInfo和bottomInfo支持富文本

### ISSUE THREAD

**Issue by Yetongge** [youzan/vant-weapp#5486]
### 这个功能解决了什么问题？

在对应日期下面可以增加图片等

### 你期望的 API 是什么样子的？

bottomInfo = "<image src='/xxx/xxx/xxx.jpg' style='width: 20px;height: 20px'></image>"

**Comment by Yetongge** [comment]
或者van-calendar__day元素支持富文本

**Comment by johnsonwong666** [comment]
暂不支持，现在实现并不是slot，改造成本比较大。
