### ISSUE TITLE
[BUG] Tabs: 在js里改变 active、title 无效

### ISSUE THREAD

**Issue by xxyuze** [youzan/vant-weapp#549]
**描述问题**
### Tabs标签页 ，在js改变active、title 无效

![image](https://user-images.githubusercontent.com/17399581/45296625-3876bd00-b535-11e8-8f67-732fac3e0c53.png)

### 只改变了字体颜色，划线和内容都没有改变，以下是当前数据

![image](https://user-images.githubusercontent.com/17399581/45296650-44fb1580-b535-11e8-8580-48cdf763f411.png)

**环境**
 - 设备: 微信开发者工具、小米5s
 - 基础库版本: 1.94
 - Vant Weapp 版本:0.3.0

**Comment by flyweights** [comment]
同时，我遇到了```<van-tabs active="{{ active }}" color="yellow">``` 选中和没有选中都变黄色了，这是不是一个bug来的？

**Comment by chenjiahan** [comment]
已经在 dev 分支修复这个问题，会在 0.3.2 发布

**Comment by swordsman-coder** [comment]
> 已经在 dev 分支修复这个问题，会在 0.3.2 发布

但是我试了下， 也是更改active是无效的 v1.0.0-beta
