### ISSUE TITLE
【求救】van-dropdown-menu

### ISSUE THREAD

**Issue by superMian** [youzan/vant-weapp#5490]
### 重现链接

【求救】van-dropdown-menu

### Vant Weapp 版本

1.10.20

### 描述一下你遇到的问题。

1。van-dropdown-menu内嵌套scroll-view，高度计算不精准。目前用的是windowHeight - 导航栏 - tabbar，但是有问题。
2。怎么实现点击van-dropdown-menu后页面滚动吸顶，再展开面板呢，目前用的before-toggle，但是面板一打开后，点击遮罩无法关闭，打开新的菜单，旧的菜单也不会关闭。

### 重现步骤

【求救】van-dropdown-menu

**Comment by johnsonwong666** [comment]
提供一个小程序代码片段看一下

**Comment by johnsonwong666** [comment]
<img width="758" alt="image" src="https://github.com/youzan/vant-weapp/assets/64689255/54af61f1-e21f-40c8-9065-9284bc33895c">
是否是通过slot 加入的 scrollview呢？ 注意一下文档的说明。
