### ISSUE TITLE
vant-tabs 在飞书小程序中报错。。。

### ISSUE THREAD

**Issue by admin-zlj** [youzan/vant-weapp#5491]
### 重现链接
```js
<van-tabs>
          <van-tab title="基本信息">
            
          </van-tab>
          <van-tab title="访问记录">
       
          </van-tab>
        </van-tabs>
```

### Vant Weapp 版本

1.10.21

### 描述一下你遇到的问题。

<img width="879" alt="image" src="https://github.com/youzan/vant-weapp/assets/101649201/4cdf7e66-8808-47b6-8202-0509c45e2880">
貌似是vant-sticky组件引起的，在微信小程序是正常的

### 重现步骤

引入后，直接白屏

**Comment by johnsonwong666** [comment]
暂不支持解决非原生微信小程序产生的问题，可能是平台差异性、编译之类的问题等。
