### ISSUE TITLE
van-radio-group 与 van-radio 不回显

### ISSUE THREAD

**Issue by guage1003** [youzan/vant-weapp#5493]
### 重现链接

<img width="1370" alt="image" src="https://github.com/youzan/vant-weapp/assets/77481125/64276178-5013-43c2-a39f-795135888f59">
<img width="846" alt="image" src="https://github.com/youzan/vant-weapp/assets/77481125/c0ca7e27-529d-4e3c-af77-2134c71b417f">

### Vant Weapp 版本

1.10.19

### 描述一下你遇到的问题。

van-radio 不回显 无法绑定值

### 重现步骤

<img width="1370" alt="image" src="https://github.com/youzan/vant-weapp/assets/77481125/64276178-5013-43c2-a39f-795135888f59">
<img width="846" alt="image" src="https://github.com/youzan/vant-weapp/assets/77481125/c0ca7e27-529d-4e3c-af77-2134c71b417f">

### 设备/浏览器

微信开发者工具

**Comment by guage1003** [comment]
手动在js改templateType，是可以绑定的

**Comment by yisirman** [comment]
@landluck 好像是类型不匹配的原因？templateType 是整型 name是字符串
