### ISSUE TITLE
goods-action组件使用icon插槽时，样式显示有问题

### ISSUE THREAD

**Issue by forget1** [youzan/vant-weapp#5494]
### 重现链接

https://gist.github.com/forget1/ac287997f730a73e49e5b96a070fc7d2

### Vant Weapp 版本

1.10.21

### 描述一下你遇到的问题。

goods-action使用icon插槽时，样式显示有问题；当不使用插槽，仅调整goods-action-icon的class-prefix时显示就没有问题

![WX20230719-113423](https://github.com/youzan/vant-weapp/assets/18653975/d8abe540-c82f-469c-8611-f513ce93d2d4)

### 重现步骤

```
<van-goods-action>
  <van-goods-action-icon text="客服">
    <van-icon slot="icon" name="home-o" class-prefix="icon2" />
  </van-goods-action-icon>
  <van-goods-action-icon icon="cart-o" text="购物车" info="5" />
  <van-goods-action-icon icon="shop-o" text="店铺" />
  <van-goods-action-button color="#be99ff" text="加入购物车" type="warning" />
  <van-goods-action-button color="#7232dd" text="立即购买" />
</van-goods-action>
```

### 设备/浏览器

Android、IOS

**Comment by johnsonwong666** [comment]
样式有问题，应该期望是上面图标下面文字，本周会修复。

**Comment by landluck** [comment]
`v1.10.22` 已修复

**Comment by luchaohai** [comment]
为什么不直接把 text 标签改成 view ？？
