### ISSUE TITLE
[Feature Request] 希望 Cell 组件提供 name Props 并在 bind:click 返回相关数据

### ISSUE THREAD

**Issue by wuchangjun233** [youzan/vant-weapp#5499]
### 这个功能解决了什么问题？

将cell作为点击单元格的时候，需要获取点击了哪个cell

### 你期望的 API 是什么样子的？

`<van-cell name="{{item}}" clickable bind:click="cellClick" />`

**Comment by wuchangjun233** [comment]
> ### 这个功能解决了什么问题？
> 将cell作为点击单元格的时候，需要获取点击了哪个cell
> 
> ### 你期望的 API 是什么样子的？
`<van-cell` name="2{{item}}" />

**Comment by ghost** [comment]
这个需求可以这样实现，仅供参考：
```html
<view class="container">
  <van-cell data-name="{{item1}}" bind:click="cellClick">11111</van-cell>
  <van-cell data-name="{{item2}}" bind:click="cellClick">22222</van-cell>
</view>

```
```js
Page({
  data: {
    item1: 'test1',
    item2: 'test2',
  },
  cellClick(e) {
    console.log(e.currentTarget.dataset.name)
  }
})
```

![Kapture 2023-07-23 at 01 05 29](https://github.com/youzan/vant-weapp/assets/106857035/2ac2d085-1187-4a35-b49b-51d757a0129b)

**Comment by wuchangjun233** [comment]
> 这个需求可以这样实现，仅供参考：
> ```html
> <view class="container">
>   <van-cell data-name="{{item1}}" bind:click="cellClick">11111</van-cell>
>   <van-cell data-name="{{item2}}" bind:click="cellClick">22222</van-cell>
> </view>
> 
> ```
> ```js
> Page({
>   data: {
>     item1: 'test1',
>     item2: 'test2',
>   },
>   cellClick(e) {
>     console.log(e.currentTarget.dataset.name)
>   }
> })
> ```
> 
> ![Kapture 2023-07-23 at 01 05 29](https://github.com/youzan/vant-weapp/assets/106857035/2ac2d085-1187-4a35-b49b-51d757a0129b)
> 
> 

好的，麻烦了，十分感谢！
