### ISSUE TITLE
van-field 使用focus的时候 出现BUG

### ISSUE THREAD

**Issue by chaituan** [youzan/vant-weapp#550]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

使用场景，点击按钮 弹出popup，popup里面放的输入框，弹出的同时也给输入框加上焦点，这时手机键盘也会同时弹出。
BUG： 在小程序 所有tabbar页面使用正常，但是在内页（也就是不再tabbar使用），popup弹出后 输入 手机键盘弹出，input弹不上来。  注意是使用 bottom的情况下。

` <van-popup show="{{ showpopup }}" position="bottom" bind:close="onClosepop" custom-class="zindex21" overlay-style="z-index:2000">
    <van-cell-group>
      <van-field  placeholder="请输入你要评论的内容" border="{{ false }}" value="{{commentVal}}" focus="{{plinput}}" bind:confirm="onCommentsub" confirm-type="send" />
    </van-cell-group>
  </van-popup>`

**环境**
 - 设备: 小米五
 - 基础库版本: 2.2
 - Vant Weapp 版本:0.3.1

**Comment by chenjiahan** [comment]
focus 是微信提供的属性，这个问题可以去微信论坛反馈~

**Comment by chaituan** [comment]
@chenjiahan  直接在popup 放入 input 使用正常。  就是调用组件显示不正常

**Comment by chenjiahan** [comment]
@chaituan 可以把 input 放到一个自定义组件内试试，能否正常工作
