### ISSUE TITLE
[Bug Report] vant-field的label-class不起效

### ISSUE THREAD

**Issue by Mini-ying** [youzan/vant-weapp#5500]
### 重现链接

<van-field label="案件信息" placeholder="请选择案件" is-link readonly bind:click-input="showPopup" border="{{false}}" label-class="caseInfo_title" value="{{casePickerValue}}" />

.caseInfo_title{
  color: #019C4D;
}

### Vant Weapp 版本

1.10.22

### 描述一下你遇到的问题。

vant-field的label-class不起效，设置了改变label的颜色但并没有起效
<img width="331" alt="image" src="https://github.com/youzan/vant-weapp/assets/70211275/41ed2723-71ec-4047-95c6-38094e010b54">

### 重现步骤

设置了改变label的颜色但并没有起效

**Comment by ghost** [comment]
可暂时使用`!important`解决

```
.caseInfo_title{
color: #019C4D!important;
}
```

**Comment by johnsonwong666** [comment]
使用 外部样式类 需要用!important 确认样式是否生效
<img width="842" alt="image" src="https://github.com/youzan/vant-weapp/assets/64689255/7fd29d82-fbdd-4585-b7ad-a54312605d91">
