### ISSUE TITLE
[Bug Report] 日历组件加载过慢

### ISSUE THREAD

**Issue by Yetongge** [youzan/vant-weapp#5501]
### 重现链接

`<van-button bind:tap="show" custom-style="margin-top: 600rpx;" type="info">打开日历</van-button>
<van-calendar wx:if="{{dateShow}}" show="{{ dateShow }}" min-date="{{minDate}}" max-date="{{ maxDate }}" color="var(--color-primary)" type="range" bind:close="calendarClose" bind:confirm="calendarConfirm" />`

`dateShow: false,
    minDate: new Date(2010, 0, 1).getTime(),
    maxDate: new Date().getTime(),`

### Vant Weapp 版本

1.10.22

### 描述一下你遇到的问题。

使用日历组件时，组件加载过慢

### 重现步骤

一个空页面放入日历组件，页面会加载很慢，在日历组件中加上wx:if时，明显看出来日历组件很慢才能加载出来

### 设备/浏览器

微信开发者工具1.06.230681

**Comment by johnsonwong666** [comment]
<img width="751" alt="image" src="https://github.com/youzan/vant-weapp/assets/64689255/45bca97c-8f68-49a7-ad22-10a37e9ce67d">
minDate 不宜设置过大 calendar组件将考虑在2.0里面优化
