### ISSUE TITLE
时间选择器建议新增selectable Range API接收范围数组和disabled禁用样式

### ISSUE THREAD

**Issue by ShouJen** [youzan/vant-weapp#5508]
### 这个功能解决了什么问题？

参考Element 的时间选择器对应API
![image](https://github.com/youzan/vant-weapp/assets/94954667/c134e002-d4e1-4b61-b893-de2a93c45e04)
![image](https://github.com/youzan/vant-weapp/assets/94954667/2ca66310-d1ca-473b-bdcb-f6acc0bc738d)

### 你期望的 API 是什么样子的？

时间选择器建议新增selectable Range API接收范围数组和disabled禁用样式

**Comment by landluck** [comment]
![image](https://github.com/youzan/vant-weapp/assets/27060081/92c300dc-e1b9-4684-b58b-abf12b94c64d)
可以使用这两个字段限制选择范围，C 端出于性能考虑不能选择的时间建议通过选择范围控制，而不是禁用选择，所以 disbled 不会考虑支持
