### ISSUE TITLE
什么时候能支持抖音小程序？

### ISSUE THREAD

**Issue by lulinzh** [youzan/vant-weapp#5510]
### 这个功能解决了什么问题？

微信转抖音小程序出现比较多适配问题

### 你期望的 API 是什么样子的？

![image](https://github.com/youzan/vant-weapp/assets/13724812/05ac6eef-7345-48ba-ac4f-1bcf3c3aa234)
类似这样的编译错误

**Comment by johnsonwong666** [comment]
目前vant-weapp不支持多端。
