### ISSUE TITLE
DatetimePicker 时间选择，修改背景色，上下颜色无法修改

### ISSUE THREAD

**Issue by xykuka** [youzan/vant-weapp#5513]
### 重现链接

<template>
  <van-popup v-model="show" position="bottom" @close="cancel">
    <van-datetime-picker
      v-model="date"
      :type="type"
      title="选择年月"
      :min-date="minDate"
      :max-date="maxDate"
      @confirm="confirm"
      @cancel="cancel"
      :formatter="formatter"
      v-if="show"
    />
  </van-popup>
</template>
<script>
export default {
  name: 'DatetimePicker',
  props: {
    type: {
      type: String,
      default: 'year-month'
    },
    currentDate: {
      type: Date,
      default: () => new Date()
    },
    minDate: {
      type: Date,
      default: () => new Date(1900, 0, 1)
    },
    maxDate: {
      type: Date,
      default: () => new Date(2100, 12, 31)
    }
  },
  data() {
    return {
      date: new Date(),
      show: true
    }
  },
  created() {
    this.date = this.currentDate
  },
  methods: {
    formatter(type, val) {
      if (type === 'year') {
        return `${val}年`
      } else if (type === 'month') {
        return `${val}月`
      }
      return val
    },
    confirm(timestamp) {
      this.show = false
      this.$emit('confirm', this.$util.getNow(null, null, timestamp))
    },
    cancel() {
      this.show = false
      this.$emit('cancel', false)
    }
  }
}
</script>

<style scoped lang="scss">
::v-deep .van-picker-column__item {
  color: #fff;
  background-color: #171c25;
  background-image: none !important;
}
::v-deep .van-picker__confirm {
  color: $--primary-color;
}
::v-deep .van-picker {
  background-color: #171c25;
  background-image: none !important;
}
</style>

### Vant Weapp 版本

2.12.38

### 描述一下你遇到的问题。

![image](https://github.com/youzan/vant-weapp/assets/59901358/24c3cde3-a95c-44c0-bb24-27fa5874b342)
想要修改背景色，上下颜色无法修改

### 重现步骤

修改主题色

**Comment by johnsonwong666** [comment]
请将issues 提至vant仓库 https://github.com/youzan/vant

**Comment by jiajiaxing1** [comment]
我也遇到了，后续怎么解决的呀
