### ISSUE TITLE
[Bug Report] uploader 支持从本地文件夹调取文件吗？而不是从聊天窗口

### ISSUE THREAD

**Issue by stantoxt** [youzan/vant-weapp#5514]
### 重现链接

暂无

### Vant Weapp 版本

1.10.23

### 描述一下你遇到的问题。

配置 uploader 的accept属性 为 all的时候，从聊天窗口选择文件，想要直接从文件夹直接选择

### 重现步骤

配置 uploader 的accept属性 为 all

**Comment by johnsonwong666** [comment]
accept传image.    accept 传 all 时 目前调用的是 wx.chooseMessageFile这个api，目前看起来传all的现象就是从聊天窗口选择。

**Comment by stantoxt** [comment]
理解，感谢
