### ISSUE TITLE
[Bug Report] 评分半星组件展示问题

### ISSUE THREAD

**Issue by Alisonispig** [youzan/vant-weapp#5515]
### 重现链接

![image](https://github.com/youzan/vant-weapp/assets/29892659/2a449fd5-d1b0-4e48-9d9b-fe7d387e5c64)

### Vant Weapp 版本

"@vant/weapp": "^1.10.23",

### 描述一下你遇到的问题。

展示半星所有的星星左半边都是亮的

### 重现步骤

展示半星所有的星星左半边都是亮的

**Comment by johnsonwong666** [comment]
void-color="#eee"
 
 加上这个属性
