### ISSUE TITLE
[Feature Request] stepper组件展示值变化后，组件绑定的value值没有自动更新，需要支持绑定更新

### ISSUE THREAD

**Issue by RyanZhao123456** [youzan/vant-weapp#5516]
### 这个功能解决了什么问题？

stepper组件展示值变化后，组件绑定的value值没有自动更新，需要支持绑定更新

### 你期望的 API 是什么样子的？

希望能与Vant 4组件中功能保持一致

**Comment by RyanZhao123456** [comment]
当前使用的是vant weapp 1.10.23版本

**Comment by johnsonwong666** [comment]
加了bind:change吗？ 在这里更新你的值

**Comment by RyanZhao123456** [comment]
是因为我这边stepper组件外层有个列表循环，bind:change方法的参数没法定位在具体哪一条数据，我这种该如何实现？

**Comment by johnsonwong666** [comment]
外层循环 把id或者索引传进回调函数里

**Comment by RyanZhao123456** [comment]
已解决；通过data-operation传递数组id，event.currentTarget.dataset.operation接收参数实现
