### ISSUE TITLE
[weapp search] bind:click-input这个事件如何触发

### ISSUE THREAD

**Issue by liumuz** [youzan/vant-weapp#5517]
### 重现链接

bind:click-input这个事件如何触发

### Vant Weapp 版本

1.10.23

### 描述一下你遇到的问题。

bind:click-input这个事件如何触发

### 重现步骤

bind:click-input这个事件如何触发

**Comment by johnsonwong666** [comment]
<img width="706" alt="image" src="https://github.com/youzan/vant-weapp/assets/64689255/24f3fb07-38d0-4f47-8440-64357689efcc">

<img width="296" alt="image" src="https://github.com/youzan/vant-weapp/assets/64689255/19b70ec7-e0ee-4a3d-bcf7-e662b4e1174b">

点击搜索区域时触发


<br class="Apple-interchange-newline">
