### ISSUE TITLE
van-uploader 组件在 小程序基础库3.0.0 中无法被唤起，ios，微信开发者工具中都无法被使用

### ISSUE THREAD

**Issue by frjacson** [youzan/vant-weapp#5518]
### 重现链接

<img width="1219" alt="image" src="https://github.com/youzan/vant-weapp/assets/52193320/62f49991-f5d8-433e-b562-710339c11ed5">

### Vant Weapp 版本

1.10.23

### 描述一下你遇到的问题。

1. 使用van-uploader组件，在微信基础库版本3.0.0中无法被唤起，但是在之前的基础库版本比如2.32.3中可以使用

### 重现步骤

1. 点击图片上传按钮

### 设备/浏览器

iphone13真机，微信开发者工具

**Comment by FishShine** [comment]
+1 ,突然不能使用
![image](https://github.com/youzan/vant-weapp/assets/97282484/20b120ba-51ef-4867-be73-ff13c06686d0)

**Comment by xiaoma-FrontEnd** [comment]
2.30.4 真机上无法使用

**Comment by frjacson** [comment]
> +1 ,突然不能使用 ![image](https://user-images.githubusercontent.com/97282484/260881901-20b120ba-51ef-4867-be73-ff13c06686d0.png)

基础库现在是不是都是3.0.0了，所以大部分手机上都无法使用了

**Comment by sean-lgt** [comment]
我也遇到这个问题了  大部分手机都无法唤起

**Comment by johnsonwong666** [comment]
https://developers.weixin.qq.com/community/develop/doc/0008ac24980978d00f30fd32f66c00?source=templatec

在社区上提问了，在使用组件前，开发者自行完成处理隐私协议。

**Comment by frjacson** [comment]
> https://developers.weixin.qq.com/community/develop/doc/0008ac24980978d00f30fd32f66c00?source=templatec
> 
> 在社区上提问了，在使用组件前，开发者自行完成处理隐私协议。

好的，感谢！

**Comment by sean-lgt** [comment]
> https://developers.weixin.qq.com/community/develop/doc/0008ac24980978d00f30fd32f66c00?source=templatec
> 
> 在社区上提问了，在使用组件前，开发者自行完成处理隐私协议。

小程序这帮开发员整天没事找事，现在又恢复了，可以上传了
