### ISSUE TITLE
[Bug Report] 日历组件 动态更改max-date后 滑动日历后 日历副标题（年月）不动态更新

### ISSUE THREAD

**Issue by lizhousheng** [youzan/vant-weapp#5519]
### 重现链接

https://vant-contrib.gitee.io/vant-weapp/#/calendar

### Vant Weapp 版本

1.10.23

### 描述一下你遇到的问题。

[Bug Report] 日历组件 动态更改max-date后 滑动日历后 日历副标题（年月）不动态更新

### 重现步骤

1 平铺日历组件
2 初始化最大显示时间为一个月
3 动态更嘎最大显示时间未一年
4 滑动后副标题只更新后一个月 其他月份未更新

**Comment by landluck** [comment]
`v1.10.24` 已发布
