### ISSUE TITLE
小程序dropdown-menu下拉菜单报错X(D.utils).bem is not a function

### ISSUE THREAD

**Issue by scancode911** [youzan/vant-weapp#5522]
### 重现链接

![381ccd1e6ed3d5942a3d7023410a01c](https://github.com/youzan/vant-weapp/assets/105727286/f80761b2-3e09-42fd-8aea-07e73a3ffdad)

### Vant Weapp 版本

1.10.23

### 描述一下你遇到的问题。

![381ccd1e6ed3d5942a3d7023410a01c](https://github.com/youzan/vant-weapp/assets/105727286/8bc6e5f1-b458-4253-a4a8-ff69aad0f20c)

### 重现步骤

进到有下拉菜单的页面 点击下拉菜单就报错

### 设备/浏览器

微信小程序真机上出现的问题,  在开发者工具上没问题
```[tasklist]
### Tasks
```

**Comment by johnsonwong666** [comment]
是什么设备、平台呢？手上机器没有复现。bem一般是作用在标签名补充类名方法等，可以自行debug看一下。

**Comment by scancode911** [comment]
> 是什么设备、平台呢？手上机器没有复现。bem一般是作用在标签名补充类名方法等，可以自行调试一下。

所有手机的体验版都会报这个错, 开发工具和真机调试都没问题debug都没办法
进一步发现 所有和popup都报错

**Comment by johnsonwong666** [comment]
> > 是什么设备、平台呢？手上机器没有复现。bem一般是作用在标签名补充类名方法等，可以自行调试一下。
> 
> 所有手机的体验版都会报这个错, 开发工具和真机调试都没问题debug都没办法 进一步发现 所有和popup都报错

影响使用效果嘛？可以提供一个小程序代码片段来看一下嘛

**Comment by scancode911** [comment]
> > > 是什么设备、平台呢？手上机器没有复现。bem一般是作用在标签名补充类名方法等，可以自行调试一下。
> > 
> > 
> > 所有手机的体验版都会报这个错, 开发工具和真机调试都没问题debug都没办法 进一步发现 所有和popup都报错
> 
> 影响使用效果嘛？可以提供一个小程序代码片段来看一下嘛
非常影响 
感觉与项目有关, 我新建一个项目使用同版本的组件和同基础库是没问题的
```
//页面
<van-dropdown-menu active-color="#066DFF">
  <van-dropdown-item value="{{ distances }}"  data-name="distances" options="{{ distancesOptions}}" bindchange="downChange" />
  <van-dropdown-item value="{{ workTypeName }}" title="{{workTypeName===''?'岗位':''}}" data-name="workTypeName" options="{{ workTypeNameOptions}}" bindchange="downChange" />
</van-dropdown-menu>
//数据
{
    distances: "",
    distancesOptions: [
      {
        value: "",
        text: "距离不限"
      }, {
        value: "1",
        text: "1公里"
      }, {
        value: "3",
        text: "3公里"
      }, {
        value: "5",
        text: "5公里"
      }, {
        value: "10",
        text: "10公里"
      }
    ],
    filter: "1",
    filterOptions: [
      {
        value: "1",
        text: "默认排序"
      },
      {
        value: "2",
        text: "当前位置"
      },
      {
        value: "3",
        text: "定位学校"
      },
    ],
}

```

**Comment by scancode911** [comment]
> 

找到原因了  是因为我项目中有个页面开启Skyline ,  关闭后就没问题了
[https://developers.weixin.qq.com/miniprogram/dev/framework/runtime/skyline/features.html](url)
<img width="771" alt="ad160a9078a41bd851a599c0a1a3fc2" src="https://github.com/youzan/vant-weapp/assets/105727286/6826e217-b3d5-4eee-b946-dc1eda5f95cb">

**Comment by scancode911** [comment]
@johnsonwong666  所以为什么开启Skyline后popup就会出问题? 后续迭代会解决吗?
