### ISSUE TITLE
[Feature Request] vant-button组件需要支持bindagreeprivacyauthorization

### ISSUE THREAD

**Issue by a1029382825** [youzan/vant-weapp#5523]
### 这个功能解决了什么问题？

解决微信[关于小程序隐私保护指引设置的公告](https://developers.weixin.qq.com/community/develop/doc/00042e3ef54940ce8520e38db61801?source=indexnew)中的隐私同意上报

### 你期望的 API 是什么样子的？
```
<van-button open-type="agreePrivacyAuthorization" bind:agreeprivacyauthorization="handleAgreePrivacyAuthorization">同意</van-button>
```

**Comment by landluck** [comment]
`v1.10.24` 已发布
