### ISSUE TITLE
[Bug Report] van-progress显示异常

### ISSUE THREAD

**Issue by jinyalong** [youzan/vant-weapp#5525]
### 重现链接

uniapp编译到微信小程序中，在van-tab下面使用van-progress

### Vant Weapp 版本

v1.10.23

### 描述一下你遇到的问题。

切换到不同的tab下面，同一个进度显示的长度不一样，同时进度为0时会溢出左边屏幕
在一个tab下面
![image](https://github.com/youzan/vant-weapp/assets/53113006/965a6e74-a48a-4aa3-bd80-85e2b6634f93)
在第二个tab下面
![image](https://github.com/youzan/vant-weapp/assets/53113006/c5afa4d4-5183-4801-9df0-a3ab1beb3a0c)

### 重现步骤

切换tab

### 设备/浏览器

微信客户端

**Comment by johnsonwong666** [comment]
非原生小程序平台产生的问题暂时不会解决，可能是一些编译的问题，请将issue提到对应的仓库下。
