### ISSUE TITLE
请问，如何修改van-grid-item背景颜色？

### ISSUE THREAD

**Issue by GXlaishengcai** [youzan/vant-weapp#5528]
### 这个功能解决了什么问题？

无法修改自定义van-grid-item背景颜色和导圆角。

### 你期望的 API 是什么样子的？

 <van-grid class="van-grid2" center="true" gutter="12"  :column-num="2" :border="false">
        <van-grid-item class="grid-item"  use-slot v-for="(item, index) in imgUrls" :key="index" >
          <div class="div-sub-grid">
             <van-image class="van-image" width="60" height="60" :src="item" />
         </div>
       </van-grid-item>
 </van-grid>

无法通过class="grid-item"修改van-grid-item的背景颜色和导圆角，van-grid-item默认一直显示白色。

**Comment by johnsonwong666** [comment]
<img width="1285" alt="image" src="https://github.com/youzan/vant-weapp/assets/64689255/507db844-9feb-4ab6-9a07-412389122b9f">
<img width="880" alt="image" src="https://github.com/youzan/vant-weapp/assets/64689255/907bf3a7-c729-47cf-b1fb-031a52cd364b">
<img width="906" alt="image" src="https://github.com/youzan/vant-weapp/assets/64689255/148e5937-b51a-4f5d-86b2-6c7409086cf7">

使用外部样式类
