### ISSUE TITLE
[Feature Request] 能否给一个小程序版本的 【无限级或者4-5级的】 Cascader 级联选择的异步加载示例呢？

### ISSUE THREAD

**Issue by dlz5257** [youzan/vant-weapp#5530]
### 这个功能解决了什么问题？

1. 现在都23年了 在网络基本就没有 小程序版本Cascader组件的使用示例呢，尤其是无限级的异步加载；
2. 好多人都在问，但是没有相关的解决方案。
3. 如果json树形数据量大的话，一次性加载，Cascader会很卡，所有异步加载示例很有必要。
4. 希望能集成到微信小程序demo里面，谢谢。

### 你期望的 API 是什么样子的？

无限级的异步加载

**Comment by johnsonwong666** [comment]
现在文档上有异步加载的示例
<img width="1044" alt="image" src="https://github.com/youzan/vant-weapp/assets/64689255/15b532de-566f-4cfc-aa00-b5311eac4393">
每次异步接口回调中去set数据
