### ISSUE TITLE
[Bug Report] image组件无法实现右下角对齐

### ISSUE THREAD

**Issue by yik7707** [youzan/vant-weapp#5535]
### 重现链接

代码片段：https://developers.weixin.qq.com/s/XeqAFRme7pKi

### Vant Weapp 版本

1.10.24

### 描述一下你遇到的问题。

使用image组件这种情况下有点尴尬
由来，我想实现移除对齐右下角的样式
使用view包裹发现高度不一样，如图：
![image](https://github.com/youzan/vant-weapp/assets/74293458/c93eb47f-d053-4547-9d68-ba7983d83a69)
发现是van-image占用的下半部分（具体节点没审查出来是哪里占用的），如图：
![image](https://github.com/youzan/vant-weapp/assets/74293458/30dfdaf4-8ba1-42a2-9e16-a145c28bee58)
这时在image组件加上custom-class position:relative也并没有用，因为没有slot插槽可以放入移除的view

后续发现是：.van-image{display:inline-block;position:relative}，的inline-block，变为block就没有溢出的现象了
![image](https://github.com/youzan/vant-weapp/assets/74293458/bcbb6564-d1af-48ce-90fe-6f5601bdcc94)

### 重现步骤

如题

**Comment by johnsonwong666** [comment]
image-layer 加个 font-size: 0

**Comment by yik7707** [comment]
> image-layer 加个 font-size: 0

请问不能将问题源码修复一下吗
