### ISSUE TITLE
[Bug Report] 在此处重置为[ ] 会导致再次调用reset 时无法回到初始值

### ISSUE THREAD

**Issue by wayw** [youzan/vant-weapp#5542]
### 重现链接

如下图

### Vant Weapp 版本

1.10.25

### 描述一下你遇到的问题。

![1693825899477](https://github.com/youzan/vant-weapp/assets/24749601/9649faf1-d5b4-4fba-abd1-81dc67cb1531)
在此处重置为[ ] 会导致再次调用reset 时无法回到初始值
![1693825931597](https://github.com/youzan/vant-weapp/assets/24749601/6c64d409-f20f-4b7f-8795-af74f611b2ba)

### 重现步骤

调用reset

**Comment by wayw** [comment]
![1693826041366](https://github.com/youzan/vant-weapp/assets/24749601/c08b9db1-a323-4656-9156-e2d7ac0fadfe)
calendar 组件

**Comment by wayw** [comment]
![image](https://github.com/youzan/vant-weapp/assets/24749601/993a6805-72c0-4487-b3f9-c70c8994906e)
![image](https://github.com/youzan/vant-weapp/assets/24749601/bd71a955-a361-460b-867c-daef2a612ff6)

**Comment by wayw** [comment]
> ![图像](https://user-images.githubusercontent.com/24749601/265579296-993a6805-72c0-4487-b3f9-c70c8994906e.png) ![图像](https://user-images.githubusercontent.com/24749601/265579356-bd71a955-a361-460b-867c-daef2a612ff6.png)

这样改动较小

**Comment by landluck** [comment]
`v1.11.0` 已修复
