### ISSUE TITLE
popup组件在小程序扫二维码和体验版报错

### ISSUE THREAD

**Issue by yunguang** [youzan/vant-weapp#5543]
### 重现链接

查看popup组件中的popup.wxml，没有引入wxs

### Vant Weapp 版本

1.10.25

### 描述一下你遇到的问题。

**问题：**
popup组件在小程序扫二维码和体验版报错： X(...).bem() is not a function

**原因：**
popup组件中的popup.wxml中没有引入
`<wxs src="../wxs/utils.wxs" module="utils" />
<wxs src="./index.wxs" module="computed" />`

希望赶紧解决一下

### 重现步骤

引入popup组件，编译完成后扫二维码，点击无法弹出popup弹窗，打开手机的开发调试，即可看到报错信息

### 设备/浏览器

安卓，ios都会有这个问题

**Comment by johnsonwong666** [comment]
没有复现这个问题  有小程序代码片段吗？

**Comment by johnsonwong666** [comment]
检查一下是不是开启了skyline引擎
