### ISSUE TITLE
[Feature Request] 骨架屏建议增加背景色和占位图颜色

### ISSUE THREAD

**Issue by changzhengithub** [youzan/vant-weapp#5544]
### 这个功能解决了什么问题？

骨架屏`van-skeleton` 只能满足背景色为白色的场景，适用场景根本无法满足其他情况，每次都为了骨架屏去单独设置一个背景色，很繁琐。建议增加两个属性，设置背景色和占位行颜色，还有考虑其他颜色时样式是否有问题。真想不懂设计这个组件时就只考虑白色背景吗？

### 你期望的 API 是什么样子的？

```xml
<van-skeleton title row="3" bg="#f2f2f2" row-color="#fff" />
```

**Comment by johnsonwong666** [comment]
v1.11.0 版本补充了文档，通过自定义样式类控制
