### ISSUE TITLE
demo跑不起来

### ISSUE THREAD

**Issue by KearLiao** [youzan/vant-weapp#5545]
### 重现链接

<img width="665" alt="image" src="https://github.com/youzan/vant-weapp/assets/10768739/a4e679d5-de65-4e6e-9d92-9269e02840e3">

### Vant Weapp 版本

1.10.5

### 描述一下你遇到的问题。

<img width="665" alt="image" src="https://github.com/youzan/vant-weapp/assets/10768739/54ff7a4e-5941-416a-9e23-7f36e487346d">
npm run dev失败

### 重现步骤

<img width="665" alt="image" src="https://github.com/youzan/vant-weapp/assets/10768739/0f5f25a9-8e12-4869-be20-2e68e3520743">

### 设备/浏览器

所有

**Comment by KearLiao** [comment]
111

**Comment by KearLiao** [comment]
111

**Comment by KearLiao** [comment]
111

**Comment by KearLiao** [comment]
2222222222222

**Comment by johnsonwong666** [comment]
尝试更换一下node版本 我的是node16.14.0
