### ISSUE TITLE
icon生成问题

### ISSUE THREAD

**Issue by tkggusraqk** [youzan/vant-weapp#555]
**描述一下问题**
van-field 生成的结果有问题，icon样式会重复生成：

#shadow-root
<viewbind:tap="onClick"class="field-index--van-field__icon van-icon van-icon van-icon-icon van-icon-icon iconfont iconfont icon-Close icon-Close"style="; "></view>
</van-icon>

**截图**

**环境**
 - 设备: iphone6
 - 基础库版本: 2.2.5
 - Vant Weapp 版本:0.3.1

**Comment by chenjiahan** [comment]
这个是微信生成的，代码中并没有声明重复的 class
