### ISSUE TITLE
Calendar日历 组件 星期几 能加上作为作为组件的属性？

### ISSUE THREAD

**Issue by Moss-Lee** [youzan/vant-weapp#5550]
### 这个功能解决了什么问题？

解决不支持多语言 通过组件属性更换

### 你期望的 API 是什么样子的？

<van-calendar default-weeks="{{ ['一', '二', .......] }}"

**Comment by Moss-Lee** [comment]
谢谢

**Comment by johnsonwong666** [comment]
多语言后续再支持
