### ISSUE TITLE
[Bug Report] 小程序Cascader组件选完不回收

### ISSUE THREAD

**Issue by lichengxian** [youzan/vant-weapp#5551]
### 重现链接

就是官网提供的基础用法的代码，选择完二级选项后，无法自动回收弹窗组件

### Vant Weapp 版本

1.10.25

### 描述一下你遇到的问题。

就是官网提供的基础用法的代码，选择完二级选项后，无法自动回收弹窗组件

### 重现步骤

就是官网提供的基础用法的代码，选择完二级选项后，无法自动回收弹窗组件

### 设备/浏览器

最新版微信开发者工具1.06

**Comment by johnsonwong666** [comment]
没有复现 提供一下小程序代码片段、设备、基础库版本等信息。

**Comment by lichengxian** [comment]
小程序代码片段是官方提供的基础用法代码，新建page复制粘贴进去
设备是win10的微信开发者工具稳定版v1.06，模拟器上就不能自动回收
基础版本库3.0.1

**Comment by chw888586** [comment]
请问解决了吗  好像还是有这个问题

**Comment by chw888586** [comment]
请问解决了吗  好像还是有这个问题
