### ISSUE TITLE
uploader组件 视频无法预览

### ISSUE THREAD

**Issue by lilin87788** [youzan/vant-weapp#5552]
### 重现链接

官方的demo我打开也一样

https://github.com/youzan/vant-weapp/assets/1483811/ce8ef3ee-6109-4eb5-9376-c4177935dd08

![3351694501201_ pic](https://github.com/youzan/vant-weapp/assets/1483811/4a4b7b31-6f02-490a-bf29-f33b6c1819a8)

### Vant Weapp 版本

我自己开发使用的是最新的版本1.10.25

### 描述一下你遇到的问题。

我在微信的vant演示小程序上，使用uploader组件选择完视频，视频无法预览播放

### 重现步骤

苹果手机异常
安卓手机正常
1、打开微信
2、搜索vant
3、打开vant小程序
4、选择uploader组件
5、选择上传视频
6、选择视频
7、完成后点击视频无法预览播放

### 设备/浏览器

我在iPhone上遇到了这个问题

**Comment by lilin87788** [comment]
我试了很多次，也直接在微信使用了官方的demo

**Comment by johnsonwong666** [comment]
#5454  类似的issue。不能解决吗？

**Comment by lilin87788** [comment]
我没有解决，然后我自己的代码也没有解决，其实这个地方对我影响蛮大的

**Comment by johnsonwong666** [comment]
官方的demo非常久的历史了，很久没有更新。使用最新版本vant-weapp 提供一下复现代码片段、设备型号、基础库版本等，或者可以自己debug一下，涉及的代码应该也是上面提到的issue附近。

**Comment by johnsonwong666** [comment]
由于长时间未提供复现代码片段，此issue暂时关闭，若能复现请提供复现代码片段协助排查。
