### ISSUE TITLE
Vant Popup 在真机上出现 bem is not a function 没有开启 Skyline

### ISSUE THREAD

**Issue by kindfarmer** [youzan/vant-weapp#5553]
### 重现链接

<van-popup
  show="{{ show }}"
  position="top"
  custom-style="height: 20%;"
  bind:close="onClose"
/>

### Vant Weapp 版本

1.10.25

### 描述一下你遇到的问题。

开发者工具正常，真机报错
MiniProgramError
X(D.utils).bem is not a function. (In 'X(D.utils).bem("popup",[D.position,{round:D.round,safe:D.safeAreaInsetBottom,safeTop:D.safeAreaInsetTop,safeTabBar:D.safeAreaTabBar}])', 'X(D.utils).bem' is undefined)
TypeError: X(D.utils).bem is not a function. (In 'X(D.utils).bem("popup",[D.position,{round:D.round,safe:D.safeAreaInsetBottom,safeTop:D.safeAreaInsetTop,safeTabBar:D.safeAreaTabBar}])', 'X(D.utils).bem' is undefined)

### 重现步骤

真机进入开发版本直接报错

### 设备/浏览器

开发者工具 RC1.06 2308291 基础库 3.0.1

**Comment by kindfarmer** [comment]
因为有glass-easel新版微信小程序组件框架的问题

**Comment by CourageAndWisdom** [comment]
我的也有问题，体验版不行。开发版本可以！

**Comment by CourageAndWisdom** [comment]
![94414b6f2b95dfd64c60f0d80b7d482e](https://github.com/youzan/vant-weapp/assets/47654609/e917e344-c27d-4e8d-b077-ebf080536af6)

开发者根据可以，预览不行，体验版不行

**Comment by panghuohz** [comment]
怎么解决
