### ISSUE TITLE
关于微信小程序的最新改动隐私协议

### ISSUE THREAD

**Issue by shuanghan9zhou** [youzan/vant-weapp#5554]
### 重现链接

随便一个项目中使用文件上传组件
"usingComponents": {
  "van-uploader": "@vant/weapp/uploader/index"
}

### Vant Weapp 版本

1.10.25

### 描述一下你遇到的问题。

因为最新小程序 关于隐私协议的改动  针对有关于uploader，Area进行测试    在第一次关于uploader尝试的 就出现了问题   uploader组件失效    原因是因为哪怕是bind:before-read事件也是在触发微信隐私协议相关接口以后去调用的。
现在需要一个新的事件置于点击事件触发时 未进行微信隐私接口调用的时候
已便于触发我们根据项目需要所编写的自身有关于隐私协议的模态框

https://developers.weixin.qq.com/miniprogram/dev/framework/user-privacy/PrivacyAuthorize.html
涉及处理用户个人信息的小程序开发者，需通过弹窗等明显方式提示用户阅读隐私政策等收集使用规则。

为规范开发者的用户个人信息处理行为，保障用户合法权益，微信要求开发者主动同步微信当前用户已阅读并同意小程序的隐私政策等收集使用规则，方可调用微信提供的隐私接口。

特别注意：

以下指南中涉及的 getPrivacySetting、onNeedPrivacyAuthorization、requirePrivacyAuthorize 等接口，目前仍处于 Beta 调试阶段，目前并未按预期返回正确的结果。开发者目前可以先阅读本指南文档和接口文档进行理解，平台将会尽快正式上线这些接口以及调试方法，上线后会在本指南文档和[相关公告](https://developers.weixin.qq.com/community/develop/doc/00042e3ef54940ce8520e38db61801?blockType=1)中进行说明。

2023.08.22更新：

以下指南中涉及的 getPrivacySetting、onNeedPrivacyAuthorization、requirePrivacyAuthorize 等接口目前可以正常接入调试。调试说明：

在 2023年9月15号之前，在 app.json 中配置 __usePrivacyCheck__: true 后，会启用隐私相关功能，如果不配置或者配置为 false 则不会启用。

在 2023年9月15号之后，不论 app.json 中是否有配置 __usePrivacyCheck__，隐私相关功能都会启用。

### 重现步骤

在 2023年9月15号之前，在 app.json 中配置 __usePrivacyCheck__: true 后，会启用隐私相关功能，如果不配置或者配置为 false 则不会启用。

在 2023年9月15号之后，不论 app.json 中是否有配置 __usePrivacyCheck__，隐私相关功能都会启用。

随便一个项目符合上述规则然后使用uploader功能
https://developers.weixin.qq.com/miniprogram/dev/framework/user-privacy/PrivacyAuthorize.html

关于微信隐私协议相关接口：
https://developers.weixin.qq.com/miniprogram/dev/framework/user-privacy/plugin-intro.html

**Comment by shuanghan9zhou** [comment]
低于 2.32.3 版本的基础库未集成隐私相关功能，也不会拦截隐私接口调用

**Comment by shuanghan9zhou** [comment]
需要那拿2.32.3 以后的版本测试

**Comment by shuanghan9zhou** [comment]
低于 2.32.3 版本的基础库未集成隐私相关功能，也不会拦截隐私接口调用，需要用2.32.3 之后的版本复现

**Comment by johnsonwong666** [comment]
隐私协议的获取开发者在调用相关api或者组件前自行完成。
