### ISSUE TITLE
新版uploader从chooseImage改为chooseMedia后，在ios企微客户端无法使用

### ISSUE THREAD

**Issue by wangwei-van** [youzan/vant-weapp#5555]
### 重现链接

![image](https://github.com/youzan/vant-weapp/assets/16934897/66542a05-fc97-4e16-bc6d-9b96629586f0)

### Vant Weapp 版本

1.10.25

### 描述一下你遇到的问题。

上传图片时点击无反应

### 重现步骤

使用最新的版本，在ios的企业微信里直接点击上传按钮

### 设备/浏览器

企业微信 ios

**Comment by landluck** [comment]
`v1.11.2` 已修复
