### ISSUE TITLE
新上线的button的openType="agreePrivacyAuthorization"问题

### ISSUE THREAD

**Issue by ClownZyk** [youzan/vant-weapp#5557]
### 重现链接

看了你源码，回调函数onAgreePrivacyAuthorization你好像没定义

### Vant Weapp 版本

1.10.25

### 描述一下你遇到的问题。

看了你源码，回调函数onAgreePrivacyAuthorization你好像没定义

### 重现步骤

看下button的源码就行了

**Comment by ClownZyk** [comment]
在mixin里看到这个方法，不过还是没法触发bind:agreeprivacyauthorization的回调

**Comment by johnsonwong666** [comment]
使用这个方法需要加一个好像需要加一个id

**Comment by ClownZyk** [comment]
> 使用这个方法需要加一个好像需要加一个id

我试着加了button-id和id，好像都没用

**Comment by johnsonwong666** [comment]
> > 使用这个方法需要加一个好像需要加一个id
> 
> 我试着加了button-id和id，好像都没用

发一个小程序代码片段看一下

**Comment by johnsonwong666** [comment]
由于长时间未提供复现代码，此issue暂时关闭，若能复现请附带复现代码片段以便排查。
