### ISSUE TITLE
DropdownMenu 下拉菜单多个时经常出现某一个不能点击

### ISSUE THREAD

**Issue by Myyidagit** [youzan/vant-weapp#5558]
### 重现链接

在uniapp中使用时出现

### Vant Weapp 版本

1.10.25

### 描述一下你遇到的问题。

DropdownMenu 下拉菜单多个时经常出现某一个不能点击

### 重现步骤

1、点击最右侧下拉菜单操作
2、点击第一个就不能选了

### 设备/浏览器

uniapp中使用

**Comment by Myyidagit** [comment]
问题出现在各个item互相覆盖上

**Comment by xiaoning101012** [comment]
我也遇到这个问题了， 我查到的是遮罩层那边有问题。

**Comment by johnsonwong666** [comment]
非原生小程序产生的问题暂不处理，可能是一些编译的问题，可以将问题提至官方。
