### ISSUE TITLE
[Bug Report] Tab报错：[Component] slot ““ is not found.

### ISSUE THREAD

**Issue by MoneySacon** [youzan/vant-weapp#5559]
### 重现链接

![image](https://github.com/youzan/vant-weapp/assets/144115695/20e0ac36-68ca-461e-a86a-a681e1e788d2)

### Vant Weapp 版本

1.10.25

### 描述一下你遇到的问题。

![image](https://github.com/youzan/vant-weapp/assets/144115695/275e0410-6518-4f50-893f-97b3b6abbe0d)

### 重现步骤

![image](https://github.com/youzan/vant-weapp/assets/144115695/e408d212-fd5d-4a09-9cc3-c05b17896eba)

### 设备/浏览器

微信小程序

**Comment by johnsonwong666** [comment]
这个会影响使用吗？
