### ISSUE TITLE
uniapp引入vant组件时  overlay 报错

### ISSUE THREAD

**Issue by xiaoning101012** [youzan/vant-weapp#5560]
### 重现链接

![image](https://github.com/youzan/vant-weapp/assets/30620599/8ef2e027-ae86-46e3-851f-96e1be7140c9)

### Vant Weapp 版本

1.10.5

### 描述一下你遇到的问题。

引用overlay，包括， 并且van-dropdown-menu， van-dropdown-item， van-popup 这三种也有问题

### 重现步骤

![image](https://github.com/youzan/vant-weapp/assets/30620599/bb7c46fd-0315-4c05-b64e-240f23b531b1)

**Comment by johnsonwong666** [comment]
非原生小程序产生的问题暂不处理，可能是一些编译的问题，可以将问题提至官方。
