### ISSUE TITLE
icon设置size大小不生效问题

### ISSUE THREAD

**Issue by yik7707** [youzan/vant-weapp#5562]
### 重现链接

代码片段：
https://developers.weixin.qq.com/s/mgDKrjmZ7LLn

### Vant Weapp 版本

1.10.25

### 描述一下你遇到的问题。

iconfont多色图标超过40个问题，就会变成灰色，从网上查找相关资料得出结果：
http://www.icodebang.com/article/305040，安装iconfont-tools npm可以不受40个限制所以进行了转换，引入iconfont文件到根目录但是，引入van-icon组件，设置size不生效
调试后得知是width和height设置才生效，请求适配width和height的问题
![image](https://github.com/youzan/vant-weapp/assets/74293458/3cbef85b-041f-4efc-b464-99aca9ef46c5)

### 重现步骤

如题

### 设备/浏览器

模拟器

**Comment by johnsonwong666** [comment]
icon的大小是通过size设置的，不支持width和height控制

**Comment by yik7707** [comment]
> icon的大小是通过size设置的，不支持width和height控制

能否评估可行性支持一下，因为超出40个设置颜色的限制也是中小型项目所需，增加width或者height的控制属性来解决？当设置size则width和height不生效，当设置width和height则size不生效

**Comment by johnsonwong666** [comment]
暂不支持。
