### ISSUE TITLE
[Bug Report] van-area 二级省市区无法滑动

### ISSUE THREAD

**Issue by saikete** [youzan/vant-weapp#5563]
### 重现链接

官方实例使用后按照标准文档配置，我做了：将直辖市变为二级目录，如北京，天津等
现象：columns-num 为2 的van-area无法下拉直辖市，回显同理

### Vant Weapp 版本

^1.6.8

### 描述一下你遇到的问题。

官方实例使用后按照标准文档配置，我做了：将直辖市变为二级目录，如北京，天津等
现象：columns-num 为2 的van-area无法下拉直辖市，回显同理

### 重现步骤

1.下载官方示例
2.在微信小程序中注册使用
3.省市区数据过滤（直辖市的区域提取到二级内
4.直辖市在微信小程序开发者工具内无法下拉滑动

**Comment by johnsonwong666** [comment]
尝试升级一下版本。

**Comment by saikete** [comment]
已更新到1.11.0，npm update , npm i ,构建npm包后还是同样的问题

**Comment by saikete** [comment]
已定位到问题，抽空提pr
