### ISSUE TITLE
真机预览组件不展示

### ISSUE THREAD

**Issue by guuuJIe** [youzan/vant-weapp#5568]
### 重现链接

 show: false,  

<van-action-sheet show="{{ show }}" title="账号选择" bind:close="onClose" bind:select="onSelect">
    <scroll-view style="height:{{scrollHeight*0.5}}px" scroll-y  bindscrolltolower="onScrollBottom">
      <view wx:for="{{thirdPartyArr}}" wx:key="index" style="padding: 10px 18px;display: flex;justify-content: space-between;" data-index="{{index}}" bindtap="onAccountSel">
        <text>{{item.tiktokNick}}</text>
        <image wx:if="{{item.checked}}" style="width:25px;height:25px" src="../../images/common/icon_select.png"></image>
        <image wx:else style="width:25px;height:25px" src="../../images/common/unselected.png"></image>
      </view>
    </scroll-view>
  </van-action-sheet>

### Vant Weapp 版本

1.11

### 描述一下你遇到的问题。

pop组件 calendar组件 actionsheet组件 真机不展示

### 重现步骤

点击按钮设置为true，弹窗无法展示，之后界面点击就无法响应了

### 设备/浏览器

真机12mini

**Comment by johnsonwong666** [comment]
真机上开开发模式 控制台有什么报错吗？

**Comment by johnsonwong666** [comment]
图片好像挂了 可以提供一下复现的代码片段吗

**Comment by johnsonwong666** [comment]
可以复现的话，麻烦提供一个小程序代码片段来看一下，此issue暂时关闭。
