### ISSUE TITLE
[Bug Report] 日历选择设置最大、最小可选日期卡顿

### ISSUE THREAD

**Issue by kobehqh** [youzan/vant-weapp#5569]
### 重现链接

1

### Vant Weapp 版本

1.10.25

### 描述一下你遇到的问题。

van-calendar 日历选择设置最大、最小可选日期卡顿

### 重现步骤

van-calendar 日历选择设置最大、最小可选日期卡顿

**Comment by johnsonwong666** [comment]
calendar性能优化，在vant-weapp 2.x版本 计划进行
