### ISSUE TITLE
[Bug Report] 开发工具正常，发布后不显示

### ISSUE THREAD

**Issue by eren186** [youzan/vant-weapp#5570]
### 重现链接

小程序正式版

### Vant Weapp 版本

1.110

### 描述一下你遇到的问题。

基础库3.1.1
本机调试正常 ，发布后rate不显示，小程序后台有相关错误提示。
不清楚是自己还是官方或者vant的问题 
`Cannot read properties of undefined (reading \'index\')
TypeError: Cannot read properties of undefined (reading \'index\')
at u (https://usr/common.app.js:1:31115)
at https://usr/common.app.js:1:31319
at https://usr/common.app.js:1:31296
at https://usr/miniprogram_npm/@vant/weapp/rate/index.appservice.js:1:558
at t.handleChildrenCreation (https://usr/common.app.js:1:30528)
at https://usr/common.app.js:1:30777
at C (https://usr/miniprogram_npm/@vant/weapp/rate/index.appservice.js:1:413)
at t.handleChildrenCreation (https://usr/common.app.js:1:30528)
at t.create (https://usr/common.app.js:1:30188)dex\')`

### 重现步骤

不显示

### 设备/浏览器

微信8.0.4

**Comment by johnsonwong666** [comment]
提供一个复现小程序代码片段看一下

**Comment by eren186** [comment]
`<view wx:for="{{pzylist}}">
      <mp-cell>    
      <image slot="icon" src="data:image/jpeg;base64,{{item.photo}}" style="margin-right: 16px;vertical-align: middle;width:100rpx; height: 100rpx;"></image>
      <view>{{item.xm}}</view>
      <view slot="footer" style="display:inline-flex; width: 300rpx;">
          <van-rate value="{{item.rate}}" size="25" color="#ffd21e" void-icon="star" void-color="#eee" readonly />
      </view>   
    </mp-cell>
</view>`

` data: {   
    pzylist:[]
}
 
let MyThis = this;
wx.request({
      method: "GET",
      url: ApiUrl,
      header: {
        'authorization': token,
      },
      success(res){
        console.log(res);
        if(res.statusCode===200)
        {
          MyThis.setData({
            pzylist:res.data,
          });
        } 
      },
      fail(res) {
      
      },
    })`

查看API调用记录 显示request 成功返回数据。
真机，开发工具都正常，但是线上就是报错-_-||

**Comment by eren186** [comment]
vant field 也有涉及到一个报错，不清楚是小程序基础库的问题 还是/
X(...).bem is not a function
TypeError: X(...).bem is not a function
at https://usr/appservice.app.js:663:56256
at https://usr/common.app.js:1:30767
at Object.C (https://usr/appservice.app.js:663:56047)
at https://usr/miniprogram_npm/@vant/weapp/field/index.appservice.js:1:2805
at t.handleChildrenCreation (https://usr/common.app.js:1:30528)
at https://usr/common.app.js:1:31868
at https://usr/miniprogram_npm/@vant/weapp/field/index.appservice.js:1:2711
at t.handleChildrenCreation (https://usr/common.app.js:1:30528)
at https://usr/common.app.js:1:30777
at https://usr/miniprogram_npm/@vant/weapp/field/index.appservice.js:1:2269

**Comment by johnsonwong666** [comment]
你是不是使用了微信的那个skyline渲染引擎？

**Comment by eren186** [comment]
> 你是不是使用了微信的那个skyline渲染引擎？

skyline 大坑 ，没有使用。
用的webview

**Comment by johnsonwong666** [comment]
你直接在原生页面使用组件有问题吗？

**Comment by eren186** [comment]
> 你直接在原生页面使用组件有问题吗？
原生页面出现的

**Comment by johnsonwong666** [comment]
小程序开发者工具预览正常吗？你那个接口在线上是否正常返回 ？我这边试了一下没什么问题。
可以的话按照下面的文档，提供一个可复现的代码片段来看一下。https://developers.weixin.qq.com/minigame/dev/devtools/minicode.html

**Comment by CourageAndWisdom** [comment]
我也有这个问题，版本1.11.1不行，试了好几个版本都不行！报错index为undefined。看了一下源码，wxml里有index，但是在js文件里没有找到

**Comment by johnsonwong666** [comment]
> 我也有这个问题，版本1.11.1不行，试了好几个版本都不行！报错index为undefined。看了一下源码，wxml里有index，但是在js文件里没有找到

index 是wx:for 提供的。
可以的话按照下面的文档，提供一个可复现的代码片段来看一下。https://developers.weixin.qq.com/minigame/dev/devtools/minicode.html

**Comment by CourageAndWisdom** [comment]
> > 我也有这个问题，版本1.11.1不行，试了好几个版本都不行！报错index为undefined。看了一下源码，wxml里有index，但是在js文件里没有找到
> 
> index 是wx:for 提供的。 可以的话按照下面的文档，提供一个可复现的代码片段来看一下。https://developers.weixin.qq.com/minigame/dev/devtools/minicode.html


<van-rate
            value="{{ detailData.wyScore }}"
            size="{{ 25 }}"
            color="#ffd21e"
            void-icon="star"
            void-color="#eee"
            data-code="pj"
            bind:change="onChange"
          />

**Comment by CourageAndWisdom** [comment]
在微信开发者工具里正常，预览即开发者版本正常，就是体验版不行。

**Comment by CourageAndWisdom** [comment]
<van-rate
            value="{{ detailData.wyScore }}"
            size="{{ 25 }}"
            color="#ffd21e"
            void-icon="star"
            void-color="#eee"
            data-code="pj"
            bind:change="onChange"
          />

**Comment by CourageAndWisdom** [comment]
`<van-rate
            value="{{ detailData.wyScore }}"
            size="{{ 25 }}"
            color="#ffd21e"
            void-icon="star"
            void-color="#eee"
            data-code="pj"
            bind:change="onChange"
          />`

**Comment by johnsonwong666** [comment]
> `<van-rate value="{{ detailData.wyScore }}" size="{{ 25 }}" color="#ffd21e" void-icon="star" void-color="#eee" data-code="pj" bind:change="onChange" />`

有没有用skyline引擎吗? 是否在uniapp或者其他开发平台上开发，尽可能提供多一点信息吧。

**Comment by CourageAndWisdom** [comment]
为啥，不能用截图。我用的是renderer: skyline   是在微信开发者工具上开发的，工具版本是1.06.2308310

**Comment by johnsonwong666** [comment]
不要使用renderer: skyline 看是否可以

**Comment by CourageAndWisdom** [comment]
我换成"renderer": "webview",  体验版，直接空白，进不去。还不知道啥原因

**Comment by CourageAndWisdom** [comment]
哎！改成了renderer: skyline还是报错，说index为undefined

**Comment by johnsonwong666** [comment]
我预估是skyline这个引擎有什么不兼容的地方，所以让你试试不要用这个是否可以。renderer这个字段是必须的？不要加看下呢？

**Comment by CourageAndWisdom** [comment]
哎！改成了renderer: webview还是报错，说index为undefined 。前一条发错了，不好意思。skyline是改成webview还是报错

**Comment by johnsonwong666** [comment]
页面能否进去？能看到组件的prop之类的信息吗？方便截图看看吗？

**Comment by CourageAndWisdom** [comment]
![8738f79229c0bd5e0fe9162ad42896e3](https://github.com/youzan/vant-weapp/assets/47654609/2816f035-f781-41eb-b976-1bb3f2d797ed)

**Comment by CourageAndWisdom** [comment]
这预览报错，开发者工具上正常

**Comment by CourageAndWisdom** [comment]
真机调试也可以，预览，以及体验版报错

**Comment by johnsonwong666** [comment]
点到wxml那一栏 然后找到van-rate 节点截图一下 tree-detail 看看  类似这样
![img_v2_44a8473d-0e5f-42a7-938d-4fed38b36bcg](https://github.com/youzan/vant-weapp/assets/64689255/b3dfbbd7-0e73-43c9-9942-3f6aa7261156)

**Comment by CourageAndWisdom** [comment]
看不到，哪个节点，整个页面空白了。有时候报那个index错误。有时候报

**Comment by CourageAndWisdom** [comment]
![b5b7b90b6ec40fd377f808f304885c44](https://github.com/youzan/vant-weapp/assets/47654609/215b5b28-1fa6-469c-a169-6bf924ed7ad5)

**Comment by johnsonwong666** [comment]
发你的个人微信或者qq 到我的邮箱 1067100250@qq.com 吧 我加一下你 这里沟通不是特别顺畅

**Comment by johnsonwong666** [comment]
与 @CourageAndWisdom  了解后。应该是skyline引起的问题，切换成 webview模式 + 最新版小程序基础库，没有报错了。 @eren186 你也试试这样看行不行。
