### ISSUE TITLE
真机输入框type类型

### ISSUE THREAD

**Issue by Kewang80** [youzan/vant-weapp#5571]
### 重现链接

<van-field label="密码：" value="{{ password }}" type="{{typeValue}}" focus="{{focue}}" placeholder="请输入密码" bind:input="passHandler" right-icon="{{iconType}}" right-icon-class="icon_txt" border="{{ false }}" bind:click-icon="iconClick" />
iconClick() {
    if (this.data.iconType == 'eye' || this.data.typeValue == 'text') {
      this.setData({ iconType: 'closed-eye', typeValue: 'password' })
    } else {
      this.setData({ iconType: 'eye', typeValue: 'text' })
    }
  },

### Vant Weapp 版本

1.10.25

### 描述一下你遇到的问题。

输入框组件点击右侧图标改变输入框类型时，password转text类型，内容自动清空，改变时给自动聚焦时。内容与placeholder重叠显示

### 重现步骤

输入框组件点击右侧图标改变输入框类型时，password转text类型，内容自动清空，改变时给自动聚焦时。内容与placeholder重叠显示

### 设备/浏览器

ios

**Comment by johnsonwong666** [comment]
wxml代码怎么写的

**Comment by Kewang80** [comment]
<van-field label="密码：" value="{{ password }}" type="{{typeValue}}" placeholder="请输入密码" bind:input="passHandler" right-icon="{{iconType}}" right-icon-class="icon_txt" border="{{ false }}" bind:click-icon="iconClick" />

**Comment by Kewang80** [comment]
“<van-field label="密码：" value="{{ password }}" type="{{typeValue}}" placeholder="请输入密码" bind:input="passHandler" right-icon="{{iconType}}" right-icon-class="icon_txt" border="{{ false }}" bind:click-icon="iconClick" />”

**Comment by Kewang80** [comment]
**_<van-field label="密码：" value="{{ password }}" type="{{typeValue}}" placeholder="请输入密码" bind:input="passHandler" right-icon="{{iconType}}" right-icon-class="icon_txt" border="{{ false }}" bind:click-icon="iconClick" `/>_**

**Comment by johnsonwong666** [comment]
按照你的说法 写一了一个测试demo 没有复现 感觉是不是跟机器有关系 微信社区有相关的讨论 
https://developers.weixin.qq.com/community/search?query=input%2520placeholder%2520%25E9%2587%258D%25E5%258F%25A0&page=1&block=0&random=1696850453104&type=1
可以的话像我这样提供一个完整的复现代码来看一下
https://developers.weixin.qq.com/s/D71fgQmt7rLX

**Comment by johnsonwong666** [comment]
由于较长时间没有提供复现代码片段，此issue暂时关闭，若能复现请附带复现代码片段排查。
