### ISSUE TITLE
field 组件 在微信小程序预览和体验版的时候，引入页面全部报错，希望你们可以重视这个问题

### ISSUE THREAD

**Issue by duyu123** [youzan/vant-weapp#5572]
### 重现链接

{
  "component": true,
  "usingComponents": {
    "van-field": "@vant/weapp/field/index",
    "van-cell-group": "@vant/weapp/cell-group/index",
    "van-uploader": "@vant/weapp/uploader/index",
    "van-image": "@vant/weapp/image/index",
    "van-button": "@vant/weapp/button/index"
  }
}

<van-field
      value="{{ userName }}"
      placeholder="请输入姓名"
      label="姓名"
      border="{{ false }}"
      bind:change="onNameChange"
    />
    <van-field
      value="{{ idCard }}"
      placeholder="请输入身份证号"
      label="身份证号"
      type="idcard"
      border="{{ false }}"
      bind:change="onNumberChange"
    />

### Vant Weapp 版本

1.11.0

### 描述一下你遇到的问题。

![9ba8b34b42d7203fd6e0ea5edb4b1b1](https://github.com/youzan/vant-weapp/assets/21079129/d32397f7-a7ad-4f4d-b612-032ec33624fc)
使用输入框组件，体验版和预览界面全部渲染失败，

### 重现步骤

打开界面

**Comment by johnsonwong666** [comment]
是否使用了 微信的skyline 引擎

**Comment by johnsonwong666** [comment]
详细的说一下你的环境吧 weapp版本 1.11.0 基础库3.1.1 小程序预览是正常的。

**Comment by Shi123cui** [comment]
预览和本地测试都是正常的，提交测试版本就报这个错误

**Comment by johnsonwong666** [comment]
测试版的有问题的话 看是否能够通过dist包 在开发者工具打开看一下有什么问题 这个X(...)bem 的报错 之前有人反馈过是使用了微信的skyline 引擎 排除一下是不是这个错误  就目前的信息的话很难排查是什么问题。

**Comment by johnsonwong666** [comment]
可以把你的个人qq或者微信 发送到 1067100250@qq.com ，我加一下你，这里沟通效率不高。

**Comment by johnsonwong666** [comment]
webview渲染 + 最新版小程序基础库 看行不行

**Comment by zptime** [comment]
这个解决了嘛？碰到一样的问题了，很无语呀。
使用了van-search组件，该组件内部引入了field，也会导致上述报错

**Comment by johnsonwong666** [comment]
@zptime  
不要使用skyline 使用 webview渲染 + 最新版小程序基础库 看看

**Comment by zptime** [comment]
> @zptime 不要使用skyline 使用 webview渲染 + 最新版小程序基础库 看看

没有用skyline 用的3.1.2的基础库；换成3.1.3也不行呀

**Comment by johnsonwong666** [comment]
> > @zptime 不要使用skyline 使用 webview渲染 + 最新版小程序基础库 看看
> 
> 没有用skyline 用的3.1.2的基础库；换成3.1.3也不行呀

你的联系方式发到我邮箱 1067100250@qq.com  我加一下你，这里沟通效率不高

**Comment by zptime** [comment]
> > > @zptime 不要使用skyline 使用 webview渲染 + 最新版小程序基础库 看看
> > 
> > 
> > 没有用skyline 用的3.1.2的基础库；换成3.1.3也不行呀
> 
> 你的联系方式发到我邮箱 [1067100250@qq.com](mailto:1067100250@qq.com) 我加一下你，这里沟通效率不高

已发送

**Comment by johnsonwong666** [comment]
field 组件报错误的，请先删除一下在app.json的skyline配置
<img width="816" alt="image" src="https://github.com/youzan/vant-weapp/assets/64689255/d9bb6e69-2c73-44c8-b5fc-e178b2077a08">

**Comment by zptime** [comment]
目前的解决办法就是使用webview渲染。
修改app.json配置

```json
{
    "renderer": "webview", // 修改渲染方式
    // "lazyCodeLoading": "requiredComponents", // 去除该代码
}
```

**Comment by johnsonwong666** [comment]
目前在官方提问了，等待回复，看后续怎么兼容处理，如有使用field报类似错误的，请在app.json删除 skyline渲染的相关配置。

**Comment by calfzhou** [comment]
用 vant 组件的时候就得步步为营，每引入一个类型的组件，就要赶紧提交到测试版看一下，没白屏，继续用，白屏了，赶紧删掉换其他方式。目前 vant loading 和 vant field 都踩坑了，错误各不相同。

**Comment by johnsonwong666** [comment]
> 用 vant 组件的时候就得步步为营，每引入一个类型的组件，就要赶紧提交到测试版看一下，没白屏，继续用，白屏了，赶紧删掉换其他方式。目前 vant loading 和 vant field 都踩坑了，错误各不相同。

field的问题主要是skyline的问题，目前已经给微信官方提问了，看下是什么问题 ，后面看怎么调整。目前使用需要使用webview模式和删掉lazyCodeLoading。 loading是什么问题

**Comment by calfzhou** [comment]
> > 用 vant 组件的时候就得步步为营，每引入一个类型的组件，就要赶紧提交到测试版看一下，没白屏，继续用，白屏了，赶紧删掉换其他方式。目前 vant loading 和 vant field 都踩坑了，错误各不相同。
> 
> field的问题主要是skyline的问题，目前已经给微信官方提问了，看下是什么问题 ，后面看怎么调整。目前使用需要使用webview模式和删掉lazyCodeLoading。 loading是什么问题

表现形式也是白屏了，只要 wxml 里加入 loading 的标签就会有。控制台信息如图：

![image](https://github.com/youzan/vant-weapp/assets/3761553/e1cab573-5e8d-4763-ac34-814cb5d750c2)

![image](https://github.com/youzan/vant-weapp/assets/3761553/8935c552-24eb-421f-8566-724009e6dc9b)

当时搜了半天，没找到解决方法。

没有用 skyline，一直都是用的 webview。

在开发工具里进行远程调试的时候也没有问题，只有提交到小程序平台，体验版的时候会出错。
