### ISSUE TITLE
1.10.25版本stepper 步进器无法输入小数

### ISSUE THREAD

**Issue by leoliuxd** [youzan/vant-weapp#5575]
### 重现链接

`     <view slot="" class="cell-stepper">
        <van-stepper input-width="60px" theme="round" value="{{ selectPrice }}" min="0" max="{{maxPrice}}" bind:change="priceChange" plus-class="stepper-class" minus-class="stepper-class">
        </van-stepper>
        <view style="margin-left: 20rpx;height:100rpx ; line-height: 100rpx;">￥</view>
      </view>`

### Vant Weapp 版本

1.10.25

### 描述一下你遇到的问题。

stepper 步进器无法输入小数

### 重现步骤

通过键盘在stepper的输入框输入小数，最终都会截断为整数

**Comment by leoliuxd** [comment]
补充：小程序基础库版本是3.0.2
之前vant weapp版本1.10.2，不存在无法输入小数的问题

**Comment by johnsonwong666** [comment]
设置一下 decimal-length 属性 看行不行
<img width="766" alt="image" src="https://github.com/youzan/vant-weapp/assets/64689255/dde537ec-d328-4a28-bbd2-f208f1a6a2f6">

**Comment by leoliuxd** [comment]
测试了下不可以。而且一旦设置了decimal-length，输入框就无法输入，只能通过步进器增加/减少数值

**Comment by johnsonwong666** [comment]
你是什么设备上不能输入？priceChange做了是什么事情？我这边是正常输入的。

**Comment by leoliuxd** [comment]
> 你是什么设备上不能输入？priceChange做了是什么事情？我这边是正常输入的。

  priceChange: function (event) {
    let that = this
    that.setData({
      selectPrice: event.detail
    })
  },
目前看下来ios设备小程序是有问题的。

**Comment by leoliuxd** [comment]
> 你是什么设备上不能输入？priceChange做了是什么事情？我这边是正常输入的。
     <view slot="" class="cell-stepper"> <van-stepper input-width="60px" theme="round" value="{{ selectPrice }}" min="0" max="{{maxPrice}}" bind:change="priceChange" plus-class="stepper-class" minus-class="stepper-class"> </van-stepper> <view style="margin-left: 20rpx;height:100rpx ; line-height: 100rpx;">￥</view> </view>


这里的value不能与priceChange 中的selectPrice联动。value设置为固定值如59.99之后就可以了。

**Comment by leoliuxd** [comment]
使用的姿势不对。value不要设置为bind:change中的回调值
