### ISSUE TITLE
view中 van-pop弹窗嵌套video标签 视频全屏幕播放之后 转小屏播放 发现最外层无法滚动 

### ISSUE THREAD

**Issue by ZeroYoung1104** [youzan/vant-weapp#5578]
### 重现链接

view中 van-pop弹窗嵌套video标签 视频全屏幕播放之后 转小屏播放 发现最外层无法滚动  预计van-pop通过视频横屏模式或者竖屏模式切换 布局错乱产生的 希望尽快修复

### Vant Weapp 版本

"version": "1.10.25",

### 描述一下你遇到的问题。

view中 van-pop弹窗嵌套video标签 视频全屏幕播放之后 转小屏播放 发现最外层无法滚动  预计van-pop通过视频横屏模式或者竖屏模式切换 布局错乱产生的 希望尽快修复

### 重现步骤

view中 van-pop弹窗嵌套video标签 视频全屏幕播放之后 转小屏播放 发现最外层无法滚动 

### 设备/浏览器

所有设备

**Comment by johnsonwong666** [comment]
可以提供一个最小复现代码片段看一下吗？

**Comment by johnsonwong666** [comment]
https://developers.weixin.qq.com/s/2VQTwVmg7ILE
按照你的描述写了一个demo。没有复现，可以复现的话将上方demo修改一下分享一个新的过来看一下

**Comment by johnsonwong666** [comment]
由于较长时间没有提供复现代码片段，此issue暂时关闭，若能复现请附带复现代码片段排查。
