### ISSUE TITLE
[Bug Report] picker组件动态修改选项，数量多以后选项底部高度出现问题。

### ISSUE THREAD

**Issue by laker55555** [youzan/vant-weapp#5579]
### 重现链接

 ` <van-picker id="wordpicker" columns="{{wordlist}}" active-class="picker-active" custom-class="backtransparent" visible-item-count="6"    default-index="{{0}}" bind:change="onChangeWord" />`

```
this.setData({
        list,
        wordlist,
        lastword: this.properties.lastword,
        currentWord: this.properties.lastword
 }

```
### Vant Weapp 版本

1.11.0

### 描述一下你遇到的问题。

我的功能是一个一个添加item进去的，在添加到10个以上的时候，底部的item无法正常被拖上去了。

### 重现步骤

https://github.com/youzan/vant-weapp/assets/51220558/63c0eda1-8987-4872-9aaf-39cbf2098dcb

**Comment by johnsonwong666** [comment]
按照你的说法 我写了一个demo尝试了一下  应是没有问题的 是不是样式设置的有问题   
可以的话请像我这种提供一个最小复现代码片段
https://developers.weixin.qq.com/s/2XSgyPmp7CLV

**Comment by laker55555** [comment]
我看了下，是我改了.van-picker-column__item的height和margin导致的
