### ISSUE TITLE
建议增加van-field输入框 可以过滤表情符号

### ISSUE THREAD

**Issue by 987603843** [youzan/vant-weapp#5580]
### 这个功能解决了什么问题？

后端接收表情符号会报错，有些场景不能输入表情符号

### 你期望的 API 是什么样子的？

<van-field emoji="false" />

**Comment by johnsonwong666** [comment]
前端在调接口前通过js方法过滤一下是不是就好了

**Comment by 987603843** [comment]
但是 如果是全局的接口， 每个接口的某个参数需要过滤，这种场景的话 是不是改动代价太大了😂

**Comment by johnsonwong666** [comment]
开发者通过js方法或者监听事件去改，都可以满足，目前在组件上暂时不会支持。
