### ISSUE TITLE
[Bug Report] 使用微信开发工具Audits，有【存在可点击元素的响应区域太小】的没通过提示

### ISSUE THREAD

**Issue by zimo2013** [youzan/vant-weapp#5582]
### 重现链接

无

### Vant Weapp 版本

1.10.3

### 描述一下你遇到的问题。

<img width="617" alt="image" src="https://github.com/youzan/vant-weapp/assets/8055636/6b076deb-4a01-41cf-822d-ebe3631d98c4">

使用微信开发工具Audits，体验里有很多【存在可点击元素的响应区域太小】的没通过提示，会影响小程序评测，请官方修复

### 重现步骤

无

**Comment by johnsonwong666** [comment]
icon是不是可以自行修改font-size来控制大小，或者把事件绑在外层容器上。

**Comment by zimo2013** [comment]
icon嵌在cell组件里，怎么设置
