### ISSUE TITLE
van-calendar只能点确认才能关闭？

### ISSUE THREAD

**Issue by qqakashi** [youzan/vant-weapp#5584]
### 重现链接

wxml:
<view class="personal-content-info-cell" bindtap="openCalendar">
  <van-calendar color="#3EB0B9" show="{{ show }}" bind:close="closeDialog" bind:confirm="setValue2" />
</view>
---------------------------
ts:
 openCalendar(){
    this.setData({show:true})
},

### Vant Weapp 版本

1.10.19

### 描述一下你遇到的问题。

日历弹窗无法点击右上角叉关闭，后面测试使用组件时setData无法修改show布尔值，或者是修改后自动变成第一次设置的值，注释日历组件使用view组件可修改show布尔值

### 重现步骤

<van-calendar color="#3EB0B9" show="{{ show }}" bind:close="closeDialog" bind:confirm="setValue2" />
close方法确实执行了但在this.setData回调中打印show还是true
this.setData({
      "show": false,
      reach: {...this.data.reach,arriveTime: event.detail}
    },()=>{
      console.log(this.data.reach, this.data.show);
});

**Comment by johnsonwong666** [comment]
绑定onClose事件 然后this.setData({show:false})

**Comment by qqakashi** [comment]
@johnsonwong666 可以了，日历组件不能放在行容器内使用，要放在最外层容器才能正确设置显隐，不清楚是不是小程序自己的bug

**Comment by johnsonwong666** [comment]
calendar用pop-up实现的，容器里面看看平铺模式能不能用。
