### ISSUE TITLE
二次封装van-field时 插槽失效

### ISSUE THREAD

**Issue by DarkerSU** [youzan/vant-weapp#5586]
### Vant Weapp 版本

1.10.23

### 子组件

```html
<slot name="right"></slot>  // 第一处
<van-field label="{{label}}" value="{{ value }}">
    <text slot="right-icon" >
     <slot name="right"></slot> //  第二处
    </text>
  </van-field>
```

### 父组件
```html
 <mj-textarea  label="{{label}}" value="otherFrom" >
          <text slot="right">
             <view>123123</view>
          </text>
  </mj-textarea>
```

此时父组件设置了具名插槽 `slot="right-icon"`，在子组件的 `van-field`下的 `slot="right-icon"` 中 **`第二处`** 处渲染父组件插槽内容就会失效，无法渲染，但是直接在封装的组件中 **`第一处`** 处渲染可以正常渲染

### 重现步骤

二次封装组件必现

### 设备/浏览器

小程序开发工具

**Comment by johnsonwong666** [comment]
尝试不同的slot名称呢？

**Comment by DarkerSU** [comment]
实验过不同于组件库的slot，依然如此，问题不是出在插槽名称上。



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年10月16日 10:08 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [youzan/vant-weapp] 二次封装van-field时 插槽失效 (Issue #5586) |

尝试不同的slot名称呢？

**Comment by johnsonwong666** [comment]
https://developers.weixin.qq.com/s/eY5Wc0m97DME
使用命名不同的slot名称 没有问题
