### ISSUE TITLE
[Feature Request] 是否会考虑支持小程序Skyline渲染引擎

### ISSUE THREAD

**Issue by const-undefined-man** [youzan/vant-weapp#5587]
### 这个功能解决了什么问题？

目前最新版本的小程序组件库，在Skyline引擎下，很多功能报错，样式丢失，就是想确认一下，后续是否会支持。

### 你期望的 API 是什么样子的？

暂无

**Comment by const-undefined-man** [comment]
closed

**Comment by johnsonwong666** [comment]
Skyline引擎目前看社区反馈问题挺多的，暂时没有是计划。
