### ISSUE TITLE
[Bug Report] 手机预览报错Error during evaluating file "xxx.js": 

### ISSUE THREAD

**Issue by web-ma-hub** [youzan/vant-weapp#5589]
### 重现链接

https://developers.weixin.qq.com/community/develop/doc/000a2c37b58d2800ea709d09861c00?fromCreate=0

### Vant Weapp 版本

1.11.1

### 描述一下你遇到的问题。

引入dialog组件页面报错![bf369e5b98bd58f457fa09b88063664](https://github.com/youzan/vant-weapp/assets/40451732/00eabf8f-e1e2-4349-a968-3c57dbe2e660)

### 重现步骤

微信开发工具点击预览,在引入dialog组件的页面当中会报错

### 设备/浏览器

wechat

**Comment by web-ma-hub** [comment]
目前解决方案: 
### 取消勾选:详情--本地设置--上传时进行代码保护
该选项.不知道是vant的问题还是微信开发工具的问题

**Comment by johnsonwong666** [comment]
代码怎么写的？ 试了一下不管是否开启代码保护都可以正常,检查一下打包后是否存在这个文件，提供一下你的环境以及提供一个复现代码片段看一下

**Comment by johnsonwong666** [comment]
由于较长时间没有提供复现代码片段，此issue暂时关闭，若能复现请附带复现代码片段排查。
