### ISSUE TITLE
[Bug Report] popup上下滑动问题

### ISSUE THREAD

**Issue by yik7707** [youzan/vant-weapp#5590]
### 重现链接

https://developers.weixin.qq.com/s/azkOZ2mA7HMY

### Vant Weapp 版本

1.11.0

### 描述一下你遇到的问题。

popup展开后，在popup内上下滑动位置会穿透滑动页面位置，该bug请修复，影响用户体验

### 重现步骤

popup展开后上下滑动

**Comment by johnsonwong666** [comment]
<img width="1033" alt="image" src="https://github.com/youzan/vant-weapp/assets/64689255/dc4a82ef-4f9e-4085-8813-8cb6268ee8c1">
试一下lock-scroll

**Comment by johnsonwong666** [comment]
<img width="790" alt="image" src="https://github.com/youzan/vant-weapp/assets/64689255/78092b58-3ba4-4be1-b801-b92d33a1c19a">
page-meta
