### ISSUE TITLE
[Bug Report] popup加上关闭图标问题

### ISSUE THREAD

**Issue by yik7707** [youzan/vant-weapp#5591]
### 重现链接

https://developers.weixin.qq.com/s/AigL73mu76Ml
![image](https://github.com/youzan/vant-weapp/assets/74293458/f99f2c65-e5b0-488d-816b-dfe0702f3614)

### Vant Weapp 版本

1.11.0

### 描述一下你遇到的问题。

popup加上关闭图标不占位会重叠现象

### 重现步骤

无

**Comment by johnsonwong666** [comment]
这里面是一个容器，自行加padding进行调整。
