### ISSUE TITLE
cascader组件disable点击事件抛出来

### ISSUE THREAD

**Issue by myGitHubHuLin** [youzan/vant-weapp#5592]
### 这个功能解决了什么问题？

禁用项；点击后续需要处理自己的逻辑；想把事件给抛出来

### 你期望的 API 是什么样子的？

<van-cascader bind:disableEvent></van-cascader>

**Comment by johnsonwong666** [comment]
不太符合html标准，暂不支持<img width="932" alt="image" src="https://github.com/youzan/vant-weapp/assets/64689255/9caa92dd-0fe6-45f3-9263-cc37c9e2d7bd">
