### ISSUE TITLE
van-tab 增加slot="title"

### ISSUE THREAD

**Issue by nsnsqk** [youzan/vant-weapp#5593]
### 这个功能解决了什么问题？

van-tab 组件的title 可以自定义，比如加入icon、image，改变字体大小样式等

### 你期望的 API 是什么样子的？

<van-tab >
    <view slot="title">title</view>
    内容
</van-tab>

**Comment by nsnsqk** [comment]
`<van-tab >
    <view slot="title">title</view>
    内容 2
</van-tab>`

**Comment by johnsonwong666** [comment]
会在vant-weapp 2.0版本支持

**Comment by nsnsqk** [comment]
> 会在vant-weapp 2.0版本支持

什么时候2.0版哇，有计划推出日期吗

**Comment by johnsonwong666** [comment]
> > 会在vant-weapp 2.0版本支持
> 
> 什么时候2.0版哇，有计划推出日期吗
规划中

**Comment by nsnsqk** [comment]
> > > 会在vant-weapp 2.0版本支持
> > 
> > 
> > 什么时候2.0版哇，有计划推出日期吗
> > 规划中

今年会出2.0吗。我看历史issue，21年就有人问了

**Comment by johnsonwong666** [comment]
> > > > 会在vant-weapp 2.0版本支持
> > > 
> > > 
> > > 什么时候2.0版哇，有计划推出日期吗
> > > 规划中
> 
> 今年会出2.0吗。我看历史issue，21年就有人问了

没有这么快。
