### ISSUE TITLE
[Bug Report] 请在此填写标题

### ISSUE THREAD

**Issue by haifding** [youzan/vant-weapp#5595]
### 重现链接

  <van-field value="{{ factoryAddress }}" label="工厂地址" placeholder="请输入 工厂地址" border="{{ true }}"  autosize type="textarea" clearable cursor-spacing="350" />

### Vant Weapp 版本

1.11.1

### 描述一下你遇到的问题。

Field 输入框，里面的 cursor-spacing 属性，实际测试单位是 px，能否变成 rpx 。

不同手机屏幕大小不一样，上推的时候，用px为单位，实际推上去位置就不可控。

或者再来个属性：输入框聚焦时底部与屏幕顶部的距离
这样就可以固定住相对位置。谢谢

### 重现步骤

Field 输入框，输入的时候

### 设备/浏览器

所有设备

**Comment by johnsonwong666** [comment]
<img width="1116" alt="image" src="https://github.com/youzan/vant-weapp/assets/64689255/0b2f75c3-72ba-4a47-bf87-cbf0d5d0102f">

cursor-spacing 这个属性 field组件只是接收一下，传给原生的input，没有涉及像素处理。 看官方文档也没有什么单位。
