### ISSUE TITLE
Uploader 多图长按拖拽排序

### ISSUE THREAD

**Issue by haifding** [youzan/vant-weapp#5596]
### 这个功能解决了什么问题？

Uploader 文件上传多图，多文件，长按拖拽排序功能

这个在电商等上传宝贝页面的基础功能，希望官方考虑，谢谢

### 你期望的 API 是什么样子的？

Uploader 文件上传多图长按拖拽排序功能

**Comment by johnsonwong666** [comment]
实现拖拽会提高组件复杂度，收益不高，目前暂不支持。
