### ISSUE TITLE
真机调试没问题  预览和体验版组件都不显示

### ISSUE THREAD

**Issue by guuuJIe** [youzan/vant-weapp#5597]
### 重现链接

  <van-action-sheet show="{{ show }}" title="账号选择" bind:close="onClose" bind:select="onSelect">

</van-action-sheet>

### Vant Weapp 版本

1.11.0 

### 描述一下你遇到的问题。

组件无法展示 界面无法进行操作

### 重现步骤

设置show 为true，组件无法展示，界面像卡死

### 设备/浏览器

iPhone 12mini

**Comment by johnsonwong666** [comment]
用的什么组件？ 
https://developers.weixin.qq.com/s/NwHGjamA7bM4  这个小程序代码片段修改一下，修改成你的情况然后重新分享一下过来看一下

**Comment by guuuJIe** [comment]
<van-action-sheet show="{{ show }}" title="账号选择" bind:close="onClose" bind:select="onSelect">

</van-action-sheet>

**Comment by guuuJIe** [comment]
> 用的什么组件？
> https://developers.weixin.qq.com/s/NwHGjamA7bM4 这个小程序代码片段修改一下，修改成你的情况然后重新分享一下过来看一下

  <van-action-sheet show="{{ show }}" title="账号选择" bind:close="onClose" bind:select="onSelect">

</van-action-sheet>

**Comment by guuuJIe** [comment]
> 用的什么组件？
> https://developers.weixin.qq.com/s/NwHGjamA7bM4 这个小程序代码片段修改一下，修改成你的情况然后重新分享一下过来看一下

**Comment by guuuJIe** [comment]
用的van-action-sheet，van-pop-up

**Comment by johnsonwong666** [comment]
> 用的van-action-sheet，van-pop-up

有什么报错提示， 能完整的说明一下吗，这点信息无法排查

**Comment by guuuJIe** [comment]
微信小程序开发工具 **预览** 看不到报错。真机调试又是正常 最简单的代码，
<van-action-sheet show="{{ show }}" title="标题">
  <view>内容</view>
</van-action-sheet>  设置show为true。然后啥也不显示，界面又不能交互

**Comment by johnsonwong666** [comment]
发你的联系QQ/微信 到 1067100250@qq.com 在线跟你了解一下情况。
@guuuJIe

**Comment by johnsonwong666** [comment]
skyline渲染问题，有任何白屏报错现象，请先在app.json去掉skyline渲染的配置

**Comment by answer33** [comment]
我也遇到了同样的问题。把app.json的一下配置删除就好了
<img width="470" alt="image" src="https://github.com/youzan/vant-weapp/assets/22948552/123edf63-5df9-4797-ad75-b6e05487d3f0">
