### ISSUE TITLE
Popup 弹出层获取不到DOM节点

### ISSUE THREAD

**Issue by changzhengithub** [youzan/vant-weapp#5599]
### 重现链接

<van-popup show="{{commentPopup.visible}}" position="bottom" safe-area-inset-bottom bind:close="closeComment">
  <view class="comment-container">
  </view>
</van-popup>

### Vant Weapp 版本

1.10.14

### 描述一下你遇到的问题。

Popup里的元素无法获取

### 重现步骤

<van-popup show="{{commentPopup.visible}}" position="bottom" safe-area-inset-bottom bind:close="closeComment">
  <view class="comment-container">
  </view>
</van-popup>

**Comment by johnsonwong666** [comment]
你要获取什么节点呢？ wx.selectComponent 不能使用？

**Comment by changzhengithub** [comment]
> 你要获取什么节点呢？ wx.selectComponent 不能使用？

就是获取DOM节点啊，不是获取组件，这都不理解？真实情况就是小程序本身就只支持获取scroll-view和canvas的dom节点，不支持获取获取其他的dom节点，导致popup里也无法获取。

**Comment by changzhengithub** [comment]
真实情况就是小程序本身就只支持获取scroll-view和canvas的dom节点，不支持获取获取其他的dom节点，导致popup里也无法获取。但是又有一个问题，popup弹窗打开后不能立即设置里面的元素，比如给input设置focus获取焦点，需要使用定时器才行。

**Comment by johnsonwong666** [comment]
popup弹窗提供了一个after-enter事件，你可以在这个回调里面去设置 focus
