### ISSUE TITLE
小程序插件开发

### ISSUE THREAD

**Issue by wangfufu** [youzan/vant-weapp#5600]
### 这个功能解决了什么问题？

可以在像小程序开发那样在小程序插件开发中使用该框架

### 你期望的 API 是什么样子的？

# 通过 npm 安装
npm i @vant/weapp -S --production

# 通过 yarn 安装
yarn add @vant/weapp --production

# 安装 0.x 版本
npm i vant-weapp -S --production

**Comment by wangfufu** [comment]
小程序插件开发集成文档

**Comment by johnsonwong666** [comment]
插件开发应该和开发小程序差不多 
参考一个这个帖子 https://developers.weixin.qq.com/community/develop/doc/00040a5a3a03e87748675f9215b000
