### ISSUE TITLE
[Bug Report] upload组件

### ISSUE THREAD

**Issue by WB967** [youzan/vant-weapp#5601]
### 重现链接

无

### Vant Weapp 版本

1.10.23

### 描述一下你遇到的问题。

示例中有一个自定义预览预览样式，没有示例代码，源码中也未找到对应的代码。
我看的源码目录：example/dist/uploader/index.wxml，在这看到了，只有isImage=false时，才会显示名称，但是这样有导致没有图片展示。和示例又不否。
示例中有个van-uploader__preview-cover的class，在代码中搜索也是没有搜到。但示例中又有，望解答下

### 重现步骤

无

**Comment by johnsonwong666** [comment]
右侧预览是vant2的，vant-weapp没有完全对齐，以文档中的叙述为主，这个自定义预览会在vant-weapp2.0版本中提供。
