### ISSUE TITLE
[Bug Report] 在uniapp中使用时field组件报错

### ISSUE THREAD

**Issue by Guizimo** [youzan/vant-weapp#5602]
### 重现链接

[Vue warn]: Unknown custom element: <include> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

### Vant Weapp 版本

1.11.1

### 描述一下你遇到的问题。

引用field组件时报错

[Vue warn]: Unknown custom element: <include> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

### 重现步骤

无

**Comment by johnsonwong666** [comment]
这个报错 看起来是组件未注册？ 然后非原生微信小程序开发工具产生的issue目前不会处理，可能会有平台编译差异性的问题，可以将问题提到对应的官方下去。
