### ISSUE TITLE
[Bug Report] textarea 设置error  placeholder样式错误

### ISSUE THREAD

**Issue by dancelion** [youzan/vant-weapp#5603]
### 重现链接

`data: {
  test: '',
  test1: true,
},`
`<van-field
      data-field="name"
      label="测试"
      title-width="10em"
      type="textarea"
      value="{{ test }}"
      placeholder="请输入"
      required="{{ true }}"
      border="{{ true }}"
      autosize="{{ true }}"
      custom-class="act-form-field"
      bind:change="onInputChange"
      error="{{test1}}"
  />`

### Vant Weapp 版本

1.11

### 描述一下你遇到的问题。

设置textarea组件error为true之后，组件的placeholder样式未生效
<img width="1213" alt="image" src="https://github.com/youzan/vant-weapp/assets/7478515/81578dee-98cf-4540-a647-75c18b736bc3">

### 重现步骤

1.设置textarea组件的error属性的变量值为false
2.修改error属性变量值为true，样式并不会变化
如果初始值设置为true则会正常显示红色
<img width="1209" alt="image" src="https://github.com/youzan/vant-weapp/assets/7478515/3c90d298-8aa5-41cc-9c8f-1ea959208f5f">

### 设备/浏览器

微信开发者工具  RC Build (1.06.2310071)

**Comment by johnsonwong666** [comment]
微信小程序官方bug  已提交至微信
https://developers.weixin.qq.com/community/develop/doc/00088cc3e500785a27904de0466400
