### ISSUE TITLE
[Bug Report] 双向绑定在uniapp vue下会报错

### ISSUE THREAD

**Issue by DemonBlackFire** [youzan/vant-weapp#5604]
### 重现链接

`<van-field model:value="{{pass}}" type="text" label="姓名" right-icon="arrow" placeholder="请输入"
						required input-align="right" class="iconOpacity" />`

vue代码：
`	export default {
		data() {
			return {
				pass: '',
			};
		},
		......`

### Vant Weapp 版本

1.11

### 描述一下你遇到的问题。

HBuilder错误提示：
11:11:13.456 [plugin:vite:vue] Error parsing JavaScript expression: 
11:11:13.457 {
11:11:13.459   model:value: '{{pass}}',
11:11:13.459   type: 'text',
11:11:13.461   label: '\u6765\u5BBE\u59D3\u540D',
11:11:13.461   rightIcon: 'arrow',
11:11:13.463   placeholder: '\u8BF7\u8F93\u5165',
11:11:13.463   required: true,
11:11:13.465   inputAlign: 'right'
11:11:13.465 }

### 重现步骤

同上

**Comment by johnsonwong666** [comment]
目前在非原生微信小程序工具上开发产生的问题不会处理，可能是平台编译差异性的问题，可以将问题提至对应官方。

**Comment by DemonBlackFire** [comment]
> 目前在非原生微信小程序工具上开发产生的问题不会处理，可能是平台编译差异性的问题，可以将问题提至对应官方。

好的，感谢回复
