### ISSUE TITLE
[Bug Report] 微信小程序-含背景色的button无法显示文字

### ISSUE THREAD

**Issue by Bange666** [youzan/vant-weapp#5605]
### 重现链接

<view>
	<van-button type="default">默认按钮</van-button>
</view>

<view>
	<van-button type="info">信息按钮</van-button>
</view>

<view>
        <van-button plain type="info">朴素按钮</van-button>
</view>

<view>
	<van-button icon="star-o" type="primary">按钮</van-button>
</view>

<view>
	<van-button plain icon="star-o" type="primary">按钮</van-button>
</view>

### Vant Weapp 版本

1.11.1

### 描述一下你遇到的问题。

 **含背景色的button无法显示文字**

调试基础库：3.1.4
真机调试也会出现同样的问题

### 重现步骤

 含背景色的button无法显示文字
![image](https://github.com/youzan/vant-weapp/assets/51155397/4a93ce95-70fe-4ddf-8561-93781d3c62f4)

**Comment by johnsonwong666** [comment]
你有自己调整样式吗？检索一下看一下样式。

**Comment by Bange666** [comment]
> 你有自己调整样式吗？检索一下看一下样式。

第一次用，刚刚安装好的，什么都没动过。。。

**Comment by Bange666** [comment]
> 你有自己调整样式吗？检索一下看一下样式。

![image](https://github.com/youzan/vant-weapp/assets/51155397/2479db4a-3930-42d2-aaec-ef680bc6b54a)

**Comment by Bange666** [comment]
> 你有自己调整样式吗？检索一下看一下样式。

style:v2，也已经在配置文件里面去除了

**Comment by johnsonwong666** [comment]
> > 你有自己调整样式吗？检索一下看一下样式。
> 
> style:v2，也已经在配置文件里面去除了

加我q1067100250在线看下
