### ISSUE TITLE
[Bug Report] 求助，van-uploader 的 使用

### ISSUE THREAD

**Issue by wanglihuaya** [youzan/vant-weapp#5607]
### 重现链接

```html
 <van-uploader file-list="{{ fileList }}" accept="image" use-before-read bind:beforeRead="beforeRead" bind:afterRead="afterRead" />
```

### Vant Weapp 版本

1.11.1

### 描述一下你遇到的问题。

```html
 <van-uploader file-list="{{ fileList }}" accept="image" use-before-read bind:beforeRead="beforeRead" bind:afterRead="afterRead" />
```

bind 必须写成这样才能 触发，但是重开一个项目不会有这个问题，调试了半天才发现。求助

### 重现步骤

```html
 <van-uploader file-list="{{ fileList }}" accept="image" use-before-read bind:beforeRead="beforeRead" bind:afterRead="afterRead" />
```

**Comment by johnsonwong666** [comment]
是在原生微信小程序开发者工具上开发的小程序吗？如果不是的话可能有这个问题

**Comment by wanglihuaya** [comment]
> 是在原生微信小程序开发者工具上开发的小程序吗？如果不是的话可能有这个问题

是用的 vscode,使用的是微信原生代码，另外一个项目就没有问题

**Comment by johnsonwong666** [comment]
> > 是在原生微信小程序开发者工具上开发的小程序吗？如果不是的话可能有这个问题
> 
> 是用的 vscode,使用的是微信原生代码，另外一个项目就没有问题

是否uniapp、taro这些开发框架开发？

**Comment by wanglihuaya** [comment]
> > > 是在原生微信小程序开发者工具上开发的小程序吗？如果不是的话可能有这个问题
> > 
> > 
> > 是用的 vscode, 使用的是微信原生代码，另外一个项目就没有问题
> 
> 是否 uniapp、taro 这些开发框架开发？

我靠 大佬秒回，项目中有嵌入 uni，有 uni 的依赖 vendor.js

**Comment by johnsonwong666** [comment]
> > > > 是在原生微信小程序开发者工具上开发的小程序吗？如果不是的话可能有这个问题
> > > 
> > > 
> > > 是用的 vscode, 使用的是微信原生代码，另外一个项目就没有问题
> > 
> > 
> > 是否 uniapp、taro 这些开发框架开发？
> 
> 我靠 大佬秒回，项目中有嵌入 uni，有 uni 的依赖 vendor.js

在微信开发者工具上创建项目开发是没有问题的，使用uniapp、taro这些 可能存在平台编译差异，使用vant-weapp可能会产生一些问题，目前不处理涉及其他框架开发产生的问题。

**Comment by wanglihuaya** [comment]
> > > > > 是在原生微信小程序开发者工具上开发的小程序吗？如果不是的话可能有这个问题
> > > > 
> > > > 
> > > > 是用的 vscode, 使用的是微信原生代码，另外一个项目就没有问题
> > > 
> > > 
> > > 是否 uniapp、taro 这些开发框架开发？
> > 
> > 
> > 我靠 大佬秒回，项目中有嵌入 uni，有 uni 的依赖 vendor.js
> 
> 在微信开发者工具上创建项目开发是没有问题的，使用 uniapp、taro 这些 可能存在平台编译差异，使用 vant-weapp 可能会产生一些问题，目前不处理涉及其他框架开发产生的问题。

是项目中 uni 开发的一部分东西 作为子包引入了，里面有 uni 的一部分构建的代码，我想应该是，那我就清楚了，我就先按驼峰的写，也能用，哈哈哈 试出来了，谢谢开源
