### ISSUE TITLE
Uploader 文件上传  v1.11.0  bind:after-read 事件未触发华为P50  之前的1.10.4正常 

### ISSUE THREAD

**Issue by HH-hexiao** [youzan/vant-weapp#5608]
### 重现链接

https://vant-contrib.gitee.io/vant-weapp/#/uploader

### Vant Weapp 版本

1.11.0

### 描述一下你遇到的问题。

Uploader 文件上传  v1.11.0  bind:after-read 事件未触发华为P50  之前的1.10.4正常 

### 重现步骤

官方实例即可

**Comment by johnsonwong666** [comment]
看下代码怎么写的？

**Comment by johnsonwong666** [comment]
由于较长时间没有提供复现代码片段，此issue暂时关闭，若能复现请附带复现代码片段排查。
