### ISSUE TITLE
微信开发工具 使用van-datetime-picker报错

### ISSUE THREAD

**Issue by jqjqjq-l** [youzan/vant-weapp#5609]
### 重现链接

![image](https://github.com/youzan/vant-weapp/assets/59220719/c3729aec-9a23-4333-9023-28f264bc6380)

### Vant Weapp 版本

1.11.1

### 描述一下你遇到的问题。

微信开发工具 使用van-datetime-picker报错

### 重现步骤

引入datetime-picker到微信小程序后直接报错了

### 设备/浏览器

微信开发工具

**Comment by johnsonwong666** [comment]
写了一个代码片段没有复现 你看下修改成你的情况再分享过来看下
https://developers.weixin.qq.com/s/7sqAaomW7uMC

**Comment by johnsonwong666** [comment]
由于较长时间没有提供复现代码片段，此issue暂时关闭，若能复现请附带复现代码片段排查。
