### ISSUE TITLE
删除这条issues。本人有点强迫症

### ISSUE THREAD

**Issue by ghost** [youzan/vant-weapp#5611]
### 重现链接

![image](https://github.com/youzan/vant-weapp/assets/42329686/040ea9c6-3660-44bb-adb2-3c2222bd1a6a)

### Vant Weapp 版本

1.10.3

### 描述一下你遇到的问题。

小红点和提示信息位置显示异常

### 重现步骤

![image](https://github.com/youzan/vant-weapp/assets/42329686/040ea9c6-3660-44bb-adb2-3c2222bd1a6a)

**Comment by wdpgithub** [comment]
确认之后删除这条issues

**Comment by johnsonwong666** [comment]
tabs的info 目前在标题的右边
<img width="355" alt="image" src="https://github.com/youzan/vant-weapp/assets/64689255/54386036-888e-4e23-b56b-67a75fa023e0">
