### ISSUE TITLE
van-dialog 组件 使用 bind:agreePrivacyAuthorization="onPrivacyConfirm" 点击同意后没有回调

### ISSUE THREAD

**Issue by static7** [youzan/vant-weapp#5612]
### 重现链接

如下图

### Vant Weapp 版本

1.11.1

### 描述一下你遇到的问题。

```
<van-dialog
        use-slot
        show="{{ true }}"
        show-cancel-button
        confirm-button-open-type="agreePrivacyAuthorization"
        bind:close="onPrivacyClose"
        bind:agreePrivacyAuthorization="onPrivacyConfirm"
        confirm-button-text="同意并继续"
        cancel-button-text="不同意"
        confirm-button-color="#03C988"
>
用户隐私保护提示
....
</van-dialog>
```
![image](https://github.com/youzan/vant-weapp/assets/11241063/34a63c99-6569-4ecc-8312-dd257ef77f0d)

```
	//同意隐私协议
	onPrivacyConfirm(){
		console.log("已经同意");
	},
```

### 重现步骤

点击同意后,点击"同意后" 没有调用 onPrivacyConfirm 方法, 微信开发工具里没有相应的日志出现

### 设备/浏览器

微信开发工具, 微信小程序预览

**Comment by johnsonwong666** [comment]
<img width="1306" alt="image" src="https://github.com/youzan/vant-weapp/assets/64689255/11b817f5-db50-43e2-ac85-25048b276c29">
https://developers.weixin.qq.com/s/GjU3opmF7IMP。写了一个demo正常输出，检查一下基础库之类的信息。

**Comment by static7** [comment]
已经解决了, 是变量污染了. 但我很好奇, 为啥会产生变量污染呢? 文件名与变量不能命名同一个?
