### ISSUE TITLE
Vant Weapp  van-dropdown-menu 跟微信原生组件scroll-view样式冲突，van-dropdown-menu下拉选项会被scroll-view覆盖

### ISSUE THREAD

**Issue by JIMYANG-315** [youzan/vant-weapp#5613]
### 重现链接

点击参考状态，显示下拉框，但是下拉框被scroll-view覆盖，使用z-index也无法调整

### Vant Weapp 版本

1.11.1

### 描述一下你遇到的问题。

点击参考状态，显示下拉框，但是下拉框被scroll-view覆盖，使用z-index也无法调整

### 重现步骤

点击参考状态，显示下拉框，但是下拉框被scroll-view覆盖，使用z-index也无法调整

```[tasklist]
### Tasks
```

```[tasklist]
### Tasks
```

**Comment by johnsonwong666** [comment]
dropdown 提供了以下几个外部样式类 尝试使用以下 应该不会出现这种情况
<img width="734" alt="image" src="https://github.com/youzan/vant-weapp/assets/64689255/650305a5-ad7d-43c3-8275-c702e141a702">

**Comment by JIMYANG-315** [comment]
I don’t need item
