### ISSUE TITLE
[Bug Report] van-button的disabled属性为true时catch:tap事件还是会触发

### ISSUE THREAD

**Issue by masicheng** [youzan/vant-weapp#5619]
### 重现链接

无法生成代码片段链接，显示超出1024kb

### Vant Weapp 版本

1.11.1

### 描述一下你遇到的问题。

van-button的disabled属性为true时catch:tap事件还是会触发

### 重现步骤

点击按钮

**Comment by johnsonwong666** [comment]
<img width="766" alt="image" src="https://github.com/youzan/vant-weapp/assets/64689255/20168794-68cd-4cf1-b9eb-d5194dcdfa3a">
使用click事件代替

**Comment by masicheng** [comment]
意思如果要达到catch的效果，要在button上面得写两个事件，一个是bind:click，另外一个是catch:tap？
