### ISSUE TITLE
van-badge-group 设置了active,没有生效

### ISSUE THREAD

**Issue by liukefeng553** [youzan/vant-weapp#562]
通过在van-badge-group上设置active属性来控制选中的badge

<van-badge-group :active="active" bind:change="onChange">
  <van-badge title="标签名称" />
  <van-badge title="标签名称" info="8" />
  <van-badge title="标签名称" info="99" />
  <van-badge title="标签名称" info="199" />
</van-badge-group>

**Comment by chenjiahan** [comment]
感谢反馈，已在 dev 分支修复，会在 0.3.2 版本发版
