### ISSUE TITLE
[Bug Report] 遮罩层偶然性无法关闭

### ISSUE THREAD

**Issue by yexiaobai0** [youzan/vant-weapp#5620]
### 重现链接

<van-overlay z-index="1" duration="1" show="{{ showMask }}" bind:click="onHideMask">
    <view class="my-center-box">
      
      <van-loading size="3rem" vertical>加载中...</van-loading>
    </view>
  </van-overlay>

this.setData({ showMask: true });//开启遮罩层
console.log('页面加载开始：'+this.data.showMask);
this.login();
this.setData({ showMask: false });//关闭遮罩层
console.log('页面加载结束：'+that.data.showMask);

### Vant Weapp 版本

1.11.1

### 描述一下你遇到的问题。

遮罩层偶然性无法关闭吗，即使遮罩层的show设置为false也无法关闭

### 重现步骤

初始化页面时

**Comment by yexiaobai0** [comment]
setTimeout(function(){
      that.setData({ showMask: false });
      console.log('页面加载结束：'+that.data.showMask);
    },1000);
通过这种异步方式来关闭就没有问题

**Comment by johnsonwong666** [comment]
发一个小程序片段来看一下   https://developers.weixin.qq.com/s/lGz6BwmA7MME  这个可以修改一下复现你的情况然后分享回来

**Comment by yexiaobai0** [comment]
https://developers.weixin.qq.com/s/4YS9XAmc7MMM

**Comment by johnsonwong666** [comment]
> https://developers.weixin.qq.com/s/4YS9XAmc7MMM

为什么   this.setData({ showMask: false });  不写在 wx.login 的succes/fail 回调里面？

**Comment by yexiaobai0** [comment]
写在回调里也会有这样的情况

**Comment by johnsonwong666** [comment]
https://developers.weixin.qq.com/s/h9YekAm976Mh.  可以正常关闭的。 @yexiaobai0

**Comment by yexiaobai0** [comment]
这个算bug吗

**Comment by yexiaobai0** [comment]
为啥我那样写不行呢

**Comment by yexiaobai0** [comment]
假如有多个回调那我不得每个回调方法里面写一个this.setData({ showMask: false });

**Comment by yexiaobai0** [comment]
我调wx.websocket也会有这样的情况，尽管是在回调函数里面写了this.setData({ showMask: false });

**Comment by johnsonwong666** [comment]
正常写业务代码一般都是在回调里面处理啊，你用定时器肯定不准确的，你怎么知道异步事件什么时候完成

**Comment by yexiaobai0** [comment]
不是，这个为啥会影响遮罩层关闭呢

**Comment by johnsonwong666** [comment]
> 不是



> 不是，这个为啥会影响遮罩层关闭呢
可以研究一下小程序 setState的机制吧

**Comment by yexiaobai0** [comment]
好吧

**Comment by yanbin218** [comment]
我也遇到一样的情况，开发者工具没问题，真机就关闭不了

**Comment by yanbin218** [comment]
<van-overlay show="{{ showLoading }}" custom-class="overlay">
      <van-loading type="spinner"></van-loading>
</van-overlay> 
 ------------------------------------
observers:{
    'loading':function (loading) {
      setTimeout(()=>{
        this.setData({
          showLoading:loading
        })
        },100);
    }
  },

设置了定期器就可以

**Comment by yanbin218** [comment]
> 我也遇到一样的情况，开发者工具没问题，真机就关闭不了

设置了定期器就可以

 observers:{
    'loading':function (loading) {
      setTimeout(()=>{
        this.setData({
          showLoading:loading
        })
        },100);
    }
  },


<van-overlay show="{{ showLoading }}" custom-class="overlay">
  <van-loading type="spinner"></van-loading>
</van-overlay>

**Comment by yanbin218** [comment]
> 我也遇到一样的情况，开发者工具没问题，真机就关闭不了

设置了定期器就可以关闭
setTimeout(()=>{
        this.setData({
          showLoading:loading }
)},100);
