### ISSUE TITLE
组件van-area的columns-num属性类型与文档描述不符

### ISSUE THREAD

**Issue by Lick-liu** [youzan/vant-weapp#5621]
### 重现链接

<van-popup show="{{ showCityPicker }}" position="bottom">
        <van-area area-list="{{ areaList }}" bind:confirm="onCityConfirm" bind:cancel="hideCityPicker" columns-num="{{3}}" />
    </van-popup>
![image](https://github.com/youzan/vant-weapp/assets/51771897/cd33b724-fa21-439d-af06-5776c3e1ba90)

<van-popup show="{{ showCityPicker }}" position="bottom">
        <van-area area-list="{{ areaList }}" bind:confirm="onCityConfirm" bind:cancel="hideCityPicker" columns-num="3" />
    </van-popup>
![image](https://github.com/youzan/vant-weapp/assets/51771897/cd670a92-a03d-488d-83cb-3e19633d62e3)

### Vant Weapp 版本

1.10.23

### 描述一下你遇到的问题。

文档中columns-num属性类型描述为String或Number，但实际上使用Number类型才可以
![image](https://github.com/youzan/vant-weapp/assets/51771897/c0c28de7-5e30-4154-b9d2-f5640768e75a)
源码是全等判断，且没有转换为Number类型,
![image](https://github.com/youzan/vant-weapp/assets/51771897/e249c1b2-260d-48bc-9cb0-7dce37e9c8e0)

### 重现步骤

<van-popup show="{{ showCityPicker }}" position="bottom">
        <van-area area-list="{{ areaList }}" bind:confirm="onCityConfirm" bind:cancel="hideCityPicker" columns-num="{{3}}" />
    </van-popup>
![image](https://github.com/youzan/vant-weapp/assets/51771897/cd33b724-fa21-439d-af06-5776c3e1ba90)

<van-popup show="{{ showCityPicker }}" position="bottom">
        <van-area area-list="{{ areaList }}" bind:confirm="onCityConfirm" bind:cancel="hideCityPicker" columns-num="3" />
    </van-popup>
![image](https://github.com/youzan/vant-weapp/assets/51771897/cd670a92-a03d-488d-83cb-3e19633d62e3)

**Comment by johnsonwong666** [comment]
可以提个pr修复一下文档。

**Comment by landluck** [comment]
`v1.11.2` 已修复
