### ISSUE TITLE
van-datetime-picker bind:input事件安卓机延迟返回问题

### ISSUE THREAD

**Issue by huangyuxin950210** [youzan/vant-weapp#5623]
### 重现链接

<van-datetime-picker
  type="date"
  value="{{ currentDate }}"
  bind:input="onInput"
  min-date="{{ minDate }}"
  formatter="{{ formatter }}"
/>

Page({
  data: {
    currentDate: new Date().getTime(),
    minDate: new Date().getTime(),
    formatter(type, value) {
      if (type === 'year') {
        return `${value}年`;
      }
      if (type === 'month') {
        return `${value}月`;
      }
      return value;
    },
  },

  onInput(event) {
    this.setData({
      currentDate: event.detail,
    });
在这里打印console.log(event.detail),安卓机有延迟
  },
});

### Vant Weapp 版本

1.11.1

### 描述一下你遇到的问题。

vant weapp van-datetime-picker 时间选择组件bind:input触发在安卓机上会有延迟卡顿现象，导致在关闭选择前没有获取到bind:input返回的value，而在ios上几乎是改变一次值就实时触发返回了value

### 重现步骤

<van-datetime-picker
  type="date"
  value="{{ currentDate }}"
  bind:input="onInput"
  min-date="{{ minDate }}"
  formatter="{{ formatter }}"
/>

Page({
  data: {
    currentDate: new Date().getTime(),
    minDate: new Date().getTime(),
    formatter(type, value) {
      if (type === 'year') {
        return `${value}年`;
      }
      if (type === 'month') {
        return `${value}月`;
      }
      return value;
    },
  },

  onInput(event) {
    this.setData({
      currentDate: event.detail,
    });
在这里打印console.log(event.detail),安卓机有延迟
  },
});

### 设备/浏览器

安卓机

**Comment by johnsonwong666** [comment]
https://developers.weixin.qq.com/s/rbAebAmE7RM5

是不是真机预览的时候返回延迟太大了，延迟太大了控制台确实有点延迟，但是预览打印是没有问题的。

**Comment by huangyuxin950210** [comment]
> https://developers.weixin.qq.com/s/rbAebAmE7RM5
> 
> 是不是真机预览的时候返回延迟太大了，延迟太大了控制台确实有点延迟，但是预览打印是没有问题的。

不是，就是安卓机bind:input返回有延迟，又没法监听这个延迟时间

**Comment by huangyuxin950210** [comment]
> https://developers.weixin.qq.com/s/rbAebAmE7RM5
> 
> 是不是真机预览的时候返回延迟太大了，延迟太大了控制台确实有点延迟，但是预览打印是没有问题的。

比如我现在这个场景，我打开时间选择，用户安卓机很快速的切换时间，此时bind:input有延迟，数据还没更新到最新的一次切换，用户确认关闭了选择时间组件，抛出的时间结果和现在用户实际选择的时间不一致，但是ios用户是正常的，瞬间返回

**Comment by johnsonwong666** [comment]
录个屏看下。尽可能提供当前环境信息。

**Comment by huangyuxin950210** [comment]
Uploading video(7).mp4…

**Comment by huangyuxin950210** [comment]
> 录个屏看下。尽可能提供当前环境信息。


Uploading video(7).mp4…

**Comment by huangyuxin950210** [comment]
> 录个屏看下。尽可能提供当前环境信息。

我视频传了半天一直显示uploading，有邮箱吗，我发您

**Comment by johnsonwong666** [comment]
> > 录个屏看下。尽可能提供当前环境信息。
> 
> 我视频传了半天一直显示uploading，有邮箱吗，我发您

1067100250@qq.com 顺便带上你的qq吧

**Comment by huangyuxin950210** [comment]
> > > 录个屏看下。尽可能提供当前环境信息。
> > 
> > 
> > 我视频传了半天一直显示uploading，有邮箱吗，我发您
> 
> [1067100250@qq.com](mailto:1067100250@qq.com) 顺便带上你的qq吧

已发
