### ISSUE TITLE
[Bug Report] 请在此填写标题

### ISSUE THREAD

**Issue by pingtianxia** [youzan/vant-weapp#5624]
### 重现链接

<uni-forms-item label="详细地址" required name="permanentAddress">
	<van-area :area-list="areaList" ></van-area>
</uni-forms-item>

### Vant Weapp 版本

1.11.1

### 描述一下你遇到的问题。

uniapp 使用 vant-weapp,使用 van-area组件 报错

使用 easycom 的方式引入
"easycom": {
	  "autoscan": true,
	  "custom": {
	    "^van-(.*)": "@/wxcomponents/vant/$1/index.vue" // 匹配components目录内的vue文件
	  }
	}

[Vue warn]: Unknown custom element: <include> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

found in

---> <VanPicker>
       <VanArea> at wxcomponents/vant/area/index.vue

### 重现步骤

编译是无法通过

**Comment by johnsonwong666** [comment]
非微信官方微信小程序开发者工具上产生issue暂不处理，可能是平台编译差异的问题，可以将问题提到对应的平台下。
