### ISSUE TITLE
Vant Weapp在使用vue cli 5.0.8创建的uniapp项目下运行问题

### ISSUE THREAD

**Issue by icyliyana** [youzan/vant-weapp#5625]
### 重现链接

无，安装报错问题

### Vant Weapp 版本

1.11.1

### 描述一下你遇到的问题。

Vant Weapp在uniapp项目下安装时，会替换或删除某些文件，导致项目无法运行；且安装后再卸载vant weapp后仍无法运行，重新安装依赖失败

### 重现步骤

1. vue create -p dcloudio/uni-preset-vue my-project新建一个uniapp项目，选择默认模板。
2. npm i @vant/weapp -S --production安装vant weapp
![image](https://github.com/youzan/vant-weapp/assets/92135677/fbbca0b9-f7df-4e50-bc27-ecd0a1a2b023)
3. 运行uniapp/卸载后再运行
![image](https://github.com/youzan/vant-weapp/assets/92135677/f8e041e2-8892-4189-807d-50878cda3155)

**Comment by icyliyana** [comment]
记得前一阵子用还可以，按照微信小程序使用组件的办法放到wxcomponents文件夹注册后可以正常使用，是不是最近uniapp更新的问题？记得并没有更新过uniapp

**Comment by johnsonwong666** [comment]
目前非微信官方微信开发者工具上产生的问题暂不处理，可能是编译的问题，可以将问题提到对应的官方去。
