### ISSUE TITLE
[Bug Report] Vant Weapp 小程序版 1.11.1 Calendar 日历组件真机报错

### ISSUE THREAD

**Issue by Jemory-git** [youzan/vant-weapp#5626]
### 重现链接

https://developers.weixin.qq.com/s/y2kt5Cm47HMx

### Vant Weapp 版本

1.11.1

### 描述一下你遇到的问题。

Calendar日历组件开发者工具中可用，但是真机预览getMonths调用报错，可在小程序中使用 "van-calendar": "@vant/weapp/calendar/index"查看控制台。

### 重现步骤

在页面中引入van-calendar组件即可预览，无需其他操作

### 设备/浏览器

安卓 苹果

**Comment by Jemory-git** [comment]
测试使用的微信都是最新版本

**Comment by johnsonwong666** [comment]
app.json删除
"renderer": "skyline",
"lazyCodeLoading": "requiredComponents"
  
 改用webview渲染，目前vant-weapp部分组件可能在使用skyline渲染下有问题。
