### ISSUE TITLE
[Bug Report] skyline渲染引擎下部分组件可能出现错误，请切换回webview模式渲染

### ISSUE THREAD

**Issue by johnsonwong666** [youzan/vant-weapp#5629]
### 重现链接

https://vant-contrib.gitee.io/vant-weapp/

### Vant Weapp 版本

1.11.0

### 描述一下你遇到的问题。

 skyline渲染引擎下部分组件出现错误

### 重现步骤

skyline渲染引擎下，控制台报错、真机白屏

**Comment by johnsonwong666** [comment]
{
    "renderer": "webview", // 修改渲染方式
    // "lazyCodeLoading": "requiredComponents", // 去除该代码
}

skyline渲染下出现错误的，将app.json里的内容做以上调整。

**Comment by johnsonwong666** [comment]
已知skyline下会报错的组件
1、field
2、popup #5628 
3、calendar #5627

**Comment by yuluod** [comment]
> { "renderer": "webview", // 修改渲染方式 // "lazyCodeLoading": "requiredComponents", // 去除该代码 }
> 
> skyline渲染下出现错误的，将app.json里的内容做以上调整。

利用这个方式解决了field的白屏问题

**Comment by Hellokugou520** [comment]
我是直接在源码的popup.wxml里加了这两行代码解决的报错问题，skyline模式也能正常使用
```js
<wxs src="../wxs/utils.wxs" module="utils" />
<wxs src="./index.wxs" module="computed" />
```
不知道是不是微信那边在不同渲染模式下对于`include`标签的处理流程不一致

**Comment by landluck** [comment]
`v1.11.2` 已修复
