### ISSUE TITLE
popup里点击按钮选择时间DatetimePicker，时间选择器会出现顶部栏消失？ios必现，安卓/开发者工具正常

### ISSUE THREAD

**Issue by Blank-Tea** [youzan/vant-weapp#5630]
### 重现链接

1、一个popup里有一个按钮，点击按钮弹出另一个popup包含一个DatetimePicker；此时即使设置show-toolbar=true时间选择器顶部栏（即：顶部的 取消 以及 确定 按钮）依旧无法显示；
2、ios真机有问题，安卓/开发者工具都是正常的；

### Vant Weapp 版本

1.10.14

### 描述一下你遇到的问题。

1、一个popup里有一个按钮，点击按钮弹出另一个popup包含一个DatetimePicker；此时即使设置show-toolbar=true时间选择器顶部栏（即：顶部的 取消 以及 确定 按钮）依旧无法显示；
2、ios真机有问题，安卓/开发者工具都是正常的；

### 重现步骤

1、一个popup里有一个按钮，点击按钮弹出另一个popup包含一个DatetimePicker；此时即使设置show-toolbar=true时间选择器顶部栏（即：顶部的 取消 以及 确定 按钮）依旧无法显示；
2、ios真机有问题，安卓/开发者工具都是正常的；

### 设备/浏览器

苹果/IOS

**Comment by johnsonwong666** [comment]
提供一个小程序代码片段来看一下。https://developers.weixin.qq.com/s/NwHGjamA7bM4 这个小程序代码片段修改一下，修改成你的情况然后重新分享一下过来看一下
