### ISSUE TITLE
[Bug Report] 微信小程序 Dialog 确认按钮，获取电话的时候，无回调

### ISSUE THREAD

**Issue by haifding** [youzan/vant-weapp#5632]
### 重现链接

`<van-dialog use-slot title="获取 电话" show="{{ phoneDialogShow }}" show-cancel-button confirm-button-open-type="getRealtimePhoneNumber" bind:close="phoneDialogClose"  bind:getrealtimephonenumber="getUserTel" >
  <image src="https://img.yzcdn.cn/1.jpg" />
</van-dialog>`

因为涉及到微信小程序的APPID和KEY才能调用取电话号码的功能，没法给微信小程序代码片段
https://vant-contrib.gitee.io/vant-weapp/#/dialog

### Vant Weapp 版本

1.11.1

### 描述一下你遇到的问题。

弹窗可以正常调用，点击确定后，也可以正常调用微信官网的获取电话号码的功能，再点击确认授权给电话号码后，无反应。不会执行我写的getUserTel函数。是完全没反应。

我换  confirm-button-open-type="getUserInfo“  bind:getuserinfo="getUserInfo"  就可以正常回调 getUserInfo 函数
我单独用 van-button 的获取电话号码，都是正常的。

### 重现步骤

1、触发弹窗
2、点确认
3、授权获取电话号码  或者  取消授权

### 设备/浏览器

所有设备

**Comment by landluck** [comment]
`v1.11.2` 已修复
