### ISSUE TITLE
picker多列，column1改变后column2位置不归位

### ISSUE THREAD

**Issue by superlbr** [youzan/vant-weapp#5635]
### 重现链接

const citys = {
  浙江: ['初中', '高中'],
  福建: ['初中', '高中'],
};

Page({
  data: {
    columns: [
      {
        values: Object.keys(citys),
        className: 'column1',
      },
      {
        values: citys['浙江'],
        className: 'column2',
        defaultIndex: 2,
      },
    ],
  },

  onChange(event) {
    const { picker, value, index } = event.detail;
    picker.setColumnValues(1, citys[value[0]]);
  },
});

### Vant Weapp 版本

1.10.5

### 描述一下你遇到的问题。

column1改变后column2位置不归位

### 重现步骤

1. 第二列选择”高中“
2. 第一列选择“福建”
3. 第二列仍然显示高中，而不是初中

### 设备/浏览器

小程序

**Comment by johnsonwong666** [comment]
原因是 在重置第二列的时候 判断到【高中】的值相同，return掉了，这个判断逻辑与历史issue相关，暂时不能去掉。

**Comment by johnsonwong666** [comment]
value值可以设置成一个对象 给id标识 代码是通过JSON.stringify来判断的  例如这样
const citys = {
  浙江: [
    { id: 1, text: '初中' },
    { id: 2, text: '高中' },
  ],
  福建: [
    { id: 3, text: '初中' },
    { id: 4, text: '高中' },
  ],
};
