### ISSUE TITLE
能否提供一个选项Popup的隐藏是否卸载子级

### ISSUE THREAD

**Issue by TallNutAlt** [youzan/vant-weapp#5638]
### 这个功能解决了什么问题？

<van-popup overlay-style="background-color:rgba(0, 0, 0, .5)" lock-scroll round show="{{ isSelector }}" bind:close="onSelector" bind:after-leave="nextInit" position="bottom" z-index="1200">
            <view style="min-height:55vh">
              <citySelector parentValue="{{nextStatus}}" bind:submit="submitCity"  bind:onClose="onSelector"></citySelector>
            </view>
          </van-popup>
          我们在一个van-popup里放了一个组件但是popup不会卸载组件导致该组件状态依旧保留，我们使用了bind:after-leave去重置子组件的状态 ，但是开销太大 我们传送的数据比较长

### 你期望的 API 是什么样子的？

提供一个选项是否去卸载子组件类使用wxif的api

**Comment by johnsonwong666** [comment]
里面的内容实用一个view包一下 使用wx:if不行吗

**Comment by TallNutAlt** [comment]
@johnsonwong666 试过了这样的话弹出层会有短暂的白屏

**Comment by johnsonwong666** [comment]
> @johnsonwong666 试过了这样的话弹出层会有短暂的白屏

加个loading 过渡一下
