### ISSUE TITLE
[Bug Report] 

### ISSUE THREAD

**Issue by tuke-code** [youzan/vant-weapp#5640]
### 重现链接

显示Calendar  高度太高

### Vant Weapp 版本

1.11.1

### 描述一下你遇到的问题。

![Uploading ant.png…]()

弹出后，日历组件太高了

### 重现步骤

显示Calendar  高度太高

**Comment by tuke-code** [comment]
![ant](https://github.com/youzan/vant-weapp/assets/78469741/71dca4b7-62eb-4dda-9ca9-eab0f5502468)

**Comment by johnsonwong666** [comment]
可以自行通过class样式类修改，但是可能会导致滑动的时候顶部月份与滑动不同步。
