### ISSUE TITLE
[Bug Report] notice-bar 组件的 `custom-class` 无效

### ISSUE THREAD

**Issue by LolipopJ** [youzan/vant-weapp#5641]
### 重现链接

略

### Vant Weapp 版本

1.11.1

### 描述一下你遇到的问题。

设置 `<van-notice-bar custom-class="this-is-a-class" />` 无效。翻看代码发现源码未对传入自定义样式解析：https://github.com/youzan/vant-weapp/blob/f98cf75027e6760901da8087f3bac182632c99c9/packages/notice-bar/index.wxml#L6

![image](https://github.com/youzan/vant-weapp/assets/42314340/dc81e590-8bf5-4cc3-b2ea-3bd227a657be)

### 重现步骤

略

**Comment by LolipopJ** [comment]
Not a bug. 能正常覆盖样式，与此处类名无关。

**Comment by caojiantao** [comment]
> Not a bug. 能正常覆盖样式，与此处类名无关。

什么意思哥们，我也遇到了。
