### ISSUE TITLE
vant weapp Calendar功能扩展

### ISSUE THREAD

**Issue by hdliyu** [youzan/vant-weapp#5649]
### 这个功能解决了什么问题？

您好？请问怎么动态设置日历组件的指定天的bottomText，我们需要在异步之后设置指定天的拜访人数，selectComponent拿到日期组件实例和文档只提供了一个reset方法，请问有类似selectDate()、setBottomText()方法吗？[Feature Request] 请在此填写标题

### 你期望的 API 是什么样子的？

```selectDate('2023-12-05').setBottomText('拜访人3个')```

**Comment by johnsonwong666** [comment]
动态修改 formatter

**Comment by hdliyu** [comment]
> 动态修改 formatter

感谢大佬已实现 ！
