### ISSUE TITLE
Dialog 组件蒙版层是否能支持z-index 层级设置？

### ISSUE THREAD

**Issue by GodStream** [youzan/vant-weapp#565]
**你需要的功能是？**
Dialog 支持z-index 层级设置

**你期望 API 是什么样的？**
z-index

**Comment by chenjiahan** [comment]
请问这个功能主要用于什么场景？

**Comment by GodStream** [comment]
如果页面上的层级高于Dialog，蒙版层无法遮盖住页面

**Comment by chenjiahan** [comment]
已在 dev 分支加入 zIndex 属性，会在 0.3.2 版本发版
