### ISSUE TITLE
真机 ios 使用van-field bug

### ISSUE THREAD

**Issue by gangweihua** [youzan/vant-weapp#5653]
### 重现链接

wxml
`
  <van-field
      value="{{ value }}"
      placeholder="请输入用户名"
      border="{{ false }}"
      bind:change="onChange"
  />
`
ts
`
Page({
  data: {
    value: '',
  },

  onChange(event) {
    // event.detail 为当前输入的值
    console.log(event.detail);
  },
});

`

### Vant Weapp 版本

"@vant/weapp": "^1.11.1",

### 描述一下你遇到的问题。

开发工具中的表现
![image](https://github.com/youzan/vant-weapp/assets/35332068/3a3bdf06-f0c5-49f3-923e-bb5ce1af3d72)

真机上的表现
![image](https://github.com/youzan/vant-weapp/assets/35332068/5588a528-8248-4543-8d34-ed35d70e2c45)

### 重现步骤

官网粘贴代码，没有任何修改，直接编译当前页面，使用真机调试

### 设备/浏览器

ios微信版本8.0.44

**Comment by shangeyao** [comment]
same issue

**Comment by gangweihua** [comment]
> same issue

@shangeyao 可以尝试，根据官网配置重新设置，调试几次，可以解决问题，因为我使用的新的框架ts sass,总感觉兼容有些问题，https://vant-contrib.gitee.io/vant-weapp/#/quickstart

**Comment by summer123123123** [comment]
same issue。重新设置也没解决，一样使用的ts sass
