### ISSUE TITLE
[Feature Request] 日历Calendar大小的需求

### ISSUE THREAD

**Issue by zixingzhuyue** [youzan/vant-weapp#5654]
### 这个功能解决了什么问题？

你好，咨询一下，我是一个小白开发者，我开发一个微信小程序，需要用到日历组件Calendar，但是我需要把日历组件放到view中作为一个组件使用，这个组件不需要那么那么大，大概占屏幕的宽度的80%，高度的50%左右,也就是自定义calendar的大小

### 你期望的 API 是什么样子的？

<vent-calendar gaodu=“自定义高度” kuandu="自定义宽度” />

**Comment by johnsonwong666** [comment]
平铺型的 通过改变--calendar-height的值修改
弹窗型的 通过改变--calendar-popup-height的值修改
