### ISSUE TITLE
vant-weapp组件在真机预览上样式全都不生效，样式错乱

### ISSUE THREAD

**Issue by yunyingchen** [youzan/vant-weapp#5655]
### 重现链接

代码片段超过1024kb，请直接按重现步骤操作

### Vant Weapp 版本

"version": "1.11.1"

### 描述一下你遇到的问题。

根据vant官方文档快速上手引入vant组件，模拟器预览效果正常，真机预览样式全部错乱，看起来像是样式未覆盖

### 重现步骤

1、新建一个小程序，不使用云服务，选择模板ts+sass基础模板；
2、然后根据vant官方文档快速上手步骤引入vant组件；
3、真机预览

### 设备/浏览器

真机预览

**Comment by yunyingchen** [comment]
![微信图片_20231212101947](https://github.com/youzan/vant-weapp/assets/30464962/38b623ef-8261-4b35-a719-2abf1e6f477d)
这是真机预览的效果，引入了按钮、popup弹出层、搜索组件

**Comment by yunyingchen** [comment]
调试基础库2.32.3

**Comment by yunyingchen** [comment]
预览模式下，外部样式类设置class名也全部不生效

**Comment by zhongq0930** [comment]
我用的 ts+less 模板，真机预览的时候 Popup Dialog 这种涉及蒙层的也出问题了

**Comment by zhongq0930** [comment]
我翻了之前的 issue #5597 ，删掉 `"componentFramework": "glass-easel"` 这一行配置就好了，你可以试试

**Comment by johnsonwong666** [comment]
> 我翻了之前的 issue #5597 ，删掉 `"componentFramework": "glass-easel"` 这一行配置就好了，你可以试试

@yunyingchen  按照这个大哥的方法试试

**Comment by yunyingchen** [comment]
> > 我翻了之前的 issue #5597 ，删掉 `"componentFramework": "glass-easel"` 这一行配置就好了，你可以试试
> 
> @yunyingchen 按照这个大哥的方法试试

样式是对了，但是弹窗关闭的按钮不是很灵敏，有点点不动
