### ISSUE TITLE
下载代码到本地构造查看效果时一直出现Warnings

### ISSUE THREAD

**Issue by zhaoyou** [youzan/vant-weapp#5656]
### 重现链接

- 将项目克隆到本地
git clone git@github.com:youzan/vant-weapp.git

- 安装项目依赖 （执行这个步骤出错））
cd vant-weapp && npm install

### Vant Weapp 版本

dev

### 描述一下你遇到的问题。
npm install 出现这个提示，一直这个警告
`(node:14247) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added to [TLSSocket]. Use emitter.setMaxListeners() to increase limit`

Node version: v20.8.1
Npm version: 10.1.0
OS: Sonoma 14.1.2 Apple M2 Pro

### 重现步骤

- 将项目克隆到本地
git clone git@github.com:youzan/vant-weapp.git

- 安装项目依赖 （出现警告，无法正常进行）
cd vant-weapp && npm install

**Comment by johnsonwong666** [comment]
切换node版本试试. 14 16 看看
