### ISSUE TITLE
Dialog 弹出框 的confirm-button-color属性颜色修改不成功

### ISSUE THREAD

**Issue by HouZhiGuoSir** [youzan/vant-weapp#5657]
### 重现链接

<van-dialog 
    id="van-dialog" 
    theme="round-button"
    show-confirm-button="false"
    confirm-button-color="#ee0a24" 
    title="申请注册成功"
    message="预计1个工作日完成审核"
    show="{{ showDialog }}"
    confirm-button-text="我知道了"
  />

### Vant Weapp 版本

1.11.1

### 描述一下你遇到的问题。

<van-dialog 
    id="van-dialog" 
    theme="round-button"
    show-confirm-button="false"
    confirm-button-color="#ee0a24" 
    title="申请注册成功"
    message="预计1个工作日完成审核"
    show="{{ showDialog }}"
    confirm-button-text="我知道了"
  />

### 重现步骤

修改confirm-button-color 颜色不生效

**Comment by johnsonwong666** [comment]
theme 为 round-button的时候没生效  已提pr

**Comment by landluck** [comment]
`v1.11.3` 已修复
