### ISSUE TITLE
Circle 环形进度条 Canvas 层级问题

### ISSUE THREAD

**Issue by Florenza** [youzan/vant-weapp#5658]
### Vant Weapp 版本

1.10.5

### 描述一下你遇到的问题。

![微信图片_20231215095607](https://github.com/youzan/vant-weapp/assets/32817812/eefbd559-5ce8-4c9b-b720-ab7cfef44f7b)

### 重现步骤

小程序canvas层级问题

**Comment by Florenza** [comment]
解决办法: https://blog.csdn.net/qq_33839972/article/details/135010071

**Comment by johnsonwong666** [comment]
可以提个pr过来修复

**Comment by johnsonwong666** [comment]
对于层级问题  可以调整一下type属性  发现不传type 不会出现这个现象

**Comment by callmegaga** [comment]
@johnsonwong666 2024.4.20发现不穿type属性，还是有这个问题
