### ISSUE TITLE
v1.11.2更新了啥

### ISSUE THREAD

**Issue by yisirman** [youzan/vant-weapp#5661]
### 这个功能解决了什么问题？

CHANGELOG 也没有更新 这个版本更新了什么？

### 你期望的 API 是什么样子的？

如上

**Comment by johnsonwong666** [comment]
`2023-12-05`

**Bug Fixes**

- dialog/goods-action-button: 修复 dialog、goods-action-button 组件缺少 getRealTimePhoneNumber 事件 [#5633](https://github.com/youzan/vant-weapp/issues/5633)
- upload: 修复企业微信下图片无法上传 [#5581](https://github.com/youzan/vant-weapp/issues/5581)
- calendar/input/textarea/popup: 修复 skyline 模式下组件报错问题 [#5650](https://github.com/youzan/vant-weapp/issues/5650)


**Document**

- area: 订正 columns-num 只支持 number 类型. [#5631](https://github.com/youzan/vant-weapp/issues/5631)
