### ISSUE TITLE
[Bug Report] van-field type="number" 输入框非数字输入框问题

### ISSUE THREAD

**Issue by liuweiqin** [youzan/vant-weapp#5662]
### 重现链接

暂无链接

### Vant Weapp 版本

1.11.2

### 描述一下你遇到的问题。

```
<van-field  value="{{ value }}" type="number"></van-field>
<input  type="number" />
```
van-field type number无效还是弹出字母键盘 而微信小程序<input  type="number" /> 这个是可以数字框的 微信小程序基础库3.1.5版本 系统是华为鸿蒙

### 重现步骤

就上面代码

### 设备/浏览器

鸿蒙系统

**Comment by johnsonwong666** [comment]
参数理论上是传过去了，我看手上测试机是可以的。手上没有你复现的那种设备，看能不能debug看下prop正确不。

**Comment by TallNutAlt** [comment]
我尝试了一下在鸿蒙系统中  并没有出现这种情况

**Comment by fujialez** [comment]
这个问题原因可能在于app.json中配置"componentFramework": "glass-easel",作者的这个bug通过这个能够复现,,这个属性会造成各种bug

**Comment by johnsonwong666** [comment]
尝试一下 @fujialez 说的 删除 "componentFramework": "glass-easel",
