### ISSUE TITLE
[Bug Report] 在<include /> 中使用wx:if条件渲染组件，在真机中无效

### ISSUE THREAD

**Issue by SecretCastle** [youzan/vant-weapp#5664]
### 重现链接

https://developers.weixin.qq.com/s/yKjGKAmn7dN7

### Vant Weapp 版本

1.11.2

### 描述一下你遇到的问题。

https://github.com/youzan/vant-weapp/blob/f2ff0e7b48de6689a7312bdb2c36d013d32e5d78/packages/field/index.wxml#L27

> 这里的判断是不是有问题？？？

* 在开发者工具中，可按条件通过`<include />`渲染引用文件。但是在真机环境下此举不生效。导致参与判断的引用文件均渲染。
* 采用最新版本基础库`3.2.4`也是同样的现象。

> 导致的问题

导致在真机场景下(安卓和iOS)，输入框的placeholder往上部偏移。安卓在调试模式下，手动删除`<textarea />`， 偏移问题消失。

设备：安卓(v8.0.44) iOS(v8.0.44)

### 重现步骤

使用`<van-Field />`，输入placeholder，真机调试查看

**Comment by johnsonwong666** [comment]
app.json 文件中删除 "componentFramework": "glass-easel" 试试

**Comment by johnsonwong666** [comment]
已反馈官方 官方在修复了
 https://github.com/wechat-miniprogram/glass-easel/issues/118
 
 临时解决
 app.json 文件中删除 "componentFramework": "glass-easel"

**Comment by SecretCastle** [comment]
@johnsonwong666 是否考虑这里做个兼容处理呢?? 比如外层使用`<block />`包裹，正如文档所属，`<block />`并不做渲染，只接受控制属性。
