### ISSUE TITLE
van-swipe-cell能否提供一个获取当前单元格的左右侧状态 

### ISSUE THREAD

**Issue by TallNutAlt** [youzan/vant-weapp#5666]
### 这个功能解决了什么问题？

我们需要对滑动后右侧删除显示出来后 进行特殊处理  但是目前获取不到右侧的状态 来判断是否显示

### 你期望的 API 是什么样子的？

在bind:click事件中加些参数 当前左右侧各自的显示状态

**Comment by johnsonwong666** [comment]
出现时 会触发 bind:open

**Comment by TallNutAlt** [comment]
> 出现时会触发bind:open

我知道，但是我需要在click点击事件里根据是否显示进行特殊处理

**Comment by TallNutAlt** [comment]
`<van-swipe-cell right-width="{{ 70 }}" async-close bind:close="onClose" data-id="clone{{index}}" id="clone{{index}}" bind:click="gotoMessage" bind:open="onOpen" data-value="{{item}}" > `
open会触发但是onClose并不会  因此我不知道左右侧是否有一方处于显示状态

**Comment by johnsonwong666** [comment]
设计上左右侧好像不会同时显示吧。

**Comment by TallNutAlt** [comment]
> 设计左右侧要求不会同时显示吧。

是的不会

**Comment by johnsonwong666** [comment]
不会同时出现的话，你open左边的，那么右边的就是关闭。触发close就是都关闭

**Comment by TallNutAlt** [comment]
> 不会同时出现的话，你打开左边的，那么右边的就是关闭。触发close就是都关闭

close并没有触发  open是正常触发的

**Comment by johnsonwong666** [comment]
close没触发，有点问题，需要修一下

**Comment by TallNutAlt** [comment]
> close没触发，有点问题，需要修一下

好的

**Comment by johnsonwong666** [comment]
我看了下代码 设计上是在使用  async-close 属性的时候 才会触发close 事件，看是否在这种情况下能不能满足你的需要？

**Comment by TallNutAlt** [comment]
`<van-swipe-cell right-width="{{ 70 }}" async-close bind:close="onClose" data-id="clone{{index}}" id="clone{{index}}" bind:click="gotoMessage" bind:open="onOpen" data-value="{{item}}" > `我已经使用async-close   close事件并没有被触发

**Comment by johnsonwong666** [comment]
https://developers.weixin.qq.com/s/NwHGjamA7bM4 这个小程序代码片段修改一下，修改成你的情况然后重新分享一下过来看一下

**Comment by TallNutAlt** [comment]
https://developers.weixin.qq.com/s/4uZYYLmY7hNq

**Comment by TallNutAlt** [comment]
@johnsonwong666

**Comment by johnsonwong666** [comment]
目前实现 有break change 计划在2.0支持
