### ISSUE TITLE
[Bug Report] van-field 真机上同时渲染出textarea input

### ISSUE THREAD

**Issue by se7en-eeen** [youzan/vant-weapp#5667]
### 重现链接

![微信图片_20231220170556](https://github.com/youzan/vant-weapp/assets/38373462/5a3246ba-c30f-4c35-a74d-3ff48dfd09d5)

### Vant Weapp 版本

1.11.1

### 描述一下你遇到的问题。

van-field 真机上同时渲染出textarea input 样式错乱
`<van-field type="text" label="昵称" placeholder="请输入昵称">
        <view slot="input">
            <input type="nickname" model:value="{{ nickname }}"
                   placeholder-style="color: #D8CDCF;" placeholder="请输入昵称"/>
        </view>
    </van-field>
    <van-field type="text" model:value="{{ phone }}" label="手机号" placeholder="请输入手机号"/>`

### 重现步骤

上述代码

### 设备/浏览器

微信小程序 基础库3.2.4

**Comment by johnsonwong666** [comment]
已反馈官方 官方在修复了
 https://github.com/wechat-miniprogram/glass-easel/issues/118
 
 临时解决
 app.json 文件中删除 "componentFramework": "glass-easel"
