### ISSUE TITLE
Cascader 级联选择

### ISSUE THREAD

**Issue by kairowan** [youzan/vant-weapp#5668]
### 这个功能解决了什么问题？

异步加载也可以多级列表吗,我看文档只有二级,我这边目前需要4级,因为我本身数据有2mb,不用异步加载会很慢很慢

### 你期望的 API 是什么样子的？
无

**Comment by johnsonwong666** [comment]
文档是示例二级，根据自己的业务情况调整代码。

**Comment by kairowan** [comment]
我的意思是小程序的是否支持异步加载4级联动

**Comment by johnsonwong666** [comment]
可以尝试一下，监听 change 事件，动态设置每一级options。

**Comment by silenceofWT** [comment]
为什么我动态更新options失效呢
