### ISSUE TITLE
tabs缺少active-color api

### ISSUE THREAD

**Issue by tong233** [youzan/vant-weapp#567]
**你需要的功能是？**
你好,设置color不管激活未激活都是一个颜色

**你期望 API 是什么样的？**
增加active-color

**Comment by chenjiahan** [comment]
color 属性就是针对激活的 tab 的

**Comment by tong233** [comment]
那就是bug了，不激活的tab也变色了。
![tim 20180913113240](https://user-images.githubusercontent.com/21073132/45480313-4c136500-b77b-11e8-8797-0e08ff53c925.png)

**Comment by tong233** [comment]
感谢修复，还有个tab的需求，tab能否固定在顶部，fixed布局。不然每次都要划回顶部才能切换tab。

**Comment by tong233** [comment]
3.2设置color后底部条没了

**Comment by sunkehappy** [comment]
我也有这个需求，tab需要固定在上面，下方的内容有可能会多于一页，需要滚动。

**Comment by chenjiahan** [comment]
@tong233 没有复现底部条消失的问题，可以提供一下复现代码吗
@sunkehappy 吸顶功能会在后续支持

**Comment by tong233** [comment]
@chenjiahan 我重新clone，底部条出现了。

**Comment by chenjiahan** [comment]
好的
