### ISSUE TITLE
[Bug Report] radio组件icon样式出现错误

### ISSUE THREAD

**Issue by Young0ne018** [youzan/vant-weapp#5670]
### 重现链接

![image](https://github.com/youzan/vant-weapp/assets/82131809/651b4658-989c-4b60-8d4a-33448dc99dd6)

### Vant Weapp 版本

1.11.2

### 描述一下你遇到的问题。

即使没有选中该radio，但是radio依然是属于打勾的状态
![image](https://github.com/youzan/vant-weapp/assets/82131809/560659d0-bb31-45c4-9c33-c677c14c0c7e)

### 重现步骤

直接点击radio

**Comment by johnsonwong666** [comment]
提供一个完整的复现代码片段看一下 https://developers.weixin.qq.com/s/NwHGjamA7bM4 
这个小程序代码片段修改一下，修改成你的情况然后重新分享一下过来看一下

**Comment by johnsonwong666** [comment]
之前有人反馈过这个问题 升级一下微信版本内核 以及基础课版本看是否可以解决。

**Comment by Young0ne018** [comment]
已经解决了，原因是项目中全局的指定了view的color属性以及更改了--color-text-primary的css变量的值
