### ISSUE TITLE
[Bug Report] vant-cascader slot="title" 不生效

### ISSUE THREAD

**Issue by zmx0142857** [youzan/vant-weapp#5672]
### 重现链接

```html
<van-cascader>
  <view slot="title" class="modal-title">111111</view>
</van-cascader>
```
![9af40ec661e21bb16a0bed568313bbe2](https://github.com/youzan/vant-weapp/assets/25482626/1244c419-f668-4adf-9b81-64ac743e14e4)

### Vant Weapp 版本

1.10.15

### 描述一下你遇到的问题。

vant-cascader slot="title" 不生效

### 重现步骤

https://github.com/youzan/vant-weapp/blob/f2ff0e7b48de6689a7312bdb2c36d013d32e5d78/lib/cascader/index.wxml#L4C80-L4C80
```html
<text class="van-cascader__title"><slot name="title"></slot>{{ title }}</text>
```
建议把 text 改为 view，因为小程序在 text 下嵌套的 view 无法正常显示

### 设备/浏览器

微信开发者工具、微信小程序安卓手机预览均可复现

**Comment by johnsonwong666** [comment]
看代码应该是想往title前面加点行内的元素，比如图标什么的。可以提个pr过来看一下。

**Comment by landluck** [comment]
`v1.11.3` 已支持
