### ISSUE TITLE
media-type 不支持 mix 值，

### ISSUE THREAD

**Issue by zhoumao1** [youzan/vant-weapp#5675]
### 重现链接

```html
<van-uploader
	multiple
	accept="media"
	media-type="mix"
/>
```

### Vant Weapp 版本

1.11.2

### 描述一下你遇到的问题。

- accept：media， media-type：mix，此时可以混合选择视频和图片，但是选择视频后，没办法拿到缩略图
![image](https://github.com/youzan/vant-weapp/assets/43697061/98fb993d-47a8-44e1-89f8-f0f779837e4e)

- 另外为什么 media-type 不支持 mix 呢？很多时候都需要混合选择图片以及视频

### 重现步骤

```html
<van-uploader
	multiple
	accept="media"
	media-type="mix"
/>
```

### 设备/浏览器

所有设备

**Comment by johnsonwong666** [comment]
media-type 传数组 ['image', 'video']

**Comment by zhoumao1** [comment]
> media-type 传数组 ['image'， 'video']media-type 传数组 ['image'，'video']

这样只能选择图片，或者只选择视频，没办法图片以及视频混合选择

**Comment by johnsonwong666** [comment]
看代码没有仅限制这两个参数 而去官方文档 需要是的是一个string数组。你把三个都传进去试试
<img width="817" alt="image" src="https://github.com/youzan/vant-weapp/assets/64689255/f51c9945-fb0d-44d1-b9aa-aa8de193c085">

**Comment by zhoumao1** [comment]
尝试了，😄还是一样的问题，我看了下源码，内部如果遇到 accept 为 media 时，会根据 fileType 来进行 format 数据，但是没有考虑到 fileType 为 mix 的情况，所以。。。以后只能等官方处理了
![image](https://github.com/youzan/vant-weapp/assets/43697061/e5f3b00d-0148-4f0e-9622-2043e29dee57)

**Comment by johnsonwong666** [comment]
可以提个pr过来兼容一下

**Comment by landluck** [comment]
`v1.11.3` 已支持
