### ISSUE TITLE
[Feature Request] van-dialog van-action-sheet 等组件对root-portal属性的支持

### ISSUE THREAD

**Issue by yming** [youzan/vant-weapp#5677]
### 这个功能解决了什么问题？

是否可以支持使用了popup的组件（如dialog  action-sheet等）对root-portal属性的支持，现在有类似需求时 就无法直接使用相关组件了，只能全部使用popup自己重建dialog   action-sheet类似的组件

### 你期望的 API 是什么样子的？

```
<van-dialog root-portal="true" />
<van-action-sheet root-portal="true" />
...
```

**Comment by landluck** [comment]
`v1.11.3` 已支持
