### ISSUE TITLE
[Bug Report] 输入框field，搜索框search的placeholder行高不生效，导致上移，原生输入框没有这个

### ISSUE THREAD

**Issue by Yetongge** [youzan/vant-weapp#5678]
### 重现链接

<van-search placeholder="请输入关键字1"></van-search>
<van-field placeholder="请输入关键字2"></van-field>
<van-cell>
  <view><input style="border: 1rpx solid #f00;text-align: left;" placeholder="请输入关键字3" /></view>
</van-cell>

### Vant Weapp 版本

1.11.2

### 描述一下你遇到的问题。

vant的输入框placeholder错位（**开发者工具正常，体验版，正式版不正常**）
![Screenshot_2023-12-27-15-55-17-706_com tencent mm](https://github.com/youzan/vant-weapp/assets/57281756/1b46e01a-da7f-43b2-a5ad-7f7668eaad7b)

### 重现步骤

无

**Comment by Yetongge** [comment]
代码
`<van-nav-bar title="标题" left-text="返回" left-arrow fixed placeholder bind:click-left="onClickLeft" />
<van-search placeholder="请输入关键字1"></van-search>
<van-field placeholder="请输入关键字2"></van-field>
<van-cell>
  <view><input style="border: 1rpx solid #f00;text-align: left;" placeholder="请输入关键字3" /></view>
</van-cell>`

**Comment by johnsonwong666** [comment]
app.json 删除skyline 相关的配置 试下可以解决不

**Comment by Yetongge** [comment]
删除了app.json中的skyline配置，还是不行


小葛
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "youzan/vant-weapp"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年12月27日(星期三) 下午4:06
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [youzan/vant-weapp] [Bug Report] 输入框field，搜索框search的placeholder行高不生效，导致上移，原生输入框没有这个 (Issue #5678)





 
app.json 删除skyline 相关的配置 试下可以解决不

**Comment by johnsonwong666** [comment]
https://developers.weixin.qq.com/s/NwHGjamA7bM4 
这个小程序代码片段修改一下，修改成你的情况然后重新分享一下过来看一下

**Comment by Yetongge** [comment]
对比出来了，是app.json中的"componentFramework":&nbsp;"glass-easel"影响的，感谢回复


小葛
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "youzan/vant-weapp"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年12月27日(星期三) 下午4:11
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [youzan/vant-weapp] [Bug Report] 输入框field，搜索框search的placeholder行高不生效，导致上移，原生输入框没有这个 (Issue #5678)





 
https://developers.weixin.qq.com/s/NwHGjamA7bM4&nbsp;这个小程序代码片段修改一下，修改成你的情况然后重新分享一下过来看一下
