### ISSUE TITLE
[Bug Report] 请在此填写标题

### ISSUE THREAD

**Issue by zeb9518** [youzan/vant-weapp#5683]
### 重现链接

<van-action-sheet show="{{ areaSheetShow }}">
  <van-area title="选择地址" area-list="{{ areaList }}" bind:cancel="hideAreaSheet" bind:confirm="handleConfirmArea" />
</van-action-sheet>

### Vant Weapp 版本

1.11.2

### 描述一下你遇到的问题。

微信小程序ios真机显示、顶部底部均出现操作栏
![1703819828622](https://github.com/youzan/vant-weapp/assets/56330641/ff28c655-6cd9-4dcf-9af3-03ea6487f63f)

### 重现步骤

在ios 真机模式下显示van-area组件

### 设备/浏览器

ios 系统版本：17.2.1

**Comment by johnsonwong666** [comment]
删除app.json  glass-easel 那个配置 微信官方的dug
