### ISSUE TITLE
van-picker 组件多列显示 className  不生效

### ISSUE THREAD

**Issue by clxye** [youzan/vant-weapp#5684]
### 重现链接

代码来源于官方示例代码，我只是添加了 column1 和 column2 的样式，但结果不生效。

wxml
`<van-picker columns="{{ columns }}" />`

js
`data: {
    columns: [
      {
        values: Object.keys(citys),
        className: 'column1',
      },
      {
        values: citys['浙江'],
        className: 'column2',
        defaultIndex: 2,
      },
    ],
  },`
  
wxss
`
.column1 {
  font-size: 30rpx;
  background-color: red;
}

.column2 {
  font-size: 80rpx;
  background-color: green;
}
`

### Vant Weapp 版本

1.11.1

### 描述一下你遇到的问题。

van-picker 多列显示不能通过 className 实现多列的样式定制。

原始需求：我需要实现下图的多列效果。
![image](https://github.com/youzan/vant-weapp/assets/6647076/e5714711-93e2-4431-bc34-bb746976f99c)
定制选中样式时需要区分当前的选中样式是第一列还是第二列，没有想到更好的方法。目前我想到的只能是初始化时分别给第一列和第二列指定不同的样式，在每个样式中通过 ::after 构建出"男孩"或"女孩"的文本。

如果是我 className 的用法有误，麻烦帮忙指正一下，给出正确用法的示例代码。如果有别的方法能够实现指定选中样式时可以区分第一列和第二列，给出相关的解决方案也行。

谢谢！

### 重现步骤

在分别制定了 column1 还 column2 后，样式没有生效。

**Comment by johnsonwong666** [comment]
这里应该是个文档错误，className应该只适用于h5版本的vant。微信小程序需要通过传递外部样式类把样式传到底层组件去，但是这个不能够动态设置。目前想要改列的样式的话需要通过传column-class去修改。
