### ISSUE TITLE
ActionSheet 动作面板

### ISSUE THREAD

**Issue by 2190371141** [youzan/vant-weapp#5689]
### Vant Weapp 版本

"@vant/weapp": "^1.11.1"

### 描述一下你遇到的问题。

关闭按钮显示失败 空白方框

### 重现步骤

弹出显示后

### 设备/浏览器

iso 微信小程序

**Comment by johnsonwong666** [comment]
重新装一下vant weapp试试  可能这个@vant/icons版本不对
