### ISSUE TITLE
uploader组件支持企业微信

### ISSUE THREAD

**Issue by shiyl962** [youzan/vant-weapp#5691]
### 这个功能解决了什么问题？

小程序在开发工具中运行正常，在真机上微信环境下运行正常，而在真机上企业微信环境下点击上传图标无响应，显示暂时不支持...，希望解决此问题

### 你期望的 API 是什么样子的？

<van-uploader :file-list="fileList"
                 accept="file"
                 upload-text="选文件"
                 @after-read="uploader.afterRead"
                 @delete="uploader.delete" />

**Comment by johnsonwong666** [comment]
什么操作显示暂时不支持呢？我试了下可以上传图片和视频呀

**Comment by johnsonwong666** [comment]
<img width="829" alt="image" src="https://github.com/youzan/vant-weapp/assets/64689255/982efce7-29d4-4ed5-bae5-ec4bd0d2991b">
搜了一下 accept为file时会调用  wx.chooseMessageFile  企业微信目前不支持这个api
