### ISSUE TITLE
请问一下sticky 是不能在 flex 布局中使用吗

### ISSUE THREAD

**Issue by niguibin** [youzan/vant-weapp#5692]
### 重现链接

`<view style="height: 1000px;">
  <view>基础用法</view>
  <view style="margin-top: 200rpx; display: flex;">
    <van-sticky>
      <van-button style="width: 300rpx;" type="primary">基础用法</van-button>
    </van-sticky>
    <view style="border: 1px solid red; display: flex; flex-direction: column; width: 450rpx; margin-left: 40rpx;">
      <view>helloworld</view>
      <van-sticky offset-top="{{ 90 }}">
        <van-button type="info">吸顶距离</van-button>
      </van-sticky>
    </view>
  </view>
</view>`

### Vant Weapp 版本

1.11.1

### 描述一下你遇到的问题。

在 flex 中，到达吸顶位置后，边距样式就不是以父元素为准了，而是以屏幕为准了，如下，蓝色这个按钮，吸顶后位置变了
![17](https://github.com/youzan/vant-weapp/assets/46620839/98253c14-bfad-4662-a96d-612eeaf260a9)

![18](https://github.com/youzan/vant-weapp/assets/46620839/47b34000-ec09-4125-92df-ccf4b734c6ed)

### 重现步骤

滑动即可

### 设备/浏览器

微信开发者工具

**Comment by niguibin** [comment]
抱歉，上面代码没格式没弄好，代码如下
```
<view style="height: 1000px;">
  <view>基础用法</view>
  <view style="margin-top: 200rpx; display: flex;">
    <van-sticky>
      <van-button style="width: 300rpx;" type="primary">基础用法</van-button>
    </van-sticky>
    <view style="border: 1px solid red; display: flex; flex-direction: column; width: 450rpx; margin-left: 40rpx;">
      <view>helloworld</view>
      <van-sticky offset-top="{{ 90 }}">
        <van-button type="info">吸顶距离</van-button>
      </van-sticky>
    </view>
  </view>
</view>
```

**Comment by johnsonwong666** [comment]
参考一下 指定容器部分
<img width="756" alt="image" src="https://github.com/youzan/vant-weapp/assets/64689255/13c47a57-2fd3-4adc-accf-9656bfd6aa92">

**Comment by mx-niguibin** [comment]
> 参考一下 指定容器部分 <img alt="image" width="756" src="https://private-user-images.githubusercontent.com/64689255/294804086-13c47a57-2fd3-4adc-accf-9656bfd6aa92.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ2ODMwMjAsIm5iZiI6MTcwNDY4MjcyMCwicGF0aCI6Ii82NDY4OTI1NS8yOTQ4MDQwODYtMTNjNDdhNTctMmZkMy00YWRjLWFjY2YtOTY1NmJmZDZhYTkyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA4VDAyNTg0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUxYTkyZDI2MmM2NzJmMDBiNTk4YjM3OTE3ZTQ1MjNhMDhlNzRkOTZjODc3ZjQ3ZTY5ZDVkZGM2NWNkY2MxNGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RNRWVx_YCRW5wdWoF_-2SlzbU-P6MJtsY9mBnT1_hUU">

仍然不行，指定父容器之后，当父容器到达顶部时，父容器的样式也会不受 flex 影响了，从而跑到左边去了，当按钮吸顶之后，按钮也不受父容器的 flex 布局影响，还是会跑到最左侧

```
<view style="height: 1000px;">
  <view>基础用法</view>
  <view style="margin-top: 200rpx; display: flex;">
    <van-sticky>
      <van-button style="width: 300rpx;" type="primary">基础用法</van-button>
    </van-sticky>
    <view id="stickyContainer" style="height: 500rpx; border: 1px solid red; display: flex; flex-direction: column; width: 450rpx; margin-left: 40rpx;">
      <view>helloworld</view>
      <van-sticky container="{{container}}">
        <van-button type="info">吸顶距离</van-button>
      </van-sticky>
    </view>
  </view>
</view>
```
<img width="376" alt="image" src="https://github.com/youzan/vant-weapp/assets/134259459/b0955ca3-5c76-47c4-acc0-344b930e7418">

<img width="374" alt="image" src="https://github.com/youzan/vant-weapp/assets/134259459/a28f0141-8090-4462-8d0b-a92f4f45f434">


然后我又试了一下不使用 flex 布局，发现按钮吸顶之后仍然不受父元素的样式影响，而且我怕 onReady 的时候，页面元素还没加载完成，在 onReady 中加了定时器，仍然是不行

wxml
```
<view style="height: 1000px;">
  <view>基础用法</view>
    <view id="stickyContainer" style="margin-top: 200rpx; height: 500rpx; border: 1px solid red; width: 450rpx; margin-left: 40rpx;">
      <view>helloworld</view>
      <van-sticky container="{{container}}">
        <van-button type="info">吸顶距离</van-button>
      </van-sticky>
    </view>
</view>
```

js
```
  onReady() {
    setTimeout(() => {
      this.setData({
        container: () => wx.createSelectorQuery().select('#stickyContainer'),
      })
      console.log(this.data.container)
    }, 1000)
  },
```

<img width="365" alt="image" src="https://github.com/youzan/vant-weapp/assets/134259459/38679ca0-19f7-4785-8ae3-cb223e89358f">

**Comment by niguibin** [comment]
> 参考一下 指定容器部分 <img alt="image" width="756" src="https://private-user-images.githubusercontent.com/64689255/294804086-13c47a57-2fd3-4adc-accf-9656bfd6aa92.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ2ODUwODksIm5iZiI6MTcwNDY4NDc4OSwicGF0aCI6Ii82NDY4OTI1NS8yOTQ4MDQwODYtMTNjNDdhNTctMmZkMy00YWRjLWFjY2YtOTY1NmJmZDZhYTkyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA4VDAzMzMwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ1ZGZjM2JjMWMyODY1YjUzMDg2MTNmYTFkZmYxMzYxNGM1OTkwNzE1NzIxNDYwMDEyMWIxYTZiNjkyMDc5M2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2o8F4-pt5JJR5deScryRyaIE4IDURo0iCmGYR0xUEhc">

仍然不行，指定父容器之后，当父容器到达顶部时，父容器的样式也会不受 flex 影响了，从而跑到左边去了，当按钮吸顶之后，按钮也不受父容器的 flex 布局影响，还是会跑到最左侧

```
<view style="height: 1000px;">
  <view>基础用法</view>
  <view style="margin-top: 200rpx; display: flex;">
    <van-sticky>
      <van-button style="width: 300rpx;" type="primary">基础用法</van-button>
    </van-sticky>
    <view id="stickyContainer" style="height: 500rpx; border: 1px solid red; display: flex; flex-direction: column; width: 450rpx; margin-left: 40rpx;">
      <view>helloworld</view>
      <van-sticky container="{{container}}">
        <van-button type="info">吸顶距离</van-button>
      </van-sticky>
    </view>
  </view>
</view>
```

<img width="762" alt="image" src="https://github.com/youzan/vant-weapp/assets/46620839/a292eb29-245e-4096-bbff-f6496394cf6e">

然后我又试了一下不使用 flex 布局，发现按钮吸顶之后仍然不受父元素的样式影响，而且我怕 onReady 的时候，页面元素还没加载完成，在 onReady 中加了定时器，仍然是不行
wxml
```
<view style="height: 1000px;">
  <view>基础用法</view>
    <view id="stickyContainer" style="margin-top: 200rpx; height: 500rpx; border: 1px solid red; width: 450rpx; margin-left: 40rpx;">
      <view>helloworld</view>
      <van-sticky container="{{container}}">
        <van-button type="info">吸顶距离</van-button>
      </van-sticky>
    </view>
</view>
```

js
```
  onReady() {
    setTimeout(() => {
      this.setData({
        container: () => wx.createSelectorQuery().select('#stickyContainer'),
      })
      console.log(this.data.container)
    }, 1000)
  },
```

<img width="347" alt="image" src="https://github.com/youzan/vant-weapp/assets/46620839/ee0e7526-106e-4110-841b-ec7686e754c1">

**Comment by johnsonwong666** [comment]
可能有点样式影响。你先复制官方示例的代码，然后在这基础上调整你的代码试试。

**Comment by niguibin** [comment]
> 可能有点样式影响。你先复制官方示例的代码，然后在这基础上调整你的代码试试。

试过了，直接用官方示例指定容器的代码，然后高度增加一点（超过屏幕高度），再加个 margin-top 和 margin-left， 就能复现出问题，所以说这是一个 bug 吗
```
<view id="container" style="border: 1px solid red; margin: 30rpx 0 0 30rpx; height: 600px;">
  <van-sticky container="{{ container }}">
    <van-button type="warning">指定容器</van-button>
  </van-sticky>
</view>
```

**Comment by johnsonwong666** [comment]
<img width="680" alt="image" src="https://github.com/youzan/vant-weapp/assets/64689255/b5262413-c854-4899-99a7-603ebc20d4e1">
实现上 sticky内部的组件 吸顶的时候 postion会设置成 fixed  会相对于屏幕

**Comment by niguibin** [comment]
> <img alt="image" width="680" src="https://private-user-images.githubusercontent.com/64689255/294826646-b5262413-c854-4899-99a7-603ebc20d4e1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ2OTY0NTUsIm5iZiI6MTcwNDY5NjE1NSwicGF0aCI6Ii82NDY4OTI1NS8yOTQ4MjY2NDYtYjUyNjI0MTMtYzg1NC00ODk5LTk5YTctNjAzZWJjMjBkNGUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA4VDA2NDIzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUwMDEzOWI2NzdiNTc2OTRiZGM0NTJjN2RiYTNlNmRiY2VkNWIxNTM3M2UyYzdkOGUyYzA4YjVjNTY3NTMyYmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.A1rYfpNF-AGz1YK7rsKZNHdqr9a3Z2fShcvEDyW_neE"> 实现上 sticky内部的组件 吸顶的时候 postion会设置成 fixed 会相对于屏幕

所以这个指定容器左右不能偏移吗，因为 sticky 组件中的父 view 设置了 position:relative，van-sticky 下想吸顶且有左右偏移量的元素也不能设置绝对定位了，这依然是个问题

**Comment by johnsonwong666** [comment]
你可以通过监听scroll事件。回调会给一个isFixed属性，然后动态设置sticky内部元素style试试。

**Comment by niguibin** [comment]
> 你可以通过监听scroll事件。回调会给一个isFixed属性，然后动态设置sticky内部元素style试试。

谢谢，，我一会试试，另外请问下，vant weapp2.x 什么时候发布呀

**Comment by johnsonwong666** [comment]
> > 你可以通过监听scroll事件。回调会给一个isFixed属性，然后动态设置sticky内部元素style试试。
> 
> 谢谢，，我一会试试，另外请问下，vant weapp2.x 什么时候发布呀

短期内还不会发布
