### ISSUE TITLE
真机调试变形不知道为什么

### ISSUE THREAD

**Issue by Gaichifanla** [youzan/vant-weapp#5693]
### 重现链接

<navigation-bar title="" back="{{true}}" color="lightgray" background="#FFF"  style="font-style: italic"></navigation-bar>
<view>
<van-cell-group>
    <van-field
            value="{{ message }}"
            type="textarea"
            placeholder="主题(必填)"
            autosize="{ maxHeight: 100rpx, minHeight: 50rpx }"
            bind:change="onChangeTopic"
            border="{{ false }}"
        />
        <van-field
            value="{{ message }}"
            type="textarea"
            placeholder="任务内容"
            custom-style="height:200rpx;margin-top:1rpx"
            autosize="{ maxHeight: 100rpx, minHeight: 50rpx }"
            bind:change="onChangeContent"
            border="{{ false }}"
        />
    </van-cell-group>

    <van-cell-group>
            <van-cell title="负责人" value="{{leaderid}}" is-link link-type="navigateTo" url="./team_member_select/select_leader" />
            <van-cell title="起止时间" value="{{ date }}" bind:click="onDisplay" />
            <van-calendar
                show="{{ show }}"
                type="range"
                bind:close="onClose"
                bind:confirm="onConfirm"
                color="#7232dd"
            />
            <van-cell title="项目" value="" is-link />
            <van-cell title="部门" value="" is-link />
            <van-cell title="优先级" value="" is-link />
            <van-cell label="本月已完成任务子项及子项" />
        </van-cell-group>
    </view>
    <van-button bind:click="" button-id="button1" color="#ffd54b" plain>保存并继续</van-button>
    <van-button bind:click="store" button-id="button2" color="#ffd54b" plain>保存任务</van-button>

### Vant Weapp 版本

1.10.25

### 描述一下你遇到的问题。

有好几个组件，日历选择，搜索框
模拟器里：
![1704721163354](https://github.com/youzan/vant-weapp/assets/109074065/a494509d-2aab-47a3-8c9e-ce4937bfb6dc)
真机调试：
![1704721236437](https://github.com/youzan/vant-weapp/assets/109074065/98d87147-b7a1-4a21-82ef-49380a096dcf)
就变了样子，我也不是很清楚为什么

### 重现步骤

就这个代码，，我用的电脑端真机调试，然后打开就是会变形

### 设备/浏览器

pc端

**Comment by johnsonwong666** [comment]
app.json 看有 { "componentFramework": "glass-easel" } 吗。删掉试试

**Comment by Gaichifanla** [comment]
可以了，非常感谢
