### ISSUE TITLE
[Feature Request] 建议新增form表单组件

### ISSUE THREAD

**Issue by paker777** [youzan/vant-weapp#5694]
### 这个功能解决了什么问题？

表单校验

### 你期望的 API 是什么样子的？

<van-form @submit="onSubmit">
  <van-field
    v-model="username"
    name="用户名"
    label="用户名"
    placeholder="用户名"
    :rules="[{ required: true, message: '请填写用户名' }]"
  />
  <van-field
    v-model="password"
    type="password"
    name="密码"
    label="密码"
    placeholder="密码"
    :rules="[{ required: true, message: '请填写密码' }]"
  />
  <div style="margin: 16px;">
    <van-button round block type="info" native-type="submit">提交</van-button>
  </div>
</van-form>
```[tasklist]
### Tasks
```

**Comment by johnsonwong666** [comment]
2.0版本 计划支持这个组件

**Comment by TopAlien** [comment]
复议
