### ISSUE TITLE
在 IOS 端 使用field组件，设置类型为 textarea， 做回显操作时, 高度没有撑开, 点击 textarea 才显示完整

### ISSUE THREAD

**Issue by yunyingchen** [youzan/vant-weapp#5696]
### 重现链接

直接看图片

### Vant Weapp 版本

"version": "1.11.1"

### 描述一下你遇到的问题。

在 IOS 端 使用 textarea 做 回显 操作时, 会出现高度没有撑开, 点击 textarea 才显示完整
如下图所示：
![image](https://github.com/youzan/vant-weapp/assets/30464962/317193ce-3d38-49e8-badc-0766e1d44af8)

### 重现步骤

1、使用van-field，设置 type="textarea" autosize="{{true}}"
2、真机预览

### 设备/浏览器

iOS系统手机

**Comment by johnsonwong666** [comment]
autosize 不用传true。直接写个autosize 在标签上试试。

**Comment by yunyingchen** [comment]
一开始写的autosize 没用

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年01月11日 19:51 |
| 收件人 | youzan/vant-weapp ***@***.***> |
| 抄送人 | yunyingchen ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [youzan/vant-weapp] 在 IOS 端 使用field组件，设置类型为 textarea， 做回显操作时, 高度没有撑开, 点击 textarea 才显示完整 (Issue #5696) |

autosize 不用传true。直接写个autosize 在标签上试试。

**Comment by johnsonwong666** [comment]
app.json 是否 有 { "componentFramework": "glass-easel" } ? 有的话删掉试试

**Comment by yunyingchen** [comment]
没有配置，之前就删掉了

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年01月12日 10:10 |
| 收件人 | youzan/vant-weapp ***@***.***> |
| 抄送人 | yunyingchen ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [youzan/vant-weapp] 在 IOS 端 使用field组件，设置类型为 textarea， 做回显操作时, 高度没有撑开, 点击 textarea 才显示完整 (Issue #5696) |

app.json 是否 有 { "componentFramework": "glass-easel" } ? 有的话删掉试试

**Comment by johnsonwong666** [comment]
https://developers.weixin.qq.com/s/NwHGjamA7bM4 
这个小程序代码片段修改一下成最小复现片段，然后重新分享一下过来看一下

**Comment by yunyingchen** [comment]
链接打开提示“正在打开微信开发者工具……”但就是打不开

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年01月15日 10:16 |
| 收件人 | youzan/vant-weapp ***@***.***> |
| 抄送人 | yunyingchen ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [youzan/vant-weapp] 在 IOS 端 使用field组件，设置类型为 textarea， 做回显操作时, 高度没有撑开, 点击 textarea 才显示完整 (Issue #5696) |

https://developers.weixin.qq.com/s/NwHGjamA7bM4 
这个小程序代码片段修改一下成最小复现片段，然后重新分享一下过来看一下

**Comment by yunyingchen** [comment]
<van-cell class="block-cell">
          <label slot="title" class="block-title">主题</label>
          <van-field value="{{ ruleForm.title }}" type="textarea" placeholder="请输入" autosize border="{{ false }}" error-message="{{errorMsg.title}}" maxlength="100" show-word-limit bind:blur="onTitleBlur" class="{{ curDisabledType ? 'textarea-title':'' }}" />
        </van-cell>

**Comment by yunyingchen** [comment]
> [https://developers.weixin.qq.com/s/NwHGjamA7bM4 ](https://developers.weixin.qq.com/s/NwHGjamA7bM4%C2%A0) 这个小程序代码片段修改一下成最小复现片段，然后重新分享一下过来看一下

<van-cell class="block-cell">
          <label slot="title" class="block-title">主题</label>
          <van-field value="{{ ruleForm.title }}" type="textarea" placeholder="请输入" autosize border="{{ false }}" error-message="{{errorMsg.title}}" maxlength="100" show-word-limit bind:blur="onTitleBlur" class="{{ curDisabledType ? 'textarea-title':'' }}" />
        </van-cell>  这是代码

**Comment by johnsonwong666** [comment]
https://developers.weixin.qq.com/s/NwHGjamA7bM4

**Comment by yunyingchen** [comment]
https://developers.weixin.qq.com/s/ATwDBemP7BOB

**Comment by yunyingchen** [comment]
> https://developers.weixin.qq.com/s/ATwDBemP7BOB

js版本 在iOS下表现是正常的，要搭建ts版本的进行测试，搭建流程参考vant官方手册https://youzan.github.io/vant-weapp/#/quickstart

**Comment by yunyingchen** [comment]
js版本 在iOS下表现是正常的，要搭建ts版本的进行测试，复现步骤：
1、新建项目，选择模板ts+sass基础模版：
![image](https://github.com/youzan/vant-weapp/assets/30464962/fa0e19f1-3de2-41a7-9331-c331528fefab)
2、引入vant组件，https://youzan.github.io/vant-weapp/#/quickstart；
3、代码片段链接：https://developers.weixin.qq.com/s/5ZxSPem57wOt，复制代码片段中的代码和样式，在iOS手机上预览

**Comment by johnsonwong666** [comment]
是什么设备？我手上这台iphone xr 按照你的步骤新建了一个项目，没有复现你那种情况，textarea 是展开的。

**Comment by yunyingchen** [comment]
我试过的设备有iPhone12pm，iPhone15,iPhone8p

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年01月16日 15:59 |
| 收件人 | youzan/vant-weapp ***@***.***> |
| 抄送人 | yunyingchen ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [youzan/vant-weapp] 在 IOS 端 使用field组件，设置类型为 textarea， 做回显操作时, 高度没有撑开, 点击 textarea 才显示完整 (Issue #5696) |

是什么设备？我手上这台iphone xr 按照你的步骤新建了一个项目，没有复现你那种情况，textarea 是展开的。

**Comment by yunyingchen** [comment]
这个问题目前我们团队已解决，您费心了，谢谢！

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年01月16日 15:59 |
| 收件人 | youzan/vant-weapp ***@***.***> |
| 抄送人 | yunyingchen ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [youzan/vant-weapp] 在 IOS 端 使用field组件，设置类型为 textarea， 做回显操作时, 高度没有撑开, 点击 textarea 才显示完整 (Issue #5696) |

是什么设备？我手上这台iphone xr 按照你的步骤新建了一个项目，没有复现你那种情况，textarea 是展开的。

**Comment by yunyingchen** [comment]
![c9665cc5b1613836a1f95f3d39869671](https://github.com/youzan/vant-weapp/assets/30464962/01bea560-6fe3-4f1a-bcf2-d5dabd3d8bb4)
源码中这个回调函数初始化时的event参数中的{height：xxx}是错误的；在外层重新渲染，回调返参才是正确的，加个wx:if，就能解决。

**Comment by johnsonwong666** [comment]
什么原因？ @yunyingchen

**Comment by johnsonwong666** [comment]
> ![c9665cc5b1613836a1f95f3d39869671](https://private-user-images.githubusercontent.com/30464962/297004855-01bea560-6fe3-4f1a-bcf2-d5dabd3d8bb4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzOTkyNzEsIm5iZiI6MTcwNTM5ODk3MSwicGF0aCI6Ii8zMDQ2NDk2Mi8yOTcwMDQ4NTUtMDFiZWE1NjAtNmZlMy00ZjFhLWJjZjItZDVkYWJkM2Q4YmI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE2VDA5NTYxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYzMGUwNDYyNGQwYTc5OWZiYjIxMDJjMDg0YTJmNzQ4ODg2MzhmNDY0N2MxMGQ2MWQ4ZDYwNGM2MjAxMGI1MjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xa3uoSFLTY03_iRLY_K2Hcci6k0HdONBKnqn5iks_Dk) 源码中这个回调函数初始化时的event参数中的{height：xxx}是错误的；在外层重新渲染，回调返参才是正确的，加个wx:if，就能解决。

了解了 wx:if 可以重新渲染组件

**Comment by yunyingchen** [comment]
是的，没错

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年01月16日 17:57 |
| 收件人 | youzan/vant-weapp ***@***.***> |
| 抄送人 | yunyingchen ***@***.***>,
Mention ***@***.***> |
| 主题 | Re: [youzan/vant-weapp] 在 IOS 端 使用field组件，设置类型为 textarea， 做回显操作时, 高度没有撑开, 点击 textarea 才显示完整 (Issue #5696) |

源码中这个回调函数初始化时的event参数中的{height：xxx}是错误的；在外层重新渲染，回调返参才是正确的，加个wx:if，就能解决。

了解了 wx:if 可以重新渲染组件

**Comment by yunyingchen** [comment]
![image](https://github.com/youzan/vant-weapp/assets/30464962/a183ec02-3f26-4d1d-b25c-fb0460a65f91)
![image](https://github.com/youzan/vant-weapp/assets/30464962/155b41f1-bcd5-44ef-829c-ae5a60fd42f6)
附上解决代码及步骤：1、在data里定义一个变量showTextarea控制显示隐藏；2、在回显数据的方法里调用setShowTextarea方法，3、 wx:if 绑定该变量。
