### ISSUE TITLE
[Bug Report] 请在此填写标题

### ISSUE THREAD

**Issue by leng-mou** [youzan/vant-weapp#5697]
### 重现链接

https://vant-contrib.gitee.io/vant-weapp/#/search

### Vant Weapp 版本

1.11.1

### 描述一下你遇到的问题。

![WechatIMG164055](https://github.com/youzan/vant-weapp/assets/57950167/c50b5db8-53c3-41d3-b60f-082240e62140)
华为meta30真机 placeholder位置显示有问题

### 重现步骤

111

**Comment by johnsonwong666** [comment]
app.json中看有"componentFramework": "glass-easel"吗？如果有的话删掉试试。

**Comment by leng-mou** [comment]
可以了谢谢大佬
