### ISSUE TITLE
微信小程序真机预览 为什么有些组件是错乱的

### ISSUE THREAD

**Issue by simplejuzi** [youzan/vant-weapp#5698]
### 重现链接

                    <van-calendar class="vancalendarStart"  show="{{ show }}" bind:close="onClose" bind:confirm="onStartDateConfiirm" />

### Vant Weapp 版本

1.11.2

### 描述一下你遇到的问题。

日历组件在开发者工具显示没有问题  但是在预览的时候就会出现图片这种情况  我切换了基础组件版本 大部分的是直接整个日历组件直接显示出来
![微信图片_20240115151226](https://github.com/youzan/vant-weapp/assets/56131811/542f3b7a-c9d4-4b48-ba9b-d63fb43ad2d4)

### 重现步骤

预览的时候直接错乱

### 设备/浏览器

只要是预览 不管是手机还是pc

**Comment by johnsonwong666** [comment]
app.json 是否 有 { "componentFramework": "glass-easel" } ? 有的话删掉试试

**Comment by simplejuzi** [comment]
> app.json 是否有 { "componentFramework": "glass-easel" } ？有什么删掉尝试

wc牛逼啊  真可以了 非常感谢大佬  这是什么原理

**Comment by johnsonwong666** [comment]
> > app.json 是否有 { "componentFramework": "glass-easel" } ？有什么删掉尝试
> 
> wc牛逼啊 真可以了 非常感谢大佬 这是什么原理

微信目前的bug
