### ISSUE TITLE
van-search搜索框问题

### ISSUE THREAD

**Issue by AliceWantToBackUw** [youzan/vant-weapp#5700]
### 重现链接

`wxml`
```
<!-- 搜索框 -->
<van-search
	class="search"
	value="{{ searchValue }}"
	label="名称"
	placeholder="请输入搜索关键词"
	use-action-slot
	bind:search="Search"
	bind:clear="Search"
	clearable
>
	<van-button slot="action" color="#7232dd" size="small" bind:click="Refresh">刷新</van-button>
</van-search>
```

### Vant Weapp 版本

1.11.2

### 描述一下你遇到的问题。

`微信开发者工具`下，检查搜索框可以看到下图
![van-search00](https://github.com/youzan/vant-weapp/assets/113964401/438e11cb-3627-4b7b-a8de-9acb67c5c4cc)

而在`真机调试`下，莫名出现了一个textarea
![van-search01](https://github.com/youzan/vant-weapp/assets/113964401/99bd0177-c1e6-4337-a688-9358e2958e8e)

**结果导致：**
本应该输入数据到input输入框的，在真机调试下全输入到了textarea；所以当在真机调试下，按下手机键盘上的回车它是换行，而不是确认。

<font color="red">该问题同样存在于`van-feild`</font>，附我当时的解决办法[http://t.csdnimg.cn/Fvoou](http://t.csdnimg.cn/Fvoou)

## 运行结果
![van-search手机02](https://github.com/youzan/vant-weapp/assets/113964401/8a92bee6-1d1e-45ea-a128-9a6eedcfa1db)
![van-search手机03](https://github.com/youzan/vant-weapp/assets/113964401/e573b50f-b500-46de-8416-3ab233b79e40)

## 运行环境
`project.config.json`
```
{
  "compileType": "miniprogram",
  "libVersion": "3.2.1",
  "packOptions": {
    "ignore": [],
    "include": []
  },
  "setting": {
    "coverView": true,
    "es6": true,
    "postcss": true,
    "minified": true,
    "enhance": true,
    "showShadowRootInWxmlPanel": true,
    "packNpmRelationList": [],
    "babelSetting": {
      "ignore": [],
      "disablePlugins": [],
      "outputPath": ""
    },
    "ignoreUploadUnusedFiles": true
  },
  "condition": {},
  "editorSetting": {
    "tabIndent": "auto",
    "tabSize": 2
  }
}
```
`project.private.config.json`
```
{
  "projectname": "demo01",
  "setting": {
    "compileHotReLoad": false,
    "urlCheck": false
  },
  "libVersion": "3.2.5"
}
```
手机：红米note10pro
![van-search手机](https://github.com/youzan/vant-weapp/assets/113964401/5f23e800-036a-48d8-816e-4739a762c15a)

真机调试：`2.0`

### 重现步骤

1、真机调试
2、在搜索框输入内容后回车

**Comment by johnsonwong666** [comment]
app.json 是否 有 { "componentFramework": "glass-easel" } ? 有的话删掉试试

**Comment by AliceWantToBackUw** [comment]
有，去掉了还真的行，非常非常感谢！(官方文档的快速上手可以加上更新一下o(〃＾▽＾〃)o)
