### ISSUE TITLE
[Feature Request] cell 组件能支持右侧 可放置 switch 组件么？

### ISSUE THREAD

**Issue by catelina95** [youzan/vant-weapp#5701]
### 这个功能解决了什么问题？

![CleanShot 2024-01-17 at 12 27 37@2x](https://github.com/youzan/vant-weapp/assets/16163090/119b9cb9-c61c-4b10-b4bf-3df594e0f646)

### 你期望的 API 是什么样子的？

![CleanShot 2024-01-17 at 12 25 53@2x](https://github.com/youzan/vant-weapp/assets/16163090/319f2c9e-4eee-465b-9abf-413abf84aab5)

**Comment by catelina95** [comment]
虽然好像可以放置switch 组件，但是没有垂直居中对齐
![CleanShot 2024-01-17 at 12 28 18@2x](https://github.com/youzan/vant-weapp/assets/16163090/4bf90f4c-6938-4013-a5a6-7409f2b96491)

**Comment by johnsonwong666** [comment]
这里样式通过custom-class调整一下，应该可以解决
