### ISSUE TITLE
<van-calendar type="range" /> 设置默认选择日期没有反应是什么原因呢

### ISSUE THREAD

**Issue by simplejuzi** [youzan/vant-weapp#5702]
### 重现链接

基础库3.3.2
代码截图 麻烦各位了 
![长图_2024-01-17](https://github.com/youzan/vant-weapp/assets/56131811/09e80200-771b-417f-beb1-707a12844b90)

### Vant Weapp 版本

1.11.2

### 描述一下你遇到的问题。

设置默认日期没反应

### 重现步骤

默认日期

### 设备/浏览器

预览和模拟器都是一样的

**Comment by johnsonwong666** [comment]
你这个是不是设置了一个过去的时间？传个min-date 把过去时间打开试试。

**Comment by simplejuzi** [comment]
> 你这个是不是设置了一个过去的时间？传个min-date 把过去时间打开试试。

我传的是2024-1-20和第二天的时间戳，而且mindate用起来特别的卡

**Comment by johnsonwong666** [comment]
https://developers.weixin.qq.com/s/NwHGjamA7bM4 
这个小程序代码片段修改一下，来个最简易的复现代码，然后重新分享一下过来看一下

**Comment by simplejuzi** [comment]
> [https://developers.weixin.qq.com/s/NwHGjamA7bM4 ](https://developers.weixin.qq.com/s/NwHGjamA7bM4%C2%A0) 这个小程序代码片段修改一下，来个最简易的复现代码，然后重新分享一下过来看一下

https://developers.weixin.qq.com/s/qihHpjmX7UOc
你看下

**Comment by johnsonwong666** [comment]
默认结束时间戳不对吧
<img width="276" alt="image" src="https://github.com/youzan/vant-weapp/assets/64689255/aafb9c03-e0ed-4cd4-9fc4-18dd48ad6577">
<img width="642" alt="image" src="https://github.com/youzan/vant-weapp/assets/64689255/fe2a4ccd-159d-4e3c-9c11-7239bb1d4c55">

**Comment by simplejuzi** [comment]
> 默认结束时间戳不对吧 <img alt="image" width="276" src="https://private-user-images.githubusercontent.com/64689255/297634396-aafb9c03-e0ed-4cd4-9fc4-18dd48ad6577.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1NjQ0ODgsIm5iZiI6MTcwNTU2NDE4OCwicGF0aCI6Ii82NDY4OTI1NS8yOTc2MzQzOTYtYWFmYjljMDMtZTBlZC00Y2Q0LTlmYzQtMThkZDQ4YWQ2NTc3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE4VDA3NDk0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU4MmZlMjNhNzY5MzA5MjExNGM5OWExMTYwZGExNGVlMDVjMzIxOWM2YjZjNmRjNzVkZTg4NDA1OTE3N2I3ZDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.79fuqD_Pmzu1C3sayjQXZXaDi8J93D1ewfOeeqr63Mw"> <img alt="image" width="642" src="https://private-user-images.githubusercontent.com/64689255/297634498-fe2a4ccd-159d-4e3c-9c11-7239bb1d4c55.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1NjQ0ODgsIm5iZiI6MTcwNTU2NDE4OCwicGF0aCI6Ii82NDY4OTI1NS8yOTc2MzQ0OTgtZmUyYTRjY2QtMTU5ZC00ZTNjLTljMTEtNzIzOWJiMWQ0YzU1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE4VDA3NDk0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMxYjlhNjA5MzNkZGQ1MWU2M2ViYzFmNTk4YTNlOWYxMDdhYjg2ZjhhZjAxN2Y2M2M5MGUwNGUxZGU0YTI2MDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lo3O1EQyFUtcpNHyWb5x2NGv43ijLIcy2LaLdAF1eM8">

解决了谢谢 是我不够细心 我都没有怀疑到时间戳方法上，一开始我有去转换 我是通过ai转换的 方法也是ai写的  我看返回来的没有问题  并没有去测试后几天的时间戳     最后非常感谢热心的大佬
