### ISSUE TITLE
DropdownMenu点击后不会自动收起

### ISSUE THREAD

**Issue by buaazyl** [youzan/vant-weapp#5703]
### 重现链接

https://developers.weixin.qq.com/s/03hsrlmL7pOD

需要点一下“构建npm”

### Vant Weapp 版本

1.11.3

### 描述一下你遇到的问题。

DropdownMenu点击后，不会自动收起

### 重现步骤

1.点击某一个选项即可

### 设备/浏览器

iOS，Mac，开发工具都可复现

**Comment by johnsonwong666** [comment]
1.11.4版本修复
