### ISSUE TITLE
小程序的treeSelect的插槽文档是不是有点问题

### ISSUE THREAD

**Issue by codermie** [youzan/vant-weapp#5706]
### 重现链接

slot=’content‘的时候说不能传items的数据，如果传了的话那么就会默认上面放着，但是上面文档举得案例也传了的，而且每个子项也是做到了每个不一样，这个文档没看懂是怎么操作的很多地方省略了好多内容，能详细介绍一下嘛，我做的业务是右边的子选项可以根据自己的插槽自己写样式，但是在文档里面没找到该途径

### Vant Weapp 版本

1.11.2

### 描述一下你遇到的问题。

slot=’content‘的时候说不能传items的数据，如果传了的话那么就会默认上面放着，但是上面文档举得案例也传了的，而且每个子项也是做到了每个不一样，这个文档没看懂是怎么操作的很多地方省略了好多内容，能详细介绍一下嘛，我做的业务是右边的子选项可以根据自己的插槽自己写样式，但是在文档里面没找到该途径
![微信截图_20240122163116](https://github.com/youzan/vant-weapp/assets/88971513/5a2c5cf0-5bcd-4118-88f2-edcc8cfa93ed)
![微信截图_20240122163200](https://github.com/youzan/vant-weapp/assets/88971513/61de0535-78e7-4609-b60f-accd2403949a)

### 重现步骤

slot=’content‘的时候说不能传items的数据，如果传了的话那么就会默认上面放着，但是上面文档举得案例也传了的，而且每个子项也是做到了每个不一样，这个文档没看懂是怎么操作的很多地方省略了好多内容，能详细介绍一下嘛，我做的业务是右边的子选项可以根据自己的插槽自己写样式，但是在文档里面没找到该途径

**Comment by codermie** [comment]
也有其他人提问过类似的但是都没解决，
https://github.com/youzan/vant-weapp/issues/4946
https://github.com/youzan/vant-weapp/issues/2036

**Comment by johnsonwong666** [comment]
![image](https://github.com/youzan/vant-weapp/assets/64689255/8acb08ea-4818-426f-84c2-5984f7f6a8f6)
