### ISSUE TITLE
[Bug Report] Toast.clear过快调用话会将后面的toast一并清理掉

### ISSUE THREAD

**Issue by renji566** [youzan/vant-weapp#5708]
### 重现链接

https://developers.weixin.qq.com/s/sLp4Vvm37QOs

### Vant Weapp 版本

1.11.4

### 描述一下你遇到的问题。

第一次调用duration为0的Toast.loading，然后调用Toast.clear,紧接着调用第二个duration为0的Toast.loading，会导致第二个loading也一并被清理,如果还带有forbidClick为true,clear后导致forbidClick依旧生效，按钮无法被点击

### 重现步骤

1.点击触发按钮 2.第一个loading立马消失，第二个loading无法显示,按钮不可在被点击

### 设备/浏览器

红米K60

**Comment by johnsonwong666** [comment]
什么场景会是这样操作的。比较常见的场景应该是某个异步请求结束后再去close，你可以给Toast.clear外面套一个setTimeout试试。然后我试了历史版本先后同步调用Toast.loading后面的会把前面那一个给覆盖掉。

**Comment by renji566** [comment]
> 什么场景会是这样操作的。比较常见的场景应该是某个异步请求结束后再去close，你可以给Toast.clear外面套一个setTimeout试试。然后我试了历史版本先后同步调用Toast.loading后面的会把前面那一个给覆盖掉。

是这样的，我是请求前loading,请求结束后close，后面产生新的loading的要去操作蓝牙设备，但是这请求响应很快，就会有问题，如果给后面那个loading加延迟，或者给close加点延迟，就不会有这个问题

**Comment by johnsonwong666** [comment]
加个settimeout 0 的定时器吧

**Comment by renji566** [comment]
> 加个settimeout 0 的定时器吧

但是以前不会有问题，突然就不好使了但是我另一个项目又正常 无语了

**Comment by johnsonwong666** [comment]
> > 加个settimeout 0 的定时器吧
> 
> 但是以前不会有问题，突然就不好使了但是我另一个项目又正常 无语了

最近有改动这一块代码 改成了异步形式 对比一下版本号
