### ISSUE TITLE
[Bug Report] 使用van-dialog 在里边使用input 输入框时 ，弹窗出现 输入框内容错位，几秒后又恢复原状

### ISSUE THREAD

**Issue by HouZhiGuoSir** [youzan/vant-weapp#5711]
### 重现链接

<van-dialog 
    use-slot
    show="{{ addShow }}"
    closeOnClickOverlay="{{true}}"
  > 
      <input placeholder="请输入开户银行"  type="text"/>
  </van-dialog>

### Vant Weapp 版本

1.11.3

### 描述一下你遇到的问题。

使用van-dialog 在里边使用input 输入框时 ，弹窗出现 输入框内容错位，几秒后又恢复原状

### 重现步骤

<van-dialog 
    use-slot
    show="{{ addShow }}"
    closeOnClickOverlay="{{true}}"
  > 
      <input placeholder="请输入开户银行"  type="text"/>
  </van-dialog>

**Comment by johnsonwong666** [comment]
input抖动 看起来是微信的老问题了 微信官方社区反馈不少
https://developers.weixin.qq.com/community/search?query=input%2520placeholder%2520%2520%25E6%258A%2596%25E5%258A%25A8&page=1&block=1&random=1706777357310&type=1
