### ISSUE TITLE
正式打包和测试环境打包 获取输入框和值的方式不一样

### ISSUE THREAD

**Issue by Hello-job** [youzan/vant-weapp#5712]
### 重现链接

 handleChange(event) {
        console.log('>>>>event', event);
        if (typeof event === 'object') {
          this.editValue = event.detail || event.detail.value;
        } else {
          this.editValue = event;
        }
      },

### Vant Weapp 版本

1.11.10

### 描述一下你遇到的问题。

正式打包和测试环境打包 获取输入框和值的方式不一样

### 重现步骤

1.测试环境数字输入框取值方式是 event.detail 到了正式环境直接返回数值导致报错 直接取event

**Comment by johnsonwong666** [comment]
vant-weapp 最新版本是1.11.4 然后你这个是在官方微信小程序开发者工具下面开发的嘛？

**Comment by Hello-job** [comment]
是的

**Comment by johnsonwong666** [comment]
> 是的

赋值怎么是this.xxx = xxx呢？有用什么框架吗？ uniapp或者taro什么的

**Comment by Hello-job** [comment]
uniapp

**Comment by Hello-job** [comment]
因为双向绑定没用

**Comment by johnsonwong666** [comment]
> uniapp

目前非原生微信小程序开发者工具上面产生的问题不会处理，可能是平台编译差异性导致

**Comment by Hello-job** [comment]
giao
