### ISSUE TITLE
van-sticky内嵌scrollview吸顶超出范围

### ISSUE THREAD

**Issue by XXiao32313322** [youzan/vant-weapp#5717]
### 重现链接

无

### Vant Weapp 版本

1.11.4

### 描述一下你遇到的问题。

van-sticky 组件在微信小程序中与scrollview联合使用出现bug：
当一个页面左右两部分都为scrollview时，右边的scrollview中有一个元素需要在scrollview区域内坐上吸顶操作，当将右边的滚动页面向上滑动时，van-sticky 包裹的元素跳出了右边的scrollview的容器范围，后来我改动了vant的源码，加上offset-left的属性，问题就可以解决了，所以希望官方在van-sticky 组件上和scrollview内嵌使用时能加一个offset-left的属性或者offset-right的属性，以此能够适应广大开发者更多的开发需求

### 重现步骤

无

### 设备/浏览器

小程序开发者工具

**Comment by johnsonwong666** [comment]
可以提个pr过来看一下

**Comment by johnsonwong666** [comment]
可以监听scroll事件，isFixed的时候，去设置left值。
