### ISSUE TITLE
[Bug Report] van-dialog 组件模式show异常，可以显示但不能关闭

### ISSUE THREAD

**Issue by zj2050** [youzan/vant-weapp#5718]
### 重现链接

<van-dialog use-slot title="授权提醒" show="{{ isLoginPopup }}" show-cancel-button style="z-index: 9999999;" confirm-button-open-type="getUserInfo" bind:getuserinfo="agreeGetUser" bind:cancel="onPopCancel">
     <view class="login-inner">
               <image class="avatar" src="/images/gravatar.png"></image>
               <view class="username">
                    <text>本操作必须获得您的授权，获取微信昵称信息，请确认</text>
               </view>
          </view>
</van-dialog>

     onPopCancel() {
          this.setData({
               isLoginPopup: false
          })
     },

定义了一个 van-dialog 组件，首次使用，可以显示，但onPopCancel事件设置 isLoginPopup  为false，dialog 不隐藏
跟踪能进入事件，且  isLoginPopup 为false

### Vant Weapp 版本

1.11.3

### 描述一下你遇到的问题。

<van-dialog use-slot title="授权提醒" show="{{ isLoginPopup }}" show-cancel-button style="z-index: 9999999;" confirm-button-open-type="getUserInfo" bind:getuserinfo="agreeGetUser" bind:cancel="onPopCancel">
     <view class="login-inner">
               <image class="avatar" src="/images/gravatar.png"></image>
               <view class="username">
                    <text>本操作必须获得您的授权，获取微信昵称信息，请确认</text>
               </view>
          </view>
</van-dialog>

     onPopCancel() {
          this.setData({
               isLoginPopup: false
          })
     },

定义了一个 van-dialog 组件，首次使用，可以显示，但onPopCancel事件设置 isLoginPopup  为false，dialog 不隐藏
跟踪能进入事件，且  isLoginPopup 为false

### 重现步骤

必须是清空状态下，单页确认后，关闭无效
![Uploading 1706249916.0882.png…]()

### 设备/浏览器

模拟器、ios、android都一样

**Comment by zj2050** [comment]
![Uploading 1706249916.0882.png…]()

**Comment by johnsonwong666** [comment]
没有很理解是什么问题 https://developers.weixin.qq.com/s/NwHGjamA7bM4 
这个小程序代码片段修改一下，修改成你的情况然后重新分享一下过来看一下

**Comment by johnsonwong666** [comment]
@zj2050

**Comment by johnsonwong666** [comment]
1.11.3 版本有bug。升级一下版本可以解决。
