### ISSUE TITLE
Skyline引擎下Calendar组件中使用的scroll-view组件缺少该引擎下独有属性type而无法加载

### ISSUE THREAD

**Issue by ClementLevi** [youzan/vant-weapp#5720]
### 重现链接

无需链接，修改`@vant/weapp/calendar/calendar.wxml`
文件下的scroll-view元素，如在第19行添加type="list"即可解决无法渲染的问题。

### Vant Weapp 版本

1.11.4

### 描述一下你遇到的问题。

日历组件使用了scroll-view微信组件实现，但该组件在Skyline渲染模式下需要一个特有的选项type才能渲染，否则即会报错。

经手动修复源码后即可解决，无需额外对skyline引擎做更多兼容。

大概也能猜到现在这个项目不愿意兼容skyline，但是这玩意修复成本挺低的。

### 重现步骤

在skyline渲染模式下引入该组件即可复现

**Comment by johnsonwong666** [comment]
可以提个pr过来看一下

**Comment by mxz2023** [comment]
这个怎么解决了，为什么关闭了

**Comment by rxitaishen** [comment]
@mxz2023 如原问题所说，修改@vant/weapp/calendar/calendar.wxml
文件下的scroll-view元素，如在第19行添加type="list"即可解决无法渲染的问题。
记得修改完重新进行一遍 工具-构建 npm
