### ISSUE TITLE
请问van-cell-group的title字体相关属性如何设置

### ISSUE THREAD

**Issue by WangShuoran** [youzan/vant-weapp#5721]
### 这个功能解决了什么问题？
我使用的下面组件：
https://youzan.github.io/vant-weapp/#/cell
比如下面图片显示的“单元格大小”字符font-size如何设置：
![image](https://github.com/youzan/vant-weapp/assets/43474491/fd355c36-5313-4371-ad52-bf12bf49b6f5)

我尝试了加入custom-class以下代码没有效果：
```
font-size: 40rpx;
```
也尝试加入title-width也无效。

### 你期望的 API 是什么样子的？

希望加入custom-class生效

**Comment by johnsonwong666** [comment]
单元格大小这几个字不属于van-cell组件的一部分 你是要改van-cell每一行左侧的字体大小吗？

**Comment by johnsonwong666** [comment]
如果你是想象修改 "单元格" 这几个字的大小 请使用title-class
