### ISSUE TITLE
icon能否实现旋转方向，如旋转90度，180度，270度

### ISSUE THREAD

**Issue by ycjnx** [youzan/vant-weapp#5725]
### 这个功能解决了什么问题？

icon能否实现旋转方向，如旋转90度，180度，270度，这样我们就可以有4倍的icon可以使用了，谢谢！

### 你期望的 API 是什么样子的？

<van-icon name="like" rotate="90"/>

**Comment by johnsonwong666** [comment]
传个    custom-style="transform: rotate(90deg)" 就可以实现了
