### ISSUE TITLE
placeholder-style没有改变placeholder样式，在输入和删除之后placeholder才改变成想要的样式

### ISSUE THREAD

**Issue by tyz-1** [youzan/vant-weapp#5727]
### 重现链接

https://developers.weixin.qq.com/s/YOtQtmmw74PQ

### Vant Weapp 版本

1.10.5

### 描述一下你遇到的问题。

van-field组件使用过程中修改placeholder样式没成功，在删除填写的内容之后才会展示想要的样式

### 重现步骤

1.使用placeholder-style来修改颜色（没有效果）
2.填写内容并删除刚填写的内容
3.可以看到颜色在这个时候才改变成功

### 设备/浏览器

微信开发者工具

**Comment by johnsonwong666** [comment]
简单看了一下你这个项目。我使用一个原生的input组件，然后传入placeholder-style属性，都不能正常生效，检查一下是否有什么东西覆盖或者配置问题。

**Comment by tyz-1** [comment]
> 简单看了一下你这个项目。我使用一个原生的input组件，然后传入placeholder-style属性，都不能正常生效，检查一下是否有什么东西覆盖或者配置问题。

我使用的是vant小程序原生的确实没问题

**Comment by johnsonwong666** [comment]
你这个代码片段 使用原生的 input 也没效果   <input type="text" placeholder-style="color: red" placeholder="请输入"/>
我新建一个项目van-field 和 原生input 正常生效。

**Comment by johnsonwong666** [comment]
https://developers.weixin.qq.com/s/Gsooium77sPT

感觉是skyline的问题 这个使用webview渲染的 没有问题

**Comment by H-Sven** [comment]
我遇到了同样的问题， 请问你解决了吗

**Comment by akinoccc** [comment]
> 我遇到了同样的问题， 请问你解决了吗

使用`--field-placeholder-text-color`这个变量就可以覆盖了
