### ISSUE TITLE
强烈建议增加一个form 组件

### ISSUE THREAD

**Issue by kong-xb** [youzan/vant-weapp#5728]
### 这个功能解决了什么问题？

能不能和vant4一样，增加form表单，里面有校验功能，现在的表单校验好麻烦，可以吗谢谢

### 你期望的 API 是什么样子的？

<van-form @submit="onSubmit">
  <van-cell-group inset>
    <van-field
      v-model="username"
      name="用户名"
      label="用户名"
      placeholder="用户名"
      :rules="[{ required: true, message: '请填写用户名' }]"
    />
    <van-field
      v-model="password"
      type="password"
      name="密码"
      label="密码"
      placeholder="密码"
      :rules="[{ required: true, message: '请填写密码' }]"
    />
  </van-cell-group>
  <div style="margin: 16px;">
    <van-button round block type="primary" native-type="submit">
      提交
    </van-button>
  </div>
</van-form>

**Comment by johnsonwong666** [comment]
计划在vant-weapp 2.x 版本中支持

**Comment by a531267910** [comment]
vant-weapp 2.x 版本，大概什么时候上线呀？可太需要了~

**Comment by linnngz** [comment]
搞快点啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊

**Comment by TopAlien** [comment]
复议
