### ISSUE TITLE
[Feature Request] 一些粘性布局中，吸顶的tabs，以及顶部导航栏等，在自定义导航栏时，吸顶会吸到最顶部以至于无法按按钮等

### ISSUE THREAD

**Issue by zgq2298673** [youzan/vant-weapp#5733]
### 这个功能解决了什么问题？

一些粘性布局中，吸顶的tabs，以及顶部导航栏等，在自定义导航栏时，吸顶会吸到最顶部以至于无法按按钮，而且右侧的小程序系统按钮与吸顶后的按钮是冲突的，这些吸顶按钮中顶部没有加slot，如果只是设置了吸顶距离，那么顶部空间的背景是空的，上滑时空背景就能看见后面的内容，所以建议在顶部加一个slot，这样可以放一些东西来填充区域，或者设置背景，还有，把下拉框放到tabs的内部左侧时，它和其他标题没法对齐，只能view设置padding对齐。还有search搜索框中的custom-class好像不起作用，我的版本是:"@vant/weapp": "^1.11.4"

### 你期望的 API 是什么样子的？

希望有所改进

**Comment by johnsonwong666** [comment]
1、自定义导航栏的时候,你可以使用一个view fixed在顶部 高度是你的offsetTop值  这样应该可以解决这么一个问题
2、第二个问题的描述不是很理解  tabs容器就是一个插槽  针对样式问题 可以调整css解决
3、van-search 的 custom-class 测试是生效的  没有生效呀发个复现代码片段过来看一下
