### ISSUE TITLE
vant-pop无法关闭

### ISSUE THREAD

**Issue by luoyan2019** [youzan/vant-weapp#5734]
### 重现链接

 <van-popup show="{{ showBotton }}" position="bottom" z-index="99999" custom-style="height: 608rpx;" close-on-click-overlay="true"
               bind:close="closeLoginPop">
  
    </van-popup>

    closeLoginPop() {

        this.setData({
            showBotton:false
        })
    },

### Vant Weapp 版本

1.11.3

### 描述一下你遇到的问题。

底部的弹窗无法被关闭

### 重现步骤

微信小程序在onshow中就将弹窗的展示参数置为true，弹窗出现再了页面，但设置了bind：close的事件设置参数为false后弹窗并未关闭，再页面上打印展示参数，确实再关闭事件触发后展示的参数置为了false

**Comment by johnsonwong666** [comment]
升级一下版本 1.11.4

**Comment by luoyan2019** [comment]
未解决
&nbsp;



***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年3月7日(星期四) 上午9:28
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [youzan/vant-weapp] vant-pop无法关闭 (Issue #5734)





 
升级一下版本 1.11.4

**Comment by johnsonwong666** [comment]
确认重新安装依赖后 重新构建npm。 依旧不行的话 发个小程序片段过来看一下
https://developers.weixin.qq.com/s/e2Ak0vmQ7KPY

**Comment by luoyan2019** [comment]
单个代码片段无法复现问题

**Comment by johnsonwong666** [comment]
> 单个代码片段无法复现问题

没有代码片段我这边也不能排查出什么问题呀。要么就检查一下自己的业务代码，同时debug一下。
