### ISSUE TITLE
picker.setIndexes多级联失效的情况下，如省市县，只有第一级省是准确的，第二三级联还是处于原始状态？

### ISSUE THREAD

**Issue by magnificent007** [youzan/vant-weapp#5735]
### 重现链接

![Snipaste_2024-03-07_16-46-28](https://github.com/youzan/vant-weapp/assets/98097886/ff2c0b9b-cac0-4062-9aa3-9759048f87e3)

### Vant Weapp 版本

1.11.2

### 描述一下你遇到的问题。

picker.setIndexes多级联设置索引的情况下，如省市县，只有第一级省是准确的，第二三级联还是处于原始状态？

### 重现步骤

点击区域选择， 弹窗地区选择弹窗picker，初始化picker索引setIndexes

```[tasklist]
### Tasks
```

**Comment by johnsonwong666** [comment]
检查一下 areaList是否正确。 如果正确依旧复现 请提供一个小程序代码片段过来看下。
<img width="743" alt="image" src="https://github.com/youzan/vant-weapp/assets/64689255/164423bb-8c5e-481e-8391-8629b95ae040">

**Comment by magnificent007** [comment]
已解决，是我自己的问题，数据用错方式了
