### ISSUE TITLE
[Feature Request] 关于cascader组件能否提供一个slot用于外部实现自定义的option-item

### ISSUE THREAD

**Issue by FullOfVigour** [youzan/vant-weapp#5736]
### 这个功能解决了什么问题？

在使用级联组件cascader的时候，目前只支持默认显示字段，无法自定义数据项

### 你期望的 API 是什么样子的？

期望能对option-item使用slot在外部自定义编辑
类似cell可以写label和value等

![image](https://github.com/youzan/vant-weapp/assets/25943199/454e720f-6feb-4527-b812-7e034f215b8b)
![image](https://github.com/youzan/vant-weapp/assets/25943199/3dec39f3-b64d-4fa3-9d0f-e97e8926f9b9)

**Comment by johnsonwong666** [comment]
暂不支持。第一slot传不了数据进去，第二需要准确的定义slot名称，这样使用上会比较复杂。

**Comment by FullOfVigour** [comment]
@johnsonwong666 大佬，微信有提供一个叫做虚拟节点的功能，这里是[微信文档](https://developers.weixin.qq.com/miniprogram/dev/framework/custom-component/generics.html#%E6%8A%BD%E8%B1%A1%E8%8A%82%E7%82%B9%E7%9A%84%E9%BB%98%E8%AE%A4%E7%BB%84%E4%BB%B6)
这是我写的一个样例：
![image](https://github.com/youzan/vant-weapp/assets/25943199/a3ab40ad-ebde-43b5-9e5b-3f4f6dbdd632)
![image](https://github.com/youzan/vant-weapp/assets/25943199/41102e0c-7980-4b71-9738-bbe47a456ef9)

**Comment by johnsonwong666** [comment]
可以提个pr过来看一下
