### ISSUE TITLE
使用输入框进行输入时，stepper的onChange监听到的值超出了max设置的值

### ISSUE THREAD

**Issue by Lick-liu** [youzan/vant-weapp#5737]
### 重现链接

WXML
<van-stepper integer value="{{quantity}}" min="{{min}}" bind:change="onQuantityChange"max="{{max}}" />
-------------------------------------------------------
JS
onQuantityChange(event) {
      const quantity = event.detail;
      console.log("onQuantityChange", quantity,this.data.quantity);
      this.triggerEvent("quantitychange", quantity);
    },
--------------------------------------------------------
控制台信息
![image](https://github.com/youzan/vant-weapp/assets/51771897/3500ca01-9692-4f2c-b945-9b5ab4975b45)

### Vant Weapp 版本

1.10.23

### 描述一下你遇到的问题。

设置了stepper的max最大值，使用输入框进行输入时，输入超出max的值，onChange监听到的值超出了max

### 重现步骤

设置了stepper的max最大值，使用输入框进行输入时
输入超出max的值，onChange监听到的值超出了max

**Comment by landluck** [comment]
`v1.11.5` 已发布
