### ISSUE TITLE
van-dropdown-menu 下拉菜单组件无法正常关闭

### ISSUE THREAD

**Issue by LiuJing1014** [youzan/vant-weapp#5739]
### 重现链接

https://developers.weixin.qq.com/s/XhEdnDmZ7tPY

### Vant Weapp 版本

1.11.3

### 描述一下你遇到的问题。

打开下拉弹窗后，不管是点击选项还是遮罩层，还是使用提供的toggle方法，都无法关闭菜单，遮罩层和下拉选项依然展示
![企业微信截图_17102347185553](https://github.com/youzan/vant-weapp/assets/57434878/7c1dbaf6-0ed8-4160-bcf2-480b600d9c32)
![企业微信截图_17102347281400](https://github.com/youzan/vant-weapp/assets/57434878/d6040ddf-6ef3-4549-bdef-ab3895a7ba35)

### 重现步骤

1、点击标题，打开下拉弹窗
2、再点击标题关闭弹窗，无法关闭

### 设备/浏览器

微信开发者工具 / 真机调试 都存在（调试基础库3.1.5）

**Comment by johnsonwong666** [comment]
升级版本 1.11.4
