### ISSUE TITLE
请问，为什么没有看到时间选择器组件呢

### ISSUE THREAD

**Issue by jzsjiale** [youzan/vant-weapp#574]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**你需要的功能是？**
请问，为什么没有看到时间选择器组件呢

**你期望 API 是什么样的？**
描述一下你期望的 API 形式

**Comment by chenjiahan** [comment]
正在开发中，参见 https://github.com/youzan/vant-weapp/projects/2
