### ISSUE TITLE
tab 标签页 Tab Slot 插槽功能希望能新增上

### ISSUE THREAD

**Issue by tangli1992** [youzan/vant-weapp#5742]
### 这个功能解决了什么问题？

![1710319114520](https://github.com/youzan/vant-weapp/assets/23614218/90f5abb8-f580-491c-a1df-ca66e15bc86b)
想实验自定义样式的tab标签页

### 你期望的 API 是什么样子的？

希望能保持和vant2  tab标签页 组件一致
![Uploading 1710319255732.jpg…]()

```[tasklist]
### Tasks
- [ ] 希望大大们帮帮我，谢谢大大们
```

**Comment by johnsonwong666** [comment]
计划在2.x版本支持
