### ISSUE TITLE
折叠面板 不能正常使用

### ISSUE THREAD

**Issue by Aipubor** [youzan/vant-weapp#5745]
### 重现链接

https://developers.weixin.qq.com/s/7FBrLPmH7YPu

### Vant Weapp 版本

1.11.4

### 描述一下你遇到的问题。

在uniapp中使用vue开发微信小程序 折叠面板不能进行正常的展开收起，点击没反应

### 重现步骤

1.点击折叠框
2.折叠框收起/展开

### 设备/浏览器

微信开发者工具

**Comment by johnsonwong666** [comment]
目前非微信官方微信开发者工具上产生的问题暂不处理，可能是编译的问题，可以将问题提到对应的官方去。
