### ISSUE TITLE
在微信小程序Skyline渲染模式下，引入外部样式无法覆盖vant-weapp组件的原有样式

### ISSUE THREAD

**Issue by cuibaoxu** [youzan/vant-weapp#5746]
### 重现链接

https://mmbiz.qpic.cn/sz_mmbiz_png/NscrPyiaCJPMzn4RUR4bvEg9YgyIdmgIoofs0UZ1ibOkgicJ15KwDWYrXZG5wjvxpnia2VNefibFk1F35hRu1UlTXsg/0?wx_fmt=png
https://mmbiz.qpic.cn/sz_mmbiz_png/NscrPyiaCJPMzn4RUR4bvEg9YgyIdmgIoPiaV7ricLdMEtM7BSObXN9Pdf4J49WOfgSJKnwFH7Hk6ZoBQxrx6vGicA/0?wx_fmt=png
https://mmbiz.qpic.cn/sz_mmbiz_png/NscrPyiaCJPMzn4RUR4bvEg9YgyIdmgIoq7JAwfZygAGNSCrOFAnLDJ1cQXC3Ef0X06lnMicMwqhj59VrGEicPlPQ/0?wx_fmt=png

### Vant Weapp 版本

1.11.4

### 描述一下你遇到的问题。

启动一个微信小程序，修改配置为Skyline渲染模式，引入vant-weapp组件后无法修改样式

### 重现步骤

1.启动微信小程序开发工具，新建小程序
2.修改渲染模式为Skyline模式
3.npm引入vant-weapp，微信小程序开发工具菜单栏：工具 ->构建npm -> 完成
4.页面引入组件，尝试覆盖样式

### 设备/浏览器

微信小程序开发工具

**Comment by johnsonwong666** [comment]
图片打不开。可以提供一个简单的复现代码片段过来看一下

**Comment by johnsonwong666** [comment]
由于较长时间没有提供复现代码片段，此issue暂时关闭，若能复现请附带复现代码片段排查。
https://developers.weixin.qq.com/s/NwHGjamA7bM4 
这个小程序代码片段修改一下，修改成你的情况然后重新分享一下过来看一下
