### ISSUE TITLE
Field: click-input 事件在windows微信上无效

### ISSUE THREAD

**Issue by knightYJ** [youzan/vant-weapp#5747]
### 重现链接

x

### Vant Weapp 版本

1.11.4

### 描述一下你遇到的问题。

Field 点击事件无效

### 重现步骤

      <van-field readonly bind:click-input="showPopup" maxlength="7" user-label-slot>
        <view slot="label" class="title">显示弹窗:</view>
      </van-field>

**Comment by johnsonwong666** [comment]
是在微信小程序开发者上测试的吗？ 测试了一下可以触发

**Comment by buaazyl** [comment]
Windows版小程序，不是开发工具，有不少用户反馈DatetimePicker也点不动，我回头找个Windows电脑测试一下再来反馈；
我的Mac版是正常的

**Comment by lihengdao** [comment]
为什么关闭，这个问题非常严重，要快点找到解决方法
