### ISSUE TITLE
[Bug Report] van-field 在type='nickName'时，无法监听bindnicknamereview 事件

### ISSUE THREAD

**Issue by nanhupatar** [youzan/vant-weapp#5748]
### 重现链接

https://youzan.github.io/vant-weapp/#/field 

### Vant Weapp 版本

1.11.4

### 描述一下你遇到的问题。

https://developers.weixin.qq.com/miniprogram/dev/component/input.html

### 重现步骤

并没有和微信小程序文档保持一致，无法监听type='nickname' 时的bindnicknamereview事件

### 设备/浏览器

小程序

**Comment by nanhupatar** [comment]
有时间看看这个问题

**Comment by landluck** [comment]
`v1.11.5` 已发布
