### ISSUE TITLE
[Bug Report] checkbox-group下的checkbox的change事件无法触发

### ISSUE THREAD

**Issue by yik7707** [youzan/vant-weapp#5757]
### 重现链接

https://developers.weixin.qq.com/s/ySrrCcmU74QU

### Vant Weapp 版本

1.11.4

### 描述一下你遇到的问题。

van-checkbox-group下的van-checkbox，绑定的change事件无法触发，这样一来循环后判断单个点击了哪个checkbox，就能很方便明确并作出一些操作，不然需要在checkbox绑定原生事件去判断，这样增加工作量，还得判断是否禁用了当前选中的checkbox

### 重现步骤

无

**Comment by johnsonwong666** [comment]
![image](https://github.com/youzan/vant-weapp/assets/64689255/a9d75b4f-f4eb-4e6e-b8a2-9048127f79e5)

代码中是 如果是使用checkbox-group包裹的话  不会触发check-box的onchange事件
