### ISSUE TITLE
[Bug Report] cascader组件的value属性在重置为""空字符串时，组件显示异常

### ISSUE THREAD

**Issue by zzxqd** [youzan/vant-weapp#5759]
### 重现链接

https://developers.weixin.qq.com/s/IIQT4jm77rQm

### Vant Weapp 版本

1.11.4

### 描述一下你遇到的问题。

重置value后cascader不展示任何选项。

### 重现步骤

随便一个多层级的options，选择一个最末一级到节点，之后将value重新赋值为""数值

**Comment by zzxqd** [comment]
看了下源码，在watch value -> this.updateValue -> this.updateTabs 中没有重置activeTab导致的，需要的话我可以发个pr

**Comment by nikolausliu** [comment]
> 看了下源码，在watch value -> this.updateValue -> this.updateTabs 中没有重置activeTab导致的，需要的话我可以发个pr

看了下这个pr的改动还没有发版，我也遇到了这个bug，说下我的处理方式，其它开发者遇到这个问题如果不升版本可以这样修复这个bug:

```wxml
<van-cascader value="{{value}}" id="cascader" />
```

```js
// 重置value后，选中cascader组件，设置activeTab为0
this.selectComponent('#cascader').setData({
  activeTab: 0,
})
```

**Comment by zzxqd** [comment]
> > 看了下源码，在watch value -> this.updateValue -> this.updateTabs 中没有重置activeTab导致的，需要的话我可以发个pr
> 
> 看了下这个pr的改动还没有发版，我也遇到了这个bug，说下我的处理方式，其它开发者遇到这个问题如果不升版本可以这样修复这个bug:
> 
> ```
> <van-cascader value="{{value}}" id="cascader" />
> ```
> 
> ```js
> // 重置value后，选中cascader组件，设置activeTab为0
> this.selectComponent('#cascader').setData({
>   activeTab: 0,
> })
> ```

如果只有一个人在维护项目，直接改生成的小程序npm包中的源码也可以

**Comment by landluck** [comment]
v1.11.6 已修复
