### ISSUE TITLE
[Feature Request] van-switch内切换显示不同的文字

### ISSUE THREAD

**Issue by kiqupo** [youzan/vant-weapp#5761]
### 这个功能解决了什么问题？

van-switch可以实现按钮内带文字，且切换会带不同的文字吗？
在众多使用场景会使用到。如点餐显示外卖or自取

### 你期望的 API 是什么样子的？

<van-switch active-text="外卖" inactive-text="自取" />
```[tasklist]
### Tasks
```

**Comment by johnsonwong666** [comment]
switch组件主要体现的是true和false的关系，暂不支持
