### ISSUE TITLE
vant-filed自动填充删除元素的高度

### ISSUE THREAD

**Issue by luoyan2019** [youzan/vant-weapp#5762]
### 重现链接

无

### Vant Weapp 版本

1.11.0

### 描述一下你遇到的问题。

使用wx-for展示多个输入框，当vant-filed的类型为textarea且设置了autosize时，随机在一个输入框输入点数据。然后删除。vant-filed的高度回自动填充删除元素的高度，不会保持原有的高度

### 重现步骤

wx-for展示多个输入框，填写内容后，删除其他的输入框

### 设备/浏览器

安卓

**Comment by johnsonwong666** [comment]
autosize 是设置内容自适应的，要保持高度，autosize不应该设置呀

**Comment by luoyan2019** [comment]
不好意思，忘记看回复了。我的需求就是让他高度根据内容自适应，所以设置了autosize属性。但是设置了之后。删除了列表的单个或多个项目后，它的高度变成了删除元素的高度。但是实际上列表的其他元素，不应该影响它的高度的

**Comment by luoyan2019** [comment]
不好意思，忘记看回复了。我的需求就是让他高度根据内容自适应，所以设置了autosize属性。但是设置了之后。删除了列表的单个或多个项目后，它的高度变成了删除元素的高度。但是实际上列表的其他元素，不应该影响它的高度的
&nbsp;



***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年4月12日(星期五) 中午11:48
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [youzan/vant-weapp] vant-filed自动填充删除元素的高度 (Issue #5762)














 
autosize 是设置内容自适应的，要保持高度，autosize不应该设置呀
