### ISSUE TITLE
[Bug Report] 在基础调试库3.4.1版本下使用一些组件会报错Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by xiaozhang959** [youzan/vant-weapp#5764]
### 重现链接

https://youzan.github.io/vant-weapp/

### Vant Weapp 版本

1.11.4

### 描述一下你遇到的问题。

报错：“Cannot read property '0' of undefined”

### 重现步骤

1. 使用微信小程序开发调试基础库3.4.1版本
2. -webview渲染模式，
3. 导入 van-button 或者(van-goods-action和van-goods-action-icon)或者(van-goods-action和van-goods-action-button)，action三个组件一起导入调用的时候也会，只用action单个组件 的时候就不会报错
4. 其他组件未测试，
5. 但是经过测试，降低基础调试库就没有触发这个问题。

### 设备/浏览器

windows 10

**Comment by xiaozhang959** [comment]
> 降低基础调试库就没有触发这个问题
当降低到3.4.0版本时，使用button按钮组件不会报错，action组件会报错

当降低到3.3.5版本时，都可以正常使用

**Comment by xiaozhang959** [comment]
> 降低基础调试库就没有触发这个问题
当降低到3.4.0版本时，使用button按钮组件不会报错，action组件会报错

当降低到3.3.5版本时，都可以正常使用

**Comment by johnsonwong666** [comment]
https://developers.weixin.qq.com/s/ORrhjomZ7MQn

可以修改一下提供一下复现代码 然后分享回来

**Comment by sunwenxu1997** [comment]
所以最后的解决方案是什么
