### ISSUE TITLE
官网挂了

### ISSUE THREAD

**Issue by 17770137331** [youzan/vant-weapp#5769]
### 重现链接

https://vant-contrib.gitee.io/vant/#/zh-CN/contribution

### Vant Weapp 版本

最新

### 描述一下你遇到的问题。

官网挂了https://vant-contrib.gitee.io/vant/#/zh-CN/contribution

### 重现步骤

https://vant-contrib.gitee.io/vant/#/zh-CN/contribution

### 设备/浏览器

chrome

**Comment by Listen-to-poetry-in-the-wind** [comment]
+1

**Comment by Listen-to-poetry-in-the-wind** [comment]
好像是换了地址 https://vant-ui.github.io/vant/#/zh-CN

**Comment by XinyeYang** [comment]
小程序文档这边还是404，不管用

**Comment by czpalis** [comment]
+1

**Comment by landluck** [comment]
那个文档挂了？gitee： https://vant-contrib.gitee.io/vant-weapp/#/home  github：https://youzan.github.io/vant-weapp/#/home 都能正常打开

**Comment by jiaruiyan** [comment]
![image](https://github.com/youzan/vant-weapp/assets/66373324/6d4ffe1e-7952-4a61-a711-ec48b7908845)

**Comment by jiaruiyan** [comment]
文档切换地址了，但是感觉文档中对应旧地址还没有同步维护
![image](https://github.com/youzan/vant-weapp/assets/66373324/c80f90b1-7d18-45ac-b8be-c3fced577cd0)

**Comment by jiaruiyan** [comment]
文档地址切换了，但是文档中的链接地址好像没有及时的对应更新
![image](https://github.com/youzan/vant-weapp/assets/66373324/a661ea76-3f65-4d71-a978-1a916a89c174)

**Comment by JaceSetry** [comment]
https://vant-ui.github.io/vant-weapp/#/home    先用GitHub的凑合吧

**Comment by singleseeker** [comment]
右侧预览效果失效。

**Comment by landluck** [comment]
https://github.com/youzan/vant-weapp/issues/5775
