### ISSUE TITLE
van-search设置clear-trigger=“always”首次渲染删除按钮不显示

### ISSUE THREAD

**Issue by zhudasen** [youzan/vant-weapp#5779]
### 重现链接

![Uploading image.png…]()

created()，未调用this.setShowClear()，修复代码created()中添加 utils_1.nextTick(()=>this.setShowClear());

### Vant Weapp 版本

1.11.5

### 描述一下你遇到的问题。

van-search设置clear-trigger=“always”，为value绑定初始值，首次渲染删除按钮不显示

### 重现步骤

van-search设置clear-trigger=“always”，为value绑定初始值，首次渲染删除按钮不显示

**Comment by landluck** [comment]
`v1.11.6` 已修复
