### ISSUE TITLE
[Bug Report] Calendar组件，使用footer slot会导致show-confirm的确认按钮不显示。或者说如何在footer插槽中实现确认按钮功能？

### ISSUE THREAD

**Issue by dsgvsn** [youzan/vant-weapp#5780]
### 重现链接

`<van-calendar show="{{ true }}" type="range" allow-same-day bind:close="onClose" bind:confirm="onConfirm">
  <view slot="footer">这是footer插槽</view>
</van-calendar>`

### Vant Weapp 版本

1.11.5

### 描述一下你遇到的问题。

日历组件的footer插槽导致默认的确认按钮不显示。

### 重现步骤

![undefined](http://p1.meituan.net/csc/bb954ebcc0d2794ea5d2241cfd21f39356553.png)

**Comment by landluck** [comment]
使用 footer slot 后按钮需要自己实现。footer slot 和 冲突
