### ISSUE TITLE
[Bug Report] <van-cell />组件使用'is-link'属性时出现bug，内容无法显示且有网络渲染层错误

### ISSUE THREAD

**Issue by pra1sejung** [youzan/vant-weapp#5786]
### 重现链接

  <van-cell-group inset>
    <van-cell title="单元格" is-link />
    <van-cell title="单元格" is-link />
    <van-cell title="单元格" is-link />
  </van-cell-group>

### Vant Weapp 版本

1.11.5

### 描述一下你遇到的问题。

<van-cell />组件使用'is-link'属性时出现bug，内容无法显示且有网络渲染层错误，如果我删除'is-link'将不再报错，但是调用内容依然无法正确显示。
值得注意的是，我有使用全局网络代理。
报错如下：
[渲染层网络层错误] Failed to load font http://at.alicdn.com/t/c/font_2553510_kfwma2yq1rs.woff2?t=1694918397022
net::ERR_CACHE_MISS 
(env: Windows,mp,1.06.2402021; lib: 3.4.1)

### 重现步骤

1. 保存+重新编译
  <van-cell-group inset>
    <van-cell title="单元格" is-link />
    <van-cell title="单元格" is-link />
    <van-cell title="单元格" is-link />
  </van-cell-group>
  2. 无内容显示并报错
  [渲染层网络层错误] Failed to load font http://at.alicdn.com/t/c/font_2553510_kfwma2yq1rs.woff2?t=1694918397022
net::ERR_CACHE_MISS 
(env: Windows,mp,1.06.2402021; lib: 3.4.1)

### 设备/浏览器

微信开发者工具

**Comment by landluck** [comment]
看报错是 icon-font 图标库无法下载，检查一下网络是否能访问 http://at.alicdn.com

**Comment by pra1sejung** [comment]
如图所示，打不开，无论我是否使用网络代理都是这个界面，但是用idm和fdm是可以正常下载链接上的文件的




礼赞丶
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "youzan/vant-weapp"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年5月13日(星期一) 下午5:52
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [youzan/vant-weapp] [Bug Report] <van-cell /&gt;组件使用'is-link'属性时出现bug，内容无法显示且有网络渲染层错误 (Issue #5786)





 
看报错是 icon-font 图标库无法下载，检查一下网络是否能访问 http://at.alicdn.com
