### ISSUE TITLE
[Bug Report] Icon在Skyline模式下无法显示图片

### ISSUE THREAD

**Issue by mxz2023** [youzan/vant-weapp#5788]
### 重现链接

<van-icon name="success" />

### Vant Weapp 版本

1.11.5

### 描述一下你遇到的问题。

Icon在Skyline模式下无法显示图片，但在使用webview模式可以正常显示
![image](https://github.com/youzan/vant-weapp/assets/141282755/7e8d93d0-885c-474f-8ce0-8e25b9e22655)

### 重现步骤

<van-icon name="success" />

**Comment by landluck** [comment]
暂未适配 skyline。
