### ISSUE TITLE
[Bug Report]van-action-sheet 自定义内容嵌套 field  ios真机点击textarea除placeholder提示位置其他区域点击无法聚焦

### ISSUE THREAD

**Issue by keke599** [youzan/vant-weapp#5789]
### 重现链接

https://developers.weixin.qq.com/s/nbtTi6mP7DR9

### Vant Weapp 版本

1.11.5

### 描述一下你遇到的问题。

![image](https://github.com/youzan/vant-weapp/assets/45028585/5ea7432d-4150-41a8-bd7b-b2c3bf5bc02c)
面板自定义内容嵌入textarea 不点击请输入（焦点初始位置） 无法聚焦

### 设备/浏览器
iphone13pro
ios真机应该都不行 安卓正常

**Comment by keke599** [comment]
给 textarea添加了个一个高度 去掉autosize="{{ { minHeight: 150 } }}" 就可以 这是什么原因呢

**Comment by landluck** [comment]
在开启 autosize 的模式下，虽然 textarea 看着是被撑开了，但微信会根据输入内容计算高度，实际的可点击区域只有 20px。点击无响应实际是可点击区域太小。autosize 暂时不建议设置太大的值。或者手动监听 view 点后设置 focus 为 true。
