### ISSUE TITLE
GoodsAction和SubmitBar有计划么？

### ISSUE THREAD

**Issue by tielei60** [youzan/vant-weapp#579]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**你需要的功能是？**
GoodsAction 商品页行动点和SubmitBar 提交订单栏
有计划要做么？

**你期望 API 是什么样的？**
描述一下你期望的 API 形式

**Comment by chenjiahan** [comment]
参见 https://github.com/youzan/vant-weapp/issues/551
