### ISSUE TITLE
Dialog.confirm “取消”按钮

### ISSUE THREAD

**Issue by nanhai-13** [youzan/vant-weapp#5790]
### 重现链接

const beforeClose = (action) =>
  new Promise((resolve) => {
    setTimeout(() => {
      if (action === 'confirm') {
        resolve(true);
      } else {
        // 点击“取消”按钮；无法关闭弹窗 
        resolve(false);
      }
    }, 1000);
  });

Dialog.confirm({
  title: '标题',
  message: '弹窗内容',
  beforeClose,
});

### Vant Weapp 版本

1.11.5 最新版本

### 描述一下你遇到的问题。

https://vant-ui.github.io/vant-weapp/#/dialog
异步关闭；官方页面实例操作；点击“取消”按钮；可以关闭弹窗。但chrome浏览器的log有错误信息！

### 重现步骤

1：点击“取消”按钮；
2：“取消”按钮“ 文字变成 loding图标不停地转圈；但却无法关闭弹窗！

### 设备/浏览器

Android的微信小程序

**Comment by landluck** [comment]
![image](https://github.com/youzan/vant-weapp/assets/27060081/981180f5-b72f-4a0d-a2c0-e483f38d543a)
返回 false 自然无法关闭弹窗，要关闭弹窗返回 true
