### ISSUE TITLE
van-datetime-picker 在小程序中无法滑动年月日

### ISSUE THREAD

**Issue by weir2010** [youzan/vant-weapp#5791]
### 重现链接

`<van-action-sheet show="{{ showBirthday }}">
    <van-datetime-picker
  type="date"
  value="{{ currentDate }}"
  bind:input="onInput"
  min-date="{{ minDate }}"
  formatter="{{ formatter }}"
/>
</van-action-sheet>`

` <van-popup
  show="{{ showBirthday }}"
  round
  position="bottom"
  custom-style="height: 50%"
  bind:close="onClose">
    <van-datetime-picker
  type="date"
  value="{{ currentDate }}"
  bind:input="onInput"
  min-date="{{ minDate }}"
  formatter="{{ formatter }}"
/>
</van-popup>`

这两种方式都不行。

<img width="379" alt="image" src="https://github.com/youzan/vant-weapp/assets/404015/82422f2f-f60b-41e8-9d35-b5a3fcac3e98">

### Vant Weapp 版本

1.11.5

### 描述一下你遇到的问题。

年月日 都不能滑动

### 重现步骤

年月日 都不能滑动

**Comment by landluck** [comment]
无法复现，提供一下小程序代码片段。[代码片段](https://developers.weixin.qq.com/miniprogram/dev/devtools/minicode.html)

**Comment by weir2010** [comment]
我在观察下 ，目前微信开发者工具上面是需要点击可以翻动，手机端我后面测试在汇报
