### ISSUE TITLE
[Feature Request] Uploader组件是否能支持到最高100个

### ISSUE THREAD

**Issue by i0ducn** [youzan/vant-weapp#5793]
### 这个功能解决了什么问题？

微信小程序wx.chooseMessageFile(Object object)接口提供了最多100个选择，能否优化一下更改成此接口[https://developers.weixin.qq.com/miniprogram/dev/api/media/image/wx.chooseMessageFile.html](url)

### 你期望的 API 是什么样子的？

<van-uploader max-count=100 />
```[tasklist]
### Tasks
```

**Comment by i0ducn** [comment]
或者可以提升到20，”基础库2.25.0前，最多可支持9个文件，2.25.0及以后最多可支持20个文件“，目前接口已经支持最多20

**Comment by TallNutAlt** [comment]
![image](https://github.com/youzan/vant-weapp/assets/109561878/59b9866e-0b9e-4178-8fc6-e37896a40252)

**Comment by TallNutAlt** [comment]
我看源码上有这个api

**Comment by TallNutAlt** [comment]
参考文档accept

**Comment by i0ducn** [comment]
> 参考文档accept
好的，好像在官方文档里没看到，不过还是推荐把默认值9改成20，会比较方便

**Comment by TallNutAlt** [comment]
> > 参考文档accept
> > 好的，好像在官方文档里没看到，不过还是推荐把默认值9改成20，会比较方便

https://youzan.github.io/vant-weapp/#/uploader#accept-de-he-fa-zhi

**Comment by TallNutAlt** [comment]
accept 传的不是image media video  使用的都是chooseMessageFile
