### ISSUE TITLE
"usingComponents": {   "van-submit-bar": "@vant/weapp/submit-bar/index" } 这个引用使用组件不显示

### ISSUE THREAD

**Issue by shizhongyu** [youzan/vant-weapp#5795]
### 重现链接

必现

### Vant Weapp 版本

1.11.4

### 描述一下你遇到的问题。

组件引用不显示

### 重现步骤

必现

**Comment by TallNutAlt** [comment]
我试了1.11.6是显示的

**Comment by shizhongyu** [comment]
那这个怎么定位问题呢？

**Comment by shizhongyu** [comment]
别的组件都可以，就这个不可以。

**Comment by TallNutAlt** [comment]
> 别的组件都可以，就这个不可以。

更新到11.6试下 或者提供一下可复现的代码片段

**Comment by shizhongyu** [comment]
<img width="342" alt="image" src="https://github.com/youzan/vant-weapp/assets/13025541/c34d6f30-28ac-4e4d-9ab3-c6ee00faacde">
<img width="590" alt="image" src="https://github.com/youzan/vant-weapp/assets/13025541/31a3d1b5-1bfc-45a7-943c-4e1a84642ec3">
<img width="400" alt="image" src="https://github.com/youzan/vant-weapp/assets/13025541/de811033-ce95-4c80-91ed-efca0d78dd2c">

**Comment by shizhongyu** [comment]
@TallNutAlt 辛苦看下

**Comment by TallNutAlt** [comment]
> @TallNutAlt 辛苦看下

[https://developers.weixin.qq.com/s/NwHGjamA7bM4](https://developers.weixin.qq.com/s/NwHGjamA7bM4%C2%A0%E8%BF%99%E4%B8%AA%E5%B0%8F%E7%A8%8B%E5%BA%8F%E4%BB%A3%E7%A0%81%E7%89%87%E6%AE%B5%E4%BF%AE%E6%94%B9%E4%B8%80%E4%B8%8B%EF%BC%8C%E4%BF%AE%E6%94%B9%E6%88%90%E4%BD%A0%E7%9A%84%E6%83%85%E5%86%B5%E7%84%B6%E5%90%8E%E9%87%8D%E6%96%B0%E5%88%86%E4%BA%AB%E4%B8%80%E4%B8%8B%E8%BF%87%E6%9D%A5%E7%9C%8B%E4%B8%80%E4%B8%8B%E2%80%A8)

**Comment by TallNutAlt** [comment]
> @TallNutAlt 辛苦看下

@shizhongyu https://developers.weixin.qq.com/s/NwHGjamA7bM4 
使用这个提供一下片段

**Comment by shizhongyu** [comment]
![image](https://github.com/youzan/vant-weapp/assets/13025541/affb5547-b1dd-40ea-82d4-d349928363cb)
怎么给你？

**Comment by TallNutAlt** [comment]
> ![image](https://private-user-images.githubusercontent.com/13025541/334305771-affb5547-b1dd-40ea-82d4-d349928363cb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4ODA4NjMsIm5iZiI6MTcxNjg4MDU2MywicGF0aCI6Ii8xMzAyNTU0MS8zMzQzMDU3NzEtYWZmYjU1NDctYjFkZC00MGVhLTgyZDQtZDM0OTkyODM2M2NiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI4VDA3MTYwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUzNDVjYTIzZTgwYmU4NWE1ZWYxYmIyYTRiNzM3NzQwMTMyYjQyNDA4ZjhjYzFmMTJmYzJiMWQwNWJmM2U4YWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6HnZJUV3Rzrdwlp5CbZgRQ9ktvnqhfNzndhMNdCzZmE) 怎么给你？

右上角有分享

**Comment by shizhongyu** [comment]
https://developers.weixin.qq.com/s/iMEtfwmP72RS

**Comment by TallNutAlt** [comment]
> https://developers.weixin.qq.com/s/iMEtfwmP72RS

![image](https://github.com/youzan/vant-weapp/assets/109561878/2f844af6-bc1e-4d6d-a853-99a0121c3fea)

wei未在json中引入

**Comment by shizhongyu** [comment]
我都是在app.json引入的。
![Uploading image.png…]()
不过现在可以了

**Comment by shizhongyu** [comment]
![image](https://github.com/youzan/vant-weapp/assets/13025541/ff517d4a-113d-442c-945c-7b2f5e6c326a)

**Comment by TallNutAlt** [comment]
好的

**Comment by shizhongyu** [comment]
我知道为啥了，底部的tabbar挡住了。

**Comment by shizhongyu** [comment]
已解决
