### ISSUE TITLE
Dialog自定义样式 当弹窗内容过多时滑动标题按钮不固定

### ISSUE THREAD

**Issue by yisirman** [youzan/vant-weapp#5797]
### 重现链接

![image](https://github.com/youzan/vant-weapp/assets/15642586/884d62c0-6944-41e1-9928-5bb4739dd16f)
如上图所示 弹窗内容比较多可以上下滑动 标题和按钮随着内容上下滑动位置移动了

### Vant Weapp 版本

1.11.4

### 描述一下你遇到的问题。

如上所示 期望标题和按钮固定 中间内容可以上下滑动 类似以下的效果
<img width="330" alt="image" src="https://github.com/youzan/vant-weapp/assets/15642586/1ec89d8e-faa1-4427-ae86-c2aec695a542">

### 重现步骤

如上

**Comment by TallNutAlt** [comment]
给滑动板块一个固定高度试试

**Comment by TallNutAlt** [comment]
使用
`<view>
	<view>title</view>
	<scroll-view style="height: 300px;">
	可滑动
	</scroll-view>
	<view>底部</view>
</view>`

**Comment by yisirman** [comment]
> 给滑动板块一个固定高度试试

不生效

**Comment by TallNutAlt** [comment]
> > 给滑动板块一个固定高度试试
> 
> 不生效

能提供一个代码片段吗

**Comment by landluck** [comment]
没复现，可以提供一下小程序代码片段
