### ISSUE TITLE
van-popup 偶现在安卓机上不弹出

### ISSUE THREAD

**Issue by secret821** [youzan/vant-weapp#5799]
### 重现链接

{
  "navigationBarBackgroundColor": "#FEC187",
  "usingComponents": {
    "van-picker": "../../../../components/vant/picker/index",
    "van-popup": "../../../../components/vant/popup/index",
    "area-modal": "../../../../components/area-modal/area-modal",
    "rule-popup": "../components/rule-popup/rule-popup"
  }
}

<area-modal areaModalVisible="{{areaModalVisible}}" areaType="provinceCityArea" bind:handleCloseAreaModal="handleToggleAreaModal" bind:confirmPicker="handelConfirmPicker" />

<van-popup show="{{ areaModalVisible }}" position="bottom" round z-index="999" bind:close="cancelModal">
    <van-picker show-toolbar="{{ true }}" columns="{{ columns }}" bind:confirm="handleConfirm" bind:cancel="cancelModal" bind:change="provinceChange" />
</van-popup>

### Vant Weapp 版本

0.x

### 描述一下你遇到的问题。

弹窗点击弹不出来

### 重现步骤

弹窗无法显示

### 设备/浏览器

用户在vivoX80这个机型发现的
```[tasklist]
### Tasks
```

**Comment by secret821** [comment]
<van-popup show="{{ areaModalVisible }}" position="bottom" round z-index="999" bind:close="cancelModal">
    <van-picker show-toolbar="{{ true }}" columns="{{ columns }}" bind:confirm="handleConfirm" bind:cancel="cancelModal" bind:change="provinceChange" />
</van-popup>

**Comment by landluck** [comment]
提供的信息无法排查，需要提供可复现的小程序代码片段和设备详细信息
