### ISSUE TITLE
vna-field组件获取微信昵称后chang事件没有生效（开发工具不行，ios真机可以）

### ISSUE THREAD

**Issue by huang160** [youzan/vant-weapp#5802]
### 重现链接

1. wxml代码-包裹在popup组件里面
```
<van-field label="昵称" title-width="fit-content" value="{{ userInfo.nickName }}" placeholder="请输入用户名" border="{{ true }}" bind:change="onInputChange" type="nickname" focus="{{ isFocus }}" bind:nicknamereview="onNicknamereview" use-slot-button>
<view slot='button' data-id="nickName" class="useWxNc" bind:tap="onChange">使用微信昵称</view>
</van-field>
```

3. js代码
data: {
		showPopup: false,
		isFocus: false,
		userInfo: {
			avatarUrl: [],
			nickName: ''
		},
	},

	// 获取头像校验成功后触发
	onNicknamereview(pass, timeout) {
		//console.log(pass, timeout)
		console.log(this.data)
	},

	// 获取昵称
	onInputChange(e) {
		//console.log(e)
		this.setData({
		  ["userInfo.nickName"]: e.detail,
		})
		console.log(this.data)
	},

	// 获取用户输入的值
	onChange(event) {
		// event.detail 为当前输入的值
	//	console.log(event)
		const id = event.target.dataset.id
		if (id && id === 'nickName') {
			this.setData({
				isFocus: true
			})
		} 
	},

### Vant Weapp 版本

1.11.6

### 描述一下你遇到的问题。

vna-field组件获取微信昵称后chang事件没有生效（开发工具不行，ios真机可以，安卓机未测试），本人通过原生input chang事件去获取是可以取到值的

### 重现步骤

1.点击昵称输入框，获取昵称后
2.chang事件打印没有获取到昵称值

### 设备/浏览器

微信开发工具（版本：1.06.2404301 win32-x64）

**Comment by landluck** [comment]
要获取昵称用 nicknamereview 事件，change 并不支持获取该值。change 的底层是 input 事件，微信官方并不支持这样使用
