### ISSUE TITLE
[Bug Report] Cascader 标题名称过长使得标题栏内容超出屏幕，此时标题栏无法滚动

### ISSUE THREAD

**Issue by dekunliu** [youzan/vant-weapp#5803]
### 重现链接

https://developers.weixin.qq.com/s/R5rtEymi7WRe

### Vant Weapp 版本

1.11.6

### 描述一下你遇到的问题。

级联选择控件数据层级小于等5时，标题名称过长使得标题栏内容超出屏幕，此时标题栏无法滚动

### 重现步骤

1、一次选择代码片段中的长标题；
2、尝试滑动标题栏。

**Comment by landluck** [comment]
[v1.11.7](https://github.com/youzan/vant-weapp/compare/v1.11.6...v1.11.7) 已支持  ellipsis 属性
