### ISSUE TITLE
[Bug Report] tabbar的info属性为0也是显示状态

### ISSUE THREAD

**Issue by yik7707** [youzan/vant-weapp#5804]
### 重现链接

https://developers.weixin.qq.com/s/fzkGxzmV78Rp

### Vant Weapp 版本

1.11.6

### 描述一下你遇到的问题。

tabbar的info属性为0也是显示状态，如何隐藏似乎使用dot为false也没法隐藏红标信息，不符合正常逻辑
![image](https://github.com/youzan/vant-weapp/assets/74293458/6325adcd-07d4-487c-8531-37462936e626)

### 重现步骤

无

### 设备/浏览器

微信开发者

**Comment by landluck** [comment]
0 也是合法的数字，如果想在为 0 的时候不显示，可以这么写 info = "{{ count || null }}"。count 为具体数字
