### ISSUE TITLE
[Bug Report] van-tabs再结合 swiper 里面放视频 在 ios 会导致视频全屏的时候 tabs 在视频上面  安卓没问题

### ISSUE THREAD

**Issue by kingdsa** [youzan/vant-weapp#5805]
### 重现链接

```
<van-tabs ellipsis="{{false}}" active="{{ active }}" bind:change="onChange">
  <van-tab title="标签 1"></van-tab>
  <van-tab title="标签 2"></van-tab>
  <van-tab title="标签 3"></van-tab>
  <van-tab title="标签 4"></van-tab>
  <view style="height: 450rpx;">
    <swiper style="height: 100%;" indicator-dots="{{true}}" autoplay="{{false}}" duration="{{500}}">
      <swiper-item>
        <video src="https://hwkjoss-kfx-biz-plat.oss-cn-hangzhou.aliyuncs.com/3423609089838644224.mp4" class="w-full" object-fit="fill" />
      </swiper-item>
    </swiper>
  </view>
</van-tabs>
```

### Vant Weapp 版本

^1.11.4

### 描述一下你遇到的问题。

van-tabs在结合 swiper 里面放视频 在 ios 会导致视频全屏的时候 tabs 在视频上面（ 并且下方的进度条 暂停按钮都看不到了 就是因为上面的 tabs 顶下去了）  安卓没问题

![iosbug](https://github.com/youzan/vant-weapp/assets/68138383/3b021dff-2f70-4931-9554-b1c8066e81ff)
![zc](https://github.com/youzan/vant-weapp/assets/68138383/668c69f3-78f6-4c8a-93b8-57d170ab8162)
第一张图是 ios 第二张是安卓

### 重现步骤

上诉视频代码写进去就会复现

### 设备/浏览器

ios 机型 比如 iPhone13

**Comment by kingdsa** [comment]
<van-tabs ellipsis="{{false}}" active="{{ active }}" active="{{ active }}" bind:change="onChange">
  <van-tab title="标签 1"></van-tab>
  <van-tab title="标签 2"></van-tab>
  <van-tab title="标签 3"></van-tab>
  <van-tab title="标签 4"></van-tab>
  <view style="height: 450rpx;">
    <swiper style="height: 100%;" indicator-dots="{{true}}" autoplay="{{false}}" duration="{{500}}">
      <swiper-item>
        <video src="https://hwkjoss-kfx-biz-plat.oss-cn-hangzhou.aliyuncs.com/3423609089838644224.mp4" class="w-full" object-fit="fill" />
      </swiper-item>
    </swiper>
  </view>
</van-tabs>

**Comment by kingdsa** [comment]
问题解决了 把代码放在 van-tabs 的外面就行了

**Comment by landluck** [comment]
没看懂具体的问题，下面这个写法本身是有问题的，内容应该放到 van-tab 里面，而不是 van-tabs 里面作为一个节点
![image](https://github.com/youzan/vant-weapp/assets/27060081/84dcc0e0-9b4a-4cdb-8474-d8885f69deb9)
