### ISSUE TITLE
[Bug Report] uploader组件预览文件bug

### ISSUE THREAD

**Issue by masicheng** [youzan/vant-weapp#5807]
### 重现链接

![image](https://github.com/youzan/vant-weapp/assets/17764401/19fbfa9b-a207-4ec7-95a1-28afd0048e4d)

### Vant Weapp 版本

1.10.25

### 描述一下你遇到的问题。

预览文件时一般会自己重写click-preview方法，因为我们需要先调用download再openDocument。这样点击预览时会调用两次openDocument方法，调用两次会导致部分安卓手机无法正常打开文件

### 重现步骤

1. 重写click-preview 调用wx.openDocument.
2. 使用安卓手机打开pdf文件

### 设备/浏览器

设备：荣耀30s 系统：鸿蒙3.0

**Comment by landluck** [comment]
[v1.11.7](https://github.com/youzan/vant-weapp/compare/v1.11.6...v1.11.7) 已修复

**Comment by bf109f** [comment]
<img width="1302" height="317" alt="Image" src="https://github.com/user-attachments/assets/075c73a1-079f-4a2b-8eb4-105cbce7bdb9" />是加了个两行代码吗？我打断点发现先执行的是onPreviewFile，然后再执行的onClickPreview，导致华为nova13pro调用报错openDocument:fail:document viewer alreadystarting
