### ISSUE TITLE
[Bug Report] van-field type="textarea" readonly  & disabled 在ios设备上失效

### ISSUE THREAD

**Issue by luchun27** [youzan/vant-weapp#5808]
### 重现链接

 data: {
      params:{
        contentDescription:"世纪东方猎杀对决开了房金卡拉萨的付了款是的哦付i哦款是的哦付i哦"  // 内容尽可能在手机上超过一行
      }
    },
 
 <van-field type="textarea" readonly disabled placeholder="请输入" value="{{ params.contentDescription }}" 

### Vant Weapp 版本

1.10.25

### 描述一下你遇到的问题。

当van-field组件指定type为textarea，设置readonly或disabled为true，或是同时都设置为true，当组件内容超过一行或多行展示时，在ios设备上readonly或disabled会失效，内容可以被点击、出现光标、可以进行添加或修改，input事件也会被正常触发。

该问题在android设备上未出现。

### 重现步骤

1. 点击禁用状态下的富文本框（当内容比较多的时候，光标会出现在最后面，可以用手指滑动滚动条至底部看到光标，键盘也会被调起）
2. 输入内容，与未禁用状态表现一致，仅组件内容颜色置灰了，依然可编辑内容

### 设备/浏览器

苹果手机（ios）

**Comment by landluck** [comment]
没能复现，如能复现，提供一下[代码片段](https://developers.weixin.qq.com/miniprogram/dev/devtools/minicode.html) 和 设备信息吧
