### ISSUE TITLE
[控制台黄色提示]addGlobalClass选项已被弃用。。。

### ISSUE THREAD

**Issue by talmudmaster** [youzan/vant-weapp#5809]
### 重现链接

<van-button type="primary">按钮</van-button>

### Vant Weapp 版本

1.11.6

### 描述一下你遇到的问题。

引入vant weapp并使用相关样式，控制台会有多个相同的黄色提示，该如何解决？

控制台黄色提示：

Dynamic `addGlobalClass` option in component definition of "miniprogram_npm/@vant/weapp/loading/index" have been deprecated, and will NOT take effect in glass-easel. Consider migrating this option to component static config (miniprogram_npm/@vant/weapp/loading/index.json) by adding `{ "styleIsolation": "apply-shared" `}

### 重现步骤

引入vant weapp并使用相关样式，控制台会有多个相同的黄色提示，该如何解决？

**Comment by TLovers** [comment]
是不是开启了 "renderer": "skyline", 如果是的话，好像是有这个问题

**Comment by landluck** [comment]
skyline 模式暂时还没有适配。skyline 组件库现在也用不了

**Comment by talmudmaster** [comment]
感谢大伙的解答，期待之后的适配

解决方法：删掉 app.json 中的 "renderer": "skyline", 就行了
