### ISSUE TITLE
ActionSheet滚动问题

### ISSUE THREAD

**Issue by tielei60** [youzan/vant-weapp#581]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**你需要的功能是？**
ActionSheet弹出后，上下滑动，没有锁定滚动条，导致背景页面跟着上下一起动

**你期望 API 是什么样的？**
描述一下你期望的 API 形式

**Comment by chenjiahan** [comment]
目前无法在组件内部阻止背景滚动，可以在弹出组件时，在外部容器上添加 `overflow: hidden;` 属性
