### ISSUE TITLE
Dialog h函数方式调用 openSetting 的

### ISSUE THREAD

**Issue by PHPwamp** [youzan/vant-weapp#5813]
### 重现链接

![微信图片_20240604104334](https://github.com/youzan/vant-weapp/assets/35019144/8662187f-eea3-4f6d-bbae-d9a6775d6cc0)
![微信图片_20240604104456](https://github.com/youzan/vant-weapp/assets/35019144/17b5fe9a-7d7a-446f-9e4e-8ee5bb1d8f14)

### Vant Weapp 版本

1.11.5

### 描述一下你遇到的问题。

真机预览，点击确认按钮可以打开设置页，但是会进入openSetting的fail回调中

### 重现步骤

看重现

### 设备/浏览器

iphone 12 pro

**Comment by landluck** [comment]
dialog 的 then 是异步调用，所以微信视为用户未点击，可以通过设置  confirmButtonOpenType = "openSetting" 来打开设置页，监听 `bind:opensetting` 监听打开授权设置页后回调
