### ISSUE TITLE
collapse bug 引入了，进入页面出错

### ISSUE THREAD

**Issue by qq992064577** [youzan/vant-weapp#5814]
### 重现链接

![image](https://github.com/youzan/vant-weapp/assets/70893645/ba477158-aff9-4005-8680-2db308ac50c8)
![image](https://github.com/youzan/vant-weapp/assets/70893645/af98af31-151d-4e1e-b116-7574b2d2a37b)
![image](https://github.com/youzan/vant-weapp/assets/70893645/51e4a548-c5e5-4cd5-84c4-b3db1d404257)
![image](https://github.com/youzan/vant-weapp/assets/70893645/01fae404-8cc2-48b7-aa12-24b1e19a07a5)

### Vant Weapp 版本

1.11.2

### 描述一下你遇到的问题。

折叠屏组件页面报错，已经引入

### 重现步骤

代码在上面

### 设备/浏览器

微信小程序

**Comment by landluck** [comment]
没有复现，可以升级最新版本尝试一下，如还能复现提供一下小程序片段和基础库相关信息
