### ISSUE TITLE
[Bug Report] Stepper组件，当有小数点时，删除数值异常

### ISSUE THREAD

**Issue by opprime** [youzan/vant-weapp#5815]
### 重现链接

`<van-stepper step="1.0" decimal-length="{{ 1 }}" />`

### Vant Weapp 版本

1.11.6

### 描述一下你遇到的问题。

将焦点移到输入框内，然后删除，删除数值，无法删除

请看下面GIF图

![WeChat_20240606090017](https://github.com/youzan/vant-weapp/assets/11596986/e45ceeb8-ce65-4b08-94e8-57e3dfb3c49c)

### 重现步骤

1、添加代码 `<van-stepper step="1.0" decimal-length="{{ 1 }}" />`
2、将焦点移到输入框内
3、点键盘上的删除按钮

### 设备/浏览器

所有设备

**Comment by landluck** [comment]
你配置了 `decimal-length="{{ 1 }}"` 所以会固定显示一位小数，如果不需要显示小数，把这个配置去掉就行

**Comment by opprime** [comment]
> 你配置了 `decimal-length="{{ 1 }}"` 所以会固定显示一位小数，如果不需要显示小数，把这个配置去掉就行

那就是说，如果有小数，不能通过输入框修改数值是吗？

PS：同样的代码，在1.11.4及之前是可以通过输入框修改的

**Comment by secchen** [comment]
我今天更新完版本也发现这个bug了，我们的价格需要显示到两位小数，设置decimal-length="{{ 2 }}"，没办法删除数字输入新的值

**Comment by opprime** [comment]
> 我今天更新完版本也发现这个bug了，我们的价格需要显示到两位小数，设置decimal-length="{{ 2 }}"，没办法删除数字输入新的值

你重新提ISSUES吧，我这个已经被他们关闭了
