### ISSUE TITLE
真机预览组件不能显示的问题

### ISSUE THREAD

**Issue by jamesnbklas** [youzan/vant-weapp#5817]
### 重现链接

小程序暂未发布

### Vant Weapp 版本

1.11.6

### 描述一下你遇到的问题。

![微信图片_20240607094957](https://github.com/youzan/vant-weapp/assets/99232702/13d4806e-7a1b-47fa-b737-1a095295035f)
引入的组件在开发者工具里面可以正常显示，但是真机预览的时候大部分都不能显示

![微信图片_20240607094942](https://github.com/youzan/vant-weapp/assets/99232702/4d611fa6-6af4-42b2-a79c-edb17b472322)
![微信图片_20240607094950](https://github.com/youzan/vant-weapp/assets/99232702/5e9cf9d6-b4ce-430d-b773-0cf293319d0a)
![微信图片_20240607095003](https://github.com/youzan/vant-weapp/assets/99232702/6cb95c0e-fb03-4587-a3f9-7bc5c26a3697)

### 重现步骤

进入页面组件就不会显示

**Comment by landluck** [comment]
提供一下设备信息
