### ISSUE TITLE
急需适配skyLine模式,现有功能不能适配skyLine模式,造成样式基本或完全失效

### ISSUE THREAD

**Issue by paulxlxy** [youzan/vant-weapp#5818]
### 这个功能解决了什么问题？

适配最新的微信小程序skyLine模式, 以便使用skyLine模式下的新功能

### 你期望的 API 是什么样子的？

完美适配skyLine模式

**Comment by lukesyy** [comment]
skyLine模式本身就不太成熟

**Comment by landluck** [comment]
skyline 目前并不稳定，有很多能力还未成熟，适配还需要一些时间。
