### ISSUE TITLE
mpvue引入vant报错thirdScriptError

### ISSUE THREAD

**Issue by don59** [youzan/vant-weapp#582]
将ES6转ES5的勾去掉后报错，详情参看附件视频
[kk 2018-09-17 16-00-44.zip](https://github.com/youzan/vant-weapp/files/2387712/kk.2018-09-17.16-00-44.zip)

> VM4443:1 thirdScriptError 
 sdk uncaught third Error 
 Unexpected token import 
 SyntaxError: Unexpected token import
console.error @ VM4443:1
(anonymous) @ WAService.js:15
(anonymous) @ WAService.js:6
e @ appservice?t=1537171540074:2914
window.onerror @ VM4443:1
VM4443:1 thirdScriptError 
 sdk uncaught third Error 
 Unexpected token export 
 SyntaxError: Unexpected token export
console.error @ VM4443:1
(anonymous) @ WAService.js:15
(anonymous) @ WAService.js:6
e @ appservice?t=1537171540074:2914
window.onerror @ VM4443:1
VM4443:1 thirdScriptError 
 sdk uncaught third Error 
 Unexpected token export 
 SyntaxError: Unexpected token export
console.error @ VM4443:1
(anonymous) @ WAService.js:15
(anonymous) @ WAService.js:6
e @ appservice?t=1537171540074:2914
window.onerror @ VM4443:1
VM4443:1 thirdScriptError 
 sdk uncaught third Error 
 Unexpected token export 
 SyntaxError: Unexpected token export
console.error @ VM4443:1
(anonymous) @ WAService.js:15
(anonymous) @ WAService.js:6
e @ appservice?t=1537171540074:2914
window.onerror @ VM4443:1
VM4443:1 thirdScriptError 
 sdk uncaught third Error 
 Unexpected token export 
 SyntaxError: Unexpected token export
console.error @ VM4443:1
(anonymous) @ WAService.js:15
(anonymous) @ WAService.js:6
e @ appservice?t=1537171540074:2914
window.onerror @ VM4443:1
VM4443:1 thirdScriptError 
 sdk uncaught third Error 
 Unexpected token import 
 SyntaxError: Unexpected token import
console.error @ VM4443:1
(anonymous) @ WAService.js:15
(anonymous) @ WAService.js:6
e @ appservice?t=1537171540074:2914
window.onerror @ VM4443:1
VM4443:1 thirdScriptError 
 sdk uncaught third Error 
 Unexpected token export 
 SyntaxError: Unexpected token export
console.error @ VM4443:1
(anonymous) @ WAService.js:15
(anonymous) @ WAService.js:6
e @ appservice?t=1537171540074:2914
window.onerror @ VM4443:1
VM4443:1 thirdScriptError 
 sdk uncaught third Error 
 Unexpected token export 
 SyntaxError: Unexpected token export
console.error @ VM4443:1
(anonymous) @ WAService.js:15
(anonymous) @ WAService.js:6
e @ appservice?t=1537171540074:2914
window.onerror @ VM4443:1
VM4443:1 thirdScriptError 
 sdk uncaught third Error 
 Unexpected token export 
 SyntaxError: Unexpected token export
console.error @ VM4443:1
(anonymous) @ WAService.js:15
(anonymous) @ WAService.js:6
e @ appservice?t=1537171540074:2914
window.onerror @ VM4443:1
VM4443:1 thirdScriptError 
 sdk uncaught third Error 
 Unexpected token import 
 SyntaxError: Unexpected token import
console.error @ VM4443:1
(anonymous) @ WAService.js:15
(anonymous) @ WAService.js:6
e @ appservice?t=1537171540074:2914
window.onerror @ VM4443:1
VM4443:1 thirdScriptError 
 sdk uncaught third Error 
 Unexpected token export 
 SyntaxError: Unexpected token export
console.error @ VM4443:1
(anonymous) @ WAService.js:15
(anonymous) @ WAService.js:6
e @ appservice?t=1537171540074:2914
window.onerror @ VM4443:1
VM4443:1 thirdScriptError 
 sdk uncaught third Error 
 Unexpected token export 
 SyntaxError: Unexpected token export
console.error @ VM4443:1
(anonymous) @ WAService.js:15
(anonymous) @ WAService.js:6
e @ appservice?t=1537171540074:2914
window.onerror @ VM4443:1
VM4443:1 thirdScriptError 
 sdk uncaught third Error 
 Unexpected token import 
 SyntaxError: Unexpected token import
console.error @ VM4443:1
(anonymous) @ WAService.js:15
(anonymous) @ WAService.js:6
e @ appservice?t=1537171540074:2914
window.onerror @ VM4443:1
VM4443:1 thirdScriptError 
 sdk uncaught third Error 
 Unexpected token export 
 SyntaxError: Unexpected token export
console.error @ VM4443:1
(anonymous) @ WAService.js:15
(anonymous) @ WAService.js:6
e @ appservice?t=1537171540074:2914
window.onerror @ VM4443:1
VM4443:1 thirdScriptError 
 sdk uncaught third Error 
 Unexpected token import 
 SyntaxError: Unexpected token import
console.error @ VM4443:1
(anonymous) @ WAService.js:15
(anonymous) @ WAService.js:6
e @ appservice?t=1537171540074:2914
window.onerror @ VM4443:1
VM4443:1 thirdScriptError 
 sdk uncaught third Error 
 Unexpected token import 
 SyntaxError: Unexpected token import
console.error @ VM4443:1
(anonymous) @ WAService.js:15
(anonymous) @ WAService.js:6
e @ appservice?t=1537171540074:2914
window.onerror @ VM4443:1
VM4443:1 thirdScriptError 
 sdk uncaught third Error 
 Unexpected token import 
 SyntaxError: Unexpected token import
console.error @ VM4443:1
(anonymous) @ WAService.js:15
(anonymous) @ WAService.js:6
e @ appservice?t=1537171540074:2914
window.onerror @ VM4443:1
VM4443:1 thirdScriptError 
 sdk uncaught third Error 
 Unexpected token import 
 SyntaxError: Unexpected token import
console.error @ VM4443:1
(anonymous) @ WAService.js:15
(anonymous) @ WAService.js:6
e @ appservice?t=1537171540074:2914
window.onerror @ VM4443:1
VM4443:1 thirdScriptError 
 sdk uncaught third Error 
 Unexpected token import 
 SyntaxError: Unexpected token import
console.error @ VM4443:1
(anonymous) @ WAService.js:15
(anonymous) @ WAService.js:6
e @ appservice?t=1537171540074:2914
window.onerror @ VM4443:1
VM4443:1 thirdScriptError 
 sdk uncaught third Error 
 Unexpected token import 
 SyntaxError: Unexpected token import
console.error @ VM4443:1
(anonymous) @ WAService.js:15
(anonymous) @ WAService.js:6
e @ appservice?t=1537171540074:2914
window.onerror @ VM4443:1
app.js:96 app created and cache logs by setStorageSync
VM4443:1 thirdScriptError 
 sdk uncaught third Error 
 module "static/vant/action-sheet/index.js" is not defined 
 Error: module "static/vant/action-sheet/index.js" is not defined
    at require (http://127.0.0.1:50389/appservice/__dev__/WAService.js:23:11483)
    at <anonymous>:13:7
    at HTMLScriptElement.scriptLoaded (http://127.0.0.1:50389/appservice/appservice?t=1537171540074:3173:23)
console.error @ VM4443:1
(anonymous) @ WAService.js:15
(anonymous) @ WAService.js:6
e @ appservice?t=1537171540074:2914
window.onerror @ VM4443:1
scriptLoaded @ appservice?t=1537171540074:3173
VM4443:1 jsEnginScriptError
Component is not found in path "static/vant/button/index" (using by "pages/index/main")
Error: Component is not found in path "static/vant/button/index" (using by "pages/index/main")
    at e (http://127.0.0.1:50389/appservice/__dev__/WAService.js:17:20877)
    at e (http://127.0.0.1:50389/appservice/__dev__/WAService.js:17:21063)
    at le (http://127.0.0.1:50389/appservice/__dev__/WAService.js:17:31464)
    at Object.i.addView (http://127.0.0.1:50389/appservice/__dev__/WAService.js:18:842)
    at Function.value (http://127.0.0.1:50389/appservice/__dev__/WAService.js:19:31598)
    at $t (http://127.0.0.1:50389/appservice/__dev__/WAService.js:20:13863)
    at on (http://127.0.0.1:50389/appservice/__dev__/WAService.js:20:16346)
    at sn (http://127.0.0.1:50389/appservice/__dev__/WAService.js:20:16684)
    at Function.<anonymous> (http://127.0.0.1:50389/appservice/__dev__/WAService.js:20:19117)
    at L.<anonymous> (http://127.0.0.1:50389/appservice/__dev__/WAService.js:19:17507)
console.error @ VM4443:1
errorReport @ WAService.js:4
(anonymous) @ WAService.js:4
M @ WAService.js:19
(anonymous) @ WAService.js:19
L.emit @ WAService.js:8
emit @ WAService.js:6
(anonymous) @ WAService.js:9
(anonymous) @ WAService.js:6
e @ appservice?t=1537171540074:2914
n.registerCallback.t @ appservice?t=1537171540074:2914
l.forEach.t @ appservice?t=1537171540074:2914
(anonymous) @ appservice?t=1537171540074:2914
i.onmessage @ appservice?t=1537171540074:2914

**Comment by chenjiahan** [comment]
目前需要打开 es6 转 es5 才能使用 Vant

**Comment by don59** [comment]
> 目前需要打开 es6 转 es5 才能使用 Vant

@chenjiahan  但是打开后不能用微信开发者工具调试了，怎么弄？

**Comment by chenjiahan** [comment]
@don59 为什么无法调试呢

**Comment by don59** [comment]
@chenjiahan  es6 转 es5那个勾勾上后，微信开发者工具webpack没法打断点，勾去掉才可以。

**Comment by pbbisme** [comment]
@don59 调试有什么解决方案没，我这里也和你去情况一样

**Comment by don59** [comment]
> @don59 调试有什么解决方案没，我这里也和你去情况一样

不去掉勾勾，只能酱紫了。调试全靠console

**Comment by limengge291** [comment]
使用debugger 可以看见未编译的js源码

**Comment by HADB** [comment]
> 目前需要打开 es6 转 es5 才能使用 Vant

这个最好在文档里说明下，因为这个问题浪费了几个小时了

**Comment by 9yues** [comment]
有个问题啊，我使用regenerator-runtime这个来支持 async await，就不能勾上ES6转ES5，但是vant又得需要ES6转ES5，这可咋办
