### ISSUE TITLE
引入组件后提示 alicdn报错？？请尽快修复

### ISSUE THREAD

**Issue by mydoge** [youzan/vant-weapp#5820]
### 重现链接

![WX20240616-132344@2x](https://github.com/youzan/vant-weapp/assets/128971573/73d916aa-acdb-44c0-94fd-31a645959289)
![WX20240616-132344@2x](https://github.com/youzan/vant-weapp/assets/128971573/7e327927-8b1f-4865-83f8-79c8a268f927)

### Vant Weapp 版本

最新版

### 描述一下你遇到的问题。

1

### 重现步骤

1

**Comment by mydoge** [comment]
我建议不要用随意用cdn！

以前有个项目我们用cdn的axios，然后这个cdn突然崩溃，造成我们整个项目停滞了好几小时，后果非常严重。

从那以后 我就看到cdn都后怕！

用cdn是最不稳定的事情，希望改进，业务稳定运行是至关重要的。

**Comment by landluck** [comment]
ERR_CACHE_MISS 这个报错大概跟开发者工具缓存有关系，遇到刷新就可以了。目前字体图标是统一托管到CDN上。放到代码包中会有体积问题
