### ISSUE TITLE
dialog弹出层为啥确定按钮点击会自动关闭弹窗？那你们的show属性的作用是什么？

### ISSUE THREAD

**Issue by 944832260** [youzan/vant-weapp#5824]
### 重现链接

<van-dialog use-slot title="填写货单号/临时码" confirm-button-color="#1673FF" show="{{ isShowModal }}" show-confirm-button show-cancel-button bind:cancel="cancelModal" bind:confirm="submit">
        <view class="huodan_input">
            <input placeholder="货单号/临时码" placeholder-style="color: #C9CDD4;" value="{{evidenceCode}}" bindinput="evCodeChange" />
        </view>
    </van-dialog>

### Vant Weapp 版本

1.10.13

### 描述一下你遇到的问题。

show属性都有了 但是没有任何作用，点确认和取消的时候 自动就关闭弹窗了 确定的时候一般有个请求吧 请求失败呢 也关闭弹窗了 怎么会有这样的设计存在，有show属性是不是应该让我自己控制

### 重现步骤

点击确认

**Comment by landluck** [comment]
如果要阻止关闭可以先用 `before-close` props 实现

**Comment by lopaz** [comment]
> 如果要阻止关闭可以先用 `before-close` props 实现

但是before-close在使用组件调用的方式时没法用吧？
