### ISSUE TITLE
[Bug Report] van-toast 会被被 van-dialog 挡住，我已经给van-toast设置了很高的zIndex 仍未解决

### ISSUE THREAD

**Issue by CQWSBUY** [youzan/vant-weapp#5825]
### 重现链接

<van-dialog use-slot title="粘贴链接" show="{{ show }}" show-cancel-button="{{false}}" show-confirm-button="{{false}}"
    confirm-button-open-type="getUserInfo" cancelButtonText="黏贴链接" confirmButtonText="确定" bind:dopast="dopast"
    bind:getuserinfo="getUserInfo" closeOnClickOverlay="true" custom-class="van-dialog">
    <view class="textAreaContainer">
            <textarea class="textarea" placeholder="请先分享链接后，在这里长按粘结" value="{{url}}"></textarea>
        </view>
        <view class="buttonContainer">
            <view class="left" bind:tap="dopast">粘贴链接</view>
            <view class="right" bind:tap="doTextExtraction">确定</view>
        </view>
</van-dialog>
<van-toast id="van-toast" zIndex="20000"/>

### Vant Weapp 版本

@vant/weapp@1.11.5

### 描述一下你遇到的问题。

我在点击确定后会对黏贴做一个内容检测，检测不通过会进行Toast提示用户，现在的问题是无论我如何设置Toast的ZInde值，都会被dialog遮挡，经过调试（主动关闭dialog）我确定toast是显示了的，只是被遮挡了
![image](https://github.com/youzan/vant-weapp/assets/42727638/8debd63c-be98-467d-9d19-3f62c62b1ef0)

### 重现步骤

点击确定按钮，触发Toast

### 设备/浏览器

微信开发者工具本地调试

**Comment by landluck** [comment]
dialog 是 2000, toast 是 1000，看下设置的是不是超过这个值。不行  textarea 开启一下 always-embed  同层渲染试试
