### ISSUE TITLE
[Bug Report] 使用vant-skeleton组件时实时渲染的问题

### ISSUE THREAD

**Issue by wyxh2004** [youzan/vant-weapp#5826]
### 重现链接

    <van-skeleton avatar-size="100rpx" title="true" avatar="true" row="1" loading="{{ loading }}">
        <view class="avatar" bind:tap="goToRegister">
            <fui-avator style="margin-right: 50rpx" text="我" background="#FFB703" />
            登录查看更多信息
            <view wx:if="{{userInfo.nickname}}">{{userInfo.nickname}}</view>
            <van-button wx:else round src="{{userInfo.avatorUrl}} || null" type="info" bind:click="goToRegister" color="rgba(244, 239, 12, 0.43)">
                点击登录
            </van-button>
        </view>
    </van-skeleton>

### Vant Weapp 版本

1.11.4

### 描述一下你遇到的问题。

在编辑调用了vant-skeleton组件的页面时，给skeleton组件内部的子组件绑定bind:tap事件并Ctrl + S保存后，模拟器中会重新加载loading占位图形并一直卡在loading动画上，只有重新编译之后才能正常显示skeleton内的内容

### 重现步骤

给示例代码中的bind:tap的goToRegister函数添加一行console(“123”)，模拟器显示骨架屏动画并卡住，重新编译后才能正常显示skeleton内的内容

### 设备/浏览器

vscode，微信开发者工具

**Comment by landluck** [comment]
![image](https://github.com/youzan/vant-weapp/assets/27060081/de29b261-4d37-4e26-8f5f-5a54723ab982)
可以尝试先把开发工具的这个选项关掉试试，这个功能在某些场景下会有异常。如还不行，需要提供可复现的[代码片段](https://developers.weixin.qq.com/miniprogram/dev/devtools/minicode.html)
