### ISSUE TITLE
vant radio组件使用自定义 图标时，选择框无法显示

### ISSUE THREAD

**Issue by mvpyb** [youzan/vant-weapp#5827]
### 重现链接

<van-radio-group value="{{ radio }}" bind:change="onChange">
        <van-radio use-icon-slot value="{{ radio }}" name="1">
          自定义图标
          <image slot="icon" src="{{ radio === '1' ? icon.active : icon.normal }}" />
        </van-radio>
        <van-radio use-icon-slot value="{{ radio }}" name="2">
          自定义图标
          <image slot="icon" src="{{ radio === '2' ? icon.active : icon.normal }}" />
        </van-radio>
      </van-radio-group>

Page({
  data: {
    radio: true,
    icon: {
      normal: '//img.yzcdn.cn/icon-normal.png',
      active: '//img.yzcdn.cn/icon-active.png',
    },
  },
  onChange(event) {
    this.setData({
      radio: event.detail,
    });
  },
});

### Vant Weapp 版本

1.11.4

### 描述一下你遇到的问题。

vant radio组件， 使用自定义图标后不生效
代码也是直接复制的官方示例代码，

渲染效果如下 ： 
![image](https://github.com/youzan/vant-weapp/assets/34262867/5d2a0829-5430-4901-837a-721387acf0a6)

### 重现步骤

直接复制的官方示例代码 

### 设备/浏览器

微信小程序

**Comment by mvpyb** [comment]
我把vant 升级到最新的1.11.6 也没用

**Comment by landluck** [comment]
自定义图标需要 `use-icon-slot` 为 `true`。如果设置为 `true`  还存在问题，提供一下小程序代码片段 [代码片段](https://developers.weixin.qq.com/miniprogram/dev/devtools/minicode.html)
