### ISSUE TITLE
Icon 如何加载本地图标呢？

### ISSUE THREAD

**Issue by josephyuen** [youzan/vant-weapp#583]
参考了文档和issue，没有发现icon 支持加载本地图标的,请问对加载本地图标有什么建议么？

**Comment by chenjiahan** [comment]
暂时没有使用本地图标的方案

**Comment by 531431988** [comment]
@font-face {
  font-family: "iconfont";
  src: url()
}
[class*=" icon icon-"]{
font-family:"iconfont" !important;
}

阿里第三方图库，调用如下： 
<van-icon name="ios-mic-off" size="20px" class-prefix="icon" />

看不懂就没办法了，同时建议组件中的icon不要用属性去添加最好能支持slot插槽的方式，这样也可以做到自定义图标了，如field组件中的icon 改用slot方式便可支持自定义图标，虽然我可以自己改，但如果你们更新了，我这边又得替换比较麻烦

**Comment by 531431988** [comment]
<van-icon name="ios-mic-off" size="20px" class-prefix="icon" />

**Comment by 531431988** [comment]
![image](https://user-images.githubusercontent.com/8703951/46240035-f4f4cd80-c3d3-11e8-8ee6-65183f62a2b0.png)

**Comment by Ding-Fan** [comment]
提议：把 vant 自带的图标命名为 `vi-xxx` 这样，并在文档里注明。这样就可以不用 `isSrc` 了，直接 `isVantIcon` 。

```js
function isVantIcon(name) {
  return /^vi-[\w\d-]+$/.test(name)
}
```

**Comment by hqzh** [comment]
uni-app无这个烦恼
