### ISSUE TITLE
van-notice-bar滚动速率不一致

### ISSUE THREAD

**Issue by bgmmd** [youzan/vant-weapp#5844]
### 重现链接

https://developers.weixin.qq.com/s/uoCHeHm27WSg

### Vant Weapp 版本

1.11.4

### 描述一下你遇到的问题。

初始化第一次速率偏慢，后续的循环滚动速率偏快。speed调快后，两次速率差距更明显

### 重现步骤

<van-notice-bar
  wrapable
  scrollable="{{ true }}"
  text="在代码阅读过程中人们说脏话的频率是衡量代码质量的唯一标准。"
/>

### 设备/浏览器

微信开发者工具和真机上都能稳定复现

**Comment by landluck** [comment]
[v1.11.7](https://github.com/youzan/vant-weapp/compare/v1.11.6...v1.11.7) 已修复
