### ISSUE TITLE
[Bug Report] 1.11.6 npm仓库没有更新：uploader 中的videoReferrerPolicy属性

### ISSUE THREAD

**Issue by xueyan1** [youzan/vant-weapp#5847]
### 重现链接

暂无

### Vant Weapp 版本

v1.11.6

### 描述一下你遇到的问题。

1.11.6版本
git代码更新了 Uploader: 新增 referrer-policy 属性支持 [#5770](https://github.com/youzan/vant-weapp/issues/5770)
但是 npm仓库代码没有更新，如下图：
![521721887823_ pic](https://github.com/user-attachments/assets/aa783853-4211-4194-b916-2eec71fbcaf3)

### 重现步骤

1.  打开npm仓库: https://www.npmjs.com/package/@vant/weapp?activeTab=code ,
2. @vant/weapp/dist/uploader/index.js文件 40行， videoReferrerPolicy属性缺失。

**Comment by landluck** [comment]
[v1.11.7](https://github.com/youzan/vant-weapp/compare/v1.11.6...v1.11.7) 已修复
