### ISSUE TITLE
[Bug Report] settper无法输入小数

### ISSUE THREAD

**Issue by ArmyMedalMei** [youzan/vant-weapp#5852]
### 重现链接

<van-stepper input-width="80px" />

### Vant Weapp 版本

1.11.6

### 描述一下你遇到的问题。

settper无法输入小数，但是将版本降级到1.10.25之后就能输入小数

### 重现步骤

- 在输入框输入2.
- 自动会将2.修改成2

### 设备/浏览器

安卓、IOS

**Comment by Baiang** [comment]
遇到同样问题

**Comment by landluck** [comment]
[v1.11.7](https://github.com/youzan/vant-weapp/compare/v1.11.6...v1.11.7) 已修复
