### ISSUE TITLE
[Bug Report] PC端Field 输入框 autosize不生效

### ISSUE THREAD

**Issue by myth984** [youzan/vant-weapp#5870]
### 重现链接

` <van-field model:value="{{ content }}" label="内容" type="textarea" autosize />`

### Vant Weapp 版本

1.11.6

### 描述一下你遇到的问题。

实机可以正常使用 但是PC端启动微信小程序 输入框高度没法自动 超出一行的情况下 上一行将会隐藏

### 重现步骤

PC端查看具备 autosize的输入框

### 设备/浏览器

PC

**Comment by landluck** [comment]
那个设备？mac 测试是可以自动撑开的

**Comment by myth984** [comment]
> 那个设备？mac 测试是可以自动撑开的

windows 最新版微信已经可以了 closed
