### ISSUE TITLE
引入 vant -steps 之后， 最后一个节点的显示问题

### ISSUE THREAD

**Issue by biel-fyq** [youzan/vant-weapp#5871]
### 重现链接

![image](https://github.com/user-attachments/assets/dfda4897-f04c-4403-b211-3266d65b087d)

### Vant Weapp 版本

1.10.3

### 描述一下你遇到的问题。

如图片所示，如果说decs只写一个 其他都不写，那么最后一个节点的圆圈就不会出现在同一水平线上

### 重现步骤

数据：steps: [
    {
      text: '预约',
      desc: '去预约',
    },
    {
      text: '面试',
      desc: '',
    },
    {
      text: '生活普查',
      desc: '',
    },
    {
      text: '体检',
      desc: '',
    },
    {
      text: '报到',
      desc: '',
    },
    {
      text: '入职',
      desc: '', 
    },
  ],

**Comment by biel-fyq** [comment]
实际上 是根据text 与desc最大字符的长度决定的 如果说长度一样 那么就不会出现图片上的问题，如果说不一样，那么最后一个节点位置的展示绝对会往上走

**Comment by landluck** [comment]
[v1.11.7](https://github.com/youzan/vant-weapp/compare/v1.11.6...v1.11.7) 已修复
