### ISSUE TITLE
[Bug Report]  van-collapse折叠面板展开后底部的线条不能去除

### ISSUE THREAD

**Issue by lyg1440321871** [youzan/vant-weapp#5882]
### 重现链接

    <van-collapse :border="false" custom-class="no-background"  wx:if="{{item.projectInfo.length > 1}}" accordion value="{{activeNames}}" bind:change="onChange">
      <van-collapse-item :border="false" name="{{item.id}}">
        <view slot="value" class="stadium-details">
          <view class="projectName">{{item.projectInfo[0].projectType}}</view>
          <view class="rigth-text" class="rigth-text">
          <view class="Price">￥{{item.projectInfo[0].minPrice}}</view>
          <view class="priceText">{{item.projectInfo[0].projectName}}</view>
        </view>
        </view>
        <view class="stadium-details" wx:if="{{index!=0}}"  bindtap="onStadiumDetail" data-pidx="{{pidx}}" data-sidx="{{sidx}}" wx:for="{{item.projectInfo}}" wx:for-item="sitem" wx:key="index">
        
          <view class="projectName">{{sitem.projectType}}</view>
          <view class="rigth-text">
              <view  class="Price">￥{{sitem.minPrice}}</view>
              <view class="priceText">{{sitem.projectName}}</view>
          </view> 
        </view>
      </van-collapse-item>
    </van-collapse>

### Vant Weapp 版本

1.11.6

### 描述一下你遇到的问题。

折叠面板展开的时候底部有一个线条，应该是border设置的。我想要去除这个线条去除不掉

### 重现步骤

点击展开折叠面板即可发现

### 设备/浏览器

Google

**Comment by landluck** [comment]
[v1.11.7](https://github.com/youzan/vant-weapp/compare/v1.11.6...v1.11.7) 已修复，使用 border属性即可
