### ISSUE TITLE
mpvue引入dialog报错

### ISSUE THREAD

**Issue by mealayaria** [youzan/vant-weapp#589]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**描述一下问题**
描述一下你遇到的问题，包括复现方式、导致结果

在mpvue中引入dialog时报错如下图，看起来好像是无法解析展开操作符，尝试加入"babel-preset-es2015"并在 babelrc 中 presets 加入"es2015", 依然无法编译成功。
但我感觉mpvue默认配置应该是支持的吧，不太确定问题出在哪里。

**截图**
如果是 UI 问题，请提供具体截图
我的babel依赖如图，相比默认mpvue-quickstart多引入了一个 "babel-preset-es2015"
![image](https://user-images.githubusercontent.com/4319965/45640389-12c55700-bae5-11e8-89f8-f2637eba1e32.png)

babelrc如图
![image](https://user-images.githubusercontent.com/4319965/45640923-89af1f80-bae6-11e8-836c-a1b3b98cc8c8.png)

报错如图
![image](https://user-images.githubusercontent.com/4319965/45640473-5c15a680-bae5-11e8-8eef-3f20ada59a1e.png)

**环境**
 - 设备: 
   系统: windows 10 1803, 使用wsl archlinux
   node: 10.10.0
 - 基础库版本: 2.3.0
 - Vant Weapp 版本: 0.3.2

**Comment by chenjiahan** [comment]
编译配置的问题，可以开启 es6 转 es5
