### ISSUE TITLE
[Bug Report] Dialog组件底部按钮显示异常

### ISSUE THREAD

**Issue by echofly** [youzan/vant-weapp#5919]
### 重现链接

https://developers.weixin.qq.com/s/MILEjKmw7eTE

### Vant Weapp 版本

v1.11.6,v1.11.7

### 描述一下你遇到的问题。

弹窗按钮显示异常，加了代码`.van-dialog__footer .van-button { width: 100% !important; }`就正常了

![image](https://github.com/user-attachments/assets/0031ad75-0c4d-4b52-b4a0-c32626595e3d)
![image](https://github.com/user-attachments/assets/02ce15e7-3baf-475c-9d8a-5ac0f30093ec)

### 重现步骤

代码片段：https://developers.weixin.qq.com/s/MILEjKmw7eTE

### 设备/浏览器

微信开发者工具，ios

**Comment by TallNutAlt** [comment]
是否开启了  "style": "v2",

**Comment by TallNutAlt** [comment]
在app.json中去掉  "style": "v2",

**Comment by echofly** [comment]
确实是，感谢
