### ISSUE TITLE
popup组件设置height：100% 显示无法全屏

### ISSUE THREAD

**Issue by webyangpei** [youzan/vant-weapp#592]
问题：
popup组件设置height：100% 显示无法全屏

直接使用的
![image](https://user-images.githubusercontent.com/24697986/45684128-ec043080-bb77-11e8-95d0-5b76f77525a0.png)
![image](https://user-images.githubusercontent.com/24697986/45684232-42716f00-bb78-11e8-8be2-84fe97ce68bf.png)

之前在vue中在浏览器端是如此使用的，可以。现在可以手动更改源代码修正样式。不过，希望有赞团队可以优化支持，在小程序中也能这样用。
 - 设备:  微信开发者工具客户端
 - 基础库版本:  2.3.0
 - Vant Weapp 版本：0.3.2

**Comment by chenjiahan** [comment]
小程序里不支持直接在组件上传入 style 属性，下个版本会在 Popup 组件上增加 customStyle 属性用于支持这种场景
