### ISSUE TITLE
[Bug Report] Cascader组件在小程序里面，如果层级过多，选择时候的滚动和回显有点问题

### ISSUE THREAD

**Issue by eighty-cents** [youzan/vant-weapp#5922]
### 重现链接

[https://developers.weixin.qq.com/s/BIJVqlmj7dVM](url)

### Vant Weapp 版本

1.11.7

### 描述一下你遇到的问题。

Cascader组件在小程序里面，如果层级过多，选择的时候，tab横向的滑动会卡顿，并且选择了之后，想更换刚才的选择，回显不对，并且tab不能滑动

### 重现步骤

1、进入代码片段
2、然后选择左上角 “工具” ---> 选择构建npm
3、清除编译，重新刷新

**Comment by TallNutAlt** [comment]
value与子级相同
![image](https://github.com/user-attachments/assets/a974f92b-67c3-43f2-ac20-3a93de4cc8f2)

**Comment by TallNutAlt** [comment]
不同后正常
![image](https://github.com/user-attachments/assets/5d272145-c5d6-4f1d-8025-c5953b30c6be)
