### ISSUE TITLE
[Bug Report] van-tabs 真机只显示一个

### ISSUE THREAD

**Issue by TopAlien** [youzan/vant-weapp#5944]
### 重现链接

无

### Vant Weapp 版本

1.11.6

### 描述一下你遇到的问题。

<img width="474" alt="image" src="https://github.com/user-attachments/assets/a91b31c4-6c8e-417b-88bd-f006f0543b4e">
模拟器显示正常。真机只显示一个
![89c61f600638983f9113ca226d78924c_compress](https://github.com/user-attachments/assets/2c3bba3f-4974-49e4-bd23-55f79ca15e8b)

### 重现步骤

无

**Comment by TopAlien** [comment]
![89c61f600638983f9113ca226d78924c_compress](https://github.com/user-attachments/assets/e6ceb3a3-76f8-4423-a318-fee71c84c974)

**Comment by chenzhoahua0830** [comment]
应该不是组件库的问题，我这边项目用tDesign也存在同样的问题。
相同的代码，以前打包上传的版本显示正常，只要是新构建的代码就会出现问题

**Comment by pengzhengpeng** [comment]
我也遇到了这样的问题，很纳闷

**Comment by zsg179** [comment]
我也遇到了一样的问题，有人解决了吗？：
在开发者工具中能正常显示4个标签tab，在手机上只显示1个标签tab，昨天还是正常的，今天没改代码，就变成这样了，在真机上调试时发现疑似就只渲染了一个tab。

开发者工具版本：1.06.2409140

调试基础库：3.6.6

PC操作系统：win11

手机型号：iphone12

手机操作系统：IOS 18.1

微信版本：8.0.54

**Comment by pengzhengpeng** [comment]
> 我也遇到了同样的问题，有人解决了吗？： 在开发者工具中能正常显示4个标签选项卡，在手机上只显示1个标签选项卡，昨天还是正常的，今天没改代码，就变成了这样了，在真机上调试时发现疑似只渲染了一个选项卡。
> 
> 开发者工具版本：1.06.2409140
> 
> 调试基础知识：3.6.6
> 
> PC操作系统：win11
> 
> 手机型号：iphone12
> 
> 手机操作系统：IOS 18.1
> 
> 微信版本：8.0.54

我已经在微信社区提了这个问题，官方目前还没回复

**Comment by TopAlien** [comment]
刚刚上去看，又可以了

**Comment by pengzhengpeng** [comment]
> 刚刚上去看，又可以了

应该是官方偷偷回滚了代码
