### ISSUE TITLE
[Bug Report] cascader反显的时候tab样式有问题

### ISSUE THREAD

**Issue by MinG252** [youzan/vant-weapp#5951]
### 重现链接

![image](https://github.com/user-attachments/assets/44202ac2-127f-42e2-ac71-3d28e14e9cbf)

### Vant Weapp 版本

1.11.7

### 描述一下你遇到的问题。

反显的时候tab的样式显示的还是在一级，value绑的是string，数据结构的value也是string

### 重现步骤

初始化默认绑定的value，打开后tab显示错误

```[tasklist]
### Tasks
```

**Comment by TallNutAlt** [comment]
提供一下代码片段

**Comment by MinG252** [comment]
`<van-popup position="bottom" show="{{ popup._platformArray }}" bind:close="cancelPopup" data-param="_platformArray">
<van-cascader show-header options="{{ options.platformArray }}" value="{{ a }}" title="推广渠道" bind:close="cancelPopup" bind:finish="confirmCascaderPopup" data-param="_platformArray" />
</van-popup>`

a: '108',

<img width="504" alt="image" src="https://github.com/user-attachments/assets/b9017284-d5ec-45c6-af5e-b2d684182b4f" />

![image](https://github.com/user-attachments/assets/118c45e3-6550-4167-a0e7-f37cbb32bba1)

就是这样，value取的二级的值，但是上面tab的样式还在一级

@TallNutAlt

**Comment by TallNutAlt** [comment]
> `<van-popup position="bottom" show="{{ popup._platformArray }}" bind:close="cancelPopup" data-param="_platformArray"> <van-cascader show-header options="{{ options.platformArray }}" value="{{ a }}" title="推广渠道" bind:close="cancelPopup" bind:finish="confirmCascaderPopup" data-param="_platformArray" /> </van-popup>`
> 
> a: '108',
> 
> <img alt="image" width="504" src="https://private-user-images.githubusercontent.com/53910987/398643610-b9017284-d5ec-45c6-af5e-b2d684182b4f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUxOTM2MjEsIm5iZiI6MTczNTE5MzMyMSwicGF0aCI6Ii81MzkxMDk4Ny8zOTg2NDM2MTAtYjkwMTcyODQtZDVlYy00NWM2LWFmNWUtYjJkNjg0MTgyYjRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI2VDA2MDg0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVjY2U1MTNkMmJhNzEzN2NlMzE5ODdiYjZkOWU1ODExMzcyYjQyNmNlMDc1MzZlMmQyZjU1YTdiNThiNjgwZTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.algPNbU5PBDglXK1HmUWleLqir9fRsiUtCJoP0QwDo4">
> ![image](https://private-user-images.githubusercontent.com/53910987/398643756-118c45e3-6550-4167-a0e7-f37cbb32bba1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUxOTM2MjEsIm5iZiI6MTczNTE5MzMyMSwicGF0aCI6Ii81MzkxMDk4Ny8zOTg2NDM3NTYtMTE4YzQ1ZTMtNjU1MC00MTY3LWEwZTctZjM3Y2JiMzJiYmExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI2VDA2MDg0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI3NGY0ZGE0MmFiZTI1YmIzMDFiNmEyNzhhZTM3NzhhNTZhYTQ3ZGM4NmIzMTdhMzgxMDE2YjQxYWE4ZGEyZDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.8ZxUTUjukNoK_ukhB9SIRLsPBhFrcyr7NmNQM1a6Xag)
> 
> 就是这样，value取的二级的值，但是上面tab的样式还在一级
> 
> @TallNutAlt
https://developers.weixin.qq.com/s/pp31jJmk7dWJ
清提供此方式的代码片段

**Comment by MinG252** [comment]
https://developers.weixin.qq.com/s/YPmZiKm97vWR
@TallNutAlt

**Comment by MinG252** [comment]
找到解决办法了，弹窗打开后再渲染组件
