### ISSUE TITLE
输入框input-align问题

### ISSUE THREAD

**Issue by tielei60** [youzan/vant-weapp#602]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**描述一下问题**
[`van-field--${data.inputAlign}`]: data.inputAlign 
改为
[`van-field__input--${data.inputAlign}`]: data.inputAlign
导致input-align不起作用

**截图**
如果是 UI 问题，请提供具体截图

**环境**
 - 设备: 
 - 基础库版本: 
 - Vant Weapp 版本:0.3.2

**Comment by chenjiahan** [comment]
感谢反馈，会在下个版本修复

**Comment by chenjiahan** [comment]
已在 0.3.3 版本修复
