### ISSUE TITLE
vant-weapp cell在iphone7 plus上报错

### ISSUE THREAD

**Issue by sonofmagic** [youzan/vant-weapp#611]
问题:
使用cell在iphone7 plus上出现问题，本人使用了3台iphone7 plus，其中有一台出现了图中的问题，导致了cell样式失效了。

截图：
![image](https://user-images.githubusercontent.com/15621541/45803323-e9c2e300-bceb-11e8-90a1-6442e80c9ff0.png)

环境：
 - 设备: iphone7 plus
 - 基础库版本: 2.2.5
 - Vant Weapp 版本:0.3.2

**Comment by chenjiahan** [comment]
同个问题：https://github.com/youzan/vant-weapp/issues/594
