### ISSUE TITLE
Layout 布局 的offset 有问题

### ISSUE THREAD

**Issue by b110** [youzan/vant-weapp#614]
**问题**
Layout 布局 的offset 好像有问题，无法偏移

**截图**
![bug截图](http://blog.nobug666.com/img/vant-col.png)

**环境**
 - 设备: 模拟器和真机6sp
 - 基础库版本: 2.3.0
 - Vant Weapp 版本:0.3.2

**Comment by chenjiahan** [comment]
已在 0.3.3 版本修复
