### ISSUE TITLE
van-dialog弹出后，滑动蒙层，底下视图仍然可以动。

### ISSUE THREAD

**Issue by flyweights** [youzan/vant-weapp#617]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**描述一下问题**
van-dialog弹出后，滑动蒙层，底下视图仍然可以动。
我看了文档，文档没有属性控制。
但是我看官方的demo是没有这个问题的。
请问是不是我的用法不对呢？

**截图**
暂无

**环境**
 - 设备: 所有
 - 基础库版本: 最新
 - Vant Weapp 版本: 3.2

**Comment by chenjiahan** [comment]
0.3.3 版本在蒙层上增加了防止滚动穿透的处理，升级版本就可以咯

**Comment by flyweights** [comment]
是吗？我刚刚升级到3.3了，但是滑动蒙层，还是可以动。控制台每次滑动都会输出
```
VM67715:1 Component "miniprogram_npm/vant-weapp/overlay/index" does not have a method "true" to handle event "touchmove".
```
是不是我还需设置其它属性呢？

**Comment by chenjiahan** [comment]
@flyweights 在什么环境下可以滚动，我用 iphone 试是 ok 的，控制台的输出下次版本会优化下

**Comment by flyweights** [comment]
你这样一说，我突然就想到了，原来是我打开了下拉刷新，导致的问题，谢谢🙏。

**Comment by chenjiahan** [comment]
ok~ 那就没问题了，控制台输出会在 0.3.4 版本去掉
