### ISSUE TITLE
可能存在的版本控制错误问题

### ISSUE THREAD

**Issue by HeaventTso** [youzan/vant-weapp#623]
**描述一下问题**
参照 https://youzan.github.io/vant-weapp/#/quickstart 中的说明获取vant-weapp包，其中使用npm方法下载的源文件，使用"van-col"时，offset无法生效，查看package.json文件标注时0.3.3版本

使用git下载的则可以生效，但引入“van-tabs”等组件时则报foreach遍历错误，以及直接打开example时，项目报错

**环境**
 - 设备: win10 x64
 - 基础库版本: 2.3.0
 - Vant Weapp 版本:0.3.3

**Comment by webyangpei** [comment]
我也出现了这个错误，另：除了tabbar报上述错误之外，样式表现全无，只剩下文字和图标。
在tabs的表现上同样出现了部分错误。感觉报错有点多，急忙回退版本。静待。

**Comment by chenjiahan** [comment]
dev 上的代码刚才有点问题，已恢复

**Comment by chenjiahan** [comment]
@HeaventTso 看了下 0.3.3 版本 offset 应该是没问题的，可以再试下

**Comment by HeaventTso** [comment]
@chenjiahan “van-col“中的属性值offset已经正常了，谢谢啦
