### ISSUE TITLE
cell 组件，在 is-link 且 value 为空的情况下，箭头图标没有右对齐

### ISSUE THREAD

**Issue by mambahao** [youzan/vant-weapp#628]
cell 组件，在 is-link 且 value 为空的情况下，箭头图标没有右对齐

<img width="379" alt="screen shot 2018-09-23 at 2 06 29 am" src="https://user-images.githubusercontent.com/571962/45920382-ca87a980-bed5-11e8-96d9-368e8c802435.png">

```
<van-cell @tap="to" clickable center is-link>
  <view slot="icon" class="line-icon">
    <image mode="aspectFit" src="/assets/imgs/icon.png" />
  </view>
  <view slot="title" style="padding-left:20px;">
    <span>标题</span>
  </view>
</van-cell>
```

 - 设备:  iPhone
 - 基础库版本: 1.9
 - Vant Weapp 版本: 0.33

**Comment by tong233** [comment]
+1

**Comment by chenjiahan** [comment]
感谢反馈，目前用了 title 插槽且 value 为空的时候会有这个问题， 下个版本会修复

**Comment by chenjiahan** [comment]
已在 0.3.4 版本修复
