### ISSUE TITLE
cell 下边框消失

### ISSUE THREAD

**Issue by chaituan** [youzan/vant-weapp#633]
cell 加上is-link 或者 icon 属性 ，border 下边框就不显示了 ，跑官方demo 也是一样不显示。 应该不是我写法问题。

![_20180925001034](https://user-images.githubusercontent.com/26025563/45964120-7e647280-c057-11e8-98db-bb10fb8aab8f.png)

版本 0.3.3

**Comment by xxyuze** [comment]
![image](https://user-images.githubusercontent.com/17399581/45988550-18550b00-c0aa-11e8-9974-68cc5e2dcf65.png)
是的，0.3.2开始，就变成这样了

**Comment by rex-zsd** [comment]
是开发者工具上出现的问题吗？我在真机上看起来没问题的样子。

**Comment by chaituan** [comment]
> 是开发者工具上出现的问题吗？我在真机上看起来没问题的样子。

真机也有问题 你的版本是 0.3.3吗

**Comment by rex-zsd** [comment]
嗯 我看demo上是没问题。

**Comment by chaituan** [comment]
> 嗯 我看demo上是没问题。

我是没有通过npm 安装， 直接把dist目录放在项目中调用的，在本地跑demo 也没有下划线。 难道要npm安装才能正常吗？

**Comment by tong233** [comment]
我真机上没有问题

**Comment by chaituan** [comment]
@rex-zsd  帮忙看看 ，是我本地字体的问题吗？ 我只要把font-size设置到14px 就好了，如果是字体问题，应该怎么调整 。 开发者工具版本：1.02.1809111   基础库2.2.3，

![11111](https://user-images.githubusercontent.com/26025563/46020349-c6939b80-c110-11e8-9e42-11d36e0d3f27.jpg)

**Comment by zhaohuwei** [comment]
@chaituan 这个问题依然存在呀，怎么关闭了，莫非不是BUG？

**Comment by chaituan** [comment]
@zhaohuwei   我看他们都说没问题，也没人处理，估计应该是我的问题吧，所以我关掉了。 我这边处理的方式是把cell组件的.wxss换成 0.3.2版本的即可。

**Comment by zation** [comment]
我也有一样的问题，我的版本是 0.3.6

**Comment by zhaohuwei** [comment]
> @zhaohuwei 我看他们都说没问题，也没人处理，估计应该是我的问题吧，所以我关掉了。 我这边处理的方式是把cell组件的.wxss换成 0.3.2版本的即可。

对，0.3.3开始就有问题了
