### ISSUE TITLE
商品sku组件有在小程序端实现的计划么？

### ISSUE THREAD

**Issue by webyangpei** [youzan/vant-weapp#636]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**你需要的功能是？**
描述一下你需要的功能，用于解决什么问题

**你期望 API 是什么样的？**
描述一下你期望的 API 形式

**Comment by rex-zsd** [comment]
目前的[roadmap](https://github.com/youzan/vant-weapp/projects/2)内还没有计划。
