### ISSUE TITLE
search组件的bind:search事件event.detail值为null

### ISSUE THREAD

**Issue by xpsp312** [youzan/vant-weapp#638]
search组件的bind:search事件event.detail值为null

.wxml相关代码如下：
`<van-search placeholder="请输入搜索关键" bind:search="onSearch" bind:change="onSearchChange" />`
.js相关代码如下：
`onSearch(event){
    console.log(event.detail);
  }`
**环境**
 - 设备:微信安卓版 和 小程序开发工具模拟器结果一样
 - 基础库版本: 2.2.4
 - Vant Weapp 版本:0.3.3

**Comment by xpsp312** [comment]
我已经修复了，就是不知道这样改是否合理。具体如下：
修改search文件夹下的index.js中的第26行，添加一行代码如下：
`this.data.value=event.detail;`
完成后的效果如下：
`onChange(event) {
      this.data.value=event.detail;
      this.$emit('change', event.detail);
    }`

**Comment by chenjiahan** [comment]
已在 0.3.4 版本修复

**Comment by towry** [comment]
van-switch 的 evt.detail 也是 null 值。很奇怪，必须要指定 activeValue={true} 才行。
