### ISSUE TITLE
图片轮播功能

### ISSUE THREAD

**Issue by xpsp312** [youzan/vant-weapp#639]
**你需要的功能是？**
需要一个图片轮播组件，类似于电商类app首页轮播大图的效果

**你期望 API 是什么样的？**
可配置图片轮播形式（循环/非循环）
可配置图片尺寸
可配置图片轮播方式（手动/自动[间隔时间]）

请大神关注一下，谢谢！

**Comment by chenjiahan** [comment]
轮播功能可以直接使用微信原生的 swipe 组件
