### ISSUE TITLE
dialog无法获取open-type数据

### ISSUE THREAD

**Issue by mealayaria** [youzan/vant-weapp#643]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**描述一下问题**
描述一下你遇到的问题，包括复现方式、导致结果
dialog无法获取到open-type数据，在zanui-weapp中有返回 hasOpenDataPromise和openDataPromise，但是在vant-weapp中没有发现提供类似的api，文档中也没有详细说明，尝试在van-dialog中绑定getuserinfo事件无效

**截图**
如果是 UI 问题，请提供具体截图

**环境**
 - 设备: 
 - 基础库版本: 
 - Vant Weapp 版本:0.3.3

**Comment by chenjiahan** [comment]
已在 0.3.4 版本支持
