### ISSUE TITLE
popup组件会被map组件覆盖

### ISSUE THREAD

**Issue by xiaodel** [youzan/vant-weapp#646]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**描述一下问题**
描述一下你遇到的问题，包括复现方式、导致结果

**截图**
如果是 UI 问题，请提供具体截图

**环境**
 - 设备: 
 - 基础库版本: 
 - Vant Weapp 版本:

**Comment by xiaodel** [comment]
popup组件会被map组件覆盖，页面上有map组件时，地图会在最顶层,希望能用cover-view写

**Comment by chenjiahan** [comment]
目前不太好使用 cover-view 实现，可以在弹出 popup 的时候隐藏 map
