### ISSUE TITLE
Dialog 使用函数方式调用 点击按钮then里的内容不执行

### ISSUE THREAD

**Issue by SakuraDoramon** [youzan/vant-weapp#649]
**描述一下问题**
dialog使用函数的方式调用alert或者confirm时，点击确定或者取消按钮，弹框关闭，then和catch里面的代码不执行

**环境**
 - 设备: 微信开发者工具
 - 基础库版本: 1.0.0
 - Vant Weapp 版本:v 0.3.3

**Comment by chenjiahan** [comment]
0.3.3 里已经修复了这个问题，请确认你的版本
