### ISSUE TITLE
taro等react语法框架tabs组件循环 警告key值问题

### ISSUE THREAD

**Issue by xiao0502** [youzan/vant-weapp#652]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**描述一下问题**
描述一下你遇到的问题，包括复现方式、导致结果
`<van-tabs active={this.state.current} onclick={this.clickTabs}>
                    {
                        this.state.typeList.map((item, index) => {
                            return (
                                <van-tab key={index} title={item.title}>{item.title}</van-tab>
                            )
                        })
                    }
                </van-tabs>`

taro等react语法编写小程序集成vant-weapp时候，使用tabs组件循环数组时，警告key值问题，编译后的xxx.wxml，只有wx:for 没有wx:key

**希望**

希望能通过给tab传递key值，干掉警告。

**截图**
如果是 UI 问题，请提供具体截图

![image](https://user-images.githubusercontent.com/20298200/46125357-4fb6e980-c25b-11e8-9b77-6ada65b6bff6.png)

**环境**
 - 设备:  mac
 - 基础库版本: 2.3.0
 - Vant Weapp 版本: 0.3.3

**Comment by chenjiahan** [comment]
这个问题和组件库没有关系，建议去框架下提问
