### ISSUE TITLE
现在支持百度智能小程序吗？

### ISSUE THREAD

**Issue by robinma** [youzan/vant-weapp#663]
现在支持百度智能小程序吗？什么时候能够支持呢？

**Comment by rex-zsd** [comment]
目前不支持，近期没有支持计划呢

**Comment by bobiscool** [comment]
### 最近  移植了一个  欢迎 **star**  https://github.com/bobiscool/vantui-baiapp
![](https://github.com/bobiscool/vantui-baiapp/raw/master/baiapp.gif)
