### ISSUE TITLE
wepy下开发class名会重复出来如下图

### ISSUE THREAD

**Issue by 531431988** [youzan/vant-weapp#667]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**描述一下问题**
描述一下你遇到的问题，包括复现方式、导致结果

**截图**
如果是 UI 问题，请提供具体截图
![image](https://user-images.githubusercontent.com/8703951/46196875-bd861280-c33a-11e8-8ca3-1d627ce0def8.png)

**环境**
 - 设备: 
 - 基础库版本: 
 - Vant Weapp 版本:

**Comment by chenjiahan** [comment]
微信框架自己加的，没影响
