### ISSUE TITLE
Dialog中拒绝open-type时不进入error回调

### ISSUE THREAD

**Issue by mealayaria** [youzan/vant-weapp#670]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**描述一下问题**
描述一下你遇到的问题，包括复现方式、导致结果
在Dialog中使用open-type能力时，如果点击拒绝，不进入Dialog的bind：error回调

**截图**
如果是 UI 问题，请提供具体截图
以下是我的组件：
![image](https://user-images.githubusercontent.com/4319965/46230741-14700400-c39c-11e8-93ae-a5cfd3753996.png)
当我拒绝授权时，打印日志如下：
![image](https://user-images.githubusercontent.com/4319965/46230761-2782d400-c39c-11e8-9855-44d8945cc749.png)

**环境**
 - 设备: 
 - 基础库版本: 
 - Vant Weapp 版本: 0.3.4

**Comment by chenjiahan** [comment]
根据微信的文档，这里应该是只有 launchApp 会触发 error 事件，其他类型需要自己判断
![image](https://user-images.githubusercontent.com/7237365/46242317-e8836b80-c3f9-11e8-9001-bbc0e2102899.png)
