### ISSUE TITLE
van-tabs active 默认无效并报错

### ISSUE THREAD

**Issue by chaituan** [youzan/vant-weapp#671]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**描述一下问题**
1、升级3.4后，van-tabs 没有写active 应该默认为0，之前没写都正常，现在直接报错，一定要写active 才正常。
2、首次打开编辑器 van-tabs 会提示警告，并且无选中下划线，编译一下才能正常
Please considering using `SelectorQuery.in` to specify a proper one.

**截图**
![qq 20180929060639](https://user-images.githubusercontent.com/26025563/46235693-1c38a400-c3ae-11e8-818f-32ab5d7e00db.png)
![qq 20180929060525](https://user-images.githubusercontent.com/26025563/46235698-1f339480-c3ae-11e8-8a2b-fa1f3590f65e.png)

**环境**
 - 设备: 
 - 基础库版本: 2.3
 - Vant Weapp 版本:0.3.4

**Comment by chenjiahan** [comment]
下个版本会修复

**Comment by chenjiahan** [comment]
已在 0.3.5 版本修复
