### ISSUE TITLE
input或者textarea中加入placeholder-class设置样式

### ISSUE THREAD

**Issue by SakuraDoramon** [youzan/vant-weapp#672]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**你需要的功能是？**
描述一下你需要的功能，用于解决什么问题
input或者textarea中加入placeholder-class设置样式，看了源码组件的props里面有placeholder-class参数，但是实际设置了placeholder-class更改样式无效。

**你期望 API 是什么样的？**
描述一下你期望的 API 形式
为van-field组件增加placeholder-class参数设置

**Comment by chenjiahan** [comment]
由于自定义组件不支持类名透传，在 0.3.6 版本中新增了 placeholder-style 属性，可以用于定义样式

**Comment by ccqgithub** [comment]
@chenjiahan 不能透传的意思是？不能像`input-class`一样传一个`input-placeholder-class`么？
