### ISSUE TITLE
popup中添加内容border-radius 失效

### ISSUE THREAD

**Issue by xuluchun8** [youzan/vant-weapp#680]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**描述一下问题**
popup中添加的内容使用border-radius 无效

**截图**
![image](https://user-images.githubusercontent.com/26465186/46246046-68292e80-c42a-11e8-91c1-f10c2e0e1b3a.png)
**环境**
 - 设备:mac 
 - 基础库版本: 1.9.94
 - Vant Weapp 版本:0.3.5

**Comment by rex-zsd** [comment]
通过custom-class可以改呀。
核心代码能贴下不？看看哪里有问题。
