### ISSUE TITLE
zanui->vant-weapp 迁移文档

### ISSUE THREAD

**Issue by zuoRambo** [youzan/vant-weapp#681]
各位开发大大好，对于大量的zanui用户，既然[建议迁移](https://github.com/youzan/vant-weapp#%E8%BF%81%E7%A7%BB%E6%8C%87%E5%8D%97)，那么官方可否出个迁移指南呢？

**Comment by chenjiahan** [comment]
建议直接参照新版组件的文档进行迁移即可

**Comment by chenjiahan** [comment]
@zuoRambo 组件基本都有对应的新版组件，直接按照新版 api 用就可以的。
不知道你说的 class 写法指的是啥
