### ISSUE TITLE
在微信开发者工具中直接把vant-weapp/example目录添加进去，直接报错。

### ISSUE THREAD

**Issue by leixuesong** [youzan/vant-weapp#682]
**描述一下问题**
在微信开发者工具中直接把vant-weapp/example目录添加进去，直接报错。
具体操作：
git clone https://github.com/youzan/vant-weapp.git
cd vant-weapp
npm i
npm run dev

**截图**
![image](https://user-images.githubusercontent.com/6357885/46254998-7d559a00-c4ca-11e8-9914-90927cb91224.png)

**Comment by chenjiahan** [comment]
未复现这个问题，麻烦拉代码试下

**Comment by leixuesong** [comment]
路径好像是有问题，
![image](https://user-images.githubusercontent.com/6357885/46601885-2e8aae80-cb21-11e8-9a29-3999dcf5490d.png)应该是../inde.wxss

**Comment by leixuesong** [comment]
路径好像是有问题，
![image](https://user-images.githubusercontent.com/6357885/46601982-7a3d5800-cb21-11e8-9df4-3415a19332e6.png)
应该是../inde.wxss
@chenjiahan

**Comment by chenjiahan** [comment]
@leixuesong 麻烦拉下最新的代码再试

**Comment by leixuesong** [comment]
git clone https://github.com/youzan/vant-weapp.git 这个应该下载的是最新的代码啊 @chenjiahan

**Comment by leixuesong** [comment]
找到问题了是unix下和windows下的路径斜杆不一样 @chenjiahan
