### ISSUE TITLE
tree-select 组件在大屏幕手机上显示比例不合理

### ISSUE THREAD

**Issue by frontbear** [youzan/vant-weapp#687]
**描述一下问题**
用大屏幕手机测试这个组件

**截图**
![image](https://user-images.githubusercontent.com/35812002/46427924-33dca780-c775-11e8-8c8b-ce09b630e3f3.png)

**环境**
 - 设备: ios
 - 基础库版本: 2.0
 - Vant Weapp 版本: 0.3

**Comment by talentant** [comment]
如果能控制左侧nav的宽度会比较好 👍 ，个人建议

**Comment by chenjiahan** [comment]
在 0.3.8 版本优化了一下左侧的宽度，按屏幕百分比适配
