### ISSUE TITLE
tab组件设置border为false不生效

### ISSUE THREAD

**Issue by talentant** [youzan/vant-weapp#689]
**描述一下问题**
tab组件设置border为false，点击仍然会显示

**截图**
逻辑问题，非界面

**环境**
 - 设备: ios
 - 基础库版本: 2.0
 - Vant Weapp 版本: 0.36

**Comment by Gitsifu** [comment]
的确没有用，我把源码中一段代码删除就没有边框白线了，具体原因还不知道，感觉源码也没问题呀
![image](https://user-images.githubusercontent.com/23445650/46571190-37ee0c80-c9a3-11e8-9a7e-cea53dfed9f5.png)

这个是有白线的图
![image](https://user-images.githubusercontent.com/23445650/46571198-4a684600-c9a3-11e8-9751-323e188e009d.png)

删除那段代码后的效果
![image](https://user-images.githubusercontent.com/23445650/46571202-6a980500-c9a3-11e8-9c5b-5e19384a7d08.png)

**Comment by chenjiahan** [comment]
未复现这个问题，建议升级版本再试

**Comment by yegaoxiang** [comment]
line-width

**Comment by RandelYuan** [comment]
<van-tabs **:border="false"**></van-tabs>
