### ISSUE TITLE
Card 组件是否支持 lazy-load？

### ISSUE THREAD

**Issue by aiingstan** [youzan/vant-weapp#693]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**你需要的功能是？**
原生的 `image` 组件有一个 `lazy-load` 选项可以实现 `scroll-view` 视图中图片的懒加载，不知道 `Card` 组件中的图片部分是否支持该特性？

**你期望 API 是什么样的？**
如果目前没有按照懒加载来设定，给 `Card` 组件添加和小程序原生 `image` 组件一样的 `lazy-load` 选项

**Comment by chenjiahan** [comment]
已在 0.3.8 版本支持
