### ISSUE TITLE
taro支持相关

### ISSUE THREAD

**Issue by rex-zsd** [youzan/vant-weapp#703]
taro目前可支持小程序自定义组件，换言之可支持vant-weapp，只需要注意几个点

1. 使用的 `@tarojs/cli` 版本必须在 `1.1.0-beta.2` 以上，否则会报 `File not found: ../common/index.wxss` 错误。
2. taro会自动将样式中的 `px` 转为 `rpx`，造成vant-weapp组件样式异常，需修改 `config/index.js` 中weapp的postcss部分。
  ```js
  {
    ...
    weapp: {
      module: {
        postcss: {
          ...
          pxtransform: {
            selectorBlackList: [
              /^.van-.*?$/
            ]
          }
        }
      }
    }
  }
  ```
3. 由于taro内部的问题，目前使用vant-weapp时事件名与[文档](https://nervjs.github.io/taro/docs/event.html)中描述不一致，需使用传统的html事件语法。如 `onClick` -> `onclick`。

具体demo可参考[taro-vant-weapp-demo](https://github.com/rex-zsd/taro-vant-weapp-demo)

**Comment by lijicheng123** [comment]
对的，现在趋向于一端开发多端使用，taro目前不支持 relations 和 Behavior，可否考虑做一个没有这些特性的版本或者直接兼容这些

**Comment by Ariskywi** [comment]
赞！
vant很好，不过在taro中使用了vant-weapp后就不能转多端了。。
是否有计划出个转成taro的版本呢？

**Comment by dwyr** [comment]
vant很好，不过在taro中使用了vant-weapp后就不能转多端了。。
是否有计划出个转成taro的版本呢？

**Comment by ZhongMingKun** [comment]
taro可以通过调整编译配置进行兼容
https://taro-docs.jd.com/taro/docs/config-detail.html#copypatterns

**Comment by chenjiahan** [comment]
没有计划出转成 taro 的版本

**Comment by mihuartuanr** [comment]
虽然问题关闭了，我这里有个疑惑，目前组件可以展示，但组件的事件无法响应。绑定各种命名方式都试过了。

**Comment by edwards19900128** [comment]
请教下在taro中引用了vant weapp组件 如何修改样式
