### ISSUE TITLE
Add more available icons

### ISSUE THREAD

**Issue by dcalsky** [youzan/vant-weapp#708]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**你需要的功能是？**
描述一下你需要的功能，用于解决什么问题

While using Vant for development, I always feel that the current number of icons is not very sufficient. Could you add more icons instead of letting me go elsewhere to download and use them.

**你期望 API 是什么样的？**
描述一下你期望的 API 形式

**Comment by chenjiahan** [comment]
暂无计划添加更多图标
