### ISSUE TITLE
van-tabbar组件正确使用方法

### ISSUE THREAD

**Issue by jackie-cheng** [youzan/vant-weapp#711]
我看小程序官网是把tabbar放在根节点的json文件注册，只需注册一次。我如果使用van-tabbar，是不是首页四个tabbar都要引用一次van-tabbar组件，而且路由的也要手动双向绑定，我目前是这样做的，感觉特别繁琐，请教有没有简单的方法

**Comment by chenjiahan** [comment]
由于小程序的页面机制限制，目前只能这样去做喔
