### ISSUE TITLE
Area 省市区选择 bug

### ISSUE THREAD

**Issue by guodongzzzZ** [youzan/vant-weapp#721]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**描述一下问题**
第一次进入的时候 北京 是可选的，滑动之后 北京 不可选

**截图**
![wechatimg523](https://user-images.githubusercontent.com/32057073/46654029-48d49300-cbda-11e8-94fd-d186fc8767e4.jpeg)

**环境**
 - 设备: ios
 - 基础库版本: 
 - Vant Weapp 版本:  0.3.7

辛苦了， 期待回复。

**Comment by Chaslee4** [comment]
+1

**Comment by rex-zsd** [comment]
应该是[这里](https://github.com/youzan/vant-weapp/pull/661/files#diff-281709ee6243a1ddbac53fee7475050bL72)导致第一项无法选中。

**Comment by ldwonday** [comment]
demo小程序里面也有这个bug

**Comment by chenjiahan** [comment]
已在 0.4.0 版本修复

**Comment by Lcla** [comment]
第一项无法选择好像还是没解决喔
