### ISSUE TITLE
van-icon 在vantabbar中使用 报错

### ISSUE THREAD

**Issue by nan1010082085** [youzan/vant-weapp#726]
> van-tabbar中 使用 van-icon 有时会无法加载 但实际已经展示
> 单独使用van-icon 没有问题
```
VM710:2 Failed to load font https://img.yzcdn.cn/vant/vant-icon-76f274.ttf
net::ERR_CACHE_MISS 
```

**环境**
 - 设备:  微信开发者工具 + mpvue
 - Vant Weapp 版本: "vant-weapp": "^0.3.6",

**Comment by chenjiahan** [comment]
这个是微信开发者工具的问题，暂时木有解决方法

**Comment by Chris-jq** [comment]
我现在也遇到小程序中使用vant-weapp , 所有的icon都不显示, 但是真机调试却显示的,
目前也是报下面这两个错误:请问现在有解决方案了么
1. Failed to load font https://img.yzcdn.cn/vant/vant-icon-76f274.ttf
net::ERR_CACHE_MISS 

2.Failed to load font https://img.yzcdn.cn/vant/vant-icon-76f274.ttf
 net::ERR_TIMED_OUT
@chenjiahan

**Comment by chenqiuxia** [comment]
我也是遇到了这样的问题。
VM2156:5 Failed to load font https://img.yzcdn.cn/vant/vant-icon-ccd101.ttf
net::ERR_CACHE_MISS 
From server 118.112.13.22

关键是由于这个问题，我的有个页面打不开，我必须要把这个问题解决了之后才能打开剩下的页面。
好尴尬

**Comment by XinjianQi** [comment]
我也遇到了问题，woff2和ttf都加载不了，真机上面也不可以；现在下载下来转成base64，在mpvue下还是不行，求解！

**Comment by arlindar1030** [comment]
同样的问题，哎，mac下

**Comment by xiao-xiaozi** [comment]
请问有遇到tabbar在模拟器、预览时正常。真机调试却显示不了的问题吗
