### ISSUE TITLE
van-dialog 显示错位

### ISSUE THREAD

**Issue by Botision** [youzan/vant-weapp#727]
您好，我想请教一个问题：van-dialog 使用自定义内容时，在iphone6 手机上整个van-dialog显示错位。请您提供下宝贵的思路或者想法。谢谢。

![image](https://user-images.githubusercontent.com/8457857/46712555-3d3da680-cc84-11e8-95f6-ea91c17be546.png)

**环境**
 - 设备: iphone6
 - 基础库版本: 
 - Vant Weapp 版本: 0.3.8

**Comment by chenjiahan** [comment]
建议看下是否开启了微信开发者工具的『样式自动补全』

**Comment by Botision** [comment]
您好，已关闭微信开发者工具的『样式自动补全』，问题依旧还在哦。
