### ISSUE TITLE
van-cell 可否添加button.open-type微信开放能力

### ISSUE THREAD

**Issue by sanwv** [youzan/vant-weapp#730]
**你需要的功能是？**
van-cell实现小程序button的open-type功能（https://developers.weixin.qq.com/miniprogram/dev/component/button.html）

van-cell非常通用，例如反馈建议、联系客服这样的功能一般用微信的open-type来实现，如果用button的话样式风格又不好统一。
![image](https://user-images.githubusercontent.com/4526812/46719267-0c6b6a80-cca0-11e8-9672-695d02b6f6ac.png)

**你期望 API 是什么样的？**
```
<van-cell is-link open-type="contact" />
```

**Comment by vopdoo** [comment]
目前 我是在cell 里重写button 样式去做的
cell 能支持open-type 那就更佳了

**Comment by rex-zsd** [comment]
感觉在`cell`里增加`button`的功能不太合适？
