### ISSUE TITLE
<van-field> 聚焦后输入框和文字会发生抖动

### ISSUE THREAD

**Issue by bythy** [youzan/vant-weapp#732]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**描述一下问题**
聚焦后输入框和文字会发生抖动，调整van-cell中的line-height后有所改善

**截图**

**环境**
 - 设备: 
 - 基础库版本: 
 - Vant Weapp 版本: 最新版本

**Comment by rex-zsd** [comment]
小程序input的老问题了，官方社区里一大批反馈的，不是vant-weapp的问题
https://developers.weixin.qq.com/community/develop/doc/0000a805c0c918a09557688ae5ec00?highLine=input%2520%25E9%2597%25AA%25E7%2583%2581
https://developers.weixin.qq.com/community/develop/doc/00084cfe5100a03fed16d369c56800?highLine=input%2520%25E6%258A%2596%25E5%258A%25A8
https://developers.weixin.qq.com/community/develop/doc/0000a805c0c918a09557688ae5ec00?highLine=input%2520%25E9%2597%25AA%25E7%2583%2581

**Comment by Kennersky** [comment]
目前小程序还没得到修复么，还是一样会抖
