### ISSUE TITLE
组件报错

### ISSUE THREAD

**Issue by 392752749** [youzan/vant-weapp#734]
引入area组件和官方提供的area.json报错
thirdScriptError
Cannot read property 'county_list' of null; [Component] Property Observer Error @ static/vant/area/index#(anonymous)
TypeError: Cannot read property 'county_list' of null

**Comment by chenjiahan** [comment]
最新版中已修复这个问题

**Comment by xujianingwui** [comment]
vant-area 滑动的时候会报错，而且报错后就无法进行滑动，不是必然，滑动多了就会触发
Cannot read property 'undefined' of undefined; [Component] Event Handler Error @ vant-weapp/dist/area/index#onChange
TypeError: Cannot read property 'undefined' of undefined
