### ISSUE TITLE
search组件 show-action动态设置true，取消按钮延迟出现

### ISSUE THREAD

**Issue by xiao0502** [youzan/vant-weapp#735]
**描述一下问题**
search组件show-action初始值为false, 获得焦点，setState show-action为true，即显示取消按钮。
问题是：在真机上，show-action为true，取消按钮延迟出现，虽然setState异步，但是打印前后变化的时间很短。延迟是因为什么原因？

**Comment by chenjiahan** [comment]
应该是 setState 有通信时间延迟导致的，组件内部并没有对这个属性做特殊处理

**Comment by xiao0502** [comment]
@chenjiahan 我在setState之前打印毫秒，setState({}, () => {// 这里也打印毫秒})，相差很少。最后用tap时间设置获取焦点和显示取消按钮才解决。

**Comment by chenjiahan** [comment]
可以帮忙定位下原因哈
