### ISSUE TITLE
小程序里面怎么引入 toast的方法 ，在线等 比较急！

### ISSUE THREAD

**Issue by Xuhengfeng** [youzan/vant-weapp#737]
我按照官方文档引入toast组件的toast方法，
就报错 ：
![image](https://user-images.githubusercontent.com/24427486/46776872-180e6e00-cd40-11e8-8da1-c5073c35c569.png)

大致意思说我注册过多？

![image](https://user-images.githubusercontent.com/24427486/46776726-83a40b80-cd3f-11e8-8f5e-fc74c1bdf6ec.png)

**Comment by CurryHan** [comment]
`import Toast from  '../../vant-weapp/dist/toast/toast'`

**Comment by rex-zsd** [comment]
请看[文档](https://youzan.github.io/vant-weapp/#/toast)

**Comment by Xuhengfeng** [comment]
谢谢！  之前我这样直接导入 能被正常的使用，之后升级了一下微信开发工具之后，就报错，一直没找到原因，现在明白了

**Comment by Xuhengfeng** [comment]
> `import Toast from '../../vant-weapp/dist/toast/toast'`
谢谢，之前一直可以正常的使用，因为升级了微信开发工具后，才出现的报错

**Comment by bmxy860815** [comment]
> > `import Toast from '../../vant-weapp/dist/toast/toast'`
> > 谢谢，之前一直可以正常的使用，因为升级了微信开发工具后，才出现的报错

大佬，所以现在应该怎么引用？？

**Comment by Dazhenga** [comment]
用npm构建的话，是这么引入，去掉'dist' 不能按照官方文档 
import Toast from '@vant/weapp/toast/toast';
