### ISSUE TITLE
小程序Tab组件 card样式问题

### ISSUE THREAD

**Issue by vinokobe** [youzan/vant-weapp#740]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**描述一下问题**
小程序tab组件（card类型）下子类目多个的时候，滚动的时候样式有问题。

**截图**
![image](https://user-images.githubusercontent.com/21050503/46791839-8c630480-cd74-11e8-9359-74f19f547beb.png)

**环境**
 - 设备: 开发工具 真机也如此
 - 基础库版本: 1.9.94
 - Vant Weapp 版本:0.3.8

**Comment by chenjiahan** [comment]
已在 0.4.0 版本修复
