### ISSUE TITLE
如何在自定义组件中使用vant-weapp呢？

### ISSUE THREAD

**Issue by shallwe99** [youzan/vant-weapp#744]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**你需要的功能是？**
我有一个自定义table表格，希望在底部引用submitbar，可是一直提示找不到usingComponent里给出路径。

**你期望 API 是什么样的？**
希望能在自定义组件中使用vant-weapp，谢谢。

**Comment by water-gui** [comment]
这段时间在做一个小程序用到了vant-weapp,遇到同样需求,一开始有报错组件没有name,后面报错多不能有多个template,百度查了许久也没找到可用的相关帖子,后面自己尝试成功在自定义组件中成功引入icon并使用,但是其他引入vant组件均报错,一番尝试后发现在自定义组件中引入vant组件时引入目录只到该组件所在目录可使用,如import vanCard from "@/wxcomponents/vant/card",如果引入为import vanCard from "@/wxcomponents/vant/card/card.vue"则无法使用,但是icon组件却又可以详细到import uniIcons from "@/components/uni-icons/uni-icons.vue"也能正确使用
