### ISSUE TITLE
地区选择组件BUG

### ISSUE THREAD

**Issue by bao2314483** [youzan/vant-weapp#752]
**描述一下问题**
地区选择组件选择其他省份之后再选回北京市,二级和三级没有进行联动

**环境**
 - 设备: 
 - 基础库版本: 
 - Vant Weapp 版本:0.3.5

**Comment by chenjiahan** [comment]
同个问题 https://github.com/youzan/vant-weapp/issues/721

**Comment by 1429880240** [comment]
mpvue area省市区选择写一个出发地和一个目的地，第二次选择时候value找不到数据，只显示省列
![1](https://user-images.githubusercontent.com/35157291/49348860-e7fd9e80-f6e2-11e8-9021-a82bbfd3a4cc.png)
![2](https://user-images.githubusercontent.com/35157291/49348870-efbd4300-f6e2-11e8-8abb-2312a82a6688.png)
![3](https://user-images.githubusercontent.com/35157291/49348877-f481f700-f6e2-11e8-8e67-f800b1a4ede9.png)
