### ISSUE TITLE
Tabbar组件使用后右侧的滚动条可以一直滚到页底，而不是组件的上方。

### ISSUE THREAD

**Issue by Fisher-Joe** [youzan/vant-weapp#754]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**描述一下问题**
Tabbar组件使用后右侧的滚动条可以一直滚到页底，而不是组件的上方。

**截图**
如果是 UI 问题，请提供具体截图
![image](https://user-images.githubusercontent.com/12068896/46900896-77a18080-cedc-11e8-9a66-82c6ec9ad88a.png)

**环境**
 - 设备: iPhone, 模拟器
 - 基础库版本: 2.2.2
 - Vant Weapp 版本:0.3.8

**Comment by Fisher-Joe** [comment]
我使用z-index时发现不能在data对像中使用。

**Comment by chenjiahan** [comment]
第一个问题和组件无关，可以使用 scroll-view
第二个问题描述不清
