### ISSUE TITLE
dialog async-close怎么控制按钮loading

### ISSUE THREAD

**Issue by tong233** [youzan/vant-weapp#755]
async-close下怎么关闭按钮loading，或者加个属性点击按钮不自动显示loading。应用场景：比如密码输错了，需要重新登录。

**Comment by Fyerl** [comment]
注意后续发版，组件调用可通过 this.selectComponent 获取 dialog 实例调 stopLoading 方法，函数调用可通过 Dialog.stopLoading 方法

**Comment by chenjiahan** [comment]
已在 0.4.2 版本支持
