### ISSUE TITLE
van-field的type设为textarea时，显示层级比popup组件还高

### ISSUE THREAD

**Issue by wishinlife** [youzan/vant-weapp#756]
**描述**
表单上有van-field，type设为textarea时，当用van-popup加van-area时，field的文字部分会显示在van-area之上，造成显示错乱。

**环境**
 - 设备: 安卓
 - 基础库版本: 2.2.3
 - Vant Weapp 版本:0.3.6

**Comment by Fyerl** [comment]
van-popup 支持设置 z-index 属性

**Comment by wishinlife** [comment]
> van-popup 支持设置 z-index 属性

设置了popup的z-index也不行，在微信小程序开发工具上显示正常，在手机上预览就不行。
微信版本：6.6.7；
系统：安卓7.0

**Comment by chenjiahan** [comment]
textarea 是原生组件，层级是最高的，可以在弹出 popup 的时候隐藏 textarea 组件
参见 https://developers.weixin.qq.com/miniprogram/dev/component/native-component.html

**Comment by hooray** [comment]
![QQ图片20181222164158.png](https://i.loli.net/2018/12/22/5c1df8edd02d3.png)
那看来面对这个情况，产品的特性都要修改了，本来头部的日期选择导航是fixed在顶部的，现在只能取消fixed属性了
