### ISSUE TITLE
支持组件自动化注册

### ISSUE THREAD

**Issue by ivenxu** [youzan/vant-weapp#758]
目前的问题：

在当前版本中，我们需要配置一个json文件（通常是main.json），详情请参见: https://github.com/youzan/vant-weapp#%E4%BD%BF%E7%94%A8%E7%BB%84%E4%BB%B6

`{
  "usingComponents": {
    "van-button": "/path/to/vant-weapp/dist/button/index"
  }
}`
这里需要指定这个组件具体的路径，文档暗示，需要vant-weapp在小程序目录中而不是node_modules中。

**你需要的功能是？**
基础组件的自动化注册。如https://cn.vuejs.org/v2/guide/components-registration.html#%E5%9F%BA%E7%A1%80%E7%BB%84%E4%BB%B6%E7%9A%84%E8%87%AA%E5%8A%A8%E5%8C%96%E5%85%A8%E5%B1%80%E6%B3%A8%E5%86%8C

**你期望 API 是什么样的？**
类似于Vue的基础组件自动化注册

PS: 这个是一个wishlist的功能，这个坑很可能微信小程序挖的。因为https://developers.weixin.qq.com/miniprogram/dev/framework/custom-component/ 小程序文档明确要求有个json文件来注册。

**Comment by chenjiahan** [comment]
小程序官方暂不支持这种方式注册，只能配置 json 文件

**Comment by chenjiahan** [comment]
可以自动生成的，在构建工具里做
