### ISSUE TITLE
van-nav-bar 的left-click right-click 事件点击无效

### ISSUE THREAD

**Issue by webyangpei** [youzan/vant-weapp#764]
问题：van-nav-bar 的left-click right-click 事件点击无效
UI表现： 就是点击没反应

**环境**
 - 设备: 微信小程序客户端开发工具 
 - 框架：mpvue
 - 基础库版本: 2.3.0
 - Vant Weapp 版本:0.4.0

这样的方式是不可以的，
![image](https://user-images.githubusercontent.com/24697986/46989394-87fd6980-d12f-11e8-9a82-e68a7b0b471e.png)

暂时是下边这个方式解决的
![image](https://user-images.githubusercontent.com/24697986/46989403-921f6800-d12f-11e8-83cd-e8e469cc8942.png)

**Comment by rex-zsd** [comment]
尝试了一下的确不触发。
发现原生组件抛出的事件名如果中间有`-`，mpvue是不会触发的，但是事件名带`-`是符合vue和小程序的规范的。
可以去[mpvue](https://github.com/Meituan-Dianping/mpvue/issues)那里提issue。

**Comment by webyangpei** [comment]
好的，🙏

**Comment by dxwb** [comment]
有结果了吗，今天我用tree-select这个组件也遇到这个问题。我暂时是用小程序原生自定义组件嵌套一层，然后改个事件名称解决的，不知道有没有更好的方法，也不知道这样做会有什么负面影响

**Comment by jasmine-song** [comment]
> 有结果了吗，今天我用tree-select这个组件也遇到这个问题。我暂时是用小程序原生自定义组件嵌套一层，然后改个事件名称解决的，不知道有没有更好的方法，也不知道这样做会有什么负面影响

我改了两个地方

**Comment by jasmine-song** [comment]
> 有结果了吗，今天我用tree-select这个组件也遇到这个问题。我暂时是用小程序原生自定义组件嵌套一层，然后改个事件名称解决的，不知道有没有更好的方法，也不知道这样做会有什么负面影响

我改了两个地方 

![image](https://user-images.githubusercontent.com/44150070/51526108-99f85200-1e6c-11e9-951e-96ed693f294d.png)

**Comment by jasmine-song** [comment]
> > 有结果了吗，今天我用tree-select这个组件也遇到这个问题。我暂时是用小程序原生自定义组件嵌套一层，然后改个事件名称解决的，不知道有没有更好的方法，也不知道这样做会有什么负面影响
> 

我改了两个地方

 ![image](https://user-images.githubusercontent.com/44150070/51526108-99f85200-1e6c-11e9-951e-96ed693f294d.png)
组件封装的发射事件方法名跟文档上的不一样 
![image](https://user-images.githubusercontent.com/44150070/51526238-e17ede00-1e6c-11e9-9b2b-7f345f9d5fa4.png)
