### ISSUE TITLE
area.js的海外城市code错误

### ISSUE THREAD

**Issue by mynameismaosheng** [youzan/vant-weapp#765]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**描述一下问题**
vant的省市区选择
选择海外的 未有国家提供选择,

**原因**
美国韩国新加坡的代码前三位应是900
东西出不来开发者会比较疑惑, 建议改成可以出来的样子.

**环境**
 - 设备: 小程序
 - 基础库版本: 2.3.0
 - Vant Weapp 版本: 4.0

**Comment by rex-zsd** [comment]
可以提供一下传入的`area-list`吗？
简单尝试了一下复现不出来。

**Comment by mynameismaosheng** [comment]
> 可以提供一下传入的`area-list`吗？
> 简单尝试了一下复现不出来。

我用的项目里面的area.js啊. 
省份的最后有个海外是900000
市区的最后几个  没有按照格式来

area-list 使用的这个文件 https://github.com/youzan/vant/blob/dev/packages/area/demo/area.js

**Comment by chenjiahan** [comment]
已在 0.4.2 版本支持
