### ISSUE TITLE
nav-bar 组件  title-class 不生效 （已多次试验）

### ISSUE THREAD

**Issue by webyangpei** [youzan/vant-weapp#769]
使用方式：
![image](https://user-images.githubusercontent.com/24697986/47003066-fd356280-d160-11e8-8fc3-08b6ba3e1385.png)
效果：
![image](https://user-images.githubusercontent.com/24697986/47003267-6e751580-d161-11e8-9b56-a7ab64020476.png)

表现：
  样式类名称上去了，但是并没有应用到元素上
**环境**
 - 设备: 微信开发这客户端
 - 基础库版本: 2.3.0
 - Vant Weapp 版本: 0.4.0
 - 框架：mpvue

**Comment by rex-zsd** [comment]
这个是由于mpvue目前对原生组件的外部样式类支持有问题。
你把组件样式的scoped去掉后样式就会正常应用上去。

**Comment by webyangpei** [comment]
灰常感谢！！！
