### ISSUE TITLE
common/index.wxss经过编译后丢失

### ISSUE THREAD

**Issue by xiao0502** [youzan/vant-weapp#772]
**描述一下问题**
执行开发命令 `npm run dev:weapp` 后，common/index.wxss没有编译到dist具体目录里面，而所有的组件样式都引用了这个文件，导致报错

**环境**
 - 设备: 
 - 基础库版本: 
 - Vant Weapp 版本:

**Comment by rex-zsd** [comment]
请问这个问题现在解决了吗？

**Comment by javascripet** [comment]
我也是这样..
thirdScriptError 
 sdk uncaught third Error 
 module "src/_zan2/icon/index.js" is not defined 
 Error: module "src/_zan2/icon/index.js" is not defined
    at require (http://127.0.0.1:37200/appservice/__dev__/WAService.js:19:7163)
    at <anonymous>:175:7

**Comment by xiao0502** [comment]
@rex-zsd 没有，我每次`npm run dev:weapp`后，都要把common里面的index.wxsscopy到dist对应的目录才行

**Comment by rex-zsd** [comment]
@xiao0502 使用的是taro框架嘛？

**Comment by xiao0502** [comment]
@rex-zsd 感谢，版本问题，已解决
