### ISSUE TITLE
tab增加一个String类型的参数value

### ISSUE THREAD

**Issue by liangjiange** [youzan/vant-weapp#773]
**你需要的功能是？**
tab增加一个String类型的参数value

**你期望 API 是什么样的？**
希望在tab中增加一个String类型的参数value，这样可以做一个value跟title的键值对，当碰到需要根据value来判断tab切换后的处理逻辑时，可以灵活处理

**Comment by rex-zsd** [comment]
`change`事件有返回对应tab的`index`，用来处理切换后的逻辑应该是足够了，没有必要增加`value`吧。

**Comment by liangjiange** [comment]
> `change`事件有返回对应tab的`index`，用来处理切换后的逻辑应该是足够了，没有必要增加`value`吧。

比如同级的tab1，tab2，tab3，tab4，希望tab1,tab2切换后展示A类内容，tab3,tab4切换后展示B类内容，这种场景还是存在的，如果只能通过index判断的话，代码实现逻辑上会变复杂，所以增加跟index一样的可取值的自定义字符串，组件会更加灵活吧
