### ISSUE TITLE
field 输入框点击清除按钮如何实现不失去焦点？

### ISSUE THREAD

**Issue by heuuLZP** [youzan/vant-weapp#774]
**问题**
field组件，当点击清除按钮后，键盘未收起，输入框仍然是聚焦状态。请问你们是如何实现这个功能的？？

我查看了mintUI , 也基于小程序input组件封装了带清除按钮功能的组件，正常逻辑是当点击清除按钮后，输入框会失去焦点，键盘会收起。

而在vant-weapp 的field组件的代码中打断点调试，实际上你们的field组件，在点击清除按钮时，事件流程为：onClear   ->  onBlur  -> onFocus 。所以实际上也是会失去焦点，只是又自动获取焦点了，但是在field源码中没找到自动获取焦点的代码，也不明白，你们是如何做到，失去焦点后，键盘未收起，望解答。

**尝试**
如果我在onClear函数里面让input聚焦，就会造成，键盘先收起再弹出的过程，而你们的键盘是一直在的。

**截图**
无

**环境**
 - 设备: ios、android、微信开发者工具

**Comment by chenjiahan** [comment]
看源码就知道咯，点击事件绑定使用 bind:touchstart 即可，如果使用 tap 会导致输入框失去焦点

**Comment by heuuLZP** [comment]
@chenjiahan 好的，谢谢你的回复，原来的触发时机不一样，tap在touchstart之后。

**Comment by edwards19900128** [comment]
> 看源码就知道咯，点击事件绑定使用 bind:touchstart 即可，如果使用 tap 会导致输入框失去焦点
学习了...不愧是小程序端No1的UI库...
是不是可以这样理解touchstart是不会focus到其他元素的一个事件。。input里一直被focus所以键盘会一直在。

**Comment by edwards19900128** [comment]
> @chenjiahan 好的，谢谢你的回复，原来是触发时机不一样，tap在touchstart之后。
今天也有一样的困扰。。看到楼主的issue 解决心头大好。。点个赞

**Comment by heuuLZP** [comment]
@edwards19900128  我的理解是：首先要明白，移动端 click 事件会有300ms 的延时，先看vant-weapp 的field组件，它通过 touchstart 绑定 onClear 事件，所以当你点击清除按钮时，会先触发 onClear 事件，300ms 之后才会触发 click 事件，在这个 300ms 时间内，value 被清除，清除按钮也隐藏了，input 也失去焦点了，但是在 300ms 结束，click 触发时，因为已经没有清除按钮了，所以click 直接作用到 input 的 focus 事件，所以并不是你说的 input 一直 focus ，我猜测应该是 input 失去焦点时，浏览器没有立即收起键盘，而是做了类似防抖的优化，以最后一刻的状态为准，不知道我的猜测对不对 @chenjiahan

**Comment by zoel070** [comment]
> @edwards19900128 我的理解是：首先要明白，移动端 click 事件会有300ms 的延时，先看vant-weapp 的field组件，它通过 touchstart 绑定 onClear 事件，所以当你点击清除按钮时，会先触发 onClear 事件，300ms 之后才会触发 click 事件，在这个 300ms 时间内，value 被清除，清除按钮也隐藏了，input 也失去焦点了，但是在 300ms 结束，click 触发时，因为已经没有清除按钮了，所以click 直接作用到 input 的 focus 事件，所以并不是你说的 input 一直 focus ，我猜测应该是 input 失去焦点时，浏览器没有立即收起键盘，而是做了类似防抖的优化，以最后一刻的状态为准，不知道我的猜测对不对 @chenjiahan

源码里是catch:touchstart，而不是bind:touchstart，用bind冒泡后可能会失效。同时，一开始就给input设置flex：1使其延长很有必要。点击时，在touchstart阶段让delete icon消失，接着触发tap，此时的tap落到了延长后的input，使得焦点仍然落在了input上。但也不是每次都能成功的，如果ui渲染慢，input没有及时延长，那焦点就无法顺利落到input上，导致失去焦点。ui 渲染和刷新率有关，不会每次事件循环后都会渲染，这是个问题。

**Comment by heuuLZP** [comment]
@zoel070 没想到这个issue还有人关注，已经5年了

5年前 0.x 版本确实是 bind:touchstart(看下图作者的回复，或者去翻下0.x的源码)，你看到的 catch:touchstart 是新版本的

![image](https://github.com/youzan/vant-weapp/assets/18410118/8e190f78-0949-4086-acc1-b5f1b237b9d2)
