### ISSUE TITLE
input-align 不生效

### ISSUE THREAD

**Issue by DestinyHunter** [youzan/vant-weapp#780]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**描述一下问题**
input-align center 不生效 

**截图**
如果是 UI 问题，请提供具体截图
![image](https://user-images.githubusercontent.com/20897838/47129644-b2365f00-d2c8-11e8-9f65-3b66153440d6.png)
![image](https://user-images.githubusercontent.com/20897838/47129660-c24e3e80-d2c8-11e8-8a17-59123a550bff.png)

**环境**
 - 设备: win10
 - 基础库版本:  2.3.0
 - Vant Weapp 版本: 0.4.0

**Comment by DestinyHunter** [comment]
![image](https://user-images.githubusercontent.com/20897838/47129727-1a854080-d2c9-11e8-9ffa-cfcad3cc5bb2.png)
类名重复.并且没有定义

**Comment by chenjiahan** [comment]
类名重复是编辑器的问题，inputAlign 属性下个版本会修复

**Comment by chenjiahan** [comment]
已在 0.4.2 版本修复
