### ISSUE TITLE
van-button不能设置宽度和高度吗？

### ISSUE THREAD

**Issue by tsplaycool** [youzan/vant-weapp#785]
新手一个，请问有赞的大佬，怎么设置宽度和高度呢？我设置了都没用呢？

**Comment by mynameismaosheng** [comment]
> 新手一个，请问有赞的大佬，怎么设置宽度和高度呢？我设置了都没用呢？

代码贴一下, 要看是否应用到那个btn的.

**Comment by rex-zsd** [comment]
可以通过`custom-class`来设置，可以看下[文档](https://youzan.github.io/vant-weapp/#/button)，
注意加`!important`。

**Comment by flyzebraV** [comment]
需要设置block才有效
<view class="buttom-btn">
    <van-button type="default" block style="width: 200rpx;">取消</van-button>
    <van-button type="primary" block style="width: 400rpx;margin-left: 20rpx;margin-right: 20rpx;" color="#7232dd">保存</van-button>
 </view>

**Comment by mxinglee** [comment]
> 需要设置block才有效 <view class="buttom-btn">     <van-button type="default" block style="width: 200rpx;">取消     <van-button type="primary" block style="width: 400rpx;margin-left: 20rpx;margin-right: 20rpx;" color="#7232dd">保存

按照这种方式也没用，宽高改不了
