### ISSUE TITLE
button 组件增加 bind:catch

### ISSUE THREAD

**Issue by mynameismaosheng** [youzan/vant-weapp#797]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**你需要的功能是？**
button放在一个大的点击热区内
点击button不执行大热区的点击事件

**你期望 API 是什么样的？**
希望button可以有一个bind:catch

**Comment by rex-zsd** [comment]
这个应该不需要增加新的API，直接在`button`组件上`catch:tap`就可以了。
类似这样：
```
<van-button type="primary" catch:tap="onCatch" bind:click="onClick">主要按钮</van-button>
```
