### ISSUE TITLE
Toast

### ISSUE THREAD

**Issue by wdxia** [youzan/vant-weapp#799]
**Toast引入失效问题**
在项目中引入Toast失效，但是重新搞一个空模板就可以用，失效报错ctx.selectComponent is not a function;
`import Toast from "../../components/dist/toast/toast.js";`
`"van-toast": "../../components/dist/toast/index"`
`<van-toast id="van-toast" />`

**环境**
 - 设备: 模拟器 
 - 基础库版本: 2.3.0 
 - Vant Weapp 版本:0.4.2

**Comment by rex-zsd** [comment]
请问`Toast`方法是如何调用的呢？

**Comment by wdxia** [comment]
直接调用 `Toast('hello,world!')`

**Comment by rex-zsd** [comment]
没复现 可以提供一个小程序代码片段不？

**Comment by Robinbiao** [comment]
请问下这种引用后， 怎么通过methods里面方法Js触发？？

**Comment by Robinbiao** [comment]
usingComponents: {
        'van-toast': '../../components/vant/toast'
      }

**Comment by rex-zsd** [comment]
@Robinbiao 使用方法请看[文档](https://youzan.github.io/vant-weapp/#/toast)

**Comment by peachQAQ** [comment]
路径是没有错的，button和col row都能正确引用。
</br>
//json文件
```
{
  "usingComponents": {
    "van-toast": "../../miniprogram_npm/vant-weapp/toast/index",
    "van-button": "../../miniprogram_npm/vant-weapp/button/index",
    "van-row": "../../miniprogram_npm/vant-weapp/row/index",
    "van-col": "../../miniprogram_npm/vant-weapp/col/index"
  }
}
```
//wxml页面
```
<text>页面</text>
<van-button bind:click="showToast"type="default">显示</van-button>
<van-toast id="van-toast" />
```
//js页面
```
import Toast from '../../miniprogram_npm/vant-weapp/toast/index';

Page({
......
showToast() {
    Toast("hello");
  }
})
```


报错：
```
(0 , _index2.default) is not a function; [Component] Event Listener Error @ miniprogram_npm/vant-weapp/button/index#(anonymous)
TypeError: (0 , _index2.default) is not a function
    at H.showToast (http://127.0.0.1:11735/appservice/pages/page_admin/page_admin.js:57:25)
    at H.A.u.(anonymous function).(anonymous function).u.addListener.capture (http://127.0.0.1:11735/appservice/__dev__/WAService.js:1:914435)
    at r.safeCallback (http://127.0.0.1:11735/appservice/__dev__/WAService.js:1:758737)
    at r.call (http://127.0.0.1:11735/appservice/__dev__/WAService.js:1:758630)
    at n (http://127.0.0.1:11735/appservice/__dev__/WAService.js:1:761627)
    at http://127.0.0.1:11735/appservice/__dev__/WAService.js:1:762209
    at p (http://127.0.0.1:11735/appservice/__dev__/WAService.js:1:761174)
    at Function.c.dispatchEvent (http://127.0.0.1:11735/appservice/__dev__/WAService.js:1:762106)
    at Function.c.triggerEvent (http://127.0.0.1:11735/appservice/__dev__/WAService.js:1:762309)
    at n.w.triggerEvent (http://127.0.0.1:11735/appservice/__dev__/WAService.js:1:838633)
```
估计指向的是showToast( ) 内的 Toast('hello')

**Comment by hungryzzz** [comment]
> 路径是没有错的，button和col row都能正确引用。
> 
> 
> //json文件
> 
> ```
> {
>   "usingComponents": {
>     "van-toast": "../../miniprogram_npm/vant-weapp/toast/index",
>     "van-button": "../../miniprogram_npm/vant-weapp/button/index",
>     "van-row": "../../miniprogram_npm/vant-weapp/row/index",
>     "van-col": "../../miniprogram_npm/vant-weapp/col/index"
>   }
> }
> ```
> 
> //wxml页面
> 
> ```
> <text>页面</text>
> <van-button bind:click="showToast"type="default">显示</van-button>
> <van-toast id="van-toast" />
> ```
> 
> //js页面
> 
> ```
> import Toast from '../../miniprogram_npm/vant-weapp/toast/index';
> 
> Page({
> ......
> showToast() {
>     Toast("hello");
>   }
> })
> ```
> 
> 报错：
> 
> ```
> (0 , _index2.default) is not a function; [Component] Event Listener Error @ miniprogram_npm/vant-weapp/button/index#(anonymous)
> TypeError: (0 , _index2.default) is not a function
>     at H.showToast (http://127.0.0.1:11735/appservice/pages/page_admin/page_admin.js:57:25)
>     at H.A.u.(anonymous function).(anonymous function).u.addListener.capture (http://127.0.0.1:11735/appservice/__dev__/WAService.js:1:914435)
>     at r.safeCallback (http://127.0.0.1:11735/appservice/__dev__/WAService.js:1:758737)
>     at r.call (http://127.0.0.1:11735/appservice/__dev__/WAService.js:1:758630)
>     at n (http://127.0.0.1:11735/appservice/__dev__/WAService.js:1:761627)
>     at http://127.0.0.1:11735/appservice/__dev__/WAService.js:1:762209
>     at p (http://127.0.0.1:11735/appservice/__dev__/WAService.js:1:761174)
>     at Function.c.dispatchEvent (http://127.0.0.1:11735/appservice/__dev__/WAService.js:1:762106)
>     at Function.c.triggerEvent (http://127.0.0.1:11735/appservice/__dev__/WAService.js:1:762309)
>     at n.w.triggerEvent (http://127.0.0.1:11735/appservice/__dev__/WAService.js:1:838633)
> ```
> 
> 估计指向的是showToast( ) 内的 Toast('hello')

能问一下这个问题解决了吗？如何解决的呢？
