### ISSUE TITLE
小程序组件 Stepper 步进器 设置disabled失效

### ISSUE THREAD

**Issue by Nana-Cti** [youzan/vant-weapp#801]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**Stepper 步进器 设置disabled无法禁用**
设置为disabled之后,样式有改变,但是input里面的数字还是会因为点击发生变化

**截图**
于是自己加了两个if
![snipaste_20181023_161946](https://user-images.githubusercontent.com/39090154/47346379-9fb09100-d6df-11e8-9bb8-14d018021e0f.png)

**环境**
 - 设备: iPhone6
 - 基础库版本: 
 - Vant Weapp 版本:0.4.2

**Comment by rex-zsd** [comment]
我尝试了一下没有复现，请问使用demo小程序可以复现吗？

**Comment by chenjiahan** [comment]
参见 https://github.com/youzan/vant-weapp/issues/796
