### ISSUE TITLE
popup弹出层bug

### ISSUE THREAD

**Issue by ljybill** [youzan/vant-weapp#802]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**描述一下问题**
复现步骤：
1、扫码readme中的演示小程序二维码，打开小程序
2、找到popup项，点击进入
3、点击“弹出popup”按钮，出现弹层，然后关闭
4、重复步骤3多次（3-5次）
5、点击除“弹出popup”按钮以外的按钮，发现效果和预期不一致

**截图**
暂无截图

**环境**
 - 设备: Android 8.1 OnePlus 5T
 - 基础库版本: 最新版
 - Vant Weapp 版本: readme预览二维码版本

**Comment by rex-zsd** [comment]
请问是出现了什么不符合预期的问题呢？

**Comment by ljybill** [comment]
popup页面一共有4个按钮，弹出Popup 底部弹出 顶部弹出 右侧弹出，各自效果是不同的，但是如果多次点击弹出popup后，再点击其他按钮，出现的效果是 弹出Popup 对应的效果

**Comment by rex-zsd** [comment]
这个其实是demo的问题，`popup`的demo上使用取反的方法来设置`popup`的显示。这样快速连点的时候`popup`会马上关闭再打开。`popup`组件本身应该是没问题的哈。
