### ISSUE TITLE
添加SwipeCell 滑动单元格

### ISSUE THREAD

**Issue by Gitsifu** [youzan/vant-weapp#803]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**你需要的功能是？**
描述一下你需要的功能，用于解决什么问题

**你期望 API 是什么样的？**
描述一下你期望的 API 形式
和vant-ui里的一样就行

**Comment by rex-zsd** [comment]
可以关注一下[roadmap](https://github.com/youzan/vant-weapp/projects/2)  
SwipeCell目前在10月计划里
