### ISSUE TITLE
mpvue 用v-model不能双向绑定

### ISSUE THREAD

**Issue by dhj2020** [youzan/vant-weapp#806]
<van-cell-group>
          <van-field
            label="手机号"
            type="number"
            placeholder="请输入登录手机号"
            border="false"
            name="mobile" 
            v-model="mobile"
          />

**Comment by dhj2020** [comment]
v-model和:value都不能双向绑定

![01](https://user-images.githubusercontent.com/11954087/47419792-86771580-d7af-11e8-959c-10424a7c9141.jpg)
![02](https://user-images.githubusercontent.com/11954087/47419793-86771580-d7af-11e8-8a2b-5e9e5b1f6569.jpg)

**Comment by rex-zsd** [comment]
mpvue不支持原生组件的双向绑定，参考 [#444](https://github.com/youzan/vant-weapp/issues/444#issuecomment-430210845)，请向mpvue[提issue](https://github.com/Meituan-Dianping/mpvue/issues/new/choose)
