### ISSUE TITLE
wepy框架  怎么引用toast类组件

### ISSUE THREAD

**Issue by Robinbiao** [youzan/vant-weapp#809]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**你需要的功能是？**
wepy框架  怎么引用toast类组件

**你期望 API 是什么样的？**
loading类组件可以使用，请问下toast这类js触发组件在wepy框架怎么用？

**Comment by rex-zsd** [comment]
issue是用来反馈bug或者提功能需求的，使用姿势的疑问可以去下面专门开的issue #413 处讨论。
