### ISSUE TITLE
样式问题

### ISSUE THREAD

**Issue by typist** [youzan/vant-weapp#812]
1. tabbar icon 跟文本没有垂直居中。
请添加样式：.van-tabbar{align-items: center;}

2.为什么不用 rpx 而用 px??
**截图**
如果是 UI 问题，请提供具体截图

 - 设备: iphone 7P
 - 基础库版本: 
 - Vant Weapp 版本: 最新版

**Comment by rex-zsd** [comment]
没有居中是指？看demo并没有这个问题

**Comment by typist** [comment]
![img_5642](https://user-images.githubusercontent.com/3132857/47538609-e6c89d00-d8fe-11e8-9167-cdf62de4d650.PNG)

**Comment by typist** [comment]
> 没有居中是指？看demo并没有这个问题

图上
