### ISSUE TITLE
界面有循环列表时，真机调试有bug

### ISSUE THREAD

**Issue by pipadawang** [youzan/vant-weapp#813]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**描述一下问题**
当在有循环列表的界面中引入自定义组件时，电脑端可以正常显示，但是真机调试不显示数据，若在调试界面更改数据，就可以正常显示

**截图**
[截图](http://lc-0b2nocdk.cn-n1.lcfile.com/c5d3a3bc8bf6e7324705.jpg)

**环境**
 - 设备: 小米mix2s
 - 基础库版本: 2.3.2
 - Vant Weapp 版本:0.4.2

**Comment by rex-zsd** [comment]
请提供一下使用的代码
