### ISSUE TITLE
小程序组件缺少 uploader 图片上传组件

### ISSUE THREAD

**Issue by hecity** [youzan/vant-weapp#821]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**你需要的功能是？**
小程序组件缺少 uploader 图片上传组件，以致于无法使用 Vant-UI 完全代替 WeUI

**你期望 API 是什么样的？**
描述一下你期望的 API 形式

**Comment by hecity** [comment]
自己做了一个，好像也不复杂，两下就搞好了。

**Comment by rex-zsd** [comment]
嗯，图片上传微信有提供完善的API，不太需要vant提供这样的能力。
