### ISSUE TITLE
TreeSelect 与小程序的下拉刷新冲突问题

### ISSUE THREAD

**Issue by aferica** [youzan/vant-weapp#822]
**描述一下问题**
当使用TreeSelect页面的enablePullDownRefresh: true，即可以下拉刷新的时候，TreeSelect多的时候，无法向上滑动，滑动就会触发小程序的下拉刷新

**截图**
无
![image](https://user-images.githubusercontent.com/23699343/47612543-a9f3d600-dab7-11e8-9b37-a638e02f947a.png)

**环境**
 - 设备: 小米
 - 基础库版本:  2.3.0
 - Vant Weapp 版本: 0.4.2

最后我将
tree-select/index.wxml中的
![image](https://user-images.githubusercontent.com/23699343/47612503-ac096500-dab6-11e8-88fc-657accdb90e7.png)
的view换为  scroll-view 解决
 
希望可以提供更好的方法

**Comment by rex-zsd** [comment]
感觉目前也就这个方法比较好了。

**Comment by chenjiahan** [comment]
已在 0.4.6 版本修复
