### ISSUE TITLE
van-panel的header-class不生效

### ISSUE THREAD

**Issue by CurryHan** [youzan/vant-weapp#826]
**描述一下问题**
```
<van-panel header-class='custom-header-class'>
```
微信开发者工具中显示结果
**截图**
![image](https://user-images.githubusercontent.com/14214176/47694038-0c271500-dc37-11e8-9f1b-8b139548fa70.png)

**环境**
 - 设备: 微信开发者工具
 - 基础库版本: 2.2.5
 - Vant Weapp 版本:0.4.0

**Comment by chenjiahan** [comment]
下个版本会修复
