### ISSUE TITLE
search组件清空输入值后 页面其他按钮需点击两下才能触发

### ISSUE THREAD

**Issue by wiexin** [youzan/vant-weapp#827]
拿最常见的带历史记录提示的搜索场景来说：
 search输入值后 点击清空按钮清空值 此时触发blur和focus。继续点击历史记录提示词进行直接搜索  只触发blur 再次点击才触发事件 。

search输入值后  直接点击其他提示词进行搜索  直接触发

**环境**
 - 设备: ios、android、开发工具
 - 基础库版本: 2.2.4
 - Vant Weapp 版本:0.4.3

**Comment by chenjiahan** [comment]
看不懂，请更清晰的描述你的问题
