### ISSUE TITLE
支持支付宝、百度等其它小程序

### ISSUE THREAD

**Issue by xiao0502** [youzan/vant-weapp#829]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**你需要的功能是？**
支持支付宝小程序吗

**你期望 API 是什么样的？**
支持

**Comment by rex-zsd** [comment]
目前还不支持，暂时没有计划支持支付宝小程序...

**Comment by Jialufeng** [comment]
百度小程序支持吗？

**Comment by rex-zsd** [comment]
对其它小程序的支持有考虑，但是暂没有具体的实现思路和计划。
欢迎参与讨论，如何比较好的支持其它小程序。

**Comment by maodei** [comment]
希望能尽快支持百度小程序，感谢项目组！

**Comment by Genuifx** [comment]
支付宝小程序的自定义组件和微信的差别比较大，兼容不好做把，支付宝小程序的hooks感觉跟react对齐。。

**Comment by rex-zsd** [comment]
是的 百度小程序和微信的API基本一致，好做很多。

**Comment by leochan2017** [comment]
同问。想知道什么时候出支付宝版本。

**Comment by bobiscool** [comment]
### 最近  移植了一个  欢迎 **star**  https://github.com/bobiscool/vantui-baiapp
![](https://github.com/bobiscool/vantui-baiapp/raw/master/baiapp.gif)

**Comment by bobiscool** [comment]
> 同问。想知道什么时候出支付宝版本。



> 希望能尽快支持百度小程序，感谢项目组！

### 最近  移植了一个  欢迎 **star**  https://github.com/bobiscool/vantui-baiapp
![](https://github.com/bobiscool/vantui-baiapp/raw/master/baiapp.gif)

**Comment by bobiscool** [comment]
> 对其它小程序的支持有考虑，但是暂没有具体的实现思路和计划。
> 欢迎参与讨论，如何比较好的支持其它小程序。

### 最近  移植了一个  欢迎 **star**  https://github.com/bobiscool/vantui-baiapp
![](https://github.com/bobiscool/vantui-baiapp/raw/master/baiapp.gif)

**Comment by chen-can** [comment]
同问。想知道什么时候出支付宝版本。
