### ISSUE TITLE
checkbox与cell组件一起使用时，点击下图中的checkbox时无效

### ISSUE THREAD

**Issue by Gitsifu** [youzan/vant-weapp#832]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**描述一下问题**
描述一下你遇到的问题，包括复现方式、导致结果

复现方式：vant-weapp已上线的演示demo就有这个问题

**截图**
如果是 UI 问题，请提供具体截图

点击图中checkbox无效

截图
![image](https://user-images.githubusercontent.com/23445650/47717500-e45c9f00-dc80-11e8-8d46-fc1ab5cac941.png)

**环境**
 - 设备: 
 - 基础库版本: 
 - Vant Weapp 版本: 目前微信小程序线上demo版本

**Comment by rex-zsd** [comment]
`checkbox`内部的`tap`事件冒泡到`cell`上导致的，把`checkbox`上的`tap`事件`catch`掉就可以了。

**Comment by rex-zsd** [comment]
更新了一下文档，示例中加入了catch的逻辑。
