### ISSUE TITLE
更新了一下文档，示例中加入了catch的逻辑。

### ISSUE THREAD

**Issue by Gitsifu** [youzan/vant-weapp#834]
_Originally posted by @rex-zsd in https://github.com/youzan/vant-weapp/issues/832#issuecomment-434293185_

改完后checkbox的触控范围太大了，有时点击了也无效

**Comment by Gitsifu** [comment]
如图：下图框出来的区域点击无效
![image](https://user-images.githubusercontent.com/23445650/47721572-5cc85d80-dc8b-11e8-8eca-2a6c9d110384.png)

**Comment by Gitsifu** [comment]
上图框错了，下图才是正确的
![image](https://user-images.githubusercontent.com/23445650/47721752-c2b4e500-dc8b-11e8-80f6-c8929c4c567f.png)

**Comment by rex-zsd** [comment]
的确是有问题，但是如果在`checkbox`组件内部catch掉的话，会影响需要冒泡的用户。
可能得找个妥善的方法处理。
