### ISSUE TITLE
cell 的 arrow-direction 属性

### ISSUE THREAD

**Issue by mynameismaosheng** [youzan/vant-weapp#837]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**cell的arrow-direction属性无效**
在官方的例子中有个 arrow-direction 属性可以控制cell的箭头的方向
实际使用中发现没什么用
官方给的api表格里面也没有这个

**环境**
 - 设备: 微信开发者工具
 - 基础库版本: 2.3.2
 - Vant Weapp 版本: 0.4.4

**Comment by chenjiahan** [comment]
已在 0.4.6 版本支持
