### ISSUE TITLE
van-cell value 如果传入数字0的话,会不显示

### ISSUE THREAD

**Issue by CurryHan** [youzan/vant-weapp#843]
**描述一下问题**
van-cell value 如果传入数字0的话,会不显示
```
    <block wx:if="{{ value }}">{{ value }}</block>
```
因为if(0) 是false ,所以没显示
这个是框架需要考虑的地方 还是用户去处理，传入字符串 ‘0’呢
**环境**
 - 设备: 微信开发者工具
 - 基础库版本: 2.2.5
 - Vant Weapp 版本:0.4.0

**Comment by chenjiahan** [comment]
下个版本支持

**Comment by chenjiahan** [comment]
已在 0.4.6 版本修复
