### ISSUE TITLE
cell组件的功能需求

### ISSUE THREAD

**Issue by huruomin** [youzan/vant-weapp#849]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**你需要的功能是？**
目前的cell组件，在设置了is-link或clickable属性后，用户在触摸移动操作时碰到cell组件，虽然不会触发页面跳转或click事件，**但是会触发hover样式，用户感知不好**，建议优化成只有触摸点击cell时才呈现hover样式。

**Comment by rex-zsd** [comment]
目前的设置是`cell`组件`active`时触发样式，并不会碰到`cell`组件就触发组件。
在iOS上点击`cell`组件后做滑动操作会触发样式，不过这属于系统的正常行为。
