### ISSUE TITLE
cell  cell-group 使用cutstom-class 设置背景颜色无效

### ISSUE THREAD

**Issue by colryzen** [youzan/vant-weapp#851]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**描述一下问题**
cell  使用cutstom-class 设置背景颜色无效

**截图**
``` html 
 <van-cell title="单元格---" value="内容"  custom-class="off" title-class="title-class"  />
``` 

off 
``` html 
.off{
  background: #ff0;
  font-size:80px;
}
``` 

.title-class{
    background-color: #f0f;
}

![image](https://user-images.githubusercontent.com/10821269/47976420-41c37680-e0ed-11e8-8bcd-93d594167b74.png)

**环境**
 - 设备:  全部平台
 - 基础库版本: 2.3.2
 - Vant Weapp 版本: 0.4.5

**Comment by rex-zsd** [comment]
`cell`和`cell-group`设置背景色是2个问题。
`cell-group`无法通过外部样式类设置背景色，因为`cell`组件内设置了白色背景，会覆盖`cell-group`的背景色。
`cell`可以通过外部样式类设置背景色，但是需要加上`!important`，因为外部样式类与内部的样式优先级是不确定的，参考[小程序官方文档](https://developers.weixin.qq.com/miniprogram/dev/framework/custom-component/wxml-wxss.html#%E5%A4%96%E9%83%A8%E6%A0%B7%E5%BC%8F%E7%B1%BB)
