### ISSUE TITLE
验证码输入框组件需求

### ISSUE THREAD

**Issue by dkvirus** [youzan/vant-weapp#852]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**你需要的功能是？**

绑定手机号，需要发送验证码，验证码大多数四位或六位，希望提供验证码组件，每输入一个数字自动跳到下一个单元格。如下图：

![image](https://user-images.githubusercontent.com/29170168/47976675-7ab01b00-e0ee-11e8-8f60-43b5af3c0608.png)

**你期望 API 是什么样的？**

**Comment by chenjiahan** [comment]
暂无计划支持这个组件
