### ISSUE TITLE
van-field的blur事件没有回调值

### ISSUE THREAD

**Issue by lwpassvoice** [youzan/vant-weapp#853]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**你需要的功能是？**
van-field的blur事件等没有回调值

**你期望 API 是什么样的？**
期望回调值能和原生匹配
并且现在field事件回调参数格式为event.detail = 回调值，不和原生匹配，有些东西可能获取不到

![image](https://user-images.githubusercontent.com/22510735/47986525-fc686e80-e117-11e8-9b8f-db74433f5008.png)

**Comment by rex-zsd** [comment]
`blur`和`focus`事件可以支持返回值。
`input`事件返回字符串替换内容的特性，目前通过事件还无法实现。

**Comment by rex-zsd** [comment]
已经有pr #956 被合并了，下版本支持
