### ISSUE TITLE
slider动态传值会失效

### ISSUE THREAD

**Issue by Dongsheng-Zhang** [youzan/vant-weapp#857]
<van-slider value="{{changePercent}}" bar-height="14rpx" bindchanging="onChangePercent" />

动态传入changePercent，在index.js中可以查看到原型数据是被重置了

**Comment by nanfeizds** [comment]
> 动态传入changePercent，在index.js中可以查看到原型数据是被重置了

<van-slider value="{{changePercent}}" bar-height="14rpx" bindchanging="onChangePercent" />

**Comment by nanfeizds** [comment]
<van-slider value="{{changePercent}}" bar-height="14rpx" bindchanging="onChangePercent" />

**Comment by chenjiahan** [comment]
已在 0.4.6 版本修复
