### ISSUE TITLE
van-cell bind:click传参

### ISSUE THREAD

**Issue by 593496637** [youzan/vant-weapp#876]
**你需要的功能是？**
van-cell bind:click事件如何传参，点击当前cell循环列表的时候如何获取当前的item对象

**你期望 API 是什么样的？**
点击van-cell 列表时，我要知道当前点击的是哪行，并且能获取到当前行的item对象

**Comment by rex-zsd** [comment]
问题和`vant-weapp`无关，请参考[微信小程序官方文档](https://developers.weixin.qq.com/miniprogram/dev/framework/view/wxml/event.html)
