### ISSUE TITLE
badge-group 组建 active 只有 0 才生效

### ISSUE THREAD

**Issue by luocong2016** [youzan/vant-weapp#877]
**描述一下问题**
badge-group 组建 active 只有 0 才生效

**截图**
![image](https://user-images.githubusercontent.com/25705196/48186008-b6a6e280-e371-11e8-8e21-e8fc9bdc263c.png)

**环境**
 - Vant Weapp 版本: 0.4.5
- mpvue

**Comment by rex-zsd** [comment]
`mpvue`跟原生小程序初始化顺序不同导致的，原生小程序中是没问题的。
下个版本做个兼容。

**Comment by chenjiahan** [comment]
已在 0.4.6 版本修复
