### ISSUE TITLE
van-field 的 label-class 不起作用

### ISSUE THREAD

**Issue by shallwe99** [youzan/vant-weapp#878]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**描述一下问题**
van-label 的input-class 不起作用

**截图**
![image](https://user-images.githubusercontent.com/4263358/48186198-49478180-e372-11e8-82fa-47e443fdc614.png)
![image](https://user-images.githubusercontent.com/4263358/48186175-39c83880-e372-11e8-807f-1c5102453e53.png)
![image](https://user-images.githubusercontent.com/4263358/48186216-55334380-e372-11e8-946e-e57fc2a06701.png)

**环境**
 - 设备: 小程序开发工具
 - 基础库版本: 2.32
 - Vant Weapp 版本:找不到在哪里 应该是最新版

**Comment by rex-zsd** [comment]
请加`!important`，参考[微信小程序官方文档](https://developers.weixin.qq.com/miniprogram/dev/framework/custom-component/wxml-wxss.html#%E5%A4%96%E9%83%A8%E6%A0%B7%E5%BC%8F%E7%B1%BB)
