### ISSUE TITLE
TreeSelect能否支持禁用选项

### ISSUE THREAD

**Issue by tong233** [youzan/vant-weapp#882]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**你需要的功能是？**
左侧右侧都可以禁用变灰

**你期望 API 是什么样的？**
item: { disable: true }

**Comment by tong233** [comment]
还有自定义选中高亮颜色

**Comment by rex-zsd** [comment]
0.4.7已支持
