### ISSUE TITLE
example运行失败

### ISSUE THREAD

**Issue by chuck-bass** [youzan/vant-weapp#886]

**Comment by chuck-bass** [comment]
下载最新版的 v0.4.6  github 代码

git clone ...

安装依赖：

npm install 

在微信开发者工具里打开

example 下的 示例应用

发现点击没有反应。

![image](https://user-images.githubusercontent.com/28384212/48301644-1a750b00-e52c-11e8-8d5f-7ca24e3cddf4.png)


仔细一看，发现 dashboard目录下 的.json 文件里居然没有 注明组件依赖！

而且pages 里所有的json 文件都没有注明依赖！

![image](https://user-images.githubusercontent.com/28384212/48301664-57410200-e52c-11e8-9a96-9359f2fd0635.png)

**Comment by rex-zsd** [comment]
升级微信开发者工具到最新版。

**Comment by chuck-bass** [comment]
工具已经升级到当前的最新版本，v1.10.1808010 ，刚刚知道知道小程序的 app.json里支持全局组件的定义和使用了。但是，仍旧无法使用 v0.4.6 的代码。发现在 page.json里增加依赖之后， 可以正常使用。
![image](https://user-images.githubusercontent.com/28384212/48308480-ee47a180-e5a0-11e8-8b19-0baed11c21c9.png)

难道是我的开发者工具出问题了？
