### ISSUE TITLE
既然这个主题都是蓝色,请button加个蓝色的吧

### ISSUE THREAD

**Issue by mynameismaosheng** [youzan/vant-weapp#887]
**主题想要统一**
本来项目里用的颜色五花八门的. 既然vant-webapp有意想把主题搞成蓝色, 
那我就想着用蓝色也好. 希望button组件提供蓝色的选项

**Comment by chenjiahan** [comment]
0.5 版本会添加蓝色按钮 (type="primary")，并且将绿色按钮的 type 调整为 success

**Comment by rex-zsd** [comment]
0.5.0中有一些breaking changes，目前还处于beta版，更新日志会在发布正式版后更新。

**Comment by jy1989** [comment]
@rex-zsd 好的 ，感谢回复。

**Comment by mynameismaosheng** [comment]
好像没改哦???

**Comment by maojindao55** [comment]
有蓝色按钮了吗？

**Comment by rex-zsd** [comment]
好像……是没有……

**Comment by maojindao55** [comment]
@rex-zsd 小哥哥能否尽快release 一版本，增加找个feature

**Comment by maojindao55** [comment]
我看  v0.5.2 release了，有这个featrue吗？

**Comment by mynameismaosheng** [comment]
感觉0.5.2也还没有,   我以为是很简单的事情~

**Comment by jy1989** [comment]
@ALANXIAORUI  
`<van-button size="large" custom-class="yourClassName">大号按钮</van-button>
`

**Comment by ALANXIAORUI** [comment]
> custom-class="yourClassName"

不行，没效果，背景颜色还是白的

wxml：
<van-button square size="large"  custom-class="main_button">上传图片</van-button>

wxss：
  .main_button{
    background-color: #E9445A
  }

**Comment by jy1989** [comment]
@ALANXIAORUI 
调试元素看看你的class加在button上面了没？ 或者再加个 ``background-color: #E9445A !important`` 试试？
之前写的代码现在不在手，但我记得是能实现的。

**Comment by ALANXIAORUI** [comment]
> background-color: #E9445A !important

important成功了，感谢！

**Comment by rex-zsd** [comment]
本来0.5.0会调整整体的颜色方案，但是后面并没有实施，所以应该暂时不会调整了。
可以用`custom-class`自定义一下button的背景色。
示例
``` css
.button--black {
    background-color: black !important;
    border-color: black !important;
}
```
