### ISSUE TITLE
按钮没有表单提交类型form-type="submit"

### ISSUE THREAD

**Issue by yundmb** [youzan/vant-weapp#890]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**你需要的功能是？**
form-type="submit" 用来解决表单提交

**你期望 API 是什么样的？**
form-type 属性希望可以加上

**Comment by rex-zsd** [comment]
请看[小程序官方文档](https://developers.weixin.qq.com/miniprogram/dev/component/button.html#bug--tip)

**Comment by mynameismaosheng** [comment]
> 请看[小程序官方文档](https://developers.weixin.qq.com/miniprogram/dev/component/button.html#bug--tip)

其实这些人只是想在form里面用van-button ,有样式统一和其他考虑吧   可否加上 然后文档说明, 如 如果 form-type="submit"没有放在form里不保证有效?

**Comment by Gokeyoung** [comment]
`<view class="simple-field outeLayer submitBtn">
        <van-button
          block
          disabled="{{ usreForm.submitProps }}"
          type="danger"
        >登录
        </van-button>
        <button class="buttonCover" form-type="submit">登录</button>
      </view>`
土方法使用，直接将一个原生的按钮贴合在van-button上面
