### ISSUE TITLE
为什么单位不用rpx

### ISSUE THREAD

**Issue by Superbao77** [youzan/vant-weapp#892]
不用rpx不好兼容啊，有些在开发工具上正常，不同手机效果就不一样了，不考虑改善吗

**Comment by Superbao77** [comment]
小程序正常来说不是都用rpx为单位吗？可以考虑复制两套，一套是rpx的单位，一套是px的单位。我本来打算自己直接替换掉px,但是有些样式会受到影响。

**Comment by rex-zsd** [comment]
事实上以`px`为单位才是主流。
比如(iview)[https://github.com/TalkingData/iview-weapp]、(wux-weapp)[https://github.com/wux-weapp/wux-weapp]、(minui)[https://github.com/meili/minui]等等，连腾讯官方出的(weui-weapp)[https://github.com/Tencent/weui-wxss]用的也是`px`。

**Comment by Superbao77** [comment]
iview我用过了，就用了个列表，在开发工具上是正常的，到了手机上就不正常了，目前市场应该还没有那么好的ui框架吧

**Comment by Dawnxiaozhao** [comment]
能不能搞一个小程序，px==>rpx教程  看不懂啊  我是小白

**Comment by web-oop** [comment]
> 能不能搞一个小程序，px==>rpx教程 看不懂啊 我是小白
这个就是你想要的
https://blog.csdn.net/u014035057/article/details/103203881
