### ISSUE TITLE
依赖loading组件后，小程序IDE卡死

### ISSUE THREAD

**Issue by CodorMonkey** [youzan/vant-weapp#893]
**描述一下问题**
小程序IDE版本 >= 1.02.1810190，在app.json直接依赖loading组件，IDE卡死，提示 “小程序重启耗时过久，请确认业务逻辑中是否有复杂运算，或者死循环的解决“

**环境**
 - 设备: 无
 - 基础库版本: 无
 - Vant Weapp 版本: 0.4.2

**Comment by chengshihard** [comment]
刚才也遇到了这个问题

**Comment by rex-zsd** [comment]
微信开发者工具的问题，全局依赖组件达到一定量，就会卡住。

**Comment by CodorMonkey** [comment]
> 微信开发者工具的问题，全局依赖组件达到一定量，就会卡住。

把loading去掉，就不会，其他组件全局依赖暂时没发现

**Comment by songStar0904** [comment]
0.4.6 npm install npm run dev 后也出现了小程序重启耗时过久。把全局依赖删除loading也不行。能用真机预览。请问该如何解决
