### ISSUE TITLE
ActionSheet 上拉菜单 显示异常

### ISSUE THREAD

**Issue by lijicheng123** [youzan/vant-weapp#895]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**描述一下问题**
ActionSheet 上拉菜单 显示异常

**截图**
![image](https://user-images.githubusercontent.com/15669871/48345897-4fac6500-e6b4-11e8-942d-e6b2904b4f38.png)

**环境**
 - 设备: 

![image](https://user-images.githubusercontent.com/15669871/48346068-e547f480-e6b4-11e8-9371-005bba00a8e9.png)

![image](https://user-images.githubusercontent.com/15669871/48345928-6652bc00-e6b4-11e8-9962-93e498afbb90.png)

 - 基础库版本: 2.3.0
 - Vant Weapp 版本:

"dependencies": {
    "vant-weapp": "^0.3.4"
  }

**Comment by rex-zsd** [comment]
小程序的问题，transition或animation触发多了以后会失效。
官方回复是下个版本修复，可参考[微信开发者社区](https://developers.weixin.qq.com/community/develop/doc/000ea201f24af85226a71f5bd56000?highLine=%25E5%258A%25A8%25E7%2594%25BB%25E5%25A4%25B1%25E6%2595%2588)
