### ISSUE TITLE
tabs 如何固定在顶部

### ISSUE THREAD

**Issue by zbage** [youzan/vant-weapp#897]
position:fixed;
top:0;
z-index:99;
试了custom-class没有起作用啊，

用 custom-clss 修改 card 的height 也不行

**Comment by chenjiahan** [comment]
通过外部样式类添加 position:fixed !important; 也是可以的

**Comment by iActing** [comment]
根据文档api只能实现上滑顶部固定位置不变，但页面下滑时依然会移动位置。
给van-tabs标签添加固定样式后，下边的内容区就无法滚动了，求解

**Comment by OnlyForYouYaner** [comment]
根据文档api只能实现上滑顶部固定位置不变，但页面下滑时依然会移动位置。
给van-tabs标签添加固定样式后，下边的内容区就无法滚动了，求解

**Comment by xueji0803** [comment]
使用「sticky」属性试一下
