### ISSUE TITLE
时间选择能多增加几种组合吗?

### ISSUE THREAD

**Issue by mynameismaosheng** [youzan/vant-weapp#898]
**我需要 year-month-day hh**
有很多业务需求精确到小时就够了, 
这个组件可以用 year-month 选择年月的格式
微信提供的api是有 年月日  时分秒的
目前看到的组件有点"鸡肋"
**你期望 API 是什么样的？**
希望type可以多增加几种款式  比如  hh:mm  一样有人用到

**Comment by wkl007** [comment]
传递的value格式去掉秒就行了，value=‘2018-01-22 12:00’。
