### ISSUE TITLE
时间选择使用wx:if判断是否显示时，时间选择器获取不到时间

### ISSUE THREAD

**Issue by lynchuh** [youzan/vant-weapp#903]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**描述一下问题**
业务需求，当点击修改日期时才下拉出 `DatetimePicker`，所以我使用了`action-sheet`嵌套`DatetimePicker`
```
<van-action-sheet show="{{ leavebegin.show }}" title="开始时间" bind:close="closeBeginsheet">
   <van-datetime-picker 
        type="datetime" 
        value="{{ leavebegin.currentDate }}" 
        min-date="{{ leavebegin.minDate }}" 
        max-date="{{ leavebegin.maxDate }}"
        bind:change="onChange" />
</van-action-sheet>
```
结果`DatetimePicker`出现错误，如下图：
![](http://pdoyygimo.bkt.clouddn.com/%E5%BE%AE%E4%BF%A1%E5%9B%BE%E7%89%87_20181114171010.png)
后来当我抽离`DatetimePicker`出来，结果显示正常，如下图
![](http://pdoyygimo.bkt.clouddn.com/%E5%BE%AE%E4%BF%A1%E6%88%AA%E5%9B%BE_20181114171207.png),
但当我给`DatetimePicker`加入条件来判断是否显示（wx:if = "{{xxx}}"）时，`DatetimePicker`又出现以上错误。

**环境**
 - 设备: 模拟器 & ios
 - 基础库版本: 原生框架
 - Vant Weapp 版本: 0.4.6

**Comment by rex-zsd** [comment]
没复现出来，是不是绑定的value值有问题？
