### ISSUE TITLE
RadioGroup、CheckboxGroup 外部样式类  无法使用

### ISSUE THREAD

**Issue by q310550690** [youzan/vant-weapp#905]
**问题**
RadioGroup、CheckboxGroup 外部样式类  无法使用

看了下0.45 的代码 ，0.46 好像删除了 
`
// 0.45 时
<view class="custom-class">
  <slot />
</view>
`
`
// 0.46 时
<slot />
`
 - Vant Weapp 版本: 0.46

**Comment by chenjiahan** [comment]
这两个组件无须使用外部样式类，直接 class="xx" 修改样式就可以
