### ISSUE TITLE
在mpvue中使用vant-weapp里的van-tabbar组件，change事件无效

### ISSUE THREAD

**Issue by teri5354** [youzan/vant-weapp#907]
我已经成功引用了van-tabbar组件，mpvue的官方文档中提到bindchange="eventName" 事件，需要写成 @change="eventName"。使用如下
使用方案一
<van-tabbar :active="active" @change="onChange">
标签
标签
标签
标签
使用方案二

标签 标签 标签 标签
调用的方法：
onChange (event) {
console.log('test')
}

运行情况：
方案一：并没有调到onChange方法，控制台并没有打印出test
方案二：Component "pages/index/main" does not have a method "onChange" to handle event "change"

请问应该如何解决？？

**Comment by mynameismaosheng** [comment]
> 我已经成功引用了van-tabbar组件，mpvue的官方文档中提到bindchange="eventName" 事件，需要写成 @change="eventName"。使用如下
> 使用方案一
> <van-tabbar :active="active" @change="onChange">
> 标签
> 标签
> 标签
> 标签
> 使用方案二
> 
> 标签 标签 标签 标签
> 调用的方法：
> onChange (event) {
> console.log('test')
> }
> 
> 运行情况：
> 方案一：并没有调到onChange方法，控制台并没有打印出test
> 方案二：Component "pages/index/main" does not have a method "onChange" to handle event "change"
> 
> 请问应该如何解决？？

重新编译, npm start

**Comment by teri5354** [comment]
重新编译没有用，找到原因了，是因为使用了Tabbar作控件名，才导致的整个项目所有事件不生效
