### ISSUE TITLE
van-tabbar 如何改变active color

### ISSUE THREAD

**Issue by teri5354** [youzan/vant-weapp#908]
van-tabbar这个组件默认的active color是蓝色的，想换成自己想要的颜色，文档里没有类似active color的属性，使用.van-tabbar-item--active {
    color: red !important;
  }
也是无效的，请求帮助，谢谢！

**Comment by rex-zsd** [comment]
tabbar可以传入2个slot，分别对应未选中和选中状态下的渲染，所以想传任何颜色的图标都是可以自己控制的。详情参考[文档](https://youzan.github.io/vant-weapp/#/tabbar)。

**Comment by teri5354** [comment]
图标通过slot可以控制我知道，但是我想要改变的是底下文本的颜色，这个文本并不是做成图标一块的
