### ISSUE TITLE
表单控件

### ISSUE THREAD

**Issue by typist** [youzan/vant-weapp#909]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**你需要的功能是？**
vant-form控件，希望能够一次性拿到表单数据

**你期望 API 是什么样的？**
-vant-form bind:change=""
   -vant-filed
-vant-form
表单内所有field等组件变化，都能够传递到form上面，我只需要监听form的change事件，这样就不需要监听所有的子控件。
vant-button 扩展 form-type="submit"属性，触发vant-form提交事件。完全可以替代掉原生的呀。
vant-field 扩展 label、name 等属性
vant-form 可以添加验证器validator属性，把wxValidator这个类装进去。

**Comment by rex-zsd** [comment]
1. 表单直接使用小程序原生的form组件就可以了，注意在使用的组件上增加`name`属性，参考[微信小程序官方文档](https://developers.weixin.qq.com/miniprogram/dev/component/form.html)
2. `van-button`为什么没有`form-type`属性请参考[微信小程序官方文档](https://developers.weixin.qq.com/miniprogram/dev/component/button.html#bug--tip)
3. 仔细看[文档](https://youzan.github.io/vant-weapp/#/field)，这两个属性`vant-field`都有
