### ISSUE TITLE
能开发类似美团饿了么的下拉筛选菜单组件吗？

### ISSUE THREAD

**Issue by sycs** [youzan/vant-weapp#911]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**你需要的功能是？**
类似美团饿了么的下拉筛选菜单组件 这个需求很多的配合treeselect用

**你期望 API 是什么样的？**
简洁就好

**Comment by hackgyj** [comment]
同样需要

**Comment by chenjiahan** [comment]
暂无计划支持喔

**Comment by pengsamkee** [comment]
同样需求啊
