### ISSUE TITLE
notice-bar不动

### ISSUE THREAD

**Issue by Daley** [youzan/vant-weapp#913]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**描述一下问题**
notice-bar不动，看了下代码，这不应该是<啊
`if (scrollable && wrapWidth < width) `

**Comment by chenjiahan** [comment]
文字超过一屏宽度的时候才会滚动

**Comment by canovie** [comment]
开发者工具能动，手机上能不能动要看运气为啥？

**Comment by chengaobin** [comment]
2个tab页切换，第一个能滚动，第二个不能滚动，是什么原因
