### ISSUE TITLE
popup内使用field，类型textarea缺乏fixed 的BUG

### ISSUE THREAD

**Issue by hackgyj** [youzan/vant-weapp#915]
**问题如下**
popup内使用field，类型textarea，出现placeholder和value文字错位，还有popup关闭后，textarea类型的placeholder文字依然会停留在屏幕上的BUG。测试了ios和android，android正常，IOS则无限BUG。翻看官方论坛和种类文章发现vant的field（textarea）缺少一个关键参数：“fixed”，其中：
[https://developers.weixin.qq.com/miniprogram/dev/component/textarea.html](https://developers.weixin.qq.com/miniprogram/dev/component/textarea.html)
[https://developers.weixin.qq.com/community/develop/doc/0008c4699a03f845d72726af75bc00](https://developers.weixin.qq.com/community/develop/doc/0008c4699a03f845d72726af75bc00)
处有相关说明，“如果 textarea 是在一个 position:fixed 的区域，需要显示指定属性 fixed 为 true，嗯，是 fixed 属性，不是 css 的 position: fixed”，同时翻看了field的textarea，确实没有该属性，我加上以后，BUG有所改善，但依然会在边缘处有一条细线。

希望：
- 官方能修复此问题，textarea增加fixed属性设置；
-  同时能复现解决popup内使用field，类型textarea的BUG，在开发工具中一切正常，但在手机上就秒现BUG了。

**截图**
![image](https://user-images.githubusercontent.com/321913/48626944-35dd8b80-e9ee-11e8-85e1-b0b3e47f6f60.png)
图中：资源对接…… 一行是value文字，显示在了popup外

**环境**
 - 设备: ios iphone8
 - 基础库版本: 2.2.2
 - Vant Weapp 版本: v0.4.6

**Comment by rex-zsd** [comment]
感谢反馈，将在下个版本修复。
