### ISSUE TITLE
DatetimePicker 年月格式按照给定时间初始化

### ISSUE THREAD

**Issue by 5night** [youzan/vant-weapp#916]
**你需要的功能是？**
希望在年月日和年月格式的`DatetimePicker `中，可以按照`currentDate`（或者新增`initDate`）的设置初始化时间（在时分格式中已经可以支持）。
应用场景：选择出生年月时，有效的输入范围为1940年1月至今，而默认的初始化时间为1990年1月，现在只支持从1940年1月开始选取。
P.S. DatatimePicker 页面似乎没有写更新日志。
**你期望 API 是什么样的？**
`currentDate` 或者 `initDate`

**Comment by rex-zsd** [comment]
不太明白你的需求，是希望达成什么效果呢？

**Comment by mynameismaosheng** [comment]
> **你需要的功能是？**
> 希望在年月日和年月格式的`DatetimePicker `中，可以按照`currentDate`（或者新增`initDate`）的设置初始化时间（在时分格式中已经可以支持）。
> 应用场景：选择出生年月时，有效的输入范围为1940年1月至今，而默认的初始化时间为1990年1月，现在只支持从1940年1月开始选取。
> P.S. DatatimePicker 页面似乎没有写更新日志。
> **你期望 API 是什么样的？**
> `currentDate` 或者 `initDate`

有min和max  也有value . 你说的需求应该可以根据min+value实现的
