### ISSUE TITLE
DatetimePicker 时间选择onchange返回值不对

### ISSUE THREAD

**Issue by changeLong** [youzan/vant-weapp#924]
![image](https://user-images.githubusercontent.com/13422021/48672741-bcbc7080-eb74-11e8-8090-fe0a9489f1b5.png)
![image](https://user-images.githubusercontent.com/13422021/48672750-e07fb680-eb74-11e8-8195-c71d4caf87ec.png)
### onchage中，event.detail.value 根本就没有；

`<van-datetime-picker
        type="date"
        value="{{ currentDate }}"
        min-date="{{ minDate }}"
        bind:change="dpChange"
      />`

` data: {
    
    minDate: new Date(),  //时间选择最小时间
    currentDate: new Date(),  //时间选择当前时间
  }`

`dpChange(event){
    console.log(event.detail)
    this.setData({
      currentDate: event.detail.value
    });
  },`

**Comment by rex-zsd** [comment]
额 看下[文档](https://youzan.github.io/vant-weapp/#/datetime-picker) `change`事件返回的是组件实例，`input`事件返回的才是值。
