### ISSUE TITLE
组件间的分割线是什么，能去掉吗？？

### ISSUE THREAD

**Issue by Mr-SPM** [youzan/vant-weapp#929]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**你需要的功能是？**
我想去掉组件间的那些分割线却没有看到样式有些这些样式，我要如何去掉呢？

**你期望 API 是什么样的？**
希望有这样的配置项。

**Comment by chenjiahan** [comment]
具体指哪个组件？

**Comment by Mr-SPM** [comment]
> 具体指哪个组件？

![image](https://user-images.githubusercontent.com/25722226/48813847-80a32e80-ed73-11e8-9be9-859927c03d07.png)

**Comment by rex-zsd** [comment]
@Mr-SPM 
请贴出组件名和使用的代码
开局一张图我们没法帮你解决问题
