### ISSUE TITLE
van-dialog建议增加确定按钮颜色、取消按钮颜色与自定义按钮列表三个参数

### ISSUE THREAD

**Issue by wkl007** [youzan/vant-weapp#933]
**你需要的功能是？**
1.van-dialog需要更改确定按钮颜色，取消按钮颜色
2.同时需要像zan-dialog一样可以自定义按钮列表

**你期望 API 是什么样的？**
options中新增三个参数

- confirmButtonColor
- cancelButtonColor
- buttons

buttons中数据格式
```
[{
  text: '现金支付',
  color: 'red',
  type: 'cash'
}, {
  text: '微信支付',
  color: '#3CC51F',
  type: 'wechat'
}, {
  text: '取消',
  type: 'cancel'
}, {
  text: '获取用户信息',
  type: 'userInfo',
  openType: 'getUserInfo'
}]
```

**Comment by caszhou** [comment]
可以直接改dialog的样式 /(ㄒoㄒ)/~~

**Comment by rex-zsd** [comment]
如果支持自定义buttons的话需要支持很多button上`openType`相关的属性，要考虑下。

**Comment by lx815** [comment]
> 可以直接改dialog的样式 /(ㄒoㄒ)/~~

直接强行修改样式还是不太好，最好是在组件内部能够加一个改变颜色的参数

**Comment by zenonux** [comment]
同需要

**Comment by DestinyHunter** [comment]
同需要

**Comment by lingsang2** [comment]
附议

**Comment by rex-zsd** [comment]
@zenonux @DestinyHunter @lingsang2 可以大致描述一下使用的场景嘛？
设计API需要参考一下，需求强烈的话后面会支持一下自定义buttons。

**Comment by zenonux** [comment]
> @zenonux @DestinyHunter @lingsang2 可以大致描述一下使用的场景嘛？
> 设计API需要参考一下，需求强烈的话后面会支持一下自定义buttons。

我们目前的需求还没有到自定义butons，能做是最好的。主题色不是蓝色，所以需要改，现在只能在你们源码里面改颜色，外部无法覆盖颜色类。版本更新时会比较麻烦

**Comment by rex-zsd** [comment]
> > @zenonux @DestinyHunter @lingsang2 可以大致描述一下使用的场景嘛？
> > 设计API需要参考一下，需求强烈的话后面会支持一下自定义buttons。
> 
> 我们目前的需求还没有到自定义butons，能做是最好的。主题色不是蓝色，所以需要改，现在只能在你们源码里面改颜色，外部无法覆盖颜色类。版本更新时会比较麻烦

ok 明白了 你的需求只是修改按钮样式咯

**Comment by DestinyHunter** [comment]
附议,

**Comment by ZjVirus** [comment]
附议

**Comment by chenjiahan** [comment]
1.0 版本会支持自定义按钮颜色

**Comment by chenjiahan** [comment]
已在 1.0.0-beta.0 版本支持自定义按钮颜色

**Comment by Candane** [comment]
> 已在 1.0.0-beta.0 版本支持自定义按钮颜色

还是不能修改Dialog组件中确认按钮的颜色呀

**Comment by anming-john** [comment]
能不能增加组件按钮样式自定义的功能啊！ 或者自定义footer 我这边UI提供的按钮就不一样， 不光光改颜色能满足的啊

**Comment by liuzhenji** [comment]
关键是我这里想了各种选择方法，就是没法把确认跟取消按钮给区分开。不知道是不是微信小程序的问题。。醉了

**Comment by liuzhenji** [comment]
> 关键是我这里想了各种选择方法，就是没法把确认跟取消按钮给区分开。不知道是不是微信小程序的问题。。醉了

看了下源码：1.6.9 已经增加了confirmButtonColor 属性，用来控制按钮颜色
