### ISSUE TITLE
时间选择器切换时反应慢,而且设置最小日期也有问题

### ISSUE THREAD

**Issue by luotingv1** [youzan/vant-weapp#934]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**描述一下问题**

时间选择器切换时反应慢,而且设置最小日期也有问题
随便设置一个new Date().getTime()作为最小日期 假设是2018年11月22号
点开选择器  月份是没用在选中状态的是浅黑色状态 (选中是深黑状态) 点击确定 返回是2018年1月1号
**截图**

还有就是在切换月份之后动画反应慢
![image](https://user-images.githubusercontent.com/24503005/48883919-14045e80-ee5d-11e8-949e-a6d08782bbab.png)
若浅黑色没有变成深黑色状态 点击确认无效 值未改变

![image](https://user-images.githubusercontent.com/24503005/48883886-e6b7b080-ee5c-11e8-9952-a18e5d315ff2.png)
 "vant-weapp": "^0.4.6",

**Comment by rex-zsd** [comment]
最小值设置的问题的确是bug
切换反应慢的问题应该是小程序的问题，因为组件内部用的是小程序原生的picker-view

**Comment by zhuhe123456** [comment]
new Date(1940,0,1).getTime() 
用这个直接赋值给最小值
