### ISSUE TITLE
 搜索框能加入圆角的设置吗？

### ISSUE THREAD

**Issue by web-kubor** [youzan/vant-weapp#935]
增加搜索框的直角或者圆角的属性，方便调节，现在调节太麻烦了

**Comment by rex-zsd** [comment]
搜索输入框本来有4px的圆角的，目前没显示出来，应该是个bug，下个版本修复。

**Comment by rex-zsd** [comment]
需要自己调节的话，得看看怎么提供一个外部样式类出来。
