### ISSUE TITLE
带单元格的checkbox有部分区域点击无效

### ISSUE THREAD

**Issue by 925934787** [youzan/vant-weapp#937]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**描述一下问题**
带单元格的checkbox有部分区域点击无效，截图中红色区域无法触发，蓝色区域可以

**截图**
![tim 20181123154356](https://user-images.githubusercontent.com/19659397/48932490-34a0e700-ef37-11e8-81b0-6a8f72d94ebc.png)

**环境**
线上的小程序示例就直接存在这样的问题

**Comment by rex-zsd** [comment]
需要给`van-cell`设置`value-class`。
```html
<van-cell
  ...
  value-class="value-class"
>
  <van-checkbox ... />
</van-cell>
```
```css
.value-class {
  flex: none !important;
}
```
