### ISSUE TITLE
van-dialog 若使用use-slot 后message属性无效

### ISSUE THREAD

**Issue by SnowCoCo** [youzan/vant-weapp#952]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**你需要的功能是？**
使用van-dialog做弹框，显示主题和内容，并且有input；
但van-dialog 若使用use-slot 后message属性无效

**你期望 API 是什么样的？**
不知道

**Comment by rex-zsd** [comment]
设置`use-slot`以后中间的内容就是完全自定义的，设置的`message`不会再生效了。

**Comment by rex-zsd** [comment]
设置`use-slot`以后中间的内容就是完全自定义的，设置的`message`不会再生效了。
