### ISSUE TITLE
使用SwipeCell组件时， 不报错，也不生效

### ISSUE THREAD

**Issue by cowblue** [youzan/vant-weapp#953]
SwipeCell ，没有效果。而且文档demo提供的异步关闭。明显是vue的方法。~~~~

**Comment by rex-zsd** [comment]
文档是有点问题，下版本修改。
使用没效果是不是使用姿势的问题？贴下使用代码看下

**Comment by mandy1219** [comment]
@rex-zsd  #
<img width="971" alt="cell" src="https://user-images.githubusercontent.com/23544832/53545527-bae74d80-3b64-11e9-9fcf-558c2c33f05f.png">
把文档好好改下吧。 照着文档做没效果，还需要自己找原因 很浪费时间的。
这里少引入了单元格组件，所以没效果

**Comment by mandy1219** [comment]
<img width="524" alt="cell1" src="https://user-images.githubusercontent.com/23544832/53545619-0a2d7e00-3b65-11e9-8021-a71a9553cd55.png">
