### ISSUE TITLE
van-dialog开启use-slot的时候如果自定义内容是一个有placeholder的input，placeholder会跳动

### ISSUE THREAD

**Issue by afishhhhh** [youzan/vant-weapp#954]
**问题**
van-dialog开启use-slot的时候如果自定义内容是一个有placeholder的input，placeholder会跳动，具体表现是刚打开dialog的时候只会显示垂直方向上一半的文字，跳动之后显示完全
```html
<dialog title="一个标题" show="{{ show }}" use-slot show-cancel-button>
  <input style="margin:15px;padding:15px" placeholder="一个placeholder" type="number"></input>
</dialog>
```

**环境**
 - 设备: 开发工具
 - 基础库版本: 2.2.5
 - Vant Weapp 版本: 0.4.5
iPhone 上也存在，微信版本 6.7.3

**Comment by SnowCoCo** [comment]
我也遇到了同样的问题

**Comment by hackgyj** [comment]
同样存在这问题

**Comment by rex-zsd** [comment]
微信小程序的问题，出现时有动画的话会显示异常。
试了一下[去掉`popup`的`transition`](https://github.com/youzan/vant-weapp/blob/dev/packages/dialog/index.wxml#L3)就会正常，但是没有动画的话不太科学。
具体参考[微信小程序官方文档]
(https://developers.weixin.qq.com/miniprogram/dev/component/input.html#bug--tip)

**Comment by chenjiahan** [comment]
可以考虑添加一个属性来控制是否开启过场动画

**Comment by rex-zsd** [comment]
感觉可以，增加一个属性控制`transition`入场动画。
