### ISSUE TITLE
tab 好像有一个BUG

### ISSUE THREAD

**Issue by chaituan** [youzan/vant-weapp#965]
在使用tab的时候，我动态生成数据 ，默认第一个选中，但是下划线不出现。
使用方式：
直接在data里面定义值，可以正常显示。如果在request 网络请求后，set 值 就会出现这种情况。难道网络请求会造成渲染的问题吗？ 

还有一个问题，现在切换tab 只能获取索引值，这样不是很灵活。  我现在动态生成tab 切换的时候通过ID获取数据库内容。只给一个索引 ，请问一下  我要怎么判断 ，我触发的id 是几？  有点不太明白。

**截图**

![_20181127103752](https://user-images.githubusercontent.com/26025563/49054826-8778e800-f230-11e8-9680-5fd7575c9073.png)

**环境**
 - 设备: 
 - 基础库版本: 
 - Vant Weapp 版本:

**Comment by mynameismaosheng** [comment]
获取id的方法
list:[{id:10,lable:"tab 1"},{id:11,lable:"tab 2"}]
list[索引].id

**Comment by rex-zsd** [comment]
尝试了一下异步设置`van-tab`，没出现这个情况，可以贴下代码不？
