### ISSUE TITLE
小程序自定义组件solt的问题请教一下

### ISSUE THREAD

**Issue by 982991084** [youzan/vant-weapp#971]
![image](https://user-images.githubusercontent.com/22464456/49073050-8b2a6000-f26c-11e8-9179-8ea3a1946be1.png)

**我看了一下，有赞ui的自定义组件solt的位置是正常的，组件的内容是在solt的**

![image](https://user-images.githubusercontent.com/22464456/49073198-d80e3680-f26c-11e8-8baa-c0b5ad23b005.png)
![image](https://user-images.githubusercontent.com/22464456/49073217-e3f9f880-f26c-11e8-8067-9c7977770e36.png)

**而我自己写的却变成同级了**

**Comment by rex-zsd** [comment]
这个是开发者工具的问题，可以看[小程序开发者社区](https://developers.weixin.qq.com/community/develop/doc/00060ea248075819e516efb385b800?highLine=slot%2520%25E5%25A4%2596%25E9%259D%25A2)。
