### ISSUE TITLE
新增ScrollNav 组件

### ISSUE THREAD

**Issue by Gitsifu** [youzan/vant-weapp#972]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**你需要的功能是？**
描述一下你需要的功能，用于解决什么问题

和cube-ui组件一样的[https://didi.github.io/cube-ui/#/zh-CN/docs/scroll-nav](https://didi.github.io/cube-ui/#/zh-CN/docs/scroll-nav)
![image](https://user-images.githubusercontent.com/23445650/49075743-60dba100-f272-11e8-8756-513546eabe90.png)

**你期望 API 是什么样的？**
描述一下你期望的 API 形式

**Comment by chenjiahan** [comment]
暂无计划支持
