### ISSUE TITLE
vant版本的picker组件

### ISSUE THREAD

**Issue by a51764579** [youzan/vant-weapp#975]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**你需要的功能是？**
需要提供类似原生picker功能的vant版本，
原因：原生picker在与vant版本的其他标签结合使用时，
          需要重新解决样式问题，或者已经有解决方案。

**你期望 API 是什么样的？**
与原生picker类似的vant版本

**Comment by rex-zsd** [comment]
小程序有提供原生的`picker`，为什么希望vant再提供一个呢？
