### ISSUE TITLE
van-stepper组件无法动态传值

### ISSUE THREAD

**Issue by Dongsheng-Zhang** [youzan/vant-weapp#978]
`<van-stepper minus-class plus-class input-class value="{{number}}" integer max="999" bind:change="changeNumber" />`
需求：number是同页面上另一个van-stepper动态改变的，但是到弹窗的van-stepper number已经被改变了，但源码中未获取到该值 导致减号按钮置灰 需点击加号按钮才可以正常显示和计算

**Comment by Dongsheng-Zhang** [comment]
希望不通过加减号按钮操作 也可以监听到value值的改变

**Comment by Dongsheng-Zhang** [comment]
`watch: {
    value: function value(_value) {
      this.triggerInput(_value)
    }
  },`
是否能提供此类的方法

**Comment by Dongsheng-Zhang** [comment]
`watch: {
    value: function value(_value) {
      this.setData({
        value: this.range(_value)
      });
    }
  },`

已自行增加该方法 解决

**Comment by 8656361** [comment]
列表中如何解决啊，购物车用了该组件，列表数据刷新，显示的不会刷新，只有通过加减的才会
