### ISSUE TITLE
weapp新功能sku商品规格

### ISSUE THREAD

**Issue by exelin** [youzan/vant-weapp#982]
sku商品规格，啥时候可以上线weapp版？
另电商的一些基础模块可以研究看看，也可以大家集思广益一起来维护。

希望可以先上线一个基础版，对标vant，后续再升级

**Comment by CQByte** [comment]
我们来自己写吧

**Comment by rex-zsd** [comment]
这是要提pr了吗 🎉

**Comment by exelin** [comment]
> 这是要提pr了吗

哈哈哈哈哈哈

**Comment by rex-zsd** [comment]
sku属于比较复杂的业务组件了，本月暂时没时间做。

**Comment by ialmost** [comment]
> sku属于比较复杂的业务组件了，本月暂时没时间做。

加油啊

**Comment by rex-zsd** [comment]
新组件的计划请关注后续的roadmap，issue先关闭了。
