### ISSUE TITLE
官方是否可出一篇自定义组件拓展的文档

### ISSUE THREAD

**Issue by leubao** [youzan/vant-weapp#983]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**你需要的功能是？**
描述一下你需要的功能，用于解决什么问题
自定义组件，现有官方提供的组件不能满足所有需要，需要自己定义一些组件
**你期望 API 是什么样的？**
描述一下你期望的 API 形式

**Comment by rex-zsd** [comment]
如果需要增加一些通用的功能，可以提issue给我们或者完成以后提pr。
如果有特殊需求，fork一份自己定制吧。
