### ISSUE TITLE
希望可以添加一个九宫格图片选择组件

### ISSUE THREAD

**Issue by FredZeng** [youzan/vant-weapp#986]
**你需要的功能是？**
1.从本地相册选择图片或使用相机拍照并返回图片
2.以九宫格布局显示图片
3.单击图片可删除选定图片

**你期望 API 是什么样的？**
通过调用该组件API可返回用户选择的图片数组。

个人认为使用到9宫格选择图片的业务场景还是挺常见的，希望能封装成一个业务组件，thx。

**Comment by rex-zsd** [comment]
微信本身的API`chooseImage`已经可以满足需求了吧。
