### ISSUE TITLE
miniprogram_npm/vant-weapp/mixins/transition

### ISSUE THREAD

**Issue by BIGTURKEY** [youzan/vant-weapp#987]
刚引入vant编译就报错
![image](https://user-images.githubusercontent.com/19204717/49263449-8d1b3b80-f485-11e8-92a0-b695f8642e6b.png)

**Comment by rex-zsd** [comment]
应该是微信开发者工具的问题，看下微信开发者工具的[更新日志](https://developers.weixin.qq.com/miniprogram/dev/devtools/download.html)。

**Comment by BIGTURKEY** [comment]
那是否有解决方案呢，要用低版本的开发者工具还是？
