### ISSUE TITLE
Dialog 点击 confirm 之后到 Dialog 关闭之前似乎没办法做一些同步操作

### ISSUE THREAD

**Issue by afishhhhh** [youzan/vant-weapp#988]
现在业务上有一个需求是这样的：
点击按钮出现一个 dialog，dialog 中输入一个数字，我需要在点击确定的时候同步验证这个数字的合法性，如果不合法弹出一个 toast 提示，或者说如果这个数字不合法，confirm 按钮就处于 disable 状态

**Comment by rex-zsd** [comment]
看下[文档](https://youzan.github.io/vant-weapp/#/dialog)，Dialog可以通过设置`asyncClose`异步关闭。

**Comment by rayroad** [comment]
> 看下[文档](https://youzan.github.io/vant-weapp/#/dialog)，Dialog可以通过设置`asyncClose`异步关闭。

我也遇到了同样的业务问题，不过启用asyncClose后当点击confirm进行拦截后 confirm就是一直处于加载状态

**Comment by afishhhhh** [comment]
> 看下[文档](https://youzan.github.io/vant-weapp/#/dialog)，Dialog可以通过设置`asyncClose`异步关闭。

@rex-zsd 我试了一下，还是不行，无论是通过组件调用还是函数调用，如果发现异步返回的结果不正确，不想关闭窗口，confirm 按钮就一直处于 loading 状态，我尝试在 then 里面调用 Dialog.stopLoading，不知道为啥只能在第一次点击确定的时候成功关闭 loading  状态

**Comment by rex-zsd** [comment]
因为返回的是`Promise`，`then`里面的逻辑只会执行一次，所以需要多次触发的场景下就不要把逻辑写在`then`里面了。
可以改成在`van-dialog`上监听`confirm`事件来处理。

**Comment by Leo-July** [comment]
van-dialog上监听confirm事件来处理。
也没办法，阻止组件默认关闭dialog 事件。

**Comment by dpgirl** [comment]
我也遇到这个问题，请问解决了吗？

**Comment by dpgirl** [comment]
> 因为返回的是`Promise`，`then`里面的逻辑只会执行一次，所以多次需要触发的场景下就不要把逻辑写在`then`里面了。
> 可以改成在`van-dialog`上监听`confirm`事件来处理。

你好，请问这个得怎么解决？阻止组件默认关闭对话事件

**Comment by dpgirl** [comment]
> van-dialog上监听确认事件来处理。
> 也没办法，阻止组件默认关闭对话事件。

请问你解决这个问题了吗？怎么做？

**Comment by 1422667480** [comment]
> > van-dialog上监听确认事件来处理。
> > 也没办法，阻止组件默认关闭对话事件。
> 
> 请问你解决这个问题了吗？怎么做？

看下源码就行了  他在回调的时候传了一个{dialog：this}实例   在我们的事件里监听后 直接调用event.detail.dialog.stopLoading(); 就可以关闭loading 也可继续后续操作了

**Comment by xiejunping** [comment]
我来说说我的看法吧，我已解决

第一，我用的  van-dialog 标签上监听确认事件来处理，错误现象， 有异步的loading，但是 confirm 响应后会自动关闭，  我在组件上监听的事件有两个， confirm  close

第二，根据上面 说的 “他在回调的时候传了一个{dialog：this}实例 在我们的事件里监听后 直接调用event.detail.dialog.stopLoading(); 就可以关闭loading 也可继续后续操作了”  看了代码，

重点： 
`onClose(action: Action) {
      if (!this.data.asyncClose) {
        this.close();
      } else {
        this.$emit('close', action);
      }
      // this.$emit('close', action);  这个改到else 分支
      // 抛出事件  
      // 异步是  confirm  cancel
      // 非异步  confirm  close

      // 把 dialog 实例传递出去，可以通过 stopLoading() 在外部关闭按钮的 loading
      this.$emit(action, { dialog: this });

      const callback = this.data[action === 'confirm' ? 'onConfirm' : 'onCancel'];
      if (callback) {
        callback(this);
      }
    }`

按以上改了后，就可以像文档中说的，自己控制弹窗关闭了， loading 在设置 show 隐藏后就关闭了，不用手动改

**Comment by Minorjone** [comment]
不用像上面说的那么复杂，在拦截了confirm事件后，如果结果返回不正确可以调用done(false)
```
if (action === 'confirm') {
  // 做校验
  if (...) {
    // 校验失败
    Toast()
    done(false)
  }
}
```

**Comment by 18229059470** [comment]
> 看下[文档](https://youzan.github.io/vant-weapp/#/dialog)，Dialog可以通过设置`asyncClose`异步关闭。

小程序有异步关闭，可是H5移动端没有异步关闭

**Comment by panhongfeng** [comment]
event.detail.dialog.close() 解决问题

**Comment by JadeLiuYC** [comment]
在onConfirm方法中调用event.detail.dialog.close()确实可以关闭loading， 但在onConfirm中执行异步方法返回错误信息时调用就不能关闭了
![image](https://user-images.githubusercontent.com/26455396/93748191-6e71d000-fc2a-11ea-868a-5e3a30cb1730.png)

**Comment by dpgirl** [comment]
可以啦，谢谢大家的帮忙解答~
