### ISSUE TITLE
0.4.7版本中，文件丢失的问题

### ISSUE THREAD

**Issue by HeaventTso** [youzan/vant-weapp#992]
**描述一下问题**
0.4.7版本中，暂时发现以下问题：

thirdScriptError 
 sdk uncaught third Error 
 module "miniprogram_npm/vant-weapp/mixins/transition" is not defined 
 Error: module "miniprogram_npm/vant-weapp/mixins/transition" is not defined

**环境**
 - 设备: 
 - 基础库版本: 
 - Vant Weapp 版本: 0.4.7

**Comment by rex-zsd** [comment]
应该是微信开发者工具的问题，可以升级下开发者工具看看。

**Comment by sky185959** [comment]
0.4.9版本中，也出现同样的问题，开发工具目前是最新的版本2018.11.29

**Comment by LHC8888** [comment]
也发现了这个问题
vant-weapp：0.5.6（npm下载）
微信开发者工具：1.02.1902010（目前最新版）
