### ISSUE TITLE
Stepper 步进器样式问题

### ISSUE THREAD

**Issue by StruggleThunder** [youzan/vant-weapp#996]
**在ipad的屏幕分辨率下，Stepper 步进器的样式会有问题。**  
![qq 20181203095849](https://user-images.githubusercontent.com/29719722/49349251-c56c8500-f6e4-11e8-8bbf-d8d9f53b869b.png)

**Comment by rex-zsd** [comment]
真机上有问题吗？
开发者工具上貌似是微信的问题，给input设置高度时内容不会自动居中，要输入一下才会恢复。

**Comment by StruggleThunder** [comment]
> 真机上有问题吗？
> 开发者工具上貌似是微信的问题，给input设置高度时内容不会自动居中，要输入一下才会恢复。

在手机屏幕(宽度)大小下没有问题，但是在iPad屏幕(宽度)大小下，就会出现上面的样式问题。  
小程序的input标签有个最小高度的默认样式`min-height: 1.4rem; `，设置input的高度的时候，`min-height`一起设置了，字体大小也要设置，因为默认的字体大小还是有点大的。

**Comment by rex-zsd** [comment]
0.4.10已修复
