### ISSUE TITLE
van-datetime-picker组件设置minDate与maxDate时间很接近的时候会有问题

### ISSUE THREAD

**Issue by AugustEnd** [youzan/vant-weapp#998]
**在开发工具里直接卡死，手机里会数据来回闪烁**
```
<van-datetime-picker
  type="datetime"
  value="1543828469723"
  min-date="1543828469726"
  max-date="1551597269726"
  bind:change="onChange"
/>
```
时间范围 2018-12-03 17:14 至 2019-03-03 15:14

正常情况下2018年只有12月份，2019年只有[1,2,3]月份

当2018切换到2019年开发工具就直接卡死

**截图**
![1](https://user-images.githubusercontent.com/20834070/49359331-e1861b80-f710-11e8-9b07-24c6680dc0e2.png)
![2](https://user-images.githubusercontent.com/20834070/49359332-e21eb200-f710-11e8-8c2e-8779dbbf0fed.png)

**环境**
 - 设备: 微信开发者工具
 - 基础库版本: 
 - Vant Weapp 版本:最新

**Comment by rex-zsd** [comment]
按这个代码尝试了一下，开发者工具里显示正常，真机上会在`2018``2019`之间闪烁一次，之后恢复正常。

**Comment by AugustEnd** [comment]
@rex-zsd 是的，但是会停在2019年3月份，我这边的出现的问题很可能跟我使用mpvue有关系。
不知道怎么解决这个问题，如果不换这个组件有什么好办法嘛
```
<van-popup :show="popup.state" position="bottom">
    <van-datetime-picker 
    type="datetime" 
    :value="popup.value" 
    @confirm="setDateTime" 
    @cancel="popup.state=false" 
    :min-date="popup.minDate" 
    :max-date="popup.maxDate" 
    @change="getDateTime" />
```

**Comment by rex-zsd** [comment]
我一会在mpvue上试一下。

**Comment by AugustEnd** [comment]
@rex-zsd 这个问题好解决嘛

**Comment by rex-zsd** [comment]
看了一下，在原生小程序中从2018切换到2019触发了多次onChange，导致显示有跳跃，要彻底解决的话需要重构部分逻辑，一次性计算出目标时间。
这个组件逻辑比较复杂，可能会花较长的时间来处理。

**Comment by AugustEnd** [comment]
@rex-zsd  好的好的，我先换个方式处理这个问题。

**Comment by rex-zsd** [comment]
0.5.0 datetime-picker已经使用picker重构了，现在不会有这个问题了。
